### ISSUE TITLE
Basic authorization for app

### ISSUE THREAD

**Issue by alexbeletsky** [dokku/dokku#111]
Deployment for staging environments are typically required to not be exposed to everyone. Simples solution is to apply Basic Auth and access by username/password.

It would be easy to do: if `/home/git/:app/` folder contains file `HTPASSWD` with one line `username:password`, following section will be added to nginx.conf location section.

```
auth_basic "Restricted";
auth_basic_user_file $APP/HTPASSWD;
```

I will be happy to add that on top of https://github.com/progrium/dokku/pull/104

**Comment by twe4ked** [comment]
There is a plugin by @matto1990 that does just this. :smile: 

https://github.com/matto1990/dokku-secure-apps
