### ISSUE TITLE
dokku asks for password on Google Compute Engine

### ISSUE THREAD

**Issue by vitch** [dokku/dokku#1131]
I have run into some issues trying to install dokku on [Google Compute Engine](https://cloud.google.com/compute/). The same steps which work on EC2 are failing on Google's system for some reason.

I install dokku onto a clean Ubuntu 14.04 instance. After installing dokku running the command prompts for a password:

```bash
$ dokku
[sudo] password for bob:
```

(where I am logged in as `bob`)

The same user can `sudo dokku`:

```bash
$ sudo dokku
Usage: dokku [--quiet|--trace|--rm-container|--rm|--force] COMMAND <app> [command-specific-options]
```

Looking at the contents of the dokku script I narrowed it down to the following command:

```bash
sudo -u dokku -E -H dokku
```

This works on an EC2 install but prompts for a password on GCE.

Any ideas why?

**Comment by vitch** [comment]
Sometimes asking the question gives you the answer...

I looked in `/etc/sudoers` on the GCE box and my user was added like so:

```
bob ALL=NOPASSWD: ALL
```

From [this answer](https://unix.stackexchange.com/questions/28309/sudo-no-password-breaks-other-sudo-u-uses/28310#28310) I tried changing it to the following and it worked:

```
bob ALL=(ALL) NOPASSWD: ALL
```

Not sure if this is something the install script can work around or a manual step I would need to take?

**Comment by josegonzalez** [comment]
How did you install dokku? Using the debian package? Did you install a specific commit?

Here is the `sudoers` file for the vagrant box:

```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	exempt_group=sudo
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo	ALL=NOPASSWD:ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
```

Sounds like maybe you set a password for the dokku user somehow?

**Comment by vitch** [comment]
I installed using the script from the README. Although the one liner didn't work so I needed to split it across a few of lines:

```
wget https://raw.github.com/progrium/dokku/v0.3.17/bootstrap.sh
chmod +x bootstrap.sh
sudo ./bootstrap.sh
rm bootstrap.sh
```

I guess the thing with the `sudoers` file is that GCE manages it in some way (the user I edited was added in there by pasting my key into the "Google Developers Console")

**Comment by michaelshobbs** [comment]
@josegonzalez what needs to be done here?

**Comment by josegonzalez** [comment]
One of us needs to test out google app engine. My contact there went silent, so thats where we are.

**Comment by jvanbaarsen** [comment]
I can confirm this is  still an issue (just tested this). I can however run `sudo -i` and then run `dokku` without having to enter a password.

**Comment by josegonzalez** [comment]
Closing as the GCE folks have yet to get back to me on getting access to their "official" package, so basically I don't care enough about that platform to fix the issue.

Willing to merge PRs to fix the issue though, so feel free to submit a fix :)
