### ISSUE TITLE
Can't "just" push to remote repo

### ISSUE THREAD

**Issue by webdevotion** [dokku/dokku#116]
Hello

Following the nice Vimeo screencast by @progrium I thought I would give Dokku another shot.
Installing goes smooth, but when I push my local Rails app to my server
I get:

```
fatal: 'ocean-app' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

When I manually create the repo on my server and push ( with success )
I don't get any of the Dokku magic like `app detected` etc.

What am I missing here?

Thanks.

**Comment by priyatam** [comment]
I created a Dokku (0.3.17) image on DigitalOcean running Ubuntu 14.04.2, and can access my server via ssh. I can't deploy the sample node-js app and get the same errors as listed by the @webdevotion,  @christiangenco, and @joshuairl.

```
fatal: 'sample' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

@plietar I setup my SSH like this and can access the server via `ssh dokku@[my-ip]` 

`cat ~/.ssh/id_rsa.pub | ssh root@[my-ip] sshcommand acl-add dock dokku-keys`

What am I missing?

**Comment by juanpastas** [comment]
I have the same problem with a Digital Ocean.

I tried copy my local public key to the server with:

```
cat ~/.ssh/id_rsa.pub | ssh root@45.xxx.xxx.xxx "sudo sshcommand acl-add dokku added_from_ssh_command"
```

I am trying pushing with root too:

```
git push root@45.xxx.xxx.xxx:mentoring2 master
fatal: 'mentoring2' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

The file `/home/dokku/.ssh/authorized_keys` has the first key I added with digital ocean, and a new one that is added with sshcommand.

Any advice?

**Comment by josegonzalez** [comment]
Please open a new issue.
