### ISSUE TITLE
What can't it do?

### ISSUE THREAD

**Issue by naggie** [dokku/dokku#12]
Under things it can't do according README.md:

> - Multi-node. Not a huge leap, but this isn't the project for it. Maybe as Super Dokku.
> - Multitenancy. It's ready for it, but again, probably for Super Dokku.

Does this mean I can't deploy more than 1 node app (or ruby) app at time time, or something else?

@frillip also.

**Comment by reverie** [comment]
This still needs to be clarified.

**Comment by progrium** [comment]
Not sure what you mean. Please be more specific in what needs to be
clarified. This has since been resolved in the docs:
http://progrium.viewdocs.io/dokku/index

On Sun, Feb 1, 2015 at 11:52 AM, Andrew Badr <notifications@github.com>
wrote:

> This still needs to be clarified.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/12#issuecomment-72380758>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by reverie** [comment]
The content I see on that page is almost exactly the same as in naggie's original bug report. Does multitenancy mean multiple apps or multiple users with distinct security privileges?

**Comment by progrium** [comment]
There is no real concept of users, but multiple apps, sure. I'll update that part.

**Comment by reverie** [comment]
Thanks! Would have made me more confident before digging in.
