### ISSUE TITLE
Running out of space with many deployments

### ISSUE THREAD

**Issue by alexbeletsky** [dokku/dokku#120]
The situation mentioned in #119 is more critical then I thought.

I'm doing heavily testing of `dokku` running for my staging environment. I did maybe ~50 deployments today and by evening I recieved that:

```
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: -----> Build complete!
remote: -----> Releasing app ...
remote: -----> Release complete!
remote: -----> Deploying app ...
remote: /usr/local/bin/dokku: line 56: echo: write error: No space left on device
remote:       ERROR: failed on rev 59b59cec24672f3bdc14704802ae3f8b81633ace - push denied
To git@stage.likeastore.com:app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@stage.likeastore.com:app'

```

I checked out and indeed, my 20GB dropplet if full!

```
root@likeastore:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda         20G   19G     0 100% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            242M  8.0K  242M   1% /dev
tmpfs            50M  236K   49M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            246M  392K  246M   1% /run/shm
none            100M     0  100M   0% /run/user
```

Running `docker images` I see a lot of images created. It shows size: `24.81 kB (virtual 1.018 GB)`, for almost all images.

This have to be mitigated some how. What I see:
1. Can we use images of smaller size? - in my assumption, it's rare case than application using file system or something to store on drive, what's the minumum size of image we can create for buildstep?
2. We have to clean-up - it makes sense to store some images, to have rollback or something, but dokku does not provide this feature now any how. My proposal is to delete image, if CONTAINER exists before new application deployment.

As always, I'm ready to contribute the stuff, let's just agree on actual strategy.

(I would also add a question here: how can I quckly remove all `<none>` images :))

**Comment by benwinding** [comment]
I found this on google, so for anyone else who stumbles here, [docker has a good article](https://success.docker.com/article/no-space-left-on-device-error).

Basically, the log files of the containers can get extremely big, in my case I had a 15G log file for a Dokku app!
