### ISSUE TITLE
Deletion of apps

### ISSUE THREAD

**Issue by chris-rock** [dokku/dokku#124]
With dokku it is really easy to deploy new apps. But it gets really difficult to clean up everything. We require something like

``` sh
dokku delete app
```

From my perspective this task requires the following:
- Remove config from plugins (e.g. nginx)
- Reload nginx (similar to new deploy)
- Stop app in docker
- Delete docker images and container
- Delete git repo

Have I missed something?

**Comment by TheNotary** [comment]
Thanks everyone who contributed.  To aid googler's, check the bottom of the docs [here](http://dokku.viewdocs.io/dokku~v0.3.23/application-deployment/) 

```
    dokku apps:destroy myapp
```

**Comment by josegonzalez** [comment]
New docs link [here](http://dokku.viewdocs.io/dokku/deployment/application-management/) for recent versions.
