### ISSUE TITLE
Overlapping docker options

### ISSUE THREAD

**Issue by kilianc** [dokku/dokku#1275]
ref https://github.com/progrium/dokku/pull/1254#issuecomment-118204117

>  can bake another PR. You said those options work their own way but it seems to me that DOKKU_DOCKER_BUILD_OPTS and DOCKER_OPTIONS_BUILD are the same, all we need is the docker plugin ones, there nothing you can't so passing params to docker, included disabling cache and exposing the port. I'll open a new ticket to iterate on this a bit more?

I confirmed with @josegonzalez that all docker options that are not DOCKER_OPTIONS_* are overlapping and we may want to get rid of them.

**Comment by josegonzalez** [comment]
Well not all, but at least the one he mentioned (`DOKKU_DOCKER_BUILD_OPTS`).

**Comment by josegonzalez** [comment]
We'll probably want to do this for the 0.4.0 release.

**Comment by kilianc** [comment]
It may be a choice to not remove them all, but they are all overlapping each other.

* `DOCKERFILE_PORT=8080 DOCKER_OPTIONS_DEPLOY="-p 8080"` 
* `DOCKER_OPTIONS_DEPLOY`
* `DOCKER_OPTIONS_RUN`
* `DOCKER_OPTIONS_BUILD`
* `DOKKU_DOCKER_BUILD_OPTS === DOCKER_OPTIONS_BUILD`
* `DOKKU_DOCKERFILE_CACHE_BUILD=0 DOCKER_OPTIONS_BUILD="--no-cache=true"`
* `DOKKU_DOCKERFILE_START_CMD` <-- should be renamed into `DOCKER_OPTIONS_DEPLOY_CMD` and moved into docker plugin.

**Comment by josegonzalez** [comment]
@kilianc Want to make a pr with all these changes? With the exception of `DOKKU_DOCKERFILE_START_CMD` - it's not been released in a stable version yet - we'll need to support both the old and new methods.

**Comment by kilianc** [comment]
I would love to, not sure what you mean with

> With the exception of DOKKU_DOCKERFILE_START_CMD - it's not been released in a stable version yet - we'll need to support both the old and new methods.

That just got merged right ?

**Comment by josegonzalez** [comment]
Oh and when making the PR, please add a `*DEPRECATED*` comment. Would be nice if it echo'd a deprecation notice, similar to how `deploy:all` works. Maybe to stderr?

**Comment by josegonzalez** [comment]
Yeah, that just got merged, but since I haven't made a release, if anyone depends on it, they can go kick rocks.

**Comment by kilianc** [comment]
Oh I just misread what you wrote, deprecation warnings for all but `DOKKU_DOCKERFILE_START_CMD` gotcha, this will take me 2/3 days I am not a bash guy :)

**Comment by josegonzalez** [comment]
Neither am I!

**Comment by kilianc** [comment]
what are we doing here O_O

![computing](https://cloud.githubusercontent.com/assets/385716/8506086/a86ef312-21b7-11e5-8bce-b0c82d694ee6.gif)

**Comment by michaelshobbs** [comment]
I'm :+1: on utilizing the docker-options plugin for consistency. IIRC, that plugin came in after the fact or at I'm choosing to remember it that way :smile:

**Comment by josegonzalez** [comment]
Note, we should probably take care of this for 0.4.0.

**Comment by michaelshobbs** [comment]
I'm not really sure what specifically we're trying to do here. To be clear the `docker-options` plugin is a method to persist desired docker args between build/deploy/run executions. 

Let me try to enumerate my questions/concerns.

- `DOKKU_DOCKERFILE_PORT`: not sure how or why we'd modify this functionality as the way it currently stands, it simplifies the logic of how to start the deployed container
- `DOKKU_DOCKERFILE_CACHE_BUILD` is a transient variable in that it can change between deployments. so we shouldn't persist it in the `docker-options` plugin
- renaming `DOKKU_DOCKERFILE_START_CMD` to `DOCKER_OPTIONS_DEPLOY_CMD` seems ambiguous as "DEPLOY" is a dokku phase.

Looking through the code I think this list is exhaustive with regards to us diverging from injecting docker args with the `docker-options` plugin. I don't think it makes sense to modify these cases but I'm definitely open to more clarifying discussions around what we're trying to accomplish.

**Comment by josegonzalez** [comment]
@michaelshobbs if you don't think there is anything to do here, I'm okay with closing :)

**Comment by michaelshobbs** [comment]
@kilianc do you have any further thoughts here?

**Comment by kilianc** [comment]
@michaelshobbs the point that I am tried to make at the time is that there are misnamed and overlapping options and you can do the same thing from both the plugin and core which is confusing.

For consistency everything should be handled by core or plugin and decide appropriate names for each option and update the docs. If I recall correctly even @josegonzalez got confused and confirmed the overlapping. The discussion is somewhere in the tickets.

I will have some time tomorrow to reorganize thoughts on this but most of my reasoning is already spilled out!

**Comment by kilianc** [comment]
> renaming DOKKU_DOCKERFILE_START_CMD to DOCKER_OPTIONS_DEPLOY_CMD seems ambiguous as "DEPLOY" is a dokku phase.

That's why it's called `DOCKER` and not `DOKKU` that's what docker calls it

**Comment by michaelshobbs** [comment]
I don't understand what you mean by `that's what docker calls it.` Can you clarify?

**Comment by kilianc** [comment]
Sorry I think I messed up! The ref is here: https://docs.docker.com/reference/run/ the `DEPLOY` is a reference to the dokku `DEPLOY` phase indeed the param is `CMD` as explained in the docker docs. It's the command executed in the deploy phase of dokku!

**Comment by josegonzalez** [comment]
@kilianc Can you make a pr with the changes you have in mind? Much easier to sort out what's overlapping when we can see some changes :)

**Comment by kilianc** [comment]
I would be happy to, but work is getting in the way lately. No time for the next 4w. Is there a deadline/expected shipping date for 0.4??

**Comment by josegonzalez** [comment]
4 days ago ;)

**Comment by josegonzalez** [comment]
Going to close this. Any work can happen in a pr if necessary.
