### ISSUE TITLE
fatal: '/hello' does not appear to be a git repository

### ISSUE THREAD

**Issue by pygy** [dokku/dokku#130]
Hello,

When I push data to my first test app, I get the following:

``` sh
pygy@Albert ~/tmp/hello> git remote add dokku ssh://git@dokku.me:2222/hello
pygy@Albert ~/tmp/hello> git push dokku master
fatal: '/hello' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

A headless, empty repository has apparently been created, though (not sure if it is complete):

``` sh
vagrant@dokku:/home/git$ ls hello
HEAD  branches  config  description  hooks  info  objects  refs
```

Thee files look legit, and the directories contain etheir nothing, empty folders, or sample hooks.

OS X 10.8. I'm using a Vagrant VM based on the provided Vagrantfile. Doku has been installed as described in the README. The public key has been succesfully uploaded.

**Comment by dynamostack** [comment]
i tried to address this here in the wiki. pl take a look.
https://github.com/debianmaster/Notes/wiki/Dokku-Auth-Setup

**Comment by pygy** [comment]
In the penultimate line what is "devmachine"?

s/not/now/ and s/devmachine/dev machine/ in the last sentence.

Otherwise it looks fine. Note that I'm not using dokku right now.
