### ISSUE TITLE
Using config:set when value contains a space is a bit confusing/annoying

### ISSUE THREAD

**Issue by jimeh** [dokku/dokku#1361]
Here's an example of what I mean using dokku_client.sh:

```
$ dokku config:set HUBOT_IRC_CONNECT_COMMAND="AUTH fakenick fakepassword"
Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]
Must specify KEY and VALUE to set.
Connection to fakedomain.com closed.

$ dokku config:set HUBOT_IRC_CONNECT_COMMAND=AUTH\ fakenick\ fakepassword
Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]
Must specify KEY and VALUE to set.
Connection to fakedomain.com closed.

$ dokku config:set HUBOT_IRC_CONNECT_COMMAND="AUTH\ fakenick\ fakepassword"
-----> Setting config vars
       HUBOT_IRC_CONNECT_COMMAND: AUTH fakenick fakepassword
-----> Restarting app fakeapp
[...]
```

Maybe I'm just being silly, but I expected all three variants of the above `config:set` command to work, alas only the last one does.

**Comment by joshco** [comment]
Yeah I've run into this too.  For the time being I've just accepted it as a dokkuism.  However it isn't something I'm looking forward to explaining in cases where I might recommend dokku for real use.

Can someone explain the tradeoffs that made this be this way?

**Comment by fwolfst** [comment]
As a good start, the output could point in that direction, e.g.

    $ dokku config:set HUBOT_IRC_CONNECT_COMMAND="AUTH fakenick fakepassword"
    Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]
    Whitespaces need to be escaped, i.e. KEY="VAL\ WITH\ SPACES"
    Must specify KEY and VALUE to set.
    Connection to fakedomain.com closed.

@josegonzalez What do you think?
And i am not absolutely sure that your shell has a word to say in that usage.

**Comment by josegonzalez** [comment]
@fwolfst sounds fine to me.

The annoying bit here is getting the whitespace consistently working both locally and via ssh.

**Comment by michaelshobbs** [comment]
The following syntax works now

```
root@dokku:~/dokku# dokku config:set testapp HUBOT_IRC_CONNECT_COMMAND="AUTH fakenick fakepassword"
-----> Setting config vars
       HUBOT_IRC_CONNECT_COMMAND: AUTH fakenick fakepassword
-----> Restarting app testapp
App testapp has not been deployed
root@dokku:~/dokku# dokku config testapp
=====> testapp config vars
HUBOT_IRC_CONNECT_COMMAND: AUTH fakenick fakepassword
```

closing as fixed. please let us know if this isn't working for you now.

**Comment by josegonzalez** [comment]
@michaelshobbs I think he means over ssh, which I don't think works.

**Comment by jimeh** [comment]
Indeed I was doing that over ssh. I don't think I'll have to update my dokku box this week, but I'll try to test it out asap :)

**Comment by michaelshobbs** [comment]
Oh but #1529 was merged. So shouldn't this issue be closed now?

```
ssh dokku@dokku.me config:set testapp HUBOT_IRC_CONNECT_COMMAND="AUTH fakenick fakepassword"
Usage: dokku config:set APP KEY1=VALUE1 [KEY2=VALUE2 ...]
Whitespaces need to be escaped, i.e. KEY="VAL\ WITH\ SPACES"
Must specify KEY and VALUE to set.
Connection to dokku.me closed.
```

**Comment by josegonzalez** [comment]
Is there a reason the others don't work? I'm happy with closing as long as we know the reason.

**Comment by josegonzalez** [comment]
Closing this in favor of #1262.
