### ISSUE TITLE
problem on ubuntu arm

### ISSUE THREAD

**Issue by pietrondo** [dokku/dokku#1393]
```bash

root@server:~# uname -a
Linux server 4.0.0-200 #1 SMP Mon Apr 13 13:54:58 UTC 2015 armv7l armv7l armv7l GNU/Linux
```

when I do DOKKU_TAG=v0.3.23 bash bootstrap.sh
```bash
root@server:~# DOKKU_TAG=v0.3.23 bash bootstrap.sh
Preparing to install v0.3.23 from https://github.com/progrium/dokku.git...
Ign http://mirror.cloud.online.net trusty InRelease
Ign http://ports.ubuntu.com trusty-security InRelease                          
Hit http://ports.ubuntu.com trusty-security Release.gpg                        
Hit http://ports.ubuntu.com trusty-security Release                            
Hit http://mirror.cloud.online.net trusty Release.gpg                          
Hit http://mirror.cloud.online.net trusty Release                              
Get:1 http://apt.syncthing.net syncthing InRelease [8,836 B]                   
Hit http://ports.ubuntu.com trusty-security/main armhf Packages                
Hit http://ports.ubuntu.com trusty-security/universe armhf Packages            
Hit http://mirror.cloud.online.net trusty/main armhf Packages                  
Hit http://mirror.cloud.online.net trusty/universe armhf Packages              
Hit http://ports.ubuntu.com trusty-security/main Translation-en                
Hit http://mirror.cloud.online.net trusty/main Translation-en                  
Hit http://mirror.cloud.online.net trusty/universe Translation-en              
Hit http://ports.ubuntu.com trusty-security/universe Translation-en            
Ign http://mirror.cloud.online.net trusty/main Translation-en_US               
Ign http://mirror.cloud.online.net trusty/universe Translation-en_US           
Hit http://repo.ajenti.org main InRelease                                      
Hit http://repo.ajenti.org main/main armhf Packages                            
Hit http://repo.ajenti.org main/ubuntu armhf Packages                       
Get:2 http://apt.syncthing.net syncthing/release armhf Packages [806 B]     
Ign http://apt.syncthing.net syncthing/release Translation-en_US               
Ign http://apt.syncthing.net syncthing/release Translation-en                  
Ign http://repo.ajenti.org main/main Translation-en_US              
Ign http://repo.ajenti.org main/main Translation-en
Ign http://repo.ajenti.org main/ubuntu Translation-en_US
Ign http://repo.ajenti.org main/ubuntu Translation-en
Get:3 http://get.docker.io docker InRelease  
Ign http://get.docker.io docker InRelease
Hit https://packagecloud.io trusty InRelease
Hit https://packagecloud.io trusty/main armhf Packages
Get:4 https://packagecloud.io trusty/main Translation-en_US
Hit http://get.docker.io docker Release.gpg        
Hit https://deb.nodesource.com trusty InRelease    
Hit https://deb.nodesource.com trusty/main Sources
Hit https://deb.nodesource.com trusty/main armhf Packages
Get:5 https://deb.nodesource.com trusty/main Translation-en_US
Ign https://packagecloud.io trusty/main Translation-en_US
Ign https://packagecloud.io trusty/main Translation-en
Hit http://get.docker.io docker Release
Ign https://deb.nodesource.com trusty/main Translation-en_US                   
Ign https://deb.nodesource.com trusty/main Translation-en                      
Fetched 9,642 B in 8s (1,092 B/s)                                              
W: Failed to fetch http://get.docker.io/ubuntu/dists/docker/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by rcarmo** [comment]
That's simple enough: there is no official ARM build of Docker at this point - only older versions in the main armhf Ubuntu/ports repo.

You can build a modern version by hand (see https://taoofmac.com/space/links/2015/08/19/0938) but you won't be able to run dokku because all the Docker images it requires are built solely for x64.

(I've been looking at doing an ARM version of buildstep, but it requires rebuilding a lot more stuff...)

**Comment by pietrondo** [comment]
deb for docker 
https://launchpad.net/ubuntu/trusty/armhf/docker.io

There are some docker image for arm

https://community.scaleway.com/t/getting-started-docker-on-c1-armhf/383

**Comment by josegonzalez** [comment]
We don't support arm, just x64, and I have no intention of doing packaging of it. If you'd like to install from source, you can do that, but we won't support the installation here.

**Comment by josegonzalez** [comment]
Question: what are you installing this onto?

**Comment by pietrondo** [comment]
I'm trying to installing on ubuntu 14.04 on arm server provided by
https://www.scaleway.com/

**Comment by josegonzalez** [comment]
Can you install from source instead?

**Comment by rcarmo** [comment]
@josegonzalez he'll be able to install from source, but the buildstep image won't run... Dockerfile deployments -might- work, but...

**Comment by josegonzalez** [comment]
Gotcha. Sounds like a lot of work on our end for very little gain to be honest. I'm going to close this - as I've been teetering on - as it sounds like only source-based installations that will be used to support just docker *might* work.

**Comment by pietrondo** [comment]
so, how can I do?

**Comment by josegonzalez** [comment]
Install from master as noted [here](http://progrium.viewdocs.io/dokku/advanced-installation/). Good luck.

**Comment by rcarmo** [comment]
Well, I intend to rebuild buildstep _some day_, but am taking it very slowly ;)

**Comment by vincentfretin** [comment]
I think you'll have to rebuild progrium/cedarish:cedar14 to be based on https://hub.docker.com/r/armbuild/ubuntu-debootstrap/ and then rebuild progrium/buildstep on your progrium/cedarish:cedar14. Good luck.

**Comment by pietrondo** [comment]
Excuse me. I'm  a beginner.. What  are the steps?

**Comment by vincentfretin** [comment]
@pietrondo Something like that. I can't test because I don't have an armhf. I can't help you further that that.

Build the cedarish image:

    git clone https://github.com/heroku/stack-images cedarish
    cd cedarish
    sed -i 's@FROM.*$@FROM armbuild/ubuntu-debootstrap:14.04@' Dockerfile
    docker build -t progrium/cedarish:cedar14 .

And then the buildstep image:

    cd -
    git clone git@github.com:progrium/buildstep.git
    cd buildstep
    make

**Comment by vincentfretin** [comment]
And to build docker itself, look at what hypriot is doing on Raspberry Pi
https://github.com/hypriot/rpi-docker-builder

**Comment by rcarmo** [comment]
@vincentfretin actually, to build `cedarish` you have to edit the `cedar-14.sh` file to replace the APT package repos (pointing them to `ports.ubuntu.com` and adding multiverse) and replace `syslinux` with `syslinux-common`. But good call on that base image, I was using mine :)

Things go south a little later (there's some other breakage I can't remember offhand), but like I said, I intend to get it done some day (I have quite a few `armhf` boards, and am actually posting this from one of them...), so we can keep using this issue to discuss things if you guys don't mind -- with luck, other interested parties can find this and chime in.

Also, the link I posted above has working instructions to build Docker for ODROID, Raspberry Pi and the Scaleway boards (provided you're running Ubuntu).

**Comment by rcarmo** [comment]
On a whim, I had a go at `cedarish` again, and got it to build. But of course the `buildstep` Dockerfile goes and tries to download a x64 build of `herokuish`, so that has to be rebuilt for ARM...

**Comment by sfcgeorge** [comment]
Ah I also was hoping to run Dokku (or Flynn or something nice) on Scaleway because their cheap truly dedicated servers seem just perfect for a personal Heroku clone. 2GB RAM, 4cores @ 1.2GHz, 50GB SSD. So :+1: but I understand the complexity.

**Comment by josegonzalez** [comment]
If someone wants to fund that development, I could be convinced to take a crack at it, but I doubt that's the case :)

**Comment by marvinroger** [comment]
There is ScaleWay, but also OVH launching a new ARM-based Cloud, priced *1.13$ a month* for  a 2.0 Ghz vCore, 2G vRAM and a 10 GB HDD (for now it is in alpha phase, so it's free). That is some crazy price! I hope Docker will do something about its ecosystem for a better ARM support, as this is probably the future of server computing, knowing how tiny, cheap, and energy-efficient it is.

**Comment by josegonzalez** [comment]
> If someone wants to fund that development, I could be convinced to take a crack at it, but I doubt that's the case :)

**Comment by josegonzalez** [comment]
Closing as it doesn't seem like anyone cares enough about the feature to work on it/support it via funding.

**Comment by sam3d** [comment]
Seeing as Docker now supports ARM natively, it'd probably make this substantially easier to work on. Don't re-open the issue as I don't have time to start working on it now but I will soon as I'd really love to be able to run Dokku on ARM.

**Comment by vasilakisfil** [comment]
@sam3d did you get any progress on that ?

**Comment by krokofant** [comment]
Any hope for this getting picked up?

**Comment by josegonzalez** [comment]
- Herokuish will probably never work on ARM unless someone takes the time to recompile it for ARM, and I somehow doubt the buildpacks will work as is.
- `plugn` needs to be updated to build for ARM, but thats not hard.
- Building a Dokku deb/rpm for ARM isn't hard either.

I'm not running Dokku on ARM, so I have no interest in seeing this implemented. If you want to see this implemented in Dokku, you're going to have to work on PRs to submit support for it.

**Comment by josegonzalez** [comment]
For anyone interested, we introduced [arm support in 0.26.x](https://dokku.github.io/release/dokku-0.26.0).
