### ISSUE TITLE
"git push dokku master" fails with "bash: box: command not found"

### ISSUE THREAD

**Issue by vijayviji** [dokku/dokku#1489]
Dokku version: 0.4.0

When I try doing 'git push dokku master' (after doing 'git remote add dokku dokku@dokku.me:project'), I faced with the following error:

>bash: box: command not found
>fatal: Could not read from remote repository.
>
>Please make sure you have the correct access rights
>and the repository exists.

*RootCause:*
This is because I've added the key as following: 
```bash
cat ~/.ssh/id_rsa.pub | ssh vagrant@dokku.me | "sudo sshcommand acl-add dokku 'Home box'"
```
Note: I've used multiple words in description.

**Comment by jvanbaarsen** [comment]
@michaelshobbs Can it be that this issue got closed by accident?

**Comment by michaelshobbs** [comment]
Nope. I patched `sshcommand` to support your use case. GitHub auto closed it when that patch was merged.

**Comment by jvanbaarsen** [comment]
:+1: Also, just to be sure, for sshcommand, is your fork the one that is currently being used? Or the original from @progrium ?

**Comment by michaelshobbs** [comment]
oh i see what happened now. my bad. no it has not been merged into the official repo nor has a release been made. 

@progrium can i get collab access to progrium/sshcommand please?
