### ISSUE TITLE
Support static websites

### ISSUE THREAD

**Issue by obrienmd** [dokku/dokku#155]
There seem to be buildpacks available for static websites on Heroku, especially this one (which I think can just be slimmed down to 'nginx'):

https://github.com/abhishekmunie/heroku-buildpack-static

IMO, this would be a great step towards dokku as a standard deployment model, as many have little static sites that would benefit from quick deployment.

**Comment by IlyaSemenov** [comment]
## Workaround below

You may convert your static site into a Dokku project by creating a `Dockerfile` in the root of your site with the following contents:

```Dockerfile
FROM ilyasemenov/dokku-static-site
```

More details here: https://github.com/IlyaSemenov/dokku-static-site

**Comment by josegonzalez** [comment]
As of a very long time ago, dokku supports static sites via the official [nginx buildpack](https://github.com/dokku/buildpack-nginx). Just add a `.static` file to the base of your repository.
