### ISSUE TITLE
Add support for purging the npm cache

### ISSUE THREAD

**Issue by rsteckler** [dokku/dokku#1570]
My package.json references an npm module at the tip of a private repo.  Works great, but since dokku caches the npm folder, it never checks if there's a new commit on that package.

It would be nice if something similar to the [Heroku repo plugin](https://github.com/heroku/heroku-repo) existed so I could dokku repo:purge_cache.

**Comment by michaelshobbs** [comment]
While I agree with this enhancement, I have the same package.json and as of [this commit](https://github.com/npm/npm/commit/5829ecf032b392d2133b) should not be an issue anymore.

**Comment by jvanbaarsen** [comment]
@michaelshobbs Can this issue be closed because of the solution you stated in your comment?
