### ISSUE TITLE
Plugin command structure

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#1579]
Currently, plugin command structure (i.e. anything that is not a trigger. think `dokku ps:restart`) lives in a `commands` file that must be "hunted for." 

execution today:
```
implemented=0
for script in $PLUGIN_ENABLED_PATH/*/commands; do
  set +e; $script "$@" ; exit_code=$? ; set -e
  if [[ "$exit_code" -eq "$DOKKU_NOT_IMPLEMENTED_EXIT" ]]; then
    continue
  fi

  implemented=1
  if [[ "$exit_code" -ne "$DOKKU_VALID_EXIT" ]]; then
    exit $exit_code
  fi
done
if [[ "$implemented" -eq 0 ]]; then
  dokku_log_warn "\`$*\` is not a dokku command."
  dokku_log_warn "See \`dokku help\` for a list of available commands."
  exit 1
fi    
```

I propose this be simplified in a similar manner as #1039 and #592. 

### benefits
- more efficient execution
- less TRACE output leads to easier debugging
- explicit plugin namespace prevents plugins from polluting other plugin namespaces. this also prevents an error in one plugin from blocking the execution of another

proposed execution example:
```
PLUGIN_NAME="$1"
if [[ -x $PLUGIN_ENABLED_PATH/$PLUGIN_NAME/command ]]; then
  "$PLUGIN_ENABLED_PATH/$PLUGIN_NAME/command" "$@"
elif [[ -x $PLUGIN_ENABLED_PATH/${PLUGIN_NAME%%:*}/subcommands/${1#*:} ]]; then
  "$PLUGIN_ENABLED_PATH/${PLUGIN_NAME%%:*}/subcommands/${1#*:}" "$@"
fi
```
refs: #592 #1039

---

### general spec
- each command lives in `plugins/<plugin_name>/subcommands/<name_of_command>`
- current UI will be maintained (i.e. `<plugin_name>:<subcommand>`)
- top-level command (i.e. `dokku ps`) will be implemented in `plugins/<plugin_name>/command`
- old method of "hunting" may be supported as an interim but will be deprecated
- execution of plugin triggers are not changed by this

### open questions
- Can we actually do this with all of the core plugins? probably not as `git` comes to mind
- If we still support the old method, do we need to wait for a major release to merge this?

thoughts?

**Comment by josegonzalez** [comment]
- Why not reverse the subcommand/command check?
- We lose most/all git history doing this.
- What commands does git need to support? We should figure this out, as we're probably being overly aggressive there.
- Nope, so long as existing stuff works, this can go into a patch release imo.

**Comment by u2mejc** [comment]
I'm onboard, I'm stoked to see that old broken plugins may stop being called for every plugin lookup. Trace will be so different.

Following what @josegonzalez said
* +1 on swapping to check sub commands exists before default to the command file, sure you meant to do this.
* History isn't lost, I'm sure you mean simply that the new file will not show the same blame line by line?
* Not sure where git would be an issue, @michaelshobbs can you elaborate what comes to mind?
* +1 testing for command if subcommand fails seems safe today, maybe in 0.5 drop command support?
* This seems like another benefit? Removing any part of the core that doesn't call the specific plugin will resolve the core being broken by plugins. Calling less specific plugin features like post-deploy would not be affected by this today.

**Comment by josegonzalez** [comment]
One thing: before 4.1, you could install a plugin (I guess you still can) with a foldername other than the prefix it provides. This might break certain installations.

**Comment by michaelshobbs** [comment]
Answers inline

- Why not reverse the subcommand/command check?
 - Sure to what end?
- We lose most/all git history doing this.
 - Not if we `git mv`
- What commands does git need to support? We should figure this out, as we're probably being overly aggressive there.
 - The case statement includes `git-*)`
- Multiple plugins can no longer handle the same command. Are any core plugins affected by this?
 - The only case that we care (I think) is `help` but we can code something specific for that use-case. This would force namespace cleanliness and would make us be conscious of where we do "weird" stuff like `help` roll up.

- before 4.1, you could install a plugin (I guess you still can) with a foldername other than the prefix it provides. This might break certain installations
 - I think this is why we still support the `commands` method still. dokku core plugins (and official ones) can minimize the debug noise and avoid getting hung up by buggy 3rd party plugins if we attempt the namespaced command first and then the old loop method. As always it will be up to 3rd party plugin authors to update to the new standard. I don't see this as an all (core + 3rd party) or nothing change. Even if we just make this change in core and official plugins, we are making huge strides forward in stability and ease of troubleshooting.

**Comment by josegonzalez** [comment]
- By reversing the check, we decrease the number of plugins we have to check for core commands.
- We can't `git mv` and split into separate files at the same time, so you'd still lose history somewhere. Not a big deal, just wanted to note that.
- Is there a way we can define this list? Or do we want to special-case the git plugin?
- Fine by me if we special case help.
- What is `$1` in your execution example? I assumed we were no longer iterating over plugins, hence if `$1` is like `tar` and we have a `dokku-tar` plugin, it wouldn't be handled as expected by a user.

What about a call that doesn't have a subcommand, like `apps`?

**Comment by michaelshobbs** [comment]
- By reversing the check, we decrease the number of plugins we have to check for core commands.
 - just to clarify you are saying it should look like this?
```
if [[ -x $PLUGIN_ENABLED_PATH/${PLUGIN_NAME%%:*}/subcommands/${1#*:} ]]; then
  "$PLUGIN_ENABLED_PATH/${PLUGIN_NAME%%:*}/subcommands/${1#*:}" "$@"
elif [[ -x $PLUGIN_ENABLED_PATH/$PLUGIN_NAME/command ]]; then
  "$PLUGIN_ENABLED_PATH/$PLUGIN_NAME/command" "$@"
fi
```
- We can't git mv and split into separate files at the same time, so you'd still lose history somewhere. Not a big deal, just wanted to note that.
 - fair point. my derp there.
- Is there a way we can define this list? Or do we want to special-case the git plugin? Fine by me if we special case help.
 - the `git` plugin commands file is the only one in core that contains a glob in the case statement
- What is $1 in your execution example? I assumed we were no longer iterating over plugins, hence if $1 is like tar and we have a dokku-tar plugin, it wouldn't be handled as expected by a user.
 - `dokku` proper would still have it's top level case statement that would implement this new command execution just like it does the old method today 
- What about a call that doesn't have a subcommand, like apps?
 - this is defined in the original general spec: "top-level command (i.e. dokku ps) will be implemented in `plugins/<plugin_name>/command`"

**Comment by josegonzalez** [comment]
- Yes, I mean that code snippet.
- Yay I win a point.
- I just want to trim down on globs, otherwise we're going to have to always special case that plugin, no?

Do we have any other large pieces of work that we want to do for the next release? If not, I think it's best this be implemented straightaway. We will wait *max* one week before merging. I don't want this sitting around forever. Do you feel this is fair?

**Comment by michaelshobbs** [comment]
It's just the one instance and I don't see us completely removing the old loop method unless we want to break 3rd party plugins again. (Not sure we benefit much from that anyway) That said, I'll do some more digging and see if we need that case or if we can be more specific and drop it.

Regarding other big things, meh? Probably? Can't think of any right now though.

**Comment by josegonzalez** [comment]
I mostly want the core plugins to all follow this pattern so that our 0.5.x can remove iterating over every plugin.

**Comment by michaelshobbs** [comment]
I honestly don't think we should force this change on existing 3rd party plugins but I strong encouragement might yield the same effect. (i.e. changing everything in core/official plugins and documentation of course)

We also control or influence a lot of the ecosystem. So this may be moot come 0.5.x.

**Comment by josegonzalez** [comment]
Note: I've made PRs to more than half the community plugins that we are aware about, and we've made it clear how we handle BC-compatibility, so I'm not too worried about dropping support in 0.5.x for the old-style iteration.
