### ISSUE TITLE
serving https domains:add without certificate

### ISSUE THREAD

**Issue by mmerickel** [dokku/dokku#1597]
I have a site that's hosted internally using a wildcard cert for the dokku instance. Later we exposed parts of it through a public-facing nginx reverse proxy using a public fqdn. I did this via adding `dokku domains:add myapp fqdn`. Where this goes wrong is when the request is forwarded from the proxy to the app. The proxy setup is as follows:

```
server {
    listen 443 ssl;
    server_name fqdn;

    ssl_certificate /etc/nginx/certs/fqdn.crt;
    ssl_certificate_key /etc/nginx/certs/fqdn.key;

    location / {
        proxy_set_header Host fqdn;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass https://myapp.dokku.me;
    }
}
```

So the SSL is terminated at the proxy and a new request is sent to the dokku instance using the internal domain.

Of note is that the host header is the fqdn (which matches the `domains:add fqdn` to the dokku instance). Also the traffic is forwarded over the internal network encrypted with the wildcard ssl certificate. Finally, the `X-Forwarded-Proto` should be respected from the original instance (`$http_x_forwarded_proto`).

So far I'm having trouble figuring out how to do this properly without putting the fqdn's certificate on the dokku instance and configuring my internal network's dns server with a local ip for the fqdn so that the proxied request looks as close to the original as possible.

The default `domains:add fqdn` includes a http-only proxy for the fqdn and as such I've been able to get the whole thing to work by using http-only internally and manually removing the `proxy_set_header X-Forwarded-Proto` from the generated config. However, this is obviously not ideal.

At the end of the day I'm sure dokku doesn't currently support what I want but I'm also having trouble coming up with "how to actually do this at all" before I can suggest a tweak to dokku. Any help would be appreciated.

**Comment by josegonzalez** [comment]
Pretty sure what you want to do is supported via the [`DOKKU_SSL_TERMINATED`](http://progrium.viewdocs.io/dokku/deployment/ssl-configuration/#running-behind-a-load-balancer) option.

**Comment by mmerickel** [comment]
Configuring `DOKKU_SSL_TERMINATED` affects the entire app configuration afaict, whereas I still want it to be internally accessible over ssl. Also I'm not clear if setting that option will allow me to communicate over ssl or not but it seems not looking at the nginx.ssl-terminated.conf template.

**Comment by michaelshobbs** [comment]
Couldn't you also ship your own nginx template to do what you wanted?

**Comment by mmerickel** [comment]
I think I could... I'm experimenting now with some options but part of the issue is that I'm not even sure it's possible to do what I want with and internal SSL connection so "my own template" doesn't exist yet. However what I want seems pretty reasonable to me so I am partially asking for advice.

**Comment by josegonzalez** [comment]
You want to terminate ssl on a load balancer but handle both ssl and non-ssl without redirects?

**Comment by mmerickel** [comment]
I want to terminate public ssl and re-encrypt the traffic with an internal certificate. This is fully supported by nginx in general.

**Comment by josegonzalez** [comment]
OH. Okay, so shouldn't the local app have the internal certificate? I'm not too familiar with this, so maybe I'm misunderstanding it.

**Comment by mmerickel** [comment]
Yes, ideally the local app would have the internal certificate. However the `Host` header needs to be the public one for the web app to function properly, which means that affects dokku's config... it needs to support mappings to that hostname.

**Comment by mmerickel** [comment]
So I was able to get this to work using the following setup:

1) No `domains:add`.
2) Add new server conf to /etc/nginx/sites-enabled/www.example.com that forwards traffic to the example upstream:

```
server {
  listen      [::]:443 ssl spdy;
  listen      443 ssl spdy;
  server_name www.example.com;
  access_log  /var/log/nginx/example-access.log;
  error_log   /var/log/nginx/example-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://example;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header X-Forwarded-For $http_x_forwarded_for;
    proxy_set_header X-Forwarded-Port $http_x_forwarded_port;
    proxy_set_header X-Request-Start $msec;
  }
}
```

So this is only marginally different from DOKKU_SSL_TERMINATED because it's listening on 443. The only quirk I see is that the ssl negotiation happens using `example.dokku` (internal fqdn) certificate, but then the host header is for something not signed by that certificate! Somehow nginx doesn't care.

This is solvable by being able to specify the more options for `domains:add` such as whether to expect ssl termination on that domain and which ports to listen on.

**Comment by josegonzalez** [comment]
Mind speccing out what that ui would look like in a comment in this thread?

**Comment by mmerickel** [comment]
Well I know that dokku is pretty bad at option parsing and there's also a lot of UI around similar things in dokku that I may or may not understand already:

1) DOKKU_SSL_TERMINATED
2) VHOSTS (which I haven't looked at very closely)
3) `domains:add` (is this related to vhosts?)

Possible option:
```
dokku config:set DOKKU_SSL_TERMINATED=www.example.com
dokku domains:add https://www.example.com
```

**Comment by josegonzalez** [comment]
Yeah, option parsing is terrible because bash isn't so great at it. We'd need to consider rewriting the core to better support it, but thats not a priority at this time.

**Comment by michaelshobbs** [comment]
IMO, this is not our primary use case and thus should be handled via a custom template.

**Comment by josegonzalez** [comment]
Closing as you can handle this with a custom template, and the 0.5.x release will be quite easy to do this with.
