### ISSUE TITLE
Client "contrib/dokku_client.sh" populates automatically parameters wrongly.

### ISSUE THREAD

**Issue by davivcgarcia** [dokku/dokku#1638]
**Description of problem:**

Client *contrib/dokku_client.sh* populates automatically parameters wrongly for a few Dokku commands, such as *mongo:create* and *postgres:create*. It uses the app name as the name parameter, ignoring the parameter given.

**Outputs:**

- `uname -a`:

```
Linux dokku 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

- `docker version`:

```
Client:
 Version:      1.8.3
  API version:  1.20
  Go version:   go1.4.2
  Git commit:   f4bf5c7
  Built:        Mon Oct 12 05:37:18 UTC 2015
  OS/Arch:      linux/amd64
 
 Server:
  Version:      1.8.3
  API version:  1.20
  Go version:   go1.4.2
  Git commit:   f4bf5c7
  Built:        Mon Oct 12 05:37:18 UTC 2015
  OS/Arch:      linux/amd64
```

- `docker -D info`:

```
 Containers: 2
 Images: 57
 Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 61
  Dirperm1 Supported: false
 Execution Driver: native-0.2
 Logging Driver: json-file
 Kernel Version: 3.13.0-66-generic
 Operating System: Ubuntu 14.04.3 LTS
 CPUs: 4
 Total Memory: 7.798 GiB
 Name: dokku
 ID: NDUS:6JUF:ZNSI:INLE:4CLG:MCX7:5GUW:PP6W:OAKW:OQIH:LM4N:U2SM
 WARNING: No swap limit support
```

- `dokku version`:

```
0.4.3
```

- `dokku plugin`:

```
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.4.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```

**Environment details (AWS, VirtualBox, physical, etc.):**

I'm running Dokku host on a instance at a OpenStack public cloud, using Ubuntu 14.04.

**How was dokku installed?:**

Using the *bootstrap.sh* script.

**How reproducible:**

Very easily.

**Steps to Reproduce:**

1. Create the local app repo (git clone).
2. Add the Git Remote for Dokku host at the local git 
3. Use the Dokku client to create the application profile.
4. Use the Dokku client to create a new db service.

**Actual Results:**

The db service created is using the app name, defined at step 3.

**Expected Results:**

The db service should be using the name provided as parameter.

**Additional Outputs:**

```
$ dokku mongo:create nosqldb 
-----> Starting container
       Waiting for container to be ready
=====> MongoDB container created: simple-app
       DSN: mongodb://simple-app:221f762ed7091dfc3fa792c8f09d4801@dokku-mongo-simple-app:27017/simple-app
$ dokku postgres:create 
-----> Starting container
       Waiting for container to be ready
       Creating container database
=====> Postgres container created: simple-app
       DSN: postgres://postgres:f41d513277df122f2352608e23019bd4@dokku-postgres-simple-app:5432/simple_app
```

**Comment by davivcgarcia** [comment]
I verified that **contrib/dokku_client.sh" always appends the name of the local git repository as a parameter. This is handy most part of the time, but it is causing misbehavior with commands that the first parameter is not the application name, like **postgres:create** and **mongo:create** which are expecting the name for the DB. Is there anyway to disable this behavior?

**Comment by esclapes** [comment]
I have bumped into this too with the mariadb plugin.

As a workarround I ended up running the commands directly on the docker host.

**Comment by josegonzalez** [comment]
@michaelshobbs what if we allow users to do something like:

```shell
dokku --app APP NAME command args
```

We could then have a `DOKKU_APP` env var that is set by the above. Commands would optionally check for this variable, and shift/unshift args as appropriate. This would fix the client issue quite nicely.

**Comment by michaelshobbs** [comment]
I haven't look at the client code in over a year I think but that seems legit.

**Comment by josegonzalez** [comment]
We definitely would need to update *all* the core code to handle this though.
