### ISSUE TITLE
Supplied nginx config in application root does not take

### ISSUE THREAD

**Issue by matthewmueller** [dokku/dokku#1659]
If I supply an `nginx.template.conf` in the app's repository root, it looks like it gets copied and concatenated with the existing nginx configuration. 

The problem is that the existing configuration already has the same server name, so the configuration below gets ignored

**Comment by josegonzalez** [comment]
We just copy that out of the repository into `/home/dokku/APP/` and use it like normal. Can you provide a repro, as well as the info we ask for in the readme?

**Comment by u2mejc** [comment]
@matthewmueller Looks like your file might be miss named? 

http://progrium.viewdocs.io/dokku/nginx/ says:
* Copy the existing template - ssl or non-ssl - into your application repository's root directory as the file `nginx.conf.template`.

I don't think nginx -t would pass with two matching locations, but let us know if that resolves it for you. :wink:

Note: I tested this built from master.

**Comment by michaelshobbs** [comment]
@matthewmueller bump. can you confirm your template is named `nginx.conf.template`?

**Comment by josegonzalez** [comment]
*bump*

**Comment by josegonzalez** [comment]
Womps. Closing, feel free to comment with more info and we can re-open.
