### ISSUE TITLE
static port for node application

### ISSUE THREAD

**Issue by oriandabud** [dokku/dokku#1672]
hi,
i have been trying to use specific port for my application 3000 for an instance
found this plugins:
[dokku-bind-port](https://github.com/stuartpb/dokku-bind-port)
[docker options](https://github.com/dyson/dokku-docker-options)
when i am using the -p flag , my application actually deployed and exposed on the correct port -> 3000 and not the default 5000

i understood that the port issue is because the old app is still running , while the new one gets deployed 

i saw this PR to docker , but dokku still seems to have this problem
[docker-fixed-port](https://github.com/docker/docker/pull/6682)

also found this on digital ocean
[subdomain-digitalOcean](https://www.digitalocean.com/community/questions/how-can-i-specify-port-for-my-dokku-droplet)
but i have no need for subdomain, and my server uses a specific pot

what am i missing? , there is a solution?
i may be new to dokku but i couldn't find clean solution, and hope the is one :+1:  , it is really handy one

**Comment by u2mejc** [comment]
Hi @oriandabud, I don't think the docker issue is related. That was a docker 1.0 specific bug that wasn't releasing ports used by stopped containers, good news is that what your trying to do has been a feature of Dokku's for some time now!

If you want to bind your application to a different port, you can set the var DOKKU_NGINX_PORT and/or DOKKU_NGINX_SSL_PORT. Note: Even for non default ports or no vhosts, nginx is still used to enable zero downtime deployments (ie you can't start a new container if another is already using the same port, instead nginx proxys the preferred port to the random backend port).  http://progrium.viewdocs.io/dokku/nginx/

Let me know if that helps. :smiley:

**Comment by michaelshobbs** [comment]
@oriandabud bump

**Comment by oriandabud** [comment]
ok great this ENV solved my problem

thanks :+1:

**Comment by oriandabud** [comment]
i seems to be happening again
tried to unset DOKKU_NO_NGINX
but still, i can access to <container-ip>:5000 , to localhost:<container-port>

but i cant access localhost:5000
why is that?
```
-----> Running post-deploy
-----> VHOST support disabled. Skipping domains setup
-----> Setting config vars
       NO_VHOST: 1
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Shutting down old containers in 60 seconds
=====> b98753d0751c86bdb6595f660d0074a2316c315cfcf32161b3161ae4660e223f
=====> Application deployed:
       http://91.213.242.81:32772 32773 (container)
       http://91.213.242.81:5000 (nginx)
       https://91.213.242.81:5000 (nginx-ssl)
```

**Comment by michaelshobbs** [comment]
I'm not sure I understand your question. You want to know why you can access your app at <ip>:5000 but not localhost:5000?

**Comment by michaelshobbs** [comment]
I was able to make that work (on master)...Can you clarify what you're attempting to do and what's not working for you?
```
-----> Running post-deploy
=====> unsupported vhost config found. disabling vhost support
-----> Setting config vars
       NO_VHOST: 1
-----> Setting config vars
       NO_VHOST: 1
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
=====> Application deployed:
       http://10.0.0.2:32790 (container)
       http://10.0.0.2:5000 (nginx)
```
```
root@dokku:~/dokku# dokku config node-js-app
=====> node-js-app config vars
DOKKU_APP_RESTORE:     1
DOKKU_DOCKERFILE_PORT: 8000
DOKKU_NGINX_PORT:      5000
NO_VHOST:              1
PORT:                  5000
root@dokku:~/dokku# curl http://10.0.0.2:5000
Hello World!
root@dokku:~/dokku# curl http://localhost:5000
Hello World!
```

**Comment by oriandabud** [comment]
oh sorry , the markdown removed my inline comments

working for me: 
 curl http://10.0.0.2:5000 (aka 10.0.0.2 is the container ip)
curl http://localhost:3728 (aka 3728 is dokku deployed port)

not working for me:
curl http://localhost:5000 (although i have DOKKU_NGINX_PORT:  5000)

**Comment by michaelshobbs** [comment]
To be clear 10.0.0.2 is not the container ip in my example. It is the standard network interface. 

Check out how port 5000 is bound with `netstat -plant`; look for port 5000. Assuming the port binding looks right, check out how you're resolving the name `localhost`. `ping localhost` is a pretty quick method of doing this. You might also `grep localhost /etc/hosts` and compare the two.

**Comment by michaelshobbs** [comment]
Also make sure not to set `DOKKU_NO_NGINX`

**Comment by oriandabud** [comment]
no DOKKU_NO_NGINX
also ping localhost works

and `grep localhost /etc/hosts` outputs
```
::1	localhost	ip6-localhost ip6-loopback
```

**Comment by michaelshobbs** [comment]
Maybe add `127.0.0.1` as an alias to localhost in `/etc/hosts`?

**Comment by michaelshobbs** [comment]
This is what I have in my vagrant env

```
root@dokku:~# grep localhost /etc/hosts
127.0.0.1  dokku.me *.dokku.me www.test.app.dokku.me www.test.dokku.me localhost
::1     localhost ip6-localhost ip6-loopback
```

**Comment by josegonzalez** [comment]
@oriandabud Do you have any update for us?

**Comment by josegonzalez** [comment]
Closing. Feel free to comment with more info and we can re-open.
