### ISSUE TITLE
Dokku Setup page still accessible after initial configuration

### ISSUE THREAD

**Issue by johnwilson** [dokku/dokku#1692]
Hello,

After installation and configuration I get redirected to the Readme page. However the web setup page is still accessible.
Everything works properly though but I would have expected the page to be publicly unavailable after initial configuration.

**Comment by josegonzalez** [comment]
It definitely should delete itself, the code for that is [here](https://github.com/progrium/dokku/blob/master/contrib/dokku-installer.rb#L60).

Can you provide the information we ask for [here](https://github.com/progrium/dokku/blob/master/CONTRIBUTING.md#reporting-other-issues), particularly how dokku was installed?

**Comment by johnwilson** [comment]
Web setup page failes to delete itself

uname -a:

```bash
Linux localhost 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

docker version:
```bash
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
```

docker -D info:
```bash
Containers: 9
Images: 72
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 90
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: localhost
ID: A3FN:OZ57:726G:NGCV:EWJE:MZH3:36TI:7WD4:ZUOM:3FO4:JGFB:S43Z
WARNING: No swap limit support
```

dokku version:
```bash
0.4.4
```

dokku plugin:
```bash
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  couchdb              1.0.0 enabled    dokku couchdb service plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```

Environment: Linode Ubuntu 14.04 with KVM. Followed the [manual setup information for linode](http://progrium.viewdocs.io/dokku/getting-started/install/linode/)

After installation completion and input of ssh key with hostname, I get the finished message and redirect to the Readme page.
I managed to deploy the heroku node.js and ruby on rails sample projects properly and each are available at their subdomains.

However the web setup page is still available on the root domain.

**Comment by johnwilson** [comment]
I run the installer commands manually and it appears the dokku-installer files in nginx and /etc/init were already removed. I'm thinking nginx just didn't restart properly(or at all) because the setup page is no longer available.

**Comment by josegonzalez** [comment]
Sounds like the restarts failed... interesting. @callahad can you check this out on linode?

**Comment by gustavohenke** [comment]
I had the same problem on a Digital Ocean droplet.

I solved it by manually executing [this lines](https://github.com/progrium/dokku/blob/master/contrib/dokku-installer.rb#L60), as originally stated by @josegonzalez

**Comment by josegonzalez** [comment]
Note, I've rewritten and thoroughly tested a new version of the dokku-installer in python, which should be a bit more robust and handle removing itself better. Please comment if you can replicate this in a more recent version. The change went out in 0.4.7.
