### ISSUE TITLE
How to deal with user uploaded files in containers?

### ISSUE THREAD

**Issue by busla** [dokku/dokku#1695]
When running an app (Django app in this case) I need to persist the /media/ folder somehow. When I git push my app it resets the container so all user submitted files are lost.

I´m trying to figure out how I can use docker-options to store uploaded files on the host but according to the docker docs this is what happens:

```
Note: If the path /opt/webapp already exists inside the container’s image, its contents will be replaced by the contents of /src/webapp on the host to stay consistent with the expected behavior of mount

https://docs.docker.com/v1.8/userguide/dockervolumes/
```

So I guess I can´t set the upload dir to the host using docker-options.

Another way would be to create a separate container to use as a cdn but would love to hear how Dokku users are dealing with this.

**Comment by michaelshobbs** [comment]
In multi-node deployments (I understand that dokku does not inherently support this) I use Amazon S3. However, on the surface, it would seem you could do the following:
```
dokku docker-options:add myapp deploy "-v /path/on/host:/path/in/container"
```

However, you'll may run into issue with permissions. The only way I've gotten around this so far is to build a custom herokuish image with a static non-root user and setting the `$USER` env variable to force `herokuish` to run everything as that user.

**Comment by johnfraney** [comment]
@busla I've been using the `docker-options ... "-v..."` method for persistent files for a few projects. I did find that if I tried to mount a folder in the container's `/opt/` directory it wouldn't work at all, but mounting the folder in the container's `/app/` directory worked as expected:

```
Deploy options:
   ...
    -v /apps/myapp/media:/app/media
    -v /apps/myapp/static:/app/static
Run options:
    ...
    -v /apps/myapp/media:/app/media
    -v /apps/myapp/static:/app/static
```

**Comment by jvanbaarsen** [comment]
@busla Is your question answered? /cc @josegonzalez

**Comment by busla** [comment]
Yes, I used docker-options to set the media volume.

**Comment by jvanbaarsen** [comment]
Ok great! Can you close this issue?

**Comment by busla** [comment]
Yes... and thanks!

**Comment by DjarallahBrahim** [comment]
Hi, i have the same problem, when i deploy my app for the first time, i used docker-option to host the uploadsIMG folder of my application:

`dokku docker-options:add betrocapi run "-v /home/dokku/dataBetroc:/uploadsIMG"`
`dokku docker-options:add betrocapi deploy "-v /home/dokku/dataBetroc:/uploadsIMG"`

and when i run:
`dokku docker-options betrocapi`
it gives me:
`Build options:
    --link dokku.mysql.betrocsql:dokku-mysql-betrocsql
Deploy options:
    --link dokku.mysql.betrocsql:dokku-mysql-betrocsql
    --restart=on-failure:10
    -v /home/dokku/dataBetroc:/uploadsIMG
Run options:
    --link dokku.mysql.betrocsql:dokku-mysql-betrocsql
    -v /home/dokku/dataBetroc:/uploadsIMG
`

But when i change something in my i app and rerun `git push dokku master` i lose all my picture.

Ps: i try also : `dokku storage:mount ....` same result.

Any one can explain to me why ? 

Thank you

**Comment by josegonzalez** [comment]
Please do not comment on 3 year old issues, and instead create a new one if you need support.

**Comment by josegonzalez** [comment]
Note: the correct way to handle this is the [official persistent storage](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/) plugin.
