### ISSUE TITLE
Best practice for non-http open ports

### ISSUE THREAD

**Issue by gaborcsardi** [dokku/dokku#1730]
I was wondering about the current best practice to open a non-http port for a container, and have other containers connect to it.

There a couple of alternatives I guess, but I just couldn't find a solution that plays well with dokku's zero downtime upgrade. Things I have tried or considered:

* set `-p` docker options, via a config file, or from the command line. E.g. `-p 8080:8080`. This is of course problematic when you upgrade, because the old docker container binds to the port, and then you cannot start the new container that would bind to the same port.
* link the containers together with `--link` docker options. This is nowadays discouraged because of `--net`, but should still work fine. As I see the problem is that when the linked container is updated, then the linking container must be manually restarted, otherwise the linking container's environment variables are not updated.
* creating a network and using `--net` to connect the containers to it. This is suggested instead of the `--link` option, but I don't see how it solves my problem, actually. Maybe I would need an overlay network, even within a single host.
* using `iptables` directly to forward packets from the container's port to the host port, and then updating them to forward from the new container, once the app is updated. This seems to be possible, but also somewhat fragile with future docker updates. I would probably need to write a dokku plugin for make it work.

What do you think?

**Comment by michaelshobbs** [comment]
The entire datastore plugin library does this. I've not been involved personally with the development of them but I would suggest looking there for some 'inspiration'.

**Comment by gaborcsardi** [comment]
@michaelshobbs You mean the db and db-like plugins at github.com/dokku?

Yes, they are good for most cases, I guess. 

Personally I would prefer to be able to have the same workflow for the db containers as well, i.e. being able to just `git push` a new config the same way as for other containers, etc. But I understand there there are good reasons to provide these containers as plugins.

So if I have a similar app, e.g. an application server that does not speak http, you suggest to put in a plugin? The application server would mostly talk to the outside world, not to the other containers on the server.

**Comment by josegonzalez** [comment]
Can you provide an example application that you are trying to handle?

**Comment by gaborcsardi** [comment]
E.g. rserve is a binary protocol, to talk to an R process, https://rforge.net/Rserve/index.html
The R process runs in the container, waits for commands and input, executes some R code, and sends back the result.

Originally I wanted to use RabbitMQ in an ordinary container, too, but have given up on that for now and I am just using the plugin. 

In general a regular container is better for me, because I can manage everything the same way.

**Comment by michaelshobbs** [comment]
You can use the docker-options plugin then assuming that the R or RabbitMQ container names don't change and are always started.

**Comment by gaborcsardi** [comment]
@michaelshobbs Is there a way to disable the zero-downtime upgrade? When I expose the port via docker-options, and upgrade, dokku cannot start a new container, because the old one binds to the port on the host. At least by default. IS there a workaround?

**Comment by michaelshobbs** [comment]
Oh wait you are running the R container as a dokku app? There is no way to disable zero downtime deployments. Our primary use case is to manage web apps.

You might try deploying the R (dockerfile i assume) as a standard docker container. Honestly though this sounds like a candidate for a dokku plugin as it sounds like the R container is a dependency for your main app? I also admit that I may not be fully grok'ing your use case.

**Comment by josegonzalez** [comment]
In theory we can use nginx as a [tcp proxy](https://www.nginx.com/blog/tcp-load-balancing-with-nginx-1-9-0-and-nginx-plus-r6/), thereby allowing you to use dokku's HA features while still managing this as an application.

**Comment by gaborcsardi** [comment]
@josegonzalez I was thinking about that, but I could only find an old unmaintained tcp nginx module. Your link with the stream module looks great! This would be indeed the perfect solution, I'll try to put it together tomorrow. Thanks for the pointer!

**Comment by gaborcsardi** [comment]
@michaelshobbs Yes, I am trying to use dokku apps only, as it is just more convenient if I can `git push` a new config the same way as for the web apps.

**Comment by michaelshobbs** [comment]
Yeah I think this would be best implemented as a dokku plugin to be honest

**Comment by josegonzalez** [comment]
Closing as I don't think it's feasible for us to support tcp proxying out of the box.

Note that if you *do* go with a tcp proxy - perhaps the [dokku-haproxy](https://github.com/256dpi/dokku-haproxy) plugin - you will want to disable zero-downtime checks:

```shell
dokku config:set APP DOKKU_SKIP_ALL_CHECKS=true DOKKU_SKIP_DEFAULT_CHECKS=true
```
