### ISSUE TITLE
config:set doesn't allow double-quotes / providing meteor settings.json file

### ISSUE THREAD

**Issue by JarnoLeConte** [dokku/dokku#1737]
In try to deploy a [meteor app](https://www.meteor.com) providing a **settings.json** file.

Therefore we need to put the content of settings.json in an **environment variable**. This can be done this way, *where it seems the double quote escaping is required by `dokku_client.sh`*
```
$ dokku config:set <app> METEOR_SETTINGS="'$(cat ./settings.json | sed "s/\"/\\\"/g")'"
```

So far so good I think ...

*2 observations*:
1. Deployment of an app **fails**, because the building process don't handle the double quotes correctly.
2. But deployment without METEOR_SETTINGS and set this variable afterwards, **succeed**.

So it's the building process that don't handles the double quotes correctly. But in the second case, when calling `dokku ps:rebuild` the build will fail again. 

I get the following error, where it seems the double quotes are missing:
```
$ dokku ps:rebuild myapp
-----> Cleaning up...
-----> Building myapp from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Fetching custom buildpack
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
######################################################################## 100.0%
-----> Bundling bundle
-----> Building Meteor with ROOT_URL: http://myapp.mydokku.me
Errors prevented isopacket load:

While loading isopacket `constraint-solver`:
packages/meteor/server_environment.js:13:1: METEOR_SETTINGS are not valid JSON:
{env: production, wait: 5 }
at packages/meteor/server_environment.js:13:1
at <runJavaScript-2>:50:4
at <runJavaScript-2>:1274:3



/tmp/buildpacks/custom/meteor-qKra/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
```

I used the [meteor-buildpack-horse](https://github.com/AdmitHub/meteor-buildpack-horse) buildpack. I'm not sure if the buildpack or Dokku is responsible for the build error?!

My questions:
- What do I wrong by providing the settings.json file this way? 
- Are there other ways to accomplish this task? 
- Maybe it's a bug in the building process that could be fixed?

**Comment by JarnoLeConte** [comment]
As of my understanding, the quotes seems to be removed by the following script:

**File : [dokku / plugins / build-env / pre-build-buildpack](https://github.com/progrium/dokku/blob/master/plugins/build-env/pre-build-buildpack) (line 27)**
```sed 's@^\([^=]*\)=\(.*\)\$@echo \\\"\2\\\" >/tmp/env/\1@g'```

What is happening here? Is the removal of double quotes required?

**Comment by josegonzalez** [comment]
I think we remove outer double-quotes.

**Comment by michaelshobbs** [comment]
The way you are setting `METEOR_SETTINGS` is definitely not in our primary use case and thus was not taken into account when we wrote the config parsing code. If you want to take a stab at making your case work and even add a test case for it, that would be greatly appreciated.

More details on tests and running a dev env can be found here: http://progrium.viewdocs.io/dokku/development/testing/

**Comment by JarnoLeConte** [comment]
```
echo "METEOR_SETTINGS='{ "key1": "val1", "key2": "val2" }'" | for ENV_VAR in $(cat); do echo $ENV_VAR |sed 's@^\([^=]*\)=\(.*\)\$@echo \\\"\2\\\" >/tmp/env/\1@g' >>/tmp/set_env.sh;done
```
this outputs `/tmp/set_env.sh`:
```
METEOR_SETTINGS='{
key1:
val1,
key2:
val2
}'
```

**Comment by josegonzalez** [comment]
You may want to escape your inner quotes.

**Comment by JarnoLeConte** [comment]
I get a working solution by escaping inner quotes. Although it's not ideal because when there already are escaped quotes in json or when single quote characters don't match then bash code breaks at several places. It seems hard to handle such input in bash. 

So for simple settings files, my solutions works. But handle all cases in bash seems hard. 

Probably a better way is to create a dokku plugin that copies the settings file to the server and directly put it in the environment variables on startup, without interfering the config vars. 

Should that be a good solution? How could it be implemented? At which state (which hook) can this be attached and how that works without conflicting other vars or ending up in config again?

**Comment by branco91** [comment]
@JarnoLeConte 

I am having the same issues has you are having.  This is my analysis so far:

If we escape the double quotes within the JSON, the build will pass however meteor will fail to start becaused escaped json is not a valid json.

**Comment by josegonzalez** [comment]
@michaelshobbs one hack I just thought of.

What if we base64-encode all commands locally before sending them over ssh, and then executing them base64-decoded on the other side?

**Comment by michaelshobbs** [comment]
Encode them at the beginning of the `dokku` script, like [here](https://github.com/dokku/dokku/blob/master/dokku#L58-L69)? How do you base64 encode in bash?

**Comment by josegonzalez** [comment]
https://gist.github.com/markusfisch/2648733

?

**Comment by michaelshobbs** [comment]
Seems legit. Still not sure how we would do that on the client side...

**Comment by josegonzalez** [comment]
Client would see its args, base64encode them, and send it off as `dokku base64 THESHA`, and server side we decode and are off to the races.

In our "official" client, we could even just require that `base64 ` is a command-line tool before running any commands.

**Comment by josegonzalez** [comment]
Closing in favor of #1262. Any solution to either should solve both, otherwise we'll just have to revisit this yet again.

**Comment by JarnoLeConte** [comment]
Indeed, #1262 will be a general solution to this problem.
But to make it work just for meteor, the [dokku-meteor](https://github.com/JarnoLeConte/dokku-meteor) plugin will be useful.

**Comment by josegonzalez** [comment]
Wait, that has to be in profile.d? If not, you could use something like the official [copy-files-to-image](https://github.com/dokku/dokku-copy-files-to-image) plugin.

**Comment by JarnoLeConte** [comment]
Copying the settings file to containers could be handled by that plugin probably, but at the end it has to be in an environment variable, therefore in profile.d I do a trick that copies the settings.json content to the environment variable METEOR_SETTINGS at start up. 

Furthermore the copy-files-to-container plugins uses **cat** to copy contents. Exactly that is where the double quotes are not preserved.

**Comment by nsvrana** [comment]
So for temporarily making this work, what am I doing wrong here? I've put this in my ENV file for this particular project

`<METEOR_SETTINGS={\"private\":{\"logger\":{\"console\":{\"level\":\"debug\",\"silent\":false},\"file\":{\"level\":\"debug\",\"silent\":false}}}}>`

But I receive:        

`<Error: METEOR_SETTINGS are not valid JSON: {\"private\":{\"logger\":{\"console\":{\"level\":\"debug\",\"silent\":false},\"file\":{\"level\":\"debug\",\"silent\":false}}}}>`

Without the escape characters I get:

`<packages/meteor/server_environment.js:13:1: METEOR_SETTINGS are not valid JSON: {private:{logger:{console:{level:debug,silent:false},file:{level:debug,silent:false}}}}>`

**Comment by josegonzalez** [comment]
Use the plugin suggested.

**Comment by abrkn** [comment]
Is there a way to set config with quotes? I'm also setting JSON from environment variables. Using files is not compatible with my configuration system.
