### ISSUE TITLE
Nginx conf in app directory is not being generated

### ISSUE THREAD

**Issue by zbyte64** [dokku/dokku#175]
This was something that was working (8/13) but when I do a fresh dokku install the /home/git/{appname}/nginx.conf does not get generated. Also missing is the VHOST file. The container does run and open up a port but for whatever reason the nginx plugin isn't doing its thing.  /etc/nginx/conf.d/dokku.conf does exist so commands and install appear to get called but post-deploy does not.

EC2 Image: ubuntu/images/ebs/ubuntu-raring-13.04-amd64-server-20130423 (ami-c30360aa)

```
dpkg --list | grep lxc-docker
ii  pluginhook                         0.1.0                            amd64

dpkg --list | grep lxc-docker
ii  lxc-docker                         0.5.3-1                          amd64
```

**Comment by skorokithakis** [comment]
I am seeing this issue right now. I deployed three apps just fine, but the fourth does not get an nginx config created. I'm not sure why, as I have dokku set up to create automatic subdomains on a main domain.

**Comment by josegonzalez** [comment]
@skorokithakis please do not comment on a 4 year old issue. Instead, create a new one with all the information we ask for. Thanks.
