### ISSUE TITLE
pushing to dokku remote after "git commit --amend"-ing a commit doesn't rebuild

### ISSUE THREAD

**Issue by cdbattags** [dokku/dokku#1755]
I just get back that everything is up to date.

**Comment by jvanbaarsen** [comment]
@cdbattags Did you try to force push to the repo?

**Comment by u2mejc** [comment]
@cdbattags Dokku (just like any remote git server) checks the hash that your pushing. `git commit --amend` allows you to rewrite history and should update sha1 hash of the commit. If you editor exits with an error, it's possible that the commit wasn't captured. Have a look at `git log`.

Let us know if that helps. If your still having trouble, please fill out the issue reporting template so we can help you further: https://github.com/dokku/dokku/blob/master/CONTRIBUTING.md#reporting-other-issues

**Comment by michaelshobbs** [comment]
@cdbattags any update here?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any update by the author.
