### ISSUE TITLE
![remote rejected] 

### ISSUE THREAD

**Issue by LukeSheard** [dokku/dokku#1759]
I'm trying to setup dokku on an EC2, and I can get as far as pushing however I get a pre-receive hook rejection everytime. I created a gist of the trace here:

I also tried ssh-ing in to the server and running `dokku deploy app` but it fails 
```
Unable to find image 'dokku/client:latest' locally
Pulling repository docker.io/dokku/client
Error: image dokku/client:latest not found
```

**Comment by michaelshobbs** [comment]
The failure is on line 508 of the gist. 
```
 git submodule update --init --recursive
```

Do you have submodules in that repo?

**Comment by LukeSheard** [comment]
Yeah, I do. I didn't even notice that. I guess I just have to add SSH access for the EC2 server to github?

**Comment by michaelshobbs** [comment]
Yeah. Check out the plugins page in the docs. There's plugin to help with injecting keys into the deploy process. 

http://dokku.viewdocs.io/dokku/plugins/
https://github.com/cedricziel/dokku-deployment-keys

**Comment by LukeSheard** [comment]
Managed to solve the issue, I couldn't get the deployment keys plugin working. Also realized that I wasn't on the dokku user on the server, to that was the cause of some of the issues.

**Comment by michaelshobbs** [comment]
What was the solution?

**Comment by LukeSheard** [comment]
I just added the ssh key to the dokku user (the found the docs:
http://dokku.viewdocs.io/dokku/application-deployment/#deploying-with-private-git-submodules )
