### ISSUE TITLE
Including other git repos in a project

### ISSUE THREAD

**Issue by zachfeldman** [dokku/dokku#1760]
Hey there, I have a project that depends on another git repo for its content. When I try to push this repo to Dokku, the pre-receive hook is declined. Seems similar to the resolution for this issue:

https://github.com/dokku/dokku/issues/1416

Does anyone have any ideas here as to how to have an internal git repo inside of your project git repo? The problem is that I can't reach outside of the docker container for the content either, which was my first instinct (just put it on the droplet/server itself)

**Comment by michaelshobbs** [comment]
I thought the the standard way to include a git repo inside another is using submodules or potentially git trees. dokku supports submodules out of the box.

**Comment by josegonzalez** [comment]
Without more information about this repository, there isn't much we can do here. Git submodules are the way to go imo for external repos.

**Comment by zachfeldman** [comment]
@michaelshobbs is right, thought this issue might be useful to others who have the same issue in the future!

I kinda hate submodules but I'll look into it.

**Comment by josegonzalez** [comment]
@zachfeldman if you can describe what you are trying to do in less vague terms, maybe we can suggest something?

**Comment by zachfeldman** [comment]
I have a repo that is a web app, that depends on another repo for its content. But if you try to push the "parent" web app repo with the other repo inside of it, and a rake task to git pull that other repo, Dokku rejects the push.

**Comment by michaelshobbs** [comment]
When you say depends, what is the current mechanism for representing the dependency in your code and/or repo?

**Comment by josegonzalez** [comment]
Does it reject the push because you don't have ssh keys in the container?

**Comment by zachfeldman** [comment]
I use Ruby to parse the files int he content repo and display them in the web app. The push is not rejected for that reason, I've already been using Dokku successfuly with other apps.

**Comment by josegonzalez** [comment]
So why is it rejected?

**Comment by zachfeldman** [comment]
The reason given was "pre-recieve hook declined"

**Comment by josegonzalez** [comment]
Can you include the debugging information we ask for in the `CONTRIBUTING.md`?

**Comment by zachfeldman** [comment]
It's ok, I'm kind of already over this (found another solution) but I'll reopen if I get back to it if that's cool.
