### ISSUE TITLE
browse directories?

### ISSUE THREAD

**Issue by fabdelgado** [dokku/dokku#1763]
Within Dokku where I can find my application to browse directories uploaded?
Thankyou

**Comment by michaelshobbs** [comment]
dokku stores your app in the form of a git server repo on disk. so the structure is quite different that that of your cloned repo. however you can browse the deployed container using the `dokku enter` command.

http://dokku.viewdocs.io/dokku/deployment/one-off-processes/#entering-existing-containers

**Comment by fabdelgado** [comment]
thankyou
