### ISSUE TITLE
Dokku events problem

### ISSUE THREAD

**Issue by fabdelgado** [dokku/dokku#1765]
Try Dokku events: off but this is gathering information.

**Comment by fabdelgado** [comment]
How to clean logs from container of dokku?

**Comment by michaelshobbs** [comment]
dokku event do not log to the container. they log to `/var/log/dokku/events.log`.

you might try `grep -R DOKKU_EVENTS /home/dokku` to see if that env var is set anywhere accidentally

**Comment by michaelshobbs** [comment]
also to be clear the command syntax looks like this
```
root@dokku:~# dokku | grep events
    events:list                                                       List logged events
    events:off                                                        Disable events logger
    events:on                                                         Enable events logger
    events [-t]                                                       Show the last events (-t follows)
```

**Comment by fabdelgado** [comment]
command "dokku cleanup" clear all logs

**Comment by michaelshobbs** [comment]
I think there is some confusion around what logs you are referring to. `dokku cleanup` will definitely recover disk space as it deletes interim container layers that are no longer needed for the deployed app. 

It should also be noted that this command is run whenever you push a repo to dokku.

**Comment by fabdelgado** [comment]
@michaelshobbs mmm, run the command:
Dokku events: off
Message: Disabling Dokku events logger

Then run logs -t app
The logs were generated and increased disk space

**Comment by michaelshobbs** [comment]
`dokku logs` != `dokku events`

You app logs will consume some disk space just as they would outside of docker/dokku.

**Comment by fabdelgado** [comment]
@michaelshobbs there is a command to clear the logs in the container?

**Comment by michaelshobbs** [comment]
I am not aware of a command to do this on a running container. However, this is definitely a docker question and might be best suited to be asked in one of their forums (irc or otherwise perhaps).

**Comment by fabdelgado** [comment]
@michaelshobbs thank you for your help
