### ISSUE TITLE
Running a Quake2 server on dokku

### ISSUE THREAD

**Issue by carlossless** [dokku/dokku#1766]
Hey guys,

I'm super new to docker and dokku, so this might seem trivial and I might have missed some documentation so bear with me please.

I have a dokku setup running a couple of websites. Now, I've got this urge to frag a couple of friends, and I want to setup a quake2 server in a docker container. Now since dokku is a docker container manager and as I understand I shouldn't mix and match those I need to do it through dokku. Luckily dokku supports using just Dockerfiles for my containers and I was able to get the server/container up and running, however I think I'm missing something with vpath, nginx and port configuration, because I'm not able to connect to my server.

Here's my Dockerfile:

```docker
FROM ubuntu:14.04
ADD . /opt/quake2
RUN apt-get update
RUN apt-get install wget curl libjpeg-turbo8 libsdl1.2debian -y
RUN wget -nv http://quake2world.net/files/quake2-quake2world.net-x86_64.tar.gz -O- | tar -zxvf - -C /opt/quake2
WORKDIR /opt/quake2
EXPOSE 27910/udp
CMD ./bin/quake2 +exec server.cfg +set dedicated 1
```

My actual question is probably this: How can I setup a dokku app to manage a non-http application with it listening on udp ports, specifically `27910/udp`.

**Comment by u2mejc** [comment]
haha I'll bite :+1:  (btw there is a comic somewhere about computer from the future, and getting quake to run on it)

I don't know when I played quake2 last, but I don't see an issue with your Dockerfile at first glance (although the older version of quetoo being downloaded every time is intense!). I would disable nginx for this app since UDP isn't supported (which kinda argues the usefulness of Dokku for quake). After that, I bet it will be working fine and you just need to get the IP address /port(s) right for the clients. Use dokku to see if there are any logs (-t tails). I think you should ask on #quetoo what the port(s) you need are, if 27910 is still in use, it wasn't clear in the 30secs of googling I did.

**Comment by michaelshobbs** [comment]
dokku does not currently support UDP dockerfiles either. i think you're probably best off to use docker directly.

**Comment by carlossless** [comment]
thanks @u2mejc, @michaelshobbs, using docker directly is what I'm doing right now, but I'm wondering since dokku is a docker container manager, if it won't interfere with my custom setup containers? Also, I like the dokku flow, and it would be awesome if it was possible to just use dokku for updating and deploying simple containers with zero additional features attached to them (like nginx vhosts and zero-downtime deployments)

**Comment by michaelshobbs** [comment]
@carlossless that totally makes sense. our current focus is mirroring Heroku functionality and thus our primary use is tcp-based web apps. Currently we support disabling nginx, running a docker container on any tcp port (not udp at the moment) and unfortunately for this use case, we don't support disabling zero downtime deployments. 

However, you can definitely do this as a plugin. I did something similar with [logspout](https://github.com/michaelshobbs/dokku-logspout).

**Comment by josegonzalez** [comment]
@carlossless You can disable nginx:

```shell
dokku nginx:disable APP
```

Next, I would try creating a plugin for something like [litl/shuttle](https://github.com/litl/shuttle) to do udp load balancing for your app, allowing you to bind to a specific socket and have zero-downtime deploys with a single, static port.

I'm closing this as it's way outside of the sort of features dokku will provide anytime soon, and is best implemented as a plugin.

**Comment by carlossless** [comment]
Awesome, thanks for the pointers @josegonzalez .

**Comment by csu** [comment]
Sorry for hijacking this thread, but what's the best/recommended way for running containers directly on Docker alongside a dokku installation? Should I run them as the `dokku` user or should I start another instance of Docker as my normal user and run them there?

**Comment by josegonzalez** [comment]
@csu mind opening another issue with your question? Will help us with prioritization.

**Comment by csu** [comment]
@josegonzalez Will do, thanks.
