### ISSUE TITLE
thought: don't try to install plugins, unless root.

### ISSUE THREAD

**Issue by leonardodino** [dokku/dokku#1768]
**running `v0.4.5`**
I came across the same problem as #1503 
`/var/lib/dokku/plugins/enabled/00_dokku-standard/install: line 16: /etc/init/dokku-redeploy.conf: Permission denied`

I was using the `sshcommand` interface where there's no sudo.

The confusing part was the cloning and everything worked fine, so I wasn't sure at which step I was, and it isn't obvious how to recover from this state. 

(what if there *where* tasks after the one that failed? impossible to tell without reading the source.)

Isn't it better to check the privileges before proceeding? and provide a helpful error, etc?

**Comment by u2mejc** [comment]
I'll +1 this, doesn't require root persay, but checking permissions first would be sweet. An overarching permissions check for the dokku command might head off other functions that might not have a solid check in place today too.

**Comment by josegonzalez** [comment]
Seems like a good idea.

**Comment by michaelshobbs** [comment]
To clarify, is this as simple as a top-level userid check on the `plugins:install` command?

**Comment by josegonzalez** [comment]
Probably. Do we *require* it to be root?

**Comment by josegonzalez** [comment]
Ideally we only require root for certain parts of the `install` hooks, and those are setup via a custom `sudoers.d` file for each command. That would allow the dokku user to run those commands without requiring sudo, and then we can just force all perms to be `dokku:dokku`.

**Comment by michaelshobbs** [comment]
We do require it for installing nginx from the ppa and writing out this service file. I don't think we want to sudo the latter. I think forcing the user to run `plugin:install` is the simplest and most concise method from a security perspective.

**Comment by josegonzalez** [comment]
Then I think clarifying that the user is `root` is best (since we assume `root` user in all cases at the moment).

**Comment by michaelshobbs** [comment]
I think there are (at least) two approaches here

1. check userid whenever `plugin:install` is called and bail with a message if we're not root
2. check userid in specific `*/install` triggers and skip (with a message) if we're not root

thoughts?

**Comment by josegonzalez** [comment]
Lets go with 1. We want the perms on all those dirs to stay root, no?
