### ISSUE TITLE
Automate the welcome page

### ISSUE THREAD

**Issue by jvanbaarsen** [dokku/dokku#1769]
I'm currently in the process of making a web shell around Dokku (https://github.com/intercity/intercity-next). One of the issues I'm running into at the moment, is that the user has to go to the browser and enter their admin key etc.

It would be great if there was a one time command that could be run to skip this step (that would run this commands: https://github.com/dokku/dokku/blob/master/contrib/dokku-installer.rb#L60

I would say this command can be called: `dokku skipwelcome` or something like that. This would then be a command that you can run once, and only if the `dokku-installer.conf` is present.

@michaelshobbs / @josegonzalez What do you think about this? Or do you think there is a better way of accomplishing this task? If we decide to implement a feature for it, I would be happy to work on that.

**Comment by josegonzalez** [comment]
If you install via the package, you can do unattended installation via [debconf](http://dokku.viewdocs.io/dokku/getting-started/install/debian/). 

Otherwise you can configure it on the cli and call a `pkill ruby`.

**Comment by jvanbaarsen** [comment]
@josegonzalez Thanks! I think the debconf will work
