### ISSUE TITLE
Dokku working on port but not on root domain

### ISSUE THREAD

**Issue by dontwork** [dokku/dokku#1772]
My dokku instance was working on domain:PORT but not on domain.

I had installed dokku without enabling custom domain support and when I had my domain ready I went about changing it... incorrectly.

I changed NO_VHOST to 0 among other things and the deploy script was showing to me that my app was deploying to my domain WITHOUT the port number on the end.

This issue was revealed to my by savant on the irc who after some debugging told me to 

`dokku config:unset APP DOKKU_NGINX_PORT`

this fixed my issue and he stated 'so while the ui said one thing, internally dokku did another'.

I'm obviously an idiot because I couldn't find any way of fixing this from googling so it does not appear to have been an issue for any one else but perhaps if NO_VHOST is 0 and DOKKU_NGINX_PORT is still set the deploy script should warn users of what is going on in the background.

**Comment by josegonzalez** [comment]
A few things we need to do:

- Update docs to show how to re-enable `VHOST` support.
- Maybe warn if we are unsetting `NO_VHOST` or setting it to `0` and there would still be no vhost support
- Detect in the url output if there is a specific port, and output it regardless of whether `NO_VHOST` isn't set to 1 or not.

@michaelshobbs related to the nginx refactor you promised me ;)

**Comment by michaelshobbs** [comment]
#1629

**Comment by michaelshobbs** [comment]
@josegonzalez I'll have time to work on this over the next few weeks. I promise :sweat_smile:

**Comment by josegonzalez** [comment]
ha

**Comment by josegonzalez** [comment]
This is done I think, right @michaelshobbs ?

**Comment by michaelshobbs** [comment]
What do you mean by done?

**Comment by josegonzalez** [comment]
I mean, we have a feature to enable/disable vhosts easily in 0.5.x, correct?

**Comment by michaelshobbs** [comment]
Yes

**Comment by josegonzalez** [comment]
So this is closable, assuming you have docs :)

**Comment by michaelshobbs** [comment]
Check the docs and make sure you're happy with them.

**Comment by josegonzalez** [comment]
Seems legit, closing :)
