### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by sevazhidkov** [dokku/dokku#1773]
The last version that Dokku is supporting - PHP 5.6.14. Heroku already announced PHP 7 support.

**Comment by blocka** [comment]
You can always use your own Dockerfile (which I do anyway since i'm a control freak)

**Comment by michaelshobbs** [comment]
You can also set the `$BUILDPACK_URL` ENV var to use the latest php buildpack

**Comment by michaelshobbs** [comment]
Latest php buildpack is now in herokuish
