### ISSUE TITLE
Automatically sanitize or warn on invalid application names

### ISSUE THREAD

**Issue by Stormsher** [dokku/dokku#1774]
Got error when trying to push my proj to dokku 

$ git push dokku master
Counting objects: 1104, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1057/1057), done.
Writing objects: 100% (1104/1104), 2.38 MiB | 2.45 MiB/s, done.
Total 1104 (delta 346), reused 0 (delta 0)
-----> Cleaning up...
-----> Building TransCRM from herokuish...
remote: repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
To dokku@nnn.nn.nn.nn:TransCRM
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@nnn.nn.nn.nn:TransCRM'

this did`t help
sudo wget -O /etc/init/docker.conf https://raw.github.com/dotcloud/docker/master/contrib/init/upstart/docker.conf
sudo service docker restart

**Comment by lacostenycoder** [comment]
I had a similar problem where I had done a dokku build command from within the dokku ssh.  Then had similar errors when trying to push my code from my local branch with git push dokku master.  Simple fix for me was to first do
```
git pull dokku master
```
In my case there were no merge conflicts so just doing 
```
git push dokku master
```
fixed my problem.  I imagine doing this would also work.

```
git push origin master --force
```

**Comment by michaelshobbs** [comment]
@Stormsher is this possibly from a plugin? I don't see that message in dokku core. Can you please provide the info requested in the contributing doc?

**Comment by josegonzalez** [comment]
Looks like it's an issue with docker itself. The name of an app *must* begin with a lowercase character.

https://github.com/docker/distribution/issues/1008

I don't think there is a good way for us to handle migrating applications, *but* we could at least sanitize everything coming into dokku first.

@Stormsher You're going to need to need to rename your app remote to `transcrm`.

**Comment by michaelshobbs** [comment]
@josegonzalez you want to `exit 1` if the app name doesn't begin with a lowercase character?

**Comment by josegonzalez** [comment]
Error and `exit 1` seems appropriate to me. We don't yet have a `rename` command, which would help fix old, broken apps.
