### ISSUE TITLE
How to upgrade to a specific version?

### ISSUE THREAD

**Issue by Epigene** [dokku/dokku#1785]
I have a problem very similar to the one discussed in issue [#1695](https://github.com/dokku/dokku/issues/1695) - I need to persist asset files across deploys containers.

Unfortunately, the solution via docker-options is not available to me since the docker version is v0.3.15 - prior to the v0.3.18 that introduced the options plugin.

I followed the upgrade guide, but ended up with dokku v0.4.x, postgres databases missing and just too much headache.

Is there a way to update dokku to a specific version (the last v0.3.x ?) or do I install the docker-options stand-alone without tinkering with dokku version?

**Comment by michaelshobbs** [comment]
To answer your specific question, you can use the `bootstrap.sh` to install. (I think)

```
    wget https://raw.githubusercontent.com/dokku/dokku/<version_tag>/bootstrap.sh
    sudo DOKKU_TAG=<version_tag> bash bootstrap.sh
```

**Comment by Epigene** [comment]
What can I expect from a successful install this way? Will existing containers continue running and new dokku components will be applied only after rebuild?

**Comment by michaelshobbs** [comment]
That would be my expectation. `0.4.x` was a major release that was not backwards compatible with many plugins and required a docker upgrade I believe. That's probably why your containers were out of whack in your previous attempt. 

Side note: I still would suggest, at some point in the relatively near future, figuring out the upgrade to `0.4.x`.

**Comment by Epigene** [comment]
Will do, thanks Michael.
