### ISSUE TITLE
pare down test suite

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#1787]
In thinking about the test suite and how to make it run faster, I'd like to propose dropping the deploy tests and only run bats tests. Given that `herokuish` now runs through all of the buildpacks in its test suite, it seems redundant that we do it as well.

Dropping those two test runs from dokku, would allow us to split up the bats test across all four of the free containers circleci provides us.

Thoughts?

**Comment by progrium** [comment]
:+1: :+1: :+1:

**Comment by u2mejc** [comment]
:+1:  :christmas_tree:

**Comment by josegonzalez** [comment]
I feel as though deploy tests have failed in the past and shown issues in pull requests, but if you're comfortable running that risk, fine by me.

**Comment by michaelshobbs** [comment]
My thinking here is that even in the unit test suite, we are deploying apps; multiple times in fact. We can also bring this functionality back very easily if we actually end up losing coverage. Another compromise is dropping the 'build herokuish from master' deploy test run and spread the unit-tests amongst 3 containers.

**Comment by josegonzalez** [comment]
Fine by me then. Ship it.
