### ISSUE TITLE
remote: nginx: [emerg] host not found in upstream 

### ISSUE THREAD

**Issue by reactima** [dokku/dokku#1806]
Having difficulties to understand why "git push dokku master" previously succeeded, failed. No code change happened. Code works well locally.

https://github.com/koajs/todo

---------------------------------------
=====> end koa-todo container output
-----> Running post-deploy
-----> Configuring koa-todo.mydomain.com...(using /var/lib/dokku/plugins/available/nginx-vhosts/templates/nginx.conf.template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
remote: nginx: [emerg] host not found in upstream "koa-todo" in /home/dokku/koa-todo/nginx.conf:16
remote: nginx: configuration file /etc/nginx/nginx.conf test failed
---------------------------------------

nginx error log is empty

Any ideas or hints are greatly appreciated

**Comment by josegonzalez** [comment]
Can you include all the information we ask for in our CONTRIBUTING.md?

**Comment by reactima** [comment]
Sorry. Will do after NY

**Comment by josegonzalez** [comment]
No worries :)

**Comment by JorgenEvens** [comment]
Steps to reproduce this issue:
```
dokku apps:create test
dokku domains:add test some.domain
```

Now try to push to any other application and nginx will find an invalid config in the `test` application.
This is caused by `dokku domains:add` generating a `nginx.conf` file without a valid upstream.

**Comment by josegonzalez** [comment]
Good catch. @michaelshobbs here's another issue for you :P

**Comment by michaelshobbs** [comment]
Should be an easy fix. I'll take a look after I get to a stopping place on this other enhancement

**Comment by reactima** [comment]
if case some one to have a look at console output for my setup

➜  ~  uname -a
Linux Ubuntu-1510-wily-64-minimal 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

➜  ~  free -m
             total       used       free     shared    buffers     cached
Mem:         32112       4527      27584        218        387       3580
-/+ buffers/cache:        559      31552
Swap:        16375          0      16375

➜  ~  docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
➜  ~

➜  ~  docker -D info
Containers: 6
Images: 56
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-19-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 31.36 GiB
Name: Ubuntu-1510-wily-64-minimal
ID: 7NRD:YJDR:KD67:KGEY:JRAW:FXQK:4FE4:OYIK:OVIO:HK5M:CFGN:GFQ3
WARNING: No swap limit support

➜  ~  docker run --rm -ti gliderlabs/herokuish:latest herokuish version
herokuish: 0.3.5
buildpacks:
  heroku-buildpack-clojure   v70
  heroku-buildpack-go        v18
  heroku-buildpack-gradle    v12
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v40
  heroku-buildpack-multi     26fa21a
  heroku-buildpack-nodejs    v86
  heroku-buildpack-php       v80
  heroku-buildpack-play      v24
  heroku-buildpack-python    v70
  heroku-buildpack-ruby      v140
  heroku-buildpack-scala     v63
  https://github.com/dokku/buildpack-nginx v5

  ➜  ~  dokku version
0.4.6

➜  ~  dokku plugin
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  mysql                1.0.0 enabled    dokku mysql service plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

**Comment by reactima** [comment]
Steps to reproduce:
- Install server from fresh Ubuntu image ;))
- Tested first found todo locally 
https://github.com/koajs/todo
- Did all basic step with keys and succeeded up to  "git push dokku master" step
- Next attempt with "git push dokku master" failed

If any other logs required, please let me know

**Comment by michaelshobbs** [comment]
@reactima can you gist up all `/home/dokku/*/nginx.conf` files? i'd like to confirm you are seeing the same thing as @JorgenEvens.

**Comment by reactima** [comment]
@michaelshobbs  please have a look
https://gist.github.com/reactima/1eafd2fe7fa5fb1c2d49

**Comment by josegonzalez** [comment]
redux-search is a different application. Did you deploy that?

**Comment by reactima** [comment]
@josegonzalez sorry. forgot to mention that redux-search build failed. so tried to use run simple example like koa-todo
https://github.com/treasure-data/redux-search

i haven't tried to re-run redux-search after first successful push of koa-todo

**Comment by reactima** [comment]
@michaelshobbs  @josegonzalez let me investigate more on weekend. i will try to find cause of problem

**Comment by josegonzalez** [comment]
Right, so redux-search failed, causing your issue. Can you quickly do a git push of *that* app and then show us the log output?

**Comment by michaelshobbs** [comment]
I think #1841 will prevent this from happening in the future as it skips the creation of `nginx.conf` if the app is not deployed.

**Comment by reactima** [comment]
redux-search git:(master) git push dokku master
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Counting objects: 509, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (222/222), done.
Writing objects: 100% (509/509), 190.21 KiB | 0 bytes/s, done.
Total 509 (delta 274), reused 508 (delta 274)
-----> Cleaning up...
-----> Building redux-search from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)

       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 5.1.1...
       Using default npm version: 3.3.12

-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)

-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)

-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)

-----> Build succeeded!
       +-- node-uuid@1.4.7
       +-- react-highlight-words@0.1.1
       `-- redux@3.0.5

-----> Discovering process types
       Default types for  -> web
-----> Releasing redux-search (dokku/redux-search:latest)...
-----> Deploying redux-search (dokku/redux-search:latest)...
-----> DOKKU_SCALE file found (/home/dokku/redux-search/DOKKU_SCALE)
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> redux-search container output:
       > redux-search@1.0.0 start /app
       > webpack-dev-server --hot --inline --config webpack.config.dev.js
       sh: 1: webpack-dev-server: not found
       npm ERR! Linux 4.2.0-19-generic
       npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
       npm ERR! node v5.1.1
       npm ERR! npm  v3.3.12
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! redux-search@1.0.0 start: `webpack-dev-server --hot --inline --config webpack.config.dev.js`
       npm ERR! spawn ENOENT
       npm ERR!
       npm ERR! Failed at the redux-search@1.0.0 start script 'webpack-dev-server --hot --inline --config webpack.config.dev.js'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the redux-search package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     webpack-dev-server --hot --inline --config webpack.config.dev.js
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls redux-search
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /app/npm-debug.log
=====> end redux-search container output
remote: Error response from daemon: Cannot kill container 3ba3460482d7056b5873f1c1718d1030e97c7d975fb09058b242ee23b66fb70e: notrunning: Container 3ba3460482d7056b5873f1c1718d1030e97c7d975fb09058b242ee23b66fb70e is not running
remote: Error: failed to kill containers: [3ba3460482d7056b5873f1c1718d1030e97c7d975fb09058b242ee23b66fb70e]
To dokku@something.com:redux-search
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@something.com:redux-search'
➜  redux-search git:(master)

**Comment by reactima** [comment]
> remote: Error response from daemon: Cannot kill container 

no running containers
~  docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
➜  ~

**Comment by josegonzalez** [comment]
So that app is just broken, but thats sort of irrelevant.

Can you do:

```shell
# destroy the app
dokku --force apps:destroy redux-search

# push the app again (should result in failure)
git push dokku master

# in the other app, make a trivial change and push it
git push dokku master
```

And tell me if you get a failed deploy on the other app?

**Comment by reactima** [comment]
@josegonzalez  

Thnx! Destroying redux-search helped. 

I did few changes in todo apps with following, commit&push. It works well.
https://github.com/koajs/todo

I've also tried to re-deployed redux-search after, and it corrupted "git push" for todo app again.
https://github.com/koajs/todo

It seems that somehow redux-search corrupts my dokku setup. redux-search "npm start" looks bad to me - running webpack server is weird from my perspective. 

    "start": "webpack-dev-server --hot --inline --config webpack.config.dev.js",
https://github.com/treasure-data/redux-search/blob/master/package.json

So I guess it cause all the mess:

-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> redux-search container output:
       > redux-search@1.0.0 start /app
       > webpack-dev-server --hot --inline --config webpack.config.dev.js
       sh: 1: webpack-dev-server: not found
       npm ERR! Linux 4.2.0-19-generic
       npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
       npm ERR! node v5.1.1
       npm ERR! npm  v3.3.12
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! redux-search@1.0.0 start: `webpack-dev-server --hot --inline --config webpack.config.dev.js`
       npm ERR! spawn ENOENT
       npm ERR!
       npm ERR! Failed at the redux-search@1.0.0 start script 'webpack-dev-server --hot --inline --config webpack.config.dev.js'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the redux-search package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     webpack-dev-server --hot --inline --config webpack.config.dev.js
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls redux-search
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /app/npm-debug.log
=====> end redux-search container output
remote: Error response from daemon: Cannot kill container 3ba3460482d7056b5873f1c1718d1030e97c7d975fb09058b242ee23b66fb70e: notrunning: Container 3ba3460482d7056b5873f1c1718d1030e97c7d975fb09058b242ee23b66fb70e is not running
remote: Error: failed to kill containers: [3ba3460482d7056b5873f1c1718d1030e97c7d975fb09058b242ee23b66fb70e]
