### ISSUE TITLE
Rails app, Procfile is used only for the web entry

### ISSUE THREAD

**Issue by flevour** [dokku/dokku#181]
Hi there,
is dokku meant to support many different process types as common Procfiles?
As far as my understanding can reach (I am still new to all of this, so sorry if I am completely out of context), the dokku bash script only runs `/start web` inside the container.
Wouldn't be appropriate to use `foreman start` so all processes in Procfile are started?

**Comment by josegonzalez** [comment]
For anyone that lands here, see our [process scaling docs](http://dokku.viewdocs.io/dokku/deployment/process-management/).
