### ISSUE TITLE
[Help] Exposing port to the public

### ISSUE THREAD

**Issue by Derimagia** [dokku/dokku#1816]
I'm having issues exposing a port to be public, anyone think they can help? I'm obviously doing something wrong. I"m trying to expose the port "25565". 

I'm testing with a Minecraft Docker (Found here: https://github.com/dlord/minecraft-docker/tree/master/vanilla) - Dockerfile I created is http://pastebin.com/qXrr2Kec

It's starting up without any issues. I tried changing DOKKU_DOCKERFILE_PORT and DOKKU_NGINX_PORT.. http://pastebin.com/QG1nBNiU

When I run docker port It's telling me "Error: No public port '25565/tcp' published for fd8919026c0e" I also tried to run "dokku docker-options:add minecraft run "-P"" to try to expose the ports through docker as well. 

Not sure if the container type is supposed to be "web" - Docker ps: http://pastebin.com/tRWD6NDV

Any toughts?

**Comment by josegonzalez** [comment]
When reporting issues, the dokku team will need more information to help debug problems. If possible please follow the following template:

    Description of problem:


    Output of the following commands

    - `uname -a`:
    - `free -m`:
    - `docker version`:
    - `docker -D info`:
    - `docker run -ti gliderlabs/herokuish:latest herokuish version`:
    - `dokku version`:
    - `dokku plugin`:
    - `docker inspect CONTAINER_ID` (if applicable):
      (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
    - `cat /home/dokku/<app>/nginx.conf` (if applicable):
    - Link to the exact repository being deployed (if possible/applicable):
    - If a deploy is failing:
      - the type of application being deployed (node, php, python, ruby, etc.)
      - whether or not you have a `Dockerfile` in the root of your repository
      - if using buildpacks, which custom buildpacks are in use
    - Output of failing dokku commands after running `dokku trace on`
      (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

    Environment details (AWS, VirtualBox, physical, etc.):

    How was dokku installed?:

    How reproducible:


    Steps to Reproduce:
    1.
    2.
    3.

    Actual Results:


    Expected Results:


    Additional info:

**Comment by josegonzalez** [comment]
The above is our standard notice. Note that - off the bat at least - dokku doesn't support load-balancing TCP or UDP ports. I'm not sure why your particular commands failed - didn't even know `docker port` was a thing - but that might be pertinent. The data above will definitely help us get to the root cause though :)

**Comment by Derimagia** [comment]
I'm sure I'm just missing something silly. I was just using docker port to debug. What is the approproiate way to expose a non-web port when using a Dockerfile through dokku? Proxying through nginx?

Here's all the info you asked for:

Description:

>See above

- `uname -a`: 

>Linux HOSTNAME 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

- `free -m`:

>total       used       free     shared    buffers     cached
>Mem:          3952       3582        369          0        319       2396
>-/+ buffers/cache:        866       3085
>Swap:          953          2        951
- `docker version`:

>Client:
> Version:      1.9.1
> API version:  1.21
> Go version:   go1.4.2
> Git commit:   a34a1d5
> Built:        Fri Nov 20 13:12:04 UTC 2015
> OS/Arch:      linux/amd64
>
>Server:
> Version:      1.9.1
> API version:  1.21
> Go version:   go1.4.2
> Git commit:   a34a1d5
> Built:        Fri Nov 20 13:12:04 UTC 2015
> OS/Arch:      linux/amd64
 
- `docker -D info`:
>Containers: 7
>Images: 63
>Server Version: 1.9.1
>Storage Driver: aufs
> Root Dir: /var/lib/docker/aufs
> Backing Filesystem: extfs
> Dirs: 77
> Dirperm1 Supported: false
>Execution Driver: native-0.2
>Logging Driver: json-file
>Kernel Version: 3.13.0-32-generic
>Operating System: Ubuntu 14.04.1 LTS
>CPUs: 8
>Total Memory: 3.86 GiB
>Name: darksupply
>ID: WTNE:DUJX:RI2D:CBKR:KYWU:E5NZ:2HR2:PPMF:VEYR:CAKI:3DB7:7DEB
>WARNING: No swap limit support

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:

>herokuish: 0.3.7
>buildpacks:
> heroku-buildpack-clojure   v73
> heroku-buildpack-go        v22
> heroku-buildpack-gradle    v16
> heroku-buildpack-grails    v19
> heroku-buildpack-java      v41
> heroku-buildpack-multi     v1.0.0
> heroku-buildpack-nodejs    v87
> heroku-buildpack-php       v90
> heroku-buildpack-play      v24
> heroku-buildpack-python    v74
> heroku-buildpack-ruby      v141
> heroku-buildpack-scala     v63
> buildpack-nginx            v5
  
- `dokku version`:
>0.4.9

- `dokku plugin`:
>00_dokku-standard    0.4.0 enabled    dokku core standard plugin
>20_events            0.4.0 enabled    dokku core events logging plugin
>apps                 0.4.0 enabled    dokku core apps plugin
>backup               0.4.0 enabled    dokku core backup plugin
>build-env            0.4.0 enabled    dokku core build-env plugin
>certs                0.4.0 enabled    dokku core certificate management plugin
>checks               0.4.0 enabled    dokku core checks plugin
>common               0.4.0 enabled    dokku core common plugin
>config               0.4.0 enabled    dokku core config plugin
>docker-options       0.4.0 enabled    dokku core docker-options plugin
>domains              0.4.0 enabled    dokku core domains plugin
>enter                0.4.0 enabled    dokku core enter plugin
>git                  0.4.0 enabled    dokku core git plugin
>logs                 0.4.0 enabled    dokku core logs plugin
>named-containers     0.4.0.1 enabled    dokku core named containers plugin
>nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
>plugin               0.4.0 enabled    dokku core plugin plugin
>ps                   0.4.0 enabled    dokku core ps plugin
>redis                1.0.0 enabled    dokku redis service plugin
>shell                0.4.0 enabled    dokku core shell plugin
>tags                 0.4.0 enabled    dokku core tags plugin

- `docker inspect CONTAINER_ID` (if applicable):
>  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
>  [
>{
>    "Id": "c6aa9e0d1544146ef83ba13cb2c9f619476c606932a9a00c6056941109c85168",
>    "Created": "2016-01-03T20:56:15.347017769Z",
>    "Path": "/usr/local/bin/minecraft",
>    "Args": [
>        "run"
>    ],
>    "State": {
>        "Status": "running",
>        "Running": true,
>        "Paused": false,
>        "Restarting": false,
>        "OOMKilled": false,
>        "Dead": false,
>        "Pid": 2984,
>        "ExitCode": 0,
>        "Error": "",
>        "StartedAt": "2016-01-03T20:56:16.336326462Z",
>        "FinishedAt": "0001-01-01T00:00:00Z"
>    },
>    "Image": "47f35b4c50b78c7d8f03043c76c0a952923c8ee68cb5dc82ac5ab15b82e3aecd",
>    "ResolvConfPath": "/var/lib/docker/containers/c6aa9e0d1544146ef83ba13cb2c9f619476c606932a9a00c6056941109c85168/resolv.conf",
>    "HostnamePath": "/var/lib/docker/containers/c6aa9e0d1544146ef83ba13cb2c9f619476c606932a9a00c6056941109c85168/hostname",
>    "HostsPath": "/var/lib/docker/containers/c6aa9e0d1544146ef83ba13cb2c9f619476c606932a9a00c6056941109c85168/hosts",
>    "LogPath": "/var/lib/docker/containers/c6aa9e0d1544146ef83ba13cb2c9f619476c606932a9a00c6056941109c85168/c6aa9e0d1544146ef83ba13cb2c9f619476c606932a9a00c6056941109c85168-json.log",
>    "Name": "/minecraft.web.1",
>    "RestartCount": 0,
>    "Driver": "aufs",
>    "ExecDriver": "native-0.2",
>    "MountLabel": "",
>    "ProcessLabel": "",
>    "AppArmorProfile": "",
>    "ExecIDs": null,
>    "HostConfig": {
>        "Binds": null,
>        "ContainerIDFile": "",
>        "LxcConf": [],
>        "Memory": 0,
>        "MemoryReservation": 0,
>        "MemorySwap": 0,
>        "KernelMemory": 0,
>        "CpuShares": 0,
>        "CpuPeriod": 0,
>        "CpusetCpus": "",
>        "CpusetMems": "",
>        "CpuQuota": 0,
>        "BlkioWeight": 0,
>        "OomKillDisable": false,
>        "MemorySwappiness": -1,
>        "Privileged": false,
>        "PortBindings": {},
>        "Links": null,
>        "PublishAllPorts": false,
>        "Dns": [],
>        "DnsOptions": [],
>        "DnsSearch": [],
>        "ExtraHosts": null,
>        "VolumesFrom": null,
>        "Devices": [],
>        "NetworkMode": "default",
>        "IpcMode": "",
>        "PidMode": "",
>        "UTSMode": "",
>        "CapAdd": null,
>        "CapDrop": null,
>        "GroupAdd": null,
>        "RestartPolicy": {
>            "Name": "no",
>            "MaximumRetryCount": 0
>        },
>        "SecurityOpt": null,
>        "ReadonlyRootfs": false,
>        "Ulimits": null,
>        "LogConfig": {
>            "Type": "json-file",
>            "Config": {}
>        },
>        "CgroupParent": "",
>        "ConsoleSize": [
>            0,
>            0
>        ],
>        "VolumeDriver": ""
>    },
>    "GraphDriver": {
>        "Name": "aufs",
>        "Data": null
>    },
>    "Mounts": [],
>    "Config": {
>        "Hostname": "c6aa9e0d1544",
>        "Domainname": "",
>        "User": "",
>        "AttachStdin": false,
>        "AttachStdout": false,
>        "AttachStderr": false,
>        "ExposedPorts": {
>            "25565/tcp": {}
>        },
>        "Tty": false,
>        "OpenStdin": false,
>        "StdinOnce": false,
>        "Env": [
>            "CURL_CONNECT_TIMEOUT=5",
>            "CURL_TIMEOUT=30",
>            "DOKKU_APP_RESTORE=1",
>            "DOKKU_DOCKERFILE_PORT=25565",
>            "DOKKU_NGINX_PORT=25565",
>            "PORT=25565",
>            "DYNO='web.1'",
>            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>            "LANG=C.UTF-8",
>            "JAVA_VERSION=7u91",
>            "JAVA_DEBIAN_VERSION=7u91-2.6.3-1~deb8u1",
>            "MINECRAFT_HOME=/opt/minecraft",
>            "MINECRAFT_OPTS=-server -Xmx1024m -XX:MaxPermSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC",
>            "MINECRAFT_SRC=/usr/src/minecraft",
>            "MINECRAFT_EULA=true",
>            "DEFAULT_OP=derimagia",
>            "MINECRAFT_VERSION=1.8.9"
>        ],
>        "Cmd": [
>            "run"
>        ],
>        "Image": "dokku/minecraft:latest",
>        "Volumes": null,
>        "WorkingDir": "",
>        "Entrypoint": [
>            "/usr/local/bin/minecraft"
>        ],
>        "OnBuild": null,
>        "Labels": {},
>        "StopSignal": "SIGTERM"
>    },
>    "NetworkSettings": {
>        "Bridge": "",
>        "SandboxID": "59d61322b046e496558bfc20e788917eba712b58968ea38ab5fa7c93da80d284",
>        "HairpinMode": false,
>        "LinkLocalIPv6Address": "",
>        "LinkLocalIPv6PrefixLen": 0,
>        "Ports": {
>            "25565/tcp": null
>        },
>        "SandboxKey": "/var/run/docker/netns/59d61322b046",
>        "SecondaryIPAddresses": null,
>        "SecondaryIPv6Addresses": null,
>        "EndpointID": "305a74e731223a8fa162b244a48572267ab33bc2c20dfe40f3e51090ea203d17",
>        "Gateway": "XX.XX.XX.X",
>        "GlobalIPv6Address": "",
>        "GlobalIPv6PrefixLen": 0,
>        "IPAddress": "XX.XX.X.X",
>        "IPPrefixLen": 16,
>        "IPv6Gateway": "",
>        "MacAddress": "02:42:ac:11:00:03",
>        "Networks": {
>            "bridge": {
>                "EndpointID": "305a74e731223a8fa162b244a48572267ab33bc2c20dfe40f3e51090ea203d17",
>                "Gateway": "XXX.XX.XX.X",
>                "IPAddress": "XXX.XX.XX.X",
>                "IPPrefixLen": 16,
>                "IPv6Gateway": "",
>                "GlobalIPv6Address": "",
>                "GlobalIPv6PrefixLen": 0,
>                "MacAddress": "XX:XX:XX:XX:XX:XX"
>            }
>        }
>    }
>}
>]
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
>server {
>  listen      [::]:25565;
>  listen      25565;
>  server_name minecraft.HOSTNAME.com ;
>  access_log  /var/log/nginx/minecraft-access.log;
>  error_log   /var/log/nginx/minecraft-error.log;
>
>  location    / {
>
>    gzip on;
>    gzip_min_length  1100;
>    gzip_buffers  4 32k;
>    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
>    gzip_vary on;
>    gzip_comp_level  6;
>
>    proxy_pass  http://minecraft;
>    proxy_http_version 1.1;
>    proxy_set_header Upgrade $http_upgrade;
>    proxy_set_header Connection upgrade;
>    proxy_set_header Host $http_host;
>    proxy_set_header X-Forwarded-Proto $scheme;
>    proxy_set_header X-Forwarded-For $remote_addr;
>    proxy_set_header X-Forwarded-Port $server_port;
>    proxy_set_header X-Request-Start $msec;
>  }
>  include /home/dokku/minecraft/nginx.conf.d/*.conf;
>}
>upstream minecraft {
>  server XXX.XX.X.X:25565;
>}

- Link to the exact repository being deployed (if possible/applicable):
>See above

- Environment details (AWS, VirtualBox, physical, etc.):
> VPS, Trying out CloudAtCost

- How was dokku installed?:
> Normal script

**Comment by josegonzalez** [comment]
As I mentioned before, dokku does not handle proxying of TCP/UDP requests, only HTTP. This is due to our reliance on nginx as a method for proxying things.

In your case, I was able to deploy by doing the following:

```shell
mkdir minecraft-test
cd minecraft-test
# get rid of those pesky windows characters
wget -qO- http://pastebin.com/raw/qXrr2Kec | tr -d '\r' > Dockerfile
git init
git add .
git commit -m "Initial commit"
# dokku.me is my dokku test host
git remote add dokku dokku@dokku.me:minecraft-test
```

Then on the remote host:

```shell
# expose the internal tcp port
dokku docker-options:add minecraft-test deploy "-P"
dokku ps:rebuild minecraft-test
docker inspect --format '{{ .NetworkSettings.Ports }}' 6311ce165c6b
# outputs: map[25565/tcp:[{0.0.0.0 32768}]]
# the port is 32768
```

I can telnet to that port from my local machine:

```
 $ telnet dokku.me 32768
Trying 104.236.52.202...
Connected to dokku.me.
Escape character is '^]'.
```

Note that if I redeploy, I get a different container:

```shell
docker inspect --format '{{ .NetworkSettings.Ports }}' 550127d8b8d1
# outputs: map[25565/tcp:[{0.0.0.0 32769}]]
# the port is 32769
```

The ports do not stay the same because of our support for zero-downtime deploys.

Dokku does not currently have plans to support TCP-based load-balancing, as our primary objective is to make web-application deployment awesome. That isn't to say we won't support it in the future, just that we won't support it now.

If you'd like to make a PR to somehow disable zero-downtime deploys and persist tcp/udp ports across deploys as a result, awesome. You may also try and replace the `nginx-vhosts` plugin with something like a haproxy plugin.

**Comment by Derimagia** [comment]
@josegonzalez Thanks for the information.

For those who are having the same issue as me I went the haproxy approach to test this out.

Enable this plugin:
https://github.com/256dpi/dokku-haproxy

Then make haproxy load balance the port through tcp.

>dokku ports:add minecraft 25565 web 25565

A bit of a shame that dokku doesn't allow this natively but I understand it's focused towards web-application deployment.

**Comment by josegonzalez** [comment]
Yeah, kind of annoying. I sort of wish we could just switch to haproxy, but seeing as how numerous users seem to use/abuse the nginx configuration customization, I doubt that will be easily possible (it's also a bit harder to tune...).

Maybe in a future release? There is an RFC open to update the nginx integration, might be worth putting in your two cents there :)

**Comment by Derimagia** [comment]
Which RFC are you referring to? I'll take a look at it and chime in.

**Comment by josegonzalez** [comment]
#1629
