### ISSUE TITLE
Upstream not configureable/templatable

### ISSUE THREAD

**Issue by wzrdtales** [dokku/dokku#1821]
Quick question, currently it is not possible to add specific settings like stick, ip_hash and so on to the upstream block. As of https://github.com/dokku/dokku/blob/a2ccbcbbfbdd41b03fb623c1434f262f5bb030c7/plugins/nginx-vhosts/functions#L228-L236 this is really just a list and a static block.

Are there already plans to support this block also in a template?

**Comment by josegonzalez** [comment]
No real plans. You may want to comment on #1629 as to what you want to see happen here.
