### ISSUE TITLE
Create a plugin that runs certain commands after deployment

### ISSUE THREAD

**Issue by jvanbaarsen** [dokku/dokku#1824]
When you deploy  a Ruby on Rails application, and you have database changes, you need to migrate those, I can imagine that for certain other tech stacks "After deploy commands" are also common.

What do you think about a plugin that looks for a `after_deploy.sh` file in the `/app` directory, and if that file is present, run it. So you can have all kind of after_deploy code in there.

I see it working kinda the same as the `HEALTH_CHECK` file.

Looking forward to hear what you think.

**Comment by Vaultman** [comment]
For this kind of tasks I successfully using this plugin - https://github.com/michaelshobbs/dokku-app-predeploy-tasks

**Comment by jvanbaarsen** [comment]
@Vaultman But that requires you to do 2 deploys right? One to do all the before_deploy stuff, and then deploy again with your new app code?

**Comment by Vaultman** [comment]
Nono, just one. In my Procfile i have a 
```
web: ...
worker: ...
migration: bundle exec rake db:migrate RAILS_ENV=production
```

and added `migration=0` to my SCALE file. When I deploy, migrations are run just after `-----> Injecting App Task Runner ...` step.

**Comment by jvanbaarsen** [comment]
Ah ok, that sounds like what I mean. @michaelshobbs / @josegonzalez Would you consider adding this to either the official plugin set, or to the core of Dokku?

**Comment by josegonzalez** [comment]
Is this before the app starts?

**Comment by Vaultman** [comment]
@josegonzalez yes

**Comment by josegonzalez** [comment]
Could someone go through these buildpacks and see what the current built-in way to do this is?

```
heroku-buildpack-clojure
heroku-buildpack-go
heroku-buildpack-gradle
heroku-buildpack-grails
heroku-buildpack-java
heroku-buildpack-multi
heroku-buildpack-nodejs
heroku-buildpack-php
heroku-buildpack-play
heroku-buildpack-python
heroku-buildpack-ruby
heroku-buildpack-scala
```

As an alternative, what if we provided a buildpack that executed extra commands, and let users chain their buildpacks somehow?

/cc @michaelshobbs since the plugin mentioned is yours.

**Comment by jvanbaarsen** [comment]
@josegonzalez I now for heroku-buildpack-ruby that there is no build-in-way of doing it. The others I have to check, will do later tonight, or tomorrow

**Comment by josegonzalez** [comment]
Note: most/all packages will drop any build tools, so they won't be useful in post-executable scenarios. A good example is the golang buildpack, which removes the go tool after the compile step.

**Comment by michaelshobbs** [comment]
@jvanbaarsen why does this plugin need to be merged into the official set?

@josegonzalez the buildpacks themselves don't support this as far as I know. i think languages/frameworks like ruby/rails and node have built-in things like deploy callbacks (maybe chef only?) and npm supports scripts in `package.json` (https://docs.npmjs.com/misc/scripts)

**Comment by jvanbaarsen** [comment]
@michaelshobbs Because I feel like this should be part of either the official plugin set, or the core feature set. (It feels like a core feature).

**Comment by michaelshobbs** [comment]
It's not been a widely requested feature in my experience. Hence my reluctance to include it.

**Comment by josegonzalez** [comment]
Personally I'd rather each buildpack do it in the best way for that language/framework, and maybe we can help do that upstream for heroku instead of have something dokku-specific.

Whenever someone goes through the above list, I'll update my comment to include what hooks we have available.

**Comment by madflow** [comment]
From my little experience with Heroku I came across the ```postdeploy``` command im ```app.json```.

https://devcenter.heroku.com/articles/app-json-schema
https://devcenter.heroku.com/articles/setting-up-apps-using-the-heroku-platform-api#post-deployment-scripts

Is this out of scope for dokku to be "like" Heroku?

**Comment by josegonzalez** [comment]
That's actually probably our best bet. What else would we like/need to support from that `app.json file?

**Comment by jvanbaarsen** [comment]
@josegonzalez In the ruby buildpack there is no support for app.json, so it looks like it is a platform feature of Heroku.

**Comment by madflow** [comment]
@josegonzalez I just did a quick test with "postdeploy" added to nodejs buildpack without the "Button" Deployment (git push) - the app.json file is being ignored on heroku. So this is just for the "Button" Deployment. Sorry for any confusion caused.

**Comment by michaelshobbs** [comment]
While the buildpacks ignore it, the platform (Heroku or dokku in our case) could support it. I think that's where @josegonzalez was going. (Please correct me if I'm wrong)

I'd be interested in digging more into supporting the `app.json` functionality.

**Comment by jvanbaarsen** [comment]
@madflow thanks for checking :-)
@michaelshobbs Will that also include all the ENV var stuff? Wouldn't that make the feature way to complex for a first pass? WHat do you think about just supporting this:

```json
before_deploy: {
  exec: "Your command"
},
after_deploy: {
  exec: "Your command"
}
```

Or maybe even support multiple execs, but mainly just keep it simple with just two hooks.

**Comment by michaelshobbs** [comment]
I'd need to look further into the full schema but getting the config plugin to parse that json would be fairly trivial.

**Comment by jvanbaarsen** [comment]
@michaelshobbs Ok :-) If I can help, let me know!

**Comment by michaelshobbs** [comment]
What do we want to call this plugin? I'm not a fan of [michaelshobbs/dokku-app-predeploy-tasks](https://github.com/michaelshobbs/dokku-app-predeploy-tasks). So someone else name it please. :stuck_out_tongue_winking_eye:

**Comment by jvanbaarsen** [comment]
dokku-apphooks? xD

**Comment by michaelshobbs** [comment]
Actually, I'm not certain it needs to be a standalone plugin. We can probably just support `app.json` in the current plugin suite.

**Comment by michaelshobbs** [comment]
I'm leaning towards adding `jq` as a dokku dependency for this. It would make the implementation pretty easy but I'm sure how that might impact SUSE and Debian installations. 

An alternative might be something like this: https://github.com/dominictarr/JSON.sh

@josegonzalez thoughts here?

**Comment by jvanbaarsen** [comment]
@michaelshobbs Quickly looking through the source of JQ, is looked like it is a C app, which needs to be compiled, while JSON.sh is just a bash script. Without thinking to much about it, I would lean towards the simple Bash script

**Comment by michaelshobbs** [comment]
@jvanbaarsen if we go the `jq` route we would install it via apt and not compile it.

**Comment by josegonzalez** [comment]
We don't do SUSE packaging - though if someone wants to PR that... - so I don't think that should stop us.

We'd use the packaged version, which I think is fine.

I don't want to add new hooks to the `app.json` schema for lulz. Can someone investigate that and see if it's heroku's pipeline to support tasks outside of buildpacks?

**Comment by michaelshobbs** [comment]
It is in their pipeline when using `app.json`. See here: https://devcenter.heroku.com/articles/app-json-schema#scripts

**Comment by josegonzalez** [comment]
> The postdeploy script is run once, after the app is created and not on subsequent deploys to the app

**Comment by michaelshobbs** [comment]
Also, for the record I am suggesting we build support for Heroku's `app.json` as-is. So that means supporting `ENV`, `scripts.postdeploy` and potentially `addons` to auto install and configure an official storage plugin under the `dokku` github org.

**Comment by josegonzalez** [comment]
Yeah but that doesn't solve this particular issue.

**Comment by michaelshobbs** [comment]
What? The title is "... runs certain commands *after deployment*" This would do that for sure.

**Comment by michaelshobbs** [comment]
Oh you're referring to the bit that says "and not on subsequent deploys to the app", yea?

**Comment by josegonzalez** [comment]
Yeah. Us reusing that for this issue is no good. But sure, we could do it for first deploys.

**Comment by michaelshobbs** [comment]
Yeah that's less compelling then....that seems dumb to only run that script on the first deploy. Must have something to do with their platform implementation. 

Given this quote, it could be inferred that they will be working on extending this in the future. 
> (object, optional) A key-value object specifying scripts or shell commands to execute at different stages in the build/release process. Currently, postdeploy is the only supported script.

In any case, we could introduce `dokku-app.json` that allows for `predeploy` and `postdeploy` tasks. Thoughts?

**Comment by josegonzalez** [comment]
I don't want to introduce another file for just dokku. Are there any other "open" file formats that do this?

Is anyone on friendly terms with a heroku developer that works on the `app.json` format? If they can just say "yeah we're going to use `scripts.derp` for post-deploy tasks that always occur", that would be really all we need.

**Comment by michaelshobbs** [comment]
Are you asking if is there is a common way to define how to deploy an app regardless of the language/framework? Isn't that what Heroku (and arguable we) are doing here?

**Comment by michaelshobbs** [comment]
I think we have two useful options here:

- We could support `app.json` and overload it's functionality a bit but compensate with upfront documentation of how we're differing from Heroku. (This could cause issues with users that deploy to both heroku and dokku but only if they were using the `deploy to heroku` button as that's the only time when heroku seems to read that file
- We introduce something like `dokku-app.json` and do our own thing; using heroku's `app.json` as inspiration

**Comment by josegonzalez** [comment]
How about this:

- We use the heroku `app.json` format as is
- We add support for a `script.dokku-prerelease` task. We can then define our own semantics around that hook, and if it maps to a future heroku hook, we'll switch to that (or deprecate our own). This allows people to use dokku while not trampling over the heroku `app.json` schema. I seriously doubt they'd use the `dokku-` prefix :)

Thoughts?

**Comment by michaelshobbs** [comment]
I like it. I'd even further clean it up to look like `script.dokku.<phase>`. (I don't like dashes in my json identifiers :P)

**Comment by josegonzalez** [comment]
Heh okay.

If someone wants to take a crack at this, would be great. The only extensions for now would be what @michaelshobbs proposed, and at some later date we can look at other things, like scheduling tasks, or setting config vars past the first deploy.

**Comment by josegonzalez** [comment]
Note: I really think we could/should make this the first non-bash plugin and write it in python.

**Comment by michaelshobbs** [comment]
I'll take a stab at it right now since I have time. I'm not sure I agree with making this a **new** plugin as `app.json` seems to be just another data input to the already functional plugin suite. 

Off the top of my head - app.json sections and appropriate plugins
`scripts.dokku.*` - `00_dokku-standard` (implemented in appropriately named phase plugn triggers)
`ENV.*` - `config`
`buildpacks` -  `00_dokku-standard` (implemented in pre-build phase plugn trigger)

potential future functionality
`image` - `00_dokku-standard` (implemented in build command)
`addons` - this could be a new plugin that does a `plugn install` and appropriate config calls

The biggest change for the initial pass (in my mind) will be the json parsing but we can do that with `jq` or [this JSON.sh project](https://github.com/dominictarr/JSON.sh). 

For the record, I'm fine with a plugin being written in python but this feature will reach all over dokku functionality. That's why I **disagree** that this is a good candidate for python.

**Comment by josegonzalez** [comment]
Fine by me (though I was really hoping you'd get to the nginx thing first ;) )

**Comment by michaelshobbs** [comment]
Yeah I know. That nginx plugin is a mess...

**Comment by josegonzalez** [comment]
Closing as there is a PR open.

**Comment by josegonzalez** [comment]
For future reference, the python buildpack supports `bin/pre_compile` and `bin/post_compile`.
