### ISSUE TITLE
[question] How to run tests when files change outside Vagrant

### ISSUE THREAD

**Issue by jvanbaarsen** [dokku/dokku#1833]
How can I run changes I made on my local machine, in the vagrant machine? I know the /vagrant folder contains all my files, but since vagrant has Dokku installed from the latest release, this is not picking up my changes.

Wondering how you run tests quickly.

**Comment by michaelshobbs** [comment]
```
$ vagrant ssh
$ sudo su -
$ cd ~/dokku
$ make lint copyfiles
```

The `copyfiles` make target is the real answer to your question. This also assumes you followed the docs on how to setup tests. Let me know if you have any other questions.

**Comment by jvanbaarsen** [comment]
After some source diving I did find the copyfiles target , but forgot to close this issue. Thanks :dancer:
