### ISSUE TITLE
Automating last step of setup?

### ISSUE THREAD

**Issue by MichaelJCole** [dokku/dokku#1850]
Hey, I wanted to automate the last setup step (the web form).

```
# Finish dokku install
DOKKU=app.example.com
IP=`dig +short $DOKKU | awk '{ print ; exit }'`
KEYS=`curl http://$IP | grep -Po "<textarea[^>]*>\K(.+?)</textarea>" | sed "s|</textarea>||"`
curl -F vhost=true -F hostname=example.com -F keys="$KEYS" http://$IP/setup
```

Is there a better way to do this?  Thanks!

**Comment by josegonzalez** [comment]
If installing via the `bootstrap.sh` or with just the debian package, you can use [debconf](http://dokku.viewdocs.io/dokku/getting-started/install/debian/#unattended-installation) to manage those requirements. This will allow you to skip the web installer and simply start using dokku.

**Comment by MichaelJCole** [comment]
Awesome, thanks!  I'll try this for DigitalOcean.  I think it sets the keyfile.

```
sudo echo "dokku dokku/web_config boolean false" | debconf-set-selections
sudo echo "dokku dokku/vhost_enable boolean true" | debconf-set-selections
sudo echo "dokku dokku/hostname boolean true" | debconf-set-selections
```
