### ISSUE TITLE
Can't mount persistent storage

### ISSUE THREAD

**Issue by yazinsai** [dokku/dokku#1853]
Following [this guide](http://blog.michelemattioni.me/2015/05/21/hosting-wordpress-with-dokku-on-digital-ocean/), I used the below commands to permanently store the contents of my `wp-content` folder on my host server:

```shell
dokku docker-options:add myblog run "-v /opt/myblog/wp-content/plugins:/app/wp-content/plugins"
```

.. followed by a `dokku ps:rebuild myblog`.

However, when I run `docker inspect containerID`, I see:

```json
...
"Mounts": [],
...
```

Also, when I upload a file to the blog via wordpress, I don't see it in `/opt/myblog` .. What am I doing wrong?

**Comment by michaelshobbs** [comment]
You'll want to use `deploy` as the phase and not `run`. The `run` phase corresponds to the `dokku run` command.

**Comment by yazinsai** [comment]
Works great, thanks @michaelshobbs !
