### ISSUE TITLE
Custoim nginx.conf.template still used after it has been deleted

### ISSUE THREAD

**Issue by craigbeck** [dokku/dokku#1857]
Dokku appears to copy the `nginx.confg.template` to the host's `/home/dokku/appname` directory. When the `nginx.conf.template` file is removed from the app's repository, Dokku continues to generate custom `nginx.conf` from the template.

**Comment by josegonzalez** [comment]
This is a bit delicate, as the way this is handled is by copying from the container to the repo if possible. We should probably remove this after the fact if it wasn't already on disk.

**Comment by craigbeck** [comment]
Maybe delete it before trying to copy from container



—

**Comment by josegonzalez** [comment]
No, because we support users creating the file manually outside of the container. Quite tricky, we'd need to keep track of the state of that file.

@michaelshobbs might be worth *not* supporting having it on disk beforehand, and requiring custom templates be inside of the deployed app...

**Comment by mmerickel** [comment]
Maybe you could copy the file to a different name and update a link if and only if the user hasn't already created a manual one. Cheap state-keeping trick I guess.

**Comment by michaelshobbs** [comment]
Yeah we've been pretty liberal with the use cases we support in the `nginx-vhosts` plugin. Feel free to add opinions to #1629

**Comment by craigbeck** [comment]
+1 for only using templates found in container repository.

**Comment by josegonzalez** [comment]
From my functional spec:

> If the template is copied from within the container into the app dir, we remove it after we use it. This will allow users to revert back to defaults.
> Deprecate setting proxy conf in app dir. If a user wants to configure it, it seems to me like it's an application level dependency, and thus should be shipped with it.

We may just completely drop setting the conf from the host app directory (up to @michaelshobbs) but any work for this is already underway in #1629. Thanks for reporting!

**Comment by michaelshobbs** [comment]
We will only pull from the app image in future releases
