### ISSUE TITLE
Nginx JSON Caching ?

### ISSUE THREAD

**Issue by hhff** [dokku/dokku#1861]
Hi All!

I'm just noticing some strange behavior in a JSON API I've got hosted on Dokku.

I don't have any caching in my API - but the strange behavior appears to be cache related, so I'm guessing there's some caching on the Nginx side. 

Is that correct?  I noticed [this](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.ssl.conf.template#L20) location block in the SSL Template .  Is there an easy way to bust that cache?

**Comment by michaelshobbs** [comment]
We're not enabling nginx caching and it is false by default.

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache

**Comment by josegonzalez** [comment]
You are probably setting cache headers in your app accidentally. Dokku doesn't set any caching at all except for ssl session caching, which is [unrelated to your issue](http://www.peterbe.com/plog/ssl_session_cache-ab).

**Comment by hhff** [comment]
Thanks guys, you're right, I was tripping.  Just wanted to double check!! :heart:

**Comment by josegonzalez** [comment]
Don't fall!

**Comment by hhff** [comment]
neverrrrrr
