### ISSUE TITLE
ipv6 test seems to be broken

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#1865]
ref: #1863 

A typo was introduced in [this commit](https://github.com/dokku/dokku/commit/467264d31f929c13134ecd95eed08cc0ef99eded#diff-24a947d0d17068c3d22fbc3fb60fa554) (thanks @josegonzalez :stuck_out_tongue_winking_eye:) and the test still passed.

**Comment by michaelshobbs** [comment]
It looks like this was actually introduced when created the ability to use nginx without a VHOST; https://github.com/dokku/dokku/commit/3e18d9aff9cae247f6cf1436e125dfd248bfcaa7

So if we don't have a global vhost file, we externally bind the container regardless of the contents of `/home/dokku/HOSTNAME`.

Not sure there is anything to do here at the moment. The entire functionality of the vhost plugin and external port binding will be reworked per #1629 (pending @josegonzalez's comments)

**Comment by josegonzalez** [comment]
@michaelshobbs closing this, but also I left my comments on the nginx issue.
