### ISSUE TITLE
Options requests are extremely slow

### ISSUE THREAD

**Issue by terion-name** [dokku/dokku#1866]
I have a strange issue.
On digital ocean (dokku one-click app), PHP application, using default heroku php buildpack with nginx. Simple and regular.
App is used in CORS, so it accepts options-preflight requests (handled by application).
And these requests are running about 55-59 seconds and sometimes fail with 504 if exceed 60s. While GET requests run normally (well, 150ms latency is not blazingly fast, but let's assume this is ok).

![2016-01-15 03 48 18](https://cloud.githubusercontent.com/assets/1060205/12343320/406a32a4-bb3b-11e5-9d2e-b0cabbd02546.png)

OPTIONS request detailed:
![2016-01-15 03 27 29](https://cloud.githubusercontent.com/assets/1060205/12343183/2691f7d2-bb3a-11e5-8831-c4048a676317.png)

This is not an application problem: app timing is good.
![2016-01-15 03 27 06](https://cloud.githubusercontent.com/assets/1060205/12343151/e5a11a78-bb39-11e5-9dfc-a785c73aba00.png)

Also it doesn't seem to be a problem with container's internal nginx (from buildpack), with apache everything is the same.

So it seems to be a problem somewhere between frontend nginx and a container.

Any ideas on this? I can't even imagine where to inspect.
There was a ticket in issues about iptables problem, can this be related?

**Comment by josegonzalez** [comment]
Basically this is a problem of tuning the nginx config that is outside of the container. We don't change the defaults, so its up to you to figure out what is causing this.

Note, here is my unscientific test against a cakephp app where I send OPTIONS request to the host (it's a DO 512MB droplet):

```
jose@mactaku:~  $ curl -X OPTIONS http://playground.dokku.me --include
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 15 Jan 2016 02:19:24 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/7.0.1
X-DEBUGKIT-ID: 290d1c77-5f89-45af-b2ed-7dd03c762140

real	0m0.112s
user	0m0.005s
sys	0m0.005s
```

**Comment by terion-name** [comment]
The most strange thing that today I've run several curl requests similar to your above - and they had run fast. I was surprised and went to application, opened it - it loaded instantly. Then I've refreshed the page and OPTIONS stuck again:
![2016-01-15 11 39 53](https://cloud.githubusercontent.com/assets/1060205/12350042/fc4ac66e-bb7c-11e5-9860-60636feaacb0.png)

While they are pending - other requests are stuck too. And again — application response is 27-29 ms. Very, very strange...

**Comment by josegonzalez** [comment]
Mind copying the curl command from those slow requests?

**Comment by terion-name** [comment]
@josegonzalez I was investigating the thing all day (even written a huge research log =)) ) and found out that problem is not with requests, but with curl inside of the app. It is strange that clockwork timelog didn't  show curl timing, so I thought that application runs ok.

Application requests a token for ember app from itself (I know that sounds strange but this is needed for time being). So it makes a curl to it's own domain. And this curl seems to be not able to access this domain. Another strange thing, that I have `curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);` but it looks like it has no effect - nginx throws 504 after 60s of waiting (or CONNECTTIMEOUT doesn't include dns-resolve time?)

So at this stage problem seems ti be in dns resolving or accessing outer world from the container.
Is this a known problem and does it have solutions?

**Comment by josegonzalez** [comment]
Can you provide *all* of the information we ask for in the contributing.md? That might help isolate the issue.

**Comment by terion-name** [comment]
@josegonzalez Sorry for delay, I just wanted to check things more deeply.

Description of problem:
Curl request from php script to application's self domain times out. While this "hanging" container does nor accept any other requests. Curl is simple:
```
    $requestUrl = $requestUrl . '?token=' . urlencode($requestToken);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $requestUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
    $response = curl_exec($ch);
    curl_close($ch);

    return $response;
```
I've added curl_setopt($ch, CURLOPT_TIMEOUT, 10); and debug stuff to curl and:
```
Verbose information: <pre>* Hostname was NOT found in DNS cache * Trying 46.101.129.220... * Connected to *correct host here, sorry, cannot show on behalf of client* (*correct ip here*) port 80 (#0) &gt; GET /api/request-token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6ImIwNjgyNzcyZGEyZjUyNTZhNzViMWQwN2UzOTI1M2RiIiwiaWF0IjoxNDUyODgwNDA2LCJleHAiOjE0NTI4ODQwMDYsIm5iZiI6MTQ1Mjg4MDQwNiwianRpIjoiMDAyMDM1YjAyMDk4MWI3MmVkMTgxZWEzZTE4NTk1MTIiLCJuYW0iOiJKb2huIERvZSIsImVtbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20ifQ.CyCFY89Q4tvWRewiRQynjJ_WJVL9faVdITalx9UbusY HTTP/1.1 Host: *correct host here* Accept: */* * Operation timed out after 10001 milliseconds with 0 bytes received * Closing connection 0 </pre>
```

There are several strange thing with this:

1. Hitting the link from error message gives the result instantly. Script at that endpoint works like a charm EXCEPT that time, when CURL request is trying to get it. I mean that while this curl is processing container does not accept any connections at all, everything freezes. But after that I hit the link in browser and I get the token.
2. This somehow affects even places where this curl doesn't invoke at all. When app is embeded to another website, that site requests token from server (/api/request-token) — it works fast, then, immediately, that site requests a server-generated js with this token from client-side — and again this works ok. But next request hangs (doesn't matter what req: OPTIONS hit first, but when I'v moved options request handler to nginx and app did not take them, subsequent get requests hanged too). If first request fulfills than all subsequent requests run ok. And the code at request-token endpoint doesn't matter: I've even placed there in a route a simple closure that simply returns a pre-generated token — the same.
3. And it is important to mention that earlier this app was hosted on a droplet with classic LEMP stack and there was no a single problem.

This is something absolutely wild. I can send you links so you could see it by yourself. Or even code if you want.
Something makes the entire process to freeze.

Output of the following commands

- `uname -a`:  Linux dokku 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:          3953       3604        348         26        328       2428
-/+ buffers/cache:        848       3104
Swap:         8191        330       7861
```
- `docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 12
Images: 75
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 99
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.861 GiB
Name: dokku
ID: DXSV:QD3M:5TGX:HGQ3:WV3H:WIEL:M2NA:XPWP:HS4Z:734H:SJXF:JFA7
WARNING: No swap limit support
```
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.8
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v5
```
- `dokku version`: 0.4.10
- `dokku plugin`:
```
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  mariadb              1.0.0 enabled    dokku mariadb service plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```
- `docker inspect CONTAINER_ID` (if applicable): https://gist.github.com/terion-name/d0b6fd84d0d5b9705212
- `cat /home/dokku/<app>/nginx.conf` (if applicable): https://gist.github.com/terion-name/7c6d0ce6d88d1c45f260
- Output of failing dokku commands with `dokku trace on` N/A
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues):

Environment details (AWS, VirtualBox, physical, etc.): DigitalOcean Droplet, domain NS are also on DO

How was dokku installed?: from DO one-click app

How reproducible: every request


Steps to Reproduce:
1. Deploy a php app in dokku with heroku builpack (webserver or php version doesn't affect)
2. Try to make curl request from php script to some endpoint of the application

Actual Results:
Request hangs and times out

Expected Results:
curl succeeds

Additional info:
Both server and domain are hosted by DO

**Comment by josegonzalez** [comment]
A small repro in code would be nice.

**Comment by terion-name** [comment]
Oh. As usual. I've cloned that app, cutted out all non-relevant stuff and pushed to dokku to have a issue-reproducing example. And guess what? It doesn't reproduce like this. This will kill me...

**Comment by josegonzalez** [comment]
Ha well something non-relevant is relevant?

**Comment by josegonzalez** [comment]
@terion-name any luck figuring this out?

**Comment by josegonzalez** [comment]
Closing as I think this is application related and there hasn't been any movement in a few weeks. If you find something, let us know!
