### ISSUE TITLE
Dokku builds not being trigerred on push.

### ISSUE THREAD

**Issue by carlossless** [dokku/dokku#1867]
Hi guys,

I've run into a problem while trying to deploy new versions of my node app to dokku. I'm successfully pushing my commits to my dokku repo, but it ends there. For some reason builds are not triggered at all by dokku, even though prior deployments worked fine.

Any ideas what caused it or where to look how to fix it?

**Comment by josegonzalez** [comment]
When reporting issues, the dokku team will need more information to help debug problems. If possible please follow the following template:

    Description of problem:


    Output of the following commands

    - `uname -a`:
    - `free -m`:
    - `docker version`:
    - `docker -D info`:
    - `docker run -ti gliderlabs/herokuish:latest herokuish version`:
    - `dokku version`:
    - `dokku plugin`:
    - `docker inspect CONTAINER_ID` (if applicable):
      (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
    - `cat /home/dokku/<app>/nginx.conf` (if applicable):
    - Link to the exact repository being deployed (if possible/applicable):
    - If a deploy is failing:
      - the type of application being deployed (node, php, python, ruby, etc.)
      - whether or not you have a `Dockerfile` in the root of your repository
      - if using buildpacks, which custom buildpacks are in use
    - Output of failing dokku commands after running `dokku trace on`
      (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

    Environment details (AWS, VirtualBox, physical, etc.):

    How was dokku installed?:

    How reproducible:


    Steps to Reproduce:
    1.
    2.
    3.

    Actual Results:


    Expected Results:


    Additional info:

**Comment by carlossless** [comment]
Sorry for not posting my description according to the template, but I've done some investigation and it seems that at some point I have had my app renamed but this didn't change the app name inside the `pre-receive` git hook. Looking at current dokku sources [here](https://github.com/dokku/dokku/blob/16544a77e25653fa0850a3213b3e27fce95008ad/plugins/apps/commands#L32) this should've been handled by the sed case.

Either way, problem solved, now it works.

**Comment by josegonzalez** [comment]
Yeah, that was a bug we fixed in the release after `apps:rename` was introduced, hence the issue. Good to hear its solved!
