### ISSUE TITLE
Multiple domains for a single App

### ISSUE THREAD

**Issue by eddiejaoude** [dokku/dokku#1874]
When creating an App, it gets the subdomain. Is it possible to point another external domain at it?

For example:
`test.example.com` and `test.com` to point to the same App officially? Or would I have to manually update the generated nginx files?

Thanks.

**Comment by josegonzalez** [comment]
You can use the [domains plugin](http://dokku.viewdocs.io/dokku/nginx/#domains-plugin) to handle this.

**Comment by eddiejaoude** [comment]
Thanks
