### ISSUE TITLE
Failed install due to cryptic herokuish error

### ISSUE THREAD

**Issue by geekdave** [dokku/dokku#1875]
Following the auto-install instructions on a fresh Ubuntu 14.04 box:

```
Setting up herokuish (0.3.8) ...
Importing herokuish into docker (around 5 minutes)
The command '/bin/sh -c curl https://github.com/gliderlabs/herokuish/releases/download/v0.3.8/herokuish_0.3.8_linux_x86_64.tgz 		--silent -L | tar -xzC /bin' returned a non-zero code: 2
dpkg: error processing package herokuish (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 herokuish
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

When I run that command manually it seems to work just fine though:

```
# curl https://github.com/gliderlabs/herokuish/releases/download/v0.3.8/herokuish_0.3.8_linux_x86_64.tgz --silent -L | tar -xzC /bin

# which herokuish
/bin/herokuish
```

Any ideas/thoughts would be greatly appreciated!

**Comment by josegonzalez** [comment]
When reporting issues, the dokku team will need more information to help debug problems. If possible please follow the following template:

    Description of problem:


    Output of the following commands

    - `uname -a`:
    - `free -m`:
    - `docker version`:
    - `docker -D info`:
    - `docker run -ti gliderlabs/herokuish:latest herokuish version`:
    - `dokku version`:
    - `dokku plugin`:
    - `docker inspect CONTAINER_ID` (if applicable):
      (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
    - `cat /home/dokku/<app>/nginx.conf` (if applicable):
    - Link to the exact repository being deployed (if possible/applicable):
    - If a deploy is failing:
      - the type of application being deployed (node, php, python, ruby, etc.)
      - whether or not you have a `Dockerfile` in the root of your repository
      - if using buildpacks, which custom buildpacks are in use
    - Output of failing dokku commands after running `dokku trace on`
      (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

    Environment details (AWS, VirtualBox, physical, etc.):

    How was dokku installed?:

    How reproducible:


    Steps to Reproduce:
    1.
    2.
    3.

    Actual Results:


    Expected Results:


    Additional info:

**Comment by geekdave** [comment]
@josegonzalez 

```
$ uname -a
Linux cwe-dokku00 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ free -m
             total       used       free     shared    buffers     cached
Mem:          3674       3127        547          0        135       2593
-/+ buffers/cache:        398       3276
Swap:        12812          0      12812

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

All subsequent docker commands failed for the same reason.

Environment: Corporate VM via some KVM thing

How was dokku installed?: via command line auto install from your instructions on fresh install

How reproducible: Every time

Steps to reproduce: See initial description

**Comment by josegonzalez** [comment]
Is your VM behind some sort of firewall?

**Comment by geekdave** [comment]
That was my thought as well, but as shown above when I ran that command in isolation it was able to download from github without any problems.

**Comment by josegonzalez** [comment]
Can you do:

```
TRACE=1 apt-get install herokuish
```
?

**Comment by geekdave** [comment]
```
$ sudo TRACE=1 apt-get install herokuish
Reading package lists... Done
Building dependency tree       
Reading state information... Done
herokuish is already the newest version.
herokuish set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up herokuish (0.3.8) ...
Importing herokuish into docker (around 5 minutes)
The command '/bin/sh -c curl https://github.com/gliderlabs/herokuish/releases/download/v0.3.8/herokuish_0.3.8_linux_x86_64.tgz 		--silent -L | tar -xzC /bin' returned a non-zero code: 2
dpkg: error processing package herokuish (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 herokuish
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by geekdave** [comment]
I can see that when I `sudo apt-get update` that we have an internal corporate apt-get repo mirror set up.  I wonder if that could be interfering somehow...

**Comment by josegonzalez** [comment]
Can you run the following:

```
sudo docker build -t gliderlabs/herokuish /var/lib/herokuish
```

**Comment by geekdave** [comment]
Aha... looks like maybe the curl command inside a docker container can't connect to github, even though curl from the outer host can:

```
$ sudo docker build -t gliderlabs/herokuish /var/lib/herokuish
Sending build context to Docker daemon 49.66 kB
Step 1 : FROM heroku/cedar:14
 ---> 56b31ddc05ad
Step 2 : RUN curl https://github.com/gliderlabs/herokuish/releases/download/v0.3.8/herokuish_0.3.8_linux_x86_64.tgz 		--silent -L | tar -xzC /bin
 ---> Running in f92a579b42e6

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c curl https://github.com/gliderlabs/herokuish/releases/download/v0.3.8/herokuish_0.3.8_linux_x86_64.tgz 		--silent -L | tar -xzC /bin' returned a non-zero code: 2
```

I wonder if there's some weird network issue with how my VMs are set up by company that's preventing docker from accessing the network even though the outer host can?

**Comment by josegonzalez** [comment]
Sounds like it. I'm going to assume you don't have some weird network settings for docker. It defaults to google's DNS servers for dns, so that might not work?

**Comment by josegonzalez** [comment]
Note: herokuish is a [recommended package](https://github.com/dokku/dokku/blob/master/debian/control#L7), so you can probably just remove it and build the image manually...

**Comment by josegonzalez** [comment]
@geekdave any luck figuring this out?

**Comment by josegonzalez** [comment]
Closing as I think this is firewall related and there hasn't been any movement in a few weeks. If you find something, let us know!
