### ISSUE TITLE
Unattended upgrade is asking for params

### ISSUE THREAD

**Issue by jvanbaarsen** [dokku/dokku#1877]
As a follow up of: https://github.com/dokku/dokku/issues/1851, I'm now running into issues where I keep getting asked for either a "Hostname Or IP" or "Keyfile for initial user:". I'm running the update with the following config:

```
    "sudo echo 'dokku dokku/web_config boolean false' | debconf-set-selections && " \
      "sudo echo 'dokku dokku/vhost_enable boolean false' | debconf-set-selections && " \
      "sudo echo 'dokku dokku/skip_key_file boolean true' | debconf-set-selections && " \
      "sudo apt-get install -qq -y dokku"
```

Am I missing certain debconfs that I still need to set?

**Comment by josegonzalez** [comment]
Can you show the entire output? Do you already have dokku installed or is this an upgrade?

**Comment by josegonzalez** [comment]
Also, you were the one to write that integration, so I expected you to test it ;)

**Comment by jvanbaarsen** [comment]
@josegonzalez haha fair point. I'll put the entire output here later on.

**Comment by jvanbaarsen** [comment]
Ok this was something outside of Dokku, I just needed to provide the Hostname, as a debconf param.
