### ISSUE TITLE
ssh: connect to host  port 22: Connection refused

### ISSUE THREAD

**Issue by Corstiaan84** [dokku/dokku#1879]
Hi there,

I get the following error when trying to git push to a dokku app (or when running any other command for that matter):

````
ssh: connect to host  port 22: Connection refused
````

Al other (3) apps are functioning normally. I have reset/readded the ssh keys for the dokku user as well, per instructions here: http://dokku.viewdocs.io/dokku/application-deployment/#adding-deploy-users

Is this a somewhat common issue and if so, what is the solution? :-)

**Comment by trevormerritt** [comment]
Sound like the SSHd isn't listening.

Can you ssh into the machine normally?  Sounds like its not dokku specific,
but a show stopper if you can't git push to it.  ;)

On Sunday, January 24, 2016, Corstiaan <notifications@github.com> wrote:

> Hi there,
>
> I get the following error when trying to git push to a dokku app (or when
> running any other command for that matter):
>
> ssh: connect to host  port 22: Connection refused
>
> Al other (3) apps are functioning normally I have reset/readded the ssh
> keys for the dokku user as well, per instructions here:
> http://dokkuviewdocsio/dokku/application-deployment/#adding-deploy-users
>
> Is this a somewhat common issue and if so, what is the solution? :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku/dokku/issues/1879>.
>


-- 
Trevor Merritt
GMail user

**Comment by Corstiaan84** [comment]
Yeah. I can ssh into it as usual. I can git push to the other apps as well without issues.

What could this be?

**Comment by josegonzalez** [comment]
Can you do a verbose push?

```
git push -vvv dokku master
```

Also, what is the name of the app remote? We had to become less "flexible" about this in a recent release due to a change in docker that affected what a valid image name is.

**Comment by Corstiaan84** [comment]
When I run
````
git push -vvv dokku master
````
I now get the following error:
````
Pushing to dokku
fatal: 'dokku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````
When I run for example
````
dokku logs
````
I get
````
Running ssh -t dokku@ logs ...
ssh: connect to host  port 22: Connection refused
````
I enabled trace on the server but I see no additional output when pushing

**Comment by u2mejc** [comment]
@Corstiaan84 Can you please fill out the issue reporting template found here: https://github.com/dokku/dokku/blob/master/CONTRIBUTING.md

**Comment by trevormerritt** [comment]
Whats you


git remote -v

look like?

On Sun, Jan 24, 2016 at 4:59 PM, Corstiaan <notifications@github.com> wrote:

> When I run
>
> git push -vvv dokku master
>
> I now get the following error:
>
> Pushing to dokku
> fatal: 'dokku' does not appear to be a git repository
> fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
> and the repository exists.
>
> When I run for example
>
> dokku logs
>
> I get
>
> Running ssh -t dokku@ logs ...
> ssh: connect to host  port 22: Connection refused
>
> I enabled trace on the server but I see no additional output when pushing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku/dokku/issues/1879#issuecomment-174345234>.
>



-- 
Trevor Merritt
GMail user

**Comment by josegonzalez** [comment]
Same as what @u2mejc asked, but also, these commands work for other apps now? This almost seems like you messed up the `authorized_keys` file for the dokku user.

Can you gist the file `/home/dokku/.ssh/authorized_keys`? Your public keys should be fine to paste, given that we can see them from the github api.

**Comment by Corstiaan84** [comment]
Hi @josegonzalez and @trevormerritt,

Sorry for the delay. Here's the gist with all requested info: https://gist.github.com/Corstiaan84/a30252eb9c5556c7f4be

@josegonzalez we also had an irc thread about a similar issue a while ago: https://www.evernote.com/l/AFTlsp6eUV1IZYzAPmNOSR3_0qiIrfM5wt8

I cleared the authorized_keys and re-add my pub key per instructions here: http://dokku.viewdocs.io/dokku/application-deployment/#adding-deploy-users. Problem persists though. One app misbehaves, the other 3 work fine.

**Comment by josegonzalez** [comment]
- You should fix the `md-plugin`
- Can you gist your `authorized_keys` file?

**Comment by Corstiaan84** [comment]
hi @josegonzalez,

* Yes, I will. Dont think its related to this issue, correct?
* Contents of keys file is first line of the gist: https://gist.github.com/Corstiaan84/a30252eb9c5556c7f4be

**Comment by josegonzalez** [comment]
No but the fewer errors the better, right? 

Can you run the following and gist the output?

```shell
ls -lah /home/dokku/fluxmatix
```

**Comment by Corstiaan84** [comment]
"No but the fewer errors the better, right?" ==> Of course :-). Will fix it.

Here's the gist. https://gist.github.com/Corstiaan84/a2613abdbb8cc1899e35

**Comment by Corstiaan84** [comment]
Hi @josegonzalez,

Any news on this perhaps? Keep up the good work! :-)

**Comment by Corstiaan84** [comment]
Hi @josegonzalez,

Since I needed to move this forward I just spinned up a fresh dokku server and made a mental note not to touch the authorized_keys file and always add deploy user as instructed in the docs.

I will keep the troublesome droplet live for a few days. Let me know if you need any info from it.

**Comment by u2mejc** [comment]
@Corstiaan84 May I take a stab? I believe @trevormerritt might be onto something pretty easy to fix, and I didn't see the responce to his question, my appologies if you did respond already.

From the git repo that your pushing from, can you `git remote -v`, then try to ssh to the (push) remote you see there: `ssh -v dokku@<host>`
Should look something like this:
```bash
$ git remote -v
dokku	dokku@dokku.me:ruby-sample (fetch)
dokku	dokku@dokku.me:ruby-sample (push)
origin	https://github.com/heroku/ruby-sample.git (fetch)
origin	https://github.com/heroku/ruby-sample.git (push)
$ ssh dokku@dokku.me
Usage: dokku [--quiet|--trace|--rm-container|--rm|--force] COMMAND <app> [command-specific-options]

Options:
...
```

**Comment by Corstiaan84** [comment]
@u2mejc Thanks :-). I will give your suggestion a go tomorrow.

**Comment by u2mejc** [comment]
@Corstiaan84 any dice checking the above?

**Comment by Corstiaan84** [comment]
Hi @trevormerritt and @u2mejc,

I destroyed the droplet already... Im sorry... Thanks for all you guys help so far. Also @josegonzalez :-)

Cheers.
