### ISSUE TITLE
Unsupported vhost config found when trying to add a custom domain to an app

### ISSUE THREAD

**Issue by JoeeGrigg** [dokku/dokku#1881]
When I am trying to add a custom domain to an app I am getting back this error:

```
root@dokku:~# dokku domains:add arc 2ra.co.uk
=====> unsupported vhost config found. disabling vhost support
-----> Setting config vars
       NO_VHOST: 1
-----> VHOST support disabled, deleting arc/VHOST
-----> Setting config vars
       NO_VHOST: 1
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Added 2ra.co.uk to arc
```

By the end of the message it looks to me like the domain has been added however it is not actually being added.

I am assuming that it is something to do with nginx vhost but I am new to all of this so unsure.

Any ideas anyone?

**Comment by josegonzalez** [comment]
Can you do the following:

```
dokku config:unset NO_VHOST
```

And let us know the output?

**Comment by michaelshobbs** [comment]
The contents of `/home/dokku/VHOST` and `/home/dokku/HOSTNAME` would be interesting as well.

**Comment by JoeeGrigg** [comment]
When I came back to it today and ran:

```
dokku config:unset NO_VHOST
```

Everything seems to be working fine... I don't know if it was removing that environment variable that fixed or what but everything is up and running.

Thank you
