### ISSUE TITLE
RFC: Development Release Branches

### ISSUE THREAD

**Issue by u2mejc** [dokku/dokku#1884]
I'd like to propose we start using release branches that will allow us to merge future release PRs, similar how docker (or even plugn) use a release branch.

When a release is has gone GM, it's merged back into master and a new branch for the next version is created off master. The release branches are rebased from master when committing new changes to keep older commits insync and eliminate the issue of having to rebase PR through 50+ commits in the future.

```
--master-----------merged release-v0.5-------------------merged release-0.6------ etc...
    \- release-v0.5-/             \-release-0.6-----\rebase--------/
```
Rebasing also helps keep a congruent timeline for master, while the minimal release branches allow us to merge PRs right away and prevent them from becoming stagnant and failing to rebase down the road.

Work flow:
* Fork repo
```
git clone git@github.com:<user>/dokku.git & cd  dokku
git checkout release-0.5
git commit -am "my sweet commit"
git fetch origin
git rebase master
git push origin release-0.5
```
* Create Pull Request, on left side, select dokku/release-0.5 instead of master.

@josegonzalez Thoughts?

**Comment by michaelshobbs** [comment]
For the record, I think is a convoluted way to manage open source software and will potentially increase the difficulty for the maintainers to manage this project. The current, more standard, method we use now decentralizes the responsibility of maintaining open PRs to those individuals that want to contribute to the project.

**Comment by josegonzalez** [comment]
I'm pretty :-1: . This sort of workflow is great companies that love to have overhead on what goes where, but to be honest, I don't think we need that, nor do I think it adds anything to the release process.

We merge PRs pretty quickly - except around a minor release, or for large pieces of work - so I don't see how this would help the common contributor. I could be wrong though.
