### ISSUE TITLE
Request: Make config_set and config_unset respect DOKKU_APP_RESTORE

### ISSUE THREAD

**Issue by petewest** [dokku/dokku#1889]
I've been upgrading the containers used by a few services (through the mysql plugin), here's my current workflow:

    docker pull mysql:5.7.10
    dokku ps:stop app
    dokku mysql:clone app-database app-database-new
    dokku mysql:unlink app-database app
    dokku mysql:link app-database-new app
    dokku ps:start app

Unfortunately, as soon as I unlink the old database it triggers a `dokku ps:restart app` (from here https://github.com/dokku/dokku/blob/master/plugins/config/functions#L226) even though DOKKU_APP_RESTORE has been set to 0.

I think it'd be a good idea if `config_set` and `config_unset` didn't restart the app if DOKKU_APP_RESTORE is set as 0.

**Comment by jvanbaarsen** [comment]
@petewest You can set a flag: `--no-restart` that will make sure there is no restart after setting the config vars.

**Comment by petewest** [comment]
That's possible when calling `dokku config:set` yourself, but when plugins call it (https://github.com/dokku/dokku-mysql/blob/master/functions#L93) it'd require extra logic in the plugin to determine whether to restart the app or not. It also makes sense not to restart the app if it's been told to stop, no matter what calls `config_set` and `config_unset`.

**Comment by jvanbaarsen** [comment]
@petewest Thanks for explaining!

**Comment by josegonzalez** [comment]
Probably shouldn't start a manually stopped app. Not sure we keep track of starts/stops anywhere.

**Comment by michaelshobbs** [comment]
We have [`post-stop`](https://github.com/dokku/dokku/blob/0ddc4ba496e04b1c1e8fcb8241f53da985b4b6ec/plugins/ps/post-stop)/[`post-deploy`](https://github.com/dokku/dokku/blob/0ddc4ba496e04b1c1e8fcb8241f53da985b4b6ec/plugins/ps/post-deploy) triggers that set `DOKKU_APP_RESTORE`. 

We could potentially modify [this block](https://github.com/dokku/dokku/blob/0ddc4ba496e04b1c1e8fcb8241f53da985b4b6ec/plugins/config/functions#L193-L196) AND [this block](https://github.com/dokku/dokku/blob/0ddc4ba496e04b1c1e8fcb8241f53da985b4b6ec/plugins/config/functions#L224-L227) to filter on `DOKKU_APP_RESTORE`.
