### ISSUE TITLE
Suggested way to run Docker containers directly alongside Dokku

### ISSUE THREAD

**Issue by csu** [dokku/dokku#1894]
What's the best/recommended way for running containers directly on Docker alongside a Dokku installation? Should I run them as the Dokku user? Or start another instance of the Docker daemon as my normal user and run them there? Or add my normal user to the Dokku group and directly add containers to the daemon?

I realize this probably depends on the use case, but what would be the best ways for going about doing this in the cases where I do and don't want to associate custom domains with my containers? For instance, if I wanted to run a backend-only game server in a container, what would be the best way? Similarly, what would be the suggested way to run a container for something that I would want on a custom domain (e.g. WordPress or Koken), but wouldn't want to commit into a git repository to deploy?

**Comment by csu** [comment]
Follow up question: does Dokku provide any way to associate a custom domain through nginx with a container that is run directly through Docker?

**Comment by josegonzalez** [comment]
From the [docs](http://dokku.viewdocs.io/dokku/application-deployment/#dokkudocker-container-management-compatibility):

> Dokku is, at its core, a docker container manager. Thus, it does not necessarily play well with other out-of-band processes interacting with the docker daemon. One thing to note as in issue #1220, dokku executes a cleanup function prior to every deployment. This function removes all exited containers and all 'unattached' images.

At the moment there is no "best way" to handle the functionality you desire. Run a different OS with docker on it and put your custom, non-dokku apps there?

For something like wordpress, it's been deployed to dokku before (search google for references) and there is nothing stopping you from following that workflow.

Regarding custom nginx domains for non-dokku containers, that is something you will need to handle on your own by adding an nginx conf to the right directory, `/etc/nginx/sites-enabled`.

**Comment by darklow** [comment]
If anyone is interested here is my dokku setup for koken, works perfect:
https://github.com/darklow/docker-koken-lemp/tree/dokku
Use official mariadb plugin for database.

My setup is fork for dokku of official https://github.com/koken/docker-koken-lemp

**Comment by josegonzalez** [comment]
Note: you can also just deploy images or a dockerfile with dokku, and we'll handle the rest. Otherwise, you're mostly on your own for linking things etc.
