### ISSUE TITLE
How to set IMAGE_VERSION for plugins via SSH

### ISSUE THREAD

**Issue by partikus** [dokku/dokku#1895]
Hi, 

How to set ``IMAGE_VERSION`` for plugins e.g. during create mysql container via SSH?

```
ssh dokku@mydokku mysql:create my-app-1
```

We can set ``MYSQL_IMAGE_VERSION`` in the ``/home/dokku/.bashrc`` adding ``export MYSQL_IMAGE_VERSION="5.5"`` but this solution set version of mysql globally.

How to set version of image per app? Have you got any other solutions?

**Comment by jvanbaarsen** [comment]
@partikus I guess this should work:

```
ssh dokku@mydokku MYSQL_IMAGE_VERSION="5.5" mysql:create my-app-1
```

**Comment by partikus** [comment]
@jvanbaarsen it does not work

```bash
ssh dokku@mydokku ELASTICSEARCH_IMAGE_VERSION="1.7.1" elasticsearch:create test-1
 !     `ELASTICSEARCH_IMAGE_VERSION=1.7.1 elasticsearch:create test-1` is not a dokku command.
 !     See `dokku help` for a list of available commands.
```

**Comment by josegonzalez** [comment]
What about this: http://superuser.com/a/163228

**Comment by jvanbaarsen** [comment]
@partikus What about changing the order:
```
ssh dokku@mydokku  elasticsearch:create test-1 ELASTICSEARCH_IMAGE_VERSION="1.7.1"
```

Dokku tries to map the first param to one of its internal command structures. So adding it to the end might actually work. If not, you probably should use the option @josegonzalez suggested

**Comment by partikus** [comment]
@jvanbaarsen unfortunatelly your solution does not work but I've added to ``/etc/ssh/sshd_config`` following line

```
AcceptEnv ELASTICSEARCH_IMAGE_VERSION MYSQL_IMAGE_VERSION
```
Thanks to that I can change IMAGE version using
```bash
export ELASTICSEARCH_IMAGE_VERSION="1.7.2"
ssh -o SendEnv=ELASTICSEARCH_IMAGE_VERSION dokku@mydokku  elasticsearch:create test-1
```

IMO dokku should consider adding ``--env="ELASTICSEARCH_IMAGE_VERSION=1.7.4"`` the same as ``--force`` option

thank you @jvanbaarsen @josegonzalez

**Comment by josegonzalez** [comment]
@partikus mind opening a new issue for that/adding a pull request?
