### ISSUE TITLE
Unable to deploy additional apps

### ISSUE THREAD

**Issue by zidik** [dokku/dokku#1896]
After installing Dokku I successfully deployed a rails app on it. But after a while I tried to add a second app
`dokku apps:create frontend`
now the problem is, that I am unable to push to the new app. Pushing to the first app is still working as expected. 

`git push dokku@myserver.com:api` succeeds, but
`git push dokku@myserver.com:frontend` fails with

```
fatal: 'frontend' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
What could cause this behaviour and how could I find a solution for it?

**Comment by josegonzalez** [comment]
Interesting. How did you create the first app, through a dokku push?

**Comment by michaelshobbs** [comment]
@zidik you might try destroying the `frontend` app and then running `git push dokku@myserver.com:frontend master`. 

perhaps something got hosed between `apps:create` and your push command? would need more info to say for sure.

**Comment by zidik** [comment]
@josegonzalez I created the first app by running `dokku apps:create api` on the server and then pushing into it `git push dokku@myserver.com:api`.

@michaelshobbs I have destroyed and recreated the `frontend`, tried another name. git push still fails the same way.

Is there any log I could take a look at?

**Comment by michaelshobbs** [comment]
@zidik you're looking at the log output already. this is git failing upfront i think. you might try running `dokku trace on` on the dokku instance and try pushing again to see if we're missing something else.

**Comment by zidik** [comment]
I ran `dokku trace on` on dokku instance and tried pushing to `frontend `- saw nothing new, only same error.

**Comment by josegonzalez** [comment]
What is the output of the following command:

```shell
ls -lah /home/dokku/frontend
```

**Comment by u2mejc** [comment]
@zidik My money is on this not being a dokku issue, it's a malformed git remote url. ;-)

Please compare your git remote for each repo and share here if you can:
```
cd /path/to/repo/frontend
git remote -v

cd /path/to/repo/api
git remote -v
```

**Comment by zidik** [comment]
```
~$ ls -lah /home/dokku/frontend
total 8.0K
drwxr-xr-x 2 dokku dokku 4.0K Feb  4 22:44 .
drwxr-xr-x 9 dokku dokku 4.0K Feb  4 22:44 ..
```


```
...
production      dokku@tindomondo.com:frontend (push)
....
```

```
...
production      dokku@tindomondo.com:api (push)
...
```

**Comment by u2mejc** [comment]
Nice, in the api repo, can you `git push -v production master`

**Comment by zidik** [comment]
Yes, this one works great
```
$ git push -v production master
Pushing to dokku@tindomondo.com:api
To dokku@tindomondo.com:api
 = [up to date]      master -> master
updating local tracking ref 'refs/remotes/production/master'
Everything up-to-date
```

**Comment by u2mejc** [comment]
bingo! Your remote's name is "production". 

You can rename it to dokku by doing this:
`git remote rename production dokku`

Let me know if that solves your issue. :+1:

**Comment by u2mejc** [comment]
ah, sorry I meant that in frontend which was broken, try that there and let me know if that works.

**Comment by zidik** [comment]
No, this does not change anything.

**Comment by zidik** [comment]
```
$ uname -a
Linux Tindomondo 3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ free -m
             total       used       free     shared    buffers     cached
Mem:          3440       1467       1973         13         93        974
-/+ buffers/cache:        398       3041
Swap:            0          0          0
```

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

```
$ docker -D info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

```
$ dokku version
0.4.13
```

```
$ dokku plugin
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

```

Environment details (AWS, VirtualBox, physical, etc.):
`Azure`
How was dokku installed?:
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.4.13/bootstrap.sh
sudo DOKKU_TAG=v0.4.13 bash bootstrap.sh
```

**Comment by zidik** [comment]
Solved the problem thanks to issue https://github.com/dokku/dokku/issues/116 by generating a new public/private key pair and using `cat ~/.ssh/id_rsa.pub | ssh admin@server sudosshcommand acl-add dokku keyname` instead of adding key manually to authorised_keys.

Strange, that it worked with one app, but not the other.
