### ISSUE TITLE
Cant push Ruby projects with ruby version dependency

### ISSUE THREAD

**Issue by mattberther** [dokku/dokku#1899]
Im not sure if Im reporting this in the right area. Please redirect me if I should be posting elsewhere.

I have an Ubuntu 14.04 box configured to use ruby 2.2.4. On the Ubuntu box, this shows up:

```
$ /usr/bin/ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux-gnu]
```

I have a ruby project with a Gemfile that has this code:

```
detected_ruby_version = Gem::Version.new(RUBY_VERSION.dup)
required_ruby_version = Gem::Version.new('2.1.0') # minimum supported version

if detected_ruby_version < required_ruby_version
  fail "RUBY_VERSION must be at least #{required_ruby_version}, " \
       "detected RUBY_VERSION #{RUBY_VERSION}"
end
```

Running `bundle install` locally with a 2.2.4 ruby works just fine. However, when I try to `git push dokku master`, I get this output:

```
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 1.55 KiB | 0 bytes/s, done.
Total 7 (delta 4), reused 0 (delta 0)
-----> Cleaning up...
-----> Building errbit from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
-----> Compiling Ruby/Rails
remote: sh: 2: Syntax error: Unterminated quoted string
       !
       !     There was an error parsing your Gemfile, we cannot continue
       !     /tmp/build/Gemfile:12:in `eval_gemfile': RUBY_VERSION must be at least 2.1.0, detected RUBY_VERSION 1.9.3 (RuntimeError)
       !     /tmp/d20160207-177-ybw4mf/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `instance_eval'
       !     /tmp/d20160207-177-ybw4mf/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `eval_gemfile'
       !     /tmp/d20160207-177-ybw4mf/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:10:in `evaluate'

       <remaining output snipped>
```

Any thoughts on what is causing dokku to identify ruby 1.9.3 instead of 2.2.4?

Thank you!

**Comment by josegonzalez** [comment]
Do you have a ruby version file with the wrong Ruby version? Can you post all the info we ask for in our contributing.md?

**Comment by mattberther** [comment]
@josegonzalez my .ruby-version file is not checked into the git repo. Although, the local version of the file says 2.2.4

Extra info from contributing.md:


Output of the following commands

- `uname -a`: 
Linux my.hostname.com 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`: 
ubuntu@apps:~$ free -m
             total       used       free     shared    buffers     cached
Mem:          2000       1553        446          2         88        345
-/+ buffers/cache:       1119        881
Swap:          511        166        345

- `docker version`:
dokku@apps:/home/ubuntu$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

- `docker -D info`:
dokku@apps:/home/ubuntu$ docker -D info
Containers: 5
Images: 86
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.954 GiB
Name: my.hostname.com
ID: 2JFD:6OLZ:RV72:473B:VFRH:RODC:2EWP:7XGM:LYB2:BDMQ:GP2X:A5D6
WARNING: No swap limit support

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.8
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v5

- `dokku version`:
dokku@apps:/home/ubuntu$ dokku version
0.4.13

- `dokku plugin`:
dokku@apps:/home/ubuntu$ dokku plugin
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  airbrake-deploy      0.4.0 enabled    Airbrake/Errbit notifier on deploy
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

- `docker inspect CONTAINER_ID` (if applicable): I dont believe this is applicable
- `cat /home/dokku/<app>/nginx.conf` (if applicable): I dont believe this is applicable
- Output of failing dokku commands with `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues):

Environment details (AWS, VirtualBox, physical, etc.): AWS EC2 instance

How was dokku installed?: apt-get install dokku

**Comment by josegonzalez** [comment]
I think you need to specify a ruby version [like so](https://devcenter.heroku.com/articles/ruby-versions). Can you either do that or add a `.ruby-version` file to see if it gets fixed?

**Comment by jvanbaarsen** [comment]
We always specify the ruby version in the Gemfile for Dokku, and only the `.ruby-version` file for rbenv.

Adding the ruby version in the Gemfile will fix this!

**Comment by mattberther** [comment]
Adding the .ruby-version didnt resolve the issue. And neither did specifying the ruby version in the Gemfile.

Ive put this code in my Gemfile -- the project, FWIW, is https://github.com/errbit/errbit.

```
source 'https://rubygems.org'

RAILS_VERSION = '~> 4.2.5.1'

ruby '2.2.4' #ENV['GEMFILE_RUBY_VERSION'] || '2.0.0'

detected_ruby_version = Gem::Version.new(RUBY_VERSION.dup)
required_ruby_version = Gem::Version.new('2.1.0') # minimum supported version

if detected_ruby_version < required_ruby_version
  fail "RUBY_VERSION must be at least #{required_ruby_version}, " \
       "detected RUBY_VERSION #{RUBY_VERSION}"
end
```

and still receive the error:

```
$ git push dokku production:master
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 619 bytes | 0 bytes/s, done.
Total 7 (delta 4), reused 0 (delta 0)
-----> Cleaning up...
-----> Building errbit from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
-----> Compiling Ruby/Rails
remote: sh: 2: Syntax error: Unterminated quoted string
       !
       !     There was an error parsing your Gemfile, we cannot continue
       !     /tmp/build/Gemfile:12:in `eval_gemfile': RUBY_VERSION must be at least 2.1.0, detected RUBY_VERSION 1.9.3 (RuntimeError)
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `instance_eval'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `eval_gemfile'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:10:in `evaluate'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/definition.rb:25:in `build'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler.rb:155:in `definition'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli/check.rb:11:in `run'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli.rb:103:in `check'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli.rb:10:in `start'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/bin/bundle:20:in `block in <top (required)>'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/gems/bundler-1.9.7/bin/bundle:18:in `<top (required)>'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/bin/bundle:23:in `load'
       !     /tmp/d20160208-176-b2sugs/bundler-1.9.7/bin/bundle:23:in `<main>'
       !     There was an error in your Gemfile, and Bundler cannot continue.
       !
```

**Comment by josegonzalez** [comment]
Can you provide the output of a deploy after running `dokku trace on`? Please ensure you don't output any secrets in that gist.

**Comment by mattberther** [comment]
Sure thing, @josegonzalez. Something tells me the `remote: sh: 2: Syntax error: Unterminated quoted string` line may be a clue here, but not sure where that's coming from.

Here's a gist: https://gist.github.com/mattberther/4d221641903302c7ac09

Thanks for looking into this.

**Comment by josegonzalez** [comment]
What are the contents of your `Gemfile` ?

**Comment by mattberther** [comment]
Both the Gemfile and UserGemfile are posted here: https://gist.github.com/mattberther/7c94908139d44f56d851

**Comment by josegonzalez** [comment]
So it seems like the "build environment" in herokuish has ruby 1.9.3, whereas on heroku it is by default 2.0.0. This only appears to affect the detection of support, not the actual built output, so you'll get ruby `2.2.4` if you remove that version check.

Not sure if there is a way to get around this tbh. Maybe checking to see if `bundle check` is in the callstack, and skipping the raise if so?

**Comment by mattberther** [comment]
So be it -- i can remove the check. I thought that perhaps I was doing something incorrectly. Thank you for your energy spent on this.

**Comment by josegonzalez** [comment]
Yay errbit!
