### ISSUE TITLE
BUILDPACK_URL environment variable is ignored when Dockerfile is present

### ISSUE THREAD

**Issue by cu12** [dokku/dokku#1903]
Hi all,

I'm experiencing an issues while trying to deploy [zendesk/samson](https://github.com/zendesk/samson) using buildpack instead of the bundled Dockerfile.

What I see is, that despite I have `BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-ruby` set under the application, Dokku still tries to build the application with the bundled Dockerfile. [Gist](https://gist.github.com/cu12/9fbdc4ebe4d998df44a1)

As I can see in the [documentation](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/) - point it out if I missed something - this is contrary to the desired behavior.

**Comment by josegonzalez** [comment]
I don't see where in your gist that `BUILDPACK_URL` is set. Can you gist that output?

**Comment by cu12** [comment]
I updated the gist, not sure why relevant parts was not included for the first time.

**Comment by GabKlein** [comment]
I had the same issue earlier today, I had to add an empty `.buildpacks` file at the root of the project to bypass the `Dockerfile` and use `BUILDPACK_URL`

**Comment by josegonzalez** [comment]
Closing as there is a PR open.
