### ISSUE TITLE
how to switch from <app>.<host> to <host>/<app> after install?

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#1905]
Hi. I installed dokku in the <app>.<host> mode but due to some SSL issues I am being asked to change the install to <host>/<app>. Usually this is something that is chosen during install... Can I now change? I am reading the docs but can't find it. Something I found that is vaguely related is http://dokku.viewdocs.io/dokku/nginx/ , under disabling VHOSTS - but that is per app. I want to change the global settings.

Anybody help please? Can the docs be updated please? Thanks!

**Comment by michaelshobbs** [comment]
If I understand your issue correctly, you think you can use `dokku domains:add` to add the domain to your app, then use a custom nginx template to answer for `<host>/<app>`. We are in the midst of revamping VHOST support for 0.5.x. Check out #1892 for details there. Docs will also be updated soon.

**Comment by michaelshobbs** [comment]
It should be noted that accessing your app at `http://<host>/<app>` is not support out of the box. Hence the custom template requirement. If you wanted to access your app at just `http://<host>`, then the answer is to simply use `dokku domains:add <app> <host>`

**Comment by sglebs** [comment]
I seemed to recall that on install one could choose between <app>.<host> (which I always use) or <host>/<app> (which I thought was possible) but reading the docs it seems that on install I have to choose either <app>.<host> or <host>:<random-high-port>, right?

Well, I have to do this tomorrow. 0.5.x is not an option for me now. It seems I am out of luck?

**Comment by michaelshobbs** [comment]
I don't know what you mean by `.`, `/`, and `:`. Can you clarify?

**Comment by michaelshobbs** [comment]
No you're not out of luck. You can add the desired domain to your app with `dokku domains:add` and use a custom template to support your app at `/<app>`

**Comment by josegonzalez** [comment]
`scheme://host/app` is not possible to do out of the box. We only support the following modes:

- `scheme://app.host`
- `scheme://host:port`

Anything fancier will *require* a custom nginx configuration.

@michaelshobbs I don't think multiple apps can listen on the same domain, so he would need a custom plugin that handles the `post-deploy` hook to rebuild his "global" nginx site. I don't think what he wants would be possible in `0.5.0` either (though it's been asked for a few times in the past).

**Comment by sglebs** [comment]
Ok, I will hunt the docs on this template tweaking stuff. If you have URLs handy, please let me know. Thanks!

**Comment by michaelshobbs** [comment]
This can definitely be done with a custom template but yeah that one app would be the only one able to answer to `<host>`

**Comment by michaelshobbs** [comment]
@sglebs http://dokku.viewdocs.io/dokku/nginx/#customizing-the-nginx-configuration

**Comment by michaelshobbs** [comment]
You may have to change your global nginx config as well; depending on what's in there.

**Comment by sglebs** [comment]
I just checked on the requirement, a root custom name will do. So, myapp.foo.com but also blortz.bar.com. adding the domain may be enough in this case. Thanks!
