### ISSUE TITLE
--rm or --rm-container do not appear to be cleaning up

### ISSUE THREAD

**Issue by mattberther** [dokku/dokku#1906]
Im sure im missing something simple here -- but since upgrading to 0.4.13, my drive has been filling up due to a dokku --rm run command in my crontab. Behavior reproducible from outside of cron also.

```
ubuntu@apps:/home/dokku$ docker --version
Docker version 1.9.1, build a34a1d5

ubuntu@apps:/home/dokku$ dokku version
0.4.13

ubuntu@apps:/home/dokku$ dokku --rm-container run raging-taters "npm run fill-cache"

> raging-taters@1.0.0 fill-cache /app
> node ./bin/cache fill

ubuntu@apps:/home/dokku$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                      PORTS               NAMES
f5357869d3fe        dokku/raging-taters:latest     "/exec 'npm run fill-"   29 seconds ago      Exited (0) 21 seconds ago                       hopeful_swanson
b843214e3992        dokku/raging-taters:latest     "/start web"             3 days ago          Up 3 days                                       raging-taters.web.1
```

**Comment by josegonzalez** [comment]
Does that command ever exit? What did you upgrade from?

**Comment by mattberther** [comment]
@josegonzalez: The command exits and the web container pulls the cached data in. The first container id shows the status as exited. I upgraded from 0.3.something.

**Comment by josegonzalez** [comment]
That should work, and in fact I believe we have tests covering that. Can you run that command after executing the following:

```
dokku trace on
```

And paste the output here?

**Comment by mattberther** [comment]
Thanks for looking at this. The trace output is here: https://gist.github.com/mattberther/d94e0afcc94875760be9

**Comment by josegonzalez** [comment]
Looks like this broke as of 0.4.5 in this commit https://github.com/dokku/dokku/commit/2ed0424860cc2d4bef87749df0a2fbbc7debad29

@michaelshobbs worth fixing in 0.4.x or waiting till 0.5.x?

**Comment by josegonzalez** [comment]
For now, you can do the following:

```
dokku config:set --global DOKKU_RM_CONTAINER=1
```

That should "fix" the proximate issue, though is certainly not a long-term solution to the broken functionality.

**Comment by mattberther** [comment]
Thanks for the short-term fix -- Ill keep an eye on this issue for a long-term fix. Please let me know if there's anything else you need from me.
