### ISSUE TITLE
resetting dokku to expected permissions

### ISSUE THREAD

**Issue by mattberther** [dokku/dokku#1914]
Based on a previous issue, I tried migrating my crontab to the dokku user. However, when I do that, I receive these errors in the output:

```
/var/lib/dokku/core-plugins/available/common/functions: line 373: plugn: command not found
Access denied
```

Since the crontab works with a user in sudoers, it leads me to believe that I might have installed dokku incorrectly. Is there an easy way to reset the dokku installation to not require cron jobs to be executed by a sudoer?

**Comment by josegonzalez** [comment]
Did you forget to add a PATH variable to your cron file? This might explain your command not found issue.

Docs for that [here](http://dokku.viewdocs.io/dokku/deployment/one-off-processes/#general-cron-recommendations).

**Comment by mattberther** [comment]
Thanks for reminding me to RTFM. :) That did the trick.
