### ISSUE TITLE
Weird characters when git pushing from CI server

### ISSUE THREAD

**Issue by robgraeber** [dokku/dokku#1917]
Hey I've been noticing some weird characters when git pushing from jenkins or other CI services. Works fine locally, something to do with encoding?

<img src="https://cloud.githubusercontent.com/assets/2387719/13048470/e35fca10-d39a-11e5-8b78-8b198f2fd2df.png" width="300">

**Comment by michaelshobbs** [comment]
The node buildpack uses UTF8 characters. I see this in my chef logs all the time.

**Comment by robgraeber** [comment]
@michaelshobbs fyi found a solution for this:

> The weird characters are actually ANSI escape codes. These tell a regular terminal to do specific things, like add colour to text, or move the cursor to the beginning of the line.
> 
> In the case of Jenkins, the console output is converted into HTML, and so the ANSI codes lose their functionality, and just get in the way. There are two options to fix this:
> 
> Use the ANSIColor Plugin, which uses the ANSI codes to construct HTML which colorises output, amongst other things.
> Strip the ANSI codes from the output before it gets to stdout, using sed:
> build_command | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
