### ISSUE TITLE
Worker process that opens internal HTTP port?

### ISSUE THREAD

**Issue by blastoffchat** [dokku/dokku#1919]
I have an app with the following processes in my Procfile: `web`, `monitor` and `bot`. 

- `web` is the external facing HTTP service as usual. 
- `bot` however is also an HTTP service but shouldn't be exposed publicly.
- `monitor` communicates with `bot` through an HTTP API and doesn't open any port. 

I was wondering if dokku supports this kind of setup and if so, how the `monitor` process can get the IP/port of `bot`.

Open to suggestions about different way to set things up but I'd prefer to keep all my code in the same git repo.

**Comment by michaelshobbs** [comment]
I think you should be able to do this with `docker-options` and using [docker links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/).

**Comment by michaelshobbs** [comment]
More than likely, however, you'll have to write your own dokku plugin to manage the lifecycle of the process that needs to make the connection.

**Comment by michaelshobbs** [comment]
With all that said, docker 1.10 introduced a whole new networking layer that I'm interested in utilizing in dokku and would make this use case much easier to handle.

**Comment by blastoffchat** [comment]
Thanks for the info. I was thinking of maybe instead creating a separate app just to run `bot` in but then I would have to maintain a separate repo just so that the `bot`'s app Procfile has the right web command. I'd also have to implement HTTP auth but that's not a big deal.

**Comment by blastoffchat** [comment]
Ended up doing that.
