### ISSUE TITLE
Cron on Dokku

### ISSUE THREAD

**Issue by JoeeGrigg** [dokku/dokku#1920]
I am running a ruby sinatra app and wanting to use cron jobs to schedule tasks. I am trying to use the whenever gem and it works locally however when I try to deploy to dokku I get an error:

```
/var/spool/cron/: mkstemp: Permission denied
```

Does anyone know the reason for this? I have read quite a few people saying that cron is a no go in dokku but if this is the case then I have two questions:

1. Why is cron not available in dokku
2. What are my other options?

Any help would be appriciated.
Thanks

**Comment by michaelshobbs** [comment]
What ended up being the issue?

**Comment by JoeeGrigg** [comment]
The issue with cron did still appear to be dokku however I found a gem called [Rufus Scheduler](https://github.com/jmettraux/rufus-scheduler) which will do what I need it to.

**Comment by michaelshobbs** [comment]
I know dokku and cron didn't work well at one point but there are folks in the community that use dokku with cron currently. Check out the docs here: http://dokku.viewdocs.io/dokku/deployment/one-off-processes/
