### ISSUE TITLE
Push on a different ssh port than 22

### ISSUE THREAD

**Issue by ale-batt** [dokku/dokku#1928]
For my server security, i change my ssh port ip. so it's not 22 but 1337 ( for exemple)

When i want to add remote my dokku, i cannot find the **right syntax**.
`git remote add dokku@myip:myapp`
i have a error : `ssh: connect to host myip port 22: Connection refused`
i try with :  `git remote add dokku@myip:1337:myapp` or `git remote add dokku@myip:1337/myapp`

Any solution ?

**Comment by josegonzalez** [comment]
You'll need to setup a custom local `~/.ssh/config` like so:

```
Host my-dokku-host
  Hostname myip
  Port 1337
```

And then use `my-dokku-host` as the remote, without the port.

**Comment by denyskoch** [comment]
alternative: git remote add ssh://dokku@myip:myport/myapp

**Comment by crystianwendel** [comment]
> alternative: git remote add ssh://dokku@myip:myport/myapp

When i did this, dokku creates an app with the port number. I think the answer from @josegonzalez is the correct one.
