### ISSUE TITLE
Question: Can I use pagespeed with dokku?

### ISSUE THREAD

**Issue by internetstyle** [dokku/dokku#1929]
Can I use pagespeed with dokku?

**Comment by michaelshobbs** [comment]
Maybe include a reference link? Not sure what pagespeed is.

**Comment by josegonzalez** [comment]
Yes, you can use [nginx pagespeed](https://github.com/pagespeed/ngx_pagespeed) with dokku. We simply require that nginx be available for use with our nginx-vhosts plugin, but what you do to tune nginx beyond that is up to you.
