### ISSUE TITLE
Setting up two sites on one vps with dokku

### ISSUE THREAD

**Issue by sammdec** [dokku/dokku#193]
Hi there,

I have one site successfully pushed using dokku but I was wondering if I point a new domain at my vps and push another app to the server how will the vps differentiate between requests?

**Comment by Dedoig** [comment]
Do I need
   `dokku apps:create newDomain.com` 
on the dokku server before I do
  `git push dokku dokku@myServer.com:newDomain.com` on my laptop?

I tried without the `apps:create` and get git error: `error: src refspec remote does not match any.`

Anything different if newDomain.com is an entirely static site?

(Hesitate to open new issue just for this clarification)

**Comment by joshmanders** [comment]
What version of dokku you using? You should be able to push without needing a repository on the server, and if set as a FQD dokku will set a vhost for it.

**Comment by Dedoig** [comment]
0.7.2

**Comment by Dedoig** [comment]
Do I need `dokku domains:add newDomain.com` or `domains:add-global` ? Right now `dokku domains` just shows my single (Global) `myServer.com` domain name, and serves one normal app already under `myApp.myServer.com`.

**Comment by joshmanders** [comment]
Make sure you've made an actual commit before pushing? What does the output of `git log` show?

**Comment by joshmanders** [comment]
Actually, I just noticed your error.

You need to first do `git remote add dokku dokku@yourserver.com:newDomain.com` then make your commits, and run `git push dokku master`

**Comment by Dedoig** [comment]
I did both `git remote add ...` and `git commit` correctly before the `push`.

**Comment by joshmanders** [comment]
Please open another issue so that we don't spam the people who are subscribed to this thread and I will continue to assist you. I am locking it.
