### ISSUE TITLE
Securing websocket subdomain

### ISSUE THREAD

**Issue by madshargreave** [dokku/dokku#1930]
Hi

I am hosting an application that uses websockets, and goes through CloudFlare.

Since CF does not support websockets, I have to route these seperately to a CNAME ws -> mydomain.com, and disable the CF for that specific record.

I get the following error:

WebSocket connection to 'wss://ws.mydomain.com/socket/websocket?vsn=1.0.0' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
I'm guessing that's because the SSL is not properly setup on the subdomain

How can I fix this?

**Comment by sseemayer** [comment]
See also dokku/dokku-letsencrypt#28

**Comment by josegonzalez** [comment]
Did you ever get this solved? I did help someone on irc with this, might be worth combing the logs to see what happened with it :)

**Comment by josegonzalez** [comment]
Closing as there hasn't been any movement.
