### ISSUE TITLE
Adding security headers to nginx.ssl.conf.template breaks app

### ISSUE THREAD

**Issue by enjikaka** [dokku/dokku#1933]
Description of problem:
Adding ```add_header X-Xss-Protection "1; mode=block" always;``` breaks app upon ps:rebuild. Commenting out this by prepending with # still breaks the app. Removing the line completely makes it work again. When it breaks. It does loads with the wrong HTTPs certs, and gives a "NET::ERR_CERT_COMMON_NAME_INVALID" error.

Environment details (AWS, VirtualBox, physical, etc.):
DigitalOcean VPS of the Dokku image.

Dokku version: 0.4.12

How was dokku installed?:
See above

How reproducible:
100 %

Steps to Reproduce:
1. Add the header to nginx.ssl.conf.template
2. Restart nginx
3. ```dokku ps:rebuild <app>``` on any app

Expected Results:
Security header is added and the app starts

Actual Results:
Dokku is, upon rebuilding, spitting out a part of the config ending in the middle of the security header line and the website is not accessible.

![](http://i.imgur.com/eQhVXm2.png)

Additional info:
Fix your parser.

**Comment by josegonzalez** [comment]
Our upcoming changes to nginx templating will fix this by using a real template engine, but there isn't much we can do with the current setup.

For now, I think you will need to escape the quote marks in your custom nginx configuration. Can you try that and let us know if it worked?

**Comment by enjikaka** [comment]
![](http://i.imgur.com/GnfrHgp.png)

This worked. Thanks.

**Comment by josegonzalez** [comment]
Cool cool.

Since this is documented [here](http://dokku.viewdocs.io/dokku~v0.4.14/nginx/), I think we can close this :)
