### ISSUE TITLE
dokku_client.sh can't connect to SSH with custom port

### ISSUE THREAD

**Issue by julienma** [dokku/dokku#1942]
Description of problem:
My remote SSH is not on port 22, so the `dokku` command does nothing.

Proposed solution:
As there's already a DOKKU_HOST env var, there could be a DOKKU_PORT optional env var.
If set with a port number, use it, otherwise fallback to default 22.

**Comment by u2mejc** [comment]
@julienma do you mind explaining the advantage to making this a new env var, vs adding the port for the server to your ~/.ssh/config file?

**Comment by julienma** [comment]
@u2mejc I shouldn't have made any proposition, as I don't know at all how dokku_client.sh works.
Anyway, I already set up my ssh alias in ~/.ssh/config, including port number.
It seems dokku_client.sh still can't connect to my dokku server.

(In the meanwhile, I found https://github.com/SebastianSzturo/dokku-cli which works perfectly, so I won't bother you with that issue).

**Comment by u2mejc** [comment]
@julienma Please never regret asking for help, I'm glad you were able to get it working. :wink: 

For reference, he're my alias that works with dokku_client.sh:
```
Host dokku.me
    HostName 127.0.0.1
    Port 2222
```
