### ISSUE TITLE
gitter

### ISSUE THREAD

**Issue by fruitl00p** [dokku/dokku#1944]
There isn't currently a gitter room for [dokku/dokku](gitter.im/dokku/dokku) To spur the collaboration amongst plugin developers / users alike i'd like to propose adding a room. This (imho) wouldn't have to be a busy room with continual presence of any 'official' users, but it would at least allow quick question / answers and shorten the feedback loop :)

Thanks!

**Comment by jvanbaarsen** [comment]
I believe there is also a IRC and Slack channel. I would be in favour of keeping only those two channels around. Since it lowers the amount of communication overhead in different channels.

**Comment by fruitl00p** [comment]
And there you go: missed the slack channel :) Thanks. This atleast is now 'documented' for anyone looking for a gitter channel :)

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by josegonzalez** [comment]
IRC works just as well too, and it's linked to in the readme. The channel is logged as well.
