### ISSUE TITLE
Custom DOKKU_IMAGE

### ISSUE THREAD

**Issue by lazydino** [dokku/dokku#1946]
Can I specify a custom DOKKU_IMAGE  on per-application basis? Would it work if I put something like "DOKKU_IMAGE=myrepos/mydokku" in the .env file on to my repos root like with custom BUILDPACK_URL?

**Comment by josegonzalez** [comment]
No, that is not currently possible. What use case do you have?

**Comment by lazydino** [comment]
I use DOKKU to deploy my node application that makes call to some legacy code done In .NET through edge.js ( https://github.com/tjanczuk/edge ) I could not find a proper node buildpack that includes MONO runtime at the moment, so I just made a custom DOKKU_IMAGE for it to support the deployment. I have other projects that don't require MONO runtime I'd like to deploy with DOKKU, so I wonder if DOKKU has the flexibility to do to accommodate different base image for different applications.

The multi buildpack_urls doesn't really help in my situation, since the .NET-node bridge interface needs to get compiled and installed during 'npm install'. I don't really need DOKKU to detect and run .NET console program , it is just that my build environment need to support .NET runtime. I guess I could just learn how to develop a custom buildpack myself.

**Comment by josegonzalez** [comment]
You could probably fork the node buildpack and install mono before the `npm install` command. I think you might also be able to run commands via the `scripts.preinstall` option as [documented here](https://docs.npmjs.com/misc/scripts).

**Comment by josegonzalez** [comment]
@michaelshobbs thoughts here? I'm of the opinion that forking and specifying a custom buildpack should be enough, but up to you...

**Comment by lazydino** [comment]
Yeah, but for developer who doesn't want to spend time learning  customizing buildpack , per application DOKKU_IMAGE will be nice.

**Comment by josegonzalez** [comment]
Personally I don't see how thats more work than customizing the herokuish image....

**Comment by michaelshobbs** [comment]
My thoughts:

There's this buildpack that seems pertinent: https://github.com/friism/heroku-buildpack-mono
Perhaps that buildpack in concert with the multi and nodejs buildpacks would work? (I'm not clear as to why the multi buildpack wouldn't work)
Maybe the dokku-apt plugin could to install the mono package assuming it's available via apt?

The simplest answer to the image question, however, is to use the mono image with all your apps and just be ok with it. The more complex answer is to write a buildpack if none of the aforementioned ideas work for you. Good news is it's a very simple API. (`bin/detect`, `bin/compile`, `bin/release`)
