### ISSUE TITLE
Redirect www to non-www

### ISSUE THREAD

**Issue by jvanbaarsen** [dokku/dokku#1949]
I'm currently looking at ways to redirect my apps to their non-www domain name, I think there are two options:

1. Use the domain-redirect plugin (https://github.com/dokku/dokku-redirect)
2. Use NGINX redirect with the custom NGINX template

For option 2, I need the server_name, but this is set dynamically by Dokku right? Is there a way to loop over all the available server_names and add the redirect per server_name? The benefit of this, is that I can keep the configuration in my app git repo.

(I removed the issue template since I feel it did not apply here)

**Comment by u2mejc** [comment]
Option two shouldn't require anything special, the custom nginx config is imported for each app you push?

Also, there are a myriad of other ways to do redirects, your app framework probably provides another. I've been deploying redirects using S3 (static site redirect) and cloudfront to terminate SSL.

**Comment by jvanbaarsen** [comment]
@u2mejc For option two you need to provide the app name:

```
server {
  listen      [::]:80;
  listen      80;
  server_name www.domainname.com;
  return 301 $scheme://domainname.com$request_uri;
}
```

So for every domainname, a block like this needs to be added. So its only possible if you keep the `dokku domains` in sync with this file. (Or am I missing a variable available in the config?)

**Comment by josegonzalez** [comment]
I think in 0.5.x you get a list of domain names you can iterate over. @michaelshobbs is that correct?

**Comment by josegonzalez** [comment]
Okay so there you go. I think you can maybe try some bash magic in your template, but otherwise there isn't much to do with this issue. Closing.

**Comment by jvanbaarsen** [comment]
Great! Then I'll wait till 0.5 and for now I'll use the redirect plugin :-)

**Comment by seospace** [comment]
What's the current way to handle that redirect? I have this via dokku redirect plugin:
````www.example.pl  example.pl  301````
And its not working.

**Comment by Loschcode** [comment]
I'm also curious about the www redirect since I'm facing the same issue

**Comment by josegonzalez** [comment]
If you need to redirect from www to non-www - or vice-versa - then you can modify your `nginx.conf.sigil` to do so.

**Comment by seospace** [comment]
@Loschcode try this https://github.com/dokku/dokku/issues/3075#issuecomment-366807867
