### ISSUE TITLE
Dokku run commands defined in Procfile?

### ISSUE THREAD

**Issue by pascalw** [dokku/dokku#1952]
Heroku allows you to run commands defined in the Procfile using `heroku run`. For example `heroku run console` will run the command defined in your Procfile as the `console` process type.

I noticed that Dokku doesn't seem to support this. Would you accept a PR that would add this functionality? I'm thinking it could work as follows:

* On `dokku run` check if the provided command name corresponds with a proc type defined in the Procfile.
  * If match -> execute the command specified for that proc type
  * Else -> execute the command as is

This should be mostly backwards compatible. Theoretically if someone would have a Procfile with a proc type that corresponds to a name of something in `$PATH` this could break. Perhaps we could even check if the name is in `$PATH` and skip Procfile execution if it is.

**Comment by josegonzalez** [comment]
Sure, go for it. Remember to write tests and add documentation :)

**Comment by josegonzalez** [comment]
@pascalw *bump*

**Comment by pascalw** [comment]
Hey sorry have been very busy. I've looked into how to implement it and it's pretty trivial (herokuish supports executing procttypes directly) but haven't gotten around to writing the tests and docs.

Will try to work on it this week.

**Comment by pascalw** [comment]
Thinking about this some more I think Dockerfile deployments now also support Procfiles right? In that case it's better not to rely on Herokuish to execute the Procfiles command but use Dokku's Procfile parsing since that would work in both cases.

**Comment by josegonzalez** [comment]
Works for me.

**Comment by michaelshobbs** [comment]
What happens if a `Procfile` key matches a command? (ex. `bash: echo 'you probably should not do this`)

Would the `Procfile` key take precedence?

**Comment by josegonzalez** [comment]
Yes, that seems reasonable to me.

We could probably output "Detected command from Procfile, running that command" as a warning...

**Comment by pascalw** [comment]
@michaelshobbs I described this in the original issue. 
The most robust approach would be to not run the Procfile command if the key corresponds with a name in $PATH in the container, however that's not particularly easy I think and also might yield some unexpected results.

Outputting a message when this behavior kicks in seems reasonable to me.

**Comment by josegonzalez** [comment]
Closing as this is taken care of by #1952.
