### ISSUE TITLE
dokku run broken in pre-deploy

### ISSUE THREAD

**Issue by ebeigarts** [dokku/dokku#1954]
Previously I could use `dokku run` in `pre-deploy` hooks, but now it shows:

```
remote: app image (dokku/<app>:<hash>) not found
```

The `<hash>` is the previous image not the `latest`, I think it previously used the latest one (the one that was just built).

I think this happened somewhere between 0.4.10 - 0.4.14.

This also [broke](https://github.com/mlomnicki/dokku-deploy-hooks/issues/10) dokku-deploy-hooks plugin.

**Comment by michaelshobbs** [comment]
This is a change in docker 1.10. Downgrade to docker 1.9 until dokku 0.5 is released.
