### ISSUE TITLE
Feature request: allow bypassing the "default container check" for non-web / worker processes

### ISSUE THREAD

**Issue by trevorturk** [dokku/dokku#1956]
Feature request: allow bypassing the "default container check" for non-web / worker processes. 

When an app contains non-web components, it's impossible to bypass the "default container check" which pauses for 10 seconds during a deploy. 

For example, if you have a Rails app with a web process and a worker process, you can use the CHECKS file to ensure zero-downtime deployments, but the CHECKS file can only reference the web process. Having enabled a worker process in DOKKU_SCALE, deployments take an unnecessary extra 10 seconds and there is no way to bypass the pause. 

I found this surprising. I expected that once the check was satisfied, the deploy would carry on. Perhaps there are use-cases where the delay makes sense, and so changing a default would be dangerous. If so, I think the simplest solution would be to add an option to the CHECKS file to disable the default container check. This could also be used for deployments where there is no need for a delay and no need for any checks. 

Perhaps the least effective change would be to allow the wait time to be configurable, such as:

`DOKKU_DEFAULT_CHECKS_WAIT=0`

...where the default could remain 10, but would be configurable, and accept `0` as a valid option to skip entirely. This would meet my needs, where I'd like to check the web process only, would be backward compatible, and would be a relatively small change. 

(`DOKKU_DEFAULT_CHECKS_WAIT` appears to be the internal name, so perhaps the CHECKS file could use `DEFAULT_WAIT`.)

See also: #1661 and #1872 /cc @josegonzalez

**Comment by josegonzalez** [comment]
@michaelshobbs might be worth it to turn the `CHECKS` file into some sort of ini-parsed file format instead...

**Comment by josegonzalez** [comment]
@trevorturk if I gave you a spec, would you be willing to work on the feature?

**Comment by trevorturk** [comment]
Sure thing!

**Comment by michaelshobbs** [comment]
Why is this a problem? We wait the to ensure that the worker process at least hung around long enough to even potentially be useful. I think a better feature might be to check that the process actually fired up.

**Comment by trevorturk** [comment]
@michaelshobbs it's not a huge problem, but in my case I have a "web" a "worker" and a "cron" process, which I think would be fairly common for a Rails app. So, when I deploy, I have to wait an extra 20 seconds for the default container checks to complete, when I'm happy once my custom web check is complete. 

I dunno about you, but when I know something is going to pause for 20 seconds it's long enough for me to check Twitter and lose my train of thought :grin:

**Comment by trevorturk** [comment]
(I agree it would be ideal if we could check that the worker process actually fired up, but I'm not sure how to do that... it's a long-running process so I don't believe we can check the return value or anything like that. Maybe you guys have a better idea than I do, though.)

**Comment by michaelshobbs** [comment]
I think the 'correct' solution here (given the current options) is to implement a `CHECKS` entry for your web app and drop `DOKKU_DEFAULT_CHECKS_WAIT` to `0`. This would essentially give you the desired functionality with no more code complexity. Maybe the action item here is to make this clearer in documentation?

**Comment by trevorturk** [comment]
Ah, I didn't realize I could configure `DOKKU_DEFAULT_CHECKS_WAIT` -- that's pretty much what I was suggesting. Are you saying if I add a line `DOKKU_DEFAULT_CHECKS_WAIT=0` to my CHECKS file it'll "just work" for my case? (If so, then I think this can just be a request for additional documentation, which I'd be happy to work up.)

**Comment by michaelshobbs** [comment]
Not in the `CHECKS` file but as a config variable. 
```
dokku config:set --no-restart <APP> DOKKU_DEFAULT_CHECKS_WAIT=0
```

**Comment by josegonzalez** [comment]
http://dokku.viewdocs.io/dokku/checks-examples/

**Comment by trevorturk** [comment]
That did it! Thank you for being so patient with me. I should have read that documentation more closely and tried to set the config globally to 0 before hassling you. 

Would you be interested in reviewing a PR if I worked up a few changes to the checks-example documentation to help clarify this sort of case? I think it would be useful for others, but perhaps I'm just new to Dokku and this'll all seem obvious to be in another week or two.

**Comment by josegonzalez** [comment]
Sure, documentation PRs are always welcome.

**Comment by michaelshobbs** [comment]
Yes! We'd love some help with docs; especially from new users. Fresh eyes are always good.
