### ISSUE TITLE
RFC: enable debug output for dokku global exports in trace

### ISSUE THREAD

**Issue by u2mejc** [dokku/dokku#1957]
- Description of problem:

Dokku exports are not constant, `dokku trace on` does not yield custom set variables in stdout.

- Proposal:

Move `[[ $DOKKU_TRACE ]] && set -x` toward the top of the `dokku` file to capture global env vars in trace.

Thoughts? Be a better mind reader?

**Comment by josegonzalez** [comment]
Has this been an issue in the past when debugging issues?

**Comment by u2mejc** [comment]
> Has this been an issue in the past when debugging issues?

I've personally experienced it.

**Comment by josegonzalez** [comment]
I don't really have an opinion either way.

One thing is that `dokku trace on` sets debug in those global env vars, so you'd have to source the files twice...

**Comment by josegonzalez** [comment]
Closing as there is a PR open.
