### ISSUE TITLE
Documentation unclear as far as where the CHECKS file should be located

### ISSUE THREAD

**Issue by haliphax** [dokku/dokku#1962]
Description of problem:

I have tried placing a CHECKS file in the root of the git repository for my application, the application's subdirectory in `/home/dokku`, the root of the container filesystem that runs the resulting Dockerfile build, and the directory of the launch point for my Python Flask application, but dokku just doesn't find my CHECKS file in any of those places. It would help if the documentation was a bit more clear as to specifically where this file needs to be placed in order to be processed properly.

Output of the following commands

- `uname -a`: `Linux gir 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.): Digital Ocean

How was dokku installed?: bootstrap command from this git repo

How reproducible: Doing this on all of my machines so far :P

Steps to Reproduce:
1. Install Flask application as a local Python package
2. Run the app server as a module (`python -m modulename`)

**Comment by josegonzalez** [comment]
It should be in `/app/CHECKS`. I will update the docs now to refer to that.

**Comment by michaelshobbs** [comment]
Perhaps we can adapt @pmac's method of getting a file from a dockerfile `WORKDIR` to make this more flexible.

**Comment by josegonzalez** [comment]
Maybe. Feel free to PR (though I'm not holding 0.5.x for this)

**Comment by haliphax** [comment]
By `/app/CHECKS`, do you mean a folder called 'app' at the root of the Docker container for the application? Or do you mean the application's subdirectory in `/home/dokku`?

**Comment by josegonzalez** [comment]
Dockerfile-based deploys can specify any directory within the docker container. In this case, we expect the path `/app/CHECKS` within the container to have the contents of the checks file. In other words, the easiest way would be to set your `WORKDIR` to `/app` and add the contents of your repository to that path.
