### ISSUE TITLE
GitHub Integration/ Pull from repo

### ISSUE THREAD

**Issue by zimt28** [dokku/dokku#1966]
Is it possible to somehow link a Dokku app to a GitHub repo (+ branch)? It would be cool if, on push, Dokku would pull from GitHub or any other repo specified. If this doesn't exist, having such `pull` functionality might be a nice feature, webhooks shouldn't be hard to do then!

**Comment by michaelshobbs** [comment]
There is no built-in feature to do this. I personally use CircleCI's deployment hooks to handle this. Sounds like a good fit for a community plugin.

**Comment by trevormerritt** [comment]
I use gitlab with gitlab-ci and documented it here...

https://geekb4ck.wordpress.com

Hope this gives you an idea of another way.  :)

**Comment by mderazon** [comment]
That would be great. One of the nice things about Heroku is that you don't need a CI in the middle if you want continuous deployments. 

If anyone know such plugin, please document it here.
