### ISSUE TITLE
Serve multiple domains with a single deployment

### ISSUE THREAD

**Issue by aschuch** [dokku/dokku#1967]
I would like to setup dokku to serve 3 different websites/web apps over the following 3 URLs.
* a.com
* b.com
* api.b.com
 
I have read the documentation regarding [`dokku domains`](http://dokku.viewdocs.io/dokku/nginx/#domains-plugin) but its not clear to me how to achieve the aforementioned setup.

I guess I could do the following:

1. Set a.com as my dokku domain
* Create app a which makes it available at a.a.com
* Create app b which makes it available at b.a.com
* Create app api.b which makes it available at api.b.a.com
* Then route a.com to a.a.com, b.com to b.a.com and api.b.com to api.b.a.com (via DNS)

Not sure if that would be the recommended setup.
Any help would be much appreciated :+1:

**Comment by trevormerritt** [comment]
*i* would use something like

Dokku.a.com for Dokku and then a.com, b.com, api.b.com as unique apps with
domain entries.

Would that fit the bill?

**Comment by aschuch** [comment]
Hm, not exactly sure what you mean. Is it possible to have multiple domains pointing to different apps served by dokku? If so, can you give me an example with `dokku domains` and/or `git remote add` that points me in the right direction?
Thanks a lot.

**Comment by trevormerritt** [comment]
Hey Alexander,

DNS:
** a.com zone **
dokku IN A 1.2.3.4
@ IN A 1.2.3.4

** b.com zone **
api IN A 1.2.3.4
@ IN A 1.2.3.4

DOKKU:
Install to dokku.a.com
Push to dokku@dokku.a.com:/my_app_here

app1 -> Domains: a.com, app1.dokku.a.com (can remove if desired)
app2 -> Domains: b.com, app2.dokku.a.com (can remove if desired)
app3 -> Domains: api.b.com app3.dokku.a.com (can remove if desired)

Does this make sense for you?


On Fri, Mar 4, 2016 at 2:59 PM, Alexander Schuch <notifications@github.com>
wrote:

> Hm, not exactly sure what you mean. Is it possible to have multiple
> domains pointing to different apps served by dokku? If so, can you give me
> an example with dokku domains and/or git remote add that points me in the
> right direction?
> Thanks a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku/dokku/issues/1967#issuecomment-192440913>.
>



-- 
Trevor Merritt
GMail user

**Comment by aschuch** [comment]
Thanks a lot for your help, I think I got it now.

To summarize, I'd create a remote for my app1 via `git remote add dokku dokku@dokku.a.com:app1`, then via add the a.com domain `dokku domains:add app1 a.com` and point DNS of a.com to the IP of the server (1.2.3.4 in your example). 

Correct? :sparkles:

**Comment by trevormerritt** [comment]
Exactly!

**Comment by aschuch** [comment]
Great, thanks again for your help. Much appreciated. :100:
