### ISSUE TITLE
! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by tomspeak** [dokku/dokku#1968]
Description of problem:

When I run `git push production` I get this error:

```
-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)
remote: /tmp/buildpacks/heroku-buildpack-nodejs/lib/dependencies.sh: line 1:   265 Killed                  npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1

-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/

       Love,
       Heroku

To dokku@[ip]:app.app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@[ip]:app.app'
```

Output of the following commands

- `uname -a`:

`Linux pomodo.work 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

- `free -m`:

```
           total       used       free     shared    buffers     cached
Mem:           490        104        385          0          7         39
-/+ buffers/cache:         58        431
Swap:            0          0          0
```

- `docker version`:

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```

- `docker -D info`:

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 9
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: app.app
ID: ZGA4:Q32P:N6JL:LS7H:3INU:FAQL:XFDY:XN3D:3TOJ:Y7CB:EX5Q:Z43C
WARNING: No swap limit support
```

- `sigil -v`:

`sigil: command not found`

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:

```
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v5
```

- `dokku version`:

`0.4.14`

- `dokku plugin`:

```
plugn: dev
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```

- `docker inspect CONTAINER_ID` (if applicable):

N/A cannot deploy

- `cat /home/dokku/<app>/nginx.conf` (if applicable):

N/A cannot deploy

- Link to the exact repository being deployed (if possible/applicable):

Private repo (can give access on requeset)

- If a deploy is failing:
  - the type of application being deployed (node, php, python, ruby, etc.)

`Node`

  - whether or not you have a `Dockerfile` in the root of your repository

`No`

  - if using buildpacks, which custom buildpacks are in use

`Webpack`

- Output of failing dokku commands after running `dokku trace on`

How was dokku installed?:

Digital Ocean one click app

How reproducible:

1. Fresh install of digital ocean app
1. (local) git remote add production dokku@[ip]:app.app

Actual Results:

I am given the error message at the top of the issue

Expected Results:

My master branch (current branch I am on) to be pushed to my server, built and deployed.

Additional info:

This is working on heroku, but fails when trying the exact same setup with dokku.

**Comment by michaelshobbs** [comment]
Looks like maybe a network issue somewhere in docker or your server. Additionally it could be the version of the buildpack. You can set the `BUILDPACK_URL` config variable to the github URL of the Heroku nodejs buildpack to test the latter hypothesis.

**Comment by radicaled** [comment]
Looks like you're running on a 512MB instance. Could it be this? http://dokku.viewdocs.io/dokku/advanced-installation/#vms-with-less-than-1gb-of-memory

**Comment by michaelshobbs** [comment]
Ah good catch. Definitely run on a 1gb instance or add some swap

**Comment by tomspeak** [comment]
Thank you, this seems to have fixed it. I was an idiot that thought the 1gb rule would not apply, I presumed that was for large apps not 170kb JavaScript files.

**Comment by michaelshobbs** [comment]
I don't blame you for wanting to go slim on the memory. 

Unfortunately the process of building the app isn't free. In fact, it's actually fairly costly. 😄

**Comment by tomspeak** [comment]
Dokku is so damn convenient and well put together, I will just have to be stoic about the +$5 extra a month fee from DigitalOcean.

**Comment by michaelshobbs** [comment]
As they say, time = money
