### ISSUE TITLE
Dokku Installation on Aliyun (Without PackageCloud)

### ISSUE THREAD

**Issue by jonathankau** [dokku/dokku#1970]
Description of problem:

Running the bootstrap.sh installation script for dokku on an Aliyun instance doesn't work because packagecloud servers are inaccessible. Is there any way to package dokku separately to circumvent this issue?

Output of the following commands

- `uname -a`:
- `free -m`:
- `docker version`:
- `docker -D info`:
- `sigil -v`:
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
- `dokku version`:
- `dokku plugin`:
- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing:
  - the type of application being deployed (node, php, python, ruby, etc.)
  - whether or not you have a `Dockerfile` in the root of your repository
  - if using buildpacks, which custom buildpacks are in use
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.):

How was dokku installed?:

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Additional info:

**Comment by michaelshobbs** [comment]
You could try installing from source. Check out the `Vagrantfile` for details. It's not an officially supported method however. You could also attempt to build the packages from a local vagrant machine. There is a profile for building the .deb files in the `Vagrantfile` as well. Again, not officially supported.
