### ISSUE TITLE
Should the installer check for its two "hard" requirements?

### ISSUE THREAD

**Issue by radicaled** [dokku/dokku#1971]
By "hard" requirements, I mean FQDN and > 1GB of memory.

I was surfing through the closed issues looking for something else, and by coincidence I saw that quite a few of them were from some people running on 512MB virtual machines.

These requirements are pointed out in the documentation, but if you're following steps from a tutorial somewhere they're not liable to mention either requirement and could cause some confusion that the installer could easily clear up with a warning and a link to the requirements page.

**Comment by michaelshobbs** [comment]
A FQDN is not a hard requirement. You can use dokku to run services that are only IP based. The 1gb issue can also be solved by additional swap space. 

Perhaps the installer can warn in the latter scenario.

**Comment by radicaled** [comment]
> A FQDN is not a hard requirement.

The documentation at http://dokku.viewdocs.io/dokku/installation/ sort of implies that a FQDN set is. Maybe this should be clarified? It's not a minimum requirement if the system is fully functional without it.

> Perhaps the installer can warn in the latter scenario.

I think it should. Ages ago I followed someone's Dokku tutorial (DigitalOcean's?), ended up with a 512MB system running Dokku for Rails app, and suffered mysterious deploy failures from time to time until I debugged the error by hand and then upped the memory usage.

**Comment by michaelshobbs** [comment]
Definitely agree the docs could be made more clear. Documentation PRs are always welcomed for sure.

**Comment by josegonzalez** [comment]
I don't think we should check for it. If a user wants to ignore the docs, thats fine by me.

We might want to add a little blurb on our landing page with the 1gb requirement.

**Comment by radicaled** [comment]
Interesting -- I've found that running Dokku in a 512MB VM just isn't enough when you start deploying applications. I guess it works OK if you're deploying an application with a slimmer memory footprint, so I can see why you wouldn't want to do any kind of sanity check.

**Comment by josegonzalez** [comment]
That's correct, which is why the documentation states you need at least 1GB of ram, and then points you in the direction of setting up swap if you don't have that.

**Comment by adrianmoya** [comment]
@michaelshobbs @radicaled I added the FQDN requirement to the docs in the past, because of #1390 . I'm not sure if recent versions work without the FQDN.

**Comment by michaelshobbs** [comment]
You don't have to have a FQDN in all scenarios as I mentioned previously. It's definitely the primary use-case, however.
