### ISSUE TITLE
Erlang buildpack's PATH ignored

### ISSUE THREAD

**Issue by sergium** [dokku/dokku#1972]
dokku: v0.4_1.3

Heroku's erlang-build-pack (master): https://github.com/heroku/heroku-buildpack-erlang

Looks like this part of the erlang's build-pack is ignored in the new dokku:

file bin/release
```
config_vars:
  PATH: /app/otp/bin:bin:/usr/bin:/bin
```

In 0.3.x it was ok.

**Comment by michaelshobbs** [comment]
We're going to need some more info. Please provide the information requested in the issue template.

**Comment by sergium** [comment]
@michaelshobbs  - are you serious) ?

IMHO it's quite obvious that in 0.4.x - code responsible for updating PATH moved to the bin/compile (I've checked it with the clojure's buildpack)


But, Ooook...

-------

Description of problem:

Heroku's erlang build-pack does not work.

https://github.com/6/heroku-erlang-example

Crashing with error:
` /bin/sh: 1: erl: not found`

Output of the following commands

- `uname -a`: 
Linux Ubuntu-1404-trusty-64-minimal 3.13.0-46-generic #76-Ubuntu SMP Thu Feb 26 18:52:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- `free -m`:
             total       used       free     shared    buffers     cached
Mem:         32039      10834      21204          2        507       6157
-/+ buffers/cache:       4169      27869
Swap:        16375          0      16375


- `docker version`:

Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64


- `docker -D info`:

Containers: 36
 Running: 9
 Paused: 0
 Stopped: 27
Images: 189
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 255
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.29 GiB
Name: Ubuntu-1404-trusty-64-minimal
ID: ZKCK:POCM:UXYC:OL26:UH4Z:ZFGJ:ZD7E:4P3I:MFB3:7KRI:5TNL:WJH5
WARNING: No swap limit support


- `sigil -v`:

sigil: command not found


- `docker run -ti gliderlabs/herokuish:latest herokuish version`:

herokuish: 0.3.8
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v5




- `dokku version`:

v0.4_1.3


- `dokku plugin`:

  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  apt                  0.4.0 enabled    Inject deb packages into dokku based on files in project
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  cloudgears           1.0.0 enabled    dokku cloudgear plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

- If a deploy is failing:
  - the type of application being deployed (node, php, python, ruby, etc.)
     Erlang

  - if using buildpacks, which custom buildpacks are in use

     https://github.com/heroku/heroku-buildpack-erlang


- Output of failing dokku commands after running `dokku trace on`

  ` /bin/sh: 1: erl: not found`



How was dokku installed?:
  http://dokku.viewdocs.io/dokku/installation/


How reproducible:
  Every time.


Steps to Reproduce:
1. add .env with this content: BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-erlang.git
2. try to push to dokku this erl-example project: https://github.com/6/heroku-erlang-example


Actual Results:
  ` /bin/sh: 1: erl: not found`

Expected Results:
   erl is found


Additional info:
 If you replace in the Procfile "erl" with "/app/otp/bin/erl"  it would work 'as expected'

**Comment by michaelshobbs** [comment]
I am indeed serious. Please remember you are coming to an OSS project for assistance. 

I have no personal experience with this buildpack and it is thus far unclear to me how dokku would be modifying the `PATH` variable. So the more information we have, the better equipped we will be to assist.

I am currently not near a terminal but once I am, I will be happy to investigate your issue further. In the meantime, if you find anything else might be useful, please post it here. 

Of note, however, dokku moved from buildstep to herokuish as its base image and method of executing buildpacks. I suspect if this is not a buildpack issue, then the issue most likely lies in there. 

Additionally a gist of your broken deployment with dokku trace enabled, would also be useful. Please be sure to strip any secrets that might be included in that output. If possible, include a sample repo that we might be able to use to recreate this issue. 

You mentioned having checked this issue with the clojure buildpack. Can you elaborate? If you already have an idea of the fix, we openly welcome PRs. Otherwise any additional info you have obtained in your own troubleshooting would be welcomed as well.

**Comment by sergium** [comment]
@michaelshobbs ok, - I've updated issue according the template, please take a look.

Regarding the clojure buildpack - please take a look at this commit:

https://github.com/heroku/heroku-buildpack-clojure/commit/fa651bc0c0de1a339566819fd9229594fb991ae3

With the comment:  "The `compile` step sets proper PATHs etc."

IMHO - it's the reason why it works with clojure and does not work anymore with erlang.

I'm not sure it's dokku-issue or  heroku-buildpack-erlang, but with the same version of heroku-buildpack-erlang and prev. version of dokku (0.3.x) it worked well -> IMHO it's on the dokku-side.

**Comment by michaelshobbs** [comment]
Curious, does this deploy on Heroku?

**Comment by michaelshobbs** [comment]
@sergium Herokuish (the underlying base image that dokku uses to build apps) definitely isn't doing anything with `config_vars` section of the `.release` file. Do you know what version of `buildstep` you were using with dokku `v0.3`?

**Comment by michaelshobbs** [comment]
Scratch that. I found the issue.

In buildstep, they used to pull in `config_vars` from `.release`. See here: https://github.com/progrium/buildstep/blob/42bd9f4aab6c29041c0854c1af742215242a7318/builder/compile.sh#L90-L92

In herokuish, they don't do anything with at section. Please file an issue [there](https://github.com/gliderlabs/herokuish/issues) and I'll see about getting a patch pushed to enable this functionality ASAP.

**Comment by michaelshobbs** [comment]
PR opened
