### ISSUE TITLE
Configuring container network options

### ISSUE THREAD

**Issue by madshargreave** [dokku/dokku#1976]
Hi

I want to disable the userland-proxy so I can receive the remote IP of clients, instead of the container

How can this be done?

**Comment by josegonzalez** [comment]
What do you mean by "remote ip of the clients"? That's already passed as a header in `X-Forwarded-For`.

In our upcoming 0.5.x, you'll be able to disable nginx completely (or swap to your own custom proxy solution), which should allow you to do what you need.

Does this help?

**Comment by u2mejc** [comment]
+1 to use the X-Forwarded-For header, this is pretty standard.

**Comment by josegonzalez** [comment]
Closing as I think we have a good solution for 0.4.x and 0.5.x will allow you to completely disable the nginx proxy in favor of your own solutions.
