### ISSUE TITLE
How can i open port for using Socket?

### ISSUE THREAD

**Issue by pavei** [dokku/dokku#1977]
Description of problem:
Hi,

I'm using the lastest version of Dokku. I have an application that runs on 80 and i need to expose a port for a socket connection. How can i do this?

**Comment by michaelshobbs** [comment]
Some clarifying questions....
- When you say latest version, do you mean latest release (`0.4.14`) or do you mean the master branch?
- When you say socket, do you mean http, websocket, plain old TCP socket, or something else?

**Comment by pavei** [comment]
Sorry about my bad informations:

1 - 0.4.14
2 - TCP Socket (it is an GPS device, that make  connection)

**Comment by michaelshobbs** [comment]
This should help: http://dokku.viewdocs.io/dokku~v0.4.14/nginx/#disabling-vhosts

Once you disable vhosts for the app, set the `DOKKU_NGINX_PORT` config variable to your desired listening port.

**Comment by pavei** [comment]
Hmmm,

But if i use postgres plugin, i can expose a port with one command and still using VHOST.

**Comment by josegonzalez** [comment]
The postgres plugin and how dokku manages vhosts are two separate concerns. Our primary use-case is for http processes, and for the existing 0.4.x series, we don't have a good story around tcp-based load balancing.

In the upcoming 0.5.x release, we will have the ability to disable nginx or swap the proxying for another service such as haproxy, which may help serve you better.

**Comment by louisbl** [comment]
The [dokku-haproxy plugin](https://github.com/256dpi/dokku-haproxy) could help you. It allows to expose tcp ports through haproxy.

**Comment by pavei** [comment]
@louisbl  It wooooooorks! Thanks a looooooot!
