### ISSUE TITLE
no tty present and no askpass program specified / fatal: 'app' does not appear to be a git repository

### ISSUE THREAD

**Issue by Corstiaan84** [dokku/dokku#1984]
- I have setup a fresh ubuntu 14.04 vps
- I have installed dokku
- I have added my key through the web admin
- I have created a dukku app
- I have added a new remote to my local repo like so: ````git remote add superbad corstiaan@serverip:app-name````

where "corstiaan" is the sudo user set during ubuntu install

When pushing my app like so: ````git push superbad````

I get ````fatal: 'everseller' does not appear to be a git repository````

I tried adding a deploy user for "corstiaan" (I thought this would not be necessary because I set a key in the web admin) like so ````cat ~/.ssh/id_rsa.pub | ssh corstiaan@serverip "sudo sshcommand acl-add dokku corstiaan"````, as per the docs.

However, this gave me this message: ````sudo: no tty present and no askpass program specified````

I "fixed" this by adding ````corstiaan ALL=(ALL) NOPASSWD: ALL```` to the sudoers file using ````sudo visudo````

Then, when running  ````cat ~/.ssh/id_rsa.pub | ssh corstiaan@serverip "sudo sshcommand acl-add dokku corstiaan"```` again, I see the fingerprint/key

When I run ````git push superbad```` now, I still get ````fatal: 'everseller' does not appear to be a git repository````.

What am I missing?

ps again, this is a fresh unbuntu install. When using the dokku droplet image the past, all worked well.

**Comment by michaelshobbs** [comment]
Have you sanity checked the authorized_keys file? Make sure only one entry for your key is in there. Perhaps the first attempt made an entry that doesn't have all the right options to wire up dokku to ssh.

**Comment by Corstiaan84** [comment]
I fixed it by removing the remote ````superbad```` and re-adding it like this: ````git remote add superbad dokku@serverip:app-name````.

Initially I added it liek ````git remote add superbad corstiaan@serverip:app-name````, which was wrong.

Thanks!
