### ISSUE TITLE
Use linux/alpine as runtime

### ISSUE THREAD

**Issue by qqiangwu** [dokku/dokku#1986]
Currently we build our code using herokuish and bundle the whole app into it. The result image is > 1G and full of unrelated runtimes. 

So, is it possible to build source code using herokuish and bundle the result with an alpine runtime into a lightweight container?  eg.

```bash
      alpine)
        # build source code 
        docker run $DOKKU_GLOBAL_RUN_ARGS --rm -v $CACHE_DIR:/cache -v $PWD:/app -e CACHE_PATH=/cache $DOCKER_ARGS $DOKKU_IMAGE /build

        # build the image
        DOCKERFILE_PORT=$(get_dockerfile_exposed_port Dockerfile)
        [[ -n "$DOCKERFILE_PORT" ]] && config_set --no-restart $APP DOKKU_DOCKERFILE_PORT=$DOCKERFILE_PORT
        plugn trigger pre-build-dockerfile "$APP"

        [[ "$DOKKU_DOCKERFILE_CACHE_BUILD" == "false" ]] && DOKKU_DOCKER_BUILD_OPTS="$DOKKU_DOCKER_BUILD_OPTS --no-cache"
        DOCKER_ARGS=$(: | plugn trigger docker-args-build $APP $IMAGE_SOURCE_TYPE)
        docker build -f Dockerfile.alpine $DOCKER_ARGS $DOKKU_DOCKER_BUILD_OPTS -t "$IMAGE" .

        plugn trigger post-build-dockerfile "$APP"
```

Users need to provide Dockerfile.alpine, which may be the following:

```Dockerfile
FROM anapsix/alpine-java:jre8

RUN adduser -S alpine

USER alpine

ADD target/zy.jar /opt/app/zy.jar

CMD ["java", "-jar", "/opt/app/zy.jar"]
```

Or we can auto-detect the runtime, provide reasonable Dockerfile and bundle the executable into it?

**Comment by josegonzalez** [comment]
I don't understand how this would work. Are you saying we should pull a binary from the herokuish and shove it into a new docker container based on alpine? I don't think that will work because things will be dynamically compiled, unless you're talking about *only* java.

**Comment by qqiangwu** [comment]
Not exactly. We can use [alpine-java](https://hub.docker.com/r/anapsix/alpine-java/) for java projects, [alpine-python](https://hub.docker.com/r/scottmiller171/alpine-python/) for python projects, and [alpine-ruby](https://hub.docker.com/r/anapsix/alpine-java/) for ruby projects. These alpine-based runtime are only 50MB or less.

**Comment by josegonzalez** [comment]
Do you mind hoping on either our irc or slack and speaking with me directly? I'm having a tough time envisioning what how this might work, or why you can't just use a dockerfile directly.

**Comment by qqiangwu** [comment]
Ok... I'll use a dockerfile directly.

**Comment by josegonzalez** [comment]
I guess it sounds like you want some sort of CI tool that will build an artifact that you can then deploy in a container via a dockerfile, is that correct?

**Comment by qqiangwu** [comment]
Yeah. That's the solution. Thank you for your time.

**Comment by josegonzalez** [comment]
Sorry, I know that's not the greatest answer. I'd be more than happy to help work out a workflow for this, just was having a tough time figuring out how it might work.

For what it's worth, I know @michaelshobbs is looking into an alpine-linux based version of herokuish, which *could* help out with image size issues. Maybe something you can help us with if you have some time?
