### ISSUE TITLE
HD with 96% of used space

### ISSUE THREAD

**Issue by nielsonsantana** [dokku/dokku#1988]
I have one server with 4 applications deployed on `dokku`.
The problem is that in this server there 20GB of HD, and only 4% is avaliable.
There are any setting to auto remove old containers?

    CONTAINER ID        IMAGE                             COMMAND                   CREATED             STATUS                       PORTS               NAMES
    a847825a7532        dokku/resultados-staging:latest   "/start web"              2 minutes ago       Exited (1) 2 minutes ago                         sleepy_torvalds
    b18a6b73498f        665a896e366b                      "/bin/bash -e -c '\nif"   2 minutes ago       Exited (0) 2 minutes ago                         adoring_kalam
    1526e4af4593        2e804d6153c1                      "/bin/bash -c 'mkdir "    2 minutes ago       Exited (0) 2 minutes ago                         sharp_newton
    57eedb414d83        ca05007d1aeb                      "/bin/bash -c 'mkdir "    2 minutes ago       Exited (0) 2 minutes ago                         gloomy_khorana
    a5011636e3a8        ca05007d1aeb                      "/start web"              3 minutes ago       Exited (1) 2 minutes ago                         hungry_hypatia
    50941aaf2738        8bc7b8b69f7e                      "/bin/bash -e -c '\nif"   3 minutes ago       Exited (0) 3 minutes ago                         silly_meitner
    f143cc52a924        86ecb3fdf193                      "/bin/bash -c 'mkdir "    3 minutes ago       Exited (0) 3 minutes ago                         furious_spence
    a29f0b475d75        96338d5e9809                      "/bin/bash -c 'mkdir "    3 minutes ago       Exited (0) 3 minutes ago                         nostalgic_fermi
    52c14d6c1175        96338d5e9809                      "/start web"              6 minutes ago       Exited (1) 6 minutes ago                         lonely_torvalds
    7d16e19e990f        e803cfe52c07                      "/bin/bash -e -c '\nif"   6 minutes ago       Exited (0) 6 minutes ago                         focused_hugle
    ea1bff89cc35        6646f3619f31                      "/bin/bash -c 'mkdir "    6 minutes ago       Exited (0) 6 minutes ago                         elegant_newton
    f4364fe3bdca        7d50775b00a1                      "/bin/bash -c 'mkdir "    6 minutes ago       Exited (0) 6 minutes ago                         focused_knuth
    680da4081c49        dokku/parceiros-staging:latest    "/start web"              10 minutes ago      Exited (1) 10 minutes ago                        clever_brattain
    4e1db1d4f695        5bfe0babaa5b                      "/bin/bash -e -c '\nif"   10 minutes ago      Exited (0) 10 minutes ago                        desperate_poincare
    9a1094d85b34        91383438dd51                      "/bin/bash -c 'mkdir "    10 minutes ago      Exited (0) 10 minutes ago                        stoic_curie
    e1f247207714        ba39fc9bc74f                      "/bin/bash -c 'mkdir "    10 minutes ago      Exited (0) 10 minutes ago                        happy_sinoussi
    aa6aca821335        4ffb693ed1ff                      "/bin/bash -e -c '\nif"   35 minutes ago      Exited (0) 35 minutes ago                        tender_leavitt
    f9540f2cd6d9        4ffb693ed1ff                      "/start web"              36 minutes ago      Exited (0) 7 minutes ago                         parceiros-staging.web.1
    5504d3fee299        2d7d1e137d31                      "/bin/bash -e -c '\nif"   36 minutes ago      Exited (0) 36 minutes ago                        awesome_jennings
    e32402528b3d        4ccec86baeeb                      "/bin/bash -c 'mkdir "    36 minutes ago      Exited (0) 36 minutes ago                        dreamy_einstein
    b0982a697460        60c13c134fa4                      "/bin/bash -c 'mkdir "    36 minutes ago      Exited (0) 36 minutes ago                        pensive_ardinghelli
    8b5b24bbc8f2        8caaeeb40fc4                      "/bin/bash -e -c '\nif"   39 minutes ago      Exited (0) 39 minutes ago                        gigantic_mestorf
    3503bf1bf8e9        8caaeeb40fc4                      "/start web"              39 minutes ago      Exited (0) 34 minutes ago                        parceiros-staging.web.1.1457840928
    6a3cdeb5cff1        15af0277040f                      "/bin/bash -e -c '\nif"   39 minutes ago      Exited (0) 39 minutes ago                        high_mietner
    83c1ca918c4e        c01ad0dc9fd3                      "/bin/bash -c 'mkdir "    39 minutes ago      Exited (0) 39 minutes ago                        serene_carson
    c6b5a3f07877        3e8d550ec39b                      "/bin/bash -c 'mkdir "    39 minutes ago      Exited (0) 39 minutes ago                        distracted_davinci
    179e2889aa8d        1135c0a763e2                      "/bin/bash -e -c '\nif"   42 minutes ago      Exited (0) 42 minutes ago                        adoring_cray
    a7e93bd40c53        1135c0a763e2                      "/start web"              42 minutes ago      Exited (0) 38 minutes ago                        parceiros-staging.web.1.1457840724
    fc6108f2f360        b03ddd1493fb                      "/bin/bash -e -c '\nif"   42 minutes ago      Exited (0) 42 minutes ago                        tiny_kalam
    43c2e22825aa        f98944db0d29                      "/bin/bash -c 'mkdir "    42 minutes ago      Exited (0) 42 minutes ago                        fervent_stallman
    c7fa0f851229        0808119df35a                      "/bin/bash -c 'mkdir "    42 minutes ago      Exited (0) 42 minutes ago                        prickly_swartz
    ece27a3a8681        4321ea9ea8ba                      "/bin/bash -e -c '\nif"   44 minutes ago      Exited (0) 44 minutes ago                        small_darwin
    712ffd446058        4321ea9ea8ba                      "/start web"              44 minutes ago      Exited (0) 41 minutes ago                        parceiros-staging.web.1.1457840533
    125824b3fd7e        21cca131c91a                      "/bin/bash -e -c '\nif"   44 minutes ago      Exited (0) 44 minutes ago                        jolly_fermat
    760424b2dbea        9ca9daa44b98                      "/bin/bash -c 'mkdir "    44 minutes ago      Exited (0) 44 minutes ago                        desperate_banach
    4346c6161b3e        2707bd305b81                      "/bin/bash -c 'mkdir "    44 minutes ago      Exited (0) 44 minutes ago                        desperate_swanson
    8307200bc26f        b7b060c0305e                      "/bin/bash -e -c '\nif"   46 minutes ago      Exited (0) 46 minutes ago                        focused_roentgen
    3f4059413efd        b7b060c0305e                      "/start web"              46 minutes ago      Exited (0) 43 minutes ago                        parceiros-staging.web.1.1457840430
    a4a307b79162        7a34da82c1df                      "/bin/bash -e -c '\nif"   46 minutes ago      Exited (0) 46 minutes ago                        naughty_easley
    df4caaac9725        4f5dc002d97c                      "/bin/bash -c 'mkdir "    46 minutes ago      Exited (0) 46 minutes ago                        jolly_swirles
    f93754415e69        9ff4d05a2e4f                      "/bin/bash -c 'mkdir "    46 minutes ago      Exited (0) 46 minutes ago                        jovial_dubinsky
    a0d0b3bc1545        ed67244978da                      "/bin/bash -e -c '\nif"   49 minutes ago      Exited (0) 49 minutes ago                        condescending_mietner
    8fe0b45c3f88        ed67244978da                      "/start web"              49 minutes ago      Exited (0) 45 minutes ago                        parceiros-staging.web.1.1457840300
    41c269eff2e8        15273fbd20ff                      "/bin/bash -e -c '\nif"   49 minutes ago      Exited (0) 49 minutes ago                        thirsty_yalow
    562e0a27ed56        4ca145efe256                      "/bin/bash -c 'mkdir "    49 minutes ago      Exited (0) 49 minutes ago                        hungry_galileo
    25b50d8889c5        3db11cf80d9c                      "/bin/bash -c 'mkdir "    49 minutes ago      Exited (0) 49 minutes ago                        adoring_poincare
    ba3b802b419d        9b7771729caf                      "/bin/bash -e -c '\nif"   2 days ago          Exited (0) 2 days ago                            sharp_bell
    ed5b76fabe45        9b7771729caf                      "/start run_migration"    2 days ago          Exited (0) 2 days ago                            website-staging.run_migrations.1
    8404f04bb63e        9b7771729caf                      "/start worker_sync_s"    2 days ago          Exited (255) 7 minutes ago                       website-staging.worker_sync_s3.1
    d9377c78a385        9b7771729caf                      "/start web"              2 days ago          Exited (0) 7 minutes ago                         website-staging.web.1
    25f2752f3155        eab23ac32b42                      "/bin/bash -e -c '\nif"   2 days ago          Exited (0) 2 days ago                            distracted_snyder
    7a10bc1dbc47        bb84c64acd33                      "/bin/bash -c 'mkdir "    2 days ago          Exited (0) 2 days ago                            sad_franklin
    e05cdde2dca1        40f757774eea                      "/bin/bash -c 'mkdir "    2 days ago          Exited (0) 2 days ago                            thirsty_brown
    e4a9a7ced3cc        6096172cf243                      "/start web"              2 days ago          Exited (6) 2 days ago                            jovial_thompson
    e94f4f99740b        6096172cf243                      "/build"                  2 days ago          Exited (0) 2 days ago                            hungry_ardinghelli
    f2ce8a53623a        e0a00b080971                      "/bin/bash -e -c '\nif"   2 days ago          Exited (0) 2 days ago                            sick_goldberg
    e4263098bed4        9fba379feab2                      "/bin/bash -e -c '\nif"   2 days ago          Exited (0) 2 days ago                            loving_perlman
    d8ef6e6f19bb        e9b9a72e1174                      "/bin/bash -c 'cat >>"    2 days ago          Exited (0) 2 days ago                            big_bardeen
    2e39914c8532        cc5525ad6922                      "/bin/bash -c 'for EN"    2 days ago          Exited (0) 2 days ago                            silly_einstein
    f5ef76c91308        cc5525ad6922                      "/bin/bash -c 'mkdir "    2 days ago          Exited (0) 2 days ago                            thirsty_swanson
    7fb73a4c5bac        2a7554aafc71                      "/bin/bash -c 'mkdir "    2 days ago          Exited (0) 2 days ago                            gloomy_fermi
    8315f8742125        2a7554aafc71                      "/bin/bash -e -c 'exp"    2 days ago          Exited (0) 2 days ago                            cranky_nobel
    a78ea6a57497        gliderlabs/herokuish              "/bin/bash -c 'mkdir "    2 days ago          Exited (0) 2 days ago                            insane_bell
    312b43dbcd11        ae26bbc48b4b                      "/start web"              2 days ago          Exited (0) 48 minutes ago                        parceiros-staging.web.1.1457840128
    9f61929884d4        7b6b3dd73230                      "/start worker_sync_s"    2 days ago          Exited (255) 2 days ago                          website-staging.worker_sync_s3.1.1457644146
    07fc0607a7c6        7b6b3dd73230                      "/start web"              2 days ago          Exited (0) 2 days ago                            website-staging.web.1.1457644145
    2a168df26571        8fc7a7ebfdef                      "/start worker_sync_s"    2 days ago          Exited (255) 7 minutes ago                       dreamy_feynman
    d74095309966        656f49a63ac1                      "/start web"              2 days ago          Exited (0) 7 minutes ago                         hopeful_franklin
    016f65d09dd8        bf85e135b695                      "/start web"              9 days ago          Exited (0) 7 minutes ago                         clever_turing
    06812c423108        c16bed9a1cf9                      "/start web"              9 days ago          Exited (0) 7 minutes ago                         determined_varahamihira
    a610ed5ca127        e4be440b239a                      "/start web"              9 days ago          Exited (0) 7 minutes ago                         cocky_dubinsky
    b18666de8715        7cf21a3959f0                      "/start web"              9 days ago          Exited (0) 7 minutes ago                         parceiros-staging.web.1.1457030649
    af03db12efaa        587d4e649fec                      "/start web"              9 days ago          Exited (0) 7 minutes ago                         mamarisk-staging.web.1
    e7f8f62cad78        ccece681c507                      "/start web"              12 days ago         Exited (0) 7 minutes ago                         resultados-staging.web.1

**Comment by nielsonsantana** [comment]
In here, the images - 144

    REPOSITORY                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    dokku/parceiros-staging    latest              e6f1ad9c9aa1        4 minutes ago       1.555 GB
    <none>                     <none>              f56579de2af0        4 minutes ago       1.555 GB
    <none>                     <none>              b553942ed704        4 minutes ago       1.555 GB
    <none>                     <none>              024576f244a7        4 minutes ago       1.555 GB
    dokku/resultados-staging   latest              dcd96a643b3a        4 minutes ago       1.55 GB
    <none>                     <none>              195b0aa2d564        4 minutes ago       1.55 GB
    <none>                     <none>              18a0729fe0bb        4 minutes ago       1.55 GB
    <none>                     <none>              5b6d797d3e70        4 minutes ago       1.55 GB
    <none>                     <none>              7d5396b33c34        16 minutes ago      1.55 GB
    <none>                     <none>              665a896e366b        16 minutes ago      1.55 GB
    <none>                     <none>              2e804d6153c1        16 minutes ago      1.55 GB
    <none>                     <none>              ca05007d1aeb        16 minutes ago      1.55 GB
    <none>                     <none>              8bc7b8b69f7e        16 minutes ago      1.55 GB
    <none>                     <none>              86ecb3fdf193        16 minutes ago      1.55 GB
    <none>                     <none>              96338d5e9809        20 minutes ago      1.55 GB
    <none>                     <none>              e803cfe52c07        20 minutes ago      1.55 GB
    <none>                     <none>              6646f3619f31        20 minutes ago      1.55 GB
    <none>                     <none>              269192f514a2        24 minutes ago      1.555 GB
    <none>                     <none>              5bfe0babaa5b        24 minutes ago      1.555 GB
    <none>                     <none>              91383438dd51        24 minutes ago      1.555 GB
    <none>                     <none>              ba39fc9bc74f        49 minutes ago      1.555 GB
    <none>                     <none>              4ffb693ed1ff        50 minutes ago      1.555 GB
    <none>                     <none>              4ccec86baeeb        50 minutes ago      1.555 GB
    <none>                     <none>              2d7d1e137d31        50 minutes ago      1.555 GB
    <none>                     <none>              60c13c134fa4        53 minutes ago      1.555 GB
    <none>                     <none>              8caaeeb40fc4        53 minutes ago      1.555 GB
    <none>                     <none>              15af0277040f        53 minutes ago      1.555 GB
    <none>                     <none>              c01ad0dc9fd3        53 minutes ago      1.555 GB
    <none>                     <none>              3e8d550ec39b        56 minutes ago      1.555 GB
    <none>                     <none>              1135c0a763e2        56 minutes ago      1.555 GB
    <none>                     <none>              b03ddd1493fb        56 minutes ago      1.555 GB
    <none>                     <none>              f98944db0d29        56 minutes ago      1.555 GB
    <none>                     <none>              0808119df35a        58 minutes ago      1.555 GB
    <none>                     <none>              4321ea9ea8ba        58 minutes ago      1.555 GB
    <none>                     <none>              21cca131c91a        58 minutes ago      1.555 GB
    <none>                     <none>              9ca9daa44b98        58 minutes ago      1.555 GB
    <none>                     <none>              2707bd305b81        About an hour ago   1.555 GB
    <none>                     <none>              b7b060c0305e        About an hour ago   1.555 GB
    <none>                     <none>              7a34da82c1df        About an hour ago   1.555 GB
    <none>                     <none>              4f5dc002d97c        About an hour ago   1.555 GB
    <none>                     <none>              9ff4d05a2e4f        About an hour ago   1.555 GB
    <none>                     <none>              ed67244978da        About an hour ago   1.555 GB
    <none>                     <none>              15273fbd20ff        About an hour ago   1.555 GB
    <none>                     <none>              4ca145efe256        About an hour ago   1.555 GB
    dokku/website-staging      latest              790a587dcfda        2 days ago          1.646 GB
    <none>                     <none>              9b7771729caf        2 days ago          1.646 GB
    <none>                     <none>              eab23ac32b42        2 days ago          1.646 GB
    <none>                     <none>              bb84c64acd33        2 days ago          1.646 GB
    <none>                     <none>              40f757774eea        2 days ago          1.646 GB
    <none>                     <none>              6096172cf243        2 days ago          1.342 GB
    <none>                     <none>              e0a00b080971        2 days ago          1.342 GB
    <none>                     <none>              9fba379feab2        2 days ago          1.342 GB
    <none>                     <none>              e9b9a72e1174        2 days ago          1.342 GB
    <none>                     <none>              cc5525ad6922        2 days ago          1.342 GB
    <none>                     <none>              2a7554aafc71        2 days ago          1.342 GB
    <none>                     <none>              3db11cf80d9c        2 days ago          1.555 GB
    <none>                     <none>              ae26bbc48b4b        2 days ago          1.555 GB
    <none>                     <none>              f38e1ba56176        2 days ago          1.555 GB
    <none>                     <none>              d0d4128e5dad        2 days ago          1.555 GB
    <none>                     <none>              ae80a6193df3        2 days ago          1.555 GB
    <none>                     <none>              91982fedc7aa        2 days ago          1.292 GB
    <none>                     <none>              b2a43cba7c14        2 days ago          1.292 GB
    <none>                     <none>              c437f60fd4db        2 days ago          1.292 GB
    <none>                     <none>              5ab6ad0e0ca6        2 days ago          1.292 GB
    <none>                     <none>              c39f969b21d2        2 days ago          1.292 GB
    dokku/mamarisk-staging     latest              f75bf142497a        9 days ago          1.689 GB
    <none>                     <none>              587d4e649fec        9 days ago          1.689 GB
    <none>                     <none>              5c8c26b2da0f        9 days ago          1.689 GB
    <none>                     <none>              3d4b2a0dc468        9 days ago          1.689 GB
    <none>                     <none>              d243b4e8894d        9 days ago          1.689 GB
    <none>                     <none>              1dd5cd7c2169        9 days ago          1.412 GB
    <none>                     <none>              51cd9c739f5f        9 days ago          1.412 GB
    <none>                     <none>              de94c367606d        9 days ago          1.412 GB
    <none>                     <none>              83b90474956f        9 days ago          1.412 GB
    <none>                     <none>              aa546df5d425        9 days ago          1.292 GB
    <none>                     <none>              7d50775b00a1        12 days ago         1.55 GB
    <none>                     <none>              ccece681c507        12 days ago         1.55 GB
    <none>                     <none>              13bb831d09aa        12 days ago         1.55 GB
    <none>                     <none>              e469cb56b6d9        12 days ago         1.55 GB
    <none>                     <none>              01db1a640947        5 weeks ago         1.55 GB
    <none>                     <none>              81194d036962        5 weeks ago         1.55 GB
    <none>                     <none>              97a54f5ebdab        5 weeks ago         1.55 GB
    <none>                     <none>              7502572465b5        5 weeks ago         1.55 GB
    <none>                     <none>              dff5a662d5ce        7 weeks ago         1.55 GB
    <none>                     <none>              a2f122feb45c        7 weeks ago         1.55 GB
    <none>                     <none>              94c711d462a6        7 weeks ago         1.55 GB
    <none>                     <none>              8d9abaadcf0c        7 weeks ago         1.55 GB
    <none>                     <none>              88a244a98aa0        7 weeks ago         1.55 GB
    <none>                     <none>              729acbeffc35        7 weeks ago         1.292 GB
    <none>                     <none>              0de84228cb36        7 weeks ago         1.292 GB
    <none>                     <none>              b16546756f15        7 weeks ago         1.292 GB
    <none>                     <none>              3c7df6e59d3f        7 weeks ago         1.292 GB
    <none>                     <none>              e2554069364a        7 weeks ago         1.292 GB
    dokku/wiki-staging         latest              d1f374fc2c3e        3 months ago        414.7 MB
    <none>                     <none>              80b806013401        3 months ago        413.1 MB
    <none>                     <none>              c27c61e3852e        3 months ago        413.1 MB
    <none>                     <none>              a03b6a0c1e6d        3 months ago        412.9 MB
    <none>                     <none>              6f43830bea29        3 months ago        410.4 MB
    <none>                     <none>              9c67ae55beda        3 months ago        301.9 MB
    gliderlabs/herokuish       latest              4d464d9705fc        3 months ago        1.29 GB
    <none>                     <none>              58e66d465791        3 months ago        1.271 GB
    <none>                     <none>              56b31ddc05ad        3 months ago        1.267 GB
    <none>                     <none>              10cd34f6cf82        3 months ago        87.09 MB
    <none>                     <none>              8e0aa5f79abe        5 months ago        87.09 MB
    <none>                     <none>              978b0fee5c40        5 months ago        87.09 MB
    <none>                     <none>              22ff522b14d0        5 months ago        301.9 MB
    istepanov/dokuwiki         latest              d6a5a2532007        5 months ago        275.4 MB
    <none>                     <none>              179bd5b5553f        5 months ago        275.4 MB
    <none>                     <none>              478aa2a9cbd9        5 months ago        275.4 MB
    <none>                     <none>              de9810acc565        5 months ago        275.4 MB
    <none>                     <none>              afa6f7785ba7        5 months ago        275.4 MB
    <none>                     <none>              7c6d7a6e5085        5 months ago        275.4 MB
    <none>                     <none>              03809f7f4d51        5 months ago        275.4 MB
    <none>                     <none>              1bed3d8d2209        5 months ago        275.4 MB
    <none>                     <none>              2d7ecb22b77b        5 months ago        275.4 MB
    <none>                     <none>              e5d51812cf4c        5 months ago        275.4 MB
    <none>                     <none>              54a0ff02cc4e        5 months ago        275.4 MB
    <none>                     <none>              0faa16797633        5 months ago        275.3 MB
    <none>                     <none>              4c70d41e53a5        5 months ago        262.9 MB
    <none>                     <none>              533cd0fa0024        5 months ago        262.9 MB
    <none>                     <none>              08978dedc2d4        5 months ago        262.9 MB
    <none>                     <none>              3a96a0cca77d        5 months ago        188.4 MB
    mprasil/dokuwiki           latest              cd265086331f        6 months ago        301.9 MB
    <none>                     <none>              58bb3f994fdd        6 months ago        301.9 MB
    <none>                     <none>              9c63c54a8b0a        6 months ago        301.9 MB
    <none>                     <none>              8db454a03787        6 months ago        301.9 MB
    <none>                     <none>              6be427da8fbf        6 months ago        301.9 MB
    <none>                     <none>              c81f670cff6a        6 months ago        301.9 MB
    <none>                     <none>              7f80db15cd01        6 months ago        301.9 MB
    <none>                     <none>              d8b13e261008        6 months ago        301.9 MB
    <none>                     <none>              0ba4836910ed        6 months ago        289.5 MB
    <none>                     <none>              cabe1fe72585        6 months ago        277 MB
    <none>                     <none>              0012eb665f40        6 months ago        264.6 MB
    <none>                     <none>              395290205bcc        6 months ago        264.6 MB
    <none>                     <none>              07e64da4845e        6 months ago        261.2 MB
    <none>                     <none>              7e7c77123b8d        6 months ago        210.8 MB
    <none>                     <none>              d0e772a6e65a        6 months ago        188.4 MB
    <none>                     <none>              b968b3a34fd3        6 months ago        188.4 MB
    <none>                     <none>              c7f36bf1e5ae        6 months ago        188.4 MB
    <none>                     <none>              e36fb1cfb40d        6 months ago        188.4 MB
    <none>                     <none>              91e54dfb1179        6 months ago        188.4 MB
    <none>                     <none>              d74508fb6632        6 months ago        188.4 MB
    <none>                     <none>              c22013c84729        6 months ago        188.4 MB
    <none>                     <none>              d3a1f33e8a5a        6 months ago        188.2 MB

**Comment by josegonzalez** [comment]
Are you linking those containers anywhere? `dokku cleanup` - which is run on deploy - will clear out any non-running containers, but it's possible your containers are somehow still being linked to.

Can you run:

```shell
DOKKU_TRACE=1 dokku cleanup
```

And gist the output for us?

**Comment by nielsonsantana** [comment]
The output after run this command is:
https://gist.github.com/nielsonsantana/623add98aa8e52076cbf

I think that the images are too old (six moths) and don't are catched by the `cleanup script`.
Can dokku run `cleanup` automatically?

**Comment by nielsonsantana** [comment]
After I try delete the oldest image, I get the error:

    root@dokku-staging:~# docker rmi d3a1f33e8a5a
    Error response from daemon: conflict: unable to delete d3a1f33e8a5a (cannot be forced) - image has dependent child images
    Error: failed to remove images: [d3a1f33e8a5a]

**Comment by josegonzalez** [comment]
What is the output of the following now that you've run the cleanup?:

```
docker ps -a
```

Again, dokku runs that cleanup script on every deploy, so there is something else going on here that is stopping it from removing old images.

**Comment by nielsonsantana** [comment]
Output for `docker ps -a`. Before run it, I run `dokku cleanup`


    CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS               NAMES
    b9c9960b3ee9        dokku/website-staging:latest      "/start worker_sync_s"   25 minutes ago      Up 25 minutes                           website-staging.worker_sync_s3.1
    cd7bbd20a834        dokku/website-staging:latest      "/start web"             25 minutes ago      Up 25 minutes                           website-staging.web.1
    593aebe1da6a        dokku/mamarisk-staging:latest     "/start web"             26 minutes ago      Up 26 minutes                           mamarisk-staging.web.1
    2441343fcdbd        dokku/parceiros-staging:latest    "/start web"             26 minutes ago      Up 26 minutes                           parceiros-staging.web.1
    25e2a9e372bc        dokku/resultados-staging:latest   "/start web"             27 minutes ago      Up 27 minutes                           resultados-staging.web.1

**Comment by nielsonsantana** [comment]
Ok. I going to slack group.

**Comment by josegonzalez** [comment]
After some investigation via chat, I'm closing this. 

After running the following:

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t
```

It looks like dokku is doing the right thing here in regards to not removing images (images are layers built onto other layers). If you want to use less diskspace, Dockerfile-based deploys are the way to go. Every "command" that is run against a deploy results in another layer, which in theory can use up more space.

I have similar usage on my own test dokku instance:

```
root@dokku:/var/lib/docker/aufs/diff# dokku apps
=====> My Apps
my_app
playground
ruby-sample
test-project
root@dokku:/var/lib/docker/aufs/diff# df -h | grep DOROOT
/dev/disk/by-label/DOROOT   20G   13G  6.0G  68% /
```

And most of that is in use by the aufs layers (9.1gb).

**Comment by nielsonsantana** [comment]
@josegonzalez, than this mean that I should use Dockerfile to deploy small images
