### ISSUE TITLE
 Deploying a go app

### ISSUE THREAD

**Issue by rjrobinson** [dokku/dokku#1994]
I am assuming that i am just missing something dumb. 

I have followed all of the heroku guides on how to depoly a go app, and I am able to deploy it to heroku. 

but when I try to deploy to my dokku instance, i get 
`Godeps are required. For instructions:` 

so... is there some plugin that I have to install?

**Comment by josegonzalez** [comment]
Can you update your issue to include the information we ask for in our [ISSUE_TEMPLATE.md](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? Will help in figuring out how the deploy is failing :)

**Comment by rjrobinson** [comment]
Description of problem:

Output of the following commands

uname -a: Linux opsen-gru-2 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
free -m: --
             total       used       free     shared    buffers     cached
Mem:          7985       2764       5220          0        106       2338
-/+ buffers/cache:        319       7665
Swap:            0          0          0

docker version: Docker version 1.10.2, build c3959b1
docker -D info: Cannot connect to the Docker daemon. Is the docker daemon running on this host?

sigil -v: sigil: command not found
docker run -ti gliderlabs/herokuish:latest herokuish version: n/a ?
dokku version: 0.4.14
dokku plugin: --
plugn: dev
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
docker inspect CONTAINER_ID (if applicable): (BEWARE: docker inspect will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
cat /home/dokku/<app>/nginx.conf (if applicable):
Link to the exact repository being deployed (if possible/applicable):
If a deploy is failing:
Application name:  go-gru
The type of application being deployed (node, php, python, ruby, etc.)
Whether or not you have a Dockerfile in the root of your repository
If using buildpacks, which custom buildpacks are in use
If it exists, the contents of your Procfile.
Output of failing dokku commands after running dokku trace on (BEWARE: trace on will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
Environment details (AWS, VirtualBox, physical, etc.):

How was dokku installed?: instructions on the main page

How reproducible: try to deploy a go app. 

Steps to Reproduce: 1. 2. 3.

Actual Results: 

git push dokku master
Counting objects: 194, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (170/170), done.
Writing objects: 100% (194/194), 11.90 MiB | 2.85 MiB/s, done.
Total 194 (delta 80), reused 0 (delta 0)
-----> Cleaning up...
-----> Building go-gru from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Go app detected
remote:  !     Godeps are required. For instructions:
remote:  !     https://devcenter.heroku.com/articles/go-support
To dokku@[removed]:go-gru
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@[removed]:go-gru'

Expected Results:

Additional info:

**Comment by michaelshobbs** [comment]
This has to do with the latest go buildpack changes. As the error message states, check out https://devcenter.heroku.com/articles/go-support for more details on the Heroku requirements for golang support.

More specifically: https://devcenter.heroku.com/articles/go-support#migrating-from-go1-5-godep-workspace-to-go1-6-with-a-vendor-directory
I followed that process to make the herokuish test app work with the latest Heroku go buildpack. Example `Godeps.json` file: https://github.com/gliderlabs/herokuish/blob/27984c6156f91e2e41e010b9e9f9e298d84369aa/buildpacks/buildpack-go/tests/go/Godeps/Godeps.json

**Comment by rjrobinson** [comment]
Ok. I tried all of those steps. 

i never had godep installed on 1.5, only 1.6 . 

I'm still getting the same error.  :(

**Comment by michaelshobbs** [comment]
This is definitely an issue with your app+buildpack. Here is the logic: https://github.com/heroku/heroku-buildpack-go/blob/82b5f054de16349d10133fe125aeab9df12d459f/bin/compile#L116-L135

Do you have a `Godeps.json` in your repo located at `Godeps/Godeps.json`?

**Comment by josegonzalez** [comment]
@michaelshobbs he's using the old version of the buildpack.

@rjrobinson can you screenshot the directory listing? We're simply using the heroku buildpack here, so it's possible you used a version that didn't need godeps and now it does.

You can setup a `Godeps.json` by running `godep save`.

**Comment by rjrobinson** [comment]
Ok, so i was able to progress... 
```
remote: can't load package: package github.[mycompany].com/opsen/gru-api: no buildable Go source files in /tmp/build/.heroku/go/src/github.[mycompany].com/opsen/gru-api
```

did I maybe put the load path wrong?

**Comment by michaelshobbs** [comment]
Did you vendor that dependency?

**Comment by michaelshobbs** [comment]
I missed @josegonzalez's comment earlier. What version of the buildpack are you using? I didn't see the herokuish version output in your initial issue.

**Comment by michaelshobbs** [comment]
Here is the logic block for v22 of the buildpack. That's the one dokku 0.4.14 shipped with.

https://github.com/heroku/heroku-buildpack-go/blob/v22/bin/compile#L75-L102
```
if test -f $build/Godeps
then
    warn "Deprecated, old ./Godeps file found!"
    warn "Please upgrade godeps (go get -u github.com/tools/godep) and"
    warn "re-save your dependencies: godep save -r ./..."
    name=$(<$build/Godeps jq -r .ImportPath)
    ver=$(<$build/Godeps jq -r .GoVersion)
elif test -f $build/Godeps/Godeps.json
then
    step "Checking Godeps/Godeps.json file."
    if ! jq -r . < $build/Godeps/Godeps.json > /dev/null
    then
        warn "Bad Godeps/Godeps.json file"
        exit 1
    fi
    name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
    ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
elif test -f $build/.godir
then
    warn "Deprecated, .godir file found!"
    warn "Please switch to godeps (github.com/tools/godep) ASAP"
    name=$(cat $build/.godir)
    ver=go${GOVERSION:-1.5}
else
    warn "Godeps are required. For instructions:"
    warn "https://devcenter.heroku.com/articles/go-support"
    exit 1
fi
```

**Comment by rjrobinson** [comment]
It's ok. I solved the issue. Maybe it is a build pack thing, but I didn't have my file six in the same pattern `cmd/{{appname}}/...app files` 

after I did that and ran godep, it worked. 

the only issue now is Nginx errors, but I'll try to troubleshoot them first.
