### ISSUE TITLE
Rails app: "No such file or directory" when running ActiveJob / QueueClassic

### ISSUE THREAD

**Issue by Corstiaan84** [dokku/dokku#1995]
My background job (worker) has a few ````File.open```` operations. They all print ````No such file or directory```` to the logs.

My web process (web) also calls a few ````File.open```` operations. They all work fine.

Am I missing a setting or permission?

**Comment by josegonzalez** [comment]
Perhaps your web process creates that dir if it doesn't exist and the background job doesn't?

**Comment by Corstiaan84** [comment]
@josegonzalez -- quick as always :-).

Well, I already added this line: ````Dir.mkdir(temp_folder) unless File.exists?(temp_folder)```` before the calls. Doesnt seems to help though...

**Comment by josegonzalez** [comment]
Do you have a stacktrace?

**Comment by Corstiaan84** [comment]
https://gist.github.com/Corstiaan84/0655c707ce69d3d3b7b1

(need to get same sleep now. GMT+1. Thanks!_

**Comment by josegonzalez** [comment]
Looks like that's being done from the root directory, not `$PWD`...

**Comment by Corstiaan84** [comment]
Could you elaborate a bit more?

**Comment by josegonzalez** [comment]
The path has a `/` prefix, so it's creating the directory in root, instead of `/app`. I'm going to assume you are using buildpacks because you didn't fill out the `ISSUE_TEMPLATE.md`...

**Comment by Corstiaan84** [comment]
It's working. Thanks!
