### ISSUE TITLE
Multiple branch deployment

### ISSUE THREAD

**Issue by istarkov** [dokku/dokku#1998]
After [this fix](https://github.com/dokku/dokku/pull/1993) it becomes possible to create multiple branch deployment with dokku, so I've created an article 

[How to create your own Heroku review apps with dokku](https://github.com/istarkov/create-your-own-heroku-review-apps-with-dokku)

It may be interesting for dokku community. 
(Haven't found official dokku twitter or anything similar)

**Comment by michaelshobbs** [comment]
Mmmmm brunch :smile:

**Comment by istarkov** [comment]
Fixed ;-) thank you

**Comment by michaelshobbs** [comment]
Hehe. @josegonzalez thoughts on where to put this? I know you were thinking about more example-focused documentation.

**Comment by josegonzalez** [comment]
Place it under [here](http://dokku.viewdocs.io/dokku/application-deployment/) in it's own section before `DOKKU/DOCKER CONTAINER MANAGEMENT COMPATIBILITY`.

**Comment by josegonzalez** [comment]
@istarkov friendly *bump*

**Comment by josegonzalez** [comment]
Looks like this is taken care of by the section [here](http://dokku.viewdocs.io/dokku/application-deployment/#deploying-non-master-branch).
