### ISSUE TITLE
docker-options doesn't seem to work.

### ISSUE THREAD

**Issue by thedracle** [dokku/dokku#2001]
Description of problem:

I am doing a Dockerfile based deploy. The app has been configured with the following docker-options:

<pre>
> dokku docker-options myimage
Run options:
    -it --net=host`
</pre>

When doing a deploy, dokku creates an image, tags it, and runs it:
<pre>
> docker ps
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                        NAMES
2c3342cb898d        dokku/myimage:latest   "/bin/sh -c /run.sh"   16 hours ago        Up 16 hours         80/tcp, 443/tcp, 5347/tcp, 10000-10010/udp  myimage.web.1</pre>

However the image is inaccessible and --net=host is clearly not working:
<pre>telnet 127.0.0.1 443
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused</pre>

If I run manually:
`
docker run -it --net=host dokku/myimage
`

Then it appears to be run correctly with --net=host, and I can access it:
<pre>telnet 127.0.0.1 443
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.</pre>

Output of the following commands

- `uname -a`:
Linux ip-172-31-48-50 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
<pre>             total       used       free     shared    buffers     cached
Mem:         16047       1821      14226          0        105        780
-/+ buffers/cache:        935      15112
Swap:            0          0          0</pre>

- `docker version`:
</pre>Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
</pre>
- `docker -D info`:
<pre>Containers: 20
 Running: 2
 Paused: 0
 Stopped: 18
Images: 22
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 61
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-172-31-48-50
ID: MAFH:FBVH:BMRJ:MD7U:5O2J:3JSR:2THU:2AX2:R5O6:FVRD:MZH4:GMCT
Username: thedracle
Registry: https://index.docker.io/v1/
WARNING: No swap limit support</pre>
- `sigil -v`:
0.3.3
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
<pre>herokuish: 0.3.9
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v88
  heroku-buildpack-php       v95
  heroku-buildpack-play      v26
  heroku-buildpack-python    v77
  heroku-buildpack-ruby      v145
  heroku-buildpack-scala     v66
  buildpack-nginx            v5`
</pre>
- `dokku version`:
v0.4.14-118-g846d1fe
- `dokku plugin`:
<pre>plugn: 0.2.1
  00_dokku-standard    0.5.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.5.0 enabled    dokku core checks plugin
  common               0.5.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.5.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  proxy                0.5.0 enabled    dokku core proxy plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  storage              0.5.0 enabled    dokku core storage plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin</pre>

Environment details (AWS, VirtualBox, physical, etc.):
AWS

How was dokku installed?:
wget https://raw.github.com/dokku/dokku/master/bootstrap.sh

etc...

How reproducible:
Every time

Steps to Reproduce:
1. Create an application
2. Set up docker-options setting run=host
3. Deploy, and observe run=host isn't being applied.

Actual Results:
Image isn't deployed with run options.

Expected Results:
Image is deployed with run options.

Additional info:

**Comment by michaelshobbs** [comment]
I think you maybe confusing the `run` phase with the `deploy` phase. Check out the the docker options docs for an explanation.

http://dokku.viewdocs.io/dokku~v0.4.14/docker-options/#about-dokku-phases

However I'm not clear on what you're trying to do. If you just want to disable nginx from proxying your app then you can read up on that here. 

http://dokku.viewdocs.io/dokku~v0.4.14/nginx/#disabling-vhosts


I'm curious if setting the `--net=host` option on a deployed app will break zero downtime deployment since two containers will be running simultaneously for a short time. (I also concede I'm not familiar with that docker run option)

**Comment by thedracle** [comment]
Yes, you're right, I was confusing the two phases.
