### ISSUE TITLE
Document dependencies and version

### ISSUE THREAD

**Issue by MorrisJobke** [dokku/dokku#2008]
As I'm building also the ArchLinux packages it would be helpful to have a common resource of which versions of which external dependencies (herokuish, sigil, ...) are needed. Or are they documented already? Do I need to check the debian package for this?

cc @josegonzalez

**Comment by josegonzalez** [comment]
Debian packages have this.

**Comment by josegonzalez** [comment]
@MorrisJobke what would we want here? We just need "latest", and the `deb.mk` handles creating those packages for us.

**Comment by MorrisJobke** [comment]
> @MorrisJobke what would we want here? We just need "latest", and the deb.mk handles creating those packages for us.


Latest is quite bad, because something like: dokku won't work without version x.y.z of herokuish for example would be crucial, because otherwise it is still valid from a packaging point of view to hold an old version without complaining. But if this is the case I just require the latest released version and that's it.

**Comment by josegonzalez** [comment]
Right, I'm just saying that the versions are the latest released ones. We don't have a hard dependency anywhere other than the `docker-engine` package (1.9.1+ atm). All dependencies are in our control file.

**Comment by josegonzalez** [comment]
@MorrisJobke fwiw, we only ever do this every so often, though requiring latest would be ideal. I can note in the release notes for times when I do this for debian, and then let you know so you can make the appropriate changes.
