### ISSUE TITLE
Persistent storage not working.

### ISSUE THREAD

**Issue by bokzor** [dokku/dokku#2010]
Description of problem:

I tried to activate persistent storage for a directory with no success

The directory is public and It's at the root.

dokku docker-options:add app-name deploy,run,build "-v /home/dokku/shared:/public"

Directory 'shared' is 755 dokku:dokku.

Output of the following commands

- `uname -a`: 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`: 
- `docker version`:
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

- `docker -D info`:

Containers: 19
 Running: 3
 Paused: 0
 Stopped: 16
Images: 32
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 95
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: digital.laboiboite.be
ID: PSWL:AQGL:FC3G:H7YY:J6QD:YOAU:WM23:DQFV:FNBL:OQKG:CSZB:D2UG
WARNING: No swap limit support
```

- `sigil -v`:
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
Herokuish: 0.3.8
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v5
```
- `dokku version`: 0.4.14

- `dokku plugin`:
```
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  builders-plugin      0.3.3 enabled    To run tools and package managers on build/release
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logging-supervisord  0.1.0 enabled    A plugin for dokku that injects supervisord
  logs                 0.4.0 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```
- `docker inspect CONTAINER_ID` (if applicable):
```
[
    {
        "Id": "sha256:5bfc5a72fc457a06f09ba0d31487f4c5b930b5f1c51c0698871dc94aa116301c",
        "RepoTags": [
            "dokku/boiboite:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:5d8f6cdd9b3abdaf6495d2654fd2b6619c04692716c0d762f59e3ca819f335cb",
        "Comment": "",
        "Created": "2016-03-20T01:21:45.060784961Z",
        "Container": "4826f014a3635315a42ee36d5a2e9b560f4cef73b21321196c4e2043a3df2a3d",
        "ContainerConfig": {
            "Hostname": "4826f014a363",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/bash",
                "-c",
                "/app/.builders_run"
            ],
            "Image": "dokku/boiboite:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "dokku": ""
            },
            "StopSignal": "SIGTERM"
        },
        "DockerVersion": "1.10.3",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/bash",
                "-c",
                "/app/.builders_run"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "dokku": ""
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1536756141,
        "VirtualSize": 1536756141,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        }
    }
]
```

  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - Whether or not you have a `Dockerfile` in the root of your repository
  - If using buildpacks, which custom buildpacks are in use
  - If it exists, the contents of your `Procfile`.
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.): DigitalOcean

How was dokku installed?:

Image digital ocean

**Comment by michaelshobbs** [comment]
Given that the resulting container contains no mounts referenced in the `docker inspect` output, my hypothesis would be that another `docker-args-*` trigger is failing before the `docker-options` trigger is called. I ran into a similar issue the other day. 

A few thoughts
- ensure the output of `dokku docker-options <app>` shows the options you set. (Just as a sanity check)
- look at the non-core plugins to see if they might be interfering
- finally, a gist of a deploy with dokku trace on could be helpful but removing other plugins that have `docker-args-*` triggers one by one might be faster/easier in finding the culprit

**Comment by bokzor** [comment]
I just tried from a fresh install only with the mongodb plugin. But without success...

**Comment by josegonzalez** [comment]
Can you gist a deploy after running `dokku trace on`?

**Comment by bokzor** [comment]
https://gist.github.com/bokzor/662f0c0f82cac097941f

**Comment by bokzor** [comment]
Yep sorry. I forgot the link

**Comment by josegonzalez** [comment]
```
docker run --label=dokku -d -p 5000 -e PORT=5000 --link dokku.mongo.boiboite:dokku-mongo-boiboite -v /home/dokku/shared:/public -e 'DYNO='\''web.1'\''' -e TRACE=true dokku/boiboite:latest /start web
```

@michaelshobbs anything suspicious there? That's the last `docker run` call, and it seems to have the proper env var set...

**Comment by michaelshobbs** [comment]
What is the docker inspect output from the new installation's running container?

**Comment by bokzor** [comment]
https://gist.github.com/bokzor/ac2b1e20d5bb10881bf9

**Comment by michaelshobbs** [comment]
That's the wrong container. We need the one that runs `/start web`

**Comment by bokzor** [comment]
https://gist.github.com/bokzor/ae19617d4b6322e257fc

It's strange because ps -a said that the container status is "Exited (255) 2 hours ago"

**Comment by michaelshobbs** [comment]
In that gist I see the volume mount you specified. Seems like one of those other plugins is bombing on the `docker-args-deploy` trigger

**Comment by bokzor** [comment]
So maybe mongoldb plugin. Because It's the only not official one.

**Comment by michaelshobbs** [comment]
It looks like the mongo db one worked in that output. I see the container link. I'd start by enabling the plugins one by to see which one breaks. Doesn't seem to be an issue with dokku at this point.

**Comment by michaelshobbs** [comment]
@bokzor Regarding your plugins: based on the output of your bug report the following plugins are NOT core and the only one that has a `docker-args-*` trigger is logging-supervisord; unless you've forked the others and added one.

```
  builders-plugin      0.3.3 enabled    To run tools and package managers on build/release
  logging-supervisord  0.1.0 enabled    A plugin for dokku that injects supervisord
  mongo                1.0.0 enabled    dokku mongo service plugin
```

**Comment by michaelshobbs** [comment]
@bokzor any luck here?

**Comment by bokzor** [comment]
No... I don't get It.

docker inspect show me this : 

```
        "Mounts": [
            {
                "Source": "/home/dokku/shared",
                "Destination": "/public/boxImage",
                "Mode": "",
                "RW": true,
                "Propagation": "private"
            }
        ],
```

but when I push a change, files are gone...

**Comment by michaelshobbs** [comment]
Do the files exist in `/home/dokku/shared`?

**Comment by bokzor** [comment]
No... And I if execute 
`dokku run my_ap ls public/boxImage`
, there is no files either...

**Comment by michaelshobbs** [comment]
@bokzor join us on [IRC](https://webchat.freenode.net/?channels=dokku) or [Slack](https://glider-slackin.herokuapp.com/) for more real time support

**Comment by michaelshobbs** [comment]
From the convo on IRC, the app was writing to `public/boxImage` but the mount was `/public/boxImage`
