### ISSUE TITLE
optimize docker image sizes?

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2015]
Hi,

   I have a minimalist python app called ping (https://github.com/sglebs/ping) deployed to dokku. The deployed docker image is rather large:
```
vagrant@dokku:~$ sudo docker images | grep ping
dokku/ping             latest              82615df3a54b        31 seconds ago      1.45 GB
```

I was looking at quite small docker images at 

   * https://hub.docker.com/r/frolvlad/alpine-python3/
   * https://hub.docker.com/r/frolvlad/alpine-python2/

Is it possible to somehow override the core docker image used by dokku so I can get to these small numbers? I am aware of the Dockerfile feature (http://blog.stevenedouard.com/git-deploy-nodejs-apps-dockerfiles-using-dokku/) but that is a bit low level. Can I retain the benefit of build packs and Procfile while being small?

Thanks!

**Comment by josegonzalez** [comment]
You can set `DOKKU_IMAGE` in your `$DOKKU_ROOT/dokkurc` file to override the base image if you'd like, though you'll need to figure out how to get buildpacks working on alpine or similar on your own.

**Comment by sglebs** [comment]
Thanks! What is the default value of DOKKU_IMAGE , in case I want to switch back and forth? Is it ginderlab/herokuish:latest ? (I am guessing from the comments at https://github.com/dokku/dokku/issues/1091)

**Comment by josegonzalez** [comment]
It is set [here](https://github.com/dokku/dokku/blob/master/dokku#L22).

**Comment by sglebs** [comment]
Thanks! Can I set it at dokku install time so that dokku will be more minimalist and fit in smaller boxes? Or do I have to manually "docker rmi" the large image that dokku uses by default?

I think dokku used to be smaller before herokuish, no? I seem to recall having to have a requirements.apt to have it install psycopg2 for example.

Thanks for taking the time to answer!

**Comment by josegonzalez** [comment]
There isn't a "slim" default dokku image you can set. If you want a smaller box, you'll need to use dockerfiles.

The dokku image was never "smaller". We used to use buildstep, but moved to herokuish as it more accurately reflects what heroku does (it's basically exactly their code). 

This `requirements.apt` file seems specific to some framework you may have been using. Dokku has never supported it.
