### ISSUE TITLE
Dockerfile & multiple processes in Procfile

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2016]
Hi,

   I have a Procfile with 2 lines and I am converting from buildpack-based to Dockerfile-based. Is there Docker Compose support in dokku (like Heroku: https://devcenter.heroku.com/articles/docker) or should I fork 2 processes myself using & in my single Dockerfile? Thanks!

**Comment by josegonzalez** [comment]
This is a feature in the upcoming [0.5.0 release](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#procfiles-and-multiple-processes), which I hope to do tonight :)
