### ISSUE TITLE
Any hook to uninstall things?

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2017]
Hi,

  I was able to get my ping example (https://github.com/sglebs/ping) to 62MB thanks to uninstalling things. Here's the Dockerfile:

```
FROM gliderlabs/alpine:3.3

WORKDIR /app
COPY . /app

RUN apk --update add python py-pip
RUN apk --update add --virtual build-dependencies python-dev build-base \
    && pip install -r requirements.txt \
    && apk del build-dependencies

EXPOSE 8080

CMD gunicorn -k gevent -b 0.0.0.0:8080 --preload --timeout 31 --keep-alive 1 --backlog 2048 --log-syslog --log-syslog-prefix GUNICORN --log-level INFO -c gunicorn_config.py wsgi:application
```

Note the "apk del build-dependencies" trick.

Can this be done with build packs? If not, can it be done with a dokku hook? If not, I guess a custom Dockerfile is the way to go then.

Thanks!

**Comment by josegonzalez** [comment]
This can be performed via [deployment tasks](http://dokku.viewdocs.io/dokku/deployment/deployment-tasks/) in the upcoming 0.5.0.

**Comment by sglebs** [comment]
you are teasing me with 0.5.0 :-) second ticket today. I can hardly wait! :-) thanks!
