### ISSUE TITLE
RFC: Mac OS X Support for development?

### ISSUE THREAD

**Issue by u2mejc** [dokku/dokku#2019]
This RFC is related to Docker adding native support for the Mac in the very near future (no more VM running linux, no more docker-machine): https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

This would be purely for ease of development. I mean who is still running a Mac in production [other then imgix](http://photos.imgix.com/racking-mac-pros)? :wink: 

With native docker support, bash, and nginx, I believe that biggest issue will be the extremely antiquated version of bash on shipped on Mac OS X.

- Mac OS 10.11.3: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)`
- Ubuntu 14.04 LTS: `GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)`

Personally I'd love to run `brew install dokku` and have it install dokku with docker and nginx as dependencies.

Would anyone else find native dokku on Mac OS useful?

**Comment by josegonzalez** [comment]
:-1: 

I would rather focus any future development work towards making it work completely within a dockerfile, as then if a platform supports linux docker, then it supports dokku.

**Comment by michaelshobbs** [comment]
👍🏼 to @josegonzalez's comment

**Comment by michaelshobbs** [comment]
👍🏼 to @josegonzalez's comment

**Comment by u2mejc** [comment]
>I would rather focus any future development work towards making it work completely within a dockerfile, as then if a platform supports linux docker, then it supports dokku.

By "linux docker" you mean what is OS exposed in the container right? Call it an assumption after you read the blog article, but because the Mac doesn't support paravirtualization, the host OS doesn't affect the running containers (think of docker on windows).

So, other than an installer and reworking some bash 4 only calls, this doesn't seem like a large hurdle.

**Comment by josegonzalez** [comment]
I just want to be able to do:

```
docker pull dokku/dokku
```

And use that everywhere. I don't want to have to worry about updating a brew formula.

**Comment by u2mejc** [comment]
Say that command succeed on any platform, then what? How do you manage dokku?

**Comment by josegonzalez** [comment]
Manage? We're trying to figure out what dokku install/upgrade/plugin manipulation means in #1076.

**Comment by AlJohri** [comment]
https://docs.docker.com/engine/installation/mac/ should make this a breeze now

**Comment by theronic** [comment]
How do I run Dokku on OSX? I can't figure it out. `bootstrap.sh` doesn't seem to work (missing /etc/os-release).

**Comment by josegonzalez** [comment]
We don't support running Dokku directly on OS X. If you'd like to run it there, we provide a VM with the Dokku project that you can use.
