### ISSUE TITLE
domain for django dokku app

### ISSUE THREAD

**Issue by drxos** [dokku/dokku#2021]
Description of problem:
I can't link dokku app to a domain name.

I did: dokku domains:add irgib irgib-africa.org.

-`docker ps`:
```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS               NAMES
0ac94b1f7a9f        dokku/irgib:latest   "/start web"             About an hour ago   Up About an hour                        irgib.web.1
caddf834bcc0        postgres:9.5.0       "/docker-entrypoint.s"   4 hours ago         Up 4 hours          5432/tcp            dokku.postgres.irgib
```

Output of the following commands

- `uname -a`:
Linux petra 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- `free -m`:
           total       used       free     shared    buffers     cached
Mem:           994        807        186         23        106        387
-/+ buffers/cache:        313        680
Swap:            0          0          0

- `docker version`:
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

- `docker -D info`:
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 18
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 994 MiB
Name: petra
ID: 5B45:L4AJ:7GN5:ZUKN:IT7D:52VD:ACWA:WGI7:YB5W:SEWE:LIBJ:ZNRT
WARNING: No swap limit support

- `sigil -v`:
zsh: command not found: sigil

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.8
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v5

- `dokku version`:
0.4.14

- `dokku plugin`:
plugn: dev
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
server {
  listen      [::]:80;
  listen      80;
  server_name irgib.229.sarl irgib-africa.org ;
  access_log  /var/log/nginx/irgib-access.log;
  error_log   /var/log/nginx/irgib-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://irgib;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/irgib/nginx.conf.d/*.conf;
}
upstream irgib { 
  server 172.17.0.4:5000;
}

- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - Whether or not you have a `Dockerfile` in the root of your repository
  - If using buildpacks, which custom buildpacks are in use
  - If it exists, the contents of your `Procfile`.
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.):

How was dokku installed?:

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Additional info:

**Comment by josegonzalez** [comment]
Did you point DNS to that server?

**Comment by drxos** [comment]
Yes

**Comment by josegonzalez** [comment]
What happens when you do:

```
sudo service nginx reload
```

**Comment by drxos** [comment]
Oh oh. After `sudo service nginx reload ` it's ok. Thanks.
