### ISSUE TITLE
Pre-receive hook declined

### ISSUE THREAD

**Issue by mbriskar** [dokku/dokku#2026]
I have problem deploying a node.js application to my dokku instance. It used to work well before. I have updated docker/dokku as well. When tracing is ON, here is the output:
https://gist.github.com/anonymous/927a9ea2cd79a01f261b

Any help would be highly appreciated.

**Comment by michaelshobbs** [comment]
Please include ALL of the info requested in our issue template. That will provide more context about your installation.

**Comment by paulwalker** [comment]
Same issue here

**Comment by michaelshobbs** [comment]
@paulwalker the root of your issue is different than this one. You are experiencing #2025. You can run `apt-get install sigil` to get past the error you're seeing.

**Comment by paulwalker** [comment]
@michaelshobbs Thanks, that was it.

**Comment by josegonzalez** [comment]
@mbriskar your issue is that your submodules aren't initializing properly. You'll need to use the [ssh hostkeys](https://github.com/cedricziel/dokku-hostkeys-plugin) and [ssh deployment keys](https://github.com/cedricziel/dokku-deployment-keys) plugins to setup a key that has access to your submodules.

**Comment by mbriskar** [comment]
@josegonzalez @michaelshobbs Sorry for not providing information, but I had hard times fixing other things in order to be able to provide the stable information. I am migrating an application from older versions into new ones as well. I am not sure how the ssh keys should help, since I am using one dokku instance to host 2 applications and one of them works just fine. The other ends with pre-receive hook declined. If the ssh key generation would help, I have then no idea how to use it.

Here, let me please list the information.

- `uname -a`:
Linux tomorrowmagic 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux


- `free -m`:
             total       used       free     shared    buffers     cached
Mem:           490        439         50          0         38        221
-/+ buffers/cache:        178        311
Swap:         4095        148       3947

- `docker version`:
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

- `docker -D info`:
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: tomorrowmagic
ID: P4IE:CQSZ:QMG2:7ADU:7FYT:4VMX:ZOLU:PT3A:RNH6:AF5B:JDIY:FJGE


- `sigil -v`:
0.4.0

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.9
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v88
  heroku-buildpack-php       v95
  heroku-buildpack-play      v26
  heroku-buildpack-python    v77
  heroku-buildpack-ruby      v145
  heroku-buildpack-scala     v66
  buildpack-nginx            v5


- `dokku version`:
0.5.2
- `dokku plugin`:
00_dokku-standard    0.5.2 enabled    dokku core standard plugin
  20_events            0.5.2 enabled    dokku core events logging plugin
  apps                 0.5.2 enabled    dokku core apps plugin
  build-env            0.5.2 enabled    dokku core build-env plugin
  builders-plugin      0.3.3 enabled    To run tools and package managers on build/release
  certs                0.5.2 enabled    dokku core certificate management plugin
  checks               0.5.2 enabled    dokku core checks plugin
  common               0.5.2 enabled    dokku core common plugin
  config               0.5.2 enabled    dokku core config plugin
  deployment-keys      0.1.0 enabled    Manage SSH deployment keys that should get injected into your containers on-build
  docker-options       0.5.2 enabled    dokku core docker-options plugin
  domains              0.5.2 enabled    dokku core domains plugin
  enter                0.5.2 enabled    dokku core enter plugin
  git                  0.5.2 enabled    dokku core git plugin
  hostkeys-plugin      0.1.0 enabled    Manage hostkeys for your container environment
  logs                 0.5.2 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.5.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.2 enabled    dokku core plugin plugin
  proxy                0.5.2 enabled    dokku core proxy plugin
  ps                   0.5.2 enabled    dokku core ps plugin
  shell                0.5.2 enabled    dokku core shell plugin
  storage              0.5.2 enabled    dokku core storage plugin
  tags                 0.5.2 enabled    dokku core tags plugin
  tar                  0.5.2 enabled    dokku core tar plugin
  wkhtmltopdf          0.1.0 enabled    dokku wkhtmltopdf


- If a deploy is failing:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
node.js
  - Whether or not you have a `Dockerfile` in the root of your repository
no
  - If using buildpacks, which custom buildpacks are in use
bower
  - If it exists, the contents of your `Procfile`.
web: grunt serve


Environment details (AWS, VirtualBox, physical, etc.):
Digital ocean small 512MB machine.

How was dokku installed?:
from the source

How reproducible:


Steps to Reproduce:
1. git push dokku +master


Actual Results:
https://gist.github.com/anonymous/927a9ea2cd79a01f261b

Expected Results:
no errors

Additional info:

**Comment by josegonzalez** [comment]
The step that fails is the git submodule init call. Do you have submodules in this repo?

**Comment by mbriskar** [comment]
Thank you for being so responsive.
What do you mean by submodules? Dokku submodule or git submodule? Basically it is a simple angular.js application, it needs npm/bower to be compiled and runned on the server side. But no submodules that I am aware of..

**Comment by mbriskar** [comment]
Jose, you were right, I have wrongly deleted a submodule and it caused the problems.
Thank you once again for being response even during the weekends.
