### ISSUE TITLE
Dockerfile nginx port problems with 0.5.0

### ISSUE THREAD

**Issue by Flink** [dokku/dokku#2028]
Hey guys I think we have a bug with the new template system for nginx config.
I did not investigate but when deploying a dockerfile app, the port is not correctly configured anymore.
I deployed a previous app that was working without any problem with v0.4.x and now it sets DOKKU_DOCKERFILE_PORT and DOKKU_DOCKERFILE_PORTS and then want to serve my app directly on the dockerfile port instead of proxying like any other apps.
I found that removing DOKKU_DOCKERFILE_PORTS seems to enable again the previous config with vhost but it then sets the port to 5000 instead of using the one declared by the dockerfile…
So for now, I had to directly edit the generated nginx.conf file to set the correct port :/

**Comment by michaelshobbs** [comment]
We definitely have dockerfile tests that pass using the new templating stuff. Sharing ALL the info requested in the issue template will help give more context around what you're seeing. (Specifically a gist of your deploy with dokku trace on)

**Comment by Flink** [comment]
@michaelshobbs here is the app that was previously working: https://github.com/Flink/cozy-flink

**Comment by nmec** [comment]
I'm having a similar issue with a Dockerfile that worked pre-0.5.

 My Dockerfile exposes 8080, previously Dokku mapped this to 80 in the nginx config, but that no longer seems to be the case. Setting the `NGINX_PORT` env to 80 doesn't seem to work either.

**Comment by michaelshobbs** [comment]
@Flink I'm attempting to recreate the issue with your test app but seeing the following message. Can you share with me the entire setup to recreate or perhaps a simpler example?

```
       COUCH_USER or COUCH_PASS env var not present!
```

**Comment by Flink** [comment]
@michaelshobbs ah yes sorry, you have to use our couchdb plugin to create a db, link it to the app and then export the following vars: `COUCH_HOST`, `COUCH_PORT`, `COUCH_USER` and `COUCH_PASS` since the app doesn’t understand `COUCHDB_URL` :/

**Comment by michaelshobbs** [comment]
sidenote: Should we auto-inject those type of variables when we link a data store container? I've hit this annoyingness a couple times where an app expects `DBNAME`, `DBHOST`, etc but we only inject `DATABASE_URL`. It's probably too variable to really support. As soon as we inject `DBNAME`, some app will require `DB_NAME` **shrug**

**Comment by michaelshobbs** [comment]
Ok looking at this further, we are definitely proxying the app; just not at `NGINX_PORT`. Instead we extract all `EXPOSE` lines and set up an nginx upstream for each one. See the migration guide [here](https://github.com/dokku/dokku/blob/v0.5.2/docs/appendices/0.5.0-migration-guide.md)

If you'd like that port to be different, you can either use a custom nginx template or modify your app's dockerfile.

I'm also working on cleaning up the docs around `DOKKU_DOCKERFILE_PORTS` and `DOKKU_DOCKERFILE_PORT`

@josegonzalez can you help add this migration guide to the docs site?

**Comment by tobru** [comment]
So that means if my applications Dockerfile says `EXPOSE 8080` and I want Nginx to listen on port 80 and proxy the connection to port 8080 I need to create a custom Nginx template? Just asking because the behaviour pre-0.5.0 was exactly that: Nginx listening on port 80 and proxying that to whatever the Dockerfile was exposing...

**Comment by michaelshobbs** [comment]
That is correct. 0.5.0 came with many changes that simplified the nginx-hosts plugin and better covered the core proxy usage. We're working on getting the migration guide into the docs site but for now you can see the major changes here: https://github.com/dokku/dokku/blob/v0.5.2/docs/appendices/0.5.0-migration-guide.md

**Comment by Flink** [comment]
I still don’t understand why the previous behavior has been changed. This is a major regression IMO. Now every time a Dockerfile app is deployed, a custom nginx conf file must be setup which will be the same *every time* just to get rid of those two lines in nginx.conf.sigil to be able to proxy correctly the app (unless I’m missing something else here):
```
{{ if .RAW_TCP_PORTS }}
{{ include "tcp.server.config" . }}
```

This is also not very consistent with the behavior we have when deploying with herokuish, which is to proxy port 80 to port 5000, not expose port 5000.

**Comment by michaelshobbs** [comment]
That is incorrect. You must only provide a custom nginx config if a) your dockerfile contains `EXPOSE` directives **AND** b) you want to have nginx listen on a different port that the only in the `EXPOSE` line.

**Comment by Flink** [comment]
I’m not saying the template is hard to create, I’m just saying that on v0.4 it worked out of the box, now that’s not the case anymore. So we had something that was easy to use, now for the same use case, I’ll have to commit a template in every project I deploy like this. So for me, it’s a pretty big regression.

So now that half my deployed apps are broken, I’ll go commit some templates :stuck_out_tongue:

**Comment by michaelshobbs** [comment]
Apologies for failing to making this more clear in the docs (truly my facepalm there), but always best to test before upgrading, yea?

**Comment by Flink** [comment]
Sorry, I don’t want to make you feel bad or anything :sweat: Just surprised at this behavior change and yes I could have tested this better but I’m used not to worry too much when there’s an upgrade for dokku :grin:

**Comment by michaelshobbs** [comment]
@Flink perhaps this didn't come through in my original point. You can also remove the `EXPOSE` line and have your app listen on port `5000` inside the container to retain the previous functionality of forwarding from port `80` or whatever `NGINX_PORT` is.

**Comment by Flink** [comment]
@michaelshobbs ah that’s something interesting to know! :)

**Comment by tobru** [comment]
I must say: I was also surprised of this change, it broke a lot of things and makes it really hard now to change all repos just to add a small nginx template. My feeling says that most of the time the application inside the container listens on an arbitrary port (f.e. 8080) and you want the Dokku Nginx to make it available on 80 and 443. So my vote goes to restoring the old behaviour and make it possible to override the Nginx port only if needed using a template. What do you think? Good idea, bad idea?

**Comment by mmerickel** [comment]
A variable for something this common seems reasonable to me. Something like `dokku config:set DOKKU_DOCKERFILE_PORT_443=9104` or something. It should be easy enough to support that in the core nginx template without losing much generality I'd think?

**Comment by michaelshobbs** [comment]
The point of this change was to make the core functionality of dokku more stable. That functionality being heroku-style app deploys. The introduction of dockerfiles was another layer of complexity and adds a whole lot of variance. 

This change was made in a major release of dokku for a reason. We maintain backward-compat within minor releases but all bets are off on majors.

You can retain the previous functionality by removing the `EXPOSE` directives and modifying the app to listen on port 5000 or supply a custom config. It's really simple.

**Comment by josegonzalez** [comment]
A few things:

- Our current minor releases are our "major" releases until we get closer to my end goal (publishing that soonish), so if you're upgrading, just be aware that we *do* break stuff during minor releases (just not patch, or at least try not to). If you were already using custom `nginx.conf.template` files, this release broke the whole world for you ;)
- This feature - yes, it is a feature, not a bug - is specifically because of the `EXPOSE` functionality. We are mirroring how docker works internally when exposing ports by default. Remove it and we'll use port 80 (or 443 assuming nginx) and proxy to the app on `5000` I think.
- Yeah, sucks that we "removed" this feature, but you get what you get and you don't get upset. Implementing a map of internal port to arbitrary external port would be ideal, but that was *not* in the scope of the change. If you can implement this within a small, self-contained bit of code that doesn't complicate the code, awesome, otherwise we're not interested in supporting this feature outside of `nginx.conf` files.

Those are my thoughts on this, and I'm completely 100% on board with @michaelshobbs here. Would be great to see submissions - code please, not in an issue RFC or a new comment here - from interested parties on this github issue.

**Comment by michaelshobbs** [comment]
> Remove it and we'll use port 80 (or 443 assuming nginx) and proxy to the app on 5000 I think.
 This is true

**Comment by Flink** [comment]
Ok so now that @michaelshobbs show me the light (:grin:), I’ll take a look to adapt my apps to use the standard port 5000 to continue to have automagic config :smiley:

**Comment by michaelshobbs** [comment]
You could also change the `EXPOSE` to port `80`.

**Comment by u2mejc** [comment]
@Flink So the long short of it, just remove `EXPOSE` from your dockerfiles to return heroku like magic for dockerfiles.

**Comment by Flink** [comment]
@michaelshobbs @u2mejc yep, just have to configure the app to listen on the correct port

**Comment by Flink** [comment]
Just upgraded to 0.5.7 and Docker apps proxing is not working anymore, again… :confused: 
It does not proxy to port 5000 anymore when there is no EXPOSE in the Dockerfile, now it finds one, I don’t know where exactly. So I’ve an image with *no* EXPOSE command in the Dockerfile *but* the resulting image exposes ports 80 AND 443! The port 80 was exposed at a time in the git history of the Dockerfile but there was never a port 443. So I really don’t understand what’s wrong this time but it’s kind of getting really annoying… This problem will break my other apps nginx configs and so if I don’t edit by hand the nginx configs for the Docker apps, nothing works!
So any idea? I really don’t understand how this is possible :confused:

**Comment by Flink** [comment]
Ah I think I understand, it might be related to the EXPOSE of the base image. But what’s strange is that it worked before… Well I’ll have to dig further!

**Comment by Flink** [comment]
Ok so that’s related to all Dockerfiles using the `nginx` image that exposes 80 and 443. And it seems there’s no way to unexpose ports… :sob:

**Comment by michaelshobbs** [comment]
This was changed to support deploying arbitrary images bypassing the build process with `tag:deploy`.

https://github.com/dokku/dokku/pull/2163


@josegonzalez no good deed....some of these features are beginning to feel like we're playing whack-a-mole...

**Comment by josegonzalez** [comment]
@michaelshobbs we really just need a way for users to set arbitrary ports to proxy and map to external ports so that they can screw around with it whenever the "magic" fails.

**Comment by Flink** [comment]
@josegonzalez @michaelshobbs guys I think this is working as intended in fact. If I inspect my image it says I have ports 80 & 443 exposed but this is because my image inherits from the `nginx` one. It’s just weird that it was working before but then again it seems that’s more docker related than dokku.
One thing we could do is when setting `DOKKU_DOCKERFILE_PORTS` to `none` or `false` then it forces the standard proxy to port 5000. At the moment I’m with an image that exposes ports I don’t want to be exposed and dokku detects them automatically (so dokku’s fine :D) and re-add them everytime I restart the app.

**Comment by pythdasch** [comment]
Hey everyone, some news about how to fix this issue ? I'm kind of blocked ?

I have my dockerfile port which is expose on port 8080 and my nginx on 80 and so I've to connect to my website on mydomain.com:8080 which is not so cool.

How should i solve this ? I'm with the new version...

**Comment by josegonzalez** [comment]
@pythdasch We mention in our dockerfile docs what the current implementation requires you to do for exposing ports [here](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports).

**Comment by pythdasch** [comment]
@josegonzalez thank you, (sorry I'm newbie with dokku) but still don't understand how I can point my domain to the port 8080. In order to reach it by just typing the domain name and not domain:8080.

Thanks in advance

**Comment by josegonzalez** [comment]
From the docs:

> If you do not explicitly EXPOSE a port in your Dockerfile, dokku will configure the nginx proxy to listen on port 80 (and 443 for TLS) and forward traffic to your app listening on port 5000 inside the container. Just like buildpack apps, you can also use the $PORT environment variable in your app to maintain portability.


So have your app listen to the `$PORT` env var and don't have an `EXPOSE` call in your Dockerfile. Otherwise, what you are trying to do will require a custom `nginx.conf.sigil` in the application repository. The docs for that are also in our documentation.

**Comment by pythdasch** [comment]
Ok because I tried to remove the EXPOSE 8080 but it's still not running well :( 

Maybe have I to remove the expose and put the nginx_port to the 8080 ?

Here is my dockerfile in fact : 

`FROM phusion/baseimage:0.9.16

RUN apt-get update && \
    apt-get install -y \
        libgtk2.0-dev \
        libjasper-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        python-dev \
        python-numpy \
        python-opencv \
        python-pip \
        python-pycurl \
        webp

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install thumbor==5.2.1

COPY thumbor.conf thumbor.conf

CMD thumbor -p 8080 -c thumbor.conf`

**Comment by josegonzalez** [comment]
@pythdasch as I said, you'll need to respect the PORT environment variable and not hardcode port 8080. Please log onto our irc/slack if you have further questions.

**Comment by pythdasch** [comment]
I went but no answers :( sorry to take your time.

**Comment by josegonzalez** [comment]
I'm there now!
