### ISSUE TITLE
`dokku checks` shows touch error messages

### ISSUE THREAD

**Issue by znz** [dokku/dokku#2029]
Description of problem:
`dokku checks` shows touch error messages when 2 or more apps exists.

Output of the following commands

- `dokku version`: v0.5.2-1-g20dfd20

Environment details (AWS, VirtualBox, physical, etc.): test on vagrant with VirtualBox

How was dokku installed?: vagrant up

How reproducible: always

Steps to Reproduce:
1. vagrant up
2. push 2 sample apps
3. dokku checks

Actual Results:
```
vagrant@dokku:~$ dokku checks
-----> App Name           Zero-Downtime Status
touch: cannot touch ‘/home/dokku/node-js-sample\nruby-rails-sample/ENV’: No such file or directory
node-js-sample            true
touch: cannot touch ‘/home/dokku/node-js-sample\nruby-rails-sample/ENV’: No such file or directory
ruby-rails-sample         true
vagrant@dokku:~$
```

Expected Results:
messages without touch error

**Comment by josegonzalez** [comment]
Good catch! I have a PR open, will merge when tests pass :)
