### ISSUE TITLE
How to run dokku locally?

### ISSUE THREAD

**Issue by SnowRipple** [dokku/dokku#203]
Hi there,

I am completely new to Paas, Docker and Dokku and I am trying to get my head around this subject. There are plenty of examples online of how to use e.g. EC2 servers with dokku but I can't find any concerning running/testing it locally.

I started using Ubuntu 13.04 (especially for docker and dokku) but I don't know how to run it locally... Does installing a server like LAMP is needed? Can someone list steps I need to perform please?

Many Thanks

**Comment by pie6k** [comment]
It's a bit old but I have a question :

Do you use some tool to ensure you have the same set of services locally and remotely?
