### ISSUE TITLE
Limit container memory and CPU?

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2033]
Hi,

   I need to limit the max memory a dokku-docker container will use, and soon the CPU as well. I was looking at https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources and saw that docker supports it. I browsed through the dokku issues and found https://github.com/dokku/dokku/issues/125 , https://github.com/dokku/dokku/issues/253 , https://github.com/dokku/dokku/pull/358 but it is not clear what the official answer is.

  So, is there an official way to limit the RAM a docker image in dokku will use? Ditto CPU. Is it currently documented? Thanks!

**Comment by josegonzalez** [comment]
Have you taken a look at our documentation website?

**Comment by josegonzalez** [comment]
Specifically, you can use the official [docker-options](http://dokku.viewdocs.io/dokku/docker-options/) plugin to manage custom options.
