### ISSUE TITLE
Segmentation fault (core dumped) sigil "${SIGIL_PARAMS[@]}" > "$NGINX_CONF"

### ISSUE THREAD

**Issue by Evlos** [dokku/dokku#2034]
Description of problem:

I got an error ```Segmentation fault      (core dumped) sigil "${SIGIL_PARAMS[@]}" > "$NGINX_CONF"```.

Output of the following commands

- `uname -a`:
```
Linux ubuntu 4.5.0-x86_64-linode65 #2 SMP Mon Mar 14 18:01:58 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:           987        580        407          5         10        333
-/+ buffers/cache:        235        751
Swap:          511          2        509
```
- `docker version`:
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 45
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-202:0-121234-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.26 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.22 GB
 Metadata Space Used: 7.487 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-x86_64-linode65
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 987.5 MiB
Name: ubuntu
ID: VGNV:ZMKO:2XPZ:OFNA:SLSI:7I5O:U5X5:EFKR:YYHK:E6V6:4O3H:534Z
WARNING: No swap limit support
```
- `sigil -v`:
```
Segmentation fault (core dumped)
```
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.9
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v88
  heroku-buildpack-php       v95
  heroku-buildpack-play      v26
  heroku-buildpack-python    v77
  heroku-buildpack-ruby      v145
  heroku-buildpack-scala     v66
  buildpack-nginx            v5
```
- `dokku version`:
0.5.2
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.5.2 enabled    dokku core standard plugin
  20_events            0.5.2 enabled    dokku core events logging plugin
  apps                 0.5.2 enabled    dokku core apps plugin
  build-env            0.5.2 enabled    dokku core build-env plugin
  certs                0.5.2 enabled    dokku core certificate management plugin
  checks               0.5.2 enabled    dokku core checks plugin
  common               0.5.2 enabled    dokku core common plugin
  config               0.5.2 enabled    dokku core config plugin
  docker-options       0.5.2 enabled    dokku core docker-options plugin
  domains              0.5.2 enabled    dokku core domains plugin
  enter                0.5.2 enabled    dokku core enter plugin
  git                  0.5.2 enabled    dokku core git plugin
  logs                 0.5.2 enabled    dokku core logs plugin
  named-containers     0.5.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.2 enabled    dokku core plugin plugin
  proxy                0.5.2 enabled    dokku core proxy plugin
  ps                   0.5.2 enabled    dokku core ps plugin
  shell                0.5.2 enabled    dokku core shell plugin
  storage              0.5.2 enabled    dokku core storage plugin
  tags                 0.5.2 enabled    dokku core tags plugin
  tar                  0.5.2 enabled    dokku core tar plugin
```
- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.) ```python```
  - Whether or not you have a `Dockerfile` in the root of your repository ```nope```
  - If using buildpacks, which custom buildpacks are in use
  - If it exists, the contents of your `Procfile`.
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.):
Linode

How was dokku installed?:
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.5.2/bootstrap.sh
sudo DOKKU_TAG=v0.5.2 bash bootstrap.sh
```

How reproducible:
100%

Steps to Reproduce:
1. Create a Linode, and using Ubuntu 15.10 image
2. Install dokku as below and deploy a python app
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.5.2/bootstrap.sh
sudo DOKKU_TAG=v0.5.2 bash bootstrap.sh
```

Actual Results:

```
-----> Cleaning up...
-----> Building temp from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Python app detected
-----> Noticed cffi. Bootstrapping libffi.
       $ pip install -r requirements.txt

---
       config_vars:

-----> Discovering process types
       Procfile declares types -> web
-----> Releasing temp (dokku/temp:latest)...
-----> Deploying temp (dokku/temp:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> App Procfile file found (/home/dokku/temp/DOKKU_PROCFILE)
-----> DOKKU_SCALE file found (/home/dokku/temp/DOKKU_SCALE)
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> temp web container output:
=====> end temp web container output
-----> Running post-deploy
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
=====> renaming container (9675aa7bb0e9) condescending_colden to temp.web.1
-----> Configuring temp.eternalelf.com...(using built-in template)
remote: /var/lib/dokku/plugins/available/nginx-vhosts/functions: line 123: 18135 Segmentation fault      (core dumped) sigil "${SIGIL_PARAMS[@]}" > "$NGINX_CONF"
To dokku@lin.eternalelf.com:temp
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@lin.eternalelf.com:temp'
```

Expected Results:
```Deployment success```

Additional info:

Thank you!

**Comment by michaelshobbs** [comment]
Given that `sigil` doesn't execute outside of dokku either, this should probably be reported under the sigil project. However, it would be good to test the sigil release binary in case there's something wrong with how we built and packaged it. 
Please download it from here (https://github.com/gliderlabs/sigil/releases/download/v0.4.0/sigil_0.4.0_Linux_x86_64.tgz ), run `sigil -v` on your Ubuntu 15.10 Linode instance and report back.

**Comment by KaRi94** [comment]
The same issue on my side. When I've tried run sigil -v I've got segmentation fault.

But after that I've checked man sigil and this is what I got: "sigil - multi-platform ebook editor"
It seems to me that this is not a proper software at all. (https://github.com/Sigil-Ebook/Sigil)

I think we can fix it by install proper sigil package. I am in the process :)

**Comment by josegonzalez** [comment]
Sounds like you will need to uninstall sigil on your system for it to work with dokku. As well, we don't officially support Ubuntu 15.10, only the current Ubuntu LTS (14.04). When the next LTS comes out, we'll add support for that, but until then, this is solely a problem with your system.

`apt-get install sigil` *should* install sigil from our repo, unless you added a custom repo for your other command, in which case ¯\_(ツ)_/¯

Closing, as this is an issue with the user's system, not with dokku.

**Comment by Evlos** [comment]
@michaelshobbs 
```
root@ubuntu:~# wget https://github.com/gliderlabs/sigil/releases/download/v0.4.0/sigil_0.4.0_Linux_x86_64.tgz
root@ubuntu:~# tar xvf sigil_0.4.0_Linux_x86_64.tgz
sigil
root@ubuntu:~# ./sigil -v
0.4.0
```
It works, thanks!

@KaRi94 Install the version above should solve the issue :>

**Comment by michaelshobbs** [comment]
@josegonzalez I think we should probably build both the `sigil` and `plugn` packages using the releases from the respective projects. I can throw together a PR tomorrow if you'd like.

**Comment by michaelshobbs** [comment]
Though now I'm realizing that actually seems to have nothing to do with this issue

**Comment by mekwall** [comment]
I got it to work on Ubuntu 15.10 by doing `apt-get install sigil -t trusty`. That installed the correct package.

**Comment by jocull** [comment]
This is happening on 16.04 LTS as well.

**Comment by micwallace** [comment]
Just an FYI that this is still an issue in Ubuntu 16.04.

Following @Evlos suggestion I downloaded a fresh copy and replaced the /usr/bin binary.

Pretty sure this is a name conflict as the sigil I had installed was the Ebook reader.

**Comment by josegonzalez** [comment]
Hence why I re-opened the issue.

**Comment by michaelshobbs** [comment]
Is this solvable by moving the binary to `/usr/bin` in our package? Then at least we'd get a more useful warning about package collision, right?

ref: #2172

**Comment by josegonzalez** [comment]
Potentially, yes.
