### ISSUE TITLE
Need to set PYTHONPATH for Dockerfile-based deployment for non-web lines in Procfile

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2036]
I am experimenting with 0.5.2 and its support for honouring the Procfile when using Dockerfile-based deployments. Here's my Procfile:

```
web: newrelic-admin run-program gunicorn -c gunicorn_config.py main.wsgi
cronloop: python dashboard/cron/cron_loop.py
```

The web target runs fine, but the cronloop target does not. It gives this error:

```
import main.settings # import this before the model to make sure the models will work
       ImportError: No module named main.settings
```

This workaround seems to work:

```
dokku config:set myapp PYTHONPATH=.:/app
```

No idea why this is not needed for the web line but needed for the cronloop line. Here's my Dockerfile:

```
FROM gliderlabs/alpine:3.3

WORKDIR /app
COPY . /app

RUN apk --update add python libjpeg-turbo zlib py-pillow py-pip postgresql-dev
RUN apk --update add --no-cache --virtual build-dependencies libjpeg-turbo-dev zlib-dev python-dev build-base \
    && pip install -r requirements.txt \
    && apk del build-dependencies

EXPOSE 80

# No CMD because dokku will honor the Procfile and will override CMD with the Procfile line
#CMD gunicorn -b 0.0.0.0:80 -c gunicorn_config.py main.wsgi

```

**Comment by michaelshobbs** [comment]
Probably something to do with how gunicorn executes your app. Not sure there's anything dokku can do here as you also have a workaround in place. @josegonzalez any thoughts here?

**Comment by josegonzalez** [comment]
Thats how python works. If it's not in your virtual environmnent, you have to set the PYTHONPATH to include those files.

Not a bug with dokku at all.

**Comment by mmerickel** [comment]
You could add the `ENV` line to your dockerfile as a better fix.

**Comment by sglebs** [comment]
@josegonzalez : why is it that it works for "web" then?

I suspect the "current dir" for the "web" line is the /app directory but not for the "cronloop" line.

**Comment by josegonzalez** [comment]
Your intuition is wrong. `newrelic-admin`probably sets the path to $PWD.
