### ISSUE TITLE
Checks appear to pass, even when it should fail

### ISSUE THREAD

**Issue by brandoncarl** [dokku/dokku#2037]
Description of problem:
Check passes, even when it should fail

Output of the following commands

- `uname -a`:
```Linux yllw 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```

- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:           490        444         45          0          6         63
-/+ buffers/cache:        374        115
Swap:         4095         63       4032
```

- `docker version`: 1.10.1
- `docker -D info`:
```
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 21
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: yllw
ID: OFVD:BK2N:YTPG:VHLM:PLQ6:AUZE:CC6V:NFJQ:V53E:6MI6:WUQH:UYFJ
WARNING: No swap limit support
```
- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.8
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v5
```

- `dokku version`: 0.5.2
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.5.2 enabled    dokku core standard plugin
  20_events            0.5.2 enabled    dokku core events logging plugin
  apps                 0.5.2 enabled    dokku core apps plugin
  build-env            0.5.2 enabled    dokku core build-env plugin
  certs                0.5.2 enabled    dokku core certificate management plugin
  checks               0.5.2 enabled    dokku core checks plugin
  common               0.5.2 enabled    dokku core common plugin
  config               0.5.2 enabled    dokku core config plugin
  docker-options       0.5.2 enabled    dokku core docker-options plugin
  domains              0.5.2 enabled    dokku core domains plugin
  enter                0.5.2 enabled    dokku core enter plugin
  git                  0.5.2 enabled    dokku core git plugin
  logs                 0.5.2 enabled    dokku core logs plugin
  named-containers     0.5.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.2 enabled    dokku core plugin plugin
  proxy                0.5.2 enabled    dokku core proxy plugin
  ps                   0.5.2 enabled    dokku core ps plugin
  shell                0.5.2 enabled    dokku core shell plugin
  storage              0.5.2 enabled    dokku core storage plugin
  tags                 0.5.2 enabled    dokku core tags plugin
  tar                  0.5.2 enabled    dokku core tar plugin
```

- `docker inspect CONTAINER_ID` (if applicable): not applicable
- `cat /home/dokku/<app>/nginx.conf` (if applicable): not applicable
- Link to the exact repository being deployed (if possible/applicable): not applicable
- Output of failing dokku commands after running `dokku trace on`: commands not failing

Environment details (AWS, VirtualBox, physical, etc.): DigitalOcean

How was dokku installed?: apt-get

How reproducible: not reproducible
Steps to Reproduce: private repo, see Additional Info

Actual Results:
Check passes

Expected Results:
Check fails

Additional info:
Check access /ready, and expects "ready". Serving returning "booting", but check passes.

**CHECKS** file
```
WAIT=20
ATTEMPTS=10

/endpoint       ready
```

Verified via web browser that "/endpoint" returns "booting" and not "ready"

**Comment by josegonzalez** [comment]
Your deploy isn't working properly, so the deploy is "failing". Please include the stacktrace of a deploy after running `dokku trace on`.

**Comment by brandoncarl** [comment]
Hi @josegonzalez, thanks for your help.

The stacktrace is 10K lines long. I'm happy to gist a subset, but want to make sure there's no sensitive information in there. Can you recommend the areas to focus on?

Separately, searching through the stacktrace, there are no "fail" messages. The build succeeded, and on the surface everything looks great. The new deploy is then available on the website.

**Comment by josegonzalez** [comment]
The part where it does the curl on your endpoint.

**Comment by michaelshobbs** [comment]
I definitely can't reproduce this behavior with the following `CHECKS` file. The endpoint returns `Hello World!`. Repo is here: https://github.com/michaelshobbs/node-js-sample
```
WAIT=2
TIMEOUT=5
ATTEMPTS=2

/ Hello!
```

**Comment by brandoncarl** [comment]
I've attached the a gist with a subset of the stacktrace here: https://gist.github.com/brandoncarl/5aeefbb146745834a30a

Notably, nowhere in the stacktrace is my endpoint referenced...

**Comment by michaelshobbs** [comment]
It looks like maybe you trimmed this output too much? For example where is the output from these lines?
https://github.com/dokku/dokku/blob/v0.5.2/plugins/checks/check-deploy#L197-L198

**Comment by michaelshobbs** [comment]
Is there not a newline at the end of your `CHECKS` file? I thought we handled that correctly but maybe I'm mistaken.

**Comment by brandoncarl** [comment]
@michaelshobbs @josegonzalez The newline solved it. Thank you guys for the awesome product and getting to the bottom of this quickly.

**Comment by brandoncarl** [comment]
As an aside, it would be awesome if the checks had a FIRST_CHECK and then WAIT. i.e. First check occurs after 90 seconds, and then checks every 10 seconds thereafter. This would allow users to estimate the start time and then quickly check the server...
