### ISSUE TITLE
Upgrade documentation needs improvements

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2041]
The install instructions on the home page say:

```
wget https://raw.githubusercontent.com/dokku/dokku/v0.5.2/bootstrap.sh
sudo DOKKU_TAG=v0.5.2 bash bootstrap.sh
```
It calls this " install from a stable release".

The page documenting how to upgrade http://dokku.viewdocs.io/dokku/upgrading/ , on the other hand, says:

   * "If dokku was installed via a debian package"  - I presume this is not the case if I used bootstrap.sh as suggested above
   * " If you have installed dokku from source" - I presume this is not the case because I did not clone the repo, I used the bootstrap.sh approach.
      * BTW, cd ~/dokku does not work for me. It has to be cd ~/../dokku. And indeed this approach is not the correct one in my case: git pull --tags origin master -> fatal: Not a git repository (or any of the parent directories): .git

  So, if I have 0.4.4 installed from wget/bootstrap.sh as the home page suggests, how can I upgrade to 0.5.2? Re-run the same install steps (wget/bootstarp.sh)?

  If this is the case, I suggest adding a section to the doc saying " if you installed from wget/bootstrap.sh as the home page suggests, you can upgrade....".

**Comment by seantanly** [comment]
@sglebs I believe the bootstrap.sh approach installs Dokku via debian package. If you do `apt-get update` and then `apt-get upgrade -s`, you should see Dokku listed when there is an available Dokku package for upgrade.

**Comment by josegonzalez** [comment]
@sglebs pull requests welcome.
