### ISSUE TITLE
No way to set nginx port when using expose in dockerfile

### ISSUE THREAD

**Issue by hayes** [dokku/dokku#2053]
Description of problem:
I have a simple node app with a docker file that looks like:
```dockerfile
FROM node:onbuild
EXPOSE 8080
```
When this is pushed to the dokku host, dokku automatically sets: `DOKKU_DOCKERFILE_PORTS=8080`

It appears that when this is set, `dokku nginx:build-config app-name` will use 8080 for both the app port that is proxied to and `NGINX_PORT`.  When running `dokku config:unset app=name DOKKU_DOCKERFILE_PORTS` and rerunning  `dokku nginx:build-config app-name` the nginx config still proxies to `8080` but now listens on `80` as expected. Unfortunately `DOKKU_DOCKERFILE_PORTS` is set again when the app is rebuilt.

Manually setting `DOKKU_NGINX_PORT` in the app config does not overwrite this behavior.

Output of the following commands

- `uname -a`: `Linux DokkuVM 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
- `free -m`:
```bash
total       used       free     shared    buffers     cached
Mem:          1678        807        871          0         81        416
-/+ buffers/cache:        308       1369
Swap:            0          0          0
```
- `docker version`:
- `docker -D info`:
- `sigil -v`:
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
- `dokku version`:
```bash
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
mhayes@DokkuVM:~$ sudo -u dokku docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```
- `dokku plugin`:
```bash
 00_dokku-standard    0.5.3 enabled    dokku core standard plugin
  20_events            0.5.3 enabled    dokku core events logging plugin
  apps                 0.5.3 enabled    dokku core apps plugin
  build-env            0.5.3 enabled    dokku core build-env plugin
  certs                0.5.3 enabled    dokku core certificate management plugin
  checks               0.5.3 enabled    dokku core checks plugin
  common               0.5.3 enabled    dokku core common plugin
  config               0.5.3 enabled    dokku core config plugin
  docker-options       0.5.3 enabled    dokku core docker-options plugin
  domains              0.5.3 enabled    dokku core domains plugin
  enter                0.5.3 enabled    dokku core enter plugin
  git                  0.5.3 enabled    dokku core git plugin
  letsencrypt          0.7.0 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.5.3 enabled    dokku core logs plugin
  named-containers     0.5.3 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.3 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.3 enabled    dokku core plugin plugin
  proxy                0.5.3 enabled    dokku core proxy plugin
  ps                   0.5.3 enabled    dokku core ps plugin
  shell                0.5.3 enabled    dokku core shell plugin
  storage              0.5.3 enabled    dokku core storage plugin
  tags                 0.5.3 enabled    dokku core tags plugin
  tar                  0.5.3 enabled    dokku core tar plugin
```
- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
```
server {
  listen      [::]:8080;
  listen      8080;
  server_name trimet.hayes.io;
  access_log  /var/log/nginx/trimet-access.log;
  error_log   /var/log/nginx/trimet-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://trimet-8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
}
include /home/dokku/trimet/nginx.conf.d/*.conf;

upstream trimet-8080 {
  server 172.17.0.2:8080;
}
```
- Link to the exact repository being deployed (if possible/applicable): https://github.com/hayes/trimet
- If a deploy is failing:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - Whether or not you have a `Dockerfile` in the root of your repository
  - If using buildpacks, which custom buildpacks are in use
  - If it exists, the contents of your `Procfile`.
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.):
Azure
How was dokku installed?:
the magic azure install button, then apt-get upgrade

How reproducible:
I have not done this on a clean install, but I have done it after destroying and recreating the app

Steps to Reproduce:
1. Create an app with a docker file that resembles the one above
2. Git push dokku master
3. Check nginx config

Actual Results:
nginx config pasted above. nginx listens on exposed port rather than expected default port.

Expected Results:
nginx listens on port 80, or can be overwitten by setting `DOKKU_NGINX_PORT`

Additional info:

**Comment by hayes** [comment]
I have worked around the issue by listening on 5000, and not expose a port in the docker file, but thought I should report the issue anyways

**Comment by michaelshobbs** [comment]
This is as designed

See discussion here #2028

**Comment by josegonzalez** [comment]
This is as expected. If you specify `EXPOSE`, they will automatically override `DOKKU_DOCKERFILE_PORTS` on every run. The documentation has been updated to reflect this, and if you'd like to work on a feature to make it possible to map internal ports to external, then you can follow the [following comments](https://github.com/dokku/dokku/issues/2028#issuecomment-203092066) for that feature.

**Comment by michaelshobbs** [comment]
http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports

**Comment by hayes** [comment]
I see, thanks, and sorry for the duplicate report. Maybe I'll try to PR
some docs changes that explain this better. I had assumed it was a bug
because it used to work differently.
