### ISSUE TITLE
Wrong application URL displayed when using custom Nginx template

### ISSUE THREAD

**Issue by tobru** [dokku/dokku#2054]
When using a custom Nginx template `nginx.conf.sigil` which overrides the ports (see also #2028) then the last output of the deployment is wrong:

```
[...]
=====> Application deployed:
       http://myapp.dokkuhost.mydomain.net:9090
```

The port `9090` is defined in the Dockerfile but in the custom Nginx template I override it to proxy port 80 to port 9090.

I wish we would be able to set the Nginx port with a variable like `DOCKERFILE_NGINX_PORT` to not have to replicate the very same `nginx.conf.sigil` to _every_ project which should proxy port 80 to the `EXPOSE` port. As `.RAW_TCP_PORTS` is at the top of the system Nginx template and this variable is not overridable, we have no chance to change the behaviour withouch changing the code.

* Dokku Version: 0.5.3
* Deployment type: Dockerfile

**Comment by josegonzalez** [comment]
If you'd like to work on a PR that implements the functionality I mention in my [comment here](https://github.com/dokku/dokku/issues/2028#issuecomment-203092066), that would be acceptable. 

Otherwise, the documentation clearly states how this should work and we don't have plans to change this.

**Comment by michaelshobbs** [comment]
Seems like there's two issues here. One is the desire to not have to use custom templates and second is the `dokku urls` command not showing ports from custom nginx templates. 

The former is understandable and a PR to address this in a sane way is welcomed. The latter seems like a legit bug. 

@josegonzalez thoughts on the latter?

**Comment by tobru** [comment]
Sorry for mixing things here =(

**Comment by josegonzalez** [comment]
Ah, didn't see the latter. Thats a bug? Re-opening, though idk what the fix for that is :P

**Comment by tobru** [comment]
Something like: `if get_custom_nginx_template() then grep info from server_name and listen directive`? (not actual code)

**Comment by josegonzalez** [comment]
Yeah I guess I'm trying to think of what that grep looks like :P

**Comment by michaelshobbs** [comment]
Thinking further on this and other issues related to dockerfile port mappings. Perhaps we can have a syntax for the `DOKKU_NGINX_*_PORT` variables that allow a user to map the nginx listen port to a container port.

example
```
DOKKU_NGINX_PORT=80->8080
DOKKU_NGINX_SSL_PORT=443->8443
```

**Comment by michaelshobbs** [comment]
Scratch that. @josegonzalez reminded me offline about previous conversations around port mapping. Will put an RFC together and start working on code.

**Comment by josegonzalez** [comment]
@michaelshobbs can this be closed out or no?

**Comment by michaelshobbs** [comment]
Closing for now. Feel free to comment if it still doesn't work in 0.6.x
