### ISSUE TITLE
Command-line tool to initialize Dokku

### ISSUE THREAD

**Issue by kaby76** [dokku/dokku#2056]
Description of problem:

Is there a command-line tool to initialize Dokku? There doesn't seem to be. In the documentation, after the first two step of installing Dokku, it then says " # go to your server's IP and follow the web installer". When I create a Ubuntu installation through a VPS provider, the box doesn't have a GUI installed, it's a big deal to get VNC set up, and I cannot stand using a GUI anyways. Also, exposing the initialization where something can input a SSH key and set up the "dokku" account is a security risk, e.g., through a Redis install. Instead, I just want to initialize Dokku on the box with a command-line script.

Additional info:

Here's a Bash script I wrote, with the help of Fiddler, to initialize Dokku without a browser.

 #
 # Set up Dokku via command line

 set -e

 if [ "$#" -ne 1 ]; then
  echo "Try this: cat ~/.ssh/id_rsa.pub | ${0##*/} -"
  exit 1
 fi

 export IP=`ip route get 8.8.8.8 | awk '{print $NF; exit}'`
 export KEY=$(</dev/stdin)

 if [ "${KEY/ssh-rsa}" = "$KEY" ] ; then
  echo "Input is not a ssh key."
  exit 1
 fi

 curl "http://localhost" > /dev/null 2>&1

 curl -XPOST --data \
        "keys=$KEY&hostname=$IP" \
        "http://localhost/setup"

**Comment by josegonzalez** [comment]
You can actually use [`debconf`](http://dokku.viewdocs.io/dokku/getting-started/install/debian/#unattended-installation) with the bootstrap file to setup your application in an unattended way. This will skip running the web ui and can be used for setting up dokku via ansible/chef/puppet.
