### ISSUE TITLE
Global Certification does not work

### ISSUE THREAD

**Issue by znz** [dokku/dokku#2057]
Description of problem:
I tried to use [Global Certification](http://dokku.viewdocs.io/dokku~v0.5.3/deployment/ssl-configuration/#global-certification), but it does not work.

Output of the following commands
- `dokku version`: `v0.5.3-6-ge114ab3`

Environment details (AWS, VirtualBox, physical, etc.): VirtualBox
How was dokku installed?: `vagrant up`

How reproducible:
[Global Certification](http://dokku.viewdocs.io/dokku~v0.5.3/deployment/ssl-configuration/#global-certification)

Steps to Reproduce:
1. `dokku certs:generate ruby-rails-sample`
2. `sudo mv /home/dokku/ruby-rails-sample/tls /home/dokku/`
3. `dokku ps:restartall`

Actual Results:
ruby-rails-sample app does not redirect to https.

Expected Results:
ruby-rails-sample app redirects to https.

Additional info:
Removed this feature at https://github.com/dokku/dokku/commit/9842d7498b8b731dc31cb82d61c8256982eed93c .
So I think this change is intentional and document should be updated.

**Comment by michaelshobbs** [comment]
This was removed in 0.5. The documentation needs to be updated. I'll get that going shortly. 

https://github.com/dokku/dokku/blob/master/docs/appendices/0.5.0-migration-guide.md


@josegonzalez can you please link the migration guide into the docs site somewhere??

**Comment by josegonzalez** [comment]
It's on the upgrading docs...

**Comment by michaelshobbs** [comment]
Link?
