### ISSUE TITLE
Running commands after any dokku command

### ISSUE THREAD

**Issue by crisward** [dokku/dokku#2063]
Description of problem:
I'd like to be able to run commands after any dokku command via a trigger. I'm currently using user-auth,  then running my command in the background, sleeping for 30 seconds... This kind of works, but there is no guarantee the original command has finished. If I could get the process id of the actual command I could maybe wait for that to exit, then run. Any ideas?

I basically trying to inform a remote service when any dokku activity has occurred.

Output of the following commands
- `dokku version`:0.4.13

**Comment by michaelshobbs** [comment]
Not sure how this would work. PRs welcomed. 

@josegonzalez thoughts?

**Comment by josegonzalez** [comment]
I'm not sure of what you are trying to do here. What is the command you are trying to run in the background?

**Comment by crisward** [comment]
I'm building a web interface to control all of our servers. It integrates with digital ocean, linode etc. Each vm runs dokku, each website running as a dokku app. The web interface needs to be kept in sync with dokku's state. To achieve this I had a sync command which ran lots of dokku commands, then parsed the output. This was proving a bit slow. To speed it up I now only run the commands after something happens in dokku, and cache the output in text files. The sync process now just needs to parse these cached files.

The command that is being run is to output the list of databases after they've been added, deleted, linked and unlinked. However I don't know when these command have finished. So I wait 30 second, which is probably ok most of the time, but it's not ideal for obvious reasons.

You can see my work in progress here 
https://github.com/crisward/dokku-gplive

**Comment by josegonzalez** [comment]
You could use [this](https://github.com/dokku/dokku-daemon) on every instance, which returns the output and a status of the command output. Just mount that into an api of sorts and then you can run commands like that.

**Comment by crisward** [comment]
Thanks for that, looks interesting.
