### ISSUE TITLE
[RFC]: completely disable zero-downtime

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#2073]
In `0.5.0` we introduced the `checks` plugin and the ability to disable zero-downtime checks. 
i.e.: https://github.com/dokku/dokku/blob/v0.5.3/plugins/checks/check-deploy#L61-L64
```
  if [[ "$(is_app_checks_enabled "$APP")" == "false" ]]; then
    dokku_log_info2_quiet "Zero downtime checks for app ($APP) have been disabled. moving on..."
    exit 0
  fi
```

However, we don't actually disable "zero-downtime" when doing this. We still startup a new container alongside the previous one and just short circuit the execution of checks.

We would like to allow the latter to be modified on a per app basis thus that a user can define an app's container(s) be stopped prior to the new deployed container being started. This RFC is meant to cover the details on UI and implementation.

New UI:
```
$ dokku checks:help
Usage: dokku checks[:COMAND]

Manage zero-downtime checks.

Additional commands:
    checks <app>           Show zero-downtime status
    checks:disable <app> [<process-type>]    Disable zero-downtime deployment  (WARNING: this will cause downtime during deployments)
    checks:enable <app> [<process-type>]    Enable zero-downtime deployment
    checks:skip <app> [<process-type>]   Skip zero-downtime checks
```

- introduces `checks:skip` that implements the current functionality of just skipping zero-downtime checks
- changes `checks:disable` to truly disable zero-downtime deploys (for all processes or just specified ones)
  - i.e. stop old container before starting new container (implies `skip`)
- `DOKKU_CHECKS_ENABLED=0` will be migrated to `DOKKU_CHECKS_SKIPPED="_all_"`
- `DOKKU_CHECKS_DISABLED` will be a comma-separated list of process types for which we won't follow zero-downtime deployment logic; can also be set to `_all_`.
- Running `disable`, `enable`, `skip` without a process type will be the same as running with all process types. We will use a special marker (perhaps `_all_` or similar) to denote this state.

**updated based on conversation from #2125**

**Comment by josegonzalez** [comment]
Love it. I assumed we could already disable the zero downtime deploys :P

This will certainly help users deploying apps where they have yet to create a TCP/UDP proxy (IRC or VPN software for instance).

- Are we reusing the var used for the current disable in the new disable?
- Is the current `checks:disable` mapping to `checks:skip`?
- What, if any, migration process is there?
- Remember to add to docs.

**Comment by josegonzalez** [comment]
One other comment. I *really* want to get the config refactor in, since we're polluting the fuck out of app env vars.

I'm also starting to see the benefits of having a "merge" branch...

**Comment by michaelshobbs** [comment]
> - Are we reusing the var used for the current disable in the new disable?
Undecided. If not, we can do another variable migration like we did in `0.5.0`
> - Is the current checks:disable mapping to checks:skip?
Yes
> - What, if any, migration process is there?
Haven't thought through that yet. Though on the surface it would only be variables if we changed their meaning.
> - Remember to add to docs.
I'll probably forget but I'll do my best :smile:

**Comment by michaelshobbs** [comment]
> One other comment. I really want to get the config refactor in, since we're polluting the fuck out of app env vars.

What's the relevance to this RFC?

**Comment by josegonzalez** [comment]
We'll have:

- `DOKKU_CHECKS_ENABLED`
- `DOKKU_CHECKS_SKIPPED`

Not really relevant to this PR (feel free to do the work without worrying about that) just something I wanted to put out there...

**Comment by michaelshobbs** [comment]
I've updated the main issue description with the migration plan and data format

**Comment by josegonzalez** [comment]
Looks good to me. Build it!

**Comment by josegonzalez** [comment]
Closing as there is a PR open for this functionality that will be merged for the next release.
