### ISSUE TITLE
Dockerfile (with EXPOSE) HTTPS/SSL config is not generated correctly

### ISSUE THREAD

**Issue by Crispy1975** [dokku/dokku#2078]
Description of problem:
On adding a wildcard certificate to an existing application we would expect the `nginx.conf` inside of the application folder to contain an `https` block, however it does not. The application is deployed via Dockerfile and exposes port 80 of the container.

Dokku reports that it thinks it has generated an `https` config in the output from the `dokku certs:add` command.

Adding a new domain to the app does update the nginx config, this shows that the config is writeable and working with other features.

Output of the following commands

```shell
$ uname -a
Linux instance-1 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```shell
$ free -m
             total       used       free     shared    buffers     cached
Mem:          7480       6706        774          0        286       3820
-/+ buffers/cache:       2599       4881
Swap:            0          0          0
```

```shell
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

```shell
$ docker -D info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 19
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-56-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.305 GiB
Name: instance-1
ID: 6NAN:VGFU:OP3F:4M43:AYKH:LXBQ:H3GM:3KZP:ARQT:7G4D:M243:S5QW
WARNING: No swap limit support
```

```shell
$ sigil -v
0.4.0
```

```shell
$ dokku version
0.5.2
```

```shell
$ dokku plugin
plugn: dev
  00_dokku-standard    0.5.2 enabled    dokku core standard plugin
  20_events            0.5.2 enabled    dokku core events logging plugin
  apps                 0.5.2 enabled    dokku core apps plugin
  build-env            0.5.2 enabled    dokku core build-env plugin
  certs                0.5.2 enabled    dokku core certificate management plugin
  checks               0.5.2 enabled    dokku core checks plugin
  common               0.5.2 enabled    dokku core common plugin
  config               0.5.2 enabled    dokku core config plugin
  deployment-keys      0.1.0 enabled    Manage SSH deployment keys that should get injected into your containers on-build
  docker-options       0.5.2 enabled    dokku core docker-options plugin
  domains              0.5.2 enabled    dokku core domains plugin
  enter                0.5.2 enabled    dokku core enter plugin
  git                  0.5.2 enabled    dokku core git plugin
  hostkeys-plugin      0.1.0 enabled    Manage hostkeys for your container environment
  logs                 0.5.2 enabled    dokku core logs plugin
  logspout             0.2.0 enabled    sends dokku app stdout to a logging service
  named-containers     0.5.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.2 enabled    dokku core plugin plugin
  proxy                0.5.2 enabled    dokku core proxy plugin
  ps                   0.5.2 enabled    dokku core ps plugin
  shell                0.5.2 enabled    dokku core shell plugin
  storage              0.5.2 enabled    dokku core storage plugin
  tags                 0.5.2 enabled    dokku core tags plugin
  tar                  0.5.2 enabled    dokku core tar plugin
```

```shell
$ cat /home/dokku/<app>/nginx.conf
server {
  listen      [::]:80;
  listen      80;
  server_name test.preview.example.com preview.example.com; 
  access_log  /var/log/nginx/preview.example.com-access.log;
  error_log   /var/log/nginx/preview.example.com-error.log;
  location    / {
    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;
    proxy_pass  http://preview.example.com-80;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
}
include /home/dokku/preview.example.com/nginx.conf.d/*.conf;
upstream preview.example.com-80 {
  server 172.17.0.3:80;
}


```

Environment details (AWS, VirtualBox, physical, etc.):
Google Cloud

How was dokku installed?:
Using the `apt-get` install as per Dokku documentation.

How reproducible:
Add wildcard certificate as per the `certs:add` command to the desired app, it reports that all is ok, and an `https` config has been generated. However this is not the case.

Steps to Reproduce:
1. dokku certs:add <app> server.crt server.key
2. dokku certs:info <app>
3. sudo cat ~dokku/<app>/nginx.conf

Actual Results:
No https/ssl block in the `nginx.conf` for the app.

Expected Results:
To have an https/ssl block in the `nginx.conf` for the app in question.

**Comment by michaelshobbs** [comment]
Can you please include a gist of a restart or deploy of your app with dokku trace on?

**Comment by Crispy1975** [comment]
@michaelshobbs here ya go...

**Comment by michaelshobbs** [comment]
I think I see the issue. Can you also please include the contents of your dockerfile?

(NOTE: merged #2080 to update issue template for the future)

**Comment by Crispy1975** [comment]
@michaelshobbs 

https://gist.github.com/Crispy1975/bc1a3a5ae07075eb04cf603215a1f952

**Comment by michaelshobbs** [comment]
Thanks. So currently SSL is not supported when you use `EXPOSE`. (Let's not get into the why. It just isn't right at this point. We expanded what dokku does with `EXPOSE` in `0.5.x` and I'm attempting to sort through the broader use cases of `EXPOSE` in an attempt to come up with a "proper" implementation) 

The short-term solution for this app is to configure the nginx process **inside the container** to listen on port `5000` and remove the `EXPOSE` directive from the dockerfile. You might also need to unset `DOKKU_DOCKER_PORTS` after pushing the other changes.

**Comment by Crispy1975** [comment]
The problem we have is these containers have to work in Dokku for our straging environments and Deis in production which has SSL termination at the nginx routers... am I right in as assuming this is a new issue in the `0.5.x` series as we've been using Dokku for a while and never had the `EXPOSE` problem before?

**Comment by josegonzalez** [comment]
This probably "worked" at some point in 0.4.x, but we revamped how we handle nginx and proxying globally in 0.5.x. Whether we "fix" this issue or not is... up for discussion. We're currently attempting to piece together what people expect/don't expect from dokku, especially in regards to dockerfiles, where you have more "control" over what is going on, and therefore less hand-holding and niceties you would get with buildpacks.

**Comment by Crispy1975** [comment]
From our point of view at least it is very handy to do SSL termination at nginx and not have to worry about certs inside containers. This makes it easy to do the Docker thing and move to Deis without changing images. Everything just works.

This has "worked" since `0.3.x` through `0.4.x`, and has only hit this issue as you say with the changes in `0.5.x`.

**Comment by josegonzalez** [comment]
Would you be up for making a PR to fix the issue?

**Comment by michaelshobbs** [comment]
@Crispy1975 this definitely changed in 0.5.0. Was your comment about this working in dokku and deis meant to imply removing the `EXPOSE` directive is not possible for you?

I think the correct move for this specific use case (of which I'm sure there are others hitting this) is to include the SSL config in the template path we use when we see `EXPOSE` directives. I can put that together.

**Comment by michaelshobbs** [comment]
Thinking about this further I'm a bit stuck. This particular case is easy because we know port 80 is http and we want to support an SSL connection on 443. This would create the standard port 80 server listener that redirects to the port 443 listener. (This is what we do for buildpack apps and apps that don't use `EXPOSE`)

However, what if someone has `EXPOSE 8080` or multiple `EXPOSE` directives, and wants to do SSL? The current implementation takes every `EXPOSE` port and creates a 1:1 nginx `server` to `upstream` block. So let's say a user pushes a dockerfile with `EXPOSE 8080` and `EXPOSE 8088`. What do we do then? 

I implemented the `EXPOSE` support with the assumption that folks were taking more ownership of how they wanted their app deployed. I think this is another case where we can't (or shouldn't) wrap automagic under the covers and require the user ship their own custom template. 

@josegonzalez @Crispy1975 thoughts?

**Comment by josegonzalez** [comment]
I think my suggestion from [this comment](https://github.com/dokku/dokku/issues/2028#issuecomment-203092066) is still valid:

> Yeah, sucks that we "removed" this feature, but you get what you get and you don't get upset. Implementing a map of internal port to arbitrary external port would be ideal, but that was not in the scope of the change. If you can implement this within a small, self-contained bit of code that doesn't complicate the code, awesome, otherwise we're not interested in supporting this feature outside of nginx.conf files.

We currently do this for the services when you do `dokku service:expose`, so it doesn't seem like too big of a leap to do it here.

I definitely agree that we can't just auto-expose a port behind ssl for dockerfile users just because a user has a cert attached. Too many if statements there.

**Comment by michaelshobbs** [comment]
@Crispy1975 I think there's two paths here. One short term and another long term. First, to make this work **today** use a custom [nginx template](http://dokku.viewdocs.io/dokku/nginx/#customizing-the-nginx-configuration). Second, someone implements the port mapping stuff that exposes nginx to app-container port mapping config.

**Comment by josegonzalez** [comment]
One thing: we *probably* shouldn't be showing a url on port `80` with `https`. Pretty sure *no one* does that :P

**Comment by michaelshobbs** [comment]
@josegonzalez If you're referring to custom templates and urls output, that is a bug that has already been reported in #2054

**Comment by josegonzalez** [comment]
Gotcha.

**Comment by Crispy1975** [comment]
From the Deis 1.x perspective they deal with this by only handling a single `EXPOSE`, for us this works as we never open more than a single port but could be an issue for those running services like MongoDB which can have multiple ports open.

Immediate fix is going to be a custom nginx config I believe, that will work in the interim.

Regarding the 1:1 mapping wouldn't it work by creating an upstream block for http and https with a unique identifier for each exposed port? Or maybe introduce a config setting that defines which port(s) the https upstream block is to forward to?

**Comment by michaelshobbs** [comment]
The latter is what I believe @josegonzalez is referring to. I think there are two concerns here
- you want a port 80 http listener in nginx that forwards to a port 443 SSL listener that then forwards to an upstream 
- other folks want to `EXPOSE` one or more ports (for say an internal service) and in that case we would want to a single listener per `EXPOSE` port and apply SSL (with no redirect) if a cert is present

I'm not sure how to "magically" solve both concerns given the same `EXPOSE` directive in both cases. How does dokku know what you want to do?

**Comment by michaelshobbs** [comment]
@Crispy1975 Added this to docs: http://dokku.viewdocs.io/dokku/nginx/#example-http-to-https-custom-template

Lemme know if it's helpful

**Comment by Crispy1975** [comment]
@michaelshobbs that should work perfectly for us, thanks.

On the port thing, perhaps something like...

`dokku ports:add <app> <from> <to>`

...and for an ssl port...

`dokku ports:add-ssl <app> <from> <to>`

...then you would also have the usual `remove`, `list` commands that go along with it. Dokku could perhaps detect the `EXPOSE` with multiple ports and map those in with the port being tagged onto the end of the upstream name in the config to keep it unique. Default would map in using non-SSL TCP connections unless a user then specified they wanted SSL on a specific port in which case they would remove the port listener and add an SSL one. Maybe not that streamlined, but ports aren't things that generally get changed that often so not like people would have to do it all the time.

**Comment by josegonzalez** [comment]
@Crispy1975 that sounds great, would you mind starting a patch for this?

**Comment by Crispy1975** [comment]
@josegonzalez I can certainly give it a go when I have some time, but time is quite hard to come by at the moment.

**Comment by josegonzalez** [comment]
Same here ;)
