### ISSUE TITLE
rename sigil due to package name conflict in latest ubuntu

### ISSUE THREAD

**Issue by MikeSchroll** [dokku/dokku#2087]
Description of problem:
dokku on ubuntu 15.10 (wiley) and upcoming LTS release 16.04 (Xenial) is broken due to a conflict with new package introduced in 15.10 called [sigil](http://packages.ubuntu.com/wily/sigil) with a naming conflict. Pre-release freeze of 16.04 appears to [include it](https://launchpad.net/ubuntu/+source/sigil)).

As a result of this conflict, dokku installs the sigil ebook-reader, which then makes the sigil command available to the system, causing errors like this during deploy:
remote: /var/lib/dokku/plugins/available/nginx-vhosts/functions: line 123: 18135 Segmentation fault      (core dumped) sigil "${SIGIL_PARAMS[@]}" > "$NGINX_CONF"

This was previously covered in #2034 however now it seems that with upcoming Ubuntu LTS having this package, @josegonzalez has commented [here](https://github.com/dokku/dokku/pull/1812#issuecomment-206117877) that perhaps dokku's sigil should be renamed.

I'm capturing this problem in a fresh issue so its not lost. (and because selfishly I'm affected by it in Ubuntu 15.10)

**Comment by josegonzalez** [comment]
Good thing we only officially support Ubuntu 14.04 :P

**Comment by MorrisJobke** [comment]
I also ran into this on ArchLinux - I simply defined, that it conflicts with the epub reader: https://aur.archlinux.org/packages/gliderlabs-sigil/

🙈 🙉 🙊

**Comment by josegonzalez** [comment]
So what should we name it?

**Comment by michaelshobbs** [comment]
Isn't the binary name still the same?

**Comment by josegonzalez** [comment]
Right, the binary is the same, but the package name should change.

**Comment by michaelshobbs** [comment]
Soooooo what if a user has them both installed?

**Comment by josegonzalez** [comment]
Our package will conflict with it (apt has a mechanism for it). We'll make sigil a pre-install requirement, so if it's install fails, dokku won't install.

**Comment by michaelshobbs** [comment]
:+1:

**Comment by MorrisJobke** [comment]
> Our package will conflict with it (apt has a mechanism for it). We'll make sigil a pre-install requirement, so if it's install fails, dokku won't install.

That is what I also did ... it's not nice, but it works for now.

**Comment by josegonzalez** [comment]
This was fixed in 0.5.8.

**Comment by MikeSchroll** [comment]
Fixed in this commit: https://github.com/dokku/dokku/commit/56dde3ff31a6b4152aea5945c0b6b17cda20e877

Thanks!
