### ISSUE TITLE
EmberJS Buildpack Fails to Install

### ISSUE THREAD

**Issue by alexking** [dokku/dokku#2090]
Heroku provides this [emberjs](https://www.heroku.com/emberjs) buildpack to run static or [fastboot](http://www.ember-fastboot.com) ember sites.The actual repository is at [heroku/heroku-buildpack-emberjs](https://github.com/heroku/heroku-buildpack-emberjs.git), but they recommend using a prebuilt `tgz` as the buildpack URL - 

> This buildpack has a binary component, so it needs to be compiled beforehand. It's easiest just to use the buildpack with the prebuilt binary.
>
> https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz

I've successfully been able to use that URL with Heroku, but I'm unable to get it to work with Dokku - running the following,

    dokku config:set reviews BUILDPACK_URL=https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz

This causes deploys to fail at `-----> Fetching custom buildpack` with no other details – [deploy with trace on here](https://gist.github.com/alexking/1233878e44574cfb724bbd905ffa2427).

I've also tried using the `.git` repository URL instead, which also fails, but differently (I'm guessing because it isn't compiled as they mentioned).

    dokku config:set reviews BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-emberjs.git

Deploying with that buildpack gets you - 
```
-----> Fetching custom buildpack
remote: /tmp/buildpacks/custom/bin/detect: line 5: /tmp/buildpacks/custom/vendor/buildpack: No such file or directory
-----> Unable to select a buildpack
```

I'm wondering if Dokku doesn't support `tgz` buildpacks? I suppose this might actually be a herokuish issue if that is the case. I'm new to the Heroku ecosystem, so I'm not really sure if `tgz` buildpacks are common or not.

#### Output of the following commands

- `uname -a`: `Linux frizard 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- `free -m`: 
```
total       used       free     shared    buffers     cached
Mem:           993        380        613          0        100        144
-/+ buffers/cache:        135        858
Swap:            0          0          0
```

- `docker version`:
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 10
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 994 MiB
Name: frizard
ID: DJ7A:ECEQ:JFAP:EPH6:OTFC:4KIY:D3MK:OSMY:NMVB:B2J6:Q5UX:NUK6
WARNING: No swap limit support
```
- `sigil -v`: `0.4.0`
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: dev
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v89
  heroku-buildpack-php       v100
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v67
  buildpack-nginx            v5
```
- `dokku version`: `0.5.4`
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.5.4 enabled    dokku core standard plugin
  20_events            0.5.4 enabled    dokku core events logging plugin
  apps                 0.5.4 enabled    dokku core apps plugin
  build-env            0.5.4 enabled    dokku core build-env plugin
  certs                0.5.4 enabled    dokku core certificate management plugin
  checks               0.5.4 enabled    dokku core checks plugin
  common               0.5.4 enabled    dokku core common plugin
  config               0.5.4 enabled    dokku core config plugin
  docker-options       0.5.4 enabled    dokku core docker-options plugin
  domains              0.5.4 enabled    dokku core domains plugin
  enter                0.5.4 enabled    dokku core enter plugin
  git                  0.5.4 enabled    dokku core git plugin
  logs                 0.5.4 enabled    dokku core logs plugin
  named-containers     0.5.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.4 enabled    dokku core plugin plugin
  proxy                0.5.4 enabled    dokku core proxy plugin
  ps                   0.5.4 enabled    dokku core ps plugin
  shell                0.5.4 enabled    dokku core shell plugin
  storage              0.5.4 enabled    dokku core storage plugin
  tags                 0.5.4 enabled    dokku core tags plugin
  tar                  0.5.4 enabled    dokku core tar plugin
```
- Link to the exact repository being deployed (if possible/applicable): https://github.com/heroku/ember-js-getting-started/tree/fastboot
- If a deploy is failing or behaving unexpectedly:
  - Application name: ember-js-getting-started
  - The type of application being deployed (node, php, python, ruby, etc.): Complicated? It's an emberjs fastboot application, which is eventually a node application, but the buildpack does extra build steps to generate that node app
  - If using buildpacks, which custom buildpacks are in use: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz
  - If using a `Dockerfile`, the contents of that file: n/a
  - If it exists, the contents of your `Procfile`: n/a
- Output of failing dokku commands after running `dokku trace on`: https://gist.github.com/alexking/1233878e44574cfb724bbd905ffa2427

Environment details (AWS, VirtualBox, physical, etc.):
DigitalOcean

How was dokku installed?:
DigitalOcean Droplet 

How reproducible:
Constant

#### Steps to Reproduce:

Checkout repo 
```
git clone https://github.com/heroku/ember-js-getting-started.git
cd ember-js-getting-started
git checkout fastboot
```

Set buildpack for app in dokku 
```
dokku apps:create test
dokku config:set test BUILDPACK_URL=https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz
```

Deploy to dokku and watch it fail 

**Actual Results:**
```
-----> Cleaning up...
-----> Building test from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Fetching custom buildpack
To dokku@[machine]:test
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Expected Results:**
Running on Heroku, you get - 
```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching set buildpack https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz... done
remote: -----> emberjs app detected
remote: -----> Setting NPM_CONFIG_PRODUCTION to false to install ember-cli toolchain
remote: -----> Fetching buildpack heroku/nodejs
remote: -----> Node.js detected
etc...
```

**Comment by michaelshobbs** [comment]
This is not currently support and will need to be filed at https://github.com/gliderlabs/herokuish

**Comment by afuno** [comment]
@josegonzalez I got a similar error: https://github.com/heroku/heroku-buildpack-emberjs/issues/51

**Comment by josegonzalez** [comment]
@afuno that seems like a bug in the buildpack itself - specifically, it is missing a file it is referencing. I've locked this issue as you commented a 2+ year issue, and we explicitly do not provide buildpack support on our issue tracker.
