### ISSUE TITLE
[RFC] bash_completion module

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#2095]
I'd love to be able to tab complete dokku commands. Thoughts? Pointers on how to implement? I'll do some research and post what I find here.

**Comment by josegonzalez** [comment]
Maybe with smarter help output parsing? `complete` is pretty simple to use, and I followed [these](https://www.debian-administration.org/article/316/An_introduction_to_bash_completion_part_1) two [docs](http://tldp.org/LDP/abs/html/tabexpansion.html)  to setup my own stuff.

**Comment by josegonzalez** [comment]
Note that if this is implemented, we'll probably get people asking if they can use the autocompletion locally and remote, so we'd need to think of a way to do that in a performant manner.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
