### ISSUE TITLE
How to add additional variables to the build phase?

### ISSUE THREAD

**Issue by bahmutov** [dokku/dokku#2096]
Hi,

I am trying to add NPM_TOKEN to the build step to allow `npm install` to install private packages. Seems the dokku 0.4.5 only exports always the same variables but not the ones I added

```
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
```

I tried adding `export NPM_TOKEN=...` to /home/dokku/BUILD_ENV and docker config file /home/dokku/DOCKER_OPTIONS_BUILD but without success. 

Is there a place where build environment variables should go? Or maybe even a place for a custom build step? Maybe I can write `.npmrc` file during the build step myself

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by bahmutov** [comment]
ok, the question was more about how to pass variables to the build step, but seems NPM install is actually working just not displaying the variable used. Thanks for the great tool dokku, guys, it is a life saver!

**Comment by josegonzalez** [comment]
Note: the NodeJS buildpack only prints out env vars starting with [`NPM_CONFIG` and `NODE`](https://github.com/heroku/heroku-buildpack-nodejs/blob/c5db0676a61341547bf70032ce7016b04d7c7956/lib/environment.sh#L8).
