### ISSUE TITLE
cannot change environment variables once set

### ISSUE THREAD

**Issue by raffaeleguidi** [dokku/dokku#2117]
Description of problem:

once set environment variables cannot be changed or unset. They appear correct in config <APP> but if you run <APP> env you can see it has not changed - only making a new deploy fixes the situation.

I tried with 0.5.3 and after an ugrade to 0.5.5 with both a meteor and an express application

Output of the following commands

- `uname -a`:Linux sp-extra 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:             
 total       used       free     shared    buffers     cached
Mem:           993        753        240          0         40        355
-/+ buffers/cache:        357        636
Swap:         4095         76       4019

- `docker version`:
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

- `docker -D info`:
Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 40
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 994 MiB
Name: sp-extra
ID: GKJX:QB33:ZZSY:QFYE:IOZH:I7JM:4GFD:LVW6:XYTZ:BZZI:CEL2:6HWZ
WARNING: No swap limit support

- `sigil -v`:0.4.0

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.11
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v89
  heroku-buildpack-php       v100
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v67
  buildpack-nginx            v5

- `dokku version`:0.5.5
- `dokku plugin`:
plugn: dev
  00_dokku-standard    0.5.5 enabled    dokku core standard plugin
  20_events            0.5.5 enabled    dokku core events logging plugin
  apps                 0.5.5 enabled    dokku core apps plugin
  build-env            0.5.5 enabled    dokku core build-env plugin
  certs                0.5.5 enabled    dokku core certificate management plugin
  checks               0.5.5 enabled    dokku core checks plugin
  common               0.5.5 enabled    dokku core common plugin
  config               0.5.5 enabled    dokku core config plugin
  docker-options       0.5.5 enabled    dokku core docker-options plugin
  domains              0.5.5 enabled    dokku core domains plugin
  enter                0.5.5 enabled    dokku core enter plugin
  git                  0.5.5 enabled    dokku core git plugin
  logs                 0.5.5 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.5.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.5 enabled    dokku core plugin plugin
  proxy                0.5.5 enabled    dokku core proxy plugin
  ps                   0.5.5 enabled    dokku core ps plugin
  shell                0.5.5 enabled    dokku core shell plugin
  storage              0.5.5 enabled    dokku core storage plugin
  tags                 0.5.5 enabled    dokku core tags plugin
  tar                  0.5.5 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):

digitalocean 1gb droplet

How was dokku installed?: DO image and then manually upgraded

How reproducible: 

Steps to Reproduce:
1. deploy an app
2. set a variable
3. set it to a different value
4. run config
5. run env in the container

Actual Results:
you will see the variable changed in config but not in the container env

Expected Results:
the variable should be changed in docker container

Additional info:
a new deploy is needed to correct the value of the variable - the redeploy command doesn't fix it. Same result with unset

**Comment by michaelshobbs** [comment]
By default, a new container is started up when a config variable is changed and nginx is updated to to route traffic to that. See my example below.
```
root@dokku:~/dokku# dokku config node-js-app | grep TEST_VAR
TEST_VAR:          foo
root@dokku:~/dokku# dokku enter node-js-app web
u18424@mobius-expa-vagrant-dokku:~$ env | grep TEST_VAR
TEST_VAR=foo
u18424@mobius-expa-vagrant-dokku:~$ exit
root@dokku:~/dokku# dokku config:set node-js-app TEST_VAR=bar
-----> Setting config vars
       TEST_VAR: bar
-----> Restarting app node-js-app
-----> Releasing node-js-app (dokku/node-js-app:latest)...
-----> Deploying node-js-app (dokku/node-js-app:latest)...
...snip...
=====> Application deployed:
       http://node-js-app.dokku.me

root@dokku:~/dokku# dokku config node-js-app | grep TEST_VAR
TEST_VAR:          bar
root@dokku:~/dokku# dokku enter node-js-app web
u18424@mobius-expa-vagrant-dokku:~$ env | grep TEST_VAR
TEST_VAR=bar
u18424@mobius-expa-vagrant-dokku:~$ exit
```

Can you show a similar flow with results that the variable did not change or is this a mismatch in expectation of how dokku works?

**Comment by raffaeleguidi** [comment]
I tried again and with the regular express application it worked flawlessly - the problem was with the meteor application which really stresses the cpu during the deployment. I had to retry several times for the same deploy, probably 1gb DO machines are not well suited for meteor deployment (although once deployed it works just fine).

**Comment by michaelshobbs** [comment]
Sounds like a resource problem then?

**Comment by michaelshobbs** [comment]
Sounds like a resource problem then?

**Comment by raffaeleguidi** [comment]
I guess. The CPU stayed at 100% for some minutes during deployments and probably the container didn't  get correctly deployed.

Thanks,
    Raffaele
