### ISSUE TITLE
How to update client postgres version?

### ISSUE THREAD

**Issue by madshargreave** [dokku/dokku#2118]
Hi

I am currently having trouble with a version mismatch when running pg_dump on my dokku hosted app

It complains the server (seperate postgres container) is version 9.5.0, while the client (my app container) is 9.4.5.

I installed it using dokku-postgres

How can I update my app container's postgres to match the server?

**Comment by michaelshobbs** [comment]
Try the `dokku-apt` plugin or build your own custom image based on herokuish.

**Comment by madshargreave** [comment]
I've tried the dokku-apt plugin, but I haven't figured out how to install a specific version

**Comment by michaelshobbs** [comment]
I think whatever you put in the file gets passed directly to `apt-get`. Perhaps ask the plugin maintainer?

**Comment by josegonzalez** [comment]
@madshargreave The plugin has directions for using an alternative version of postgres for the server. If you want to use `pg_dump`, I suggest you use the `postgres:export` command from that plugin anyhow.

**Comment by madshargreave** [comment]
@josegonzalez I am running `pg_dump` from within my application layer inside the app container. Is it possible to run commands from the on dokku server from inside such container?

**Comment by josegonzalez** [comment]
No, it is not.

**Comment by madshargreave** [comment]
I see. Instead of downgrading my server, how would I upgrade my client container?

**Comment by josegonzalez** [comment]
Can you log onto slack/irc and get support for your issue there? We'll update this issue once we've figured out a solution.

**Comment by nekapoor** [comment]
any updates on how to upgrade to a more recent version of postgres from within my client dokku container?

**Comment by joshmanders** [comment]
@nekapoor this is an old issue, can you please open a new one with the information requested in it filled out. Thanks.
