### ISSUE TITLE
[RFC]: configurable docker stop timeout

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#2126]
Currently we execute `docker stop` on the old container. Might be useful to make that timeout configurable.

```
$ docker stop --help

Usage:	docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop a running container.
Sending SIGTERM and then SIGKILL after a grace period

  --help             Print usage
  -t, --time=10      Seconds to wait for stop before killing it
```

**Comment by josegonzalez** [comment]
Does that return immediately? If so, then it doesn't matter since I *think* we call `docker kill`. Otherwise, making it configurable is fine.

Should we make it configurable per-app, or just globally?

**Comment by u2mejc** [comment]
@michaelshobbs and I talked outside of GH about this:
>jclark [4:40] 
>The only option (in 2126) is `—time`, is that simply to control the grace period between SIGTERM and SIGKILL?
>
>michael [4:41 PM] 
>yes
>
>[4:41] 
>I propose we let that be configurable
>
>[4:42] 
>default it to not include `--time` unless the use defines it (edited)
>
>jclark [4:44 PM] 
>sure why not, I mean it’s not to “drain” the app, since nginx reload has already stopped listening to that upstream right? It’s really just house keeping like uploading logs?
>
>michael [4:46 PM] 
>worker containers for example might need more than the default of 10 seconds to shutdown gracefully
>
>[4:46] 
>in some procs they catch `SIGTERM` and attempt to shutdown nicely but if they have an active job that takes longer, it’ll just get killed
>
>jclark [4:47 PM] 
>yep, totally makes sense for backend / worker procs.
>
>michael [4:47 PM] 
>even with some web apps
>
>[4:47] 
>but it won’t matter as much i think

**Comment by michaelshobbs** [comment]
> Does that return immediately? If so, then it doesn't matter since I think we call docker kill. Otherwise, making it configurable is fine.

No it returns after the timeout. Also `docker stop` already sends `SIGKILL` after the timeout if the container hasn't stopped. So we can probably nix that bit in dokku

> Should we make it configurable per-app, or just globally?

Per-app or globally is fine

**Comment by josegonzalez** [comment]
Would love to get away from global options, but in either case, the implementation is up to you.

👍

**Comment by michaelshobbs** [comment]
We can just make it per app then. I'm fine with that.
