### ISSUE TITLE
nginx.conf.template generating duplicate configuration contexts?

### ISSUE THREAD

**Issue by Corstiaan84** [dokku/dokku#2133]
Description of problem:
Dokku generates this (https://gist.github.com/Corstiaan84/f7c79fdd39582a7ec3f765e7b4b76bdb) nginx conf on deploy

I have put a custom conf template in the root of my app (https://gist.github.com/Corstiaan84/62968a70538e8530f60d4c1bce2f63bc) to allow for an additional proxy my app needs. I tried naming this file ````nginx.conf.ssl_terminated.template```` as well as ````nginx.conf.template````

Please note I have enabled ssl.

It looks like the generated conf has duplicate configuration contexts if I am not mistaken. The app deploys successfully with no nginx config errors. My app functions properly post deploy but the internal proxy is not being called by my Rails app. It throws a "Route not found" exception. What am I missing?

Output of the following commands

- `uname -a`:
Linux superbad 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- `free -m`:
             total       used       free     shared    buffers     cached
Mem:          3953       3790        163         26         36        181
-/+ buffers/cache:       3572        380
Swap:         4092       3399        693

- `docker version`:
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

- `docker -D info`:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

- `dokku version`:
0.4.14

- `dokku plugin`:
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  app-predeploy-tasks  0.1.0 enabled    Run arbitrary app tasks prior to dokku's deploy phase
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  mysql                1.0.0 enabled    dokku mysql service plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):
TransIp vps

How was dokku installed?:
apt-get

How reproducible:
See description

**Comment by Corstiaan84** [comment]
Never mind... I guess the "duplicate" server contexts are for "everseller.com" and "www.everseller.com" respectively?

**Comment by Corstiaan84** [comment]
I got a bit further by just moving my custom conf into /nginx.conf.d and and to let the default conf template handle it. No got a 502 bad gateway error but at least the request is being picked up by nginx.

**Comment by josegonzalez** [comment]
Did you get this solved? Seems like it was an error in your template.

**Comment by Corstiaan84** [comment]
Still stuck on the 502 nginx error. Dont know if that's dokku related though?

**Comment by josegonzalez** [comment]
Can you gist your current generated `nginx.conf`?

**Comment by Corstiaan84** [comment]
Here you go: https://gist.github.com/Corstiaan84/74f8c491a90dedb54b0a2bd11f6c0157

The app runs fine overall. It's just the route/url that call to an action that offloads its response to the "internal_redirect" location of the conf that throws a 502.

In folder nginx.conf.d I have this: https://gist.github.com/Corstiaan84/163901bfba53f5e2a985c5230e40b255. Saved as "download_proxy.conf"

**Comment by Corstiaan84** [comment]
Hi @josegonzalez I have some developments regarding this matter.

I am now using this custom conf, saved as nginx.conf.template in the root folder of my app: https://gist.github.com/Corstiaan84/fd3cc19ee656d17b9f8938d7c0d365ce

This generates this following conf: https://gist.github.com/Corstiaan84/85ddad401609bacae5349cffa6bd33a5

Should't Dokku generate a conf starting at line 84 the now generated conf?

Thanks!

**Comment by Corstiaan84** [comment]
Hi @josegonzalez any thoughts on this perhaps?

(I know, I am a bit spoiled with your very fast replies usually ;-))

**Comment by josegonzalez** [comment]
Not sure what was going on here - and sorry for letting this fall off! - but the whole nginx configuration was rebuilt in the 0.5.x release. 

It's possible there is some weird interaction in bash variable interpolation for the 0.4.x series - hence the rewrite - so unless you have some further follow-up here, or a duplication in 0.5.x, I'm going to mark this as closed.
