### ISSUE TITLE
Third-party plugins: When can we break backwards compatibility with dokku 0.4?

### ISSUE THREAD

**Issue by sseemayer** [dokku/dokku#2134]
I am thinking about changing dokku-letsencrypt to the subcommand structure introduced in dokku 0.5 and also switching templating over to sigil. Unfortunately, both those changes would break backwards compatibility with dokku 0.4 which leads me to two questions:

- Do you think it's a good idea to break backward compatibility _right now_, or should I wait another $time_difference?
- Is there an official timeline for when we assume that everyone has updated to 0.4 and that all plugins should be supporting 0.5 instead?
- Can I tell dokku which versions my plugin is compatible with, e.g. by a line in the plugin.toml (I didn't find anything like this)? Is there another way I can ensure that users of dokku 0.4 will not accidentally upgrade their plugins to a version that that doesn't support their dokku?

**Comment by michaelshobbs** [comment]
You could use a release branch or tag and have folks install from that. @josegonzalez probably has more thoughts here

**Comment by josegonzalez** [comment]
Use a release branch - 0.4.0 perhaps - to signify minimum compatibility with a version. We can make it so that if the major dokku release is 0.5.0, then an official plugin with 0.4.x isn't required to support it.

**Comment by jvanbaarsen** [comment]
@josegonzalez Would it make sense to create a system in Dokku that you can add a minimum required version to your plugin? (That the plugin installer will check for)

**Comment by josegonzalez** [comment]
Maybe? That could be a plugn thing though.

**Comment by jvanbaarsen** [comment]
Ah ok :-) I though Dokku handled the plugin installation.

**Comment by josegonzalez** [comment]
We outsource most of the plugin handling to plugn, and I think it makes sense to have this sort of logic there.

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by josegonzalez** [comment]
Feel free to file an issue in `plugn` for that feature and/or implement it.

**Comment by michaelshobbs** [comment]
I believe `plugin:update` supports a branch name. The dokku bats test hits that code IIRC.

**Comment by sseemayer** [comment]
Thanks for all the helpful comments! I will attempt the release branch method and will report back with my experiences :+1:

**Comment by sseemayer** [comment]
I haven't yet started making any compatibility-breaking changes but this is what I've come up with: https://github.com/dokku/dokku-letsencrypt/tree/master#installation

**Comment by sseemayer** [comment]
And I'm proud to say that dokku-letsencrypt is now a full dokku 0.5 plugin - again, thanks for the help!

**Comment by michaelshobbs** [comment]
Excellent! I know there's quite a few dokku-letsencrypt users out there ready for an upgrade 😄
