### ISSUE TITLE
Host restart issue

### ISSUE THREAD

**Issue by ypadlyak** [dokku/dokku#2139]
**Description of problem:**
Oh host restart, the projects following failing to start project, doesn't come up

**uname -a:**
Linux ip-10-0-0-75 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
**    free -m:**
             total       used       free     shared    buffers     cached
Mem:          3952       3511        440          6        382        701
-/+ buffers/cache:       2427       1524
Swap:            0          0          0

**docker version:**
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
**    docker -D info:**
Containers: 66
 Running: 11
 Paused: 0
 Stopped: 55
Images: 270
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 399
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-10-0-0-75
ID: TP62:4U7B:4762:K2KQ:XYLJ:KQAS:5EJN:DL4H:ZXF3:YDUG:R5BE:SMPI
WARNING: No swap limit support

**sigil -v:**
0.4.0
**docker run -ti gliderlabs/herokuish:latest herokuish version:**
herokuish: 0.3.11
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v89
  heroku-buildpack-php       v100
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v67
  buildpack-nginx            v5

**dokku version:**
0.5.5
**dokku plugin:**
No such command: version

Available commands:
  config                       Plugin configuration
  disable                      Disable a plugin
  enable                       Enable a plugin
  help                         Shows help information for a command
  init                         Initialize an empty plugin path
  install                      Install a new plugin from a Git URL
  list                         List all local plugins
  source                       Source commands for sourcable plugins
  trigger                      Triggers hook in enabled plugins
  uninstall                    Remove plugin from available plugins

**Why it doesn't print list of the plugins?**

**Environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2 instance

**How was dokku installed?:**
deb package

**How reproducible:**
every time

**Steps to Reproduce: 1. 2. 3.**
1. screwup one application config, so it doesn't deploy
2. restart host
 
**Actual Results:**
the apps, which come right after the broken one in `dokku ls` will not start

**Expected Results:**
The broken app is skipped. The apps, which come right after the broken one in `dokku ls` will start

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by ypadlyak** [comment]
@josegonzalez done

**Comment by josegonzalez** [comment]
@ypadlyak The plugin thing is weird. Can you verify the version of `plugn` installed from the apt package? For reference, here is the output of mine:

```
root@dokku:~# dokku plugin
plugn: dev
  00_dokku-standard    0.5.5 enabled    dokku core standard plugin
  20_events            0.5.5 enabled    dokku core events logging plugin
  apps                 0.5.5 enabled    dokku core apps plugin
  auth                 0.4.0 enabled    dokku auth plugin
  build-env            0.5.5 enabled    dokku core build-env plugin
  certs                0.5.5 enabled    dokku core certificate management plugin
  checks               0.5.5 enabled    dokku core checks plugin
  common               0.5.5 enabled    dokku core common plugin
  config               0.5.5 enabled    dokku core config plugin
  copyfiles-to-image   1.0.0 enabled    dokku plugin to copy files from the host to the built docker image
  docker-options       0.5.5 enabled    dokku core docker-options plugin
  domains              0.5.5 enabled    dokku core domains plugin
  enter                0.5.5 enabled    dokku core enter plugin
  git                  0.5.5 enabled    dokku core git plugin
  letsencrypt          0.7.1 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.5.5 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  mysql                1.0.0 enabled    dokku mysql service plugin
  named-containers     0.5.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.5 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.5.5 enabled    dokku core proxy plugin
  ps                   0.5.5 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  rethinkdb            1.0.0 enabled    dokku rethinkdb service plugin
  shell                0.5.5 enabled    dokku core shell plugin
  storage              0.5.5 enabled    dokku core storage plugin
  tags                 0.5.5 enabled    dokku core tags plugin
  tar                  0.5.5 enabled    dokku core tar plugin
```

**Comment by ypadlyak** [comment]
it was v. 0.2.0. Upgrade to 0.2.1 helped. Thanks! 
The output is:
plugn: dev
  00_dokku-standard    0.5.5 enabled    dokku core standard plugin
  20_events            0.5.5 enabled    dokku core events logging plugin
debug2: channel 0: window 999417 sent adjust 49159
  apps                 0.5.5 enabled    dokku core apps plugin
  build-env            0.5.5 enabled    dokku core build-env plugin
  certs                0.5.5 enabled    dokku core certificate management plugin
  checks               0.5.5 enabled    dokku core checks plugin
  common               0.5.5 enabled    dokku core common plugin
  config               0.5.5 enabled    dokku core config plugin
  deployment-keys      0.1.0 enabled    Manage SSH deployment keys that should get injected into your containers on-build
  docker-options       0.5.5 enabled    dokku core docker-options plugin
  domains              0.5.5 enabled    dokku core domains plugin
  enter                0.5.5 enabled    dokku core enter plugin
  git                  0.5.5 enabled    dokku core git plugin
  hostkeys-keys        0.1.0 enabled    Manage hostkeys for your container environment
  hostname             0.2.0 enabled    Sets the docker hostname option for dokku
  letsencrypt          0.7.0 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.5.5 enabled    dokku core logs plugin
  logspout             0.2.0 enabled    sends dokku app stdout to a logging service
  maintenance          0.4.0 enabled    Maintenance mode for apps
  named-containers     0.5.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.5 enabled    dokku core plugin plugin
  proxy                0.5.5 enabled    dokku core proxy plugin
  ps                   0.5.5 enabled    dokku core ps plugin
  shell                0.5.5 enabled    dokku core shell plugin
  storage              0.5.5 enabled    dokku core storage plugin
  tags                 0.5.5 enabled    dokku core tags plugin
  tar                  0.5.5 enabled    dokku core tar plugin

**Comment by ypadlyak** [comment]
I think it is fixed in https://github.com/dokku/dokku/pull/2171 , and we may close this.
