### ISSUE TITLE
DOKKU_CONFIG_RESTART=false doesn't work

### ISSUE THREAD

**Issue by adastreamer** [dokku/dokku#2141]
Using version `0.4.*` when the `DOKKU_CONFIG_RESTART` is set to `false`, we can run command `config:set` without restarting of the target app. Using version `0.5.*` it doesn't work anymore.

**Comment by michaelshobbs** [comment]
Turns out it worked previously due to a side-effect of a variable scoping bug in the `config` plugin. Alternatively you can use `dokku config:set --no-restart $APP FOO=bar` to prevent restarting when setting config variables.
