### ISSUE TITLE
Dokku installs node and npm after every push

### ISSUE THREAD

**Issue by TheNotary** [dokku/dokku#2143]
Description of problem:

I'm on a bandwidth budget and also debugging some weird (I think) CORS related problems with web sockets and https so I'm push lots of commits.  It would be nice if I could push my node app while the server is a completely offline state if the node and npm versions have been installed in the past.  

I'm on Debian btw, I'm not sure if there's a glitch somewhere there or if this is the current behavior and no ones looked into bandwidth/ offline capabilities for pushing node apps yet.  

Linux xref 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

Here's the app I'm testing with:  https://github.com/TheNotary/fayecom/tree/3dd8334e82981b7efc64ec8c82671a701eab4fbf

**Comment by michaelshobbs** [comment]
This is handled by the [nodejs buildpack](https://github.com/heroku/heroku-buildpack-nodejs/blob/v90/lib/binaries.sh#L10-L26). I don't think dokku can do anything here. You might an issue there.

Alternatively, you could try a [dockerfile deployment](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/) with dokku.

**Comment by TheNotary** [comment]
Thanks for the quick and extremely helpful reply @michaelshobbs!  I finally learned app dockerization :metal:
