### ISSUE TITLE
Can't access app config variables in nginx.conf.sigil template

### ISSUE THREAD

**Issue by jlachowski** [dokku/dokku#2149]
Dokku 0.5.5

Description of problem:
Can't access app config variables (ENV) in nginx.conf.sigil template.
The function "var" returns only variables which are available in the shell that nginx.conf generation is run.

**Comment by josegonzalez** [comment]
Pretty sure this is [by design](http://dokku.viewdocs.io/dokku/nginx/#available-template-variables). What use case do you have?

@michaelshobbs can you confirm/deny?

**Comment by jlachowski** [comment]
I would like to change the `listen` line to use an external IP eg.:

`listen    {{ if var "EXT_IP" }}{{ var "EXT_IP" }}:{{ .NGINX_PORT }}{{ else }}{{ .NGINX_PORT }}{{ end }};`

which (if EXT_IP is defined) should produce something like:

`listen  xxx.xxx.xxx.xxx:80;`

where xxx.xxx.xxx.xxx is the IP.
This was possible with the pre-sigil templates.

Currenlty it only works if I export the variable in shell and regenerate the config but not on deployment e.g.:

`$> export EXT_IP=1.1.1.1`
`$> dokku nginx:build-config app`

**Comment by michaelshobbs** [comment]
That is by design. If, in fact, having everything exported in the shell env works, that could be an easy way to support this again. @josegonzalez thoughts? any reason not to support this?

**Comment by josegonzalez** [comment]
You could maybe accidentally clobber the existing env we say we provide, causing issues with the build. That could be a concern.

**Comment by michaelshobbs** [comment]
What is the order of preference in `sigil`? (i.e. env vs passed vars)

**Comment by josegonzalez** [comment]
We should always override with those we say we provide, and everything else is lower preference.

Note that this could *also* be a security breach if your nginx conf does something stupid like display all env vars.

**Comment by michaelshobbs** [comment]
100% agree. However that was not my question. My question is **what is** `sigil`'s preference wrt env vs passed vars?

**Comment by josegonzalez** [comment]
I don't think you can use env vars in sigil, at least not according to the docs.

**Comment by michaelshobbs** [comment]
I think what @jlachowski is saying though is that it does seem to work. @jlachowski can you confirm?

**Comment by michaelshobbs** [comment]
@josegonzalez I can confirm that adding `eval "$(config_export app "$APP")"` right before the call to `sigil` and adding `# {{ var "TEST_VAR" }}` to the end of `nginx.conf.sigil` will yield an nginx config with that variable interpolated.

Now, the remaining questions are, is this by design in `sigil` and is the something we want to support in dokku? I know we were attempting to move away from exporting APP vars in the dokku shell environment at one point. I'll leave this product decision to @josegonzalez :smile:

**Comment by jlachowski** [comment]
Thanks a lot guys, sorry could'n replay earlier.
