### ISSUE TITLE
Dokku plugin doesn't work (user-auth)

### ISSUE THREAD

**Issue by alexgleason** [dokku/dokku#2152]
Hi all. I'm sure this is user error but I would appreciate some help. Here's the contents of `user-auth` for a plugin I'm trying to create.

```shell
#!/usr/bin/env bash
# Deny config access to any user who isn't root

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
[[ "$SSH_USER" != "root" && $3 == config:* ]] && exit 1
exit 0
```

It doesn't do anything at all. In fact:

```shell
#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
exit 1
```

doesn't do a thing, either... I would expect it to prevent me from running commands, but that isn't the case.

I can still run commands like `dokku apps` and `dokku config` and it displays output. According to [the docs](http://dokku.viewdocs.io/dokku/development/plugin-triggers/#user-auth), this hook "is a special plugin trigger that is executed on every command run." So, I would expect it to display no output when using `exit 1`.

Have I installed it incorrectly or is my plugin structure incorrect?

Here is my plugin. https://github.com/directactioneverywhere/dokku-rootconfig

Thank you.

**Comment by michaelshobbs** [comment]
Is the exec bit set on the `user-auth` file? (I'm on mobile right so I can't tell)

**Comment by alexgleason** [comment]
Thank you so much!! Argh, I remember actually reading this now when skimming through the docs. :laughing: Late night.

Really appreciate the help, and btw want to say that Dokku is awesome. Once you go Dokku you never go back.
