### ISSUE TITLE
! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by lolorama** [dokku/dokku#2154]
Description of problem:
After several push's something have been broken. 
I have rebased git and change /home/dokku/gmbay/refs/head/master to old commit. All was ok. After that I have several pushes and then I've got error:

` ! [remote rejected] master -> master (pre-receive hook declined)` 

Actually I haven't any idea on what I've change to get such error, because new commit has 1 changed line in requirements.txt.

Output of the following commands

- `uname -a`: 
Linux vm105925.local 3.16.0-45-generic #60~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
Please wait, scanning... c0000
Found something at c0000 (4096 bytes) (checksum 6)
Please wait, scanning... c1000
Found something at c1000 (2560 bytes) (checksum 0)
Please wait, scanning... c2000
Found something at c2000 (2560 bytes) (checksum 0)
Please wait, scanning... c3000
Found something at c3000 (9216 bytes) (checksum 0)
Please wait, scanning... ed800
Found something at ed800 (10240 bytes) (checksum 214)
Please wait, scanning... f0000
- `docker version`:
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
- `docker -D info`:
Containers: 14
 Running: 3
 Paused: 0
 Stopped: 11
Images: 21
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-45-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 1.977 GiB
Name: vm105925.local
ID: W44Z:QPS5:KHRF:3E3E:3264:KFMM:IB3B:G36P:5GM4:ILZC:ZVPT:QWC7
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
- `sigil -v`:
0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.11
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v89
  heroku-buildpack-php       v100
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v67
  buildpack-nginx            v5
- `dokku version`:
0.5.5
- `dokku plugin`:
00_dokku-standard    0.5.5 enabled    dokku core standard plugin
  20_events            0.5.5 enabled    dokku core events logging plugin
  apps                 0.5.5 enabled    dokku core apps plugin
  build-env            0.5.5 enabled    dokku core build-env plugin
  certs                0.5.5 enabled    dokku core certificate management plugin
  checks               0.5.5 enabled    dokku core checks plugin
  common               0.5.5 enabled    dokku core common plugin
  config               0.5.5 enabled    dokku core config plugin
  docker-options       0.5.5 enabled    dokku core docker-options plugin
  domains              0.5.5 enabled    dokku core domains plugin
  enter                0.5.5 enabled    dokku core enter plugin
  git                  0.5.5 enabled    dokku core git plugin
  logs                 0.5.5 enabled    dokku core logs plugin
  named-containers     0.5.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.5 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.5.5 enabled    dokku core proxy plugin
  ps                   0.5.5 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  require              0.1.0 enabled    dokku plugin to setup all the requirement for your app on push
  shell                0.5.5 enabled    dokku core shell plugin
  storage              0.5.5 enabled    dokku core storage plugin
  tags                 0.5.5 enabled    dokku core tags plugin
  tar                  0.5.5 enabled    dokku core tar plugin

- Output of failing dokku commands after running `dokku trace on`
https://gist.github.com/lolorama/43999e1fa9c19baeef5b212f1959e7af

How was dokku installed?:
wget https://raw.githubusercontent.com/dokku/dokku/v0.5.6/bootstrap.sh
sudo DOKKU_TAG=v0.5.6 bash bootstrap.sh

**Comment by josegonzalez** [comment]
Did you add a submodule to your repository? It seems like that may be the case. If so, then you need to use the following plugins to setup ssh keys:

- https://github.com/cedricziel/dokku-deployment-keys
- https://github.com/cedricziel/dokku-hostkeys-plugin

**Comment by lolorama** [comment]
Thanks you so much!!! It was submodule..

I've added to requirements.txt
`-e git://github.com/arthanson/django-genericadmin.git#egg=django-genericadmin`
tested installation locally and missed that 'src' folder was created.
