### ISSUE TITLE
glusterfs mount disappearing

### ISSUE THREAD

**Issue by markwoodhall** [dokku/dokku#2156]
Hi, thanks for the work on dokku. I'm really enjoying using it. 

I have a question related to a predeploy script I am running. The script is mounting a glusterfs volume using the glusterfs-client. Everything works as expected, the last step of this script is to run `mount`, here I can see that the volume was mounted successfully. However, when I then run `docker exec my_container mount` the volume is no longer mounted. If I then manually execute the predeploy script using `docker exec` the volume is mounted again and this time is persistent. 

Is there anything I'm not considering regarding the predeploy script that would make the mounted volume go away unexpectedly?

**Comment by josegonzalez** [comment]
The pre-deploy script runs within the container, not on the host. Are you sure that's what you want here?

**Comment by markwoodhall** [comment]
Yes, I wanted to mount using the glusterfs-client on the container. Unless it is better to mount that volume on the host and use it in the container some how?

**Comment by josegonzalez** [comment]
The pre-deploy scripts are run in separate containers, not the specific container you are running against. If it was, then you'd be scoped to that single container anyhow, not any other scaled processes.

What you want to do is mount that gluster volume on the host, and then use the storage plugin to mount it as a volume on your app.

**Comment by markwoodhall** [comment]
Ok, thanks. I will try that.

**Comment by markwoodhall** [comment]
That was a much better way of doing it and it worked perfectly. Thanks for the guidance. 👍
