### ISSUE TITLE
git deploy with an empty Procfile fails to create DOKKU_SCALE file

### ISSUE THREAD

**Issue by simmerer** [dokku/dokku#2158]
Running `git push dokku master` hits several errors, the first of which involves the emberjs buildpack.

    $ git push dokku master
    Counting objects: 3678, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (3539/3539), done.
    Writing objects: 100% (3678/3678), 850.05 KiB | 0 bytes/s, done.
    Total 3678 (delta 2410), reused 0 (delta 0)
    -----> Cleaning up...
    -----> Building qc2 from herokuish...
    -----> Setting config vars
           CURL_CONNECT_TIMEOUT: 5
    -----> Setting config vars
           CURL_TIMEOUT: 30
    -----> Adding BUILD_ENV to build environment...
    remote: setuidgid: fatal: unable to run /tmp/buildpacks/emberjs/bin/detect: access denied

Traceback continues, hitting some git-related errors:

    -----> Ruby app detected
    -----> Compiling Ruby/Rails
    -----> Using Ruby version: ruby-2.3.0
    -----> Installing dependencies using bundler 1.11.2
           Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
           Fetching gem metadata from https://rails-assets.tenex.tech/..
           Fetching gem metadata from https://rubygems.org/..........
           Fetching version metadata from https://rails-assets.tenex.tech/..
           Fetching version metadata from https://rubygems.org/...
           Fetching dependency metadata from https://rails-assets.tenex.tech/..
           Fetching dependency metadata from https://rubygems.org/..
           Fetching git://github.com/hayesr/administrate.git
           fatal: Could not parse object '3d876a9cd2b0e64d2d36c94ad8836e1ade04265b'.
           Git error: command `git reset --hard 3d876a9cd2b0e64d2d36c94ad8836e1ade04265b`
           in directory
           /tmp/build/vendor/bundle/ruby/2.3.0/bundler/gems/administrate-3d876a9cd2b0 has
           failed.
           If this error persists you could try removing the cache directory
           '/tmp/build/vendor/bundle/ruby/2.3.0/cache/bundler/git/administrate-bba647b035c9dd5d997cae9baf24fd6234cb1ff5'
           Bundler Output: Fetching gem metadata from https://rails-assets.tenex.tech/..
           Fetching gem metadata from https://rubygems.org/..........
           Fetching version metadata from https://rails-assets.tenex.tech/..
           Fetching version metadata from https://rubygems.org/...
           Fetching dependency metadata from https://rails-assets.tenex.tech/..
           Fetching dependency metadata from https://rubygems.org/..
           Fetching git://github.com/hayesr/administrate.git
           fatal: Could not parse object '3d876a9cd2b0e64d2d36c94ad8836e1ade04265b'.
           Git error: command `git reset --hard 3d876a9cd2b0e64d2d36c94ad8836e1ade04265b`
           in directory
           /tmp/build/vendor/bundle/ruby/2.3.0/bundler/gems/administrate-3d876a9cd2b0 has
           failed.
           If this error persists you could try removing the cache directory
           '/tmp/build/vendor/bundle/ruby/2.3.0/cache/bundler/git/administrate-bba647b035c9dd5d997cae9baf24fd6234cb1ff5'
           !
           !     Failed to install gems via Bundler.
           !
    To dokku@XXXXXXX:qc2
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'dokku@XXXXXXX:qc2'

Output of the following commands

- `uname -a`:
```
Linux qc2-dokku-2 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- `free -m`:
```
                 total       used       free     shared    buffers     cached
    Mem:          2001       1453        548         11        157       1088
    -/+ buffers/cache:        208       1793
    Swap:            0          0          0
```
- `docker version`:
```
    Client:
     Version:      1.11.1
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   5604cbe
     Built:        Tue Apr 26 23:30:23 2016
     OS/Arch:      linux/amd64    

    Server:
     Version:      1.11.1
     API version:  1.23
     Go version:   go1.5.4
     Git commit:   5604cbe
     Built:        Tue Apr 26 23:30:23 2016
     OS/Arch:      linux/amd64
```

- `docker -D info`:
```
    Containers: 8
     Running: 2
     Paused: 0
     Stopped: 6
    Images: 13
    Server Version: 1.11.1
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 75
     Dirperm1 Supported: false
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins: 
     Volume: local
     Network: bridge null host
    Kernel Version: 3.13.0-85-generic
    Operating System: Ubuntu 14.04.4 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 2
    Total Memory: 1.955 GiB
    Name: qc2-dokku-2
    ID: 52WZ:7TBP:3NAQ:AO6Z:GWVJ:N5NE:CCMQ:LCBI:MYJS:GJY5:ACQZ:VQZD
    Docker Root Dir: /var/lib/docker
    Debug mode (client): true
    Debug mode (server): false
    Registry: https://index.docker.io/v1/
```

- `sigil -v`:
```
    0.4.0
```
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
    herokuish: 0.3.12
    buildpacks:
      emberjs.tgz                latest
      buildpack-nginx            v5
      heroku-buildpack-clojure   v75
      heroku-buildpack-erlang    fa17af9
      heroku-buildpack-go        v34
      heroku-buildpack-gradle    v17
      heroku-buildpack-grails    v20
      heroku-buildpack-java      v44
      heroku-buildpack-multi     v1.0.0
      heroku-buildpack-nodejs    v90
      heroku-buildpack-php       v101
      heroku-buildpack-play      v26
      heroku-buildpack-python    v80
      heroku-buildpack-ruby      v146
      heroku-buildpack-scala     v70
```

- `dokku version`:
```
    0.5.6
```
- `dokku plugin`:

```
    plugn: dev
      00_dokku-standard    0.5.6 enabled    dokku core standard plugin
      20_events            0.5.6 enabled    dokku core events logging plugin
      apps                 0.5.6 enabled    dokku core apps plugin
      build-env            0.5.6 enabled    dokku core build-env plugin
      certs                0.5.6 enabled    dokku core certificate management plugin
      checks               0.5.6 enabled    dokku core checks plugin
      common               0.5.6 enabled    dokku core common plugin
      config               0.5.6 enabled    dokku core config plugin
      docker-options       0.5.6 enabled    dokku core docker-options plugin
      domains              0.5.6 enabled    dokku core domains plugin
      enter                0.5.6 enabled    dokku core enter plugin
      git                  0.5.6 enabled    dokku core git plugin
      logs                 0.5.6 enabled    dokku core logs plugin
      named-containers     0.5.6 enabled    dokku core named containers plugin
      nginx-vhosts         0.5.6 enabled    dokku core nginx-vhosts plugin
      plugin               0.5.6 enabled    dokku core plugin plugin
      proxy                0.5.6 enabled    dokku core proxy plugin
      ps                   0.5.6 enabled    dokku core ps plugin
      psql-single-container 0.4.0.1 enabled    PostgreSQL single container service
      redis                1.0.0 enabled    dokku redis service plugin
      shell                0.5.6 enabled    dokku core shell plugin
      storage              0.5.6 enabled    dokku core storage plugin
      tags                 0.5.6 enabled    dokku core tags plugin
      tar                  0.5.6 enabled    dokku core tar plugin
```

- If a deploy is failing or behaving unexpectedly:
  - Application name: **qc2**
  - The type of application being deployed: **Rails**
  

- Output of failing dokku commands after running `dokku trace on`:
**See https://gist.github.com/simmerer/0cd2bf67ac1e25425bd5aa37ba3c3a6e**

Environment details (AWS, VirtualBox, physical, etc.) **DigitalOcean VPS, 2GB RAM**

How was dokku installed? **DigitalOcean one-click Dokku 0.5.6/Ubuntu 14.0.4**

How reproducible: **every time**

Steps to Reproduce:
1. set up new Dokku 0.5.6 droplet on DigitalOcean
2. create qc2 app
3. visit IP address of droplet, submit Dokku configuration form (SSH key & hostname).
4. install https://github.com/Flink/dokku-psql-single-container, create database for qc2 app
5. install https://github.com/dokku/dokku-redis plugins, create and link database to qc2 app
6. `git push dokku master` from local machine

Actual Results:
Deploy ultimately fails with `! [remote rejected] master -> master (pre-receive hook declined)`

Expected Results:
Error-free deploy :)

Additional info:
Deploys using `git push dokku master` had been working just fine on a previous DigitalOcean VPS running Dokku 0.5.3. My local repo is pointed at the correct IP address for the new VPS.

The `access denied` error seems to suggest a permissions issue, but I haven't altered any permissions on the DO/Dokku instance, and permissions on `/tmp` are `1777`. I've added the SSH public key from the dokku user on this instance to my GitHub SSH keys, and that hasn't affected the errors output.

**Comment by michaelshobbs** [comment]
Couple things here 

It doesn't seem that the `access denied` error is causing your deploy error. Instead this is the cause
```
       Fetching git://github.com/hayesr/administrate.git
       fatal: Could not parse object '3d876a9cd2b0e64d2d36c94ad8836e1ade04265b'.
       Git error: command `git reset --hard 3d876a9cd2b0e64d2d36c94ad8836e1ade04265b`
       in directory
```

While the `access denied` error shouldn't be there (also I am unable to reproduce this locally), I did open gliderlabs/herokuish#151 to address file ownership and perms on the top level buildpack directory. Again, though, this is **not** the cause of your error.

**Comment by simmerer** [comment]
Ok, I'll keep digging - much appreciate any bit of guidance.

**Comment by michaelshobbs** [comment]
Looks like you might have an invalid committish in your `Gemfile` or that github repo is private. If the latter is true, you'll need to use the hostkeys and deployment-keys plugins.

- https://github.com/cedricziel/dokku-hostkeys-plugin
- https://github.com/cedricziel/dokku-deployment-keys

**Comment by simmerer** [comment]
Resolved. I'd like to say I had a clear "don't do this" takeaway, but unfortunately it's a little muddy.

While re-running the build locally (with the `administrate` gem commented out) I noticed that Rails 5.0.0.beta3 was superseded by Rails 5.0.0.beta4 a few days ago, and the beta3 release was taken down. So I've updated to beta4, which upgraded several dependent packages. Brought Administrate back in, bundled just fine.

Tried `git push dokku master` once more, and this time got a build without git complaints (https://gist.github.com/simmerer/51381e47fd23147c32aec0e1c621e4f0). The `remote: setuidgid: fatal: unable to run /tmp/buildpacks/emberjs/bin/detect: access denied` error was still present, but bundler ran.

Still got a `pre-receive hook declined` at the end, and fixed that by a simple `touch DOKKU_SCALE` to create the file it was complaining about.

Deployment now succeeds.

**Comment by michaelshobbs** [comment]
Perhaps you've hit an edge case where we didn't generate the `DOKKU_SCALE` file or something ended up in a bad state after the prior failed deploys. 

Can you attempt a fresh deploy by running `dokku apps:destroy <app>` on your droplet and try pushing your app again? Additionally, is your app repo public?

**Comment by michaelshobbs** [comment]
Two things.
- Can you share `/home/dokku/qc2/DOKKU_PROCFILE`?
- Can you gist a fresh deploy with `dokku trace on`?

**Comment by simmerer** [comment]
`/home/dokku/qc2/DOKKU_PROCFILE` exists but is empty.

Here's a traced deploy attempt: https://gist.github.com/simmerer/9340cb77cdd6eeb670e4970e523d951a

**Comment by michaelshobbs** [comment]
Hrm. Yeah seems like we had a problem parsing your `Procfile`. Can you share the `Procfile` in your app repo?

**Comment by simmerer** [comment]
Procfile exists, but is empty.

**Comment by michaelshobbs** [comment]
We generate the `DOKKU_SCALE` file based on the keys in `Procfile`. How are you expecting your app to start? Do you define that anywhere?

**Comment by michaelshobbs** [comment]
Did you check in a blank `Procfile` into your app repo?

**Comment by simmerer** [comment]
Yyyyyep. I didn't really understand what was needed in a Procfile until now, and since my app had previously deployed/started without having a Procfile present, I'd assumed a blank one wouldn't make a difference.

**Comment by michaelshobbs** [comment]
Ah ok. When you say it deployed, do you mean on Heroku or elsewhere?

**Comment by simmerer** [comment]
Deployed to a previous Dokku/DigitalOcean instance.

Everything had been going fine until I began incorporating Resque/Redis for mailer jobs in the background, which worked fine locally but not on DO. I mistakenly introduced the blank `Procfile` while trying to figure out how to install/configure Resque/Redis on my DO instance. I'm now setting up `foreman` with a correctly populated `Procfile`. 

This `DOKKU_SCALE` issue is a non-issue, then? It might be useful to document that a blank `Procfile` will cause problems. Maybe that's just commonly understood, but as someone new to Rails, I wouldn't have known that, and I don't think I've seen it pointed out anywhere.

**Comment by michaelshobbs** [comment]
Ah that makes sense. Some buildpacks will create a `.release` file with a default proc type to run. When you create a `Procfile` you override that. It's in the Heroku documentation.

@josegonzalez thoughts on where or if to include this in our docs?

**Comment by josegonzalez** [comment]
Buildpack deploy docs :)
