### ISSUE TITLE
Dokku CHECKS file and Django ALLOWED_HOSTS

### ISSUE THREAD

**Issue by lolorama** [dokku/dokku#2159]
After adding CHECKS file to prodject I have en error during deployment in my django app.

`django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.17.0.4:5000'. You may need to add '172.17.0.4' to ALLOWED_HOSTS.`

It occurs because in production we don't have 172.17.0.4 in ALLOWED_HOSTS.

I assume correct way is to get address from environment variables but it seems that there is no predefined variable for that purpose?

What is correct way to add dokku local host ip to ALLOWED_HOSTS for django app?

**Comment by josegonzalez** [comment]
We can't set that as an environment variable, and I'm guessing something else is at play here.

Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by michaelshobbs** [comment]
I had the same issue in my django apps. I'm mobile right now but I ended up inspecting the network interface to add the dynamic ip to `ALLOWED_HOSTS`

**Comment by michaelshobbs** [comment]
in `settings/production.py`
```
# retrieve first ip address for use in dokku deployments
ALLOWED_HOSTS.append(socket.getaddrinfo(socket.gethostname(), 'http')[0][4][0])
```

**Comment by josegonzalez** [comment]
That works.

**Comment by lolorama** [comment]
@michaelshobbs @josegonzalez, thanks guys!

**Comment by lolorama** [comment]
Buy the way. 

Why not to add HTTP_HOST header with dokku app domain for all requests from CHECKS file?

I assume it's more efficient way for acceptance testing to ensure that container is ready for production deployment, isn't it?

**Comment by michaelshobbs** [comment]
What would we set `HTTP_HOST` to? An app might have 1 or 10 or 100 domains attached to it....

**Comment by lolorama** [comment]
Yeah.. probably bad idea.

**Comment by josegonzalez** [comment]
@michaelshobbs we could just use the first configured domain.

**Comment by michaelshobbs** [comment]
Yeah I didn't mean to imply it was a bad idea just that we would have to arbitrarily use a domain name. I'm also not clear on what the benefit would be by doing this.

**Comment by lwm** [comment]
Is https://github.com/dokku/dokku/issues/2159#issuecomment-216906544 the official way to get this working? Im grateful for the fix but it is definitely not something I would have come up with easily or saw in the documentation. Can this be improved?

**Comment by josegonzalez** [comment]
I don't think this can be improved as the issue is application code which checks the allowed hosts, not Dokku. Other than _maybe_ stating that the host header being used for the check will not necessarily be a host header you've defined for your app - which one should we use? how are we supposed to know that your application doesn't support checks from another host? - I don't think there is anything we can improve here.

Feel free to pull request that note to our docs, but a particular fix for django definitely doesn't belong in our documentation.

**Comment by lwm** [comment]
Faire enough @josegonzalez. I'll add something to the documentation.

**Comment by ksanderer** [comment]
Solution:

```
from socket import gethostname, gethostbyname 

ALLOWED_HOSTS = [ gethostname(), gethostbyname(gethostname()), ] 
```

https://stackoverflow.com/questions/37031749/django-allowed-hosts-ips-range

**Comment by turicas** [comment]
Since we configure the domains using `dokku domains:add/set`, I'm wondering if the Dokku checks engine could use it and send the first domain as the HTTP `Host` header. This will make configuration easier and more secure for frameworks that enforce host check.

**Comment by josegonzalez** [comment]
@turicas if you have feature requests or bug reports, please don't make them on a 6 year old post. I don't have any way of keeping track of old comments and hopefully filing a feature request is straightforward enough ;)
