### ISSUE TITLE
Cannot deploy to dokku, app is not detected.

### ISSUE THREAD

**Issue by jsdario** [dokku/dokku#2160]
App is pushed but not deployed, nor detected. 

It started with basic configuration, tried rails sample app and worked. Added an app, this time in node.js and started getting the:
```
git push dokku@<site ip>:dashboard master
fatal: 'dashboard' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Tried a little bit else and found this https://www.digitalocean.com/community/questions/dokku-cannot-git-push-my-files

So tried:
```
git init --bare dashboard
```

Now it pushes just fine, but it does not deploy properly, nor detects the app. The repo the app was taken from is https://github.com/netbeast/dashboard, with an added **Procfile**.

**Comment by michaelshobbs** [comment]
Can you include ​*all*​ of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by michaelshobbs** [comment]
Additionally using `git init --bare` bypasses the creation of the dokku git hook that makes all the dokku "magic" possible. You'll need to destroy the app and debug the original issue.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any update in over a week.
