### ISSUE TITLE
Another gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by anoland** [dokku/dokku#2161]
Description of problem:
[Similar to this problem #2079](https://github.com/dokku/dokku/issues/2079)
gzip: stdin: not in gzip format on herouku-buildpack-php > v95
I had the problem with v100 and v101
Downgraded the buildpack to v95 as suggested in other ticket and it works.
Relatively fresh install of Arch Linux using pacaur to install dokku.
I had the app running successfully yesterday. When I tried to redeploy today is when I got the error message about gzip stdin not in gzip format.

Output of the following commands

- `uname -a`:
    Linux iris 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux

- `free -m`:
    iris% free -m
              total        used        free      shared  buff/cache   available
    Mem:           3955         208         548          34        3198        3615
    Swap:          4095           0        4095

- `docker version`:
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

- `docker -D info`:
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 13
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-1443141-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.282 GB
 Data Space Total: 107.4 GB
 Data Space Available: 61.63 GB
 Metadata Space Used: 6.218 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.121 (2016-04-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.863 GiB
Name: iris
ID: ZU5A:QRCZ:AUK7:YCR6:7FJG:R7JU:CP3M:FZO6:YAYL:3MCF:W33I:WHWV
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/

- `sigil -v`: 
0.4.0

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.12
buildpacks:
  emberjs.tgz                latest
  buildpack-nginx            v5
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v34
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v90
  heroku-buildpack-php       v101
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v70

- `dokku version`:
0.5.5

- `dokku plugin`:
plugn: 0.2.1
  00_dokku-standard    0.5.5 enabled    dokku core standard plugin
  20_events            0.5.5 enabled    dokku core events logging plugin
  apps                 0.5.5 enabled    dokku core apps plugin
  build-env            0.5.5 enabled    dokku core build-env plugin
  certs                0.5.5 enabled    dokku core certificate management plugin
  checks               0.5.5 enabled    dokku core checks plugin
  common               0.5.5 enabled    dokku core common plugin
  config               0.5.5 enabled    dokku core config plugin
  docker-options       0.5.5 enabled    dokku core docker-options plugin
  domains              0.5.5 enabled    dokku core domains plugin
  enter                0.5.5 enabled    dokku core enter plugin
  git                  0.5.5 enabled    dokku core git plugin
  logs                 0.5.5 enabled    dokku core logs plugin
  named-containers     0.5.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.5 enabled    dokku core plugin plugin
  proxy                0.5.5 enabled    dokku core proxy plugin
  ps                   0.5.5 enabled    dokku core ps plugin
  shell                0.5.5 enabled    dokku core shell plugin
  storage              0.5.5 enabled    dokku core storage plugin
  tags                 0.5.5 enabled    dokku core tags plugin
  tar                  0.5.5 enabled    dokku core tar plugin

- `docker inspect CONTAINER_ID` (if applicable):
N/A
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
N/A
- Link to the exact repository being deployed (if possible/applicable):
iris% git  remote  -v
dokku	dokku@iris:php (fetch)
dokku	dokku@iris:php (push)
origin	https://github.com/heroku/php-getting-started (fetch)
origin	https://github.com/heroku/php-getting-started (push)

- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
php
  - If using buildpacks, which custom buildpacks are in use
    - N/A
  - If using a `Dockerfile`, the contents of that file
    - N/A
  - If it exists, the contents of your `Procfile`.
    -  web: vendor/bin/heroku-php-apache2 web/

- Output of failing dokku commands after running `dokku trace on`
https://gist.github.com/anoland/a4ce587092cdab40edea2b3bb130b6ce

Environment details (AWS, VirtualBox, physical, etc.):
Physical

How was dokku installed?:
Arch Linux pacaur -S dokku

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Additional info:
After downgrading buildpack to v95 it works again.
dokku config:set php BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php.git#v95

**Comment by josegonzalez** [comment]
What happens when you downgrade to version 100?

**Comment by anoland** [comment]
Just changing the buildpack is successful.
But changing code and pushing again causes the error.

https://gist.github.com/anoland/7d591bdf8555dfec0531f6bbc204a1e2

**Comment by romavab** [comment]
i got same problem today :/
set an older php buildpack version

**Comment by Epigene** [comment]
I started having the same issue on DO's dokku v0.5.6 image a couple days ago, worked fine on Monday, May 2nd for sure.

v100 does not work.
v95 does work.

**Comment by josegonzalez** [comment]
Thats really weird. Can you see what the potential differences are between 95 and 96, assuming 96 doesn't work?

**Comment by Epigene** [comment]
Will have to follow up Monday.

**Comment by josegonzalez** [comment]
Cool thanks.

If someone has an app they can put online that will reproduce the issue, I can try and take a look on my test box.

**Comment by anoland** [comment]
@josegonzalez What does that entail? If you give me your public key can you access my dokku instance somehow?

**Comment by josegonzalez** [comment]
Here are my public keys: https://api.github.com/users/josegonzalez/keys

**Comment by anoland** [comment]
I added the first key. id 92236.
dokku@php.token.technology

**Comment by josegonzalez** [comment]
I think you did that wrong:

```
$ ssh dokku@php.token.technology
 !     `-c FINGERPRINT=SHA256:0uliNFsISm1scML7uA29BHkqB53RVSOIskVDpecv5Ps NAME="josegonzalez" `cat /var/dokku//.sshcommand` $SSH_ORIGINAL_COMMAND` is not a dokku command.
 !     See `dokku help` for a list of available commands.
Connection to php.token.technology closed.
```
Can you check to ensure that the line for my token is valid?

**Comment by anoland** [comment]
Try again.

**Comment by anoland** [comment]
Try again with the second key.
`
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBdJ8RIVfTBd3UCDn1MW2zj4/pVN0JSUnUxAT+1R4LUlmjGXdOCWFBquLd1hIpBmLXMPqZ5UmhiinUsbBUE1emN1N7UVyhdCao8zVoV1tnlmiMinPQ4z89n7CcrbLn7IHKH+jIlEVA4nSWU/XQujz646rlukkT58Jt1YVxwoq6pz3/rvTognr1FMiVol19ZsWtl3cLN85gc+RRTPywhMa7kcJ+4B3iUnUpHRrf0Crms8G4IPZYiG4gx3J6CzhmzSthKaC9F1Tk3MNV6ujZPVFFllFX52ilYpyEzNUwB7i85QXGkYuLCgZh3jl30hiQGh8JgjmDdL+QNNG/Ky+p38un | sshcommand acl-add dokku josegonzalez
SHA256:5fdItd0YArJhADN6n/zC9IDo+HEZ20V+FhAZXFqhtoE
`

`
command="FINGERPRINT=SHA256:udlUcUCtZBrb3AY3hW/Nsn0IF80aVb31tDq5kOFepEk NAME=\"local key\" `cat /var/dokku//.sshcommand` $SSH_ORIGINAL_COMMAND",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQb0XsD2C/UEwOzx1uJ2SVUdXqjVFTNQZuiDFdVRIx/+DmbQeEdco05mPE34M+OqoKMdPM0ej6yOcsKAvyiiNWCjWup9+ekRNXaWMjyjKPx69JZ9Xmk7SAAVPyDWAlfPDPLmCiwlQp98c75+GDH36velU/q5ke2a1DW79a6NWWClEOz1K7+0K2sSG7LorhS44NK5fLMKfiXfyglwwM70UO3jEV0FZ7gfRZMtgyR6E3GO3v5MFQgxDAv2lQeSSa0ljQv6SZ16ogdnjBD5CX5v3IS3Bo/FGgpLlHS3YgVHJqMPyiGOtgECtxAwN0ZQD2PlL9dPTTQgPEqHTKI6GhN8z5 anoland@iris
command="FINGERPRINT=SHA256:5fdItd0YArJhADN6n/zC9IDo+HEZ20V+FhAZXFqhtoE NAME=\"josegonzalez\" `cat /var/dokku//.sshcommand` $SSH_ORIGINAL_COMMAND",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBdJ8RIVfTBd3UCDn1MW2zj4/pVN0JSUnUxAT+1R4LUlmjGXdOCWFBquLd1hIpBmLXMPqZ5UmhiinUsbBUE1emN1N7UVyhdCao8zVoV1tnlmiMinPQ4z89n7CcrbLn7IHKH+jIlEVA4nSWU/XQujz646rlukkT58Jt1YVxwoq6pz3/rvTognr1FMiVol19ZsWtl3cLN85gc+RRTPywhMa7kcJ+4B3iUnUpHRrf0Crms8G4IPZYiG4gx3J6CzhmzSthKaC9F1Tk3MNV6ujZPVFFllFX52ilYpyEzNUwB7i85QXGkYuLCgZh3jl30hiQGh8JgjmDdL+QNNG/Ky+p38un
~                                                                                                
`

**Comment by anatolinicolae** [comment]
Same problem here. Deploying PHP applications on Dokku 0.5.6 and buildpacks > v95 doesn't work, while v95 deploys successfully.

**Comment by Epigene** [comment]
On change between heroku-buildpack-php v95 and v96..

Cloning the repo and doing `git diff v95 v96` gives 2500 lines of changes.
Key changes have been marked down in CHANGELOG, they are:

```
## v96 (2016-03-10)

### ADD

- ext-imagick/3.4.1 for all PHP versions, with platform imagemagick [David Zuelke]
- ext-mongodb/1.1.3 [David Zuelke]
- ext-ldap, with SASL, for PHP builds (#131) [David Zuelke]
- ext-gmp for PHP builds (#117) [David Zuelke]
- ext-event/2.0.0 [David Zuelke]
- apcu_bc for ext-apcu on PHP 7 (#137) [David Zuelke]
- ext-newrelic/6.0.1.156 (#153) [David Zuelke]

### CHG

- Use Composer/1.0.0beta1 [David Zuelke]
- Remove vendored ICU library and use platform ICU52 for PHP [David Zuelke]
- Remove vendored zlib and use platform version for PHP and Apache [David Zuelke]
- Remove vendored pcre library and use platform version for Apache [David Zuelke]
- Use platform pcre and zlib for Nginx [David Zuelke]
- Update vendored gettext to 0.19.7 and build only its runtime parts [David Zuelke]
- Use platform libsasl for libmemcached [David Zuelke]
- Strip platform packages on build install [David Zuelke]
- Ignore platform package replace/provide/conflict from root `composer.json` on platform package install [David Zuelke]

### FIX

- Platform installer is incompatible with PHP 5.5 [David Zuelke]
```

Searching for `gzip` and `gz` in changes gives 0 hits for `gzip` and 42 hits for `gz`

Among those 42 are:

```
-curl --silent --location "${s3_url}php-min.tar.gz" | tar xz -C $build_dir/.heroku/php-min
-curl --silent --location "${s3_url}composer-1.0.0alpha11.tar.gz" | tar xz -C $build_dir/.heroku/php
+curl --silent --location "${s3_url}php-min-7.0.4.tar.gz" | tar xz -C $build_dir/.heroku/php-min
+curl --silent --location "${s3_url}composer-1.0.0-beta1.tar.gz" | tar xz -C $build_dir/.heroku/php
```

```
+python $(dirname $BASH_SOURCE)/_util/include/manifest.py "heroku-sys-package" "heroku-sys/pkg-${dep_name}" "$dep_version" "${dep_formula}.tar.gz" > $dep_manifest
```

Lots of `${dep_dirname}.tgz`, `${dep_dirname}.tar.gz` and `${dep_formula}.tar.gz` invocations.

**Comment by michaelshobbs** [comment]
A new version of herokuish was released yesterday that includes v102 of this buildpack and seems to resolve this issue.

**Comment by crisward** [comment]
Following this issue and #2079 it may make sense for dokku to have a buildpacks command
which aliases `sudo docker run -ti gliderlabs/herokuish:latest herokuish version`

It's also be nice if it had eg

`dokku buildpacks:set php 105`

So we could globally set buildpack versions.

* Do you see any problem with this?
* Will just editing `/var/lib/herokuish/buildpacks/buildpack-php` change version (I'm guessing not) or does the herokuish image need rebuilding afterwards?

**Comment by jordi12100** [comment]
I'm having this issue with the latest PHP build pack (v120).

I'm using v119 for now, but that shouldn't be a permanent solution.  
`dokku config:set spotify  BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php#v119`

**Comment by crisward** [comment]
Strange, we got this recently and using v120 fixed it.

**Comment by crisward** [comment]
This is just a theory, but the php buildpack downloads php and nginx on each push. Could the older buildpacks be pointing at non-existant urls ? - and trying to unzip them, a 404 page would return a non-unzippable payload.

**Comment by jordi12100** [comment]
Is there any way for me to see more detailed logs around this issue?
It pushed a new/non-existing project, in case you might be interested.

**Comment by crisward** [comment]
Did you specify the php version in your non-working project? (perhaps in the composer.json file)

**Comment by jordi12100** [comment]
Yes. Did set it to `>=5.6`, later tried `>=5.6, <7.1` just to see if that was working (without any luck).

**Comment by josegonzalez** [comment]
Please do not resurrect old issues like this. File a new issue and include all the information we ask for when filing issues.
