### ISSUE TITLE
deploying arbitrary docker image with tags:deploy yields failed nginx config

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#2162]
from @jgillich in #2153 

I retagged the official couchdb image and launched it using dokku tags:deploy - inside the container, couchdb works just fine, outside I just get a 502 on both port 80 and 5984.

```
# dokku apps:create foo
# docker pull couchdb:1.6
# docker tag couchdb:1.6 dokku/foo:1.0
# dokku tags:deploy foo 1.0
-----> Releasing foo (dokku/foo:1.0)...
-----> Deploying foo (dokku/foo:1.0)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> No Procfile found in app image
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
=====> renaming container (e1127f540e38) compassionate_sammet to foo.web.1
-----> Creating new /home/dokku/foo/VHOST...
-----> Setting config vars
       DOKKU_NGINX_PORT: 80
-----> Configuring foo.dokku.bar...(using built-in template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
=====> Application deployed:
       http://foo.dokku.bar
```

* `http://foo.dokku.bar` -> 502
* `http://foo.dokku.bar:5984` -> Connection refused
* `dokku enter foo web` && `curl localhost:5984` -> works
* `docker ps` -> `5984/tcp`

Am I missing something?

Erm. You asked for reproduction steps, I posted them. This is simply about a exposed (yes, yes HTTP) port not being detected. The [docs clearly say](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/):

> Dokku will extract all tcp ports exposed using the EXPOSE directive (one port per line) and setup nginx to proxy the same port numbers to listen publicly

And that is not the case. I don't see any reason to create a new issue here.

**Comment by michaelshobbs** [comment]
@jgillich you have definitely attempted an unsupported method of deploying an image.

As you point out [per the docs](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/):
>Dokku will extract all tcp ports exposed using the EXPOSE directive (one port per line) and setup nginx to proxy the same port numbers to listen publicly

However, in your use case, you've never presented dokku with a `Dockerfile` from which to extract the ports.

**Comment by michaelshobbs** [comment]
This seems to work given your use case

```
root@dokku:~# dokku apps:create couchdb
Creating couchdb... done
root@dokku:~# dokku config:set couchdb DOKKU_DOCKERFILE_PORTS=5984
-----> Setting config vars
       DOKKU_DOCKERFILE_PORTS: 5984
-----> Restarting app couchdb
App couchdb has not been deployed
root@dokku:~# docker pull couchdb:1.6
root@dokku:~# docker tag couchdb:1.6 dokku/couchdb:1.0
root@dokku:~# dokku tags:deploy couchdb 1.0
-----> Releasing couchdb (dokku/couchdb:1.0)...
-----> Deploying couchdb (dokku/couchdb:1.0)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> No Procfile found in app image
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
=====> renaming container (bb254f0e1a87) ecstatic_lumiere to couchdb.web.1
-----> Creating new /home/dokku/couchdb/VHOST...
-----> Configuring couchdb.dokku.me...(using built-in template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
=====> Application deployed:
       http://couchdb.dokku.me:5984


root@dokku:~# curl localhost:5984
{"couchdb":"Welcome","uuid":"21169f9207a37cd22c375444d64dbc48","version":"1.6.1","vendor":{"version":"1.6.1","name":"The Apache Software Foundation"}}
```

**Comment by jgillich** [comment]
Oh wow. `docker inspect` also returns that information, I'm surprised it needs the Dockerfile for that.

Thanks!

**Comment by michaelshobbs** [comment]
If you have suggestions for how to build support for this into dokku, feel free to submit a PR.

**Comment by jgillich** [comment]
@michaelshobbs cc @josegonzalez

You should realize that behaviour like this reflects very poorly on the project. At no point have you given me a single reason why this is a different issue, all you've been telling me was "you're doing it wrong, fuck off", and then you went ahead and deleted the entire conversation.

**Comment by michaelshobbs** [comment]
First, it is still unclear whether your issue is the same as #2162. Second, I copied all of the **relevant** comments from that issue and posted them here after inviting you (multiple times) to either create a new issue or join us on slack for support. (Of note, I even linked the two issues together for reference.) Third, I provided you with a solution to your problem here in a dedicated issue to your question and invited you help contribute if you thought this method of deploying an app could be useful to the dokku project. 

Finally, nobody **ever** said you're doing it wrong and to fuck off. I merely stated that you were using the project in an unsupported way. In fact you decided to take the conversation to an unprofessional place here. 
> Well, I couldn't care less if it's meant for that, I'm just trying out Dokku. The issue is about ports exposed by a container not being picked up, right?

In any case, this is open source software. Nobody is getting paid to work on or support dokku. I am one of the maintainers of this project and frankly, I can choose how I want to support it. Including splitting two issues apart. So, what exactly are you hoping to accomplish here, Jakob?

**Comment by josegonzalez** [comment]
For the record, I fully back @michaelshobbs handling of the issue. I was out getting absolutely shit-faced, otherwise I would have moved the conversation around your problem to another issue. It's still not clear to me that they are the same issue, though that might because of my hangover :P

I'm not a huge fan of fixing this, mostly because deploying image tags seems like a case of "training wheels off" mode. I'd personally rather document "hey, this is gonna be painful because of X, here is the workaround", but I'm discussing on slack with @michaelshobbs what the best code-fix would be since it's not clear to me _where_ this should go.

**Comment by jgillich** [comment]
> It's still not clear to me that they are the same issue

Are you guys for real? The steps to reproduce in the original issue were the SAME as the one's I posted, and the result was also EXACTLY the same. @michaelshobbs has not given me ANY explanation as to why he thought it was a different issue. I REPEATEDLY presented arguments that supported my claim that it is the same issue, then he just went ahead and "moved" everything here. As it turns out, both issues are actually about the same..who would've thought?

This is not acceptable behaviour in my book. I've been working with and on open source projects for more than a few years, and never has a maintainer responded so poorly. But further discussion of this matter won't do any good, so that is all from me.

**Comment by michaelshobbs** [comment]
The [original issue report](https://github.com/dokku/dokku/issues/2153) said
> I can't connect to the port exposed by a docker container created using a custom Dockerfile. Dokku seems ignoring the exposed ports and fallback to the default port 5000. 

The key piece of information here is "custom Dockerfile." How that image was built was ambiguous to me up until about 2 hours ago when the original poster showed a similar workflow to yours. (Of note, I called out that these issues are in fact almost identical after this was confirmed)

All I'm seeing is criticism on a judgement call of the guy (**me**) that wrote the code you were having issues with. Again, Jakob, what are you hoping to accomplish by personally attacking how we handle supporting a free project?

**Comment by jgillich** [comment]
I'm not trying to accomplish anything, I'm just telling you that the whole thing was handled poorly. If you had explained yourself, I would've been fine with opening a new issue. But instead, you deleted the whole conversation, still without any reason given, which was very frustrating for me. I won't be using Dokku because I don't want to deal with issues like this one on a regular basis, which I suppose we both can agree on is for the best. It is up to you to draw your own conclusions, or not.

**Comment by josegonzalez** [comment]
Since:

- The issue has been resolved
- We prematurely moved the issue (we've done this in the past)
- You aren't using dokku

I'm going to lock this issue as there isn't anything useful to be gained from further discussion. Apologies if we came off as rude and/or abrasive.
