### ISSUE TITLE
Incorrect domain existence check on domains:add

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2165]
In the [domains_add](https://github.com/dokku/dokku/blob/5940e43c85a36d4a8f609bb00d1d700f25ae8e96/plugins/domains/functions#L69) code, we currently only check for the existence of the first domain, and subsequently bail out if we find it. This command actually takes multiple domains.

We should instead:

- Check on each domain during the iteration [here](https://github.com/dokku/dokku/blob/5940e43c85a36d4a8f609bb00d1d700f25ae8e96/plugins/domains/functions#L75).
- Avoid bailing out and instead just continue, since the desired state already exists.

**Comment by jvanbaarsen** [comment]
@josegonzalez If you want I can take a stab at this?

**Comment by josegonzalez** [comment]
Go for it.

**Comment by jvanbaarsen** [comment]
:+1:
