### ISSUE TITLE
Is it possible to have a plugin hook for logs?

### ISSUE THREAD

**Issue by pltchuong** [dokku/dokku#2169]
That would be helpful if someone (like me) wanted to have some custom actions on logging (like write to file)

**Comment by pltchuong** [comment]
I realized I should output it myself instead of having a hook

**Comment by josegonzalez** [comment]
If you're trying to push logs somewhere, may I recommend rsyslog? https://gist.github.com/tmornini/aa25e93556622b982d473899e5305e33
