### ISSUE TITLE
Executables should be installed in /usr/bin

### ISSUE THREAD

**Issue by hansmi** [dokku/dokku#2172]
This is a variation of [sshcommand issue 28](https://github.com/dokku/sshcommand/issues/28). The `dokku` and `sshcommand` packages install their executables in `/usr/local/bin`. 

This is problematic because the `dokku` package depends on `sshcommand` and uses an unqualified name:

```
# grep sshcommand /var/lib/dpkg/info/dokku.postinst
    sshcommand create dokku /usr/local/bin/dokku
        sshcommand acl-add dokku default < "$RET" || true
```

There are environments where PATH does not contain `/usr/local/bin` during package installation, e.g. in Puppet (PATH is `/bin:/sbin:/usr/bin:/usr/sbin`). Consequently the `dokku` package fails to install (`/var/lib/dpkg/info/dokku.postinst: line 17: sshcommand: command not found`).

The underlying issue is the location used by the `sshcommand` package, however.

The package for Debian/Ubuntu distributions installs the `sshcommand` binary in `/usr/local/bin`. [According to the FHS](http://www.pathname.com/fhs/2.2/fhs-4.9.html) `/usr/local` is to for “use by the system administrator when installing software locally”.

**Comment by u2mejc** [comment]
I'm not keen to this, but it might be a shared feeling.

I'm not sure that's a good enough reason to move to a directory that will break future portability on distros / platforms that are setting up security enclaves. Puppet's PATH is easily updated, so that kinda mute too. But more to the point, since /usr/local/bin is an available binary path, we can simply add the fully qualified path to the command to fix this issue. I prefer explicit, rather than implicit.

**Comment by josegonzalez** [comment]
Thats certainly true, but we should still follow the lintian guidelines, which also barf on this path.

**Comment by tobru** [comment]
I also vote for having binaries installed by a distro-package to be located in `/usr/bin` because that's the common default. `/usr/local/bin` is reserved for binaries which come by other mechanisms than distro-packages.

**Comment by josegonzalez** [comment]
I just copied what was going on in the Makefile, which appears to put it in `/usr/local/bin`. From that perspective, an apt-get install needs to at least remove the Makefile version if it exists.

**Comment by hansmi** [comment]
> I just copied what was going on in the Makefile, which appears to put it in /usr/local/bin.

`/usr/local` is the default prefix used by most software. Distribution packagers change the prefix to `/usr` (e.g. with autoconf/automake: `./configure --prefix=/usr && make && make install DESTDIR=/tmp/…/dir/for/packaging && tar -C /tmp/…/dir/for/packaging -czf /tmp/package.tar.gz .`). See also the [Debian's New Maintainers' Guide](https://www.debian.org/doc/manuals/maint-guide/modify.en.html#destdir).

> From that perspective, an apt-get install needs to at least remove the Makefile version if it exists.

A user may want to have multiple versions installed in different prefix paths. A distribution package should only touch the files it installed in the first place. Your Makefile could provide an `uninstall` target, though.
