### ISSUE TITLE
What are the exact moments the deployment tasks are triggered? 

### ISSUE THREAD

**Issue by melbic** [dokku/dokku#2179]
Description of problem:
I couldn't find any description when exactly the pre- and postdeploy scripts are executed. My guess: `predeploy`: AFTER building the container and BEFORE new container(s) are going live.
`postdeploy`: AFTER new container(s) going live and before/at the same time as the old are torn down.

If anybody could confirm my guesses, I'd be happy to do a documentation PR.

**Comment by michaelshobbs** [comment]
Documenting the build/deploy process is probably a good idea. (I thought this was already done?) 

Anyway here's what it looks like.  

```
pre-build triggers 
  - buildpack OR dockerfile
build app image 
  - copy app files and run buildpack OR docker build
post-build triggers 
  - buildpack OR dockerfile
pre-release triggers 
  - buildpack OR dockerfile
release 
  - inject config vars into /app/.profile.d/ or build docker ENV file
post-release triggers
  - buildpack or dockerfile
pre-deploy triggers
  - includes app.json pre-deploy tasks committed to app image
deploy
  - start up app container based on build image
post-deploy triggers
  - includes app.json post-deploy tasks NOT run inside app container or committed to app image
  - includes (re)building nginx configuration 
```

Hope this helps.

**Comment by josegonzalez** [comment]
This should already be documented in the plugin triggers doc.

**Comment by michaelshobbs** [comment]
I not certain it's clearly laid out in a way that includes the entire build and deploy process
