### ISSUE TITLE
v0.5.6 Nginx templating documentation

### ISSUE THREAD

**Issue by Epigene** [dokku/dokku#2180]
Description of problem:
The nginx.conf file generated by default (without nginx.conf.sigil) differs from one generated when using `nginx.conf.sigil` template with default content taken from [docs](http://dokku.viewdocs.io/dokku~v0.5.6/nginx), specifically, lacks gzip settings block.

```
gzip on;
gzip_min_length  1100;
gzip_buffers  4 32k;
gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
gzip_vary on;
gzip_comp_level  6;
```

Possible Solution:
Update vanilla template in docs.

Additional Info:
Are docs a repo? I can make the needed changes and post a PR.

**Comment by michaelshobbs** [comment]
The example in the docs is meant to be exactly that; an example not a full recreation of the default config. In any case, docs live in this repo under `docs/` and the docs site gets generated from those markdown files.

**Comment by Epigene** [comment]
I've done my part: PR @ https://github.com/dokku/dokku/pull/2183

**Comment by michaelshobbs** [comment]
Cool. Thanks!
