### ISSUE TITLE
Allow restarting specific container or process type

### ISSUE THREAD

**Issue by mtarnovan** [dokku/dokku#2184]
It would be useful to extend the `ps:restart` command to allow restarting a specific container or process type:

`ps:restart <app> <container_id_or_name_or_type>`

For example:

``` bash
  ps:restart my_app worker  # would restart all containers of type worker
  ps:restart my_app worker.1 # would restart just worker.1
  ps:restart my_app my_app.worker.1 # same as above, but identified via container name
```

_Note_: you can currently restart a process type by scaling down to zero:
`ps:scale web=1 worker=0 && ps:scale web=1 worker=1`
would restart all workers, but this seems a little clumsy.

**Comment by michaelshobbs** [comment]
Notes from Heroku UI
```
$ heroku ps:restart -h
Usage: heroku ps:restart [DYNO]

restart app dynos

 -a, --app APP       # app to run command against
 -r, --remote REMOTE # git remote of app to run command against

if DYNO is not specified, restarts all dynos on app

Examples:

  $ heroku ps:restart web.1
  Restarting web.1 dyno... done

  $ heroku ps:restart web
  Restarting web dynos... done

  $ heroku ps:restart
  Restarting dynos... done
```

**Comment by josegonzalez** [comment]
I don't think we should ever do the third option mentioned in the OP:

```
ps:restart my_app my_app.worker.1 # same as above, but identified via container name
```

Too much parsing.

**Comment by josegonzalez** [comment]
This is actually non-trivial due to how we handle process restarting, and probably it's better to expose restart policies to handle cases where a user wants to auto-restart apps.

https://github.com/dokku/dokku/pull/2290

**Comment by drbraden** [comment]
I think this would be very useful, too.  I agree with @josegonzalez that the third form in the OP is unneeded.  Since the app must exist as the previous argument, including it in the next argument is completely superfluous.  But, I like the first two examples:
```
ps:restart my_app worker    # would restart all containers of type worker
ps:restart my_app worker.1  # would restart just worker.1
```

**Comment by josegonzalez** [comment]
I looked into it, and our current restart model makes this a bit difficult, since we call `release_and_deploy`.

**Comment by josegonzalez** [comment]
I think what I'm going to do is trigger a `scheduler-deploy` but with a process type specified. That plugin trigger implements deploying an app and all it's processes. It's easier for us to lean on it than refactor the container start process to handle a single process type or an instance of a process.

As a side-effect, I'm also going to only support restarting the process type, and not the instance of a process type. We can implement the latter later if it is really interesting, but not doing so allows us to more or less reuse the logic when scaling (meaning scaling is much faster).

We'll also keep track of the deployed image tag, and use that as the image when triggering a deploy. If the image does not exist, then the user should trigger an app rebuild instead.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
