### ISSUE TITLE
Unknown source of Error during build: `Error: '' invalid`

### ISSUE THREAD

**Issue by benmarten** [dokku/dokku#2185]
I am running into an issue that when pushing to dokku the build fails with a verbose error message. I don't know what the error is and why it's coming...

`Error: '' invalid`

Here's the full log: https://gist.github.com/benmarten/b80017ba1f30d8a3bcaf5dfd3c8726f1#file-gistfile1-txt-L1486

It only happens when Dokku-APT is enabled and after adding the repository

    ppa:ubuntu-toolchain-r/test

On pushing to dock, it seems to be added fine, but fails with the last line being `Error: '' invalid`

	Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
	remote: gpg: keyring `/tmp/tmp51y68o64/secring.gpg' created
	remote: gpg: keyring `/tmp/tmp51y68o64/pubring.gpg' created
	remote: gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
	remote: gpg: /tmp/tmp51y68o64/trustdb.gpg: trustdb created
	remote: gpg: key BA9EF27F: public key "Launchpad Toolchain builds" imported
	remote: gpg: Total number processed: 1
	remote: gpg:               imported: 1  (RSA: 1)
	OK
	Error: '' invalid

Manually this works exactly the same; I don't know where the last line is coming from...
Any ideas?

**Comment by benmarten** [comment]
Any suggestions how I can debug this error? I am willing to investigate, but not having a clue of where I should start digging... Any tips appreciated :)

**Comment by michaelshobbs** [comment]
Do you still have the same issue if you disable the dokku-apt plugin?

**Comment by josegonzalez** [comment]
I'm unable to replicate this with  an `apt-repositories` file with the following contents:

```
ppa:ubuntu-toolchain-r/test
```

And an apt-packages file with the following contents:

```
libstdc++-6-dev
```

Closing this issue and #2176.
