### ISSUE TITLE
Unattended install is asking for param

### ISSUE THREAD

**Issue by chanlvh** [dokku/dokku#2188]
Description of problem:
Install latest dokku unattended deb with this script: https://raw.githubusercontent.com/chanlvh/config/master/setup.sh

This screen still shows up
<img width="263" alt="screen shot 2016-05-13 at 11 11 48 am" src="https://cloud.githubusercontent.com/assets/409493/15237775/85344cbc-18fb-11e6-8124-bb90b357bc17.png">

 even though I did the following:

```bash
echo "dokku dokku/web_config boolean false" | sudo debconf-set-selections
echo "dokku dokku/vhost_enable boolean true" | sudo debconf-set-selections
echo "dokku dokku/hostname string $HOST_NAME" | sudo debconf-set-selections
echo "dokku dokku/skip_key_file boolean true" | sudo debconf-set-selections
sudo apt-get --yes --force-yes -qq install dokku
```

**Comment by josegonzalez** [comment]
Debconf will still prompt you for an answer to `dokku/key_file`, even if you set `dokku/skip_key_file` to true. Nothing we can do about that, since that is how debconf works. If you set a value, we just won't import that file.
