### ISSUE TITLE
Inconsistent config files conventions

### ISSUE THREAD

**Issue by mtarnovan** [dokku/dokku#2199]
Currently some config files are picked up from the app repo (e.g. `DOKKU_SCALE`), while others must be places on the server in `$DOKKU_HOME/$APP` (e.g. `DOCKER_OPTIONS_*`). While it's debateable which is the right place™ to keep these files, it seems arbitrary to handle them differently.

In my opinion *all* these files should be picked up from the app repo, and `DOCKER_OPTIONS_*` should be renamed to `DOKKU_DOCKER_OPTIONS_*`.

**Comment by michaelshobbs** [comment]
Context:
The app repo convention comes from Heroku and is required (i.e. `Procfile`). The `$DOKKU_ROOT/$APP` placement was picked lazily and arbitrarily as a location to store app configuration. For example, you'll notice that `ENV` is also stored there. We have an [open issue](https://github.com/dokku/dokku/issues/1558) for moving app config out of the app dir.

To clarify on your second point, you are referring to the filenames, correct?

Also, PRs are welcomed.

**Comment by josegonzalez** [comment]
@mtarnovan Can you answer the question posed by @michaelshobbs?

**Comment by mtarnovan** [comment]
Correct, I'm referring to the filenames.

**Comment by josegonzalez** [comment]
Closing in favor of #1558. I've added a note to the generic spec to name things properly.
