### ISSUE TITLE
/etc/hosts heritage

### ISSUE THREAD

**Issue by dalou** [dokku/dokku#2200]
Dokku app instance doesn't herit from /etc/hosts ?
My problem : 
I'm on a private serveur over a VPN, i have 2 website on 2 different machines.
the **SITE1** : www.[SITE1].com, its contains an API i must call from the SITE2

the **SITE2** on a dokku container, where my /etc/hosts/ (on the VM) contains the hostname to access the first through the VPN: 
```
127.0.0.1       localhost
10.1.2.3        ******
10.1.1.245      www.[SITE1].fr
```
on the SITE2 machine root : 
```
> root@SITE2# curl "http://www.[SITE1].com" 
OK status 200
```
but inside the container:
```
> root@SITE2# dokku run SITE2 bash
u27751@10f14c512a7c:~$ curl "http://www.[SITE1].com" 
[...] Try accessing the router by IP address instead of by hostname. [...]
```
so dokku bypass /etc/hosts ? how to add this configuration for a container ?

Thanks

**Comment by josegonzalez** [comment]
Docker uses it's own networking stack, not the hosts. You'll need to either:

- use the `--net=host` flag to change this via the official `docker-options` plugin. See the [docker networking docs](https://docs.docker.com/v1.8/articles/networking/) for more details.
- use the `--add-host host:ip` flag to dynamically add entries via the official `docker-options` plugin. Blog post on that [here](http://jasani.org/2014/11/19/docker-now-supports-adding-host-mappings/).

Closing, as this isn't a bug with dokku, but just an "oddity" in how docker handles networking.
