### ISSUE TITLE
Question: Newrelic for PHP

### ISSUE THREAD

**Issue by Epigene** [dokku/dokku#2204]
I am looking to set up Newrelic for some WordPress blogs on dokku v0.5.6. Is this possible? What would be the workflow? I am not sure how [Heroku's PHP agent installation](https://docs.newrelic.com/docs/agents/php-agent/advanced-installation/php-agent-heroku#installing) translates to dokku.

**Comment by michaelshobbs** [comment]
You would need to follow NewRelic's installation guide. I believe the Heroku add-on only works in the Heroku infrastructure.

**Comment by michaelshobbs** [comment]
Note: You can still control config with ENV vars like on Heroku

i.e. https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration
```
NEW_RELIC_LICENSE_KEY='YOUR_LICENSE_KEY'
NEW_RELIC_LOG_LEVEL="warning"
NEW_RELIC_APP_NAME="YOUR_APP_NAME"
```

**Comment by michaelshobbs** [comment]
To be clear, I've not used NR with PHP and dokku. I'm reading the install guide now and I think you would need to manually download the agent files, place them in your app repo and somehow configure PHP to load the agent on startup. 

In python, you can do something like the following but no idea how to do it with PHP
```
NEW_RELIC_APP_NAME="YOUR_APP_NAME" NEW_RELIC_CONFIG_FILE=/app/newrelic.ini \
newrelic-admin run-program python /app/.heroku/python/bin/celery worker -A appcelery \ 
-P eventlet -c 1000 --loglevel=INFO
```

**Comment by Epigene** [comment]
From [NR's PHP installation guide](https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian), it comes exclusively as a system tool via apt-get or dpkg. It seems to me that even if I managed to get the agent files, I'd still end up installing Newrelic each time there'd be a container build. Inefficient.
Perhaps an independent, persistent php-newrelic service much like a database is needed. Though I imagine it's way above my head.

**Comment by josegonzalez** [comment]
You need newrelic running in the container, not externally like you can in a database.

You can use the [dokku-apt](https://github.com/F4-Group/dokku-apt) plugin to handle installation before the buildpack runs, which would allow you to cache the install while you have the same herokuish image.

**Comment by Epigene** [comment]
Yes! With dokku-apt providing Newrelic inside the container (and hopefully running the daemon) and ENV variables for settings, I just might get it running.
Will report tomorrow.

**Comment by Epigene** [comment]
Tested dokku-apt, and it can install straightforward packages like htop easily, but [PHP agent installation](https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian) has custom elements I do not see it supporting.

I think I can reverse-engineer dokku-apt and write a new plugin that installs Newrelic specifically.

Closing for now. I will report back once I get something working. Thanks for all your help @michaelshobbs  and @josegonzalez

**Comment by Epigene** [comment]
I've just managed to get some NewRelic going with correct use of dokku-apt's `dpkg-packages` and `apt-debconf` functionality.

Full writeup @ https://gist.github.com/Epigene/6b1defa2cb1d0f82bd88a478d14898da#install-newrelic

**Comment by Neamar** [comment]
If anyone is looking for something similar, this is now easier to achieve: just set your `NEW_RELIC_LICENSE_KEY` and the PHP buildpack will install and setup newrelic for you ;)

(see https://github.com/heroku/heroku-buildpack-php/blob/master/bin/util/newrelic.sh for the actual implementation)
