### ISSUE TITLE
Dokku client auto push after creating an App

### ISSUE THREAD

**Issue by GabKlein** [dokku/dokku#2210]
Hi, I'm having an issue with the Dokku client that automatically push after creating an new App.
In my case I have many other step to happen prior deploying a new app. 
I need different environment variables, buildpacks and service. This behavior is making my builds failed

- `dokku version`: 0.5.7
- `code`: https://github.com/dokku/dokku/blob/master/contrib/dokku_client.sh#L82 

Steps to Reproduce:
1. `dokku app:create new-name`

**Comment by michaelshobbs** [comment]
Seems like Heroku no longer (or didn't in the first place) behaves this way. 

@josegonzalez thoughts on removing the auto push on `apps:create` in the client?

**Comment by josegonzalez** [comment]
Fine by me. Less magic == better imo.

**Comment by michaelshobbs** [comment]
@GabKlein As a workaround, you could provision your app on the server first.
