### ISSUE TITLE
dokku installation left vulnerable if web setup isn't completed

### ISSUE THREAD

**Issue by jbothma** [dokku/dokku#2211]
### Description of problem:

If you don't follow the web setup, it remains accessible and can be used to insert an SSH key by an attacker.

### Output of the following commands

n/a

### Environment details (AWS, VirtualBox, physical, etc.):

n/a

### How was dokku installed?:

script, then added SSH keys via command line and vhosts via dokku command line client

### How reproducible:

Quite

#### Steps to Reproduce:
1. Run install script
2. Don't complete web setup
3. Wait to get haxxored

#### Actual Results:

Someone can at the very least insert a key and execute dokku commands

#### Expected Results:

Users would realise how easily this happens and not do it, or the web setup would be unaccessible to unauthorised visitors

### Additional info:
 n/a

**Comment by michaelshobbs** [comment]
Closed by #2212
