### ISSUE TITLE
Trying to get the Vagrant build running

### ISSUE THREAD

**Issue by kalua85** [dokku/dokku#2213]
Description of problem:

Cloned the repository and started vagrant up. Stops before finishing with error

Actual Results:
```
>==> dokku: d1183b4e86d0: Download complete
==> dokku: c02c7df4a131: Pull complete
==> dokku: a3ed95caeb02: Pull complete
==> dokku: c76060a6dfb2: Pull complete
==> dokku: 41eb4b5b2528: Verifying Checksum
==> dokku: 41eb4b5b2528: Download complete
==> dokku: 41eb4b5b2528: Pull complete
==> dokku: 088b72a57684: Pull complete
==> dokku: d1183b4e86d0: Pull complete
==> dokku: Digest: sha256:b01e5d3a1118722a215c0cc98d619eb4b9666d0c12eb54181664302949cd0840
==> dokku: Status: Downloaded newer image for gliderlabs/herokuish:latest
==> dokku: make[1]: Leaving directory `/root/dokku'
==> dokku: git describe --tags > ~dokku/VERSION  2> /dev/null || echo '~master (2016-05-26T15:04+0000)' > ~dokku/VERSION
==> dokku: cp dokku /usr/local/bin/dokku
==> dokku: mkdir -p /var/lib/dokku/core-plugins /var/lib/dokku/plugins
==> dokku: rm -rf /var/lib/dokku/core-plugins/*
==> dokku: test -d /var/lib/dokku/core-plugins/enabled || PLUGIN_PATH=/var/lib/dokku/core-plugins plugn init
==> dokku: Initialized empty Plugn plugin path in /var/lib/dokku/core-plugins
==> dokku: test -d /var/lib/dokku/plugins/enabled || PLUGIN_PATH=/var/lib/dokku/plugins plugn init
==> dokku: Initialized empty Plugn plugin path in /var/lib/dokku/plugins
==> dokku: find plugins/ -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | while read plugin; do \
==> dokku:              rm -Rf /var/lib/dokku/core-plugins/available/$plugin && \
==> dokku:              rm -Rf /var/lib/dokku/plugins/available/$plugin && \
==> dokku:              rm -rf /var/lib/dokku/core-plugins/$plugin && \
==> dokku:              rm -rf /var/lib/dokku/plugins/$plugin && \
==> dokku:              cp -R plugins/$plugin /var/lib/dokku/core-plugins/available && \
==> dokku:              ln -s /var/lib/dokku/core-plugins/available/$plugin /var/lib/dokku/plugins/available; \
==> dokku:              find /var/lib/dokku/ -xtype l -delete;\
==> dokku:              PLUGIN_PATH=/var/lib/dokku/core-plugins plugn enable $plugin ;\
==> dokku:              PLUGIN_PATH=/var/lib/dokku/plugins plugn enable $plugin ;\
==> dokku:              done
==> dokku: chown dokku:dokku -R /var/lib/dokku/plugins /var/lib/dokku/core-plugins
==> dokku: make addman
==> dokku: make[1]: Entering directory `/root/dokku'
==> dokku: mkdir -p /usr/local/share/man/man1
==> dokku: help2man -Nh help -v version -n "configure and get information from your dokku installation" -o /usr/local/share/man/man1/dokku.1 dokku
==> dokku: help2man: can't get `help' info from dokku
==> dokku: Try `--no-discard-stderr' if option outputs to stderr
==> dokku: make[1]:
==> dokku: *** [addman] Error 2
==> dokku: make[1]: Leaving directory `/root/dokku'
==> dokku: make:
==> dokku: *** [copyfiles] Error 2
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

C:\Users\servicepunt\Documents\dokku-master>
```

Expected Results:
Good working container :)

Additional info:
Already checked the issue with line endings in windows and configured git correctly. Don't know what else could be wrong.

**Comment by michaelshobbs** [comment]
#1490 seems pertinent here
Try using `vagrant up dokku-windows`

**Comment by kalua85** [comment]
Great thanks that solved it. Maybe something to add to the docs?

Now however when I make a connection with putty and login, the connection gets closed almost immediately.

>login as: dokku
>Authenticating with public key "rsa-key-20160527" from agent
>Usage: dokku [--quiet|--trace|--rm-container|--rm|--force] COMMAND <app> [command-specific-  >options]
>
>Primary help options, type "dokku COMMAND:help" for more details, or dokku help --all to see all  >commands.
>
>Commands:
>
>    apps             List your apps
>    certs            Manage Dokku apps SSL (TLS) certs
>    checks           Show zero-downtime status
>    config           Display all global or app-specific config vars
>    docker-options   Display app's Docker options for all phases (or comma separated phase list)
>    domains          List domains
>    enter            Connect to a specific app container
>    events           Show the last events (-t follows)
>   help             Print the list of commands
>    logs             Show the last logs for an application
>    ls               Pretty listing of deployed applications and containers
>    nginx            Interact with Dokku's Nginx proxy
>    plugin           Print active plugins
>    proxy            Show proxy for app
>    ps               List processes running in app container(s)
>    run              Run a command in the environment of an application
>    shell            Spawn dokku shell
>    storage          Mount local volume / directories inside containers
>    tags             List all app image tags
>    tar              An alternative to using git. Apps are loaded via tarballs instead
>    trace            Enable dokku tracing
>    url              Show the first URL for an application (compatibility)
>    urls             Show all URLs for an application
>    version          Print dokku's version


After the last line the connection is getting closed.

**Comment by kalua85** [comment]
Last piece of the raw ssh log:

>  00000220  20 20 20 20 20 20 20 20 20 20 20 20 20 20 50 72                Pr
  00000230  65 74 74 79 20 6c 69 73 74 69 6e 67 20 6f 66 20  etty listing of 
  00000240  64 65 70 6c 6f 79 65 64 20 61 70 70 6c 69 63 61  deployed applica
  00000250  74 69 6f 6e 73 20 61 6e 64 20 63 6f 6e 74 61 69  tions and contai
  00000260  6e 65 72 73 0d 0a 20 20 20 20 6e 67 69 6e 78 20  ners..    nginx 
  00000270  20 20 20 20 20 20 20 20 20 20 20 49 6e 74 65 72             Inter
  00000280  61 63 74 20 77 69 74 68 20 44 6f 6b 6b 75 27 73  act with Dokku's
  00000290  20 4e 67 69 6e 78 20 70 72 6f 78 79 0d 0a 20 20   Nginx proxy..  
  000002a0  20 20 70 6c 75 67 69 6e 20 20 20 20 20 20 20 20    plugin        
  000002b0  20 20 20 50 72 69 6e 74 20 61 63 74 69 76 65 20     Print active 
  000002c0  70 6c 75 67 69 6e 73 0d 0a 20 20 20 20 70 72 6f  plugins..    pro
  000002d0  78 79 20 20 20 20 20 20 20 20 20 20 20 20 53 68  xy            Sh
  000002e0  6f 77 20 70 72 6f 78 79 20 66 6f 72 20 61 70 70  ow proxy for app
  000002f0  0d 0a 20 20 20 20 70 73 20 20 20 20 20 20 20 20  ..    ps        
  00000300  20 20 20 20 20 20 20 4c 69 73 74 20 70 72 6f 63         List proc
  00000310  65 73 73 65 73 20 72 75 6e 6e 69 6e 67 20 69 6e  esses running in
  00000320  20 61 70 70 20 63 6f 6e 74 61 69 6e 65 72 28 73   app container(s
  00000330  29 0d 0a 20 20 20 20 72 75 6e 20 20 20 20 20 20  )..    run      
  00000340  20 20 20 20 20 20 20 20 52 75 6e 20 61 20 63 6f          Run a co
  00000350  6d 6d 61 6e 64 20 69 6e 20 74 68 65 20 65 6e 76  mmand in the env
  00000360  69 72 6f 6e 6d 65 6e 74 20 6f 66 20 61 6e 20 61  ironment of an a
  00000370  70 70 6c 69 63 61 74 69 6f 6e 0d 0a 20 20 20 20  pplication..    
  00000380  73 68 65 6c 6c 20 20 20 20 20 20 20 20 20 20 20  shell           
  00000390  20 53 70 61 77 6e 20 64 6f 6b 6b 75 20 73 68 65   Spawn dokku she
  000003a0  6c 6c 0d 0a 20 20 20 20 73 74 6f 72 61 67 65 20  ll..    storage 
  000003b0  20 20 20 20 20 20 20 20 20 4d 6f 75 6e 74 20 6c           Mount l
  000003c0  6f 63 61 6c 20 76 6f 6c 75 6d 65 20 2f 20 64 69  ocal volume / di
  000003d0  72 65 63 74 6f 72 69 65 73 20 69 6e 73 69 64 65  rectories inside
  000003e0  20 63 6f 6e 74 61 69 6e 65 72 73 0d 0a 20 20 20   containers..   
  000003f0  20 74 61 67 73 20 20 20 20 20 20 20 20 20 20 20   tags           
  00000400  20 20 4c 69 73 74 20 61 6c 6c 20 61 70 70 20 69    List all app i
  00000410  6d 61 67 65 20 74 61 67 73 0d 0a 20 20 20 20 74  mage tags..    t
  00000420  61 72 20 20 20 20 20 20 20 20 20 20 20 20 20 20  ar              
  00000430  41 6e 20 61 6c 74 65 72 6e 61 74 69 76 65 20 74  An alternative t
  00000440  6f 20 75 73 69 6e 67 20 67 69 74 2e 20 41 70 70  o using git. App
  00000450  73 20 61 72 65 20 6c 6f 61 64 65 64 20 76 69 61  s are loaded via
  00000460  20 74 61 72 62 61 6c 6c 73 20 69 6e 73 74 65 61   tarballs instea
  00000470  64 0d 0a 20 20 20 20 74 72 61 63 65 20 20 20 20  d..    trace    
  00000480  20 20 20 20 20 20 20 20 45 6e 61 62 6c 65 20 64          Enable d
  00000490  6f 6b 6b 75 20 74 72 61 63 69 6e 67 0d 0a 20 20  okku tracing..  
  000004a0  20 20 75 72 6c 20 20 20 20 20 20 20 20 20 20 20    url           
  000004b0  20 20 20 53 68 6f 77 20 74 68 65 20 66 69 72 73     Show the firs
  000004c0  74 20 55 52 4c 20 66 6f 72 20 61 6e 20 61 70 70  t URL for an app
  000004d0  6c 69 63 61 74 69 6f 6e 20 28 63 6f 6d 70 61 74  lication (compat
  000004e0  69 62 69 6c 69 74 79 29 0d 0a 20 20 20 20 75 72  ibility)..    ur
  000004f0  6c 73 20 20 20 20 20 20 20 20 20 20 20 20 20 53  ls             S
  00000500  68 6f 77 20 61 6c 6c 20 55 52 4c 73 20 66 6f 72  how all URLs for
  00000510  20 61 6e 20 61 70 70 6c 69 63 61 74 69 6f 6e 0d   an application.
  00000520  0a 20 20 20 20 76 65 72 73 69 6f 6e 20 20 20 20  .    version    
  00000530  20 20 20 20 20 20 50 72 69 6e 74 20 64 6f 6b 6b        Print dokk
  00000540  75 27 73 20 76 65 72 73 69 6f 6e 0d 0a           u's version..
Incoming raw data at 2016-05-27 11:32:11
  00000000  7d da 04 de 3a e8 60 6b 1b 43 16 cd 61 07 4b 5a  }...:.`k.C..a.KZ
  00000010  c0 dd 3e 59 29 52 ea 9a 05 75 88 15 8d 33 e7 a5  ..>Y)R...u...3..
  00000020  20 a1 62 d0 b8 27 90 c8 86 fe 72 ce 68 e0 ed be   .b..'....r.h...
  00000030  99 71 10 9b 45 76 7f de 4a 13 08 65 d9 c8 62 c6  .q..Ev..J..e..b.
  00000040  cc 24 10 e4 a5 a2 91 76 87 fa 49 d1 f8 64 41 0e  .$.....v..I..dA.
  00000050  c3 19 9b f4 c3 44 ce c1 66 c6 a8 c9 5c da fa 93  .....D..f...\...
  00000060  e1 ab 33 37 7c 7b c6 11 49 95 b8 fb c3 4d 84 a4  ..37|{..I....M..
  00000070  25 2a 00 8b e2 46 86 ff e7 a3 13 b9 ef 62 af 69  %*...F.......b.i
  00000080  6d ab d6 8e 0f 12 9f 12 eb 96 2b fb 29 c7 94 9b  m.........+.)...
  00000090  6a f1 8f a3 de df a0 71 97 43 3b f6 98 9a 32 fe  j......q.C;...2.
  000000a0  58 98 23 93 e8 18 64 f2 b1 4f 6f 63 3c ff ec 0a  X.#...d..Ooc<...
Incoming packet #0x1f, type 98 / 0x62 (SSH2_MSG_CHANNEL_REQUEST)
  00000000  00 00 01 00 00 00 00 0b 65 78 69 74 2d 73 74 61  ........exit-sta
  00000010  74 75 73 00 00 00 00 00                          tus.....
Event Log: Server sent command exit status 0
Incoming packet #0x20, type 96 / 0x60 (SSH2_MSG_CHANNEL_EOF)
  00000000  00 00 01 00                                      ....
Outgoing packet #0xb, type 96 / 0x60 (SSH2_MSG_CHANNEL_EOF)
  00000000  00 00 00 00                                      ....
Outgoing raw data at 2016-05-27 11:32:11
  00000000  f0 2e bd ac 8b 63 3e 82 be 18 ca 95 c6 c5 8c 2e  .....c>.........
  00000010  e6 74 df 94 ee d2 15 75 d1 cd ec 35 42 cb ee a4  .t.....u...5B...
  00000020  5c 73 a2 1b 26 8f fb 32 30 7a 15 b3 42 0b 27 f4  \s..&..20z..B.'.
Outgoing packet #0xc, type 97 / 0x61 (SSH2_MSG_CHANNEL_CLOSE)
  00000000  00 00 00 00                                      ....
Outgoing raw data at 2016-05-27 11:32:11
  00000000  3b 06 99 36 ab 7b 57 aa b0 bb d7 a5 19 2b 7d fc  ;..6.{W......+}.
  00000010  74 6f 2e 74 c6 27 c5 3c 08 44 9b aa a5 92 21 f9  to.t.'.<.D....!.
  00000020  16 c1 a8 d2 73 27 b0 f8 2b 28 41 10 8a ee 68 7c  ....s'..+(A...h|
Incoming packet #0x21, type 97 / 0x61 (SSH2_MSG_CHANNEL_CLOSE)
  00000000  00 00 01 00                                      ....
Event Log: Disconnected: All channels closed

**Comment by kalua85** [comment]
Nevermind I just saw in another issue that the dokku user is limited. So how do I run commands from a windows host? Can't do ssh dokku@dokku.me, can I?

**Comment by michaelshobbs** [comment]
Looks like you figured it out then?

`vagrant ssh` will yield a shell into the vm

**Comment by kalua85** [comment]
Yeah figured it out. vagrant ssh doesn't work well on windows. But I can login to the VM with putty and login/pass = vagrant/vagrant
