### ISSUE TITLE
Permission denied when trying to create anything in shared storage

### ISSUE THREAD

**Issue by mbajur** [dokku/dokku#2215]
Description of problem:

I'm trying to use a shared storage to store some files between deploys. I've been following an official guide from here: http://dokku.viewdocs.io/dokku/dokku-storage/ so everything should work the same as described.

When i want to create a file (`$ touch /storage/test.txt`) from inside a container (`dokku enter`), it gives me Permission denied error.

Output of the following commands

- `uname -a`: Linux prod 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`: http://i.imgur.com/MSLLhsc.png
- `docker version`: http://i.imgur.com/dYzIQjJ.png
- `docker -D info`: http://i.imgur.com/vA6uZLq.png
- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`: http://i.imgur.com/lcsy4p9.png
- `dokku version`: 0.5.6
- `dokku plugin`: http://i.imgur.com/NnIcdJs.png

Environment details (AWS, VirtualBox, physical, etc.): 
Remove VPS

How was dokku installed?: 
Using installation script

Steps to Reproduce:
1. dokku storage:mount app-name /var/lib/dokku/data/storage:/storage
2. dokku enter app web
3. touch /storage/test.txt

Actual Results:
Permission denied

Expected Results:
File test.txt being created

**Comment by michaelshobbs** [comment]
What are the permissions on `/var/lib/dokku/data/storage`?

**Comment by mbajur** [comment]
It's 'drwxr-xr-x dokku dokku'
27 maj 2016 16:09 "Michael Hobbs" <notifications@github.com> napisał(a):

**Comment by michaelshobbs** [comment]
Yeah so that's why it doesn't work. By default in buildpack apps, the executing user is a random unprivileged user.

You'll need to manage the permissions on the host filesystem to allow for the user to write to that directory. I handle it in the [dokku-app-user plugin like this](https://github.com/expa/dokku-app-user/blob/255edda24e61add9c8f004b53db558f966694b35/pre-deploy#L20)

Feel free to use that plugin as well.

**Comment by josegonzalez** [comment]
@michaelshobbs worth updating docs to cover this case?

**Comment by mbajur** [comment]
I'm sorry guys, i don't feel quite self-confident when it comes to configuring unix and docker (and that's one of many reasons i'm using dokku instead of configuring all by myself - and that's why i love dokku) so that might sound trivial but i'm not sure what actually needs to be done. First of all - is that a bug or is it intended behaviour? From my perspective (person who tries to create a shared directory for all my deploys) - creating it using official docs ends up with permission denied error which comes down to not being able to save anything in that shared dir. So it looks 100% like a bug :) On the other hand, you guys sounds like it's kind of intended, i'm a bit confused...

Please correct me if i'm wrong - when i'm running anything inside dokku container (using dokku run or dokku enter), i'm running it as some random non-privileged user while dokku storage mounts it's dirs as some other user (user: 1000 / group: 1000 in my setup - are these numbers some kind of user/group ids?). So what i need to do is to change permissions of that mounted dir from 1000:1000 to u1657:u1657 OR run all the dokku run / dokku enter commands using 1000:1000 user (which seems kind of weird but i'm not any kind of a specialist in that matter, i fully trust you). Will installing plugin you mentioned @michaelshobbs automagicaly fix my issue? In readme of that plugin, i can see that i need to use custom herokuish buildpack for that because i need to create a special user - is that all the most easy way to be able to use shared directory in dokku?

Please don't get me wrong - i really love dokku and the way it works. I'm just a bit concerned that setting up shared dirs is so complicated (which makes me think that i misunderstood something you guys wrote)

Thanks in advance for any support and for your fast reply!

**Comment by rauluranga** [comment]
any news on this??
should i first install dokku-app-user plugin, then create a user
and finally give proper permissions of that user on unix?? something like `sudo chown myuser:myuser /HOST_PATH`

**Comment by michaelshobbs** [comment]
I don't think we have a good answer here. @josegonzalez thoughts?

**Comment by josegonzalez** [comment]
@michaelshobbs What *should* the initial permissions/ownership on the directory be? If we get an answer to that, then we can figure out how to present this to the user. Otherwise, I think we should fix the `USER` story in herokuish so that the user is persistent (somehow) and it doesn't muck up stuff like this.

**Comment by michaelshobbs** [comment]
I think creating a default user and id in herokuish and then in dokku using that id as the owner of storage dirs is probably a sane default

**Comment by bahmutov** [comment]
@mbajur I just gave everyone write access to the host folder, then the random dokku user that runs the container can also write there
```sh
chmod a+w /var/lib/dokku/data/storage/app/data
```

**Comment by josegonzalez** [comment]
Note: in the upcoming minor release - 0.7.0 - users will be able to properly handle setting permissions for the container user for buildpack deploys, and ensure they can be readable even in the case that they are shared amongst multiple applications.

**Comment by brylie** [comment]
> Note: in the upcoming minor release - 0.7.0 - users will be able to properly handle setting permissions for the container user for buildpack deploys, and ensure they can be readable even in the case that they are shared amongst multiple applications.

Is there a quick example of this in the documentation?
