### ISSUE TITLE
nginx-vhosts plugin should use HTTP/2 module in Nginx 1.9.5 and newer

### ISSUE THREAD

**Issue by hansmi** [dokku/dokku#2216]
When used with Nginx 1.9.5 or newer, the nginx-vhosts plugin writes a configration using the superseded “spdy” module:
```
listen      [::]:443 ssl spdy;
listen      443 ssl spdy;
```

This leads to a warning every time the configuration is reloaded:
```
invalid parameter "spdy": ngx_http_spdy_module was superseded by ngx_http_v2_module
in /home/dokku/…/nginx.conf:18
```

The replacement module is [ngx_http_v2_module](http://nginx.org/en/docs/http/ngx_http_v2_module.html).

Environment: Ubuntu 14.04.4 LTS, nginx 1.10.0, Dokku 0.5.7

**Comment by josegonzalez** [comment]
@hansmi what should the option be instead of what we have now?

**Comment by hansmi** [comment]
@josegonzalez This is a feature request, not asking for a change of existing functionality. It is my understanding that `dokku checks` only emits the status of the deployment checks (i.e. enabled/disabled). There is no way to run the same checks while an application is running. It'd be useful for monitoring the status of applications.

**Comment by hansmi** [comment]
@josegonzalez `s/spdy/http2/g` should be all
