### ISSUE TITLE
(yet another) pre-receive hook declined

### ISSUE THREAD

**Issue by Epigene** [dokku/dokku#2217]
Dokku -v 0.5.6 running on DO droplet.
Trace: https://gist.github.com/Epigene/3114e7726988cc9da38a1ab68fea34c8

What happened:
I had two rails5 apps working in production, both deployable. Then deploys started to fail, I ssh-ed into the server and found out that all of the disk space was taken up by docker logs.  
I cleaned three logs under `/var/lib/docker/containers/<hash>/<hash>-json.log` using bash's `> log`.  
Deploy still not working.
I made another dokku app and tried deploying existing app code to that, no luck.
I tried deploying ruby-rails-sample app, it works.

The trace is of an attempt to deploy the original "ccb" app to a "ccb2" dokku app.

What did I break?

**Comment by Epigene** [comment]
I should also mention that I can successfully rebuild the dokku app on server. It even correctly enters the waiting loop if I trigger a deploy while the app is being rebuilt. Sadly, only to fail when the wait if over.

**Comment by michaelshobbs** [comment]
[This command](https://gist.github.com/Epigene/3114e7726988cc9da38a1ab68fea34c8#file-trace-txt-L932) failed for some reason. Not sure why though.

**Comment by Epigene** [comment]
I am 90% sure the culprit was a `.tags` file in project root. I ended up unlinking dokku apps from services, destroying unneeded containers with

```
$ docker ps --filter status=dead --filter status=exited -aq | xargs -r docker rm -v
$ docker images --no-trunc | grep '<none>' | awk '{ print $3 }' | xargs -r docker rmi
```

Then rebooting, recreating and relinking the apps seems to have fixed this.

I wonder though what I should do next time some verbose service makes 15Gb log file?

**Comment by josegonzalez** [comment]
What heroku does is restart all dynos every 24 hours. You could do the same - `dokku ps:restartall && dokku cleanup` - in a cron task. That would clear up containers with large amounts of logs.
