### ISSUE TITLE
checks plugin should expose a command for manual checking

### ISSUE THREAD

**Issue by hansmi** [dokku/dokku#2218]
When implementing monitoring for applications it would be rather helpful to re-use the existing infrastructure for application checks using the `CHECKS` file. From what I gather it's not possible to execute the checks outside deploying as of Dokku 0.5.7.

A command like `dokku checks:run <app>` with the exit status matching the check result would be desirable.

**Comment by josegonzalez** [comment]
@hansmi sounds like a great idea, would you be willing to contribute this change?

**Comment by josegonzalez** [comment]
Closing as a working PR for 0.7.0 has been created.
