### ISSUE TITLE
Dokku installation failure

### ISSUE THREAD

**Issue by finwo** [dokku/dokku#2219]
Description of problem:
When installing dokku, heroku complaints it can not install. I've fixed it once before on my own, but I've forgotten which packages had to be installed through apt-get to be able to fix it with a final `apt-get -f install`.

Whenever this problem occurs, dokku becomes unusable due to docker refusing to start.

Output of the following commands
Also attached in [dokku.2.txt](https://github.com/dokku/dokku/files/291797/dokku.2.txt)

- `uname -a`:
```
Linux dokku 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- `free -m`:
```
              total        used        free      shared  buff/cache   available
Mem:           2000         145          48          29        1806        1778
Swap:          1022          55         967
```
- `docker version`:
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
- `docker -D info`:
```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
- `sigil -v`:
```
Segmentation fault
```
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
```
- `dokku version`:
```
0.5.7
```
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.5.7 enabled    dokku core standard plugin
  20_events            0.5.7 enabled    dokku core events logging plugin
  apps                 0.5.7 enabled    dokku core apps plugin
  build-env            0.5.7 enabled    dokku core build-env plugin
  certs                0.5.7 enabled    dokku core certificate management plugin
  checks               0.5.7 enabled    dokku core checks plugin
  common               0.5.7 enabled    dokku core common plugin
  config               0.5.7 enabled    dokku core config plugin
  docker-options       0.5.7 enabled    dokku core docker-options plugin
  domains              0.5.7 enabled    dokku core domains plugin
  enter                0.5.7 enabled    dokku core enter plugin
  git                  0.5.7 enabled    dokku core git plugin
  logs                 0.5.7 enabled    dokku core logs plugin
```
Environment details (AWS, VirtualBox, physical, etc.):
I've logged the issue for:
Fresh LXC container running on an Ubuntu 16.04 machine
`lxc-create -n dokku -t ubuntu`
Even though it happends on a minimal install of ubuntu (14.04 tested) on bare metal as welll.

How was dokku installed?:
See attached log file [dokku.txt](https://github.com/dokku/dokku/files/291527/dokku.txt)

How reproducible:
Every time on a minimal ubuntu installation

Steps to Reproduce:
1. Create the LXC container
2. SSH into the container
3. Run the installation steps from the base README.md

For the complete step 3, see [dokku.txt](https://github.com/dokku/dokku/files/291527/dokku.txt)

Actual Results:
Non-functional dokku installation

Expected Results:
Functional dokku installation, like it does on full ubuntu installations

Additional info:
[dokku.txt](https://github.com/dokku/dokku/files/291527/dokku.txt)
[dokku.2.txt](https://github.com/dokku/dokku/files/291797/dokku.2.txt)
[gist version](https://gist.github.com/finwo/010d649d945f93eb6b913ce8dfcc851d)

These .txt files are piped from SSH
`ssh hostname | tee dokku.txt`

**Comment by josegonzalez** [comment]
I've never tested in an LXC container, but our installation definitely works on ubuntu.

What happens when you follow the instructions on the `apt` tab [here](http://dokku.viewdocs.io/dokku/#install-apt)?

**Comment by finwo** [comment]
That generated a lot more output than I expected, but here the file is in the same format as the other ones (logged with `ssh hostname | file.txt`)

[dokku.3.txt](https://github.com/dokku/dokku/files/291772/dokku.3.txt)

fyi: I've logged it from a terminal of 238x58 characters

**Comment by josegonzalez** [comment]
Can you try that again, except make sure the `apt-get install` commands have `TRACE=1` in their env? That will turn on really verbose logging for the dokku installation bits.

**Comment by finwo** [comment]
Same format as the previous files.

[dokku.4.txt](https://github.com/dokku/dokku/files/292334/dokku.4.txt)

**Comment by finwo** [comment]
FYI
After the [dokku.4.txt](https://github.com/dokku/dokku/files/292334/dokku.4.txt), the server did start the webconfig. Haven't tested yet with deploying something on it.

**Comment by josegonzalez** [comment]
Seems like maybe something about LXC is incompatible with pulling/compiling docker containers...

**Comment by finwo** [comment]
That shouldn't be the issue, because I've fixed it once before by adding some packages through apt-get, and the problem occurs as well on minimal installations of ubuntu.

If I'd still remember the package names to fix it, I would've opened a PR by now.

**Comment by josegonzalez** [comment]
The problem goes away on a full server install?

**Comment by finwo** [comment]
Correct. When I install all packages that would normally be on a fresh server install, the problem does not occur.

**Comment by josegonzalez** [comment]
Basically [this](https://github.com/dokku/dokku/blob/master/deb.mk#L91) is what we do. More concerning is the fact that you sometimes don't have the docker daemon running, which may mean there is an unrelated docker issue going on?

**Comment by josegonzalez** [comment]
@finwo sorry for not being able to respond online, my timezone is EST so it was a bit early for chat for me :)

**Comment by finwo** [comment]
@josegonzalez It happens, don't worry about it.
I haven't had the time yet to test deploying to the installation that ran in [dokku.4.txt](https://github.com/dokku/dokku/files/292334/dokku.4.txt), but as soon as I do I'll post the results here.

**Comment by josegonzalez** [comment]
Okay so I basically can't do *anything* within that herokuish container within a minimal lxc instance:

```
Sending build context to Docker daemon 52.74 kB
Step 1 : FROM heroku/cedar:14
 ---> 4abcdadeb44e
Step 2 : RUN ls -lah /bin
 ---> Running in ddf49c75d8a1
Container command '/bin/sh' could not be invoked.
```

If I try with the base `ubuntu-debootstrap:14.04` image:

```
Sending build context to Docker daemon 52.74 kB
Step 1 : FROM ubuntu-debootstrap:14.04
14.04: Pulling from library/ubuntu-debootstrap

c02c7df4a131: Already exists
a3ed95caeb02: Already exists
Digest: sha256:b424724203198bdb60d79368bf967c71534dd25f2b7703021110f04e1a81b78c
Status: Downloaded newer image for ubuntu-debootstrap:14.04
 ---> 898cb62b7368
Step 2 : RUN ls -lah /bin
 ---> Running in 6913ec6eafea
Container command '/bin/sh' could not be invoked.
```

And finally, here is an `ubuntu:14.04` image:

```
Sending build context to Docker daemon 52.74 kB
Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu

56eb14001ceb: Pull complete
7ff49c327d83: Pull complete
6e532f87f96d: Pull complete
3ce63537e70c: Pull complete
Digest: sha256:d67ef8e385f1c8b13d8c3e7622dc31b51d07e5623c1d034ebe2acb14a11fb30d
Status: Downloaded newer image for ubuntu:14.04
 ---> 38c759202e30
Step 2 : RUN ls -lah /bin
 ---> Running in 2f4c8222d8ae
Container command '/bin/sh' could not be invoked.
```

I don't think this is an issue with dokku at all, but rather that docker somehow requires some package to invoke `RUN` properly and isn't finding it on an lxc instance.

@finwo Do you mind filing an issue upstream with docker/docker? I assume this is something they can fix in their debian package requirements. Not much we can do if docker itself has a missing requirement.
