### ISSUE TITLE
[RFC] proxy port mapping

### ISSUE THREAD

**Issue by michaelshobbs** [dokku/dokku#2239]
The topic of port mapping has come up quite a few times since the 0.5 release. I'd like to collect that conversation here.

### Problem
The current implementation of dockerfile ports is very rigid. If your dockerfile OR inherited image have `EXPOSE` directives, dokku will only proxy those ports. 

### Solution
Create a port mapping construct that any proxy implementation can use to configure its listeners and subsequent upstreams.

##### UI
```
proxy:ports <app>
proxy:ports-clear <app>
proxy:ports-add <app> <scheme>:<host-port>:<container-port> [<scheme>:<host-port>:<container-port>...]
proxy:ports-remove <app> <host-port> [<host-port>...]
```

##### Under the hood
- The aforementioned UI would interact with a config variable named `DOKKU_PROXY_PORTS` and would be a space-separated tuple of colon-separated port mappings; host to container. (ex. 80:8080)
- Defaults (can be overridden prior to first deploy)
  - buildpack apps: `80:5000`; same behavior as 0.5.x
  - dockerfile apps with `EXPOSE`: 1:1 proxy to container mapping; same behavior as 0.5.x
- dokku will not do any validation that the upstream port is available and/or listening. this config is directly up to the user to get right
- state change between domains disable/enable and cert add/remove will reset port mappings to ensure consistent working state of a given app

##### Cleanup (potential)
- deprecate the following config variables
  - `DOKKU_NGINX_PORT` - keeping for backwards compatibility
  - `DOKKU_NGINX_SSL_PORT` - keeping for backwards compatibility
  - `DOKKU_DOCKERFILE_PORTS` - (needed to derive `RAW_TCP_PORTS`; potential uses for other proxy implementations)

refs #2028 #2054 #2066 #2078

**Comment by michaelshobbs** [comment]
@josegonzalez @Flink @u2mejc @mmerickel @sglebs @Crispy1975 would love your feedback here

**Comment by michaelshobbs** [comment]
One thing I'm not certain about is how to delineate between an SSL and non-SSL port

**Comment by josegonzalez** [comment]
host:port:scheme ? That way we can "support" TCP or whatever. Core would only use http and https, though I can see us wanting to do tcp for haproxy.

**Comment by michaelshobbs** [comment]
Yeah that could work. I like `scheme:host:container` slightly better.

**Comment by josegonzalez** [comment]
That works for me as well. Is there prior art in the docker container world or elsewhere as to how to map ports?

**Comment by josegonzalez** [comment]
More notes

- We need to validate that the port is a valid integer in the range of valid ports.
- What happens when the proxy is turned off? Do we still retain mapped ports?
- Similar to the above, what happens when VHOST is disabled for an app?
- Do we need to validate the scheme? I say no.
- What happens when a user tries to remap a port to different schemes? Last one wins?
- Server proxies need to know the difference between the different kinds of ports. This may be potentially breaking to custom templates.
- Should we allow proxying a single container port to multiple host ports? What sort of validation are we doing there?

**Comment by michaelshobbs** [comment]
> We need to validate that the port is a valid integer in the range of valid ports.

+1 

> What happens when the proxy is turned off? Do we still retain mapped ports?

Without a proxy, port mapping has no working context. We can retain the variable but not doing with it.

>Similar to the above, what happens when VHOST is disabled for an app?

Not clear on the question here. Currently VHOST is ignored when the proxy is disabled.

>Do we need to validate the scheme? I say no.

I think it would be up to the proxy implementation to "do the right thing" with a provided scheme.

> What happens when a user tries to remap a port to different schemes? Last one wins?

The `scheme:hostport` would the be the "primary key"

> Server proxies need to know the difference between the different kinds of ports. This may be potentially breaking to custom templates.

Example? I defer to the configured proxy implementation to sort this out. 

> Should we allow proxying a single container port to multiple host ports? What sort of validation are we doing there?

I don't think we need to do anything special here. Again, no validation. This is an advanced feature and it's up to the user to make sure a given port mapping has a matching `EXPOSE` port.

**Comment by u2mejc** [comment]
@michaelshobbs What's your plan to expose (and document) support for different transport and session protocols? You mentioned SSL above for one, and I didn't see it resurfaced. Since we have talked about heterogeneous proxy support, should we start delineating if the proxy (or individual port) is inspecting / manipulating the packets, just forwarding, and/or not supporting zero down time? 

I've been focused on other projects recently, sorry if this was covered somewhere else, and thx for the @ mention.

**Comment by michaelshobbs** [comment]
If I understand your question correctly, the configured proxy implementation will be responsible for setting up configuration for its underlying proxy software. nginx only handles http/https so it will only deal with those two schemes.

**Comment by u2mejc** [comment]
>  the configured proxy implementation will be responsible for setting up configuration for its underlying proxy software.

This, ^ mostly answered my question.

**Comment by Crispy1975** [comment]
This sound pretty cool to me and definitely would help with the `0.5.x` issues we had with SSL/HTTPS. We are still on the `0.4.x` releases as that works for us with nginx doing the ssl termination side of things.

I really liked the idea that @josegonzalez mentioned about multiple ports, while most run a single service inside a container it would be useful to be able to proxy multiples. We have at least one utility container in dev that exposes multiple ports. As are target prod set-up is Deis there we only ever expose a single port.

All-in-all I like this a lot and would be great to move up to `0.5.x`. :+1:

**Comment by josegonzalez** [comment]
This would be targeting the new 0.6.x release, not 0.5.x.

**Comment by Crispy1975** [comment]
Cool, it doesn't have to have a `5` in it. ;-)
