### ISSUE TITLE
Dokku + Apidoc

### ISSUE THREAD

**Issue by stanislasdrg** [dokku/dokku#2245]
Hello everybody,
does anyone know how to generate an Apidoc on Dokku ?
I've looked for a plugin, but there isn't any, I also tried something like : 
`dokku --rm run appname apidoc -i appname/ -o apidoc/`
But it obviously returns an error :
`setuidgid: fatal: unable to run apidoc/: file does not exist`

I also saw that there is a grunt plugin, but it's imo overkill.

Thanks !

**Comment by josegonzalez** [comment]
It looks like you'll need to just install that as an npm package in your `package.json`, and then it will exist in the binary path for your app. Check out our slack group if you have any questions on how to do this.
