### ISSUE TITLE
Port problems with Dockerfile driven containers after update to 0.6.0

### ISSUE THREAD

**Issue by markdorrill** [dokku/dokku#2251]
Description of problem:
After I followed the steps on the upgrade page to update from 0.4.14 to 0.6.0 , all my containers broke. Initially, it was not clear what had happened, after some investigation looking at the nginx.conf app files it appears that all docker driven containers stopped serving on port 80 and now only work on web port 5000. After allot of reading it might be connected with the use of sigil templates after 0.5.0 but I tried to use a template and it doesnt seem to get picked up when checking the containers ngnix.conf. 

I am currently stuck as I have the container ngnix.conf manually changed but cannot deploy without manually adjusting it again after the deploy.

Output of the following commands

- `uname -a`: Linux dokku01.ams.apmano.net 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:              total       used       free     shared    buffers     cached
Mem:           490        451         38          6        126         98
-/+ buffers/cache:        227        263
Swap:          999         28        971

- `docker version`: Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

- `docker -D info`: Containers: 21
 Running: 11
 Paused: 0
 Stopped: 10
Images: 163
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 192
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: dokku01.ams.apmano.net
ID: UXRO:XOFK:FQQK:ARR4:B3SF:IJXI:OSBQ:NFGA:37D5:LRB3:5JC6:K3ML
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.13
buildpacks:
  emberjs.tgz                latest
  buildpack-nginx            v5
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v36
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v90
  heroku-buildpack-php       v102
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v70

- `dokku version`: Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.6.0 enabled    dokku core standard plugin
  20_events            0.6.0 enabled    dokku core events logging plugin
  apps                 0.6.0 enabled    dokku core apps plugin
  build-env            0.6.0 enabled    dokku core build-env plugin
  certs                0.6.0 enabled    dokku core certificate management plugin
  checks               0.6.0 enabled    dokku core checks plugin
  common               0.6.0 enabled    dokku core common plugin
  config               0.6.0 enabled    dokku core config plugin
  docker-options       0.6.0 enabled    dokku core docker-options plugin
  domains              0.6.0 enabled    dokku core domains plugin
  enter                0.6.0 enabled    dokku core enter plugin
  git                  0.6.0 enabled    dokku core git plugin
  logs                 0.6.0 enabled    dokku core logs plugin
  named-containers     0.6.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.6.0 enabled    dokku core nginx-vhosts plugin
cat: /var/lib/dokku/plugins/available/nginx-vhosts-custom-configuration/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100540c0)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
        /home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
        /home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7f148bd1af00, 0x4, 0x4, 0x6aeb58, ...)
        /home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
        /home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
cat: /var/lib/dokku/plugins/available/nginx-vhosts-custom-configuration/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100540c0)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
        /home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
        /home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7fb63c2b6f00, 0x4, 0x4, 0x6aeb58, ...)
        /home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
        /home/vagrant/gocode/src/github.com/dokku/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
  nginx-vhosts-custom-configuration       disabled   
  plugin               0.6.0 enabled    dokku core plugin plugin
  proxy                0.6.0 enabled    dokku core proxy plugin
  ps                   0.6.0 enabled    dokku core ps plugin
  repo                 0.5.3 enabled    dokku core repo plugin
  shell                0.6.0 enabled    dokku core shell plugin
  storage              0.6.0 enabled    dokku core storage plugin
  tags                 0.6.0 enabled    dokku core tags plugin
  tar                  0.6.0 enabled    dokku core tar plugin
```

- `docker inspect CONTAINER_ID` (if applicable):

  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):

- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file

```
FROM smebberson/alpine-nginx-nodejs

RUN mkdir /app
ADD . /app

#EXPOSE 5000

CMD ["nginx", "-c", "/app/nginx.conf"]

RUN npm install -g grunt-cli &>/dev/null
WORKDIR app/src/apps/email-builder
RUN npm install &>/dev/null && \
    grunt
```
  - If it exists, the contents of your `Procfile`.
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.): Digital Ocean Ubunutu Server

How was dokku installed?: apt-get

Template used in root: nginx.conf.sigil

```
server {
  listen      [::]:80;
  listen      80;
  server_name {{ .NOSSL_SERVER_NAME }};
  access_log  /var/log/nginx/{{ .APP }}-access.log;
  error_log   /var/log/nginx/{{ .APP }}-error.log;

  # set a custom header for requests
  add_header X-Served-By www-ec2-01;

  gzip on;
  gzip_min_length  1100;
  gzip_buffers  4 32k;
  gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
  gzip_vary on;
  gzip_comp_level  6;

  location    / {
    proxy_pass  http://{{ .APP }};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include {{ .DOKKU_ROOT }}/{{ .APP }}/nginx.conf.d/*.conf;
}

upstream {{ .APP }} {
{{ range .DOKKU_APP_LISTENERS | split " " }}
  server {{ . }};
{{ end }}
}
```

How reproducible: 100%

Steps to Reproduce:
1. Run Dokku 0.4.14 wtih dockerised containers using Expose 5000 
2. Upgrade to 0.6.0 following the information using the upgrade page
3. Rebuild all containers
4. Try to access containers via port 80
5. Change nginix port to port 80 using dokku config <app-name>
6. Include sigil template in root of repo to use ngnix port variable
7. deploy from repo

Actual Results:
- Horokuish containers work as they did before upgrade on port 80
- Dockerfile driven Container is still only accessible from port 5000 via web browser

Expected Results:
1. Upgrade docs or installer messaging covers this scenario if it because of changed or removed functionality

Additional info:

**Comment by michaelshobbs** [comment]
A couple things to clarify here. First, it looks like you have at least one plugin that may not be compatible. Second, the template you posted has port 80 hard coded. Is this actually the template you're having issues with?

We'll need some additional info to help you get this sorted. Please gist the output of `dokku config APP | grep DOKKU_` and a deploy of the problematic app with dokku trace on.

**Comment by markdorrill** [comment]
Thanks for your assistance with this.

I doubled checked and I was experiencing issues with the template from the docs @ http://dokku.viewdocs.io/dokku/nginx/

I had hard coded port 80 after having problems with the copy and pasted one from the docs.

I have re-tested the template from the docs and now it works on my staging and preview containers but does not work on the prod container with the same dockerfile, sigil template and ngnix.conf.

- problematic deploy gist: https://gist.github.com/markdorrill/3fb2662243bcb4d98ab00384ced5c099
- problematic config gist: https://gist.github.com/anonymous/867b892a851a6a8528891048212efa4f

I'm having a problem saving the full output of problematic `dokku config APP | grep DOKKU_  using dokku config repo-leads-prod | grep DOKKU_ > op-2.txt 2>&1 `

Any ideas how to capture the full config output? (the same command worked for the deploy output)

**Comment by josegonzalez** [comment]
The `nginx-vhosts-custom-configuration` plugin isn't compatible with 0.4.x+ since it needs a plugin.toml at least.

**Comment by michaelshobbs** [comment]
Yeah it's fine that they are. By default we will still proxy 1:1 based on the docker file `EXPOSE` directives. In this case you can modify `DOKKU_PROXY_PORT_MAP` for that app to be `http:80:5000`.

**Comment by michaelshobbs** [comment]
@josegonzalez I think the docs on the proxy port mapping could use some love still. It's pretty sparse atm and could probably use a dedicated section on the nginx page. Currently we only show the UI to interact with the setting and don't explain when one might modify it.

**Comment by josegonzalez** [comment]
Cool. Heading out right now, but I'll play around with all the various port stuff (there are a lot of nobs to twist here) and come up with something reasonable.

**Comment by michaelshobbs** [comment]
@markdorrill as previously mentioned, try setting `DOKKU_PROXY_PORT_MAP` to `http:80:5000` for that app. Let us know if that works. 

Thanks and apologies for the confusion here.

**Comment by markdorrill** [comment]
Thanks Michael, what is the command to modify `DOKKU_PROXY_PORT_MAP` for that app to be `http:80:5000` ? 

I tried `dokku config <APP-NAME> DOKKU_PROXY_PORT_MAP=http:80:5000` but it stays at 5000:5000

Also the containers that work are on 5000:5000 so I'm confused why they work and the problematic one does not.

https://gist.github.com/markdorrill/fedca751eeeecb60eb710ea475a1f6df

**Comment by michaelshobbs** [comment]
Ah! This might be a bug. I'm remote at the moment. Can you try the following flow?

```
$ dokku config:unset <APP> DOKKU_DOCKERFILE_PORT DOKKU_DOCKERFILE_PORTS
$ dokku config:set <APP> DOKKU_PROXY_PORT_MAP=http:80:5000
```

**Comment by markdorrill** [comment]
Sure, to my great relief those commands worked and have resolved the problem on the problematic container.

**Comment by michaelshobbs** [comment]
@markdorrill try redeploying that app. I suspect it will break again

**Comment by michaelshobbs** [comment]
If not what is the current state of your dockerfile? Specifically, do you have the `EXPOSE` directive commented out?

**Comment by markdorrill** [comment]
Yep, I ran two tests specifically after using the config commands you suggested:

- Redeployed with `EXPOSE` commented out - successful
- Redeployed with the original problem state `EXPOSE 5000` - also successful

**Comment by michaelshobbs** [comment]
Excellent. The expectation is that `DOKKU_PROXY_PORT_MAP` has the final say in proxy port config. Everything else is there for backwards compatibility.

**Comment by markdorrill** [comment]
I have some other containers, untouched in the original problematic state post update so can run any tests that might help you if you identify a bug or problem somewhere.

**Comment by michaelshobbs** [comment]
It sounds like things are behaving appropriately. The default behavior is a 1:1 port mapping based on any `EXPOSE` directives found in the dockerfile/app image. 

In order to override this, you would just modify `DOKKU_PROXY_PORT_MAP` config var with the `dokku config:set` command.

**Comment by markdorrill** [comment]
Ok, great. I wondered wondering:
- why only one out of three problematic containers need the config:set to work in addition to adding the template? (the others worked without `config:set `and just the new template)
- should I `config:set` all containers to 80:5000 as a matter of good practice or should just adding the new sigil template be enough?

Thanks and keep up the great work on Dokku.

**Comment by michaelshobbs** [comment]
Not sure exactly. If the other apps are buildpack apps or they are dockerfile apps with no `EXPOSE` directive, then the default `DOKKU_PROXY_PORT_MAP` is `http:80:5000`. 

What is `DOKKU_PROXY_PORT_MAP` set to for all of your apps? Also please include the type and whether they have `EXPOSE` directives set.

**Comment by josegonzalez** [comment]
@markdorrill friendly *bump*

**Comment by markdorrill** [comment]
thanks @josegonzalez @michaelshobbs 

I looked again and the containers where I did not use the `config:set` were not actually working with port 80 / without port 5000 so the config outputs were behaving consistently after all.

`root@dokku01:~# dokku config repo-leads-preview
=====> repo-leads-preview config vars
DOKKU_APP_RESTORE:      1
DOKKU_APP_TYPE:         dockerfile
DOKKU_DOCKERFILE_CMD:   CMD ["nginx", "-c", "/app/nginx.conf"]
DOKKU_DOCKERFILE_PORT:  5000
DOKKU_DOCKERFILE_PORTS: 5000
DOKKU_NGINX_PORT:       80
DOKKU_PROXY_PORT_MAP:   http:5000:5000
root@dokku01:~# dokku config repo-leads-staging
=====> repo-leads-staging config vars
DOKKU_APP_RESTORE:      1
DOKKU_APP_TYPE:         dockerfile
DOKKU_CHECKS_SKIPPED:   _all_
DOKKU_DOCKERFILE_CMD:   CMD ["nginx", "-c", "/app/nginx.conf"]
DOKKU_DOCKERFILE_PORT:  5000
DOKKU_DOCKERFILE_PORTS: 5000
DOKKU_NGINX_PORT:       80
DOKKU_PROXY_PORT_MAP:   http:5000:5000
root@dokku01:~# dokku config repo-leads-prod
=====> repo-leads-prod config vars
DOKKU_APP_RESTORE:      1
DOKKU_APP_TYPE:         dockerfile
DOKKU_DOCKERFILE_CMD:   CMD ["nginx", "-c", "/app/nginx.conf"]
DOKKU_DOCKERFILE_PORTS: 5000
DOKKU_NGINX_PORT:       80
DOKKU_PROXY_PORT_MAP:   http:80:5000`

I have used the `config:set` changes to 80:5000 and the other containers now work as expected. So looks like the docs need to mention i) sigil template and ii) config:set to 80:5000 to avoid breaking containers after upgrading from earlier versions.

**Comment by josegonzalez** [comment]
Migration docs for 0.5.x mention sigil.

Are you saying that the `http:80:5000` was set for that one app but not the others?

**Comment by markdorrill** [comment]
Yes, that's correct. 

I though the ones that I did not change were working with port 80 without using `config:set` change but it seems they were not. 

They now work as expected using the `config:set` change.

Btw I upgraded from 0.4.x using https://github.com/dokku/dokku/blob/master/docs/upgrading.md

**Comment by josegonzalez** [comment]
Yep, the `nginx.conf.sigil` changes were called out in the migration docs afaik. If not, please make a pull request to add the necessary info.

I *think* the missing `http:80:5000` entry is a bug, but we'll need to investigate this on a fresh server. I'll try an upgrade from 0.4.14 to 0.6.0 and see if I can reproduce.

Thanks for the info!

**Comment by josegonzalez** [comment]
@michaelshobbs Mind updating [this doc](https://github.com/dokku/dokku/blob/master/docs/appendices/0.6.0-migration-guide.md) to include that?

**Comment by markdorrill** [comment]
I tried with Expose 5000 commented out and I still needed the manual
config:set so looks like they did not default to 80 when there was no
Expose in the Dockerfile if it helps.

**Comment by michaelshobbs** [comment]
That is by design. The setting won't be automatically overridden on subsequent pushes. You would need to use `config:set` on `DOKKU_PROXY_PORT_MAP` or the `proxy:ports-*` commands.

See docs here: http://dokku.viewdocs.io/dokku/proxy/
