### ISSUE TITLE
dokku apps:rename old_app new_app shouldn't trigger post-delete

### ISSUE THREAD

**Issue by pltchuong** [dokku/dokku#2252]

**Comment by pltchuong** [comment]
i understand that under the hood, `apps:rename` will execute `apps_destroy` then `ps_rebuild` after that. However `apps_destroy` will trigger `pre-delete` and `post-delete`, however `ps_rebuild` won't trigger `post-create`, which is a bit lacking logic here. So we should either trigger `post-create` or not triggering delete hooks within `apps:rename`

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
