### ISSUE TITLE
TCP Port mapping options in 0.6.0

### ISSUE THREAD

**Issue by RickCarlino** [dokku/dokku#2253]
Greetings,

I was previously using `dokku-haproxy` to forward raw TCP traffic (MQTT, specifically) to my container.

I've just discovered that the dokku-haproxy plugin [doesn't support 0.6.0 yet](https://github.com/256dpi/dokku-haproxy/issues/7#issuecomment-227151931).

The new proxy plugin in 0.6.0 works great for my HTTP traffic, but doesn't seem to work for non-http traffic.

Are there any plugins out there that support this behavior and are compatible with 0.6.0? Is there a way to configure the proxy plugin to do this?

**Comment by josegonzalez** [comment]
We don't have any official plugins for this and at the moment have no plans to include such functionality.

You may support (non-scaled) applications that require TCP traffic by using a combination of the following:

- disable the proxy for your app
- disable zero-downtime deploys for your app
- use the docker-options plugin to map a port from the host to the container via the `-p` flag

Note: We recommend things like MQTT instead follow the pattern laid out by our datastore plugins, as they aren't specifically applications, and more of an attached service.
