### ISSUE TITLE
Adding storages to build stage should be optional

### ISSUE THREAD

**Issue by zakdoek** [dokku/dokku#2254]
In pull request #2238 the storage plugin changed functionality. The volumes now are added to the build stage as well. This should be configurable.

For example:
`dokku storage:mount app_name /path/to/dir:/mounted_path <run,deploy>`

**Comment by josegonzalez** [comment]
Why should this be configurable?

**Comment by zakdoek** [comment]
On a build, i noticed an issue. Before only the run and deploy stages linked to volumes. Sometimes linkage of volumes is not desired on the build stage.

The Php buildpack from heroku will somehow "clean" the linked containers. This was with a slightly modified wordpress/bedrock build. The storage plugin was linked the uploads folder.

I need to investigate further what happend in the buildscript to know what happened exactly.

**Comment by josegonzalez** [comment]
Hmmm okay. @michaelshobbs I know you're at dockercon, but do you mind taking a look when you get a chance? I think this is worth making an enhancement for, just not clear on what the UI looks like.

@zakdoek FWIW, I believe we changed this in `0.5.8`.

**Comment by josegonzalez** [comment]
Actually, looks like this may be a bug as implemented, and should be off by default.

@michaelshobbs looks like herokuish will [attempt to delete the `$app_path`](https://github.com/gliderlabs/herokuish/blob/c0bd075fc655de23f7cd1e6eeaa32521d35772ca/include/buildpack.bash#L155) - git history doesn't explain why - which ends up causing deploy issues for some applications with attached storage?

**Comment by drale2k** [comment]
When i mount a storage location,i  am running into an issue where i get the following message when i try to deploy a Rails application to Dokku 0.6.0 

`remote: rm: cannot remove '/app/public/storage': Device or resource busy`

Here is a gist with a deploy while having "dokku trace on"  https://gist.github.com/drale2k/bcbadc7426387fe47cd70e76bd9f63a2

**Comment by michaelshobbs** [comment]
@josegonzalez Are you concerned folks will create mounts under `$app_path` and thus delete the contents of the persistent storage?

**Comment by michaelshobbs** [comment]
One potential solution here is to revert the original change and document using the `docker-options` plugin to do this manually. We should also note using a docker volume under `$app_path` in a buildpack app could cause issues.

**Comment by josegonzalez** [comment]
Yes, that is my concern, but also it seems like depending upon where the storage is mounted from - if it's an external disk - the `rm` could error out, as @drale2k is seeing.

I'm 👍 on the revert and documenting how it works.

**Comment by michaelshobbs** [comment]
Additionally we could modify herokuish to not have to `rm -rf $app_path`. I'll have some time later to work on this.

**Comment by michaelshobbs** [comment]
I looked into modifying herokuish here but there's isn't a clear fix and would likely introduce other issues. I think the best thing to do here is my former suggestion of reverting and documenting.
