### ISSUE TITLE
domains:add rejects valid domains

### ISSUE THREAD

**Issue by otium** [dokku/dokku#2257]
Description of problem:
domains:add rejects valid domains that contain numeric characters not surrounded by alphabet characters. e.g. 2.example.com
The rejection code was just added in 9a29cc59a8872265a59f3849b8968ea30504519f.

- `dokku version`: 0.6.1

How was dokku installed?: bootstrap.sh

How reproducible: easily

Steps to Reproduce:
1. `dokku domains:add <app_name> 2.example.com`

Actual Results: 2.example.com is invalid. exiting...

Expected Results: domain added

**Comment by michaelshobbs** [comment]
From https://en.m.wikipedia.org/wiki/DNS_label

>The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-'). The original specification of hostnames in RFC 952, mandated that labels could not start with a digit or with a hyphen, and must not end with a hyphen. However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits. No other symbols, punctuation characters, or white space are permitted.

**Comment by josegonzalez** [comment]
> However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits.

**Comment by michaelshobbs** [comment]
Yup added just for reference. Should have said that originally

**Comment by otium** [comment]
`^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$` should handle everything.
