### ISSUE TITLE
[RFC] Log Driver Plugin

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2268]
At the moment, when a user attempts to retrieve logs for an application, we use the `docker logs` command to retrieve logs directly from the container. There are a few issues with this:
- An application deploy will cause a log tail to fail as the `CID` will no longer exist.
- Logs from previous deploys are lost forever
- Logs are currently not shipped externally, so users have to use stuff like [dokku-logspout](https://github.com/michaelshobbs/dokku-logspout) or similar if they want to store the logs offsite.

One possible solution would be to have porcelain around the docker [`log-driver`](https://docs.docker.com/engine/admin/logging/overview/) feature. We could do something similar to the following:

``` shell
dokku logs:options APP
dokku logs:options-add APP [LOG_DRIVER_OPTION...]
dokku logs:options-remove APP [LOG_DRIVER_OPTION...]
dokku logs:report APP
dokku logs:set APP APP LOG_DRIVER_TYPE
```

Dokku could default to the `syslog` driver with defaults to ship logs locally, though users could in theory override this to use whatever driver/options they'd like. This feature would be powered by the `docker-options` plugin.

On the rsyslog side, we would ensure that application logs are tagged with the application name and the `dokku-app` label so that we can properly filter them.

Once implemented, `dokku logs` should instead tail the log file from the system, or optionally we can allow users to tail logs from _either_ the system or the container. If a user has configured a driver, we would disable the `dokku logs` command for that application and direct them towards their shipping method of choice.

> If someone wants to work on this, a good model is the `ps:restart-policy` bit from the `ps` plugin :)

**Comment by piotrkochan** [comment]
+1

**Comment by josegonzalez** [comment]
@piotrkochan a +1 doesn't really push the needle either way here. If you'd like to contribute this change, that would be great.

**Comment by mrname** [comment]
@josegonzalez what drivers would you imagine supporting in the initial implementation?

**Comment by josegonzalez** [comment]
We wouldnt really support a specific driver. If no driver setting is detected for an app, we'd set it to use rsyslog and then start pulling logs from there. Otherwise, users should be free to figure out where they want to ship their logs.

This is just porcelain (log plugin) over plumbing (docker-options plugin).

**Comment by henrik** [comment]
@haywirez I'm in the same situation – still happy with that solution?

**Comment by jpaulomotta** [comment]
I'm also looking for a solution to this.

I have a log intensive app in production that is filling up a 50GB ssd in a week. I've been running ```docker system prune``` on a cronjob every week in order to be able to keep the system running without filling up the entire disk.

I will try @haywirez solution and will report back in case it works.

**Comment by josegonzalez** [comment]
I've jumped back on this. I think instead of doing the above, we're gonna have an integration with [vector](https://vector.dev/) for log shipping. Users will be able to do whatever they want with docker logs as the source, which won't impede the existing container log tailing support.

What will this mean?

- `dokku logs $APP` will still not cross app rebuild boundaries for docker-local
- `dokku logs $APP` will work the same as it currently does for all scheduler plugins
- users can ship logs to an external location without breaking `dokku logs`

I'm still trying to figure out if there is a way to set a global shipper in addition to doing so on a per-app basis, but not sure if that will land in this release. If I do add that, users will be able to support either global, per-app, or even do both at the same time (not sure why you'd want that though).

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by nuzelac** [comment]
If anyone's dealing with large json log files and is trying @haywirez's solution, I had to use different phase to make it work.

`dokku docker-options:add <yourapp> deploy --log-opt max-size=10m --log-opt max-file=1`

(described in https://github.com/dokku/dokku/blob/master/docs/advanced-usage/docker-options.md#about-dokku-phases)

**Comment by josegonzalez** [comment]
Note: Dokku 0.23.x will start capping _all_ container log files to 100m via [this pr](https://github.com/dokku/dokku/pull/4337) (which may end up using docker options instead of the logrotation file, not sure yet).
