### ISSUE TITLE
Multiple Hostnames

### ISSUE THREAD

**Issue by xadh00m** [dokku/dokku#2276]
We have a dokku server and can reach it via two distinct hostnames configured in our DNS server. It seems to be not supported yet to declare two hostnames in dokku. Although this works:
```
dokku domains:set-global "foo bar"
```
It does not create the correct hostnames for apps when calling:
```
dokku domains:disable myApp && dokku domains:enable myApp
```
The global domain is treated as one domain string. This leads to the app hostnames:
```
dokku domains myApp
=====> Global Domain Name
foo bar
=====> myApp Domain Names
myApp.foo bar
```

Is this feature something Dokku should support? AFAIK the relevant functionlity is in `dokku/plugins/enabled/domains/functions`.
Would you be interested in a PR for this? Any hints how this feature should be incorporated and which edge cases need to be considered?

Thanks,
Mirko

**Comment by josegonzalez** [comment]
A few things:

- If you put quotes around strings in bash, bash will treat them as a single string.
- We do not have the ability to set more than one global hostname. That's why the method is called `domains:set-global`, not `domains:add-global`.
  - @michaelshobbs it appears that we can get more than one global hostname via `get_app_domains`, but we never use the function that way. I'm actually not sure where in the code we retrieve all the hostnames...
- If you'd like to set more than one hostname for an application, you can use the `dokku domains:add` command.

**Comment by xadh00m** [comment]
Thank you for the fast reply!

Yes, `dokku domains:add`can achieve that but I would actually like to declare another global domain which applies to all deployed and future apps without setting an extra domain per app.

**Comment by josegonzalez** [comment]
We don't currently support that. If you'd like to contribute a patch to add `domains:add-global` and `domains:set-global` (with tests!), that would be great.

**Comment by xadh00m** [comment]
`domains:set-global`does exist already. Did you mean `domains:remove-global` instead?
Speaking of it: Does it sound more consistent to align the domains global commands with the app domains commands?

E.g.:
```
domains:add-global
domains:remove-global
domains:clear-global
domains:disable-global
domains:enable-global
```
Note: No `domains:set-global` command there for consistency.

Although this looks a bit more consistent it might be hard to achieve e.g. because [`is_global_vhost_enabled`](https://github.com/dokku/dokku/blob/master/plugins/common/functions#L824) is determined implicitly.

**Comment by josegonzalez** [comment]
Yeah I meant remove.

**Comment by xadh00m** [comment]
This pull request adds `domains:add-global`and `domains:remove-global`. It does not (yet) remove `domains:set-global`.

The common function `get_global_vhost` has been renamed to `get_global_vhosts` to reflect the possibility of multiple hosts.

I´m not 100% sure if `is_global_vhost_enabled` works correctly with multiple hosts added though.

**Comment by josegonzalez** [comment]
Closing as there is a PR open.
