### ISSUE TITLE
Missing dokku local command

### ISSUE THREAD

**Issue by guillaumewuip** [dokku/dokku#2280]
Just a general question : is there any plan to implement a `dokku local` command (like `heroku local` does).
For buildpacks apps, `heroku local` can be used, but for Dockerfile deployement we have to run the full `docker` command by hand. And it can be impractical when we have configured `dokku dockker-options build/run` options.

**Comment by michaelshobbs** [comment]
We don't currently have plans to implement this. However, PRs are welcomed.

**Comment by guillaumewuip** [comment]
Ok. Seems a bit complicated to imagine since the `dokku` client command is just a ssh wrapper :/

**Comment by michaelshobbs** [comment]
Though it doesn't have to be *just* an ssh wrapper. I know there are other dokku clients out there that ostensibly do more "stuff".

**Comment by guillaumewuip** [comment]
Indeed you're right @michaelshobbs. I will plan some time to think about it.

**Comment by josegonzalez** [comment]
I think this is a bit out of scope for a few reasons:

- You can run dokku locally via vagrant.
- The "official" client is just an ssh wrapper, and yeah, it would be a bit more work to implement a full dokku run there.
- The goal of dokku is to manage application deployment lifecycles.

If anything, this would be a separate project. If you want to work on one, feel free to and we may consider making it an official project :)

**Comment by guillaumewuip** [comment]
Okey @josegonzalez :)
