### ISSUE TITLE
dokku storage

### ISSUE THREAD

**Issue by rauluranga** [dokku/dokku#2284]
so i'm trying to persist the uploads folder from a wp project using `dokku storage` as the docs says but my folder is always empty.

but found a solution:

**this do not work**
```
$ dokku storage:mount app-name /var/lib/dokku/data/storage:/storage
```
**but this works**
```
$ dokku storage:mount app-name /var/lib/dokku/data/storage:/app/storage
```

you must append the "/app" path to the container directory.!!!

docs for dokku storage need to be updated?? or i'm doing something wrong??

**Comment by josegonzalez** [comment]
Probably worth updating the docs. The second path is relative to the root path, not the application working directory.
