### ISSUE TITLE
plugn should be installed in /usr/bin

### ISSUE THREAD

**Issue by hansmi** [dokku/dokku#2285]
This is a follow-up to #2172. The plugn package should also install its binary in `/usr/bin`.

As of version 0.2.1 the binary is in `/usr/local/bin`:
```
$ dpkg -L plugn | grep /bin/plugn
/usr/local/bin/plugn
```

**Comment by josegonzalez** [comment]
Whenever we get to a release of plugn - which needs to have functional changes, not just packaging - it will be in the "correct" directory. The changes are already applied to deb.mk.
