### ISSUE TITLE
Dynamic build-arg for Dockerfile based build

### ISSUE THREAD

**Issue by lucasm-iRonin** [dokku/dokku#2288]
Hi,
I would like to ask it it's possible to pass dynamic `build_args` to Dockerfile based build?

What I need is to be able to bust the cache for `git pull` command. I've found solution [here](https://github.com/docker/docker/issues/1996#issuecomment-185872769) which requires passing different value for argument on every build. However docku escapes `$()` and backticks which makes it impossible. Are there any other workarounds?

**Comment by josegonzalez** [comment]
Can you explain why you want to do this? What is your intended goal?

**Comment by josegonzalez** [comment]
Actually, I don't think this is appropriate for dokku to provide directly. I would instead say that you should build a plugin that uses the `docker-args-build` hook to set this argument for you. Here is an example you can use in your applications:

```shell
#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

dynamic-build-arg() {
  declare desc="docker args plugin trigger"
  local STDIN=$(cat)
  local output=""

  local output=" --build-arg CACHEBUST=$(date +%s)"
  echo -n "$STDIN$output"
}

dynamic-build-arg "$@"
```

I'll update the plugin-triggers documentation to have this as an example :)

**Comment by lucasm-iRonin** [comment]
@josegonzalez thank you for your answer and snippet. It helped me to create custom plugin.
