### ISSUE TITLE
[RFC] Improve the UI for Dokku Help All

### ISSUE THREAD

**Issue by nahtnam** [dokku/dokku#2293]
Hey!

In my opinion it would be better if the `dokku help --all` looked a lot more like this:
![https://i.imgur.com/KjWIebJ.png](https://i.imgur.com/KjWIebJ.png)

Currently it looks like this:
![https://i.imgur.com/ywbn8rl.png](https://i.imgur.com/ywbn8rl.png)

In my opinion the first image is better because you can better differentiate the top level commands and their sub-commands.

Thanks.

**Comment by arturopuente** [comment]
👍 This would really be a welcome change!

**Comment by josegonzalez** [comment]
I've thought about this for a little and am going to close the issue. This makes it a bit more difficult for automated tooling to consume the entire help output. `dokku help` will give you top-level help output for all plugins, and if you want to get more information for a specific plugin, you can either issue `dokku PLUGIN_NAME:help` for a specific plugin (to get the above) or `dokku help --all` to list *every* command as is.
