### ISSUE TITLE
docs site needs redirects and correct status code

### ISSUE THREAD

**Issue by samuelcolvin** [dokku/dokku#2305]
Currently there are lots of links to the dokku documentation website which go to "page not found". There should surely be redirects from the old page locations to the new pages.

If not redirected they should at least give the correct response code, currently the "page not found" page is returning 200.

**Example:** http://dokku.viewdocs.io/dokku/nginx/ should redirect to http://dokku.viewdocs.io/dokku/configuration/nginx/

**Comment by josegonzalez** [comment]
Fixed!
