### ISSUE TITLE
! [remote rejected] master -> master (pre-receive hook declined) when trying to push a Pelican static blog

### ISSUE THREAD

**Issue by dm-wyncode** [dokku/dokku#2306]
Output of trace "on": https://gist.github.com/dm-wyncode/c67e55786fe21060d5a2944614731291

Description of problem:

I have installed Dokku on a Linode instance.

To test that Dokku functions as expected, I deployed a sample Rails app from https://github.com/heroku/ruby-rails-sample

The Rails app deploys with no problems: http://ruby-rails-sample.zip.thruhere.net/

I then decided to try deploying a Pelican static site as described in this blog: https://launchbylunch.com/posts/2014/Jan/23/blog-tech-stack/

I used this repo to create my own Pelican site: https://github.com/sehrope/pelican-dokku-bare

Output of the following commands

- `uname -a`: Linux zip.thruhere.net 4.5.5-x86_64-linode69 #3 SMP Fri May 20 15:25:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

- `free -m`:
             total       used       free     shared    buffers     cached
Mem:          1999       1608        391         23         32       1276
-/+ buffers/cache:        298       1700
Swap:          511          0        511

- `docker version`: Docker version 1.11.2, build b9f10c9
- `docker -D info`:

Containers: 8
 Running: 2
 Paused: 0
 Stopped: 6
Images: 12
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-8:0-130165-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.847 GB
 Data Space Total: 107.4 GB
 Data Space Available: 20.87 GB
 Metadata Space Used: 3.633 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.5-x86_64-linode69
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: zip.thruhere.net
ID: UQJJ:UUB2:RKJ5:YDKY:UC55:CG2E:K25I:KVQJ:ZL4Y:QXYE:JE7Q:QX6K
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:

herokuish: 0.3.13
buildpacks:
  emberjs.tgz                latest
  buildpack-nginx            v5
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v36
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v90
  heroku-buildpack-php       v102
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v70

- `dokku version`: 0.5.7

- `dokku plugin`:
plugn: dev
  00_dokku-standard    0.5.7 enabled    dokku core standard plugin
  20_events            0.5.7 enabled    dokku core events logging plugin
  apps                 0.5.7 enabled    dokku core apps plugin
  build-env            0.5.7 enabled    dokku core build-env plugin
  certs                0.5.7 enabled    dokku core certificate management plugin
  checks               0.5.7 enabled    dokku core checks plugin
  common               0.5.7 enabled    dokku core common plugin
  config               0.5.7 enabled    dokku core config plugin
  docker-options       0.5.7 enabled    dokku core docker-options plugin
  domains              0.5.7 enabled    dokku core domains plugin
  enter                0.5.7 enabled    dokku core enter plugin
  git                  0.5.7 enabled    dokku core git plugin
  logs                 0.5.7 enabled    dokku core logs plugin
  named-containers     0.5.7 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.7 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.7 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.5.7 enabled    dokku core proxy plugin
  ps                   0.5.7 enabled    dokku core ps plugin
  shell                0.5.7 enabled    dokku core shell plugin
  storage              0.5.7 enabled    dokku core storage plugin
  tags                 0.5.7 enabled    dokku core tags plugin
  tar                  0.5.7 enabled    dokku core tar plugin

- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

- `cat /home/dokku/<app>/nginx.conf` (if applicable):

- Link to the exact repository being deployed (if possible/applicable): https://github.com/sehrope/pelican-dokku-bare

- If a deploy is failing or behaving unexpectedly:
  - Application name: blog
  - The type of application being deployed (node, php, python, ruby, etc.): python Pelican static blog
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.): Linode instance

How was dokku installed?:
 using https://github.com/dokku/dokku/blob/master/bootstrap.sh

How reproducible: so far only with a Pelican static blog. A Ruby Rails app deploys as expected.

Steps to Reproduce:
1. git push dokku master where remote is set appropriately
2.
3.

Actual Results:
master (pre-receive hook declined)

Expected Results:

app deployed as described in this blog post: https://launchbylunch.com/posts/2014/Jan/23/blog-tech-stack/

Additional info: I'm new to Dokku. It's probably something I am not understanding that is different about the Pelican static blog. I tried various things in an app.json file with no success. I tried setting

`dokku config:set blog BUILDPACK_URL=https://github.com/getpelican/heroku-buildpack-pelican`

without any success.

**Comment by josegonzalez** [comment]
The git submodules seem to be failing to be installed. If you remove the piping to `/dev/null` in `/var/lib/dokku/plugins/enabled/git/functions` on [this line](https://github.com/dokku/dokku/blob/master/plugins/git/functions#L31) you should be able to see whats going on.

**Comment by josegonzalez** [comment]
Also that buildpack doesn't work at all. Looks like it's trying to use an [older version of distribute](https://pypi.python.org/packages/source/d/distribute/0.6.49.tar.gz) for some reason.

https://github.com/sehrope/heroku-buildpack-pelican/blob/master/bin/compile#L43

**Comment by dm-wyncode** [comment]
I did the following:

- forked https://github.com/dokku/dokku
- edited in my fork [the line you suggested](https://github.com/dokku/dokku/blob/master/plugins/git/functions#L31) to be [this value](https://github.com/dm-wyncode/dokku/blob/63ef3c24cb2d1085f3ce31913622294989c01aca/plugins/git/functions#L31).
- edited [bootstrap.sh](https://github.com/dm-wyncode/dokku/blob/63ef3c24cb2d1085f3ce31913622294989c01aca/bootstrap.sh#L129) to point to my fork of dokku.
- installed Dokku using [this bootstrap.sh](https://raw.githubusercontent.com/dm-wyncode/dokku/i2306/bootstrap.sh) which installs my fork.
- installed a sample rails app to demonstrate the dokku install works as expected: [sample rails app](http://ruby-rails-sample.zip.thruhere.net/)
- started with a fresh clone of [Pelican blog sample repo](https://github.com/duilio/pelican-octopress-theme)
- cloned [octopress theme](https://github.com/duilio/pelican-octopress-theme) into themes directory in the sample Pelican blog repo
- created some content in sample Pelican blog
- created app "blog" on dokku server: `dokku apps:create blog`
- turned on tracing on dokku server: `dokku trace on`
- set the remote on pelican blog: `git remote add dokku dokku@zip.thruhere.net:blog`
- deployed from local machine: `git push dokku master > deploy.log 2>&1`
- [gist of the output](https://gist.github.com/dm-wyncode/fa8dc4943323b110912d19261278d33d)

The output doesn't seem to have changed.

Could my having cloned a theme into `./themes/` have anything to do with it?

I'm missing something since you were able to deploy it. Did I properly modify the './plugins/git/functions/' file?

Thanks for your help.

**Comment by dm-wyncode** [comment]
I was perusing the dokku/dokku repo and noticed the [a test directory for a python-flask app](https://github.com/dokku/dokku/tree/master/tests/apps/python-flask). It deployed successfully.

I wanted to rule out some sort of Python related issue. (I'm new to Dokku and app deployment in general. I was exposed to Heroku at coding bootcamp 2 months ago.)

Thanks for writing code that is as educational as it is functional!

**Comment by josegonzalez** [comment]
It could be that the ssh command output was not properly sent to stderr, so we didn't catch the actual error. Mind manually running a deploy with trace enabled to see why that command might fail? You could also manually try cloning the repository on that server as the dokku user and running the failing git submodule commands:

```
sudo su - dokku
cd /tmp
git clone /home/dokku/blog /tmp/blog
cd /tmp/blog
git fetch --depth=1 origin refs/tags/dokku/57f51f3660a925749797a1f92cfc427902d80f51
git reset --hard FETCH_HEAD
git submodule update --init --recursive
```

Hopefully that fails with some error message we can take a look at.

**Comment by dm-wyncode** [comment]
`git fetch --depth=1 origin refs/tags/dokku/57f51f3660a925749797a1f92cfc427902d80f51` fails with

> fatal: Couldn't find remote ref refs/tags/dokku/57f51f3660a925749797a1f92cfc427902d80f51

The /home/dokku/blog repo is in an abnormal state. Perhaps because the deploy failed?

`git log` from `/home/dokku/blog` or `/tmp/blog` returns

> fatal: bad default revision 'HEAD'

**Comment by dm-wyncode** [comment]
If you would like to take a look on the Linode instance, send me your id_rsa.pub

The instance will be trashed after I get this solved.

**Comment by josegonzalez** [comment]
```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2xccmkWiO9cvGwvgUwFzCF7lJrsEscfscOxLP7gMDwvI++xOa30873J7843bSV7xokGrf4wEXtbDjelC9ixYcxUiUEXQRsMqwPU6FuFKbio9glgFJt+kJwt3MXgy8dtyo5X8uNoXeEjIoDQQD2wqL0qzKMi5OnA9ch5ToE5yu5MON+6E3YMUdHd6Clo9SUrrV9owREh7H5dISqqce1TeJ2ERX0SeAJ2x7AV3GA+zSHo1E3I/cwuR0G2y+PvcKd+23e4genJh6pd8XzJeLX9UxWFuClzkIiBLcfhdTOC4gmO67JM8XEOXpQ+Lzx9UdAY0rGVw17pNLJ5lJeMPvU2yvQ== jose@mactaku.local
```

**Comment by dm-wyncode** [comment]
The original repo I used is using the Pelican buildpack. That might be the problem.

I found something after `git show f025e3272ead7707f5900f958ee9d643964aafb1`

>  <snip>
>  Author: dm-wyncode <dm.wyncode@gmail.com>

> Date:   Sat Jul 9 11:01:54 2016 -0400
> 
>      Initial commit
> 
> diff --git a/.env b/.env
> new file mode 100644
> index 0000000..36f6ead
> --- /dev/null
> +++ b/.env
> @@ -0,0 +1 @@
> +BUILDPACK_URL=https://github.com/sehrope/heroku-buildpack-pelican

**Comment by dm-wyncode** [comment]
added your key

login with: `ssh dmmmd@zip.thruhere.net`
sudo user pass is: `mgmgms`

**Comment by dm-wyncode** [comment]
[I think this is the problem.](https://github.com/sehrope/pelican-dokku-bare/blob/7a414dace1faf9c0fdf8e369339cdf01e2395dce/.env#L1)

**Comment by josegonzalez** [comment]
No, I don't think that is the problem.

I was able to fix the initial git submodule bit by upgrading that dokku instance to the latest release - 0.6.5. I had to also destroy the blog app since I believe the git work you did may have deleted the remote master ref. Once I did that, a push worked fine (though the aforementioned distribute issue exists).

In general, please run the latest version, we include a ton of bug fixes and features that fix stuff like this. I looked over the commit log and nothing stands out to me. 

I'll apps:destroy the blog now. Let me know if you get past the initial git phase on your next push.

**Comment by dm-wyncode** [comment]
I tried it again. No change.

I tried destroying the blog app and tried it again. Same thing.

:-(

> To dokku@zip.thruhere.net:blog
 ! [remote rejected] master -> master (pre-receive hook declined)

**Comment by josegonzalez** [comment]
Was that the entire output? Do you maybe have a password on your ssh key?

**Comment by dm-wyncode** [comment]
https://gist.github.com/dm-wyncode/e55c676175792bef4178b9ef2b341479

**Comment by josegonzalez** [comment]
I think maybe the system is trying to use your passworded key and failing because it can't get the key for some reason - maybe a failing in your ssh-agent config.

As a test, try deploying [this app](https://github.com/dokku/dokku/tree/master/tests/apps/gitsubmodules) after running the following commands in the fresh app repo:

```
git submodule add https://github.com/heroku/node-js-sample.git node-js-sample
git commit -m "test"
```

If it fails, thats probably it.

I fucking hate git submodules.

**Comment by dm-wyncode** [comment]
Indeed it failed: https://gist.github.com/dm-wyncode/a6d35d32c8e35254a0dec45892f3f1c7

**Comment by dm-wyncode** [comment]
One second. I didn't quite follow the instructions correctly.

**Comment by dm-wyncode** [comment]
It did not fail: https://gist.github.com/dm-wyncode/a6d35d32c8e35254a0dec45892f3f1c7

**Comment by dm-wyncode** [comment]
Since you think it's the passworded key, I will try a new Linode instance with a fresh install of the (current!) dokku and use a key with no password. I will post the results after I do that.

**Comment by dm-wyncode** [comment]
I created a new Linode instance with a current version (0.6.5) of dokku.
I am using ssh key with no password when I push to the dokku server.

Same failure for the Pelican blog: https://gist.github.com/dm-wyncode/2dbfa3b09015a82c2245be58a8cd3494

Flask, Rails, and gitsubmodules succeed where gitsubmodules is [this repo](https://github.com/dm-wyncode/dokku-gitsubmodules-test) that you asked me to create earlier:

- http://ruby-rails-sample.nopwd.thruhere.net/
- http://python-flask.nopwd.thruhere.net/
- http://gitsubmodules.nopwd.thruhere.net/

**Comment by josegonzalez** [comment]
If you're around on IRC/Slack, we might be able to give faster support there. At the moment I'm at a loss as to what is happening. Do you have any special configuration in your `.ssh/config`, or have you pre-configured anything on the server before installing dokku?

**Comment by josegonzalez** [comment]
Oh, can you also try [this](http://dokku.viewdocs.io/dokku/deployment/application-deployment/#deploying-with-private-git-submodules):

```
# on your dokku host
su - dokku
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
ssh -T git@github.com
```

**Comment by dm-wyncode** [comment]
- `su - dokku`
- `ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts`
> # github.com SSH-2.0-libssh-0.7.0
- `ssh -T git@github.com`
> Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
> Permission denied (publickey).

**Comment by josegonzalez** [comment]
You could try adding an ssh key that is attached to a github account to your dokku user - assuming a push failed - and then another deploy.

I'm at a loss as to how this was missed by dozens of previous users...

**Comment by dm-wyncode** [comment]
I added a GitHub authorized id_rsa key to `/home/dokku/.ssh/` so now
`ssh -T git@github.com`

> dokku@nopwd:~/.ssh$ ssh -T git@github.com
> Hi dm-wyncode! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by josegonzalez** [comment]
Cool, try deploying now?

**Comment by dm-wyncode** [comment]
Hmmm. Same thing. Let me destroy and re-create the app and deploy again.

**Comment by dm-wyncode** [comment]
I'll try something else tomorrow. I have made a mess of my ssh keys and ssh config.  I will start fresh with both. (I have two Github accounts and lack of familiarity with .ssh config, etc. I now suspect I had something improperly set in .ssh/config.)

Knowing that dokku needs a key makes me think what you're thinking. I will let you know when I have started with a clean slate.

**Comment by josegonzalez** [comment]
Let me know what you find out. If you're online tomorrow, I'd be happy to debug via chat and figure out how we can better surface these errors to our users :)

**Comment by dm-wyncode** [comment]
Great! Thanks. Slack is easiest since I'm already on it. I would have to set up an IRC client. I haven't used it in a while.

**Comment by josegonzalez** [comment]
http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/ <-- Link so you can get started :)

**Comment by dm-wyncode** [comment]
Thanks. Signing up for Slack now. 👍

**Comment by dm-wyncode** [comment]
I started from scratch this morning:

- one no-password key: `~/.ssh/id_rsa` that is registered with my GitHub account
- no ssh-agents
- installed v0.6.5 of dokku
- copied GitHub registered key to `/home/dokku/.ssh` on the dokku machine
- able to deploy 3 apps
  
  - Ruby on Rails: http://ruby-rails-sample.zip.thruhere.net/
  - Python Flask: http://python-flask.zip.thruhere.net/
  - Nodejs: http://sample-nodejs.zip.thruhere.net/

I attempted to deploy the Pelican static blog. Here is [the output with trace "on"](https://gist.github.com/dm-wyncode/18107e12d0f47d58d30fd22f40c51d8e)

See line 588.

**Comment by josegonzalez** [comment]
@michaelshobbs I'm at a loss here. Thoughts on what could be going down?

**Comment by michaelshobbs** [comment]
@dm-wyncode i'd be happy to take a further look. here is my ssh key
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7ScmhllvMKCnT0Ury5n6hgP9iNLV3KO38NP++15SyWbUqxM3qmJZiwwfJZuVLE5n5qCItRRpahfgbbRiaybszR47FMc9WiKyp8Pk8DuYrCOjj8RV73UKq5gwHYoedAPDIe8PK21W6KRvbQI+zbtt4mRFXGCyKTogZbttoAUDv4OE3jOG8haB0b55nXcdeqxOsjS6A0XFk3BUtRTJI/DwiBmxJk18uMVqZb98GxyxWX2JzRp6hU2cE3onQyvo+pHrf2mOcTVYr3z/htiKlRs2XMg3XkxuBYrGxgqksgeKeCJi7WWsWnYPajtOJOeZONT32rbhD0n3M3d6RArWlAXZR mhobbs@mobius.local
```

**Comment by dm-wyncode** [comment]
Problem solved!

I failed to do the following with the git submodule. (Up until this point I was completely ignorant of them!)

I decided to do some reading about git submodules. I failed to recognized that the submodule had to be initialized and updated. I was simply cloning the theme 'octopress' into the 'themes' directory.

`$ git submodule init`
> Submodule 'themes/octopress' (https://github.com/sehrope/pelican-octopress-theme) registered for path 'themes/octopress'
$ git submodule update
> Cloning into 'themes/octopress'...
> remote: Counting objects: 455, done.
> remote: Total 455 (delta 0), reused 0 (delta 0), pack-reused 455
> Receiving objects: 100% (455/455), 161.88 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (206/206), done.
> Checking connectivity... done.
> Submodule path 'themes/octopress': checked out 'f213d2416c41678274dcab550cf752439ca3269a'

And then it deployed!

**Comment by dm-wyncode** [comment]
I thought I found the solution. I spoke too soon. I am on my MacBook now with git version 2.7. (Before I was on Ubuntu 14.04 with git 1.9. I upgrade to 2.9 and the deploy still didn't work.)

Problem solved!

I failed to do the following with the git submodule. (Up until this point I was completely ignorant of them!)

I decided to do some reading about git submodules. I failed to recognized that the submodule had to be initialized and updated. I was simply cloning the theme 'octopress' into the 'themes' directory and leaving .gitmodules as it was. (I don't know if that matters.)

`$ git submodule init`
> Submodule 'themes/octopress' (https://github.com/sehrope/pelican-octopress-theme) registered for path 'themes/octopress'

`$ git submodule update`

> Cloning into 'themes/octopress'...
> remote: Counting objects: 455, done.
> remote: Total 455 (delta 0), reused 0 (delta 0), pack-reused 455
> Receiving objects: 100% (455/455), 161.88 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (206/206), done.
> Checking connectivity... done.
> Submodule path 'themes/octopress': checked out 'f213d2416c41678274dcab550cf752439ca3269a'

`git push dokku master`

Here is the output: https://gist.github.com/dm-wyncode/e2789ff5e9180dcf567695b54fc81a6f

**Comment by josegonzalez** [comment]
Cool so the submodule issue was solved by fixing the submodules in the repository. The pelican blog tutorial is out of date and that buildpack doesn't work, though you can easily replicate it by using the official python buildpack and using our `pre-deploy` functionality as documented [here](http://dokku.viewdocs.io/dokku/advanced-usage/deployment-tasks/).
