### ISSUE TITLE
Publishing plugin services via nginx instead of exposing them.

### ISSUE THREAD

**Issue by cu12** [dokku/dokku#2309]
We're using Dokku as a core component in our QA system, where users could have their own "slot" and deploy a bunch of applications that play together in one slot and test them.

In these slots we have couple of plugins that are providing services via http such as Fake S3, Thumbor etc. Due to the amount of slots it's not really an option to just expose these services, mostly due to security (too many open ports) reasons, so I was thinking about the alternates.

One alternative I see is to use the built-in NGiNX template functions and besides the `APPs` have `SERVICEs` as well, although as I can see it's not really an option without huge refactoring.

it would look something like this in the sigil template:
```
...
{{ if $.DOKKU_PUBLISHED_SERVICES }}
{{ range $index, $service := $.DOKKU_PUBLISHED_SERVICES | split " " }}
{{ $upstream_port := index ($.DOKKU_SERVICE_UPSTREAM_PORTS | split " ") $index }}
upstream {{ $service }}-{{ $upstream_port }} {
{{ $listeners := index ($.DOKKU_SERVICE_LISTENERS | split " ") $index }}
{{ $listener_list := $listeners | split ":" }}
{{ $listener_ip := index $listener_list 0 }}
{{ $listener_port := index $listener_list 1 }}
  server {{ $listener_ip }}:{{ $upstream_port }};
}
{{ end }}{{ end }}
```

any better ideas?

**Comment by josegonzalez** [comment]
Could you not instead do something like the following:

```shell
include /var/lib/dokku/services/*/*/nginx.conf
```

in `/etc/nginx/conf.d/dokku-load-service-nginx.conf` and have your services fill in an nginx configuration? I'm not sure if the above would expand twice - once for the service type and once for the service name - but if so, it's an elegant solution I'd be okay with building into the core.

**Comment by josegonzalez** [comment]
@cu12 were you able to try out my suggestion?
