### ISSUE TITLE
Disable domains for all published apps by default

### ISSUE THREAD

**Issue by samholmes1337** [dokku/dokku#2310]
It would a be a nice feature to be able to publish primarily internal services without them being publicly routable by default. Something like `dokku domains:disable --global` for example would be a great addition, and then any public services could have their domain names set manually.

Would love to hear your thoughts on this as a feature!

**Comment by josegonzalez** [comment]
I think that's doable. We'd probably want to do the same for `enable`, as well as document this functionality. Do you mind whipping up a pull request for this functionality?

Note: what I currently do is `dokku apps:create`, configure the app, _then_ push it.

**Comment by josegonzalez** [comment]
@samholmes1337 any chance you want to add such functionality in a pull request?

**Comment by samholmes1337** [comment]
Super busy at the mo' but I will at some point soon!

**Comment by josegonzalez** [comment]
This can be performed by doing the following:

- Disable the proxy for an app using `dokku proxy:disable APP`
- Removing any configured global domains using `dokku domains:remove-global GLOBAL.TLD`
- Add iptables rules to block access to any port above `1024` unless explicitly allowed.

All new apps will now be no longer publicly routable via the proxy, and iptables will block the public ports as well.
