### ISSUE TITLE
[RFC] Repository Copy Files Plugin

### ISSUE THREAD

**Issue by aaron-trout** [dokku/dokku#2312]
I think this was sort of mentioned in #2138, but it was brushed over because that wasn't the primary focus of that issue.

Basically, what I'd like is for the contents of `nginx.conf.d/` in my git repository to be copied to the corresponding place in the dokku application directory, so that I don't have to manually scp up files to the dokku server after I've deployed the application. (further, but outside the scope of this issue I believe that _ALL_ application config should live in the git repo, so that essentially the dokku server is a throwaway worker for running the web applications - this would make redeploying / moving between dokku servers very easy)

I know that I could add a sigil file to my root, but copying an 86 line template file and just adding one line (in this case, adding the `client_max_body_size` parameter) seems a bit suboptimal, and I might miss out on exciting changes to the default template when upgrading.

If this is something that could work, I'd be happy to have a bash (pun intended) at making it work but would probably need somebody to point me in the right direction (I had a look at a bunch of files but couldn't work out where this might go in a way that would work for git push / tar file etc).

Thanks!
Aaron

**Comment by michaelshobbs** [comment]
I agree with @josegonzalez. We're going to be moving all dokku config out of the app repo dir in an upcoming release. 

We still need to decide on a common location for dokku config inside of an app repo. I personally am not a fan of cluttering the root of the repo for deployment concerns. Perhaps something like `.dokku/`. Then dokku will copy all those file to the app's config dir on the local host. As part of that change we can also extract a `nginx.include.conf` from the image to support what you're looking for here.

In the meantime, your options are creating a plugin trigger to extract the file and place it in the current `include_dir` or using a custom template that includes your changes.

**Comment by josegonzalez** [comment]
So I took over the [dokku-supply-config](https://github.com/josegonzalez/dokku-supply-config) plugin, which is pretty okay. A few things:

- We'll need to keep track of recently copied files so that they can be deleted next time.
- We'll need to add directory structure copying (to handle the nginx config).
- Need to deprecate all other Dokku-specific file retrieval from Dokku core (DOKKU_SCALE for instance). We can do that in one minor and then remove the functionality in the next major.

Thoughts, @aaron-trout? I know its a bit late, but wanted to let you know that we're working on it :)

**Comment by kevinob11** [comment]
I too want to store some nginx config in my repo. To clarify dokku-supply-config gets us part way there by copying the files in .dokku to the root of the app folder. However the nginx template still needs to be updated to include a specific config filename that would be copied there. Is that correct? Also I vote yes on the approach, seems good to me.

**Comment by josegonzalez** [comment]
Our nginx template [already loads files in `nginx.conf.d`](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L36), so we just need to be sure to copy files into that.

**Comment by mimischi** [comment]
I'm trying to come up with a new project structure, when using Docker during local development and deployment. Deploying an application without a `Dockerfile` in its root directory, will lead to Dokku building the app with a buildpack that was never defined.

The project structure that I'm aiming at is this one:
```
.
├── app
│   ├── [...]
├── docker
│   ├── dokku
│   │   ├── Dockerfile
│   │   ├── [...] (other Dokku specific files, copied by instructions inside `Dockerfile`)
│   └── local
│       ├── Dockerfile-dev
├── docker-compose.yml
└── README.md
```

I can start my local development environment (Django app, PostgreSQL) via `docker-compose up`, while the actual `Dockerfile` resides in `./docker/local/Dockerfile-dev`. Deploying the app to Dokku does not work without a `Dockerfile` in the project root. Using the `post-extract` trigger, I was able to write a [small plugin](https://github.com/mimischi/dokku-dockerfile) to move the production `Dockerfile` from `./docker/dokku/Dockerfile` to the root. It's a very specific case, but also fits this issue.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open (that should handle the original case as well as the case proposed by @mimischi). As it is somewhat complex and potentially unexpected, the behavior is off by default.

**Comment by josegonzalez** [comment]
With recent changes to Dokku works (app.json, monorepo) I don't think this is necessary anymore. We should have better solutions for many/all of the problems in this ticket as of 0.25.0.
