### ISSUE TITLE
Dokku doesn't map on the right port with Dockerfile deployment  

### ISSUE THREAD

**Issue by abellion** [dokku/dokku#2313]
Hey, Dokku seems to let the default port 5000 map even with the "EXPOSE" command in the Dockerfile.
It's happen only with the following steps : 

- ```dokku apps:create my-app```
- ```dokku domains:add my-app sub.domain.com```

Then, from the host, ```git push dokku master```, the port inside the Dockerfile is detected but the "DOKKU_PROXY_PORT_MAP" is not updated. If you take a look at the nginx.conf you'll see that.

A workaround for this issue is to run ```dokku proxy:ports-clear my-app```.

Dokku version : 0.6.4

See you !

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
@abellion friendly *bump* :)

**Comment by abellion** [comment]
- uname -a : Linux scw-d78731 4.5.1-std-1 #1 SMP Mon Apr 18 19:58:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- free -m : 
![image](https://cloud.githubusercontent.com/assets/9916488/17224465/49f5221a-5501-11e6-9051-578f5faa1dc9.png)]

- docker version : 
![image](https://cloud.githubusercontent.com/assets/9916488/17224489/5df9cb9e-5501-11e6-9d4b-4745fc0a7b9e.png)

- sigil -v : 0.4.0

- docker run -ti gliderlabs/herokuish:latest herokuish version : 
![image](https://cloud.githubusercontent.com/assets/9916488/17224548/a00ee528-5501-11e6-9bd4-008f870a5a1b.png)

- dokku version : 0.6.4

- dokku plugin : 
![image](https://cloud.githubusercontent.com/assets/9916488/17224578/cc8be3a8-5501-11e6-8417-02091f633b4e.png)

**Comment by beverku** [comment]
@josegonzalez @abellion is this still needs info status?

**Comment by josegonzalez** [comment]
The documentation around how we handle ports on non-deployed applications was clarified [here](https://github.com/dokku/dokku/commit/b3b1f12e6939c97fc8d9c6a6fe0b6ec485f4f213).
