### ISSUE TITLE
Can't connect host volumes to dokku app

### ISSUE THREAD

**Issue by lolorama** [dokku/dokku#2319]
Description of problem:
I'm trying to add host volumes to docker container. 

Host dirs locations:
/home/dokku/smsvolna/storage/media
/home/dokku/smsvolna/storage/static

Dirs media and static are created under 'su dokku'
drwxrwxr-x  4 dokku dokku 4096 Jul 15 17:40 storage
drwxrwxr-x 2 dokku dokku 4096 Jul 15 17:40 media
drwxrwxr-x 2 dokku dokku 4096 Jul 15 17:40 static

I've tried two ways and both of them doesn't work for me. 

1) file DOCKER_OPTIONS_RUN with content:
-v /home/dokku/smsvolna/storage/media:/app/media
-v /home/dokku/smsvolna/storage/static:/app/static_root

2) dokku docker-options smsvolna run "-v /home/dokku/smsvolna/storage/media:/app/media"
dokku docker-options smsvolna run "-v /home/dokku/smsvolna/storage/media:/app/media"

More then that - for each way static_root dir doesn't apear in the docker container (dokku enter smsvolna web)

---
- dockerfile content:
FROM python:3.5.1
ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
ADD requirements.txt /app/
RUN pip3 install -r requirements.txt
ADD . /app/
RUN chmod 0777 /app/prod-init.sh

- dokku docker-options smsvolna:
Build options:
    --link dokku.postgres.smsvolna-db:dokku-postgres-smsvolna-db
    --link dokku.redis.smsvolna-db:dokku-redis-smsvolna-db
Deploy options:
    --link dokku.postgres.smsvolna-db:dokku-postgres-smsvolna-db
    --link dokku.redis.smsvolna-db:dokku-redis-smsvolna-db
Run options:
    --link dokku.postgres.smsvolna-db:dokku-postgres-smsvolna-db
    --link dokku.redis.smsvolna-db:dokku-redis-smsvolna-db
    -v /home/dokku/smsvolna/storage/media/:/app/media/
    -v /home/dokku/smsvolna/storage/static/:/app/static_root/

Environment details (AWS, VirtualBox, physical, etc.):
VPS

How was dokku installed?:
bootstrap.sh

How reproducible:
I have another dokku app with exactly the same settings and dockerfile (except volumes dirs)  in which host volumes works correctly. I'm totally stuck with this issue and need advice to move on!

---

Output of the following commands

- `uname -a`:
Linux vm105925.local 3.16.0-45-generic #60~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
                    total       used       free     shared    buffers     cached
Mem:          2024       1887        136         41        171        216
-/+ buffers/cache:       1499        524
Swap:           29         29          0
- `docker version`:
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

- `docker -D info`:
root@vm105925:/home/dokku/smsvolna/storage# docker -D info
Containers: 12
 Running: 9
 Paused: 0
 Stopped: 3
Images: 34
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 115
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-45-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 1.977 GiB
Name: vm105925.local
ID: W44Z:QPS5:KHRF:3E3E:3264:KFMM:IB3B:G36P:5GM4:ILZC:ZVPT:QWC7
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
- `sigil -v`:
0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
  'heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v89
  heroku-buildpack-php       v100
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v67
  buildpack-nginx            v5'
- `dokku version`:
0.5.5
- `dokku plugin`:
  00_dokku-standard    0.5.5 enabled    dokku core standard plugin
  20_events            0.5.5 enabled    dokku core events logging plugin
  apps                 0.5.5 enabled    dokku core apps plugin
  build-env            0.5.5 enabled    dokku core build-env plugin
  certs                0.5.5 enabled    dokku core certificate management plugin
  checks               0.5.5 enabled    dokku core checks plugin
  common               0.5.5 enabled    dokku core common plugin
  config               0.5.5 enabled    dokku core config plugin
  docker-options       0.5.5 enabled    dokku core docker-options plugin
  domains              0.5.5 enabled    dokku core domains plugin
  enter                0.5.5 enabled    dokku core enter plugin
  git                  0.5.5 enabled    dokku core git plugin
  logs                 0.5.5 enabled    dokku core logs plugin
  named-containers     0.5.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.5 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.5.5 enabled    dokku core proxy plugin
  ps                   0.5.5 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  require              0.1.0 enabled    dokku plugin to setup all the requirement for your app on push
  shell                0.5.5 enabled    dokku core shell plugin
  storage              0.5.5 enabled    dokku core storage plugin
  tags                 0.5.5 enabled    dokku core tags plugin
  tar                  0.5.5 enabled    dokku core tar plugin

**Comment by lolorama** [comment]
Here is "dokku deploy app" log:

https://gist.github.com/lolorama/56d211a415109acfae1ce9ee49b630f6

**Comment by lolorama** [comment]
Please close this issue.

I have had to add volumes on "deploy" stage as well as "run".

**Comment by josegonzalez** [comment]
You should upgrade your dokku installation and use the official persistent storage plugin that is built into the core instead.
