### ISSUE TITLE
NOPASSWD sudo user has to be in sudo group to execute dokku

### ISSUE THREAD

**Issue by Fei-Guang** [dokku/dokku#2320]
Description of problem:
user is a  NOPASSWD  sudo  user , but can't execute dokku.
ano@execd2:~$ dokku
[sudo] password for ano:
Sorry, user ano is not allowed to execute '/usr/bin/dokku' as dokku on execd2.local.

ano@execd2:~$ id
uid=1000(ano) gid=1000(ano) groups=1000(ano),0(root),999(docker)

Output of the following commands

- `uname -a`:
ano@execd2:~$ uname -a
Linux execd2.local 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- `free -m`:
- `docker version`:
ano@execd2:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
- `docker -D info`:

ano@execd2:~$ docker -D info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: execd2.local
ID: T6EU:Y3JF:ETWK:XTJS:NK2U:SL24:UZLN:BO7G:XYGK:ENOW:Z73U:YAFE
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

- `sigil -v`:
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
- `dokku version`:

- `dokku plugin`:
- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.):

How was dokku installed?:

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Additional info:

**Comment by Fei-Guang** [comment]
the dokku runs after user is added to sudo group

ano@execd2:~$ id
uid=1000(ano) gid=1000(ano) groups=1000(ano),0(root),27(sudo),999(docker)

**Comment by u2mejc** [comment]
Hi @Fei-Guang , sorry to hear you're having trouble. The issue you're having isn't directly related to dokku, but how `/etc/sudoers` is setup on your system.

Your user `ano` will need to have the ability to execute not just `/usr/bin/dokku`, but also `sudo -u dokku`. The different results you're seeing above is you from adding the user to a group called "sudo", this group probably has additional permissions then just NOPASSWD.

References:
https://www.sudo.ws/man/sudoers.man.html

If you're comfortable, post your sudoer file in a gist and I'll take a quick peak at it.

**Comment by josegonzalez** [comment]
Closing. The issue here isn't strictly dokku related, but how you provisioned your server. We require the sudoers change to ensure that only the proper users have access to dokku/docker, and as such will not change our security model.

**Comment by joshco** [comment]
FYI, i wanted to add a user so they can run dokku, but not to other general tasks like sudo bash, sudo crontab etc.  To make that work, I put this rule in /etc/sudoers.d/dokku-users

> %dokku ALL=(ALL:ALL) NOPASSWD:SETENV: /usr/bin/dokku

**Comment by josegonzalez** [comment]
@joshco Can you make a pr with that to the documentation? Thats more discoverable than a random issue.

**Comment by joshco** [comment]
sure thing buddy. what place in the docs would you like me to put it?

**Comment by josegonzalez** [comment]
Probably here: http://dokku.viewdocs.io/dokku/getting-started/advanced-installation/

**Comment by joshco** [comment]
ok, working on it.

**Comment by joshco** [comment]
done.  #2639
