### ISSUE TITLE
Containerize nginx?

### ISSUE THREAD

**Issue by cweagans** [dokku/dokku#2323]
Expected:
- nginx just runs in a container
- configuration is updated via something like docker-gen

Actual:
- nginx is running outside of Docker with what I assume is manually (well, automated via script, but still a separate thing) updated configuration

Any reason not to just run Nginx in a container and bind to port 80 and 443?

**Comment by josegonzalez** [comment]
Time and complexity. Currently we run dokku and all it's components on the host, so any stab at moving to a container would probably be better served working on [this issue](https://github.com/dokku/dokku/issues/1076).
