### ISSUE TITLE
VHOST doesn't work as expected

### ISSUE THREAD

**Issue by vladfaust** [dokku/dokku#2324]
**Issue:**
`<appname>.domain.tld` returns **This site can’t be reached** error. `domain.tld` responds with the last app deployed.

**How to reproduce:**
Just grab a fresh Digital Ocean droplet with Ubuntu 14.04 and Dokku 0.6.5 in it, go to `domain.tld` and enable virtual hostname for apps. Then deploy the first app & click it's url in terminal. Do the same with the second deployed app.

The only DNS record of `domain.tld` is A pointing to the droplet's IP.

**Comment by josegonzalez** [comment]
If you don't set a DNS record for each app or a wildcard DNS entry, your browser won't be able to resolve the dns, so yes, you'll get that error.
