### ISSUE TITLE
What is the correct way to install additional libraries if they are not in existing plugins.

### ISSUE THREAD

**Issue by EJIqpEP** [dokku/dokku#2327]
Hello guys. I'm trying to install ffmpeg library after container was deployed. As I understand writing plugin for this is not the best solution as it will be applied to all containers.
Should I write it as shell script on postinstall?
The commands that I need to run are
```bash
apt-get update 
apt-get install software-properties-common 
add-apt-repository ppa:mc3man/trusty-media 
apt-get update 
apt-get dist-upgrade 
apt-get install ffmpeg
```

**Comment by josegonzalez** [comment]
We recommend using the [dokku-apt](https://github.com/F4-Group/dokku-apt) plugin to handle that case. If you need more than what said plugin offers, we recommend using [Dockerfile-based deployment](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/).
