### ISSUE TITLE
POODLE vulnerability

### ISSUE THREAD

**Issue by brandoncc** [dokku/dokku#2339]
Would it be okay for me to submit a PR disabling SSLv3? I made [this](https://gitlab.com/dokku-alt/dokku-alt/commit/eca3b1da18649931ef32bcc768467be7d2e45536#diff-0) same change in my local template and it works well, SSL Labs is not reporting the vulnerability anymore. It seems like this is an important thing to fix. The only remaining issue as reported by SSL Labs is "The server does not support Forward Secrecy with the reference browsers. Grade reduced to A-." It was originally a C until I disabled SSLv3.

**Comment by josegonzalez** [comment]
Go for it.
