### ISSUE TITLE
dokku ssh-keys:list output is useless

### ISSUE THREAD

**Issue by IlyaSemenov** [dokku/dokku#2343]
The current output of `dokku ssh-keys:list` is completely useless:

```console
root@dokku:~# dokku ssh-keys:list
 SSHCOMMAND_ALLOWED_KEYS: no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding
 SSHCOMMAND_ALLOWED_KEYS: no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding
```

It should have at least include the key names for `dokku ssh-keys:remove`, and perhaps the fingerprints.

The relevant info below:

```console
root@dokku:~# cat /home/dokku/.ssh/authorized_keys
command="FINGERPRINT=SHA256:y/lCsvs2fCWjcYc0whZFYQ3UX/OO2qv+n6wE7D9dCeI NAME=\"admin\" `cat /home/dokku/.sshcommand` $SSH_ORIGINAL_COMMAND",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1F98keUFBulWE04RO2+wv3bXASs3TeBXZwG7l4/DKAGc8Qx+U0wb8hZNRtPo2cZP2NRBnVRe6hYEHhr++ocDkPjWY1vggJu/nhubqVELVg+gblpC3rYJur6c4uoTUx/Ea1JzHZ9CKhQJRUj7t6KDfDYv8CM7mgS71QdL/YifTjDeIqXiaSRnb0Q2HkuKQQ5yxT0TLwN3chp4WfVqYcbWvnjUk23IfKAos/1e7F3DOMvO+gU8OYyV17iXVB2Bmb5YZodEYeomprL+yfeh5Qa8Kswo+fYRKJ+9SLYVAVNGxbpktUyv+DlLxuRD4AsGDWKuDqk5U3O6cK3CNQWYUGSVew== semenov
command="FINGERPRINT=SHA256:sxDqS3wXgZ7RUfzHKLbJElMPwqEg14op/bTk/qqmiwI NAME=\"gitlab\" `cat /home/dokku/.sshcommand` $SSH_ORIGINAL_COMMAND",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4Voz9muoVNAqm31Ce2KCb+UOg1DheZSUYFbiQV/mrziTRJKLmQQb2cjj7xpk3A7rZ4fXOCpdwAX2JDtPO/KHAGAXf0EWEe8zOwqeTAB2dOIFRSlkb8lIUZFq0NvEBRrYx5oM04T6QLJWzN8TTdqSkFdW7M5L0zSsJSehNlIIt+/5fOtPWoYI1RVB+AbJ3YHhOiizETZRB1RHkpKWwqlM/ZKVUl55mTJqAy+2+v4Wdgrz/RncKWyVNRxqC2JCbMoXb7eJfwvfH/1x+QZ/K4GkkhL7/YJ501RA1hgXHFYpZjr/Fxu2+BJ9/WWbDvCsF3j8Chwfkqnx91ojr70pV8U+f semenov@daedra.intra.inetss.com
root@dokku:~# uname -a
Linux dokku 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@dokku:~# dokku version
0.7.0
root@dokku:~# dokku plugin | grep ssh-keys
  ssh-keys             0.6.4 enabled    dokku core ssh-keys plugin
root@dokku:~# dpkg -l | grep dokku
ii  dokku                              0.7.0                           amd64        Docker-powered PaaS that helps build and manage the lifecycle of applications
root@dokku:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

You can check `dokku trace on` output [in this gist](https://gist.github.com/IlyaSemenov/6870737da02f245aab68a32941c54cd6).

**Comment by michaelshobbs** [comment]
Thanks for the feedback. Would you like to put a PR together to make this output more useful?

**Comment by IlyaSemenov** [comment]
I probably could, actually.

**Comment by josegonzalez** [comment]
My output for that command includes more metadata, so I wonder if sshcommand isn't parsing your file correctly.

Can you check the version of sshcommand and also gist /home/dokku/.ssh/authorized_keys?

**Comment by IlyaSemenov** [comment]
@josegonzalez I included the contents of `authorized_keys` in the initial report.

sshcommand is version 0.5.0 (at least, that's whats `dpkg -l | grep sshcommand` says).

**Comment by pascalw** [comment]
I have the same issue as @IlyaSemenov. Also sshcommand 0.5.0.

It indeed looks like a parsing bug in sshcommand, though my case is slightly different. In my `authorized_keys` the `NAME` value is not quoted (my keys were added earlier probably on Dokku 0.4.x) and [this](https://github.com/dokku/sshcommand/blob/master/sshcommand#L175-L176) piece of code doesn't seem to handle that.

In @IlyaSemenov's case the fingerprint looks weird, at least it's not what sshcommand expects (`[a-f0-9]{2}(:[a-f0-9]{2}){15}`). Given that @IlyaSemenov is on Ubuntu 16.04 I would guess that `ssh-keygen` on 16.04 uses a different kind of fingerprints? In any case the parsing in sshcommand could be made a bit more lenient, it could match any `FINGERPRINT=\([^ ]*\)` for example.

**Comment by IlyaSemenov** [comment]
@pascalw Can you please paste the contents of your `authorized_keys` and I'll make sure that the PR works with it as well?

**Comment by pascalw** [comment]
@IlyaSemenov I'll add it to the issue on sshcommand
