### ISSUE TITLE
Unable to activate slowlog - php-fpm: Permission denied

### ISSUE THREAD

**Issue by internetstyle** [dokku/dokku#2344]
In my fpm_custom.conf:

```
request_slowlog_timeout = 5s
slowlog = /var/log/www.log.slow
``` 
(I try change permissions to 777, owner... but not work)

Error in deploy:

```
[02-Aug-2016 13:49:21] ERROR: Unable to create or open slowlog(/var/log/www.log.slow): Permission denied (13)
[02-Aug-2016 13:49:21] ERROR: failed to post process the configuration
[02-Aug-2016 13:49:21] ERROR: FPM initialization failed
```

I think it's a simple thing, someone can help me?

**Comment by michaelshobbs** [comment]
Can you include ​*all*​ of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by internetstyle** [comment]
I found the solution. I just changed to:

`slowlog = www.log.slow `

and fix my problem. The slowlog file created inside container in folder:

` ./heroku/php`

Thanks.

**Comment by leiting6** [comment]
Please modify of slowlog dir:
slowlog = var/log/www.log.slow

**Comment by josegonzalez** [comment]
@leiting6 We do not manage the PHP buildpack, so we cannot make that change.

Please also do not comment on 2 year old github issues, it notifies folks who may no longer be using this project.
