### ISSUE TITLE
git commit and git fetch i.e. Wordpress live code updates ? 

### ISSUE THREAD

**Issue by niccolox** [dokku/dokku#2346]
hi

can you folks confirm that the way to deal with Wordpress style live site updates - Wordpress core updates, new themes, new plugins - running inside a Dokku app container - is to mount the folders and commit to git from there and then make this a second remote and fetch into the local / dev repo ? 

in other words, Dokku seems to have a git push model and Dokku doesn't seem to allow git commit inside a live container and then git fetch from a live container into a local repo

am thinking about some kind of dev > test > live or blue > green workflow and the Dokku only handles git push model

from my searching so far, it seems I would need to create a git remote for the mounted plugin, theme, etc folders and then commit and pull into the dev git repo ? 

I guess this might be a neat plugin or some kind of contrib

thanks

**Comment by michaelshobbs** [comment]
If I understand the flow correctly, it doesn't work because there is no git repository inside of the running container. You could definitely make a dokku plugin to automate this.

**Comment by niccolox** [comment]
thanks for the quick response

I've noticed a trend towards live updates of updates, Wordpress, Gitlab, Discourse... they all handle it differently and its always a risky thing to do, but its there... 

I was just poking around inside /home/dokku/wordpress2 and also the mounted folders and its not quite right

not a simple git repo

```
ls -alh /home/dokku/wordpress2
total 88K
drwxr-xr-x  8 dokku dokku 4.0K Jul 31 20:56 .
drwxr-xr-x 14 dokku dokku 4.0K Jul 31 20:14 ..
drwxrwxr-x  2 dokku dokku 4.0K Jul  7 12:25 branches
drwxrwxr-x  3 32767 32767 4.0K Jul  7 12:26 cache
-rw-rw-r--  1 dokku dokku   66 Jul  7 12:25 config
-rw-rw-r--  1 dokku dokku   65 Jul 31 20:56 CONTAINER.web.1
-rw-rw-r--  1 dokku dokku   73 Jul  7 12:25 description
-rw-r--r--  1 dokku dokku   53 Jul  7 13:06 DOCKER_OPTIONS_BUILD
-rw-r--r--  1 dokku dokku  261 Jul 31 20:14 DOCKER_OPTIONS_DEPLOY
-rw-r--r--  1 dokku dokku  291 Jul  7 14:32 DOCKER_OPTIONS_RUN
-rw-rw-r--  1 dokku dokku    6 Jul  7 12:26 DOKKU_SCALE
-rw-------  1 dokku dokku  227 Jul  7 13:06 ENV
-rw-rw-r--  1 dokku dokku   23 Jul  7 12:25 HEAD
drwxrwxr-x  2 dokku dokku 4.0K Jul  7 12:25 hooks
drwxrwxr-x  2 dokku dokku 4.0K Jul  7 12:25 info
-rw-rw-r--  1 dokku dokku   12 Jul 31 20:56 IP.web.1
-rw-------  1 dokku dokku 1.2K Jul 31 20:56 nginx.conf
drwxrwxr-x 77 dokku dokku 4.0K Jul 31 20:56 objects
-rw-rw-r--  1 dokku dokku    5 Jul 31 20:56 PORT.web.1
drwxrwxr-x  4 dokku dokku 4.0K Jul  7 12:25 refs
-rw-rw-r--  1 dokku dokku  229 Jul 31 20:56 URLS
-rw-rw-r--  1 dokku dokku  119 Jul 31 20:46 VHOST
```

mounted persistent folder

```
ls -alh /opt/wordpress2/wp-content/
total 20K
drwxr-xr-x  5 root  root  4.0K Jul  7 13:21 .
drwxr-xr-x  3 root  root  4.0K Jul  7 13:21 ..
drwxr-xr-x  8 32767 32767 4.0K Jul 31 20:04 plugins
drwxr-xr-x 15 32767 32767 4.0K Aug  2 01:16 themes
drwxr-xr-x  4 32767 32767 4.0K Jul 31 21:19 uploads
```


I would need to mount the entire app as a persistent folder I think and create it as a remote, I guess I should be looking around for plugins around git and persistent folders 

I'll kludge this manually for a bit and see what comes out in the wash

may end up just bypassing this for the present and working locally for dev

although, I noticed some container based cloud hosters of Wordpress have a dev>test>live workflow and allow commits after live updates ... 

I suppose rapid collaboration between developers and clients is the use case

another option would be to rsync back the persistent folder


you can close or leave open, I'll add some bits and pieces as I progress


thanks

**Comment by michaelshobbs** [comment]
To clarify, `/home/dokku/APP` is a git repo in the server format (not the working space format). I was referring to `/app` inside of the running app container not being a git repo.

My thinking on a plugin was something that would maintain a local git clone of wordpress and give you an easy interface into updating that clone and then pushing into dokku.

**Comment by niccolox** [comment]
actually, thinking about this more, I suspect a better way would be to mount the entire app as persistent and then create it as a git repo and push it to a gitlab/github repo

this git repo would be the upstream for dev

would be interested to hear from other dokku wordpress people out there (yes, I know this isn't 12 factor etc, this is not how its designed to be used)

but, I've noticed Pantheon for instance allowing all sorts of extensions from 12 factor

**Comment by niccolox** [comment]
one more idea; this seems to be more of a DEV mode for Dokku as opposed to the more stable PRODUCTION or LIVE mode which is based on git push

in Pantheon on DEV, I have in the past done rapid dev of Wordpress sites, doing live updates of themes and plugins and then commited the code on the server 

anyways, probably a distraction and un-needed

**Comment by josegonzalez** [comment]
If you want to mount a directory into the dokku app, you can do so using our official [persistent-storage plugin](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/). You could also automate pushing *just* the template using a new ssh user - maybe something like "theme" - and [sshcommand](https://github.com/dokku/sshcommand) to customize the command that occurs on push.

Alternatively, you could drop sshcommand and use [gitreceived](https://github.com/progrium/gitreceive) to run whatever script you wanted. For instance, your script could simply update the theme in the mounted persistent storage, so you'd have git push for both the theme *and* the wordpress app.

Anyhow, this is outside of the scope of dokku, but I think the above should give you a good idea on getting started. Good luck! :)

**Comment by niccolox** [comment]
devstep has some interesting ideas https://github.com/fgrehm/devstep

not quite exactly relevant

**Comment by niccolox** [comment]
thanks @josegonzalez @michaelshobbs 

interesting entry point into hacking dokku

cheers for now

and great to see Dokku as such a sophisticated paas

**Comment by niccolox** [comment]
@michaelshobbs 

> My thinking on a plugin was something that would maintain a local git clone of wordpress and give you an easy interface into updating that clone and then pushing into dokku.

do you mean a plugin that would clone the /app folder ? 

second question, will dokku break if I make the /app folder a git repo? (I can test this myself, though I expect it might bork the app)

**Comment by michaelshobbs** [comment]
No. This would manage a cloned wordpress repo outside of the container for the sole purposes of pushing into dokku in order to create the running app container.

**Comment by niccolox** [comment]
@michaelshobbs ok, I cant quite visualize this right now, hopefully with more dokku experience it will come to me

since its non-core dokku, and there maybe 2 or 3 obvious workarounds I'll leave the plugins option for now

perhaps someone from the dokku expanded universe might contribute some thoughts

another workaround was sshfs into a persistent folder and hack inside the app directly and then use that to push to a github upstream

lots of possibilities
