### ISSUE TITLE
SSL nginx.conf template

### ISSUE THREAD

**Issue by internetstyle** [dokku/dokku#2349]
Hi,

Before updating dokku I had two template files, and in deploy was identified the right to use:

```
ngix.conf.template
ngix.ssl.conf.template
```

The new template has changed to:

`ngix.conf.sigil`

However SSL template (ngix.ssl.conf.sigil) no more automatically recognized. 

Why?

**Comment by josegonzalez** [comment]
We no longer have two different templates in dokku for generating nginx configuration, and now use sigil - a go-template based template engine - to generate config files for nginx. Please see our [migration docs](http://dokku.viewdocs.io/dokku/appendices/0.5.0-migration-guide/) for more information.

**Comment by internetstyle** [comment]
Thanks.

My conf now needs a some like:

`{{ if .SSL_INUSE }}`
SSL configuration.
`{{ else }}`
No SSL configuration.
`{{ end }}`

Correct?

**Comment by josegonzalez** [comment]
More or less. Here is our [current template](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil).
