### ISSUE TITLE
dokku postgres container has disappeared after docker stop command

### ISSUE THREAD

**Issue by lolorama** [dokku/dokku#2350]
Here is my commands history:

  531  docker ps
  532  docker im
  533  docker images
  **534  docker stop dokku.redis.gmbay-db**
  **535  docker stop dokku.postgres.gmbay-db**
  536  docker ps
  537  dokku deploy gmbay
  538  dokku gmbay logs
  539  dokku logs gmbay
  540  mc
  541  dokku logs gmbay
  542  dokku deploy gmbay
  543  htop
  544  'docker run --help
  545  docker run --help
  546  mc
  547  dokku redis help
  548  dokku help
  549  dokku redis:start gmbay-db
  550  dokku redis:list
  551  dokku redis:restart gmbay-db
  552  dokku ps:restart gmbay
  553  mc
  554  dokku ps:restart gmbay
  555  ls
  556  dokku redis:logs gmbay-db
  557  docker ps
  558  docker images
  559  docker
  560  history

Now I can't find containers dokku.redis.gmbay-db (and  dokku.postgres.gmbay-db) in "docker ps" or "docker images"

What should I do?

```
root@vm105925:/home/dokku/gmbay# dokku postgres:start gmbay-db
-----> Starting container
       No container exists for gmbay-db
```

```
root@vm105925:/home/dokku/gmbay# dokku redis:list
Error: No such image or container: dokku.redis.gmbay-db
Error: No such image or container: b5ace8b020eccf50ed077f0a404b114a255533400c716e60ac5b4b4e6e4a5f05
Error: No such image or container: b5ace8b020eccf50ed077f0a404b114a255533400c716e60ac5b4b4e6e4a5f05
Error: No such image or container: b5ace8b020eccf50ed077f0a404b114a255533400c716e60ac5b4b4e6e4a5f05
Error: No such image or container: b5ace8b020eccf50ed077f0a404b114a255533400c716e60ac5b4b4e6e4a5f05
Error: No such image or container: b5ace8b020eccf50ed077f0a404b114a255533400c716e60ac5b4b4e6e4a5f05
NAME         VERSION      STATUS   EXPOSED PORTS  LINKS
cpatrack_db  redis:3.0.7  running  -              cpatrack
gmbay-db     stopped      -        gmbay gmbay2
smsvolna-db  redis:3.0.7  running  -              smsvolna
```

**Comment by josegonzalez** [comment]
Upgrade the plugins and try starting them again. We create a new container if one doesn't exist.

**Comment by lolorama** [comment]
Thanks. I have had restored vps from snapshot already. Please close this issue.

**Comment by vidurangaw** [comment]
Hi
This happened to me too. Unfortunately, I don't have a snapshot. Is there a way to recover the data?

Thanks

**Comment by cooperaj** [comment]
Theres a chance the data will be in a docker local volume `docker volume ls` but you'll have to have a rummage to see and figure out recovery options from there.

**Comment by vidurangaw** [comment]
Thanks for your reply. It's not there as well :( I checked

BTW, did you ever find out the reason for that? Only thing I did was stopping the containers. But somehow it has also removed them

**Comment by josegonzalez** [comment]
As mentioned in my comment, all official services can have their containers restarted by running `dokku SERVICE:start SERVICE_NAME`. Data for official datastore plugins isn't stored in docker volumes but on the disk itself.

Also, please don't comment on 3 year old closed issues. It notifies folks who may no longer be using the project/unable to give you an answer.

If you are still having issues with a particular plugin that isn't shipped with the core, please open them in the repository for that plugin.
