### ISSUE TITLE
Question: Git revision in postdeploy hook

### ISSUE THREAD

**Issue by mattberther** [dokku/dokku#2351]
Is it possible to access the git revision in a postdeploy hook? Currently, Im trying this, but am receiving an error (its not a .git repository).

```
{
  "scripts": {
    "dokku": {
      "postdeploy": "curl https://tracker/deploy -F revision=`git log -n 1 --pretty=format:\"%H\"`"
    }
  }
}
```

It'd be outstanding if this was available via ENV somehow. :)

**Comment by michaelshobbs** [comment]
This might be relevant: https://github.com/cjblomqvist/dokku-git-rev

**Comment by mattberther** [comment]
Thanks @michaelshobbs - I might be missing something. This appears to set $GIT_REV in the app container. To notify the deployment tracker, I need to know the $GIT_REV during the build process.

**Comment by michaelshobbs** [comment]
My thinking was the following:

- You would need to extract `$GIT_REV` from the app container environment or inspect how that plugin does it. 
- Then you could send that value to your endpoint.

**Comment by mattberther** [comment]
@michaelshobbs thank you. this was my thinking as well. Ive tried running various forms of enabling DOKKU_TRACE to see the output of the plugin as it appears as thought it writes /app/.dokku-git-rev in a receive-app hook. However, I never see the file get generated.

DOKKU_TRACE dokku ps:rebuild <app> doesn't seem to show the plugin trace statements even though its listed as enabled.

```
± |master ✗| → dokku plugin 
plugn: dev
  00_dokku-standard    0.7.0 enabled    dokku core standard plugin
  20_events            0.7.0 enabled    dokku core events logging plugin
  apps                 0.7.0 enabled    dokku core apps plugin
  build-env            0.7.0 enabled    dokku core build-env plugin
  certs                0.7.0 enabled    dokku core certificate management plugin
  checks               0.7.0 enabled    dokku core checks plugin
  common               0.7.0 enabled    dokku core common plugin
  config               0.7.0 enabled    dokku core config plugin
  docker-options       0.7.0 enabled    dokku core docker-options plugin
  domains              0.7.0 enabled    dokku core domains plugin
  enter                0.7.0 enabled    dokku core enter plugin
  git                  0.7.0 enabled    dokku core git plugin
  git-rev              1.0.0 enabled    adds the current git hash as an environment variable
  logs                 0.7.0 enabled    dokku core logs plugin
 ....
```

Do you know if there is something else I need to do to activate the plugin for the app?

Thanks again for your help with this.

**Comment by josegonzalez** [comment]
It only works on the `receive-app` call as shown [here](https://github.com/cjblomqvist/dokku-git-rev/blob/master/receive-app#L16).

**Comment by mattberther** [comment]
Sorry for all the runaround on this -- turns out this works beautifully, so long as Im not using a Dockerfile deployment. The plugin works out of the box to provide $GIT_REV to my postdeploy app.json hook when running with a buildpack. 

Im not sure what the difference is between a dockerfile vs buildpack deployment. Regardless, I can live with a buildpack deployment for now. :)

**Comment by josegonzalez** [comment]
@mattberther do you have a `Dockerfile` you can gist to confirm that the app.json hook *doesn't* trigger? It should, just that if you customized your WORKDIR, things may not occur as you expect them to.

**Comment by mattberther** [comment]
Sorry -- the app.json does trigger. The problem was that the $GIT_REV variable from the plugin (https://github.com/cjblomqvist/dokku-git-rev) wasn't populated in the postdeploy from the app.json.

`Dockerfile:`
```
FROM python:2.7

ADD . /app
WORKDIR /app

RUN pip install -r requirements.txt
```

`app.json`
```
{
  "scripts" : {
    "dokku": {
      "postdeploy": "curl https://api.rollbar.com/api/1/deploy/ -F access_token=$ROLLBAR_ACCESS_TOKEN -F environment=$PY_ENV -F revision=$GIT_REV"
    }
  }
}
```

When running with the buildpack, the $GIT_REV variable is populated.
