### ISSUE TITLE
[RFC] Create `report` subcommand for all plugins

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2356]
It would be cool if we could have commands such as:
- [x] apps:report
- [x] certs:report
- [x] checks:report
- [x] docker-options:report
- [x] domains:report
- [ ] ~~nginx:report~~
- [x] proxy:report
- [x] ps:report
- [x] storage:report

This could help fill in a command like `dokku report APP` and allow users to see debug information for their entire system as well as an app that is not behaving well.

Thoughts? Would be useful because in many cases, we might not need to see a stacktrace to diagnose a problem, but all the reporting information for various bits of dokku would certainly help. Could also be useful for those diagnosing issues in their own applications.

**Comment by mbtamuli** [comment]
I would like to work on this.  Could you please give example of what would `apps:report` or `ps:report` contain so that I can start with that.

**Comment by josegonzalez** [comment]
Heh oops, totally missed your comment.

`apps:report` would have output like the following:


```shell
=====> App Information
       App dir:          /var/lib/dokku/services/mysql/playground/config
       Linked Services:
       Git Sha:       -
       Status:                  running
```

Something like that. We could add extra data as time goes on for anything specific to the `app` plugin (ditto for the rest).

**Comment by josegonzalez** [comment]
Note: this can be worked on plugin by plugin, no need to do all of them at once. If anyone would like sample info we want for each plugin, feel free to comment and say you're taking that specific plugin :)

**Comment by mbtamuli** [comment]
I will start with the apps plugin. (`apps:report`)

**Comment by josegonzalez** [comment]
`ps:report` output. I think each process that is "scaled" should have an entry here as to whether it is started/stopped/etc. Not sure if the way I have for representing container IDs is necessarily the best one, but open to suggestions.

```
=====> node-js-app ps:report
       Processes:        3
       Deployed:         true
       Running:          true
       Restart Policy:   on-failure:3
       Status web.1:     running (CID: 12345)
       Status worker.1:  stopped
       Status worker.2:  stopped
```

**Comment by josegonzalez** [comment]
Closing as pull requests are available for all plugins.

I decided against `nginx:report` as it's not yet clear what data would be useful there.
