### ISSUE TITLE
domains:add rejects domains with hyphen in host path

### ISSUE THREAD

**Issue by xadh00m** [dokku/dokku#2359]
Description of problem:
domains:add rejects domains that contain a hyphen in the host path e.g. dokku.my-server

How was dokku installed?: apt-get

Dokku version: 0.7.0

How reproducible: easily

Steps to Reproduce:
1. dokku domains:add <app_name> dokku.my-server

Actual Results: 
dokku.my-server is invalid. exiting...

Expected Results:
domain added

We face this issue running dokku in a private network.

**Comment by jvanbaarsen** [comment]
Are hyphens allowed in a TLD? I was trying to find the ISO specs about it, but was not able to find any information about this :(

**Comment by josegonzalez** [comment]
Closing as there is a PR up.
