### ISSUE TITLE
Default site on SSL

### ISSUE THREAD

**Issue by jonian** [dokku/dokku#2361]
Hi.

How can I catch all unknown HOST header values for SSL. The docs include example only for port 80.

```
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name _;
  return 410;
  log_not_found off;
}
```
I tried using the example above and replace 80 with 443, but it returns 410 on existing apps.
Thanks in advance.

**Comment by josegonzalez** [comment]
http://stackoverflow.com/a/29448657/1515875

You'll either need to get a wildcard cert and attach that to a 443 `_` vhost, or you'll need to modify your nginx configuration to redirect if the hostname doesn't match one of the ones specified by your application.

**Comment by jonian** [comment]
Thank you for the quick answer!

**Comment by despairblue** [comment]
I tried to use https://github.com/josegonzalez/dokku-global-cert to generate a default cert and appended 

```
server {
  listen 433 ssl default_server;
  listen [::]:433 ssl default_server;
  
  ssl_certificate /var/lib/dokku/config/global-cert/server.crt;
  ssl_certificate_key /var/lib/dokku/config/global-cert/server.key;
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;

  server_name _;
  return 410;
  log_not_found off;
}
```

to `00-default-vhost.conf`. 

But nginx still routes to the first app 😕 

My problem is that this behaviour tricks external monitoring to think that all apps are fine if any app is fine.

**Comment by josegonzalez** [comment]
@despairblue please do not resuscitate old issues.

I'm not sure what url you are going to in this case, but without that information, I can't actively help you. I highly recommend asking for support in our [slack or irc](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/) channels, where we might be able to quicker answer this question.

**Comment by despairblue** [comment]
@josegonzalez sure, sorry, I just thought that the benefit would be that people finding this issue via Google would also find the solution here.

I'll ask on slack.

**Comment by josegonzalez** [comment]
I'll also look at trying to update our docs site for this once you/I have sorted this out via chat :)

**Comment by devkokov** [comment]
Hey, did you find a solution for this? There's nothing in the docs for default site on SSL http://dokku.viewdocs.io/dokku/configuration/domains/

Cheers.

**Comment by josegonzalez** [comment]
@devkokov its the last section on that page [here](http://dokku.viewdocs.io/dokku/configuration/domains/#default-site).

**Comment by devkokov** [comment]
@josegonzalez do you mean this:

> Alternatively, you may push an app to your Dokku host with a name like "00-default". As long as it lists first in ls /home/dokku/*/nginx.conf | head, it will be used as the default nginx vhost.

I was hoping to get it fixed with an Nginx conf file, but the example below doesn't work with SSL:

```
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name _;
  return 410;
  log_not_found off;
}
```

Thanks for your help!

**Comment by josegonzalez** [comment]
HTTPS is slightly different. You can use the following listen stanza:

```
  listen 80 default_server;
  listen 443 ssl default_server;
  listen [::]:80 default_server;
  listen [::]:443 ssl default_server;
```

But if your site isn't serving up the proper ssl certificate, you will have issues with the redirection as most browsers will loudly complain to your users. Unfortunately, there isn't a way around this.

If you want to update the docs with the above and add a note about ssl loading for wildcard domains, that would be great.
