### ISSUE TITLE
Deploy two applications using Dockerfile with same git repository

### ISSUE THREAD

**Issue by nielsonsantana** [dokku/dokku#2363]
I would like know whether is possible deploy two applications in two different containers using Dockerfile. I currently using Procfile with herokuish images. 
But, deploy with Dockerfile is very fast. 
My two applications are: 1) a website; 2) a worker;

**Comment by josegonzalez** [comment]
We have [Procfile support for Dockerfile deploys](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/#procfiles-and-multiple-processes), which should handle your use case.

**Comment by nielsonsantana** [comment]
@josegonzalez, thanks!
