### ISSUE TITLE
ps:rebuild ignores images deployed from tag

### ISSUE THREAD

**Issue by treythomas123** [dokku/dokku#2374]
My team recently switched to [deploying from a docker registry](http://dokku.viewdocs.io/dokku/deployment/methods/images/#deploying-from-a-docker-registry), where we had previously used `git push` and a Dockerfile. So our new deployments are via a `dokku tags:deploy` command.

I noticed that now, if I run `dokku ps:rebuild` on an app that had previously been deployed via `git push`, dokku rebuilds the app from the last commit that I had git-pushed, rather than using the latest image that I had deployed with `dokku tags:deploy`.

We encountered this problem when updating to the latest dokku version, since the [upgrade instructions](http://dokku.viewdocs.io/dokku/getting-started/upgrading/#upgrade-instructions) say to run `dokku ps:rebuildall`. Thus, after upgrading to the latest dokku version, some of our apps were reverted to old versions.

I think the `ps:rebuild` command should recognize that the app was most recently deployed using an image tag, and should simply redeploy that image tag instead of rebuilding from the app's git repo.

### Steps to Reproduce
1. Deploy an app with `git push` and a Dockerfile (not sure if Dockerfile is necessary to recreate)
2. Deploy an updated version of the app from a registry using [these instructions](http://dokku.viewdocs.io/dokku/deployment/methods/images/#deploying-from-a-docker-registry) (i.e. `dokku tags:deploy <app-name> <tag>`)
3. Run `dokku ps:rebuild <app-name>`

### Actual Results:
The old version of the app is built, from the last git commit that was pushed.

### Expected Results:
The app was re-deployed using the more recent, updated image that was deployed with `dokku tags:deploy`

### Info Commands
- `uname -a`: 
```
Linux tefprd.eng.netapp.com 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:          3953       3605        347         45        231        550
-/+ buffers/cache:       2823       1129
Swap:         4095        335       3760
```
- `docker version`:
```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 35
 Running: 31
 Paused: 0
 Stopped: 4
Images: 509
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 561
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.861 GiB
Name: tefprd.eng.netapp.com
ID: SZE5:TRE2:MRWQ:6RH3:6BAT:OLLJ:MKDE:2GJA:5SYK:VPBG:DD2N:O5D3
WARNING: No swap limit support
```
- `sigil -v`: 
```
0.4.0
```
- `dokku version`:
```
0.7.0
```
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.7.0 enabled    dokku core standard plugin
  20_events            0.7.0 enabled    dokku core events logging plugin
  apps                 0.7.0 enabled    dokku core apps plugin
  build-env            0.7.0 enabled    dokku core build-env plugin
  certs                0.7.0 enabled    dokku core certificate management plugin
  checks               0.7.0 enabled    dokku core checks plugin
  common               0.7.0 enabled    dokku core common plugin
  config               0.7.0 enabled    dokku core config plugin
  docker-options       0.7.0 enabled    dokku core docker-options plugin
  dokku-logspout       0.1.0 disabled   sends dokku app stdout to a logging service
  domains              0.7.0 enabled    dokku core domains plugin
  enter                0.7.0 enabled    dokku core enter plugin
  git                  0.7.0 enabled    dokku core git plugin
  logs                 0.7.0 enabled    dokku core logs plugin
  logspout             0.1.0 enabled    sends dokku app stdout to a logging service
  named-containers     0.7.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.7.0 enabled    dokku core proxy plugin
  ps                   0.7.0 enabled    dokku core ps plugin
  repo                 0.7.0 enabled    dokku core repo plugin
  shell                0.7.0 enabled    dokku core shell plugin
  ssh-keys             0.6.4 enabled    dokku core ssh-keys plugin
  storage              0.7.0 enabled    dokku core storage plugin
  tags                 0.7.0 enabled    dokku core tags plugin
  tar                  0.7.0 enabled    dokku core tar plugin
```

**Comment by treythomas123** [comment]
By the way -- I tried a `dokku ps:rebuild` on a new app that I deployed using `dokku tags:deploy` (i.e. an app that has never been deployed using `git push`) and it simply exited successfully without printing any output. This would probably be the desired behavior for any app that has most recently been deployed using `dokku tags:deploy`.

**Comment by josegonzalez** [comment]
So a `ps:rebuild` for an app that is using an image should do nothing?

**Comment by treythomas123** [comment]
Restarting the app might be a better behavior actually.

The [upgrade instructions](http://dokku.viewdocs.io/dokku/getting-started/upgrading/#upgrade-instructions) say to run `ps:stop` before the upgrade, and `ps:rebuildall` to restart all the apps. So `ps:rebuildall` should at least start any stopped apps, otherwise the upgrade instructions won't work for people using images.

**Comment by josegonzalez** [comment]
@michaelshobbs I think we do some stuff surrounding env vars in `ps:rebuild`. I haven't dug, but if you know off the top of your head, can you confirm?

**Comment by michaelshobbs** [comment]
`ps:rebuild` calls `plugn trigger receive-app $APP`. the issue would be in our image tag resolution code somewhere

**Comment by josegonzalez** [comment]
@michaelshobbs We have two `receive-app` triggers:

- `git`: Will trigger if there is a `$DOKKU_ROOT/$APP/refs` directory.
- `tar`: Will trigger if there is a `$DOKKU_ROOT/$APP/src.tar` file.

A `tags:deploy` takes `APP` and `IMAGE_TAG`, and we never store the `IMAGE_TAG` anywhere. As well, since this particular app had a git push at some point in it's history, we'd *also* trigger a deploy for that.

Perhaps the `receive-app` triggers should store a file like `$DOKKU_ROOT/$APP/deploy-method`, which contains a reference to the last way an application was deployed. We'd also want a `tags/receive-app` plugin trigger to handle image rebuilding, and we'd need to store the last `IMAGE_TAG` that was manually deployed.

> We can fallback to the previous checks when the `deploy-method` file does not exist.

**Comment by josegonzalez** [comment]
After discussing with @michaelshobbs, we decided that documenting the edge cases was the best way forward. I've done so in multiple places, including the upgrade docs.

Closing as there is a pr open.
