### ISSUE TITLE
Cannot deploy when ssh keys are not in default place

### ISSUE THREAD

**Issue by auduchinok** [dokku/dokku#2375]
I'm not able to reproduce it and run commands below because the bug had appeared some time ago  and I've just found a reminder to report an issue.

I tried deploying to a server after I'd configured OpenSSH server by following [this tutorial](https://help.ubuntu.com/community/SSH/OpenSSH/Keys#Encrypted_Home_Directory) and moving authorized keys from encrypted home directory as described there. I tried pushing a Rails app but nothing happened after successful git push. After digging it for couple of hours I found that the reason was my OpenSSH config.

Maybe there should be some check for such configuration or, at least, a notice in tutorials.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by auduchinok** [comment]
I'm sorry for not providing in the initial message. I've managed to solve the issue a month ago, so I don't think the output from all of these commands will be relevant because it doesn't reproduce anymore. Here it is:
```bash
eugene@hwproj:~$ uname -a
Linux hwproj 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
eugene@hwproj:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3846         682         436          92        2727        2730
Swap:          3991           0        3991
eugene@hwproj:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
eugene@hwproj:~$ docker -D info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
eugene@hwproj:~$ sigil -v
0.4.0
eugene@hwproj:~$ docker run -ti gliderlabs/herokuish:latest herokuish version
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
eugene@hwproj:~$ dokku version
[sudo] password for eugene: 
0.6.5
eugene@hwproj:~$ dokku plugin
plugn: dev
  00_dokku-standard    0.6.5 enabled    dokku core standard plugin
  20_events            0.6.5 enabled    dokku core events logging plugin
  apps                 0.6.5 enabled    dokku core apps plugin
  build-env            0.6.5 enabled    dokku core build-env plugin
  certs                0.6.5 enabled    dokku core certificate management plugin
  checks               0.6.5 enabled    dokku core checks plugin
  common               0.6.5 enabled    dokku core common plugin
  config               0.6.5 enabled    dokku core config plugin
  docker-options       0.6.5 enabled    dokku core docker-options plugin
  domains              0.6.5 enabled    dokku core domains plugin
  enter                0.6.5 enabled    dokku core enter plugin
  git                  0.6.5 enabled    dokku core git plugin
  logs                 0.6.5 enabled    dokku core logs plugin
  named-containers     0.6.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.6.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.6.5 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.6.5 enabled    dokku core proxy plugin
  ps                   0.6.5 enabled    dokku core ps plugin
  repo                 0.5.3 enabled    dokku core repo plugin
  shell                0.6.5 enabled    dokku core shell plugin
  storage              0.6.5 enabled    dokku core storage plugin
  tags                 0.6.5 enabled    dokku core tags plugin
  tar                  0.6.5 enabled    dokku core tar plugin
eugene@hwproj:~$ docker inspect hwproj
[]
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
eugene@hwproj:~$ 
```

**Comment by josegonzalez** [comment]
I looked into this a bit, turns out its that you moved the `authorized_keys` file from the "normal" location. The logic for adding/removing users is handled by sshcommand, so if you want to improve support for non-standard installations, please make a pull request there :).

The relevant code is anywhere that handles `USERHOME`, such as [here](https://github.com/dokku/sshcommand/blob/master/sshcommand#L114).

One final thing: our [user management docs](http://localhost:8888/dokku/deployment/user-management/) clearly state the location of the `authorized_keys` file, so I'm not sure there is any documentation work either.
