### ISSUE TITLE
Upgrade Issue. Apps won't build

### ISSUE THREAD

**Issue by sbehrends** [dokku/dokku#2376]
I just upgraded to v0.7.0 and all my apps are down now.
Tried to rebuildall but it hangs on the first app and won't rebuild

```
dokku ps:rebuildall
-----> Cleaning up...
-----> Building xxx-stg from herokuish...
-----> Adding BUILD_ENV to build environment...
```

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by sbehrends** [comment]
This is the required information of the system: https://gist.github.com/sbehrends/3006aff64cbcf4c113e6e1dc5dbba787

Regarding how to reproduce it, no exact steps.
Just had dokku installed on a server and runned
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.7.0/bootstrap.sh
sudo DOKKU_TAG=v0.7.0 bash bootstrap.sh
```

Thats it.

**Comment by sbehrends** [comment]
Issue was resolved by upgrading herokuish
```
apt-get install herokuish
```

afterwards just rebuilded all apps

**Comment by kevinmickey** [comment]
I experienced this same issue.  Had Dokku 0.6.5, tried to upgrade to Dokku 0.7.2 with bootstrap.sh, and builds failed after "Adding BUILD_ENV to build environment...".  @sbehrends fix worked for me.

Is there a way to have bootstrap.sh upgrade herokuish if necessary?

**Comment by josegonzalez** [comment]
Yes, can you open an issue for this?
