### ISSUE TITLE
docker-options port forwarding isn't working

### ISSUE THREAD

**Issue by benwilber** [dokku/dokku#2380]
I am running dokku 0.6.5 and trying to get TCP port forwarding working to my `nginx-rtmp` app inside my container.  In addition to the standard port 80, nginx-rtmp also exposes tcp/1935.  The nginx inside my container has `listen 1935`, I am not using `EXPOSE 1935` in my Dockerfile since I don't want the host nginx to proxy it (it's not HTTP).  I have tried:

```
$ dokku apps:create nginx-rtmp
Creating nginx-rtmp... done
$ dokku docker-options:add nginx-rtmp deploy "-p 1935:1935"
$ dokku docker-options nginx-rtmp
Deploy options:
    -p 1935:1935
```

And then I push and check `netstat`:

```
$ netstat -pnelt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:2000            0.0.0.0:*               LISTEN      0          9543        983/python2.7   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          9529        1057/nginx      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          9464        1012/sshd       
tcp6       0      0 :::80                   :::*                    LISTEN      0          32664       1057/nginx      
tcp6       0      0 :::22                   :::*                    LISTEN      0          9466        1012/sshd
```

I expect to see `docker-proxy` listening on `:::1935`, but it's not there.  I guess the `-p 1935:1935` docker-option is not being applied?

**Comment by michaelshobbs** [comment]
Can you include ​*all*​ of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

Also can you link to a gist of a fresh push with dokku trace on?

**Comment by josegonzalez** [comment]
I tried to replicate this on the latest 0.7.0 release. I used [this repo](https://github.com/brocaar/nginx-rtmp-dockerfile) with the following change:

```
commit 52b6200b5eb8edae1888245d1d2422a750d30408
Author: Jose Diaz-Gonzalez <jose@localhost>
Date:   Fri Aug 26 18:58:49 2016 -0400

    Unexpose the port

diff --git a/Dockerfile b/Dockerfile
index 702f93f..0a0a6b4 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,7 +3,6 @@ FROM ubuntu:trusty
 ENV DEBIAN_FRONTEND noninteractive
 ENV PATH $PATH:/usr/local/nginx/sbin

-EXPOSE 1935
 EXPOSE 80

 # create directories
```

And here is the output of the inspection commands:

```
# dokku apps:create nginx-rtmp
Creating nginx-rtmp... done

# dokku docker-options:add nginx-rtmp deploy "-p 1935:1935"

# dokku docker-options nginx-rtmp
Deploy options:
    -p 1935:1935
    --restart=on-failure:10

# docker inspect --format='{{(index (index .NetworkSettings.Ports "1935/tcp") 0).HostPort}}' 10583dafe5e1
1935

# netstat -plent | grep 1935
tcp6       0      0 :::1935                 :::*                    LISTEN      0          131293      1705/docker-proxy
```

Without any further information, we're not going to be able to debug this issue, so I'll auto-close this in 4 days assuming that stays the case.
