### ISSUE TITLE
Trouble setting up http:22:22 so I can SSH into a Docker container

### ISSUE THREAD

**Issue by alexgleason** [dokku/dokku#2383]
Hi all,

I'm running [gogs](http://gogs.io) off a Dokku subdomain, `http://code.<mydomain>.com`

gogs is a GitHub clone, so I want to be able to push repos to it with ssh. I've been trying to use `dokku proxy:ports-add` in various configurations to try to get it to work.

* `http:22:22` nope
* `ssh:22:22` nope
* `http:10022:22` nope
* `ssh:10022:22` not even

Pushing to `git@code.<mydomain>.com:my-repo.git` makes it ask for a password for the git user. I think it's ignoring the proxy ports in this case and trying to get into my host machine.

Pushing to `ssh://git@code.<mydomain>.com:10022/my-repo.git` makes it tell me I don't have access to push to the repository, even though that's been configured within gogs.

Pushing code via https works fine.

Does anyone know what I'm doing wrong? Thanks!

The Dockerfile exposes port 22 and 3000. I have http:80:3000 mapped fine.

**Comment by michaelshobbs** [comment]
This might be helpful: https://dokku.github.io/tutorials/deploying-gogs-to-dokku

```
# expose container `http` port 3000 on host `http` port 80
$ dokku proxy:ports-add gogs http:80:3000
```
```
# expose the container port 22 on host port 2222
$ dokku docker-options:add gogs deploy -p 2222:22
```

**Comment by alexgleason** [comment]
Thank you! I was able to get this working using the `docker-options` command. Unfortunately it does require mapping `2222` to the Docker container.

Do you know if it's possible to have a subdomain function differently for port 22 despite being on the same IP address? Basically, I want my ssh URLs to be `git@code.<mydomain>.com` instead of `git@code.<mydomain>.com:2222` (I don't want the 2222, ideally)

When pushing apps to Dokku (the host server) I push to `dokku@<mydomain>.com`. But when pushing to a subdomain, `git@code.<mydomain>.com` I'd like Dokku to recognize that it's not the Dokku URL and let me route the activity accordingly.

**Comment by michaelshobbs** [comment]
Not sure how you'd have the different behavior on the same port since its two different processes handling either case. One is the gogs container and the other is the host ssh server. Maybe add another IP address to the host and configure the processes to listen on either one but not both?

**Comment by alexgleason** [comment]
I bet Dokku could theoretically listen to port 22, grab the domain being requested, and route the request to a container if that domain has been added to an app. I wonder if/how Docker does it.

IMO this issue should stay open to address the 2222 problem, since it is non-standard and wouldn't be a problem on a dedicated server.

**Comment by josegonzalez** [comment]
Dokku is a pipeline of scripts, and doesn't listen on any given port. Your ssh server - likely OpenSSH - triggers the dokku binary via [`sshcommand`](https://github.com/dokku/sshcommand) with some fancy footwork in the `/home/dokku/.ssh/authorized_keys` file. At no point does Dokku "listen to a port". It's just wired up to be the default command for the `dokku` ssh user.

You *might* be able to have sshcommand trigger a different command for a `git` user on the host server which would push the command into your docker container on that container's ssh port, but how you wire that up is up to you.

There isn't anything here we can do about you needing to have two separate ports for two different processes, so I'm closing the issue. Let us know if you figure out the ssh bit, would be interesting to hear.

**Comment by alexgleason** [comment]
Thanks for the info. I would like to see something built into Dokku. Just thinking out loud now, but perhaps a Dokku command could invoke sshcommand to create the `git` user, and then set it up to forward into a container.

I envision an API like

```dokku sshuser:add myapp git 22:22```

**Comment by josegonzalez** [comment]
I'd be happy to work on such a plugin, but do not think it belongs in the dokku core as it probably isn't a common use-case for Dokku.

If you'd like to sponsor the work involved in getting that going as an official plugin, please see the [sponsorship section in our readme](https://github.com/dokku/dokku#sponsors).

**Comment by josegonzalez** [comment]
As an alternative, you can use an `.ssh/config` to set the default push port to 2222 like in this [blog post](http://sshmenu.sourceforge.net/articles/transparent-mulithop.html).
