### ISSUE TITLE
Document scheme options for dokku proxy:ports-*

### ISSUE THREAD

**Issue by alexgleason** [dokku/dokku#2384]
All the examples use `http`, ex `http:80:3000`.

What else can we use? `https`? `ssh`?

Also, what does the scheme do that Docker doesn't? Because for Docker, we use `-p 80:3000`, and the scheme is not specified. Why should we specify it here?

Thanks. :smile:

**Comment by michaelshobbs** [comment]
Depends on the proxy plugin. We ship with nginx which only supports http/https.
