### ISSUE TITLE
Trouble getting persistent storage to work

### ISSUE THREAD

**Issue by blocka** [dokku/dokku#2399]
Trying to get persistent storage to work:

I'm using dokku 0.7.1 on ubuntu 14.04 on es

`dokku storage:mount app /var/lib/dokku/data/storage/:/path/to/uploads/folder`

Seems simple enough, but content I put in `/path/to/uploads/folder` does not show up in `/var/lib/dokku/data/storage/` and vice versa.

**Comment by josegonzalez** [comment]
Did you ps:rebuild your application after adding the storage mount?

**Comment by blocka** [comment]
That works. Thanks! In retrospect, I don't know why I didn't think of that myself.
