### ISSUE TITLE
Dokku doesn't restore apps on server reboots

### ISSUE THREAD

**Issue by alexgleason** [dokku/dokku#2400]
Description of problem:

If I reboot the server, I have to run `dokku ps:restartall` otherwise the apps will all say "Bad gateway" even though the apps are running.

Output of the following commands

- `uname -a`: Linux candlewaster.co 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:          2001       1741        260         41         47        293
-/+ buffers/cache:       1400        600
Swap:            0          0          0
```
- `docker version`:
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 126
 Running: 12
 Paused: 0
 Stopped: 114
Images: 91
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 486
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: candlewaster.co
ID: ZIHL:M4GL:DWBE:NB3J:2UCG:GWFB:HIB2:KG3X:PUYM:4DME:C3T3:NXTN
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
```
- `sigil -v`: `0.4.0`
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.18
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v81
  heroku-buildpack-java      v44
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v109
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v5
  emberjs.tgz                latest
```
- `dokku version`: `0.7.0`
- `dokku plugin`:
```
  00_dokku-standard    0.7.0 enabled    dokku core standard plugin
  20_events            0.7.0 enabled    dokku core events logging plugin
  apps                 0.7.0 enabled    dokku core apps plugin
  build-env            0.7.0 enabled    dokku core build-env plugin
  certs                0.7.0 enabled    dokku core certificate management plugin
  checks               0.7.0 enabled    dokku core checks plugin
  common               0.7.0 enabled    dokku core common plugin
  config               0.7.0 enabled    dokku core config plugin
  docker-options       0.7.0 enabled    dokku core docker-options plugin
  domains              0.7.0 enabled    dokku core domains plugin
  enter                0.7.0 enabled    dokku core enter plugin
  git                  0.7.0 enabled    dokku core git plugin
  letsencrypt          0.8.5 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.7.0 enabled    dokku core logs plugin
  mariadb              1.0.0 enabled    dokku mariadb service plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  mysql                1.0.0 enabled    dokku mysql service plugin
  named-containers     0.7.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.7.0 enabled    dokku core proxy plugin
  ps                   0.7.0 enabled    dokku core ps plugin
  repo                 0.7.0 enabled    dokku core repo plugin
  shell                0.7.0 enabled    dokku core shell plugin
  ssh-keys             0.6.4 enabled    dokku core ssh-keys plugin
  storage              0.7.0 enabled    dokku core storage plugin
  tags                 0.7.0 enabled    dokku core tags plugin
  tar                  0.7.0 enabled    dokku core tar plugin
```

Environment details (AWS, VirtualBox, physical, etc.):

DigitalOcean droplet

How was dokku installed?:

DigitalOcean Dokku image

How reproducible:

Every reboot

Steps to Reproduce:
1. Reboot machine
2. Visit any app URL

Actual Results:

Rebooting makes apps not come up.

Expected Results:

Rebooting would make the apps come up.

Additional info:

I'm using the latest Dokku on DigitalOcean's Dokku image.

One image in particular was using docker-options to proxy port 2222 to 22, and that one refused to come up with dokku. I had to use `docker ps` to find the container, run `docker stop CONTAINER`, then I could do `dokku ps:start myapp`. Otherwise it would say:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint drunk_blackwell (8f1e0c8f1a1b0ab3511548a5e05d3d8fcc18c2c4dcc25eabbee35545d43cc46a): Bind for 0.0.0.0:2222 failed: port is already allocated.
```

**Comment by josegonzalez** [comment]
Can you provide *all* the information in our ISSUE_TEMPLATE.md? It helps when debugging these issues as we can then accurately reconstruct your system. Thanks.

**Comment by alexgleason** [comment]
Sorry about that. I've updated the issue. Thank you!

**Comment by josegonzalez** [comment]
Okay I see whats going on. When we do a `ps:restore`, we start all the containers. Unfortunately, the ip address changes - wtf docker, that wasn't the case before! - so we also need to re-retrieve the ip address and then issue a `nginx:build-config`.

@michaelshobbs I think the only bit we need to do is reset all the container IPs into the files. That sound right to you? Don't know where that logic belongs - maybe the new `network` plugin we were talking about - but seems like the best course of action here. I can work on that - and move the proxy stuff - and do a minor release if thats fine with you.

**Comment by michaelshobbs** [comment]
@josegonzalez can you recreate that locally? I've not seen this personally. Also, the short term workaround would be to run `dokku ps:rebuildall`.

**Comment by josegonzalez** [comment]
I did by rebooting and inspecting the containers. My IP was stale. I might have a different docker version though.

**Comment by michaelshobbs** [comment]
Ah yeah and I just realized my envs rebuild on boot.

**Comment by alexgleason** [comment]
@michaelshobbs `rebuildall` is not necessary. `restartall` works fine.

**Comment by josegonzalez** [comment]
Closing in favor of building this into a new `network` plugin.
