### ISSUE TITLE
Reverting with push by force says everything is up to date

### ISSUE THREAD

**Issue by lucasm-iRonin** [dokku/dokku#2402]
When I want to push one of the commits before HEAD (i.e. HEAD~1) to master:

`git push -f dokku direct_commit_id:master` it says everything up to date and the only option to revert is to add a new commit on top of that.

I would expect to re-push the code and rebuild the image.

**Comment by josegonzalez** [comment]
Can you include all of the information in our ISSUE_TEMPLATE.md? It helps for replicating issues. Thanks.

**Comment by lucasm-iRonin** [comment]
@josegonzalez let me know if that's enough:

- `uname -a`: 4.2.0-25-generic #30-Ubuntu 
- `docker version`:
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:32:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:32:54 2016
 OS/Arch:      linux/amd64
```
- `sigil -v`: not installed
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.11
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v89
  heroku-buildpack-php       v100
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v67
  buildpack-nginx            v5
```
- `dokku version`: 0.4.13

Environment: VPS
Dokku installed with script from official page:

```
wget https://raw.githubusercontent.com/dokku/dokku/v0.4.13/bootstrap.sh
sudo DOKKU_TAG=v0.4.13 bash bootstrap.sh
```

**Comment by josegonzalez** [comment]
I think this was fixed a while ago, and I'm unable to replicate this on the following dokku setup:

- Docker 1.10.3
- Dokku 0.7.1
- Herokuish 0.3.18
- sigil 0.4.0
- sshcommand 0.6.0 (also I need to add a version command to this...)
- plugn dev (@michaelshobbs  we should fix the version identifier in plugn releases...)

Please upgrade your dokku installation when you get a chance. Also checkout our migration guides, which point out various changes between releases.

**Comment by lucasm-iRonin** [comment]
@josegonzalez actually the problem was related to build error (I'm using https://github.com/michaelshobbs/dokku-app-predeploy-tasks plugin and one of the commands failed). Because there was error during, git tree wasn't updated so I wasn't able to revert. I've checked it locally and if build passes it works as expected.
