### ISSUE TITLE
[RFC] Network Plugin

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2403]
There are a few shortcomings in network support at the moment:

- Docker [introduced a change](https://github.com/moby/moby/issues/2801) which causes it to sometimes change the internal IP/proxied port of a container on reboot of the host (and sometimes on container restart).
- When a container is restarted by docker - for instance, on server reboot - there is no way outside of a `ps:rebuild` to update the IPs associated with an application.
- Enabling the proxy plugin forces the application to run on an internal network ip. The reverse is also true.
- In the case where an application is using a network overlay, we do not grab the correct ip address - mostly because docker doesn't provide a straightforward way of retrieving the information.

What would fixing the above allow?
- Fix issues where an application might have stale IPs attached because _docker_.
- We could use a network overlay, allowing users to do custom routing.
- Allow the proxy handling to continue to occur properly, while also allowing stuff like consul to report on the state of the actual container as opposed to the proxied app.

What are we not going to fix here?
- Full swarm support. This would help us get there from a networking perspective, but that is not the goal.
### Proposal

I'm proposing a new `network` plugin to handle all of these issues. Things it would do:
- provide `functions/network_ip_for_container` for retrieving the current ip associated with a container. This should also retrieve the `deploy` docker options for an application and parse out the relevant `--network` argument to figure out if we should retrieve an ip from a specific overlay when binding to the "internal" interface.
- provide `functions/network_write_container_ips` for writing the relevant ip to disk for a given container
- `ps:restore` needs to call `network:rebuild-ips` for each app.

New commands:
- `network:set APP key value`: set a property to a value for the network plugin. Properties include:
  - `bind-all`: Whether we should bind to all interfaces or not. Valid options:
    - `internal`: `default`, meaning lets use the "internal" docker ip (existing `DOKKU_IS_APP_PROXY_ENABLED` functionality).
    - `external`: Tell our internal networking that we want to bind ports on the host's `0.0.0.0`
- `network:rebuild-ips APP`: rebuilds the ip mapping at any point in time
- `network:report APP`: report the currently written and _actual_ ips associated to a given application, as well as generic networking information

We'd slightly refactor [this bit of code](https://github.com/dokku/dokku/blob/master/plugins/common/functions#L590-L603) to use the new methodology.

> I'd also like to say we could move the port handling here, though my gut feeling says that it belongs more closely with the `proxy` plugin.
### Relevant issues
- #2085: overlay network, nginx listening to the wrong container ip
- #2400: Dokku doesn't restore apps on server reboots
- #2356: [RFC] Create `report` subcommand for all plugins

---

Thoughts? I think the above should handle a few different issues and potentially increase the flexibility of Dokku going forward.

**Comment by cromulus** [comment]
Not sure, but I think I'd like to be able to bind to specific IP addresses, not just "external".

Think of a host with both a public WAN IP address and a private LAN IP address. It would be nice to be able to specify which to bind to.

Just my $0.02

**Comment by josegonzalez** [comment]
Good call. Anything other than the two specified identifiers seems reasonable. Maybe we can instead use interfaces?

**Comment by cromulus** [comment]
Hmm... not sure about interfaces, unless you are specifying down to a specific alias. IP addresses/ranges seem to make the most sense. Those tend to be the logical divisions between network "types" and the way we think about how a service should interact with other services...

**Comment by bakketun** [comment]
In early versions of Docker the IP address of containers where stable. At some point this was changed, since it was never really specified behavior, see https://github.com/docker/docker/issues/2801. Docker was changed again to make IPs stable. Unfortunately this resulted in a different problem. When a container restarts with the same IP, it might not be unable to rebind to the same ports. The stable IP fix was thus reverted: https://github.com/docker/docker/pull/8497. 

Possible solutions for Dokku:

- Dokku assigns IPs to containers (using option --ip).
- Monitor IPs of containers and update Nginx config whenever they change.
- Ignore IPs of containers, and use the port forwarding of feature of Docker instead. 

I think port forwarding might be the best solution. Forwarded ports can be bound to localhost interface.

IPs assign by Dokku still has the problem with ports that might be reused after a crash. Monitoring IPs can be difficult since IPs also changes when docker restarts containers.

**Comment by josegonzalez** [comment]
Port forwarding:

- is slower
- is much more difficult to handle across multiple apps
- is less secure if the user changes an option and makes it bind on `0.0.0.0`

Perhaps a hybrid of setting the `--ip` flag and also allowing users to bind to a specific interface would work well?

**Comment by matthewmueller** [comment]
> Fix issues where an application might have stale IPs attached because docker.

Curious, does this happen often in practice? Or right now should we assume that if the container goes down, the IP will change?

**Comment by josegonzalez** [comment]
Thats what people are trying to explain to me, though it doesn't make sense that a restart would automatically connect to a new IP. *shrug* just going with what users say.

**Comment by matthewmueller** [comment]
hehe okay, I'll test it out today and report back :-)

**Comment by bakketun** [comment]
Here is a script that reproduces IPs changing in Docker on my machine.

**WARNING: This script kills all nginx process on the machine!**

```
#!/bin/bash

num_containers=5

for i in $(seq $num_containers) ; do
    containers="$containers $(docker run --restart on-failure:10 -d nginx)"
done

show_ips() {
    docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $containers
}

echo "IPs before crash"
show_ips
sudo killall -9 nginx
sleep 3
echo "IPs after crash"
show_ips
echo

echo "IPs before restart"
show_ips
docker stop $containers
docker start $containers
echo "IPs after restart"
show_ips
```

Example output:
```
IPs before crash
172.17.0.17
172.17.0.18
172.17.0.19
172.17.0.21
172.17.0.22
IPs after crash
172.17.0.10
172.17.0.6
172.17.0.2
172.17.0.5
172.17.0.9

IPs before restart
172.17.0.10
172.17.0.6
172.17.0.2
172.17.0.5
172.17.0.9
IPs after restart
172.17.0.2
172.17.0.5
172.17.0.6
172.17.0.9
172.17.0.10
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

$ uname -a
Linux gaus02 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ docker version 
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by bakketun** [comment]
Using the --ip parameter of docker run solves the problem, see this gist:
https://gist.github.com/bakketun/9c8444e032934f7ad7c723b817340e0e

Maybe this is the way to go? The changes to dokku aren't that big. A network has to be created at installation of dokku (--ip can only be used with custom network with custom subnet). Also dokku need to do the IP assignment of containers.

Apparently there are situations where reusing the IP wont work, but seems like this is only the case when ports a forwarded, see https://github.com/docker/docker/issues/8493.

**Comment by josegonzalez** [comment]
Relevant: https://github.com/int128/docker-eventhandler/blob/master/eventhandler.sh

**Comment by chiedo** [comment]
Is there any temporary fix that anyone recommends here?

**Comment by chiedo** [comment]
Going to try and tackle this part as an FYI

- provide functions/network_ip_for_container for retrieving the current ip associated with a container. This should also retrieve the deploy docker options for an application and parse out the relevant --network argument to figure out if we should retrieve an ip from a specific overlay when binding to the "internal" interface.

We'll see how it goes!

**Comment by josegonzalez** [comment]
`common/functions` should probably have a way of getting the current container ids as a space-separated list. Then that can be used to feed retrieval of the network ip/port.

**Comment by chiedo** [comment]
Hoping to make some progress on this next week or later this week. Been bogged down with some deadlines!

**Comment by chiedo** [comment]
Question, I'm wondering if we're making this too complicated.

Is there a reason we can't just stop using docker restart policies?

Couldn't we just make dokku restart policies result in `dokku ps:restart`?

If that's ok, I'll head that direction instead and try to implement that.

**Comment by jipiboily** [comment]
Possibly stupid question: but would that work on server reboot too?

JP Boily
Founder @ Metrics Watch http://metricswatch.com

**Comment by josegonzalez** [comment]
@chiedo no that won't work. The restart policies are a built-in thing for docker, we can't just say "hey run this glob of code instead when you want to restart a container". I also don't want to reimplement restart policies in non-docker code, that seems like a waste of our time to implement/maintain.

I was working on fixing/updating [this](https://github.com/progrium/docker-plugins). The client it uses needs to be updated, but once thats done, we can just write a small plugin that listens to docker restart events and triggers `network:rebuild-ips` and `nginx:build-config` via the dokku-daemon socket. That seems pretty doable to me.

@chiedo unfortunately, sometimes things need to be complicated, because docker. Welcome to operations! :)

**Comment by chiedo** [comment]
Haha Thanks @josegonzalez

**Comment by chiedo** [comment]
Hi all, 

In the meantime, you can use `monit` to take care of restarting your apps.

**You can install monit with `sudo apt-get install monit`**

**Then update your /etc/monit/monitrc file and add the following:**

```
check host web-server with address APP_URL
    start program = "/usr/bin/dokku ps:start APP_NAME"  with timeout 180 seconds
    stop program = "/usr/bin/dokku ps:stop APP_NAME"
    if failed
        port 443
        protocol http
        request /
        with timeout 30 seconds
        then restart
```

**You can set whatever frequency you want for the monitoring at the top of your /etc/monit/monitrc file but I went with the following:**

```
  set daemon 300            # check services at x-second intervals
    with start delay 120    # optional: delay the first check by x-seconds (by 
```

**Comment by josegonzalez** [comment]
@chiedo alternative: https://github.com/mbreit/dokku-monit

**Comment by chiedo** [comment]
Hahaha I wish someone had mentioned that before when asking for alternatives lol! Sigh... At least I learned something.

**Comment by mbreit** [comment]
@chiedo That is my fault, sorry. @josegonzalez asked me to mention it here, and I forgot that.
The plugin is very young, so I appreciate any feedback!

**Comment by jipiboily** [comment]
Apparently, the project exist then...first commit was 12 days ago 😀

**Comment by chiedo** [comment]
Hahaha no worries. Glad it exists. Time to try it and update my AMI. LOL!!!

**Comment by chiedo** [comment]
@mbreit great job! Monit was an answer to a problem. dokku-monit just made it easier to implement. Just put dokku-monit in my project and it works like a charm!

**Comment by chiedo** [comment]
A little delayed, but as expected due to how monit works.

**Comment by josegonzalez** [comment]
Shame, sounds like no one is going to work on actually fixing the issue :)

**Comment by chiedo** [comment]
It's actually still on my to-do list @josegonzalez. :)

It will just take some time. I spend most of my days writing web code (node, ruby, php, etc) and the occasional CLI util with Golang. Too much of this codebase is new territory for me so everything will take longer as I'll be learning how things were set up before and reading through documentation about the different languages/tools involved before I can write anything meaningful. 

So all that to say, it's on my to-do list still but can't hit it until I get a bigger chunk of time than I get most days.

**Comment by josegonzalez** [comment]
Lol not an indictment, no one is being forced to work on anything here (or I would have done this months ago).

**Comment by chiedo** [comment]
Phew @josegonzalez I was worried for a second 😝

**Comment by chiedo** [comment]
On a serious note, just trying to make sure my intent is clear :)

**Comment by chiedo** [comment]
Once I can read dokku code without a bunch of noob questions that slow me down and understand what the heck all the code means, you can expect many more pull requests from me 😄

**Comment by chiedo** [comment]
@rvalyi follow the conversation from https://github.com/dokku/dokku/issues/2643#issuecomment-295580805 here.

No problem on the clarification! To clarify further though, see below:

1. `sudo reboot` is just where I've seen the issue the most. And monit actually does solve this. Prior to monit, when a server was rebooted, the app was dead until manual intervention. But with monit, the app is automatically started within a few minutes of the reboot.
2. I've also had production apps die outside of the reboots after some sort of error. Without monit, they **sometimes** stay dead and don't come back alive until I restart the app manually. With monit, they don't ever stay dead.

So this issue really seems to be what is at the root of it.

Ultimately, I need to be able to launch an app and trust that it will stay up without me getting an email that the site is down and having to manually stop what I'm doing and SSH somewhere. Whatever way that needs to happen, I'm fine with.

Before monit, I got those emails once a week total (I'm using dokku on about 5 production sites). With monit, I haven't gotten any.

**Comment by josegonzalez** [comment]
> I've also had production apps die outside of the reboots after some sort of error. Without monit, they sometimes stay dead and don't come back alive until I restart the app manually. With monit, they don't ever stay dead.

Almost certainly that they have a new IP address, so don't appear alive to nginx.

**Comment by chiedo** [comment]
I agree @josegonzalez :)

**Comment by rvalyi** [comment]
BTW, I have such apps that use to die randomly in production. I just upgraded to Dokku 9.4 and set the Docker restart policy for them. As I said my tests with kill -9 of the process were positive with the restart policy (and negative without). I'll let you know like in 10 days if the docker restart policy (restart always) does the job in production for me or not. I never face accidental reboots fortunately though I understand a solution for reboot is needed too.

**Comment by josegonzalez** [comment]
Our normal policy is to restart on failure (up to ten times). If your app exits with an exit code of `0`, then you have different issues :)

**Comment by rvalyi** [comment]
@josegonzalez my last tests in production were with Dokku version < 0.6. I guess there was no restart policy at all at that time, correct? That may explain why I did have some apps dying randomly like once a month eventually (these apps are huge codebase it's not clear what make them die and seems more reasonable to supervise them than try to fix them). I doubt very much they die with a 0 return code.

**Comment by josegonzalez** [comment]
Yep, restart policies are [new as of Dokku 0.7.0](http://dokku.viewdocs.io/dokku/deployment/process-management/#restart-policies).

**Comment by chiedo** [comment]
Gave this another look and this is really freaking hard... lol. I played around for about an hour but couldn't get any traction. Too many questions and too unfamiliar with the codebase (as of now) to be efficient. Don't think I'm going to me any use on this item.

**Comment by josegonzalez** [comment]
There is the open pull request, #2736. Maybe you can help me track down why tests fail by pulling that branch, turning on trace mode, and finding the fail for a deploy?

**Comment by chiedo** [comment]
Awesome @josegonzalez ! 😄 

I'll let you know if I have any questions. (As I probably will).

Is there any contributing getting started guide? I took a look at [this](https://github.com/dokku/dokku/blob/master/CONTRIBUTING.md) but I'm still sure what the next step would be.

Can you explain what you mean by `turning on trace mode` and `finding the fail for a deploy`

What do I need to run and know to start debugging stuff?

Would [this](http://dokku.viewdocs.io/dokku/development/testing/) be all I needed for the `finding the fail for a deploy` portion? 

If I just need to fumble around let me know, but if you can get all the trivial (you either know it or you don't) stuff out the way for me without "oh this is how this project is set up road blocks" so I can get straight to debugging, that would be awesome and I'll be that much more help!

**Comment by josegonzalez** [comment]
Update: doesn't seem like you can create an overlay network without using swarm mode anymore:

```
# docker network create -d overlay my-multihost-network
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

I'm going to punt on doing anything special for overlay networks as a result.

I'm also modifying this RFC to use a generic `set` method for setting network properties. This is a bit more flexible and will allow us to easily add new settable properties for the plugin in the future.

For now, we'll only be able to set whether `bind-external` is true or not. This will be a toggle on whether we should bind individual container ports or not to all interfaces. Don't think that will stop anyone from fiddling with the container's network settings, but should allow us to schedule a container against a standalone swarm cluster, bind to all interfaces, and still use a proxy implementation.

**Comment by chrisnew** [comment]
@josegonzalez how can I help you to push the network plugin? 
I had some issues today with wrong IPs in nginx configuration after I tore down some containers and one of the nginx-wired containers restarted after a crash automatically. (relates loosely to #2602) 
One idea to fix this is to use fixed IP addresses per container which requires a user defined network if I recall correctly.
I implemented that approach only using IPv6 in a different project. The containers may restart and the IP is still fixed which is quite nice.

**Comment by yegor256** [comment]
@josegonzalez what is the solution? What should I do to fix this in my Dokku setup?
