### ISSUE TITLE
DOCS: warning to complete the web installation should be much more prominent

### ISSUE THREAD

**Issue by longhotsummer** [dokku/dokku#2413]
The warning to complete the web installation in https://github.com/dokku/dokku/blob/master/docs/getting-started/installation.md#2-setup-ssh-key-and-virtualhost-settings is critical. Without this step, the server is very vulnerable.

The warning should be big and bold, maybe in a red box. It's way too easy to gloss over, particularly if the user completes the installation without using the web interface.

**Comment by josegonzalez** [comment]
Good call. I can probably make it a "warning" in css with a bit of js, though I can't do much other than make it a blockquote on the github url.

Here is the [doc in prod](http://dokku.viewdocs.io/dokku/getting-started/installation/).

**Comment by josegonzalez** [comment]
Closed by #2437.
