### ISSUE TITLE
how can i run linux command in dokku 

### ISSUE THREAD

**Issue by LabN36** [dokku/dokku#2422]
Hi, I'm beginner in server & Dokku thing, so as i logged into server using SSH it successfully logged in
now my query is that<br /> 1. how can i look up to my source code of different application, suppose if i want to change a file through nano/vi in command can i do that ? 
2. how can i run simple linux command just like **ls** nd all 
please guide

**Comment by deviousgeek** [comment]
You can use `dokku enter [app name] [process name] [command]`. 

If your app only has one process you can leave the name out as it is implicit. The command can be an interpreter such as `sh` or `bash`. Whatever you use is able to be run interactively.

**Comment by josegonzalez** [comment]
All code is edited locally, on your computer, and you `git push` a source tree to the dokku server. Please refer to the documentation for your operating system on how to do that, and refer to our documentation for general usage of dokku. If you have further questions, feel free to hop onto our slack or irc rooms, which are linked to in our documentation and readme.
