### ISSUE TITLE
Document the `logs` plugin

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2424]
This is currently undocumented.

Needs:

- Link on the sidebar after [this](https://github.com/dokku/dokku/blob/master/docs/template.html#L200) line
- A section at the top with the help output for the log output like [this](https://github.com/dokku/dokku/blob/master/docs/deployment/application-management.md)
- A section on behavioral modifiers [like so](https://github.com/dokku/dokku/blob/master/docs/deployment/remote-commands.md#behavioral-modifiers)
- It needs to be a new document called `docs/deployment/logs.md`

**Comment by cynicaldevil** [comment]
I'll take a stab at this.

**Comment by josegonzalez** [comment]
Yep closing!
