### ISSUE TITLE
Problem to create a tag with dokku

### ISSUE THREAD

**Issue by carloslimasis** [dokku/dokku#2425]
Description of problem:

Hi, I'm trying create a tag with dokku and i have this problem:
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.

Output of the following commands

- dokku tags:create veronica v1.0

Environment details (AWS, VirtualBox, physical, etc.):
AWS

How was Dokku installed?:

- wget https://raw.githubusercontent.com/dokku/dokku/v0.7.1/bootstrap.sh
- sudo DOKKU_TAG=v0.7.1 bash bootstrap.sh

Steps to Reproduce:
1. dokku tags:create veronica v1.0

Actual Results:
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.

Expected Results:
=====> Added v1.0 tag to dokku/veronica

Additional info:
Dokku version: 0.7.1
Docker version: Docker version 1.12.1, build 23cf638

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? Specifically, operating system version and the trace output of the command are missing. It is helpful for debugging problems. Thanks.

**Comment by michaelshobbs** [comment]
I think docker dropped -f. I remember seeing a deprecation warning in 1.11.

**Comment by carloslimasis** [comment]
ubuntu@ip-172-31-16-216:~$ dokku --trace tags:create veronica v1
+ case "$(lsb_release -si)" in
++ lsb_release -si
+ export DOKKU_DISTRO=ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOKKU_IMAGE=gliderlabs/herokuish
+ DOKKU_IMAGE=gliderlabs/herokuish
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args tags:create veronica v1
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ for arg in '"$@"'
+ false
+ case "$arg" in
+ local next_index=2
+ for arg in '"$@"'
+ false
+ case "$arg" in
+ local next_index=3
+ for arg in '"$@"'
+ false
+ case "$arg" in
+ local next_index=4
+ return 0
+ args=("$@")
+ [[ tags:create =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ /usr/bin/tty
+ [[ /dev/pts/0 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
++ id -un
+ [[ dokku != \r\o\o\t ]]
+ [[ tags:create =~ ^plugin:.* ]]
++ id -un
+ [[ dokku != \r\o\o\t ]]
+ [[ tags:create == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ -n '' ]]
+ dokku_auth tags:create veronica v1
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=ubuntu
+ SSH_USER=ubuntu
+ export SSH_NAME=default
+ SSH_NAME=default
+ plugn trigger user-auth ubuntu default tags:create veronica v1
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ tags:create =~ (ssh-keys:add|ssh-keys:remove) ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd tags:create veronica v1
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=tags:create
+ local PLUGIN_CMD=tags:create
+ local implemented=0
+ local script
+ argv=("$@")
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/tags
+ [[ /var/lib/dokku/core-plugins/available/tags == *core-plugins* ]]
+ [[ tags:create == \t\a\g\s\:\c\r\e\a\t\e ]]
+ shift 1
+ [[ ! -z '' ]]
+ set -- tags:create veronica v1
+ [[ -x /var/lib/dokku/plugins/enabled/tags:create/subcommands/default ]]
+ [[ -x /var/lib/dokku/plugins/enabled/tags:create/subcommands/tags:create ]]
+ [[ -x /var/lib/dokku/plugins/enabled/tags/subcommands/create ]]
+ /var/lib/dokku/plugins/enabled/tags/subcommands/create tags:create veronica v1
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ source /var/lib/dokku/plugins/available/tags/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+ tags_create_cmd tags:create veronica v1
+ declare 'desc=creates an images tag for app via command line'
+ local cmd=tags:create
+ [[ -z veronica ]]
+ local APP=veronica
+ local IMAGE_TAG=v1
++ get_app_image_repo veronica
++ declare 'desc=central definition of image repo pattern'
++ local APP=veronica
++ local IMAGE_REPO=dokku/veronica
++ [[ -z veronica ]]
++ echo dokku/veronica
+ local IMAGE_REPO=dokku/veronica
+ verify_app_name veronica
+ declare 'desc=verify app name format and app existence'
+ local APP=veronica
+ [[ ! -n veronica ]]
+ [[ ! veronica =~ ^[a-z].* ]]
+ [[ ! -d /home/dokku/veronica ]]
+ return 0
+ tag_image dokku/veronica:latest dokku/veronica:v1
+ declare 'desc=convenience method for docker tag interface'
+ docker tag -f dokku/veronica:latest dokku/veronica:v1
+ unknown shorthand flag: 'f' in -f
+ See 'docker tag --help'.
