### ISSUE TITLE
Multiple contiguous spaces in environment variables get collapsed to a single space

### ISSUE THREAD

**Issue by treythomas123** [dokku/dokku#2427]
When I attempt to set an environment variable with more than one space in row, the environment variable is being set with the multiple spaces collapsed into just one space:

```
$ dokku apps:create test-app
Creating test-app... done

$ dokku config:set test-app TESTVAR="word1  word2"
-----> Setting config vars
       TESTVAR: word1  word2
-----> Restarting app test-app
App test-app has not been deployed

$ dokku config:get test-app TESTVAR
word1 word2
```

Note that the `config:set` command has two spaces between `word1` and `word2`. The initial output of `config:set` appears correct (it shows two spaces), but a subsequent call to `config:get` shows that the value was stored with only one space. 

I also tried running `env` inside a linux app, and confirmed that the variable appeared inside the container with only one space. So this isn't just an issue with the output of the `config:get` command.

This is on dokku version 0.7.0 and docker version 1.10.2. I'm not sure the rest of the recommended info commands would be helpful in this case, but let me know if you need them.

**Comment by josegonzalez** [comment]
Escape each space?

**Comment by treythomas123** [comment]
Same behavior when escaping the spaces instead of using a quoted string:

```
$ dokku apps:create test-app
Creating test-app... done

$ dokku config:set test-app TESTVAR=word1\ \ word2
-----> Setting config vars
       TESTVAR: word1  word2
-----> Restarting app test-app
App test-app has not been deployed

$ dokku config:get test-app TESTVAR
word1 word2
```

**Comment by josegonzalez** [comment]
Closing in favor of #1262. The config plugin needs a bit of love.
