### ISSUE TITLE
Invalid SSL Certificate for Chrome 53 and OS X Sierra

### ISSUE THREAD

**Issue by mindeavor** [dokku/dokku#2428]
Description of problem:

I installed SSL using `dokku certs:add` for a couple weeks now. Everything has been working great.

However, today a coworker attempted to access [the app](https://helpdesk.makerpass.com/), and got a certificate error! He had been using it quite often; apparently this started happening after he upgraded his OS to Sierra.

This SSL certificate is a wildcard certificate. The coworker is able to access our other apps that use the same cert, even after the OS upgrade.

What could be the problem? What more information can I give to help debug?

<details>
<summary>**Output of the following commands:**</summary>

- `uname -a`:

    Linux makerpass.helpdesk 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- `free -m`:

```
             total       used       free     shared    buffers     cached
Mem:           489        471         18          1         56        187
-/+ buffers/cache:        227        262
Swap:            0          0          0
```

- `docker version`:

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

- `docker -D info`:

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 15
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: makerpass.helpdesk
ID: BGSL:WPH2:WMTX:5XLD:JMKK:5PUP:6EMW:23DH:CORU:IN7H:U7D7:JRCO
WARNING: No swap limit support
```

- `sigil -v`: `0.4.0`
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:

```
herokuish: 0.3.9
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v88
  heroku-buildpack-php       v95
  heroku-buildpack-play      v26
  heroku-buildpack-python    v77
  heroku-buildpack-ruby      v145
  heroku-buildpack-scala     v66
  buildpack-nginx            v5
```

- `dokku version`: `0.5.4`
- `dokku plugin`:

```
plugn: dev
  00_dokku-standard    0.5.4 enabled    dokku core standard plugin
  20_events            0.5.4 enabled    dokku core events logging plugin
  apps                 0.5.4 enabled    dokku core apps plugin
  build-env            0.5.4 enabled    dokku core build-env plugin
  certs                0.5.4 enabled    dokku core certificate management plugin
  checks               0.5.4 enabled    dokku core checks plugin
  common               0.5.4 enabled    dokku core common plugin
  config               0.5.4 enabled    dokku core config plugin
  docker-options       0.5.4 enabled    dokku core docker-options plugin
  domains              0.5.4 enabled    dokku core domains plugin
  enter                0.5.4 enabled    dokku core enter plugin
  git                  0.5.4 enabled    dokku core git plugin
  logs                 0.5.4 enabled    dokku core logs plugin
  named-containers     0.5.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.4 enabled    dokku core plugin plugin
  proxy                0.5.4 enabled    dokku core proxy plugin
  ps                   0.5.4 enabled    dokku core ps plugin
  shell                0.5.4 enabled    dokku core shell plugin
  storage              0.5.4 enabled    dokku core storage plugin
  tags                 0.5.4 enabled    dokku core tags plugin
  tar                  0.5.4 enabled    dokku core tar plugin
```

- `docker inspect CONTAINER_ID` (if applicable): **N/A**
- `cat /home/dokku/<app>/nginx.conf` (if applicable):

```
server {
  listen      [::]:80;
  listen      80;
  server_name helpdesk.makerpass.com; 
  access_log  /var/log/nginx/helpdesk-access.log;
  error_log   /var/log/nginx/helpdesk-error.log;


  return 301 https://$host:443$request_uri;

}

server {
  listen      [::]:443 ssl spdy;
  listen      443 ssl spdy;
  server_name helpdesk.makerpass.com; 
  access_log  /var/log/nginx/helpdesk-access.log;
  error_log   /var/log/nginx/helpdesk-error.log;

  ssl_certificate     /home/dokku/helpdesk/tls/server.crt;
  ssl_certificate_key /home/dokku/helpdesk/tls/server.key;

  keepalive_timeout   70;
  add_header          Alternate-Protocol  443:npn-spdy/2;
  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://helpdesk;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/helpdesk/nginx.conf.d/*.conf;

}

upstream helpdesk {
  server 172.17.0.2:5000;
}
```

- Link to the exact repository being deployed (if possible/applicable): **N/A**
- Output of failing Dokku commands after running `dokku trace on` **N/A?**

- Environment details (AWS, VirtualBox, physical, etc.): DigitalOcean

- How was Dokku installed?: Don't remember. I think the one-click installer?
</details>

**Comment by josegonzalez** [comment]
Does this happen on other browsers? What about other OS versions with the same browser version? Or other Sierra installations?

Seems like something is off with how you signed your browser, not with Dokku itself. I would check with your certificate provider. If you need any more help, I highly suggest hopping on our Slack or IRC channels and asking there.

**Comment by mindeavor** [comment]
I'm using Chrome 53 on El Capitan with no problems.

Thank you for your response. I will investigate further and update this comment with what I find for future googlers.

**Comment by rileytg** [comment]
getting this also after upgrade to OS sierra on chrome  53.0.2785.116 (64-bit)

**Comment by mindeavor** [comment]
Update: The SSL certificate is still broken for the first co-worker, for both chrome versions `53.0.2785.116` and `53.0.2785.143` (he tried updating chrome). However, using safari works fine for him. Chrome Canary also works fine.

Another co-worker, is using chrome version `53.0.2785.116` on El Capitan with no issues.

It seems that this is specifically a Sierra + Chrome 53 issue, but I still don't know why. We have other apps that use the same wildcard certificate, and the co-worker on Sierra can access those other apps just fine (using chrome). Because of this, I can't 100% rule out dokku quite yet (the other apps run on heroku).

**Comment by josegonzalez** [comment]
Can you verify its the same cert? What about Firefox? What happens if you do another dokku app with that cert? Also, try a clean install of Chrome.

**Comment by ericlaw1979** [comment]
The problem here is that the certificate chain is incomplete; the server should send required intermediate certificates so that the browser can construct the chain all the way back to a trusted Root certificate. (See the "Extra Download" warnings here: https://www.ssllabs.com/ssltest/analyze.html?d=helpdesk.makerpass.com&latest

**Comment by mindeavor** [comment]
I see, @ericlaw1979, that is most likely the problem. Thank you for pointing me in the right direction.
