### ISSUE TITLE
Change hacktoberfest issue label

### ISSUE THREAD

**Issue by arr-dev** [dokku/dokku#2434]
Hi.

Official hacktoberfest issue label is [hacktoberfest](https://github.com/search?l=&q=state%3Aopen+label%3Ahacktoberfest&ref=advsearch&type=Issues&utf8=%E2%9C%93).

Switching from `#hacktoberfest` to `hacktoberfest` would make issues easier to find.

**Comment by josegonzalez** [comment]
Done.
