### ISSUE TITLE
Web SSH Key not added when key is already attached to server

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2445]
As both the debian package and the web ui use the `admin` user, the web ui will fail to add the ssh key, resulting in some users not having access to dokku push.

We should instead use `admin-web` as the admin user from the web ui if we detect that there is an existing `admin` user.

[Here](https://github.com/dokku/dokku/blob/master/contrib/dokku-installer.py#L103) is the line of code that executes this. What I'd do is list users, check if `admin` is in the list, and if so, change the username there from `admin` to `admin-web`.

**Comment by AshwinFL** [comment]
I would like to work on this bug , do you mind giving some more pointers?

**Comment by josegonzalez** [comment]
@AshwinFL updated with a bit more context.

**Comment by mbtamuli** [comment]
@josegonzalez 
> Here is the line of code that executes this. What I'd do is list users, check if admin is in the list, and if so, change the username there from admin to admin-web.

By list users, do you mean the users found when we do `dokku ssh-keys:list`
```shell
48:74:c1:5a:23:bd:0c:0f:fb:b3:09:0a:c4:48:94:74 NAME="admin" SSHCOMMAND_ALLOWED_KEYS="no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding"
05:9f:fb:be:eb:91:79:00:96:81:9b:dc:b1:86:48:90 NAME="test" SSHCOMMAND_ALLOWED_KEYS="no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding"
```

Like _admin_ and _test_ in this case?

**Comment by josegonzalez** [comment]
Yes, that is correct.
