### ISSUE TITLE
Adding a file with two ssh-keys can result in an error

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2446]
We should validate that the input file only has one string. As well, the output of the `ssh-keys:add` should include a 0 exit code _only_ if the `authorized_keys` file is still valid.

**Comment by arr-dev** [comment]
I could try fixing this for hacktoberfest

**Comment by josegonzalez** [comment]
:)

**Comment by polettix** [comment]
@arr-dev did you start working on this? I'd like to give it a try too but I don't want to "steal" anything.

**Comment by arr-dev** [comment]
Hi @polettix I've started on it but have been busy and haven't committed anything.
I hope to have time over the weekend to finish it.

**Comment by polettix** [comment]
NP happy coding!

2016-10-14 10:45 GMT+02:00 Nenad <notifications@github.com>:

**Comment by arr-dev** [comment]
Hey @polettix, work stuff got their better of me over the weekend too,
so hack away on this if you can.

**Comment by josegonzalez** [comment]
Closing as a pr was merged!
