### ISSUE TITLE
Build on a separate machine?

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2448]
Hi,

   I know that docker swarm support is way in the future (https://github.com/dokku/dokku/issues/1795), so I was wondering if it is possible to at least (optionally) use a different host to perform the builds. The reason I ask is because if one uses for example Python with event in the app, it requires a ton of C++ compilation etc. Since all this runs on the same host running the apps, it drains the performance from these running apps. Supporting the build step on a separate host would be a way to alleviate this problem.

  If combined with Amazon Spot Instances, even better. I could have machines on-demand at a lower cost, for the builds, without impacting the single-host SaaS provided by dokku. This could definitely increase the usefulness of the current single-host approach.

**Comment by josegonzalez** [comment]
If you want to do this, you can push/pull images using the [`tags` plugin](http://dokku.viewdocs.io/dokku/deployment/methods/images/), which has a workflow documented for using pre-built images (whether they be from docker hub or otherwise).

I've used this workflow with quay.io.

**Comment by sglebs** [comment]
For the record: I would like to keep using git push for deploy and have the herokuish steps run on a separate host, different form the runtime/execution host. I don't want to have to resort to docker files and docker images. The tags plugin does not help me here AFAIK.

**Comment by josegonzalez** [comment]
You can have a post-push plugin on the other instance that then connects to the original server and deploys the built image using the tags plugin.

Making this process seamless is not in the scope of dokku core, but if you'd like to contract with me to have me write such a plugin, please get in touch via email.
