### ISSUE TITLE
Request: Include git commit hash in dokku ls output

### ISSUE THREAD

**Issue by kevinmickey** [dokku/dokku#2456]
It would be nice to have a column in the dokku ls output that includes the git commit hash.

I know that you can access it for each app manually (http://stackoverflow.com/questions/29801570/see-git-commit-hash-of-running-dokku-app/29890812), or include it in the environment (https://github.com/Anadea/dokku-git-rev).

I'm not sure if a plugin can override an existing Dokku command, but it looks like it may be a simple line or two to add to https://github.com/dokku/dokku/blob/master/plugins/00_dokku-standard/subcommands/ls

Is there interest in this, or possibility of adding to dokku core?

**Comment by josegonzalez** [comment]
Why would this be nice?

Personally I want to remove `dokku ls` in favor of `dokku apps`, but that is unrelated to this.

**Comment by kevinmickey** [comment]
If I have the same git repo deployed as four different apps (e.g., dev, qa, stage, prod, or maybe dev-a, dev-b, dev-c, prod, or whatever), it would be convenient to quickly check the code versions.

On the sidenote, I agree with you -- if dokku apps has the more detailed output of dokku ls, dokku ls becomes entirely unnecessary.

**Comment by josegonzalez** [comment]
Note: this would be a bc-incompatible change regardless, as users may be parsing cli output for whatever integrations.

**Comment by willianpaixao** [comment]
Is there anyone working on this issue? Can I get it?

**Comment by kevinmickey** [comment]
@willianpaixao, no I don't think anyone is currently working on this.  If you implement this, I can test it out.

**Comment by josegonzalez** [comment]
This should actually be rolled into #2356, where we can add extra metadata to the `report` output for an app. Closing in favor of that issue.
