### ISSUE TITLE
Is there a way to link app container to other docker containers?

### ISSUE THREAD

**Issue by raphaklaus** [dokku/dokku#2458]
Hi there! Is there a way to link app container to other docker containers? Being these containers initialized by docker or docker-compose?

Example: I've a Docker PostgreSQL container which is running on port 5432. I want the app container be able to listen to this container's service.

I know the existence of dokku plugins, but I do prefer run "outside and vanilla".

I've tried create a link using docker-options:

```
Run options:
    --link root_database_1:mongo
    --link root_redis_1:redis
```

But when I push to deploy I got `connection refused` on the port 5432. 

It occours for any service I attach to app.

**Comment by josegonzalez** [comment]
The `run` phase is for `dokku run` commands. You probably want the `deploy` phase, as documented [here](http://dokku.viewdocs.io/dokku/advanced-usage/docker-options/#about-dokku-phases).

Outside of that, you're more or less on your own, as you're using docker more or less directly at that point. Good luck!

**Comment by raphaklaus** [comment]
@josegonzalez thank you for your reply. 

I run into some issues trying to do link in the deploy phase:

`docker: Error response from daemon: Cannot link to /root_database_1, as it does not belong to the default network.`

I've also tried:
` dokku docker-options:add backend deploy "--net=736e77a21019"` adding my container's network (originated in `docker-compose up -d`), and trying with **build, deploy, run** phases but I've got the same error or something like:

` docker: Error response from daemon: service endpoint with name loving_borg already exists.`

The way I am trying to do is supported by dokku? Or exist another way to achieve this?

**Comment by adrm** [comment]
Hi @raphaklaus, how did you finally achieved this? I would like to have a private service that can only be accessed by the apps I decide via local network. Does dokku now supports some way to do this? I would like it to work as with database services, but I want to avoid the hassle of writing a dokku service if possible.

**Comment by joshmanders** [comment]
@adrm All all services provided by Dokku are linked locally and require an expose command to be ran to open them to the outside world.

**Comment by josegonzalez** [comment]
A few things:

- please don't comment on 2 year old issues. Folks might not be using Dokku anymore, so this would make their notifications sad.
- The "regular" way to do this is to expose a process to the world and then just use normal external networking. Thats actually how folks do it on Heroku. You can make this more secure by:
  - using SSL
  - only allowing network requests from your own IP address via iptables
  - making requests to internal ip addresses if you're in a private cloud
- The correct way to do this is via custom docker networks. [Here is a high-level spec](https://github.com/dokku/dokku/issues/2085) if you want to get started on implementing them in Dokku. Pull requests are _definitely_ welcome.

I'm locking the issue, as this isn't really possible to do correctly without custom networks, and the work necessary for them is outlined in the linked issue.
