### ISSUE TITLE
Dokku doesn't restore all apps after system reboot

### ISSUE THREAD

**Issue by ebeigarts** [dokku/dokku#2463]
I have around 30 apps on one host and after a reboot only half of my apps were started, because one app failed to start and `ps:restore` subcommand has `set -e` which exits the script and doesn't try to start all the other apps. Also it is not very efficient to restore 30+ apps using just single CPU.

I am currently using `dokku apps | grep -v '=====>' | parallel -v -v dokku ps:start` to restart all the apps and use all 8 CPU cores and speeding the process 8x.

One solution would be to get rid of `set -e` in `ps:restore` command.
Another solution would be to use GNU parallel, but that's a new dependency, which is available using `apt-get install parallel`.

@josegonzalez WDYT?

**Comment by josegonzalez** [comment]
we should probably continue and log the error. @michaelshobbs ?

**Comment by josegonzalez** [comment]
Closing as there is now a pull request open.
