### ISSUE TITLE
Unexpected ssh config when using vagrant

### ISSUE THREAD

**Issue by timaschew** [dokku/dokku#2466]
Description of problem:
I installed dokku via Vagrant and I realized in this step:

> Setup SSH Config in `~/.ssh/config`. The port listed here is usually correct, though you may want to verify that it is the same as the one listed in the output of `vagrant ssh-config dokku` 

That the output for me is: 

``` ini
Host dokku
  HostName 127.0.0.1
  User vagrant
  Port 2222
```

and not 

``` ini
Host dokku.me
  Port 22
```

But I needed to use `dokku.me`and port `22` to get it working.

Output of the following commands
- `uname -a`: Linux
- `docker version`: 1.12.2
- `dokku version`: v0.7.2-17-g3200c16
- Vagrant 1.8.6
- VirtualBox: Version 5.1.6 r110634 (Qt5.5.1)

Environment details (AWS, VirtualBox, physical, etc.): VirtualBox and Vagrant

How was Dokku installed?: From source, like it's described here: http://dokku.viewdocs.io/dokku/getting-started/install/vagrant/#install-dokku-using-vagrant

How reproducible:

Follow the instructions from the link above

Actual Results:

``` ini
Host dokku
  HostName 127.0.0.1
  User vagrant
  Port 2222
```

Expected Results:

``` ini
Host dokku.me
  Port 22
```

**Comment by josegonzalez** [comment]
The docs there assume that you are using `dokku.me` as the hostname, and have `dokku.me` set to `10.0.0.2`, which is the default ip of the server. I'll update the docs to make this a bit more clear.

**Comment by timaschew** [comment]
I'm wondering about the Port, why it's 2222 in the output but the real port is 22?
Also the output of `vagrant up` contains 2222
```
==> dokku: Waiting for machine to boot. This may take a few minutes...
    dokku: SSH address: 127.0.0.1:2222
```

**Comment by josegonzalez** [comment]
Vagrant remaps the port on the host because port `22` is a reserved port that needs sudo access to bind to, and usually you already have `sshd` running on it.
