### ISSUE TITLE
Installing and running dokku behind http proxy

### ISSUE THREAD

**Issue by tuukkamustonen** [dokku/dokku#2467]
After getting around a few hickups during installation while behind proxy (e.g. http://stackoverflow.com/a/28093517/165629 and https://github.com/dokku/dokku/issues/2181#issuecomment-219237898), I got into state where I don't know what to configure.

Following http://dokku.viewdocs.io/dokku/deployment/application-deployment/#deploy-the-app:

```
$ git push dokku master
Counting objects: 236, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (136/136), done.
Writing objects: 100% (236/236), 42.01 KiB | 0 bytes/s, done.
Total 236 (delta 84), reused 236 (delta 84)
-----> Cleaning up...
-----> Building ruby-rails-sample from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
       !
       !     Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.11.2.tgz -s -o - | tar zxf - ' failed unexpectedly:
       !
remote: : Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/bundler-1.11.2.tgz -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
remote: 
remote: gzip: stdin: unexpected end of file
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
...
```

I'm 99% sure this happens due to missing proxy config.

There is something at https://gist.github.com/mugifly/899a169d353f511c378d but especially this bit (modifying dokku commands to inject http proxy params) feels way way too hacky.

Does dokku support running behind proxy? If so, any pointers to what I can do/configure here?

Relevant bits:

`uname -a`:

```
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
```

`docker version`:

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:43:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:43:41 2016
 OS/Arch:      linux/amd64
```

`docker run -ti gliderlabs/herokuish:latest herokuish version`:

```
# docker run -ti gliderlabs/herokuish:latest herokuish version
herokuish: 0.3.19
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v82
  heroku-buildpack-java      v46
  heroku-buildpack-gradle    v18
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v110
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v6
  emberjs.tgz                latest
```

`dokku version`: `0.7.2`

**Comment by josegonzalez** [comment]
You can create a plugin that uses the `docker-args-build` hook to set custom `--build-args`, or use the official `docker-options` plugin to set those arguments for a specific application.

For the moment, dokku does not support easily configuring running behind a proxy - you'll see there are also docker-related things you'd need to do - and while good docs on doing so would be useful (I don't know why that's a gist and not just a pull request to this project...), we won't be supporting it in the core as a command you can run to configure it.

If you'd like to continue getting support, please check out our irc or slack room, perhaps someone can help there.
