### ISSUE TITLE
dokku config:unset is not unsetting the environment variable

### ISSUE THREAD

**Issue by timaschew** [dokku/dokku#2468]
Description of problem:
Unset is not unsetting the environment variable, even if the a new deployment is triggered.

Ubuntu 16 (VirtualBox with Vagrant) on a OS X host
Dokku v0.7.2-17-g3200c16
Docker 1.12.2

How reproducible:
Set a env via `dokku config:set` then try to `dokku config:unset` it.

Actual Results:
env variable is still there, I can verify it via `docker enter` and then run`env`
but `root@dokku:/home/dokku/inquiry-webhook/.env` does not contain the variable anymore

Expected Results:
env variable should not be present after unsetting

Additional info:

Here is the output after unsetting the variable:

```
# dokku config:unset inquiry-webhook EMAIL_ACCOUNT
-----> Unsetting inquiry-webhook
-----> Unsetting EMAIL_ACCOUNT
-----> Restarting app inquiry-webhook
-----> Releasing inquiry-webhook (dokku/inquiry-webhook:latest)...
-----> Deploying inquiry-webhook (dokku/inquiry-webhook:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> App Procfile file found (/home/dokku/inquiry-webhook/DOKKU_PROCFILE)
-----> DOKKU_SCALE file found (/home/dokku/inquiry-webhook/DOKKU_SCALE)
=====> web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
-----> Found previous container(s) (bff1135a4e15) named inquiry-webhook.web.1
=====> renaming container (bff1135a4e15) inquiry-webhook.web.1 to inquiry-webhook.web.1.1476883169
=====> renaming container (21d8d6d9b426) kickass_northcutt to inquiry-webhook.web.1
-----> Configuring inquiry-webhook.dokku.me...(using built-in template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
-----> Shutting down old containers in 60 seconds
=====> bff1135a4e155b187c14418f2442e00203675a15f2a5af4eb361baadaaf28846
=====> Application deployed:
       http://inquiry-webhook.dokku.me
```

```
root@dokku:/home/user# dokku enter inquiry-webhook
herokuishuser@21d8d6d9b426:~$ env
...
EMAIL_ACCOUNT=foobar@gmail.com
...
```

**Comment by timaschew** [comment]
any feedback?

**Comment by josegonzalez** [comment]
Do you mind jumping on our irc or slack room to get some support for this? I am `savant` on both.

**Comment by mtarnovan** [comment]
I'm having this exact issue, same Dokku version. Was there a solution on slack for this? I can't find it in history.

**Comment by tmlee** [comment]
Somehow i am noticing this too, after `unset`, the ENV variable still accessible with the old value in the app

**Comment by josegonzalez** [comment]
Please file a new issue with all the info in the issue template if you are seeing this issue.

**Comment by jgeurts** [comment]
If anyone stumbles across this, I was having troubles with what I thought was dokku not unsetting a variable, but it was rather that I had a few orphaned docker containers of my dokku app running. After killing the rogue docker containers, things worked as expected again.

**Comment by josegonzalez** [comment]
Please be sure to upgrade to the latest Dokku release, which has a fix for t
Orphaned containers.

**Comment by Kjwon15** [comment]
It is still happened in latest dokku

**Comment by ajb** [comment]
This is still happening! It is triggering a rebuild but the env variable is persisting :(

**Comment by josegonzalez** [comment]
Please file a new issue with all the info in the issue template if you are seeing this issue.
