### ISSUE TITLE
Clarifying ps:scale

### ISSUE THREAD

**Issue by matthewmueller** [dokku/dokku#2471]
This is a pretty noob question, but what does `ps:scale` actually do for dokku?

On heroku I think it makes sense because I think they give you more resources, but what does this do when the resources are fixed? Is there a way to set it up so scaling will actually give you more resources on say AWS or DO? 

Otherwise, my thought is that it's just more cpu shares being allocated to it, so if `web=2 worker=1`, web gets twice as much CPU share as worker. 

I'd love to get this cleared up – thanks!

**Comment by michaelshobbs** [comment]
Currently this just equates to additional docker containers running the specified process type. The design use case a single threaded process (perhaps an asynchronous worker) running on a multicore instance.

**Comment by josegonzalez** [comment]
@matthewmueller As @michaelshobbs mentioned, it simply spins up a new docker container against the configured local docker host. You can limit resources assigned to a container using the `docker-options` plugin, though each "process" that is scaled will get the same options.

As Dokku is an open source project, we currently have no immediate plans to make it multi-host, and would rather concentrate on making it the best single-host solution out there. If you're interested in sponsoring work to make it multi-host, please get in touch with me directly.

Relevant discussion is also available at #1795.

**Comment by chiedo** [comment]
So just to be clear, if I were on a 16 core box, in order to utilize my 16 cores with a nodejs app, I would want to scale up to 16 web processes?

Thanks!

**Comment by josegonzalez** [comment]
That seems reasonable. Don't know how your processor would schedule it, but my naive thinking on that lines up with what you're trying to do.

**Comment by chiedo** [comment]
Haha thanks man.
