### ISSUE TITLE
nginx.conf server_name is doubled

### ISSUE THREAD

**Issue by mirkogeest** [dokku/dokku#2474]
Description of problem:
Many dokku apps have the server_name twice at /home/dokku/$APP/nginx.conf:

```
server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;
  server_name aaa.bbb.com aaa.bbb2.com aaa2.bbb.com;
  server_name aaa.bbb.com aaa.bbb2.com aaa2.bbb.com;
...
}
```

Thus I get errors like this when restarting nginx:

> nginx: [warn] conflicting server name "aaa.bbb.com" on [::]:443, ignored

This apps were just created this way:

```
git push dokku@XX.XXXX.com:myapp
dokku config:set myapp <many config vars>
dokku domains:add myapp aaa.bbb.com aaa.bbb2.com aaa2.bbb.com
```

When I delete the first doubled line, it is-recreated when executing:
`dokku ps:rebuild myapp`

**Command Outputs:**
- `uname -a`: Linux ip-XXX-XX-XX-XXX 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:

> ```
>          total       used       free     shared    buffers     cached
> ```
> 
> Mem:          7983       7678        305        255        506       5059
> -/+ buffers/cache:       2112       5871- `docker version`:
> - `docker -D info`:
> 
> ```
> Containers: 30
>  Running: 23
>  Paused: 0
>  Stopped: 7
> Images: 192
> Server Version: 1.12.2
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 255
>  Dirperm1 Supported: false
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge null host overlay
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Security Options: apparmor
> Kernel Version: 3.13.0-100-generic
> Operating System: Ubuntu 14.04.5 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 2
> Total Memory: 7.797 GiB
> Name: ip-XXX-XX-XX-XXX
> ID: BOJC:BBD5:6MMO:JCDY:6EGD:2AJY:DE7T:UPS3:BAIV:VEXI:R6UU:2NGC
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): true
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> WARNING: No swap limit support
> Insecure Registries:
>  127.0.0.0/8
> ```
> - `sigil -v`: 0.4.0
> - `docker run -ti gliderlabs/herokuish:latest herokuish version`:
> 
> ```
>   heroku-buildpack-multi     v1.0.0
>   heroku-buildpack-ruby      v146
>   heroku-buildpack-nodejs    v91
>   heroku-buildpack-clojure   v75
>   heroku-buildpack-python    v81
>   heroku-buildpack-java      v44
>   heroku-buildpack-gradle    v17
>   heroku-buildpack-grails    v21
>   heroku-buildpack-scala     v72
>   heroku-buildpack-play      v26
>   heroku-buildpack-php       v109
>   heroku-buildpack-go        v44
>   heroku-buildpack-erlang    fa17af9
>   buildpack-nginx            v5
>   emberjs.tgz                latest
> ```
> - `dokku version`: 0.7.2
> - `dokku plugin`:
> 
> ```
>   00_dokku-standard    0.7.2 enabled    dokku core standard plugin
>   20_events            0.7.2 enabled    dokku core events logging plugin
>   apps                 0.7.2 enabled    dokku core apps plugin
>   build-env            0.7.2 enabled    dokku core build-env plugin
>   certs                0.7.2 enabled    dokku core certificate management plugin
>   checks               0.7.2 enabled    dokku core checks plugin
>   common               0.7.2 enabled    dokku core common plugin
>   config               0.7.2 enabled    dokku core config plugin
>   docker-options       0.7.2 enabled    dokku core docker-options plugin
>   domains              0.7.2 enabled    dokku core domains plugin
>   enter                0.7.2 enabled    dokku core enter plugin
>   git                  0.7.2 enabled    dokku core git plugin
>   logs                 0.7.2 enabled    dokku core logs plugin
>   named-containers     0.7.2 enabled    dokku core named containers plugin
>   nginx-vhosts         0.7.2 enabled    dokku core nginx-vhosts plugin
>   plugin               0.7.2 enabled    dokku core plugin plugin
>   proxy                0.7.2 enabled    dokku core proxy plugin
>   ps                   0.7.2 enabled    dokku core ps plugin
>   repo                 0.7.2 enabled    dokku core repo plugin
>   shell                0.7.2 enabled    dokku core shell plugin
>   ssh-keys             0.7.2 enabled    dokku core ssh-keys plugin
>   storage              0.7.2 enabled    dokku core storage plugin
>   tags                 0.7.2 enabled    dokku core tags plugin
>   tar                  0.7.2 enabled    dokku core tar plugin
> ```
> 
> How was Dokku installed?: sudo DOKKU_TAG=v0.7.2 bash bootstrap.sh

**Comment by josegonzalez** [comment]
Do you have a custom `nginx.conf.sigil` for your app?

**Comment by mirkogeest** [comment]
No, I just installed dokku. I changed/added this lines in /etc/nginx/nginx.conf:

```
        set_real_ip_from   XXX.XX.0.0/16;
        real_ip_header      X-Forwarded-For; #Put the Header that your proxy set

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
```

**Comment by dmr** [comment]
I have a similar issue with a custom `nginx.conf.sigil` :)
Is there a common mistake users make with this?

**Comment by josegonzalez** [comment]
Are you using https by any chance?

**Comment by dmr** [comment]
I didn't have time to track down the issue in full detail but I think I was using https

**Comment by josegonzalez** [comment]
https://github.com/dokku/dokku/pull/2464

It'll go out in the next release :)

**Comment by dmr** [comment]
Thank you!

**Comment by dmr** [comment]
Is there already a plan when the next release will happen?
