### ISSUE TITLE
Disabling application access log

### ISSUE THREAD

**Issue by DanielStejskal** [dokku/dokku#2478]
Is there any simple way to disable access logs on application?

I have high-traffic application and it produces additional load on machine. Thank you

**Comment by josegonzalez** [comment]
There is no built in way to disable logging. To do so, you'd need to copy our nginx template into your application repo and disable logging via nginx config. Documentation surrounding that is available [here](http://dokku.viewdocs.io/dokku/configuration/nginx/).
