### ISSUE TITLE
git submodule update --init failure needs a better error message

### ISSUE THREAD

**Issue by fisxoj** [dokku/dokku#2479]
Description of problem:
Pushing a repo that causes `git submodule update --init` to fail gives a generic error message from git that doesn't point to the real problem.  It would be nice to say that there was a problem checking out a submodule.

In my case, this was because I had bundled some dependencies into my repo and the dependency manger had cloned a repo or two into that bundle.

Output of the following commands

- `uname -a`: Linux podcastinet 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:          1000        845        155          0         64        584
-/+ buffers/cache:        195        804
Swap:            0          0          0
```
- `docker version`: Docker version 1.12.3, build 6b644ec
- `docker -D info`:
- `sigil -v`:
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
- `dokku version`: 0.7.2

Environment details (AWS, VirtualBox, physical, etc.): Digial Ocean

How was Dokku installed?: curl | bash

How reproducible: Every time

Steps to Reproduce:
1. Bundle up a common lisp webapp with [fukamachi/qlot](https://github.com/fukamachi/qlot)
2. Save the `quicklisp/` directory to the app repo
3. Attempt to push to dokku

Actual Results: https://gist.github.com/fisxoj/a4f5784e0398d13375cae96a3ee6d906
```
To podcastinet.com:podcastinet
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@podcastinet.com:podcastinet'
```

Expected Results:

Additional info:

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
