### ISSUE TITLE
`dokku certs:generate` does not add proxy ports

### ISSUE THREAD

**Issue by znz** [dokku/dokku#2480]
Description of problem:
For test environment on vagrant, I use `dokku certs:generate`, but nginx does not listen port 443.

How reproducible:

Steps to Reproduce:
1. `git clone https://github.com/dokku/dokku`
2. `cd dokku`
3. `vagrant up`
4. open `http://10.0.0.2/` and set `, set `Hostname` to `10.0.0.2.xip.io`, check `Use virtualhost naming for apps`, and click `Finish Setup`
5. `vagrant ssh`
6. `git clone git@github.com:heroku/ruby-rails-sample.git`
7. `cd ruby-rails-sample`
8. `git remote add dokku dokku@dokku.me:ruby-rails-sample`
9. `git push dokku master`
10. `dokku certs:generate ruby-rails-sample`, and set `Common Name` to `ruby-rails-sample.10.0.0.2.xip.io`
11. `dokku nginx:build-config ruby-rails-sample`
12. open `http://ruby-rails-sample.10.0.0.2.xip.io/`

Actual Results:
Redirect to `https://ruby-rails-sample.10.0.0.2.xip.io/`, and `Connection refused`.

Expected Results:
Redirect to `https://ruby-rails-sample.10.0.0.2.xip.io/`, and open normally.

Additional info:
- It seems that `plugins/nginx-vhosts/post-certs-update` add proxy ports.
- `plugins/certs/subcommands/add` calls `plugn trigger post-certs-update "$APP"`, but `plugins/certs/subcommands/generate` does not.
- `../dokku-letsencrypt/subcommands/default` uses `dokku certs:add`.

**Comment by josegonzalez** [comment]
Closing as there is now a PR open.
