### ISSUE TITLE
dokku proxy says: touch: cannot touch ‘/home/dokku/bar\nfoo/ENV’: No such file or directory

### ISSUE THREAD

**Issue by znz** [dokku/dokku#2481]
Description of problem:

Output of the following commands

- `dokku version`: v0.7.2-51-gd7c8e47

How was Dokku installed?: `vagrant up`

How reproducible:

Steps to Reproduce:
1. multiple apps created
2. `dokku proxy`

Actual Results:

```
vagrant@dokku:~$ dokku apps:create foo
Creating foo... done
vagrant@dokku:~$ dokku apps:create bar
Creating bar... done
vagrant@dokku:~$ dokku proxy
-----> App Name           Proxy Type
touch: cannot touch ‘/home/dokku/bar\nfoo/ENV’: No such file or directory
bar                       nginx
touch: cannot touch ‘/home/dokku/bar\nfoo/ENV’: No such file or directory
foo                       nginx
```

Expected Results:
Show information without error messages.

**Comment by josegonzalez** [comment]
Can you run the following command and gist the output for us?

```
dokku --trace proxy
```

**Comment by znz** [comment]
Created: https://gist.github.com/znz/c32097482a8f2e65ea2531f08a1073bb

**Comment by znz** [comment]
This issue is similar to https://github.com/dokku/dokku/issues/2029
I think problem is setting `APP` at https://github.com/dokku/dokku/blob/d7c8e47e785ea97308cc53e0fe5df5283e4a7e24/plugins/proxy/subcommands/default#L13

**Comment by josegonzalez** [comment]
Fix incoming, took a bit to get the time to investigate.
