### ISSUE TITLE
can i run nodejs + wordpress both on dokku ?

### ISSUE THREAD

**Issue by LabN36** [dokku/dokku#2483]
Hi, I'm new to dokku with already running nodejs server now i want to run a wordpress site is it possible ?if yes please tell me how can i do it

**Comment by josegonzalez** [comment]
Dokku is capable of running more than one application, you'll simply need to deploy your wordpress site to it.

As far as actually guiding you through that process, you'll have better luck in our [irc/slack](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels) chat groups. Please direct any questions regarding deployment there.
