### ISSUE TITLE
Mention that ports are ignored in CHECKS doc

### ISSUE THREAD

**Issue by kblcuk** [dokku/dokku#2487]
[Current docs](https://github.com/dokku/dokku/blob/master/docs/deployment/zero-downtime-deploys.md#customizing-checks) don't mention whether ports are taken into account in check. They sometimes are (if you use absolute url, like `http://my-host:8080/check OK`), but are ignored in case of `:8080/check OK`).

Probably should just mention that for relatives check, specifying port is not needed.

**Comment by josegonzalez** [comment]
Thanks for the issue!
