### ISSUE TITLE
how to separate dokku apps ?

### ISSUE THREAD

**Issue by LabN36** [dokku/dokku#2499]
let's consider a scenario
i have a dokku powered server which has some apps deloped
now my friend to create an app on it but i dont want him to share my apps, plugins

is it possible ? if yes how can i do this ?

**Comment by josegonzalez** [comment]
Dokku is not setup for multi-tenant systems, nor do we have any immediate plans to implement such a thing in the core.

There are two plugins available:

- https://github.com/mlebkowski/dokku-acl
- https://github.com/mainto/dokku-access

Please refer to their issue trackers for any additional support if you end up using either solution.

**Comment by LabN36** [comment]
1. are they reliable plugin to use ? (according to you)
2. why you don't want to implement this on dokku(i mean what is you thinking behind this)

**Comment by josegonzalez** [comment]
- No idea, have never used them as I don't have the need to. As with all software, you'll need to try them out and see if they suit your needs.
- Multi-tenant systems are inherently harder to build and maintain. As Dokku is an open source project without corporate backing, it's hard for me to justify working on this feature when it's a bit outside of the goal of the software: To provide a great, single-server deployment solution.
