### ISSUE TITLE
[RFC] Collecting User Analytics

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2502]
I'm mostly curious as to what versions and operating systems our users use. I don't care so much for plugins - some might be internal - or commands being run - that's not useful at all.

For anyone who would be against this, here is what this would help with:

- figuring out uptake of new versions
- figuring out what we should be supporting, os-wise
- tracking docker versus dokku versions

A concern people might have is that we are sending metrics somewhere neither they nor we control, and who knows what else we might be running on their systems.

- If we cannot trust Google with the above two bits of information, you certainly can't trust any of the supply chain (Github, Packagecloud, your Hosting provider) with not injecting stuff into your install.
- We already have root when we install Dokku, so the latter point is moot. It's entirely possible that I've been sending all your super secret dog photo sharing app codes to my server (I promise I haven't been).
- We'd set the IP tracking to anonymous. I have no desire to figure out where we are getting installs from, other than potentially the Hosting provider, but even thats not uber useful.

This would be opt-out by default. I have no interest in making it opt-in.

- Opt-out would happen via debconf, so you can avoid the code entirely by setting the proper debconf option and *then* running the install.
- We'd add a tick-box on the web-ui to allow people to opt-out before first use.
- You could opt-in/out at any point in the future via a cli command (we'd document that).
- It'll probably be implemented as a plugin that you can just disable/delete without us being any wiser.
- First run of dokku - before analytics are invoked - would ask the users to confirm that they are okay with sending metrics, and if not, then not send them unless re-enabled.

For the other maintainers, thoughts? It's certainly interesting data, though potentially not more than vanity metrics.

For our users, complaints? I realize this may not be a popular choice, but if we can use the data to better serve our you all - and we make it easy to disable - then I think it's a win.

> Note: This is way far down my implementation pipeline. I'd rather implement some of the other RFCs - the network plugin, log-driver handling - than this. Just wanted to open an RFC to figure out what we should/should not do here.

**Comment by jvanbaarsen** [comment]
@josegonzalez I can absolutly see the usecase for this for you as a maintainer, I do have one concern (Which is almost completly covered in your RFC), when I opt-out will there never be any data send to you? 

Reason for asking this, we have Dokku running as part of a server management tool as a on-premise solution, which has to go through some heavy compliance checks in some cases.

If there is no data going out if you opt-out, I really like this. 
Would you be open in sharing the data in some way?

**Comment by josegonzalez** [comment]
Nah, before the first data-send, we'd prompt. If we can't prompt because there isnt a tty, then we don't send data. If the plugin implementing analytics doesn't exist - because you customized your packaging to remove it - then we don't send data.

Dokku is pretty auditable - it's like 7k lines of code with plugins - you could probably diff our packaging with what is in the repo to figure out if we snuck in code. Though honestly, if you don't trust me in regards to packaging Dokku, I have no idea why you're essentially giving me root on your box (you'd need to for installing plugins for instance).

I'd certainly be willing to share it, most likely in a blog post - maybe once a year, and more often if we get enough data - with whatever data exported as a spreadsheet most likely.

**Comment by jvanbaarsen** [comment]
@josegonzalez I think you understand me wrong :-) It's not about trust from our side, it's from the compliance department in those companies. Also, it's not about auditability. The compliance I'm talking about is mostly about not being allowed to send data to the outside world.

**Comment by josegonzalez** [comment]
Right right. If you set the appropriate debconf setting, we'd respect that right away, no further prompting necessary.

**Comment by joshmanders** [comment]
I'm for it. Nothing better than helping those who help us help us more efficiently.

**Comment by josegonzalez** [comment]
Relevant discussion in the Django community: https://lwn.net/SubscriberLink/707443/5710ef3733710462/

**Comment by josegonzalez** [comment]
Closing this. While we may implement this in the future, at this time there are no "time" resources to devote to making this occur.
