### ISSUE TITLE
git version compatibility

### ISSUE THREAD

**Issue by fruitl00p** [dokku/dokku#2512]
Description of problem:
We're running into issues with the newly released Git version (1:2.11.0-0ppa3~ubuntu14.04.1)
The first push of a project seems to incorrectly create the tag in the repo, and afterwards every other push will fail with the omnimous `! [remote rejected] master -> master (pre-receive hook declined)`

This is probably going to be related to the #2263 issue... (we are running the latest 16.10 after inline upgrades from 14.04 to 16.04 to 16.10) and only started getting these errors with the very latest git version... 

As i couldn't find anyone else with these types of issues...I'm posting it here.. :)

If someone is running into this aswell the way to `resolve` this is to downgrade to a GIT version of (in our case) 1:1.9.1-1

**Comment by josegonzalez** [comment]
What do you mean, "incorrectly create the tag in the repo"? We're going to need trace output from both a working and non-working system on your end to figure out whats going on.

Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by fruitl00p** [comment]
@josegonzalez you're right... I'll try again:

Description of problem:
It seems dokku is incompatible with the latest git (2.11.0) on my 14.04 environment

Output of the following commands

- `uname -a`: ```Linux plunger 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:         12011      11264        747         59       1299       4504
-/+ buffers/cache:       5460       6551
Swap:         2894        465       2429
```
- `docker version`:
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 22
 Running: 8
 Paused: 0
 Stopped: 14
Images: 80
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 243
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-91-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.73 GiB
Name: plunger
ID: CCCI:YFYH:E4AL:YEMJ:6SG3:BTF7:VVEM:L4YC:YAYY:DERT:ZCKD:KPJT
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
- `sigil -v`: ```0.4.0```
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.19
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v82
  heroku-buildpack-java      v46
  heroku-buildpack-gradle    v18
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v110
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v6
  emberjs.tgz                latest
```
- `dokku version`: ```0.7.2```
- `dokku plugin`: 
```
plugn: 0.2.2
  00_dokku-standard    0.7.2 enabled    dokku core standard plugin
  20_events            0.7.2 enabled    dokku core events logging plugin
  apps                 0.7.2 enabled    dokku core apps plugin
  build-env            0.7.2 enabled    dokku core build-env plugin
  certs                0.7.2 enabled    dokku core certificate management plugin
  checks               0.7.2 enabled    dokku core checks plugin
  common               0.7.2 enabled    dokku core common plugin
  config               0.7.2 enabled    dokku core config plugin
  docker-options       0.7.2 enabled    dokku core docker-options plugin
  domains              0.7.2 enabled    dokku core domains plugin
  enter                0.7.2 enabled    dokku core enter plugin
  git                  0.7.2 enabled    dokku core git plugin
  logs                 0.7.2 enabled    dokku core logs plugin
  named-containers     0.7.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.2 enabled    dokku core plugin plugin
  proxy                0.7.2 enabled    dokku core proxy plugin
  ps                   0.7.2 enabled    dokku core ps plugin
  repo                 0.7.2 enabled    dokku core repo plugin
  shell                0.7.2 enabled    dokku core shell plugin
  ssh-keys             0.7.2 enabled    dokku core ssh-keys plugin
  storage              0.7.2 enabled    dokku core storage plugin
  tags                 0.7.2 enabled    dokku core tags plugin
  tar                  0.7.2 enabled    dokku core tar plugin
```
- `docker inspect CONTAINER_ID` (if applicable): n/a
- `cat /home/dokku/<app>/nginx.conf` (if applicable): n/a
- Link to the exact repository being deployed (if possible/applicable): n/a

Environment details (AWS, VirtualBox, physical, etc.): pysical machine

How was Dokku installed?: We installed it a while ago but upgraded from 0.4.3 to 0.7.2 today via ```apt upgrade dokku``` (and found out nothing worked so we did a clean install by removing _everything_ and reinstalling via `apt install dokku`)

How reproducible:
just push a repo, see it fail and try again, see it fail differently... 

Steps to Reproduce:
1. Push a new project to dokku
2. get the following output:
```
Counting objects: 15, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 23.33 KiB | 0 bytes/s, done.
Total 15 (delta 0), reused 0 (delta 0)
To plunger:testapp
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@server:testapp'
```
2. When trying it again:
```
error: refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca does not point to a valid object!
Counting objects: 15, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 23.33 KiB | 0 bytes/s, done.
Total 15 (delta 0), reused 0 (delta 0)
To plunger:testapp
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@plunger:testapp'
```

Expected Results:
1. just work like it always did :)

Additional info:
I've added the trace output in a gist: https://gist.github.com/fruitl00p/c9452e00021af1119d08833b1265f030

**Comment by josegonzalez** [comment]
In your original issue, you said you were using Ubuntu 16.10, not 14.04. What version *doesn't* work right now?

The latest git package available on trusty is `1:1.9.1-1ubuntu0.3`. Are you running a custom ppa for git?

**Comment by fruitl00p** [comment]
@josegonzalez my bad... The ubuntu version ís 14.04.5 and we are using the git-core/ppa. But since dokku doesnt mention a git version compatibility and in the 16.04 updates no mention of `git` was given i'd thought i'd mention it here... 
(16.04 will come with git 2.7.4)

**Comment by josegonzalez** [comment]
Does this issue replicate on 16.04 with the default git version?

**Comment by fruitl00p** [comment]
@josegonzalez vanilla 16.04 seems to work .. (`git version`:2.7.4) Will check the 16.10 now

**Comment by fruitl00p** [comment]
@josegonzalez on 16.10 the `docker-engine`-package has been renamed to `docker.io`-packgage but according to https://github.com/docker/docker/issues/27521 there seems to be some discussion... 

After that the install scripts breaks down on broken packages so unable to test further with the given git version `2.9.3` of ubuntu 16.10

**Comment by josegonzalez** [comment]
Gotcha, so for now I'm going to say we don't support 16.10 at all.

[This line](https://gist.github.com/fruitl00p/c9452e00021af1119d08833b1265f030#file-dokku-git-2-11-0-L615) seems to be whats breaking. Can you modify your dokku install with the newer (broken) git to remove the redirect to dev null to see whats going on there?

**Comment by fruitl00p** [comment]
@josegonzalez 

I've retested it withouth the dev null redirect ():
```
....
remote: + git fetch --depth=1 origin refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca
remote: error: refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca does not point to a valid object!
remote: fatal: Couldn't find remote ref refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca
....
```
it seems the tagging just before that has gone wrong...

```
....
remote: + local APP=testapp
remote: + local REV=703889929c4aca18d67453a210afabba46e6d9ca
remote: ++ mktemp -d /tmp/dokku_git.XXXX
remote: + local GIT_BUILD_APP_REPO_TMP_WORK_DIR=/tmp/dokku_git.GyJn
remote: + trap 'rm -rf "$GIT_BUILD_APP_REPO_TMP_WORK_DIR" > /dev/null' RETURN INT TERM EXIT
remote: + local TMP_TAG=dokku/703889929c4aca18d67453a210afabba46e6d9ca
remote: + chmod 755 /tmp/dokku_git.GyJn
remote: + unset GIT_DIR GIT_WORK_TREE
remote: + pushd /tmp/dokku_git.GyJn
remote: + [[ ! -d /home/dokku/testapp ]]
remote: + GIT_DIR=/home/dokku/testapp
remote: + git tag -d dokku/703889929c4aca18d67453a210afabba46e6d9ca
remote: + GIT_DIR=/home/dokku/testapp
remote: + git tag dokku/703889929c4aca18d67453a210afabba46e6d9ca 703889929c4aca18d67453a210afabba46e6d9ca
remote: + git init
remote: + git config advice.detachedHead false
remote: + git remote add origin /home/dokku/testapp
remote: + git fetch --depth=1 origin refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca
remote: error: refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca does not point to a valid object!
remote: fatal: Couldn't find remote ref refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca
....
````

After removing all the dev null redirects:
```
....
remote: + git_build testapp 703889929c4aca18d67453a210afabba46e6d9ca
remote: + declare 'desc=setup and call git_build_app_repo'
remote: + local APP=testapp
remote: + [[ 2 -ge 2 ]]
remote: + local REF=703889929c4aca18d67453a210afabba46e6d9ca
remote: + git_build_app_repo testapp 703889929c4aca18d67453a210afabba46e6d9ca
remote: + declare 'desc=builds local git app repo for app'
remote: + verify_app_name testapp
remote: + declare 'desc=verify app name format and app existence'
remote: + local APP=testapp
remote: + [[ ! -n testapp ]]
remote: + [[ ! testapp =~ ^[a-z].* ]]
remote: + [[ ! -d /home/dokku/testapp ]]
remote: + return 0
remote: + local APP=testapp
remote: + local REV=703889929c4aca18d67453a210afabba46e6d9ca
remote: ++ mktemp -d /tmp/dokku_git.XXXX
remote: + local GIT_BUILD_APP_REPO_TMP_WORK_DIR=/tmp/dokku_git.7jKD
remote: + trap 'rm -rf "$GIT_BUILD_APP_REPO_TMP_WORK_DIR" > /dev/null' RETURN INT TERM EXIT
remote: + local TMP_TAG=dokku/703889929c4aca18d67453a210afabba46e6d9ca
remote: + chmod 755 /tmp/dokku_git.7jKD
remote: + unset GIT_DIR GIT_WORK_TREE
remote: + pushd /tmp/dokku_git.7jKD
remote: /tmp/dokku_git.7jKD ~/testapp
remote: + [[ ! -d /home/dokku/testapp ]]
remote: + GIT_DIR=/home/dokku/testapp
remote: + git tag -d dokku/703889929c4aca18d67453a210afabba46e6d9ca
remote: Deleted tag 'dokku/703889929c4aca18d67453a210afabba46e6d9ca' (was 7038899)
remote: + GIT_DIR=/home/dokku/testapp
remote: + git tag dokku/703889929c4aca18d67453a210afabba46e6d9ca 703889929c4aca18d67453a210afabba46e6d9ca
remote: + git init
remote: Initialized empty Git repository in /tmp/dokku_git.7jKD/.git/
remote: + git config advice.detachedHead false
remote: + git remote add origin /home/dokku/testapp
remote: + git fetch --depth=1 origin refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca
remote: error: refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca does not point to a valid object!
remote: fatal: Couldn't find remote ref refs/tags/dokku/703889929c4aca18d67453a210afabba46e6d9ca
remote: + rm -rf /tmp/dokku_git.7jKD
remote: fatal: The remote end hung up unexpectedly
remote: + exit_code=128
remote: + set -e
remote: + [[ 128 -eq 10 ]]
remote: + implemented=1
remote: + [[ 128 -ne 0 ]]
remote: + exit 128
....
````

Hope this helps... !

**Comment by bakketun** [comment]
It's not the tagging that fails, but the fetch. I modified the pre-receive hook to do a git show of the tag in the GIT_DIR repository just before the git fetch. That worked fine, yet the fetch still claims the commit is not there. After the push has failed the commit is also not present in the GIT_DIR repository so I get errors that the tag now points to an non-existent commit.

A workaround is to first push to a different branch, then push to master. The first push will ensure the commit is really present.

Based on these observations it looks like newer versions of git stores newly receive objects in some temporary location, which is not accessible when using the repository as a remote.

**Comment by josegonzalez** [comment]
@bakketun good investigation. Not sure what the best fix is here on our end.

**Comment by rrader** [comment]
Encountered same issue on ArchLinux
git version 2.11.0
Dokku version 0.8.0

**Comment by josegonzalez** [comment]
Can someone test this with `git 2.10.0`?

**Comment by beauraF** [comment]
Same issue on Archlinux :
* `git version 2.12.0`
* `dokku 0.8.0`

**Comment by josegonzalez** [comment]
@beauraF can you check 2.11?

**Comment by josegonzalez** [comment]
Hmm, seems like git broke something in `2.11.0` then. Anyone mind reading through the git changelog to see what shenanigans they pulled?

**Comment by beauraF** [comment]
I'm sorry, but I really do not know what to look for in there : https://github.com/git/git/blob/master/Documentation/RelNotes/2.11.0.txt

**Comment by beauraF** [comment]
Seems to work with : `git version 2.12.1`

**Comment by mbreit** [comment]
I think it's this change (from RelNotes/2.11.0.txt):

>  * In order for the receiving end of "git push" to inspect the
   received history and decide to reject the push, the objects sent
   from the sending end need to be made available to the hook and
   the mechanism for the connectivity check, and this was done
   traditionally by storing the objects in the receiving repository
   and letting "git gc" expire them.  Instead, store the newly
   received objects in a temporary area, and make them available by
   reusing the alternate object store mechanism to them only while we
   decide if we accept the check, and once we decide, either migrate
   them to the repository or purge them immediately.

**Comment by josegonzalez** [comment]
Oh great. Anyone want to dig into how we would get them from the temporary area?

**Comment by mbreit** [comment]
One solution could be to refactor `git_build_app_repo()` to use `git worktree`. That seems to work inside a pre-receive hook and is much cleaner (and more space efficient) than the current cloning approach. The problem is that git worktree was introduced in git 2.5, so that would require two code paths and some git feature detection to support systems with older git versions like Ubuntu 14.04.

**Comment by josegonzalez** [comment]
I think either way we'd have two code-paths. I'm fine with that though.

**Comment by mbreit** [comment]
Okay, then I can try to create a pull request for that.
Any idea how to do the feature detection?
`git help -a | grep -q worktree` would do the trick but I am not sure if I like that...

**Comment by josegonzalez** [comment]
Just detect it based on git version?

**Comment by mbreit** [comment]
Yeah, that will work. ;)

**Comment by bakketun** [comment]
Don't forget to initialize submodules in the new workdir:
`git submodule update --init`

**Comment by mbreit** [comment]
@bakketun Of course I have: https://github.com/mbreit/dokku/commit/0127958c1883e59309e56df8399189c2c9982697
I am doing some testing now but so far it looks good, so expect a PR today.
