### ISSUE TITLE
dokku apps using ubuntu 16?

### ISSUE THREAD

**Issue by seibelj** [dokku/dokku#2513]
I see that dokku has official ubuntu 16 support. However, when I use the apt buildpack (https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt) to install packages, the repos checked are for ubuntu 14 (trusty). Sample `apt-get update` output that happens on push:

```
-----> Updating apt caches
       Hit http://apt.postgresql.org trusty-pgdg InRelease
       Ign http://archive.ubuntu.com trusty InRelease
       Hit http://archive.ubuntu.com trusty-security InRelease
       Hit http://apt.postgresql.org trusty-pgdg/main amd64 Packages
       Hit http://archive.ubuntu.com trusty-updates InRelease
       Hit http://archive.ubuntu.com trusty Release.gpg
       Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
       Hit http://archive.ubuntu.com trusty Release
       Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
       Hit http://archive.ubuntu.com trusty/main amd64 Packages
       Hit http://archive.ubuntu.com trusty/universe amd64 Packages
```

How can I make sure that dokku apps also run in ubuntu 16 containers? I can't find any documentation for this. It is odd to me that I'm running ubuntu 16 as the instance's operating system, yet the containers are ubuntu 14. There is a specific package I need that is only available in ubuntu 16. Is there some setting or config I can set to force this?

**Comment by seibelj** [comment]
For example, I need `php-mbstring`, and the git push error output is:

```
-----> Fetching .debs for php-mbstring
       Reading package lists...
       Building dependency tree...
remote: E: Unable to locate package php-mbstring
remote: ls: cannot access /cache/apt/cache/archives/*.deb: No such file or directory
```

Which is right - this package is not in trusty, it's in ubuntu 16.

**Comment by josegonzalez** [comment]
Nope. Herokuish - the docker container we use to emulate heroku for all buildpack deploys - is a clone of Heroku's current cedar stack, which uses Ubuntu 14.04 as it's base. We won't be changing that until Heroku decides to update their stack to something newer.

I apologize if this throws a wrench in your workflow. You are welcome to use a [custom Dockerfile](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/) for deploying to Dokku, which is something we fully support.

**Comment by seibelj** [comment]
Ah thanks, makes sense. I need to get the buildpack to use php5 rather than php7, but that's my issue. Unless you know something off the top of your head to help me do that, this issue is done.

**Comment by josegonzalez** [comment]
If you want to use a different php version, you'll need to handle that in your `composer.json`.

**Comment by seibelj** [comment]
yep I figured it out 👍 thanks for all your time
