### ISSUE TITLE
cannot push the same code to different app

### ISSUE THREAD

**Issue by abhishekscript** [dokku/dokku#2514]
Description of problem:
I have created two apps on the machine ,
fl_data_microservice_dev and fl_data_microservice , I can **successfully** deploy my app to fl_data_microservice but whenever I try deploying my code to fl_microservice_dev it says 

`remote: =====> Application deployed:`
 `remote:        http://<MY-HOST> :5001`
 `remote: To <MY-HOST>:fl_data_microservice_dev`
 `! [remote rejected] master -> master (shallow update not allowed)`
`error: failed to push some refs to 'dokku@<MY_HOST>:fl_data_microservice_dev'`

For a moment I can see application deployed and next it fails.

I also change my port to 5000 for fl_microservice and   5001 for _dev so that there is no port issue 

Here is the log of fl_microservice app that is successfully deployed
`remote: =====> Application deployed:`
`remote:        http://<MY-HOST>:5000`
`remote: To <MY-HOST>:fl_data_microservice `
`   68514b4..28dea19  master -> master`

Am I missing something  ?  Can we not deploy the same code to different apps on the same machine with different ports ?

Any help would be appreciated. Thanks.

**Comment by josegonzalez** [comment]
Can you show the entire push logs, as well as the initial command you ran?

**Comment by abhishekscript** [comment]
On host machine I did :
1) wget https://raw.githubusercontent.com/dokku/dokku/v0.7.2/bootstrap.sh
2) sudo DOKKU_TAG=v0.7.2 bash bootstrap.sh
3) entered my ssh keys

Now from local machine the same 2 git commands.
Here is the entire log
http://pastebin.com/1mqKT76U

**Comment by josegonzalez** [comment]
What is the *exact* git push command you ran?

**Comment by abhishekscript** [comment]
This is the exact command , with correct dokku app.
git remote add dokku dokku@<IP-ADDR>:fl_data_microservice
git push dokku master

**Comment by josegonzalez** [comment]
Is your local repository a shallow clone?

**Comment by abhishekscript** [comment]
Ok yes , you are right , this solved my problem.
**git fetch --unshallow**

Thanks

**Comment by arusa** [comment]
If someone else also gets this problem while using a GitLab Pipeline to deploy to dokku. GitLab introduced a new variable `git depth` that is set to 50 by default.
Changing it to "0" in your project CI/CD General pipelines settings solves the problem.
Also you could add `git fetch --unshallow` before the git push in `.gitlab-ci.yml`
