### ISSUE TITLE
[Question] DigitalOcean and block volumes

### ISSUE THREAD

**Issue by GesJeremie** [dokku/dokku#2520]
Hey guys, I played last week end with Dokku + Digital Ocean and deployed successfully 4 different apps in different languages in less than 1hour, my experience was just ... amazing, thanks for that!

Still, the 20GB space disk of the droplet were full after that. I saw Digital Ocean provides a new feature called Block Storage: https://www.digitalocean.com/community/tutorials/how-to-use-block-storage-on-digitalocean to expand the size of the droplet for a cheap price than resize the droplet to a bigger plan.

I'm quite a noob with devops and I would like to know if it's possible to install Dokku on the block storage, if so, how ?

Thanks for everything guys and keep up the good work <3

**Comment by josegonzalez** [comment]
Someone tried [this](https://github.com/dokku/dokku/pull/2501) to get everything on block storage, but it still needs some work.

**Comment by GesJeremie** [comment]
At the end (and I didn't know it back then) I wanted to "move" the folder /var/lib/docker to the block storage. It was simple as creating a symlink.

```
1) Stop docker: service docker stop. Verify no docker process is running ps faux
2) Double check docker really isn't running. Take a look at the current docker directory: ls /var/lib/docker/
2b) Make a backup - tar -zcC /var/lib docker > /mnt/pd0/var_lib_docker-backup-$(date +%s).tar.gz
3) Move the /var/lib/docker directory to your new partition: mv /var/lib/docker /mnt/pd0/docker
4) Make a symlink: ln -s /mnt/pd0/docker /var/lib/docker
5) Take a peek at the directory structure to make sure it looks like it did before the mv: ls /var/lib/docker/ (note the trailing slash to resolve the symlink)
6) Start docker back up service docker start
```

Source: https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169/2

I did the instructions above after I've created the droplet and setup the Volume of digital ocean.

This is really awesome, I have a PAAS for $10 / month ($5 droplet + $5 for 50GB), and I can scale the space disk up to 16TB, how cool is that!

Thanks for this awesome project, you did amazing.
