### ISSUE TITLE
error while installing dokku on aws

### ISSUE THREAD

**Issue by LabN36** [dokku/dokku#2521]
hi I'm trying to setup dokku on aws ec2
but I'm getting this error

root@ip-172-131-63-194:~# wget https://raw.githubusercontent.com/progrium/dokku/
v0.7.2/bootstrap.sh sudo DOKKU_TAG=v0.7.2 bash
--2016-12-06 17:13:30--  https://raw.githubusercontent.com/progrium/dokku/v0.7.2
/bootstrap.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.32.13
3
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.32.1
33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5299 (5.2K) [text/plain]
Saving to: `bootstrap.sh'

100%[======================================>] 5,299       --.-K/s   in 0s

2016-12-06 17:13:30 (105 MB/s) - `bootstrap.sh' saved [5299/5299]

--2016-12-06 17:13:30--  http://sudo/
Resolving sudo (sudo)... failed: Name or service not known.
wget: unable to resolve host address `sudo'
--2016-12-06 17:13:30--  http://dokku_tag=v0.7.2/
Resolving dokku_tag=v0.7.2 (dokku_tag=v0.7.2)... failed: Name or service not kno
wn.
wget: unable to resolve host address `dokku_tag=v0.7.2'
--2016-12-06 17:13:30--  http://bash/
Resolving bash (bash)... failed: Name or service not known.
wget: unable to resolve host address `bash'
FINISHED --2016-12-06 17:13:30--
Total wall clock time: 0.3s
Downloaded: 1 files, 5.2K in 0s (105 MB/s)

please help

**Comment by joshmanders** [comment]
`wget https://raw.githubusercontent.com/progrium/dokku/
v0.7.2/bootstrap.sh` and `sudo DOKKU_TAG=v0.7.2 bash bootstrap.sh` need to be ran independently. Looks to me that you ran them all together so wget was trying to resolve `sudo` and `bash` as urls.

**Comment by josegonzalez** [comment]
You turned the `|` into a `/`. Please copy/paste the installation command *exactly* as it is written.

**Comment by LabN36** [comment]
wget https://raw.githubusercontent.com/dokku/dokku/v0.7.2/bootstrap.sh
sudo DOKKU_TAG=v0.7.2 bash bootstrap.sh this is what is did but not working there is no '|' in my command

**Comment by joshmanders** [comment]
You need to run `wget https://raw.githubusercontent.com/dokku/dokku/v0.7.2/bootstrap.sh` and when that's finished, then run `sudo DOKKU_TAG=v0.7.2 bash bootstrap.sh`

You were running them at the same time, and wget was trying to resolve `sudo` and `bash` as hostnames.

**Comment by josegonzalez** [comment]
@joshmanders mind finding all installation instances and adding a semicolon after the wget statement so this issue doesn't happen again?

**Comment by joshmanders** [comment]
@josegonzalez yup, I can do that tonight after work.

**Comment by LabN36** [comment]
there is one more problem I've encountered when actually it install successfully and when i access my IP a dokku setup open is display and there was some public key already there so click the **Finish Setup Button** not I'm not able to push my code to server it say permission denied I've .pem file of aws and the public key (which is came autofilled) please help I've not getting any solution in web

**Comment by LabN36** [comment]
the autofilled public key was like that 
**no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10" ssh-rsa A_LONG_STRING dokku**

I've noted it down but can push my code, whats the problem heare

1. I've also run dokku ssh-key:list command which is empty
2. I'm able to ssh in my server by using this command ssh -i aws.pem ubuntu@ipAdd but not but ssh ubuntu@ipAdd
3. I've also tried to enter my key in authorized_key as **ssh-rsa A_long_string dokku** then i pressed Ctrl+O ans Ctrl+X and when i go to that file again my key is there by don't know what's the problem

please please guide me what I'm doing wrong
