### ISSUE TITLE
Bootstrapping Dokku on OpenStack doesn't work

### ISSUE THREAD

**Issue by andyjeffries** [dokku/dokku#2524]
Trying to bootstrap Dokku on an OpenStack Mitaka instance doesn't work. The reason is that this command fails:

```
docker build -t gliderlabs/herokuish /var/lib/herokuish
```

The curl to an HTTPS URL times out. This is because of a change in Docker where it no longer uses the MTU from the host, as described [here](https://github.com/docker/docker/issues/20178).

The fix I found is to then go in to where your `$DOCKER_OPTS` are passed in and add in the MTU of your OpenStack installation (from `ifconfig`, generally 1450 seems like the right value) using the format `-mtu=1450`. For example on Ubuntu 16.04 the file to edit is `/lib/systemd/system/docker.service` and it should look like this:

```
ExecStart=/usr/bin/dockerd -H fd:// -mtu=1450
```

My proposed solution is to somehow pass `$DOCKER_OPTS` in to `bootstrap.sh`, that way we can also customise the `--dns` flag so it uses OpenStack's DNS servers not Google's. I don't know how you'd want to do this given that `bootstrap.sh` supports multiple distributions and each has a different way of configuring docker to start though.

Output of Docker version (I don't think most of the other commands are relevant)

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Comment by andyjeffries** [comment]
I've been testing this further and on multiple instances and it definitely works with that setting. Is there anything I can do to help get this fix in? Any tips on how to integrate this in to bootstrap.sh?

**Comment by joshmanders** [comment]
Can you submit a PR with tests accompanying it so we can verify it works?

**Comment by andyjeffries** [comment]
I can't find any tests currently for bootstrap.sh, are there any? I'm not very good in Bash, but if you can give me a pointer in the right direction I'm happy to have a go! :-)

**Comment by josegonzalez** [comment]
In our bootstrap script, we simply depend on docker being installed. You can install docker beforehand and configure it to use whatever options you want.

I don't think the solution here involves any changes in Dokku core - modifying a user's docker settings seems like it would be annoying for some users and non-trivial for us to do properly - so I am closing this.
