### ISSUE TITLE
how to git push on aws based dokku server

### ISSUE THREAD

**Issue by LabN36** [dokku/dokku#2527]
**Objective I want to push a hello world express server on dokku server (AWS Ubuntu)
Note: I have window machine on my local** 

**1.** created Ubuntu 14.x in aws and created foo.pem file

**2.** now i opend my window localterminal and typed
**ssh -i foo.pem ubuntu@35.154.69.145** 
successfully ssh into server

3. installed dokku on ubuntu by this command
**wget https://raw.githubusercontent.com/dokku/dokku/v0.7.2/bootstrap.sh**
then **sudo DOKKU_TAG=v0.7.2 bash bootstrap.sh**

4. now dokku is installed on ubuntu server 

4.1 when i hit IP **35.154.69.145** in browser a dokku page is opened asking for public key 
so i went to this directory in my local computer **C:\Users\rishabhagrawal\.ssh and opened id_rsa.pub** file which seems like this

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOf5zqKXvDzcHOPi+C2qMj42iVZ8KIpgEu5FxjktkWcBTVJL84D0W71TP4khTX8g76okFU7otLQHyr08h71NxNl223mHmnhvIxyReA5n9A4/azu+nwZ2F4p92TrioPMRNPz+TvMdOxra3fsDbfM2HzZZE4dCtiu+dGHTS5lhl5Mpy7XZY2paEosvotU/faBs3DKPniC+Vh1yVuWnP/m273JUaYHv/XslSgtopbPtwAWm2EJmoJruaVdoAwxGQJwFnBuZOTKAX8P8JQcMH93eqy4JcguIRWWRZylLQEC1QYxIMMFUvFiU4sU+255PJ6J2cajHRUhOjacacy3Sw31CUZ rishabhagrawal@Rishab4231

after clicking ok the dokku page dissappear and i thought my public key might be added successfully

but when in run this command **dokku:ssh-keys:list** after ssh into server i got **no public key found**

so i think i should run **dokku:ssh-keys:add command**
**Note:** this is my location where my public key is exist in my local machine C:\\Users\\rishabhagrawal\\.ssh\\id_rsa.pub

i run **sudo dokku ssh-keys:add admin C:\Users\rishabhagrawal\.ssh\id_rsa.pub** from my local machine after ssh 
**output** cat: C:Usersrishabhagrawal\\.sshid_rsa.pub: no such file or directory

i run this sudo dokku ssh-keys:add admin C:\\Users\\rishabhagrawal\\.ssh\\id_rsa.pub
**output** cat: C:\Users\rishabhagrawal\.ssh\id_rsa.pub: no such file or directory

i run this sudo dokku ssh-keys:add admin C:/Users/rishabhagrawal/.ssh/id_rsa.pub
**output** cat: C:/Users/rishabhagrawal/.ssh/id_rsa.pub: no such file or directory

i run this sudo dokku ssh-keys:add admin C://Users//rishabhagrawal//.ssh//id_rsa.pub
**output** cat: C://Users//rishabhagrawal//.ssh//id_rsa.pub: no such file or directory

after all this attempt i go this this link
http://stackoverflow.com/questions/4632749/how-to-push-to-git-on-ec2
they said To copy your local ssh key to amazon try this
cat ~/.ssh/id_?sa.pub | ssh -i amazon-generated-key.pem ec2-user@amazon-instance-public-dns "cat >> .ssh/authorized_keys"

so in my case i run this from my lcoal machine
**cat C:\Users\rishabhagrawal\.ssh\id_rsa.pub | ssh -i fbm.pem ubuntu@35.154.69.145 "cat >> .ssh/authorized_keys"**
**after running this command i got nothing in the terminal** 

i thought my key might be added on the dokku
so i run **dokku ssh-keys:list to check this** 
output **/home/dokku/.ssh/authorized_keys failed ssh-keygen check.**

**5.** after ssh into server from my local machine i run this command to check for the key
**cd /home/dokku/.ssh
then nano authorized_key**
after this i got a file opend like this 
command="FINGERPRINT=4b:5d:b0:27:80:9f:cb:ca:0a:95:b8:20:4d:25:b5:48 NAME=\"admin\" `cat /home/dokku/.sshcommand` $SSH_ORIGINAL_COMMAND",no-agent-forwading,no-user-rc,no-X11-forwarding,no-port-farwarding
 no-port-farwarding ,no-agent-forwading,no-X11-forwarding,command="echo 'Please login as the user ubuntu rather than the user root echo sleet 10 ssh-rsa A_LONG_STRING_KEY fbm
 
**Note:**i think this key is not as i provided in the above 

**6.** I want to push a hello world express server on dokku 
so i cloned a hello world repository then run this command from the repository

**git remote add dokku dokku@35.154.69.145:test**
then i run **git push dokku master**
output: **permission denied (publickey)**
**fatal could not read from remote repository
please make sure you have the correct access right and the repository exist**

then i also run this command
**git remote add ubuntu ubuntu@35.154.69.145:test**
then i run **git push ubuntu master**

again i got the same error

can anyone guide me what is the problem

**Comment by joshmanders** [comment]
Like stated from the other day, you need to ssh into your machine from root/ubuntu user, and `sudo su dokku` to change to dokku user. Then you need to run this command:

```
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOf5zqKXvDzcHOPi+C2qMj42iVZ8KIpgEu5FxjktkWcBTVJL84D0W71TP4khTX8g76okFU7otLQHyr08h71NxNl223mHmnhvIxyReA5n9A4/azu+nwZ2F4p92TrioPMRNPz+TvMdOxra3fsDbfM2HzZZE4dCtiu+dGHTS5lhl5Mpy7XZY2paEosvotU/faBs3DKPniC+Vh1yVuWnP/m273JUaYHv/XslSgtopbPtwAWm2EJmoJruaVdoAwxGQJwFnBuZOTKAX8P8JQcMH93eqy4JcguIRWWRZylLQEC1QYxIMMFUvFiU4sU+255PJ6J2cajHRUhOjacacy3Sw31CUZ rishabhagrawal@Rishab4231 | dokku ssh-keys:add admin`

Your ways of doing it was wrong, because it was trying to find an ssh key on the server that doesn't exist.

**Comment by LabN36** [comment]
when run above command after **sudo su dokku** it says this command must be run as root so i append  sudo before the command but after this it's asking me for password :(
![password](https://cloud.githubusercontent.com/assets/10628287/21082281/ad55ff88-bffe-11e6-9d2b-79d2c22dd4c4.png)

**Comment by joshmanders** [comment]
Okay, that's because dokku user is not in root, so exit out of that user and make sure you're connected as `root` or `ubuntu` and run the command prefixed with `sudo` and it should work

**Comment by LabN36** [comment]
when i run this command i did ssh -i fbm.pem ubuntu@35.154.69.145

**Comment by joshmanders** [comment]
As long as `ubuntu` user has access to sudo, and I assume it does, because you were able to `sudo su dokku`, just run the command as that user prefixed with `sudo` and it should work.

**Comment by LabN36** [comment]
step1:  ssh -i fbm.pem ubuntu@35.154.69.145
step2: sudo su dokku
step3: echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOf5zqKXvDzcHOPi+C2qMj42iVZ8KIpgEu5FxjktkWcBTVJL84D0W71TP4khTX8g76okFU7otLQHyr08h71NxNl223mHmnhvIxyReA5n9A4/azu+nwZ2F4p92TrioPMRNPz+TvMdOxra3fsDbfM2HzZZE4dCtiu+dGHTS5lhl5Mpy7XZY2paEosvotU/faBs3DKPniC+Vh1yVuWnP/m273JUaYHv/XslSgtopbPtwAWm2EJmoJruaVdoAwxGQJwFnBuZOTKAX8P8JQcMH93eqy4JcguIRWWRZylLQEC1QYxIMMFUvFiU4sU+255PJ6J2cajHRUhOjacacy3Sw31CUZ rishabhagrawal@Rishab4231 | dokku ssh-keys:add admin

this is what i did 
yo
![fuckedup](https://cloud.githubusercontent.com/assets/10628287/21082382/674a82dc-c000-11e6-8051-88aed50066e1.png)

**Comment by joshmanders** [comment]
step1: ssh -i fbm.pem ubuntu@35.154.69.145
step3: echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOf5zqKXvDzcHOPi+C2qMj42iVZ8KIpgEu5FxjktkWcBTVJL84D0W71TP4khTX8g76okFU7otLQHyr08h71NxNl223mHmnhvIxyReA5n9A4/azu+nwZ2F4p92TrioPMRNPz+TvMdOxra3fsDbfM2HzZZE4dCtiu+dGHTS5lhl5Mpy7XZY2paEosvotU/faBs3DKPniC+Vh1yVuWnP/m273JUaYHv/XslSgtopbPtwAWm2EJmoJruaVdoAwxGQJwFnBuZOTKAX8P8JQcMH93eqy4JcguIRWWRZylLQEC1QYxIMMFUvFiU4sU+255PJ6J2cajHRUhOjacacy3Sw31CUZ rishabhagrawal@Rishab4231 | sudo dokku ssh-keys:add admin

**Comment by LabN36** [comment]
when i run step 2 it says this command must be run as root

**Comment by joshmanders** [comment]
Please show screenshot so I can verify you ran it correctly.

**Comment by LabN36** [comment]
now its saying Duplicate SSH key name
ssh command returned an error :255

**Comment by joshmanders** [comment]
Okay, what does `dokku ssh-keys:list` show?

**Comment by LabN36** [comment]
/home/dokku/.ssh/authorized_keys failed ssh-keygen check

**Comment by PAStheLoD** [comment]
Excuse my interjection, I just found this thread (sort of the same problem, I just installed dokku 0.7.2 on an Ubuntu 16.04 VM and tried to add another ssh key).

Why does dokku need to be run as root, when /home/dokku/.ssh/authorized_keys is writeable by dokku?

**Comment by joshmanders** [comment]
Okay, open that file up in `vi` and delete the contents of it.

**Comment by joshmanders** [comment]
@PAStheLoD The whole `ssh-keys` plugin requires to be ran as root. https://github.com/dokku/dokku/blob/master/plugins/ssh-keys/user-auth#L8

**Comment by joshmanders** [comment]
@LabN36 once you've cleared out the contents of `/home/dokku/.ssh/authorized_keys` so that it's empty, run step2 again and it should work, then `dokku ssh-keys:list` should show that key in there. Now you should be able to `ssh dokku@35.154.69.145` and get the outputs of the dokku command.

**Comment by joshmanders** [comment]
Why this all stopped working is, aws sets `root`'s `authorized_keys` file to tell you to use `ubuntu` user and not `root`, when you install dokku it grabs the contents of this file, and throws it into the form on the web installer. You need to clear out that form and paste in your own key. Otherwise this error happens.

Maybe we can figure out a way to sanitize the key @josegonzalez?

**Comment by LabN36** [comment]
thanks a ton!! finally solved the problem :)
