### ISSUE TITLE
How to reduce filesize

### ISSUE THREAD

**Issue by madshargreave** [dokku/dokku#2529]
My application images are continuously growing in size and is now reaching 5gb+

What's the best way to diagnose/reduce these?

**Comment by FilipLukac** [comment]
@madshargreave - do you have some persistent storage ? (photos, documents, uploads, etc..?)

**Comment by madshargreave** [comment]
Yes I have a postgres instance, but that lives in separate container

**Comment by FilipLukac** [comment]
@madshargreave id dosnt matter, you have connected these two together.. maybe your data in your database are growing

**Comment by madshargreave** [comment]
Database is only 400mb, yet the images has grown 2-3gb of the last couple of months

**Comment by josegonzalez** [comment]
For buildpack apps, write less code/use fewer dependencies - especially for Node applications, which tend to balloon dependency trees. You may also wish to clear your cache using `dokku repo:purge-cache APP`, which could clear out unused deps that may be mounted for some reason.

For dockerfile containers, same applies, though you could try using a smaller base image, like alpine linux.
