### ISSUE TITLE
Is Buildstep still necessary?

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#2530]
In a 2 years old [article](http://donpottinger.net/blog/2014/11/17/bye-bye-heroku-hello-dokku.html) I read that "Dokku uses Buildstep to build applications using Heroku’s buildpacks".
I could not find any other information about it.
The progrium/buildstep GitHub repository seems inactive: the last opened issue is more than one year old.
So I am wondering: is Buildstep still necessary?
I am interested in creating a Droplet at DigitalOcean and I do not understand whether is it still necessary or not more necessary, as suggested by the above article, to update Buildstep to use the supported buildpacks with the following command:

docker pull progrium/buildstep:latest

**Comment by joshmanders** [comment]
Dokku has the buildstep already in it, you don't need to pull it. Just install dokku like normal, or use the dokku image on DO.

**Comment by michaelshobbs** [comment]
To clarify, dokku now uses [herokuish](https://github.com/gliderlabs/herokuish) to deploy apps using a heroku-style buildpack. Herokuish is not necessary for dockerfile-based apps and the image is pulled automatically during the installation (or in the DO case, the droplet provisioning) process. 

Hope this clears things up.
