### ISSUE TITLE
Proposal: make HTTP 410 for unknown hosts default behaviour

### ISSUE THREAD

**Issue by pascalw** [dokku/dokku#2534]
I include the following snippet found [in the docs](http://dokku.viewdocs.io/dokku/configuration/domains/#default-site) in literally all my Dokku installs.

```
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name _;
  return 410;
  log_not_found off;
}
```

I would like to propose to make this the default behaviour. Routing traffic to the lexicographically first host is super confusing and I can't even think of a use case where this would be desirable.

Please let me know what you think.

**Comment by pascalw** [comment]
Hey @josegonzalez @michaelshobbs what do you think?

**Comment by josegonzalez** [comment]
@michaelshobbs thoughts? I'm 👎 as we'd need to both:

- delete the default site - who knows if the dev has set a custom one
- set an 00-default - ditto

**Comment by pascalw** [comment]
Hey @josegonzalez thanks for your response. Indeed that's a good point I didn't consider. I would really like this to be the default behaviour but going about that in a backwards compatible way is probably tricky for the points you outlined.

Is it feasible to apply this behaviour only to new installs? E.g. only create this default host on new installs but not on update?

**Comment by josegonzalez** [comment]
It's not even a backwards compatibility thing. If a developer sets a custom default site via configuration management, we'll almost certainly just steamroll over it if we do either of the two things above. For instance, on the Dokku servers I've been setting up, I setup a default vhost site that displays all the deployed sites.

**Comment by michaelshobbs** [comment]
We had this convo back in the day and decided to just document this as an option instead of forcing it on folks. nginx config can be very custom based on the need and thus I think forcing a system-wide config is undesirable.

**Comment by pascalw** [comment]
Ok fair enough. I still think it's a bad default but given your arguments I can understand why it is the way it is.
