### ISSUE TITLE
Please specify an app to run the command on

### ISSUE THREAD

**Issue by pynixwang** [dokku/dokku#2537]
Description of problem:
when I use dokku cli, I always forgot to specify app name, heroku does 'nt need app name when you navigate into app folder. can we implement this feature?

Output of the following commands

- `dokku version`:
`0.7.2`

**Comment by josegonzalez** [comment]
What cli? You mean directly on the server, or locally?

**Comment by pynixwang** [comment]
@josegonzalez dokku command itself

**Comment by pynixwang** [comment]
server!

**Comment by josegonzalez** [comment]
How do you think we'd know what app you want to run a command on if you run the `dokku` bin directly on the server?

**Comment by pynixwang** [comment]
@josegonzalez navigate into app folder.

**Comment by pynixwang** [comment]
heroku maybe get it from git remote url

**Comment by josegonzalez** [comment]
Yeah but you run the `heroku` command locally, not on the server. If you use our dokku cli in the contrib folder locally, then it'll emulate what heroku does.

**Comment by josegonzalez** [comment]
Yes.

**Comment by pynixwang** [comment]
@josegonzalez thanks.
