### ISSUE TITLE
`docker-options` does not pass any arguments to `docker run`

### ISSUE THREAD

**Issue by RaitoBezarius** [dokku/dokku#2541]
Description of problem:
When setting some arguments with `docker-options` to an application.
After `dokku ps:rebuild` or `dokku ps:restart`, the arguments set (actually: UDP ports mapping) are not passed to `docker run` invocation.

Output of the following commands

- `uname -a`:
> Linux some-host 4.5.7-docker-4 #1 SMP Tue Jul 12 09:41:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
              total        used        free      shared  buff/cache   available
 Mem:           2001         905         624          74         470         776
 Swap:             0           0           0
- `docker version`:
> Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

> Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

- `docker -D info`:
> Containers: 35
 Running: 10
 Paused: 0
 Stopped: 25
Images: 170
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 260
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.5.7-docker-4
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: some-host
ID: LSAG:JQBU:SZK3:IZ6C:P46O:67VG:TTZY:OCVZ:WVAZ:DDMW:7U72:YZRV
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=scaleway
Insecure Registries:
 127.0.0.0/8

- `sigil -v`:
> 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
> herokuish: 0.3.19
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v82
  heroku-buildpack-java      v46
  heroku-buildpack-gradle    v18
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v110
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v6
  emberjs.tgz                latest
- `dokku version`:
> 0.7.2
- `dokku plugin`:
> plugn: 0.2.2
  00_dokku-standard    0.7.2 enabled    dokku core standard plugin
  20_events            0.7.2 enabled    dokku core events logging plugin
  apps                 0.7.2 enabled    dokku core apps plugin
  build-env            0.7.2 enabled    dokku core build-env plugin
  certs                0.7.2 enabled    dokku core certificate management plugin
  checks               0.7.2 enabled    dokku core checks plugin
  common               0.7.2 enabled    dokku core common plugin
  config               0.7.2 enabled    dokku core config plugin
  deployment-keys      0.1.0 enabled    Manage SSH deployment keys that should get injected into your containers on-build
  docker-options       0.7.2 enabled    dokku core docker-options plugin
  domains              0.7.2 enabled    dokku core domains plugin
  enter                0.7.2 enabled    dokku core enter plugin
  git                  0.7.2 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.7.2 enabled    dokku core logs plugin
  mariadb              1.0.0 enabled    dokku mariadb service plugin
  named-containers     0.7.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.2 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.7.2 enabled    dokku core proxy plugin
  ps                   0.7.2 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  repo                 0.7.2 enabled    dokku core repo plugin
  robots.txt           0.1.0 enabled    manage robots.txt for applications
  shell                0.7.2 enabled    dokku core shell plugin
  slack                0.4.0 enabled    Slack notifier on deploy
  ssh-keys             0.7.2 enabled    dokku core ssh-keys plugin
  storage              0.7.2 enabled    dokku core storage plugin
  tags                 0.7.2 enabled    dokku core tags plugin
  tar                  0.7.2 enabled    dokku core tar plugin
- Link to the exact repository being deployed (if possible/applicable): https://gitlab.com/sgl-eng/ebot-docker

Environment details (AWS, VirtualBox, physical, etc.): Scaleway.

How was Dokku installed?: `curl` method.

Steps to Reproduce:
1. Set up a MariaDB container: `dokku mariadb:create ebot-db`
2. Create an `ebot` app, without NGINX proxy: `dokku apps:create ebot && dokku proxy:disable ebot`
3. Link the MariaDB container to it: `dokku mariadb:link ebot-db ebot`
4. Do `docker-options:add ebot run "-p 0.0.0.0:some_port:12360/udp"`
5. `dokku ps:restart`
6. Inspect the container with Docker or Dokku, no mappings to the UDP port, i.e. `dokku ls` or `docker ps` or `netstat` or `nmap -sU hostname -p some_port`.

Actual Results:

Dokku proxy the `12360` TCP port to a random port on the host.

Expected Results:

Dokku should have proxied the `12360` UDP port to the `some_port` on the host.

Additional info:

According to the `trace`, I see no `docker-options` args passed on the `docker run` invocation.

**Comment by josegonzalez** [comment]
Should be `docker-options:add`, no space between the commands. Try that?

**Comment by RaitoBezarius** [comment]
@josegonzalez Sorry, I meant that I can see that the options are added to the `docker-options` because when I do `docker-options`, I get a list of all options, including the new ones I specified.

**Comment by josegonzalez** [comment]
> Create an ebot app, without NGINX proxy!

Whats that mean? What steps *exactly* are you running?

**Comment by RaitoBezarius** [comment]
@josegonzalez `dokku apps:create ebot && dokku proxy:disable ebot`

**Comment by josegonzalez** [comment]
You actually want to use the `deploy` phase, not `run`:

```
dokku docker-options:add ebot deploy "-p 0.0.0.0:12360:12360/udp"
```

The run phase is for `dokku run` calls, not `docker run` calls.
