### ISSUE TITLE
Dokku apps:create won't generate a git bare

### ISSUE THREAD

**Issue by abnerlee** [dokku/dokku#2543]
Description of problem:

Output of the following commands

- `uname -a`: Linux typora 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:           489        421         68          0         18        336
-/+ buffers/cache:         66        423
Swap:            0          0          0
```
- `docker version`:
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: typora
ID: ECQQ:SHAK:7N5U:BNUL:GAMH:YETK:GBJY:OCNR:GKBC:2E7K:WTU2:ORNU
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
```
- `sigil -v`: `0.4.0`
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.13
buildpacks:
  emberjs.tgz                latest
  buildpack-nginx            v5
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v36
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v90
  heroku-buildpack-php       v102
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v70
```
- `dokku version`: 0.6.5
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.6.5 enabled    dokku core standard plugin
  20_events            0.6.5 enabled    dokku core events logging plugin
  apps                 0.6.5 enabled    dokku core apps plugin
  build-env            0.6.5 enabled    dokku core build-env plugin
  certs                0.6.5 enabled    dokku core certificate management plugin
  checks               0.6.5 enabled    dokku core checks plugin
  common               0.6.5 enabled    dokku core common plugin
  config               0.6.5 enabled    dokku core config plugin
  docker-options       0.6.5 enabled    dokku core docker-options plugin
  domains              0.6.5 enabled    dokku core domains plugin
  enter                0.6.5 enabled    dokku core enter plugin
  git                  0.6.5 enabled    dokku core git plugin
  logs                 0.6.5 enabled    dokku core logs plugin
  named-containers     0.6.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.6.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.6.5 enabled    dokku core plugin plugin
  proxy                0.6.5 enabled    dokku core proxy plugin
  ps                   0.6.5 enabled    dokku core ps plugin
  repo                 0.5.3 enabled    dokku core repo plugin
  shell                0.6.5 enabled    dokku core shell plugin
  storage              0.6.5 enabled    dokku core storage plugin
  tags                 0.6.5 enabled    dokku core tags plugin
  tar                  0.6.5 enabled    dokku core tar plugin
```
- `docker inspect CONTAINER_ID` (if applicable):
```
[]
Error: No such image or container: CONTAINER_ID
```
- `cat /home/dokku/<app>/nginx.conf` (if applicable): no such file

Environment details (AWS, VirtualBox, physical, etc.): Digital Ocean dokku image (v0.6.5)

How was Dokku installed?:

Installed when creating Digital Ocean droplets with one-click app.

How reproducible:

Steps to Reproduce:
1. `dokku apps:create test`
2. `cd /home/dokku/test`
3. `ls -a`

Actual Results:
`. ..` (the folder is empty)

Expected Results:
shouldn't be a git repo so I won't get `fatal: 'test' does not appear to be a git repository` when I push from my client machine?

Additional info:

**Comment by josegonzalez** [comment]
This is working as expected. You are getting an error for a different reason. What version of Ubuntu and Git are you using?

**Comment by abnerlee** [comment]
Ubuntu 14.04.4 LTS and git version 1.9.1

**Comment by abnerlee** [comment]
Correct me if I am wrong: If `dokku apps:create` does not create a server bare, how to `git push dokku master` without error

**Comment by abnerlee** [comment]
And if I do `git init --bare` in that empty folder, I can do push, but won't trigger dokku rebuild...

**Comment by joshmanders** [comment]
That's because there's more to setting up the app than just `git init --bare` as done here https://github.com/dokku/dokku/blob/master/plugins/git/functions#L97-L107

**Comment by abnerlee** [comment]
But I think `dokku apps:create` should do the setup, and adding files like `nginx.conf`, but it didn't

**Comment by josegonzalez** [comment]
No,`apps:create` does not do any setup other than calling the post-create hook and creating the directory. This is working as intended, so it sounds like you have another issue thats going on in regards to pushing code. Can you gist the output of a `git push dokku master` call?

**Comment by abnerlee** [comment]
it is solved if I do not use the 3 auto-filled ssh key in dokku setup page, but only fill one ssh key in dokku setup page.
