### ISSUE TITLE
Cloudformation/AMIs for AWS?

### ISSUE THREAD

**Issue by matthewmueller** [dokku/dokku#2545]
I was wondering if there are any existing Cloudformation/AMIs/terraform modules or official instructions for getting up and running on AWS?

I've been spinning up dokku boxes using Digital Ocean, which has been fantastic, but I'm wondering if there are any information on getting that setup in a reproducible way on AWS?

**Comment by josegonzalez** [comment]
I've personally been using a set of ansible playbooks - complete with native ansible roles, check the tweets for `dokku` for screenshots - but we don't have an official AMI. That costs money, so we'd need to sell it for me to recoup hosting costs. Is that something you're interested in? I think a nominal fee (a dollar? idk what it would be) is probably fine.

**Comment by matthewmueller** [comment]
Oh that's lame – I didn't realize that. I guess it seems like a public Cloudformation would be the way to go then. I'll write an email to AWS to see if they can host it or waive the cost of an AMI. 

For those coming to this later, here's the links to the Ansible screenshots: 

- https://twitter.com/savant/status/815348124529152000
- https://twitter.com/savant/status/815346528034426880

Just discovered this terraform module too: https://github.com/dhinus/dokku-terraform

Cloudformation seems the most future proof, so maybe I'll put something together if I don't find anything. Thanks for the info!

**Comment by matthewmueller** [comment]
Doing a bit more searching, this also seems really promising: https://halotis.com/deploying-a-python-flask-app-on-amazon-lightsail-with-dokku/

**Comment by josegonzalez** [comment]
Yeah, I basically ran my ansible playbooks on the cheapest lightsail box, worked great.

**Comment by josegonzalez** [comment]
Closing as there isn't much to do here :)

**Comment by tobiasmcnulty** [comment]
For anyone stumbling across this issue, I thought this would actually be pretty handy to have, and put together a simple CloudFormation template here:

https://github.com/tobiasmcnulty/dokku-aws
