### ISSUE TITLE
Build process inconsistently ignoring .buildpacks file

### ISSUE THREAD

**Issue by kevinob11** [dokku/dokku#2551]
Description of problem: I use a .buildpacks file, about ~75% of the time when I deploy it uses the 3 buildpacks I have defined in that file, ~25% of the time it ignores that file and just uses the nodejs buildpack.

Output of the following commands

- `uname -a`: `Linux app 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- `free -m`:
```
              total        used        free      shared  buff/cache   available
Mem:          32167         743       21579         147        9843       30586
Swap:         32765           0       32765
```
- `docker version`:
```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 14
 Running: 7
 Paused: 0
 Stopped: 7
Images: 59
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.41 GiB
Name: app
ID: 3IKX:NTFH:HGIF:CQ5D:YQ4D:YIMX:CCLM:EPNG:EGNT:UAGA:THZE:AWB7
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
- `sigil -v`: `0.4.0`
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.19
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v82
  heroku-buildpack-java      v46
  heroku-buildpack-gradle    v18
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v110
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v6
  emberjs.tgz                latest
```
- `dokku version`: `0.7.2`
- `dokku plugin`:
```
plugn: 0.2.2
  00_dokku-standard    0.7.2 enabled    dokku core standard plugin
  20_events            0.7.2 enabled    dokku core events logging plugin
  apps                 0.7.2 enabled    dokku core apps plugin
  build-env            0.7.2 enabled    dokku core build-env plugin
  certs                0.7.2 enabled    dokku core certificate management plugin
  checks               0.7.2 enabled    dokku core checks plugin
  common               0.7.2 enabled    dokku core common plugin
  config               0.7.2 enabled    dokku core config plugin
  docker-options       0.7.2 enabled    dokku core docker-options plugin
  domains              0.7.2 enabled    dokku core domains plugin
  enter                0.7.2 enabled    dokku core enter plugin
  git                  0.7.2 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.7.2 enabled    dokku core logs plugin
  named-containers     0.7.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.2 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.7.2 enabled    dokku core proxy plugin
  ps                   0.7.2 enabled    dokku core ps plugin
  repo                 0.7.2 enabled    dokku core repo plugin
  shell                0.7.2 enabled    dokku core shell plugin
  ssh-keys             0.7.2 enabled    dokku core ssh-keys plugin
  storage              0.7.2 enabled    dokku core storage plugin
  tags                 0.7.2 enabled    dokku core tags plugin
  tar                  0.7.2 enabled    dokku core tar plugin
```
- `docker inspect CONTAINER_ID` (if applicable): N/A
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable): N/A
- Link to the exact repository being deployed (if possible/applicable): Can't
- If a deploy is failing or behaving unexpectedly:
  - Application name: `praece-portal-staging-api`
  - The type of application being deployed (node, php, python, ruby, etc.): multi buildpack nodejs
  - If using buildpacks, which custom buildpacks are in use
```
.buildpacks

https://github.com/heroku/heroku-buildpack-apt.git
https://github.com/captain401/heroku-buildpack-xvfb.git
https://github.com/heroku/heroku-buildpack-nodejs.git
```
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`: `web: node app.js`
- Output of failing Dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.): hyper-v

How was Dokku installed?: standard curl

How reproducible: I'm not sure it is reproducible, as it is only this repo, happy to dig into repro'ing with a simpler sample repo.

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Additional info:

**Comment by josegonzalez** [comment]
Can you create a simple repository for me to reproduce the issue?

**Comment by josegonzalez** [comment]
Closing as we haven't had any feedback in two weeks. Feel free to comment with the information I asked for and we can reopen the issue as necessary.

**Comment by kevinob11** [comment]
Sorry didn't see your request, I'll get this tested with trace-enabled deploys soon.

**Comment by josegonzalez** [comment]
Related issue: https://github.com/gliderlabs/herokuish/issues/232

**Comment by kevinob11** [comment]
I posted over there
