### ISSUE TITLE
`nginx` is not a dokku command.

### ISSUE THREAD

**Issue by rogovdm** [dokku/dokku#2561]
Description of problem:

after running
`
dokku nginx
`
the response is following

`
nginx is not a dokku command.
`

Output of the following commands

- `uname -a`:
Linux dokku-512mb-lon1-01 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- `free -m`:
             total       used       free     shared    buffers     cached
Mem:           489        380        109          1         30         72
-/+ buffers/cache:        277        212
Swap:         2047        192       1855

- `docker version`:
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

- `docker -D info`:
Containers: 17
 Running: 6
 Paused: 0
 Stopped: 11
Images: 57
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 94
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: dokku-512mb-lon1-01
ID: VPLB:L2CF:MZ6T:NKFX:SZZD:6556:6HG7:357B:7FWO:M2KG:F6DV:2C3D
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/

- `sigil -v`:
0.4.0

**Comment by rogovdm** [comment]
Same with `dokku certs`

**Comment by josegonzalez** [comment]
Closed by #2508.
