### ISSUE TITLE
Pushing to Dokku with FQDN not working

### ISSUE THREAD

**Issue by OmgImAlexis** [dokku/dokku#2568]
Description of problem:
When pushing with a FQDN subdomain Dokku launches the app on the first global domain instead of the one specified.

Environment details (AWS, VirtualBox, physical, etc.):
Dokku version 0.8.0
DigitalOcean Dokku one click app

How reproducible:
It happens every time.

Steps to Reproduce:
1. `dokku domains:add-global wvvw.me #Server`
2. `git remote add dokku dokku@SERVER_IP:api.wvvw.me #Client`
3. `git push dokku master #Client`

Actual Results:
```
➜  wvvw.me git:(master) git push dokku master
Counting objects: 3336, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2398/2398), done.
Writing objects: 100% (3336/3336), 7.82 MiB | 1.18 MiB/s, done.
Total 3336 (delta 820), reused 3310 (delta 806)
-----> Cleaning up...
-----> Building api.wvvw.me from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 6.9.1...
       Using default npm version: 3.10.8
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (0.18.1)...
       Installed yarn 0.18.1
       
-----> Restoring cache
       Skipping cache restore (new runtime signature)
       
-----> Building dependencies
       Installing node modules (yarn)
       yarn install v0.18.1
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       Done in 10.03s.
       
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
       
-----> Build succeeded!
       
       yarn ls v0.18.1
       info Visit https://yarnpkg.com/en/docs/cli/list for documentation about this command.
       
-----> Discovering process types
       Procfile declares types -> api
-----> Releasing api.wvvw.me (dokku/api.wvvw.me:latest)...
-----> Deploying api.wvvw.me (dokku/api.wvvw.me:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> App Procfile file found (/home/dokku/api.wvvw.me/DOKKU_PROCFILE)
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> api=0
-----> Running post-deploy
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
=====> Application deployed:
       http://twistly.xyz
       wvvw.me

To SERVER_IP:api.wvvw.me
 * [new branch]      master -> master
```

Expected Results:
Application to deploy to domain specified.

**Comment by josegonzalez** [comment]
What domain do you expect your application to be available on?

**Comment by OmgImAlexis** [comment]
From what I can figure from the docs I should be able to use api.wvvw.me to access it since I have wvvw.me set as a global domain. I'm not sure if I read the docs wrong or this just isn't supported.

**Comment by josegonzalez** [comment]
Is `twistly.xyz` the actual domain in use?

**Comment by OmgImAlexis** [comment]
It's the domain I used on setup. Both domains have `@` and `*` DNS entries pointing to the dokku machine.

**Comment by OmgImAlexis** [comment]
I've just tried running the app destroy command and re pushing and now it's showing the app on `twistly.xyz` even thought the push command ends in this.

```
=====> Application deployed:
       http://api.wvvw.me
       http://api.wvvw.me.wvvw.me
```

**Comment by josegonzalez** [comment]
Yeah so what we do is we try and see if its a domain name you are pushing to. If it looks like one, we'll use that. We also will use the app name as a prefix to the global domain.

My gut reaction here is that you didn't have a global domain name set at first - I responded right as you logged off on IRC about that - and so the domain you thought you were pushing to wasn't being picked up. Once you added it, the app still was in a "no-domain" mode, so thats why your custom domain wasn't being picked up.

I would just name your app `api` and push it up. You can manage domains separately after that using the `domains` plugin.

**Comment by OmgImAlexis** [comment]
@josegonzalez check the above comments. This looks like a bug in a sense. I do now have it "working" but it's serving the content on multiple domains instead of just the one provided.


I think you may be right about the domain not being set until after. I actually got kicked from IRC as I moved to wifi instead of ethernet. Oops.


The reason I don't want to rename to api is that I have all my sites using a js frontend with the data coming from an api subdomain and I'd like move all my sites over to a single dokku install.

**Comment by josegonzalez** [comment]
> This looks like a bug in a sense. I do now have it "working" but it's serving the content on multiple domains instead of just the one provided.

From our [domains documentation](http://dokku.viewdocs.io/dokku/configuration/domains/#customizing-hostnames):

> If a FQDN such as other.tld is used as the application name, the default $DOKKU_ROOT/VHOST will be ignored and the resulting vhost URL for that application will be other.tld. The exception to this rule being that if the FQDN has the same ending as the default vhost (such as subdomain.domain.tld), then the entire FQDN will be treated as a subdomain. The application will therefore be deployed at subdomain.domain.tld.domain.tld.

As far as renaming:

> The reason I don't want to rename to api is that I have all my sites using a js frontend with the data coming from an api subdomain and I'd like move all my sites over to a single dokku install.

I don't see what that has to do with renaming your application.

**Comment by OmgImAlexis** [comment]
So basically I should manage all domains manually instead of dokku just seeing this as a sub domain of a global domain and configuring itself automatically?

> I would just name your app api and push it up. You can manage domains separately after that using the domains plugin.
If I name the app api then for the next app I'll call it api_1? This should just accept the subdomain as a valid one since it has the root domain added as a global domain and then route it correctly, no?

**Comment by josegonzalez** [comment]
If you set the app name to `api`, dokku will automatically pick up the full domain as `api.example.com`, where `example.com` is your global domain name. If you don't want that at all, you can simply then do the following to completely override your application's domain name:

```shell
dokku domains:set APP api.another-domain.tld
```

> If I name the app api then for the next app I'll call it api_1? This should just accept the subdomain as a valid one since it has the root domain added as a global domain and then route it correctly, no?

Domains cannot have underscores in them, so if anything, you'd name it `api-1`. Regardless, I don't quite understand this comment. If you join us on slack or irc, we can clear this up, but I don't think there is any bug as documented.
