### ISSUE TITLE
Currenty running node.js application fails to deploy

### ISSUE THREAD

**Issue by j-klassen** [dokku/dokku#2571]
I have a currently running node.js application, and when attempting the run `dokku deploy jobs` I get the following output:

```
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> Running 'npm run build' in app container
       restoring installation cache...
       /bin/bash: npm: command not found
execution of 'npm run build' failed!
```

I've deployed several version of this application so far with no issue, today I attempted a new push and no luck. I tried the command above to see if I could restart the app.

**app.json contents**:

```json
{
  "name": "jobs",
  "scripts": {
    "dokku": {
      "predeploy": "npm run build"
    }
  },
  "buildpacks": [
    {
      "url": "https://github.com/heroku/heroku-buildpack-nodejs"
    }
  ]
}

```

**Results from `dokku report`**

```
-----> uname: Linux AppServer-1 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:            488         174          26           4         287         276
Swap:             0           0           0
-----> docker version: 
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
-----> docker daemon info: 
Containers: 22
 Running: 1
 Paused: 0
 Stopped: 21
Images: 21
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.5 MiB
Name: AppServer-1
ID: G55O:K2MT:DJCC:TRYZ:VQM3:C6MX:NCL2:WS3G:JJTL:5L2P:UMDQ:77AV
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.19
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v82
  heroku-buildpack-java      v46
  heroku-buildpack-gradle    v18
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v110
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v6
  emberjs.tgz                latest
-----> dokku version: 0.7.2
-----> dokku plugins: 
plugn: 0.2.2
  00_dokku-standard    0.7.2 enabled    dokku core standard plugin
  20_events            0.7.2 enabled    dokku core events logging plugin
  apps                 0.7.2 enabled    dokku core apps plugin
  build-env            0.7.2 enabled    dokku core build-env plugin
  certs                0.7.2 enabled    dokku core certificate management plugin
  checks               0.7.2 enabled    dokku core checks plugin
  common               0.7.2 enabled    dokku core common plugin
  config               0.7.2 enabled    dokku core config plugin
  docker-options       0.7.2 enabled    dokku core docker-options plugin
  domains              0.7.2 enabled    dokku core domains plugin
  enter                0.7.2 enabled    dokku core enter plugin
  git                  0.7.2 enabled    dokku core git plugin
  logs                 0.7.2 enabled    dokku core logs plugin
  named-containers     0.7.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.2 enabled    dokku core plugin plugin
  proxy                0.7.2 enabled    dokku core proxy plugin
  ps                   0.7.2 enabled    dokku core ps plugin
  repo                 0.7.2 enabled    dokku core repo plugin
  shell                0.7.2 enabled    dokku core shell plugin
  ssh-keys             0.7.2 enabled    dokku core ssh-keys plugin
  storage              0.7.2 enabled    dokku core storage plugin
  tags                 0.7.2 enabled    dokku core tags plugin
  tar                  0.7.2 enabled    dokku core tar plugin
```

**Tail of trace log (after ENV variables) when running `dokku deploy jobs`**:

```
+ for line in '$(docker logs "$CID" 2>&1)'
+ dokku_log_verbose_quiet '+ [[ -d /cache ]]'
+ declare 'desc=log verbose formatter (with quiet option)'
+ [[ -z '' ]]
+ echo '       + [[ -d /cache ]]'
       + [[ -d /cache ]]
+ for line in '$(docker logs "$CID" 2>&1)'
+ dokku_log_verbose_quiet '+ echo restoring installation cache...'
+ declare 'desc=log verbose formatter (with quiet option)'
+ [[ -z '' ]]
+ echo '       + echo restoring installation cache...'
       + echo restoring installation cache...
+ for line in '$(docker logs "$CID" 2>&1)'
+ dokku_log_verbose_quiet '+ rm -rf /tmp/cache'
+ declare 'desc=log verbose formatter (with quiet option)'
+ [[ -z '' ]]
+ echo '       + rm -rf /tmp/cache'
       + rm -rf /tmp/cache
+ for line in '$(docker logs "$CID" 2>&1)'
+ dokku_log_verbose_quiet 'restoring installation cache...'
+ declare 'desc=log verbose formatter (with quiet option)'
+ [[ -z '' ]]
+ echo '       restoring installation cache...'
       restoring installation cache...
+ for line in '$(docker logs "$CID" 2>&1)'
+ dokku_log_verbose_quiet '+ ln -sf /cache /tmp/cache'
+ declare 'desc=log verbose formatter (with quiet option)'
+ [[ -z '' ]]
+ echo '       + ln -sf /cache /tmp/cache'
       + ln -sf /cache /tmp/cache
+ for line in '$(docker logs "$CID" 2>&1)'
+ dokku_log_verbose_quiet '+ npm run build'
+ declare 'desc=log verbose formatter (with quiet option)'
+ [[ -z '' ]]
+ echo '       + npm run build'
       + npm run build
+ for line in '$(docker logs "$CID" 2>&1)'
+ dokku_log_verbose_quiet '/bin/bash: npm: command not found'
+ declare 'desc=log verbose formatter (with quiet option)'
+ [[ -z '' ]]
+ echo '       /bin/bash: npm: command not found'
       /bin/bash: npm: command not found
+ IFS=' 	
'
+ dokku_log_fail 'execution of '\''npm run build'\'' failed!'
+ declare 'desc=log fail formatter'
+ echo 'execution of '\''npm run build'\'' failed!'
execution of 'npm run build' failed!
+ exit 1
```

**Procfile Contents:** `web: npm start`

**Environment details (AWS, VirtualBox, physical, etc.):** Digital Ocean box.

**How was Dokku installed?:** Via curl and the `bootstrap.sh` on the front page.

**Comment by josegonzalez** [comment]
If you're using nodejs, why not just use the build scripts as documented [here](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process)?

I'm guessing npm isn't in the path that is executing. If you can do

```
echo $PATH && npm run build
```

That might help us diagnose the issue.

**Comment by j-klassen** [comment]
Thanks for the link. I've updated `package.json` to use `scripts.postinstall` and attempted to push my local branch. I get the following output.

```
Counting objects: 69, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (64/64), done.
Writing objects: 100% (69/69), 23.42 KiB | 0 bytes/s, done.
Total 69 (delta 33), reused 0 (delta 0)
-----> Cleaning up...
-----> Building jobs from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  6.9.1
       engines.npm (package.json):   3.10.9
       
       Downloading and installing node 6.9.1...
       Downloading and installing npm 3.10.9 (replacing version 3.10.8)...
       
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules (not cached - skipping)
       - bower_components (not cached - skipping)
       
-----> Building dependencies
       Installing node modules (package.json)
remote: /tmp/buildpacks/02_buildpack-nodejs/lib/dependencies.sh: line 10:   340 Killed                  npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1
       
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
To 159.203.63.193:jobs
 ! [remote rejected] build-issue -> master (pre-receive hook declined)
```

**Comment by josegonzalez** [comment]
Seems like you have a low-memory system. For nodejs, we recommend *at least* 1GB of memory, if not 2GB. You can enable swap memory as mentioned in [this troubleshooting doc](http://dokku.viewdocs.io/dokku/getting-started/troubleshooting/) under "Symptom: Build fails with Killed message."

**Comment by j-klassen** [comment]
@josegonzalez Thanks, increasing to 1GB seems to have fixed the issue.

**Comment by nelsonic** [comment]
In `case` anyone `else` has this issue ... 
we are using a **2GB** DigitalOcean instance ($10/month)
and our **node.js** app _still_ would not build (_because of some rather large dependencies..._).
Running the "swapfile" script Joes refers to above http://dokku.viewdocs.io/dokku/getting-started/troubleshooting and creating the 2GB swapfile solved the "failing build" issue 
and now our app deploys fine.
Thanks!

(_it still seems strange that dokku/docker would **need** more than 2GB to install node.js dependencies and build an app that is comparatively "small" ... I am **curious** why this is the case!_)

**Comment by josegonzalez** [comment]
@nelsonic I think you sort of answered your question.

> and our node.js app still would not build (because of some rather large dependencies...).

Dokku has very little memory overhead - it's mostly shell executing more shell. Docker has some memory overhead, but its also pretty negligible. The thing that uses memory is the nodejs processes involved in actually building your code.

I would guess that you develop on a machine with 8GB or 16GB of ram, and haven't ever actually benchmarked memory usage. NPM/Webpack/Nodejs build tools have been notorious at inhaling memory, and you could probably find memory leak issues in their issue trackers pretty easily. Heroku even has a nice article about [memory usage with nodejs](https://devcenter.heroku.com/articles/node-memory-use). We recommend 2gb of RAM minimum because many build processes are just very bad at memory management.

Many CI platforms allocate 4GB or 8GB of ram - [TravisCI differs depending on the platform](https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System) - and some even allow swap. I believe heroku actually uses larger build servers for compiling slugs - this gives users a faster build experience and also skirts the initial resource usage problem.

Folks also don't realize that hosted environments such as Heroku provide a minimum amount of memory for their processes. While you may be affected by noisy neighbors, each build/running dyno is _guaranteed_ at least X CPU/Memory. That isn't the case on your own self-hosted server, where you are probably running multiple apps - likely without any resource constraints - and also have to deal with OS overhead. If you have 2 apps already running and are deploying one of them, the resources used by the running apps don't just magically disappear during the build :( . Some folks get around this by using a separate build Dokku server, and then deploy the resulting images on others - this is actually the process I use for HA Dokku, and how many build/deploy pipelines handle it.

So yes, it does seems strange that your "comparatively small" app with "some rather large dependencies" would use so much ram for building resulting application code. As with any piece of code, benchmarking this locally and on a Linux host _outside_ of the Dokku build process to see true resource usage would be the best way to figure out what bottlenecks exist in your system, and potentially raise the issues with the correct developers for the piece of software that is at fault.

This was a long way of saying "Dokku/Docker aren't the problem here, its the nodejs build ecosystem." Hope that all makes sense.

**Comment by joshmanders** [comment]
Is there something we can do to mitigate such issues being posted and bumped by detecting the text output by the fail and supply a more helpful error message?

**Comment by nelsonic** [comment]
Hi @josegonzalez, I have a habit of using _emphasis_ in comments ... it's not intended as anything more than formatting style. I wouldn't dream of "attacking" you, just _thanking_ you for the ***amazing*** work you have done on Dokku and your generosity with your time! ❤️

**Comment by josegonzalez** [comment]
@joshmanders the only thing would be tee'ing the contents out to stdout/stderr as well as something else that greps the output for `Killed`.

I'd also be fine with just a big, fat warning when nodejs is detected, saying that folks need a lot more ram than they expect.

**Comment by joshmanders** [comment]
I'll toy around with stuff and maybe I can manage to make a build failure catching plugin that will look for common errors and give better help messages on what's going on.
