### ISSUE TITLE
dokku enter doesn't work with containers missing bash

### ISSUE THREAD

**Issue by OmgImAlexis** [dokku/dokku#2572]
`dokku enter` should fall back to sh is bash is missing since 99% of containers will have at least sh.

Currently if you try and run `dokku enter` on a container/app without bash you get this ugly message.

```
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\"\n"
```

**Comment by josegonzalez** [comment]
Any way to detect this?

**Comment by OmgImAlexis** [comment]
Maybe try using launching sh with a wrapper, something like this?

```
if [ -f /bin/bash ]
then
    bash
else
   sh
fi
```

**Comment by josegonzalez** [comment]
I actually don't think this is possible without injecting a script into the container. Currently we do the [following](https://github.com/dokku/dokku/blob/master/plugins/enter/subcommands/default#L54):

```shell
docker exec $DOKKU_RUN_OPTS $ID $EXEC_CMD "${@:-/bin/bash}"
```

Which doesn't lend itself well to what you'd like. You could do the following though:

```shell
dokku enter APP sh
```

@OmgImAlexis do you have a sample app that has `sh` and not `bash`?

**Comment by OmgImAlexis** [comment]
Here's a static file app I use.
https://github.com/OmgImAlexis/test.pymedusa.com

Would it be possible then to try bash and if it returns an error then try sh?

This is the current error that's returned.
```
root@dokku-512mb-nyc1-01:~# dokku enter test.pymedusa.com
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\"\n"
```

**Comment by chrisnicola** [comment]
I'm seeing this issue during the executing of app.json predeploy scripts. Looks like it trys to use /bin/bash to execute. This fails with alpine linux images. Simple solution is installing bash, but that doesn't seem like the ideal.

```
remote: docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory".
remote: execution of 'rake db:migrate' failed!
       container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory"
```

**Comment by chrisnicola** [comment]
Seems similar to #1364

**Comment by josegonzalez** [comment]
I think there are two issues here:

- Some images don't have bash (@chrisnicola mentioned one such case). This affects app.json scripts.
- A user may sometimes wish to have a shell different from bash.

I think we can solve both cases by making the shell configurable (`/bin/bash` by default) and using that shell to execute scripts. We should also document that the value may need to be set in the deployment task and enter documentation.

I think switching to `sh` as the default shell isn't a great experience, and in the absence of someone making a pull request to do that, I will simply make the change to enable the manual change.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
