### ISSUE TITLE
Dokku can think that app is not deployed after lack of HDD space

### ISSUE THREAD

**Issue by mspanc** [dokku/dokku#2577]
Description of problem:

One of my apps have eaten whole disk space today. After freeing some space, and rebooting the server dokku did not launched one of the apps, and kept saying `App myapp has not been deployed` unless I have pushed code again.

Version:

```
-----> uname: Linux dokku-ovh1-002 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
              total        used        free      shared  buff/cache   available
Mem:          32074         439       30556          39        1078       31150
Swap:          1532           0        1532
-----> docker version:
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
-----> docker daemon info:
Containers: 32
 Running: 4
 Paused: 0
 Stopped: 28
Images: 57
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /home/docker/aufs
 Backing Filesystem: extfs
 Dirs: 147
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32 GiB
Name: dokku-ovh1-002
ID: TKDU:6J5B:6A6N:37VT:TVR7:3UZP:SQQW:NEQS:DJB5:Y7VW:F627:KJVR
Docker Root Dir: /home/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
-----> sigil version: 0.4.0
-----> herokuish version:
herokuish: 0.3.24
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v150
  heroku-buildpack-nodejs    v93
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v97
  heroku-buildpack-java      v48
  heroku-buildpack-gradle    v19
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v117
  heroku-buildpack-go        v54
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.8.0
-----> dokku plugins:
plugn: 0.2.2
  00_dokku-standard    0.8.0 enabled    dokku core standard plugin
  20_events            0.8.0 enabled    dokku core events logging plugin
  apps                 0.8.0 enabled    dokku core apps plugin
  build-env            0.8.0 enabled    dokku core build-env plugin
  certs                0.8.0 enabled    dokku core certificate management plugin
  checks               0.8.0 enabled    dokku core checks plugin
  common               0.8.0 enabled    dokku core common plugin
  config               0.8.0 enabled    dokku core config plugin
  docker-options       0.8.0 enabled    dokku core docker-options plugin
  domains              0.8.0 enabled    dokku core domains plugin
  enter                0.8.0 enabled    dokku core enter plugin
  git                  0.8.0 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.8.0 enabled    dokku core logs plugin
  named-containers     0.8.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.8.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.8.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.8.0 enabled    dokku core proxy plugin
  ps                   0.8.0 enabled    dokku core ps plugin
  repo                 0.8.0 enabled    dokku core repo plugin
  shell                0.8.0 enabled    dokku core shell plugin
  ssh-keys             0.8.0 enabled    dokku core ssh-keys plugin
  storage              0.8.0 enabled    dokku core storage plugin
  tags                 0.8.0 enabled    dokku core tags plugin
  tar                  0.8.0 enabled    dokku core tar plugin
```

Environment details (AWS, VirtualBox, physical, etc.):

Bare metal server

How was Dokku installed?:

Ansible script:

```
- name: Dokku - Install Dokku apt key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Dokku - Add Dokku apt repository
  apt_repository: repo="deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main" state=present

- name: Dokku - Set DOKKU_VHOST_ENABLE debconf variable
  shell: 'echo "dokku dokku/vhost_enable boolean true" | debconf-set-selections'

- name: Dokku - Set DOKKU_WEB_CONFIG debconf variable
  shell: 'echo "dokku dokku/web_config boolean false" | debconf-set-selections'

- name: Dokku - Set DOKKU_HOSTNAME debconf variable
  shell: 'echo "dokku dokku/hostname string {{ansible_fqdn}}" | debconf-set-selections'

- name: Dokku - Set DOKKU_SKIP_KEY_FILE debconf variable
  shell: 'echo "dokku dokku/skip_key_file boolean true" | debconf-set-selections'

- name: Dokku - Ensure that Dokku is in the latest version
  apt: pkg=dokku state=latest
```

How reproducible:

Rarely, just try to destabilize docker in such way that it fails to launch containers, e.g. due to lack of hard drive space.

Steps to Reproduce:
1. Fill HDD

Actual Results:

App boots

Expected Results:

App does not boot
Additional info:

**Comment by josegonzalez** [comment]
Try `dokku ps:rebuild APP`.

**Comment by mspanc** [comment]
I know how to fix it, I think that should just not happen. Or dokku should issue `ps:rebuild` automatically in such case. So I disagree with `type:support` label, I think it's an improper behaviour.

**Comment by josegonzalez** [comment]
@mspanc Well I want to know what it does in this case. It's currently a support issue because filling your filesystem will cause all sorts of weird behavior on an operating system, and as I don't know how you manage your infra, I can't be sure that you didn't accidentally delete files you shouldn't have.

For reference, we output that message when there are [no CONTAINER files](https://github.com/dokku/dokku/blob/master/plugins/common/functions#L382) for your app, meaning to me that you either deleted those or some other thing corrupted your disk, resulting in those files somehow disappearing.

**Comment by mspanc** [comment]
I had to rebuild the app as it happened on the production server, but I will check out what is happening next time. I am pretty sure that I had not deleted anything. I filled DB by creating and index on huge table within postgresql container. After reboot docker kept restarting containers. When I released some space it had launched some containers, but some left dead.

**Comment by josegonzalez** [comment]
I mean as I showed you, our check for whether an application is deployed is pretty simple. Either the files exist or they don't.

You may also want to save the syslog output, as when a box comes back up, we run `ps:restore`, which may have been failing for you for other reasons.

**Comment by josegonzalez** [comment]
I'm thinking that what happened here is you actually deleted the `/var/lib/docker` paths associated with an app, so docker couldn't start the service. We currently try to [restore all applications](https://github.com/dokku/dokku/blob/master/plugins/ps/subcommands/restore#L7), and warn when that doesn't occur properly.

Our `ps:restore` logs should be shipped to your syslog, but in cases where you don't have any disk space, they'll probably be piped to /dev/null. Once you free up disk space, it should log back to syslog.

We also use a restart policy of `10` restarts after failed starts before stopping. It's possible that you ran out of restarts and docker stopped attempting after that. Nothing we can do there.

Without docker/dokku logs, there isn't much investigation to do here, so I'm closing this for now. If it happens again and you can retrieve more logging information, we can reopen this issue.
