### ISSUE TITLE
Uncontrolled docker version in debian package dependencies

### ISSUE THREAD

**Issue by marqu3z** [dokku/dokku#2584]
I noticed docker dependency version in debian package requires `docker-engine (>= 1.9.1)`
https://github.com/dokku/dokku/blob/master/debian/control#L6

Docker releases often break previous api. 
Doing a fresh debian installation now it will install v1.13.0 that also has breaking changes leading to a possible not working environment.

Isn't safer to lock docker to a stable and known version?

**Comment by josegonzalez** [comment]
@marqu3z what currently breaks with Docker 1.13.0?

**Comment by marqu3z** [comment]
@josegonzalez I did not tested it, so i'm not stating it will not work. But i think there is no guarantee it will without any issue. (we had a short discussion on slack about it)

With the current strategy installing the same dokku version in the same machine on different times the first could work and the second could not if docker breaks the api.

Maybe it never happened. But i just wanna open a discussion about it, if it makes sense to lock the docker version within a dokku release, or it is too restrictive.

The goal is to be sure dokku will always work as expected.

**Comment by josegonzalez** [comment]
I'd imagine it would be a royal pain the ass to keep testing every docker version to verify it works with a given Dokku version. As well, if a patch breaks something but the next one fixes it, should we be arbitrarily limiting ourselves?

In the future, we'll switch to using their versioned APIs, which will avoid this issue, but for now I don't want to deal with developers asking why they can't use a specific version of Docker with a specific version of Dokku.
