### ISSUE TITLE
Gentoo compatibility and user experience with dokku on gentoo?

### ISSUE THREAD

**Issue by dmr** [dokku/dokku#2585]
Hi dokku-Team,

thanks again for the great job of maintaining dokku, it's a great tool to work with!

Is anybody running dokku on a Gentoo-based linux installation?

In the installation there are a few apt-get things mentioned but from what I understood about dokku if a host system only requires:
1. docker installed 
2. a user "dokku" with a custom shell "sshcommand"
3. a nginx installation which includes /home/dokku/*/nginx.conf

The dokku user must be allowed to use docker and reload nginx.

What did I miss that is required by the system environment?

**Comment by josegonzalez** [comment]
Thats more or less it. We put some app stuff in `DOKKU_ROOT` - typically `~dokku` - and then all the config/data is in `/var/lib/dokku`.

At this time I would rather not spend more efforts on adding another packaging system unless it is [Docker](https://github.com/dokku/dokku/issues/1076), so we won't be adding any "official" gentoo support.

**Comment by dmr** [comment]
Thank you for the quick reply!

**Comment by josegonzalez** [comment]
@dmr if you want to pitch in on the docker-based install process, that would be wonderful!

**Comment by viktorbezdek** [comment]
@dms Did you manage to run it successfully?

**Comment by dmr** [comment]
Yes, it's running right now.
But from what I remember the installation was sort of manual run -> debug -> run... because of some apt-get commands in the installation.
