### ISSUE TITLE
Deployment on a cPanel server?

### ISSUE THREAD

**Issue by ylluminate** [dokku/dokku#2589]
Has anyone deployed `dokku` successfully on a cPanel server with CentOS?  Wanting to get a lay of the land before digging in and seeing if its feasible before I start...

**Comment by josegonzalez** [comment]
Nope. Dokku definitely isn't meant to work with something like CPanel. I suggest spinning up a new 1GB droplet on Digitalocean with Dokku installed. Will cost you about a quarter to test for 24 hours, so not too hard.

**Comment by ylluminate** [comment]
Hmm, I've got a server that I host various other Ruby and Rails sites on via cPanel and was hoping to integrate dokku to emulate heroku, but with some real juice.

**Comment by josegonzalez** [comment]
CPanel etc. doesn't play nice with anything that tries to integrate with it, so I'd imagine it would break stuff like ssh or nginx proxying because it doesn't like in the cpanel world.

**Comment by ylluminate** [comment]
Hmm, I'll have to dig in and see what actually happens. If / when I have the chance I'll let you know how things go.

**Comment by beppe9000** [comment]
Bump.

**Comment by josegonzalez** [comment]
Dokku isn't meant to be installed on a server managed by CPanel, nor will we document such a thing in our documentation.

You may wish to try using pDokku via Docker](http://dokku.viewdocs.io/dokku/getting-started/install/docker/), which is fairly self-contained and may work.

Locking as this is a 2 year old issue.
