### ISSUE TITLE
Directory created during buildstep disappears?

### ISSUE THREAD

**Issue by buhrmi** [dokku/dokku#2595]
Description of problem:
Hello guys,

I have a buildstep defined in my package.json:

    "scripts": {
        "prestart": "npm build",
        "start": "node server.js"
    }

After deploying, I can see in the logs that the prestart step is being run. It creates a folder `dist` with all the bundled javascript, css, etc. But when I do `dokku enter app`, the `dist` folder is not there.

Running `npm build` after entering the container creates the folder just fine.

What is wrong here? Where could I look? Thanks.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by buhrmi** [comment]
OK, here is the additional information. Hope it helps.

`uname -a`
 
    Linux ip-172-31-27-73 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

`free -m`
                  total        used        free      shared  buff/cache   available
    Mem:            990         237         278          12         474         698
    Swap:             0           0           0

`docker version`

    Client:
     Version:      1.13.0
     API version:  1.25
     Go version:   go1.7.3
     Git commit:   49bf474
     Built:        Tue Jan 17 09:58:26 2017
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.13.0
     API version:  1.25 (minimum version 1.12)
     Go version:   go1.7.3
     Git commit:   49bf474
     Built:        Tue Jan 17 09:58:26 2017
     OS/Arch:      linux/amd64
     Experimental: false
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker -D info

    Containers: 8
     Running: 2
     Paused: 0
     Stopped: 6
    Images: 18
    Server Version: 1.13.0
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 39
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins: 
     Volume: local
     Network: bridge host macvlan null overlay
    Swarm: inactive
    Runtimes: runc
    Default Runtime: runc
    Init Binary: docker-init
    containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
    runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
    init version: 949e6fa
    Security Options:
     apparmor
     seccomp
      Profile: default
    Kernel Version: 4.4.0-53-generic
    Operating System: Ubuntu 16.04.1 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 1
    Total Memory: 990.7 MiB
    Name: ip-172-31-27-73
    ID: GKAH:HLN5:NSKC:CLS4:JJ4Y:LJJL:SMZB:Q3O4:RGSA:A4IJ:WAB7:WK6N
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): true
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    WARNING: No swap limit support
    Experimental: false
    Insecure Registries:
     127.0.0.0/8
    Live Restore Enabled: false

`sigil -v`

    0.4.0

`docker run -ti gliderlabs/herokuish:latest herokuish version`

    herokuish: 0.3.24
    buildpacks:
      heroku-buildpack-multi     v1.0.0
      heroku-buildpack-ruby      v150
      heroku-buildpack-nodejs    v93
      heroku-buildpack-clojure   v75
      heroku-buildpack-python    v97
      heroku-buildpack-java      v48
      heroku-buildpack-gradle    v19
      heroku-buildpack-grails    v21
      heroku-buildpack-scala     v72
      heroku-buildpack-play      v26
      heroku-buildpack-php       v117
      heroku-buildpack-go        v54
      heroku-buildpack-erlang    fa17af9
      buildpack-nginx            v8

`dokku version`

    0.8.0

`dokku plugin`

    plugn: 0.2.2
      00_dokku-standard    0.8.0 enabled    dokku core standard plugin
      20_events            0.8.0 enabled    dokku core events logging plugin
      apps                 0.8.0 enabled    dokku core apps plugin
      build-env            0.8.0 enabled    dokku core build-env plugin
      certs                0.8.0 enabled    dokku core certificate management plugin
      checks               0.8.0 enabled    dokku core checks plugin
      common               0.8.0 enabled    dokku core common plugin
      config               0.8.0 enabled    dokku core config plugin
      docker-options       0.8.0 enabled    dokku core docker-options plugin
      domains              0.8.0 enabled    dokku core domains plugin
      enter                0.8.0 enabled    dokku core enter plugin
      git                  0.8.0 enabled    dokku core git plugin
      letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
      logs                 0.8.0 enabled    dokku core logs plugin
      named-containers     0.8.0 enabled    dokku core named containers plugin
      nginx-vhosts         0.8.0 enabled    dokku core nginx-vhosts plugin
      plugin               0.8.0 enabled    dokku core plugin plugin
      proxy                0.8.0 enabled    dokku core proxy plugin
      ps                   0.8.0 enabled    dokku core ps plugin
      repo                 0.8.0 enabled    dokku core repo plugin
      shell                0.8.0 enabled    dokku core shell plugin
      ssh-keys             0.8.0 enabled    dokku core ssh-keys plugin
      storage              0.8.0 enabled    dokku core storage plugin
      tags                 0.8.0 enabled    dokku core tags plugin
      tar                  0.8.0 enabled    dokku core tar plugin

`docker inspect 453c280d6941`

    [
        {
            "Id": "453c280d6941c929d2c0f10a6e771d795d0875e1a9349457277ce50c76a69b55",
            "Created": "2017-02-03T08:23:33.821592449Z",
            "Path": "/start",
            "Args": [
                "web"
            ],
            "State": {
                "Status": "running",
                "Running": true,
                "Paused": false,
                "Restarting": false,
                "OOMKilled": false,
                "Dead": false,
                "Pid": 5126,
                "ExitCode": 0,
                "Error": "",
                "StartedAt": "2017-02-03T08:23:33.970669595Z",
                "FinishedAt": "0001-01-01T00:00:00Z"
            },
            "Image": "sha256:9adf10df7218db105d5f302892bdf0b6ed3908ac9754f628ccb3d867c2a04fe6",
            "ResolvConfPath": "/var/lib/docker/containers/453c280d6941c929d2c0f10a6e771d795d0875e1a9349457277ce50c76a69b55/resolv.conf",
            "HostnamePath": "/var/lib/docker/containers/453c280d6941c929d2c0f10a6e771d795d0875e1a9349457277ce50c76a69b55/hostname",
            "HostsPath": "/var/lib/docker/containers/453c280d6941c929d2c0f10a6e771d795d0875e1a9349457277ce50c76a69b55/hosts",
            "LogPath": "/var/lib/docker/containers/453c280d6941c929d2c0f10a6e771d795d0875e1a9349457277ce50c76a69b55/453c280d6941c929d2c0f10a6e771d795d0875e1a9349457277ce50c76a69b55-json.log",
            "Name": "/platform.web.1",
            "RestartCount": 0,
            "Driver": "aufs",
            "MountLabel": "",
            "ProcessLabel": "",
            "AppArmorProfile": "",
            "ExecIDs": [
                "1c55d070ab801a1e1563ced27b5ea07803f11770ff1c864b2097fc0efdee9a7f"
            ],
            "HostConfig": {
                "Binds": null,
                "ContainerIDFile": "",
                "LogConfig": {
                    "Type": "json-file",
                    "Config": {}
                },
                "NetworkMode": "default",
                "PortBindings": {},
                "RestartPolicy": {
                    "Name": "on-failure",
                    "MaximumRetryCount": 10
                },
                "AutoRemove": false,
                "VolumeDriver": "",
                "VolumesFrom": null,
                "CapAdd": null,
                "CapDrop": null,
                "Dns": [],
                "DnsOptions": [],
                "DnsSearch": [],
                "ExtraHosts": null,
                "GroupAdd": null,
                "IpcMode": "",
                "Cgroup": "",
                "Links": null,
                "OomScoreAdj": 0,
                "PidMode": "",
                "Privileged": false,
                "PublishAllPorts": false,
                "ReadonlyRootfs": false,
                "SecurityOpt": null,
                "UTSMode": "",
                "UsernsMode": "",
                "ShmSize": 67108864,
                "Runtime": "runc",
                "ConsoleSize": [
                    0,
                    0
                ],
                "Isolation": "",
                "CpuShares": 0,
                "Memory": 0,
                "NanoCpus": 0,
                "CgroupParent": "",
                "BlkioWeight": 0,
                "BlkioWeightDevice": null,
                "BlkioDeviceReadBps": null,
                "BlkioDeviceWriteBps": null,
                "BlkioDeviceReadIOps": null,
                "BlkioDeviceWriteIOps": null,
                "CpuPeriod": 0,
                "CpuQuota": 0,
                "CpuRealtimePeriod": 0,
                "CpuRealtimeRuntime": 0,
                "CpusetCpus": "",
                "CpusetMems": "",
                "Devices": [],
                "DiskQuota": 0,
                "KernelMemory": 0,
                "MemoryReservation": 0,
                "MemorySwap": 0,
                "MemorySwappiness": -1,
                "OomKillDisable": false,
                "PidsLimit": 0,
                "Ulimits": null,
                "CpuCount": 0,
                "CpuPercent": 0,
                "IOMaximumIOps": 0,
                "IOMaximumBandwidth": 0
            },
            "GraphDriver": {
                "Name": "aufs",
                "Data": null
            },
            "Mounts": [],
            "Config": {
                "Hostname": "453c280d6941",
                "Domainname": "",
                "User": "",
                "AttachStdin": false,
                "AttachStdout": false,
                "AttachStderr": false,
                "Tty": false,
                "OpenStdin": false,
                "StdinOnce": false,
                "Env": [
                    "PORT=5000",
                    "USER=herokuishuser",
                    "DYNO=web.1",
                    "CACHE_PATH=/cache",
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
                ],
                "Cmd": [
                    "/start",
                    "web"
                ],
                "Image": "dokku/platform:latest",
                "Volumes": null,
                "WorkingDir": "",
                "Entrypoint": null,
                "OnBuild": null,
                "Labels": {
                    "dokku": ""
                }
            },
            "NetworkSettings": {
                "Bridge": "",
                "SandboxID": "637e8e6c3806c63974ddaced552f5cd55dd301f0598dbc7185f44a5587a0ea1e",
                "HairpinMode": false,
                "LinkLocalIPv6Address": "",
                "LinkLocalIPv6PrefixLen": 0,
                "Ports": {},
                "SandboxKey": "/var/run/docker/netns/637e8e6c3806",
                "SecondaryIPAddresses": null,
                "SecondaryIPv6Addresses": null,
                "EndpointID": "92c83341267463b65e180bcf860deaecc64caed1be1c839286e2f298dfed6aec",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAddress": "172.17.0.3",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "MacAddress": "02:42:ac:11:00:03",
                "Networks": {
                    "bridge": {
                        "IPAMConfig": null,
                        "Links": null,
                        "Aliases": null,
                        "NetworkID": "78b94c9d86bd638154f10a3d09f11a33b411c8ead419ffb49595de0ddb1e042d",
                        "EndpointID": "92c83341267463b65e180bcf860deaecc64caed1be1c839286e2f298dfed6aec",
                        "Gateway": "172.17.0.1",
                        "IPAddress": "172.17.0.3",
                        "IPPrefixLen": 16,
                        "IPv6Gateway": "",
                        "GlobalIPv6Address": "",
                        "GlobalIPv6PrefixLen": 0,
                        "MacAddress": "02:42:ac:11:00:03"
                    }
                }
            }
        }
    ]

`cat /home/dokku/platform/nginx.conf`

    server {
      listen      [::]:80;
      listen      80;
      server_name qurate.site; 
      access_log  /var/log/nginx/platform-access.log;
      error_log   /var/log/nginx/platform-error.log;

      return 301 https://$host:443$request_uri;

    }

    server {
      listen      [::]:443 ssl ;
      listen      443 ssl ;
      server_name qurate.site; 
      server_name qurate.site; 
      access_log  /var/log/nginx/platform-access.log;
      error_log   /var/log/nginx/platform-error.log;

      ssl_certificate     /home/dokku/platform/tls/server.crt;
      ssl_certificate_key /home/dokku/platform/tls/server.key;
      ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;

      keepalive_timeout   70;
      

      location    / {

        gzip on;
        gzip_min_length  1100;
        gzip_buffers  4 32k;
        gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
        gzip_vary on;
        gzip_comp_level  6;

        proxy_pass  http://platform-5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Request-Start $msec;
      }
      include /home/dokku/platform/nginx.conf.d/*.conf;
    }

    upstream platform-5000 {

      server 172.17.0.3:5000;
    }

`cat Procfile`

   web: npm start

`How was dokku installed`

    wget https://raw.githubusercontent.com/dokku/dokku/v0.8.0/bootstrap.sh
    sudo DOKKU_TAG=v0.8.0 bash bootstrap.sh

`environment details`

Nothing special, just a fresh ubuntu box on aws ec2

How to reproduce:

Unfortunately I'm not allowed to open up the github repo. It's just a simple node app with webpack that creates a dist/ directory. When deploying with git, the buildstep is run (there is output on the console), but when entering the dokku container, the directory is not there.

Actual result

The dist/ directory is missing

Expected result

The dist/ directory exists

**Comment by joshmanders** [comment]
How are you running the command to create the `dist/`?

**Comment by buhrmi** [comment]
Hi @joshmanders, in the Procfile I have `web: npm start`, which executes the npm start script. in my package.json file I have defined `"scripts":  {"prestart": "npm run build", "start": "nodemon --exec node server.js", "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"}`. The prestart script `npm run build` is executed before the `start` script. The `npm run build` runs the build script automatically every time `npm start` is executed and `webpack` is executed.

**Comment by buhrmi** [comment]
Okay turns out the server was just running out of memory during build. I increased the swap file size and now it's working. Thanks all.
