### ISSUE TITLE
Deploy hooks from pre-built docker image

### ISSUE THREAD

**Issue by aeons** [dokku/dokku#2596]
I'm trying to use app.json/deploy hooks with a pre-built docker image, deployed with `dokku tags:deploy`.

I have put the app.json inside the docker image in the `WORKDIR`, however it seems to not be run.

Where should I put it to get it picked up by dokku when I'm deploying a pre-built docker image?

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by aeons** [comment]
Description of problem:
Hooks in `app.json` are ignored when deploying a pre-built docker image.

dokku report: https://gist.github.com/aeons/3d243c76ea074fbd6c9900f31b19a6af

Environment details (AWS, VirtualBox, physical, etc.): VM on Azure with Ubuntu 16.04

How was Dokku installed?: APT

Steps to Reproduce:
1. Build a docker image with an `app.json` in the `WORKDIR` with a `scripts.dokku.postdeploy` value.
2. Deploy that docker image using `dokku tags:deploy`
3. Observe that the post deploy hook is not executed

Actual Results:
```
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
-----> Shutting down old containers in 60 seconds
```

Expected Results:
```
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
<some output from the post deploy hook here>
```

Additional info:
The documentation does not mention anything about deploying docker images in the section about deployment tasks, so it is not clear to me where the `app.json` should be placed in the image to get picked up.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. 

Specifically I need the full output from a deploy after turning on dokku trace.

**Comment by aeons** [comment]
Sorry, I somehow deleted those lines without reading them.

Will get one.

**Comment by aeons** [comment]
So, in recreating the image that caused me to create this issue, I apparently did something differently, so now it works.

Sorry for wasting your time and thanks for a wonderful piece of software :)
