### ISSUE TITLE
pre-receive hook declined. Why is it trying to delete directories?

### ISSUE THREAD

**Issue by fjbat** [dokku/dokku#2598]
**Description of problem:**
Getting ` ! [remote rejected] master -> master (pre-receive hook declined) `when deploying.
The build process is trying to delete any folders in the project, maybe that's causing the error.
`remote: rm: cannot remove '/app/public': Directory not empty`
Tried a sample nodejs app with the same error. No errors when deploying to heroku.

**Dokku Report:**
```
-----> uname: Linux DD-PRD 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:           7823         849        5418           9        1555        6520
Swap:          1023           0        1023
-----> docker version: 
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 14
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.64 GiB
Name: DD-PRD
ID: STQI:ZRNT:CT3U:NLFP:TGJL:M3FB:5ICR:NRVF:LHLK:CVTT:4VTV:VBVV
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.24
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v150
  heroku-buildpack-nodejs    v93
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v97
  heroku-buildpack-java      v48
  heroku-buildpack-gradle    v19
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v117
  heroku-buildpack-go        v54
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.8.0
-----> dokku plugins: 
plugn: 0.2.2
  00_dokku-standard    0.8.0 enabled    dokku core standard plugin
  20_events            0.8.0 enabled    dokku core events logging plugin
  apps                 0.8.0 enabled    dokku core apps plugin
  build-env            0.8.0 enabled    dokku core build-env plugin
  certs                0.8.0 enabled    dokku core certificate management plugin
  checks               0.8.0 enabled    dokku core checks plugin
  common               0.8.0 enabled    dokku core common plugin
  config               0.8.0 enabled    dokku core config plugin
  docker-options       0.8.0 enabled    dokku core docker-options plugin
  domains              0.8.0 enabled    dokku core domains plugin
  enter                0.8.0 enabled    dokku core enter plugin
  git                  0.8.0 enabled    dokku core git plugin
  logs                 0.8.0 enabled    dokku core logs plugin
  named-containers     0.8.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.8.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.8.0 enabled    dokku core plugin plugin
  proxy                0.8.0 enabled    dokku core proxy plugin
  ps                   0.8.0 enabled    dokku core ps plugin
  repo                 0.8.0 enabled    dokku core repo plugin
  shell                0.8.0 enabled    dokku core shell plugin
  ssh-keys             0.8.0 enabled    dokku core ssh-keys plugin
  storage              0.8.0 enabled    dokku core storage plugin
  tags                 0.8.0 enabled    dokku core tags plugin
  tar                  0.8.0 enabled    dokku core tar plugin
```

**Trace:**
https://www.pastiebin.com/589b29131f55a

**Comment by VitoNordloh** [comment]
I assume you have added a user which is allowed to push, right? That was my problem the first time.
See http://dokku.viewdocs.io/dokku/deployment/user-management/ for more information.

You could also take a look at issue #2512.

**Comment by josegonzalez** [comment]
@VitoNordloh that issue has nothing to do with this one.

**Comment by fjbat** [comment]
I've tried a node.js sample app and a rails sample app, both with the same issue.

**Comment by josegonzalez** [comment]
@fjbat can you replicate this with an ubuntu-based installation?

**Comment by fjbat** [comment]
I have successfully used dokku in ubuntu on DigitalOcean before, but right now I must use centos 7.

**Comment by josegonzalez** [comment]
Yes I understand that, I'm asking if you can replicate this issue *now* with Dokku installed on Ubuntu.

**Comment by ebeigarts** [comment]
I had the same problem using `overlay` + `xfs`, I also tried `overlay` + `ext4`, both didn't  work. At the end I used `Dockerfile` and it worked great with `overlay` + `xfs`.  Anyway, you should probably try `devicemapper` + `lvm`, at least with loopback I didn't have problems, you can also try using newer linux kernel.

**Comment by ebeigarts** [comment]
The problem comes from this line https://github.com/gliderlabs/herokuish/blob/199351c56da379335e11a9765b92d8d710636cb1/include/buildpack.bash#L176 and I think has to do something with https://github.com/docker/docker/issues/9572

**Comment by fjbat** [comment]
Tks! The kernel update (4.9.8-1.el7.elrepo.x86_64) didn't work. I really want to use buildpacks, so I'm going to try devicemapper + lvm.

**Comment by josegonzalez** [comment]
Sounds like a bug in docker. @ebeigarts mind adding this to our troubleshooting doc?

**Comment by josegonzalez** [comment]
Also idk why anyone cares about the underlying Dokku OS. You're almost certainly not using this in an "enterprise" setting, so why not just use Ubuntu, which is actually tested via CI and not experimental?

**Comment by ebeigarts** [comment]
@josegonzalez lets wait and see if `direct-lvm` works. @fjbat did you manage to run buildpacks with `devicemapper` + `direct-lvm`?

**Comment by fjbat** [comment]
Well, I've just deployed smoothly on ubuntu. No issues at all. 
Thanks guys

**Comment by josegonzalez** [comment]
@fjbat does the `devicemapper` + `direct-lvm` setup on centos work?

**Comment by fjbat** [comment]
I couldn't go with that route after all because I would have to mess around with the disk partitions, and that wouldn't be possible.

**Comment by josegonzalez** [comment]
@ebeigarts mind adding this to the docs as a potential fix?

I'm going to close this issue now as it appears to me that the bug is actually in the OS itself, not in Dokku or anything about how we handle docker.
