### ISSUE TITLE
Error on push: insufficient permission for adding an object to repository database ./objects

### ISSUE THREAD

**Issue by nielsonsantana** [dokku/dokku#2599]
This problem occur after push a commit to dokku remote repository.
To solve the problem, I need access the server and execute the fallowing commands:

- chmod -Rf u+w .
- chgrp -R dokku .

After this commands, I can push again, but some pushes later(1 or 2), the problem is back.

Description of problem:
$ git push dokku@ip_address:parceiros master
remote: error: insufficient permission for adding an object to repository database ./objects        
remote: fatal: failed to write object        
error: unpack failed: unpack-objects abnormal exit
To dokku@ip_address:parceiros
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to 'dokku@ip_address:parceiros'

Output of the following commands

- `uname -a`:
Linux genomika-dokku-staging-v2 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
             total       used       free     shared    buffers     cached
Mem:           994        787        206          3         38        134
-/+ buffers/cache:        614        379
Swap:         1023        548        475
- `docker version`:
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
- `docker -D info`:
Containers: 19
 Running: 10
 Paused: 0
 Stopped: 9
Images: 174
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 214
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 994 MiB
Name: genomika-dokku-staging-v2
ID: FRSM:3JF2:MBC6:HHBQ:WQSV:FXBS:ZZ2K:WQMI:NMP6:Y7JZ:NIF3:ENKQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

- `sigil -v`:
0.3.3

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.18
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v81
  heroku-buildpack-java      v44
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v109
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v5
  emberjs.tgz                latest

- `dokku version`:
0.7.1
- `dokku plugin`:

Environment details (AWS, VirtualBox, physical, etc.):
DigitalOcean
How was Dokku installed?:
apt-get install dokku
How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Additional info:

**Comment by josegonzalez** [comment]
Do you have something that is changing the permissions on those files? We don't run any cron tasks or anything that would do so.

**Comment by nielsonsantana** [comment]
I don't know if there any agent on the server that change the permissions of the file.
The changed folder is ".git/objects", folder managed by dokku. 
I will deploy a fresh server and test if the problem persist.

**Comment by josegonzalez** [comment]
We certainly don't modify any permissions on those files other than to create them, so it definitely sounds like something on your end.

Closing as there hasn't been any update in a bit.
