### ISSUE TITLE
Pre-receive hook declined

### ISSUE THREAD

**Issue by vijayviji** [dokku/dokku#2600]
**Description of problem:**
When I try to push my changes, I'm receiving pre-receive hook declined error.

[vijis@vijis-m01 sdct]$ git push one master
Counting objects: 98, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (95/95), done.
Writing objects: 100% (98/98), 37.55 KiB | 0 bytes/s, done.
Total 98 (delta 60), reused 0 (delta 0)
-----> Cleaning up...
-----> Building one from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/vijayviji/heroku-buildpack-apt
=====> Detected Framework: Apt
To one.eng.vmware.com:one
 **! [remote rejected] master -> master (pre-receive hook declined)**
error: failed to push some refs to 'dokku@one.eng.vmware.com:one'

I checked out the issue #497. It's different.

**Output of the following commands**

- `uname -a`: Linux one 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
             total       used       free     shared    buffers     cached
Mem:          3952       3533        418          1        338       2365
-/+ buffers/cache:        830       3122
Swap:         4091        112       3979
- `docker version`:
WARNING: Error loading config file:stat /home/one/.docker/config.json: permission denied
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
- `docker -D info`:
WARNING: Error loading config file:stat /home/one/.docker/config.json: permission denied
Containers: 7
Images: 124
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 138
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 3.86 GiB
Name: one
ID: AKVG:2TD2:3L2K:YCGT:Z452:EXYV:WKG5:KIQ6:OK4C:CQ7Q:5TR2:ZE4J
WARNING: No swap limit support
- `sigil -v`:
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
WARNING: Error loading config file:stat /home/one/.docker/config.json: permission denied
herokuish: 0.3.3
buildpacks:
  heroku-buildpack-clojure   v67
  heroku-buildpack-go        fa0679c
  heroku-buildpack-gradle    v12
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v38
  heroku-buildpack-multi     26fa21a
  heroku-buildpack-nodejs    v76
  heroku-buildpack-php       v70
  heroku-buildpack-play      v24
  heroku-buildpack-python    v61
  heroku-buildpack-ruby      v138
  heroku-buildpack-scala     v60
- `dokku version`:
0.4.1
- `dokku plugin`:
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  app-predeploy-tasks  0.1.0 enabled    Run arbitrary app tasks prior to dokku's deploy phase
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  mariadb              1.0.0 enabled    dokku mariadb service plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.):
VM in vsphere
How was Dokku installed?:

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual Results:

Expected Results:

Additional info:

**Comment by josegonzalez** [comment]
It is indeed different. Can you provide the output from a deploy with `dokku trace on`? I suspect this is just an issue in the buildpack you are using (it's not one that is packaged with Dokku, so it's possible it's just broken).

**Comment by vijayviji** [comment]
Indeed it's a problem with the buildpack. The buildpack was written to fail from Jan 2, 2017. I just removed it and it works. (https://github.com/vijayviji/heroku-buildpack-apt/commit/5b1ca566c60b317e7c284c6e2bb66d61b5d584f7)

Thanks @josegonzalez

**Comment by spnkr** [comment]
> 
> ```
>  ! [remote rejected]   master -> master (pre-receive hook declined)
> error: failed to push some refs to 'dokku@SERVER-IP-HERE:appnamehere'
> ```
> 

Solution: for me, I just have to `git push dokku master` a few times (on the same code) to get dokku to accept the push.

I don't know why it fails sometimes (about 75% of the time when I push actually).

**Comment by josegonzalez** [comment]
@spnkr If you're still seeing this problem anywhere, please file a new issue. This one is a year+ old, and its possible your problem has nothing to do with the one reported here.
