### ISSUE TITLE
inter app dependencies?

### ISSUE THREAD

**Issue by fruitl00p** [dokku/dokku#2601]
Description of problem:
We currently have the situation that app A depends on app B for actually running (since they are linked together) This works except for a nasty part: the ps:restore (on boot of the instance) does an alphabetical listing of the apps to restore (ps:restart appA .... ps:restart appB) Thus not booting A but booting B... 

The solution is ofcourse renaming appB to '_appB' in order to move it up alphabetically but you can see where this might lead to ;)

Is there any other way of making sure we have appB running before appA ?

**Comment by josegonzalez** [comment]
Nope. I'd probably say you should use a different method of linking the services together - maybe via a shared message queue - as "requiring" another service to start before the current one does is an anti-pattern.

See [this post](https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c#.8x8kv1yjo) by Kelsey Hightower for more on that line of thought.
