### ISSUE TITLE
Problem during the install

### ISSUE THREAD

**Issue by rafaeljimenez** [dokku/dokku#2604]
**Description of problem:**

I try to install dokku in my machine but I doesn't work

**Environment details (AWS, VirtualBox, physical, etc.):**

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               2199.968
BogoMIPS:              4399.93
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0
How reproducible:

Steps to Reproduce:
1. wget https://raw.githubusercontent.com/dokku/dokku/v0.8.0/bootstrap.sh
2. sudo DOKKU_TAG=v0.8.0 bash bootstrap.sh

**Actual Results:**
```
--> Installing dokku

2017-02-13 21:23:23 URL:https://packagecloud.io/gpg.key [3889/3889] -> "-" [1]
OK
deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main
E: Unable to correct problems, you have held broken packages.
```

**Expected Results:**
Install dokku

**Comment by josegonzalez** [comment]
You should run:

```
apt-get install -f
```

As it says, you have held broken pacakges, and need to figure out what is breaking. I doubt it's dokku related.

**Comment by josegonzalez** [comment]
If you need support with installation, please checkout our slack chat in the #dokku room.
