### ISSUE TITLE
Specifying Ubuntu version for a dokku container

### ISSUE THREAD

**Issue by medbenmakhlouf** [dokku/dokku#2606]
Description of problem:
I've installed dokku on Ubuntu 16.04, and deployed an app on it. Looks like the app's container is based on Ubuntu 14.04:

I want the app's environment to be 16.04 also. How do I control this?

Output of the following commands
dokku run myapp bash
$ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

Environment details (AWS, VirtualBox, physical, etc.):
VPS

How was Dokku installed?:
following the instructions on this repo.

Any Help Please,
thanks :)

**Comment by josegonzalez** [comment]
You cannot control this, as this is based on Heroku's Cedar stack. They are currently experimenting with 16.04, so maybe at some point we have a herokuish that uses that, but for now you are stuck with 14.04.

If you want a different Distribution or Distribution version, please use the dockerfile method for deployment (check out our docs for more details).

Closing.
