### ISSUE TITLE
Wrong container mappings on subdomain

### ISSUE THREAD

**Issue by sarbull** [dokku/dokku#2608]
**Description of the problem:**
The application container maps the domain with the main root domain. (http://busline.rocks instead of http://node-js-sample.busline.rocks)

**How was Dokku installed?:**
DigitalOcean (One-Click Apps: Dokku 0.8.0)

**How reproducible:**
http://api.busline.rocks loads the app instead of http://node-js-sample.api.busline.rocks

**Steps to Reproduce:**
1. Enter on http://node-js-sample.api.busline.rocks, it should open the sample app

**Actual Results:**
Nothing loads

**Expected Results:**
Load the application

**Additional info:**
My DigitalOcean Networking

| Type |    Hostname  |               Value             |   TTL |
|------|----------------|-------------------------|-------|
|   A    | *.api.busline.rocks |        46.101.123.114       | 1800 |
|  NS   | busline.rocks | ns1.digitalocean.com. | 1800 |
|  NS   | busline.rocks | ns2.digitalocean.com. | 1800 |
|  NS   | busline.rocks | ns3.digitalocean.com. | 1800 |

**Comment by sarbull** [comment]
i managed to find a workaround

```bash
user@hostname:# cat /etc/nginx/conf.d/dokku.conf 
server {
  listen   80;
  root /var/www/dokku;
  index index.html index.htm;

  server_name api.busline.rocks;
}

include /home/dokku/*/nginx.conf;
```

I added a custom handler for the api.busline.rocks subdomain.

How can it be disabled by default?

**Comment by josegonzalez** [comment]
You likely didn't complete the web installer to set the default VHOST on the app. As well, from our docs:

> By default, Dokku will route any received request with an unknown HOST header value to the lexicographically first site in the nginx config stack. If this is not the desired behavior, you may want to add the following configuration to the global nginx configuration.

You can modify your dokku domain setup by following our [documentation](http://dokku.viewdocs.io/dokku/configuration/domains/).
