### ISSUE TITLE
Outdated installation instructions for Linode.com

### ISSUE THREAD

**Issue by emveeoh** [dokku/dokku#2610]
dokku/docs/getting-started/install/linode.md

The directions for Dokku installation on Linode.com are outdated. 

Linode.com now has KVM as default. 

GRUB2 is offered in the Kernal menu.

The directions currently suggest that the user should install:
- linux-image-virtual
- linux-image-extra-virtual

Are these still required?

```
apt-get install linux-image-virtual linux-image-extra-virtual
```

**Comment by joshmanders** [comment]
I just today setup v0.8.0 on Linode and followed the steps and it works fine, best to do it just until we can verify that it's not needed, and we'll update docs. Unless you want to verify it and submit a PR with it removed if it works without the steps. :)

**Comment by emveeoh** [comment]
@joshmanders 
I would be happy to update the docs via PR, but I'm not sure if these additional libs are still required, even though you can select GRUB 2 from the Kernal menu...
linux-image-virtual
linux-image-extra-virtual

The installation directions say:

**Comment by joshmanders** [comment]
@emveeoh can you do the setup using GRUB 2 and KVM without installing `linux-image-*` packages and let me know if it works for you?

**Comment by emveeoh** [comment]
@joshmanders 

I can confirm that it does work. Does that mean that AUFS is being used? If so, I will update the docs and submit the PR.

**Comment by joshmanders** [comment]
Run `docker info` as `dokku` user and see if `Storage Driver: aufs` is present. If so, yes, update docs and submit PR.

**Comment by stephenhowells** [comment]
I have a stock 16.04 install with GRUB 2 selected as the kernel and it does list the Storage Driver as `aufs`. I didn't have to run any of the commands in the Dokku documentation. Glad to see things have gotten easier on Linode. Especially with the new $5 plan they offer for 1GB of RAM. Those will make great little Dokku machines to tinker on.

**Comment by emveeoh** [comment]
@joshmanders & @stephenhowells ... Thanks guys!  I can also confirm that my Debian install with GRUB 2 kernel also lists the Storage Driver as `aufs`. 

Closing this issue and will update the .md shortly...

**Comment by joshmanders** [comment]
A tip when making the PR, since it's just docs, put `[ci skip]` in the PR body, that way we don't have to worry about the CI running.

**Comment by emveeoh** [comment]
Thanks Josh

**Comment by joshmanders** [comment]
No problem, and thanks for helping with this!

**Comment by emveeoh** [comment]
I did a full cleanup of the Linode installation instructions and committed them. Today, my updates have been reverted to the old, incorrect instructions... So glad I bothered to try and help...

**Comment by joshmanders** [comment]
Wait, what do you mean?

**Comment by joshmanders** [comment]
Your changes are right here: https://github.com/emveeoh/dokku/commit/af224ff60f167c125549cdf0fbdc7411a46cb8db

Just make a PR from that branch to the master branch on this repo.

**Comment by joshmanders** [comment]
You made a PR against your own repo for your patch.

**Comment by emveeoh** [comment]
oh... okay...  Sorry, newbie error...

**Comment by joshmanders** [comment]
No worries, happens to all of us. :)
