### ISSUE TITLE
Integrate the dokku-git-rev plugin into the main repository

### ISSUE THREAD

**Issue by NDuggan** [dokku/dokku#2621]
I've discussed this with @josegonzalez on Dokku's Slack but we're hoping to hear opinions from others.

I recently had a problem getting the [git-rev](https://github.com/cjblomqvist/dokku-git-rev) plugin to work correctly (as it was getting the previous commit, instead of the current). @josegonzalez helped out, [refactored the plugin](https://github.com/josegonzalez/dokku-git-rev/tree/patch-1) and it turned out to be a race condition based on the plugin name.

Using the plugin name `git-rev` meant the `GIT_REV` environment variable was added too late during the build process, but naming the plugin using the `--name dokku-git-rev` option meant that it was added earlier during the build process.

I asked @josegonzalez if this is something that would/could be added to the main Dokku installation as I believe a lot of users might require it as some point. I've already needed it in 2 separate projects and my colleague @andyjeffries has also recently required it.

@josegonzalez believes it could well be added, but also mentioned that once features are added it becomes harder to change/remove them in the future, so it's not a decision that can be made lightly. He also suggested that if it was added to the main repo, then it would be better to provide an option to disable it for people that did *not* want the environment variable set.

**Comment by joshmanders** [comment]
Gets my vote, I always thought putting the git hash onto the container as something that should be part of core.

**Comment by michaelshobbs** [comment]
@joshmanders actually you bring up a good point. As an additional feature of this, it might be good to tag the container with the git rev as well as adding it to the container environment.

**Comment by rvalyi** [comment]
may be off topic, but asking in any case: are we able (eventually with this plugin) to know the git rev previously before making a new build. In some cases that may be useful for specialized buildpacks to make a diff and eventually do things with the database or log some warnings.

**Comment by josegonzalez** [comment]
We could but we'd need a concrete use case for that before implementing such a thing.

**Comment by AxelTheGerman** [comment]
I'd love to see this being part of the core. A number of plugins require the git revision, often in a post-deploy hook or similar (dokku-rollbar, dokku-airbrake-deploy). Currently we either need to duplicate the logic or rely on this plugin to be installed.

**Comment by josegonzalez** [comment]
Be the change you wish to see in the world :)

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. Still needs tests for this specific feature, but also improves our handling of custom git branches.
