### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by ckhatton** [dokku/dokku#2623]
Before I spend time forking, branching, and pull requesting the repo. I would like to contribute uninstall instructions to the README.md. Is that something you would like added?

> I come from dokku-alt, where I had to figure out how to uninstall it haha

:octocat:

**Comment by josegonzalez** [comment]
Sure thats fine with me. Please create a new doc for it and include documentation for all platforms - Arch, CentOS, Debian.
