### ISSUE TITLE
Allow disabling port-mapping if proxy was disabled

### ISSUE THREAD

**Issue by srigi** [dokku/dokku#2624]
#### Description of problem:
I will cite the documentation:

> [If a proxy is disabled, Dokku will bind your container's port to a random port on the host for every deploy, e.g. 0.0.0.0:32771->5000/tcp.](http://dokku.viewdocs.io/dokku~v0.8.0/advanced-usage/proxy-management/#container-network-interface-binding)

I'm using Dokku to orchestrate data-oriented services (Kafka, Zookeeper). This services are used only for linking with other containers. I need an dokku command that will disable behaviour described above. It is required for me that these services would not expose its ports to the host machine.

Can this subcommand be added to `proxy:ports`?

**Comment by srigi** [comment]
OK, this can be closed, automapping of the ports is made only for `web` kind of processes.

**Comment by josegonzalez** [comment]
The proper way to do services is to follow the pattern set by service plugins, such as [dokku-redis](https://github.com/dokku/dokku-redis).

**Comment by srigi** [comment]
Other services I setup via plugins, but Kafka & Zookeeper don't have plugins. So I'm using `Dockerfile` deployment.

**Comment by josegonzalez** [comment]
Right, what I'm saying is that you should follow that same pattern and write a custom plugin for each of those services.
