### ISSUE TITLE
Link processes - or expose non-web process 

### ISSUE THREAD

**Issue by b3njamin** [dokku/dokku#2632]
What is the best way to link 2 process of a Procfile - say if i want to run 2 different web services.

**Comment by josegonzalez** [comment]
A few things:

- A deployed app can only run a maximum of one web service at a time. You'll need a second app to run the second service.
- You cannot link two apps in Dokku using any method. We do not support direct application links.
- You may wish to communicate over https in the clear, or use some other method of proxying the applications (outside of dokku).
