### ISSUE TITLE
Install dokku through apt, requires docker-engine instead of docker-ce

### ISSUE THREAD

**Issue by Blackrush** [dokku/dokku#2636]
Description of problem:

    [16:41:19]  <achauvin>	hello guys, i'm trying to install dokku on a ubuntu xenial server, i had installed docker beforehand using apt
    [16:42:05]  <achauvin>	but now it's the installed package is called  `docker-ce`, not `docker-engine`, which breaks dokku's installation using apt too

Output of the following commands

- `uname -a`: Linux sauron 4.4.38-std-1 #1 SMP Mon Dec 12 10:45:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`: Mem:           2003          39        1343          16         619        1761
- `docker version`:
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Environment details (AWS, VirtualBox, physical, etc.): Scaleway VC1S

How was Dokku installed?: APT

How reproducible:

Steps to Reproduce:
1. install docker through https://docs.docker.com/engine/installation/linux/ubuntu/#os-requirements
2. install dokku through http://dokku.viewdocs.io/dokku/#install-apt

Actual Results: 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dokku : Depends: docker-engine-cs (>= 1.9.1) but it is not installable or
                  docker-engine (>= 1.9.1) but it is not installable
         Recommends: herokuish but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Expected Results:

Additional info: 
```
root@sauron:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by josegonzalez** [comment]
Fixed by the above, will go out in the next patch release.
