### ISSUE TITLE
Feature: Better default nginx error page

### ISSUE THREAD

**Issue by chiedo** [dokku/dokku#2640]
Currently, if the dokku app is down for whatever reason, the user will get a nasty 502 error page.

If you guys are on board, I'd like to change the default to being something more user friendly via a custom error page.

I've done this manually on some of my apps with the nginx.conf.sigil file and thing it would be a nice addition.

If you're in favor, please let me know and I'll submit a PR.

If you could point me to the default nginx file in the codebase, that will save me some time grepping :)

Thanks for all you guys do.

**Comment by joshmanders** [comment]
I was thinking about this issue before, and I'm open to it. Not sure about others.

**Comment by chiedo** [comment]
Awesome!

Could you point me to the nginx file in the codebase?

I can grep if it's not trivial for you to find

**Comment by joshmanders** [comment]
https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil

**Comment by chiedo** [comment]
https://github.com/dokku/dokku/pull/2641

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
