### ISSUE TITLE
Unable to deploy PHP app with default buildpack

### ISSUE THREAD

**Issue by afermon** [dokku/dokku#2645]
Description of problem:
Unable to deploy PHP app with default buildpack

Output of the following commands

-----> uname: Linux XXXXXXXXX 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
              total        used        free      shared  buff/cache   available
Mem:            488         177          31          16         278         257
Swap:           999         100         899
-----> docker version:
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info:
Containers: 7
 Running: 3
 Paused: 0
 Stopped: 4
Images: 25
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.4 MiB
Name: XXXXXXXXX
ID: 5OWA:LNOP:4ZUU:XT2W:NBGV:5AZZ:TIB5:53VM:LBXD:H7BW:Y6WH:PJ35
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
-----> sigil version: 0.4.0
-----> herokuish version:
herokuish: 0.3.24
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v150
  heroku-buildpack-nodejs    v93
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v97
  heroku-buildpack-java      v48
  heroku-buildpack-gradle    v19
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v117
  heroku-buildpack-go        v54
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.8.0
-----> dokku plugins:
plugn: 0.2.2
  00_dokku-standard    0.8.0 enabled    dokku core standard plugin
  20_events            0.8.0 enabled    dokku core events logging plugin
  apps                 0.8.0 enabled    dokku core apps plugin
  build-env            0.8.0 enabled    dokku core build-env plugin
  certs                0.8.0 enabled    dokku core certificate management plugin
  checks               0.8.0 enabled    dokku core checks plugin
  common               0.8.0 enabled    dokku core common plugin
  config               0.8.0 enabled    dokku core config plugin
  docker-options       0.8.0 enabled    dokku core docker-options plugin
  domains              0.8.0 enabled    dokku core domains plugin
  enter                0.8.0 enabled    dokku core enter plugin
  git                  0.8.0 enabled    dokku core git plugin
  global-cert          0.0.1 enabled    dokku plugin that allows setting a global certificate for applications
  logs                 0.8.0 enabled    dokku core logs plugin
  maintenance          0.4.0 enabled    Maintenance mode for apps
  mariadb              1.0.0 enabled    dokku mariadb service plugin
  named-containers     0.8.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.8.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.8.0 enabled    dokku core plugin plugin
  proxy                0.8.0 enabled    dokku core proxy plugin
  ps                   0.8.0 enabled    dokku core ps plugin
  repo                 0.8.0 enabled    dokku core repo plugin
  shell                0.8.0 enabled    dokku core shell plugin
  ssh-keys             0.8.0 enabled    dokku core ssh-keys plugin
  storage              0.8.0 enabled    dokku core storage plugin
  tags                 0.8.0 enabled    dokku core tags plugin
  tar                  0.8.0 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):
DigitalOcean Droplet

How was Dokku installed?:
wget https://raw.githubusercontent.com/dokku/dokku/v0.8.0/bootstrap.sh;
sudo DOKKU_TAG=v0.8.0 bash bootstrap.sh

Steps to Reproduce:
1. Php app with procfile "web: vendor/bin/heroku-php-apache2"
2. git push to dokker

Actual Results:
Pushing to dokku@xxxxxx:phptest
remote: [1G-----> Cleaning up...        
remote: [1G-----> Building phptest from herokuish...        
remote: [1G-----> Adding BUILD_ENV to build environment...        
remote: [1G[1G       [1G-----> PHP app detected        
remote: [1G[1G-----> Bootstrapping...        
remote: 
**remote: gzip: stdin: not in gzip format**        
remote: tar: Child returned status 1        
remote: tar: Error is not recoverable: exiting now        

To xxxxxxxxx:phptest
 ! [remote rejected] slim -> master (pre-receive hook declined)
 ! [remote rejected] 1.0.0 -> 1.0.0 (pre-receive hook declined)
 ! [remote rejected] 1.0.0-rc.2 -> 1.0.0-rc.2 (pre-receive hook declined)
 ! [remote rejected] 1.0.0-rc.3 -> 1.0.0-rc.3 (pre-receive hook declined)
 ! [remote rejected] 1.0.0-rc.4 -> 1.0.0-rc.4 (pre-receive hook declined)
 ! [remote rejected] 1.0.0-slim -> 1.0.0-slim (pre-receive hook declined)
 ! [remote rejected] 1.0.2 -> 1.0.2 (pre-receive hook declined)
 ! [remote rejected] 1.2.0 -> 1.2.0 (pre-receive hook declined)
 ! [remote rejected] 1.2.1 -> 1.2.1 (pre-receive hook declined)
 ! [remote rejected] v1.0.0-RC1 -> v1.0.0-RC1 (pre-receive hook declined)
 ! [remote rejected] v1.0.0-alpha1 -> v1.0.0-alpha1 (pre-receive hook declined)
error: failed to push some refs to 'dokku@xxxxxxx:phptest'

Expected Results:
app deployed correctly

Additional info:
It works if I add the buildpack config as follows
dokku config:set phptest BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php#v119

**Comment by michaelshobbs** [comment]
upgrading your herokuish image and rebuilding/deploying your apps will fix this

```
docker pull gliderlabs/herokuish:latest
dokku ps:rebuildall
```

**Comment by afermon** [comment]
@michaelshobbs Thanks! It does fix the issue.

This was a clean installation (yesterday)  shouldn't it be the latest version?

**Comment by josegonzalez** [comment]
@afermon herokuish wasn't released as a deb package since it's been fixed, so you still want to do that to get the latest fix.

**Comment by afermon** [comment]
@josegonzalez Thanks!
