### ISSUE TITLE
pre-receive hook declined

### ISSUE THREAD

**Issue by harshjv** [dokku/dokku#2651]
Description of problem:

`! [remote rejected] master -> master (pre-receive hook declined)`

Trace: https://gist.github.com/harshjv/94f715dab6e6d7130675997fa10e46b1#file-dokku-trace-log

## `dokku report`

-----> uname: Linux DokkuVM 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:           6967         161        2580           8        4225        6457
Swap:             0           0           0
-----> docker version: 
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.804 GiB
Name: DokkuVM
ID: PNU7:H26I:VBEU:GOBI:MEG5:TJVV:BJVL:6HP7:4Q2O:HJVB:AEJC:3JAL
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.26
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v153
  heroku-buildpack-nodejs    v98
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v99
  heroku-buildpack-java      v51
  heroku-buildpack-gradle    v21
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v120
  heroku-buildpack-go        v62
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.8.0
-----> dokku plugins: 
plugn: 0.2.2
  00_dokku-standard    0.8.0 enabled    dokku core standard plugin
  20_events            0.8.0 enabled    dokku core events logging plugin
  apps                 0.8.0 enabled    dokku core apps plugin
  build-env            0.8.0 enabled    dokku core build-env plugin
  certs                0.8.0 enabled    dokku core certificate management plugin
  checks               0.8.0 enabled    dokku core checks plugin
  common               0.8.0 enabled    dokku core common plugin
  config               0.8.0 enabled    dokku core config plugin
  docker-options       0.8.0 enabled    dokku core docker-options plugin
  domains              0.8.0 enabled    dokku core domains plugin
  enter                0.8.0 enabled    dokku core enter plugin
  git                  0.8.0 enabled    dokku core git plugin
  logs                 0.8.0 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.8.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.8.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.8.0 enabled    dokku core plugin plugin
  proxy                0.8.0 enabled    dokku core proxy plugin
  ps                   0.8.0 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  repo                 0.8.0 enabled    dokku core repo plugin
  shell                0.8.0 enabled    dokku core shell plugin
  ssh-keys             0.8.0 enabled    dokku core ssh-keys plugin
  storage              0.8.0 enabled    dokku core storage plugin
  tags                 0.8.0 enabled    dokku core tags plugin
  tar                  0.8.0 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.): Azure (7 GB and 100 GB Disk)

How was Dokku installed?:
Azure's Dokku Template (https://github.com/azure/azure-quickstart-templates/tree/master/dokku-vm)

Steps to Reproduce:
1. `git push dokku master`

Additional info:
Application is a node project. It doesn't have any github repo as depencency or any submodules. It is just plain express "hello world" application.

**Comment by josegonzalez** [comment]
Is this repository available online somewhere? The `git submodule` part is the bit that is failing, so I sort of doubt that you don't have a submodule in there or an errant `git clone` in your repo.

**Comment by harshjv** [comment]
@josegonzalez The repo is private and it doesn't have any submodules.

**Comment by josegonzalez** [comment]
So it's not a plain "hello world" application then.

In the file `/var/lib/dokku/plugins/available/git/functions`, around line 31, can you remove the redirection of output to `/dev/null` from the line that has `git submodule update --init --recursive` in it, and then try another deploy? That will give you the exact error that you need to investigate.

**Comment by idivait** [comment]
@josegonzalez Thank you for saying the word 'submodule' in this response - Was trying to troubleshoot a similar error and realized I had an old submodule of files in my app that I needed to disconnect.

**Comment by josegonzalez** [comment]
@harshjv were you able to resolve this issue?

**Comment by harshjv** [comment]
@josegonzalez you are right.

The problem is with my git repository and it had a submodule configured. I couldn't find `.gitmodules` while debugging because earlier we removed submodules (but I guess we failed to remove it properly).

Now, I've removed submodule properly and it is working smoothly. Thanks @josegonzalez
