### ISSUE TITLE
latest(?) php buildpack 117 and "rainloop": "gzip: stdin: not in gzip format"

### ISSUE THREAD

**Issue by fwolfst** [dokku/dokku#2653]
Description of problem:

 - deployment of php-application `rainloop` fails
I guess this is due to some php buildpack issue, at least that is what older issues with that gzip error messages were about. A `dokku config:set rainloop "BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php#v119"` does "fix" the issue, but I am not sure if that is how it should be.

Output of the following commands

ARG, read the "+" as "-", seeing just now.

- `uname -a`:
Linux shapeshifter 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
Mem:           2000         639         279          36        1081        1100
Swap:          1021          52         969
- `docker version`:
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
- `docker -D info`:
Containers: 10
 Running: 6
 Paused: 0
 Stopped: 4
Images: 38
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: shapeshifter
ID: TPYW:2SJB:MI3T:6KQO:RFG2:4JUH:7RR5:OOTS:XPSR:76V4:H4MB:ET6R
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

- `sigil -v`:
0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
herokuish: 0.3.24
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v150
  heroku-buildpack-nodejs    v93
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v97
  heroku-buildpack-java      v48
  heroku-buildpack-gradle    v19
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v117
  heroku-buildpack-go        v54
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
- `dokku version`:
0.8.0
- `dokku plugin`:
- If a deploy is failing or behaving unexpectedly:
  - Application name
rainloop (from https://www.rainloop.net/downloads/)
  - The type of application being deployed (node, php, python, ruby, etc.)
php
- Output of failing Dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.):
Virtual kvm/qemu

How was Dokku installed?:
bootstrap script

How reproducible:
Steps to Reproduce:
1.
```
mkdir -p /tmp/rainloop-tmp
cd /tmp/rainloop-tmp
wget https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip
unzip *zip
git init .
git add .
git commit -m "rainloop v1.11.0.203"
git remote add dokku .....
git push dokku master
```

Actual Results:
deploy fails
```
-----> Building rainloop from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> PHP app detected
       
       !     WARNING: No 'composer.json' found.
       Using 'index.php' to declare app type as PHP is considered legacy
       functionality and may lead to unexpected behavior.
       
-----> Bootstrapping...
remote: 
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now

```

Expected Results:
deploy succeeds

**Comment by josegonzalez** [comment]
You need to update herokuish:

```
apt-get update
apt-get install herokuish
```

**Comment by fwolfst** [comment]
Ouch that hurts, I am sorry.I assume that `ssh dokku-shapeshifter
config:set rainloop "BUILDPACK_URL="` together with `
dokku repo:purge-cache rainloop` will "reset" my customly chosen buildpack
and let it fall back to the default one (from herokuis)? If so, I would
add/PR a respective section to
http://dokku.viewdocs.io/dokku/deployment/methods/buildpacks/ , as a
compensation for this stupid issue :)

**Comment by josegonzalez** [comment]
You just `config:unset` the value.

**Comment by fwolfst** [comment]
fair enough. docs are fine at this point i think.
