### ISSUE TITLE
How to remove volumes created while running cron tasks ?

### ISSUE THREAD

**Issue by incyclum** [dokku/dokku#2658]
Hi,

I need to run a cron job every x hours on a deployed app so I added
'dokku --rm run somme-app some-command' to my crontab. Its remove
the created container (using --rm) after running the container. It works,
but it doesn't remove associated volumes.

How can I fix this?

Thanks

**Comment by josegonzalez** [comment]
What volumes are you talking about? Dokku doesn't use native docker volumes for anything.

**Comment by incyclum** [comment]
The cronjob is a background task to update my RSS feeds on a Miniflux deployed app.
See https://github.com/miniflux/miniflux/blob/master/docs/cronjob.markdown

The command is 'dokku --rm run miniflux php /var/www/html/cronjob.php'.
It leaves a dangling volume (/var/lib/docker/volumes/f45...afd07e2b/_data) for every run.

**Comment by josegonzalez** [comment]
This has to do with the [underlying semantics](https://docs.docker.com/engine/reference/run/#clean-up---rm) around `docker run --rm`:

> Note: When you set the `--rm` flag, Docker also removes the volumes associated with the container when the container is removed. This is similar to running `docker rm -v my-container`. Only volumes that are specified without a name are removed. For example, with `docker run --rm -v /foo -v awesome:/bar busybox top`, the volume for `/foo` will be removed, but the volume for `/bar` will not. Volumes inherited via `--volumes-from` will be removed with the same logic – if the original volume was specified with a name it will not be removed.

As a workaround if you are using named volumes, you can add the following to cron:

```shell
docker volume ls -qf dangling=true | xargs -r docker volume rm
```

There isn't anything wrong with how Dokku handles this, so I'm closing this issue.

**Comment by incyclum** [comment]
Thank you
