### ISSUE TITLE
failing installation of dokku behind proxy: unknown flag: --build-args

### ISSUE THREAD

**Issue by Finkes** [dokku/dokku#2665]
Description of problem:

I try to install dokku on Ubuntu behind a corporate proxy following the official documentation. The installation fails during the installation of herokuish with following output: 

```
Adding proxy settings to docker build: --build-args http_proxy=<PROXY_ADDRESS> --build-args https_proxy=<PROXY_ADDRESS>
unknown flag: --build-args
See 'docker build --help'.
dpkg: error processing package herokuish (--configure):
 subprocess installed post-installation script returned error exit status 125
```

I think this is a very simple issue, because the official docker docs says the flag is called **--build-arg** instead of **--build-args**! see : https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

Could you check this?

**Comment by michaelshobbs** [comment]
Can you include ​*all*​ of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by Finkes** [comment]
thanks for the quick fix! When can I expect a new build to be released as .deb package?

**Comment by josegonzalez** [comment]
Jesus be a bit more patient.

I've rebuilt the packages for `0.3.25` and `0.3.26`, and also created a new `0.3.27` release with the updated ruby buildpack. Thanks for reporting the issue.
