### ISSUE TITLE
Deprecate special Linode instructions?

### ISSUE THREAD

**Issue by callahad** [dokku/dokku#2675]
As of version 1.12, Docker will happily use Linux 4.x's `overlayfs` filesystem with its [overlay2 driver](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/), which is evidently a natural successor to AUFS. Linode's kernel supports `overlayfs`.

As such, the warnings at [docs/getting-started/install/linode.md](https://github.com/dokku/dokku/blob/9ee6c7aab630eaccf20d9858b10302e79e467519/docs/getting-started/install/linode.md) and inside [bootstrap.sh](https://github.com/dokku/dokku/blob/ab51c3b4b451e750432954c6dfc20cb5c04665e5/bootstrap.sh#L120-L125) can probably be removed.

**Comment by josegonzalez** [comment]
Sounds good to me. If you want to take care of cleaning up our Linode docs, that would be A+.

**Comment by stephenhowells** [comment]
During a Linode installation you still get this message:

```
Warning: current kernel is not supported by the linux-image-extra-virtual
 package.  We have no AUFS support.  Consider installing the packages
 linux-image-virtual kernel and linux-image-extra-virtual for AUFS support.
```

Is this safe to ignore then?

**Comment by josegonzalez** [comment]
@callahad ?

**Comment by callahad** [comment]
Weird. @stephenhowells, what's the output of the following commands?

- `uname -r`
- `lsb_release -d`
- `sudo docker version`
- `sudo docker info | grep -iE 'storage|filesystem'`

**Comment by joshmanders** [comment]
I've deployed a few instances to Linode without those instructions, so I think it's safe to say it's good to be removed.

**Comment by stephenhowells** [comment]
@josegonzalez @callahad It does list the storage driver as `overlay2` when running `docker info` which I suppose means it's ok? If so then it appears `bootstrap.sh` should be updated to not display the AUFS warning when overlay2 is available.

![image](https://cloud.githubusercontent.com/assets/436173/24672146/a9ee8544-1928-11e7-9390-5897886f2338.png)

**Comment by stephenhowells** [comment]
@callahad 


**uname -r:** `4.9.7-x86_64-linode80`

**lsb_release -d:** `Description:    Ubuntu 16.04.2 LTS`

**sudo docker version:**
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**sudo docker info | grep -iE 'storage|filesystem':**
```
Storage Driver: overlay2
 Backing Filesystem: extfs
WARNING: No swap limit support
```

**Comment by josegonzalez** [comment]
That warning is from us calling the docker bootstrap script, not directly from our bootstrap.

**Comment by callahad** [comment]
Oh, yep, here it is in the upstream Docker install script: https://github.com/docker/docker/blob/9f17b97820912001a1bf7fd827a65b0298b4dd1f/hack/install.sh#L428-L449

Options:

1. Change our `bootstrap.sh` to use APT instead of `curl https://get.docker.com | sh`
2. Add a "safe to ignore the following warning" notice in our `bootstrap.sh`
3. Petition upstream to remove the warning
4. Something else?

**Comment by josegonzalez** [comment]
That would force our install script to only work on Deb-based systems, and also would mean we need to update it whenever they change their repo (lol, often).

We should do both #2 and #3.

**Comment by callahad** [comment]
It'd be easy enough to switch between apt and yum based on `lsb_release` data, falling back to `curl | sh` otherwise, but I'm fine with options 2 and 3 for now. I'll file the upstream issue.

**Comment by josegonzalez** [comment]
@callahad can you also add an appropriate warning to our bootstrap ?

**Comment by callahad** [comment]
Sure. Looks like the `curl | sh` installation method is no longer publicly documented (it's still present at https://docs.docker.com/engine/getstarted/linux_install_help/, but that page is not present in any of the navigation links). In https://github.com/docker/docker/issues/31514 there are a few comments from Docker employees to the effect of:

> "get.docker.com will install the docker-engine packages in a manner as it always has. For new installations, it is recommended to use the new repository"

> "the download.docker.com repository should be used going forward. The get.docker.com repository is maintained to not break existing installs, but eventually no new packages will be published there"

> "How did you arrive on that page? Is it linked somewhere, through search? Perhaps it's an old page and needs to be removed"

That one orphan page itself even discourages using it, suggesting "you should use the [recommended installation procedure](https://docs.docker.com/engine/installation/) for your operating system instead."

From those statements, I'm getting the distinct impression that Dokku should begin planning a move away from `curl | sh` where possible.

**Comment by josegonzalez** [comment]
I guess then lets do that 🤷‍♂️

**Comment by callahad** [comment]
Upstream issue: https://github.com/docker/docker/issues/32361

**Comment by ylluminate** [comment]
So ultimately where are we going to find the linode instructions now?  What are the general preferred steps to follow for a Linode installation at this point since [this](https://dokku.viewdocs.io/dokku~master/getting-started/install/linode/) is gone?

**Comment by josegonzalez** [comment]
Use the normal bootstrap method of installation, which will guide you through setup. If you find that inadequate, please open up a new issue.
