### ISSUE TITLE
Unused $listener_port in nginx.conf.sigil

### ISSUE THREAD

**Issue by callahad** [dokku/dokku#2676]
The nginx.conf.sigil template [defines upstream blocks](https://github.com/dokku/dokku/blob/9ee6c7aab630eaccf20d9858b10302e79e467519/plugins/nginx-vhosts/templates/nginx.conf.sigil#L84) as:

(Reindented for clarity)

```go
{{ if $.DOKKU_APP_LISTENERS }}
  {{ range $upstream_port := $.PROXY_UPSTREAM_PORTS | split " " }}

    upstream {{ $.APP }}-{{ $upstream_port }} {
      {{ range $listeners := $.DOKKU_APP_LISTENERS | split " " }}
        {{ $listener_list := $listeners | split ":" }}
        {{ $listener_ip := index $listener_list 0 }}
        {{ $listener_port := index $listener_list 1 }}
        server {{ $listener_ip }}:{{ $upstream_port }};
      {{ end }}
    }

  {{ end }}
{{ end }}
```

The `$listener_port` variable is unused, and `$upstream_port` is used on the `server` line. Is that correct?

**Comment by callahad** [comment]
It doesn't *seem* right, since `$upstream_port` is an array instead of a single value, but it's been in there for [9 months](https://github.com/dokku/dokku/commit/6c1d6225f9162e33e5af13c30a6ac664374313ab), so maybe it is?

**Comment by josegonzalez** [comment]
Next release should have a fix for this.

**Comment by max2three** [comment]
Before this, I was able to change the default container port from 5000 to 4000 using

`dokku proxy:ports-add node-js-app http:80:4000`.

After upgraded to 0.10.2, my app doesn't work due to #2739 and I need to manually update the `upstream`.

**Comment by josegonzalez** [comment]
@max2three what does it change the port to since 0.10.2?

**Comment by max2three** [comment]
@josegonzalez It uses the `$listener_port` which is 5000.

**Comment by josegonzalez** [comment]
@max2three can you gist the logs of `dokku nginx:build-config` after running `dokku trace on`?

**Comment by max2three** [comment]
@josegonzalez Sorry for the wait, here is the [gist](https://gist.github.com/max2three/6065afbcd75e3767ced51a9109ece6ea) for `dokku nginx:build-config`.

**Comment by josegonzalez** [comment]
Wait why is your `node-js-app` app listening on port `4000`? Is this actually a herokuish app? For those, we expect you to respect the upstream port, which is set to `5000`.

The "fix" for this is to skip upstreams that don't match `upstream_port`. Should be fine?

**Comment by max2three** [comment]
It is a herokuish app, but my bad for not knowing it should always respect the `5000` upstream port as previously I was able to change it to something else.

App is working after I changed to match `upstream_port`. Thanks for the help!

**Comment by joshmanders** [comment]
Your node app should always check for `process.env.PORT` and use that or default to your own. That avoids this issue. :)

**Comment by max2three** [comment]
@josegonzalez After the clarification, does that mean the container's port `5000` shouldn't be altered with `proxy:ports-add` command?

http://dokku.viewdocs.io/dokku/advanced-usage/proxy-management/

`proxy:ports-add <app> <scheme>:<host-port>:<container-port>`

**Comment by josegonzalez** [comment]
If you are using buildpacks, we expect you to support the `$PORT` variable that is set. Assuming you are also using virtualhosts, then that port will always be 5000.

**Comment by josegonzalez** [comment]
Closing as there isn't anything to do here.
