### ISSUE TITLE
Container DNS settings?

### ISSUE THREAD

**Issue by darkpixel** [dokku/dokku#2687]
For some reason, Google's DNS servers (8.8.4.4 and 8.8.8.8) are having problems from Digital Ocean's network where I have a Dokku instance deployed.  Firing up a bash shell inside one of my apps and looking at /etc/resolv.conf, I see only one DNS server--8.8.8.8.  This is causing problems for the container which is trying to use DNS to connect to the database server.

Where does the container get its DNS settings? I've tried rebuilding the app container, but it doesn't appear to get DNS settings from the local system at build time.

**Comment by josegonzalez** [comment]
It uses docker defaults - which I think enable google dns by default. You can override this via the official docker-options plugin.

**Comment by darkpixel** [comment]
Thanks @josegonzalez.
