### ISSUE TITLE
Plugin architecture for web components

### ISSUE THREAD

**Issue by danielepolencic** [dokku/dokku#2688]
**Disclaimer**: this is not a bug report. If you think this shouldn't be here, please close the ticket and I'll post it somewhere else.

I can divided most of Dokku's plugins in three categories:

- Static plugins, such as [dokku-redirect](https://github.com/dokku/dokku-redirect) or [dokku-hostname](https://github.com/michaelshobbs/dokku-hostname). Those plugins augment Dokku with new commands or hooks.
- Lifecycle plugins, such as [dokku-build-hook](https://github.com/fteychene/dokku-build-hook) or [dokku-slack](https://github.com/ribot/dokku-slack). Those plugins consume hooks and are triggered at different phases of the deployment.
- Plugins with UI, such as [dokku-man](https://github.com/beydogan/dokku-man) or [dokku-github-webhook](https://github.com/kiyo-e/dokku-github-webhook).

For the former two, the installation is very simple:

```bash
$ sudo dokku plugin:install <url> --comittish <sha>
```

For the latter, it's not clear how one should proceed. My initial thought process was to deploy the application as I normally would. However the only way to interact with Dokku from within the container is to install [dokku-daemon](https://github.com/dokku/dokku-daemon) and mount the socket in the container with [docker container options](https://github.com/dokku/dokku/blob/master/docs/advanced-usage/docker-options.md).
While this works fine, it's cumbersome. Any developer wanting to install the plugin would need to:

```bash
$ git push origin master # this is the current web ui plugin I want to deploy
# and
$ dokku docker-options:add <yourapp> run /var/run/dokku-daemon/dokku-daemon.sock:/app/dokku.sock
```

The other option is not run the application within the container. While this simplifies the interactions with Dokku, it introduces a lot of extra complexity in managing the lifecycle of the app and bindings (such as `nginx.conf`).

Lastly, it's unclear how a plugin could offer a web ui and some static commands while still being able to be installed with `dokku plugin:install`. As an example, the [dokku-github-webhook](https://github.com/kiyo-e/dokku-github-webhook) plugin offers a convenient way to listen to webhooks (sinatra app) and some extra commands to pull and build the application.

Ideally I'd like to install a plugin that offers a UI and some static commands as any other plugin: `dokku plugin:install`. Is this possibile?

Is there anything else you would recommend exploring?

**Comment by josegonzalez** [comment]
When I deploy applications that need extra configuration, here is what I do:

```shell
dokku apps:create APP
# run configuration steps here
git push dokku master
```

We don't have any current way of orchestrating dokku itself on application deployment. I think this is good, as I would be hesitant to run an arbitrary dokku command on push. Command runs should be explicit, not implicit, imo. One exception is the pre/post deployment tasks functionality, which we'd like to extend further as noted in RFC #2269.

I don't think installing stuff on the host is a great option. To me, thats a bit of a hack and just shows that people don't want to go the extra mile to do it properly (for better or worse). Here is a WIP [dokku-api](http://github.com/dokku/dokku-api) that does it correctly.

Regarding exposing some sort of web ui, some of the plugins already do this. A good example is the elasticsearch plugin, where you can expose the web ui for external use. I'm actually in the process of adding an `nginx-expose` and `nginx-unexpose` subcommand *specifically* for the graphite-grafana plugin, which is another example of a plugin offering a web ui.

Hope that answers your question, and if not, I'm happy to discuss further on [slack](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/).
