### ISSUE TITLE
Failure of predeploy task does not abort deployment

### ISSUE THREAD

**Issue by ayust** [dokku/dokku#2692]
dokku continues with a deployment even when a predeploy command returns a nonzero exit code. This can result in a broken deployment due to a required prerequisite (e.g. running a database migration) not having completed successfully.

**Observed behavior:** deploy continues after failure of predeploy action
**Expected behavior:** deploy aborts, leaving previous version in place

(It's unclear to me what the intended behavior is here, so this may be either a bug or a feature request.)

Observed on Ubuntu 16.04.2 LTS; `dokku version` = `0.8.0`, `docker version`:
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by joshmanders** [comment]
I'd say it's a bug. I'd expect any pre/post deploy tasks failing to abort the deploy... 

http://dokku.viewdocs.io/dokku/advanced-usage/deployment-tasks/

**Comment by josegonzalez** [comment]
Post-deployment tasks will not fail the deploy, as they happen, well, after the deploy is complete. However, a failing pre-deploy task should fail the deploy.

Does anyone want to submit a test-case that we can use to verify the bug/fix it?

**Comment by michaelshobbs** [comment]
related: #2526

**Comment by josegonzalez** [comment]
@ayust do you mind looking at the pr @michaelshobbs made? We can't seem to replicate this issue, so unless you have log output, will be hard for us to figure out what exactly went wrong here.

**Comment by ayust** [comment]
I dug into this a bit further - if I modify the predeploy command we're using to add `&& false` to the end, the deploy is reliably rejected. So it's possible my own due diligence on the predeploy script's exit codes here was insufficient and this was a local issue. I'll close this for now and reopen if it turns out not to be a local issue and I can get you a more self-contained repro case.
