### ISSUE TITLE
apt packages missing for Ubuntu releases

### ISSUE THREAD

**Issue by ineffyble** [dokku/dokku#2704]
So, I'm currently running Ubuntu 16.10 (Yakkety), which isn't listed as supported, but it looks like the problem exists for 16.04 (Xenial) as well.

Running an `apt-get install dokku` to upgrade my installed Dokku from 0.8.0 to 0.9.2 was telling me it was already on the latest version.

Having a look on packagecloud.io, I can see that all recent Dokku deb packages are only tagged as ubuntu/trusty (14.04).

I modified my apt sources to specify trusty as a workaround, but should they be released for other Ubuntu versions too?

**Comment by josegonzalez** [comment]
We've always only had Trusty packages. I've written them in such a way as to support 14.04, 16.04, and Debian Jessie. 

#2263 should implement the release process changes that create a 16.04 repo, but the packages will work just fine for 16.04 now :)
