### ISSUE TITLE
Is there any way to "wait for linked plugins start"?

### ISSUE THREAD

**Issue by 4ndv** [dokku/dokku#2713]
Description of problem:

Every time i reboot my server, my rails application failing to start because it can't connect to linked Redis:

```
2017-04-13T04:07:04.337129264Z app[sidekiq.2]: 11 TID-gn4u232l4 ERROR: Error fetching job: Error connecting to Redis on dokku-redis-postmaster-redis:6379 (Errno::ECONNREFUSED)
2017-04-13T04:07:04.337145064Z app[sidekiq.2]: 11 TID-gn4u232l4 ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection'
2017-04-13T04:07:04.337159610Z app[sidekiq.2]: 11 TID-gn4u232l4 ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:331:in `establish_connection'
2017-04-13T04:07:04.337315052Z app[sidekiq.2]: 11 TID-gn4u232l4 ERROR: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
```

Then i do `dokku ps:restart myapp` and it starts normally

Output of the following commands

```
-----> uname: Linux keith.andv.xyz 4.4.38-std-1 #1 SMP Mon Dec 12 10:45:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:           2003         529         866          40         606        1195
Swap:             0           0           0
-----> docker version: 
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 19
 Running: 7
 Paused: 0
 Stopped: 12
Images: 26
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.38-std-1
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.956GiB
Name: keith.andv.xyz
ID: MYRR:IG5D:EYWZ:TVXG:4NLA:2G23:ZAOR:GOJT:B3WU:RUBG:3VVB:246N
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.27
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v155
  heroku-buildpack-nodejs    v98
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v99
  heroku-buildpack-java      v51
  heroku-buildpack-gradle    v21
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v120
  heroku-buildpack-go        v62
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.9.4
-----> dokku plugins: 
 !     Deprecated: Please use plugin:list
plugn: 0.3.0
  00_dokku-standard    0.9.4 enabled    dokku core standard plugin
  20_events            0.9.4 enabled    dokku core events logging plugin
  apps                 0.9.4 enabled    dokku core apps plugin
  build-env            0.9.4 enabled    dokku core build-env plugin
  certs                0.9.4 enabled    dokku core certificate management plugin
  checks               0.9.4 enabled    dokku core checks plugin
  common               0.9.4 enabled    dokku core common plugin
  config               0.9.4 enabled    dokku core config plugin
  docker-options       0.9.4 enabled    dokku core docker-options plugin
  domains              0.9.4 enabled    dokku core domains plugin
  enter                0.9.4 enabled    dokku core enter plugin
  git                  0.9.4 enabled    dokku core git plugin
  logs                 0.9.4 enabled    dokku core logs plugin
  named-containers     0.9.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.9.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.9.4 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.9.4 enabled    dokku core proxy plugin
  ps                   0.9.4 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  repo                 0.9.4 enabled    dokku core repo plugin
  shell                0.9.4 enabled    dokku core shell plugin
  ssh-keys             0.9.4 enabled    dokku core ssh-keys plugin
  storage              0.9.4 enabled    dokku core storage plugin
  tags                 0.9.4 enabled    dokku core tags plugin
  tar                  0.9.4 enabled    dokku core tar plugin
```

Environment details (AWS, VirtualBox, physical, etc.): Ubuntu 16.04 Scaleway x64 VPS

How was Dokku installed?: default "just-from-the-guide" installation

How reproducible:

Every signle reboot

Steps to Reproduce:
1. Deploy application
2. Link redis
3. Reboot server

Actual Results:

App fail to start

Expected Results:

App not fail to start

Additional info:

**Comment by josegonzalez** [comment]
Weird. We do a docker link, which should hold further containers from starting until dependencies are up...

Can you confirm/deny that via docker docs? If so, sounds like a docker bug. If not, let me think of ways around it, I have one or two ideas...

**Comment by 4ndv** [comment]
Found [this article](https://docs.docker.com/compose/startup-order/) (but about compose) which says:

> However, Compose will not wait until a container is “ready” (whatever that means for your particular application) - only until it’s running.

So looks like it can't guarantee, that on moment of my app startup, redis will be ready to accept connections.

I wasn't successful finding out how exactly Dokku links containers, so that article is only thing that i found.

**Comment by josegonzalez** [comment]
We use the --link arg for docker run, so something to look into.

**Comment by 4ndv** [comment]
[Legacy Links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/):

This, but nothing about startup order:

> Warning: The --link flag is a deprecated legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

**Comment by josegonzalez** [comment]
Fuck ok. Sounds like we need a new hook to start services. Good catch. I'll work on it this week (sat probably) as that's a shit experience for our users.

**Comment by chrisnew** [comment]
My experiences are slightly different:
* Docker is not waiting for dependencies to come up. It just tells, that dependencies need to be running first. It also doesn’t wait for the actual service in each dependency to be ready. So your linking app needs to be able to handle connection errors. 
* The new user-defined network is no longer exposing the environment variables about the link and the linked container’s. But this shouldn’t matter as the most dokku plugins set their own information in custom environment variables.
* Links are no longer written into the host file inside the containers. Docker is now using DNS for such things which also support IPv6, if the user-defined network has IPv6 enabled.

**Comment by tonyc** [comment]
Apologies for bumping this closed issue - but I'm curious how I can take advantage of this change. I'm using Dokku 0.12.5 and dokku-redis 1.2.7, Ubuntu 16.04 running Docker version 18.04.0-ce, build 3d479c0 on DigitalOcean, and I'm running into this same startup-ordering problem when my server boots and everything starts up.  Any pointers would be appreciated!

**Comment by josegonzalez** [comment]
So individual plugins now need to take advantage of this. I _think_ I don't do this for any of the official plugins - the hook is there, we just don't use it. If this is affecting you for datastores, mind filing an issue in the dokku-redis repo? I use that one for coordinating common datastore changes.

**Comment by tonyc** [comment]
Will do! Thank you!
