### ISSUE TITLE
Dokku, aufs and Linode

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#2716]
I was looking for documentation on how to better install Dokku at Linode and I found two blogs offering a small tutorial: one [here](https://blog.codeminer42.com/using-dokku-for-rails-applications-on-a-linode-server-5f2db3f06c2c), the other [here](https://dkurets.me/article/deploy-your-rails-applications-with-dokku-and-linode) .

The first states that the steps suggested are necessary "because of Docker has a better performance with AUFS". I looked for information about AUFS and found it at [Wikipedia](https://en.wikipedia.org/wiki/Aufs), where it is confirmed that "Docker originally used aufs for container filesystem layers". 

My questions are: is AUFS still preferable for Dokku? Is AUFS supplied by installing `linux-image-virtual` and `linux-image-extra-virtual`?

The second tutorial references an [official Dokku documentation](http://dokku.viewdocs.io/dokku/getting-started/install/linode/) about installing and configuring Dokku at Linode. However the page was removed. I am wondering why this page was removed: are there specific reasons such as incompatibility between Dokku and Linode's Linux images, end of contribution or support by Linode  or else?

**Comment by joshmanders** [comment]
Modern versions of docker work fine on linode now.

https://github.com/dokku/dokku/pull/2679
