### ISSUE TITLE
Hostname options during configuration after installation

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#2717]
I purchased a cheap domain name at namecheap for one year.
Dokku should be configured, once installed, by navigating to the host's IP address and entering the Hostname's name. Since I may not renew my domain name at namecheap, I wonder if is it possible to write instead my hostname's ip address, and if this may be not the best choice for most cases after all.

I also wonder what concretely choosing the ip address over the domain name (or vice versa) entail for Dokku.

Once my application is deployed, will I not eventually be able to add any domain of my choice any time afterwards? If I did not misunderstand, the following command can be used to add domains:

`$ dokku domains:add <app> <domain>`

**Comment by joshmanders** [comment]
Yes, you can add any domain to any app as long as that domain is pointed to the server, by running the `domains:add` command.
