### ISSUE TITLE
--force flag can not be used to destroy apps over ssh

### ISSUE THREAD

**Issue by Mawalu** [dokku/dokku#2720]
Description of problem:

I want to destroy a dokku app over ssh as part of my Ci flow and the additional confirmation is a problem. When running the command directly on the server `dokku --force apps:destroy my-app` can be used to bypass the confirmation but this does not work over ssh. I tried `ssh dokku@dokku.me "--force apps:destroy my-app"` but `--force` is always interpreted as a ssh flag which results into an error.

Environment details (AWS, VirtualBox, physical, etc.): VM on dedicated server

How was Dokku installed?: Installer script

How reproducible:
Just run the command

Actual Results:
"unknown option -- -"

Expected Results:
The app should be destroyed

**Comment by josegonzalez** [comment]
Lose the quotes and prefix the `--force` with a `--`.

**Comment by Mawalu** [comment]
Thanks 👍
