### ISSUE TITLE
`dokku report` calls deprecated plugin listing

### ISSUE THREAD

**Issue by weyert** [dokku/dokku#2722]
Earlier today I was reporting an issue (see ##2721) with the `ps:report` command here I noticed that when you run `dokku report` the following is returned:

```
-----> dokku plugins: 
 !     Deprecated: Please use plugin:list
plugn: 0.3.0
```

Might be worth fixing it. Also if you do `dokku help` it not listed the `dokku plugin:list` is available.

**Comment by josegonzalez** [comment]
Closed by #2723
