### ISSUE TITLE
How to choose the application's url in advance

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#2727]
I purchased a domain, say `example.me`
Once deployed my application with Dokku, I would like its url be `www.example.me`
Am I expected to name my application `www` on the Dokku host with the following command?

`$ dokku apps:create www`

**Comment by joshmanders** [comment]
You can read about domain configuration on the docs. http://dokku.viewdocs.io/dokku/configuration/domains/

**Comment by josegonzalez** [comment]
You can create an app:

```shell
dokku apps:create derp
```

And then set any domains you want

```shell
dokku domains:set derp www.example.com
```

And then deploy it as normal:

```
git push dokku master
```

See our [domains](http://dokku.viewdocs.io/dokku/configuration/domains/) documentation for more details.

**Comment by knzudgt** [comment]
@josegonzalez If I set `example.me` during initial configuration (global domain name) and then I do as you suggest, since the documentation says that the typical application's url is `scheme://subdomain.domain.tld`, and the subdomain is inferred from the pushed application name, I would like to avoid that my application, after deployment, will get the url: `http://derp.www.example.me`.
Instead, I would like it to be referenced as `http://www.example.me` or `http://example.me`
Would the following command suit me?

    dokku domains:set derp example.me www.example.me

**Comment by josegonzalez** [comment]
Yes, that works fine. If you call `domains:set`, it overrides any automatic domain addition.
