### ISSUE TITLE
Option to disable docker installation requirement

### ISSUE THREAD

**Issue by gaston23** [dokku/dokku#2728]
Hi Guys!

This is not the first time it happens to me that I have a current docker installation that I want to keep untouched and dokku tries to override. Wouldn't it be better if we give users the option to override current docker installation or to leave it? 

Also, I tried to install dokku in Ubuntu 17 and it was really hard because repos doesn't have a build for it yet. I think it would be great to let users select another repo source, I installed from xenial source  (I hardcoded it) and it worked.

Thank you

**Comment by josegonzalez** [comment]
Can you fill out this issue futher? If not, I'll close it.

**Comment by gaston23** [comment]
@josegonzalez done! sorry, everything I wrote didn't send properly.

**Comment by josegonzalez** [comment]
A few things:

- For Ubuntu, we only ever officially support LTS releases.
- Our packages should work on any Debian-based OS that runs amd64 arch, so no need to "change" our repository. In fact, we only have a `trusty` repo that everyone installs from anyhow.
- If you want to install the packages directly, you can use the [apt](http://dokku.viewdocs.io/dokku/#install-apt) instructions. The bootstrap method is meant to get started, but if you want to customize your installation further, that should not be the method you are using.
- Latest Dokku deb release supports the following Docker deb releases:
  - docker-engine-cs
  - docker-engine
  - docker-ce
  - docker-ee

Given the above, there isn't anything for us to do here, as you should be able to use the underlying apt-based setup to do what you need.
