### ISSUE TITLE
Old containers are still running after machine rebooting

### ISSUE THREAD

**Issue by mpz** [dokku/dokku#2731]
I have old runned docker containers after mahine rebooting or app push.

```
$dokku ps app-name
-----> running processes in container: 9a93dc18d455
```

it is only one container

but in:
`docker ps -a 
`

i have several containers for this app.

It is typical behavior? 
Sush containers are running and spent memory.  
There is any task for stop such containers on dokku?

dokku version: 0.9.0

**Comment by mpz** [comment]
also i try to stop such containers via:

`docker stop container_id`

App works correctly, memory is ok now.

**Comment by josegonzalez** [comment]
Can you be more specific about whats going on? You didn't include the output of `docker ps -a`, so its hard to tell what you mean.

**Comment by mpz** [comment]
`docker ps -a`

in red arrea - not really worked containers.
in green area - really worked containers. 

![2017-04-20 13-00-54](https://cloud.githubusercontent.com/assets/369032/25211731/0f1b285c-25ca-11e7-8ba4-26dd29f62e49.png)

**Comment by michaelshobbs** [comment]
I've seen this at times when the instance/machine was resource starved.

**Comment by josegonzalez** [comment]
It's either that or the containers rebooted with a new IP. Reboots will sometimes trigger this, and the way forward is #2403.
