### ISSUE TITLE
Unable to install dokku RPMs due to 'docker-engine' dependency

### ISSUE THREAD

**Issue by aqtrans** [dokku/dokku#2732]
Description of problem:
This is similar to #2636, except affecting CentOS. It looks like Docker's RPM package name was recently changed from 'docker-engine' to 'docker-ce', and the dokku RPMs continue to rely on the old name:
```
--> Finished Dependency Resolution
Error: Package: herokuish-0.3.27-1.x86_64 (dokku_dokku)
           Requires: docker-engine >= 1.9.1
Error: Package: dokku-0.9.4-1.x86_64 (dokku_dokku)
           Requires: docker-engine >= 1.9.1
 You could try using --skip-broken to work around the problem
```
But I do indeed have Docker installed:
```
(0|0s):> sudo rpm -qa|grep docker
docker-ce-17.03.1.ce-1.el7.centos.x86_64
```

Output of the following commands
- `uname -a`: `Linux frink.es.gy 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- `free -m`: 
 ```
              total        used        free      shared  buff/cache   available
Mem:           7984        5238         321         641        2423        1787
Swap:           511         511           0
```
- `docker version`: 
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Environment details (AWS, VirtualBox, physical, etc.):
Linode VM

How was Dokku installed?:
Attempting to install from the packagecloud.io repo. 

How reproducible:
Should be very reproducible in a CentOS 7 server.

Steps to Reproduce:
1. Install CentOS and Docker from official repo
2. Attempt to use bootstrap.sh

Actual Results:
Yum install portion fails:
```
--> Finished Dependency Resolution
Error: Package: herokuish-0.3.27-1.x86_64 (dokku_dokku)
           Requires: docker-engine >= 1.9.1
Error: Package: dokku-0.9.4-1.x86_64 (dokku_dokku)
           Requires: docker-engine >= 1.9.1
 You could try using --skip-broken to work around the problem
```

Expected Results:
Dokku installed and ready.

**Comment by josegonzalez** [comment]
@ebeigarts can we do `dep | dep` in rpms?

**Comment by aqtrans** [comment]
Thanks for the quick fix! 
I spun up a Debian VM locally in the meantime and am loving Dokku. 😸

**Comment by chrisnew** [comment]
I still get the error on CentOS 7. Did I do something wrong?
```
--> Processing Dependency: docker-engine >= 1.9.1 for package: dokku-0.9.4-1.x86_64
```

**Comment by josegonzalez** [comment]
We haven't released a new version yet, so no.

**Comment by chrisnew** [comment]
Alright! In the meantime I got it running with a dirty trick. Dummy package which provides docker-engine. Looking forward for the next release! :)

**Comment by mimischi** [comment]
@chrisnew Could you elaborate how you actually did this?

@josegonzalez Any estimate when there will be a new release?

**Comment by chrisnew** [comment]
@mimischi actually. I cannot recommend my way at all. It broke more things in the mid term. Updates of docker won’t work etc.

What I eventually did instead:
* Grab the latest source code of dokku
* Spin the dokku workspace up using vagrant
* `make rpm-all`
* Deploy the freshly created rpms the way you like it
