### ISSUE TITLE
Renaming an App Renames the Domains

### ISSUE THREAD

**Issue by nahtnam** [dokku/dokku#2740]
# High-level plan

Lets follow what [heroku did](https://devcenter.heroku.com/articles/fork-app#custom-domains) for forked applications.

- Add `-e "./tls"` to the clone ignore call [here](https://github.com/dokku/dokku/blob/master/plugins/apps/subcommands/clone#L40)
- Use the new `post-apps-clone-setup` trigger from #3349 and create a hook in the `domains` plugin to remove the `URLS` and `VHOST` files from the new app

---
# Original Post

## Description of problem:

If you rename an app from `domain` to `domain_old` the attached domains change from `domain.com` to `domain_old.com`. While sometimes when people are renaming apps, they are also switching domains, but most of the time this is not the case. This shouldn't be the default and if the user wants to change the domain, they should do it manually.

## Steps to Reproduce:

1. `dokku apps:create testing`
2. `dokku domains:add testing testing.com`
3. `dokku apps:rename testing testing_old`

## Actual Results:

Domain goes from `testing.com` to `testing_old.com`

## Expected Results:

Domain should remain the same. If the user wants to change domains, they should use the `domains:add` and `domains:remove` commands.

## Additional info:

The code that needs to be changed can be found here: https://github.com/dokku/dokku/blob/master/plugins/apps/subcommands/rename#L23-L24

**Comment by josegonzalez** [comment]
We should probably only rename the "default" domain, which would follow what heroku does, as opposed to all of them.

**Comment by nahtnam** [comment]
I personally think that even the "default" domain should remain, but a new "default" domain should be added. So both `testing.domain.com` and `testing_old.domain.com` point to the same project until either a new project is created with the name `testing` or the user chooses to remove the domain.

**Comment by josegonzalez** [comment]
Thinking back on this, copying all the domains seems dumb. I'll add a plan to the original post.

**Comment by josegonzalez** [comment]
Closing as there is (finally) a pull request open.
