### ISSUE TITLE
restrict deployment authorization of apps

### ISSUE THREAD

**Issue by Finkes** [dokku/dokku#2741]
Is it somehow possible to restrict the deployment of an app (git push) to only one or more specific ssh keys? 

Background: I want to give another user the possibility to deploy exactly one app on dokku. But I don't want him to be able to push changes to any of my dokku apps.

**Comment by rvalyi** [comment]
I guess this is what you need https://github.com/dokku-community/dokku-acl

**Comment by josegonzalez** [comment]
This is not built into Dokku and likely will not be for a while. For now, you can use either the above plugin or [this one](https://github.com/mainto/dokku-access).
