### ISSUE TITLE
nginx-pre-reload syntax error for Dockerfile deploy

### ISSUE THREAD

**Issue by mrooney** [dokku/dokku#2742]
Description of problem:

We are seeing this when deploying a Dockerfile-based project:

-----> Creating http nginx.conf
-----> Running nginx-pre-reload
remote: /tmp/bashenv.738885525: line 134: syntax error near unexpected token `('
remote: /tmp/bashenv.738885525: line 134: `	eval "$1() { '
remote: /home/dokku/.basher/bash: main: command not found

Output of the following commands

-----> uname: Linux XXX 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:         257853       13658      147154         162       97039      242474
Swap:        262031          45      261986
-----> docker version: 
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64
-----> docker daemon info: 
Containers: 18
 Running: 7
 Paused: 0
 Stopped: 11
Images: 176
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 159
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-42-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 251.8 GiB
Name: XXX
ID: SRU6:EQHD:5UUY:KKH5:6ZNU:E4WS:VTDN:TXQA:QVLS:V5W4:XXXX
Http Proxy: http://XXX:XXX
Https Proxy: http://XXX:XXX
WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.27
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v155
  heroku-buildpack-nodejs    v98
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v99
  heroku-buildpack-java      v51
  heroku-buildpack-gradle    v21
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v120
  heroku-buildpack-go        v62
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.8.2
-----> dokku plugins: 
 !     Deprecated: Please use plugin:list
plugn: 0.3.0
  00_dokku-standard    0.8.2 enabled    dokku core standard plugin
  20_events            0.8.2 enabled    dokku core events logging plugin
  apps                 0.8.2 enabled    dokku core apps plugin
  build-env            0.8.2 enabled    dokku core build-env plugin
  certs                0.8.2 enabled    dokku core certificate management plugin
  checks               0.8.2 enabled    dokku core checks plugin
  common               0.8.2 enabled    dokku core common plugin
  config               0.8.2 enabled    dokku core config plugin
  docker-options       0.8.2 enabled    dokku core docker-options plugin
  domains              0.8.2 enabled    dokku core domains plugin
  enter                0.8.2 enabled    dokku core enter plugin
  git                  0.8.2 enabled    dokku core git plugin
  logs                 0.8.2 enabled    dokku core logs plugin
  named-containers     0.8.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.8.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.8.2 enabled    dokku core plugin plugin
  proxy                0.8.2 enabled    dokku core proxy plugin
  ps                   0.8.2 enabled    dokku core ps plugin
  repo                 0.8.2 enabled    dokku core repo plugin
  shell                0.8.2 enabled    dokku core shell plugin
  ssh-keys             0.8.2 enabled    dokku core ssh-keys plugin
  storage              0.8.2 enabled    dokku core storage plugin
  tags                 0.8.2 enabled    dokku core tags plugin
  tar                  0.8.2 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):

Physical hardware running Ubuntu 16.0.4.1 LTS.

How was Dokku installed?:

http://dokku.viewdocs.io/dokku/#install-apt

How reproducible:

100%

Steps to Reproduce:
1. dokku apps:destroy foobar && dokku apps:create foobar
2. git push dokku release/example:master # dokku remote points to foobar

Actual Results:

Successfully built 2ec6f4f7f08e
-----> Releasing foobar (dokku/foobar:latest)...
-----> Deploying foobar (dokku/foobar:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> No Procfile found in app image
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
=====> renaming container (925735c36ce8) trusting_wright to foobar.web.1
=====> no global VHOST set. disabling vhost support
-----> Unsetting foobar
-----> Unsetting DOKKU_NGINX_PORT
-----> Unsetting DOKKU_NGINX_SSL_PORT
-----> Unsetting DOKKU_PROXY_PORT_MAP
-----> Setting config vars
       NO_VHOST: 1
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP: http:27017:27017
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
remote: /tmp/bashenv.738885525: line 134: syntax error near unexpected token `('
remote: /tmp/bashenv.738885525: line 134: `	eval "$1() { '
remote: /home/dokku/.basher/bash: main: command not found

Expected Results:

I imagine nginx-pre-reload should successfully complete.

Additional info:

Thanks for any tips!

**Comment by josegonzalez** [comment]
It sounds like you ran out of disk space or inodes.

Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? Specifically, I'd like the output from a deploy *after* you've turned on trace mode via `dokku trace on`. It is helpful for debugging problems. Thanks.

**Comment by mrooney** [comment]
Apologies for the missing info, I was just trying to be a good reporter and follow instructions where it said "If you're running 0.4.10+ just use dokku report" :) Does this help! Thanks for investigating and the quick response! BTW, the local machine has 447GB free on /, but are you saying the container might be having problems?

remote: ++ local 'VARS=DOKKU_APP_TYPE='\''dockerfile'\''
remote: DOKKU_DOCKERFILE_CMD='\''CMD ["sh", "-c", "mongod --fork --logpath /var/log/mongodb.log --config /etc/mongodb.conf --smallfiles && \'\''
remote: DOKKU_DOCKERFILE_PORTS='\''27017'\''
remote: DOKKU_PROXY_PORT_MAP='\''http:27017:27017'\''
remote: NO_VHOST='\''1'\'''
remote: ++ echo 'DOKKU_APP_TYPE='\''dockerfile'\''
remote: DOKKU_DOCKERFILE_CMD='\''CMD ["sh", "-c", "mongod --fork --logpath /var/log/mongodb.log --config /etc/mongodb.conf --smallfiles && \'\''
remote: DOKKU_DOCKERFILE_PORTS='\''27017'\''
remote: DOKKU_PROXY_PORT_MAP='\''http:27017:27017'\''
remote: NO_VHOST='\''1'\'''
remote: ++ awk '{print "export " $0}'
remote: ++ return 0
remote: + eval 'export DOKKU_APP_TYPE='\''dockerfile'\''
remote: export DOKKU_DOCKERFILE_CMD='\''CMD ["sh", "-c", "mongod --fork --logpath /var/log/mongodb.log --config /etc/mongodb.conf --smallfiles && \'\''
remote: export DOKKU_DOCKERFILE_PORTS='\''27017'\''
remote: export DOKKU_PROXY_PORT_MAP='\''http:27017:27017'\''
remote: export NO_VHOST='\''1'\'''
remote: ++ export DOKKU_APP_TYPE=dockerfile
remote: ++ DOKKU_APP_TYPE=dockerfile
remote: ++ export 'DOKKU_DOCKERFILE_CMD=CMD ["sh", "-c", "mongod --fork --logpath /var/log/mongodb.log --config /etc/mongodb.conf --smallfiles && \'
remote: ++ DOKKU_DOCKERFILE_CMD='CMD ["sh", "-c", "mongod --fork --logpath /var/log/mongodb.log --config /etc/mongodb.conf --smallfiles && \'
remote: ++ export DOKKU_DOCKERFILE_PORTS=27017
remote: ++ DOKKU_DOCKERFILE_PORTS=27017
remote: ++ export DOKKU_PROXY_PORT_MAP=http:27017:27017
remote: ++ DOKKU_PROXY_PORT_MAP=http:27017:27017
remote: ++ export NO_VHOST=1
remote: ++ NO_VHOST=1
remote: + SIGIL_PARAMS=(-f $NGINX_TEMPLATE APP="$APP" DOKKU_ROOT="$DOKKU_ROOT" NOSSL_SERVER_NAME="$NOSSL_SERVER_NAME" DOKKU_APP_LISTENERS="$DOKKU_APP_LISTENERS" PASSED_LISTEN_IP_PORT="$PASSED_LISTEN_IP_PORT" SPDY_SUPPORTED="$SPDY_SUPPORTED" HTTP2_SUPPORTED="$HTTP2_SUPPORTED" DOKKU_APP_LISTEN_PORT="$DOKKU_APP_LISTEN_PORT" DOKKU_APP_LISTEN_IP="$DOKKU_APP_LISTEN_IP" APP_SSL_PATH="$APP_SSL_PATH" SSL_INUSE="$SSL_INUSE" SSL_SERVER_NAME="$SSL_SERVER_NAME" NGINX_PORT="$NGINX_PORT" NGINX_SSL_PORT="$NGINX_SSL_PORT" RAW_TCP_PORTS="$RAW_TCP_PORTS" PROXY_PORT_MAP="$PROXY_PORT_MAP" PROXY_UPSTREAM_PORTS="$PROXY_UPSTREAM_PORTS")
remote: + local SIGIL_PARAMS
remote: + xargs -i echo '-----> Configuring {}...(using built-in template)'
remote: ++ echo '' ''
remote: ++ tr ' ' '\n'
remote: ++ sort -u
remote: + cat -s
remote: + sigil -f /var/lib/dokku/plugins/available/nginx-vhosts/templates/nginx.conf.sigil APP=foobar DOKKU_ROOT=/home/dokku NOSSL_SERVER_NAME= DOKKU_APP_LISTENERS=172.17.0.8:27017 PASSED_LISTEN_IP_PORT= SPDY_SUPPORTED=false HTTP2_SUPPORTED=false DOKKU_APP_LISTEN_PORT= DOKKU_APP_LISTEN_IP= APP_SSL_PATH=/home/dokku/foobar/tls SSL_INUSE= SSL_SERVER_NAME= NGINX_PORT= NGINX_SSL_PORT= RAW_TCP_PORTS=27017 PROXY_PORT_MAP=http:27017:27017 PROXY_UPSTREAM_PORTS=2701
remote: + is_deployed foobar
remote: + declare 'desc=return 0 if given app has a running container'
remote: + local APP=foobar
remote: + [[ -f /home/dokku/foobar/CONTAINER ]]
remote: ++ ls /home/dokku/foobar/CONTAINER.web.1
remote: ++ echo 0
remote: + [[ 0 -eq 0 ]]
remote: + return 0
remote: + dokku_log_info1 'Creating http nginx.conf'
remote: + declare 'desc=log info1 formatter'
remote: + echo '-----> Creating http nginx.conf'
remote: + mv /tmp/dokku_nginx_template.gL6Dl/nginx.conf.8rOGwC /home/dokku/foobar/nginx.conf
-----> Creating http nginx.conf
remote: + is_deployed foobar
remote: + declare 'desc=return 0 if given app has a running container'
remote: + local APP=foobar
remote: + [[ -f /home/dokku/foobar/CONTAINER ]]
remote: ++ ls /home/dokku/foobar/CONTAINER.web.1
remote: ++ echo 0
remote: + [[ 0 -eq 0 ]]
remote: + return 0
remote: + dokku_log_info1 'Running nginx-pre-reload'
remote: + declare 'desc=log info1 formatter'
remote: + echo '-----> Running nginx-pre-reload'
remote: + plugn trigger nginx-pre-reload foobar '' ''
-----> Running nginx-pre-reload
remote: /tmp/bashenv.109849003: line 135: syntax error near unexpected token `('
remote: /tmp/bashenv.109849003: line 135: `	eval "$1() { '
remote: /home/dokku/.basher/bash: main: command not found
remote: + rm -rf /tmp/dokku_nginx_template.gL6Dl/nginx.conf.8rOGwC /tmp/dokku_nginx_template.gL6Dl
remote: + rm -rf ''
remote: + exit_code=127
remote: + set -e
remote: + [[ 127 -eq 10 ]]
remote: + implemented=1
remote: + [[ 127 -ne 0 ]]
remote: + exit 127
+ exit_code=0
+ set -e
+ [[ 0 -eq 10 ]]
+ implemented=1
+ [[ 0 -ne 0 ]]
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/logs/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/nginx-vhosts/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/plugin/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/proxy/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/ps/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/repo/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/shell/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/ssh-keys/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/storage/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/tags/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in '$PLUGIN_ENABLED_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/enabled/tar/commands git-receive-pack ''\''foobar'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ [[ 1 -eq 0 ]]
+ set +f
+ exit 0
To remote:foobar
 ! [remote rejected] release/example -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@remote:foobar'

**Comment by josegonzalez** [comment]
Well for one, we provide an official [mongodb](http://github.com/dokku/dokku-mongo) plugin that you can use instead of this, which will likely net you better results (you can't link apps to other apps and have to go out onto the network).

Can you gist the output of:

```shell
dokku config APP_NAME --export
```

**Comment by mrooney** [comment]
https://gist.github.com/mrooney/e310ff64ba3003a22217fa23f76c2f1d Thanks again for your help!

**Comment by josegonzalez** [comment]
Can you do `dokku trace off` and then rerun `dokku config APP_NAME --export`?

**Comment by mrooney** [comment]
Haha yes, sorry for that :)

```
% dokku config foobar --export                                                                                                                                                                                                  
export DOKKU_APP_TYPE='dockerfile'
export DOKKU_DOCKERFILE_CMD='CMD ["sh", "-c", "mongod --fork --logpath /var/log/mongodb.log --config /etc/mongodb.conf --smallfiles && \'
export DOKKU_DOCKERFILE_PORTS='27017'
export DOKKU_PROXY_PORT_MAP='http:27017:27017'
export NO_VHOST='1'
```

**Comment by josegonzalez** [comment]
Can you provide this repository publicly? I'm not able to see how this might be replicated easily without it.

**Comment by mrooney** [comment]
Here's a sanitized Dockerfile, which I can at least provide: https://gist.github.com/mrooney/d7b4226c35f928d0de1cd0529528214b. Let me know if you see anything, I will work on a simpler example in the mean time.

**Comment by josegonzalez** [comment]
Does this sanitized version also break for you?

**Comment by mrooney** [comment]
Yes, it does :)

**Comment by josegonzalez** [comment]
Well thats not helpful. Let me know when you have a repository I can use to reproduce the issue, otherwise this isn't anything I can help debug.

**Comment by josegonzalez** [comment]
Note: my current thought is that there is something strange going on in regards to `plugn` initializing to run a trigger. Perhaps you ran out of inodes randomly, which you can check via `df -hi`.

**Comment by mrooney** [comment]
Thanks! It looks pretty available to me. I ran "watch -n 1 df -hi" and watched it during a push, nothing ended up changing.

```
Filesystem                  Inodes IUsed IFree IUse% Mounted on
udev                           32M   479   32M    1% /dev
tmpfs                          32M   884   32M    1% /run
/dev/mapper/vg-root    40M  4.8M   36M   12% /
tmpfs                          32M    23   32M    1% /dev/shm
tmpfs                          32M     5   32M    1% /run/lock
tmpfs                          32M    18   32M    1% /sys/fs/cgroup
/dev/sda1                     122K   326  122K    1% /boot
cgmfs                          32M    14   32M    1% /run/cgmanager/fs
tmpfs                          32M     4   32M    1% /run/user/1002
tmpfs                          32M     4   32M    1% /run/user/1001
```

**Comment by josegonzalez** [comment]
Any luck getting a new repository I can use to reproduce your issue?

**Comment by mrooney** [comment]
Alas, I needed to move on to some tasks with more priority, so I just stood it up with Docker on the same host. Feel free to close if you think that's best!

**Comment by josegonzalez** [comment]
Got it :)

**Comment by jcrben** [comment]
I'm running into this as well in a vagrant machine (ubuntu cloud image) - can probably package it up in a portable format but I'm trying to figure out what core plugin actually hooks into `nginx-pre-reload` as I can't find one.

**Comment by josegonzalez** [comment]
@jcrben did you get everything working?

**Comment by jcrben** [comment]
for posterity, @josegonzalez and I ended up discussing this at length around Aug 20 in the #dokku Slack chat (see e.g. https://gliderlabs.slack.com/messages/C0FP0R13J/search/from:%3C@U6MS6PX3P%7C@jcrben%3E/):
> also if you recall our conversation last weekend, I'm pretty sure that situation was just a weird bug with the `tar:in` method of building - not having trouble when pushing to build

**Comment by Floby** [comment]
In case anyone got this problem, here is what worked for me.

1. I had written my `CMD` as a multiline command (which `docker build` doesn't seem to mind)
2. On first push to dokku, it tried to set its `DOKKU_DOCKERFILE_CMD` config by (i assume) `sed`ding the line where `CMD` appears in the dockerfile. In my case it set `DOKKU_DOCKERFILE_CMD="CMD  [ \"` which in turn made some stuff go crazy in the generated bash scripts afterwards
2. After fixing my Dockerfile to have a simpler `CMD` entry, the problem persisted as the config was now set and took precedence.
3. After unsetting the config entry and repushing the repo, it worked better (well not the same problem at least ;)

**Comment by josegonzalez** [comment]
@Floby mind opening a new issue with the exact contents of your Dockerfile/a reproduction of your issue?

**Comment by simpleshadow** [comment]
@Floby Just experienced this issue. Thanks for the resolution. Fixed it with a single line `CMD` as well.

Many of the other issues I came across were indicating my "syntax error" had to do with running out of disk space but I doubted it given I was on a fresh box.

**Comment by josegonzalez** [comment]
@simpleshadow can you post a new issue with the exact contents of your Dockerfile/a reproduction of your issue? I'd like to fix this in Dokku core but a comment on a years old, potentially unrelated issue doesn't help...

**Comment by madwort** [comment]
Think I just hit the same issue. 

In `Dockerfile` I have something like:
```
CMD ["uwsgi", \
	"--hook-master-start", "unix_signal:15 gracefully_kill_them_all", \
	"--http-socket", "0.0.0.0:5000", \
...etc...
```

if I run `dokku config myproject --export`, I get this bad looking `DOKKU_DOCKERFILE_CMD`:
```
DOKKU_CHECKS_SKIPPED:    _all_
DOKKU_DOCKERFILE_CMD:    CMD ["uwsgi", \
DOKKU_DOCKERFILE_PORTS:  5000
```

**Comment by josegonzalez** [comment]
In 0.22.0, we'll be removing `DOKKU_DOCKERFILE_CMD` and `DOKKU_DOCKERFILE_ENTRYPOINT`, so that should go away completely :)
