### ISSUE TITLE
Should nginx return 444 for requests without hostname header?

### ISSUE THREAD

**Issue by puterleat** [dokku/dokku#2743]
In Django there is an ALLOWED_HOSTS setting which is used as a security measure against XSS attacks. It's recommended that any proxy sitting in front of django does not forward requests without a suitable hostname header, e.g. see http://stackoverflow.com/questions/18220519/how-to-disable-djangos-invalid-http-host-error

This can be implemented in nginx like so: http://stackoverflow.com/questions/15238506/djangos-suspiciousoperation-invalid-http-host-header/17477436#17477436

Should Dokku perhaps implement this kind of bad request filtering by default?

**Comment by josegonzalez** [comment]
- What happens when a user doesn't set domains for their app?
- What happens for users using a custom template?
- What happens when you are using a wildcard domain?
- What happens if you don't want this behavior?

**Comment by puterleat** [comment]
> What happens when a user doesn't set domains for their app?

Is this a common use case? Would they access it through the bare IP?

> What happens for users using a custom template?

I've not used custom templates, so I'm not sure what a sensible default would be.

> What happens when you are using a wildcard domain?

The proxy would filter any request with a hostname which did not match the wildcard?

> What happens if you don't want this behavior?

Without wanting to sound flippant, perhaps you know what you are doing and would be able to disable it?

I guess my question (and it genuinely was a question) was whether matching requests to domains should be the default. If it doesn't make sense as a default, what's the best way for users to enable it currently? Could we document that?

**Comment by josegonzalez** [comment]
- They would access their apps via `ip:port` or `domain:port` I suppose.
- Maybe nothing, and we just document "hey this is a new thing we're doing with the default templates"?
- Does that trick work with wildcard domains?
- True.

Secure by default seems like a good bet. Our next minor will be PCI compliant by default - you can allow older browsers if you wish via a custom template - so this also seems like a reasonable addition.

Our template is here if you want to take a crack at it: https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil

I wonder if there is a way to do this without extra variables though?

**Comment by mimischi** [comment]
To overcome this problem I usually define a `00-default` site in nginx showing a blank page. This way I don't get any `invalid HTTP host` errors in Django, when some bots try to access my sites by the server IP.

**Comment by josegonzalez** [comment]
I'm going to close this.

- No one has made a pull request for it.
- It is relatively easy to workaround by creating an `00-default` app - which is desirable in some cases.
- You can disable this by customizing your application's nginx.conf.sigil.

If someone wants to implement this, feel free to submit a pull request.
