### ISSUE TITLE
How to uninstall 

### ISSUE THREAD

**Issue by webmutation** [dokku/dokku#2744]
Is there a simple way/script to uninstall dokku? I did not find this on the documentation.

installed using
sudo DOKKU_TAG=v0.9.4 bash bootstrap.sh

**Comment by josegonzalez** [comment]
As you installed a tag, `apt-get purge dokku` is what you want. Or the equivalent on arch/centos I suppose.

But my opinion on this is that you should throw away your VM and bring up a new one. *shrug*.
