### ISSUE TITLE
Ability to specify base image in app or plugin

### ISSUE THREAD

**Issue by rvalyi** [dokku/dokku#2745]
Hello, in some cases it could be handy if the application itself or eventually a plugin could set some custom base image before the buildpacks are applied.

Today one can do that with the dokkurc file. But this is system wide then and this can be a bit annoying. I looked at the current code if I could change the DOKKU_IMAGE in a plugin hook such as post-extract (so based on some app file analysis I would like to eventually switch the base image) but I couldn't figure out anything. If I try to export DOKKU_IMAGE again it doesn't override the value where it is called.

Currently, the DOKKU_IMAGE is set by sourcing dokkurc or setting its default value in the dokku executable and it is used in:
```
plugins/common/functions:      local id=$(docker run $DOKKU_GLOBAL_RUN_ARGS -d -v $CACHE_DIR:/cache -e CACHE_PATH=/cache $DOCKER_ARGS $IMAGE /build)
```

Is there any way to override it? Any simple refactor I could contribute to allow it? Thanks.

**Comment by josegonzalez** [comment]
You can do this by using a `.dokkurc/` file or using a dockerfile.

**Comment by rvalyi** [comment]
problem is using a Dockerfile will skip the buildpack logic. You could perfectly imagine to use a more complete specialized base image for some sort of project to speed up the build while you may not want to use it for all containers (the dokkurc file). Any other idea?

**Comment by josegonzalez** [comment]
We don't currently have a way to do that. I suppose we could create a new plugin trigger, but I'm loathe to add things for good reason.

Why dont you wish to use your base image globally?

**Comment by rvalyi** [comment]
I work with the Odoo open source ERP https://github.com/odoo/odoo. Its git code base is around 500 Mo even for a shallow clone (and because it is a moving target you can hardly use a shallow clone). Code differs vastly between Odoo version , 9 or 10. So when you fire an Odoo instance for some company, you typically load your customization modules in the /app directory while you use Odoo as a library downloaded by a specialized buildpack ( https://github.com/akretion/heroku-buildpack-buildout ). Even when using the cache directory smartly to cache odoo, it would still be very handy to be able to use a different specialized base image. And for instance I also deploy all sort of other projects on a Dokku host, I feel it is invasive to always use our unique Odoo specialized base image.

**Comment by fzerorubigd** [comment]
Is this a good thing to load the base-image from the app configuration? I need to change the base image per-app, so I can set a something like DOKKU_IMAGE (or some other variable name) on app config and  the build use that 
if this is good, I think I can implement it .

**Comment by josegonzalez** [comment]
@fzerorubigd that works fine for me for now.
