### ISSUE TITLE
Pre-receive hook declined, dokku trace doesn't seem to have any error message

### ISSUE THREAD

**Issue by CherryDT** [dokku/dokku#2748]
I am trying to push a new version of a project I have. It worked great before. But now I cannot push anymore. I enabled `dokku trace` and this is the output: https://gist.github.com/CherryDT/90cd76f6cd9ad8a05581cd501790f89c

I scanned the output for possible error messages but I didn't really find anything.

`dokku report` output: https://gist.github.com/CherryDT/027d6d251a7320d8f6546e904d8bdfe9

Environment is AWS EC2.

**Comment by josegonzalez** [comment]
Judging from the output, looks like either you have a permissions issue on the repo on your box or you ran out of diskspace/inodes.

- Change permissions: `chown -R /home/dokku/APP_NAME`
- Check disk space: `df -h`
- Check inodes: `df -hi`

**Comment by CherryDT** [comment]
I will check it, thanks - how did you get to those conclusion? I would like to understand it so I can identify such issues myself next time.

**Comment by josegonzalez** [comment]
It seemed to fail on `git reset`, meaning something is either wrong with the repo (and it cant reset) or something is wrong with your disk (you ran out of space/inodes).

**Comment by CherryDT** [comment]
It was indeed disk space. I had moved the containers to an external storage but failed to realize that the cache directories will still eat disk space. What is the recommended way to move them? Can I stop the services, move `/home/dokku` and symlink it (I did the same for `/var/lib/docker`), or would this cause problems?

**Comment by josegonzalez** [comment]
Will maybe cause issues on reboot if you don't set docker/dokku stuff to wait on your mounted drives to boot.

**Comment by joshmanders** [comment]
Perhaps we should put a list of common reasons for a push failing, as the docs just say "Turn trace on" and that's about it. 

http://dokku.viewdocs.io/dokku/getting-started/troubleshooting/

**Comment by josegonzalez** [comment]
@joshmanders pull requests welcome.

Might also be worth adding `df -h` and `df -hi` to the `dokku report` output.
