### ISSUE TITLE
One request at a time? Which configs to look at and change (django, dokku, nginx)? 

### ISSUE THREAD

**Issue by szeptak1** [dokku/dokku#2750]
Hi, 
I don't where to look, where to find solution for my problem. 

I open in browser custom form in Django admin created by me, put some values - text field with 20K rows.
It is processing 2-6 minutes, each line creating new record - it is ok. 

But the problems is when it is processing, none of the admin pages are available - pages are loading until processing in form is finished. If I open new tab in web browser and try to do something in django admin I have to wait.

It is anoying because I am not the only one who is using Django Admin and everyone have to wait if someone is using the form.

It seems like 1 request (or maybe one process) is allowed. I change "ps scale web=4", and didn't help.

Any ideas where could be the problem ? 
Nginx? 
Dokku? 
Django configuration? 

Thanks

**Comment by joshmanders** [comment]
This sounds like an issue with django not nginx/dokku.

**Comment by josegonzalez** [comment]
We run 4 unique containers when you scale processes, so it's likely that you are writing to your database with some sort of exclusive lock which blocks reads.

You may wish to move your text processing to a background worker, such as celery, as long-running web requests are a bit of an anti-pattern.
