### ISSUE TITLE
Create /home/dokku/.ssh/authorized_keys if doesn't exist

### ISSUE THREAD

**Issue by PWAckerman** [dokku/dokku#2752]
This issue was suggested by @josegonzalez after helping me troubleshoot an issue with ssh keys that only recently surfaced on a long-running instance of dokku. If `authorized_keys` has been removed, this seems to break or impair the `ssh-keys:add` command, resulting in `No public keys found.` when trying to execute the command.

The suggestion was to create the file if not present, and make sure it has appropriate permissions:
`touch /home/dokku/.ssh/authorized_keys && chown dokku:dokku /home/dokku/.ssh/authorized_keys && chmod 644 /home/dokku/.ssh/authorized_keys`

**Comment by rgroothuijsen** [comment]
Can't replicate this one on my test box, as ssh-keys:add does create a new authorized_keys file after I delete it. Looking at the source, it seems like the command should touch authorized_keys by default as well. Might be strictly a permissions issue.

Test environment: Debian 8.7 (3.16 kernel)
Test version: Dokku 0.9.4

**Comment by josegonzalez** [comment]
@rgroothuijsen can you point out where in the dokku codebase we touch the `authorized_keys` file? I just looked and that doesn't seem to be the case.

**Comment by rgroothuijsen** [comment]
In the file "plugins/ssh-keys/subcommands/add", a call is made to a function called create_ssh_key_file. This function shows up in the file: "plugins/ssh-keys/functions":

```
create_ssh_key_file() {
declare desc="Ensure the public key file exists"
touch "${DOKKU_ROOT}/.ssh/authorized_keys"
}
```

**Comment by josegonzalez** [comment]
@PWAckerman can you add the normal debugging information we ask for in our `ISSUE_TEMPLATE.md` ? Thanks.

**Comment by josegonzalez** [comment]
@rgroothuijsen good catch, missed that completely.

**Comment by PWAckerman** [comment]
@josegonzalez Version currently running on that server is 0.7.2, so yes, older than 0.8.0

**Comment by josegonzalez** [comment]
Awesome great, so nothing to do here :)

Thanks again @rgroothuijsen !
