### ISSUE TITLE
Feature request for comments: non web checks?

### ISSUE THREAD

**Issue by fruitl00p** [dokku/dokku#2760]
### High Level Plan:

See https://github.com/dokku/dokku/issues/2760#issuecomment-490674563

### Original Post

Description of problem:
I'd like to propose a feature addition to the `CHECKS` handling of non-web processes. (and this might also be related to #2582 ) Currently the [CHECKS](https://github.com/dokku/dokku/blob/master/plugins/checks/check-deploy) only handles web processes or at least only allows defining how / what to check for web processes. I'd like to propose also being able to check non-web processes.

This would change the `CHECKS`-file definition a bit, but in my opinion would lead to a much cleaner interface.

Suggestion:
Instead of a base CHECKS file, I propose (also) supporting a CHECKS.json file which (currently) would be something of the following:
```json
{
	"web": {
		"url": "",
		"response": "",
		"wait": "",
		"timeout": "",
		"attempts": ""
	},
	"some-other-proctype-as-defined-in-Procfile": {
		"script": "this-could-be-some-script-thats-executable-in-the-environment?",
		"url": "this could be allowed as the non-web might still expose something?",
		"wait": "same as the other",
		"timeout": "same as the other",
		"attempts": "same as the other"
	}
}
```

The actual deploy-checks could first see if there is a CHECKS.json definition and otherwise fallback to 'regular' CHECKS as currently. But the JSON spec would increase the possibilities of custom checks (i.e. the `web`-proctype could also have a 'script' key that would manually do the 'curl' et al. The only requirement of the 'script' is that it returns a 0 / 1 exit status (the normal way of clean exiting a shell-script)

The migration from old to new would be something like these:
Old:
```
/status-check THIS IS MY TEXT ON THE STATUS PAGE
```
New:
```json
{
	"web": {
		"url": "/status-check",
		"response": "THIS IS MY TEXT ON THE STATUS PAGE"
	}
}
```
We could even go further in the simplification and might possibly use this:
```json
{
	"/status-check": "THIS IS MY TEXT ON THE STATUS PAGE"
}
```
The way this works would be something like:
- check for known 'Proctypes' (and resolve #2582)
- include the known default `web`
- match those against the given checktypes (`/status-check` in this case)
- realize it doesn't match the Procfile defintiion (as there doesnt have to be any)
- fallback to `web` and process the check itself: which is in this case a string 
- thus the check would be does `/status-check` match `THIS IS MY TEXT ON THE STATUS PAGE`

In other words a spec for the `CHECKS.json` would be something like:
```json
{
	"proctype-or-url": "The value would be the string to match the URL with and is the simplest form of the new CHECKS.json definition.",
	"another-form-of-proctype-or-url": {
		"urlKey-or-the-actual-url": "The value would be the URL and is required in case of the object style definition",
		"wait": "The amount of seconds to wait before hitting the url. A specific optional keyword that only accepts integers, defaults to 5",
		"attempts": "The number of attempts. A specific optional keyword that only accepts integers, defaults to 5",
		"timeout": "the timeout in seconds. A specific keyword that only accepts integers, defaults to 30",
		"script": "A specific keyword that only accepts strings pointing to executables within the app. If both the url-key (or an unknown key) is given, this is ignored."
	}
}
```

I hope this is clear (enough) to start a discussion. It would allow for easy CHECKS as currently available, including fallback for backwards compatibility but also allow for future enhancements (without increasing the complexity of the format / configuration)

This is merely a discussion before i start meddling with a PR ... (I've looked into the current plugin status and it seems like this could be built without breaking too much...)

Any thoughts?

**Comment by josegonzalez** [comment]
I'd prefer it if we somehow added these checks to the app manifest. Might make sense to see if there is some work being done by heroku to add healthchecks or similar to their app manifest, and incorporate that into our implementation.

BTW, I would maybe look at how healthchecks are designed in consul, as they've done some excellent work around process healthchecking.

**Comment by fruitl00p** [comment]
I fully agree on inclusion into the app manifest. I was just building upon the current CHECKS implementation and seeing where it could go. I couldn't find anything in Heroku regarding the dokku-way of a CHECKS file anyway.. Do you have any insight into this?

As for Consul, my current proposal sort of is like [theirs](https://www.consul.io/docs/agent/checks.html) already... Although i agree on the keys being named differently and my proposal being more dokku-minded ... But the basics are more or less the same for the spec definition at least...

**Comment by josegonzalez** [comment]
https://github.com/app-json/app.json is their app manifest repo. Worth filing an issue or poking around to see if they added something similar to their spec?

**Comment by fruitl00p** [comment]
I've been looking into the app.json specs and they have no mentioning on the actual status checks. I'll post and issue there to gauge their interest...

**Comment by josegonzalez** [comment]
I'm going to close this. It's a great idea - and one that I would love to see in the future - but given the lack of movement, I think it is unlikely to happen in the future. I also personally think this falls under the purview of the specific scheduler in use, and our move to support multiple schedulers will push this further away from Dokku's authority.

If someone would like to implement something along the lines of this issue, I would be happy to review and merge it in the future :)

**Comment by fruitl00p** [comment]
Understood. It has indeed been too quiet (atleast on the app.json repo)

You mentioned the move to support multiple schedulers... Is there a roadmap for the entirety of dokku available somewhere? And why would the scheduler be of influence for checking the health of the app / process being deployed? 

thnx!

**Comment by josegonzalez** [comment]
Other than the Milestone 1.0 - which are things we are for sure going to have in our 1.0 release - there is no roadmap. Things get done as I have time/get pull requests.

I think most schedulers have a way to perform application healthchecks - nomad integrates with consul to do this for instance - so we'd rely on them for application health.

**Comment by josegonzalez** [comment]
Related - new - format: https://devcenter.heroku.com/articles/buildpack-builds-heroku-yml

**Comment by fruitl00p** [comment]
@josegonzalez this would entail a pretty big rewrite to incorporate any form of 'release phase' checks. Also I haven't yet found the non-web spec in the wercker.yml (as the wercker.yml spec only seems to include a single 'run' / 'web' command) where this check should / probably must be a part of... 

In any case, lets see where they take this!

**Comment by josegonzalez** [comment]
In the run-up to adding [kubernetes](https://github.com/dokku/dokku-scheduler-kubernetes) and [nomad](https://github.com/dokku/dokku-scheduler-nomad) support, I think it's worth re-opening this. Here is an example of what I'd want in the app.json manifest:

```json
{
  "healthchecks": {
    "web": [
        {
          "type":        "readiness",
          "name":        "Healthcheck",
          "description": "Checking if the app works",
          "path":        "/health/ready",
          "content":     "this would only be checked for docker-local because kubernetes doesn't support content checks"
        },
        {
          "type": "liveness",
          "path": "/health/live",
          "initialDelaySeconds": 10
        }
    ],
    "worker": [
        {
          "type": "readiness",
          "command": ["some", "command", "here"]
        }
    ]
  }
}
```

A few notes:

- `readiness` checks (naming from kubernetes) roughly corresponds with the existing `CHECKS` support. They _do_ continue running after the fact though, unlike with `CHECKS`.
- `liveness` checks would be kubernetes only at first, but we could support them for Dokku if we desire parity.
- If a `liveness` check fails, the container is restarted under kubernetes.
- If a `readiness` check fails, traffic is no longer served to the container (think nginx upstream healthchecks)
- The `CHECKS` format supports checking if there is specific content on the page. Kubernetes probes do not support this, and only check that the response code is between 200-400 (not inclusive of 400).
- `command` type checks would be new, and correspond with a `docker exec` call (docker-local) and the `exec` probe (kubernetes)
- HTTP healthchecks could support custom headers, same as on kubernetes.
- We would support both formats, though the `app.json` spec would become canonical, and deprecate the `CHECKS` format.

What would this mean in terms of actual work?

- Revamped `checks` plugin. We can support the existing `CHECKS` format at the same time, and remind folks to move to a non-deprecated form.
- We could initially support _just_ readiness checks - and document the caveat when running under kubernetes. Supporting both wouldn't be hard though.
- For docker-local, we could build a daemon that persistently runs checks as specified for each app (future work).

**Comment by fruitl00p** [comment]
@josegonzalez that looks **really** nice! It's not overly hard to read, it corresponds to a leading solution in naming, spec and does provide a way forward!

Awesome!

**Comment by josegonzalez** [comment]
Of note: the Kubernetes plugin for dokku now has some flavor of this. Next up is to Port that functionality into the docker-local core plugin...

**Comment by josegonzalez** [comment]
Okay this is pretty far along now. I have a new binary [here](https://github.com/dokku/docker-container-healthchecker) that handles healthchecks in the format I want. There may be one or two new features to add to it, but it is ready to integrate into Dokku.

One thing to note is that this will completely remove support for the existing `CHECKS` file format. I'm doing that because the migration path is kinda finicky - generating json from the `CHECKS` file doesn't seem fun - and it is easier for me to just remove the functionality. I think this is a good tradeoff given the flexibility of the new format.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
