### ISSUE TITLE
Update documentation with user recommendations for Dockerfile template

### ISSUE THREAD

**Issue by ZiadSalah** [dokku/dokku#2770]
Hello,

Jose has been kind enough to help me with Dokku, and during our chats we realised that the documentation doesn't currently have a section that recommends a starting Dockerfile template nor does it include user recommendations on what to include or exclude.

In particular, Jose thinks the documentation should state how cmd vs entrypoint works with dokku.

**Comment by fruitl00p** [comment]
Isn't there already some documentation regarding the difference / usage of `CMD` vs `ENTRYPOINT` [here](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/#procfiles-and-multiple-processes)?

One allows for overriding (`CMD`) whilst the other (`ENTRYPOINT`) is non-overridable but only accepts parameters from dokku ?

I'd be happy to add something to the docs, but exactly what was the confusion?

**Comment by ZiadSalah** [comment]
Hi fruitl00p, it looks like we just missed that part of the documentation, apologies. That looks good enough for me, I'll close this issue.

**Comment by fruitl00p** [comment]
@ZiadSalah no problem!
