### ISSUE TITLE
Investigate if it's possible that there's no need to delete the cache dir for dockerfile apps

### ISSUE THREAD

**Issue by ZiadSalah** [dokku/dokku#2771]
Description of problem:
I had a Dockerfile app deployment on Dokku that had an entrypoint definition instructing it to run a jar file. When attempting to delete the app, it would appear that Dokku would go to delete the app cache directory, which would trigger the entrypoint, which would attempt to start the jar file.

The side effect is that I was unable to delete the app, and would have to start a new terminal window because I couldn't grab control back.

Jose suspects that for Dockerfile deployments there might be no need to delete the cache dir.

**Comment by josegonzalez** [comment]
Closing as there is a pull request up.
