### ISSUE TITLE
Support for docker.io packages maintained by Ubuntu

### ISSUE THREAD

**Issue by feldi88** [dokku/dokku#2775]
At the moment, dokku requires one of four different docker packages to be installed: `docker-engine-cs (>= 1.9.1) | docker-engine (>= 1.9.1) | docker-ce | docker-ee` (see https://github.com/dokku/dokku/blob/master/debian/control)

Nevertheless, there exists a further, quite importan one: `docker.io` (see http://packages.ubuntu.com/de/xenial/docker.io)
It is maintained by the Ubuntu community and available in the official package sources. There are a few use cases, where you have to use this version, for example, if you use docker in a lxc/lxd container.

Since this package depends on the offical docker sources, and the version is recent enough to contain all features used by dokku, I don't see any problems to add this package as a fifth variant for the docker dependency.

**Comment by josegonzalez** [comment]
@fruitl00p Mind making a PR with your change to fix this issue?
