### ISSUE TITLE
Problem to set variables for the Dockerfile file

### ISSUE THREAD

**Issue by templth** [dokku/dokku#2776]
Does the way to set variables for the Dockerfile file still apply for latest version of Dokku? I use Dokku version 0.9.4. I saw the issue https://github.com/dokku/dokku/issues/1860 but I can't make this approach work, i.e. can't get the variable into the file...

Here is the command I use:

```
dokku docker-options:add myapp build '--build-arg "NG_ENV=prod"'
```

and in my Dockerfile file:

```
FROM node:6.9.2

ARG NG_ENV

RUN mkdir -p /app

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app

COPY package.json /usr/src/app/
RUN npm install

RUN $(npm bin)/ng build --aot --environment ${NG_ENV}

EXPOSE 3000

CMD [ "npm", "start" ]
```

I have nothing in the `NG_ENV` variable...

Thanks very much for your help!

_____

## Additional hints

__uname -a__: `Linux prod-myapp 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

__free -m__:

```
              total        used        free      shared  buff/cache   available
Mem:            992         163         107          10         721         611
Swap:             0           0           0
```

__docker version__:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

__docker -D info__:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-77-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.4MiB
Name: prod-myapp
ID: MFYU:LFXZ:JRNE:MGZT:L5RC:AYRW:PUQW:O37A:3RUC:L3OK:2CCB:HRZV
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

__sigil -v__: `0.4.0`

__docker run -ti gliderlabs/herokuish:latest herokuish version__:

```
herokuish: 0.3.28
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v158
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v99
  heroku-buildpack-java      v51
  heroku-buildpack-gradle    v21
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v121
  heroku-buildpack-go        v64
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
```

__dokku version__: `0.9.4`

_______

## Output

(with `dokku trace on`)

```
-----> Cleaning up...
-----> Building myapp from dockerfile...
-----> Setting config vars
       DOKKU_DOCKERFILE_PORTS: 3000
-----> Setting config vars
       DOKKU_DOCKERFILE_CMD: CMD [ "npm", "start" ]
remote: build context to Docker daemon 835.6 kB
Step 1/11 : FROM node:6.9.2
 ---> faaadb4aaf9b
Step 2/11 : ARG NG_ENV
 ---> Using cache
 ---> bc15c7909c3f
Step 3/11 : RUN mkdir -p /app
 ---> Using cache
 ---> 91a7d779c29c
Step 4/11 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 5fc3f5f03e90
Step 5/11 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 4bb567157a2b
Step 6/11 : COPY . /usr/src/app
 ---> bfee9d3e5980
Removing intermediate container 536fc9df71ab
Step 7/11 : COPY package.json /usr/src/app/
 ---> ca314023f6d5
Removing intermediate container 4dfac19a8a33
Step 8/11 : RUN npm install
 ---> Running in 09b6cec7f4bd

(...)

npm info ok 
 ---> 564b3d9851f9
Removing intermediate container 09b6cec7f4bd
Step 9/11 : RUN $(npm bin)/ng build --aot --environment ${NG_ENV}
 ---> Running in 1e5a1f86c29a
npm info it worked if it ends with ok
npm info using npm@3.10.9
npm info using node@v6.9.2
npm info ok 
Environment "" does not exist.
remote: The command '/bin/sh -c $(npm bin)/ng build --aot --environment ${NG_ENV}' returned a non-zero code: 1
remote: 
To 178.62.215.242:myapp
 ! [remote rejected] develop -> master (pre-receive hook declined)
```

**Comment by fruitl00p** [comment]
Could you have a typ0 in your `dokku docker-options` command? It seems like you're removing the option on build?

**Comment by templth** [comment]
Yes you're right, @fruitl00p! I updated the snippet. Thanks very much for pointing this out!

**Comment by fruitl00p** [comment]
@templth could you try again with the following:
`dokku docker-options:add myapp build '--build-arg NG_ENV=prod'`
(first remove the old, then add the new, or just edit the `DOCKER_OPTIONS_BUILD`-file in the /home/dokku/{APP_NAME}/ folder)

**Comment by templth** [comment]
@fruitl00p thanks for your answer!

I tried what you proposed. I can see the option in the `DOCKER_OPTIONS_BUILD` file but the variable within the `Dockerfile` is empty.

When the content of this file is executed, this corresponds to the `build` phase, right?

**Comment by fruitl00p** [comment]
That should do it yes... Weird... Maybe i'm missing something that @josegonzalez might see?

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

As well, please include the output of a deploy after running `dokku trace on`

**Comment by templth** [comment]
Thanks, guys! I added the requested additional hints in the question... Thanks very much for your help!

**Comment by josegonzalez** [comment]
That is not the output after running `dokku trace on`. Please run that command, and then trigger a deploy. Then, gist the entire output for me.

**Comment by templth** [comment]
@josegonzalez not to sure to understand what you expect... Here is what I did:

* I logged in on the host where I want to deploy
* I execute the command `dokku trace on` on this host and get the message `Enabling dokku trace`
* On dev, I execute the commands: `git remote add dokku dokku@<some-ip>:myapp` and `git push dokku develop:master`
* I have the output pasted above

Thanks!

**Comment by josegonzalez** [comment]
The trace output is quite a bit more verbose than that, hence why I don't think it's the correct output.

**Comment by josegonzalez** [comment]
Can you try using `$NG_ENV` instead of `${NG_ENV}`? The `${VARIABLE}` syntax is used for environment variables, and if you don't have one set, I think docker will just make it a literal value.

**Comment by templth** [comment]
@josegonzalez I tried both but they are empty...

**Comment by josegonzalez** [comment]
Do you have a sample app I can test out?

**Comment by templth** [comment]
@josegonzalez thanks very much for your help! I pushed a minimal sample app here: https://github.com/templth/dokku-angular2. Feel free to tell if it's enough to test out...

**Comment by josegonzalez** [comment]
Note: that app fails to start on latest dokku.

EDIT: the dockerfile contents were commented out...

**Comment by josegonzalez** [comment]
Heh now it just fails because of nodejs.

Given that I'm unable to duplicate this and there isn't any trace output, I'm going to close this issue. If someone is able to give me a simple way to replicate this issue on the latest version - maybe something that doesn't require nodejs since its basically impossible to install a node app after a month of the code stagnating because npm is a goddamn tirefire - I'll try and take a look much quicker.

Apologies for being slow on the draw here.
