### ISSUE TITLE
Running a dokku inside of LXD container.

### ISSUE THREAD

**Issue by hivearts** [dokku/dokku#2779]
Hello,

I am using Ubuntu 16.04 and LXD container on it.
I can install docker from docker.io package and it is working, but when i try to bootstrap dokku it fails.

Does somebody running successfully dokku inside of LXD container?

**Comment by rvalyi** [comment]
Hello. I have really no clue about this issue, but may be it is related to https://github.com/dokku/dokku/issues/2775 as per what the author describes.

**Comment by josegonzalez** [comment]
Yep, duplicate of that issue. Closing.
