### ISSUE TITLE
How to add a 3rd party module to nginx within dokku?

### ISSUE THREAD

**Issue by Hamada92** [dokku/dokku#2780]
Hey guys, 

Thanks for all the hardwork. Is there a dokku way to add a 3rd party module to nginx? Or do I have to uninstall and install it again? 

Thanks

**Comment by fruitl00p** [comment]
@Hamada92 are you using it globally or in a specific application?

If you want it globally you could add the config to a `.conf`-file in `/etc/nginx/conf.d/`
- OR -
if you want to have a specific addition to your app' ngnix config, you could a `.conf`-file to `/home/dokku/{YOUR_APP}/nginx.conf.d/`

Would that solve your issue?
(see also http://dokku.viewdocs.io/dokku/configuration/nginx/#customizing-via-configuration-files-included-by-the-default-tem)

**Comment by josegonzalez** [comment]
If you want a 3rd party module on the host nginx, you'll need to recompile nginx. For a 3rd party module inside of a container (such as for the php buildpack) you'll need to fork the buildpack and modify it as necessary.

Closing as this is outside of the scope of dokku to manage for users.
