### ISSUE TITLE
Outdated documentation für nginx.conf.sigil files?

### ISSUE THREAD

**Issue by krautnerds** [dokku/dokku#2782]
Description of problem:
I just wanted to create a custom nginx.conf.sigil file in my dokku buildpack application but found an incorrect template file in 

https://github.com/dokku/dokku/blob/master/docs/configuration/nginx.md

As suggested by the documentation i should use the examples that are included in the documentation. But in my case I already support http2 so for example the following lines should be updated to reflect the current standards:

` listen      [::]:443 ssl spdy;
  listen      443 ssl spdy;`

to

` listen      [::]:443 ssl http2;
  listen      443 ssl http2;`

Maybe the templates should be updated in general to meet current standards?

**Comment by josegonzalez** [comment]
Mind making a PR to reflect the changes?
