### ISSUE TITLE
Wrong appurl on ec2 instance

### ISSUE THREAD

**Issue by ethicalvats** [dokku/dokku#2783]
Description of problem:
I am getting wrong appurl for the ruby on rails app deployed on amazon ec2 instance

Output of the following commands

$ dokku version
0.9.4

$ sudo docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

How reproducible:
I am not sure if the bug can be reproduced on other machines or not but I just launched a new t2.mico AWS instance today and installed dokku using bash script.

Steps to Reproduce:
1. Launch EC2 instance 
2. install dokku
3. create app
4. deploy

Actual Results:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "en_IN",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Counting objects: 29505, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8551/8551), done.
Writing objects: 100% (29505/29505), 294.22 MiB | 868.00 KiB/s, done.
Total 29505 (delta 20187), reused 29437 (delta 20122)
-----> Cleaning up...
-----> Building flexiple from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.2
-----> Installing dependencies using bundler 1.13.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from http://rubygems.org/..........
       Fetching version metadata from http://rubygems.org/..
       Fetching dependency metadata from http://rubygems.org/.
       Installing multipart-post 1.2.0
       Installing unf_ext 0.0.7.2 with native extensions
       Installing rake 11.1.2
       Installing netrc 0.11.0
       Installing mime-types 2.99.2
       Installing i18n 0.7.0
       Installing json 1.8.6 with native extensions
       Installing minitest 5.9.1
       Installing thread_safe 0.3.5
       Installing builder 3.2.2
       Installing erubis 2.7.0
       Installing mini_portile2 2.1.0
       Installing rack 1.6.4
       Installing arel 6.0.3
       Installing htmlentities 4.3.4
       Installing rubyzip 1.0.0
       Installing thor 0.19.1
       Installing concurrent-ruby 1.0.2
       Installing tilt 2.0.5
       Installing angularjs-file-upload-rails 2.2.0
       Installing babel-source 5.8.35
       Installing execjs 2.7.0
       Installing bcrypt 3.1.11 with native extensions
       Installing bower-rails 0.10.0
       Installing chronic 0.10.2
       Installing coffee-script-source 1.10.0
       Installing orm_adapter 0.5.0
       Installing hashie 3.4.6
       Installing multi_json 1.12.1
       Installing jwt 1.5.1
       Using bundler 1.13.7
       Installing mini_magick 4.5.1
       Installing multi_xml 0.5.5
       Installing mysql 2.9.1 with native extensions
       Installing mysql2 0.4.4 with native extensions
       Installing puma 3.8.2 with native extensions
       Installing rails_serve_static_assets 0.0.5
       Installing rails_stdout_logging 0.0.5
       Installing sass 3.4.22
       Installing turbolinks-source 5.0.0
       Installing faraday 0.8.8
       Installing mail 2.6.4
       Installing tzinfo 1.2.2
       Installing nokogiri 1.6.8.1 with native extensions
       Installing rack-test 0.6.3
       Installing warden 1.2.6
       Installing passenger 5.0.30 with native extensions
       Installing sprockets 3.7.0
       Installing babel-transpiler 0.7.0
       Installing uglifier 3.0.2
       Installing unf 0.1.4
       Installing whenever 0.9.4
       Installing coffee-script 2.4.1
       Installing omniauth 1.3.1
       Installing rdoc 4.2.2
       Installing rails_12factor 0.0.3
       Installing turbolinks 5.0.1
       Installing oauth2 1.1.0
       Installing activesupport 4.2.5
       Installing tzinfo-data 1.2016.4
       Installing sprockets-es6 0.9.2
       Installing domain_name 0.5.20160615
       Installing sdoc 0.4.2
       Installing omniauth-oauth2 1.4.0
       Installing rails-deprecated_sanitizer 1.0.3
       Installing globalid 0.3.7
       Installing activemodel 4.2.5
       Installing jbuilder 2.6.0
       Installing http-cookie 1.0.2
       Installing omniauth-facebook 4.0.0
       Installing omniauth-google-oauth2 0.4.0
       Installing activejob 4.2.5
       Installing activerecord 4.2.5
       Installing carrierwave 0.10.0
       Installing rest-client 1.8.0
       Installing foreigner 1.7.4
       Installing Instamojo-rb 1.1.0
       Installing rails-dom-testing 1.0.7
       Installing loofah 2.0.3
       Installing rails-html-sanitizer 1.0.3
       Installing axlsx 2.0.1
       Installing actionview 4.2.5
       Installing actionpack 4.2.5
       Installing actionmailer 4.2.5
       Installing railties 4.2.5
       Installing acts_as_xlsx 1.0.6
       Installing sprockets-rails 3.2.0
       Installing coffee-rails 4.1.1
       Installing responders 2.3.0
       Installing angular-rails-templates 1.0.0
       Installing font-awesome-rails 4.7.0.1
       Installing rails 4.2.5
       Installing jquery-rails 4.2.1
       Installing sass-rails 5.0.6
       Installing devise 4.2.0
       Installing mailboxer 0.13.0
       Installing ngannotate-rails 1.2.2
       Installing simple_token_authentication 1.15.1
       Bundle complete! 55 Gemfile dependencies, 98 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from rdoc:
       Depending on your version of ruby, you may need to install ruby rdoc/ri data:
       <= 1.8.6 : unsupported
       = 1.8.7 : gem install rdoc-data; rdoc-data --install
       = 1.9.1 : gem install rdoc-data; rdoc-data --install
       >= 1.9.2 : nothing to do! Yay!
       Bundle completed (36.64s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
-----> Installing node-v6.10.0-linux-x64
       Detected manifest file, assuming assets were compiled locally
       
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing flexiple (dokku/flexiple:latest)...
-----> Deploying flexiple (dokku/flexiple:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> App Procfile file found (/home/dokku/flexiple/DOKKU_PROCFILE)
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
=====> renaming container (0a14bf64f250) gallant_volhard to flexiple.web.1
=====> no global VHOST set. disabling vhost support
-----> Unsetting flexiple
-----> Unsetting DOKKU_NGINX_PORT
-----> Unsetting DOKKU_NGINX_SSL_PORT
-----> Unsetting DOKKU_PROXY_PORT_MAP
-----> Setting config vars
       NO_VHOST: 1
-----> no nginx port set. setting to random open high port
-----> Setting config vars
       DOKKU_NGINX_PORT: 2192
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP: http:2192:5000
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
-----> Running 'bundle exec rake db:migrate' in app container
       restoring installation cache...
         ActiveRecord::SchemaMigration Load (0.6ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
       removing installation cache...
=====> Application deployed:
       http://ip-172-31-55-159.ec2.internal:2192

Expected Results:
http://54.174.104.213:2192

Additional info:
Onething to note though I had not went through the dokku web interface for adding ssh key just added it using the acl-add commad

**Comment by josegonzalez** [comment]
If you don't use the web interface to fill out the hostname, we use the hostname from the server itself.

In this case, your hostname is that `ip-172-31-55-159.ec2.internal`, which you can verify via the `hostname` command on the box.

**Comment by josegonzalez** [comment]
You can modify that vhost by using the domains plugin as specified here: http://dokku.viewdocs.io/dokku/configuration/domains/
