### ISSUE TITLE
Dokku cleanup doesn't work after a server reboot

### ISSUE THREAD

**Issue by chiedo** [dokku/dokku#2786]
After a server reboot, `dokku cleanup` doesn't work. I think it's due to instances dokku created that it no longer "knows about?" in relation to https://github.com/dokku/dokku/issues/2403

Not sure if I should create this issue or post in the other one. :)

**Comment by josegonzalez** [comment]
@chiedo not sure if you know how to replicate this now, but if you can do so, can you gist the output of `docker inspect` on those orphaned containers?

**Comment by chiedo** [comment]
No worries @josegonzalez!

DMed you in Slack. It doesn't work before or after server reboot.

**Comment by josegonzalez** [comment]
The `inspect` output contains a `restarting` container. Not sure we can do much with that, other than output a warning to logs during a `ps:restore`.

**Comment by chiedo** [comment]
Hmmm @josegonzalez is there any performance hit or issues with scaling that could result from those building up? As you saw, I had like 12 of them on an app that hasn't been running that long. 

Is there a reason we can't add some lines to the `dokku cleanup` script that finds containers with "restarting" status and removes them? If you're OK with that, I'll try and find where to add it and submit a PR

**Comment by josegonzalez** [comment]
No idea, though I'm not sure how safe that is. Is that the status you get from docker restart policies? If so, a cleanup during the middle of a restart might be bad...

**Comment by chiedo** [comment]
I get that status when I run `sudo docker ps`. And it always says X days ago so I could only cleanup containers that say 1 day ago or more. No reason a container should be restarting for over a day .

The status output is usually `Restarting (0) 2 days ago` so it would be easy to parse.

**Comment by josegonzalez** [comment]
Go for it.

**Comment by chiedo** [comment]
Perfect. Stay posted.

**Comment by chiedo** [comment]
Hey @josegonzalez,

I'm also thinking about addressing this issue that I keep running into 

```
CONTAINER ID        IMAGE                COMMAND             CREATED              STATUS              PORTS               NAMES
4e0aea349ef3        dokku/lplaw:latest   "/start web"        About a minute ago   Up About a minute                       x.web.1
8018970cef1d        58d66e6a9f8f         "/start web"        28 minutes ago       Up 2 minutes                            x.web.1.1501068011
```
dokku cleanup seems to miss anything that was a result of an error (system reboot, application crash, etc.)

For situations like this, I could also remove any containers that contain start with *.web.x but don't have latest in the image and were created over 30 minutes ago. The combination of those things seems to be a reasonable sign that dokku has 'lost track of' a container.

Thoughts?

**Comment by joshmanders** [comment]
Starting with `.web` might not be the best route, if you have worker containers those will be left behind too, as `.web` is just the name of the procfile command.

**Comment by josegonzalez** [comment]
We should kill any containers that follow the naming pattern `app.proc_type.index.SOME_NUMBER` on reboot.

**Comment by josegonzalez** [comment]
@chiedo what is the inspect output on that random extra container?

**Comment by chiedo** [comment]
Awesome, I'll plan to create any containers with the following naming pattern when dokku cleanup is run, (which I'm assuming runs at reboot?) `app.proc_type.index.SOME_NUMBER`

I've officially launched the web app I was using for that and I've manually cleared all the rogue containers with sudo docker stop and rm but I'll try and reproduce on a staging server which will probably be pretty easy to do. Rebooting a server seems to leave remnants every time.

**Comment by josegonzalez** [comment]
Don't remember if we run that on ps:restore, but if not, it can be the last thing that runs after the restore finishes?

**Comment by chiedo** [comment]
Cool

**Comment by digitalhurricane-io** [comment]
I believe I had this issue too. I installed docker around 4 days ago and have rebooted several times. I noticed I had around 15 extra running containers. Stopped and removed them all.

**Comment by josegonzalez** [comment]
This was taken care of in https://github.com/dokku/dokku/pull/3109/commits/78503ed17855643507f66f3c596b191c06e0558e and should be out in the next release (0.12.0).
