### ISSUE TITLE
Push to dokku in local VM throws connection timeout

### ISSUE THREAD

**Issue by jlares** [dokku/dokku#2787]
## Description of the problem:
**Background info:**
- I have successfully installed and pushed to a remote Dokku in Digital Ocean.
- I have installed Dokku in my Virtual Box Ubuntu 16.04 VM (3 times, in completely fresh VMs; same error).

**The problem:**
I want to push to localhost dokku, so I run:
`git remote add dev dokku@dokku.me:appName` (have also tried with the localhost ip)
and then 
`git push dev master`

but the terminal does not return anything for a while, and then outputs:
`ssh: connect to host dokku.me port 22: Connection timed out`
I also attempted to add remote using the ip address, same output.

Environment details (AWS, VirtualBox, physical, etc.):

How was Dokku installed?:

via command:
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.9.4/bootstrap.sh;
sudo DOKKU_TAG=v0.9.4 bash bootstrap.sh
```

How reproducible:

Steps to Reproduce:
1. Download linux desktop 16.04 and create a new VM with virtual disk using VirtualBox
2. Install Dokku,  setup with VM ipv4, use same pk for everything in that machine
3. try to push to localhost dokku

Actual Results:

ssh connection timeout problem.

Expected Results:

a succesfull push just like the one that occurs when i push to the digital ocean dokku

Additional info:

**Comment by josegonzalez** [comment]
Did you set an entry in your `.ssh/config` for the vm?

**Comment by jlares** [comment]
if you mean in directory '/etc/ssh/ssh_config' I did configured it to use the same pk

If you mean in my user dir, same pk is found in directory '.ssh/authorized_keys'

if you mean in my dokku user's .ssh folder, the same key can be found

**Comment by josegonzalez** [comment]
I mean your local ssh, outside of the vm.

**Comment by jlares** [comment]
I have not done anything outside of the VM. 

I am using a windows 10 computer running this VirtualBox VM. 

The only thing i know networking-wise here is that the network adapter is attached to NAT (don't know if that helps at all).

**Comment by josegonzalez** [comment]
Please use our [windows VM](http://dokku.viewdocs.io/dokku/getting-started/install/vagrant/) for setting up dokku with vagrant. We don't support any other configuration for local development.

**Comment by jlares** [comment]
Thank you @josegonzalez
