### ISSUE TITLE
Variable expansion when using Procfiles and Dockerfile together.

### ISSUE THREAD

**Issue by pardo-bsso** [dokku/dokku#2793]
# Description of problem:

When deploying an application that has both a Procfile and Dockerfile we found that environment variables
in the Procfile are not expanded when running the commands inside it.

A sample repo to reproduce this is available at: https://github.com/Cambalab/dokku-procfile-dockerfile

# Output of dokku report:

  -----> uname: Linux dokku1 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
  -----> memory: 
               total       used       free     shared    buffers     cached
  Mem:          2001       1642        359          2        316        611
  -/+ buffers/cache:        714       1287
  Swap:          999        276        723
  -----> docker version: 
  Client:
   Version:      17.05.0-ce
   API version:  1.29
   Go version:   go1.7.5
   Git commit:   89658be
   Built:        Thu May  4 22:06:06 2017
   OS/Arch:      linux/amd64
  
  Server:
   Version:      17.05.0-ce
   API version:  1.29 (minimum version 1.12)
   Go version:   go1.7.5
   Git commit:   89658be
   Built:        Thu May  4 22:06:06 2017
   OS/Arch:      linux/amd64
   Experimental: false
  -----> docker daemon info: 
  Containers: 13
   Running: 4
   Paused: 0
   Stopped: 9
  Images: 100
  Server Version: 17.05.0-ce
  Storage Driver: aufs
   Root Dir: /var/lib/docker/aufs
   Backing Filesystem: extfs
   Dirs: 261
   Dirperm1 Supported: false
  Logging Driver: json-file
  Cgroup Driver: cgroupfs
  Plugins: 
   Volume: local
   Network: bridge host macvlan null overlay
  Swarm: inactive
  Runtimes: runc
  Default Runtime: runc
  Init Binary: docker-init
  containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
  runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
  init version: 949e6fa
  Security Options:
   apparmor
  Kernel Version: 3.13.0-77-generic
  Operating System: Ubuntu 14.04.4 LTS
  OSType: linux
  Architecture: x86_64
  CPUs: 2
  Total Memory: 1.955GiB
  Name: dokku1
  ID: NM4Z:O2Q5:N4LS:JGHS:5UTC:MARE:IEKA:ZINK:XQ2Z:5JNT:VEGR:4VE7
  Docker Root Dir: /var/lib/docker
  Debug Mode (client): true
  Debug Mode (server): false
  Registry: https://index.docker.io/v1/
  Experimental: false
  Insecure Registries:
   127.0.0.0/8
  Live Restore Enabled: false
  
  WARNING: No swap limit support
  -----> sigil version: 0.4.0
  -----> herokuish version: 
  herokuish: 0.3.29
  buildpacks:
    heroku-buildpack-multi     v1.0.0
    heroku-buildpack-ruby      v159
    heroku-buildpack-nodejs    v99
    heroku-buildpack-clojure   v76
    heroku-buildpack-python    v99
    heroku-buildpack-java      v51
    heroku-buildpack-gradle    v21
    heroku-buildpack-grails    v21
    heroku-buildpack-scala     v76
    heroku-buildpack-play      v26
    heroku-buildpack-php       v121
    heroku-buildpack-go        v64
    heroku-buildpack-erlang    fa17af9
    buildpack-nginx            v8
  -----> dokku version: 0.9.4
  -----> dokku plugins: 
   !     Deprecated: Please use plugin:list
  plugn: 0.3.0
    00_dokku-standard    0.9.4 enabled    dokku core standard plugin
    20_events            0.9.4 enabled    dokku core events logging plugin
    apps                 0.9.4 enabled    dokku core apps plugin
    apt                  0.4.0 enabled    Inject deb packages into dokku based on files in project
    apt-old              0.4.0 disabled   Inject deb packages into dokku based on files in project
    build-env            0.9.4 enabled    dokku core build-env plugin
    certs                0.9.4 enabled    dokku core certificate management plugin
    checks               0.9.4 enabled    dokku core checks plugin
    common               0.9.4 enabled    dokku core common plugin
    config               0.9.4 enabled    dokku core config plugin
    docker-options       0.9.4 enabled    dokku core docker-options plugin
    domains              0.9.4 enabled    dokku core domains plugin
    enter                0.9.4 enabled    dokku core enter plugin
    git                  0.9.4 enabled    dokku core git plugin
    letsencrypt          0.7.4 enabled    Automated installation of let's encrypt TLS certificates
    logs                 0.9.4 enabled    dokku core logs plugin
    mariadb              1.0.0 enabled    dokku mariadb service plugin
    mongo                1.0.0 enabled    dokku mongo service plugin
    named-containers     0.9.4 enabled    dokku core named containers plugin
    nginx-vhosts         0.9.4 enabled    dokku core nginx-vhosts plugin
    plugin               0.9.4 enabled    dokku core plugin plugin
    postgres             1.0.0 enabled    dokku postgres service plugin
    proxy                0.9.4 enabled    dokku core proxy plugin
    ps                   0.9.4 enabled    dokku core ps plugin
    redis                1.0.0 enabled    dokku redis service plugin
    repo                 0.9.4 enabled    dokku core repo plugin
    shell                0.9.4 enabled    dokku core shell plugin
    sphinx               1.0.0 enabled    dokku sphinx service plugin
    ssh-keys             0.9.4 enabled    dokku core ssh-keys plugin
    storage              0.9.4 enabled    dokku core storage plugin
    tags                 0.9.4 enabled    dokku core tags plugin
    tar                  0.9.4 enabled    dokku core tar plugin

# How was Dokku installed?:

Debian package from https://packagecloud.io/dokku/dokku/ubuntu/ (trusty main)

# How reproducible:

Always.

# Steps to Reproduce:

Clone the repo https://github.com/Cambalab/dokku-procfile-dockerfile
Deploy master and no-dockerfile to different applications.

# Actual Results:

Output of dokku logs dockerfile-test -t is:

  2017-05-31T17:19:17.386619579Z app[web.1]: Express server listening on port 9000
  2017-05-31T17:19:17.389624417Z app[web.1]: Args /usr/local/bin/node,/opt/app/app.js,$PORT

Output of dokku logs dockerfile-test-no-dockerfile -t is:

2017-05-31T17:25:15.202521711Z app[web.1]: Express server listening on port 5000
2017-05-31T17:25:15.204257292Z app[web.1]: Args /app/.heroku/node/bin/node,/app/app.js,5000

# Expected Results:

Both applications expand the $PORT variable when running Procfile commands.

# Additional info:

This behaviour was found trying to deploy Sharetribe to dokku.

**Comment by josegonzalez** [comment]
I made this [go-procfile-util](https://github.com/josegonzalez/go-procfile-util) repo that should allow us to expand env vars properly for dockerfile applications.

**Comment by josegonzalez** [comment]
Closing in favor of #3196.

**Comment by yskarpathiotis** [comment]
Is there an updated official way to use ENV vars in a Procfile thats being deployed with a Dockerfile? In all my tests the ENV variables used in Procfile commands end up just being blank. Sorry if I am missing something obvious.

**Comment by josegonzalez** [comment]
@yskarpathiotis please file a ticket for any new issue (its hard for me to keep track of comments on closed tickets).
