### ISSUE TITLE
SSH agent forwarding?

### ISSUE THREAD

**Issue by phuongnd08** [dokku/dokku#2800]
Any plan to allow private repo gem to be built with dokku? This would requires dokku forward ssh agent to the docker.

**Comment by rvalyi** [comment]
I think this popular Dokku plugin is for what you want https://github.com/cedricziel/dokku-deployment-keys
Can please you confirm and close the issue if so?

**Comment by fruitl00p** [comment]
@phuongnd08 from experience the aforementioned plugin works like a charm for private NPM and Composer packages so I'd expect this to work for Gems aswell!

**Comment by phuongnd08** [comment]
Thank you. I tried the plugin and it works great.
