### ISSUE TITLE
Hosting your own private buildpacks

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [dokku/dokku#2801]
Is it possible to host your own buildpacks privately . I have tried to host the buildpacks on my own installation on gitlab and found that for some reason it is not able to download the buildpacks.

**Comment by josegonzalez** [comment]
You can specify a custom buildpack using [these instructions](http://dokku.viewdocs.io/dokku/deployment/methods/buildpacks/#specifying-a-custom-buildpack). You may need to set the repositories as public or include some token in the url to allow access.

**Comment by Utkarsh-vishnoi** [comment]
I have made the repositories as public. Also i have logged in as dokku user and manually tried to clone the repository it works but while deploying an application it just says downloading buildpack and git pre receive hook declined. Also after turning on the dokku trace. There wasn't anything that could have helped me. I will post the dokku trace output soon as i am writing from mobile curremtly.
