### ISSUE TITLE
Documentation on hosting your own buildpacks if it is possible.

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [dokku/dokku#2804]
How are buildpacks downloaded by dokku? Is it possible to host your own private buildpacks. There is nothing related to this on the internet. Can you point me to an article or write on your own. 

Regards,
Utkarsh Vishnoi

**Comment by Utkarsh-vishnoi** [comment]
What exactly happens under the hood when dokku is downloading a buildpack.
Need more information...

**Comment by joshmanders** [comment]
dokku uses https://github.com/gliderlabs/herokuish

**Comment by josegonzalez** [comment]
Closing. We do exactly the same as Heroku does, and all the same documentation for them applies here.
