### ISSUE TITLE
Dokku Rewrite?

### ISSUE THREAD

**Issue by iSDP** [dokku/dokku#2806]
Hello!

I'm looking at the code base and noticing most glue stuff is written in Bash.  
This leaves me wondering, isn't it better to use something like Go?

Go is fast, it lies close to C when compiled, very easy to learn, and easy to extend.

That would lift quite some restrictions and allows Dokku to grow even more as a PaaS platform.

I'm willing to dedicate my time to rewriting Dokku in cooperation with the current maintainers.

I hope this at least sparks a discussion about the future of Dokku! 😄

**Comment by josegonzalez** [comment]
We're actually in the process of rewriting in Golang. All new core plugins are *required* to be in golang - though you can continue using existing plugins written in any language. We're also slowly rewriting existing plugins.

An example is the `repo` plugin, as well as the PRs for Config and Network plugins.

Closing as I think we have a direction going forward here (though maybe not well publicized).
