### ISSUE TITLE
any plan for heroku-16

### ISSUE THREAD

**Issue by pynixwang** [dokku/dokku#2812]
`heroku-16` is available for 2 months.

[https://blog.heroku.com/heroku-16-is-generally-available](https://blog.heroku.com/heroku-16-is-generally-available)

**Comment by josegonzalez** [comment]
That's part of a separate project, [herokuish](https://github.com/gliderlabs/herokuish/). If you would like to make a pull request to that project with support for heroku-16, that would be great. Otherwise, the answer is "it will be done when someone has time".
