### ISSUE TITLE
Option to globally disable proxy and forwarding ports externally

### ISSUE THREAD

**Issue by OmgImAlexis** [dokku/dokku#2813]
I'd like to use a caddy docker container to handle routing to my container instead of nginx so I've disabled the proxy feature on all of my apps using `dokku proxy:disable <app_name>`.

I'd like to have an option to globally disable proxying instead of needing to disable it on each app with that it'd be great to also be able to disable auto-forwarding of port 5000 to some random external port so my caddy container can handle it all.

**Comment by josegonzalez** [comment]
Basically you want the changes that are going to be introduced [here](https://github.com/dokku/dokku/pull/2736).

The only feature that won't be built is globally disabling the proxy. I'm not sure how I feel about that change, as I waffle between adding global config and not adding it.

If you could disable the proxy, then the functionality would be:

```
# to check if proxy is enabled
- check global
  - if disabled, return false
  - if enabled, check app
    - if disabled, return false
    - if enabled, return true
```

Would you be willing to build this (with tests)? If so, this can stay open. If not, I'm not volunteering to build it so will close the issue.

**Comment by OmgImAlexis** [comment]
I'm fine with trying to add it.

Shall I wait for https://github.com/dokku/dokku/pull/2736 to be merged first?

**Comment by josegonzalez** [comment]
Nope, you can go for it. Will be a bit before I can revisit that pull request...

**Comment by OmgImAlexis** [comment]
Where is dokku located after it's installed?

**Comment by josegonzalez** [comment]
Other than the `~dokku` directory, everything follows normal linux conventions, so `/var/lib/dokku`

**Comment by OmgImAlexis** [comment]
Closing this as it seems like it'd be better to go with the proxy plugin route so I'm working on making a plugin for caddy.
