### ISSUE TITLE
Check for netcat while installing

### ISSUE THREAD

**Issue by OmgImAlexis** [dokku/dokku#2818]
I'm using a OpenVZ VPS from SSDNodes and by default they don't have netcat installed meaning any scripts using `nc` will get `nc: command not found`.

**Comment by joshmanders** [comment]
Dokku should be installing all it's dependencies... Is there somewhere in Dokku where netcat is being used expecting it installed?

**Comment by josegonzalez** [comment]
Is that a debian-based installation? It seems we only install it by default in rpm systems.

@joshmanders its used for getting a random port to start the service on.

**Comment by OmgImAlexis** [comment]
It's Ubuntu 16.04. If you need anymore info just let me know.

**Comment by joshmanders** [comment]
@josegonzalez ah, that makes sense.

@OmgImAlexis do they use a custom build or something? I've been building machines from both 14.04 and 16.04 for the last couple days and haven't had issues.

**Comment by OmgImAlexis** [comment]
Yeah they tried to strip the install down as much as possible. The kernel is also custom which is why I'm using dokku as it's the only thing I found that doesn't rely on the overlay kernel module.

I think the only other thing I installed so far is curl and nano.

**Comment by joshmanders** [comment]
ah, I see...

**Comment by josegonzalez** [comment]
@OmgImAlexis do we want `netcat-openbsd` or some other package?

**Comment by OmgImAlexis** [comment]
Since it's only used to check the port I think either `netcat` or `netcat-openbsd` should be fine.

[Difference between them](https://askubuntu.com/questions/346869/what-are-the-differences-between-netcat-traditional-and-netcat-openbsd).
