### ISSUE TITLE
Add docs for switching from Dockerfile -> Buildpack

### ISSUE THREAD

**Issue by OmgImAlexis** [dokku/dokku#2819]
As per Slack switching over requires all of these config values to be unset.
```
DOKKU_DOCKERFILE_CMD DOKKU_DOCKERFILE_ENTRYPOINT DOKKU_PROXY_PORT_MAP
```

This is just a note for myself so I remember to do then later today.

**Comment by aashutoshrathi** [comment]
Can I work on this ?

**Comment by OmgImAlexis** [comment]
Yeah that's fine.

You also need to reset the proxy settings so nginx works again.
