### ISSUE TITLE
Bad Gateway errors on all apps other than the heroku sample app

### ISSUE THREAD

**Issue by Mmarzex** [dokku/dokku#282]
Hi,

I have a simple node app that is just a bunch of get requests to a database basically but dokku deploys it but does not start a docker container and the proxying doesn't working giving me a Bad Gateway error when I try to load it. My question or rather concern is, is there a certain way that projects have to adhere to in order for dokku to work?

**Comment by sebastiaandegeus** [comment]
@ Mmarzex  in which file did you add this port line?

**Comment by sebastiaandegeus** [comment]
@Mmarzex  in which file did you add this port line?

**Comment by scientist1642** [comment]
Hmm, I'm also trying to deploy a rails app with the same issue (Gateway error) and I get no errors at all.. 
docker logs - 
    I, [2015-02-18T22:09:04.510541 #16]  INFO -- : listening on addr=0.0.0.0:5000 fd=9
    I, [2015-02-18T22:09:04.812871 #16]  INFO -- : master process ready
    I, [2015-02-18T22:09:04.815086 #19]  INFO -- : worker=0 ready
    I, [2015-02-18T22:09:04.829571 #22]  INFO -- : worker=1 ready
    I, [2015-02-18T22:09:04.831589 #24]  INFO -- : worker=2 ready
test nodejs app is working fine.
