### ISSUE TITLE
Web installer - opt-out?

### ISSUE THREAD

**Issue by h4ckninja** [dokku/dokku#2830]
**Description of problem:**

I wrote an [Ansible](https://docs.ansible.com/ansible/index.html) role to remotely install and manage my Dokku installation. I type in my playbook location and let it run. However, this currently leaves the web interface wide open, as noted in http://dokku.viewdocs.io/dokku/getting-started/installation/#2-setup-ssh-key-and-virtualhost-settings. The relevant section from my role tries to set the key:

~~~
- name: "Upload dokku public key"
  copy:
    src: '/Users/[me]/.ssh/keys/dokku.pub'
    dest: '/home/{{ primary_user|lower }}/dokku.pub'
    owner: "{{ primary_user|lower }}"
    group: "{{ primary_user|lower }}"
    mode: 0644

- name: "Set debconf selections"
  command: 'echo "dokku dokku/{{ item.option }} {{ item.value }}" | debconf-set-selections'
  with_items:
    - { option: 'web_config', value: 'boolean false' }
    - { option: 'vhost_enable', value: 'boolean true' }
    - { option: 'hostname', value: 'string {{ global_hostname }}' }
    - { option: 'skip_key_file', value: 'boolean false' }
    - { option: 'key_file', value: '/home/{{ primary_user|lower }}/dokku.pub' }

- name: "Dokku Install"
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - docker-ce
    - dokku

- name: "Dokku Dependencies: Core"
  command: dokku plugin:install-dependencies --core

- name: "Remove dokku public key"
  file:
    path: '/home/{{ primary_user|lower }}/dokku.pub'
    state: absent
~~~

For those not familiar with Ansible, this YAML file description does the following:

- SFTP the key and set file permissions
- Execute `debconf` as described in http://dokku.viewdocs.io/dokku/getting-started/install/debian/#unattended-installation
- `apt install` docker and dokku
- Install the plugin dependencies
- And finally remove the key from the filesystem as it is no longer needed

The confusion here for me is the difference between the unattended documentation and the setup SSH key documentation. I'd like for the option to be completely unattended. I have the tools to automatically install, update, and manage my Dokku installation.

**Environment details (AWS, VirtualBox, physical, etc.):**

Linode

**How was Dokku installed?:**

Custom Ansible role.

**How reproducible:**

Execute a playbook with the above role snippet and note that the web interface is still open.

**Comment by h4ckninja** [comment]
Thanks for getting back to me so quickly. I thought I had debugged it to narrow it down, but I'll give it another look.

**Comment by josegonzalez** [comment]
@h4ckninja *bump*

**Comment by h4ckninja** [comment]
Apologies for the delay, I've been busy.

I've confirmed manually that the debconf settings are getting set, but for whatever reason, they are not taking during installation.

That said, I copied and pasted your YAML it seemed to work. Thanks again for the help.
