### ISSUE TITLE
Add DOKKU=1 env var

### ISSUE THREAD

**Issue by skorokithakis** [dokku/dokku#2837]
It would be nice if there were a persistent environment variable so we could change things programmatically if the app were running in dokku. Something like a constant `IN_DOKKU=1` would work well.

**Comment by josegonzalez** [comment]
You can get that by checking if `DYNO` is set.

**Comment by skorokithakis** [comment]
That env var doesn't seem to be set for the `run` command:

```
In [3]: os.environ.get("DYNO")

In [4]: 
```

**Comment by josegonzalez** [comment]
Good catch. Looks like we'll need to inject that as an env var for `run`:

```
$ heroku run bash
Running bash on ⬢ haldane... up, run.3870 (Standard-1X)
~ $ env | grep DYNO
DYNO=run.3870
DYNO_RAM=512
```

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
