### ISSUE TITLE
Disk space usage

### ISSUE THREAD

**Issue by alexjamesbrown** [dokku/dokku#2838]
Not sure if this is dokku specific, but it seems to be using disk space like it is going out of fashion:

running
>df -h

I get:

![image](https://user-images.githubusercontent.com/437743/28242134-f65af0ca-699b-11e7-995e-a8ecc79971a3.png)

/var/lib/docker/aufs/mnt/ seems to be filling up...?

Any ideas why?

**Comment by josegonzalez** [comment]
You are probably logging into a file in the container in your applications. This is really just an application-specific issue, as our container images (when built) are about 1-2GB in size.

**Comment by alexjamesbrown** [comment]
Sorry, yeah - i just noticed the path is /var/lib/**docker** (i read that as dokku last night)

Any idea how I could find out what / where it's logging?

**Comment by josegonzalez** [comment]
Depends on your application. I would `ps:rebuild` each one, one at a time, and see which rebuild drops disk space usage. That will give you a hint as to which application is behaving poorly.
