### ISSUE TITLE
CloudFlare + Let's Encrypt + Dokku

### ISSUE THREAD

**Issue by RichardB122** [dokku/dokku#2841]
Hi, I have two websites running on my vps with Dokku. Both domains are routed through Cloudflare to the ip of my vps running Dokku. I want to keep the caching and analytics benefits of Cloudflare and I would like to stay on the free plan. Unfortunately I have been having some issues. 

Both Chrome and Chromium return this error when I attempt to access my site "ERR_SPDY_PROTOCOL_ERROR". However, Firefox works fine, I think it may be an issue between using SPDY and HTTP/2 vs HTTP1.

I talked to some people and did some research and I was suggested to setup Let's Encrypt. So I setup the Let's Encrypt plugin and after some trouble finally managed to get it to work. I then switched Cloudflare to "Full (Strict)" SSL and everything worked in Firefox, but I continued to experience the same error in Chrome and Chromium.

The two domains are:
https://www.minecraftmedia.net
https://www.thesimsmedia.com

Thank you and let me know if you all need any additional information.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

Also, can you include the output of the following?

`nginx -V`

**Comment by RichardB122** [comment]
uname -a:
> Linux localhost 4.9.15-x86_64-linode81 #1 SMP Fri Mar 17 09:47:36 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

free -m
> total        used        free      shared  buff/cache   available
Mem:            988         348         117          70         522         492
Swap:           255         145         110

docker version
> Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@localhost:~# docker -D info
Containers: 11
 Running: 4
 Paused: 0
 Stopped: 7
Images: 29
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.15-x86_64-linode81
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989MiB
Name: localhost
ID: 357V:6ZTF:NIHZ:ABOU:L6FO:MOBS:EJLU:3LI7:BB5O:P55I:SNVI:YVJA
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

docker -D info
> Containers: 11
 Running: 4
 Paused: 0
 Stopped: 7
Images: 29
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.15-x86_64-linode81
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989MiB
Name: localhost
ID: 357V:6ZTF:NIHZ:ABOU:L6FO:MOBS:EJLU:3LI7:BB5O:P55I:SNVI:YVJA
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
WARNING: No swap limit support

sigil -v
> 0.4.0

docker run -ti gliderlabs/herokuish:latest herokuish version
> herokuish: 0.3.31
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v163
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v109
  heroku-buildpack-java      v52
  heroku-buildpack-gradle    v22
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v121
  heroku-buildpack-go        v69
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8

dokku version
> 0.10.3

dokku plugin
>  !     Deprecated: Please use plugin:list
plugn: 0.3.0
  00_dokku-standard    0.10.3 enabled    dokku core standard plugin
  20_events            0.10.3 enabled    dokku core events logging plugin
  apps                 0.10.3 enabled    dokku core apps plugin
  build-env            0.10.3 enabled    dokku core build-env plugin
  certs                0.10.3 enabled    dokku core certificate management plugin
  checks               0.10.3 enabled    dokku core checks plugin
  common               0.10.3 enabled    dokku core common plugin
  config               0.10.3 enabled    dokku core config plugin
  docker-options       0.10.3 enabled    dokku core docker-options plugin
  domains              0.10.3 enabled    dokku core domains plugin
  enter                0.10.3 enabled    dokku core enter plugin
  git                  0.10.3 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.10.3 enabled    dokku core logs plugin
  mariadb              1.0.0 enabled    dokku mariadb service plugin
  named-containers     0.10.3 enabled    dokku core named containers plugin
  nginx-vhosts         0.10.3 enabled    dokku core nginx-vhosts plugin
  plugin               0.10.3 enabled    dokku core plugin plugin
  proxy                0.10.3 enabled    dokku core proxy plugin
  ps                   0.10.3 enabled    dokku core ps plugin
  repo                 0.10.3 enabled    dokku core repo plugin
  shell                0.10.3 enabled    dokku core shell plugin
  ssh-keys             0.10.3 enabled    dokku core ssh-keys plugin
  storage              0.10.3 enabled    dokku core storage plugin
  tags                 0.10.3 enabled    dokku core tags plugin
  tar                  0.10.3 enabled    dokku core tar plugin

docker inspect c689af123f91
`[
    {
        "Id": "c689af123f91313e2f3b9aed3da0357b0959b528c6bba77b73cec4d10e16f009",
        "Created": "2017-07-31T00:52:48.460378566Z",
        "Path": "/start",
        "Args": [
            "web"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 27813,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-07-31T00:52:48.667987904Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:2f41a7c68855c6720d0db1ba7da8e99ad6ec971af7e5485a8d19d948f892c189",
        "ResolvConfPath": "/var/lib/docker/containers/c689af123f91313e2f3b9aed3da0357b0959b528c6bba77b73cec4d10e16f009/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/c689af123f91313e2f3b9aed3da0357b0959b528c6bba77b73cec4d10e16f009/hostname",
        "HostsPath": "/var/lib/docker/containers/c689af123f91313e2f3b9aed3da0357b0959b528c6bba77b73cec4d10e16f009/hosts",
        "LogPath": "/var/lib/docker/containers/c689af123f91313e2f3b9aed3da0357b0959b528c6bba77b73cec4d10e16f009/c689af123f91313e2f3b9aed3da0357b0959b528c6bba77b73cec4d10e16f009-json.log",
        "Name": "/mcmedia.web.1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 10
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": [
                "/dokku.mariadb.database:/mcmedia.web.1/dokku-mariadb-database"
            ],
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/19429ae24c82ed8b15f29833978036b423dca1969d286d21f4619d39f0102ec1-init/diff:/var/lib/docker/overlay2/46cf461a02f37a50174a54b4bb27eb44900108794044e1035b77ae1853cea94d/diff:/var/lib/docker/overlay2/35b1862982f97d12582b5f5f6eff1fc18500a00c98c9270d9cf73cf92e53be2c/diff:/var/lib/docker/overlay2/1076e17aae67774577f6b40982c77ac76b86947dc99b32d5ade86c5d3ea6934c/diff:/var/lib/docker/overlay2/0dfe82930f0920e600df79cb69bfbb0566dd5025743a412c476de371244642ee/diff:/var/lib/docker/overlay2/524155cb5d582c884eadb98e70fc8ddb98f6b5bbae9ca2fb5bf8621a80d8b10e/diff:/var/lib/docker/overlay2/3eb681afeec2f7a86f26d41a58715a9e49586e18f2d411f0ab69372e321c41a4/diff:/var/lib/docker/overlay2/1c9df9159473cf80f32ad2c423e82e25b09b5624e203e4bbdc19a2c196f57a8d/diff:/var/lib/docker/overlay2/77c3635a6314b62113c95cd724a5f2138525a1d9ea226df2d833426fe1ae753b/diff:/var/lib/docker/overlay2/2b20d40251e9e2d86fc98da82f5e03e96fc0fcc5298db442bbbca830baef9d2c/diff:/var/lib/docker/overlay2/cd773b954c08805aee4c0c7a11d08cf357e37ef375e14d93705ab218ea15cdea/diff:/var/lib/docker/overlay2/cf84122d79b2b38d454c5817af8cdbf5098523752adf2b7da93a87dc68187a78/diff:/var/lib/docker/overlay2/eca1f0804b000a6344e0e543a861f7addf913d7951137b3cf5ec7e6a8d587c21/diff:/var/lib/docker/overlay2/7781b2b29a68d36c1552161ada9a13f1be811b85068bf593a307b3bf4ddc0f7a/diff:/var/lib/docker/overlay2/c444c87865558797e2fa5f5f5a11184b1a7edd4e686a2979fdbcf4d982af5c15/diff",
                "MergedDir": "/var/lib/docker/overlay2/19429ae24c82ed8b15f29833978036b423dca1969d286d21f4619d39f0102ec1/merged",
                "UpperDir": "/var/lib/docker/overlay2/19429ae24c82ed8b15f29833978036b423dca1969d286d21f4619d39f0102ec1/diff",
                "WorkDir": "/var/lib/docker/overlay2/19429ae24c82ed8b15f29833978036b423dca1969d286d21f4619d39f0102ec1/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "c689af123f91",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PORT=5000",
                "USER=herokuishuser",
                "DYNO=web.1",
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/start",
                "web"
            ],
            "Image": "dokku/mcmedia:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "dokku": ""
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e9d353fa996151d9047f4c53a53ee74bc74a36eca3cb2ded553606133e6b5cc2",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/e9d353fa9961",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "0ca91f5627bd56c058255da7ca6ea4adb55280745b7f27bfffeb434bc9c23ed4",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2b8bf63eaa076c1321367040f0ddf30777d78cd6998a78b26da237b68d792230",
                    "EndpointID": "0ca91f5627bd56c058255da7ca6ea4adb55280745b7f27bfffeb434bc9c23ed4",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:03",
                    "DriverOpts": null
                }
            }
        }
    }
]
`

cat /home/dokku/mcmedia/nginx.conf
See gist [here](https://gist.github.com/RichardB122/9d0b8f42b517ebdbb1282e8a035f0f36).

**Repository for code:** N/A - There is no GitHub repository for my site's code

**Environment Details:** $5 Linode VPS plan

**How was Dokkku installed?** It was installed on a fresh Linode VPS using the bootstrap.sh file specified in the directions [here](http://dokku.viewdocs.io/dokku~v0.4.3/installation/).

**Steps to reproduce:**
1. Setup a Dokku PHP app using the heroku php5 buildpack on a fresh install of dokku
2. Setup Let's Encrypt with Cloudflare disabled
3. Enable Cloudflare network and CDN functions
4. Connect with Firefox (works)
5. Connect with Chrome or Chromium (does not work and gives an error about SPDY)

I am guessing that Firefox supports HTTP/2 and connections through HTTP/2 and HTTP/1.1 work fine my site, but that Chrome still uses SPDY instead of HTTP/2 and SPDY does not work to my site. I assume the solution is to change some values in the NGINX config for each app, but I don't know what to do and I might be completely incorrect.

**Comment by joshmanders** [comment]
Try removing `http2` from this https://gist.github.com/RichardB122/9d0b8f42b517ebdbb1282e8a035f0f36#file-nginx-conf-L13-L14

Restart nginx and see if it works.

**Comment by RichardB122** [comment]
@joshmanders I made the changes and restarted the nginx service, but it didn't seem to have any effect. I also tried replacing http2 with spdy and having both spdy and http2, but none of them seemed to fix it.

**Comment by axilleas** [comment]
What nginx version are you using? For HTTP/2 to work properly, you need at least 1.11.5 as suggested by [this issue](https://github.com/dokku/dokku/issues/2435). I opened a PR to clarify this in the docs https://github.com/dokku/dokku/pull/2922.

**Comment by josegonzalez** [comment]
Closing as this is a support issue that we'll need to help you with on slack, and github isn't the best medium for your needs.

If we find a resolution, we'll comment here with an update. For future commenters, please don't add a "me too" or `+1` to this issue, as thats both not helpful to the OP and annoying to maintainers. Thanks!

**Comment by Herbo4** [comment]
I ran into this myself, using Let'sEncrypt was proving difficult so I tackled cert generation from the Cloudflare end: 

In Cloudflare you need to download a cert and key under Crypto > Origin Certificates. You create a new cert, then Cloudflare will present you with the cert and key raw. You can copy these and create a couple of new files on the dokku server by pasting the contents into mysite.crt and mysite.key respectively. 

Next use 
`tar cvf mysite.tar mysite.crt mysite.key` 
to combine the two files into a tarfile. Now you can 
`dokku certs:add myapp < mysite.tar`
Your last step is to make sure the domain for your cert is linked to your app in dokku with 
`dokku domains:add myapp *.mysite.com` 
I used a * in mine so I could optionally deploy any subdomain ex: admin.mysite.com, ftp.mysite.com
