### ISSUE TITLE
Ports appear to be closed on Digital Ocean Dokku v0.9.4 

### ISSUE THREAD

**Issue by stevemacn** [dokku/dokku#2842]
### Description of problem:

Everything is deployed properly but the port appears to be closed. Curl from inside the server leads to expected results. Testing the ports from the outside shows that they are not accessible. I already had to open ports to be able to access MongoDB. 

### Output of the following commands

```
uname: Linux bloom-taxonomy 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

-----> docker version:
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.3MiB

-----> sigil version: 0.4.0
-----> herokuish version:
herokuish: 0.3.29

plugn: 0.3.0
  00_dokku-standard    0.9.4 enabled    dokku core standard plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  ...

```

Environment details (AWS, VirtualBox, physical, etc.): Digital Ocean Dokku One Click Deploy

### How was Dokku installed?: 

Digital Ocean

### How reproducible:

Easily

### Steps to Reproduce:

1. Follow instructions: http://dokku.viewdocs.io/dokku/deployment/application-deployment/
2. Nav to the URL (it times out). 
3. See if port is open: http://www.yougetsignal.com/tools/open-ports/ (it isn't)
4. Curl the url from inside the server (all the requests are working as expected and returning results)

### Additional info:

It seems like everything is working but the port is not open. Dokku usually handles this for me. I tried to use Docker to open the port but I don't think I did it correctly:

docker run -d -p 7000:40744 -t nginx

docker ps shows the port is redirecting but the port is still closed externally.

**Comment by josegonzalez** [comment]
16.04 comes with ufw enabled for all non-standard ports. Either turn off ufw or enable access to those ports with it.

**Comment by stevemacn** [comment]
I guess that is 6 hours right into the trash :( 

Thank you so much for your help! I was even starting to consider dropping Dokku altogether which would have been a real tragedy since I've used it for such a long time with so much success!! 

Is there a way that this potential pitfall can be more visible in the documentation. I imagine many other users are using Ubuntu 16+ and it could save them a ton of time.

Thank you again for all your hard work!

**Comment by josegonzalez** [comment]
Pull requests to our installation and port management docs welcome ;)
