### ISSUE TITLE
apt-get "held broken packages" error while running bootstrap.sh on Ubuntu 14.04 (in Docker)

### ISSUE THREAD

**Issue by scjody** [dokku/dokku#2845]
Description of problem:

When `bootstrap.sh` is used to install dokku, `apt-get` fails with a "held broken packages" error.

Output of the following commands

- `dokku version`: v0.10.3

Environment details (AWS, VirtualBox, physical, etc.):

I am installing dokku into a Docker image based on Ubuntu 14.04, but I believe this error will affect any Ubuntu 14.04-based system. I'll attach the Dockerfile for reference.

How reproducible: always

Steps to Reproduce:
1. `docker build .` with the attached Dockerfile

Actual Results:

```
+ apt-get -qq -y --no-install-recommends install dokku=0.10.3
E: Unable to correct problems, you have held broken packages.
```

Expected Results:

`dokku` is installed

Additional info:

Removing the `-qq` on the `apt-get` reveals:

```
The following packages have unmet dependencies:
 dokku : PreDepends: nginx (>= 1.8.0) or
                     openresty but it is not installable
E: Unable to correct problems, you have held broken packages.
```

This bug was introduced in https://github.com/dokku/dokku/commit/9f9ecca59c0c2207aeb7bbcb6c5bb22689c6661e . The only version of nginx available in the base distro (Ubuntu 14.04) is 1.5.4.
A ppa for nginx is added later in the install process. But if the `dokku` package can’t be installed, that doesn’t happen.

`plugins/nginx-vhosts/dependencies` adds the PPA. It’s called by `sudo -E dokku plugin:install-dependencies --core`, which runs _after_ the `apt-get install` (for obvious reasons).

[Dockerfile.txt](https://github.com/dokku/dokku/files/1166070/Dockerfile.txt)

**Comment by scjody** [comment]
I think the correct fix is to add the nginx PPA _before_ running `apt-get install`.

I'll produce a PR.

From @josegonzalez on Slack:

>be careful about adding the ppa
> only add it where necesary
> on 14.04 for instance

**Comment by fccoelho** [comment]
I am facing the same issue now on a clean Ubuntu server VM 22.04

The error message is:
```
E: Unable to correct problems, you have help broken packages
```

**Comment by scjody** [comment]
@fccoelho It looks like you're facing a different issue with similar symptoms. This one was specific to Ubuntu 14.04.

I suggest opening a new issue, with more information if you're able to collect it:
* What apt command is failing exactly?
* If a "quiet" flag is used on the apt command (e.g. `apt-get -qq`), can you remove the flag and include the full output from the failing command?

**Comment by josegonzalez** [comment]
@fccoelho please file a new issue. This ticket is about an unsupported operating system, and you haven't actually posted anything we can use to debug what exactly is wrong. A new ticket will help us track and debug your issue properly. Thanks!

Also thanks @scjody for pointing out some helpful commands that will help debug the issue at hand :)
