### ISSUE TITLE
When I deploy my rails app, why can't my CHECKS file be found?

### ISSUE THREAD

**Issue by amorimlucas** [dokku/dokku#2852]
Hey, guys. I followed the instructions [here](http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/#customizing-checks) to create a custom CHECKS file, but when I deploy my app I keep getting this message:

```
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
```

The file is in the root directory of my rails app. This is the file's contents:

```
WAIT=10 
ATTEMPTS=6 
/check.txt it_works
```
And I attached the actual CHECKS file to this post, maybe the extension is wrong, or maybe something else.
[CHECKS.txt](https://github.com/dokku/dokku/files/1183753/CHECKS.txt)

**Comment by josegonzalez** [comment]
Run the following in your repo root:

```
ls -lah
```

Also, that file has a ton of extra content that isn't related to checks and is likely your editor adding extra stuff. Mind removing it to make it an actually valid checks file?

**Comment by josegonzalez** [comment]
As well, ensure the file has no extension, not even a hidden one.

**Comment by amorimlucas** [comment]
Result of ls -lah in my local app root:

```
total 112
drwxr-xr-x  24 lamorim  staff   816B Jul 28 13:49 .
drwxr-xr-x  11 lamorim  staff   374B Jul 27 01:10 ..
-rw-r--r--@  1 lamorim  staff    10K Jul 28 13:59 .DS_Store
drwxr-xr-x  12 lamorim  staff   408B Jul 28 13:49 .git
-rw-r--r--   1 lamorim  staff   536B Jun 19 14:43 .gitignore
-rw-r--r--@  1 lamorim  staff   363B Jul 28 12:55 CHECKS.txt
-rw-r--r--   1 lamorim  staff   2.2K Jul 27 14:41 Gemfile
-rw-r--r--   1 lamorim  staff   6.0K Jul 27 14:41 Gemfile.lock
-rw-r--r--@  1 lamorim  staff   120B Jul 28 12:45 Procfile
-rw-r--r--   1 lamorim  staff   374B Jun 19 14:43 README.md
-rw-r--r--   1 lamorim  staff   227B Jun 19 14:43 Rakefile
drwxr-xr-x  11 lamorim  staff   374B Jul 28 13:15 app
-rw-r--r--   1 lamorim  staff   197B Jul 28 13:03 app.json
drwxr-xr-x  12 lamorim  staff   408B Jul 25 23:39 bin
drwxr-xr-x  16 lamorim  staff   544B Jul 12 22:06 config
-rw-r--r--   1 lamorim  staff   130B Jun 19 14:43 config.ru
drwxr-xr-x   9 lamorim  staff   306B Jul 26 22:32 db
drwxr-xr-x   5 lamorim  staff   170B Jul  6 18:32 lib
drwxr-xr-x   5 lamorim  staff   170B Jun 19 14:48 log
-rw-r--r--   1 lamorim  staff    66B Jun 19 14:43 package.json
drwxr-xr-x  11 lamorim  staff   374B Jul 25 15:45 public
drwxr-xr-x  13 lamorim  staff   442B Jul 23 13:37 test
drwxr-xr-x   8 lamorim  staff   272B Jul 25 18:32 tmp
drwxr-xr-x   3 lamorim  staff   102B Jun 19 14:43 vendor
```

**Comment by amorimlucas** [comment]
Now after removing the file extension:

`...
drwxr-xr-x  12 lamorim  staff   408B Jul 28 14:06 .git
-rw-r--r--   1 lamorim  staff   536B Jun 19 14:43 .gitignore
-rw-r--r--   1 lamorim  staff   363B Jul 28 12:55 CHECKS
-rw-r--r--   1 lamorim  staff   2.2K Jul 27 14:41 Gemfile
-rw-r--r--   1 lamorim  staff   6.0K Jul 27 14:41 Gemfile.lock
...`

It's still not working.

**Comment by amorimlucas** [comment]
Which parts of the file aren't valid? The `check.txt it_works` line?

**Comment by amorimlucas** [comment]
I create a fresh CHECKS file through sublime and indeed it went from about 300 bytes to 40 bytes, and now it's working. I guess creating it through Word added some extra bytes that were messing it up. Thanks for your help!

**Comment by josegonzalez** [comment]
Did you commit the rename and push the app again?
