### ISSUE TITLE
Why can't worker find file uploaded to rails directory?

### ISSUE THREAD

**Issue by amorimlucas** [dokku/dokku#2853]
Hey, guys. I have the latest dokku installed in a fresh DO droplet, with a rails app successfully deployed. Right now I'm running into an issue with uploaded files.

My app receives image uploads, processes them, and later uploads them to S3. Locally, the way I did this was to upload the images to ~/app/assets/images/tmp, and then grab them from there with my workers to process them.

On my deployed app, I don't get any errors when I run the file upload. But when the worker tries to grab an uploaded image, I get the error:

`No such file or directory @ rb_sysopen - app/assets/images/tmp/`

I'm at a loss as to what's happening. 

I have an FTPS connection open to my droplet. Where is the rails app located? Is its folder structure even preserved in the deployed environment? Or does the structure maybe get changed?

**Comment by josegonzalez** [comment]
Each process runs in a separate, isolated container. That includes local disk.

If you want shared/persistent storage, check out our [persistent storage](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/) documentation.

**Comment by amorimlucas** [comment]
Ok, I'm going to read that over. Also, is there a way to run a rake/rails command inside the already running container? I need to run "rails jobs:clear" to clear the delayed_jobs queue, because now it's cycling through a job that keeps returning an error.

**Comment by josegonzalez** [comment]
You can either [enter an existing container](http://dokku.viewdocs.io/dokku/deployment/one-off-processes/#entering-existing-containers) or [run a one-off command](http://dokku.viewdocs.io/dokku/deployment/one-off-processes/#run-a-command-in-an-app-environment).

I'd also modify your application to handle that sort of error so that this doesn't happen in the future ;)

Please go through all of our docs, I'm sure we have something for every issue you're seeing :)

**Comment by amorimlucas** [comment]
Hey @josegonzalez, I think I have persistent storage set up correctly. In my app I'm attempting to upload to /storage. That's the path I should use, right? But I'm getting this error:

`Errno::EACCES (Permission denied @ dir_s_mkdir`

**Comment by amorimlucas** [comment]
My app needs to dynamically create tmp directories inside /storage, is this possible?

**Comment by josegonzalez** [comment]
Did you properly set permissions on the directory you mounted? What did you run to add persistent storage?

**Comment by amorimlucas** [comment]
I just ran:

`dokku storage:mount app /var/lib/dokku/data/storage/app:/storage`

And then rebuilt the app. (My is just called "app" in my install). 

This is my `dokku storage:report app`:

```
=====> app storage information
       Storage build mounts:                          
       Storage deploy mounts: -v /var/lib/dokku/data/storage/app:/storage 
       Storage run mounts:  -v /var/lib/dokku/data/storage/app:/storage 
```

**Comment by amorimlucas** [comment]
I'm able to call mkdir manually on this folder, but not through my code for some reason:

```
root@...:~# mkdir /var/lib/dokku/data/storage/test
root@...:~# ls -l /var/lib/dokku/data/storage
total 8
drwxr-xr-x 2 32767 root 4096 Jul 28 22:15 app
drwxr-xr-x 2 root  root 4096 Jul 29 18:52 test
```

**Comment by amorimlucas** [comment]
What user does dokku run my app as?

**Comment by amorimlucas** [comment]
I was able to get it working by changing the permissions to the /storage/app. Sorry for all the questions, and I really appreciate all the help so far. I'm really loving dokku, cheers!

**Comment by josegonzalez** [comment]
Persistent storage usage instructions - including directory ownership - are shown [here](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/#usage).
