### ISSUE TITLE
Specify domains in VHOST file

### ISSUE THREAD

**Issue by sam3d** [dokku/dokku#2854]
Couldn't find this anywhere in the issues, but thought it'd be a cool idea to make deployment easier. The ability to specify the domains for an application in a `VHOST` file in the repository or something similar, and if it was present, to only use the ones in the file instead of the remote name.

Is there something like this that I'm missing? Thank you!

**Comment by josegonzalez** [comment]
You didn't look hard enough ;) http://dokku.viewdocs.io/dokku/configuration/domains/

**Comment by sam3d** [comment]
Haha I did check there, but there was nothing about a file that you actually commit in the repository. Just about the `VHOST` file once it's on the server and how to modify the domains using the CLI.

**Comment by josegonzalez** [comment]
I highly recommend not editing files directly as their location and contents may change, and instead that you orchestrate via the cli tool.

**Comment by sam3d** [comment]
Nah of course; so there is no simple way to specify the (potentially) multiple domains an application _could_ have locally in the repository, before it's been deployed to the server? Or does it have to happen using CLI orchestration for now.

**Comment by josegonzalez** [comment]
You can call `dokku apps:create`, run all your config commands, then deploy the app.

**Comment by sam3d** [comment]
Ah okey dokey I've got you. Could something like this be a feature? Not asking for it to be made, as I'd be happy to take a crack at it.

**Comment by josegonzalez** [comment]
I don't understand what new functionality there is to add here. Mind explaining so I get a better picture?

**Comment by sam3d** [comment]
Of course, in theory it should be relatively simple:

I want to be able to deploy, for the first time, an application called `redirect` to the server, using the remote `dokku@dokku.me:redirect`. I want the domains for this to be `testing.com`, `www.testing.com` & `api.testing.com`. And these are the only domains I'll ever want for this application.

Currently- I could create the app on the server, configure it using the CLI and then push it; or I could push it and then configure the domains once it's uploaded. But there's no easily reproducible way, other than a plugin, to get these domains configured right out of the door.

I'm posing the idea of a `VHOST` file or a `HOSTS` file in the local repository of the `redirect` application that contains the following contents:

```
testing.com
www.testing.com
api.testing.com
```

So, in the same format as the automatically generated `VHOST` file (that shouldn't be written to). Except it just detects it copies the configuration over (much like the `DOKKU_SCALE` file is).

**Comment by sam3d** [comment]
So in essence, I'm just lazy and don't want to have to type out the domains every time I deploy 😂

**Comment by josegonzalez** [comment]
What you're asking for is something *like* #2312, though again, because the location of these files can change, it's not exactly it. I'm hoping the vhosts stuff - and other plugin-specific configuration - goes into something like #1558, where we just have a configuration domain of `domain`, with a key of `VHOST` and the value being a set of virtual hosts.

Instead I suggest you look into something like configuration management to ensure that a *server* has the correct configuration for your applications. I do this via ansible like so:

![https://cl.ly/0F1u0u3T0h2l](https://d3vv6lp55qjaqc.cloudfront.net/items/2o031X1T3O1u331T3C3c/Image%202017-05-15%20at%204.53.01%20PM.png?X-CloudApp-Visitor-Id=71f9f25184adc4c9e1750983ed1e76e6&v=4c85855f)

Is this something you'd be interested in?

**Comment by sam3d** [comment]
Reading your comments in the linked issues regarding configuration tied to the repository was interesting and inspired me to just suck it up and develop repo-independent automation & deployment. Thank you!
