### ISSUE TITLE
How to create a subdomain for a mail server?

### ISSUE THREAD

**Issue by amorimlucas** [dokku/dokku#2855]
I'm trying to create a subdomain to use for a Dovecot mail server.

I ran `domains:add-global mail.mydomain.com`, and from domains:report it looks like it was added.

But when I try to create a SSL cert for the subdomain with `sudo certbot --nginx -d mail.myserver.com` I get the message:

> Cannot find a VirtualHost matching domain mail.mydomain.com.

I have mail.mydomain.com listed on the server_name line of /etc/nginx/sites-available/default.

What am I doing wrong? Thanks.

**Comment by josegonzalez** [comment]
Why not use the official letsencrypt plugin?

**Comment by joshmanders** [comment]
https://github.com/dokku/dokku-letsencrypt will handle this for you.

**Comment by amorimlucas** [comment]
I was able to get SSL installed on the new subdomain, I needed to the subdomain to the app itself instead of to the "global" domains. Now I'm struggling a bit trying to get my Postfix/Dovecot setup to send emails.

**Comment by RickHornstein** [comment]
You can also install Wildcard Certificate of other vendor, if the letsencrypt is not working. I have a same issue with my client domain. So I used bought Wildcard Certificate at [$59 per year](https://www.cheapsslshop.com/wildcard-ssl-certificates) from reseller.
