### ISSUE TITLE
Can't git push to Dokku instance on Azure

### ISSUE THREAD

**Issue by nasushkov** [dokku/dokku#2856]
> Environment details (AWS, VirtualBox, physical, etc.):

Azure

> How was Dokku installed?:

It was installed using [this template](https://github.com/Azure/azure-quickstart-templates/tree/master/dokku-vm)

> Steps to Reproduce:

After installing Dokku with dokku-vm template for Azure (I use the latest Dokku version with Ubuntu 16.04)
I can't _git push_ to Dokku remote. The problem, I think, is that a special admin User is created from this template. So, I can ssh using its name, but when I try to git push to remote it prompts for password. What's the best way to get around this?

**Comment by josegonzalez** [comment]
Did you setup your ssh key for the dokku user on the instance? I believe you still need to access the web ui to do that.

**Comment by nasushkov** [comment]
@josegonzalez You are right. The problem was that I didn't set the public key explicitly on Web UI. My bad.
