### ISSUE TITLE
Getting 403 Forbidden Error On Deployed Static Website

### ISSUE THREAD

**Issue by amorimlucas** [dokku/dokku#2860]
I was able to deploy a rails app successfully last week, and it's working fine. Now I'm trying to get a static website working. I deployed it with the help of [this guide](https://github.com/florianheinemann/buildpack-nginx). 

It deployed without any errors that I saw, but now I keep getting 403 Forbidden when I try to access the website. My error logs:

`2017-08-04T14:52:02.708231749Z app[web.1]: 2017/08/04 14:52:02 [error] 139#0: *14 directory index of "/app/www/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "..."`

**Comment by josegonzalez** [comment]
What was the issue?

**Comment by amorimlucas** [comment]
Kind of dumb, I had named my main file something other than index.html. After I named it index.html it started working fine.

**Comment by bfontaine** [comment]
For anyone having this error on an app that uses the Node buildpack followed by the static buildpack, the fix is to run `dokku config:set your_app NGINX_ROOT=dist`.

**Comment by josegonzalez** [comment]
Please don't comment on 4 year old issues.

If anyone sees the above comment, only change the NGINX_ROOT value to something appropriate for your app. If your app has static assets in the `dist` directory, then the above is correct. If it writes the static files to root, then don't set the value.
