### ISSUE TITLE
Can't install on 16.04 Linode fails

### ISSUE THREAD

**Issue by amingilani** [dokku/dokku#2865]
Description of problem:

Running the install script on Linode Ubuntu 16.04 fails.

Output of the following commands

- `uname -a`:
- `free -m`:
- `docker version`:
- `docker -D info`:
- `sigil -v`:
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
- `dokku version`:
- `dokku plugin`:
- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details (AWS, VirtualBox, physical, etc.):

How was Dokku installed?:

Using the installation docs

How reproducible:

Tried twice, same result

Steps to Reproduce:

Follow the installation docs and run:

```
$ sudo DOKKU_TAG=v0.6.2 bash bootstrap.sh
```

Actual Results:

```
$ sudo DOKKU_TAG=v0.6.2 bash bootstrap.sh
...
n-attack-surface
         for more information.

--> Installing dokku
2017-08-08 21:02:54 URL:https://packagecloud.io/gpg.key [3889/3889] -> "-" [1]
OK
deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main
E: Unable to correct problems, you have held broken packages.
root@localhost:~# sudo DOKKU_TAG=v0.6.2 bash bootstrap.sh

```

Expected Results:

```
$ sudo DOKKU_TAG=v0.6.2 bash bootstrap.sh
....
YAYYY, ALL DONE, YOU'RE AWESOME!
```

Additional info

```
Right afterwards, I ran `apt-get install dokku` and it worked!
```

**Comment by joshmanders** [comment]
Try using `DOKKU_TAG=v0.10.3` instead of `DOKKU_TAG=v0.6.2`

**Comment by amingilani** [comment]
@joshmanders, sorry about that I used `DOKKU_TAG=v0.10.3`

**Comment by josegonzalez** [comment]
@amingilani can you run a new server with the following code and gist the exact output?

```
 wget https://raw.githubusercontent.com/dokku/dokku/v0.10.3/bootstrap.sh
 sudo DOKKU_TAG=v0.10.3 bash bootstrap.sh
```

**Comment by amingilani** [comment]
No idea what happened, but I took a break and restarted, while recording with asciinema and it worked. Closing this since I can't reproduce it anymore.
