### ISSUE TITLE
How to deploy dokku app without committing secret yml configuration files?

### ISSUE THREAD

**Issue by hilkoc** [dokku/dokku#2870]
A typical app requires a database.yml and other config.yml files that contain secret information. In the repository these files are obviously gitignored. (There is only a template file for each, with the secret information removed.)

Dokku fails to build and deploy the app, complaining that these configuration files are missing.

How can the app be deployed, using dokku, without committing the configuration files to git?
I don't want to create a separate branch and unignore them. It should be possible to maintain these files on the server (where dokku runs), because they are and need to be different on each server. Dokku should find and copy them from a local directory on the server. How can that be done?

If this is already possible, this should be documented and linked to from the getting-started documentation page.

**Comment by joshmanders** [comment]
Use environment variables. I assume you're using Rails, so do a google for "Rails with Dokku" and it should give you plenty of articles on how to get it working.

**Comment by hilkoc** [comment]
Thanks @joshmanders for your quick reply. I've read about environment variables and know how to use them. Yet, it does solve my issue:  I still need to commit my .yml files, otherwise deployment fails immediately.

**Comment by joshmanders** [comment]
From what I understand, those yml files are configuration, so your app needs them.

**Comment by josegonzalez** [comment]
In rails, you can read from environment variables directly within yaml, so the process of committing them and using env vars is the same.

We provide documentation on using environment variables [here](http://dokku.viewdocs.io/dokku/configuration/environment-variables/), and I recommend you look at the documentation for your specific framework in order to figure out how it should be configured for cloud deployments.

**Comment by hilkoc** [comment]
I get it now. If I carefully replace all my passwords with environment variables there is no objection to committing my config files. It's just that I've always been very strict in never committing configuration files, so I was trying to find a way to avoid that.
This is a new habit I just need to get used to.

Many thanks for your answers.
