### ISSUE TITLE
postdeploy fails when ran from circleci but succeeds otherwise.

### ISSUE THREAD

**Issue by mauriciozaffari** [dokku/dokku#2877]
Description of problem:
I need to deploy the application directly from circleci and run the database migrations after it. It's a rails application. When running from my machine, the deploy works as expected, but when it runs from circleci, it fails on the database connection.

Output of the following commands

    -----> uname: Linux staging 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    -----> memory:
                  total        used        free      shared  buff/cache   available
    Mem:            488         206          39          10         242         229
    Swap:          1023         437         586
    -----> docker version:
    Client:
     Version:      17.05.0-ce
     API version:  1.29
     Go version:   go1.7.5
     Git commit:   89658be
     Built:        Thu May  4 22:10:54 2017
     OS/Arch:      linux/amd64

    Server:
     Version:      17.05.0-ce
     API version:  1.29 (minimum version 1.12)
     Go version:   go1.7.5
     Git commit:   89658be
     Built:        Thu May  4 22:10:54 2017
     OS/Arch:      linux/amd64
     Experimental: false
    -----> docker daemon info:
    Containers: 16
     Running: 9
     Paused: 0
     Stopped: 7
    Images: 58
    Server Version: 17.05.0-ce
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 112
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: bridge host macvlan null overlay
    Swarm: inactive
    Runtimes: runc
    Default Runtime: runc
    Init Binary: docker-init
    containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
    runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
    init version: 949e6fa
    Security Options:
     apparmor
     seccomp
      Profile: default
    Kernel Version: 4.4.0-78-generic
    Operating System: Ubuntu 16.04.2 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 1
    Total Memory: 488.3MiB
    Name: staging
    ID: 2INT:UGU7:6WRE:WXR2:EJOS:HHO6:VJJ2:OAHQ:A62G:JAD6:2KDS:EDEL
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): true
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    Experimental: false
    Insecure Registries:
     127.0.0.0/8
    Live Restore Enabled: false

    -----> sigil version: 0.4.0
    -----> herokuish version:
    herokuish: 0.3.29
    buildpacks:
      heroku-buildpack-multi     v1.0.0
      heroku-buildpack-ruby      v159
      heroku-buildpack-nodejs    v99
      heroku-buildpack-clojure   v76
      heroku-buildpack-python    v99
      heroku-buildpack-java      v51
      heroku-buildpack-gradle    v21
      heroku-buildpack-grails    v21
      heroku-buildpack-scala     v76
      heroku-buildpack-play      v26
      heroku-buildpack-php       v121
      heroku-buildpack-go        v64
      heroku-buildpack-erlang    fa17af9
      buildpack-nginx            v8
    -----> dokku version: 0.9.4
    -----> dokku plugins:
     !     Deprecated: Please use plugin:list
    plugn: 0.3.0
      00_dokku-standard    0.9.4 enabled    dokku core standard plugin
      20_events            0.9.4 enabled    dokku core events logging plugin
      apps                 0.9.4 enabled    dokku core apps plugin
      build-env            0.9.4 enabled    dokku core build-env plugin
      certs                0.9.4 enabled    dokku core certificate management plugin
      checks               0.9.4 enabled    dokku core checks plugin
      common               0.9.4 enabled    dokku core common plugin
      config               0.9.4 enabled    dokku core config plugin
      docker-options       0.9.4 enabled    dokku core docker-options plugin
      domains              0.9.4 enabled    dokku core domains plugin
      enter                0.9.4 enabled    dokku core enter plugin
      git                  0.9.4 enabled    dokku core git plugin
      logs                 0.9.4 enabled    dokku core logs plugin
      named-containers     0.9.4 enabled    dokku core named containers plugin
      nginx-vhosts         0.9.4 enabled    dokku core nginx-vhosts plugin
      plugin               0.9.4 enabled    dokku core plugin plugin
      postgres             1.0.0 enabled    dokku postgres service plugin
      proxy                0.9.4 enabled    dokku core proxy plugin
      ps                   0.9.4 enabled    dokku core ps plugin
      repo                 0.9.4 enabled    dokku core repo plugin
      shell                0.9.4 enabled    dokku core shell plugin
      ssh-keys             0.9.4 enabled    dokku core ssh-keys plugin
      storage              0.9.4 enabled    dokku core storage plugin
      tags                 0.9.4 enabled    dokku core tags plugin
      tar                  0.9.4 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):
Dokku is installed in DigitalOcean.

How was Dokku installed?:
From DigitalOcean droplet selection.

How reproducible:
5/10

Steps to Reproduce:
1. Deploy ruby on rails application to dokku with postgres
2. Configure circleci to automatically deploy to dokku.
3. Deploy to dokku locally with git push

Actual Results:
Deploy from circleci fails while deploy with git push succeeds.

Expected Results:
Both should work.

Additional info:
Deploy step from circleci config:

    - type: deploy
      name: "Deploy to staging"
      command: |
        if [ "${CIRCLE_BRANCH}" == "development" ]; then
          echo 'kart.guru ssh-rsa AAAAB3NzaC1yc2EAAAA...M+7f0rju/X9P1YWNx' >> ~/.ssh/known_hosts
          git remote add staging dokku@host:app.git
          git push staging development:master
        fi

app.json

    {
      "scripts": {
        "dokku": {
          "postdeploy": "bundle exec rake db:migrate"
        }
      }
    }

**Comment by josegonzalez** [comment]
Can we get logging output from the commands? All of the work happens on the Dokku instance, and there isn't any functional difference between pushing from a CI box and pushing from local.

**Comment by mauriciozaffari** [comment]
Here are the relevant parts.

Failing from CI:

    -----> Creating http nginx.conf
    -----> Running nginx-pre-reload
           Reloading nginx
    -----> Setting config vars
           DOKKU_APP_RESTORE: 1
    -----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
    -----> Running 'bundle exec rake db:migrate' in app container
    remote: execution of 'bundle exec rake db:migrate' failed!
           restoring installation cache...
           rake aborted!
           PG::ConnectionBad: could not connect to server: No such file or directory
            Is the server running locally and accepting
            connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
           /app/vendor/bundle/ruby/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
           /app/vendor/bundle/ruby/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `new'
           /app/vendor/bundle/ruby/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:695:in `connect'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:220:in `initialize'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `postgresql_connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/connection_handling.rb:88:in `connection'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/schema_migration.rb:20:in `table_exists?'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/schema_migration.rb:24:in `create_table'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1125:in `initialize'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1007:in `new'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:1007:in `up'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/migration.rb:985:in `migrate'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
           /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.3/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
           /app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
           /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
           /app/bin/bundle:3:in `load'
           /app/bin/bundle:3:in `<main>'
           Tasks: TOP => db:migrate
           (See full trace by running task with --trace)
    To dokku@host:app.git
     ! [remote rejected] development -> master (pre-receive hook declined)

Working locally:

    ----> Creating http nginx.conf
    -----> Running nginx-pre-reload
           Reloading nginx
    -----> Setting config vars
           DOKKU_APP_RESTORE: 1
    -----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
    -----> Running 'bundle exec rake db:migrate' in app container
           restoring installation cache...
           D, [2017-08-19T04:57:48.241714 #7] DEBUG -- :    (1.0ms)  SELECT pg_try_advisory_lock(1745050808474813070)
           D, [2017-08-19T04:57:48.261055 #7] DEBUG -- :    (0.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
           D, [2017-08-19T04:57:48.269510 #7] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.5ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
           D, [2017-08-19T04:57:48.276939 #7] DEBUG -- :    (0.2ms)  BEGIN
           D, [2017-08-19T04:57:48.278700 #7] DEBUG -- :    (0.2ms)  COMMIT
           D, [2017-08-19T04:57:48.279230 #7] DEBUG -- :    (0.3ms)  SELECT pg_advisory_unlock(1745050808474813070)
           removing installation cache...
    -----> Shutting down old containers in 60 seconds
    =====> 6e518f744e17e9717015018f1cff202b017682fce7ea6623510540e9caa15033
    =====> Application deployed:
           http://host

    To dokku@host:app
     + 46bd0ef...4fddc90 development -> master (forced update)

**Comment by josegonzalez** [comment]
Can you turn on trace mode via `dokku trace on` and then rerun the deploy in both cases?

Are you running postgres inside of the container, or via a linked service?

**Comment by mauriciozaffari** [comment]
Failing from CI:
https://gist.github.com/mauriciozaffari/8acefa91173c307d4451dd11008cd960

Working locally:
https://gist.github.com/mauriciozaffari/b74460bd318f8e7da73de87497b7bb6d

**Comment by mauriciozaffari** [comment]
@josegonzalez Seems that for some reason, on CI it's not exporting `DATABASE_URL`.

**Comment by josegonzalez** [comment]
You are pushing to two separate applications. Locally, your remote is:

```
dokku@host:app
```

On CI, you set it to:

```
dokku@host:app.git
```

Everything, *including* the `.git`, is part of the app name, so your options are not the same. If you remove the `.git` from the remote in CI, this should work fine again.

**Comment by mauriciozaffari** [comment]
Thanks for spotting it @josegonzalez, that was indeed the case.
