### ISSUE TITLE
Do I need to use a plugin to use dokku with postgres?

### ISSUE THREAD

**Issue by J77J** [dokku/dokku#2882]
I have a server with postgres set up. I am looking to deploy to it with dokku, but the only instructions I can find tell me I need to install a plugin (eg https://github.com/dokku/dokku-postgres which will then install postgres for me?..)

Is this the only way? Can I not use the DB I have already set up? The one I have has the extensions I need already in place (just postgis and citext right now admittedly) and user/password etc and is working with phppgadmin etc

Will a db in a container not lose all data when the container shuts down?

can I use the instance of postgresql I have? Do I need to uninstall and then reinstall with the plugin?

am I making this way harder for myself than I need to?

I'm pretty sure I am not completely understanding this so any tips would be gratefully received,

J.

**Comment by joshmanders** [comment]
You can use the db you have already setup, but we recommend using a plugin. We cant support your own custom setup thought.

**Comment by J77J** [comment]
OK,

no point in fighting the tide then... I'll use the plugin.

Am I right in thinking that anything saved to the db will not be persisted though?

Would I need to use the storage plugin to make sure the db is persisted?

**Comment by joshmanders** [comment]
That's the spirit.
