### ISSUE TITLE
How to stop a running build

### ISSUE THREAD

**Issue by chrisdobler** [dokku/dokku#2883]
When I deploy a certain app, sometimes the build hangs. What is the proper way to stop the build so that I can redeploy it?

**Comment by josegonzalez** [comment]
At the moment, the only way to do so is to kill any build containers that may still be running - a bit hard... - and also remove the lockfile from the repo. We can automate the second part and warn the user that build containers may be chilling on their box and they need to manually remove them.

**Comment by josegonzalez** [comment]
We'll add something like

```
dokku deploy:lock
dokku deploy:unlock
```

These will lock/unlock deploys. We'll also want to split out the `deploy` command that currently lives in the `00_dokku-standard` plugin into it's own `deploy` plugin while we're at it.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

The subcommands are now actually in the `apps` namespace, so:

```
dokku apps:lock APP
dokku apps:unlock APP
```

And the lock status is now contained in the output of `dokku apps:report APP`.

Closing as there is a pull request open.
