### ISSUE TITLE
ps:rebuild doesn't build the new container with last commit id.

### ISSUE THREAD

**Issue by medbenmakhlouf** [dokku/dokku#2887]
Hi, 

I am having problem using [dokku-clone](https://github.com/crisward/dokku-clone) with dokku (v.10.3) on ubuntu 16.04. 
what ever the branch name I put in the command `dokku clone APP_NAME GITHUB URL BRANCH_NAME`, i always found that the new container is running with `master` branch source code. I couldn’t build any container with any different branch.

I went through the [dokku-clone](https://github.com/crisward/dokku-clone) source code and all what it does , it is updating `.git` under `$DOKKU_ROOT/$APP` and then run the command `ps:rebuild`but it doesn't pickup the last `$REV` when building the new container. it always refer to `master`. is there way to solve this ?

thanks for your help

**Comment by josegonzalez** [comment]
This seems like an issue with the plugin, not Dokku. The `dokku-clone` plugin appears to try and rsync the clone contents to itself. It doesn't change the master ref, so it probably wouldn't build an arbitrary branch.

Closing as there isn't anything we can do here.
