### ISSUE TITLE
`git push` without reinstalling node and npm

### ISSUE THREAD

**Issue by aleclarson** [dokku/dokku#2891]
I want to avoid reinstalling `node` and `npm` when I only update the application code or its `package.json` dependencies.

Is it possible to use `dokku tags` to achieve this?

Maybe you can point me to a guide. 😄 

---

`dokku report` ⇒ [link](https://pastebin.com/raw/0HGKPNB4)

Environment details: **VirtualBox v5.1.26**

How was Dokku installed?: **vagrant up**

**Comment by josegonzalez** [comment]
We use buildpacks on deployment, so we'll support whatever they support - as far as I know, you shouldn't need to reinstall node or npm. 

As we mention in our issue template, please see our [chat](https://glider-slackin.herokuapp.com/) when dealing with buildpack issues. Thanks!

**Comment by aleclarson** [comment]
Must be because I was using `git push -f`?

My question wasn't entirely buildpack-related, since I was asking if `dokku tags` was the recommended solution.

**Comment by josegonzalez** [comment]
The image tags plugin just lets you deploy pre-built docker images. You'd need to create those images somehow else, which you're welcome to do. I would read the documentation on each method to figure out what works best for your specific use case.

**Comment by aleclarson** [comment]
In case anyone else sees this, [this issue](https://github.com/heroku/heroku-buildpack-nodejs/issues/346) explains why the `node` binary is not cached by the buildpack.
