### ISSUE TITLE
Port forwarding with Vagrant

### ISSUE THREAD

**Issue by aleclarson** [dokku/dokku#2892]
I'm trying to test a NodeJS server using Dokku and Vagrant, but I can't access it from the host machine. Using `curl` from inside SSH works as expected.

I assume it's something to do with port forwarding. I've tried accessing `http://dokku.me` and `http://10.0.0.2:8080` without success. The server is listening at `http://73.255.219.219:58823` and I'm using the default `Vagrantfile` which forwards `guest: 80, host: 8080`.

I've tried doing `dokku config:set <app> PORT=80` but got an error when restarting the server.

```
events.js:182
        throw er; // Unhandled 'error' event
        ^
  Error: listen EACCES 0.0.0.0:80
      at Object._errnoException (util.js:1041:11)
      at _exceptionWithHostPort (util.js:1064:20)
      at Server.setupListenHandle [as _listen2] (net.js:1305:19)
      at listenInCluster (net.js:1370:12)
      at Server.listen (net.js:1466:7)
```

Next I'll try changing the `guest` port, but I decided to file an issue since this could affect others.

---

Dokku: **v0.10.3-53-g5e0ea9c**
Vagrant: **v1.9.8**
VirtualBox: **v5.1.26**
NodeJS: **v8.4.0**

**Comment by aleclarson** [comment]
Changing the `guest` port from 80 to 8080 (and using `dokku config:set <app> PORT=8080`) did not work for me.

On the host machine, I tried using `curl` with:
- `http://dokku.me`
- `http://<app>.dokku.me`
- `http://10.0.0.2:8080`

The first two returned:
`curl: (52) Empty reply from server`

...and the last returned:
`curl: (7) Failed to connect to 10.0.0.2 port 8081: Connection refused`.

**Comment by josegonzalez** [comment]
What is the output of: vagrant ip-config

**Comment by aleclarson** [comment]
@josegonzalez The version of `vagrant` I'm using does not have that command.

**Comment by josegonzalez** [comment]
https://stackoverflow.com/a/22333221

**Comment by josegonzalez** [comment]
Try the above

**Comment by aleclarson** [comment]
```sh
$ vagrant ssh -c "ip address show eth0 | grep 'inet ' | sed -e 's/^.*inet //' -e 's/\/.*$//'"
10.0.2.15
Connection to 127.0.0.1 closed.
```

I preemptively tried `curl http://10.0.2.15:8080` and it timed out.

**Comment by josegonzalez** [comment]
Make your app respect the PORT env vars and unset the PORT env var on your test app. Then ensure it listens on all interfaces.

Do you have another vm or something listening on 10.0.0.2?

**Comment by aleclarson** [comment]
Just the Ubuntu 14.04 VM created by Vagrant, AFAIK.

I used `dokku config:unset <app> PORT`.
The NodeJS server is now listening at `http://73.255.219.219:58823`.

Using `curl http://10.0.2.15:8080` still times out.

**Comment by josegonzalez** [comment]
How did you setup the vm? Did you set the vhost to dokku.me, as we mention in our vagrant docs?

**Comment by aleclarson** [comment]
Here's the setup I used:
```sh
git clone https://github.com/dokku/dokku.git
cd dokku
vagrant up
cd ../my-app
git remote add dokku dokku@dokku.me:my-app
git push dokku master
```

There is no "vhost" mentioned in [this guide](http://dokku.viewdocs.io/dokku/getting-started/install/vagrant/).

But I did not add `Host dokku.me \n Port 22` to my `~/.ssh/config`. Is this required for me to access my server?

**Comment by josegonzalez** [comment]
Yes. The vm config is set such that dokku.me should work perfectly unless you have strange networking requirements.

**Comment by aleclarson** [comment]
Alright, I'll report back if there are any issues. 😉 

Is this how I set up SSH to work properly?

```sh
Host dokku.me
  Port 22

Host dokku.me
  User git
  IdentityFile ~/.ssh/dokku
  IdentitiesOnly yes
```

**Comment by josegonzalez** [comment]
Combine  those two stanzas

**Comment by aleclarson** [comment]
Everything is working. Thanks for the diagnosis.
