### ISSUE TITLE
Trying to get app to communicate with image server

### ISSUE THREAD

**Issue by J77J** [dokku/dokku#2893]
My main app uses an image server for images,

I have my main app set up in a container and it will use an image server for images (also running in a container)

how do I go about getting one to communicate with the other?

Can I somehow link the two? or do I need to expose the port on the image server container? If so - I can't see any instructions on how to do that. I use the postgres plugin which allows me to easily expose the db service's port - is there something like that?

apologies if this is documented somewhere as I cannot find instruction on how to do this..

Thanks in advance,

Johnny

**Comment by josegonzalez** [comment]
We do not allow linking applications to each other at this time, and you'll need to use public dns to have one reference the other.

**Comment by sglebs** [comment]
At a client they implemented https://github.com/isaacsouza/dokku-apps-env for that. Unfortunately the Readme is in Brazilian Portuguese. But the essence is at the end:

Commands

$ dokku help
    apps:link <app-source> <app-target>       Set in <app-target> variable APP_SOURCE_NAME_URL with access url
    apps:unlink <app-source> <app-target>     Unset in <app-target> APP_SOURCE_NAME_URL

You use env vars to make it configurable and this plugin will inject the value automatically if the app is under the same dokku.

**Comment by J77J** [comment]
@josegonzalez OK, thought I'd check before I went ahead and did it, in case there was an easy way within dokku.. :)

@sglebs thanks I'll take a look at that.

Johnny
