### ISSUE TITLE
Traffic being routed to the incorrect application

### ISSUE THREAD

**Issue by dabeeeenster** [dokku/dokku#2896]
I have two pretty vanilla apps running on a single host, each with a domain pointing to each app. After rebooting for a kernel security ipdate, all traffic is being routed to one of the apps. If I restart the app (with a ```ps:restart```) that is not being routed to, things correct themselves. This is with 0.10.4.

**Comment by josegonzalez** [comment]
This is a known issue, has to do with docker-related changes. See #2403 for more information, and #2736 to follow along with the fix.

**Comment by dabeeeenster** [comment]
Great - thanks for the swift response, and thanks for the amazing project.
