### ISSUE TITLE
rake assets:precompile fails are pushing a few times

### ISSUE THREAD

**Issue by hilkoc** [dokku/dokku#2897]
Hi, let me first say I am impressed with the capabilities of dokku: Installing a database, setting up a letsencrypt certificate, deploying an app,  all with a few commands. That is really amazing. Thanks for making that possible.

I managed to get my rails app up and running with dokku using this [guide](https://wiki.diasporafoundation.org/Installation/Dokku).  Then I started to make a few small changes and push those to my dokku server. Now every push fails with this error
```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       Rack::SSL is enabled
       rake aborted!
       Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/build/app/assets/images/branding/logos-s72255883d0.png
       /tmp/build/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/asset.rb:99:in `binread'
       /tmp/build/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/asset.rb:99:in `source'
       /tmp/build/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/utils/gzip.rb:7:in `initialize'
```

Logging into the server and doing dokku ps:rebuild produces the same error. I am really stuck. Please help!

Iet me post some more details below.

repository: git clone --branch dokku https://github.com/hilkoc/diaspora.git
steps to reproduce: https://wiki.diasporafoundation.org/Installation/Dokku
then add some whitespace to a random file, commit and push. Repeat this a few times

uname -a:
`Linux MVFC001 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

free -m:
```
             total        used        free      shared  buff/cache   available
Mem:            992         103         375           8         514         677
Swap:          3903         125        3778
```

docker version:
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64


Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker -D info:
```
Containers: 9
 Running: 4
 Paused: 0
 Stopped: 5
Images: 49
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 99
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: MVFC001
ID: 44MF:SLAS:RGHS:G63R:DAMZ:IN5C:T52X:EBOF:5YL6:TBMQ:POIW:XDWR
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

sigil -v:
`0.4.0`

docker run -ti gliderlabs/herokuish:latest herokuish version:
```
herokuish: 0.3.31
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v163
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v109
  heroku-buildpack-java      v52
  heroku-buildpack-gradle    v22
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v121
  heroku-buildpack-go        v69
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
```

dokku version:
`0.10.3`

dokku plugin:
```
!     Deprecated: Please use plugin:list
plugn: 0.3.0
  00_dokku-standard    0.10.3 enabled    dokku core standard plugin
  20_events            0.10.3 enabled    dokku core events logging plugin
  apps                 0.10.3 enabled    dokku core apps plugin
  build-env            0.10.3 enabled    dokku core build-env plugin
  certs                0.10.3 enabled    dokku core certificate management plugin
  checks               0.10.3 enabled    dokku core checks plugin
  common               0.10.3 enabled    dokku core common plugin
  config               0.10.3 enabled    dokku core config plugin
  docker-options       0.10.3 enabled    dokku core docker-options plugin
  domains              0.10.3 enabled    dokku core domains plugin
  enter                0.10.3 enabled    dokku core enter plugin
  git                  0.10.3 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.10.3 enabled    dokku core logs plugin
  named-containers     0.10.3 enabled    dokku core named containers plugin
  nginx-vhosts         0.10.3 enabled    dokku core nginx-vhosts plugin
  plugin               0.10.3 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.10.3 enabled    dokku core proxy plugin
  ps                   0.10.3 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  repo                 0.10.3 enabled    dokku core repo plugin
  shell                0.10.3 enabled    dokku core shell plugin
  ssh-keys             0.10.3 enabled    dokku core ssh-keys plugin
  storage              0.10.3 enabled    dokku core storage plugin
  tags                 0.10.3 enabled    dokku core tags plugin
  tar                  0.10.3 enabled    dokku core tar plugin
```

contents of Procfile (see also https://github.com/hilkoc/diaspora/blob/dokku/Procfile):
```
web: bin/bundle exec unicorn -c config/unicorn.rb -p $PORT
sidekiq: bin/bundle exec sidekiq
```

**Comment by josegonzalez** [comment]
Does that asset exist in your repository?

**Comment by hilkoc** [comment]
I assume it does. Or at least it did. I've seen my app up and running. I don't understand how doing a rebuild can suddenly make this logo disappear.

**Comment by josegonzalez** [comment]
That file doesn't exist here: https://github.com/hilkoc/diaspora/tree/develop/app/assets/images/branding

**Comment by hilkoc** [comment]
This is confusing me. I've made only two changes in the original source:  1) add a ruby version to the Gemfile, 2) unignore and commit the database.yml and diaspora.yml files.

I've never touched any image files. Indeed I see the file is not there, but my guess is that somehow the  assets:precompile step must have created it the first time when it succeeded.

How could I debug this further?

**Comment by hilkoc** [comment]
After running rake assets:precompile locally. I find
```
ls public/assets/branding/
logos-s72255883d0-99eda28179edece43baa5427818f91368cb8f31d71e310477a6238d4e09a6c9b.png
```
of which the first part of the file name matches that in the error
`/tmp/build/app/assets/images/branding/logos-s72255883d0.png`

So it looks like the assets:precompile  creates this, but with a much longer name.

**Comment by josegonzalez** [comment]
This is almost certainly an application error, not a Dokku issue (or even a heroku buildpack issue). You'll need to figure out what the precompile step is doing when it generates the file - maybe sprockets has a debug mode?

It's possible sprockets does some weird caching somewhere, and is using an [old file](https://github.com/rails/sprockets/issues/127). Try [purging your build cache](http://dokku.viewdocs.io/dokku/advanced-usage/repository-management/) and see if this happens.

Finally, I would suggest reaching out to the sprockets community to see what is going on. It's possible your ruby update caused the gem to update as well, and there is some functionality that changed in the writing of any generated files.

Closing as this isn't a Dokku issue, but something to do with how your application is built.

**Comment by hilkoc** [comment]
`dokku repo:purge-cache diaspora` is a usable workaround. It takes a while, because all the gems need to be downloaded again, but at least it works and my app is deploying again!

This is a very useful command, because at least I don't need to destroy and recreate the whole app.

Many thanks for your time and quick reply.
