### ISSUE TITLE
Error accessing logs after restarting server

### ISSUE THREAD

**Issue by ealbuquerque** [dokku/dokku#2898]
I restarted my server and now I can not access the application logs.
Apparently my application is working.

`
$ dokku logs app_name -t
`
`
error from daemon in stream: Error grabbing logs: EOF
`

Dokku version: 0.10.4

**Comment by josegonzalez** [comment]
Can you run the following:

```
dokku --trace logs app_name -t
```

**Comment by ealbuquerque** [comment]
@josegonzalez 

`$ dokku --trace logs app_name  -t

+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOKKU_IMAGE=gliderlabs/herokuish
+ DOKKU_IMAGE=gliderlabs/herokuish
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args logs app_name -t
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=2
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=3
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=4
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ logs =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ /usr/bin/tty
+ [[ /dev/pts/0 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ logs =~ ^plugin:.* ]]
+ [[ logs == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ -n '' ]]
+ dokku_auth logs app_name -t
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=ubuntu
+ SSH_USER=ubuntu
+ export SSH_NAME=default
+ SSH_NAME=default
+ plugn trigger user-auth ubuntu default logs app_name -t
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ logs =~ (ssh-keys:add|ssh-keys:remove) ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd logs app_name -t
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=logs
+ local PLUGIN_CMD=logs
+ local implemented=0
+ local script
+ argv=("$@")
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/logs
+ [[ /var/lib/dokku/core-plugins/available/logs == *core-plugins* ]]
+ [[ logs == \l\o\g\s ]]
+ shift 1
+ [[ ! -z '' ]]
+ set -- logs app_name -t
+ [[ -x /var/lib/dokku/plugins/enabled/logs/subcommands/default ]]
+ /var/lib/dokku/plugins/enabled/logs/subcommands/default logs app_name -t
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ logs_default_cmd logs app_name -t
+ declare 'desc=shows the last logs for an app via command line'
+ local cmd=logs
+ [[ -z app_name ]]
+ local APP=app_name
+ verify_app_name app_name
+ declare 'desc=verify app name format and app existence'
+ local APP=app_name
+ is_valid_app_name app_name
+ declare 'desc=verify app name format'
+ local APP=app_name
+ [[ ! -n app_name ]]
+ [[ ! app_name =~ ^[a-z].* ]]
+ return 0
+ [[ ! -d /home/dokku/app_name ]]
+ return 0
+ local APP_ROOT=/home/dokku/app_name
+ COLORS=(36 33 32 35 31)
+ local COLORS
+ is_deployed app_name
+ declare 'desc=return 0 if given app has a running container'
+ local APP=app_name
+ [[ -f /home/dokku/app_name/CONTAINER ]]
++ ls /home/dokku/app_name/CONTAINER.web.1
++ echo 0
+ [[ 0 -eq 0 ]]
+ return 0
+ shift 2
++ getopt -o htqn:p: --long help,tail,quiet,num:,ps: -n 'dokku logs' -- -t
+ local 'TEMP= -t --'
+ local EXIT_CODE=0
+ [[ 0 != 0 ]]
+ eval set -- ' -t --'
++ set -- -t --
+ local DOKKU_LOGS_LINE_NUMBERS=100
+ true
+ case "$1" in
+ local 'DOKKU_LOGS_ARGS+=--follow '
+ shift
+ true
+ case "$1" in
+ shift
+ break
+ [[ -n '' ]]
+ CONTAINERS=("$APP_ROOT"/CONTAINER.*)
+ local CONTAINERS
++ stat -t /home/dokku/app_name/CONTAINER.web.1
+ [[ -z /home/dokku/app_name/CONTAINER.web.1 65 8 81b4 1001 1001 ca01 304588 1 0 0 1504578308 1504578308 1504578308 0 4096 ]]
+ local 'DOKKU_LOGS_ARGS+=--tail 100'
+ (( MAX_INDEX=1 - 1 ))
+ true
+ for i in '${!CONTAINERS[*]}'
++ sed -r 's/.*CONTAINER\.(.*)/\1/'
++ echo /home/dokku/app_name/CONTAINER.web.1
+ local DYNO=web.1
+ local CID=381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676
+ local COLOR=36
+ [[ '' == \t\r\u\e ]]
+ local 'DOKKU_LOGS_PRETTY_PRINT_CMD=sed -r '\''s/^([^Z]+Z )/\x1b[36m\1app[web.1]:\x1b[0m /gm'\'''
+ local 'DOKKU_LOGS_CMD+=(docker logs -t --follow --tail 100 381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676 2>&1 | sed -r '\''s/^([^Z]+Z )/\x1b[36m\1app[web.1]:\x1b[0m /gm'\'')'
+ [[ 0 != \0 ]]
+ local 'DOKKU_LOGS_CMD+=; '
+ bash -c '((docker logs -t --follow --tail 100 381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676 2>&1 | sed -r '\''s/^([^Z]+Z )/\x1b[36m\1app[web.1]:\x1b[0m /gm'\''); )'
error from daemon in stream: Error grabbing logs: EOF

+ implemented=1
+ [[ 1 -eq 0 ]]
+ [[ 1 -eq 0 ]]`

**Comment by josegonzalez** [comment]
Run the following:

```
docker inspect 381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676
```

**Comment by ealbuquerque** [comment]
@josegonzalez 

```json
[
    {
        "Id": "381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676",
        "Created": "2017-09-05T02:25:08.340990156Z",
        "Path": "/start",
        "Args": [
            "web"
        ],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 128,
            "Error": "driver failed programming external connectivity on endpoint vigilant_hodgkin (8b38fc8c6121edc1e6fdaa3d478b05a89d4c48c6be0c10a5442a55a3bedf7977): Bind for 0.0.0.0:11003 failed: port is already allocated",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:3b7413650432797ea78d4394a68526f9875ec8e7d3f5e671db52c0e0be332426",
        "ResolvConfPath": "/var/lib/docker/containers/381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676/resolv.conf",
        "HostnamePath": "",
        "HostsPath": "/var/lib/docker/containers/381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676/hosts",
        "LogPath": "",
        "Name": "/app_name.web.1",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "11001/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "11001"
                    }
                ],
                "11003/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "11003"
                    }
                ],
                "11004/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "11004"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 10
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": [
                "/dokku.postgres.app_name:/app_name.web.1/dokku-postgres-app_name"
            ],
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "381bb80bed85",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "11001/tcp": {},
                "11003/tcp": {},
                "11004/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PORT=5000",
                "USER=herokuishuser",
                "DYNO=web.1",
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/start",
                "web"
            ],
            "Image": "dokku/app_name:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "dokku": ""
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "c02460094d8f50e38f12209b418b2d40b4dca2d7ef22ec771f9396d384d5a3b4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/c02460094d8f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "922d0500aeb87b94acd87b8bf83d63a81fc37177ea7b0d7772a85a1a6050a311",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by josegonzalez** [comment]
docker logs -t --follow --tail 100 381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676

**Comment by ealbuquerque** [comment]
@josegonzalez, the same error

```sh
$ sudo docker logs -t --follow --tail 100 381bb80bed85596eb1f642669bc005666e17766bbd7d8724bfb96d2558cf1676
error from daemon in stream: Error grabbing logs: EOF
```

**Comment by josegonzalez** [comment]
Sounds like a docker bug, I would file it with them. Sorry.

**Comment by ealbuquerque** [comment]
Oh, okay ... I'll make a backup of the database and my application and reinstall everything.

Thanks for the fast support!!

**Comment by josegonzalez** [comment]
You can try to just rebuild the app, which should "fix" the container by replacing it:

```
dokku ps:rebuild APP
```

**Comment by ealbuquerque** [comment]
For now, apparently, the app is working properly.
I've run this command before...

Can this bug be solved soon? Or should I backup and reinstall everything?

Anyway... thank you @josegonzalez

**Comment by josegonzalez** [comment]
Thats literally a docker bug. We don't maintain docker, just use it. If the docker daemon is responding with that bug, you will need to report it to them and figure out what the issue is upstream.

If the ps:rebuild of your app doesn't make the logs command work, then I'd say something is wrong with the daemon and would defer to what the docker folks say.

**Comment by DavidLemayian** [comment]
After spending some time upgrading and downgrading dokku and docker-ce packages on Ubuntu server, it looks like it's an issue with  `dokku>=0.10.4` only `dokku=0.10.3` working for me.

If anyone else getting the same issue, this solved it for me:
```sh
$ sudo apt install dokku=0.10.3
$ dokku ps:rebuild APP
```

**Comment by josegonzalez** [comment]
@DavidLemayian can you open a separate issue as to what you're seeing and why you think this is an issue with Dokku? Thanks.
