### ISSUE TITLE
About Website Improvement

### ISSUE THREAD

**Issue by buckle2000** [dokku/dokku#2899]
Dokku is so great!
You people should definitely mention that dokku has nginx and db integration on the index page, not somewhere hidden in docs.
In fact, all features should be mentioned on the index page, so more devs will decide to use Dokku

**Comment by josegonzalez** [comment]
I have an updated homepage that is going out - along with some "for sale" enterprisey plugins - at some point soon, and will definitely be including features on the homepage. Thanks for the idea!
