### ISSUE TITLE
bug: CACHE_DIR env var during herokuish build can be shadowed by config_export

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#2901]
If a user sets `CACHE_DIR` for their app, then the variable set [here](https://github.com/dokku/dokku/blob/15494d85a9f1ecde7cd398863e80ffa3941260b5/plugins/common/functions#L445) can be shadowed by the [config_export](https://github.com/dokku/dokku/blob/15494d85a9f1ecde7cd398863e80ffa3941260b5/plugins/common/functions#L447) call.

We should rename our variable so that people can set this commonly set env var.

**Comment by curious-attempt-bunny** [comment]
Thank you for diagnosing the problem, @josegonzalez!
