### ISSUE TITLE
Integrate dokku registry plugin

### ISSUE THREAD

**Issue by chrisnicola** [dokku/dokku#2904]
The dokku registry plugin looks like it isn't being maintained any longer. However it is a much better workflow for those of us using CI to build our docker images and potentially storing them in a private repository like those that Gitlab provides.

I'm using the patch in https://github.com/agco/dokku-registry/pull/4 however it really seems like this should just be built into the tags feature itself or as a separate feature. The current workflow involving piping images over ssh doesn't really work well.

**Comment by chrisnicola** [comment]
Just realizing that the 'docker-direct' plugin also provides sufficient functionality to achieve deployment by using it to login, pull and tag an image from another repository. Either way the ability to access basic docker repository functionality via the dokku user seems really fundamental for good docker workflows.

**Comment by josegonzalez** [comment]
While I think managing docker registry authentication is interesting, there are a few edge cases sometimes - particularly with ECR. As it's not something 80% of our users will be using, I'm going to punt on inclusion of such functionality in the core.

I think if anything, this is a good candidate for an official plugin - in the same vein as any of the datastores - before promotion to being in the core. I might consider it as something to develop for when we hit the next [patreon](https://www.patreon.com/dokku) goal.

**Comment by josegonzalez** [comment]
There is a _very alpha_ plugin available [here](https://github.com/dokku/dokku-registry) for Dokku that will provide a lot of this functionality, and our upcoming scheduler work somewhat depends on it. Once it gets better/any test coverage, this will likely land in the core.
