### ISSUE TITLE
Is it possible to deploy an app to a subfolder rather than subdomain?

### ISSUE THREAD

**Issue by J77J** [dokku/dokku#2905]
ie - if I'm looking to deploy myapp it would normally be deployed as:

`myapp.mydomain.com`

is it possible to deploy to `mydomain.com/myapp` instead?

How would I go about this (if possible)

Thanks,

J.

**Comment by J77J** [comment]
I'm thinking about this totally wrong am I not? I think I should be looking to proxy through nginx to achieve this..

**Comment by josegonzalez** [comment]
We cannot do subfolder proxies as domains are tied to an app.

What we do at the CakePHP organization is have a separate nginx conf in `/etc/nginx/sites-enabled` that proxies internally like so:

```
    location ~ ^/2\.0(.*) {
        proxy_set_header Host "book-2.cakephp.org";
        rewrite ^/2\.0(.*) /2.0$1 break;
        proxy_pass http://localhost:80;
    }
```

And then we simply call the application `book-2`.
