### ISSUE TITLE
Please mention formal url for git push

### ISSUE THREAD

**Issue by buckle2000** [dokku/dokku#2907]
In the docs, only `dokku@<site>:<app name>` is mentioned as a git push "url".

Actually, it is not an URL at all. According to [Git](https://git-scm.com/docs/git-clone#_git_urls_a_id_urls_a), this is a scp-like syntax, which is only supported by few services.

~~However, the `:` may confuse some services, including Gitlab. (Gitlab can not sync to a repo with two `:` in the url.~~

Alternatively, please put `ssh://dokku@<site>/<app name>` in the docs.

**Comment by joshmanders** [comment]
Pull requests welcome.

**Comment by josegonzalez** [comment]
Where are you seeing two colons in the url? We have precisely one, which is between the server and the application name.

**Comment by buckle2000** [comment]
@josegonzalez There is an implicit one (but gitlab only allows url with explicit protocol).
`git://example.com:app`
`ssh://example.com:app`

**Comment by josegonzalez** [comment]
I see a colon in your scheme, but don't see where there would otherwise be an implicit colon.

**Comment by buckle2000** [comment]
Well, I misunderstood that as an URL.

**Comment by josegonzalez** [comment]
Closed by #2910.
