### ISSUE TITLE
Debian package upgrade removes users from group "dokku"

### ISSUE THREAD

**Issue by xals** [dokku/dokku#2908]
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

Description of problem:

I upgraded the package dokku yesterday, on a Debian system. After the upgrade, the users I had added in "dokku" group were removed.

Output of the following commands

Dokku report: 

-----> uname: Linux btl-dev01 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
-----> memory:                       
              total        used        free      shared  buff/cache   available
Mem:           3955         614         944         101        2396        2956
Swap:          1023           0        1023
-----> docker version:     
Client:
 Version:      17.05.0-ce     
 API version:  1.29        
 Go version:   go1.7.5   
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64         
                                 
Server:                         
 Version:      17.05.0-ce       
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5          
 Git commit:   89658be          
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64      
 Experimental: false             
-----> docker daemon info:      
Containers: 5                       
 Running: 3                    
 Paused: 0                  
 Stopped: 2          
Images: 38  
Server Version: 17.05.0-ce                                         
Storage Driver: overlay2                                                 
 Backing Filesystem: xfs                                       
 Supports d_type: true                                              
 Native Overlay Diff: true                                                       
Logging Driver: json-file                                        
Cgroup Driver: cgroupfs                                          
Plugins:                                                         
 Volume: local                                                           
 Network: bridge host macvlan null overlay                        
Swarm: inactive                                                 
Runtimes: runc                                                
Default Runtime: runc                                          
Init Binary: docker-init                                                   
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145           
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228           
init version: 949e6fa                                                
Security Options:                                               
 seccomp                                                     
  Profile: default                                             
Kernel Version: 4.9.0-3-amd64                                   
Operating System: Debian GNU/Linux 9 (stretch)                     
OSType: linux                                                     
Architecture: x86_64                                           
CPUs: 2                                                       
Total Memory: 3.863GiB
Name: btl-dev01
ID: M4DL:WXYP:OUYG:XLU4:YOII:RHYB:TFSH:JFSH:YAMY:NJE4:OOWX:NPGJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version:
herokuish: 0.3.32
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v168
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v77
  heroku-buildpack-python    v99
  heroku-buildpack-java      v53
  heroku-buildpack-gradle    v23
  heroku-buildpack-scala     v78
  heroku-buildpack-play      v26
  heroku-buildpack-php       v122
  heroku-buildpack-go        v72
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.10.4
-----> dokku plugins:
plugn: 0.3.0
  00_dokku-standard    0.10.4 enabled    dokku core standard plugin
  20_events            0.10.4 enabled    dokku core events logging plugin
  apps                 0.10.4 enabled    dokku core apps plugin
  build-env            0.10.4 enabled    dokku core build-env plugin
  certs                0.10.4 enabled    dokku core certificate management plugin
  checks               0.10.4 enabled    dokku core checks plugin
  common               0.10.4 enabled    dokku core common plugin
  config               0.10.4 enabled    dokku core config plugin
  docker-options       0.10.4 enabled    dokku core docker-options plugin
  domains              0.10.4 enabled    dokku core domains plugin
  enter                0.10.4 enabled    dokku core enter plugin
  git                  0.10.4 enabled    dokku core git plugin
  logs                 0.10.4 enabled    dokku core logs plugin
  named-containers     0.10.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.10.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.10.4 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.10.4 enabled    dokku core proxy plugin
  ps                   0.10.4 enabled    dokku core ps plugin
  repo                 0.10.4 enabled    dokku core repo plugin
  shell                0.10.4 enabled    dokku core shell plugin
  ssh-keys             0.10.4 enabled    dokku core ssh-keys plugin
  storage              0.10.4 enabled    dokku core storage plugin
  tags                 0.10.4 enabled    dokku core tags plugin
  tar                  0.10.4 enabled    dokku core tar plugin

How was Dokku installed?:

Using Debian package repository:

    deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main

How reproducible:

I only have one server with dokku.

Steps to Reproduce:
1. aptitude upgrade
2.
3.

Actual Results:

Dokku group is empty:

    # getent group dokku
    dokku:x:1006:

And the following lines were found in `/var/log/auth.log`:

    Sep 21 23:04:57 btl-dev01 gpasswd[18990]: user dokku added by root to group adm
    Sep 21 23:04:57 btl-dev01 gpasswd[18995]: members of group dokku set by root to

Expected Results:

Dokku group contains previously added users:

    # getent group dokku
    dokku:x:1006:removedforprivacy

Additional info:

Adding user in dokku group is documented and upgrade should care about it: 
https://github.com/dokku/dokku/blob/master/docs/deployment/user-management.md#granting-other-unix-user-accounts-dokku-access

**Comment by josegonzalez** [comment]
Our documentation actually doesn't say to add them to the group, but instead says to use a sudoers file. Is there a reason why you did the former and not the latter?

**Comment by josegonzalez** [comment]
Note: Seems we remove everyone from the dokku group [here](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/install#L56). @michaelshobbs do you recall why we do that?
