### ISSUE TITLE
What's wrong with the docs?

### ISSUE THREAD

**Issue by buckle2000** [dokku/dokku#2909]
![Image: page](https://user-images.githubusercontent.com/10850402/30770816-84632336-a06c-11e7-8e1d-c90a0006eb22.png)
![Image: inspector](https://user-images.githubusercontent.com/10850402/30770821-957dcf4a-a06c-11e7-85a8-83d0b7f5a673.png)

**Comment by josegonzalez** [comment]
Upstream bug in github's rendering which viewdocs uses. It was filed [here](https://github.com/progrium/viewdocs/issues/51) already. I guess someone just pushed that change out today.

**Comment by josegonzalez** [comment]
Looks like github fixed their renderer :)
