### ISSUE TITLE
How to change IP/default URL

### ISSUE THREAD

**Issue by buckle2000** [dokku/dokku#2914]
## Description of problem:

After the server's IP address is changed, the IP address displayed by dokku is not changed.

But the apps inside dokku can still work.

## dokku report:
https://gist.github.com/buckle2000/8f3244133df2f290b999f29a23f9b4ed

## Steps to Reproduce:
1. Open up a server at ip address `a.a.a.a`
2. Install dokku
3. Change the server's ip to `b.b.b.b`
4. Run `dokku urls <whatever app>`

## Actual Results:
`http://a.a.a.a:<port>/`

## Expected Results:
`http://b.b.b.b:<port>/`

**Comment by josegonzalez** [comment]
Please see our [domains documentation](http://dokku.viewdocs.io/dokku/configuration/domains/).

**Comment by buckle2000** [comment]
But no global or app-specific domain in this case.

**Comment by josegonzalez** [comment]
Check the domains that are attached both globally and for the app. You'll see that we're using the ip address.

**Comment by buckle2000** [comment]
```bash
# dokku domains:report
=====> xxxxxxxxx domains information
       Domains app enabled: true
       Domains app vhosts:
       Domains global enabled: false
       Domains global vhosts:
```

**Comment by josegonzalez** [comment]
What is the output of `dokku domains APP`:

**Comment by buckle2000** [comment]
The same as above.

**Comment by josegonzalez** [comment]
Can you do:

```
cat /home/dokku/VHOST
cat /home/dokku/HOSTNAME
```

And show me the output of each file?

**Comment by buckle2000** [comment]
```bash
$ cat /home/dokku/VHOST
cat: /home/dokku/VHOST: No such file or directory
$ cat /home/dokku/HOSTNAME
163.172.182.72
```

**Comment by josegonzalez** [comment]
We store it as that is what you specified you wanted to use as the hostname for dokku. You'll need to update it if you want to change the ip address of the box.

**Comment by josegonzalez** [comment]
Related issue as to the difference between the two: https://github.com/dokku/dokku/pull/2196

**Comment by punnerud** [comment]
Solved it for me by changing the value in HOSTNAME in dokku-user root on the host, and running this command:
`dokku domains:set-global example.com`
(replace example.com)
