### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by wootwoot1234** [dokku/dokku#2917]
I keep getting the "413 Request Entity Too Large" error when uploading files that are larger than 1M.  I followed the following instructions from [here](http://dokku.viewdocs.io/dokku/configuration/nginx/) but it didn't work.

    mkdir /home/dokku/myapp/nginx.conf.d/
    echo 'client_max_body_size 50M;' > /home/dokku/myapp/nginx.conf.d/upload.conf
    chown dokku:dokku /home/dokku/myapp/nginx.conf.d/upload.conf
    service nginx reload

I tried updating my `Procfile` adding a php.ini file to my root directory with the following entry but it also didn't help:

Procfile:

    web: vendor/bin/heroku-php-nginx -C nginx.conf -i php.ini php/

php.ini:

    upload_max_filesize = 100M
    post_max_size = 100M

What am I doing wrong?  Is there anyway to test if my configurations are being used or if they are being overwritten by something else?  I checked `phpinfo();` and those setting are being used, is there an equivalent to that for nginx? 

Is there a way to change the nginx settings globally for all images?

**Comment by josegonzalez** [comment]
You need to replace `myapp` with your application's name in the instructions.

**Comment by wootwoot1234** [comment]
I should have said that, sorry.  Yes, I used my app name not `myapp` and it's not working.

**Comment by josegonzalez** [comment]
Can you hop onto our slack chat room to get support? That will make debugging this issue for you much easier.

**Comment by wootwoot1234** [comment]
Sure.  Do you have a link.  I've never use slack but can sign up.

**Comment by josegonzalez** [comment]
http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/

**Comment by josegonzalez** [comment]
Problem was that the user customized their heroku app's nginx config but neglected to add the `client_max_body_size 50M;` to the config.

**Comment by wootwoot1234** [comment]
@josegonzalez figured it out:

In my `Procfile` I have:

    web: vendor/bin/heroku-php-nginx -C nginx.conf -i php.ini php/

so in addition to my other configurations (see my first post) I had to add `client_max_body_size 100m;` to the top of `nginx.conf`, mine looks like this:

    client_max_body_size 100m;
    location / {
        index index.php;
        try_files $uri $uri/ /index.php$is_args$args;
    }
