### ISSUE TITLE
[RFC] Check if nginx is running before trying to reload

### ISSUE THREAD

**Issue by aleclarson** [dokku/dokku#2921]
Could [`restart_nginx`](https://github.com/dokku/dokku/blob/8004f0962cf92d77a1f17435a83466c4fd8fc488/plugins/nginx-vhosts/functions#L49) be changed to try `nginx start` first?

In the automated bootstrap phase for my server, `nginx -s stop` is called immediately after installing Dokku in order to avoid the "Welcome to nginx" page from being served before I deploy the first version of my app.

After pushing my app, the `nginx reload` command fails because nginx was stopped.

Or would you suggest I do something different to avoid serving the "Welcome to nginx" page?

---

dokku version: `v0.10.4`

**Comment by josegonzalez** [comment]
You could create a default site instead: http://dokku.viewdocs.io/dokku/configuration/domains/#default-site

I recommend doing the above, especially if you are installing everything via configuration management.
