### ISSUE TITLE
The Persistent Storage with Rails application does not work correctly

### ISSUE THREAD

**Issue by afuno** [dokku/dokku#2923]
I did everything exactly the same way as described on [this](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/) page:

```
mkdir -p /var/lib/dokku/data/storage/my-rails-app
chown -R 32767:32767 /var/lib/dokku/data/storage/my-rails-app
dokku storage:mount my-rails-app /var/lib/dokku/data/storage/my-rails-app:/app/public/uploads
```

If I upload a file through the site, then it is placed in this directory: `/var/lib/dokku/data/storage/my-rails-app`.

Rails project is configured correctly, because locally (without dokku) everything works.

Output of the following commands

- `uname -a`: Linux news 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`: https://pastebin.com/raw/AZ571x1h
- `docker version`: https://pastebin.com/raw/SbSX5wa8
- `docker -D info`: https://pastebin.com/raw/QKH3Zp5j
- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`: https://pastebin.com/raw/TzWTTiNd
- `dokku version`: 0.10.4
- `dokku plugin`: https://pastebin.com/raw/t6WCb66u
- `cat /home/dokku/<app>/nginx.conf` (if applicable): https://pastebin.com/raw/DnJnnZzd

**Comment by josegonzalez** [comment]
> If I upload a file through the site, then it is placed in this directory: /var/lib/dokku/data/storage/my-rails-app.

Sounds like it works?

**Comment by afuno** [comment]
@josegonzalez Files are uploaded to the server in the desired directory. With this part everything is fine.

But why are these files not available on the site?

Rails is configured correctly. And more precisely - CarrierWave.
CarrierWave has a path to the root:
 - Local: /Users/profox/Library/Mobile Documents/com~apple~CloudDocs/Projects/rails-app/public
 - Server: /app/public

That is, the path to the public directory is correct.

**Comment by josegonzalez** [comment]
> But why are these files not available on the site?

What do you mean by "not available"? You just said the persistent storage plugin doesnt work, but you are clearly uploading files and they are being stored correctly. If you mean that you aren't able to link to them properly, that sounds like an application-level bug?

**Comment by afuno** [comment]
@josegonzalez 

```html
<img class="img-fluid" src="http://my.site/uploads/image/file/76/47/96/36fa0c7964b6c498.jpg" alt="Xxl 36fa0c7964b6c498">
```

Error:
> Failed to load resource: the server responded with a status of 404 (Not Found)

This looks like an application error, but locally the Rails application is working fine. In two environments - development and production.

Apparently the problem is that Rails application can not find anything in /app/public.

**Comment by josegonzalez** [comment]
Run the following command:

```
# replace APP with your application's name
dokku enter APP
```

That will enter the running application container at the `/app` location (or WORKDIR if you are deploying via `Dockerfile`). At that point, you can cd into the public directory and try to find your file.

**Comment by afuno** [comment]
@josegonzalez 
I'm using the .buildpacks file.
Is it very bad in this scenario?

**Comment by josegonzalez** [comment]
No, I didn't say that was bad, I just said that it would be a different base directory that `dokku enter` would drop you into.

I asked you to do something, can you do that? Please enter the container and see if the following path is valid:

```
# what is the output of the following commands when run within the container
ls -lah /app/public
ls -lah /app/public/uploads
ls -lah /app/public/uploads/image/file/76/47/96/36fa0c7964b6c498.jpg
```

**Comment by afuno** [comment]
@josegonzalez All files are present.

But why does not Rails see them?
The path to the /app/public directory is specified in the settings.
And as far as I understand there is no need to do anything in nginx?

I wrote above about two paths - local and server. Are they identical in essence?
From their root they lead to the desired directory...

**Comment by josegonzalez** [comment]
Can you show me the output of the commands as I asked?

**Comment by afuno** [comment]
@josegonzalez I apologize :(

**ls -lah /app/public:**

```
total 36K
drwxr-xr-x  5 herokuishuser herokuishuser 4.0K Sep 30 22:45 .
drwxr-xr-x 28 herokuishuser herokuishuser 4.0K Sep 30 22:45 ..
-rw-r--r--  1 herokuishuser herokuishuser 1.7K Sep 30 22:42 404.html
-rw-r--r--  1 herokuishuser herokuishuser 1.7K Sep 30 22:42 422.html
-rw-r--r--  1 herokuishuser herokuishuser 1.6K Sep 30 22:42 500.html
-rw-r--r--  1 herokuishuser herokuishuser    0 Sep 30 22:42 apple-touch-icon.png
-rw-r--r--  1 herokuishuser herokuishuser    0 Sep 30 22:42 apple-touch-icon-precomposed.png
drwxr-xr-x  9 herokuishuser herokuishuser 4.0K Sep 30 22:44 assets
-rw-r--r--  1 herokuishuser herokuishuser    0 Sep 30 22:42 favicon.ico
drwxr-xr-x  3 herokuishuser herokuishuser 4.0K Sep 30 22:44 packs
-rw-r--r--  1 herokuishuser herokuishuser   98 Sep 30 22:42 robots.txt
drwxr-xr-x  3 herokuishuser herokuishuser 4.0K Sep 30 22:46 uploads
```

**ls -lah /app/public/uploads**:

```
total 12K
drwxr-xr-x 3 herokuishuser herokuishuser 4.0K Sep 30 22:46 .
drwxr-xr-x 5 herokuishuser herokuishuser 4.0K Sep 30 22:45 ..
drwxr-xr-x 3 herokuishuser herokuishuser 4.0K Sep 30 22:46 image
```

**ls -lah /app/public/uploads/image/file/76/47/96/36fa0c7964b6c498.jpg**:

```
-rw-r--r-- 1 herokuishuser herokuishuser 144K Sep 30 22:47 /app/public/uploads/image/file/76/47/96/36fa0c7964b6c498.jpg
```

**Comment by josegonzalez** [comment]
This is definitely an application-error, not a Dokku issue. The files are written to the place we'd both expect and are readable by the rails process. if you're using the 12-factor gem, you might find [this](https://github.com/heroku/rails_12factor/issues/12) issue interesting.

Closing as there isn't anything we can do here. I would drop into some rails support channel to see if they have any further ideas.
