### ISSUE TITLE
Can't access website API endpoint on DO, all known checks clear

### ISSUE THREAD

**Issue by vfulco** [dokku/dokku#2925]
Description of problem:

Pushed sample Dockerfile (toy example) from R-Project's plumber package to DO droplet. Dockerfile exposes port 8000. Upon completion, says "deployed" and gives URL of the app previously set up on host.  Docker PS indicates image running, can ping FQDN remotely, checks of UFW, Nginx status and config file all pass.  Attempt to use API hangs on 'connecting', i.e. "basic.foo.foo/mean" or "basic.foo.foo:8000/mean?samples=10000" or Curl from remote.  Also tried to install SSL cert using let's encrypt plugin and error is "unreachable".

Output of the following commands

sudo dokku report
-----> uname: Linux weisisheng 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:            992         146         567           3         278         691
Swap:             0           0           0
-----> docker version: 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: foo
ID: IWBD:CG6G:FH2W:IZII:GDIU:6ZR4:7G7J:ANJD:NI4T:M2BO:QNC6:PSZB
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.32
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v168
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v77
  heroku-buildpack-python    v99
  heroku-buildpack-java      v53
  heroku-buildpack-gradle    v23
  heroku-buildpack-scala     v78
  heroku-buildpack-play      v26
  heroku-buildpack-php       v122
  heroku-buildpack-go        v72
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.10.4
-----> dokku plugins: 
plugn: 0.3.0
  00_dokku-standard    0.10.4 enabled    dokku core standard plugin
  20_events            0.10.4 enabled    dokku core events logging plugin
  apps                 0.10.4 enabled    dokku core apps plugin
  build-env            0.10.4 enabled    dokku core build-env plugin
  certs                0.10.4 enabled    dokku core certificate management plugin
  checks               0.10.4 enabled    dokku core checks plugin
  common               0.10.4 enabled    dokku core common plugin
  config               0.10.4 enabled    dokku core config plugin
  docker-options       0.10.4 enabled    dokku core docker-options plugin
  domains              0.10.4 enabled    dokku core domains plugin
  enter                0.10.4 enabled    dokku core enter plugin
  git                  0.10.4 enabled    dokku core git plugin
  http-auth            0.4.0 enabled    HTTP authentication for apps
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.10.4 enabled    dokku core logs plugin
  named-containers     0.10.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.10.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.10.4 enabled    dokku core plugin plugin
  proxy                0.10.4 enabled    dokku core proxy plugin
  ps                   0.10.4 enabled    dokku core ps plugin
  repo                 0.10.4 enabled    dokku core repo plugin
  shell                0.10.4 enabled    dokku core shell plugin
  ssh-keys             0.10.4 enabled    dokku core ssh-keys plugin
  storage              0.10.4 enabled    dokku core storage plugin
  tags                 0.10.4 enabled    dokku core tags plugin
  tar                  0.10.4 enabled    dokku core tar plugin

- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX)
: sudo docker inspect 30a
[
    {
        "Id": "30a3868123f53413008a6cacd33c345b812446b4d4610736a47898db4113fe7f",
        "Created": "2017-10-02T03:41:59.676055161Z",
        "Path": "R",
        "Args": [
            "-e",
            "pr <- plumber::plumb(commandArgs()[4]); pr$run(host='0.0.0.0', port=8000)",
            "/usr/local/lib/R/site-library/plumber/examples/04-mean-sum/plumber.R"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2124,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-10-02T04:19:55.040568755Z",
            "FinishedAt": "2017-10-02T04:19:29.683743949Z"
</snip for brevity purposes>

- `cat /home/dokku/basic/nginx.conf` (if applicable):
server {
  listen      [::]:8000;
  listen      8000;
  server_name basic.foo.foo; 
  access_log  /var/log/nginx/basic-access.log;
  error_log   /var/log/nginx/basic-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://basic-8000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/basic/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

}

upstream basic-8000 {

  server 172.17.0.2:8000;
}

- If a deploy is failing or behaving unexpectedly:
  - Application name == 'basic'
  - The type of application being deployed (node, php, python, ruby, etc.) R-project plumber API creator

  - If using a `Dockerfile`, the contents of that file:

cat Dockerfile
FROM rocker/r-base
MAINTAINER Jeff Allen <docker@trestletech.com>

RUN apt-get update -qq && apt-get install -y \
  git-core \
  libssl-dev \
  libcurl4-gnutls-dev

RUN R -e 'install.packages(c("devtools"))'

RUN R -e 'devtools::install_github("trestletech/plumber")'

EXPOSE 8000
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(commandArgs()[4]); pr$run(host='0.0.0.0', port=8000)"]
CMD ["/usr/local/lib/R/site-library/plumber/examples/04-mean-sum/plumber.R"]
##

Environment details (AWS, VirtualBox, physical, etc.):  DO droplet

How was Dokku installed?: One-Click image

How reproducible:
Followed standard dokku site instructions

Actual Results:
Can't reach API endpoint

Expected Results:
Numerical output of example code i.e. mean of x random variables.

Additional info:

ping basic.foo.foo
PING basic.foo.foo (188.166.212.49) 56(84) bytes of data.
64 bytes from foo.foo (188.166.212.49): icmp_seq=1 ttl=52 time=433 ms
64 bytes from foo.foo (188.166.212.49): icmp_seq=2 ttl=52 time=638 ms
64 bytes from .foo.foo (188.166.212.49): icmp_seq=3 ttl=52 time=432 ms

**Comment by josegonzalez** [comment]
What is the url you are trying to hit? Can you screenshot the error you are getting? 

What happens when - from that host - you do:

```
curl 172.17.0.2:8000
```

**Comment by vfulco** [comment]
URL: http://basic.weisisheng.asia/
The API endpoint for this toy example is: http://basic.weisisheng.asia:8000/mean which I believe re-routes to port 80. I have tried without giving a port and same result.

I am not getting an error per se, only 'connecting...' and it hangs.

Curl from the host raises a '404':

curl 172.17.0.2:8000
{"error":["404 - Resource Not Found"]}

BTW, thanks for the extraordinary response time and attention. I am kinda at the crossroads of noobville on docker, dokku, and the R plumber package.  The thing to do independently would be to enter the specific container and look through log files?  Otherwise I didn't see anything else indicating an issue.

**Comment by vfulco** [comment]
Ah, stop the presses.  My issue turned out to be I needed to manually proxy port from 8000 to 80 on dokku host, "dokku proxy:ports-add basic http:80:8000". I probably need to fix mapping in the original Dockerfile.  Answer was found here for anyone messing with dokku, DO, R's plumber package --> https://finbarrs.co/dokku/2017/08/05/deploy-express-app-with-dokku/

**Comment by josegonzalez** [comment]
Note: that is documented in our dockerfile deploy documentation [here](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/).
