### ISSUE TITLE
On Ubuntu `apt-get upgrade dokku` system overwrites /home/dokku/VHOST

### ISSUE THREAD

**Issue by silverfix** [dokku/dokku#2927]
On Ubuntu 16.04 `apt-get upgrade dokku` system command overwrites /home/dokku/VHOST so I need to re-do `dokku domains:set-global mydomain.tld`

**Comment by josegonzalez** [comment]
Ah I think what happens here is that we always overwrite this file. Should be relatively simple to just check if the file exists and has contents and do nothing [here](https://github.com/dokku/dokku/blob/master/debian/postinst#L103).
