### ISSUE TITLE
Dokku install fails w/ NIS automount because /home/dokku cannot be created

### ISSUE THREAD

**Issue by yulius-fxpal** [dokku/dokku#2930]
Description of problem:
Install on linux system w/ NIS automount /home fails because /home/dokku cannot be created.
Maybe move /home/dokku to be /var/lib/dokku or some other place other than /home?

Environment details (AWS, VirtualBox, physical, etc.):
physical

How was Dokku installed?:
apt-get install dokku

How reproducible:
100% if /home is not writeable because of automount

Steps to Reproduce:
1. Setup NIS to automount /home
2. apt-get install dokku

Actual Results:
dokku cannot be installed

Expected Results:
dokku can be installed

**Comment by josegonzalez** [comment]
What is NIS automount?

**Comment by yulius-fxpal** [comment]
It's a system to allow multiple machines user accounts to be managed from a central place.

Here are some docs.
https://help.ubuntu.com/community/SettingUpNISHowTo
https://help.ubuntu.com/community/Autofs

**Comment by josegonzalez** [comment]
We use the `dokku` user for quite a bit of stuff, so if the home directory for that user cannot be created, then what should the alternative be?

We could probably allow the user to specify - via debconf for debian at least - where the home directory should be - not `/var/lib/dokku`, since thats in use for other stuff - but I don't know that this is a solution.

**Comment by yulius-fxpal** [comment]
Sorry, I shouldn't have said /var/lib/dokku as an example of where to relocate /home/dokku.

I would just like to be able to specify where /home/dokku should be created like you mentioned.  Currently I install dokku and it fails.  I modify the post install scripts and replace /home/dokku with /dokku  and re-run the post install scripts.

All the linux machines are setup w/ NIS to allow multiple users in the organization to login and have their home directory mounted on it.   I would like some machines to have dokku installed because we have some services that are hand deployed and it makes running the services harder to document.

**Comment by josegonzalez** [comment]
A few things:

- [This](https://github.com/dokku/dokku/blob/master/rpm/dokku.postinst#L7) needs to be refactored to use sshcommand.
- sshcommand needs to be modified [here](https://github.com/dokku/sshcommand/blob/master/sshcommand#L57) and [here](https://github.com/dokku/sshcommand/blob/master/sshcommand#L104) to allow passing a home directory (probably as the third argument to `sshcommand create`).
- Maybe we can support `/etc/defaults/dokku` and let people specify `DOKKU_ROOT` there, which we can source in the deb and rpm post installation scripts.
- The [dokku bin](https://github.com/dokku/dokku/blob/master/dokku#L5) should source in the `/etc/defaults/dokku` file to support a custom `DOKKU_ROOT` path.

**Comment by yulius-fxpal** [comment]
Great.  I'll work on it and create a pull request when I'm' done.

**Comment by josegonzalez** [comment]
I'm going to close this. I don't have a system where I can replicate NIS automount.

While we can still do a bit more refactoring around how sshcommand is integrated with the rpm packaging - and sshcommand can be enhanced to add support for a custom home - I'm extremely unlikely to work on this further.

If you want to contribute patches to make this possible, please do so and I would be happy to review them.
