### ISSUE TITLE
Place apps on diffrent harddrives

### ISSUE THREAD

**Issue by chrismessiah** [dokku/dokku#2943]
My current setup has 2 harddrives, on which the first holds the OS, Dokku and all apps and the other being empty. I'm wondering if Dokku supports placing the app on custom locations,  something like `apps:create fooApp -l /some/path` would be super handy.

In general, is there any possibility to specify a custom location or move an existing app to another folder/drive?

**Comment by sman591** [comment]
I think you could achieve this by making a symlink for the `dokku` user's home directory (`/home/dokku/`) to wherever your second drive is mounted. This would also work for individual apps (symlink just the specific app's directory, `/home/dokku/app-name`). See:
* https://askubuntu.com/questions/465493/how-can-i-symlink-my-home-folder-from-another-drive
* https://superuser.com/questions/107208/linux-can-a-home-directory-be-symlinked

**Comment by chrismessiah** [comment]
Thanks! After creating the app it's just about copying the files, creating symbolic link and updating permissions 👍

**Comment by josegonzalez** [comment]
> PS: Important note is that apps:destroy doesn't remove the actual files under app-name so they has to be removed manually since only the symbolic link is being removed

Seems false. Can you provide a reproduction of this?

**Comment by chrismessiah** [comment]
Was able to reproduce it like this

```
dokku apps:create APP_NAME

// push some random hello world project 

dokku ps:stop APP_NAME
cp -R /home/dokku/APP_NAME /mount/VOLUME_NAME/path/APP_NAME/
rm -rf /home/dokku/APP_NAME
ln -s /mount/VOLUME_NAME/path/APP_NAME/ /home/dokku/APP_NAME
chown -R dokku:dokku /home/dokku/APP_NAME/
dokku ps:start APP_NAME

// project should now be working as usual

dokku apps:destroy APP_NAME
```

After running the last command the files are still available under `/mount/VOLUME_NAME/path/APP_NAME/`

**Comment by josegonzalez** [comment]
Mind redoing that but with the following line changed?

https://github.com/dokku/dokku/blob/master/plugins/apps/post-delete#L9

Change that to:

```
if [[ -n $APP ]]; then
  rm -rf "${DOKKU_ROOT:?}/$APP/" > /dev/null
  rm -rf "${DOKKU_ROOT:?}/$APP" > /dev/null
fi
```

And see if it removed the files? In this case, its because `rm -rf` doesn't remove what the symbolic link points to, so your hack ends up orphaning files in your mount directory.

**Comment by chrismessiah** [comment]
Awsome @josegonzalez, it removed the files! 👍
