### ISSUE TITLE
Some comments of main are same as other files in plugins/network/src/triggers/*/*.go

### ISSUE THREAD

**Issue by znz** [dokku/dokku#2946]
https://github.com/dokku/dokku/blob/9876b9e5884ac518b2d18b77ee8f538ba0a77de5/plugins/network/src/triggers/network-config-exists/network-config-exists.go#L11
same as main of network-get-ipaddr.go?

https://github.com/dokku/dokku/blob/9876b9e5884ac518b2d18b77ee8f538ba0a77de5/plugins/network/src/triggers/network-get-property/network-get-property.go#L12
same as main of network-get-port.go?

https://github.com/dokku/dokku/blob/9876b9e5884ac518b2d18b77ee8f538ba0a77de5/plugins/network/src/triggers/post-delete/post-delete.go#L9
same as main of network-get-port.go?

**Comment by josegonzalez** [comment]
Mind putting out a pr to fix them?
