### ISSUE TITLE
dokku apps shows git repo folders

### ISSUE THREAD

**Issue by leshik** [dokku/dokku#2948]
Hi,
After several upgrades during past year or two to the latest 0.10.5, my `dokku apps` command now lists git repo folders, such as branches, hooks, info, objects, and refs. I also found them containing DOCKER_OPTIONS_DEPLOY and ENV files. Deleted, but they are still shown when executing `dokku apps`. What can be done to resolve the issue?

**Comment by josegonzalez** [comment]
Can you run the following command:

```
dokku --trace apps
```

And gist the output?

**Comment by leshik** [comment]
@josegonzalez yes, here it is: https://gist.github.com/leshik/75ccbb2a820892d8e075cc01c1a18ae4 (I deleted my apps from the output).

**Comment by josegonzalez** [comment]
What is the output of:

```sh
find /home/dokku -follow -maxdepth 1 -mindepth 1 -type d '!' -name tls '!' -name '.*' -printf '%f\n'

ls -lah /home/dokku
```

Do not redact the output please.

**Comment by leshik** [comment]
find: https://gist.github.com/leshik/f0d2ae7b6ef8348fa07e78eb12b4e627
ls: https://gist.github.com/leshik/784e7c014cbd0a35c17b9e19f57cd0cd

> Do not redact the output please.

ok, I've just changed app names this time :)

**Comment by josegonzalez** [comment]
You'll notice you have a bunch of git-related files in `/home/dokku`. You almost certainly either:

- somehow created a git directory at the top-level
- moved a bunch of files from an app to top-level

You'll need to manually delete those files/folders.
