### ISSUE TITLE
vagrant up stalls due to NAT interface disabled

### ISSUE THREAD

**Issue by miraculixx** [dokku/dokku#2955]
**Problem**

`vagrant up` stalls connecting via ssh:

```
$ ~/projects/dokku$ vagrant up --provision
Bringing machine 'dokku' up with 'virtualbox' provider...
==> dokku: Importing base box 'bento/ubuntu-14.04'...
==> dokku: Matching MAC address for NAT networking...
==> dokku: Checking if box 'bento/ubuntu-14.04' is up to date...
==> dokku: Setting the name of the VM: dokku_dokku_1508783076111_56615
==> dokku: Clearing any previously set network interfaces...
==> dokku: Preparing network interfaces based on configuration...
    dokku: Adapter 1: nat
    dokku: Adapter 2: hostonly
==> dokku: Forwarding ports...
    dokku: 80 (guest) => 8080 (host) (adapter 1)
    dokku: 22 (guest) => 2222 (host) (adapter 1)
==> dokku: Running 'pre-boot' VM customizations...
==> dokku: Booting VM...
==> dokku: Waiting for machine to boot. This may take a few minutes...
    dokku: SSH address: 127.0.0.1:2222
    dokku: SSH username: vagrant
    dokku: SSH auth method: private key
```

This stalls endlessly and eventually fails unless the virtualbox NAT cable is set to "Cable connected"

![selection_778](https://user-images.githubusercontent.com/859611/31907641-b216e972-b834-11e7-9df2-cb5871b3593d.jpg)

**Resolution**

Update `Vagrantfile` to include

```
# enable NAT adapter cable https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838999
vm.vm.provider :virtualbox do |vb|
  vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
end
```

**Environment**

dokku 0581b38adfb4ff56ba704243185a8c06ccfae2b7
vboxmanage 4.3.36_Ubuntur105129
Vagrant 2.0.0
Linux Mint 17 Qiana

**Comment by josegonzalez** [comment]
@miraculixx Seems like you're using a pretty ancient version of virtualbox - current stable is 5.2, and this box might not be compatible with versions older than 5.0.

We can patch over the issue, but I'm not going to merge this in without a pull request as it's clear to me that its an upstream problem and you should also upgrade your software.

**Comment by miraculixx** [comment]
@josegonzalez thank you. Indead I can confirm that upgrading virtualbox to 5.x resolves this issue. Note however that Virtualbox 4.3 is the most recent version supported on Linux Mint 17 Qiana, which is an LTS version [supported until April 2019](https://linuxmint.com/download_all.php). Created a PR.
