### ISSUE TITLE
env variables with asterisks

### ISSUE THREAD

**Issue by martunta** [dokku/dokku#2959]
if you set env variable like this VAR="* * *", second and sub sequential asterisks are expanded into list of files in current directory. 

Maybe it is not a dokku fault, but rather operating systems (Ubuntu 16.04), but overall it is odd. I will need to rework my application to avoid putting this in env variable as it seems to be impossible.

**Comment by josegonzalez** [comment]
@alexquick is this an issue with your new changeset or no? My gut says no, but potentially still is.

**Comment by alexquick** [comment]
@josegonzalez I tried this with master and can't seem to recreate it.

@martunta, do you see the expansion immediately when setting it or just when accessing it in your application? Does `dokku config:get APP VAR` output "* * *" or the incorrect version?

**Comment by martunta** [comment]
I see expansion when accessing it. I have version 0.10.5

interesting that if there is three asterisks, then only second and third are expanded, not the first one

**Comment by josegonzalez** [comment]
We're going to release a 0.11.0 this weekend, so if you can upgrade to that and see if it repros, that will be great.

**Comment by josegonzalez** [comment]
@martunta can you try upgrading to v0.11.0 and  seeing if you still have this issue?

**Comment by martunta** [comment]
fixed now!
