### ISSUE TITLE
Images not deleting themselves after commit?

### ISSUE THREAD

**Issue by wootwoot1234** [dokku/dokku#2961]
Looks like some of my images aren't being deleted after new ones are created.  These images should not be running:

    IMAGE
    c01ff664e4f2
    462be243b092
    7bd9848f47a9

How can I manually delete these images?

Here's a what I see when I run `docker ps`:

    root@dokku:~# docker ps
    CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS              PORTS                   NAMES
    2fc9c9cd377f        dokku/EEEEEEEEEEEEEE:latest                          "/start worker"          38 minutes ago      Up 38 minutes                               EEEEEEEEEEEEEE.worker.1
    1d503036e0d1        dokku/EEEEEEEEEEEEEE:latest                          "/start web"             38 minutes ago      Up 38 minutes                               EEEEEEEEEEEEEE.web.1
    b111490a11c3        c01ff664e4f2                                         "/start worker"          3 days ago          Up 7 hours                                  EEEEEEEEEEEEEE.worker.1.1509316706
    a51532571615        c01ff664e4f2                                         "/start web"             3 days ago          Up 7 hours                                  EEEEEEEEEEEEEE.web.1.1509316706
    03c5be3ee4c2        dokku/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA:latest        "/start web"             5 days ago          Up 7 hours                                  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.web.1
    31e3abc7024c        462be243b092                                         "/start web"             13 days ago         Up 7 hours                                  EEEEEEEEEEEEEE.web.1.1508450973
    38176a1f847c        dokku/BBBBBBBBBBBBBBBBBBBBBBB:latest                 "/start web"             3 weeks ago         Up 7 hours                                  BBBBBBBBBBBBBBBBBBBBBBB.web.1
    c1c70592e7b3        dokku/php-sandbox:latest                             "/start web"             4 weeks ago         Up 7 hours                                  php-sandbox.web.1
    d319211ab10b        mysql:5.7.12                                         "docker-entrypoint..."   4 weeks ago         Up 7 hours          3306/tcp                dokku.mysql.php-sandbox-mysql
    ee865bca8e7b        mysql:5.7.12                                         "docker-entrypoint..."   4 weeks ago         Up 7 hours          3306/tcp                dokku.mysql.BBBBBBBBBBBBBBBBBBBBBBB-mysql
    a61b8ac3ee1e        dokku/DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD:latest   "/start web"             5 weeks ago         Up 7 hours                                  DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.web.1
    2ffd2af6e96b        dokku/CCCCCCCCCCCCCCCCC:latest                       "/start web"             5 weeks ago         Up 7 hours                                  CCCCCCCCCCCCCCCCC.web.1
    5ea0b143ccb7        7bd9848f47a9                                         "/start web"             5 weeks ago         Up 7 hours                                  DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.web.1.1506530985
    db255ad46a00        mysql:5.7.12                                         "docker-entrypoint..."   5 weeks ago         Up 7 hours          3306/tcp                dokku.mysql.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-mysql
    aa325d0ed4e7        mysql:5.7.12                                         "docker-entrypoint..."   5 weeks ago         Up 7 hours          3306/tcp                dokku.mysql.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD-mysql
    0adb621de781        mysql:5.7.12                                         "docker-entrypoint..."   5 weeks ago         Up 7 hours          3306/tcp                dokku.mysql.CCCCCCCCCCCCCCCCC-mysql
    9cf89a4d7c84        gliderlabs/logspout:v3.1                             "/bin/logspout sys..."   6 weeks ago         Up 7 hours          127.0.0.1:514->80/tcp   logspout

and `dokku report`:

    root@dokku:~# dokku report
    -----> uname: Linux dokku 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    -----> memory:
                  total        used        free      shared  buff/cache   available
    Mem:            488         356          13           1         118          76
    Swap:           999         656         343
    -----> docker version:
    Client:
     Version:      17.05.0-ce
     API version:  1.29
     Go version:   go1.7.5
     Git commit:   89658be
     Built:        Thu May  4 22:10:54 2017
     OS/Arch:      linux/amd64

    Server:
     Version:      17.05.0-ce
     API version:  1.29 (minimum version 1.12)
     Go version:   go1.7.5
     Git commit:   89658be
     Built:        Thu May  4 22:10:54 2017
     OS/Arch:      linux/amd64
     Experimental: false
    -----> docker daemon info:
    Containers: 17
     Running: 17
     Paused: 0
     Stopped: 0
    Images: 73
    Server Version: 17.05.0-ce
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 151
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: bridge host macvlan null overlay
    Swarm: inactive
    Runtimes: runc
    Default Runtime: runc
    Init Binary: docker-init
    containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
    runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
    init version: 949e6fa
    Security Options:
     apparmor
     seccomp
      Profile: default
    Kernel Version: 4.4.0-98-generic
    Operating System: Ubuntu 16.04.2 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 1
    Total Memory: 488.3MiB
    Name: dokku-512mb-sfo2-01
    ID: TZHQ:BCCQ:63HI:WPXL:MJAJ:K5MX:YVSH:QYSZ:GSPV:FS37:RRON:LCSF
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): true
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    Experimental: false
    Insecure Registries:
     127.0.0.0/8
    Live Restore Enabled: false

    -----> sigil version: 0.4.0
    -----> herokuish version:
    herokuish: 0.3.29
    buildpacks:
      heroku-buildpack-multi     v1.0.0
      heroku-buildpack-ruby      v159
      heroku-buildpack-nodejs    v99
      heroku-buildpack-clojure   v76
      heroku-buildpack-python    v99
      heroku-buildpack-java      v51
      heroku-buildpack-gradle    v21
      heroku-buildpack-grails    v21
      heroku-buildpack-scala     v76
      heroku-buildpack-play      v26
      heroku-buildpack-php       v121
      heroku-buildpack-go        v64
      heroku-buildpack-erlang    fa17af9
      buildpack-nginx            v8
    -----> dokku version: 0.9.4
    -----> dokku plugins:
     !     Deprecated: Please use plugin:list
    plugn: 0.3.0
      00_dokku-standard    0.9.4 enabled    dokku core standard plugin
      20_events            0.9.4 enabled    dokku core events logging plugin
      apps                 0.9.4 enabled    dokku core apps plugin
      build-env            0.9.4 enabled    dokku core build-env plugin
      certs                0.9.4 enabled    dokku core certificate management plugin
      checks               0.9.4 enabled    dokku core checks plugin
      common               0.9.4 enabled    dokku core common plugin
      config               0.9.4 enabled    dokku core config plugin
      docker-options       0.9.4 enabled    dokku core docker-options plugin
      domains              0.9.4 enabled    dokku core domains plugin
      enter                0.9.4 enabled    dokku core enter plugin
      git                  0.9.4 enabled    dokku core git plugin
      hostname             0.2.0 enabled    Sets the docker hostname option for dokku
      letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
      logs                 0.9.4 enabled    dokku core logs plugin
      logspout             0.3.0 enabled    sends dokku app stdout to a logging service
      mongo                1.0.0 enabled    dokku mongo service plugin
      mysql                1.0.0 enabled    dokku mysql service plugin
      named-containers     0.9.4 enabled    dokku core named containers plugin
      nginx-vhosts         0.9.4 enabled    dokku core nginx-vhosts plugin
      plugin               0.9.4 enabled    dokku core plugin plugin
      proxy                0.9.4 enabled    dokku core proxy plugin
      ps                   0.9.4 enabled    dokku core ps plugin
      repo                 0.9.4 enabled    dokku core repo plugin
      shell                0.9.4 enabled    dokku core shell plugin
      ssh-keys             0.9.4 enabled    dokku core ssh-keys plugin
      storage              0.9.4 enabled    dokku core storage plugin
      tags                 0.9.4 enabled    dokku core tags plugin
      tar                  0.9.4 enabled    dokku core tar plugin

**Comment by josegonzalez** [comment]
On a deploy, we keep the old containers around for ~2 minutes. This is so connections have time to finish and you get a zero downtime deploy.

We also re-use the `latest` tag for the new image, so the old image will get untagged.

These old containers get stopped after two minutes, and we also remove old images etc. on every deploy. You can manually call `dokku cleanup` to remove them, but as it uses a layered filesystem, you should be fine.

**Comment by wootwoot1234** [comment]
Hey @josegonzalez.  Thanks for the help.  It's been more than two minutes and they are still up.  I tried `dokku cleanup` and they are still there.  I even restarted the server and they are still there...  Is there anything else I can check?

**Comment by josegonzalez** [comment]
Can you `docker inspect` the containers and show me the output?

**Comment by wootwoot1234** [comment]
root@dokku:~# docker inspect
    "docker inspect" requires at least 1 argument(s).
    See 'docker inspect --help'.

    Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

    Return low-level information on Docker objects

**Comment by wootwoot1234** [comment]
I did a server restart and now none of my containers are running.  I'm not sure what's going on.  Maybe I shouldn't have restarted the server.

**Comment by josegonzalez** [comment]
`docker inspect CONTAINER_ID` is how you use that.

Re your containers not running, I would check `docker ps -a`, and view the dokku/docker logs. Not much I can do there, but you can rebuild everything by doing `dokku SERVICE:start SERVICE_NAME` and then `dokku ps:rebuildall`.

**Comment by wootwoot1234** [comment]
Sorry to ask this, I'm sure it's a dumb question, but what do I put in place of `SERVICE` and `SERVICE_NAME`

**Comment by wootwoot1234** [comment]
For others that come across this. Running `docker stop 5ea0b143ccb7` where `5ea0b143ccb7` is the `CONTAINER ID` for all the apps that had a random number after them like `EEEEEEEEEEEEEE.worker.1.1509316706` will stop them.  

It sounds like this is a bug that will be fixed with the next build (0.10.6?) and typically these containers should automagically close themselves about 2 minutes after the new ones are created. 

@josegonzalez once again, thanks for the help.  You're a lifesaver!

**Comment by josegonzalez** [comment]
Stuff like `mysql:start` and the service being deployed, in cases where you have a datastore plugins enabled.

**Comment by seospace** [comment]
Ive deleted my app but there are still 3 containers running for that app, is that a normal behaviour?
dokku cleanup does not help

**Comment by josegonzalez** [comment]
Please do not comment on months old issues that have been closed. If you are having an problem, please open a new issue and provide all the data we ask for. Thanks!
