### ISSUE TITLE
Portainer + Dokku (securely exposing Docker daemon over TCP)

### ISSUE THREAD

**Issue by woudsma** [dokku/dokku#2962]
Not really an issue, sorry. Please close if necessary.
I did a quick write-up of the steps on how to setup a Dokku host as remote to [Portainer](https://github.com/portainer/portainer).
It comes down to exposing the Docker daemon over TCP, issuing client/server certificates to enable TLS secured requests *while still making the Docker socket available to Dokku*.

See: https://gist.github.com/woudsma/03c69260715327ee8453f73b121f416c

Please let me know if there are issues. Happy coding!

**Comment by josegonzalez** [comment]
Thanks for the writeup! We'll see what we can do to add this to our docs.

**Comment by josegonzalez** [comment]
It's actually not clear to me that this particular thing belongs in our docs. If you'd like to submit this as a pull request to our [blog](https://github.com/dokku/dokku.github.io/), that would be great.

Thanks for your contribution nonetheless, and apologies on the late reply here.
