### ISSUE TITLE
Add instructions for deployment using Gitlab CI

### ISSUE THREAD

**Issue by buckle2000** [dokku/dokku#2975]
I wrote [this tutorial for using Gitlab with Dokku](https://gist.github.com/buckle2000/935db75bb1767d63cae3e48730bbc52d) but I don't know where to put it in the docs.

**Comment by skorokithakis** [comment]
By the way, can you add the port there? Ilya has changed his image so it now supports `hostname:port/`, which might be helpful to add to the example.
