### ISSUE TITLE
app.json predeploy command doesn't seem to run

### ISSUE THREAD

**Issue by ianschillebeeckx** [dokku/dokku#2977]
**Description of problem:**
Hi, I'm trying to run a pre-deployment command. Eventually, i want to set permissions of a directory so that i can setup a rotating log in my container for my django app. I couldn't get those permissions to be set, nor any command, even a touch. 

**Dokku Report:**

-----> uname: Linux ip-10-0-0-101 3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
             total       used       free     shared    buffers     cached
Mem:          3764       3527        237         68        457       2263
-/+ buffers/cache:        807       2957
Swap:            0          0          0
-----> docker version: 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:17:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:17:31 2017
 OS/Arch:      linux/amd64
 Experimental: true
-----> docker daemon info: 
Containers: 13
 Running: 5
 Paused: 0
 Stopped: 8
Images: 32
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-119-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.676GiB
Name: ip-10-0-0-101
ID: UXLV:ZVFF:MEBI:JJKF:WVWC:4TPZ:ZBYA:N456:XRM5:E7PX:DOJ5:N4LT
Docker Root Dir: /data/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.33
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v170
  heroku-buildpack-nodejs    v111
  heroku-buildpack-clojure   v77
  heroku-buildpack-python    v120
  heroku-buildpack-java      v57
  heroku-buildpack-gradle    v24
  heroku-buildpack-scala     v79
  heroku-buildpack-play      v26
  heroku-buildpack-php       v126
  heroku-buildpack-go        v78
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.10.4
-----> dokku plugins: 
plugn: 0.3.0
  00_dokku-standard    0.10.4 enabled    dokku core standard plugin
  20_events            0.10.4 enabled    dokku core events logging plugin
  apps                 0.10.4 enabled    dokku core apps plugin
  build-env            0.10.4 enabled    dokku core build-env plugin
  certs                0.10.4 enabled    dokku core certificate management plugin
  checks               0.10.4 enabled    dokku core checks plugin
  common               0.10.4 enabled    dokku core common plugin
  config               0.10.4 enabled    dokku core config plugin
  docker-options       0.10.4 enabled    dokku core docker-options plugin
  domains              0.10.4 enabled    dokku core domains plugin
  enter                0.10.4 enabled    dokku core enter plugin
  git                  0.10.4 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.10.4 enabled    dokku core logs plugin
  maintenance          0.4.0 enabled    Maintenance mode for apps
  memcached            1.0.0 enabled    dokku memcached service plugin
  named-containers     0.10.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.10.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.10.4 enabled    dokku core plugin plugin
  proxy                0.10.4 enabled    dokku core proxy plugin
  ps                   0.10.4 enabled    dokku core ps plugin
  redirect             0.5.0 enabled    Simple redirects for apps
  redis                1.0.0 enabled    dokku redis service plugin
  repo                 0.10.4 enabled    dokku core repo plugin
  shell                0.10.4 enabled    dokku core shell plugin
  ssh-keys             0.10.4 enabled    dokku core ssh-keys plugin
  storage              0.10.4 enabled    dokku core storage plugin
  tags                 0.10.4 enabled    dokku core tags plugin
  tar                  0.10.4 enabled    dokku core tar plugin

**Environment details (AWS, VirtualBox, physical, etc.):**
I'm actually using a hipaa compliant host which is using AWS i believe.

**How was Dokku installed?:**
Not sure.

**Steps to Reproduce:**
My app.json is in the root directory and its contents is:
{
  "scripts": {
    "dokku": {
      "predeploy": "touch /app/predeploy.test",
      "postdeploy": "touch /app/postdeploy.test",
    }
  }
}

**Actual Results:**
At deployment, it's unclear if the app.json is executing:
-----> Cleaning up...
-----> Building w4c from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Python app detected
       !     The latest version of Python 3 is python-3.6.2 (you are using python-3.6.1, which is unsupported).
       !     We recommend upgrading by specifying the latest version (python-3.6.2).
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing requirements with pip
       
-----> $ python manage.py collectstatic --noinput
       68 static files copied to '/tmp/build/static'.
       
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing w4c (dokku/w4c:latest)...
-----> Deploying w4c (dokku/w4c:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> App Procfile file found (/home/dokku/w4c/DOKKU_PROCFILE)
-----> DOKKU_SCALE file found (/home/dokku/w4c/DOKKU_SCALE)
=====> web=1

There is no predeploy.test file in /app 

**Expected Results:**

A predeploy.test file in /app

**Comment by josegonzalez** [comment]
Your json file isn't valid, and has a trailing comma on the `postdeploy` script. You can use [jsonlint](https://jsonlint.com/) to validate your file.

**Comment by ianschillebeeckx** [comment]
err. sorry it was trivial. thank you for catching it!
