### ISSUE TITLE
Publicly exposing Redis/Mysql

### ISSUE THREAD

**Issue by XuryaX** [dokku/dokku#2986]
This is not an issue, but I couldnt find anywhere else where I can ask this.

I am running dokku on 2 instances and load balancing between them. Works good. 
For larger apps I am using Amazon RDS for Database . But for the smaller apps which I am just testing out, I want to use dokku redis or mysql or postgre, but if i create a redis instance on both hosts, then there would be data inconsistency. And I am not sure if I can expose my redis publicly. If that is possible it would be great. This is something that was on Flynn, is it also possible in Dokku?

**Comment by josegonzalez** [comment]
Please see the help output for the particular plugins you are using. In particular:

```
# mysql
dokku mysql:help expose

# redis
dokku redis:help expose
```
