### ISSUE TITLE
config:set removes most of the ENV file rows when variable name isn't specified, just the value

### ISSUE THREAD

**Issue by ypadlyak** [dokku/dokku#2990]
Description of problem:

config:set removes most of the ENV file rows in some cases

Output of the following commands

-----> uname: Linux ip-10-0-0-77 3.13.0-110-generic #157-Ubuntu SMP Mon Feb 20 11:54:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
             total       used       free     shared    buffers     cached
Mem:          3951       3125        826         60         99        269
-/+ buffers/cache:       2756       1195
Swap:            0          0          0
-----> docker version: 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 96
 Running: 16
 Paused: 0
 Stopped: 80
Images: 240
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 560
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-110-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: ip-10-0-0-77
ID: TP62:4U7B:4762:K2KQ:XYLJ:KQAS:5EJN:DL4H:ZXF3:YDUG:R5BE:SMPI
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.32
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v168
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v77
  heroku-buildpack-python    v99
  heroku-buildpack-java      v53
  heroku-buildpack-gradle    v23
  heroku-buildpack-scala     v78
  heroku-buildpack-play      v26
  heroku-buildpack-php       v122
  heroku-buildpack-go        v72
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.10.4
-----> dokku plugins: 
plugn: 0.3.0
  00_dokku-standard    0.10.4 enabled    dokku core standard plugin
  20_events            0.10.4 enabled    dokku core events logging plugin
  apps                 0.10.4 enabled    dokku core apps plugin
  build-env            0.10.4 enabled    dokku core build-env plugin
  certs                0.10.4 enabled    dokku core certificate management plugin
  checks               0.10.4 enabled    dokku core checks plugin
  common               0.10.4 enabled    dokku core common plugin
  config               0.10.4 enabled    dokku core config plugin
  deployment-keys      0.1.0 enabled    Manage SSH deployment keys that should get injected into your containers on-build
  docker-options       0.10.4 enabled    dokku core docker-options plugin
  domains              0.10.4 enabled    dokku core domains plugin
  enter                0.10.4 enabled    dokku core enter plugin
  git                  0.10.4 enabled    dokku core git plugin
  hostkeys-plugin      0.1.0 enabled    Manage hostkeys (.ssh/known_hosts) in your container environment
  hostname             0.2.0 enabled    Sets the docker hostname option for dokku
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.10.4 enabled    dokku core logs plugin
  logspout             0.2.0 enabled    sends dokku app stdout to a logging service
  maintenance          0.4.0 enabled    Maintenance mode for apps
  mysql                1.0.0 enabled    dokku mysql service plugin
  named-containers     0.10.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.10.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.10.4 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.10.4 enabled    dokku core proxy plugin
  ps                   0.10.4 enabled    dokku core ps plugin
  repo                 0.10.4 enabled    dokku core repo plugin
  shell                0.10.4 enabled    dokku core shell plugin
  ssh-keys             0.10.4 enabled    dokku core ssh-keys plugin
  storage              0.10.4 enabled    dokku core storage plugin
  tags                 0.10.4 enabled    dokku core tags plugin
  tar                  0.10.4 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):
AWS

How was Dokku installed?:
deb package
How reproducible:

Steps to Reproduce:
1. create dummy app and add some ENV variables with `dokku config:set`
2. try adding one more, but this time do not specify variiable name and `=`, e.g
dokku config:set postgresql://postgres:postgres@example.com:5432/dbname?pool=25

Actual Results:
unexpectedly some ENV file lines are removed

Expected Results:

new variable is added

Additional info:

**Comment by josegonzalez** [comment]
I dont see a `key` in that env var you are setting, though we shouldnt be deleting everything. Can you see if this is reproducible using an installation of master from source?

**Comment by ypadlyak** [comment]
That is the point, I forgot to specify the `KEY=` and got ENV file almost emptied( I may be able to upgrade to the latest .deb version and try to reproduce, but not to master

**Comment by josegonzalez** [comment]
Can you use the vagrant setup to see if you can replicate this locally with latest master?

**Comment by josegonzalez** [comment]
@ypadlyak can you upgrade to v0.11.0 and see if this issue is fixed?

**Comment by josegonzalez** [comment]
This was confirmed working as desired in v0.11.0.
