### ISSUE TITLE
App as backend service

### ISSUE THREAD

**Issue by rvillablanca** [dokku/dokku#2992]
Hi, 

I don't know if stackoverflow was the right place to ask the question about deploy apps as backend service, so I leave the question [here](https://stackoverflow.com/questions/47572665/dokku-apps-as-backend-service).
In brief, We need to deplo two apps using a common rest service so we would like to deploy the three apps on our Dokku platform but common service must not be exposed.

I think this could be achieved disabling proxy for this service with `dokku proxy:disable shared-service`, but could other apps see this service then ?

**Comment by josegonzalez** [comment]
Thats not currently possible. Why not use a proxy but set a domain that doesnt have DNS pointing at your server for?

**Comment by rvillablanca** [comment]
Maybe I could remove the proxy and connect through private docker ip, so app1 and app2 can see the backend service. Your advice will work but we would like to avoid expose across internet so, I will try it with internal docker ip.

Do you think is possible to have plugins features on apps, maybe in a future ? For example, some app can link to another app in the same way as plugins.

Thanks for the support @josegonzalez
