### ISSUE TITLE
Installer should be able to deal with a stopped nginx

### ISSUE THREAD

**Issue by ilkka** [dokku/dokku#3019]
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

Description of problem:

If nginx is installed but stopped with e.g. `systemctl stop nginx`, installation will fail with messages about being unable to reload nginx due to it being inactive. The installer should proceed regardless but instead it exits with an error.

Output of the following commands

-----> uname: Linux XXXXXXXX 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
              total        used        free      shared  buff/cache   available
Mem:           3934         192         619          21        3122        3381
Swap:          4091           0        4091
-----> docker version:
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:37:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info:
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.842GiB
Name: XXXXXXXX
ID: RKWE:YMK5:4ZAC:RMQR:XHSW:JD2W:F7ZU:NR2B:7VXZ:3PQJ:RUHX:A52V
Docker Root Dir: /data/docker
Debug Mode (client): true
Debug Mode (server): false
HTTP Proxy: XXXXXXXX
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version:
herokuish: 0.3.33
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v170
  heroku-buildpack-nodejs    v111
  heroku-buildpack-clojure   v77
  heroku-buildpack-python    v120
  heroku-buildpack-java      v57
  heroku-buildpack-gradle    v24
  heroku-buildpack-scala     v79
  heroku-buildpack-play      v26
  heroku-buildpack-php       v126
  heroku-buildpack-go        v78
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.11.2
-----> dokku plugins:
plugn: 0.3.0
  00_dokku-standard    0.11.2 enabled    dokku core standard plugin
  20_events            0.11.2 enabled    dokku core events logging plugin
  apps                 0.11.2 enabled    dokku core apps plugin
  build-env            0.11.2 enabled    dokku core build-env plugin
  certs                0.11.2 enabled    dokku core certificate management plugin
  checks               0.11.2 enabled    dokku core checks plugin
  common               0.11.2 enabled    dokku core common plugin
  config               0.11.2 enabled    dokku core config plugin
  docker-options       0.11.2 enabled    dokku core docker-options plugin
  domains              0.11.2 enabled    dokku core domains plugin
  enter                0.11.2 enabled    dokku core enter plugin
  git                  0.11.2 enabled    dokku core git plugin
  logs                 0.11.2 enabled    dokku core logs plugin
  named-containers     0.11.2 enabled    dokku core named containers plugin
  network              0.11.2 enabled    dokku core network plugin
  nginx-vhosts         0.11.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.11.2 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.11.2 enabled    dokku core proxy plugin
  ps                   0.11.2 enabled    dokku core ps plugin
  repo                 0.11.2 enabled    dokku core repo plugin
  shell                0.11.2 enabled    dokku core shell plugin
  ssh-keys             0.11.2 enabled    dokku core ssh-keys plugin
  storage              0.11.2 enabled    dokku core storage plugin
  tags                 0.11.2 enabled    dokku core tags plugin
  tar                  0.11.2 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):

Unknown VM.

How was Dokku installed?:

Using `bootstrap.sh`

How reproducible:

Always

Steps to Reproduce:
1. Install nginx
2. `systemctl stop nginx`
3. Install dokku

Actual Results:

Installation fails due to failure to reload nginx config.

Expected Results:

Installation should proceed without starting nginx.

Additional info:

**Comment by josegonzalez** [comment]
I'd actually like to get rid of the installer in favor of #2247.

**Comment by josegonzalez** [comment]
Closing as there is a pull request up.
