### ISSUE TITLE
Dockerfile apps don't work with Virtualhost config

### ISSUE THREAD

**Issue by AndyBarron** [dokku/dokku#3026]
# Overview of issue

When pushing a Dockerfile app to a fresh Dokku server with Virtualhost URLs enabled, the app only listens on that app's specified port. (Running `netstat -tuplen` confirms that nothing is listening on port 80.)

This may well be intended behavior, but if so, it should be documented. (Also, it should totally be a feature, because Dockerfile deploys rock!)

# Output from `dokku report`

```
-----> uname: Linux dokku-1 3.13.0-137-generic #186-Ubuntu SMP Mon Dec 4 19:09:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
             total       used       free     shared    buffers     cached
Mem:          2001       1827        174          0        141       1323
-/+ buffers/cache:        362       1638
Swap:            0          0          0
-----> docker version:
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:36 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:12 2017
  OS/Arch:	linux/amd64
  Experimental:	false
-----> docker daemon info:
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 19
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-137-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955GiB
Name: dokku-1
ID: FFHS:ZYU2:L23U:XU3V:ANDX:HMPJ:EBWQ:OPC2:ZTDO:TXOO:4QNB:T45M
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version:
herokuish: 0.3.33
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v170
  heroku-buildpack-nodejs    v111
  heroku-buildpack-clojure   v77
  heroku-buildpack-python    v120
  heroku-buildpack-java      v57
  heroku-buildpack-gradle    v24
  heroku-buildpack-scala     v79
  heroku-buildpack-play      v26
  heroku-buildpack-php       v126
  heroku-buildpack-go        v78
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.11.2
-----> dokku plugins:
plugn: 0.3.0
  00_dokku-standard    0.11.2 enabled    dokku core standard plugin
  20_events            0.11.2 enabled    dokku core events logging plugin
  apps                 0.11.2 enabled    dokku core apps plugin
  build-env            0.11.2 enabled    dokku core build-env plugin
  certs                0.11.2 enabled    dokku core certificate management plugin
  checks               0.11.2 enabled    dokku core checks plugin
  common               0.11.2 enabled    dokku core common plugin
  config               0.11.2 enabled    dokku core config plugin
  docker-options       0.11.2 enabled    dokku core docker-options plugin
  domains              0.11.2 enabled    dokku core domains plugin
  enter                0.11.2 enabled    dokku core enter plugin
  git                  0.11.2 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.11.2 enabled    dokku core logs plugin
  named-containers     0.11.2 enabled    dokku core named containers plugin
  network              0.11.2 enabled    dokku core network plugin
  nginx-vhosts         0.11.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.11.2 enabled    dokku core plugin plugin
  proxy                0.11.2 enabled    dokku core proxy plugin
  ps                   0.11.2 enabled    dokku core ps plugin
  repo                 0.11.2 enabled    dokku core repo plugin
  shell                0.11.2 enabled    dokku core shell plugin
  ssh-keys             0.11.2 enabled    dokku core ssh-keys plugin
  storage              0.11.2 enabled    dokku core storage plugin
  tags                 0.11.2 enabled    dokku core tags plugin
  tar                  0.11.2 enabled    dokku core tar plugin
```

# Description & repro

Environment details (AWS, VirtualBox, physical, etc.):
DigitalOcean (tried Dokku preset and Ubuntu 16.04/14.04 with Dokku installed manually)

How was Dokku installed?:
See above

How reproducible:
Every time

Steps to Reproduce:
1. Set up fresh Dokku install with Virtualhost enabled
2. Push a new app that uses a `Dockerfile` with a single `EXPOSE` port directive
3. Ping the new app's subdomain and running `netstat -tuplen`

Actual Results:
Server refuses connections; nothing listening on port 80

Expected Results:
Server displays app on subdomain and nginx is listening on port 80

**Comment by josegonzalez** [comment]
When you enable virtualhosts and do not bind to all interfaces, your application listens on an internal `docker0` network. This will assign a random IP to your application.

We'll also respect whatever your `EXPOSE` directive is if you have one. If you _do not_  have one, then we'll listen on the internal ip and port 5000, proxying that to the frontend on port 80.

This is documented in our Dockerfile deploy docs [here](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/#exposed-ports). We ended up on this behavior because many of our users were confused as to why we'd ignore their expose directive and assumed it would use that port *publicly*.

If you want things to _just work_, you'll need to drop the `EXPOSE` env var (and also probably remove all the `DOKKU_` config env vars, since we try not fuck with any settings if its unclear they should be changed or not). Otherwise, you're stuck with manually configuring ports via our [proxy plugin](http://dokku.viewdocs.io/dokku/networking/proxy-management/#proxy-port-mapping).

Let me know if that fills in the gaps in how dokku works.

**Comment by josegonzalez** [comment]
Closing as there were no further follow-up questions.

**Comment by victorkane** [comment]
Hi, I have the same problem on DigitalOcean one-click Dokku install (0.9.4). I read all the documentation you are referring to, but am not clear on what to do. My app (name: staging) Dockerfile has EXPOSE on port 5045 (the same port my node.js app is running), so http://staging.example.com:5045 WORKS. But http://staging.example.com gets ERR_CONNECTION_REFUSED.

```
dokku proxy:report
=====> staging proxy information
       Proxy enabled:       true
       Proxy type:          nginx
       Proxy port map:      http:5045:5045
```

Should I do a `dokku proxy:ports-add staging http:80:5045`?

Normally, without dokku/docker I would do an nginx proxy from 5045 directly to 80 on subdomain staging.linguathon.com.

Can someone help please?

**Comment by josegonzalez** [comment]
@victorkane that's exactly what you need to run (or proxy:ports-set).

**Comment by AndyBarron** [comment]
Alternatively, don't use EXPOSE at all, and have your app simply read from
the PORT environment variable. That will work with virtualhost without
requiring you to add ports manually.

**Comment by victorkane** [comment]
Thanks everyone, love using Dokku!
