### ISSUE TITLE
Dokku Apps Suddenly Down

### ISSUE THREAD

**Issue by XuryaX** [dokku/dokku#3029]
I have had deployed multiple microapps on dokku. 
I was trying to install https://github.com/Matterwiki/Matterwiki
After I installed, with a few modifications, other apps stopped working.
I installed Matterwiki on http://wiki.xoxzo.tech/
Another app installed at http://mockbin.xoxzo.com/ stopped working.
Now I deleted wiki.xoxzo.tech but the other apps are still down, although if I visit wiki.xoxzo.tech , it shows the mockbin app ( most probably it is chosen as default routing now.)

When I run nginx:error-logs mockbin.xoxzo.com

`2018/01/10 08:16:06 [error] 30987#30987: *352 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.20.107, server: mockbin.xoxzo.com, request: "GET / HTTP/1.1", upstream: "http://172.17.0.12:5000/", host: "mockbin.xoxzo.com"`

Dockerfile for  `Matterwiki`
`FROM node:9

RUN mkdir -p /server
WORKDIR /server

COPY package.json /server/

RUN npm install
COPY .babelrc ./
COPY db/ ./db
COPY *.js ./
COPY models/ ./models
COPY migrations/ ./migrations
COPY client/ ./client
COPY api/ ./api

RUN npm run build

EXPOSE 80

VOLUME db

CMD [ "npm", "start" ]`

I tried deleting one of the apps and then re-adding but still same result.

**Comment by XuryaX** [comment]
I should also mention that this is in EC2 instance. I restarted the instances which has changed the IPs of the hosts. This might also be the issue.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Closing as there hasn't been a response in more than a week.
