### ISSUE TITLE
`dokku_client.sh` with remote alternative port

### ISSUE THREAD

**Issue by kbuilds** [dokku/dokku#3035]
Typically, I add remotes like this:

```
git remote add dokku dokku@example.com:app_name
```

However, if I need the remote to be targeted on a different port, I need to add it like this:

```
git remote add dokku ssh://dokku@example.com:port_number/app_name
```

This works fine for git, but it breaks the dokku_client.sh

When I try to run some commands, the script parses the git remote incorrectly. It thinks that that app name is `port_number/app_name`, rather than just `app_name`.

Is there an environment variable that I can set? Something like `DOKKU_APP`, that will override this behavior?

**Comment by josegonzalez** [comment]
You can set [`DOKKU_PORT`](https://github.com/dokku/dokku/blob/master/contrib/dokku_client.sh#L3), or you can use a custom `.ssh/config` to set the port implicitly.

**Comment by kbuilds** [comment]
@josegonzalez Thank you for the quick reply, and thank you for all of your work on this project.

The `.ssh/config` option is certainly viable. I was just wondering if there was a solution available through the environment configuration.

`DOKKU_PORT` affects the dokku client, but does not affect git. Because I need to push and communicate with dokku over the same port, I need to set the remote-url via ssh://

The problem I am running into is that when the remote-url is set in a way that specifies the port number, as shown above, the dokku client script no longer parses the app name correctly. It does work properly if I specify the app name using the `--app app_name` arg, as outlined in this thread:
https://github.com/dokku/dokku/issues/1638

I just wasn't sure if there was a clean way for me to not have to specify this every time. If there is no way around it, I will use the ssh config route.

Thanks again,
K

**Comment by josegonzalez** [comment]
We can only control the `dokku_client.sh` route, and the correct way to do it is to use the env var as specified _or_ use the `.ssh/config` method. Sorry, but those are the options I have for you :(

**Comment by kbuilds** [comment]
@josegonzalez No problem, dude. Just making sure I have investigated all options.

This is an excellent project. Thanks for all of your support.

**Comment by josegonzalez** [comment]
Let me know if you figure out an alternative. I think the only way we'd be able to do this would be to screw around with parsing the pushed app name, but I'm not sure if we'd end up breaking anything.

**Comment by kbuilds** [comment]
@josegonzalez I think that we could potentially avoid having to increase the complexity of parsing the app name. What if there was an optional environment available, for example `DOKKU_APP_NAME`, that would get picked up instead of having to parse at all?

If it's a good way of solving the problem, I can play around with it this weekend and see what I can come up with. I suck at bash scripting, but I'll give it a shot. Let me know what you think.

**Comment by josegonzalez** [comment]
We already support  `dokku --app APP_NAME command:subcommand` in the `dokku` binary, but that is opt-in for non-official plugins, and is pretty error prone.

If you want to change the parsing in the client so that it splits on `/` and takes the last chunk if the first chunk is a number, that could work (and I'd be happy to see the PR). However, I'm not going to personally work on that so still keeping this issue closed.

**Comment by kbuilds** [comment]
@josegonzalez Ok, I will try doing it that way.

**Comment by stefsava** [comment]
@josegonzalez 
> You can set DOKKU_PORT, or you can use a custom .ssh/config to set the port implicitly.

What you say seems to me incorrect.
Currently only DOKKU_PORT works, custom .ssh / config can not work because dokku_client.sh always calls ssh with -p "$ DOKKU_PORT" where the default is 22.
The port setting in .ssh / config is ignored.
