### ISSUE TITLE
Unable to unset invalid config

### ISSUE THREAD

**Issue by prichey** [dokku/dokku#3036]
This is a pretty weird edge case which may or may not be an actual bug, I'm just not sure what to do about it. My temporary solution is to downgrade to 0.10.5, which works ok, but probably not a long-term solution.

In upgrading to 0.11.3 (I think from 0.10.5 but not totally sure), one of my app builds started breaking like so:

```
root@prichey:~# dokku ps:rebuild appname
-----> Cleaning up...
-----> Building appname from herokuish...
/var/lib/dokku/core-plugins/available/common/functions: line 448: export: --: invalid option
export: usage: export [-fn] [name[=value] ...] or export -p
```

After enabling trace, I found this:

```
++ /var/lib/dokku/plugins/available/config/subcommands/export config:export appname
++ return 0
+ eval 'export --no-restart='\''--no-restart'\''
export DOKKU_APP_RESTORE='\''1'\''
export DOKKU_APP_TYPE='\''herokuish'\''
export DOKKU_NGINX_PORT='\''80'\''
export DOKKU_NGINX_SSL_PORT='\''443'\''
export DOKKU_PROXY_PORT_MAP='\''http:80:5000 https:443:5000'\''
++ export --no-restart=--no-restart
/var/lib/dokku/core-plugins/available/common/functions: line 448: export: --: invalid option
export: usage: export [-fn] [name[=value] ...] or export -p
```

I checked my config and sure enough:

```
root@prichey:~# dokku config appname
=====> appname env vars
DOKKU_NGINX_PORT:      80
DOKKU_PROXY_PORT_MAP:  http:80:5000 https:443:5000
--no-restart:          --no-restart
```

Somehow I had been able to set an env var `--no-restart`.

I tried unsetting it, but:

```
root@prichey:~# dokku config:unset appname --no-restart
FAILED: Invalid key name: '--no-restart'
root@prichey:~# dokku config:unset appname "--no-restart"
FAILED: Invalid key name: '--no-restart'
root@prichey:~# dokku config:unset appname \--no-restart
FAILED: Invalid key name: '--no-restart'
```

So, that's where I'm at. The app won't build because I have a config with an invalid key name, but I can't unset that var because its name is invalid.

Any ideas?

Here's a link to my `dokku report` if pertinent: https://gist.github.com/prichey/0e8563cee603bd17447538bc9e1e2cdb.

**Comment by josegonzalez** [comment]
Can you downgrade and unset, then re-upgrade?

@alexquick I do see that we're parsing that flag differently now, is it possible we're passing that accidentally and setting it somewhere?

**Comment by alexquick** [comment]
@josegonzalez over the next few days I’ll have a chance to double check to make sure we aren’t setting this accidentally ourselves and look around for anything else odd going on. I’ll also look into how hard it would be to have invalid env vars be permitted to be unset for those who have upgraded from prior versions.

**Comment by josegonzalez** [comment]
Thanks!

**Comment by prichey** [comment]
Weirdly enough, downgrading, unsetting, then re-upgrading did not work.

I started (with a working app) at 0.10.5. You can check out my `dokku report` [here].(https://gist.github.com/prichey/05d445b1b9b87caec26aed99129b213a)). 

My config looked like this:

```
root@prichey:~# dokku config appname
=====> appname config vars
DOKKU_APP_RESTORE:    1
DOKKU_NGINX_PORT:     80
DOKKU_NGINX_SSL_PORT: 443
DOKKU_PROXY_PORT_MAP: http:80:5000 https:443:5000
```

As you can see, no `--no-restart` set. Just to be sure, I did this:

```
root@prichey:~# dokku config:unset appname --no-restart
-----> Unsetting appname
Reinitializing monit daemon
```

`dokku config` yielded the same thing as before.

Then, I upgraded to 0.11.3. Report [here](https://gist.github.com/prichey/dd63baa384a8a42b9a4977411d1c1c97).

Upgrading went fine, but I attempted to rebuild my app and I got the same error as before:

```
root@prichey:~# dokku ps:rebuild appname
-----> Cleaning up...
-----> Building appname from herokuish...
/var/lib/dokku/core-plugins/available/common/functions: line 448: export: --: invalid option
export: usage: export [-fn] [name[=value] ...] or export -p
```

I checked my config, and for some reason the var came back?

```
root@prichey:~# dokku config appname
=====> appname env vars
--no-restart:          --no-restart
DOKKU_PROXY_PORT_MAP:  http:80:5000 https:443:5000
DOKKU_NGINX_PORT:      80
DOKKU_NGINX_SSL_PORT:  443
```

I'm going to stay downgraded for now (which is totally not a big deal). I'd be happy to provide any further information that might be helpful. Thanks!

**Comment by josegonzalez** [comment]
What would be useful is for you gist the following:

- downgrade
- remove the bad env var
- get the current config
- upgrade
- get the current config
- dokku --trace ps:rebuild appname
- get the current config

**Comment by prichey** [comment]
@josegonzalez Here you go: https://gist.github.com/prichey/eb291c86c7bb3e97e75e72177ecf28cf

**Comment by josegonzalez** [comment]
Okay so the `upgrade` ends up setting it somewhere. Can you do the following:

```
sudo su -
apt-get install dokku=0.10.5
dokku config:unset appname --no-restart
dokku config appname
export TRACE=1
export DOKKU_TRACE=1
apt-get install dokku
unset TRACE
unset DOKKU_TRACE
```

And gist the output?

**Comment by alexquick** [comment]
@josegonzalez 
Playing around with it a little bit If you end up setting '--no-restart' as an env key in 10.5 it won't show up in `config appname` nor `config:unset`/`config:get` but will remain in the `ENV` file. Then 11.x freaks out after the upgrade.

```bash
#against 10.5
$ dokku config:set guh hey=hi
-----> Setting config vars
       hey:  hi
$ dokku config:set guh "--no-restart=value"
-----> Setting config vars
       --no-restart: value
-----> Restarting app guh
App guh has not been deployed
$ dokku config:unset guh "--no-restart"
-----> Unsetting guh
$ dokku config guh
=====> guh config vars
hey: hi
$ cat ~dokku/guh/ENV 
export hey='hi'
export --no-restart='value'

# switch to 11.3
$ dokku config guh
=====> guh env vars
--no-restart:  value
hey:           hi
$ dokku config:unset guh '--no-restart'
FAILED: Invalid key name: '--no-restart'
```

I will look more into it tomorrow.

**Comment by prichey** [comment]
@josegonzalez Here you go: https://gist.github.com/prichey/e1ce3d3a2e187e6ff6d798d4d0a4ea57

(I just scanned through and I don't think there's anything compromising in there but I'm taking it on good faith that there isn't. 🙂)

Just a note: the app name is actually named `rottentrumpatoes`. I've been copy/pasting in `appname` to make it generic. I did the same in this gist, I just wanted to mention it for posterity.

**Comment by alexquick** [comment]
@prichey what does ‘~dokku/rottrumpatoes/ENV’ look like? If you downgrade, back it up, delete the ‘—no-restart line’, and then upgrade does it reappear?

**Comment by prichey** [comment]
Sure enough, it was set in my `ENV`.

After removing, upgrading, and rebuilding, everything is working fine. I should have thought to do that in the first place. Thanks for the help!

**Comment by prichey** [comment]
@josegonzalez @alexquick 

I'll leave the issue open in case you guys are going to make any changes but feel free to close.

**Comment by mebezac** [comment]
Thanks @alexquick that was my issue as well, `--no-restart` was in my `ENV` file in my app's directory
