### ISSUE TITLE
Dead Gratipay link in README

### ISSUE THREAD

**Issue by thomasfedb** [dokku/dokku#3037]
The link in your README to `https://gratipay.com/dokku/` leads to a 404 since [Gratipay is no more](https://gratipay.news/the-end-cbfba8f50981).

I previously tried donating via OpenCollective, but that somehow managed to create several unlinked accounts, confused my payment details, and so far support haven't managed to sort out the mess after several months. I would still, however, really like to set up a recurring contribution.

Perhaps you would consider a [Patreon](https://www.patreon.com)? They certainly seem to have the technology sorted out, and there are a few other FOSS project there also, such as [Ubuntu MATE](https://www.patreon.com/ubuntu_mate) and [elementary OS](https://www.patreon.com/elementary).

**Comment by josegonzalez** [comment]
Okay so I've created a Patreon [here](https://www.patreon.com/dokku) and more or less expect the original poster and @sman591 (who 👍 this issue) to donate. I've also added a few levels and rewards, so if people want to get the ball rolling on some cool stuff, feel free to donate!

**Comment by sman591** [comment]
Nice! Also, how does Open Collective play into this? It looks like there's already a considerable amount of donations there (~$2.6k right now) and several monthly subscriptions. https://opencollective.com/dokku

**Comment by josegonzalez** [comment]
I'm going to use them slightly differently.

## Open Collective

Open Collective will be used for me to spend a considerable amount of time actively developing Dokku - versus playing with my cat, drinking, day job - and I'll bill it at my normal rate. In fact, most of the work for 0.11.4 was a direct result of me spending time away from my Day Job, and I'll be invoicing the Open Collective for that.

We will also be using these funds to pay for any external costs we incur - hosting, domain names, CI, etc. Spinning up a DigitalOcean instance for testing something a user has reported isn't free. These sorts of things haven't been traditionally booked towards Open Collective - I've been eating the charges as of late - but hopefully I can spend more time doing so.

One nice thing about Open Collective is that we can be pretty transparent about where the money goes.

## Patreon

Patreon is a bit more directed around seeing "goals" reached. At least for donors, you'll have the ability to see tutorials and posts on how to do specific things in Dokku. A good example of what you might see are the [dokku-wordpress](https://github.com/dokku-community/dokku-wordpress/) repository that guides you through deploying Wordpress on Dokku, or the [Gogs Blog Post](http://dokku.github.io/tutorials/deploying-gogs-to-dokku).

One thing I was playing around with was selling actual Dokku plugins. These are plugins that are more "nice to have" - such as deploying via webhook from Github, or managing interactions with ECR/Docker Hub - but are more useful from the viewpoint of a business. This may still end up happening, but if the Patreon stuff goes well, funders will help guide their development and keep the code open source.

For the most part, Patreon funds will be used for me to be able to justify spending time on the community, specifically in regards to outreach, tutorial development, and general upkeep.

## Closing thoughts

Users can donate on either site - or both! - as they please. I don't generally like providing multiple options, but if thats what people want to see, so be it. I think there is enough room in the OSS funding space for our users to be able to choose which method they prefer.

Hope all of that makes sense, and I hope to see your monthly donation Real Soon™ ;)
