### ISSUE TITLE
Installing Dokku on RHEL 7?

### ISSUE THREAD

**Issue by CarlosAmaral** [dokku/dokku#3046]
Is it possible?

**Comment by josegonzalez** [comment]
Did you attempt to follow our centos docs?

**Comment by ebeigarts** [comment]
Since rhel7 and centos7 are very similiar, it should work, if you change `centos` with `centos|rhel` in all the `case` statements in `dokku` source and rebuild `rpm` images:

```diff
 case "$DOKKU_DISTRO" in
-  arch|debian|centos)
+  arch|debian|centos|rhel)
   ...
```

https://github.com/dokku/dokku/search?utf8=%E2%9C%93&q=centos&type=

**Comment by josegonzalez** [comment]
Ah thats cool. Since I don't run RHEL, pull requests welcome!

If you to sponsor the work, we can also do that :)

**Comment by CarlosAmaral** [comment]
@josegonzalez I had tried with CentOS yes. Thanks, it would be cool to have it working on Rhel! :)

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
