### ISSUE TITLE
refs/heads/master: No such file or directory  when trying to deploy using dokku tar:from

### ISSUE THREAD

**Issue by cirovladimir** [dokku/dokku#3047]
Description of problem:
/var/lib/dokku/plugins/available/git/functions: line 142: /home/dokku/diju/refs/heads/master: No such file or directory

when trying to deploy using dokku tar:from

Output of the following commands

-----> uname: Linux wellington 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:           7983        1780         378         129        5824        5681
Swap:          8191           1        8190
-----> docker version: 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 25
 Running: 6
 Paused: 0
 Stopped: 19
Images: 44
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 141
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.797GiB
Name: wellington
ID: XXXXXXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.29
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v159
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v99
  heroku-buildpack-java      v51
  heroku-buildpack-gradle    v21
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v121
  heroku-buildpack-go        v64
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.9.4
-----> dokku plugins: 
 !     Deprecated: Please use plugin:list
plugn: 0.3.0
  00_dokku-standard    0.9.4 enabled    dokku core standard plugin
  20_events            0.9.4 enabled    dokku core events logging plugin
  apps                 0.9.4 enabled    dokku core apps plugin
  build-env            0.9.4 enabled    dokku core build-env plugin
  certs                0.9.4 enabled    dokku core certificate management plugin
  checks               0.9.4 enabled    dokku core checks plugin
  common               0.9.4 enabled    dokku core common plugin
  config               0.9.4 enabled    dokku core config plugin
  docker-options       0.9.4 enabled    dokku core docker-options plugin
  domains              0.9.4 enabled    dokku core domains plugin
  elasticsearch        1.0.0 enabled    dokku elasticsearch service plugin
  enter                0.9.4 enabled    dokku core enter plugin
  git                  0.9.4 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.9.4 enabled    dokku core logs plugin
  mysql                1.0.0 enabled    dokku mysql service plugin
  named-containers     0.9.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.9.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.9.4 enabled    dokku core plugin plugin
  proxy                0.9.4 enabled    dokku core proxy plugin
  ps                   0.9.4 enabled    dokku core ps plugin
  repo                 0.9.4 enabled    dokku core repo plugin
  shell                0.9.4 enabled    dokku core shell plugin
  ssh-keys             0.9.4 enabled    dokku core ssh-keys plugin
  storage              0.9.4 enabled    dokku core storage plugin
  tags                 0.9.4 enabled    dokku core tags plugin
  tar                  0.9.4 enabled    dokku core tar plugin

- If a deploy is failing or behaving unexpectedly:
  - Application name: diju
  - The type of application being deployed: java
  - If using buildpacks: https://github.com/heroku/heroku-buildpack-java
  - If it exists, the contents of your `Procfile`.
web: java $JAVA_OPTS -jar diju-0.0.1-SNAPSHOT.war --server.port=$PORT
- Output of failing Dokku commands after running `dokku trace on`
ssh -t dokku@dokku.tribunalqro.gob.mx tar:from diju https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXXXX?e=download
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOKKU_IMAGE=gliderlabs/herokuish
+ DOKKU_IMAGE=gliderlabs/herokuish
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXX?e=download'
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=2
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=3
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=4
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ tar:from =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ /usr/bin/tty
+ [[ /dev/pts/1 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ tar:from =~ ^plugin:.* ]]
+ [[ tar:from == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ -n tar:from diju https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXX?e=download ]]
+ export -n SSH_ORIGINAL_COMMAND
+ [[ tar:from =~ config-* ]]
+ [[ tar:from =~ docker-options* ]]
+ set -f
+ /usr/bin/dokku tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXX?e=download'
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOKKU_IMAGE=gliderlabs/herokuish
+ DOKKU_IMAGE=gliderlabs/herokuish
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXX?e=download'
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=2
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=3
+ for arg in '"$@"'
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=4
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ tar:from =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ /usr/bin/tty
+ [[ /dev/pts/1 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ tar:from =~ ^plugin:.* ]]
+ [[ tar:from == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ -n '' ]]
+ dokku_auth tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXX?e=download'
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=dokku
+ SSH_USER=dokku
+ export SSH_NAME=admin1
+ SSH_NAME=admin1
+ plugn trigger user-auth dokku admin1 tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXX?e=download'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ tar:from =~ (ssh-keys:add|ssh-keys:remove) ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXX?e=download'
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=tar:from
+ local PLUGIN_CMD=tar:from
+ local implemented=0
+ local script
+ argv=("$@")
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/tar
+ [[ /var/lib/dokku/core-plugins/available/tar == *core-plugins* ]]
+ [[ tar:from == \t\a\r\:\f\r\o\m ]]
+ shift 1
+ [[ ! -z '' ]]
+ set -- tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXX?e=download'
+ [[ -x /var/lib/dokku/plugins/enabled/tar:from/subcommands/default ]]
+ [[ -x /var/lib/dokku/plugins/enabled/tar:from/subcommands/tar:from ]]
+ [[ -x /var/lib/dokku/plugins/enabled/tar/subcommands/from ]]
+ /var/lib/dokku/plugins/enabled/tar/subcommands/from tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXXX?e=download'
+ source /var/lib/dokku/plugins/available/tar/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+ tar_from_cmd tar:from diju 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXX?e=download'
+ declare 'desc=deploys app from tarball at URL via command line'
+ local cmd=tar:from
+ verify_app_name diju
+ declare 'desc=verify app name format and app existence'
+ local APP=diju
+ [[ ! -n diju ]]
+ [[ ! diju =~ ^[a-z].* ]]
+ [[ ! -d /home/dokku/diju ]]
+ return 0
+ local APP=diju
+ local 'URL=https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXX?e=download'
+ shift 3
+ tar_in_cmd tar:in diju
+ declare 'desc=deploys app from tarball on STDIN via command line'
+ local cmd=tar:in
+ local APP=diju
+ verify_app_name diju
+ declare 'desc=verify app name format and app existence'
+ local APP=diju
+ [[ ! -n diju ]]
+ [[ ! diju =~ ^[a-z].* ]]
+ [[ ! -d /home/dokku/diju ]]
+ return 0
+ curl -# --insecure -L 'https://doc-10-5c-docs.googleusercontent.com/docs/XXXXXX?e=download'
+ wc -c
+ tee /home/dokku/diju/src.tar
######################################################################## 100.0%
75570688
+ plugn trigger receive-app diju
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ source /var/lib/dokku/plugins/available/git/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
++ source /var/lib/dokku/plugins/available/apps/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
+++ source /var/lib/dokku/plugins/available/config/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
++++ source /var/lib/dokku/core-plugins/available/common/functions
+++++ set -eo pipefail
+++++ [[ -n 1 ]]
+++++ set -x
++ source /var/lib/dokku/plugins/available/config/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
+ git_receive_app diju
+ declare 'desc=git receive-app plugin trigger'
+ local trigger=git_receive_app
+ local APP=diju
+ local REV=
+ [[ ! -d /home/dokku/diju/refs ]]
+ acquire_app_deploy_lock diju exclusive
+ declare 'desc=acquire advisory lock for use in git/tar deploys'
+ local APP=diju
+ verify_app_name diju
+ declare 'desc=verify app name format and app existence'
+ local APP=diju
+ [[ ! -n diju ]]
+ [[ ! diju =~ ^[a-z].* ]]
+ [[ ! -d /home/dokku/diju ]]
+ return 0
+ local LOCK_TYPE=exclusive
+ local APP_DEPLOY_LOCK_FD=200
+ local APP_DEPLOY_LOCK_FILE=/home/dokku/diju/.deploy.lock
+ local 'LOCK_WAITING_MSG=diju is currently being deployed. Waiting...'
+ local 'LOCK_FAILED_MSG=diju is currently being deployed. Exiting...'
+ local SHOW_MSG=true
+ eval 'exec 200>/home/dokku/diju/.deploy.lock'
++ exec
+ [[ exclusive == \w\a\i\t\i\n\g ]]
+ flock -n 200
+ git_build diju
+ declare 'desc=setup and call git_build_app_repo'
+ local APP=diju
+ [[ 1 -ge 2 ]]
/var/lib/dokku/plugins/available/git/functions: line 142: /home/dokku/diju/refs/heads/master: No such file or directory
+ local REF=
+ git_build_app_repo diju
+ declare 'desc=builds local git app repo for app'
+ verify_app_name diju
+ declare 'desc=verify app name format and app existence'
+ local APP=diju
+ [[ ! -n diju ]]
+ [[ ! diju =~ ^[a-z].* ]]
+ [[ ! -d /home/dokku/diju ]]
+ return 0
+ local APP=diju
+ local REV=
++ mktemp -d /tmp/dokku_git.XXXX
+ local GIT_BUILD_APP_REPO_TMP_WORK_DIR=/tmp/dokku_git.lc8E
+ trap 'rm -rf "$GIT_BUILD_APP_REPO_TMP_WORK_DIR" > /dev/null' RETURN INT TERM EXIT
+ local TMP_TAG=dokku/
+ chmod 755 /tmp/dokku_git.lc8E
+ unset GIT_DIR GIT_WORK_TREE
+ [[ ! -d /home/dokku/diju ]]
+ use_git_worktree
+ declare 'desc=detects whether to use git worktree'
+ local GIT_VERSION MAJOR_VERSION MINOR_VERSION
++ awk '{split($0,a," "); print a[3]}'
++ git --version
+ GIT_VERSION=2.7.4
++ awk '{split($0,a,"."); print a[1]}'
++ echo 2.7.4
+ MAJOR_VERSION=2
++ awk '{split($0,a,"."); print a[2]}'
++ echo 2.7.4
+ MINOR_VERSION=7
+ [[ 2 -ge 3 ]]
+ [[ 2 -eq 2 ]]
+ [[ 7 -ge 11 ]]
+ return 1
+ pushd /tmp/dokku_git.lc8E
+ GIT_DIR=/home/dokku/diju
+ git tag -d dokku/
+ true
+ GIT_DIR=/home/dokku/diju
+ git tag dokku/ ''
+ rm -rf /tmp/dokku_git.lc8E
Connection to dokku.tribunalqro.gob.mx closed.

Environment details: VMWare

How was Dokku installed?: 
wget https://raw.githubusercontent.com/dokku/dokku/v0.9.4/bootstrap.sh
sudo DOKKU_TAG=v0.9.4 bash bootstrap.sh

How reproducible:
always

Steps to Reproduce:
1. create an app
2. depoy using git method
3. redeploy using tar method

Actual Results:
/var/lib/dokku/plugins/available/git/functions: line 142: /home/dokku/diju/refs/heads/master: No such file or directory

Additional info:
<@savant> i think I should add the currently detected deploy method in `dokku apps:report`

**I've destroyed the app and created it again, then deployed using only one and the same method tar:from without problems**

**Comment by cirovladimir** [comment]
@josegonzalez you asked me to remember you "...add the currently detected deploy method in dokku apps:report"

**Comment by josegonzalez** [comment]
So this is just how the deploys work. First detected deploy method gets triggered, and you can't switch from tar to git deploys (or rather, shouldn't).

I'm going to add some info to `apps:report` via a new plugin trigger that retrieves the deploy method, and that will allow us to more quickly debug this sort of issue. Will also ensure there is documentation.

**Comment by josegonzalez** [comment]
I've opened a pull request which implements the report method, but also forces a tar build when `tar:from` or `tar:in` is triggered.

Closing as there is a pull request open.
