### ISSUE TITLE
Change domain pointed when did web install ?

### ISSUE THREAD

**Issue by AnthoniG** [dokku/dokku#3048]
Hi, just figuring out Dokku and am a really new user, but loving it so far.

I've got it installed on my VPS and I can see my app when I go to the IP of the server. However I am having trouble with the domain I put into the text box when did the web install with the ssh key.

What is the config file called that stores this (presuming I can just edit it in shell with vi) ?

**Comment by josegonzalez** [comment]
Checkout the domains documentation on our site. It shows the commands you can use to checkout your domain configuration and change settings.

**Comment by AnthoniG** [comment]
@josegonzalez 
When I run ```domains:add-global toribund.com``` I get the following
```domains:add-global: command not found```

That is what is listed in your document though [Domains Document](http://dokku.viewdocs.io/dokku~v0.11.3/configuration/domains/)

**Comment by josegonzalez** [comment]
What version of Dokku are you running?

**Comment by AnthoniG** [comment]
Hahah, silly me.
I forgot to put dokku in front of the command :| sorry about that

**Comment by AnthoniG** [comment]
I am having serious difficulty with domains. This is my final stumbling block and I just can't seem to get past it. Ripping my hair out here :(

I can see the ruby sample when I put in my IP (i even have to push via the IP because I can't get the domain to work). However when I goto app<mydomain> it always says server not found.

Is there anything you can do to help please?

**Comment by josegonzalez** [comment]
Mins jumping on our slack channel? It's linked to in our "where to get help" docs

**Comment by AnthoniG** [comment]
OK, give me a few mintues then I will be on :)

**Comment by josegonzalez** [comment]
Based on chat in slack, I believe the user's browser/OS/ISP is caching his DNS entries, as everything appears fine from my laptop and mobile.
