### ISSUE TITLE
Dokku Docker overhead?

### ISSUE THREAD

**Issue by fullofcaffeine** [dokku/dokku#3049]
Hi!

I'm new to Dokku but I find the concept highly appealing! Right now I use ansible to do most of my provisioning and deployment, and it works okay. I'd rather use an interface like Heroku's though, hence Dokku seems to be the perfect solution for me, given that I also didn't get to the point of having to scale to multiple servers yet.

Right now I have a reasonably-sized (~32GB RAM, 60GB SSD) for a couple of small/medium-sized Rails apps and another for Wordpress blogs. I use ansible to set up a new app/blog and deploy them. It works well enough but I have to edit the ansible scripts repo. I'd rather just set some vars and push

I'd like to migrate this to Dokku and perhaps only use Ansible to provision Dukku on the servers. I'm wondering about something though, will using Dokku create an additional overhead for the Wordpress blogs / Rails apps in terms of memory/space because of the Docker containers that are required for each app deployed, meaning I wouldn't be able to store as many apps as if I wasn't using Dokku? Could someone enlighten me about this?

Thanks in advance!

**Comment by josegonzalez** [comment]
Dokku runs zero persistent processes - only actually executing when you specifically run commands - and thus has no overhead when not being executed.

Docker containers are - by default - not set with any QoS resource limitation, and thus can use the entire system's memory. Depending on your networking modes, you may see a decrease in network throughput, but you're likely not saturating your internal bandwidth so it shouldn't matter.

If you are more curious about docker overhead, I recommend googling about it - I don't have any links handy - as there should be at least one person out there with benchmarks :)

Let me know if that answered your questions.

**Comment by josegonzalez** [comment]
Closing as there haven't been any follow-up questions.
