### ISSUE TITLE
Using Dokku to deploy WordPress / Laravel on AWS

### ISSUE THREAD

**Issue by distributev** [dokku/dokku#3057]
This is more of a query - How achievable is to use Dokku to achieve what is described in this project?

https://github.com/distributev/wordpress-laravel-docker-local-cloud

Any Dokku / Docker expert willing to take on this project?

**Comment by josegonzalez** [comment]
This is more of an issue tracker than a way to find people to do freelance. If you'd like to do that, please post on our [slack group](https://slack.gliderlabs.com/).
