### ISSUE TITLE
[QUESTION] Python versions.

### ISSUE THREAD

**Issue by seospace** [dokku/dokku#3067]
I receive this message while deploying:
````
The latest version of Python 3 is python-3.6.2 (you are using python-3.6.4, which is unsupported).
````
Is it a real problem? What if i want to use new python 3.7 thats is coming soon? Are there any problems that are gonna happen ?

**Comment by josegonzalez** [comment]
@seospace if your application deploys properly with 3.6.4, then its fine. Buildpacks are provided by Heroku, and any python versions are similarly provided by them. Once they provide a specific python, you'll be able to use a newer version
