### ISSUE TITLE
validate_nginx failed / invalid number of arguments in "server_name" << using template from docs

### ISSUE THREAD

**Issue by seospace** [dokku/dokku#3068]
First of all, cool project 👍 . I was looking for something like that to deploy my python apps ASAP with custom domains and https certs. This is what i am looking for, but already i faced same issues like in other projects of this type. I dived into docs but they are not clear, i want to perform really simple steps.
If the problems i am facing may be expected behaviour of dokku, may someone explain to me what i am doing wrong and how to achieve my expected results in a better way?

Also a question i couldnt find in docs (theres no search in docs?):
Why there are multiple docker containers for my app as i perform more deploys?
Why they are not automatically deleted and keep runing (dokku cleanup does not help).
If my python app is a flask application running on port 80 via gunicorn in Procfile, will that cause issues beacuse i have to expose port 443 for the SSL to work?)

**Expected Results:**
1. Create a new repository (python app) with a custom domain name (from what i understand, naming my app: mydomain.tld should setup everything for me, as docs are saying: adding domain before the app may cause issues).
2. Push it with custom nginx config ( i want to redirect www version to non-www).
3. Setup SSL via letsencrypt plugin ( from what i understand dokku will automatically handle redirection of http to https).
3. Repeat with new app & domain

As you see this looks really simple and this is why i am diving into this project. It looks awesome 🥇 

**Description of problem:**
- When using custom nginx config (copied from docs, nothing added or changed) i receive nginx configuration problem as seen in actual results.
- When not using custom nginx config app is deployed and works.

**How was Dokku installed?:**
Digitalocean, its a fresh install and nothing is done on it.

**Steps to Reproduce:**
1. custon nginx.conf.sigil (copied from docs, nothing changed, check in custom config below for content)
2. git init. && git add . && git commit
3. git remote add dokku dokku@dokku.me:**mydomain.tld**
4. git push dokku master

**Actual Results with custom config:**
````
remote: -----> Cleaning up...
remote: -----> Building mydomain.tld from herokuish...
remote: -----> Adding BUILD_ENV to build environment...
remote:        -----> Python app detected
remote:        !     The latest version of Python 3 is python-3.6.2 (you are using python-3.6.4, which is unsupported).
remote:        !     We recommend upgrading by specifying the latest version (python-3.6.2).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing requirements with pip
remote:
remote:        -----> Discovering process types
remote:        Procfile declares types -> web
remote: -----> Releasing mydomain.tld (dokku/mydomain.tld:latest)...
remote: -----> Deploying mydomain.tld (dokku/mydomain.tld:latest)...
remote: -----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
remote: -----> App Procfile file found (/home/dokku/mydomain.tld/DOKKU_PROCFILE)
remote: -----> DOKKU_SCALE file found (/home/dokku/mydomain.tld/DOKKU_SCALE)
remote: =====> web=1
remote: -----> Attempting pre-flight checks
remote:        For more efficient zero downtime deployments, create a file CHECKS.
remote:        See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
remote:        CHECKS file not found in container: Running simple container check...
remote: -----> Waiting for 10 seconds ...
remote: -----> Default container check successful!
remote: -----> Running post-deploy
remote: -----> Found previous container(s) (12de4f551a10) named mydomain.tld.web.1
remote: =====> renaming container (12de4f551a10) mydomain.tld.web.1 to mydomain.tld.web.1.1518895508
remote: =====> renaming container (9c29d9d0822e) sad_stallman to mydomain.tld.web.1
remote: -----> VHOST support disabled. Skipping domains setup
remote: -----> Overriding default nginx.conf with detected nginx.conf.sigil
remote: -----> Creating http nginx.conf
remote: -----> Running nginx-pre-reload
remote:        Reloading nginx
remote: nginx: [emerg] invalid number of arguments in "server_name" directive in /home/dokku/mydomain.tld/nginx.conf:4
remote: nginx: configuration file /etc/nginx/nginx.conf test failed
remote:        validate_nginx failed. contents of /home/dokku/mydomain.tld/nginx.conf below...
remote: server {
remote:   listen      [::]:42318;
remote:   listen      42318;
remote:   server_name ;
remote:   access_log  /var/log/nginx/mydomain.tld-access.log;
remote:   error_log   /var/log/nginx/mydomain.tld-error.log;
remote:
remote:   # set a custom header for requests
remote:   add_header X-Served-By www-ec2-01;
remote:
remote:   gzip on;
remote:   gzip_min_length  1100;
remote:   gzip_buffers  4 32k;
remote:   gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
remote:   gzip_vary on;
remote:   gzip_comp_level  6;
remote:
remote:   location    / {
remote:     proxy_pass  http://mydomain.tld;
remote:     proxy_http_version 1.1;
remote:     proxy_set_header Upgrade $http_upgrade;
remote:     proxy_set_header Connection "upgrade";
remote:     proxy_set_header Host $http_host;
remote:     proxy_set_header X-Forwarded-Proto $scheme;
remote:     proxy_set_header X-Forwarded-For $remote_addr;
remote:     proxy_set_header X-Forwarded-Port $server_port;
remote:     proxy_set_header X-Request-Start $msec;
remote:   }
remote:   include /home/dokku/mydomain.tld/nginx.conf.d/*.conf;
remote: }
remote:
remote: upstream mydomain.tld {
remote:
remote:   server 172.17.0.6:5000;
remote:
remote: }
To dokku.me:mydomain.tld
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku.me:mydomain.tld'
````
**Actual nginx.conf without custom config:**
````
server {
  listen      [::]:42318;
  listen      42318;

  access_log  /var/log/nginx/mydomain.tld-access.log;
  error_log   /var/log/nginx/mydomain.tld-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://mydomain.tld-5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/mydomain.tld/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

}

upstream mydomain.tld-5000 {

  server 172.17.0.7:5000;
}
````
Custom config :

````
server {
  listen      [::]:{{ .NGINX_PORT }};
  listen      {{ .NGINX_PORT }};
  server_name {{ .NOSSL_SERVER_NAME }};
  access_log  /var/log/nginx/{{ .APP }}-access.log;
  error_log   /var/log/nginx/{{ .APP }}-error.log;

  # set a custom header for requests
  add_header X-Served-By www-ec2-01;

  gzip on;
  gzip_min_length  1100;
  gzip_buffers  4 32k;
  gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
  gzip_vary on;
  gzip_comp_level  6;

  location    / {
    proxy_pass  http://{{ .APP }};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include {{ .DOKKU_ROOT }}/{{ .APP }}/nginx.conf.d/*.conf;
}

upstream {{ .APP }} {
{{ range .DOKKU_APP_LISTENERS | split " " }}
  server {{ . }};
{{ end }}
}

server {
    server_name www.{{ .NOSSL_SERVER_NAME }};
    return 301 $scheme://{{ .NOSSL_SERVER_NAME }}$request_uri;
}
````

**Comment by seospace** [comment]
After this command:
````
 dokku domains:add mydomain.tld mydomain.tld
````
Everything is deployed and works fine.
Can you tell me then, do i have to worry about this (from docs)? 
Is it confusing or its my fault?
````
Adding a domain before deploying an application will result in port mappings being set. This may cause issues for applications that use non-standard ports, as those will not be automatically detected. Please refer to the proxy documentation for information as to how to reconfigure the mappings.
````

**Comment by josegonzalez** [comment]
The generated nginx config file does not match the template you said you are using. Can you update this to _actually_ show your `nginx.conf.sigil`?

As well, please provide _all_ the details we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), including the output of the failed command after running `dokku trace on`.

**Comment by seospace** [comment]
@josegonzalez Yes, it does not match, theres this line:
````
server {
    server_name www.{{ .NOSSL_SERVER_NAME }};
    return 301 $scheme://{{ .NOSSL_SERVER_NAME }}$request_uri;
}
````
But its just a paste issue, i tried without it and the same happen.
But i dont think you had a chance to read my new comment.

**Comment by josegonzalez** [comment]
Okay I see, the second block confused me.

The problem here is that you didn't have domains set for your application. You _maybe_ didn't complete the web installation, or you disabled vhosts. In either case, the example templates there are just that - examples.  In this case, it didn't have an extra guard around setting the `server_name` that is shown [here](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L11).

Since they are a bit confusing - and we link to the `nginx.conf.sigil` file that people should be basing their changes on anyhow - I'll remove them.

**Comment by seospace** [comment]
Ok, just answering my own question that other may ask in future and land into this topic: ive created really small guide to make what i need ASAP https://github.com/seospace/HTTP200-ASAP

Thank you Dokku team for this amazing project good luck to you

**Comment by elahmo** [comment]
This might not directly be related to this issue, but could someone please help me with the actual location of the `nginx.conf.sigil`?

I need to alter the default nginx config, so I tried putting the altered template in various locations, and dokku doesn't seem to pick it up to overwrite the default.

I have tried the following (from the root directory of the source code)
./nginx.conf.sigil
./app-nginx.conf.sigil
./nginx/app-nginx.conf.sigil
./ngnix/nginx.conf.sigil
./app/nginx.conf.sigil
./app/app-nginx.conf.sigil

I also tried putting it in the /home/dokku/appname/, but it didnt work. For now I edit the nginx.conf manually, then reload nginx, but thats super tedious and I have to do it after each deployment.

**Comment by josegonzalez** [comment]
This isn't related to the ticket :)

It needs to be inside of your repo. As in committed to the repository. From our [docs](http://dokku.viewdocs.io/dokku/configuration/nginx/#customizing-the-nginx-configuration):

> - Copy the following example template to a file named nginx.conf.sigil and either:
>  - If using a buildpack application, you must check it into the root of your app repo.
>  - ADD it to your dockerfile WORKDIR
>  - if your dockerfile has no WORKDIR, ADD it to the /app folder
