### ISSUE TITLE
multiple ports exopse

### ISSUE THREAD

**Issue by chagainota** [dokku/dokku#3070]
Hi 

I'm new to dokku and trying to understand something simple

how do i expose more then one port

i always see in the command dokku network:report that my process expose port 5000
dokku network:report
=====> mentorcruise network information
       Network bind all interfaces: true
       Network listeners: 172.17.0.3:5000

i want it will expose 2 ports for example 5000 and 5002?

Thanks
Chagai Nota

**Comment by josegonzalez** [comment]
By default, the network binding for buildpacks is only aware of a single port, port 5000. That won't change, though if your app is listening on a second port - port 5002 - and you are not using host networking, then you should be able to use the same upstream ip and reference the port within your nginx config.

For Dockerfile deploys, you can `EXPOSE` any arbitrary number of ports you'd like, and they will be used _as is_ on the host. This means scaling a process horizontally may cause issues as you cannot reuse the exposed port across multiple containers.

Does the above make sense?

**Comment by chagainota** [comment]
Hi,

First of all thanks for answer.

I try to do what you say according the buildpacks but with no success.
can you please send me example how to implement it in my code.

Thx
Chagai Nota

**Comment by josegonzalez** [comment]
If you're having specific issues with buildpacks, you'll need to join us in our slack chat room (as mentioned in the issue template. See [here](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/) for more details on logging into slack chat.

**Comment by chagainota** [comment]
Thx

I will do it
