### ISSUE TITLE
Feature Request: Multiple global domains

### ISSUE THREAD

**Issue by lwm** [dokku/dokku#3087]
I've been fishing around in the issues but can't seem to find an answer.

I'd like to have one dokku installation handle multiple global domains.

I could have app A on foo.com and app B on bar.com.

As far as I know, this is not possible right now.

If someone can map out the steps, I could try and get a patch in!

**Comment by josegonzalez** [comment]
I believe you can use `dokku domains:add-global` to create multiple domains. You can also generally use the [domains plugin](http://dokku.viewdocs.io/dokku/configuration/domains/) to manage domain configuration for specific applications.

Let me know if that helps, and if it does, please consider donating to our [Patreon](https://www.patreon.com/dokku) or [OpenCollective](https://opencollective.com/dokku) :)

**Comment by lwm** [comment]
Ah, I see! I will give this a blast later and close this now optimistically. Thanks! Great that you have the OpenCollective account. I'm also getting one setup for my project. Since we rely on Dokku, it is certainly on our minds to put a cut of anything we get in there :)
