### ISSUE TITLE
Question: Using docker and NGinx

### ISSUE THREAD

**Issue by rvillablanca** [dokku/dokku#3094]
Hi,
I have DigitalOcean droplet with Dokku installed on it and I would like to know if can I use Nginx or Docker installed by Dokku for other apps ?
I have some apps managed by Dokku but I would like to install other services like Gogs/Gitea and Hugo but it should be installed behind of Nginx through port 80. For Hugo, I think I need to use a VHost with Nginx.

So, Is possible to use Docker and Nginx for any other usage unrelated with dokku safely ?

**Comment by josegonzalez** [comment]
That should be fine, we only cleanup dead/stopped containers that have the Dokku label, and cleanup unused images. `nginx` still includes the default path for site config, so using that is still allowed.

Closing as this isn't really a question about Dokku usage. Feel free to continue the discussion on our slack channel if you need further clarification.
