### ISSUE TITLE
dokku app stopped working after a non planned reboot of a server

### ISSUE THREAD

**Issue by LarsBuur** [dokku/dokku#3099]
Description of problem: 
Kind of desperate and I have been trawling trough github and google. I have inherited a elixir project running on dokku in a digital ocean droplet. Yesterday the server rebooted for now apparent reason and now the dokku app have stopped running and when I try to start / restore / rebuild it tries to start and are then stopped.

I think this is the cause (the output after trying to start the dokku app): 
"cat: /app/Procfile: No such file or directory        
setuidgid: usage: setuidgid account child"

the app have been running for about two years - I have no idea on how to fix it. Any suggestions would be much appriciated.

Output of the following commands

- `uname -a`: 'Linux drnx1 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux'

- `free -m`: '              total        used        free      shared  buff/cache   available
Mem:           3951         198         498          41        3253        3274
Swap:          1023           0        1023'

- `docker version`:
'Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false'

- `docker -D info`:
'Containers: 20
 Running: 4
 Paused: 0
 Stopped: 16
Images: 127
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 193
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: drnx1
ID: RF4D:M2LV:CMWO:6ALI:CYO4:NEZB:6R3T:UGXU:VEHL:JEZ4:BAWN:VI74
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false'

- `sigil -v`: '0.4.0'
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
'herokuish: 0.3.24
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v150
  heroku-buildpack-nodejs    v93
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v97
  heroku-buildpack-java      v48
  heroku-buildpack-gradle    v19
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v117
  heroku-buildpack-go        v54
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8'
- `dokku version`: '0.8.0'
- `dokku plugin`: 
'  00_dokku-standard    0.8.0 enabled    dokku core standard plugin
  20_events            0.8.0 enabled    dokku core events logging plugin
  apps                 0.8.0 enabled    dokku core apps plugin
  build-env            0.8.0 enabled    dokku core build-env plugin
  certs                0.8.0 enabled    dokku core certificate management plugin
  checks               0.8.0 enabled    dokku core checks plugin
  common               0.8.0 enabled    dokku core common plugin
  config               0.8.0 enabled    dokku core config plugin
  docker-options       0.8.0 enabled    dokku core docker-options plugin
  domains              0.8.0 enabled    dokku core domains plugin
  enter                0.8.0 enabled    dokku core enter plugin
  git                  0.8.0 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.8.0 enabled    dokku core logs plugin
  named-containers     0.8.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.8.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.8.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.8.0 enabled    dokku core proxy plugin
  ps                   0.8.0 enabled    dokku core ps plugin
  repo                 0.8.0 enabled    dokku core repo plugin
  shell                0.8.0 enabled    dokku core shell plugin
  ssh-keys             0.8.0 enabled    dokku core ssh-keys plugin
  storage              0.8.0 enabled    dokku core storage plugin
  tags                 0.8.0 enabled    dokku core tags plugin
  tar                  0.8.0 enabled    dokku core tar plugin'

- `docker inspect CONTAINER_ID` (if applicable): 'The container does not run'
- `cat /home/dokku/<app>/nginx.conf`: 
'server {
  listen      [::]:80;
  listen      80;
  server_name messenger.drnx.io;
  access_log  /var/log/nginx/messenger-access.log;
  error_log   /var/log/nginx/messenger-error.log;

  return 301 https://$host:443$request_uri;

}

server {
  listen      [::]:443 ssl ;
  listen      443 ssl ;
  server_name messenger.drnx.io;
  access_log  /var/log/nginx/messenger-access.log;
  error_log   /var/log/nginx/messenger-error.log;

  ssl_certificate     /home/dokku/messenger/tls/server.crt;
  ssl_certificate_key /home/dokku/messenger/tls/server.key;
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;

  keepalive_timeout   70;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://messenger-5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/messenger/nginx.conf.d/*.conf;
}

upstream messenger-5000 {

  server 172.17.0.6:5000;
}'
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name : 'messenger'
  - The type of application being deployed (node, php, python, ruby, etc.): elixir
  - If using buildpacks, which custom buildpacks are in use: ?
  - If using a `Dockerfile`, the contents of that file. 'no docker file'
  - If it exists, the contents of your `Procfile`. 'Does not exist'
- Output of failing Dokku commands after running `dokku trace on` 'see attached file':
[messenger_trace.log](https://github.com/dokku/dokku/files/1788570/messenger_trace.log)

Environment details (AWS, VirtualBox, physical, etc.): running on Digital Ocean droplet (4 GB Memory / 60 GB Disk / AMS3 - Ubuntu 16.04.1 x64)

How was Dokku installed?: No idea.

How reproducible:
Every time. I am unable to start the app.

Steps to Reproduce:
1. Reboot machine. Check if docker container is running using docker ps 
2. The container is not running. Also the dokku cli tools fails when trying to rebuild, restore or start
3.

Actual Results:
Dokku app is not running.

Expected Results:
Dokku app should be running

Additional info:

**Comment by josegonzalez** [comment]
Generally speaking, we'll restore applications on reboot for users. Depending on the state of docker on reboot, we'll either just start or rebuild the application. In this case, we tried to rebuild.

Turns out the buildpack was "updated" on the github and was not pinned in the repo - user used a `.buildpacks` file to specify their buildpack - which meant Dokku would (rightfully) pull down the latest version of the buildpack. In the latest version, erlang was updated to 20.1, but the user specified an elixer that is only compatible with 19.3. Erlang was therefore mismatched with elixer in the container. I ended up updating both `herokukish`, `plugn`, and `dokku` to latest, but that didn't quite fix it (the Procfile thing was a bug and we fixed that).

Next was some shitty elixer bug about versions:

```
** (Version.InvalidRequirementError) ~> 1.0
    (elixir) lib/version.ex:159: Version.match?/3
    (mix) lib/mix/local.ex:100: Mix.Local.check_elixir_version_in_ebin/1
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/local.ex:50: Mix.Local.append_archives/0
    (mix) lib/mix/cli.ex:8: Mix.CLI.main/1
```

After a bit of spelunking in the [buildpack](https://github.com/HashNuke/heroku-buildpack-elixir) and erlang/elixer community, I settled on the following as a fix:

```
# forces us to download the correctly compiled elixer for the latest supported erlang otp
curl -s "https://repo.hex.pm/builds/elixir/v1.3.4-otp-19.zip" -o /home/dokku/messenger/cache/elixir-v1.3.2.zip
# replaces the "detected" erlang otp with the correct version to match the compiled elixer binaries
curl -s "https://s3.amazonaws.com/heroku-buildpack-elixir/erlang/cedar-14/OTP-19.3.tar.gz" -o /home/dokku/messenger/cache/OTP-20.1.tar.gz
# rebuild the app!
dokku ps:rebuild messenger
```

The app works fine now. So a few things:

- Keep everything up to date! It helps shake out bugs :)
- Pin your dependencies! The buildpack changed default erlang and elixer. In order to weather a push, the user's repo should have a `elixir_buildpack.config` file with the following:
    ```
    erlang_version=19.3
    elixir_version=1.3.4
    ````
- Pin your buildpacks! The user's repo has a `.buildpacks` file with nodejs and elixer, neither of which are pinned to a commit or a release. We have docs on how to pin to specific version in our documentation.

Hope that helps anyone having a similar issue :)
