### ISSUE TITLE
Suggestion: Dokku Staging

### ISSUE THREAD

**Issue by crisward** [dokku/dokku#3122]
Not sure if this should be a plugin, or in core. So just thought I'd suggest this here for feedback then take it from there.

## The problem.
At the moment we use dokku to develop websites and apps inside local vm's. Then deploy them to a live server also running dokku. We have some scripts to sync db's and volumes.

However when a client comes back to us, possibly years later, we need to setup their site again locally, which can be time consuming, especially if we're just making small template changes. 

## Possible solution
If we could pull the site, do our change then push to a remote branch other than master. Then preview those changes on another domain, before pushing to master, there would be no need to setup the site locally or sync any volumes or databases.

The temp branch domains could be 
```bash
myapp.mydomain.com # master branch
myapp-staging.mydomain.com # staging branch
```
We would need a way of removing the staging container when we finished. We could either have a command to remove them eg. `dokku apps:destroy myapp:staging` or just automatically do this on the next push to master.

Thoughts?

**Comment by jalcine** [comment]
@crisward: Have you checked out https://github.com/glassechidna/dokku-graduate? It's not as hand-held as it'd seem but it can handle working on separate 'environments' for your projects.

**Comment by josegonzalez** [comment]
You can currently do the following:

```
dokku apps:clone EXISTING_APP NEW_APP
```

This copies all configuration for the app - except a reference to any service links, though those continue working - and you can push to the app as you wish, destroying it after you are done. I think this is the correct way to do this, and was in fact built for a purpose very similar to this - creating review apps from a CI/CD pipeline.

Here is an example!

```
# clone node-js-app to io-js-app in order to test movement to iojs
dokku apps:clone --skip-deploy node-js-app io-js-app

# ensure we setup the domains correctly or the deploy may fail
dokku domains:set io-js-app iojs-test.dokku.me

# rebuild the app now that its all done
dokku ps:rebuild io-js-app
```

> A nice addition to this workflow would be to sync a specific remote branch to your application for the purpose of setting up a review app, though not really all that relevant to this particular use case. That is planned for the [next patreon goal](https://www.patreon.com/dokku)...

I don't think being able to push to a new branch and having some dynamic host be created is a great idea - probably will make it very confusing to some folks as to what exactly is going on when they push the wrong branch (we already have code for alternate branch handling as well, so this would make that impossible to hook into). Anything outside of that also borders on making Dokku a configuration management tool, and I think there are quite a few options in that space.

Closing this issue for now as I think there is a satisfactory , but feel free to chime
