### ISSUE TITLE
slow deployment, unnecessary node.js upgrade 

### ISSUE THREAD

**Issue by thian4** [dokku/dokku#3124]
This process took most of the time, I waited here about 2 min.

```
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 8.x...
       Downloading and installing node 8.10.0...
       Using default npm version: 5.6.0

```
Why is dokku upgrading node.js? this is so unnecessary, can skip this execution?

**Comment by josegonzalez** [comment]
_Dokku_ isn't upgrading anything. This has to do with the nodejs buildpack provided by heroku. They generally do not cache downloads like nodejs locally - it would increase their cache directory tremendously - so if you're not provisioning on AWS, this can take a while.

You can avoid this by using a Dockerfile, or implementing [this functionality](https://github.com/heroku/heroku-buildpack-nodejs/issues/521) in the buildpack and then pulling the code from a local cache of some sort (I do this on GCP for some freelance stuff). You may also wish to figure out why the downloads of that file are so slow on your machine.

Hope the above helps. Let me know if you have any other questions.
