### ISSUE TITLE
stuck in `Running 'npm run build' in app container`

### ISSUE THREAD

**Issue by thian4** [dokku/dokku#3126]
Description of problem:
I was able to deploy with `git push dokku master`, but for the second time I added this in app.json

```
{
  "scripts": {
    "dokku": {
      "predeploy": "npm run build"
    }
  }
}
```

then it got stuck at  ====> Running 'npm run build' in app container

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Closing as there hasn't been an update. Feel free to post an update when you have one :)
