### ISSUE TITLE
Is yarn.lock file taken into account when pushing to master?

### ISSUE THREAD

**Issue by pirmax** [dokku/dokku#3127]
Is **yarn.lock** taken into account when pushing to master?

I have the impression that during the build in production, he installs a package with Yarn which is corrupt, a simple configuration error on postcss-loader.

I fixed this problem locally by downgrading the version of postcss-loader but the problem persists when putting into production.

> 2018-03-20T15:33:06.225750294Z app[web.1]: ERROR in ./node_modules/css-loader??ref--2-1!./node_modules/nuxt/node_modules/postcss-loader/lib??ref--2-2!./node_modules/vuetify/dist/vuetify.min.css
> 2018-03-20T15:33:06.225753516Z app[web.1]: Module build failed: ValidationError: PostCSS Loader Invalid Options
> 2018-03-20T15:33:06.225756406Z app[web.1]: 
> 2018-03-20T15:33:06.225759078Z app[web.1]: options['useConfigFile'] is an invalid additional property
> 2018-03-20T15:33:06.225761960Z app[web.1]: 
> 2018-03-20T15:33:06.225764681Z app[web.1]:  @ ./node_modules/vuetify/dist/vuetify.min.css 4:14-142
> 2018-03-20T15:33:06.225767586Z app[web.1]:  @ ./resources/plugins/vuetify.js
> 2018-03-20T15:33:06.225770324Z app[web.1]:  @ ./.nuxt/index.js
> 2018-03-20T15:33:06.225773084Z app[web.1]:  @ ./.nuxt/client.js
> 2018-03-20T15:33:06.225775970Z app[web.1]: 
> 2018-03-20T15:33:06.225778660Z app[web.1]: ERROR in ./node_modules/css-loader??ref--2-1!./node_modules/nuxt/node_modules/postcss-loader/lib??ref--2-2!./node_modules/font-awesome/css/font-awesome.min.css
> 2018-03-20T15:33:06.225781881Z app[web.1]: Module build failed: ValidationError: PostCSS Loader Invalid Options
> 2018-03-20T15:33:06.225784784Z app[web.1]: 
> 2018-03-20T15:33:06.225787425Z app[web.1]: options['useConfigFile'] is an invalid additional property
> 2018-03-20T15:33:06.225790228Z app[web.1]: 
> 2018-03-20T15:33:06.225792845Z app[web.1]:  @ ./node_modules/font-awesome/css/font-awesome.min.css 4:14-147
> 2018-03-20T15:33:06.225795728Z app[web.1]:  @ ./resources/plugins/font-awesome.js
> 2018-03-20T15:33:06.225798485Z app[web.1]:  @ ./.nuxt/index.js
> 2018-03-20T15:33:06.225801212Z app[web.1]:  @ ./.nuxt/client.js
> 2018-03-20T15:33:06.225804018Z app[web.1]: 
> 2018-03-20T15:33:06.225807075Z app[web.1]: ERROR in ./node_modules/css-loader??ref--2-1!./node_modules/nuxt/node_modules/postcss-loader/lib??ref--2-2!./resources/assets/css/main.css
> 2018-03-20T15:33:06.225812764Z app[web.1]: Module build failed: ValidationError: PostCSS Loader Invalid Options
> 2018-03-20T15:33:06.225815625Z app[web.1]: 
> 2018-03-20T15:33:06.225818286Z app[web.1]: options['useConfigFile'] is an invalid additional property
> 2018-03-20T15:33:06.225821122Z app[web.1]: 
> 2018-03-20T15:33:06.225823754Z app[web.1]:  @ ./resources/assets/css/main.css 4:14-167
> 2018-03-20T15:33:06.225826543Z app[web.1]:  @ ./.nuxt/App.js
> 2018-03-20T15:33:06.225829286Z app[web.1]:  @ ./.nuxt/index.js
> 2018-03-20T15:33:06.225832046Z app[web.1]:  @ ./.nuxt/client.js
> 2018-03-20T15:33:06.232469369Z app[web.1]: Error: Webpack build exited with errors
> 2018-03-20T15:33:06.232550287Z app[web.1]:     at compiler.run (/app/node_modules/nuxt/lib/builder/builder.js:589:29)
> 2018-03-20T15:33:06.232557957Z app[web.1]:     at emitRecords.err (/app/node_modules/webpack/lib/Compiler.js:265:13)
> 2018-03-20T15:33:06.232572379Z app[web.1]:     at Compiler.emitRecords (/app/node_modules/webpack/lib/Compiler.js:371:38)
> 2018-03-20T15:33:06.232592104Z app[web.1]:     at emitAssets.err (/app/node_modules/webpack/lib/Compiler.js:258:10)
> 2018-03-20T15:33:06.232595406Z app[web.1]:     at applyPluginsAsyncSeries1.err (/app/node_modules/webpack/lib/Compiler.js:364:12)
> 2018-03-20T15:33:06.232598201Z app[web.1]:     at next (/app/node_modules/tapable/lib/Tapable.js:218:11)
> 2018-03-20T15:33:06.232601114Z app[web.1]:     at Compiler.compiler.plugin (/app/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
> 2018-03-20T15:33:06.232603923Z app[web.1]:     at Compiler.applyPluginsAsyncSeries1 (/app/node_modules/tapable/lib/Tapable.js:222:13)
> 2018-03-20T15:33:06.232606666Z app[web.1]:     at Compiler.afterEmit (/app/node_modules/webpack/lib/Compiler.js:361:9)
> 2018-03-20T15:33:06.232609373Z app[web.1]:     at require.forEach.err (/app/node_modules/webpack/lib/Compiler.js:350:15)
> 2018-03-20T15:33:06.232612209Z app[web.1]:     at /app/node_modules/webpack/node_modules/async/dist/async.js:473:16
> 2018-03-20T15:33:06.232614928Z app[web.1]:     at iteratorCallback (/app/node_modules/webpack/node_modules/async/dist/async.js:1050:13)
> 2018-03-20T15:33:06.232617678Z app[web.1]:     at /app/node_modules/webpack/node_modules/async/dist/async.js:958:16
> 2018-03-20T15:33:06.232620388Z app[web.1]:     at /app/node_modules/graceful-fs/graceful-fs.js:43:10
> 2018-03-20T15:33:06.232623208Z app[web.1]:     at FSReqWrap.oncomplete (fs.js:153:20)
> 2018-03-20T15:33:07.561209428Z app[web.1]: Webpack Bundle Analyzer saved report to /app/.nuxt/dist/report.html
> 2018-03-20T15:33:09.200552218Z app[web.1]: Webpack Bundle Analyzer saved stats file to /app/.nuxt/dist/webpack-stats.json

**Comment by josegonzalez** [comment]
This has to do with the buildpack itself, not with anything Dokku or Herokuish does.

As mentioned in our issue template:

> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

**Comment by pirmax** [comment]
You don't have reply to my question... Is yarn.lock taken into account when pushing to master?

The rest of the message was meant to put you in the context of the problem!

**Comment by josegonzalez** [comment]
Again, this is a buildpack issue , and very specifically the `nodejs` buildpack. I do not know what that buildpack does - it is helpfully provided by Heroku, an organization with no actual ties to us - and thus we have different rules around supporting it.

If you would like support for this particular issue, I highly encourage you to log into our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels).
