### ISSUE TITLE
"Unable to select a buildpack" with Dockerfile

### ISSUE THREAD

**Issue by Corstiaan84** [dokku/dokku#3129]
Description of problem:
An asp.net core 2.0 app with Dockerfile throughs `Unable to bind to http://localhost:5001 on the IPv6 loopback interface: Error -99 EADDRNOTAVAIL address not available.`.

This might be a asp.net core / Docker issue but had no luck finding the solution in that area.

This my docker file:
`FROM microsoft/dotnet:latest`
`COPY . /app`
`WORKDIR /app`
`RUN ["dotnet", "restore"]`
`RUN ["dotnet", "build"]`
`ENV ASPNETCORE_URLS http://*:5001`
`EXPOSE 5001`
`WORKDIR /app/App.Web`
`ENTRYPOINT ["dotnet", "run"]`

Any thoughts? Thanks.

-----> uname: Linux aceventura 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
              total        used        free      shared  buff/cache   available
Mem:           3951        2997         269          20         684         650
Swap:          1020        1020           0
-----> docker version:
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
-----> docker daemon info:
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 34
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: aceventura
ID: 26QY:RFAO:U6ZC:EUE4:ISNC:ODYI:OH6I:H5ZE:PY6O:ENF5:E6ZE:YWAF
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version:
herokuish: 0.3.36
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v174
  heroku-buildpack-nodejs    v121
  heroku-buildpack-clojure   v78
  heroku-buildpack-python    v124
  heroku-buildpack-java      v59
  heroku-buildpack-gradle    v25
  heroku-buildpack-scala     v79
  heroku-buildpack-play      v26
  heroku-buildpack-php       v132
  heroku-buildpack-go        v85
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v9
-----> dokku version: 0.11.6
-----> dokku plugins:
plugn: 0.3.0
  00_dokku-standard    0.11.6 enabled    dokku core standard plugin
  20_events            0.11.6 enabled    dokku core events logging plugin
  apps                 0.11.6 enabled    dokku core apps plugin
  build-env            0.11.6 enabled    dokku core build-env plugin
  certs                0.11.6 enabled    dokku core certificate management plugin
  checks               0.11.6 enabled    dokku core checks plugin
  common               0.11.6 enabled    dokku core common plugin
  config               0.11.6 enabled    dokku core config plugin
  docker-options       0.11.6 enabled    dokku core docker-options plugin
  domains              0.11.6 enabled    dokku core domains plugin
  enter                0.11.6 enabled    dokku core enter plugin
  git                  0.11.6 enabled    dokku core git plugin
  logs                 0.11.6 enabled    dokku core logs plugin
  named-containers     0.11.6 enabled    dokku core named containers plugin
  network              0.11.6 enabled    dokku core network plugin
  nginx-vhosts         0.11.6 enabled    dokku core nginx-vhosts plugin
  plugin               0.11.6 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.11.6 enabled    dokku core proxy plugin
  ps                   0.11.6 enabled    dokku core ps plugin
  repo                 0.11.6 enabled    dokku core repo plugin
  shell                0.11.6 enabled    dokku core shell plugin
  ssh-keys             0.11.6 enabled    dokku core ssh-keys plugin
  storage              0.11.6 enabled    dokku core storage plugin
  tags                 0.11.6 enabled    dokku core tags plugin
  tar                  0.11.6 enabled    dokku core tar plugin

Environment details (AWS, VirtualBox, physical, etc.):
Linux Ubuntu 16.4 VM

How was Dokku installed?:
cURL instructions from homepage

**Comment by josegonzalez** [comment]
This is definitely a .net core issue, not a Dokku issue. Change your binding to be on 0.0.0.0, not localhost. Regardless of the issue, that will ensure that when you place a proxy in front of it, the proxy will be able to talk to the application.

I'm going to close this, but feel more than free to reach out on our slack or irc channel if you need more help in figuring out what is going on here.

**Comment by Corstiaan84** [comment]
@josegonzalez thank you
