### ISSUE TITLE
Missing encryption key to decrypt file with.

### ISSUE THREAD

**Issue by ipatovanton** [dokku/dokku#3130]
I use rails 5.2
Add dokku config:set my_app RAILS_MASTER_KEY='rails_master_key'
When i'm trying to deploy I have this error
`ActiveSupport::EncryptedFile::MissingKeyError: Missing encryption key to decrypt file with. Ask your team for your master key and write it to /tmp/build/config/master.key or put it in the ENV['RAILS_MASTER_KEY']`

**Comment by josegonzalez** [comment]
Can you provide _all_ of the information we ask for in our issue template, as well as the output of a deploy? It helps us debug issues. Thanks.

**Comment by ipatovanton** [comment]
There was an error in the app name
