### ISSUE TITLE
Update AUR package

### ISSUE THREAD

**Issue by Tyilo** [dokku/dokku#3133]
The package on AUR is for version 0.8.0, but the latest release of dokku is 0.11.6.

Please update it: https://aur.archlinux.org/packages/dokku

@josegonzalez seems to be the maintainer

**Comment by D1ceWard** [comment]
I'm helping on it, actually i successfully installed latest version.
I just have no time to completely test it for now... you can check changes : [D1ceWard/dokku-arch](https://github.com/D1ceWard/dokku-arch)

If you want to contribute do a pull request on this repository : [dokku/dokku-arch](https://github.com/dokku/dokku-arch)

**Comment by josegonzalez** [comment]
Because of our inclusion of golang, the package needs to be updated to compile binaries. I unfortunately do not have time to do this - nor do I have an arch machine to test - so if you want this completed, please file the requisite issue against the related repositories.
