### ISSUE TITLE
Add support for release in Procfile

### ISSUE THREAD

**Issue by jpleger** [dokku/dokku#3136]
### High-level plan

- [ ] Refactor `app.json` handling into a separate `deployment-tasks` plugin.
- [ ] Use `go-procfile-util` to extract the `release` command for the Procfile.
- [ ] Execute the `release` command in `scripts.dokku.predeploy`.
- [ ] Document the specialness of the `release` command

### Original Post

Description of problem:
Heroku added functionality for a "release" phase a while back. This allows a user to define in their procfile a release command which would run after deployment. Functionally, it is nearly identical to the apps.json key scripts.dokku.postdeploy.

Can be fairly useful for compatibility between heroku, especially in django projects where a db migration occurs.

Additional info:
Changelog from Heroku: https://devcenter.heroku.com/changelog-items/1140
More details on their implementation: https://devcenter.heroku.com/articles/release-phase

**Comment by josegonzalez** [comment]
This is actually closer to `scripts.dokku.predeploy`, not `scripts.dokku.postdeploy`.

**Comment by josegonzalez** [comment]
I made this [go-procfile-util](https://github.com/josegonzalez/go-procfile-util) repo that should allow us to refactor our existing procfile management, as well as new stuff. Of particular importance is also handling `#2793`, which means handling the `PORT` env var during expansion of the command that is going to be run.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
