### ISSUE TITLE
Default CURL_TIMEOUT too low

### ISSUE THREAD

**Issue by ebeigarts** [dokku/dokku#3142]
Hi,

Can we increase the default `CURL_TIMEOUT` to ~10 minutes, to make the defaults more friendly.
Currently the first thing I do after installing `dokku` is to set the timeout to `600`.

For example https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.5.1.tgz is 19MB.

With current default `60s` it needs network speed with at least 316KB/s. At least on DigitalOcean AMS3 the speeds to Heroku's S3 can drop below 80KB/s.

If we increase this to 10 minutes, then the minimum would be ~32KB/s.

**Comment by josegonzalez** [comment]
Seems fine to me.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
