### ISSUE TITLE
Support nginx's new "http2_push_preload"

### ISSUE THREAD

**Issue by malixsys** [dokku/dokku#3165]
Description of problem:

nginx 1.13.9 now supports `http2_push_preload on`
> c.f. [this artice](https://www.nginx.com/blog/nginx-1-13-9-http2-server-push)

it should be added [here](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L84) when supported according to the installed `nginx` version, perhaps using a new `HTTP2_PUSH_SUPPORTED` set [here](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/functions#L215)

**Comment by malixsys** [comment]
CC @callahad

**Comment by josegonzalez** [comment]
Not sure why you mentioned @callahad, but would you be willing to contribute this change?

**Comment by malixsys** [comment]
I think I had looked at who touched those files...

Created [PR #3181](https://github.com/dokku/dokku/pull/3181)

**Comment by malixsys** [comment]
https://github.com/dokku/dokku/pull/3181 approved

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
