### ISSUE TITLE
Dokku 0.12.3  on Debian stretch

### ISSUE THREAD

**Issue by zyriusa** [dokku/dokku#3166]
Hello,

i'm trying to install and get error below. How could i get missing packages?
root@mail:~# curl -s https://packagecloud.io/install/repositories/dokku/dokku/script.deb.sh | sudo bash
Detected operating system as debian/stretch.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/dokku_dokku.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
root@mail:~# apt-get install dokku
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
dokku : PreDepends: plugn (>= 0.3.0) but it is not installable
         Depends: sshcommand (>= 0.6.0) but it is not going to be installed
         Depends: gliderlabs-sigil but it is not installable
         Depends: docker-engine-cs (>= 1.9.1) but it is not installable or
                  docker-engine (>= 1.9.1) but it is not installable or
                  docker-io (>= 1.9.1) but it is not installable or
                  docker-ce but it is not installable or
                  docker-ee but it is not installable
         Recommends: herokuish (>= 0.3.4) but it is not going to be installed
         Recommends: parallel but it is not going to be installed
         Recommends: dokku-update but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by josegonzalez** [comment]
Do you have docker installed?

**Comment by zyriusa** [comment]
No, it was not installed. I installed it now
root@mail:~# docker -v
Docker version 18.03.0-ce, build 0520e24

**Comment by josegonzalez** [comment]
Mind going through the rest of the install, as noted in our documentation?

**Comment by zyriusa** [comment]
I think i stuch at the same point

DOKKU_TAG=v0.12.3 bash bootstrap.sh
Preparing to install v0.12.3 from https://github.com/dokku/dokku.git...
--> Ensuring we have the proper dependencies
--> Initial apt-get update
--> Installing docker
2018-04-19 10:03:45 URL:https://get.docker.com/ [13825/13825] -> "-" [1]
# Executing docker install script, commit: 92d5116
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/debian stretch edge" > /etc/apt/sources.list.d/docker.list
+ [ debian = debian ]
+ [ stretch = wheezy ]
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sh -c docker version
Client:
 Version:       18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:22:52 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:        Tue Apr 10 18:20:59 2018
  OS/Arch:      linux/amd64
  Experimental: false
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
--> Installing dokku
2018-04-19 10:04:15 URL:https://packagecloud.io/gpg.key [3889/3889] -> "-" [1]
OK
deb https://packagecloud.io/dokku/dokku/debian/ stretch main
E: Unable to correct problems, you have held broken packages.

**Comment by josegonzalez** [comment]
Ah I see whats going on. One moment.

**Comment by josegonzalez** [comment]
Can you try:

```
apt-get update
apt-get install dokku herokuish plugin sshcommand dokku-update
```

**Comment by zyriusa** [comment]
root@mail:~# apt-get update
Hit:1 http://repository.balt.net/debian stretch InRelease
Ign:2 http://debian.balt.net/debian stretch InRelease
Hit:3 http://debian.balt.net/debian stretch-updates InRelease
Hit:4 http://debian.balt.net/debian stretch-backports InRelease
Hit:5 http://debian.balt.net/debian stretch Release
Hit:6 http://security.debian.org stretch/updates InRelease
Hit:7 https://download.docker.com/linux/debian stretch InRelease
Hit:9 https://packagecloud.io/dokku/dokku/debian stretch InRelease
Reading package lists... Done
root@mail:~# apt-get install dokku herokuish plugin sshcommand dokku-update
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package plugin

replaced plugin with plugn
root@mail:~# apt-get install dokku herokuish plugn sshcommand dokku-update
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dokku : Depends: gliderlabs-sigil but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by josegonzalez** [comment]
Try that last command again? Sorry, I didn't realize all these packages were missing from the debian apt repo...

**Comment by zyriusa** [comment]
it's ok now. dokku installed. Thank you

**Comment by josegonzalez** [comment]
Going to re-open this, as we need to modify the release script to ensure we push assets to all the apt repos.

**Comment by josegonzalez** [comment]
Ah this is fixed for our release process already :)
