### ISSUE TITLE
App currently has a deploy lock in place. Exiting...  

### ISSUE THREAD

**Issue by babarinde** [dokku/dokku#3167]
Description of problem:
Using My CI, I get the error:

> abba-schoolable-core currently has a deploy lock in place. Exiting...  

However when i look through my logs, I see the app following through with the deployment.
A rebuild after initial failure shows:

> Everything up-to-date

- If a deploy is failing or behaving unexpectedly:
  - Application name
abba-schoolable-core
  - The type of application being deployed (node, php, python, ruby, etc.)
php
  - If using buildpacks, which custom buildpacks are in use
heroku-php
  - If using a `Dockerfile`, the contents of that file
Nil

How reproducible:
It appeared that a Build was hanging from my terminal, but the logs showed the build was completed

Steps to Reproduce:
1. Push to an app from terminal
2. Truncate a Build in php
3. Try pushing  using a CI

Actual Results:
abba-schoolable-core currently has a deploy lock in place. Exiting...  

Expected Results:
full build process

Additional info:

**Comment by josegonzalez** [comment]
If you think your build succeeded - it probably didn't to be honest - you can use [apps:unlock](http://dokku.viewdocs.io/dokku/deployment/application-management/#unlocking-app-deploys) to unlock deploys again. Deploys for a given app are locked until the complete, whether thats successful or not. It's possible you just killed the deploy in some other way.

**Comment by babarinde** [comment]
It did suceed, I see my changes in my app using

> dokku enter abba-schoolable-core
and doing a cat on the file changed.
am I missing something?

**Comment by josegonzalez** [comment]
Okay well if you say it succeeded, thats fine. You can still use the `apps:unlock` method to continue on.

**Comment by babarinde** [comment]
Used the apps:lock command

> dokku apps:unlock abba-schoolable-core

Another push to the CI fails with the same error and my logs shows

> Starting httpd...

At the end

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? Also include the deploy log output. It is helpful for debugging problems. Thanks.
