### ISSUE TITLE
E: Some index files failed to download. They have been ignored, or old ones used instead.

### ISSUE THREAD

**Issue by FilipLukac** [dokku/dokku#3174]
Hello there,

at first, I apologize for no including issue template, but I have problem with the fresh installation of dokku. I'm using dokku in 10 severals projects and never had this error.

Platform
`digitalocean Ubuntu 16.04` (installed before 1h ago )

```
root@frank-production:~# sudo DOKKU_TAG=v0.12.5 bash bootstrap.sh
Preparing to install v0.12.5 from https://github.com/dokku/dokku.git...
--> Ensuring we have the proper dependencies
E: Failed to fetch http://ams2.mirrors.digitalocean.com/ubuntu/dists/xenial-updates/main/source/Sources.xz  Hash Sum mismatch
E: Failed to fetch http://ams2.mirrors.digitalocean.com/ubuntu/dists/xenial-updates/universe/source/Sources.xz
E: Failed to fetch http://ams2.mirrors.digitalocean.com/ubuntu/dists/xenial-updates/universe/binary-amd64/Packages.xz
E: Failed to fetch http://ams2.mirrors.digitalocean.com/ubuntu/dists/xenial-updates/universe/i18n/Translation-en.xz
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Is there any problem with downloading dependencies (they does not exists?)

**Comment by josegonzalez** [comment]
Those seem like issues with digitalocean's apt mirrors, _not_ anything referencing Dokku. They may have been uploading new packages as you hit that. Maybe just try again?

**Comment by FilipLukac** [comment]
Thank you so much for quick reply @josegonzalez I thought that. Already tried but nothing new appears... Will try a bit later, you can Close this issue and again, thank you so much !

**Comment by FilipLukac** [comment]
For someone, who have the same problem, solved by:

```
sudo apt-get clean
sudo rm -rf /var/lib/apt/lists/
sudo apt-get update --fix-missing
```
