### ISSUE TITLE
dokku:rebuild fails when run in the root user's home directory

### ISSUE THREAD

**Issue by alexgleason** [dokku/dokku#3178]
Weird issue in the latest version (on Ubuntu 17.10):

```
root@liberationphilly:~# dokku ps:rebuild bylaws
Preparing /tmp/dokku_git.NLSC (identifier dokku_git.NLSC)
/var/lib/dokku/plugins/available/git/functions: line 48: popd: /root: Permission denied
```

I'm inside of `/root`, therefore `popd` refuses to work. Simply changing into another directory fixes the problem, though I was very confused by this at first.

Workaround:

```
root@liberationphilly:~# cd /home/dokku
root@liberationphilly:/home/dokku# dokku ps:rebuild bylaws
Preparing /tmp/dokku_git.Ioud (identifier dokku_git.Ioud)
~/bylaws /tmp/dokku_git.Ioud ~
/tmp/dokku_git.Ioud ~
-----> Cleaning up...
-----> Building bylaws from herokuish...
-----> Adding BUILD_ENV to build environment...

...etc. it proceeds, finishes, and works.
```

As you can see I'm running the exact same command, just in a different directory. It doesn't seem to matter that I am the root user and own the directory I'm in, popd doesn't want to mess with /root.

I was thrown off by this since /root is the default directory for the root user when you shell in. I'm not sure you can really avoid this problem, but maybe you could include a warning?

Thanks!

**Comment by josegonzalez** [comment]
This is what is going on: https://github.com/dokku/dokku/issues/2978#issuecomment-351288650

Woof. This is going to be a bit difficult to fix globally, since some commands require relative paths. Good catch though!

**Comment by josegonzalez** [comment]
Closing as a pull request is open. Thanks for filing the issue!
