### ISSUE TITLE
bug: http -> https redirect

### ISSUE THREAD

**Issue by fruitl00p** [dokku/dokku#3180]
Description of problem: Why trying to letsencrypt an already LE-ed site (because i.e. an extra domain was added) the http -> https redirect is faulty. [The nginx.sigil template includes a `:` where it shouldn't.](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L15)

`return 301 https://$host:{{ $.PROXY_SSL_PORT }}$request_uri;`
should read
`return 301 https://$host{{ $.PROXY_SSL_PORT }}$request_uri;`
if i'm not mistaken... ?

Thanks!

**Comment by joshmanders** [comment]
No it needs the `:` to separate the port from the host.

**Comment by josegonzalez** [comment]
@fruitl00p are you seeing an actual issue here?

**Comment by fruitl00p** [comment]
@joshmanders true, but since {{ $.PROXY_SSL_PORT }} might be empty, it could (and in my case) led to the nginx config written as:
`
 return 301 https://$host:$request_uri;
`
Which leads to redirects including the `:` as the actual `Location`-header:
`curl -I http://example.net' resulting in `Location: https://example.net:/`

That location header works most of the time, but fails on the client used by Letsencrypt... Thus failing to renew the cert... Now you could argue that it's their problem, but the header seems malformed to me...

**Comment by josegonzalez** [comment]
When is that empty? I think _that_ is a bug we need to fix, and if you have a way for me to consistently reproduce it, we can work on that :)

**Comment by joshmanders** [comment]
Should be setting the port as `443` shouldn't it?

**Comment by fruitl00p** [comment]
@josegonzalez haven't been able te reproduce it in a separate environment... All i know is that the app is a dockerfile deployment, resulting in the following dokku config:
`
DOKKU_APP_RESTORE:      1
DOKKU_APP_TYPE:         dockerfile
DOKKU_CHECKS_DISABLED:  _all_
DOKKU_DOCKERFILE_PORTS: 443/tcp 80/tcp
DOKKU_PROXY_PORT_MAP:   http:80:80 https:443:80
`
This then results in the aforementioned nginx config line: `return 301 https://$host:$request_uri;`

Could it be that the root cause is the dockerfile deployment?

**Comment by josegonzalez** [comment]
Closing as I don't currently have a way to reproduce this. If someone can bring up a way to do so, I'd be happy to turn it into a test case and resolve.
