### ISSUE TITLE
Snap package support

### ISSUE THREAD

**Issue by Mikerr1111** [dokku/dokku#3185]
I've done the installation process for Dokku before. I was thinking that the installation process could possibly be improved by having a [Snap](https://snapcraft.io/) version that would help Dokku be installed easily across a wide range of Linux distros such as [Ubuntu, Debian, Arch Linux, Solus, Fedora, and CentOS 7](https://docs.snapcraft.io/core/install).

**Comment by josegonzalez** [comment]
I have no experience with snap, so "Pull requests welcome."

**Comment by Mikerr1111** [comment]
I will start working on it.

**Comment by josegonzalez** [comment]
I'm going to close this for now. I'll still accept the pull request and work with you to get it merged/into our release process as appropriate, but I don't think we necessarily need a standalone issue for it.
