### ISSUE TITLE
ssh-keys:add documentation seems to contradict the code

### ISSUE THREAD

**Issue by dbohdan** [dokku/dokku#3188]
## Description of problem

The [user management documentation](http://dokku.viewdocs.io/dokku~v0.12.5/deployment/user-management/) for v0.12.5 states that if you are an admin you can run the command `ssh-keys:add` as the SSH user `dokku`:

>Admin users and root can also add keys remotely:
>`cat ~/.ssh/id_rsa.pub | ssh dokku@dokku.me ssh-keys:add KEY_NAME`

However, the action appears to [require](https://github.com/dokku/dokku/blob/a6b047805c3caab3ac544a79fa849b50a995e962/dokku#L81) that you SSH in as `root`.

## Steps to Reproduce
1\. Provision a fresh Dokku VM. E.g., here is the Vagrantfile I used.

```ruby
$script = <<-SCRIPT
wget https://raw.githubusercontent.com/dokku/dokku/v0.12.5/bootstrap.sh
sudo DOKKU_TAG=v0.12.5 bash bootstrap.sh
ip a
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, inline: $script
  config.vm.network "public_network"  # security hazard on untrusted networks

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
  end
end
```
2\. Add your public key via `dokku-installer`.
3\. Run `cat ~/.ssh/id_rsa.pub | ssh dokku@${host} ssh-keys:add foo`

## Actual Results
```none
This command must be run as root
```
## Expected Results
The key being added.

**Comment by josegonzalez** [comment]
Ah, stale docs. The error is correct, docs are bad.

**Comment by dbohdan** [comment]
:+1:
