### ISSUE TITLE
validate_nginx failed

### ISSUE THREAD

**Issue by luizpicolo** [dokku/dokku#3201]
When using the dokku ps: restart MyAPP command I get the following snippet of output and the application does not start.

    =====> renaming container (627b1699ac47) sistemas.na.web.1 to sistemas.na.web.1.1526922122
    =====> renaming container (7d3360175921) gallant_murdock to sistemas.na.web.1
    -----> Configuring sistemas.na.ifms.edu.br...(using built-in template)
    -----> Creating http nginx.conf
    -----> Running nginx-pre-reload
           Reloading nginx
    nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
    nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
    2018/05/21 13:02:04 [emerg] 10414#0: open() "/var/log/nginx/access.log" failed (2: No such file or directory)
    nginx: configuration file /etc/nginx/nginx.conf test failed
           validate_nginx failed. contents of /home/dokku/siai/nginx.conf below...

    server {
      listen      [::]:2697;
      listen      2697;
      
      access_log  /var/log/nginx/siai-access.log;
      error_log   /var/log/nginx/siai-error.log;

      location    / {

        gzip on;
        gzip_min_length  1100;
        gzip_buffers  4 32k;
        gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;

**Comment by josegonzalez** [comment]
@luizpicolo did you figure out what the problem was here?

**Comment by luizpicolo** [comment]
@joseganzalez Yes, I do not know why, the nginx directory had been excluded. I created it again and gave the permissions. Work.
