### ISSUE TITLE
How to keep alive services (nginx and lxc)?

### ISSUE THREAD

**Issue by matiasmm** [dokku/dokku#3202]
Hi, I don't know if this is the right place to ask questions, I couldn't find any other place than the issues section. My apologies if this is not the right place.

I've just installed dokku in a brand new ubuntu 16.04 box with 2GB ram memory. I've also added a very simple app to make sure dokku is working.

It works fine for a while but, after some minutes, nginx service stops working along with the one container for the app I used for testing.

Is there any good way to keep these services up and running?

**Comment by joshmanders** [comment]
They should stay up by default. Can you please provide the information requested in the issue template.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

As well, how do you know things "stop working"? Are nginx and your container stopped? Can you show the output of `ps auxf` on the host? Also, if you could take a look at your syslog, that might show if you're seeing oomkills.

**Comment by matiasmm** [comment]
Sorry, here is all the updated information, you can find the url for a gist below.

Output of the following commands

Description of problem:
Nginx and container works, but after a while they stop working and they need to be restarted manually. 
They do work if I start nginx manually and if I redeploy the application after that.

Output of the following commands

I created this gist with all the output of the commands you requested: 
https://gist.github.com/matiasmm/6b1d9ee56825e74f4d230c2b89cabf79
I'm deploying to test: https://github.com/matiasmm/hello-world


Environment details (AWS, VirtualBox, physical, etc.):
- Linode box with ubuntu 16.04 (xenial), 2GB of ram and 
50GB Storage
1 CPU Core
2TB XFER

How was Dokku installed?:
  wget https://raw.githubusercontent.com/dokku/dokku/v0.12.7/bootstrap.sh
  sudo DOKKU_TAG=v0.12.7 bash bootstrap.sh


How reproducible:

Steps to Reproduce:
1. created a new linode box with 2MB of ram with ubuntu 16.4
2. install dokku with bootstrap.sh
3. deployed app with `git push dokku master`
4. See if the app is running (it will be), wait for a while

Actual Results:
Both, nginx and the container stop working

Expected Results:


Additional info:
I'm starting to believe it might be failing because of hardware issues...nginx service stop (which is not common) and `nginx -t` succeeds.
Everything works when I run nginx start, but then it breaks

**Comment by joshmanders** [comment]
@matiasmm I edited your comment as you made a typo and I didn't want anyone to get hung up on that minor typo. (2MB -> 2GB)

**Comment by matiasmm** [comment]
After upgrading from Ubuntu 16.04 to 18.04, this issue is not showing up anymore. So I guess it only happened in ubuntu 16.04.

Thanks @josegonzalez for all the help!

**Comment by josegonzalez** [comment]
In case anyone stumbles across this, seems maybe related to https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864
