### ISSUE TITLE
Let BUILDPACK_URL support multiple buildpacks

### ISSUE THREAD

**Issue by jxltom** [dokku/dokku#3206]
Currently for using multiple buildpacks, only ```.buildpacks``` which in the root directory is supported. This makes buildpacks for app is fixed.

Is it better to let ```BUILDPACK_URL``` as environment variables support multiple buildpacks? Then app which is deployed into different machine could use different buildpacks.

This is useful when app is deployed to machines in different network area and buildpack maybe blocked in certain network area.

**Comment by josegonzalez** [comment]
This isn't going to happen. Heroku doesn't support multiple buildpacks here, and us supporting multiple buildpacks would deviate from how that works.

Their alternative is a `buildpacks` command family that allows managing a set of buildpacks per application. If you would like to contribute that, feel free to submit a PR. There are no plans to write this at the moment.

Closing as there isn't anything to do here.

**Comment by joshmanders** [comment]
@josegonzalez what would be the best route to go about adding support for that family of commands? Just have it write to `/home/dokku/APP/.buildpacks` itself?

**Comment by josegonzalez** [comment]
Probably worth investigating the order in which heroku supports setting buildpacks - `.buildpacks`, buildpack api/commands, `heroku.yml`, `app.json`, `BUILDPACK_URL`, and autodetection all come to mind.

Herokuish itself only supports `.buildpacks` and `BUILDPACK_URL`, so this would need to jack into that somehow.
