### ISSUE TITLE
Dokku image optimization

### ISSUE THREAD

**Issue by mtzfactory** [dokku/dokku#3216]
Hi,

I would like to know if there is any option or trick to optimize the docker image size after a deployment...

Regards,
mtz

**Comment by josegonzalez** [comment]
There is no "trick" for slimming down buildpack deploys. However, you can use a [dockerfile](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/) for your application builds, at which point you can control every part of the build process. Please consult the documentation for further details on how dockerfile deploys work.
