### ISSUE TITLE
Question: pull from server

### ISSUE THREAD

**Issue by internetstyle** [dokku/dokku#3217]
I accidentally lost my local git repository with 8 days of work, however the files are on the dokku production server.

Question: is there any way to make git pull or clone from dokku server?

Thanks.

**Comment by joshmanders** [comment]
Yes, your server is just another git repo, just like here on github. Just do `git clone dokku@your.server.ip:project` and you should have it again.

**Comment by internetstyle** [comment]
Thank you, but not working:

With user dokku@ 

`Permission denied (publickey).`

With correct credentials:

```
Cloning into 'my-project'...
fatal: 'my-project' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
What can be?

**Comment by SamirMokiem** [comment]
Firewall can be a problem

**Comment by josegonzalez** [comment]
Not knowing anything about your server, I would say that the key you have locally isn't the same as the one you initially added to the `dokku` user via the `ssh-keys` plugin. You can use the [following directions](http://dokku.viewdocs.io/dokku/deployment/user-management/) to update your dokku user's ssh keys.
