### ISSUE TITLE
Horizontal scaling for multiple workers

### ISSUE THREAD

**Issue by bastienrobert** [dokku/dokku#3228]
I've dokku installed on a material server and I want to add a second material server because there's a lot of trafic so I need more power. 
Here's what I'm talking about: a "manager" server used to manage my two "workers" (instances) of Dokku. Maybe it can work with Docker using [Swarm](https://docs.docker.com/engine/swarm/join-nodes/) but I don't know if it can be compatible with Dokku.

**Comment by josegonzalez** [comment]
Dokku is not compatible with swarm at this time.

To be more clear, there are two different versions of swarm:

- Docker swarm: a standalone thing, only way to cluster "natively" prior to 1.12. Requires that we parse out the `DOCKER_HOST` and set it in the right places. I had a hack that "worked" except we needed to start thinking about how to handling other things more generically (networking, load balancing, etc.).
- Swarm Mode: This is the new swarm. It works in a completely different way for scheduling, so wouldn't work at all without writing a custom scheduler plugin for Dokku.

Scheduler plugins are new as of 0.12, and we only include a docker-local scheduler plugin. You are free to write your own plugin to integrate with an alternative scheduler, and I recommend you look into [this](http://dokku.viewdocs.io/dokku/advanced-usage/schedulers/docker-local/) list of plugin hooks you'll need to modify.

Hope this helps.
