### ISSUE TITLE
No output from dokku run

### ISSUE THREAD

**Issue by abstractcoder** [dokku/dokku#323]
dokku run doesnt produce any output. This can be reproduced by running `dokku run www echo "Hello"`

**Comment by jmatsuba** [comment]
> I am encountering a related issue: the first output of an interactive command is shown, but nothing after, aka
> 
> ```
> root@ucevents:~# dokku run app rails c
> Connecting to database specified by DATABASE_URL
> Loading production environment (Rails 3.2.13)
> irb(main):001:0> Event.all
> ```
> 
> @plietar

Ever figure this out? I'm running into this now too.
