### ISSUE TITLE
Is there a way to set worker-specific ENV variable? 

### ISSUE THREAD

**Issue by hippich** [dokku/dokku#3230]
With `dokku config:set` I can set per-app variables. But I need to set per-worker. Is there any way to do that?

**Comment by josegonzalez** [comment]
There is no way to do that, and that isn't a workflow I think we should support. It would increase the complexity of Dokku and make it work differently enough from Heroku to make it confusing to new users.

If you need process specific environment variables, I recommend you inject them by switching on flags passed to the worker process.
