### ISSUE TITLE
https co taking to me to default nginx page

### ISSUE THREAD

**Issue by mandalalifeart** [dokku/dokku#3233]
my https://site is taking me to default nginx page , while my http version taking me to my dokku page ,

how can I link https traffic to same database as http

thank you

**Comment by malixsys** [comment]
Try the `letsencrypt` plug-in ?

**Comment by josegonzalez** [comment]
Do you have an ssl certificate setup?

I think you might have better luck asking in our [slack channel](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/) for this sort of support.
