### ISSUE TITLE
Error pages documentation is weak and needs improving

### ISSUE THREAD

**Issue by kgrosvenor** [dokku/dokku#3239]
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

## Description of problem

I need a way to set 404.html for example whilst my app is in some downtime, i want to change the message on 500 also, how do i do this and also where do the current dokku templates live on the server?

### Steps to Reproduce

1.
2.
3.

### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> You may also run `dokku report` without any arguments to display the top-level reporting information.

### Additional information

- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

**Comment by josegonzalez** [comment]
At the moment, the location for those error messages is in `/var/lib/dokku/data/nginx-vhosts/dokku-errors`, and they are shared for _all_ applications. To customize them for a specific app, you'll need to vendor the `nginx.conf.sigil` file as referenced [here](http://dokku.viewdocs.io/dokku/configuration/nginx/) and change their paths to point elsewhere.

If you modify the ones in the core, I can't say that your changes will stick/they won't be overwritten on upgrades. Best bet is to customize your `nginx.conf.sigil` and provision the error files separately.
