### ISSUE TITLE
dokku CLI does not recognize descriptor redirects

### ISSUE THREAD

**Issue by moltar** [dokku/dokku#3250]
## Description of problem

I need to be able to initiate backups from a CI system before a project is deployed. I am trying to do the following:

```
ssh dokku@host -- "postgres:export production > /tmp/backup.dump"
```

However, the `dokku` command does not recognize that I want to redirect the output and instead just outputs everything to `STDOUT`.

### How reproducible

```
ssh dokku@www.amzdemo.xyz -- "ps:report > /tmp/report"
```

#### Actual Results

```
App name must begin with lowercase alphanumeric character
Invalid flag passed, valid flags: --processes --deployed --running --restore --restart-policy
```

#### Expected Results

File `/tmp/report` to be created on the remote machine with the output of `ps:report`.

### `dokku report APP_NAME` output

Same as #3249

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Digital Ocean + upgrade

**Comment by josegonzalez** [comment]
This has nothing to do with Dokku the cli, but with `ssh`. You're basically saying that those are arguments to the `dokku` binary (which gets auto-executed by `ssh dokku@host`) and it's not recognizing them.

Regarding the postgres redirect issue, I would file an enhancement ticket in the `dokku-redis` plugin issue tracker. While that plugin is official, this issue tracker isn't the best place for them, and I also centralize all enhancements to the datastore plugins in the dokku-redis issue tracker.
