### ISSUE TITLE
Error deploying: fatal: unable to run cd: file does not exist

### ISSUE THREAD

**Issue by KerryRitter** [dokku/dokku#3253]
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

### How reproducible

Reproduced on two servers, multiple apps

### Steps to Reproduce

1. Set buildpack to https://github.com/jincod/dotnetcore-buildpack#v2.1.301.
2. Push an ASP.NET Core app.

#### Actual Results

```
remote: -----> Cleaning up...
remote: -----> Building intapi from herokuish...
remote: -----> Adding BUILD_ENV to build environment...
remote:        -----> Fetching custom buildpack
remote:        -----> ASP.NET Core app detected
remote:        Installing dotnet
remote:        dotnet-2.1.301.tar.gz from cache folder
remote:        publish /tmp/build/H2I.Integrations.Web/H2I.Integrations.Web.csproj
remote:        Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
remote:        Copyright (C) Microsoft Corporation. All rights reserved.
remote:
remote:        Restoring packages for /tmp/build/H2I.Integrations.DataAccess/H2I.Integrations.DataAccess.csproj...
remote:        Generating MSBuild file /tmp/build/H2I.Integrations.DataAccess/obj/H2I.Integrations.DataAccess.csproj.nuget.g.props.
remote:        Generating MSBuild file /tmp/build/H2I.Integrations.DataAccess/obj/H2I.Integrations.DataAccess.csproj.nuget.g.targets.
remote:        Restore completed in 335.42 ms for /tmp/build/H2I.Integrations.DataAccess/H2I.Integrations.DataAccess.csproj.
remote:        Restoring packages for /tmp/build/H2I.Integrations.Web/H2I.Integrations.Web.csproj...
remote:        Generating MSBuild file /tmp/build/H2I.Integrations.Web/obj/H2I.Integrations.Web.csproj.nuget.g.props.
remote:        Generating MSBuild file /tmp/build/H2I.Integrations.Web/obj/H2I.Integrations.Web.csproj.nuget.g.targets.
remote:        Restore completed in 1.34 sec for /tmp/build/H2I.Integrations.Web/H2I.Integrations.Web.csproj.
remote:        Restore completed in 22.4 ms for /tmp/build/H2I.Integrations.Web/H2I.Integrations.Web.csproj.
remote:        /tmp/build/.heroku/dotnet/sdk/2.1.301/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Data.Tools.Schema.Sql, Version=13.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/tmp/build/H2I.Integrations.DataAccess/H2I.Integrations.DataAccess.csproj]
remote:        /tmp/build/.heroku/dotnet/sdk/2.1.301/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Data.Tools.Schema.Sql.UnitTesting, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk.
If this reference is required by your code, you may get compilation errors. [/tmp/build/H2I.Integrations.DataAccess/H2I.Integrations.DataAccess.csproj]
remote:        /tmp/build/.heroku/dotnet/sdk/2.1.301/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Data.Tools.Schema.Sql.UnitTestingAdapter, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/tmp/build/H2I.Integrations.DataAccess/H2I.Integrations.DataAccess.csproj]
remote:        H2I.Integrations.DataAccess -> /tmp/build/H2I.Integrations.DataAccess/bin/Release/netcoreapp2.1/H2I.Integrations.DataAccess.dll
remote:        H2I.Integrations.Web -> /tmp/build/H2I.Integrations.Web/bin/Release/netcoreapp2.1/linux-x64/H2I.Integrations.Web.dll
remote:        H2I.Integrations.Web -> /tmp/build/heroku_output/
remote:        -----> Discovering process types
remote:        Procfile declares types -> web
remote: -----> Releasing intapi (dokku/intapi:latest)...
remote: -----> Deploying intapi (dokku/intapi:latest)...
remote: -----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
remote: -----> App Procfile file found (/home/dokku/intapi/DOKKU_PROCFILE)
remote: -----> DOKKU_SCALE file found (/home/dokku/intapi/DOKKU_SCALE)
remote: =====> web=1
remote: -----> Attempting pre-flight checks
remote:        For more efficient zero downtime deployments, create a file CHECKS.
remote:        See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
remote:        CHECKS file not found in container: Running simple container check...
remote: -----> Waiting for 10 seconds ...
remote: 977c8544211b8ba96cdf1b6fb23da81982b726009953a5888129749b06f00a6e
remote: App container failed to start!!
remote: =====> intapi web container output:
remote:        /tmp/bashenv.876820103: line 564: ./H2I.Integrations.Web: Is a directory
remote:        setuidgid: fatal: unable to run cd: file does not exist
remote:        /tmp/bashenv.134636560: line 564: ./H2I.Integrations.Web: Is a directory
remote:        setuidgid: fatal: unable to run cd: file does not exist
remote:        /tmp/bashenv.863000092: line 564: ./H2I.Integrations.Web: Is a directory
remote:        setuidgid: fatal: unable to run cd: file does not exist
remote:        /tmp/bashenv.472216656: line 564: ./H2I.Integrations.Web: Is a directory
remote:        setuidgid: fatal: unable to run cd: file does not exist
remote:        /tmp/bashenv.342639763: line 564: ./H2I.Integrations.Web: Is a directory
remote:        setuidgid: fatal: unable to run cd: file does not exist
remote:        /tmp/bashenv.838075374: line 564: ./H2I.Integrations.Web: Is a directory
remote:        setuidgid: fatal: unable to run cd: file does not exist
remote:        /tmp/bashenv.088644215: line 564: ./H2I.Integrations.Web: Is a directory
remote:        setuidgid: fatal: unable to run cd: file does not exist
remote: =====> end intapi web container output
To if02.h2itechnology.com:intapi
```

#### Expected Results

Application deploys as expected.

### `dokku report APP_NAME` output

-----> uname: Linux dokku-s-1vcpu-1gb-nyc1-01 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           2000         265          98          30        1636        1497
       Swap:             0           0           0
-----> docker version: 
       Client:
        Version:	17.12.0-ce
        API version:	1.35
        Go version:	go1.9.2
        Git commit:	c97c6d6
        Built:	Wed Dec 27 20:11:19 2017
        OS/Arch:	linux/amd64
       
       Server:
        Engine:
         Version:	17.12.0-ce
         API version:	1.35 (minimum version 1.12)
         Go version:	go1.9.2
         Git commit:	c97c6d6
         Built:	Wed Dec 27 20:09:53 2017
         OS/Arch:	linux/amd64
         Experimental:	false
-----> docker daemon info: 
       Containers: 23
        Running: 5
        Paused: 0
        Stopped: 18
       Images: 62
       Server Version: 17.12.0-ce
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 89623f28b87a6004d4b785663257362d1658a729
       runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
       init version: 949e6fa
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.4.0-133-generic
       Operating System: Ubuntu 16.04.3 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 1.953GiB
       Name: dokku-s-1vcpu-1gb-nyc1-01
       ID: A2JY:SWKD:NEE6:YCS2:2LUY:OJ4L:63KJ:C4PE:BXJQ:OJYX:J5DZ:INYG
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.4.3
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v188
         heroku-buildpack-nodejs    v123
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v136
         heroku-buildpack-java      v62
         heroku-buildpack-gradle    v27
         heroku-buildpack-scala     v82
         heroku-buildpack-play      v26
         heroku-buildpack-php       v137
         heroku-buildpack-go        v89
         buildpack-nginx            v9
-----> dokku version: 0.12.12
-----> dokku plugins: 
       plugn: 0.3.0
         00_dokku-standard    0.12.12 enabled    dokku core standard plugin
         20_events            0.12.12 enabled    dokku core events logging plugin
         apps                 0.12.12 enabled    dokku core apps plugin
         build-env            0.12.12 enabled    dokku core build-env plugin
         certs                0.12.12 enabled    dokku core certificate management plugin
         checks               0.12.12 enabled    dokku core checks plugin
         common               0.12.12 enabled    dokku core common plugin
         config               0.12.12 enabled    dokku core config plugin
         docker-options       0.12.12 enabled    dokku core docker-options plugin
         domains              0.12.12 enabled    dokku core domains plugin
         enter                0.12.12 enabled    dokku core enter plugin
         git                  0.12.12 enabled    dokku core git plugin
         letsencrypt          0.8.8 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.12.12 enabled    dokku core logs plugin
         mysql                1.3.0 enabled    dokku mysql service plugin
         network              0.12.12 enabled    dokku core network plugin
         nginx-vhosts         0.12.12 enabled    dokku core nginx-vhosts plugin
         plugin               0.12.12 enabled    dokku core plugin plugin
         proxy                0.12.12 enabled    dokku core proxy plugin
         ps                   0.12.12 enabled    dokku core ps plugin
         repo                 0.12.12 enabled    dokku core repo plugin
         scheduler-docker-local 0.12.12 enabled    dokku core scheduler-docker-local plugin
         shell                0.12.12 enabled    dokku core shell plugin
         ssh-keys             0.12.12 enabled    dokku core ssh-keys plugin
         storage              0.12.12 enabled    dokku core storage plugin
         tags                 0.12.12 enabled    dokku core tags plugin
         tar                  0.12.12 enabled    dokku core tar plugin
=====> intapi app information
       App dir:                       /home/dokku/intapi       
       Git sha:                       e833d85                  
       Deploy source:                 git                      
       Locked:                        true                     
=====> intapi ssl information
       Ssl dir:                       /home/dokku/intapi/tls   
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> intapi checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> intapi docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> intapi domains information
       Domains app enabled:           true                     
       Domains app vhosts:            intapi.if02.h2itechnology.com 
       Domains global enabled:        true                     
       Domains global vhosts:         if02.h2itechnology.com   
=====> intapi git information
       Git rev env var:               GIT_REV                  
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
=====> intapi network information
       Network bind all interfaces:   false
       Network listeners:             172.17.0.6:80
=====> intapi proxy information
       Proxy enabled:                 true                     
       Proxy type:                    nginx                    
       Proxy port map:                http:44393:44393         
=====> intapi ps information
       Processes:                     1                        
       Deployed:                      true                     
       Running:                       true                     
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Status web.1:                  running    (CID: 7464dd11604f)
=====> intapi scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> intapi storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:                                     

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

DigitalOcean droplet for v0.11, upgraded to v0.12.12.

### Additional information

Using herokuish, buildpack https://github.com/jincod/dotnetcore-buildpack

**Comment by josegonzalez** [comment]
Closing as we do not do buildpack support on the dokku issue tracker. This isn't the best venue for doing that, unfortunately. Please reach out on slack/irc and wait for a response.
