### ISSUE TITLE
Equivalent of heroku buildpacks command

### ISSUE THREAD

**Issue by philm** [dokku/dokku#3256]
Would love to see the equivalent of Heroku's recently added support for multiple buildpacks, e.g. ```heroku buildpacks:add --index 1 heroku/nodejs```

Not a high priority since the .buildpacks approach works fine but we have had customers ask about it in the past. Posting this suggestion here to see if others would find it useful.

Ref: https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

**Comment by josegonzalez** [comment]
That would be pretty cool. I think managing the dockerfile vs buildpack support can be very confusing, so we should do some discovery to see how heroku handles the various options (they also support a heroku.yml and app.json for this).

As you mentioned this was requested by client's, isthis work you'd be interested in _specifically_ sponsoring?

**Comment by josegonzalez** [comment]
Regarding next steps:

- trying the various methods on heroku to see what order of operations/merging it applies would be useful for figuring out how we should replicate it.
  - `BUILDPACK_URL` env var
  - `.buildpacks` file
  - `app.json` standard
  - `heroku.yml` standard
  - `buildpacks:*` command and relevant api
  - `Dockerfile` support
- Making a decision on which of these we should support
  - `BUILDPACK_URL`: Simple, but only handles a single buildpack
  - `.buildpacks`: Nicer, but requires committing a file
  - `app.json`: Seems deprecated/unmaintained. Unfortunate, as its a great standard
  - `heroku.yml`: unclear on it's future, heroku-only
  - `buildpacks:*`: nice UX, but maybe cribs on the other files/standards?
  - `Dockerfile` support: we have something that does "detection" of how to build (buildpack vs dockerfile), and it might make sense for us to standardize this somehow.

I think if we can figure out how they cascade/override, the technical implementation might be to:

- use the `post-extract` hook to merge the list into one place
- write the list of buildpacks into `.buildpacks` within the repo
- ensure herokuish respects the format correctly
- ensure we respect `Dockerfile` building

I'd _love_ to make this be "refactor our builder support". Ideally folks can create arbitrary `builder` plugins - similar to how we handle schedulers. I'd _love_ to have it be possible to build a builder plugin for, say, lambda functions. Having a "selector" function for this - what builder should we use, and how should that builder plugin function? - seems relatively straightforward.

@michaelshobbs thoughts on the above? I think you worked on our initial Dockerfile support, so might have some insight into this/how you'd like to see such functionality evolve.

**Comment by philm** [comment]
@josegonzalez it was requested by customers of Healthcare Blocks - already a sponsor. :)

I love the idea of builder plugins. Would provide more flexibility and ability to handle unique build scenarios.

**Comment by josegonzalez** [comment]
Lets see how much I can get done in ~12 hours (just eyeballed the OC sponsorship :P).

For future reference, I previously worked on the builder stuff [here](https://github.com/dokku/dokku/pull/2900) though it was never merged.

**Comment by josegonzalez** [comment]
That only took all day...

Apologies for the wait, but closing now that there is a pull request open - this will land in the next minor release.
