### ISSUE TITLE
Get/Store IP addresses and ports of non-web containers

### ISSUE THREAD

**Issue by lazyatom** [dokku/dokku#3258]
## High-level Plan

- Ensure we call `network-write-ipaddr` for all process types
- Add support for fetching non-web listeners to `network-get-listeners` as the second variable
- Keep track of all listener types in `DOKKU_APP_${PROC_TYPE}_LISTENERS`
- Append the above variable mapping to the list of variables passed to the nginx template via sigil
- Update the docs

---

## Original Comment

I would like to be able to deploy an application and route some requests to a non-`web` process (for example, a Rails application with a separate Node.js process that deals with streaming connections). 

At the moment, only the `web` containers are available for use in the `nginx.conf.sigil` template (via the `$.DOKKU_APP_LISTENERS` variable). I can see for simplicity that it might make sense not to add non-web containers to `$.DOKKU_APP_LISTENERS`, but at the moment I don't think I can even write a custom plugin or Buildpack to add the behaviour that I want, without replicating the parts of Dokku's internals to determine what the internal IPs & ports of those other containers are.

From what I can tell, the `$.DOKKU_APP_LISTENERS` value is constructed from the contents of the files `IP.web.*` and `PORT.web.*` in the `/home/dokku/<app>` directory. Would it be feasible to have deployment write out `IP.<proctype>.<instance>` and `PORT.<proctype>.instance` files for all containers, rather than just web ones? With that, I'd be able to write a plugin that modified the nginx configuration to my needs.

**Comment by josegonzalez** [comment]
Sure. Want to file a pull request?

**Comment by josegonzalez** [comment]
I added a high-level plan if anyone wants to pickup the work :)

**Comment by ppawlak** [comment]
I have a use case for this.
I have an app which defines 2 _gunicorn_ processes. I would like these 2 processes to be web-accessible on 2 different domain names.

I currently can't find a solution on how to do this with a single app. What are my options until this issue get implemented? Deploy the same code on 2 different apps?

**Comment by josegonzalez** [comment]
Even with the high-level plan implemented in this issue, we will not be able to associate a domain to a given process within an app without manual work on the part of the user (you'd need to supply a custom nginx.conf.sigil). Thus, I think your best bet will be to deploy the same code to 2 separate applications.

**Comment by ppawlak** [comment]
@josegonzalez Thanks for the quick reply! I will do this

Actually code won't be exactly the same as I will 2 different _Procfile_. I can handle this with a code branch or is there a way to specify an other _Procfile_ when deploying?

**Comment by josegonzalez** [comment]
You can push an arbitrary branch to an arbitrary app - see our git docs for an example. There is no way to specify a Procfile for an app.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
