### ISSUE TITLE
CHECKS file ignored for Dockerfile deployments

### ISSUE THREAD

**Issue by heyarne** [dokku/dokku#3263]
## High level Spec

- [ ] Extend [dockfmt](https://github.com/jessfraz/dockfmt/) to add a command to show the workdir for a specific stage of a dockerfile (or at least just latest)
- [ ] Package dockfmt in deb/rpm files (with permission from upstream!) and host on packagecloud.
- [ ] Modify [Docker local deploying](https://github.com/dokku/dokku/blob/f80b152c9bcf9ef1c2ab0797a6611399cc923532/plugins/scheduler-docker-local/scheduler-deploy#L59) to attach `DOKKU_IS_HEROKUISH` as some form of env var or label when scheduling the container.
- [ ] Modify [checks-deploy](https://github.com/dokku/dokku/blob/f80b152c9bcf9ef1c2ab0797a6611399cc923532/plugins/scheduler-docker-local/check-deploy#L83) to inspect the container to see if its not a herokuish container. If it isn't, inspect the container, grab the `WORKDIR` (default to `/app`) and use that path for the cp.

### Description of problem
I was using [heroku-buildpack-static](https://github.com/heroku/heroku-buildpack-static) via the `BUILDPACK_URL` environment variable. Because it took quite long to deploy a static site I thought I could speed it up by using a `Dockerfile` based on [this one](https://hub.docker.com/r/zzrot/alpine-caddy/). While this sped things up, the CHECKS file in the root is ignored. 

#### `dokku report APP_NAME` output

```
-----> uname: Linux baleine 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:            985         270         152           1         562         554
       Swap:             0           0           0
-----> docker version: 
       Client:
        Version:           18.06.1-ce
        API version:       1.38
        Go version:        go1.10.3
        Git commit:        e68fc7a
        Built:             Tue Aug 21 17:24:51 2018
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server:
        Engine:
         Version:          18.06.1-ce
         API version:      1.38 (minimum version 1.12)
         Go version:       go1.10.3
         Git commit:       e68fc7a
         Built:            Tue Aug 21 17:23:15 2018
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
WARNING: No swap limit support
       Containers: 6
        Running: 4
        Paused: 0
        Stopped: 2
       Images: 38
       Server Version: 18.06.1-ce
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
       runc version: 69663f0bd4b60df09991c08812a60108003fa340
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-33-generic
       Operating System: Ubuntu 18.04.1 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 985.5MiB
       Name: baleine
       ID: EXWZ:ONBR:AQOX:N6LZ:A25W:PYZW:CKXE:FGDS:2IVZ:FWWZ:HTXL:EX7D
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       
-----> sigil version: 0.4.0
-----> herokuish version: 
the input device is not a TTY
```

### Additional information

Dockerfile:
```
FROM zzrot/alpine-caddy
COPY . /var/www/html
```

CHECKS:
```
/ Hello world
```

Deployment log:
```
﻿Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 352 bytes | 352.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Preparing /tmp/dokku_git.t6n8 (identifier dokku_git.t6n8)
remote: ~/xyz /tmp/dokku_git.t6n8 ~/xyz
remote: /tmp/dokku_git.t6n8 ~/xyz
-----> Cleaning up...
-----> Building xyz from dockerfile...
remote: build context to Docker daemon  3.746MB
Step 1/2 : FROM zzrot/alpine-caddy
 ---> 0d58100176b3
Step 2/2 : COPY . /var/www/html
 ---> 12fff9c43867
Successfully built 12fff9c43867
Successfully tagged dokku/xyz:latest
-----> Releasing xyz (dokku/xyz:latest)...
-----> Deploying xyz (dokku/xyz:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> No Procfile found in app image
-----> DOKKU_SCALE file found (/home/dokku/xyz/DOKKU_SCALE)
=====> web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
-----> Configuring xyz.example.com...(using built-in template)
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE:  1
-----> Found previous container(s) (0585336ad11f) named xyz.web.1
=====> Renaming container (0585336ad11f) xyz.web.1 to xyz.web.1.1536267967
=====> Renaming container (240f39be6756) determined_williams to xyz.web.1
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
-----> Shutting down old containers in 60 seconds
=====> 0585336ad11fc9d2e8f96dade4ef277b497e07551a279b1c6c0215f818dc8ac3
=====> Application deployed:
       http://xyz.example.com
       https://xyz.example.com

To example.com:xyz
   c5c97c5..633b257  master -> master

```

**Comment by josegonzalez** [comment]
It needs to be in WORKDIR or /app, as per our docs.

At a bar so can't link, but hope that helps.

**Comment by heyarne** [comment]
I changed the Dockerfile to

```
FROM zzrot/alpine-caddy
WORKDIR /var/www/html
COPY . /var/www/html
```

and I can `GET http://xyz.example.com/CHECKS` after deployment, which returns the correct content, however I still get the same notice about the file not being found in the container. I just checked again and this is actually consistent with the docs:

> For dockerfile-based deploys, the file *must* be in /app/CHECKS within the container. /app is used by default as the root container directory for buildpack-based deploys. ([source](http://dokku.viewdocs.io/dokku~v0.12.12/deployment/zero-downtime-deploys/#customizing-checks))

Changing `WORKDIR /var/www/html` to `COPY CHECKS /app/CHECKS` fixed it. Sorry for not reading the docs properly!

Is there any plan to add the lookup in `WORKDIR` as you stated above?

**Comment by josegonzalez** [comment]
Ah you're right, this isn't a feature at the moment.

Looks like we might be able to leverage [dockfmt](https://github.com/jessfraz/dockfmt/) to show the `WORKDIR` for the last stage in a Dockerfile. If set, we'd use that for the extraction path.

**Comment by josegonzalez** [comment]
@heyarne So looking at this, it's not possible to pull the inherited workdir from a Dockerfile. Since we don't have the source image's Dockerfile in place, we can't inspect it :|

I think the best way forward here is to actually remove the explicit file prefixing in `copy_from_image`. Checking that the image exists and is herokuish before deciding whether to pull `/app/FILE` or just `FILE` will be maybe best. We can expect `docker cp` to use the path relative to `WORKDIR` in cases where its a Dockerfile and we need respect it.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. Thanks for the initial issue!
