### ISSUE TITLE
Host-internal communication between apps

### ISSUE THREAD

**Issue by chrismessiah** [dokku/dokku#3271]
## Description of problem

We have 2 containers, lets call them `A` and `B`, which need to perform some host-internal communication. This can be achieved by sending requests to the network listener addresses which are retrieved by `dokku network:report`.  So if `A` listens on `172.17.0.2:5000` and `B` listens on `172.17.0.10:9090` then they can communicate by exchanging each others IPs and ports. 

So far no problem. However, lets say the host restarts or `A` is deployed again, then it will have a new internal IP and with it the communication is broken. 

After looking into the `dokku-postgres` plugin, I noted that provides a hostname (such as `dokku-postgres-appname-db` as the host in the `DATABASE_URL` env var) which keeps track of the database container.

So the question is - does dokku support hostnames to enable this type of communication but for any deployed containers and not just database-containers? And will the hostnames be available outside the containers so that services which are running on the host can communicate in a similar manner?

### How was Dokku installed?

Digital Ocean 1-Click Image with dokku v0.12.12 on Ubuntu 18.04.

**Comment by chrismessiah** [comment]
One (temporary) solution to this is to pin each container to a specific IP. However, this will prevent any following  deployment as dokku uses zero-downtime deployments. This means that each container must be manually stopped with `dokku ps:stop` in order to deploy.

**Comment by chrismessiah** [comment]
A better way is to achieve this is to create a `docker network` where the containers run and then use the `--network-alias` docker option as a tracker for the ip. However this would require all containers to use the new network and not the default network. 

Still, is really a separate network necessary when dokku already achieves this in the dokku-postgres plugin and on the default network?

**Comment by josegonzalez** [comment]
The dokku plugins use the deprecated `--link` flag to do that, which isn't resilient to linked service restarts - this is rare for services, so not a "real" concern.

The correct way to do this is highlighted in #2085. Closing in favor of continuing investigation there.
