### ISSUE TITLE
copy_from_image breaks when container has no "bash" command

### ISSUE THREAD

**Issue by SebastianApel** [dokku/dokku#3272]
# High Level Plan

- Modify [this](https://github.com/dokku/dokku/blob/8fa869fab25b0d485a189bf73d25fb21ffdbf9c4/plugins/common/functions#L312) to use `sh` instead of `bash`.

# Original Post

## Description of problem

copy_from_image breaks when container has no "bash" command
(as is the case for Alpine Linux (which are busybox based and only have "sh")

ADD: same is true for "dokku enter"

### How reproducible
By using a Dockerfile based deploy with an alphine based image (for example nextcloud:14-fpm-alpine) and then trying to use nginx.conf.sigil

### Steps to Reproduce
see above

#### Actual Results

copy_from_image does not return the file it is looking for (because the container is not running when trying to copy out the file, in my case "nginx.conf.sigil")

#### Expected Results

well, copy the file - even if the container does not exist

### `dokku report APP_NAME` output

-----> uname: Linux v22017124888258539 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
       Speicher:        3951         768         191         140        2992        2700
       Auslagerungsspeicher:        3899          47        3852
-----> docker version: 
       Client:
        Version:           18.06.1-ce
        API version:       1.38
        Go version:        go1.10.3
        Git commit:        e68fc7a
        Built:             Tue Aug 21 17:24:56 2018
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server:
        Engine:
         Version:          18.06.1-ce
         API version:      1.38 (minimum version 1.12)
         Go version:       go1.10.3
         Git commit:       e68fc7a
         Built:            Tue Aug 21 17:23:21 2018
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
WARNING: No swap limit support
       Containers: 59
        Running: 10
        Paused: 0
        Stopped: 49
       Images: 103
       Server Version: 18.06.1-ce
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
       runc version: 69663f0bd4b60df09991c08812a60108003fa340
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.4.0-134-generic
       Operating System: Ubuntu 16.04.5 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 4
       Total Memory: 3.859GiB
       Name: v22017124888258539
       ID: 6KHQ:I42L:HH7N:HHKS:3IXU:TZ5I:FC2K:2NIZ:A6QK:TE7N:XCJW:E5HV
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.4.3
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v188
         heroku-buildpack-nodejs    v123
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v136
         heroku-buildpack-java      v62
         heroku-buildpack-gradle    v27
         heroku-buildpack-scala     v82
         heroku-buildpack-play      v26
         heroku-buildpack-php       v137
         heroku-buildpack-go        v89
         buildpack-nginx            v9
-----> dokku version: 0.12.12
-----> dokku plugins: 
       plugn: 0.3.0
         00_dokku-standard    0.12.12 enabled    dokku core standard plugin
         20_events            0.12.12 enabled    dokku core events logging plugin
         apps                 0.12.12 enabled    dokku core apps plugin
         build-env            0.12.12 enabled    dokku core build-env plugin
         certs                0.12.12 enabled    dokku core certificate management plugin
         checks               0.12.12 enabled    dokku core checks plugin
         common               0.12.12 enabled    dokku core common plugin
         config               0.12.12 enabled    dokku core config plugin
         docker-options       0.12.12 enabled    dokku core docker-options plugin
         domains              0.12.12 enabled    dokku core domains plugin
         enter                0.12.12 enabled    dokku core enter plugin
         git                  0.12.12 enabled    dokku core git plugin
         letsencrypt          0.8.8 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.12.12 enabled    dokku core logs plugin
         mariadb              1.2.7 enabled    dokku mariadb service plugin
         network              0.12.12 enabled    dokku core network plugin
         nginx-vhosts         0.12.12 enabled    dokku core nginx-vhosts plugin
         plugin               0.12.12 enabled    dokku core plugin plugin
         postgres             1.2.7 enabled    dokku postgres service plugin
         proxy                0.12.12 enabled    dokku core proxy plugin
         ps                   0.12.12 enabled    dokku core ps plugin
         redis                1.2.7 enabled    dokku redis service plugin
         repo                 0.12.12 enabled    dokku core repo plugin
         scheduler-docker-local 0.12.12 enabled    dokku core scheduler-docker-local plugin
         shell                0.12.12 enabled    dokku core shell plugin
         ssh-keys             0.12.12 enabled    dokku core ssh-keys plugin
         storage              0.12.12 enabled    dokku core storage plugin
         tags                 0.12.12 enabled    dokku core tags plugin
         tar                  0.12.12 enabled    dokku core tar plugin
=====> nextcloudfpm app information
       App dir:                       /home/dokku/nextcloudfpm 
       Git sha:                       a7d3ebc                  
       Deploy source:                 git                      
       Locked:                        false                    
=====> nextcloudfpm ssl information
       Ssl dir:                       /home/dokku/nextcloudfpm/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> nextcloudfpm checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> nextcloudfpm docker options information
       Docker options build:          --link dokku.mariadb.nextcloudfpm_db:dokku-mariadb-nextcloudfpm-db 
       Docker options deploy:         --link dokku.mariadb.nextcloudfpm_db:dokku-mariadb-nextcloudfpm-db --restart=on-failure:10 -v /var/lib/dokku/data/storage/nextcloudfpm/:/var/www/html 
       Docker options run:            --link dokku.mariadb.nextcloudfpm_db:dokku-mariadb-nextcloudfpm-db -v /var/lib/dokku/data/storage/nextcloudfpm/:/var/www/html 
=====> nextcloudfpm git information
       Git rev env var:               GIT_REV                  
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
=====> nextcloudfpm network information
       Network listeners:             172.17.0.12:9000
       Network bind all interfaces:   false
=====> nextcloudfpm proxy information
       Proxy enabled:                 true                     
       Proxy type:                    nginx                    
       Proxy port map:                http:9000:9000           
=====> nextcloudfpm ps information
       Processes:                     1                        
       Deployed:                      true                     
       Running:                       true                     
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Status web.1:                  running    (CID: 75b78610eb9a)
=====> nextcloudfpm scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> nextcloudfpm storage information
       Storage build mounts:                                   
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/nextcloudfpm/:/var/www/html 
       Storage run mounts:            -v /var/lib/dokku/data/storage/nextcloudfpm/:/var/www/html 

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

VPS Ubuntu 16.04

**Comment by josegonzalez** [comment]
Makes sense. Looks like we just need to start a container, so `sh` should be fine enough for our use case.

**Comment by SebastianApel** [comment]
Hi Jose, do you want to cover the "enter" command (that suffers from the same "problem" when bash is not present) under this issue? Or do you want me to open a different issue?

**Comment by josegonzalez** [comment]
@SebastianApel if that `docker create` methodology works, ship it. Should be much faster/more performant to boot :)

**Comment by josegonzalez** [comment]
For the `enter` command, you can set `DOKKU_APP_SHELL`.

Closing this issue as there is a pull request open for this issue.
