### ISSUE TITLE
RawGit is now in a sunset phase

### ISSUE THREAD

**Issue by znz** [dokku/dokku#3284]
https://rawgit.com/ announced it will shut down.
Because http://dokku.viewdocs.io/dokku/ uses cdn.rawgit.com, I think it should use another service.

**Comment by welkie** [comment]
Seems like GutHub Pages would be the best platform to move the docs site to.

**Comment by pedrofracassi** [comment]
RawGit recommended using [jsDelivr](https://www.jsdelivr.com/) on their twitter. I've been using it for some personal projects, and it's great.

**Comment by josegonzalez** [comment]
Does that work for non-js assets?

**Comment by jalcine** [comment]
Yeah the js part is a misnomer.

**Comment by josegonzalez** [comment]
Awesome this seems like a quick way to fix the issue. I'll take a look later tonight, thanks all!
