### ISSUE TITLE
Pointing domain to dokku on Digital Ocean without subdomain name

### ISSUE THREAD

**Issue by hanshank** [dokku/dokku#3289]
Hi,

I am trying to point my domain, let's call it mydomain.com, to my dokku app that is currently hosted on Digital Ocean. I do not want a subdomain like: appname.domainname.com. I simply want domainame.com to display my dokku app. 

How do i achieve this?

**Comment by josegonzalez** [comment]
Please see our [domains documentation](http://dokku.viewdocs.io/dokku/configuration/domains/) for details on how to add a domain to a specific application. You'll need to refer to your DNS provider's docs for modifying the domain to point at your ip address.
