### ISSUE TITLE
dokku config no longer sorts by alpha

### ISSUE THREAD

**Issue by joshco** [dokku/dokku#3293]
This is a small issue, but I noticed it when upgrading from old old dokku like 0.3 to 0.12.13.

Running dokku config <app>  used to return the environment variables sorted by alpha A-Z.
With version 0.12.13 it returns them in random order that is different every time the command is run.

Is there a reason why this is?

**Comment by josegonzalez** [comment]
No reason, that just wasn’t a thing we tested for.

@alexquick is this something you can look into?
