### ISSUE TITLE
Dokku user's home directory

### ISSUE THREAD

**Issue by t0xicCode** [dokku/dokku#3300]
Has there been discussion as to the reason why dokku's home directory is `/home/dokku` yet it also uses a directory in `/var/lib/dokku`?

Typically, system users have their home directories under `/var/lib` (e.g. nginx, chrony, haproxy) or somewhere else under `/var` (e.g. `/var/opt/gitlab` for gitlab) so that only "human" users are in `/home`.

Would it be possible to have the home directory at `/var/lib/dokku` and not have a separate path for the libraries?

**Comment by t0xicCode** [comment]
Just now I'm seeing that #2930 started addressing this. Would you be receptive to patches that would change the home directory?

**Comment by josegonzalez** [comment]
@t0xicCode I would rather we first consolidate all config into `/var/lib/dokku` as mentioned in #1558. That will then let us cleanly migrate repositories to another directory, as at the moment there are quite a few files in those directories that are currently in use by various plugins.

**Comment by josegonzalez** [comment]
Closing in favor of #1558, as we should resolve where config/data lives in the same issue imo.
