### ISSUE TITLE
Q: How to set two different apps for single domain with subdomain?

### ISSUE THREAD

**Issue by matissg** [dokku/dokku#3317]
Hi,
I'd like to create single DigitalOcean droplet with Dokku domain setup like this:
1) first app with mydomain.com
2) second app with files.mydomain.com

I have deployed both apps and first one works as expected. However second one doesn't open to the domain and redirects to my default app.
**Is my desired setup possible and if yes, what should be my steps to complete, please?**

At the moment I get error from Letsencrypt as well: 
`2018-11-22 05:08:54,218:ERROR:urllib3.connection:360: Certificate did not match expected hostname: files.mydomain.com.`

In `dokku domains:report` I see both apps have domains:
```
=====> nextcloud domains information
       Domains app enabled:           true
       Domains app vhosts:            files.mydomain.com
       Domains global enabled:        true
       Domains global vhosts:         dokku-own-apps
=====> rubyandmore domains information
       Domains app enabled:           true
       Domains app vhosts:            mydomain.com www.mydomain.com
       Domains global enabled:        true
       Domains global vhosts:         dokku-own-apps
```

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by wcalandro** [comment]
@matissg Can you please provide the output of `dokku proxy:ports nextcloud` and `dokku proxy:ports rubyandmore`? I recently ran into a similar issue and it turned out that one of my applications wasn't having it's HTTP/HTTPS traffic routed to the container.

**Comment by matissg** [comment]
@wcalandro I changed my strategy and now I'm trying to deploy it as sub-domain app. So it looks something like this:
```
-----> Port mappings for rubyandmore
-----> scheme             host port                 container port
http                      80                        5000
https                     443                       5000

-----> Port mappings for cloud.rubyandmore.lv
-----> scheme             host port                 container port
http                      9000                      9000
```
Bascially I'm placing Nextcloud under `cloud.rubyandmore.lv`. So far result is the same as with previous approach.

**Comment by wcalandro** [comment]
@matissg So, the issue here is that, for `cloud.rubyandmore.lv`, port 9000 on your server is what is being routed to container port 9000. To fix this, I would run:
```
proxy:ports-add cloud.rubyandmore.lv http:80:9000 https:443:9000
```

This will route port 80 and 443 from the server (Basically your requests from your browser to the server) properly to the container. Please let me know if this works.

**Comment by josegonzalez** [comment]
I'm guessing `cloud.rubyandmore.lv` is a dockerfile app, and we respect dockerfile ports over standard when you have an `EXPOSE` in it (this is documented).

**Comment by wcalandro** [comment]
That was my assumption as well

**Comment by wcalandro** [comment]
@matissg Can you post the output of `dokku domains:report` again?
This is what I see when I visit your URL. Is this your default app? ![chrome_2018-12-07_09-30-25](https://user-images.githubusercontent.com/6374653/49660000-bd715580-fa02-11e8-9138-623b10382ac2.png)

**Comment by matissg** [comment]
@wcalandro Yeah, that's default app. Here's domains report:
```
=====> cloud.rubyandmore.lv domains information
       Domains app enabled:           true
       Domains app vhosts:            cloud.rubyandmore.lv
       Domains global enabled:        true
       Domains global vhosts:         dokku-own-apps
=====> rubyandmore domains information
       Domains app enabled:           true
       Domains app vhosts:            rubyandmore.lv www.rubyandmore.lv
       Domains global enabled:        true
       Domains global vhosts:         dokku-own-apps
```
I've removed info regarding 2 apps not related to the case (no issues for those apps - work like charm on Dokku :) )

**Comment by wcalandro** [comment]
@matissg Can you confirm that the container has been deployed and is running for that application? When I visit cloud.rubyandmore.lv:9000 directly I get a plain nginx page.

**Comment by wcalandro** [comment]
The only other thing I imagine could be happening is that you named your application `cloud.rubyandmore.lv` while the instructions specifically state for you to name is `nextcloud` because it uses dokku-require to set up dependencies.

**Comment by matissg** [comment]
@wcalandro Container is deployed and running. It could be true, I have to rename it to `nextcloud`. I'll try to do it and let you know of the result.

**Comment by josegonzalez** [comment]
I definitely recommend jumping onto our slack and asking for support directly. We should be able to help you quicker there :)

**Comment by lovasoa** [comment]
Did you solve this problem ? I have the same issue 

```
# dokku domains:report 
=====> mainapp domains information
       Domains app enabled:           true                     
       Domains app vhosts:            mainapp.com              
       Domains global enabled:        true                     
       Domains global vhosts:         mainapp.com              
=====> subapp domains information
       Domains app enabled:           true                     
       Domains app vhosts:            subapp.mainapp.com       
       Domains global enabled:        true                     
       Domains global vhosts:         mainapp.com     
```

However, accessing subapp.mainapp.com loads mainapp.
I know that subapp is running correctly because I can access it via ip and port.

**Comment by josegonzalez** [comment]
@lovasoa mind filing a new issue with your problem? It's likely not related to this one. Thanks.
