### ISSUE TITLE
Command not found - config_get from scheduler-docker-local/internal-functions plugin

### ISSUE THREAD

**Issue by fluxcorenz** [dokku/dokku#3323]
## Description of problem

After upgrading from 0.12.13 to 0.13.0 on ubuntu 14.04, every hour during the '/usr/bin/dokku ps:retire' process (kicked off via /etc/cron.d/dokku-retire), the following message is emitted:

/var/lib/dokku/plugins/available/scheduler-docker-local/internal-functions: line 98: config_get: command not found

### How reproducible

Every time the task runs.

### Steps to Reproduce

1. Run /usr/bin/dokku ps:retire 

#### Actual Results

The following line is output:
/var/lib/dokku/plugins/available/scheduler-docker-local/internal-functions: line 98: config_get: command not found

#### Expected Results

No error output

## Environment Information

-----> uname: Linux prod01.mhn 4.4.0-139-generic #165~14.04.1-Ubuntu SMP Wed Oct 31 10:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                    total       used       free     shared    buffers     cached
       Mem:          7983       2814       5169         49        366        899
       -/+ buffers/cache:       1548       6434
       Swap:         7811          0       7811
-----> docker version: 
       Client:
        Version:      17.05.0-ce
        API version:  1.29
        Go version:   go1.7.5
        Git commit:   89658be
        Built:        Thu May  4 22:06:06 2017
        OS/Arch:      linux/amd64
       
       Server:
        Version:      17.05.0-ce
        API version:  1.29 (minimum version 1.12)
        Go version:   go1.7.5
        Git commit:   89658be
        Built:        Thu May  4 22:06:06 2017
        OS/Arch:      linux/amd64
        Experimental: false
-----> docker daemon info: 
       Containers: 32
        Running: 13
        Paused: 0
        Stopped: 19
       Images: 209
       Server Version: 17.05.0-ce
       Storage Driver: aufs
        Root Dir: /var/lib/docker/aufs
        Backing Filesystem: extfs
        Dirs: 379
        Dirperm1 Supported: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins: 
        Volume: local
        Network: bridge host macvlan null overlay
       Swarm: inactive
       Runtimes: runc
WARNING: No swap limit support
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
       runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
       init version: 949e6fa
       Security Options:
        apparmor
       Kernel Version: 4.4.0-139-generic
       Operating System: Ubuntu 14.04.5 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 4
       Total Memory: 7.796GiB
       Name: prod01.mhn
       ID: HYU4:767N:B4PE:6MXQ:33XV:CKET:BUA3:5O2W:NNOM:JR6G:R2FK:43LH
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.4.5
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v195
         heroku-buildpack-nodejs    v130
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v144
         heroku-buildpack-java      v62
         heroku-buildpack-gradle    v27
         heroku-buildpack-scala     v82
         heroku-buildpack-play      v26
         heroku-buildpack-php       v145
         heroku-buildpack-go        v94
         buildpack-nginx            v9
-----> dokku version: 0.13.0
-----> dokku plugins: 
       plugn: 0.3.0
         00_dokku-standard    0.13.0 enabled    dokku core standard plugin
         20_events            0.13.0 enabled    dokku core events logging plugin
         apps                 0.13.0 enabled    dokku core apps plugin
         build-env            0.13.0 enabled    dokku core build-env plugin
         certs                0.13.0 enabled    dokku core certificate management plugin
         checks               0.13.0 enabled    dokku core checks plugin
         common               0.13.0 enabled    dokku core common plugin
         config               0.13.0 enabled    dokku core config plugin
         copy-files-to-image  1.0.0 enabled    dokku plugin to copy files from the host to the built docker image
         deployment-keys      0.1.0 enabled    Manage SSH deployment keys that should get injected into your containers on-build
         docker-options       0.13.0 enabled    dokku core docker-options plugin
         domains              0.13.0 enabled    dokku core domains plugin
         enter                0.13.0 enabled    dokku core enter plugin
         git                  0.13.0 enabled    dokku core git plugin
         hostkeys-plugin      0.1.0 enabled    Manage hostkeys (.ssh/known_hosts) in your container environment
         logs                 0.13.0 enabled    dokku core logs plugin
         network              0.13.0 enabled    dokku core network plugin
         nginx-vhosts         0.13.0 enabled    dokku core nginx-vhosts plugin
         plugin               0.13.0 enabled    dokku core plugin plugin
         postgres             1.0.0 enabled    dokku postgres service plugin
         proxy                0.13.0 enabled    dokku core proxy plugin
         ps                   0.13.0 enabled    dokku core ps plugin
         redis                1.0.0 enabled    dokku redis service plugin
         repo                 0.13.0 enabled    dokku core repo plugin
         scheduler-docker-local 0.13.0 enabled    dokku core scheduler-docker-local plugin
         shell                0.13.0 enabled    dokku core shell plugin
         ssh-keys             0.13.0 enabled    dokku core ssh-keys plugin
         storage              0.13.0 enabled    dokku core storage plugin
         tags                 0.13.0 enabled    dokku core tags plugin
         tar                  0.13.0 enabled    dokku core tar plugin

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main 
Ubuntu 14.04 VPS on local KVM

### Additional information

I'm thinking the 'fn-scheduler-docker-local-retire-container' function might need to 'source "$PLUGIN_AVAILABLE_PATH/config/functions"' (a la dokku_build function in plugins/common/functions)

**Comment by josegonzalez** [comment]
Good catch, I'll get that fixed now!
