### ISSUE TITLE
CHEKS: custom success HTTP code

### ISSUE THREAD

**Issue by IlyaSemenov** [dokku/dokku#3331]
## Description of problem

I have a Dokku app that runs a websocket server directly. It responds with 426 Upgrade Required when accessed with HTTP on `/`, and I would like to be able to check that with CHECKS. However, currently the check fails with:

```
=====> web=1
-----> Attempting pre-flight checks
-----> Attempt 1/5 Waiting for 5 seconds ...
       CHECKS expected result:
       http://localhost/ => "Upgrade Required"
remote:  !
remote: curl: (22) The requested URL returned error: 426 Upgrade Required
remote:  !     Check attempt 1/5 failed.
```

(which is the expected response!)

### Proposal

I propose to add a new CHECKS option along with `WAIT`, `TIMEOUT`, etc., something like `EXPECT_STATUS=426`.

**Comment by josegonzalez** [comment]
I'm going to close this, see #2760 for more information on a richer checks format.

Feel free to push a PR - with tests! - for this specific functionality!
