### ISSUE TITLE
Problem to configure a dokku app on a network

### ISSUE THREAD

**Issue by templth** [dokku/dokku#3333]
## Description of problem

I try to configure a network for a dokku application (named here `app_dokku`).

I can execute the command:

```
$ dokku network connect net_name app_dokku
```

After that, I can use the network to access exposed applications from the `app_dokku` application.

### How reproductible

The problem is that the connection on the network is lost after a re-deployment.

### Question

Is it possible to keep the network connect after a re-deployment through the dokku configuration of the application?

**Comment by josegonzalez** [comment]
This is not currently possible, though is something that has been planned out in #2085. Feel free to file a PR with the requisite changes :)
