### ISSUE TITLE
Problem with DOKKU_APP_LISTENERS within nginx configuration

### ISSUE THREAD

**Issue by templth** [dokku/dokku#3336]
Hello,

Within the nginx configuration of a dokku application, I use the `DOKKU_APP_LISTENERS`.

```
upstream {{ .APP }} {
{{ range .DOKKU_APP_LISTENERS | split " " }}
  server {{ . }};
{{ end }}
}
```

This worked fine but recently I got an error when deploying an application (when Dokku tries to validate the nginx configuration)

It seems that after the server keyword, I have two IP addresses used with a port at the end:

```
upstream my app {
  server 172.10.34.6172.10.34.4:5000
}
```

How to use `dokku proxy` commands to fix that?

How to change this?
Thanks for your help.
Therry

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Seems as if this is caused when you add a second network to an application - which isn't something we currently support out of the box.

Closing as there is a pull request open. Thanks for filing!
