### ISSUE TITLE
how to determine git hash of app deployed via dockerfile

### ISSUE THREAD

**Issue by tansaku** [dokku/dokku#3340]
when an app is deployed via buildpacks we can check the hash of the deployed system relatively easily e.g.  https://stackoverflow.com/a/34946672/316729

however this won't work for dockerfile deploys - does anyone know how to check what the git hash of the deployed app is when it's been deployed using a dockerfile?

**Comment by tansaku** [comment]
ah sorry, looks like they do work the same - was stupidly looking at an undeployed app - doh!

**Comment by josegonzalez** [comment]
I believe we inject that as an environment variable now - though only at runtime for docker file deploys. Check our git docs for more details.
