### ISSUE TITLE
tags:create always uses the latest version for its source image

### ISSUE THREAD

**Issue by baikunz** [dokku/dokku#3355]
## Description of problem
I'm deploying docker-hub images as apps using `tags:deploy`. I followed the docs but I think either there is something wrong with the docs, or with the code.

Code from the docs for deploying an updated image :
```bash
dokku tags:create test-app previous
dokku tags:deploy test-app v12 && dokku tags:create test-app latest
```
As far as I understand it. Those lines implies that there is no `latest` tag associated with the app.
However by reading the code it looks like the `tags:create` command is using the `latest` tag by default on the source image, which does not exist. 

https://github.com/dokku/dokku/blob/86cc15d28532796dba410e829639a63b09f2e8ec/plugins/tags/subcommands/create#L14

I might have missed something, but I don't see how to use the dokku `tags:create` command for deploying docker-hub images. To create the `latest` tag I had to use docker directly, but another problem arised. When redeploying an updated image using the 2 lines above, the `latest` is not pointing to the newly deployed app, but still to the previous one.

### Steps to Reproduce

1. Follow the steps described in the [docs](http://dokku.viewdocs.io/dokku/deployment/methods/images/#deploying-from-a-docker-registry)
2. `dokku tags:create test-app latest` **-> fail**
3. `docker tag dokku/test-app:v12 dokku/test-app:latest`
4. `docker pull demo-repo/some-image:v13`
5. `docker tag demo-repo/some-image:v13 dokku/test-app:v13`
6. `dokku tags:deploy test-app v13 && dokku tags:create latest` **-> `latest` is still pointing to previous image**

**Comment by josegonzalez** [comment]
The documentation doesn't say to use `tags:create` for deploying a tag. That subcommand creates a tag from the `latest` image version of a deployed app. So if you have an app called `lollipop`, the existing local image would be `dokku/lollipop:latest`, and calling `dokku tags:create lollipop derp` would create the tag `dokku/lollipop:derp`.

Step `2` on your list fails because - as I said above - it tags the current `latest` image. I guess the docs are slightly incorrect, but at the very least we should be re-tagging `latest` on successful deploy

Would retagging to `latest` on `tags:deploy` success work for your use-case? I think thats a reasonable workaround.

**Comment by josegonzalez** [comment]
I _think_ the above PR fixes the issue - and is more correct behavior regardless - but feel free to comment on it if it does not.

**Comment by baikunz** [comment]
Thanks for the explanation ! I think I misunderstood the docs then !
I think that PR is a nice addition that's great ;-)

I still think there is something unclear in the last part of the docs :
```bash
# build the image
docker build -t dokku/test-app:v12 .
# copy the image to the dokku host
docker save dokku/test-app:v12 | bzip2 | ssh my.dokku.host "bunzip2 | docker load"
# tag and deploy the image
ssh my.dokku.host "dokku tags:create test-app previous; dokku tags:deploy test-app v12 && dokku tags:create test-app latest"
```

I might be wrong (I don't know dokku very well yet) but it looks to me that the `dokku tags:create test-app latest` won't do anything, it will run `docker tag dokku/test-app:latest dokku/test-app:latest`
This is the line I can't understand !

Thanks for the PR anyway! This will be great and more consistent with the buildpack deployments !

**Comment by alfonmga** [comment]
I think docs are wrong or I'm missing something.

The only way to do it was to do it like this:
```bash
# tag previous
ssh my.dokku.host "dokku tags:create server previous" &&
# copy the image to the dokku host and tags latest
docker save dokku/server:latest | bzip2 | ssh root@116.203.113.136 "bunzip2 | docker load" &&
# deploy latest image
ssh my.dokku.host "dokku tags:deploy server latest"
```

Otherwise `previous` tag is not correct.

**Comment by josegonzalez** [comment]
@alfonmga if you think the docs are wrong, please open up a new issue instead of bumping an old one. Thanks!
