### ISSUE TITLE
Passing JSON to config:set in Dokku

### ISSUE THREAD

**Issue by solarsoft0** [dokku/dokku#3364]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

## Description of problem
auth.json contains [https://getcomposer.org/doc/articles/http-basic-authentication.md](see here)
dokku config:set <app-name> COMPOSER_AUTH="$(cat auth.json)"

### How to reproduce
dokku config:set <app-name> COMPOSER_AUTH="$(cat auth.json)"
### Steps to Reproduce
1. set the above config  on a dokku app
2.  build 
3.

#### Actual Results
remote:   [UnexpectedValueException]
remote:   COMPOSER_AUTH environment variable is malformed, should be a valid JSON object
remote:
remote:
remote: config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [--] [<setting-key>] [<setting-value>]...
remote:
remote:
remote:  !     ERROR: An unknown internal error occurred.
remote:  !
remote:  !     Contact Heroku Support for assistance if this problem persists.
remote:  !
remote:  !     Stack trace follows for debugging purposes:
remote:  !     254 main /tmp/buildpackWxXYn/bin/compile
remote:
 ! [remote rejected] master -> master (pre-receive hook declined)
#### Expected Results

successful build 

### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> You may also run `dokku report` without any arguments to display the top-level reporting information.
## my dokku report says
Swap:             0           0           0
-----> docker version: 
       Client:
        Version:           18.06.1-ce
        API version:       1.38
        Go version:        go1.10.3
        Git commit:        e68fc7a
        Built:             Tue Aug 21 17:24:51 2018
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server:
        Engine:
         Version:          18.06.1-ce
         API version:      1.38 (minimum version 1.12)
         Go version:       go1.10.3
         Git commit:       e68fc7a
         Built:            Tue Aug 21 17:23:15 2018
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
       Containers: 16
        Running: 5
        Paused: 0
        Stopped: 11
       Images: 93
       Server Version: 18.06.1-ce
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
       runc version: 69663f0bd4b60df09991c08812a60108003fa340
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-36-generic
       Operating System: Ubuntu 18.04.1 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 985.5MiB
       Name: civicmonitor
       ID: 4Z7C:RNK3:OE5Y:MXRN:FM6U:HAKU:42I4:ODTJ:MRCC:4ILJ:VKX5:CYQE
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.4.6
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v197
         heroku-buildpack-nodejs    v134
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v146
         heroku-buildpack-java      v62
         heroku-buildpack-gradle    v27
         heroku-buildpack-scala     v83
         heroku-buildpack-play      v26
         heroku-buildpack-php       v148
         heroku-buildpack-go        v98
         buildpack-nginx            v10
-----> dokku version: 0.13.4
-----> dokku plugins: 
       plugn: 0.3.0
         00_dokku-standard    0.13.4 enabled    dokku core standard plugin
         20_events            0.13.4 enabled    dokku core events logging plugin
         apps                 0.13.4 enabled    dokku core apps plugin
         build-env            0.13.4 enabled    dokku core build-env plugin
         certs                0.13.4 enabled    dokku core certificate management plugin
         checks               0.13.4 enabled    dokku core checks plugin
         common               0.13.4 enabled    dokku core common plugin
         config               0.13.4 enabled    dokku core config plugin
         docker-options       0.13.4 enabled    dokku core docker-options plugin
         domains              0.13.4 enabled    dokku core domains plugin
         enter                0.13.4 enabled    dokku core enter plugin
         git                  0.13.4 enabled    dokku core git plugin
         hostkeys-plugin      0.2.1 enabled    Manage hostkeys (.ssh/known_hosts) in your container environment
         letsencrypt          0.8.8 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.13.4 enabled    dokku core logs plugin
         mariadb              1.4.10 enabled    dokku mariadb service plugin
         network              0.13.4 enabled    dokku core network plugin
         nginx-vhosts         0.13.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.13.4 enabled    dokku core plugin plugin
         postgres             1.4.12 enabled    dokku postgres service plugin
         proxy                0.13.4 enabled    dokku core proxy plugin
         ps                   0.13.4 enabled    dokku core ps plugin
         redis                1.4.11 enabled    dokku redis service plugin
         repo                 0.13.4 enabled    dokku core repo plugin
         scheduler-docker-local 0.13.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.13.4 enabled    dokku core shell plugin
         ssh-keys             0.13.4 enabled    dokku core ssh-keys plugin
         storage              0.13.4 enabled    dokku core storage plugin
         tags                 0.13.4 enabled    dokku core tags plugin
         tar                  0.13.4 enabled    dokku core tar plugin

### Additional information

Procfile 
web: vendor/bin/heroku-php-apache2 public/

**Comment by josegonzalez** [comment]
You can try setting it via an `--encoded` environment variable as shown here: http://dokku.viewdocs.io/dokku/configuration/environment-variables/
