### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by josephchan91** [dokku/dokku#3373]
## Description of problem
Hi fellow dokku users, I'm setting up a data warehouse at work. I have some ETL scripts running on node that I'd like to deploy to a dokku instance on an ubuntu machine. I plan to have cron jobs that will call certain dokku commands once a day. My container is failing to start... I don't have a super strong grasp of containers and would appreciate any help. Thanks!!!

### How reproducible
Everytime

### Steps to Reproduce

1. Push code to remote dokku@193.9.9.254:data-warehouse-etl
2. Push fails with following [trace](https://gist.github.com/josephchan91/94cc4122136a30e018408076256cfa5f)

## Environment Information
I'm on Mac OSX 10.10.5.
Dokku 0.12.13 is installed on a physical ubuntu machine (18.04.1 LTS)

### `dokku report APP_NAME` output
-----> uname: Linux joseph-desktop 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           1855         747         188          66         919         865
       Swap:          2047         319        1728
-----> docker version: 
       Client:
        Version:           18.09.0
        API version:       1.39
        Go version:        go1.10.4
        Git commit:        4d60db4
        Built:             Wed Nov  7 00:49:01 2018
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          18.09.0
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.4
         Git commit:       4d60db4
         Built:            Wed Nov  7 00:16:44 2018
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
       Containers: 7
        Running: 0
        Paused: 0
        Stopped: 7
       Images: 13
       Server Version: 18.09.0
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
       runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-43-generic
       Operating System: Ubuntu 18.04.1 LTS
       OSType: linux
WARNING: No swap limit support
       Architecture: x86_64
       CPUs: 4
       Total Memory: 1.812GiB
       Name: joseph-desktop
       ID: SZAB:BRZ4:PJ77:T46U:PSI5:USMF:V67M:HKV4:QI7X:IC7P:L4BL:IA3F
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.4.4
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v190
         heroku-buildpack-nodejs    v123
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v138
         heroku-buildpack-java      v62
         heroku-buildpack-gradle    v27
         heroku-buildpack-scala     v82
         heroku-buildpack-play      v26
         heroku-buildpack-php       v143
         heroku-buildpack-go        v90
         buildpack-nginx            v9
-----> dokku version: 0.12.13
-----> dokku plugins: 
       plugn: 0.3.0
         00_dokku-standard    0.12.13 enabled    dokku core standard plugin
         20_events            0.12.13 enabled    dokku core events logging plugin
         apps                 0.12.13 enabled    dokku core apps plugin
         build-env            0.12.13 enabled    dokku core build-env plugin
         certs                0.12.13 enabled    dokku core certificate management plugin
         checks               0.12.13 enabled    dokku core checks plugin
         common               0.12.13 enabled    dokku core common plugin
         config               0.12.13 enabled    dokku core config plugin
         docker-options       0.12.13 enabled    dokku core docker-options plugin
         domains              0.12.13 enabled    dokku core domains plugin
         enter                0.12.13 enabled    dokku core enter plugin
         git                  0.12.13 enabled    dokku core git plugin
         logs                 0.12.13 enabled    dokku core logs plugin
         network              0.12.13 enabled    dokku core network plugin
         nginx-vhosts         0.12.13 enabled    dokku core nginx-vhosts plugin
         plugin               0.12.13 enabled    dokku core plugin plugin
         proxy                0.12.13 enabled    dokku core proxy plugin
         ps                   0.12.13 enabled    dokku core ps plugin
         repo                 0.12.13 enabled    dokku core repo plugin
         scheduler-docker-local 0.12.13 enabled    dokku core scheduler-docker-local plugin
         shell                0.12.13 enabled    dokku core shell plugin
         ssh-keys             0.12.13 enabled    dokku core ssh-keys plugin
         storage              0.12.13 enabled    dokku core storage plugin
         tags                 0.12.13 enabled    dokku core tags plugin
         tar                  0.12.13 enabled    dokku core tar plugin
=====> data-warehouse-etl app information
not deployed

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Installed with wget to a physical ubuntu machine (Ubuntu 18.04.1 LTS)

### Additional information
My code isn't starting any server since I'm just using it for one-off cron job commands. Is this why the container isn't running?

**Comment by josegonzalez** [comment]
Looks like your nodejs-detected container is not starting, and has no log output. Given that this is probably an issue with you using a buildpack, do you mind hopping onto our slack chat and asking there? We'll be able to help you more quickly via chat.

Here is a helpful link: http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/
