### ISSUE TITLE
CORS problem in Firefox for web-based installer

### ISSUE THREAD

**Issue by heyarne** [dokku/dokku#3387]
## Description of problem

I just tried using the web-based installer in Firefox 64. The scripts are not loaded and the web page is unresponsive. I disabled my ad blockers and the problem persists.

![2019-01-10-160112_900x320_scrot](https://user-images.githubusercontent.com/525780/50977842-6411b000-14f3-11e9-9a7f-7c887b64aa8c.png)

Interestingly enough Chromium 71 doesn't have this problem. The domain I used for setting up did not have a certificate at that time which might have caused the problem.

**Comment by josegonzalez** [comment]
Can you manually check the sha256 for the file and verify its incorrect? I got that directly from the jQuery site, but happy to update it if necessary.

**Comment by josegonzalez** [comment]
Ah I see what you mean. That's annoying. I wonder if cdnjs supports http and https?

**Comment by heyarne** [comment]
A quick check tells me they're auto-redirecting. The problem with migration to https-only would also stay. I could also try to remove the jQuery dependency alltogether; the code seems very straightforward and cross-browser-compatible js is quite bearable to write and maintain these days.

**Comment by josegonzalez** [comment]
Closing as there is a pull-request open.

Thanks for working on this!
