### ISSUE TITLE
Feature Request: Support BUILD_PATH to specify path inside repo to build.

### ISSUE THREAD

**Issue by thomasfedb** [dokku/dokku#3388]
Firstly, thank you for the continued work on Dokku. I've been using it on several small scale deployments for many months and am very happy with it. I support Dokku's Patreon.

There are cases where a repo will contain multiple related applications that are deployed independently but version controlled together. For example, a repo might contain a `client` directory containing a React.js app, and a `server` directory with a Ruby on Rails backend.

It would be idea if Dokku could support a `BUILD_PATH` to specific a directory inside the repo which should be built - with buildpack or Dockerfile detection occurring once inside the `BUILD_PATH`.

**Comment by josegonzalez** [comment]
Feel free to reach out via slack if you have any further questions (or here of course!).

Closing for now.

**Comment by thomasfedb** [comment]
Hi @josegonzalez, thanks for the reply. Great to hear that this would be possible to implement as a plugin. I didn't realise how comprehensive the hooks were!
