### ISSUE TITLE
deb source not longer available

### ISSUE THREAD

**Issue by marcelinollano** [dokku/dokku#3390]
## Description of problem

The [install script](https://raw.githubusercontent.com/dokku/dokku/master/bootstrap.sh) runs the following line:

    echo "deb https://packagecloud.io/dokku/dokku/$DOKKU_DISTRO/ $OS_ID main" | tee /etc/apt/sources.list.d/dokku.list

In my case I'm using ubuntu which results in:

    user@localhost ~ cat /etc/apt/sources.list.d/dokku.list
    deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main

However, that resource no longer seems available:

  <img width="608" alt="screenshot 2019-01-10 at 17 39 03" src="https://user-images.githubusercontent.com/6335/50983005-c45a1f00-14fe-11e9-8179-b1384feeeff8.png">

### Steps to Reproduce

1. Install dokku using the [install script](https://raw.githubusercontent.com/dokku/dokku/master/bootstrap.sh) 

2. `apt update`

3. 💥 Boom:

    ```sh
    W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/dokku/dokku/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FAAB6AAAA1CD193A
    W: Failed to fetch https://packagecloud.io/dokku/dokku/ubuntu/dists/trusty/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FAAB6AAAA1CD193A
    W: Some index files failed to download. They have been ignored, or old ones used instead.
    ```

#### Actual Results

`apt` fails to update dokku.

#### Expected Results

`apt` should update from `deb` source.

### `dokku report APP_NAME` output

Does not apply.

### How was Dokku installed?

Installed using the install script, `deb` in `Ubuntu 16.04.5 LTS`, `Linode`.

### Additional information

Something must have changed at https://packagecloud.io, because https://packagecloud.io/dokku/dokku is still available, but the distro resource seems to not be available anymore.

**Comment by josegonzalez** [comment]
The distro resource was never available. Your actual issue is that the gpgkey imported is not the correct one, as the raw install docs never got updated, just the bootstrap file. I'll fix that now!

**Comment by josegonzalez** [comment]
Run the following and you'll be fine with the manual install docs.

```
wget -nv -O - https://packagecloud.io/dokku/dokku/gpgkey | apt-key add -
```

**Comment by josegonzalez** [comment]
Also, please ensure you are using the latest bootstrap script, as previous versions will have the wrong gpgkey path.

**Comment by marcelinollano** [comment]
@josegonzalez ohhh that was it! Thank you so much, I was totally stuck. 🙇

**Comment by michiels** [comment]
@josegonzalez Can you always use the latest bootstrap script, even when installing old tags? Currently our installer at intercity.io also checks out the bootstrap script belonging to the Git tag. But probably those old bootstrap scripts also have the old key line still there.

If we could use the `bootstrap.sh` from `master`, but still install an old release tag, that'd be perfect.

Thanks for your answer!

**Comment by josegonzalez** [comment]
Yeah the latest master script will always install the tag environment bad specified.

**Comment by creativecoder** [comment]
> `wget -nv -O - https://packagecloud.io/dokku/dokku/gpgkey | apt-key add -`

This solved my issue as well, thank you so much!
