### ISSUE TITLE
Can't add ssh keys to Dokku via Ansible

### ISSUE THREAD

**Issue by jakubgs** [dokku/dokku#3417]
## Description of problem
I'm running via ansible `command` like so:
```
dokku ssh-keys:add ${user} ${key}
```
but it fails silently with exit code `1` without errors.

### How reproducible
```yaml
- command: dokku ssh-keys:add testuser /home/testuser/.ssh/id_rsa.pub
  become: true
  become_user: root
```

### Steps to Reproduce

1. Run above task via Ansible (I'm using `2.7.6`)
2. See it fail
3. See no output in `stdout` or `stderr`
4. Try the same command in an interactive shell, and see it works just fine.

#### Actual Results
```
TASK [dokku : command] ********************************************************************************************************************************
fatal: [myhost.example.org]: FAILED! => {"changed": true, "cmd": ["dokku", "ssh-keys:add", "testuser", "/home/testuser/.ssh/id_rsa.pub"], "delta": "0:00:00.221301", "end": "2019-01-24 13:37:27.068312", "msg": "non-zero return code", "rc": 1, "start": "2019-01-24 13:37:26.847011", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```
#### Expected Results
It works.

## Environment Information
Dokku version: `0.14.4`
Operating System: `Ubuntu 18.04.1 LTS`
Source: `deb https://packagecloud.io/dokku/dokku/ubuntu/ bionic main`

### Additional information
I tried running it in `strace` but got nothing useful.
I'm wondering if this has something to do with shell not having a tty and not being interactive.
I tried running this command via regular `ssh` session and it just get's stuck on `read -r key_from_pipe`:
```bash
$ ssh myhost.example.org 'sudo dokku --trace ssh-keys:add testuser /home/testuser/.ssh/id_rsa.pub' 
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ssh-keys:add =~ (ssh-keys:add|ssh-keys:remove) ]]
+ check_ssh_keys_user root default ssh-keys:add testuser /home/testuser/.ssh/id_rsa.pub
+ declare 'desc=check user passed by user-auth for ssh-keys plugin'
+ local SSH_USER=root SSH_NAME=default
+ [[ root == \r\o\o\t ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ source /var/lib/dokku/plugins/available/ssh-keys/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+ add_keys ssh-keys:add testuser /home/testuser/.ssh/id_rsa.pub
+ declare 'desc=add a new key via sshcommand'
+ local cmd=ssh-keys:add
+ shift
+ local name=testuser key_file=/home/testuser/.ssh/id_rsa.pub key_contents key_from_pipe
+ [[ -p /dev/stdin ]]
+ read -r key_from_pipe
```
Which suggests to me that this is related to lack of tty.

**Comment by kgrosvenor** [comment]
Isn't this just a case of adding id rsa to authorized keys, under the dokku
user?

Login to your server copy the ssh key you want and append into
dokku/.ssh/authorised_keys from what I remember

**Comment by josegonzalez** [comment]
Maybe related to https://github.com/dokku/dokku/pull/2603. I'll take a look.

**Comment by jakubgs** [comment]
Interestingly enough, when I do the same `ssh` command with `-t` option that means `Force pseudo-terminal allocation.` then it works just fine:
```bash
 ssh -t myhost.example.org 'sudo dokku ssh-keys:add testuser /home/testuser/.ssh/id_rsa.pub'        
SHA256:aaaaaaaaaaaaaabbbbbbbbbbbbccccccccccccccccc
Connection to myhost.example.org closed.
```
Which confirms my suspicion that your scripts require a tty to work.

**Comment by josegonzalez** [comment]
We check stdin first before doing the file check, I think it needs to be reversed.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
