### ISSUE TITLE
Can't update Dokku version with dokku-update

### ISSUE THREAD

**Issue by matissg** [dokku/dokku#3421]
## Description of problem
Can't upgrade Dokku on Digitalocean Ubuntu 18.04 one-click-droplet to the newest version.
### Steps to Reproduce
```
root@dokku-own-apps:~# sudo dokku-update
-----> Running system updates
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY [some-key]
W: GPG error: https://packagecloud.io/dokku/dokku/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY [some-key]
E: The repository 'https://packagecloud.io/dokku/dokku/ubuntu trusty InRelease' is not signed.
```
When I change `trusty` to `bionic` I get this error:
`W: Failed to fetch https://packagecloud.io/dokku/dokku/ubuntu/dists/bionic/InRelease`

Am I doing something wrong, please?
My current Dokku version is 0.13.4

**Comment by josegonzalez** [comment]
See this comment for more details : https://github.com/dokku/dokku/issues/3390#issuecomment-453178841
