### ISSUE TITLE
Dokku-windows nginx version problem

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [dokku/dokku#3424]
## Description of problem
On installing dokku-windows, on my vagrant machine, when I opened dokku.me, It showed the nginx default web page. According to the troubleshooting section of the docs, I ran `nginx -t` on the vagrant VM.
Below is the output

    vagrant@dokku:/etc/nginx/conf.d$ nginx -t
    nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
    2019/01/28 19:58:29 [warn] 24778#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
    2019/01/28 19:58:29 [emerg] 24778#0: unknown directive "ssl_session_tickets" in /etc/nginx/conf.d/dokku.conf:8
    nginx: configuration file /etc/nginx/nginx.conf test failed
    vagrant@dokku:/etc/nginx/conf.d$

I went to the nginx documentation [here](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_tickets) and found that, This directive is only available in nginx version `1.5.9` onwards.
I quickly ran `nginx -v` and found the version to be '1.4.6'.

Please fix the nginx version.

### Steps to Reproduce

1. Install dokku-windows
2. Access [dokku.me](https://dokku.me)
3. It will load up the default nginx page

#### Actual Results
Show the dokku installer webpage on loading dokku.me
#### Expected Results
Shows the default nginx page.
## Environment Information
win 8.1, 64 bit, vagrant version `2.2.3`, virtualbox version `6.0.4 r128413 (Qt5.6.2)`

### `dokku report APP_NAME` output

Not Applicable

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
installed using vagrant and virtualbox on my win 8.1 server.

### Additional information
None

**Comment by josegonzalez** [comment]
I don't have a windows box to test this on, but I think I see the problem.

**Comment by Utkarsh-vishnoi** [comment]
Car you fix it?

**Comment by josegonzalez** [comment]
Yes but I'll need to wait till this weekend.

**Comment by josegonzalez** [comment]
This was fixed by #3411 and shipped in 0.14.3.
