### ISSUE TITLE
predeploy script is ran multiple times if multiple buildpacks in use

### ISSUE THREAD

**Issue by benbristow** [dokku/dokku#3426]
## Description of problem

* predeploy script defined in `app.json` is ran multiple times (once for each buildpack) if multiple buildpacks are enabled.

### Steps to Reproduce

1. Create project with multiple buildpacks
2. Add a predeploy script to app.json
3. Notice the script gets ran multiple times for each build pack

#### Actual Results

Runs multiple times for each buildpack

#### Expected Results

Runs once after all buildpacks are installed, or is configurable per buildpack.

## Environment Information

https://gist.github.com/benbristow/03d87cf5d6c606a89acb1f6ab93e3665

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

DigitalOcean

### Additional information

.buildpacks

```
https://github.com/heroku/heroku-buildpack-nodejs.git#v87
https://github.com/heroku/heroku-buildpack-ruby.git#v142
```

Procfile

```
web: bundle exec thin start -p $PORT -e $RACK_ENV
```

**Comment by josegonzalez** [comment]
Can you include the deploy output before and after running `dokku trace on`, as well as your `app.json` file?

**Comment by benbristow** [comment]
Actually, nevermind. I think it's me.

Getting confused as the NodeJS buildpack runs `npm install` during installation and then my app.json script was also running `npm install`.

Apologies for wasting your time.
