### ISSUE TITLE
Dokku should always be able to scale any proc to 0

### ISSUE THREAD

**Issue by julialucyhogan** [dokku/dokku#3428]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

## Description of problem
Even if a proc type no longer exists, it should be able to be scaled to 0. If you push a new version with an updated Procfile that removes/renames a process, you cannot scale down to 0 the removed/renamed proc type

Additionally: `-` in a proc name will break the procfile utils. from discussion, this should be audited against Heroku functionality, and either fixed or added to Procfile documentation as a requirement (no dashes in proc names)

### Steps to Reproduce
1. deploy an app with some additional process defined in the Profile
2. scale the additional process 
3. update Procfile to remove the additional process
4. deploy app
5. deploy will exit with errors, and on dokku server user will not be able to scale down the additional process

#### Actual Results
```
[proc] is not a valid process name
```
#### Expected Results
successful scaling of given process to 0

### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> You may also run `dokku report` without any arguments to display the top-level reporting information.

### Additional information

- Container Inspect Output (if applicable):
  - 0.13.0+: `dokku inspect APP_NAME`
  - <0.13.0: `docker inspect CONTAINER_ID`: WARNING, `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX.
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

**Comment by josegonzalez** [comment]
Thanks for the report, this should be fairly straightforward to fix.

**Comment by josegonzalez** [comment]
Looks like Heroku allows dashes in a `Procfile` name. I'll add that to `go-procfile-util`

**Comment by josegonzalez** [comment]
The regex issue will be fixed in 0.6.0 of go-procfile-util: https://github.com/josegonzalez/go-procfile-util/pull/15

**Comment by josegonzalez** [comment]
See #3464 for the go-procfile-util update.

**Comment by josegonzalez** [comment]
Apologies for the wait! Closing now as we finally have a PR open.
