### ISSUE TITLE
Suppport to Oracle Linux

### ISSUE THREAD

**Issue by phasath** [dokku/dokku#3430]
Hi! I've been using Dokku for a while, however, it doesn't suport Oracle Linux. 
So, I created an bash script to [install Dokku on Oracle Linux here](https://github.com/phasath/dokku_on_oracle_linux). Maybe, we can work to put it inside the dokku core as it used yum and Oracle Linux is really close to RHEL and CentOS.

**Comment by josegonzalez** [comment]
I think this can be closed in favor of https://github.com/dokku/dokku/issues/1076, which will allow us to run Dokku within a container on any host. I definitely recommend looking into that issue instead :)

Thanks for the suggestion though!
