### ISSUE TITLE
Failed: error connecting to db server: server returned error on SASL authentication step

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [dokku/dokku#3432]
I figured this is dokku 's issues more or less. I hope it's ok to post it here. 
https://github.com/dokku/dokku-mongo/issues/115

**Comment by josegonzalez** [comment]
This is not a dokku issue, that is why I moved it to the correct repository. The mongodb plugin you are using is not provided in the core repository, and this issue tracker is only for issues affecting the core.
