### ISSUE TITLE
Session issues on Scaling

### ISSUE THREAD

**Issue by ifightcode** [dokku/dokku#3437]
## Session issues when scaling the app
I'm using dokku for several years. However, all were for smaller web apps, never need any scaling. This time, I needed to scale and I used **dokku ps:scale myapp web=4**

All went well in command line, homepage of my web app came fine, so I sit back. After a few munites later, I started getting emails from my web app users, all of them were using issues in login.

I knew what changes I made, so scaled back to web=1 and everything came back to normal.

I understood, web=4 created 4 different containers, so definitely session was the reason for the issues I faced. I investigated a lot and became sure.

### How reproducible
I tried using Flask and Tornado, Python web framework. Both had the same issues. Create a small app in Tornado which uses session, push that in dokku apps without scaling, check. Then scale that to at least web=2 and recheck.

I'm sure there are some technologies to handle this situation instead of using third party session storage but I failed to find. So creating this issue to have a suggestion from you.

Thanks

**Comment by josegonzalez** [comment]
Can you describe he I might replicate this issue?

**Comment by ifightcode** [comment]
> Can you describe he I might replicate this issue?

I've prepared an example here
https://github.com/ifightcode/Dokku-Session-Issue-On-Scaling

**Comment by josegonzalez** [comment]
Your [cookie secret](https://github.com/ifightcode/Dokku-Session-Issue-On-Scaling/blob/master/main.py#L30) is unique for every invocation of the app. If you want to share cookie sessions across different processes, that should be the same.

I recommend setting the cookie as an environment variable via `dokku config:set`, and reading that into your app.

**Comment by ifightcode** [comment]
Yes, that worked. 
Thanks for your help.
