### ISSUE TITLE
Quotes over ssh not working

### ISSUE THREAD

**Issue by plietar** [dokku/dokku#345]
Using quotes as part of an ssh command is broken : 

Over SSH:
- `ssh -t dokku@dokku.me run app echo Hello` prints Hello
- `ssh -t dokku@dokku.me run app bash -c "echo Hello"` prints an empty newline.
- `ssh -t dokku@dokku.me run app 'bash -c "echo Hello"'` fails
- `ssh -t dokku@dokku.me run app bash -c \"echo Hello\"` fails

This is the error in the 3rd and 4th cases :

```
Hello": -c: line 0: unexpected EOF while looking for matching `"'
Hello": -c: line 1: syntax error: unexpected end of file
```

As a comparaison, on a non dokku ssh server (using bash as remote shell) :
- `ssh -t host echo Hello` prints Hello
- `ssh -t host bash -c "echo Hello"` prints an empty newline
- `ssh -t host 'bash -c "echo Hello"'` prints Hello
- `ssh -t host bash -c \"echo Hello\"` prints Hello

The second case is because the double quotes are interpreted by the local shell.
The command ends up as `bash -c echo Hello`, which runs echo with no args, and `Hello` is ignored.

As far as a know, this is not related to the run command, docker or pluginhook at all.
I just wanted the simplest use case, but it could be reproduced easily with other commands, part of the main `dokku` script.

The reason I've found is that `SSH_ORIGINAL_COMMAND`, used by sshcommand to pass arguments to dokku, does not give access to split arguments by default, but just the whole string. The remote command is then responsible for splitting it up, using "it's own" rules, which bash does in the second example.

Here are some links to posts and other similar projects dealing with the issue, and how to solve it, which could be used :
- http://www.ict.griffith.edu.au/anthony/info/apps/ssh.hints
- http://www.hackinglinuxexposed.com/tools/authprogs/src/authprogs
- https://github.com/GNOME/sysadmin-bin/blob/e296a647fa016d5802a14e6aea070d0b4a6dae36/run-git-or-special-cmd
- https://github.com/GNOME/sysadmin-bin/blob/master/run-git-or-special-cmd (Same as the above, rewritten in python)
- http://selenic.com/pipermail/mercurial-devel/2012-January/037268.html

This should be considered as low priority for now.

**Comment by ebeigarts** [comment]
Was this really fixed? I am trying this with 0.6.3 and 0.5 and 0.4 and it doesn't work:

```bash
$ ssh -t dokku@example.com -- run myapp echo Hello
Hello
Connection to example.com closed.
$ ssh -t dokku@example.com -- run myapp bash -c "echo Hello"

Connection to example.com closed.
$ ssh -t dokku@example.com -- run myapp 'bash -c "echo Hello"'

Connection to example.com closed.
$ ssh -t dokku@example.com -- run myapp bash -c \"echo Hello\"

Connection to example.com closed.
$ ssh -t dokku@example.com -- version
0.6.3
Connection to example.com closed.
```

**Comment by josegonzalez** [comment]
Did you setup your ssh config to use a [tty](http://dokku.viewdocs.io/dokku/deployment/remote-commands/)?

**Comment by ebeigarts** [comment]
@josegonzalez yes, I am using `-t`

**Comment by josegonzalez** [comment]
Please open a new issue with the necessary details.
