### ISSUE TITLE
Known problem - wrong ip after autoreset

### ISSUE THREAD

**Issue by adrian-kurzeja** [dokku/dokku#3451]
Hello, I'm junior dev. Don't know if there is right place to write about it but I think there are dokku masters that can help me. If it is wrong place I am sorry, but have no idea how to deal with problem.

I have a known problem:

Wrong ip used for docker container after auto restart. In nginx config there is still 172.17.0.18:5000 while app after restart has 172.17.0.6:5000.

command: "dokku nginx:build-config ws -t" fixs the problem but I have no idea how to detect restart of app inside container.

The implementation forces me to use 'dokku network:set node-js-app bind-all-interfaces false' - always false, becouse I have few apps/services on the same port, and when i turn on binding to all interfaces everything crashes out.

I made a service that rebuild config when it found in logs that app reseted but in docker events there are no such events ;/
in service file:
/usr/bin/docker events --filter "service=ws.web" --filter event=restart | /usr/bin/dokku nginx:build-config ws -t

Any ideas how can I fix it another way? Maybe corn job that will reset config every some time? but it is a kind of hack and I'm not sure if all will work correctly

**Comment by josegonzalez** [comment]
Unfortunately, I believe this is basically the same issue as #3152. I'd check the thread there as there are some workarounds until we get a proper fix in place.

Sorry you're having a bad experience!
