### ISSUE TITLE
Userland dokku?

### ISSUE THREAD

**Issue by ylluminate** [dokku/dokku#3452]
Is there a way to run Dokku in a kind of userland mode like Homebrew?  For example, if you want to deploy it to a single user account on a vps shared host such that dokku handles the dev + deployment cycle, and then could receive some customized scripting to restart services as needed?

Or would this require some custom tooling and/or a fork?

I'd like to see a heroku style tool that allows one to deploy apps across a variety of servers and styles of servers with some additional customization, but I'm afraid Dokku may not be entirely geared towards this from what I'm seeing.

**Comment by josegonzalez** [comment]
It’s not clear what you mean by “userland mode” in your post.

Dokku does allow people to deploy code via git, in a similar “style” as Heroku - and actually uses Heroku build packs by default - so it seems like we actually support what you want here? What limitations are you seeing from Dokku?

**Comment by josegonzalez** [comment]
Closing as it's been two weeks without comment. Feel free to leave a note if you have further notes.
