### ISSUE TITLE
Cannot SSH to dokku user from local machine

### ISSUE THREAD

**Issue by Lyelt** [dokku/dokku#3456]
I'm trying to deploy my app to my dokku server ([following this tutorial](http://www.karam.io/2018/Deploying-a-NET-Core-application-to-a-5-digitalocean-droplet-using-dokku/)), but I'm stuck due to the fact that SSH does not seem to be working for the "dokku" user. My remotes are set up as follows:

`dokku   dokku@my.domain:project (fetch)`
`dokku   dokku@my.domain:project (push)`
`origin  git@github.com:Lyelt/Project.git (fetch)`
`origin  git@github.com:Lyelt/Project.git (push)`

Running `git push dokku master` results in me being prompted to enter `dokku@my.domain's password`. Ditto when I run `ssh dokku@my.domain` locally. 

Running `ssh root@my.domain` works as expected (I am prompted for my key's passphrase). 

Running `ssh dokku@my.domain` works as expected when I run it from the dokku server.

**Comment by josegonzalez** [comment]
Did you browse to the server's ip - or domain name - and complete the web installer?

**Comment by Lyelt** [comment]
Yes, I did complete the web installer. Initially when I set it up I just used the IP address given to me, but I have since set up my DNS so that's what I've been using everywhere. I thought it could be a domain issue, but I am able to `ssh root@my.domain` just fine, so I settled on it being an SSH issue (the issue looked very similar to #528 but that solution did not work for me).

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems.

As well, please run the following commands for me:

```shell
dokku ssh-keys:list
cat /home/dokku/.ssh/authorized_keys
```

**Comment by Lyelt** [comment]
The results of the commands you requested:
[dokku-ssh-keys-list.txt](https://github.com/dokku/dokku/files/2924430/dokku-ssh-keys-list.txt)
[home-dokku-ssh-authorized_keys.txt](https://github.com/dokku/dokku/files/2924431/home-dokku-ssh-authorized_keys.txt)

`dokku report`:
[dokku-report.txt](https://github.com/dokku/dokku/files/2924432/dokku-report.txt)

Installed in a DigitalOcean Ubuntu 18.04.2 x64 Droplet.

Attempting to deploy [this repository](https://github.com/Lyelt/portfolio) (via SSH).

**Comment by josegonzalez** [comment]
Is the ssh key you are using the same for both the root user and your `dokku` user? Can you cat the contents of your _local_ `.ssh/config` file? Please let me know if you redact anything.

Can you also show me the output of:

```shell
# where $HOSTNAME is your server's hostname
ssh -vvv dokku@$HOSTNAME
```

**Comment by Lyelt** [comment]
Hmm, I actually don't have a local `.ssh/config` file at all. And yes, I am using the same key for both root and dokku users.

I used PuTTY to set up SSH locally and I am using Git Bash to run these commands locally. My local `.ssh` directory contains only `id_rsa`, `id_rsa.pub`, and `known_hosts`.

Here is the output of the requested command:
[ssh-vvv-dokku.txt](https://github.com/dokku/dokku/files/2924468/ssh-vvv-dokku.txt)

**Comment by josegonzalez** [comment]
What is the output of:

```
# where $HOSTNAME is your server's hostname
ssh -vvv dokku@$HOSTNAME
```

**Comment by josegonzalez** [comment]
You might also want to try our slack channel (#dokku on the [gliderlabs slack](https://slack.gliderlabs.com/)), where I can help you more quickly - I'll be sure to post any resolution here once we get to it - than a github issue.

**Comment by Lyelt** [comment]
I will join the Slack - thank you for being so responsive. 

In the meantime, you can see my last comment for the output of that command.

**Comment by josegonzalez** [comment]
Ah crap, I meant:

```
# where $HOSTNAME is your server's hostname
ssh -vvv root@$HOSTNAME
```

**Comment by Lyelt** [comment]
Ah, okay. Here is that output:

[ssh-vvv-root.txt](https://github.com/dokku/dokku/files/2924529/ssh-vvv-root.txt)

P.S. Do I need an invite to join that particular Slack? I've only used Slack for one workspace, so I'm not too familiar with it.

**Comment by josegonzalez** [comment]
Yep, each slack is unique, so you need to add our workspace (use that site to create a login etc.)

**Comment by Lyelt** [comment]
Sorry about my ignorance - I only ask because I clicked "Get My Invite" but it seemed to get stuck there and I did not receive any invitation email.

**Comment by josegonzalez** [comment]
Mind emailing me at the email on my profile? I'll send you an invite once you do :)

**Comment by Lyelt** [comment]
Done

**Comment by josegonzalez** [comment]
The issue here was two-fold:

- Permissions on `/home/dokku/.ssh/authorized_keys` (and the `/home/dokku/.ssh` folder) were `root:root`.
- The ssh key added was not the one the user actually used locally.

Not sure how we got into this position, but likely not easy for us to figure out a workaround. I'll close this for now, but if anyone has any good ideas, I'm all ears :)
