### ISSUE TITLE
Question: Creating an app with a wildcard domain.

### ISSUE THREAD

**Issue by KarlSayle** [dokku/dokku#3457]
Hi,

Are there any special considerations to be made (other than SSL certs) when creating an app that uses a wildcard subdomain? Do we create the app as per the docs? For example:

    dokku apps:create *.example.com

Thanks.

**Comment by josegonzalez** [comment]
We don't currently support domains named that way - that call will fail as `*` is not in the allowed regex for application names - and currently also do not support a wildcard subdomain in our domains plugin.

There is an existing issue to add this support in #3075, so I'll close this for now. Definitely want to get this in though!
