### ISSUE TITLE
remote rejected with trace (Rails, Webpacker)

### ISSUE THREAD

**Issue by dakotalightning** [dokku/dokku#3460]
## Description of problem
I can't seem to figure out why I'm getting this error, I've reviewed the troubleshooting doc. I've increased the memory, did multiple `git` deploys and nothing.
https://github.com/dokku/dokku/blob/master/docs/getting-started/troubleshooting.md

            Webpacker is installed 🎉 🍰
            Using /tmp/build/config/webpacker.yml file for setting up webpack paths
            Compiling…
            Compilation failed:
            
            
            
            !
            !     Precompiling assets failed.
            !
      To koda.cloud:space
      ! [remote rejected] feature/dokku -> master (pre-receive hook declined)
      error: failed to push some refs to 'dokku@cloud.com:space'

Trace
https://gist.github.com/dakotalightning/4f68cadf4b0e397f905edc53048d4f31

### Buildpacks

https://github.com/heroku/heroku-buildpack-nodejs
https://github.com/heroku/heroku-buildpack-ruby

Version: `0.12.13`

### `dokku report APP_NAME` output

    -----> uname: Linux cloud-01 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
    -----> memory: 
                        total        used        free      shared  buff/cache   available
          Mem:           1993         206        1537          11         249        1628
          Swap:             0           0           0
    -----> docker version: 
          Client:
            Version:           18.06.1-ce
            API version:       1.38
            Go version:        go1.10.3
            Git commit:        e68fc7a
            Built:             Tue Aug 21 17:24:51 2018
            OS/Arch:           linux/amd64
            Experimental:      false
          
          Server:
            Engine:
            Version:          18.06.1-ce
            API version:      1.38 (minimum version 1.12)
            Go version:       go1.10.3
            Git commit:       e68fc7a
            Built:            Tue Aug 21 17:23:15 2018
            OS/Arch:          linux/amd64
            Experimental:     false
    -----> docker daemon info: 
          Containers: 7
            Running: 3
            Paused: 0
            Stopped: 4
          Images: 24
          Server Version: 18.06.1-ce
          Storage Driver: overlay2
            Backing Filesystem: extfs
            Supports d_type: true
            Native Overlay Diff: true
          Logging Driver: json-file
          Cgroup Driver: cgroupfs
          Plugins:
            Volume: local
            Network: bridge host macvlan null overlay
            Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
          Swarm: inactive
          Runtimes: runc
          Default Runtime: runc
          Init Binary: docker-init
          containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
          runc version: 69663f0bd4b60df09991c08812a60108003fa340
          init version: fec3683
          Security Options:
            apparmor
            seccomp
            Profile: default
          Kernel Version: 4.15.0-36-generic
          Operating System: Ubuntu 18.04.1 LTS
          OSType: linux
          Architecture: x86_64
          CPUs: 2
          Total Memory: 1.947GiB
          Name: cloud-01
          ID: ...
          Docker Root Dir: /var/lib/docker
          Debug Mode (client): true
          Debug Mode (server): false
          Registry: https://index.docker.io/v1/
          Labels:
          Experimental: false
          Insecure Registries:
            127.0.0.0/8
          Live Restore Enabled: false
          
    -----> sigil version: 0.4.0
    -----> herokuish version: 
    the input device is not a TTY

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Digital Ocean

**Comment by dakotalightning** [comment]
It was the swap file!

I figured DigitalOcean's one-click install already configured everything. I guess that's my bad if anyone has a similar issue check your swap file.

**Comment by bepitulaz** [comment]
@dakotalighning can you explain more about the swap file, please? I get the same issue now. I deploy Rails 6 to Dokku in AWS Lightsail. Thanks.

**Comment by josegonzalez** [comment]
Please check [this document](http://dokku.viewdocs.io/dokku/getting-started/troubleshooting/) for information on adding a swap file to your server.
