### ISSUE TITLE
My rails app launched with dokku fails at all times (DigitalOcean)

### ISSUE THREAD

**Issue by veritme** [dokku/dokku#3472]
I have a rails application deployed with dokku and every day I have this error, "We're sorry, but something went wrong". Restart dekku with "dokku ps: restart app" and return to normal but after a while the same error comes back, thanks for your help.
This error in the logs, A server is already running. Check /app/tmp/pids/server.pid.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Closing as there hasn't been an update in two weeks.
