### ISSUE TITLE
App behind multiple proxies breaks remote_ip (forwarded-for etc)

### ISSUE THREAD

**Issue by fruitl00p** [dokku/dokku#3475]
### Description of problem
Currently we have an app behind another proxy (which is another dokku app on another host) I know, multiple hops, but hey, we like Skippy :)

### How reproducible
Have another proxy, in front of the app on a (i.e.) separate host. Try and read the x-forwarded-for remote IP of the original client. Due to the nginx.config.sigil having the wrong values for:
```
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
```
which should read
```
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header X-Forwarded-For $http_x_forwarded_for;
    proxy_set_header X-Forwarded-Port $http_x_forwarded_port;
```

I know this only works if the app is behind another proxy, but there might be another magic nginx flag somewhere that works both ways? (or allowing only overriding these params in a custom sigil?)

**Comment by josegonzalez** [comment]
What happens if you _don't_ have a proxy in front? Can the values be spoofed? What does the internet say about the correct values for those headers?

**Comment by fruitl00p** [comment]
If you don't have a proxy it should work just the same... However it indeed can be spoofed ... Since we've encountered this issue my colleague created a WIP-plugin to allow editing these headers ...  https://github.com/kingsquare/dokku-nginx-vhost-trustproxy This is still pretty much WIP, but should allow enabling the correct headers... 

This allows 'setting' the trust-proxy to a certain depth inside the application based on the environment variable (and thus mitigating the possible header injection issues) 

The plugin works, but if you look at the code for editing the nginx config it seems the `sed`-commands are a bit clunky :)

**Comment by josegonzalez** [comment]
Given the ability to spoof them, I think I prefer this being either a custom `nginx.conf.sigil` - you can inject one at the `post-extract` if deploying a lot of apps - or a custom plugin as you mentioned.

I'd rather our setup be safe for the 80% case than us try to do custom logic to handle an extra 10% and then have either bugs or subtle security issues. Hope that makes sense.

For now, can you PR that plugin? It seems like a somewhat reasonable approach. The `nginx.conf.sigil` doesn't change often, and the `sed` call _should_ be fine.

> We really need an actual plugin registry site...

**Comment by fruitl00p** [comment]
@josegonzalez thanks. Will add a PR for the plugin
