### ISSUE TITLE
Dokku ![remote rejected] error after pushing

### ISSUE THREAD

**Issue by AmiyKumar** [dokku/dokku#3483]
Dokku throws remote rejected error while trying to push Flask app.
Getting this error even after manually installing dokku by removing DigitalOcean
one-click-app image.
Error: Unable to select buildpack

Error log:
```
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (6/6), 517 bytes | 129.00 KiB/s, done.
Total 6 (delta 0), reused 0 (delta 0)
-----> Cleaning up...
-----> Building ok_app from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Unable to select a buildpack
To 68.183.xx.xx:app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@68.183.xx.xx:app'
```

**Comment by josegonzalez** [comment]
This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). 

Issues pertaining to buildpacks will be closed and/or locked.

> Note: This seems like a buildpack issue (its almost certainly that you haven't included a `requirements.txt` file.
