### ISSUE TITLE
Unable to upgrade Dokku

### ISSUE THREAD

**Issue by weyert** [dokku/dokku#3486]
## Description of problem
I have been trying to upgrade Dokku using the suggested command line `sudo apt-get install -qq -y dokku herokuish sshcommand plugn` but it each time says: `E: Packages were downgraded and -y was used without --allow-downgrades.`

## Environment Information

Output from `apt-get update`

```
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease  
Hit:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:4 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease         
Hit:5 http://ppa.launchpad.net/nginx/stable/ubuntu xenial InRelease            
Hit:6 https://download.docker.com/linux/ubuntu xenial InRelease                
Hit:7 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:8 https://packagecloud.io/dokku/dokku/ubuntu xenial InRelease
Reading package lists... Done
```

Linux version: Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-1079-aws x86_64)

`uname -a
Linux ip-10-77-16-149 4.4.0-1079-aws #89-Ubuntu SMP Tue Mar 26 15:25:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

I have installed it via the `bootstrap.sh` and is running on AWS EC2

**Comment by josegonzalez** [comment]
Can you run the following?

```
sudo apt-get install -y dokku herokuish sshcommand plugn
```

That will let me know what exactly is being downgraded (there shouldn't be anything in Dokku that is, but its certainly possible).

**Comment by josegonzalez** [comment]
I also need the full output of `dokku report`.

**Comment by weyert** [comment]
The problem which stopped me from upgrading was because I used the Ansible Dokku script (paid) which pins the packages

**Comment by josegonzalez** [comment]
Seems as though the user had an older version pinned via the official ansible playbooks in a `/etc/apt/preferences.d/ansible-hold-dokku` file, and then ran a forceful upgrade separately through the bootstrap script.

When installing via the ansible modules, it is more or less expected that the versions specified there are the ones the user wishes to install, and thus users should continue using the ansible playbooks in those cases (modifying their variables appropriately).
