### ISSUE TITLE
[noob] Deployment failure for dockerized Rails app

### ISSUE THREAD

**Issue by soykje** [dokku/dokku#3503]
## Description of problem
Hello, I'm getting started with Dokku, and currently trying to deploy a dockerized Rails application with it.
But when I run the `git push dokku` command, deployment fails for a reason I can't get :/

### How reproducible
I run Dokku through a DigitalOcean droplet (10$ plan), and added swap (just in case...).

### Steps to Reproduce
1. Create a Dokku instance, and link a newly created app to the repository
2. Push the branch
3. The error comes!

#### Actual Results
https://gist.github.com/soykje/1ddeb5f04fd85e8bd2d2b1f46e63da1e

#### Expected Results
Of course, I expected success... But maybe my docker configuration is not correct?

### `dokku report APP_NAME` output
https://gist.github.com/soykje/f5192775742848f96437705c6608080f

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Dokku has been installed through a One-click droplet from DigitalOcean.

### Additional information
**Dockerfile**
```
FROM ruby:2.5.5-slim

ARG PRECOMPILEASSETS

ENV SECRET_KEY_BASE=foo

RUN apt-get update && apt-get install -y curl gnupg
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN curl -q https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

RUN apt-get -y update && \
    apt-get install --fix-missing --no-install-recommends -qq -y \
      build-essential \
      imagemagick \
      vim \
      wget gnupg \
      git-all \
      curl \
      ssh \
      postgresql-client-10 libpq5 libpq-dev -y && \
    wget -qO- https://deb.nodesource.com/setup_9.x  | bash - && \
    apt-get install -y nodejs && \
    wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install yarn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN gem install bundler
# Install gems
RUN mkdir /gems
WORKDIR /gems
COPY Gemfile .
COPY Gemfile.lock .
RUN bundle install

ARG INSTALL_PATH=/beweeg
ENV INSTALL_PATH $INSTALL_PATH
WORKDIR $INSTALL_PATH
COPY . .

# Precompile assets (or not)
RUN docker/potential_asset_precompile.sh $PRECOMPILEASSETS
```

Thank you in advance for your help!

**Comment by josegonzalez** [comment]
You do not have a `Procfile` in your repository to define commands to run, and your Dockerfile also does not specify a `CMD`. You'll need one or the other in order for containers to run. See [this documentation](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/#customizing-the-run-command) for more details.

I noticed in a previous version of this post, you had a docker-compose file attached. We don't support docker-compose, nor do we have any plans to do so, which is why your app isn't starting (we won't respect the commands placed in that file).
