### ISSUE TITLE
Triggering builds with webhooks

### ISSUE THREAD

**Issue by happenslol** [dokku/dokku#3505]
Hi! I'm currently using this awesome project to host many of my personal sites. Among them are several static pages that have their content either included in the repo in markdown files, or on external pages such as [prismic](https://prismic.io/).

Prismic can call a specified webhook whenever content was updated, so that your apps can re-generate and retrieve the changed content. I've previously implemented docker images that would basically serve the static app just like normal, but have an endpoint that triggers the build process inside the running app. This however doesn't have the benefits of zero-downtime redeployment and everything else I would get if I just used `ps:rebuild <app>`, so I would prefer having a solution that's built into dokku itself, e.g. something akin to a webhook-plugin.

It could work as follows:

* The user can dedicate a url to webhooks with a command like `webhooks:add-domain hooks.example.org`
* A very simple server with persistent key-value store (in go) can be enabled by the user: `webhooks:enable`
* The user can enable webhooks for certain apps by adding a secret for them, which will be required to trigger them: `webhooks:add-secret my-app abcdefg123456789`
* POSTing the appropriate secret to `hooks.example.org/my-app/rebuild` would then trigger a rebuild. Other actions such as restart or start/stop could also be added easily.

I'm interested in implementing this myself, do you have any general concerns with the idea? And would you be open to answering a few questions about implementation details? I could probably dig through it myself, but I'm sure it would be quicker with a few pointers :-)

**Comment by josegonzalez** [comment]
This is a neat idea, and something I manually did before. The way I did it was a golang app that mounted the dokku-daemon socket and issued commands. I specifically did this with the socket approach as I wanted the web/worker to be managed as a Dokku app, which meant the options were to either mount the socket or ssh back into the box (blech).

If you run it on the host, then you can do a subprocess call within your application when interacting with Dokku, but I don't like that approach as its kinda messy in terms of installing the process if you don't use something that compiles binaries.

I could track secrets for each app in a database, in an `apps` table.

- app name
- a secret

Thus, a secret may only be used for a single app.

Endpoints were defined in the database in the `endpoints` table, and were comprised of

- A dokku command that would be executed
- A description for the command
- A url path that would invoke this endpoint
- A json dictionary describing each argument for the command and a definition for each argument. Something like `{"app": "name of app", "process-type": "name of the process type"}`
- A command template. Something like: `checks:disable $app $process-type`

I then tied endpoints to apps, so each app could enable/disable an endpoint at will. Once that was done, I had a simple listing of all apps and could click through to each one to see what endpoints were enabled, and how to call them.

If a user triggered an endpoint on the web process, I did a few things:

- Validate the secret against the app specified
- Verify that the endpoint called was valid for the app in question
- Validate that all the arguments defined in the json dictionary were defined as query string arguments
- Queue up the message for later processing (A Postgres table as I didn't want multiple datastores).
- Respond with a token to be used to track job progress.

A background worker then worked on the message. It would fetch the endpoint in question, template out the command, and call the socket process with that command. The logging output would be stored in the database alongside any data for the "job" in question. These logs could be viewed at any time via a simple web ui, and also retrieved via api.

---

Some prior art:

- dokku-api: https://github.com/dokku/dokku-api
- dokku-daemon: https://github.com/dokku/dokku-daemon
- dokku-daemon (in go): https://github.com/beydogan/dokku-daemon-go
- deployer: https://github.com/mak-it/deployer

---

You could probably build the same thing with a plugin that integrated with the above (it could either hit api endpoints to configure webhooks or write directly to the database. The former is cleaner.). The thing that is missing is a `git-sync` plugin. I have this as closed source but am hoping to add it to Dokku core in the next minor release, and you'd then be able to run something like:

```shell
# allow talking to a remote host
dokku git:allow-host github.com

# set the git remote
dokku git:set APP remote git@github.com:example/example.git

# just fetch changes to the app
# and manually call rebuild
dokku git:fetch APP
dokku ps:rebuild APP

# or fetch and build the app at the same time
dokku git:fetch-and-build APP

# fetch and build a specific commit
dokku git:fetch-and-build APP abc1234
```

---

If you have further questions, it might be great to discuss this in slack/irc. I'm going to close this for now as having this sort of thing built into Dokku would be cool, but definitely a huge distraction from the main project (cool as an official subproject though!).
