### ISSUE TITLE
Can't get mobile app to connect to a worker container

### ISSUE THREAD

**Issue by paschaldev** [dokku/dokku#3508]
I have a serious problem with a worker container running on port `6001`. My `web` container runs fine on PORT 80 and the domain and everything is good.

However, I have a socket server worker container that is started and it runs on PORT `6001` but unfortunately, I can never connect to it.

This question might be unrelated to dokku (not sure) but I need help if any. When I `curl` the URL on port `6001`, it FAILS TO CONNECT.

**Comment by josegonzalez** [comment]
Dokku only supports proxying the `web` container, and does not create a proxy for any other containers. Unfortunately, you will need to deploy separate applications if you want two processes exposing ports.
