### ISSUE TITLE
Error Deploying: fatal: unable to run cd: file does not exist

### ISSUE THREAD

**Issue by HiepMa** [dokku/dokku#3519]
root@dokku-be:~/AsOnlineASTest1/webapp# dokku logs:failed webapp
=====> webapp failed deploy logs
/tmp/bashenv.041366666: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.006201950: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.950853302: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.824272401: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.851754736: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.168958537: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

Can you also run the following:

```
dokku --trace logs:failed webapp
```

And paste the output?

**Comment by HiepMa** [comment]
root@dokku-be:~/AsOnlineASTest1/webapp# dokku --trace logs:failed webapp
+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOKKU_IMAGE=gliderlabs/herokuish
+ DOKKU_IMAGE=gliderlabs/herokuish
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ DOKKU_GLOBAL_RUN_ARGS=--label=dokku
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args logs:failed webapp
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=2
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ next_index=3
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ logs:failed =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ /usr/bin/tty
+ [[ /dev/pts/1 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ logs:failed =~ ^plugin:.* ]]
+ [[ logs:failed == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ -n '' ]]
+ dokku_auth logs:failed webapp
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=root
+ SSH_USER=root
+ export SSH_NAME=default
+ SSH_NAME=default
+ plugn trigger user-auth root default logs:failed webapp
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ logs:failed =~ (ssh-keys:add|ssh-keys:remove) ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd logs:failed webapp
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=logs:failed
+ local PLUGIN_CMD=logs:failed
+ local implemented=0
+ local script
+ argv=("$@")
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/logs
+ [[ /var/lib/dokku/core-plugins/available/logs == *core-plugins* ]]
+ [[ logs:failed == \l\o\g\s\:\f\a\i\l\e\d ]]
+ shift 1
+ [[ -n '' ]]
+ set -- logs:failed webapp
+ [[ -x /var/lib/dokku/plugins/enabled/logs:failed/subcommands/default ]]
+ [[ -x /var/lib/dokku/plugins/enabled/logs:failed/subcommands/logs:failed ]]
+ [[ -x /var/lib/dokku/plugins/enabled/logs/subcommands/failed ]]
+ [[ -n failed ]]
+ /var/lib/dokku/plugins/enabled/logs/subcommands/failed logs:failed webapp
+ source /var/lib/dokku/plugins/available/apps/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
++ source /var/lib/dokku/plugins/available/config/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
+ source /var/lib/dokku/plugins/available/config/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+ set -eo pipefail
+ [[ -n 1 ]]
+ set -x
+ cmd-logs-failed logs:failed webapp
+ declare 'desc=shows the last failed deploy logs'
+ argv=("$@")
+ declare cmd=logs:failed argv
+ [[ logs:failed == \l\o\g\s\:\f\a\i\l\e\d ]]
+ shift 1
+ declare APP=webapp
+ local DOKKU_SCHEDULER
+ [[ -z webapp ]]
+ fn-logs-failed-single webapp
+ declare 'desc=shows the last failed deploy logs for an app'
+ declare APP=webapp
+ local DOKKU_SCHEDULER
+ dokku_log_info2_quiet 'webapp failed deploy logs'
+ declare 'desc=log info2 formatter (with quiet option)'
+ [[ -z '' ]]
+ echo '=====> webapp failed deploy logs'
=====> webapp failed deploy logs
++ get_app_scheduler webapp
++ declare 'desc=fetch the scheduler for a given application'
++ declare APP=webapp
++ local DOKKU_APP_SCHEDULER DOKKU_GLOBAL_SCHEDULER DOKKU_SCHEDULER
++ [[ -n webapp ]]
+++ config_get webapp DOKKU_SCHEDULER
+++ declare 'desc=get value of given config var'
+++ config_sub get webapp DOKKU_SCHEDULER
+++ declare 'desc=executes a config subcommand'
+++ local name=get
+++ shift
+++ /var/lib/dokku/plugins/available/config/subcommands/get config:get webapp DOKKU_SCHEDULER
+++ true
++ DOKKU_APP_SCHEDULER=
+++ config_get --global DOKKU_SCHEDULER
+++ declare 'desc=get value of given config var'
+++ config_sub get --global DOKKU_SCHEDULER
+++ declare 'desc=executes a config subcommand'
+++ local name=get
+++ shift
+++ /var/lib/dokku/plugins/available/config/subcommands/get config:get --global DOKKU_SCHEDULER
+++ true
++ DOKKU_GLOBAL_SCHEDULER=
++ DOKKU_SCHEDULER=
++ [[ -z '' ]]
++ DOKKU_SCHEDULER=docker-local
++ echo docker-local
+ DOKKU_SCHEDULER=docker-local
+ plugn trigger scheduler-logs-failed docker-local webapp
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ scheduler-docker-local-scheduler-logs-failed docker-local webapp
+ declare 'desc=scheduler-docker-local scheduler-logs-failed plugin trigger'
+ declare 'trigger=scheduler-docker-local scheduler-logs-failed'
+ declare DOKKU_SCHEDULER=docker-local APP=webapp
+ local FAILED_CONTAINERS_FILE=/var/lib/dokku/data/scheduler-docker-local/webapp/failed-containers
+ DEAD_CONTAINERS=()
+ DOKKU_LOGS_CMD=()
+ RUNNING_CONTAINERS=()
+ local DEAD_CONTAINERS DOKKU_LOGS_CMD RUNNING_CONTAINERS
+ local CID LINE PREFIX
+ shift 2
+ [[ docker-local != \d\o\c\k\e\r\-\l\o\c\a\l ]]
+ [[ ! -f /var/lib/dokku/data/scheduler-docker-local/webapp/failed-containers ]]
+ read -r LINE
++ cut -d ' ' -f1
++ echo 'f48da36571785b5309f9c912f4a3622eee11d033d72f389a13df2a374f5cd392 web.1'
+ CID=f48da36571785b5309f9c912f4a3622eee11d033d72f389a13df2a374f5cd392
++ cut -d ' ' -f2
++ echo 'f48da36571785b5309f9c912f4a3622eee11d033d72f389a13df2a374f5cd392 web.1'
+ PREFIX=web.1
+ docker inspect f48da36571785b5309f9c912f4a3622eee11d033d72f389a13df2a374f5cd392
+ RUNNING_CONTAINERS+=("$CID")
+ read -r LINE
+ [[ -n '' ]]
+ [[ 1 -eq 0 ]]
+ (( MAX_INDEX = 1 - 1 ))
+ true
+ for i in ${!RUNNING_CONTAINERS[*]}
+ local CID=f48da36571785b5309f9c912f4a3622eee11d033d72f389a13df2a374f5cd392
+ DOKKU_LOGS_CMD+='(docker logs  f48da36571785b5309f9c912f4a3622eee11d033d72f389a13df2a374f5cd392 2>&1)'
+ [[ 0 != \0 ]]
+ local 'DOKKU_LOGS_CMD+=; '
+ bash -c '((docker logs  f48da36571785b5309f9c912f4a3622eee11d033d72f389a13df2a374f5cd392 2>&1); )'
/tmp/bashenv.139672766: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.823933575: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.457584478: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.273965792: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.589520133: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.412402440: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
/tmp/bashenv.937998093: line 563: ./webapp: Is a directory
setuidgid: fatal: unable to run cd: file does not exist
+ implemented=1
+ [[ 1 -eq 0 ]]
+ [[ 1 -eq 0 ]]

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

Also, if you can show the entire output of your deploy, that would be useful. It sounds like your Procfile was attempting to execute a binary that doesn't exist in your codebase potentially.

**Comment by josegonzalez** [comment]
Closing as there hasn't been an update in two weeks.
