### ISSUE TITLE
moving to go module?!

### ISSUE THREAD

**Issue by AlaaAttya** [dokku/dokku#3521]
it's just a suggestion to move to go modules

**Comment by josegonzalez** [comment]
In regards to moving to go modules, such a move doesn't buy us anything at this time. The existing setup works fine for us. A better use of my time in the golang dependency world would be to mount a build-cache during CI runs.

Closing as this is likely not going to be implemented by me anytime soon, though if you'd like to contribute this as a pull request, feel more than free to :) .
