### ISSUE TITLE
 --quiet in "dokku run" and "Found ... in Procfile, running that command" output

### ISSUE THREAD

**Issue by supcik** [dokku/dokku#3522]
## Description of problem

I am running a dokku command to start a regular job (using cron). For this project, I am using dokku version 0.15.5 with Python buildpack. I wrote a simple `Procfile` with the command that I want to run:

```
command-name: python command-name.py
```

Here is the line from the crontab:

```
@hourly dokku --quiet --rm-container run my-app command-name
```

It works fine, but my log is full of "Found command-name in Procfile, running that command". I tried to add the `--quiet` flag, but it did not help.

Then I tried to call the command directly (`python command-name.py`), and the program seemed to be called but then the message was "no matching process entry found". (Did my command actually run? The message was rather "pessimistic" and perhaps something like "no matching process entry found, running command ... directly." would be more helpful).

In your [documentation](https://github.com/dokku/dokku/blob/master/docs/deployment/one-off-processes.md) you write : 

> Try to keep tasks quiet so that mails only send on errors

and I fully agree! So I would actually like that `dokku run` keeps quiet if it correctly finds a command in the `Procfile`.

## Workaround

I solved this issue by completely deleting the Procfile and calling the command directly. Now the command is called and the output is "clean".

## Proposal

Suppress the output "Found ... in Procfile, running that command" when the option `--quiet` is given to `dokku run`

**Comment by josegonzalez** [comment]
Sounds like there are two issues:

- Moving the `Found ...` message to log_quiet.
- Figure out why your command isn't being found.

Can you provide a sample application where this issue can be duplicated so I can fix the latter?

**Comment by supcik** [comment]
Thank you for your reply. You are right; we can see two issues here.

Here is a sample application to illustrate the issue : https://github.com/supcik/dokku-3522.

Here are 3 invocation

1) Run using the key in Procfile:
```
> dokku --rm-container run dokku-3522 hello
-----> Found 'hello' in Procfile, running that command
Hello
```

2) Run a non-existing name/command:
```
> dokku --rm-container run dokku-3522 not-here
no matching process entry found
setuidgid: fatal: unable to run not-here: file does not exist
```

3) Run a command directly (not a key in the Procfile):
```
> dokku --rm-container run dokku-3522 python hello.py   supcik@js-do-fra1-ubu18
no matching process entry found
Hello
```

In cases 2) and 3), the message is the same : "no matching process entry found". This is indeed an error for 3), but for 2) there is no error.

How can I help further ? Do you want me to create a new issue for this case ?

**Comment by josegonzalez** [comment]
Nope, this is totally fine.

Seems like we'll want to also change the `no matching process entry found` to be part of log_quiet too, which should help.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
