### ISSUE TITLE
![remote rejected] pre-receive hook declined

### ISSUE THREAD

**Issue by vaibhav-y** [dokku/dokku#3524]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

## Description of problem
Pushing to dokku (from a remote host, or from my DO box, fails wth

### How reproducible
Consistent hook rejections

### Steps to Reproduce

1. Try to deploy http://github.com/vaibhav-y/website
2. No buildpacks configured on server (I have a .buildpacks file in the project root)
3. dokku env vars: NGINX_ROOT=/app/www/public HUGO_VERSION=0.40.1

#### Actual Results
https://gist.github.com/vaibhav-y/1d2c1b7702d4e2a748a035b1bf8243bc

#### Expected Results
Should've deployed and served static files via nginx

## Environment Information
Trace output: https://gist.github.com/vaibhav-y/1d2c1b7702d4e2a748a035b1bf8243bc#file-dokku-trace-and-push

```bash
$ cat /home/dokku/calloc_site/ENV
DOKKU_APP_TYPE="herokuish"
GIT_REV="ed8fcf24463fd791f7ad69268bf8b42e52f7098f"
HUGO_VERSION="0.40.1"
NGINX_ROOT="/app/www/public"
```

### `dokku report APP_NAME` output
https://gist.github.com/vaibhav-y/1d2c1b7702d4e2a748a035b1bf8243bc#file-dokku-report-app-output

### Additional information

- Container Inspect Output (if applicable):
  - 0.13.0+: `dokku inspect APP_NAME`
  - <0.13.0: `docker inspect CONTAINER_ID`: WARNING, `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX.
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

**Comment by josegonzalez** [comment]
For a specified buildpack to work, the `detect` phase must _also_ exit 0. In this case, the static buildpack requires a `.static` file in your repo (your Hugo buildpack should be sure to copy it into place if it does not).

Closing as this is an app setup issue, but we also don't give general buildpack support here on Github issues (its not the easiest venue to go back and forth on). Please join our irc or slack channel if you'd like continued support.
