### ISSUE TITLE
400 Bad Request error with DotNet Core Web API hosted with Dokku on DigitalOcean

### ISSUE THREAD

**Issue by gorums** [dokku/dokku#3526]
## Description of problem

I have problem with my Dotnet Core Web API with Angular 7. Everything works perfectly on localhost. When I upload to Dokku I am unable to send POST to server, I am getting 400. The GET methods are fine.

What do I need to change on the nginx to allow this and how to change it???

**Comment by gorums** [comment]
check this https://stackoverflow.com/questions/55640013/400-bad-request-error-with-asp-net-core-hosted-with-dokku-on-digitalocean

**Comment by josegonzalez** [comment]
You may freely customize your `nginx.conf.sigil` as shown in our nginx documentation.

Closing as this isn't an issue with Dokku or our buildpacks. Feel free to ask for support on our slack or irc channel.
