### ISSUE TITLE
502 Bad Gateway after server reboot

### ISSUE THREAD

**Issue by zakelfassi** [dokku/dokku#354]
On Ubuntu 13.04, When the server is rebooted, all the app (Rack/Rails) show a `502 Bad Gateway` , `dokku ps` has only PostgreSQL containers, and the `/var/run/docker.sock` permissions are reset.

Any idea?

Edit: The Ngix logs show : 

```
2013/11/27 13:35:52 [error] 2186#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: [IP_ADDRESS], server: APP.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:49153/favicon.ico", host: "APP.com"
```

**Comment by dallas** [comment]
I'm having major trouble getting a Ghost app (an Express.js app running on node) to work on my dokku (version 0.3.13-88-g2dad1af) running on a Digital Ocean droplet. I've added the config variable to set `NODE_ENV=production` and the app logs tell me that "Ghost is running... Your blog is now available on http://dallasandnicole.com". In the nginx error.log I just see lines like this `2015/02/04 23:27:51 [error] 25746#0: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 24.117.148.163, server: dallasandnicole.com, request: "GET / HTTP/1.1", upstream: "http://172.17.1.84:5000/", host: "www.dallasandnicole.com"`. I can't for the life of me figure out what is wrong with it. Can anybody help point me in the right direction?

**Comment by dallas** [comment]
okay, I did `nmap -p1-10000 172.17.1.84` (the port we're looking for is `5000`) and got these results:

```
Starting Nmap 6.40 ( http://nmap.org ) at 2015-02-04 23:57 EST
Nmap scan report for 172.17.1.84
Host is up (0.000023s latency).
All 10000 scanned ports on 172.17.1.84 are closed
MAC Address: 02:42:AC:11:01:54 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 3.70 seconds
```

When I ran the same thing on another node app I have successfully running, I get:

```
Starting Nmap 6.40 ( http://nmap.org ) at 2015-02-04 23:58 EST
Nmap scan report for 172.17.0.185
Host is up (0.000024s latency).
Not shown: 9999 closed ports
PORT     STATE SERVICE
5000/tcp open  upnp
MAC Address: 02:42:AC:11:00:B9 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 3.38 seconds
```

What gives? What do I need to do to ensure that the port is open?

**Comment by michaelshobbs** [comment]
Can you please open a new issue? Also include the output from `dokku logs <app name>`.

**Comment by dallas** [comment]
Created #948 for my issue, thanks!

**Comment by bogdanrn** [comment]
For whoever lands here like i did, i had the same problem. After i rebooted the machine, i got 502 bad gateway and couldn't deploy the app. When i checked the nginx logs i found something related to mongodb, and as i saw in this thread, i went on a goose chase trying to figure out how to re-attach mongodb to my app, but that wasn't the case.

The fix was simple, after reboot , dokku doesn't start the mongodb service automatically , so i just had to dot it manually

``` dokku mongodb:start ``` 

The app was still not working, but after i re-deployed it , it worked.
