### ISSUE TITLE
[feature-request]: Add `can_scale` value to `ps:report`

### ISSUE THREAD

**Issue by tarzzz** [dokku/dokku#3544]
## High Level Plan

- Add a function called `fn-ps-can-scale()`. This should attempt to extract the `DOKKU_SCALE` file to a temp directory, and return 0 if it can, 1 if it cannot.
- Add the `--ps-can-scale` flag to `ps:report`
- Add a check to ps:scale (when invoked with scale args) to verify that the scale command will indeed scale. [Exit 78](https://github.com/freebsd/freebsd/blob/6c262608dd9129e8699bd3c3a84425b8076b83ae/include/sysexits.h#L113) if it cannot scale.

## Original Post

Currently, There is no way to know the app scale is being managed from `ps:scale`, or `DOKKU_SCALE` present in the repository. If `DOKKU_SCALE` is present in the repository, running `ps:scale` has no affect on the app-scale.

Would be great to have a `can_scale` (boolean) value available on `ps:report` which checks the presence of `DOKKU_SCALE` file and reports accordingly.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
