### ISSUE TITLE
Remove injection of secrets into profile files

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#3545]
Rather than inject secrets into the docker image, it would be great to be able to use environment variables for executing commands. A few notes:

- Removing the secrets from the docker image would allow images to be more safely shipped to a registry without having the registry leak app secrets.
- If secrets are not injected into the docker image, a given docker image can be used across multiple apps, allowing for UAT-type pipelines to be run a bit more easily.
- `--env-file` does [not support](https://github.com/moby/moby/issues/12997) multiline environment variables. This is a hard-blocker on that path, unfortunately.
- We can use the `-e` flag [without an value](https://github.com/moby/moby/issues/12997#issuecomment-253929145) to have it inherit the value from the current context. This might require scoping regular variables in the context to use a prefix, or maybe even having a `docker_run` style command.
    - How does this handle container restarts?

@michaelshobbs Any thoughts?

**Comment by michaelshobbs** [comment]
might be tricky to implement for the reasons you've outlined, but worth the effort IMO

**Comment by josegonzalez** [comment]
Since you responded, I've assigned the ticket to you :D

**Comment by michaelshobbs** [comment]
i feel attacked

**Comment by josegonzalez** [comment]
One thing this might allow is faster `ps:restart/ps:start` calls, as the image wouldn't need to be rebuilt again for each one. I think this is the major reason we do that in the first place.

**Comment by weyert** [comment]
Do you mean that you are saving the config vars when you are building with a build pack in profile.d? Sounds like a great idea to avoid leaking secrets. I am wondering if there is any way I could assist?

**Comment by josegonzalez** [comment]
Yeah, thats exactly what we're doing at the moment.

If you want to help out, you could try looking at the workaround I posted above for executing `docker run` commands with the environment specified.

**Comment by alexquick** [comment]
I'm not too familiar with the profile stuff so it may not help, but fwiw `config:export/config_export` supports formatting an entire config as docker args:
```
# dokku config:export --format docker-args --merged envtest
--env=CURL_CONNECT_TIMEOUT='90' --env=CURL_TIMEOUT='600' --env=DOKKU_APP_RESTORE='1' --env=DOKKU_APP_TYPE='herokuish' --env=DOKKU_PROXY_PORT='80' --env=DOKKU_PROXY_PORT_MAP='http:80:5000  ' --env=FLASK_APP='server.py' --env=GIT_REV='049e89a8b005ff60665a17ab4f1e7d43b38574c4'
```

Newlines, single quotes, etc are quoted and escaped so that a bash eval into an array will yield the correct values, which can then be interpolated into the `docker run` command.

**Comment by josegonzalez** [comment]
That might help. Not sure if docker properly injects environment variables in a way that respects newlines if using `--env` with a value, but worth a try!

**Comment by weyert** [comment]
Wouldn't converting them to escaped variant e.g. \n solve this?

**Comment by josegonzalez** [comment]
Configs and secrets don't apply to generic `docker run` commands, as we're trying to build an image here.

**Comment by josegonzalez** [comment]
0.22.0 added experimental support for [Cloud Native Buildpacks](https://buildpacks.io/) which avoids this entire issue. A future release of Dokku will switch over entirely to this over Herokuish (once `pack` supports all the functionality we need) so I'm going to close this for now as we won't be "fixing" this for the herokuish builder.
