### ISSUE TITLE
Change nginx proxy

### ISSUE THREAD

**Issue by Padrio** [dokku/dokku#3569]
Hi there,

so I know, you're planing to implement the capability of swapping the proxy software in the future. At least that's what [the docs](https://github.com/dokku/dokku/blob/master/docs/networking/proxy-management.md) tell me: 
> (...) In the future this will allow other proxy software - such as HAProxy or Caddy - to be used in place of nginx.

But in my specific case I don't want to completely replace nginx with a different software like HAProxy but rather compiling my own nginx version to upgrade the base version and include some more plugins (brotli, pagespeed etc). 

What do I have to watch out for, when compiling nginx from source? 
As i know, building from source will put configs etc into a different directory than installing through a package manager. Is there any config to maybe just change some variables to tell dokku where nginx is located?

**Comment by josegonzalez** [comment]
> Swapping out proxies is possible today, though there are no plans to provide alternative implementations as an official project. The nginx-vhosts plugin handles it well enough as is.

If you can provide OS packages for Nginx, then that should be enough to swap out the existing nginx support. On Debian, you can also provide an `openresty` package, as shown in the [control file](https://github.com/dokku/dokku/blob/master/debian/control#L8).

If you need any more help, please drop by our slack or irc channel.
