### ISSUE TITLE
Deployment to dokku on local server - failed to connect to ftp.csx.cam.ac.uk on version 0.9.4

### ISSUE THREAD

**Issue by developer-ly** [dokku/dokku#3572]
## Description of problem
Trying to deploy my frontend application on dokku, but it fails to do so on a new branch because the ftp.csx.cam.ac.uk is not reachable...

### Steps to Reproduce
Here is the step where the deployment fail. this is a snippet from my gitlab-ci.yml file

deployWithGitProd:
    stage: deploy
    only:
        - master
    tags:
        - angular
        - vpn
    script:
        - xcopy /s build_files dist
        - cd dist
        - git init
        - git add .
        - git commit -m "Deploy commit"
        - git remote add dokku01 dokku@dokku01.[domain].intra:[appName]
        - git push -f dokku01 master
        - cd ..

#### Actual Results
$ git remote add dokku01 dokku@dokku01.[domain].intra:[appName]
$ git push -f dokku01 master
remote: -----> Cleaning up...        
remote: -----> Building [appName] from herokuish...        
remote: -----> Adding BUILD_ENV to build environment...        
remote:        -----> Fetching custom buildpack        
remote:        -----> .static app detected        
remote: -----> copy static files to www        
remote: -----> download and unzip pcre        
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current        
remote:                                  Dload  Upload   Total   Spent    Left  Speed        
remote: 
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to ftp.csx.cam.ac.uk port 80: Connection refused        
To dokku01.[domain].intra:[appName]
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku01.[domain].intra:[appName]'
ERROR: Job failed: exit status 1

#### Expected Results
expected is fetching nginx from ftp.csx.cam.ac.uk instead of reusing the cached version. the cached version here is from the deployment from the development branch instead of this master branch.

remote: -----> Cleaning up...        
remote: -----> Building [appName]-staging from herokuish...        
remote: -----> Adding BUILD_ENV to build environment...        
remote:        -----> Fetching custom buildpack        
remote:        -----> .static app detected        
remote: -----> copy static files to www        
remote: -----> reuse nginx from cache        
remote: -----> using user provided nginx.conf.erb        
remote: -----> using default mime.types        
remote:        -----> Discovering process types        
remote:        Default types for  -> web        
remote: -----> Releasing [appName]-staging (dokku/[appName]-staging:latest)...        
remote: -----> Deploying [appName]-staging (dokku/[appName]-staging:latest)...        
remote: -----> Attempting to run scripts.dokku.predeploy from app.json (if defined)        
remote: -----> App Procfile file found (/home/dokku/[appName]-staging/DOKKU_PROCFILE)        
remote: -----> DOKKU_SCALE file found (/home/dokku/[appName]-staging/DOKKU_SCALE)        
remote: =====> web=1        
remote: -----> Attempting pre-flight checks        
remote:        For more efficient zero downtime deployments, create a file CHECKS.        
remote:        See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples        
remote:        CHECKS file not found in container: Running simple container check...        
remote: -----> Waiting for 10 seconds ...        
remote: -----> Default container check successful!        
remote: -----> Running post-deploy        
remote: -----> Found previous container(s) (77561e66e183) named [appName]-staging.web.1        
remote: =====> renaming container (77561e66e183) [appName]-staging.web.1 to [appName]-staging.web.1.1559034177        
remote: =====> renaming container (687dfef4ccae) gallant_nobel to [appName]-staging.web.1        
remote: -----> Configuring [appName]-staging.[domain].ch...(using built-in template)        
remote: -----> Creating http nginx.conf        
remote: -----> Running nginx-pre-reload        
remote:        Reloading nginx        
remote: -----> Setting config vars        
remote:        DOKKU_APP_RESTORE: 1        
remote: -----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)        
remote: -----> Shutting down old containers in 60 seconds        
remote: =====> 77561e66e183821d1dcc039875204651123bd8d6da1d267c1f64df6ee6f59863        
remote: =====> Application deployed:        
remote:        http://[appName]-staging.[domane]        
remote:         
To dokku01.[domain].intra:[appName]-staging
 + c8e7069...b03a678 master -> master (forced update)
$ cd ..
Job succeeded

### `dokku report APP_NAME` output
-----> uname: Linux [ServerName] 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
              total        used        free      shared  buff/cache   available
Mem:           7983         380        5170          87        2432        7008
Swap:          8191           0        8191
-----> docker version:
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info:
Containers: 43
 Running: 7
 Paused: 0
 Stopped: 36
Images: 230
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 344
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796GiB
Name: [ServerName]
ID: MNCS:O5JP:4IND:NRKH:ZRWQ:63QD:4POK:3NTE:CVTJ:Y4IV:5L2B:BN4F
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version:
herokuish: 0.3.29
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v159
  heroku-buildpack-nodejs    v99
  heroku-buildpack-clojure   v76
  heroku-buildpack-python    v99
  heroku-buildpack-java      v51
  heroku-buildpack-gradle    v21
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v76
  heroku-buildpack-play      v26
  heroku-buildpack-php       v121
  heroku-buildpack-go        v64
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.9.4
-----> dokku plugins:
 !     Deprecated: Please use plugin:list
plugn: 0.3.0
  00_dokku-standard    0.9.4 enabled    dokku core standard plugin
  20_events            0.9.4 enabled    dokku core events logging plugin
  apps                 0.9.4 enabled    dokku core apps plugin
  build-env            0.9.4 enabled    dokku core build-env plugin
  certs                0.9.4 enabled    dokku core certificate management plugin
  checks               0.9.4 enabled    dokku core checks plugin
  common               0.9.4 enabled    dokku core common plugin
  config               0.9.4 enabled    dokku core config plugin
  docker-options       0.9.4 enabled    dokku core docker-options plugin
  domains              0.9.4 enabled    dokku core domains plugin
  enter                0.9.4 enabled    dokku core enter plugin
  git                  0.9.4 enabled    dokku core git plugin
  logs                 0.9.4 enabled    dokku core logs plugin
  named-containers     0.9.4 enabled    dokku core named containers plugin
  nginx-vhosts         0.9.4 enabled    dokku core nginx-vhosts plugin
  plugin               0.9.4 enabled    dokku core plugin plugin
  proxy                0.9.4 enabled    dokku core proxy plugin
  ps                   0.9.4 enabled    dokku core ps plugin
  repo                 0.9.4 enabled    dokku core repo plugin
  shell                0.9.4 enabled    dokku core shell plugin
  ssh-keys             0.9.4 enabled    dokku core ssh-keys plugin
  storage              0.9.4 enabled    dokku core storage plugin
  tags                 0.9.4 enabled    dokku core tags plugin
  tar                  0.9.4 enabled    dokku core tar plugin

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
local server on a client's infrastructure

**Comment by josegonzalez** [comment]
Two things:

- As mentioned in the issue template, we don't work on buildpack issues in this repository. Slack/IRC is the best place to find support for that.
- You're on an ancient version of both Dokku and Herokuish. This was fixed in a newer version of Herokuish. Please upgrade your installation :)

If you still need help, please feel free to join us on slack/irc. Links are available in our documentation.
