### ISSUE TITLE
Mounting storage with User created in Dockerfile

### ISSUE THREAD

**Issue by chgad** [dokku/dokku#3573]
Hi,
## Description of problem
 i have a problem with mounting storages under Dockerfile Deployment.
We changed to Dockerfile deployment a while ago and encountered now that our Django application is not able to write to the mounted storage. The storage is still owned by the herokuish user and group "32767:32767". 

In our Dockerfile we create a specific user to run our application as non-root :
Dockerfile

    FROM python:alpine3.7
    ENV PYTHONBUFFERED=1

    # Add new user to run the whole thing as non-root
    RUN addgroup -S app \
        && adduser -G app -h /app -D app

    # Install build dependencies
    RUN apk update \
        && apk add bash \
        && apk add \
        && apk add --no-cache \
           gcc \
           musl-dev \
           zlib-dev \
           jpeg-dev \
           libxslt-dev \
           libxml2-dev \
           postgresql \
           postgresql-dev \
           jpeg \
           gettext \
           tzdata

    # Set the correct timezone
    RUN cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
        && echo "Europe/Berlin" > /etc/timezone

    # Copy Pipfile and install python dependencies
    COPY --chown=app:app Pipfile Pipfile.lock /
    RUN pip install pipenv
    RUN LIBRARY_PATH=/lib:/usr/lib /bin/sh -c "pipenv install --system --deploy"

    # Copy dokku specific files to the project root
    COPY --chown=app:app docker/dokku/* /app/
    COPY --chown=app:app docker/dokku/entrypoint.sh /
    RUN chmod +x entrypoint.sh /app/deploy.sh

    USER app
    WORKDIR /app

    # Copy all related app files
    COPY --chown=app:app . /app
    RUN chown -R app:app /app/geomat/media
    ENTRYPOINT ["/entrypoint.sh"]

As written [here](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/)
we need to set the ownership of the storage/stored files to this newly created User, correct ?

But i have no idea how to do that, as the User only exists within the Dokku app.

Is there something I'm overlooking?

Any advice would be really neat.

**Comment by josegonzalez** [comment]
Files need to be owned by whatever the user is within the container. You can either set that uid/gid directly when creating that user in the docker container or figure out what that maps to and use it on the host. In this case, you are doing neither (the former is probably what you want to do with the addgroup/adduser calls).
