### ISSUE TITLE
Dokku do not kill old container, stay linked to it

### ISSUE THREAD

**Issue by Loschcode** [dokku/dokku#3582]
As said from #2979 there is still this issue going on.

I deployed 2 apps at the same time (api / app from the same project) and my Sidekiq / Redis wouldn't take the new codebase into consideration. I figured that might be a problem of residual container or something like that.

I had to remove my containers manually and rebuild all the apps of my droplet to fix the problem; no server restart or stop from Dokku would fix it. That sounds pretty critical to me. I'm on Dokku 0.17.5.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

As well, do you have a sample app I might be able to deploy to replicate the issue?

**Comment by josegonzalez** [comment]
Friendly _bump_.

**Comment by josegonzalez** [comment]
Closing as there hasn't been a response in a while. Feel free to comment with the requested information and we'll re-open as appropriate.
