### ISSUE TITLE
tty checking fails if system language is not english

### ISSUE THREAD

**Issue by schmaxit** [dokku/dokku#3588]
I am using cron to schedule a dokku run command and the system language is italian.

This is the tracing output of has_tty function execution
```
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ /usr/bin/tty
++ true
+ [[ non è un tty == \n\o\t\ \a\ \t\t\y ]]
+ return 0
+ DOCKER_ARGS+=' -i -t'
```

I have resolved setting LC_ALL to en_US in crontab. Maybe this could be mentioned in the docs

**Comment by josegonzalez** [comment]
If you set `LC_ALL` to `en_US` when you execute dokku, does that work?

**Comment by schmaxit** [comment]
Setting `LC_ALL=en_US` in the crontab just like usually is done with `MAILTO` env var fixed the `dokku run [...]` execution

**Comment by josegonzalez** [comment]
I guess the fix here is to add `LC_ALL=en_US` when executing `/usr/bin/tty`?

@michaelshobbs is this something you could take a look at?

**Comment by michaelshobbs** [comment]
@josegonzalez no sir. i'm back on my $ay job today. trying to split time between that and the docker PR

**Comment by michaelshobbs** [comment]
i'm also not sure the right solution is to hard code `LC_ALL` to `en_US` in all cases

**Comment by josegonzalez** [comment]
Hmmm maybe we can switch to the [`-t` check](https://stackoverflow.com/a/911213/1515875).

**Comment by renemeye** [comment]
One usually would overwrite the language with `LC_ALL=C` for that specific command, where you need "Computer" readable output.
As in: https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do

**Comment by josegonzalez** [comment]
@renemeye I like this answer :)

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
