### ISSUE TITLE
Dokku does not explain why it does not deploy alternative branches

### ISSUE THREAD

**Issue by FunkyloverOne** [dokku/dokku#3592]
So I have foolishly followed instructions from [here](http://dokku.viewdocs.io/dokku~v0.17.8/deployment/methods/git/#changing-the-deploy-branch). 

And then I tried to also set up MinIO on that server (using this [repo](https://github.com/slypix/minio-dokku)), and you know, it just wasn't deploying. :slightly_smiling_face: 

It took me hours to realize that `master` now is not the right branch...

So yeah, it was my dumb mistake, but I think that Dokku might be a bit friendlier here, and point me on it.

**Comment by josegonzalez** [comment]
We actually already do this [here](https://github.com/dokku/dokku/blob/master/plugins/git/functions#L150)...

**Comment by josegonzalez** [comment]
Heh oops, we had a `receive-branch` trigger in the `20_events` plugin. Fix incoming!

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
