### ISSUE TITLE
How do you cleanly undeploy an app?

### ISSUE THREAD

**Issue by fcarriedo** [dokku/dokku#36]
What would be best way to cleanly and completely remove a deployed app (image)?

Would it be?:

```
$ docker rm <container>
$ docker rmi <image>
$ rm -rf ~/dokku/<app>
```

Thanks!

**Comment by lastmj** [comment]
I believe that

    dokku cleanup

Is now the command. See this issue #793

**Comment by michaelshobbs** [comment]
This is documented. Why are we commenting on 2+ year old closed issues?

**Comment by lastmj** [comment]
I didn't see it listed in the output of the dokku help command; I had a hard time finding out that this command exists. Where is it documented?

**Comment by michaelshobbs** [comment]
`dokku apps:destroy <app>` is the preferred method. You can either run `man dokku` or `dokku --help` to see the following

```
    apps:destroy <app>                                                 Permanently destroy an app
```
