### ISSUE TITLE
two similar web processes in one container

### ISSUE THREAD

**Issue by roman-vabishchevych** [dokku/dokku#3601]
Hi!
How I can start two processes in one container?
My Procfile:
```
web: node index.js
api: node api.js
```

Locally works fine with node-foreman.
web – works at 5000
api – works at 3000

I use `proxy:ports-add http:3000:3000`, but nothing works in browser.

Two docker-containers was created.

Can you see plz?
https://github.com/SE7ENSKY/heroku-express-template/tree/proc

**Comment by josegonzalez** [comment]
Every entry in a procfile is isolated from each other, and we will not support running multiple processes within a single container. If you'd like that functionality, perhaps you should look into using a Dockerfile for app deployment.

We also do not currently support proxying multiple process types. This may come in the future, but is not currently a development priority.
