### ISSUE TITLE
config:set and config:unset do not verify correct number of args

### ISSUE THREAD

**Issue by alexymik** [dokku/dokku#3606]
## Description of problem

It is possible to run `dokku config:set` and `config:unset` without specifying any environment variables, which could result in a needless container reboot.

### How to reproduce

Run `dokku config:set app` or `dokku config:unset app` without specifying a key/value or key, respectively.

#### Actual Results

The application will be restarted without any changes to environment variables.

#### Expected Results

The command should be rejected due to insufficient args.

### Additional information

From documentation:

```
config:set [--encoded] [--no-restart] (<app>|--global) KEY1=VALUE1 [KEY2=VALUE2 ...]  Set one or more config vars
config:unset [--no-restart] (<app>|--global) KEY1 [KEY2 ...]                          Unset one or more config vars
```

**Comment by josegonzalez** [comment]
@alexquick Is this something you have time to work on?

**Comment by alexquick** [comment]
Sure thing, I'll take care of it in the next few days.
