### ISSUE TITLE
Write the docker container name as an /etc/hosts entry resolving to 127.0.0.1 to each app/service

### ISSUE THREAD

**Issue by cooperaj** [dokku/dokku#3617]
## Description of problem
The service/app name of the container is not written in a way that it can access, it is unable to resolve it's own name. This causes issues when a container must be able to address itself using the same configuration value that other "linked" containers will do. 

For example a website may be linked with a service and can address that service using something like "dokku-mongo-appdb" but the dokku-mongo-appdb container will not be able to resolve that host, in this case to itself.

This has affected me specifically when using mongo replicasets and an application that needs them (RocketChat)

Alternatively allow access to services 'docker-options' so I can use `--add-host` to do this.

### How reproducible
No service container is able to resolve it's own dokku service hostname. This may be a niche requirement but it's a blocker if it is required.

### Steps to Reproduce

1. Configure Mongo replicasets using (see https://github.com/dokku/dokku-mongo/issues/88)
2. Add the service name as a host to the replicaset. This is used in two places. Mongo must use it to talk to the instance and the application that uses Mongo must use it to talk to the primary instance.
3. Mongo is unable to resolve the dokku hostname and so fails

#### Actual Results
Either the app fails to start as Mongo gives it a replica to talk to that it can't route to. Or Mongo fails to start since it can't route to itself.

I was able to get a temporary fix in place by manually editing /etc/hosts in the Mongo service container to route it's dokku hostname to 127.0.1.1

#### Expected Results
A working application using a Mongo replicaset.

**Comment by josegonzalez** [comment]
Given that this is a MongoDB service - and not an app - I'm going to close this as it doesn't impact running apps.
