### ISSUE TITLE
How to access the persistent storage directory on nodeJS

### ISSUE THREAD

**Issue by NikodemBieniek** [dokku/dokku#3621]
## Description of problem
I'm creating an image uploader and it works fine locally because the folder '/public/uploads' doesn't get cleared. So I'm trying to use the persistent storage so the images don't get deleted upon restart. 

### Steps to Reproduce

1.I've mounted images - `dokku storage:mount images /var/lib/dokku/data/storage/images/:/app/storage`
2. In my configuration file I've set the path to equal './app/storage/public/uploads' for production environment. `if(process.env.NODE_ENV === 'production'){
  module.exports = {
//Dooku
    public_folder: "./app/storage/public/",
  }
}else {
//Local
  module.exports = {
    public_folder: "./public/",
  }
}`

#### Actual Results
The prominent error in the logs is '

> no such file or directory, scandir './app/storage/public/'' 
What am i doing wrong?
#### Expected Results
It shouldn't crash because the directory exists - https://i.imgur.com/jl8EawV.png
## Environment Information
https://pastebin.com/AFjBNLSN

**Thanks in advance**

**Comment by josegonzalez** [comment]
By prefixing the directory path with a dot - `.` - character, you are forcing it to use a path relative to what is likely the script name, and not the root path. If you remove that `.` in front of the `/app/storage/public/` path, it should work fine.
