### ISSUE TITLE
absolute import fail during build process in digital ocean dokku deployment. NODE_PATH=src

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [dokku/dokku#3622]
### Describe the bug
Thanks for the great work! I'm deploying the app to dokku with .env looking like this 

.env
NODE_PATH=src
NPM_CONFIG_PRODUCTION=false

.buildpacks
https://github.com/mars/create-react-app-buildpack.git

package.json
  "scripts": {
    "dokku": {
      "predeploy": "",
      "postdeploy": ""
    },
    "start": "react-scripts start",

error response
```js
-----> Build
       Running build

       > fusion-software@0.1.0 build /tmp/build
       > react-scripts build

       Creating an optimized production build...
       Failed to compile.

       ./src/components/Clients/WhatWeOffer.js
       Cannot find module: 'assets/img/Enterprise.svg'. Make sure this package is installed.

       You can install this package by running: npm install assets/img/Enterprise.svg.
```

### Did you try recovering your dependencies?
yeah

### Which terms did you search for in User Guide?
absolute import deploy build fail 

### Environment

it's on digital ocean dokku

### Steps to reproduce

explained above

### Expected behavior

absolute import works normally

### Actual behavior

explained above

### Reproducible demo
explained above

**Comment by SeunghunSunmoonLee** [comment]
when I run npm run build on mac, it build without issues, but it only happens when I deploy to dokku

**Comment by josegonzalez** [comment]
Hi! This seems like its a buildpack issue, not one related to dokku. For those sorts of issues, debugging via GitHub issues is difficult, so please join us via [slack or irc](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels).
