### ISSUE TITLE
SPONSORS.md does not exist/README.md links to non-existent file

### ISSUE THREAD

**Issue by fronbasal** [dokku/dokku#3624]
### Description of problem

The README.md links to SPONSORS.md in line 16, yet that file does not exist.

### How reproducible

README.md in commit 4848473, line 16.

#### Actual Results

404 SPONSORS.md

#### Expected Results

An existent SPONSORS.md file :)

**Comment by josegonzalez** [comment]
Removed In https://github.com/dokku/dokku/pull/3510
