### ISSUE TITLE
Aliasing or copying env vars at runtime

### ISSUE THREAD

**Issue by LeviSchuck** [dokku/dokku#3632]
This is a question

## Description of problem

I have a dokku plugin that provides `DATABASE_URL` at runtime to a linked application, this is not available at build time or by configuration.

However the application, which comes prepackaged in a docker container, wants `DATABASE_HOSTS`. The value can be copied verbatim between these two.

How should I go about aliasing an env var?

Brainstorming:
* Create a new entrypoint / cmd command and script that exports those env vars in the expected way
* I've seen string interpolation in dotenv files for ruby, but documentation around this seems pretty thin
* Maybe there's additional plugin functionality that can do this that I don't know about?

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?: 
physical, wget + bootstrap.sh

### Additional information
In this case, I'm trying to get dokku-elasticsearch to work with a kibana docker image.
But the same problem applies to providing things like `PORT` -> `GF_SERVER_HTTP_PORT` for other apps like grafana.

**Comment by josegonzalez** [comment]
This is unfortunately not possible, nor do I think it is worth trying to solve - how would you handle order of operations or variable interpolation? Can you do simple templating or logic? I don't know of any PaaS that supports this sort of thing, as it get tricky to do correctly.

The way I've done it before is for the app itself to modify the env. This would be how you'd do it in whatever bootstraps your code for a ruby app:

```ruby
ENV['PORT'] = ENV['GF_SERVER_HTTP_PORT'] if !ENV.fetch('GF_SERVER_HTTP_PORT', nil).nil?
```

For Dockerfile-based deploys, you could add a replacement entrypoint that triggers the original entrypoint, and alias the environment variables there.

Hope those options help.

**Comment by LeviSchuck** [comment]
Thank you
