### ISSUE TITLE
Adapt default NGINX to allow dokku to run behind a load balancer

### ISSUE THREAD

**Issue by dsander** [dokku/dokku#3633]
### High Level Plan

- Modify the generated [`/etc/nginx/conf.d/dokku.conf`](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/install#L40) to include the `map` as shown below
- Modify the [`validate.conf.sigil`](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/validate.conf.sigil) to include the `map` as shown below.
- Modify both the http and https stanzas of the [`nginx.conf.sigil`](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L26) to include the `proxy_set_header` call.

### Original Post

Hi 👋 !

I am running dokku behind a SSL terminating caddy proxy. Like you [dokumented](http://dokku.viewdocs.io/dokku/configuration/ssl/#running-behind-a-load-balancer) this requires a custom NGINX configuration at the moment.

Using the nginx [map module](http://nginx.org/en/docs/http/ngx_http_map_module.html) I believe it is possible (at least it's working for my rails applications) to have a configuration that supports both uses cases:

```
map $http_x_forwarded_proto $forwarded_proto {
  default $scheme;
  ~. $http_x_forwarded_proto;
}
....
    proxy_set_header X-Forwarded-Proto $forwarded_proto;
....
```

If you are open for a change like this, I will open a pull request.

Thanks for the great work on dokku!

**Comment by josegonzalez** [comment]
Sounds like a good pr!

**Comment by josegonzalez** [comment]
Actually looks like the map module isn't included by default.

**Comment by josegonzalez** [comment]
Reopening as that may only be the case on ubuntu 14.04....

**Comment by josegonzalez** [comment]
@dsander friendly _bump_

**Comment by josegonzalez** [comment]
Actually I'm thinking about this a bit more. If this is enabled, then all the client can spoof whether a request comes in as https, possibly enabling MITM attacks.

As the goal of Dokku is to provide a great, single-server solution for hosting applications, I think adding this functionality makes the default less secure and potentially opens up users to attacks. Therefore, while this is otherwise a neat trick, I'm disinclined to merge it.

Aside, should we ever get multi-server in Dokku _core_, then this feature makes sense, though at that point the proxy implementation is unlikely to be exactly the same as what we have now (switching to something like traefik or embracing the ingress solution for the scheduler would be better).

**Comment by josegonzalez** [comment]
Oh also the solution above does not handle `X-Forwarded-For` and `X-Forwarded-Port` (though both are relatively easy to add.

**Comment by dsander** [comment]
> If this is enabled, then all the client can spoof whether a request comes in as https, possibly enabling MITM attacks.

Can you explain how that would enable MITM attacks? If I am already "in  the middle" as an attacker I can switch the request to non-ssl, but does that gain me anything? I am mostly concerned about my own setup 😄 

I would have added the same logic for `X-Forwarded-Port` but not `X-Forwarded-For` for the latter I believe one want's to have all proxy IPs in that header and not drop remove the dokku NGINX from it.

**Comment by josegonzalez** [comment]
This works fine for your case, but not the general case that our users have where there _isn't_ a load balancer proxying to your app.

**Comment by dsander** [comment]
I did some digging trying to figure our where the error I was getting in my Rails application comes from and why the change might cause a security issue. My double proxy setup tripped the [CSRF protection](https://github.com/rails/rails/blob/v6.0.0/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L441-L449) because the request url was containing `http` (the request is coming from the SSL terminating proxy), but the `Origin` header contained `https` (because the browser made the request via SSL). Setting the `X-Forwarded-Scheme` header makes rack [change the request url](https://github.com/rack/rack/blob/bbd2a93f422508c615ae23d007c34b8bfb405b91/lib/rack/request.rb#L209). [This firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=446344) explains the idea behin using the `Origin` header as (aditional) CSRF protection.

The suggested change would - in theory - allow to bypass that check, but I don't know if that can really be done in practise, setting HTTP headers from request made by a browser is only possible for XHR request. So if a server is configured to accept CORS and does not have additional CSRF protection (like requiring a token) it might become an issue. But since applications can't trust the `Origin` header (Firefox does not yet use it), I don't  think it would cause issues right now.

I understand that you are not willing to take the risk of future applications becoming vulnerable due to this change.
