### ISSUE TITLE
Update base nginx.conf across all apps?

### ISSUE THREAD

**Issue by nkrumm** [dokku/dokku#3634]
## Description of problem
I'd like to modify some directives in dokku's default nginx.conf so that *all* deployed apps are affected.  Is this possible? I know I can add nginx.conf.sigil files to each app, but I'd like this to work transparently.

More detail on what I'm trying to accomplish: We're using dokku to host user-developed apps behind an AWS ALB load balancer. The load balancer implements our authentication, and then passes a JWT token in the HTTP header to the app.  For compliance reasons, we need to log this header (at a minimum) so that we know which auth'd user is associated with the request. Our goal is make this fully transparent .

## Possible solutions?

 - I could update the template for nginx.conf.sigil dokku code and use a forked branch: https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil
 - Write a plugin-- but then the problem becomes having the plugin be installed for all applications on deploy

Currently on dokku 0.14.5 but could upgrade if that makes a difference. 

Thank you for your help. We love dokku and it has served us very well in a HIPAA environment to date.

**Comment by josegonzalez** [comment]
Depending on what you need to inject, you could:

- Use a custom plugin with a `post-extract` hook to inject the custom `nginx.conf.sigil` into the app. This would happen on every deploy, and you would want to update your template whenever the upstream one gets updated (rare).
- Use a custom plugin with a `nginx-pre-reload` hook to add a custom `hipaa.conf` in the `/home/dokku/$APP/nginx.conf.d/` directory. This would be a bit more minimal, but not as useful if you need invasive changes to your nginx.conf.

A custom plugin is definitely the way to go here, as you have the most flexibility in injecting whatever you need into your apps. There isn't any other way to do this globally - we removed global `nginx.conf.sigil` as globals are usually tougher to reason about in the Dokku codebase - outside of a plugin.

Closing as I hope I answered your question, but feel free to comment with any other questions/concerns. Also, upgrade Dokku!

> Aside, donations to the patreon or opencollective are welcome!

**Comment by josegonzalez** [comment]
Also, feel free to join on slack/irc with questions (they are linked) or to discuss this further.
