### ISSUE TITLE
Resource limit unit

### ISSUE THREAD

**Issue by vincelwt** [dokku/dokku#3649]
Hi!

I'm trying the new `dokku resource:limit` to limit CPU usage of an app but the docs   doesn't say about the unit of the value. 

Specifically, if I set a limit of `100` and my machine has 8 cores, is it 100% of the 8 cores or is it like `top` where 100% = 1 core (and thus can go as high as 800%) ? 

The Docker CFS scheduler uses decimal values where `1` = 1 core (1.5 = 1 core and half, etc..) so it doesn't seem to be the same unit of Dokku.

Thanks

**Comment by josegonzalez** [comment]
From the docs:

> The meaning of a values and it's units are specific to the scheduler in use for a given app. If a scheduler does not support a given resource type combination, it will be ignored. All resource commands require an app rebuild or deploy in order to take effect.

If the scheduler you are using requires units, then you should use units. The docker-local scheduler has a [section on how these work](http://dokku.viewdocs.io/dokku/advanced-usage/schedulers/docker-local/#supported-resource-management-properties) in the docs.

**Comment by vincelwt** [comment]
Thanks but I still don't understand based on the docs :/
So the `dokku resource:limit` by default uses the docker-local scheduler ?

The docker-local doc you referenced says:
`cpu: (docker option: --cpus), and is specified in number of CPUs a process can access.`
So I guess correct values would be `1`, `1.5`, `2`, ...

But the `resource:limit` main example [in the docs](http://dokku.viewdocs.io/dokku/advanced-usage/resource-management/#resource-management) is `dokku resource:limit --cpu 100` 
It can't be the number of cores as in the docker-local scheduler right?

It would just be great to have an extra sentence in the "Resource Management" docs for people like me to explain what the `100` value in the docs means (100% of all CPUs or 1 core at 100%)

**Comment by josegonzalez** [comment]
As I said, the default value of resource limits don't have any semantic sense internally to Dokku. They only make sense when combined with a scheduler - there is actually also a [kubernetes](https://github.com/dokku/dokku-scheduler-kubernetes) and [nomad](https://github.com/dokku/dokku-scheduler-nomad) scheduler.

Each scheduler takes its values differently. Some allow values without any unit, in which case the unit is implicit (Kubernetes does this for some values). The example in the resource docs just sets the value to 100, but that might not mean anything for your particular scheduler of choice.

For the docker-local scheduler, the `cpu` resource limit maps to the `--cpus` docker run flag. From the [docker docs](https://docs.docker.com/config/containers/resource_constraints/#cpu) on the `--cpus` flag:

> Specify how much of the available CPU resources a container can use. For instance, if the host machine has two CPUs and you set --cpus="1.5", the container is guaranteed at most one and a half of the CPUs. This is the equivalent of setting --cpu-period="100000" and --cpu-quota="150000". Available in Docker 1.13 and higher.

So this means that setting `resource:limit` for cpu to `100` when using the `docker-local` scheduler means your app can access at most 100 CPUs. If you have fewer than 100 CPUs on your server, then your app will be able to access all of them.

On Kubernetes, you can [specify units on the cpu count](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu). So `100` and `100m` CPU have different real values in the `Kubernetes` case, as do `1` and `1m` CPU.

If you have a better, succinct way of explaining this, feel free to file a docs pull request.

**Comment by josegonzalez** [comment]
@vincelwt feel free to reach out on slack if this is still confusing so we can work out how to clarify the docs.

**Comment by vincelwt** [comment]
Thanks for taking the time to explain this, it does make sense now. 
I think how you put it is perfect, I'll submit a PR based on that to clarify the docs. 
Have a great day.

**Comment by ltalirz** [comment]
@vincelwt Was this PR ever made? If not, would you mind opening it?

I tend to agree that using 100 as the "random example number" is probably not the best choice if it translates into 100 CPUs for the local scheduler (since the intuitive association is with 100%). 2 might be a better choice.
