### ISSUE TITLE
Are nginx ssl_ciphers are too restrictive or what?

### ISSUE THREAD

**Issue by leshik** [dokku/dokku#3661]
Not sure where to report it. Today all of a sudden my deploy became broken after I renewed my Let's Encrypt certificate. I have many subdomains thus I don't use `dokku-letsencrypt` plugin, but instead I request wildcard certificates with [lego](https://github.com/go-acme/lego) and then upload them with `dokku certs:update`:

```
lego --path /usr/local/etc/lego --dns cloudflare --domains "*.site1.org" --email my@email.org renew --days 60
cd /usr/local/etc/lego/certificates/
tar cf - _.site1.org.crt _.site1.org.key | dokku certs:update myapp
```

All was working fine until today I decided to add one more non-wildcard domain in addition to what I had.

Before it was like:

```
CN=*.site1.org
...
X509v3 Subject Alternative Name:
  DNS:*.site1.org
```

And after it became:

```
CN=*.site1.org
...
X509v3 Subject Alternative Name:
  DNS:*.site1.org, DNS:site2.com
```

(I also upgraded `lego` from `1.0.1` to `3.0.2` but I don't think it matters.)

The site then immediately stopped working with `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`.

After a bit of investigation and visiting https://mozilla.github.io/server-side-tls/ssl-config-generator/ I narrowed down the problem to `ssl_ciphers` option.

This works:

```
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
```

This doesn't:

```
ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
```

However, it works with previous certificates.

**Comment by josegonzalez** [comment]
We use the ciphers we use because ssllabs.com otherwise reports us as weak. I would rather installations with SSL are as secure as possible than not. Users can override ciphers in their own `nginx.conf.sigil` if desired.

Can you tell me the exact differences between those two cipher lists?

**Comment by leshik** [comment]
They are totally different. The one that works is from https://ssl-config.mozilla.org/ (intermediate config.) Also `ssl_ciphers` now in `dokku.conf` don't have `ECDSA` at all. I wonder how `RSA` could be more secure than `ECDSA`?

**Comment by josegonzalez** [comment]
Don't know, this was the recommended cipher list from Mozilla the last time I updated them (in Dec 2018). If you can run your setup and get an A/A+ from SSL Labs, then I'll consider switching.

Note: this is all fairly difficult to get correct and changes all the time, so I'm not surprised it's changed in the past year (the Modern one even dropped the cipher list completely...).

**Comment by leshik** [comment]
I get `A` with my ciphers (which are from Mozilla):
![image](https://user-images.githubusercontent.com/443678/63568982-a62ec400-c5a1-11e9-82c4-337d483aed78.png)
You can try yourself if you wish.

**Comment by josegonzalez** [comment]
Seems legit. How do those ciphers fair with a "normal" letsencrypt cert?

I can't change ciphers in a patch release, but if you want to make a PR and the cipher list works with a normal cert, I'm happy to merge/release with the next minor.

**Comment by leshik** [comment]
Normal Let's Encrypt certs work fine too.
