### ISSUE TITLE
dokku is creating me subdomains even when I set "no use virtual host" in my setup

### ISSUE THREAD

**Issue by cocodrino** [dokku/dokku#3663]
Hi guys, I'm a bit newbie with dokku (looks great so far) my only problem right now is that when I did the install I disable "use virtualhost naming for apps" because I want access to my apps through the port...I'm following this tutorial and that is the only difference with the cited text

https://www.linode.com/docs/applications/containers/deploy-a-flask-application-with-dokku/

so far so good, after push my branch I didn't see any information about the used port,instead this show me some info about a subdomain

```
=====> Application deployed:
       http://flask-example.dokku-s-....-4gb-nyc3-01
```

if I try to access to that subdomain fails, if I try access to my ip:port also fails....

but if I use the port 80 this works ok, if I run

```
dokku proxy:ports flask-example
```

I get this

```
-----> scheme             host port                 container port                                     
http                      80                        5000   
```

then I was thinking, ok maybe it just use the port 80 for the first app, and after create new apps it starts using random ports, I create a new app and again I get

```
-----> scheme             host port                 container port                                     
http                      80                        5000   
```

is it ok?..how can I disable the virtualhost and enabl access through port?..is it possible after configure dokku for the first time?...thank you so much

**Comment by josegonzalez** [comment]
It seems like you didnt disable virtualhost usage in the setup, as its reporting that you have it enabled. You can disable it using `dokku domains:clear-global` and then running `dokku domains:disable APP` for each app. 

See our documentation on [domains management](http://dokku.viewdocs.io/dokku/configuration/domains/) and [port management](http://dokku.viewdocs.io/dokku/networking/port-management/) for more details.
