### ISSUE TITLE
Dokku with external network cannot determine container IP address

### ISSUE THREAD

**Issue by myros** [dokku/dokku#3665]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

## Description of problem

As of 0.14 (probably), using DOCKER_OPTIONS_DEPLOY with --network creates wrong nginx.conf.

### Steps to Reproduce

1. create Docker network
2. deploy ruby-getting-started app and make sure everything is ok
3. add network to DOCKER_OPTIONS_DEPLOY
--restart=on-failure:10
--network=nginx-proxy
4. dokku ps:restart  ruby-getting-started

the same thing happenes on deploy, not only on restart

#### Actual Results

getting this results after restart 

upstream ruby-getting-started-5000 {

  server <no:5000;

  server value>:5000;
}

#### Expected Results

nging.conf should contain server with proper IP

upstream ruby-getting-started-5000 {

  server 172.17.0.14:5000;
}

### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> You may also run `dokku report` without any arguments to display the top-level reporting information.

### Additional information

- Container Inspect Output (if applicable) via `dokku ps:inspect APP_NAME`
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
The issue here is actually explained a bit more [here](https://github.com/dokku/dokku/issues/2085#issuecomment-359285731). Unfortunately, this will require significant changes to Dokku, so it isn't straightforward to do. Closing as we already have an issue to track this work.
