### ISSUE TITLE
Docs are down!

### ISSUE THREAD

**Issue by ericmjl** [dokku/dokku#3666]
Hi guys, leaving a quick message here indicating that the docs appear to be down as of 31 August 2019. 12:15 PM (EST). 

![image](https://user-images.githubusercontent.com/2631566/64066533-0bf5fe00-cbe9-11e9-82d1-795bddb47f0e.png)

Please feel free to close when relevant.

**Comment by josegonzalez** [comment]
Thanks. I'm currently in between apartments so this will need to wait a bit before I can get to a computer to restart the viewdocs app.

**Comment by josegonzalez** [comment]
Heroku restarted it so the docs are back up.
