### ISSUE TITLE
Allow users to override /etc/nginx/conf.d/dokku.conf

### ISSUE THREAD

**Issue by haggen** [dokku/dokku#3674]
### High Level Plan

- Make `dokku.conf` a regular file in the built package (also handle from-source installs) that can be ignored during upgrades (apt has support for this built-in). If users wish to ignore changes to config files we ship, they can do so at their own risk.

### Original Post

Hi! I'm experimenting with heavily customizing nginx configuration on one of my servers but I noticed today that after an upgrade dokku has overwritten the changes I've made to `/etc/nginx/conf.d/dokku.conf`.

This behavior was verified when I looked into [plugins/nginx-vhosts/install:40](https://github.com/dokku/dokku/blob/2b93c76b1db83cca6682d52cf218222412f8f568/plugins/nginx-vhosts/install#L40). Interestingly enough just a few lines below there's a comment:

> allow users to override their server_names_hash_bucket_size

So I wonder if it there would be any issues if we made the same check before overriding `dokku.conf`. If you see no problems I'd be glad to send a PR.

Thanks!

**Comment by josegonzalez** [comment]
Note: `ssl_ciphers` can be modified on a per-app basis, as it can be specified both in the `http` and `server` context.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by gurpreetatwal** [comment]
For anyone else who runs into this issue and doesn't have experience with Dokku plugin development (like myself), all you need to do is:

1. Create an empty git repository
2. Commit the following 3 files to the repository
    `plugin.toml`: Manifest file required for all Dokku plugins, see [Plugin creation](http://dokku.viewdocs.io/dokku/development/plugin-creation/#always-create-a-plugintoml) for more information.
    ```toml
    [plugin]
    description = "<description>"
    version = "0.0.1"
    [plugin.config]
    ```
    `nginx-dokku-template-source`: The "trigger" responsible for returning the path to the config template, see [Plugin triggers](http://dokku.viewdocs.io/dokku/development/plugin-triggers/) for more information.
    ```bash
    #!/usr/bin/env bash
    set -eo pipefail
    [[ $DOKKU_TRACE ]] && set -x
    
    echo "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/dokku.conf.sigil"
    ```
    `dokku.conf.sigil`: The nginx config template itself, see [`nginx-dokku-template-source`](http://dokku.viewdocs.io/dokku/development/plugin-triggers/#nginx-dokku-template-source) for more information.
    ```conf
    # whatever you want
    include {{ $.DOKKU_ROOT }}/*/nginx.conf;
    ```
3. Install your custom plugin: 
```bash
sudo dokku plugin:install https://githost.com/path/to/repo
```
4. Enjoy! :tada:
