### ISSUE TITLE
Using OpenResty Ubuntu pre-built packages out-of-the-box does not work

### ISSUE THREAD

**Issue by arimus** [dokku/dokku#3675]
## Description of problem

Dokku expects the nginx binaries and configuration to be in the default nginx locations. This means that it breaks even after installing the openresty packages from https://openresty.org/en/linux-packages.html, where the nginx binaries and config are under /usr/local/openresty/nginx/.

Also, if you happened to leave nginx installed and just disabled it (per instructions for OpenResty), Dokku will then run into additional problems as it wants nginx up and running and is using the old nginx binary to config test.

### Steps to Reproduce

1. Install Dokku and get it working on Ubuntu (Bionic)
2. Follow OpenResty installation instructions: https://openresty.org/en/linux-packages.html
3. Push an app or otherwise trigger a change, which will cause an error

#### Actual Results

In my case:

```
...
-----> Running post-deploy
-----> Overriding default nginx.conf with detected nginx.conf.sigil
remote: Could not find nginx binary in $PATH or at '/usr/sbin/nginx'.
```

#### Expected Results

A clean config test and deployment.

### `dokku report APP_NAME` output

-----> uname: Linux dokku-g-2vcpu-8gb-sfo2-01 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           7976         341        4580           1        3055        7340
       Swap:             0           0           0
-----> docker version:
       Client:
        Version:           18.09.6
        API version:       1.39
        Go version:        go1.10.8
        Git commit:        481bc77
        Built:             Sat May  4 02:35:57 2019
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          18.09.6
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.8
         Git commit:       481bc77
         Built:            Sat May  4 01:59:36 2019
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info:
       Containers: 9
        Running: 8
        Paused: 0
        Stopped: 1
       Images: 37
       Server Version: 18.09.6
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
       runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-52-generic
       Operating System: Ubuntu 18.04.2 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 2
       Total Memory: 7.79GiB
       Name: dokku-g-2vcpu-8gb-sfo2-01
       ID: J6Y6:NATE:MSG7:W34K:TWL2:DTDE:ZSHF:CROX:M4EG:SSQH:KEQU:Z5E4
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine

-----> sigil version: 0.4.0
-----> herokuish version:
       herokuish: 0.5.0
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v200
         heroku-buildpack-nodejs    v142
         heroku-buildpack-clojure   v83
         heroku-buildpack-python    v149
         heroku-buildpack-java      v63
         heroku-buildpack-gradle    v28
         heroku-buildpack-scala     v84
         heroku-buildpack-play      v26
         heroku-buildpack-php       v151
         heroku-buildpack-go        v104
         buildpack-nginx            v10
-----> dokku version: dokku version 0.18.3
-----> dokku plugins:
       plugn: 0.3.2
         00_dokku-standard    0.18.3 enabled    dokku core standard plugin
         20_events            0.18.3 enabled    dokku core events logging plugin
         app-json             0.18.3 enabled    dokku core app-json plugin
         apps                 0.18.3 enabled    dokku core apps plugin
         builder-dockerfile   0.18.3 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.18.3 enabled    dokku core builder-herokuish plugin
         buildpacks           0.18.3 enabled    dokku core buildpacks plugin
         certs                0.18.3 enabled    dokku core certificate management plugin
         checks               0.18.3 enabled    dokku core checks plugin
         common               0.18.3 enabled    dokku core common plugin
         config               0.18.3 enabled    dokku core config plugin
         docker-options       0.18.3 enabled    dokku core docker-options plugin
         domains              0.18.3 enabled    dokku core domains plugin
         enter                0.18.3 enabled    dokku core enter plugin
         git                  0.18.3 enabled    dokku core git plugin
         letsencrypt          0.8.9 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.18.3 enabled    dokku core logs plugin
         network              0.18.3 enabled    dokku core network plugin
         nginx-vhosts         0.18.3 enabled    dokku core nginx-vhosts plugin
         plugin               0.18.3 enabled    dokku core plugin plugin
         proxy                0.18.3 enabled    dokku core proxy plugin
         ps                   0.18.3 enabled    dokku core ps plugin
         repo                 0.18.3 enabled    dokku core repo plugin
         resource             0.18.3 enabled    dokku core resource plugin
         scheduler-docker-local 0.18.3 enabled    dokku core scheduler-docker-local plugin
         shell                0.18.3 enabled    dokku core shell plugin
         ssh-keys             0.18.3 enabled    dokku core ssh-keys plugin
         storage              0.18.3 enabled    dokku core storage plugin
         tags                 0.18.3 enabled    dokku core tags plugin
         tar                  0.18.3 enabled    dokku core tar plugin
         trace                0.18.3 enabled    dokku core trace plugin
=====> dev app information
       App dir:                       /home/dokku/dev
       Git sha:                       35164d0
       Deploy source:                 git
       Locked:                        true
=====> dev buildpacks information
       Buildpacks list:
CN = dev.appbloks.si=====> dev ssl information
       Ssl dir:                       /home/dokku/dev/tls
       Ssl enabled:                   true
te
error 20 at 0 depth lookup: unable to get local issuer certificate
       Ssl hostnames:                 dev.appbloks.site
       Ssl expires at:                Dec  4 21:36:17 2019 GMT
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Sep  5 21:36:17 2019 GMT
       Ssl subject:                   subject=CN = dev.appbloks.site
       Ssl verified:                  self signed
=====> dev checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> dev docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> dev domains information
       Domains app enabled:           true
       Domains app vhosts:            dev.appbloks.site
       Domains global enabled:        true
       Domains global vhosts:         appbloks.site
=====> dev git information
       Git rev env var:               GIT_REV
       Git deploy branch:             master
       Git global deploy branch:      master
=====> dev network information
       Network bind all interfaces:   false
       Network listeners:             172.17.0.10:5000
=====> dev proxy information
       Proxy enabled:                 true
       Proxy type:                    nginx
       Proxy port map:                http:80:5000 https:443:5000
=====> dev ps information
       Processes:                     1
       Deployed:                      true
       Running:                       true
       Restore:                       true
       Restart policy:                on-failure:10
       Ps can scale:                  true
       Status web.1:                  running    (CID: 3ba2ab25fca2)
=====> dev scheduler-docker-local information
       Scheduler docker local disable chown:
=====> dev storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

DigitalOcean Dokku Droplet using Ubuntu Bionic

**Comment by josegonzalez** [comment]
As part of some work-related feature I want to build, I took a stab at fixing this. Seems to work well in the docker-based setup, but Nginx functionality should remain unchanged, so I'll merge if normal tests pass.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by arimus** [comment]
@josegonzalez 👍 Thank you sir! I ended up using OpenResty inside my container to get around this, since I wanted to use dynamic ENV-based proxy_pass routes (using set_by_lua). This will certainly help when that method isn't desirable though.

**Comment by josegonzalez** [comment]
@arimus I'd love to see you post a bit more about what you're doing/how you're doing it, as that sounds pretty interesting and relevant to the reason I worked on this last night...

**Comment by arimus** [comment]
Essentially, I had the following scenario:

Need http://dev.mydokku.com/api/(.*) requests proxied to http://dev-backend.mydokku.com/$1 to avoid CORS config, auth server issues, exposing the backend to users, etc.

Backend server container - provides API methods (e.g. dev-backend.mydokku.com)
Frontend server container - provides Angular SPA (e.g. dev.mydokku.com)

So, outside of this thread, we've talked about using nginx.conf.sigil to accomplish this same thing in a more straight forward manner, but this may still be useful to others looking to make their nginx config dynamic on container start.

First, you have to ensure that you update your nginx.conf to include the ENV vars you want to expose to your server blocks. Example:
```
...
# expose these env variables inside our docker nginx
env ADMIN_API_PROXY_BASE_URL;
env CONTENT_API_PROXY_BASE_URL;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
...
```

Then you need your server block to include the bits you want to make dynamic based on ENV. Example:
```
server {
    listen 5000;
    port_in_redirect off;

    # set our variables based on the environment variable
    set_by_lua $admin_api_proxy_base_url 'return os.getenv("ADMIN_API_PROXY_BASE_URL")';

    # with some defaults if you desire
    if ($admin_api_proxy_base_url = '') {
      set $admin_api_proxy_base_url 'http://localhost:5000/';
    }

    location / {
        root "/usr/share/nginx/html";
        autoindex
            on;
        index
            index.html
            index.htm;
        try_files $uri $uri/ /index.html;
    }

    # here we're mapping /api/blah -> SOME_BASE_URL/blah
    location ~ ^/api/(.*)$ {
        # note that we create a new var here, as proxy_pass doesn't seem to like evaluating the $1 mashed at the end itself
        set $proxy_path_url $admin_api_proxy_base_url$1;
        proxy_pass $proxy_path_url;

        proxy_http_version 1.1;
        ...
```
