### ISSUE TITLE
Static HTML support without individual containers for every site

### ISSUE THREAD

**Issue by cweagans** [dokku/dokku#3683]
I've been kicking around this idea for a bit and just wanted to validate it with somebody that knows a bit more about Dokku.

It seems strange to me to spin up individual containers for every Hugo site that I have (I host several for myself and others). The containerized build process is really nice/predictable, but given that we're already running an Nginx instance on the host, I keep wondering if maybe we can simplify the `run` phase a bit.

Because the sites are 100% static files, I don't think there's a lot of value of isolating them in a container, and there's a cost to running a separate Nginx process as well. I'm wondering if it would be possible/feasible to have a variant of the static site buildpack that _only_ performs the build step, dumps all the output to disk somewhere on the host, and exits, perhaps coupled with a plugin that expects that behavior and generates Nginx configuration appropriately.

Is this too crazy? Is this bending Dokku too far out of the realm of what it was designed for? Is it even a valuable endeavor?

**Comment by josegonzalez** [comment]
Basically the answer boils down to "there is a cost".

Doing this would be quite different from what we expect from the build process. None of the buildpacks are quite meant to be run this way, and its certainly possible that someone runs the static buildpack with another buildpack, or runs a custom version of the static buildpack. In the former case, we probably don't want to run outside of the container, and in the latter, the user will expect and be confused when we don't.

We could probably make it such that all services are always run outside of the container by extracting the `/app` directory, but then we need to take care that users aren't using the `dokku-apt` plugin to customize packages, and we'd also need to have all the herokuish dependencies installed on the host OS (they've only been tested on Ubuntu 18.04, so we'd be limiting our install-base again).

Ultimately, I don't think this is worth it. You could potentially do it with a custom scheduler plugin, but it'd be a ton of work for maybe little actual value - I'd imagine the overhead of running nginx in a container for a static is fairly small. There are a few moving parts of Dokku - sshcommand, plugn - that could be used to build such a static site service, and thats probably worth being a standalone project.

Cool idea though, and I highly encourage you to work on it if you think it's interesting :)

**Comment by cweagans** [comment]
Thanks for the thoughtful reply! Just to be clear, I was thinking about this more in an "opt-in" kind of way --- this is definitely not something that I'd advocate for including in Dokku itself or anything.

I'm gonna think about this and if I end up with a workable plugin, I'll follow up here. :)
