### ISSUE TITLE
Feature request - Provide a way for dynamic nginx variables to be used in the nginx.conf.sigil

### ISSUE THREAD

**Issue by arimus** [dokku/dokku#3686]
Currently, nginx configuration can't be dynamic based on some runtime configuration (outside of simple pattern-based options and with vars that are already generated by Dokku, like `http://{{ $.APP }}-backend`). It would be nice to have a way to configure a docker app and use that configuration within the nginx.conf.sigil.

Possible example options (either or both would be valuable):

**Option 1 - Creation of an nginx:set command to set variables for use in nginx.conf.sigil**

```
dokku nginx:set myapp API_BASE_URL="http://backend:5000"
```

then in the sigil:

```
proxy_pass  {{ $.NGINX_API_BASE_URL }};
```

**Option 2 - Allow usage of config:set ENV variables in nginx.conf.sigil**

```
dokku config:set myapp API_BASE_URL="http://backend:5000"
```

then in the sigil:

```
proxy_pass  {{ $.ENV_API_BASE_URL }};
```

**General**

- Using a prefix for the vars / tokens to prevent collisions would seem to be a nice precaution (e.g. NGINX_ and ENV_ see above).
- Option 1 keeps this configuration separate and isolated to nginx, which can be a nice compartmentalization in many use cases. This can however lead to duplication of config or can lead to split config that would be nicer to see co-located in some situations.
- Option 2 is useful for harnessing standard config for nginx configuration, however this could feel polluting if this were the only way to make dynamic nginx config tweaks.
- Both of the above have their advantages and disadvantages and are complementary, rather than competing implementations IMO

Thanks @josegonzalez for hashing over these with me.

**Comment by arimus** [comment]
FYI, I just found this in the docs (http://dokku.viewdocs.io/dokku/configuration/nginx/):

> Note: Application config variables are available for use in custom templates. To do so, use the form of {{ var "FOO" }} to access a variable named FOO.

I had no idea that part of this functionality already existed and takes care of the above Option 2. I tested and confirmed that this does currently work!

**Comment by josegonzalez** [comment]
Oh lol guess we had that...

**Comment by arkadybag** [comment]
It was difficult to find this small note in the documentation.
Thanks @arimus
