### ISSUE TITLE
Translate documents into Korean

### ISSUE THREAD

**Issue by gayeon1025** [dokku/dokku#3696]
Hi! recently I love to deploy my apps using Dokku.
However, at first, It was hard to know how to use Dokku because there aren't enough Korean documents. Thus I'm trying to translate document into Korean. 
I hope many Korean know Dokku's usefulness. Can I request pull request for this issue?

**Comment by josegonzalez** [comment]
Hi @gayeon1025 ! This seems like a great idea - I am always happy to take documentation changes such as these - though I have concerns about sustainability.

Before I spend time working on getting translation support for our docs, it would be great to see a pull request with, lets say, 60% of the docs translated. We have quite a few pages to be translated, and I fully believe that partial translation is actually worse than no translation - I've dealt with this issue for the CakePHP project, and we were lucky enough to have native speakers on the core team for multiple languages.

Given that this is a small OSS project, there certainly isn't enough money to keep a funded translation effort going for any language - I'd personally love to translate to French/Spanish, but don't quite have the time - so I think the condition above is good for the health of the project.

What do you think?

**Comment by gayeon1025** [comment]
Thank you for your kind reply and I agree with your thought that partial translation is actually worse than no translation. I will ask you to review the document again after completing some document translation.

**Comment by josegonzalez** [comment]
Closing this for now, but feel free to continue the discussion on the slack channel (I'm excited that this is happening btw!).
