### ISSUE TITLE
CHECKS fails with 406 Not Acceptable, But it fine with manual curl

### ISSUE THREAD

**Issue by Kjwon15** [dokku/dokku#3700]
## Description of problem
All checks in /CHECKS fails with status code `406 Not Acceptable`

### How reproducible
I run [Mastodon](https://github.com/tootsuite/mastodon) with [this repo](https://bitbucket.com/qdon/qdon.space)
It checks these

- /api/v1/instance version
- /about/more @qdon_support
- /@qdon_support.atom <feed
- /emoji/ae.svg <svg

And it always fails.

#### Actual Results
```
-----> Attempt 5/5 Waiting for 10 seconds ...
       CHECKS expected result:
       http://localhost/api/v1/instance => "version"
       CHECKS expected result:
       http://localhost/about/more => "@qdon_support"
       CHECKS expected result:
       http://localhost/@qdon_support.atom => "<feed"
remote:  !
remote: curl: (22) The requested URL returned error: 406 Not Acceptable
       CHECKS expected result:
       http://localhost/emoji/ae.svg => "<svg"
remote:  !     Check attempt 5/5 failed.
```

#### Expected Results

```
kjwon15@qdon:dokku/qdon/cache % curl -q --compressed --fail --location -H X-Forwarded-Proto:https -H Host:localhost 172.17.0.6:5000/emoji/ae.svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><path fill="#292F33" d="M18 0C8.059 0 0 8.06 0 18c0 9.941 8.059 18 18 18s18-8.059 18-18c0-9.94-8.059-18-18-18zm0 34C9.164 34 2 26.837 2 18 2 9.164 9.164 2 18 2c8.837 0 16 7.164 16 16 0 8.837-7.163 16-16 16z"/><path fill="#292F33" d="M10.777 9.342c0-1.488.837-2.418 2.388-2.418h5.457c4.775 0 7.72 2.14 7.72 7.007 0 3.411-2.573 5.364-5.736 5.86l5.272 5.644c.433.465.619.93.619 1.364 0 1.209-.961 2.387-2.324 2.387-.559 0-1.303-.217-1.799-.806l-6.883-8.341h-.062v6.728c0 1.551-.992 2.418-2.326 2.418s-2.326-.867-2.326-2.418V9.342zm4.651 7.348h3.193c1.705 0 2.884-1.023 2.884-2
```

**Comment by josegonzalez** [comment]
Can you show the output of a deploy after running `dokku trace:on`?

**Comment by Kjwon15** [comment]
@josegonzalez It is too much long(over 6000 lines). So I cannot paste here or pastebin.
How should I send you a log?

**Comment by josegonzalez** [comment]
I just want the portion that is doing checks, so everything after  `Attempt 5/5 Waiting for 10 seconds`

**Comment by Kjwon15** [comment]
https://pastebin.com/9bAXzxk2
Here is it. HTML that is too long and some tokens are edited.

**Comment by Kjwon15** [comment]
Oh I found it. the last checks (`/@qdon_support.atom`) doesn't accept `text/html` and return 406.
Until CHECKS doesn't support custom status code nor custom header, it'll fail and it's not a bug.

I'm closing this issue.
