### ISSUE TITLE
How do I set jvm's max heap size properly?

### ISSUE THREAD

**Issue by Elvis5566** [dokku/dokku#3705]
## Description of problem
I ran into OutOfMemoryError: GC overhead limit exceeded sometimes on my play framework app.
I think that is because heroku-buildpack-scala picked up default setting JAVA_TOOL_OPTIONS: -Xmx300m, which is too small.
so I set
```
dokku config:set staging JAVA_TOOL_OPTIONS="-Xmx3000m"
```
when the app starts, it shows 
```
Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 -Xmx3000m
```
I thought my -Xmx3000m will override -Xmx300m, however, I still got this issue randomly.
then I found out 

> This buildpack uses sbt-extras to run sbt. In this way, the execution of sbt can be customized either by setting the SBT_OPTS config variable, or by creating a .sbtopts file in the root directory of your project. When passing options to the underlying sbt JVM, you must prefix them with -J. 

so now I'm trying
```
dokku config:set production SBT_OPTS="-J-Xmx3000m"
```

By checking Runtime.getRuntime.maxMemory, neither of them work. 
What is the proper way to set -Xmx for play application?

Thank you

### `dokku report APP_NAME` output
```
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           3943        1456        1135           1        1351        2206

-----> herokuish version:
       herokuish: 0.5.0
       buildpacks:
         heroku-buildpack-scala     v84
         buildpack-nginx            v10
-----> dokku version: dokku version 0.17.9
```

**Comment by Elvis5566** [comment]
Ok...turns out I have to set JAVA_OPTS to make it work...

**Comment by trungkmy** [comment]
> Ok...turns out I have to set JAVA_OPTS to make it work...
Hi Elvis5566, can you share the solutions for this. I'm deploying spring boot application into dokku app in my ubuntu machine. The application running without any JAVA installation, so do I need to set JAVA_OPTS? If need, so can you share the way to do that? Thank you!

**Comment by josegonzalez** [comment]
@trungkmy you can set the JAVA_OPTS environment variable via `config:set`. Please open another issue if you are having trouble using Dokku, or refer to our slack/irc channels for further support.
