### ISSUE TITLE
Release phase does not use Dockerfile entrypoint properly

### ISSUE THREAD

**Issue by jrvidal** [dokku/dokku#3706]
## Description of problem
The release phase command does not work together with the Dockerfile's image entrypoint.

### How reproducible

100%

### Steps to Reproduce

1. Demo app:

    Dockerfile:
    ```
    FROM debian:stable-slim

    COPY entrypoint.sh Procfile /

    ENTRYPOINT ["/entrypoint.sh"]
    ```

    entrypoint.sh:
    ```bash
    #!/bin/sh

    echo "$@"

    if test "$1" != "release"; then
      exit 1
    fi
    ```

    Procfile:
    ```
    release: release
    ```

2. `dokku apps:create ...`, `git push dokku`

#### Actual Results

```
 !     Release command declared: 'release'
remote: execution of 'release' failed!
       /bin/bash -c set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x ;  if [[ -d '/app' ]]; then    export HOME=/app ;    cd $HOME ;  fi ;  if [[ -d '/app/.profile.d' ]]; then    for file in /app/.profile.d/*; do source $file; done ;  fi ;  if [[ -d '/cache' ]]; then    rm -rf /tmp/cache ;    ln -sf /cache /tmp/cache ;  fi ;  release || exit 1; if [[ -d '/cache' ]]; then    rm -f /tmp/cache ;  fi ; 
```

#### Expected Results
I expected a status code of 0, though the docs are a bit unclear on this point.

According to http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/:

> If you use an ENTRYPOINT in your Dockerfile, the lines in your Procfile will be passed as arguments to the ENTRYPOINT script instead of being executed.

However, according to http://dokku.viewdocs.io/dokku/advanced-usage/deployment-tasks/#procfile-release-command:

> To use the release command, simply add a release stanza to your Procfile.
> > release: curl https://some.external.api.service.com/deployment?state=built

If the `release` key is just supposed to be a bunch of arguments for my ENTRYPOINT, then the above `/bin/bash ...` command is in no shape that my ENTRYPOINT can understand.

OTOH, if the `release` key is supposed to be the _whole_ command, then my ENTRYPOINT shouldn't be called in the first place. (I suppose I can work around the issue by detecting the whole `/bin/bash ...` shenanigans and `exec`ing from there).

### `dokku report APP_NAME` output

```
=====> releasedemo app information
not deployed
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Docker image

### Additional information

`dokku --trace tags:deploy releasedemo latest`: https://gist.github.com/jrvidal/ff6d6eec11c29aa483dfd3ada8bdbdd5

(BTW, Dokku is :tada: :+1: :1st_place_medal: :fireworks: :heart:  )

**Comment by josegonzalez** [comment]
I wonder if this is the same bug as dokku/dokku#3143...

**Comment by josegonzalez** [comment]
Yeah I think if there is an entrypoint specified in the Dockerfile, then the command invoked should not have anything _but_ what is specified in the deployment task or in the release script. I'll get that fixed right up :)
