### ISSUE TITLE
[Feature Request] Notify plugins when certain events occur

### ISSUE THREAD

**Issue by dean1012** [dokku/dokku#3710]
# Description of problem

It would be helpful if Dokku plugins could subscribe in some way to events that may affect them.

This would allow plugins to perform certain actions on the system automatically when certain things are done through Dokku.

For example, check out dokku/dokku-letsencrypt#176

In this issue, it is discovered that renaming an app with `apps:rename` causes letsencrypt to break unless the certs folder is emptied under `/home/dokku/<app>/letsencrypt` because the plugin was not notified that the app changed names.

If this feature request is completed, plugins like `letsencrypt` could subscribe to the `apps:rename` event and have a chance to resolve the issue before it becomes a problem.

For example, the plugin could wipe the old certificate and generate a new one automatically using the new app domain name. 

## Environment Information

This is an issue with all dokku versions.

**Comment by josegonzalez** [comment]
That's called a plugin trigger. Plugins can subscribe to any triggers they think are useful. In fact, this is how a majority of Dokku’s functionality is implemented.

Closing as I don’t think there is anything to do here.
