### ISSUE TITLE
Issue with TLSv1.3 default in Ubuntu 16.04

### ISSUE THREAD

**Issue by rvschuilenburg** [dokku/dokku#3711]
## Description of problem
Starting with v0.19.0, the default setting is to use TLSv1.3 (added in https://github.com/dokku/dokku/pull/3680)
However, there is no official support for TLSv1.3 in Ubuntu 16.04. Therefore, after the update, restarting or rebuilding an app results in an Nginx error: `nginx: [warn] invalid value "TLSv1.3" in /home/dokku/<appname>/nginx.conf:23` `nginx: configuration file /etc/nginx/nginx.conf test failed`

### How reproducible
Install Dokku v0.19.0 on Ubuntu 16.04 LTS and deploy an app.

#### Actual Results
Nginx fails to start due to an unsupported config value.

#### Expected Results
Nginx should start up correctly and serve the app

## Environment Information

-----> uname: Linux shipyard 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           3951        1686         458         678        1806        1095
       Swap:          2047        2047           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           19.03.3
        API version:       1.40
        Go version:        go1.12.10
        Git commit:        a872fc2
        Built:             Tue Oct  8 00:59:54 2019
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          19.03.3
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.12.10
         Git commit:       a872fc2
         Built:            Tue Oct  8 00:58:28 2019
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.2.10
         GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
        runc:
         Version:          1.0.0-rc8+dev
         GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info: 
       Client:
        Debug Mode: true
WARNING: No swap limit support
       
       Server:
        Containers: 229
         Running: 89
         Paused: 0
         Stopped: 140
        Images: 479
        Server Version: 19.03.3
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
        runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 4.4.0-165-generic
        Operating System: Ubuntu 16.04.6 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.859GiB
        Name: shipyard
        ID: 55QT:2OOQ:NXQV:7FJP:LMVX:IMMT:UEWN:JAQ3:47QO:NGZV:QCGC:46QF
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.5.3
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v201
         heroku-buildpack-nodejs    v161
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v154
         heroku-buildpack-java      v63
         heroku-buildpack-gradle    v30
         heroku-buildpack-scala     v85
         heroku-buildpack-play      v26
         heroku-buildpack-php       v159
         heroku-buildpack-go        v126
         buildpack-nginx            v12
-----> dokku version: dokku version 0.19.0
-----> dokku plugins: 
       plugn: 0.3.2
         00_dokku-standard    0.19.0 enabled    dokku core standard plugin
         20_events            0.19.0 enabled    dokku core events logging plugin
         app-json             0.19.0 enabled    dokku core app-json plugin
         apps                 0.19.0 enabled    dokku core apps plugin
         builder-dockerfile   0.19.0 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.19.0 enabled    dokku core builder-herokuish plugin
         buildpacks           0.19.0 enabled    dokku core buildpacks plugin
         certs                0.19.0 enabled    dokku core certificate management plugin
         checks               0.19.0 enabled    dokku core checks plugin
         common               0.19.0 enabled    dokku core common plugin
         config               0.19.0 enabled    dokku core config plugin
         docker-options       0.19.0 enabled    dokku core docker-options plugin
         domains              0.19.0 enabled    dokku core domains plugin
         enter                0.19.0 enabled    dokku core enter plugin
         git                  0.19.0 enabled    dokku core git plugin
         letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.19.0 enabled    dokku core logs plugin
         network              0.19.0 enabled    dokku core network plugin
         nginx-vhosts         0.19.0 enabled    dokku core nginx-vhosts plugin
         plugin               0.19.0 enabled    dokku core plugin plugin
         proxy                0.19.0 enabled    dokku core proxy plugin
         ps                   0.19.0 enabled    dokku core ps plugin
         redis                1.4.10 enabled    dokku redis service plugin
         repo                 0.19.0 enabled    dokku core repo plugin
         resource             0.19.0 enabled    dokku core resource plugin
         scheduler-docker-local 0.19.0 enabled    dokku core scheduler-docker-local plugin
         shell                0.19.0 enabled    dokku core shell plugin
         ssh-keys             0.19.0 enabled    dokku core ssh-keys plugin
         storage              0.19.0 enabled    dokku core storage plugin
         tags                 0.19.0 enabled    dokku core tags plugin
         tar                  0.19.0 enabled    dokku core tar plugin
         trace                0.19.0 enabled    dokku core trace plugin

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
It's running on a virtual machine inside VMWare. Using the official bootstrap script.

### Additional information
I found some PPA repositories that supposedly contain a version of Nginx built for Ubuntu 16.04 that supports TLSv1.3, but that would require installing a version of Nginx outside the official repositories.

**Comment by alexymik** [comment]
I ran into this issue on a server, temporary fix would be to downgrade to the previous version:

`apt-get install dokku=0.18.5`

Optionally lock the dokku package to avoid a breaking update:

`apt-mark hold dokku`

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. I'll merge that once tests pass and release 0.19.1.

At some point, I'll need to drop support for older Operating Systems completely. Not that its a ton of trouble to support them, but even stuff like installing latest docker isn't possible anymore on Ubuntu 16.04, so its becoming more of a kludge as time goes on :(
