### ISSUE TITLE
Unable to install dokku on AWS ec2 instance

### ISSUE THREAD

**Issue by rkamran1** [dokku/dokku#3717]
## Description of problem
Unable to install dokku on AWS ec2 instance

### How reproducible
wget https://raw.githubusercontent.com/dokku/dokku/v0.19.1/bootstrap.sh
sudo DOKKU_TAG=v0.19.1 bash bootstrap.sh

### Steps to Reproduce
1. Created a fresh instance
2. Ran sudo apt-get update
3. Ran installation commands

#### Actual Results
First Time the error was this.

Errors were encountered while processing: /tmp/apt-dpkg-install-OrzbyA/0-dokku_0.19.1_amd64.deb E: Sub-process /usr/bin/dpkg returned an error code (1)

After I ran again
sudo DOKKU_TAG=v0.19.1 bash bootstrap.sh

and the error changed to this.
Preparing to install v0.19.1 from https://github.com/dokku/dokku.git...
--> Ensuring we have the proper dependencies

E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

#### Expected Results
it should install dokku

## Environment Information
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

The server is this one
![Screenshot 2019-10-18 at 3 39 32 PM](https://user-images.githubusercontent.com/2954644/67088108-c2c03480-f1bd-11e9-8304-d23ca7006700.png)
with 
64-bit (x86) selected

**Comment by josegonzalez** [comment]
Is that the entire output of the installation process? Can you paste which AMI you used to create this?

**Comment by rkamran1** [comment]
I have update the description with the more information. Can you please guide me.

**Comment by rkamran1** [comment]
Even if I need to change the server. I can terminate this one and create a new if you suggest so.

**Comment by josegonzalez** [comment]
```
Error: keyfile '/root/.ssh/id_rsa.pub' not found.
       you can enter a new keyfile path when you restart the installation.
```

This is the error. You'll need to set a public key there if you want to continue.

**Comment by rkamran1** [comment]
@josegonzalez Thanks this issue is resolved but after this there is another error which is coming let me paste the output.

Preparing to unpack .../0-dokku_0.19.2_amd64.deb ...
[ ok ] Reloading nginx configuration (via systemctl): nginx.service.
Unpacking dokku (0.19.2) ...
Selecting previously unselected package herokuish.
Preparing to unpack .../1-herokuish_0.5.3_amd64.deb ...
Unpacking herokuish (0.5.3) ...
Selecting previously unselected package libsensors4:amd64.
Preparing to unpack .../2-libsensors4_1%3a3.4.0-4_amd64.deb ...
Unpacking libsensors4:amd64 (1:3.4.0-4) ...
Selecting previously unselected package sysstat.
Preparing to unpack .../3-sysstat_11.6.1-1_amd64.deb ...
Unpacking sysstat (11.6.1-1) ...
Selecting previously unselected package dokku-update.
Preparing to unpack .../4-dokku-update_0.1.0_amd64.deb ...
Unpacking dokku-update (0.1.0) ...
Selecting previously unselected package parallel.
Preparing to unpack .../5-parallel_20161222-1_all.deb ...
Adding 'diversion of /usr/bin/parallel to /usr/bin/parallel.moreutils by parallel'
Adding 'diversion of /usr/share/man/man1/parallel.1.gz to /usr/share/man/man1/parallel.moreutils.1.gz by parallel'
Unpacking parallel (20161222-1) ...
Setting up libonig4:amd64 (6.7.0-1) ...
Setting up procfile-util (0.7.0) ...
Setting up dos2unix (7.3.4-3) ...
Setting up gliderlabs-sigil (0.4.0) ...
Setting up libjq1:amd64 (1.5+dfsg-2) ...
Setting up sshcommand (0.8.0) ...
Setting up libsensors4:amd64 (1:3.4.0-4) ...
Setting up herokuish (0.5.3) ...
Importing herokuish into docker (around 5 minutes)
v0.5.3: Pulling from gliderlabs/herokuish
6abc03819f3e: Pull complete
05731e63f211: Pull complete
0bd67c50d6be: Pull complete
177d5694bbfd: Pull complete
7f8a16e8ebed: Pull complete
d179e7ffc3d9: Pull complete
a156e958fda8: Pull complete
e110587f3d53: Pull complete
8b93d0ac0dd3: Pull complete
e76d205f5d10: Pull complete
bd4ddf6c4ec6: Pull complete
1423af4c8d72: Pull complete
Digest: sha256:bcff679e3076ebb8ba4ea374a2490ce0681946fb1e82ce9a1a2e416648ff8ccf
Status: Downloaded newer image for gliderlabs/herokuish:v0.5.3
docker.io/gliderlabs/herokuish:v0.5.3
Setting up jq (1.5+dfsg-2) ...
Setting up sysstat (11.6.1-1) ...

Creating config file /etc/default/sysstat with new version
update-alternatives: using /usr/bin/sar.sysstat to provide /usr/bin/sar (sar) in auto mode
Created symlink /etc/systemd/system/multi-user.target.wants/sysstat.service → /lib/systemd/system/sysstat.service.
Setting up dokku (0.19.2) ...
Purging old database entries in /usr/share/man...
Processing manual pages under /usr/share/man...
Updating index cache for path `/usr/share/man/man8'. Wait...done.
Checking for stray cats under /usr/share/man...
Checking for stray cats under /var/cache/man...
Purging old database entries in /usr/share/man/de...
Processing manual pages under /usr/share/man/de...
Updating index cache for path `/usr/share/man/de/man1'. Wait...done.
Checking for stray cats under /usr/share/man/de...
Checking for stray cats under /var/cache/man/de...
Purging old database entries in /usr/share/man/es...
Processing manual pages under /usr/share/man/es...
Updating index cache for path `/usr/share/man/es/man1'. Wait...done.
Checking for stray cats under /usr/share/man/es...
Checking for stray cats under /var/cache/man/es...
Purging old database entries in /usr/share/man/pl...
Processing manual pages under /usr/share/man/pl...
Updating index cache for path `/usr/share/man/pl/man1'. Wait...done.
Checking for stray cats under /usr/share/man/pl...
Checking for stray cats under /var/cache/man/pl...
Purging old database entries in /usr/share/man/tr...
Processing manual pages under /usr/share/man/tr...
Purging old database entries in /usr/share/man/sv...
Processing manual pages under /usr/share/man/sv...
Updating index cache for path `/usr/share/man/sv/man1'. Wait...done.
Checking for stray cats under /usr/share/man/sv...
Checking for stray cats under /var/cache/man/sv...
Purging old database entries in /usr/share/man/fi...
Processing manual pages under /usr/share/man/fi...
Purging old database entries in /usr/share/man/ru...
Processing manual pages under /usr/share/man/ru...
Purging old database entries in /usr/share/man/pt_BR...
Processing manual pages under /usr/share/man/pt_BR...
Updating index cache for path `/usr/share/man/pt_BR/man1'. Wait...done.
Checking for stray cats under /usr/share/man/pt_BR...
Checking for stray cats under /var/cache/man/pt_BR...
Purging old database entries in /usr/share/man/id...
Processing manual pages under /usr/share/man/id...
Purging old database entries in /usr/share/man/sr...
Processing manual pages under /usr/share/man/sr...
Purging old database entries in /usr/share/man/cs...
Processing manual pages under /usr/share/man/cs...
Purging old database entries in /usr/share/man/da...
Processing manual pages under /usr/share/man/da...
Purging old database entries in /usr/share/man/ko...
Processing manual pages under /usr/share/man/ko...
Purging old database entries in /usr/share/man/fr...
Processing manual pages under /usr/share/man/fr...
Updating index cache for path `/usr/share/man/fr/man1'. Wait...done.
Checking for stray cats under /usr/share/man/fr...
Checking for stray cats under /var/cache/man/fr...
Purging old database entries in /usr/share/man/pt...
Processing manual pages under /usr/share/man/pt...
Purging old database entries in /usr/share/man/sl...
Processing manual pages under /usr/share/man/sl...
Purging old database entries in /usr/share/man/nl...
Processing manual pages under /usr/share/man/nl...
Updating index cache for path `/usr/share/man/nl/man1'. Wait...done.
Checking for stray cats under /usr/share/man/nl...
Checking for stray cats under /var/cache/man/nl...
Processing manual pages under /usr/share/man/uk...
Updating index cache for path `/usr/share/man/uk/man1'. Wait...mandb: warning: /usr/share/man/uk/man1/dos2unix.1.gz: whatis parse for unix2dos(1) failed
mandb: warning: /usr/share/man/uk/man1/dos2unix.1.gz: whatis parse for unix2mac(1) failed
mandb: warning: /usr/share/man/uk/man1/dos2unix.1.gz: whatis parse for mac2unix(1) failed
mandb: warning: /usr/share/man/uk/man1/dos2unix.1.gz: whatis parse for dos2unix(1) failed
done.
Checking for stray cats under /usr/share/man/uk...
Checking for stray cats under /var/cache/man/uk...
Purging old database entries in /usr/share/man/it...
Processing manual pages under /usr/share/man/it...
Purging old database entries in /usr/share/man/ja...
Processing manual pages under /usr/share/man/ja...
Purging old database entries in /usr/share/man/zh_CN...
Processing manual pages under /usr/share/man/zh_CN...
Updating index cache for path `/usr/share/man/zh_CN/man1'. Wait...done.
Checking for stray cats under /usr/share/man/zh_CN...
Checking for stray cats under /var/cache/man/zh_CN...
Purging old database entries in /usr/share/man/hu...
Processing manual pages under /usr/share/man/hu...
Purging old database entries in /usr/share/man/zh_TW...
Processing manual pages under /usr/share/man/zh_TW...
Processing manual pages under /usr/local/man...
12 man subdirectories contained newer manual pages.
73 manual pages were added.
0 stray cats were added.
5 old database entries were purged.
Setting up dokku user
Adding user `dokku' ...
Adding new group `dokku' (1001) ...
Adding new user `dokku' (1001) with group `dokku' ...
Creating home directory `/home/dokku' ...
Copying files from `/etc/skel' ...
docker:x:999:
Setting up storage directories
Setting up plugin directories
Migrating old plugins
Enabling all core plugins
Install all core plugins
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
............................................................................................................................................................................................++*++*++*++*
Adding user dokku to group adm
[ ok ] Starting nginx (via systemctl): nginx.service.
-----> Priming bash-completion cache
Ensure proper sshcommand path
Setting up dokku-installer
Traceback (most recent call last):
  File "/usr/share/dokku/contrib/dokku-installer.py", line 23, in <module>
    if ':' in hostname:
TypeError: a bytes-like object is required, not 'str'
dpkg: error processing package dokku (--configure):
 installed dokku package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of dokku-update:
 dokku-update depends on dokku; however:
  Package dokku is not configured yet.

dpkg: error processing package dokku-update (--configure):
 dependency problems - leaving unconfigured
Setting up parallel (20161222-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Processing triggers for systemd (237-3ubuntu10.29) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ufw (0.36-0ubuntu0.18.04.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Errors were encountered while processing:
 dokku
 dokku-update
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Koeng101** [comment]
I have also encountered the two errors reported while attempting a dokku install. Previously, this script has worked for me, so possibly an update has caused this error? Am interested in what is causing this.

[Not posting terminal output because it is basically the same]

**Comment by markuspoerschke** [comment]
I can confirm this issue.

It looks like the cause of this problem is a problem in the Python script:

```
Traceback (most recent call last):
  File "/usr/share/dokku/contrib/dokku-installer.py", line 23, in <module>
    if ':' in hostname:
TypeError: a bytes-like object is required, not 'str'
```

The content of the Python file:

```
hostname = ''
try:
    command = "bash -c '[[ $(dig +short $HOSTNAME) ]] && echo $HOSTNAME || wget -q -O - icanhazip.com'"
    hostname = subprocess.check_output(command, shell=True)
    if ':' in hostname:
        hostname = ''
except subprocess.CalledProcessError:
    pass
```

**Comment by s-h-a-d-o-w** [comment]
> ```
> Error: keyfile '/root/.ssh/id_rsa.pub' not found.
>        you can enter a new keyfile path when you restart the installation.
> ```
> 
> This is the error. You'll need to set a public key there if you want to continue.

In that case, I'd recommend to update the ["Getting Started" instructions](http://dokku.viewdocs.io/dokku/getting-started/installation/) because there, it says: "Dokku is designed for usage on a fresh VM installation,"

But of course there are no SSH keys on a fresh VM...

(I'm facing the same problem right now.)

**Comment by PabOu-be** [comment]
Got the same two issues on a brand new ubuntu 18.04 installation with all the upgrades.
Works fine with v0.19.1.

**Comment by s-h-a-d-o-w** [comment]
> Works fine with v0.19.1.

Thanks for mentioning that! Now I got it running too. After installing python.
I don't know whether v0.19.2 installs python by itself but if not, there's another thing that should go into the "Getting Started" requirements.

**Comment by Koeng101** [comment]
Strange. With v0.19.1 I still get the error
```
Adding user dokku to group adm
[ ok ] Starting nginx (via systemctl): nginx.service.
-----> Priming bash-completion cache
Ensure proper sshcommand path
Setting up dokku-installer
Traceback (most recent call last):
  File "/usr/share/dokku/contrib/dokku-installer.py", line 23, in <module>
    if ':' in hostname:
TypeError: a bytes-like object is required, not 'str'
dpkg: error processing package dokku (--configure):
 installed dokku package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of dokku-update:
 dokku-update depends on dokku; however:
  Package dokku is not configured yet.

dpkg: error processing package dokku-update (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 dokku
 dokku-update
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by MaddoxDevelopment** [comment]
I am getting this issue as well on a brand new fresh Ubuntu 18.04 instance on UpCloud. Worked fine with the previous Dokku version from a few weeks ago.

**Comment by MaddoxDevelopment** [comment]
v0.18.5 seems to be the latest version that works.

**Comment by toanalien** [comment]
@markuspoerschke  I got same issues. It works for me. Hope this helps!

https://medium.com/@_t/dokku-v0-19-2-ubuntu-18-04-x64-python3-workaround-3cbeb31555e5

**Comment by josegonzalez** [comment]
Mind trying the latest Dokku version instead of that python workaround?

**Comment by josegonzalez** [comment]
I'll take a look at the ssh key issue today/tomorrow/

**Comment by dean1012** [comment]
@josegonzalez this is related to dokku/dokku-daemon#26 as well

I verified with a local VM install of Ubuntu Bionic that versions 0.19.0 and higher of dokku will not install from a fresh system due to this key error.

Interestingly, if I install 0.18.3 then upgrade to 0.19.3 it works fine.

I believe once this is resolved, you can start the Travis run again for dokku/dokku-daemon and it will pass.

**Comment by josegonzalez** [comment]
Whats weird is that I don't think I've touched any of that for 0.19.x, so I'd be curious to see what actually is causing that issue... Will be a fun one to debug, I might make it such that we just don't import it if the file doesn't exist, but output a message to stderr...

**Comment by dean1012** [comment]
For what it's worth, i'm investigating too but if you happen to find the answer first be my guest.

**Comment by dean1012** [comment]
@josegonzalez can you clarify by chance what this key is being used for?

It looks from the source like it's being used to setup the public key on the dokku user but when I setup a key and then successfully ran the installer I didn't see the key setup on the dokku user.

Understanding that component better may lead to a better resolution.

I can confirm this affects installation whether you are using bootstrap script or straight deb install (such as through the Travis/Makefile commands on dokku/dokku-daemon).

From what it seems, the installers for dokku pretty much assume that you are running in a cloud environment where you would almost be guaranteed to have a key setup on the server.

Without knowing further information, I think the best solution would probably be to silently ignore the key file if it does not exist OR to silently create a new key if needed before that part of the installation.

I'd avoid sending output through stderr in this case because it may cause the apt deb to fail installation.

**Comment by josegonzalez** [comment]
Output on stderr doesn't fail a deb deploy, only non-zero exit will. You could consider it a warning.

The key is used for the initial ssh push user.

Mind jumping on slack? We can probably discuss this better in realtime, and then summarize what the solution should be here.
