### ISSUE TITLE
Best practice for serving Ruby on Rails assets / public folder?

### ISSUE THREAD

**Issue by philkry** [dokku/dokku#372]
Currently I'm trying to deploy my Rails app with dokku. Working just fine so far.
But I'm struggling to find a proper way to serve the public/assets folder of my Rails app.

From a Rails perspective when you deploy to production environment you want your assests(javascripts, css, fonts etc) and everything else in 'public/' (e.g. large downloads) to be served by your webserver (i.e. apache or nginx), not Rails itself.
How would I accomlish this with dokku? As anginx is running on the host machine and the app is inside a self containing container, nginx has no access to the file system ('/app/public/') of my app.

I did a bit of research and only found two possible solutions, neither of those sound ideal to me:

1) moving nginx into a docker container and run the container with '-volumes-from' to get access to my app container filesystem (http://docs.docker.io/en/latest/use/working_with_volumes/)
2) configure nginx vhost's root directory to /var/lib/docker/$LONG_ID/rootfs/app/public 

I really hope there is a better way to accomplish this.
Any ideas?

**Comment by fwolfst** [comment]
Would it also work to "volume in" (using persistent storage plugin) `/app/assets/` and adjust the nginx template to serve it from there? Or is the volume not yet there during the build step?
