### ISSUE TITLE
Trademark Questions - Creating Elixir library

### ISSUE THREAD

**Issue by alanvardy** [dokku/dokku#3738]
Hello and thank you for this awesome tool, I use Dokku for all of my deployments.

I am creating an Elixir library called `ex_dokku` that provides quality of life tools and want to make sure that I do things properly!

There isn't much yet, but it can be seen here:

https://github.com/alanvardy/ex_dokku

I am planning to licence it under MIT, include a blurb about how I am not part of the Dokku team, I don't own the Dokku trademark, and provide a link to this repo.

Is there anything else I can do?

Thank you!

**Comment by josegonzalez** [comment]
Thats all fine :)
