### ISSUE TITLE
Error during "Setting up dokku-installer" when updating from 0.7.2 to 0.9.2

### ISSUE THREAD

**Issue by dsander** [dokku/dokku#3740]
Hi!

I upgraded dokku from `0.17.2` to `0.19.2` on Ubuntu 18.04 and got the following error while `dokku-installer` was set up:

```
[ ok ] Starting nginx (via systemctl): nginx.service.
-----> Priming bash-completion cache
Ensure proper sshcommand path
Setting up dokku-installer
82.207.218.104

Traceback (most recent call last):
  File "/usr/share/dokku/contrib/dokku-installer.py", line 49, in <module>
    if "inactive" in ufw_output:
TypeError: a bytes-like object is required, not 'str'
dpkg: error processing package dokku (--configure):
 installed dokku package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 dokku
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Not sure why this is even running during an upgrade, I was able to solve the issue by adding the `universal_newlines=True` argument to all `subprocess.check_output` calls in https://github.com/dokku/dokku/blob/master/contrib/dokku-installer.py

I would send a PR if I were more comfortable with Python, from what I have read on Stackoverflow it's something that changed in Python 3.x?

**Comment by toanalien** [comment]
@dsander I got same issues. It works for me. Hope this helps!

https://medium.com/@_t/dokku-v0-19-2-ubuntu-18-04-x64-python3-workaround-3cbeb31555e5

**Comment by josegonzalez** [comment]
Mind trying the latest Dokku version instead of that python workaround?

**Comment by dsander** [comment]
Worked like a charm, thank you!
