### ISSUE TITLE
Trying to run dokku inside Docker (502 error)

### ISSUE THREAD

**Issue by sardaukar** [dokku/dokku#3775]
## Description of problem

I start dokku's docker container with 

```
docker run --rm --env DOKKU_HOSTNAME=host.domain.tld --name dokku --publish 7022:22 --publish 7080:80 --publish 7443:443 --volume /var/lib/dokku:/mnt/dokku --volume /var/run/docker.sock:/var/run/docker.sock dokku/dokku
```

and my nginx config is:

```
server {
  listen 443;
  server_name host.domain.tld *.host.domain.tld;

  ssl on;
  ssl_certificate /etc/letsencrypt/live/host.domain.tld/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/host.domain.tld/privkey.pem;

  ssl_session_timeout 10m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_ciphers RC4:HIGH:!aNULL:!MD5;

  add_header Strict-Transport-Security max-age=31536000;

  location / {
    proxy_pass http://127.0.0.1:7080;

    #proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    #proxy_set_header        Accept-Encoding   "";
    #proxy_set_header        Host            $host;
    proxy_set_header        X-Real-IP       $remote_addr;
    #proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    #proxy_set_header        X-Forwarded-Proto $scheme;
    add_header              Front-End-Https   on;
    #proxy_redirect     off;
  }

  client_max_body_size 1024m;
}
```

When I try to go to `host.domain.tld` I get a 502 page from nginx.

### How reproducible

Always.

### Steps to Reproduce

1. docker pull dokku/dokku
2. setup nginx
3. run `docker run` as above
4. go to `https://host.domain.tld` in the browser
5. 502 page

#### Actual Results

502 error

#### Expected Results

Dokku setup page with SSH key upload

## Environment Information

Ubuntu 18.04 LTS, minimal server install, only sshd and docker installed

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Via Docker, on a Vultr VPS

### Additional information

Info on nginx's log:

```
*28 upstream prematurely closed connection while reading response header from upstream, client: 93.108.140.44, server:
host.domain.tld, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:7080/", host: "host.domain.tld"
*28 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 93.108.140.44, server: host.domain.tld, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:7080/", host: "host.domain.tld"
```

**Comment by josegonzalez** [comment]
The docker image does not run the setup page. If you wish to add ssh keys, you'll need to enter the container and use the `ssh-keys:add` command. This is documented near the bottom of the [docker-based installation](http://dokku.viewdocs.io/dokku/getting-started/install/docker/) instructions page.
