### ISSUE TITLE
Inaccessible setup page 

### ISSUE THREAD

**Issue by radar1975** [dokku/dokku#3795]
Setup page is inaccessible after 

docker run \
  --env DOKKU_HOSTNAME=dokku.me \
  --name dokku \
  --publish 3022:22 \
  --publish 8080:80 \
  --publish 8443:443 \
  --volume /var/lib/dokku:/mnt/dokku \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  dokku/dokku:0.19.10

http://localhost/ does not work with "This site can't be reached
http://[ip adresse]/ does not work with "This site can't be reached

i tried a different port .. still the same issue

Using Docker on Windows and Docker on a CentOs with same result

Help would be appreciated

**Comment by josegonzalez** [comment]
The bootstrap ui is not enabled in the docker container, nor will it be. You can use the `ssh-keys` plugin to add ssh keys, and deploys will otherwise work as expected.

**Comment by josegonzalez** [comment]
If you need further assistance, please checkout our slack group.
