### ISSUE TITLE
Add variable to specify IP address to bind nginx to

### ISSUE THREAD

**Issue by Signum** [dokku/dokku#3805]
## Description of problem

IP address (IPv4/IPv6) that the nginx proxy binds to is not configurable. Nginx binds to all interfaces.

## Workaround

Currently I am shipping an `nginx.conf.sigil` file with my project to override the nginx configuration template. But that feels very dirty and it makes the project in my Git repository work only on my development system. It would fail as soon as I send it to someone else.

## How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

deb on virtual server running Debian Stretch

## Remedy

I suggest to add environment variables like `DOKKU_PROXY_BIND_IP4` and `DOKKU_PROXY_BIND_IP6` to set the binding addresses. In my opinion that should be a global variable similar to "HOSTNAME" or "VHOST".

I would like to help with a pull request. I believe that the nginx.conf.sigil needs _listen_ directives like these:

```
server {
  listen      [${PROXY_BIND_IP6:-"::"}]:{{ $listen_port }};
  listen      {{ if $.PROXY_BIND_IP4}}{{ $.PROXY_BIND_IP4}}:{{end}}{{ $listen_port }};
```

And I assume that the nginx-vhosts/functions needs to get environment variables to pass them on to _sigil_. So at the right place there it may need:

```
local PROXY_BIND_IP4=$(config_get "$APP" DOKKU_PROXY_BIND_IP4)
local PROXY_BIND_IP6=$(config_get "$APP" DOKKU_PROXY_BIND_IP6)
```

Unfortunately I cannot build the Debian package properly. "make deb-dokku" fails at the help2man stage here. Hints welcome.

**Comment by josegonzalez** [comment]
I'd like to avoid adding more config via environment variables, and instead use the properties system, but otherwise this seems pretty good.
