### ISSUE TITLE
pull herokuish image when needed

### ISSUE THREAD

**Issue by pynixwang** [dokku/dokku#3822]
more and more app deployed using docker, herokuish is the largest image. 1.33G.

delay pull can save some space.

**Comment by josegonzalez** [comment]
When you do an install via debian package, you can run `apt install` with the `--no-install-recommends` flag to avoid installing the package/pulling the image.

If you are using buildpacks for deploying, delaying that image pull does not help as the image is in use, so the above is only actually useful if you are _only_ deploying via Dockerfiles or if you are in an airgapped environment where the image is pulled via some other method.

**Comment by pynixwang** [comment]
add this flag to bootstrap script is good

**Comment by josegonzalez** [comment]
You can specify that via an environment variable as well - that is documented [here](http://dokku.viewdocs.io/dokku/getting-started/advanced-installation/#skipping-herokuish-installation).

**Comment by pynixwang** [comment]
@josegonzalez sorry ,  I should search it first.

**Comment by pynixwang** [comment]
@josegonzalez sorry ,  I should search it first.
