### ISSUE TITLE
plugin_prime_bash_completion function never finishes

### ISSUE THREAD

**Issue by dennismende** [dokku/dokku#3832]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

## Description of problem
Whenever I try to install dokku on one of my servers, the installation stops/freezes when the function "plugin_prime_bash_completion" is getting executed.

### How reproducible
Just install dokku. I think it's a system specific topic but I have no clue what the reason could be. I want to install dokku 0.19.3 on a Debian Jessie machine.

**Comment by josegonzalez** [comment]
Is this on a fresh server?

Can you run:

```
export DOKKU_TRACE=1
export TRACE=1
```

and then retry the install?

**Comment by dennismende** [comment]
The problem has been an internal network issue. Nothing to do with dokku. Downloading if buildpacks was not possible and that's why the deployment was not working anymore.
