### ISSUE TITLE
Finding the application path after deployment

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#3834]
I successfully deployed my Ruby on Rails application `fireworks_app` with `Dokku` in a `Ubuntu 18.04 LTS` machine, and now I would like to add a logrotate file for my Rails logs. What is the path of my application (and thus of my log files)? There is a `/home/dokku/fireworks_app` folder but this folder contains only the following items:

    $ ls
    CONTAINER.web.1        DOCKER_OPTIONS_RUN  HEAD        URLS      cache        hooks          maintenance   objects
    DOCKER_OPTIONS_BUILD   DOKKU_SCALE         IP.web.1    VHOST     config       info           nginx.conf    refs
    DOCKER_OPTIONS_DEPLOY  ENV                 PORT.web.1  branches  description  letsencrypt    nginx.conf.d

There is no trace of the `/app` folder. I suppose somewhere in the system there is a folder containing my application with the known Rails file structure, but I cannot find it.

**Comment by josegonzalez** [comment]
Your app is running within a docker container, and as we only run a single process in that container - assuming you are deploying via buildpacks - there isn't a way to run logrotate in the container. Your rails app should not be logging to files, it should be logging to stdout, as per the 12factor.net manifesto.

If your app is still logging to files for some reason, I would recommend using a log-writer in your app that does logrotation automatically. Most frameworks support something like this, and I assume rails is no exception.

Hope that helps.
