### ISSUE TITLE
Unable to connect: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#3839]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.

## Description of problem
I successfully deployed my Ruby on Rails application in a Ubuntu root server at NetCup.
When I try to connect via browser to my server I get the following error message from Chromium: This site can’t be reached. cinemeeting.eu refused to connect. ERR_CONNECTION_REFUSED.
Firefox says "Unable to connect. Firefox can’t establish a connection to the server at cinemeeting.eu."
Maintenance mode works when it is on.
The following are my IPTABLES rules:

    # Allow all loopback (lo0) traffic and reject traffic
    # to localhost that does not originate from lo0.
    -A INPUT -i lo -j ACCEPT
    -A INPUT ! -i lo -s 127.0.0.0/8 -j REJECT

    # Allow ping.
    -A INPUT -p icmp -m state --state NEW --icmp-type 8 -j ACCEPT

    # Allow SSH connections.
    -A INPUT -p tcp --dport 22 -m state --state NEW -j ACCEPT

    # Allow HTTP and HTTPS connections from anywhere
    # (the normal ports for web servers).
    -A INPUT -p tcp --dport 80 -m state --state NEW -j ACCEPT
    -A INPUT -p tcp --dport 443 -m state --state NEW -j ACCEPT

    # Allow inbound traffic from established connections.
    # This includes ICMP error returns.
    -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

    # Log what was incoming but denied (optional but useful).
    -A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables_INPUT_denied: " --log-level 7

    # Reject all other inbound.
    -A INPUT -j REJECT

    # Log any traffic that was sent to you
    # for forwarding (optional but useful).
    -A FORWARD -m limit --limit 5/min -j LOG --log-prefix "iptables_FORWARD_denied: " --log-level 7

    # Reject all traffic forwarding.
    -A FORWARD -j REJECT

### Steps to Reproduce
1. Simply try to connect to cinemeeting.eu via browser

#### Actual Results
Your connection will be refused

#### Expected Results
My application should show up

### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> You may also run `dokku report` without any arguments to display the top-level reporting information.

```
$ dokku report cinemeeting_app
[sudo] password for user: 
-----> uname: Linux rocinante 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           7976         661        3091          24        4223        7226
       Swap:          8191           0        8191
-----> docker version: 
       Client: Docker Engine - Community
        Version:           19.03.5
        API version:       1.40
        Go version:        go1.12.12
        Git commit:        633a0ea838
        Built:             Wed Nov 13 07:29:52 2019
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          19.03.5
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.12.12
         Git commit:       633a0ea838
         Built:            Wed Nov 13 07:28:22 2019
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.2.10
         GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
        runc:
         Version:          1.0.0-rc8+dev
         GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info: 
       Client:
        Debug Mode: true
       
       Server:
        Containers: 15
         Running: 5
         Paused: 0
         Stopped: 10
        Images: 16
        Server Version: 19.03.5
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
WARNING: No swap limit support
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
        runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 4.15.0-74-generic
        Operating System: Ubuntu 18.04.3 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 7.79GiB
        Name: rocinante
        ID: QWLE:G63M:FPIA:TX2P:V2WM:NE43:A3WR:UKVP:YWII:I5QJ:BUSK:FHHO
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.5.5
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v207
         heroku-buildpack-nodejs    v166
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v162
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v86
         heroku-buildpack-play      v26
         heroku-buildpack-php       v166
         heroku-buildpack-go        v136
         buildpack-nginx            v12
-----> dokku version: dokku version 0.19.12
-----> dokku plugins: 
       plugn: 0.3.2
         00_dokku-standard    0.19.12 enabled    dokku core standard plugin
         20_events            0.19.12 enabled    dokku core events logging plugin
         app-json             0.19.12 enabled    dokku core app-json plugin
         apps                 0.19.12 enabled    dokku core apps plugin
         builder-dockerfile   0.19.12 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.19.12 enabled    dokku core builder-herokuish plugin
         buildpacks           0.19.12 enabled    dokku core buildpacks plugin
         certs                0.19.12 enabled    dokku core certificate management plugin
         checks               0.19.12 enabled    dokku core checks plugin
         common               0.19.12 enabled    dokku core common plugin
         config               0.19.12 enabled    dokku core config plugin
         docker-options       0.19.12 enabled    dokku core docker-options plugin
         domains              0.19.12 enabled    dokku core domains plugin
         enter                0.19.12 enabled    dokku core enter plugin
         git                  0.19.12 enabled    dokku core git plugin
         letsencrypt          0.9.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.19.12 enabled    dokku core logs plugin
         maintenance          0.5.0 enabled    Maintenance mode for apps
         network              0.19.12 enabled    dokku core network plugin
         nginx-vhosts         0.19.12 enabled    dokku core nginx-vhosts plugin
         plugin               0.19.12 enabled    dokku core plugin plugin
         postgres             1.9.5 enabled    dokku postgres service plugin
         proxy                0.19.12 enabled    dokku core proxy plugin
         ps                   0.19.12 enabled    dokku core ps plugin
         redis                1.10.4 enabled    dokku redis service plugin
         repo                 0.19.12 enabled    dokku core repo plugin
         resource             0.19.12 enabled    dokku core resource plugin
         scheduler-docker-local 0.19.12 enabled    dokku core scheduler-docker-local plugin
         shell                0.19.12 enabled    dokku core shell plugin
         ssh-keys             0.19.12 enabled    dokku core ssh-keys plugin
         storage              0.19.12 enabled    dokku core storage plugin
         tags                 0.19.12 enabled    dokku core tags plugin
         tar                  0.19.12 enabled    dokku core tar plugin
         trace                0.19.12 enabled    dokku core trace plugin
=====> cinemeeting_app app information
       App dir:                       /home/dokku/cinemeeting_app
       Git sha:                       2c4bf48                  
       Deploy source:                 git                      
       Locked:                        false                    
=====> cinemeeting_app buildpacks information
       Buildpacks list:               
=====> cinemeeting_app ssl information
       Ssl dir:                       /home/dokku/cinemeeting_app/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> cinemeeting_app checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> cinemeeting_app docker options information
       Docker options build:          --link dokku.postgres.cinemeeting_postgres:dokku-postgres-cinemeeting-postgres --link dokku.redis.cinemeeting_redis:dokku-redis-cinemeeting-redis 
       Docker options deploy:         --link dokku.postgres.cinemeeting_postgres:dokku-postgres-cinemeeting-postgres --link dokku.redis.cinemeeting_redis:dokku-redis-cinemeeting-redis --restart=on-failure:10 
       Docker options run:            --link dokku.postgres.cinemeeting_postgres:dokku-postgres-cinemeeting-postgres --link dokku.redis.cinemeeting_redis:dokku-redis-cinemeeting-redis 
=====> cinemeeting_app domains information
       Domains app enabled:           true                     
       Domains app vhosts:            cinemeeting.eu www.cinemeeting.eu
       Domains global enabled:        false                    
       Domains global vhosts:                                  
=====> cinemeeting_app git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
=====> cinemeeting_app network information
       Network listeners:             172.17.0.5:5000
       Network bind all interfaces:   false
=====> cinemeeting_app nginx information
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
=====> cinemeeting_app proxy information
       Proxy enabled:                 true                     
       Proxy type:                    nginx                    
       Proxy port map:                http:80:5000             
=====> cinemeeting_app ps information
       Processes:                     3                        
       Deployed:                      true                     
       Running:                       true                     
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Ps can scale:                  true                     
       Status web.1:                  running    (CID: c013a225ac84)
       Status worker.1:               running    (CID: 3d2e26c9bf11)
       Status worker.2:               running    (CID: b6b34dc2bde5)
=====> cinemeeting_app scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> cinemeeting_app storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:                                     
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Dokku was installed in a Ubuntu root server at [netcup](https://www.netcup.eu/) with the following commands:

    wget https://raw.githubusercontent.com/dokku/dokku/v0.19.13/bootstrap.sh;
    sudo DOKKU_TAG=v0.19.13 bash bootstrap.sh

### Additional information

- Container Inspect Output (if applicable) via `dokku ps:inspect APP_NAME`
    $ dokku ps:inspect cinemeeting_app
    Error: No such container

- The nginx configuration (if applicable) via `dokku nginx:show-conf`
    $ dokku nginx:show-conf
    APP must not be null

- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
Is your rails app listening on all interfaces - `0.0.0.0` - and respecting the `PORT` environment variable?

**Comment by knzudgt** [comment]
@josegonzalez how can I check that?
The `config/puma.rb` file suggested by [Heroku](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#config) is below:

    workers Integer(ENV['WEB_CONCURRENCY'] || 2)
    threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
    threads threads_count, threads_count

    preload_app!

    rackup      DefaultRackup
    port        ENV['PORT']     || 3000
    environment ENV['RACK_ENV'] || 'development'

    on_worker_boot do
      # Worker specific setup for Rails 4.1+
      # See: https://devcenter.heroku.com/articles/
      # deploying-rails-applications-with-the-puma-web-server#on-worker-boot
      ActiveRecord::Base.establish_connection
    end

**Comment by josegonzalez** [comment]
https://stackoverflow.com/a/52788415

**Comment by knzudgt** [comment]
@josegonzalez , on which port is the server in the docker container listening for connections? As you can see in my original post, my firewall rules allow http and https connections only from port 80 and port 443, rejecting all other inbound.

**Comment by josegonzalez** [comment]
The container should be listening on the PORT environment variable, which we set to `5000`. However, it also needs to listen on all interfaces, which in puma is controlled by the `bind` statement. Have you checked that your app is indeed listening on all interfaces, and not just `127.0.0.1`?

**Comment by knzudgt** [comment]
@josegonzalez now my application is listening on all interfaces with the line of code suggested by nateberkopec at the puma GitHub page:

    bind "tcp://0.0.0.0:#{ENV['PORT'] || 3000}"

 Also my firewall now accepts incoming connections from port 5000. However I still have the same issue. Any other idea?

**Comment by josegonzalez** [comment]
From the server, what happens when you run:

```
curl $(dokku network:report cinemeeting_app --network-listeners)
```

**Comment by josegonzalez** [comment]
I just tested a curl to your domain.

```
# curl --include cinemeeting.eu
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Mon, 17 Feb 2020 21:46:14 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Location: https://cinemeeting.eu/
```

See that redirect to https? This is a rails app, so you likely have `config.force_ssl=true`, and the app itself is redirecting to https. Since you haven't attached an SSL certificate to the app - see the certs section of your report output - the server isn't listening to https requests, so thats why you are getting connection refused errors.

Disable the force ssl redirect or add an ssl certificate to fix the problem.

**Comment by knzudgt** [comment]
@josegonzalez I am using [dokku-letsencrypt](https://github.com/dokku/dokku-letsencrypt/).
I followed the instructions and installed letsencrypt with the following command:

    sudo dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git

I set an email for my app:

    dokku config:set --no-restart cinemeeting_app DOKKU_LETSENCRYPT_EMAIL=myemail@email.com

I turned it on:

    dokku letsencrypt cinemeeting_app

Then I automated the renewal of the certificate with a cron job:

    dokku letsencrypt:cron-job --add

This is what happens when I run:

    curl --include $(dokku network:report cinemeeting_app --network-listeners)
    HTTP/1.1 301 Moved Permanently
    Content-Type: text/html
    Location: https://172.17.0.5:5000/
    Transfer-Encoding: chunked

**Comment by josegonzalez** [comment]
What is the output of `dokku nginx:show-conf cinemeeting_app`?

```
$ curl --include cinemeeting.eu
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 18 Feb 2020 19:43:46 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Location: https://cinemeeting.eu/

$ curl --include https://cinemeeting.eu
curl: (7) Failed to connect to cinemeeting.eu port 443: Connection refused
```

Indicates to me that you still have a firewall issue or nginx isn't listening on port 443 for this app.

**Comment by knzudgt** [comment]
@josegonzalez , this is the output of `dokku nginx:show-conf cinemeeting_app`:

    $ dokku nginx:show-conf cinemeeting_app

    server {
      listen      [::]:80;
      listen      80;
      server_name cinemeeting.eu www.cinemeeting.eu; 
      access_log  /var/log/nginx/cinemeeting_app-access.log;
      error_log   /var/log/nginx/cinemeeting_app-error.log;

      location    / {

        gzip on;
        gzip_min_length  1100;
        gzip_buffers  4 32k;
        gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
        gzip_vary on;
        gzip_comp_level  6;

        proxy_pass  http://cinemeeting_app-5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Request-Start $msec;
      }
      include /home/dokku/cinemeeting_app/nginx.conf.d/*.conf;

      error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
      location /400-error.html {
        root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
        internal;
      }

      error_page 404 /404-error.html;
      location /404-error.html {
        root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
        internal;
      }

      error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
      location /500-error.html {
        root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
        internal;
      }

    }

    upstream cinemeeting_app-5000 {

      server 172.17.0.5:5000;
    }


Also, if this can be useful, when I deploy the application the web URLs generated are `http://cinemeeting.eu` and `http://www.cinemeeting.eu`, not `https://cinemeeting.eu` and `https://www.cinemeeting.eu`

**Comment by josegonzalez** [comment]
Do you have something like cloudflare in front of your app?

**Comment by knzudgt** [comment]
@josegonzalez no, I do not have anything like cloudflare

**Comment by josegonzalez** [comment]
Did you disable the forced ssl redirect in your rails app?

**Comment by knzudgt** [comment]
No, I did not disable it

**Comment by josegonzalez** [comment]
Is there a chance you can join us on slack for support? Github issues isn't the best place for this sort of back and forth.

**Comment by knzudgt** [comment]
How can I join you on slack? I even do not know what slack is

**Comment by josegonzalez** [comment]
http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels <-- you can join via slack or irc (slack is somewhat preferred as I can message you if we just miss each other and you'll get notified, though both are linked together).

**Comment by knzudgt** [comment]
Do you mean Gliderlabs Slack? The you@yourdomain.com I have to provide means my email address?

**Comment by knzudgt** [comment]
@josegonzalez now I am on Slack

**Comment by knzudgt** [comment]
`config.force_ssl = true` option in `config/environments/production.rb` was somehow screwing with the application. So we set `config.force_ssl = false`, deployed the application and then ran `dokku letsencrypt cinemeeting_app`. Then we reset `config.force_ssl = true` and redeployed the application.
