### ISSUE TITLE
Publishing a custom port with Dockerfile? (for an ngrok alternative)

### ISSUE THREAD

**Issue by nabati** [dokku/dokku#3856]
Basically, I'm trying to setup a reverse proxy that can tunnel requests from a subdomain to my localhost together with Dokku, like a self-hosted ngrok. 

I've made a custom Docker image that should be reverse-proxying the requests to the local port 7890, but binding the containers port to a port on the host (that I can use locally) is proving to be difficult. 

Looking at the source code, the salient part is here; 

```
          cid=$("$DOCKER_BIN" container create --label=com.dokku.container-type=deploy --label=com.dokku.process-type=$PROC_TYPE "${DOCKER_RUN_LABEL_ARGS[@]}" $DOKKU_GLOBAL_RUN_ARGS --init $DOKKU_DOCKER_PORT_ARGS --env PORT=$DOKKU_PORT "${ARG_ARRAY[@]}" $IMAGE $START_CMD)
```

where I would basically like to insert an arbitrary per-app parameter BEFORE `$IMAGE`, such as `-p 7890:7890`. Then I could set up an SSH tunnel between the host and my development environment.

Is this possible to achieve somehow?

**Comment by josegonzalez** [comment]
This is possible through the [port management system](http://dokku.viewdocs.io/dokku/networking/port-management/), though we  use nginx to proxy things, so it will be an http/https proxy.

If you want to directly expose a tcp port on the host, you'll need to disable the proxy for the app and disable zero-downtime checks, add the proper `EXPOSE` command to your Dockerfile, and add `--network=host` via docker options.

Hope that helps.
