### ISSUE TITLE
How to stop/restart running processes

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#3859]
Before redeploying my application, my running processes were the following:

    $ dokku ps:scale my_app 
                                              
    web:    1                                                                            
    worker: 2    

I redeployed my application and restarted it with the following command:

    $ dokku ps:restart my_app

After that, my running processes were still the same:

    $ dokku ps:scale my_app 
                                              
    web:    1                                                                            
    worker: 2    

This makes me think that the above processes were not restarted.
Since I made some changes to the configuration file of my web server, I need to restart it. How can I make a restart of the web and worker processes?

**Comment by josegonzalez** [comment]
The processes were restarted if you ran `ps:restart`. That command starts completely new containers. You can check if this is the case by running `dokku ps:report APP` before and after a restart to see that the container was recreated. The output of `ps:scale` is the current scale count for each process type.
