### ISSUE TITLE
change an environment variable value

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#3867]
I need to change the value of an environment variable.
Am I expected to unset it and then set it again, or can I set it to the new value straight away?
In other words, am I required to do as follows:

$ dokku config:unset --no-restart cinemeeting_app SENDIBLUE_PASSWORD
$ dokku config:set --no-restart cinemeeting_app SENDIBLUE_PASSWORD="new_password" 

or reset it immediately?:

$ dokku config:set --no-restart cinemeeting_app SENDIBLUE_PASSWORD="new_password"

**Comment by josegonzalez** [comment]
You can `config:set` directly, no need to unset first, though if you do `--no-restart`, the app won't restart and the change won't get picked up until the next rebuild or next deploy.

**Comment by knzudgt** [comment]
@josegonzalez so it is advisable to avoid using --no restart if I immediately need the change? In fact I need the change straight away

**Comment by josegonzalez** [comment]
Yes. The flag does what it says on the tin, so if you don't want that behavior, don't use that flag?
