### ISSUE TITLE
environment variables value in quotation marks?

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#3872]
In order to set an environment variable is it necessary to include its value in quotation marks, as follows?:

    $ dokku config:set cinemeeting_app SENDIBLUE_PASSWORD="12334567890"

Or instead the value must be expressed without quotation marks, as follows?

    $ dokku config:set cinemeeting_app SENDIBLUE_PASSWORD=12334567890

Or again the two expressions are equivalent?

**Comment by josegonzalez** [comment]
They are equivalent. Quoting is useful when you have spaces or similar in your value.

Feel free to [PR the docs](http://dokku.viewdocs.io/dokku/configuration/environment-variables/) if you think this can be better exposed.
