### ISSUE TITLE
cpio is missing in the docker image

### ISSUE THREAD

**Issue by ricsam** [dokku/dokku#3875]
Hi, it seems like cpio is missing from the image at https://hub.docker.com/r/dokku/dokku, could that be added? simple apt-get install cpio :)

**Comment by ricsam** [comment]
\*or `RUN apt-get update && apt-get install cpio` is what I've added to my docker image extending dokku/dokku

It will fix the following error: `/var/lib/dokku/plugins/enabled/apps/subcommands/clone: line 44: cpio: command not found` when creating an app

**Comment by josegonzalez** [comment]
It should be added as a dependency to the redhat/debian packages.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
