### ISSUE TITLE
Does set environment variables require the application be deployed?

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#3876]
I am having some issues in authenticating with username and password via smtp at Sendinblue, both values being stored in environment variables.
I have set the above environment variable before deploying the application for the first time, so I wonder if this choice might be causing the issue.

**Comment by josegonzalez** [comment]
No it does not.

In the future, please ask these sorts of general questions on our [slack or irc chat](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/). Github issues isn't the best forum for getting general support.
