### ISSUE TITLE
fatal: 'dokku/master' does not appear to be a git repository

### ISSUE THREAD

**Issue by luisCalzada** [dokku/dokku#3878]
Hello everyone.
Recently i got assigned to a project that uses dokku, but before the responsible of said project could set my ssh key for the dokku user. he left the company and even tho im trying to reach him he doesn answer. He left an old copy of the code. I want to pull request the current code.
I used:
cat ~/.ssh/id_rsa.pub | ssh root@dokku.me dokku ssh-keys:add KEY_NAME
To set my ssh key for the dokku user (I can ssh to the root user of the DigitalOcean droplet), but i get:
fatal: 'dokku/master' does not appear to be a git repository
I really appreciate any guidence
Also i've googled and it seems like an issue with my ssh key, but can't find a solution to my case.

**Comment by josegonzalez** [comment]
This is more of a support question, can you join us on [slack/irc](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/)? Github issues isn't the best place for this sort of thing (I'll follow-up here if there was an actual issue).
