### ISSUE TITLE
How to make dokku deploy app to https connection only

### ISSUE THREAD

**Issue by amjedomar** [dokku/dokku#3882]
I added domain to my dokku app
```
dokku domains:add myapp example.com
```
then I encrypted the app connection
```
dokku letsencrypt myapp
```

the problem is when I deployed my app it deployed to `http` and `https` connections
```
=====> Application deployed:
       http://example.com
       https://example.com
```

My question is how to make dokku deploy app to `https` connection only

> The reason behind make dokku only deploy app to `https` connection
> 1. Because if app deploy to `http` connection then the attacker can access my app via requested `http` connection `http://example.com` using postman (for example or other tool). An example of this case is `heruko.com` it is encrypted using [Letsencrypt][1] but if you try to make request using http connection `http://heruko.com` via postman then success response will returned.
> 2. Another reason that if the `https` certificate expires then the attacker can access my app via http connection

  [1]: https://letsencrypt.org/

**Comment by josegonzalez** [comment]
http requests will redirect to https if you have an ssl certificate.
