### ISSUE TITLE
Running App Locally

### ISSUE THREAD

**Issue by amjedomar** [dokku/dokku#3886]
I have two applications

- the first one is `nodejs api` running on public host `api.mydomain.com`
- the other is `php api`, I want to running it locally and it will be called by `nodejs api`

**My question:** can I running app locally in dokku
if I can please describe how to implement that

**Comment by josegonzalez** [comment]
Dokku is meant to run on a server. If you are attempting to build docker images using buildpacks locally, please look into  [pack](https://github.com/buildpacks/pack).

**Comment by amjedomar** [comment]
I don't mean hosting app in local machine
both of two apps will be hosting in server (digitalocean droplet)

**My question is** in dokku can I host app in private host (localhost)?, can I do something familiar to the following?

- the `php-api`
```
dokku domains:set php-api localhost:3456
``` 

- the `nodejs-api` code
```
// make http request to php-api using its private host (localhost)
got.get('http://localhost:3456/users'));
```

> By **private host**: I mean this app cannot accessed outside the server, it only can accessed inside the server
