### ISSUE TITLE
Expose docker load

### ISSUE THREAD

**Issue by SteffenL** [dokku/dokku#3898]
Since the `dokku` binary does not expose `docker load` somehow, it is not clear to me how to directly deploy a Docker image to a Dokku host without opening up my system to all sorts of stuff that can come through SSH.

http://dokku.viewdocs.io/dokku/deployment/methods/images/#deploying-an-image-from-ci

Do you have room to consider this use case more?

Here is my failed attempt at following the documented method:

```
docker save "${DOKKU_IMAGE}" | ssh "dokku@${DOKKU_HOST}" "docker load | dokku tags:deploy ${DOKKU_APP} ${DOKKU_TAG}"
 !     `docker load | dokku tags:deploy [...]` is not a dokku command.
 !     See `dokku help` for a list of available commands.
```

**Comment by josegonzalez** [comment]
I wonder if we should rename the `tags` plugin to an `image` plugin, and somehow merge it with the external [registry](https://github.com/dokku/dokku-registry) plugin? 

I'm not super convinced that loading an image from remote is a great idea - the workflow is documented to facilitate the usecase, but ideally folks are deploying images built _with_ Dokku, or at the very least using a remote registry to pull those images...

**Comment by SteffenL** [comment]
Please note that I have barely tried to use dokku. I am just one guy having a hard time finding something that can allow me to finally (and easily) have a more professional development and deployment workflow.

I have a few concerns with letting dokku build my images (valid or otherwise).

I want..
- Early feedback in case of build failures or test failures.
- Notifications of build success/failure sent to wherever I want them.
- To upgrade my app and database in a controlled manner.

When I deploy to a testing/staging environment, perhaps multiple times per day, maybe that could create a lot of noise/junk that takes up precious resources and possibly increases costs. Using Docker registries means that the junk is stored in more places.

When it's time for a release, it will be tagged in Git and maybe then it will be a good idea to push that image to a Docker registry; however, that image does not matter as much as the app's binaries (artifacts) that were built by the CI server. Those will be stored elsewhere.

When it's time to deploy to any environment, especially production, I want to deploy already-built images to avoid affecting other apps running on that server more than necessary.

The approach I'm seeking seems backwards when I see what the most common workflow is for dokku and other PaaS.

I don't know if this is going to work for me in the long run but I decided to hijack the dokku SSH command to work around the problem the simplest way I could think of.

`deploy-helper.py`:
```python
#!/usr/bin/env python3

import subprocess
import sys

def cmd_docker_load(args):
    if len(args) < 2:
        raise Exception("Image file is required")
    with sys.stdin.buffer if args[1] == "-" else open(args[1], "rb") as image:
        subprocess.check_call(["docker", "load"], stdin=image)

def cmd_dokku(args):
    subprocess.check_call(["dokku"] + args)

commands = {
    "docker:load": cmd_docker_load
}

def main(args):
    (commands.get(args[0], cmd_dokku) if len(args) > 0 else cmd_dokku)(args)

if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except Exception as e:
        print("Error: {}".format(e))
```

Installation:
```
cd /usr/bin
sudo nano deploy-helper
sudo chown root:root deploy-helper
sudo chmod 755 deploy-helper

cd /home/dokku/
sudo mv .sshcommand .sshcommand.old
echo "/usr/bin/deploy-helper" | sudo tee .sshcommand > /dev/null
sudo chown dokku:root .sshcommand
sudo chmod 644 .sshcommand
```

Example:
```
$ docker save dokku/my-app:ci | bzip2 | ssh dokku@dokku-host -- docker:load -
Loaded image: dokku/my-app:ci

$ ssh dokku@dokku-host -- tags:deploy my-app ci
-----> Setting config vars
       DOKKU_DOCKERFILE_PORTS:  80/tcp
-----> Releasing my-app (dokku/my-app:ci)...
-----> Deploying my-app (dokku/my-app:ci)...
[...]
```

**Comment by josegonzalez** [comment]
I think the correct path forward here is to push your images to an intermediate docker registry and use the [official registry plugin](https://github.com/dokku/dokku-registry) - not bundled because it has no test suite just yet, but works just fine - to pull images down.

Otherwise, `docker load` can be run through the normal ssh methods  - and this is documented in our docs. I don't think this is common enough of a workflow to support, but I can be convinced otherwise if others request this functionality in the future (via chat, github issues, twitter, etc.).

**Comment by Yihao-G** [comment]
Actually, I'd still prefer to run `docker load` using `dokku` account which only exposes Dokku commands. 

So I wrote a simple plugin to expose `docker load`: https://github.com/Yihao-G/dokku-docker-load and it should be able to handle this use case.
