### ISSUE TITLE
Dokku does not set server_name in the nginx.conf

### ISSUE THREAD

**Issue by murbanowicz** [dokku/dokku#3908]
Dokku version: 0.20.0
nginx version: nginx/1.14.0 (Ubuntu)

I found the doc here: http://dokku.viewdocs.io/dokku/configuration/domains/#default-site

When I add this file, it brakes all apps and all domain are getting specified response. 
I did not change anything and I did everything as specified in the docs.

As soon as I comment out this file, everything is working fine.

Other strange behaviour is that when I try to call my VPS IP directly, it will always respond with "Welcome to nginx"

I found the issue, but don't have the solution: **Dokku does not specify `server_name` inside the `/home/dokku/myappname/nginx.conf`.** As soon as I manually added `server_name` it is all working correctly.

What is wrong?

UPDATE: In some I removed the domain associated with the app. It was causing this issue. As soon as I added the domain to the app and ran deployment again it went as expected.

**Comment by josegonzalez** [comment]
We definitely have `server_name` set [here](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L11), and pulls that from the domains plugin. Not sure how your setup was configured, but glad to hear it works now.
