### ISSUE TITLE
Feature: Add option to disable webserver logs

### ISSUE THREAD

**Issue by pixelbrackets** [dokku/dokku#3911]
## Description of the feature

As an app maintainer I would like to disable/enable webserver logs with one setting to 
- increase performance, maybe even for just a short period of time (eg. high traffic app, writing logs which are not needed increases execution time with no benefit)
- support privacy policies / GDPR (eg. dont collect any personal data - access logs however contain an IP address and in case of GET requests maybe other personal data)

### How to solve

Add an option (like the [bind-address-ipv4](http://dokku.viewdocs.io/dokku/configuration/nginx/#binding-to-specific-addresses) or an environment variable) to toggle `access_log` and `error_log` in [nginx.conf](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil) from file-path to `/dev/null/`/`off`.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
