### ISSUE TITLE
Trying to add totally invalid buildpacks should give an error

### ISSUE THREAD

**Issue by jarthod** [dokku/dokku#3923]
When adding a buildpack URL using `buildpacks:add`, if the wrong number of arguments is passed (in my case because I was using dokku_client.sh it silently added the app name) and so I ended up with (shown with the application name for clarity here):
```
> dokku buildpacks:add suzaku ruby https://github.com/jarthod/heroku-buildpack-ruby.git
> dokku buildpacks:list suzaku
-----> suzaku buildpack urls
       ruby
```

So I though "ruby" was the name of the buildpack whereas in fact I was adding a buildpack with the URL "ruby". The `buildpacks:add` command should have refused this IMO, for any of these two reasons:
- wrong number of argument
- invalid URL.

**Comment by josegonzalez** [comment]
Pull request to validate them and and transform valid values to full github-backed buildpack urls is up, so closing this.

**Comment by jarthod** [comment]
So fast, thanks! :+1:
