### ISSUE TITLE
Update Dockerfile documentation to specify more information about ports

### ISSUE THREAD

**Issue by nahtnam** [dokku/dokku#3927]
## Description of problem

Currently, I feel as if anyone skimming the http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/#exposed-ports docs will miss the part at the end talking about exposing. Since there is no content other than a link, people will assume that it's supplementary information, however, it is still required to proxy the port 80 to whatever port you expose.

## Solution

I think a line like this:

```
dokku proxy:ports-set APP_NAME http:80:3000
```

should be added right above the link to signify that action is required for the app to work similarly to the buildpack method.

**Comment by josegonzalez** [comment]
I've been thinking about this for a while, and I think it's a bit odd to think that it's unnecessary to click through for more information (it's not like there is other documentation in that section).

That said, it does only say "for more information". I'll go through all the docs and expand that part of the sentence where it appears so it makes more sense in context. However, I don't agree that I should duplicate the docs as it makes it harder to remove stale docs and also lengthens documentation unnecessarily.
