### ISSUE TITLE
In some cases dokku doesn't set the expected value of environment variable 

### ISSUE THREAD

**Issue by amjedomar** [dokku/dokku#3938]
## Description of problem

In the following cases dokku doesn't set the expected value of environment variable

- I run this command `dokku config:set appname ENVNAME="!d3"` but I got this error `-bash: !d3: event not found`
- I run this command `dokku config:set appname ENVNAME="d!3"` however dokku set a different value `ddokku version`
- I also run this command `dokku config:set appname ENVNAME="d$3"` however dokku set a different value `d`

All of these problems happened when I was using version `0.19.13` and it keeps happening even when I upgraded to version `0.20.2`

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
I created server using the [official digitalocean dokku image](https://marketplace.digitalocean.com/apps/dokku) 

Then I upgrade it to version `0.20.2` via the bootstrap script
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.20.2/bootstrap.sh
sudo DOKKU_TAG=v0.20.2 bash bootstrap.sh
```

**Comment by josegonzalez** [comment]
This isn't related to Dokku, but how the shell works. Shells generally expand variables in double-quotes, so you will likely want to use single quote marks instead.
