### ISSUE TITLE
Ports in CHECKS not documented

### ISSUE THREAD

**Issue by viraptor** [dokku/dokku#3941]
## Description of problem

CHECKS file documentation does not describe how to set the check port.
It defaults to port 5000, even for an app which has:
```
DOKKU_PROXY_PORT:            80
DOKKU_PROXY_PORT_MAP:        http:80:6543
```
There's unfortunately nothing about the port on http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/

I see there's some kind of reference to ports in the checks functions, however it's not immediately clear how to set them.

**Comment by josegonzalez** [comment]
Can you provide a reproduction for the issue where we don't respect the port specified? I believe if your app uses buildpacks for app deploys, we automatically assume port 5000 (we inject that as the PORT environment variable) but not sure what will happen for Dockerfile support.

**Comment by josegonzalez** [comment]
As well, can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Closing as there hasn't been an update to the the original issue. If you can provide that information, I'll re-open and begin investigation. Thanks.
