### ISSUE TITLE
Install failed, believed to be because home directory inaccessible to root

### ISSUE THREAD

**Issue by asilano** [dokku/dokku#3944]
## Description of problem
Can't install dokku (using bootstrap script or apt package for Ubuntu) fails if root can't write to installing-user's home directory, for instance if the home directory is an access-restricted NFS mount.

After checking the slightly-fuller logs of `sudo dpkg --configure dokku`, it looks like the problem is caused by the installer trying to create  `~/.basher/`. Installation was able to proceed after manually creating `~/.basher/` and granting it world-write priveleges.

### How reproducible
Believed to be 100%; but difficult to say the root cause is as described because dpkg logs aren't descriptive of problems. I regret I don't have a spare system in the same state to try again.

### Steps to Reproduce

1. Fresh system with user's home directory inaccessible by root
2. within `~`, either run bootstrap script or via instructions in [Debian install instructions](http://dokku.viewdocs.io/dokku/getting-started/install/debian/)

#### Actual Results
`apt` package installation fails. dokku may be _partially_ installed - I believe the executable existed but none of the required plugins.

#### Expected Results
dokku installed correctly

### `dokku report APP_NAME` output

dokku did not install - no output.

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Install attempted by apt on Ubuntu 16.04 (so, by deb) on VMWare VM; home directory an access-restricted NFS4 mount.

**Comment by josegonzalez** [comment]
@asilano do you know how I would set this up?

> Fresh system with user's home directory inaccessible by root

**Comment by asilano** [comment]
I don't, I'm afraid. I believe it's somehow related to our home directories being an NFS4 mount - presumably the machine-local root can't access the mounted directories because it lacks permissions on the server hosting the mount.

I will see if my IT department is happy to share details of the setup for you.

**Comment by josegonzalez** [comment]
Alright if you can figure out how we can reliably reproduce this, I can try to solve the issue, otherwise I'll close the issue (and we can come back to it if someone can provide a repro in the future).

**Comment by josegonzalez** [comment]
Given that there hasn't been a documented way to repro the exact issue, I'm going to close this for now. If a repro is documented, I'm happy to reopen and figure out a way to fix it.

**Comment by asilano** [comment]
Yeah, that's fair. I haven't heard back from my IT dept. I'll update and re-open if they get back to me.
