### ISSUE TITLE
More than 100+ Domains SSL

### ISSUE THREAD

**Issue by AlexR1712** [dokku/dokku#3948]
Hi, I have a problem that I don't know how to address because from dokku it's not possible.

I have an app that has many domains, over 100.
But I cannot put ssl for domain of lets encrypts because it limits me up to 100 casually.

How I could do in a case like this? to put ssl to each domain by individual in such a case.

**Comment by josegonzalez** [comment]
Buy an SSL certificate - maybe a wildcard certificate? - that covers all your domains. There isn't any other way to get an SSL certificate past those limits (we don't offer SSL certificates either).
