### ISSUE TITLE
can't finish install (dokku plugin:install-dependencies --core)

### ISSUE THREAD

**Issue by hovancik** [dokku/dokku#3949]
## Description of problem
```
dokku plugin:install-dependencies --core
W: --force-yes is deprecated, use one of the options starting with --allow instead.
```
### Steps to Reproduce

1. `dokku plugin:install-dependencies --core`
2.
3.

#### Actual Results
`W: --force-yes is deprecated, use one of the options starting with --allow instead.`
#### Expected Results
install deps

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Debian 10, via Repo, on VPS

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by hovancik** [comment]
Hi @josegonzalez , when can I expect this to be released? 

Thanks for your work!

**Comment by josegonzalez** [comment]
You can expect this to be released when I make a release.

If you or your organization needs tighter turnaround for particular changes, feel free to [sponsor the project](https://github.com/dokku/.github/blob/master/SPONSORING.md).

Note: the install is actually done after this message, thats merely a warning.
