### ISSUE TITLE
Ubuntu 20.04 LTS support

### ISSUE THREAD

**Issue by vincelwt** [dokku/dokku#3961]
Ubuntu 20.04 Focal Fossa is out and is the new LTS release, supported until 2025. Having dokku support it would be neat, as most cloud providers will start providing the image very soon.

Thanks

**Comment by josegonzalez** [comment]
The existing packages for bionic _should_ work for Focal, but #3967 starts the publishing process for that platform, so we'll see how that goes :)

Note: For sanity reasons, I won't be supporting any non-LTS release of any OS. In theory, packages will work on those, but in practice, things might break (though pull requests will be welcome to fix such issues).

**Comment by josegonzalez** [comment]
Closing as there is a pull request open (this will be all ready for 0.21.0).

**Comment by migueltorrescosta** [comment]
Do we  know when 0.21.0 will be available?
