### ISSUE TITLE
dokku enter app not working

### ISSUE THREAD

**Issue by lmdc45** [dokku/dokku#3972]
Just updated from 0.19.3 to latest version 0.20.4

When running
`dokku enter app`
nothing happen.

I realized it is working fine running 
`dokku enter app web`

Noting I only have one single container type defined (web) and dokku enter app was working on 0.19.3

> Additionally, you can run enter with no container-type. If only a single container-type is defined in your app, you will be dropped into the only running container. This behavior is not supported when specifying a custom command; as described below.

[(as notified here)](https://github.com/dokku/dokku/blob/844b86840a7f32a4de1316c14c96339abfe3ca56/docs/deployment/one-off-processes.md#entering-existing-containers)

normal behaviour should be that 
`dokku enter app`
automatically select the web process if this is the only one (or maybe alert to notify a process name is required)

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by lmdc45** [comment]
Dokku was installed on an OVH vps with default install process from the doc bootstrap.sh

was installed with version 0.19.3 and then updated to 0.20.4

I was used to enter 'dokku enter app' so was surprised when not working after update. However when realizing it is just a matter of adding the process name it is not a big issue. However seems still not normal behavior so might worth having a look.

See below dokku report app:

`-----> uname: Linux XXXX 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           3853        1658         703          40        1491        1937
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           19.03.6
        API version:       1.40
        Go version:        go1.12.16
        Git commit:        369ce74a3c
        Built:             Thu Feb 13 01:27:58 2020
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          19.03.6
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.12.16
         Git commit:       369ce74a3c
         Built:            Thu Feb 13 01:26:32 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.2.13
         GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info:
       Client:
        Debug Mode: true

       Server:
        Containers: 43
         Running: 8
         Paused: 0
         Stopped: 35
        Images: 60
        Server Version: 19.03.6
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 4.19.0-8-cloud-amd64
        Operating System: Debian GNU/Linux 10 (buster)
        OSType: linux
        Architecture: x86_64
        CPUs: 1
WARNING: No swap limit support
        Total Memory: 3.763GiB
        Name: XXXX
        ID: RXPV:CC4P:YOCO:GNIF:UMKY:WGEE:LE47:BMKB:KY7Z:XAIH:HVRJ:RHZH
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> sigil version: 0.5.0
-----> herokuish version:
       herokuish: 0.5.12
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v215
         heroku-buildpack-nodejs    v170
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v169
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v173
         heroku-buildpack-go        v141
         buildpack-nginx            v13
-----> dokku version: dokku version 0.20.4
-----> dokku plugins:
       plugn: 0.3.2
         00_dokku-standard    0.20.4 enabled    dokku core standard plugin
         20_events            0.20.4 enabled    dokku core events logging plugin
         app-json             0.20.4 enabled    dokku core app-json plugin
         apps                 0.20.4 enabled    dokku core apps plugin
         builder-dockerfile   0.20.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.20.4 enabled    dokku core builder-herokuish plugin
         buildpacks           0.20.4 enabled    dokku core buildpacks plugin
         certs                0.20.4 enabled    dokku core certificate management plugin
         checks               0.20.4 enabled    dokku core checks plugin
         common               0.20.4 enabled    dokku core common plugin
         config               0.20.4 enabled    dokku core config plugin
         couchdb              1.10.1 enabled    dokku couchdb service plugin
         deployment-keys      0.2.0 enabled    Manage SSH deployment keys that should get injected into your containers on-build
         docker-options       0.20.4 enabled    dokku core docker-options plugin
         domains              0.20.4 enabled    dokku core domains plugin
         enter                0.20.4 enabled    dokku core enter plugin
         git                  0.20.4 enabled    dokku core git plugin
         hostkeys-plugin      0.2.1 enabled    Manage hostkeys (.ssh/known_hosts) in your container environment
         letsencrypt          0.9.2 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.20.4 enabled    dokku core logs plugin
         mongo                1.10.1 enabled    dokku mongo service plugin
         network              0.20.4 enabled    dokku core network plugin
         nginx-vhosts         0.20.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.20.4 enabled    dokku core plugin plugin
         postgres             1.10.0 enabled    dokku postgres service plugin
         proxy                0.20.4 enabled    dokku core proxy plugin
         ps                   0.20.4 enabled    dokku core ps plugin
         repo                 0.20.4 enabled    dokku core repo plugin
         resource             0.20.4 enabled    dokku core resource plugin
         rethinkdb            1.10.1 enabled    dokku rethinkdb service plugin
         scheduler-docker-local 0.20.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.20.4 enabled    dokku core shell plugin
         ssh-keys             0.20.4 enabled    dokku core ssh-keys plugin
         storage              0.20.4 enabled    dokku core storage plugin
         tags                 0.20.4 enabled    dokku core tags plugin
         tar                  0.20.4 enabled    dokku core tar plugin
         trace                0.20.4 enabled    dokku core trace plugin
=====> APP app information
       App deploy source:
       App dir:                       /home/dokku/APP
       App locked:                    false
=====> APP buildpacks information
       Buildpacks list:
CN = APP.dokku.me
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> APP ssl information
       Ssl dir:                       /home/dokku/APP/tls 
       Ssl enabled:                   true
       Ssl hostnames:                 dokku2.me APP.dokku.me
       Ssl expires at:                Jun  7 08:54:02 2020 GMT
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Mar  9 08:54:02 2020 GMT
       Ssl subject:                   subject=CN = APP.dokku.me
       Ssl verified:                  self signed
=====> APP checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> APP docker options information
       Docker options build:          --link dokku.couchdb.service:dokku-couchdb-service --link dokku.mongo.service:dokku-mongo-service --link dokku.rethinkdb.service:dokku-rethinkdb-service
       Docker options deploy:         --link dokku.couchdb.service:dokku-couchdb-service --link dokku.mongo.service:dokku-mongo-service --link dokku.rethinkdb.service:dokku-rethinkdb-service --restart=on-failure:10 -v /var/lib/dokku/data/storage/APP/Static:/app/Static -v /var/lib/dokku/data/storage/APP/static:/app/static -v /var/lib/dokku/data/storage/images:/app/Static/images
       Docker options run:            --link dokku.couchdb.service:dokku-couchdb-service --link dokku.mongo.service:dokku-mongo-service --link dokku.rethinkdb.service:dokku-rethinkdb-service -v /var/lib/dokku/data/storage/APP/Static:/app/Static -v /var/lib/dokku/data/storage/APP/static:/app/static -v /var/lib/dokku/data/storage/images:/app/Static/images       
=====> APP domains information
       Domains app enabled:           true
       Domains app vhosts:            APP.dokku.me dokku2.me
       Domains global enabled:        true
       Domains global vhosts:         dokku.me dokku2.me
=====> APP git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       1e9dcdf
=====> APP network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.8:5000
=====> APP nginx information
       Nginx access log path:         /var/log/nginx/APP-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx error log path:          /var/log/nginx/APP-error.log
       Nginx hsts:                    true
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
=====> APP proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> APP ps information
       Processes:                     1
       Deployed:                      true
       Running:                       true
       Restore:                       true
       Restart policy:                on-failure:10
       Ps can scale:                  true
       Status web.1:                  running    (CID: 600b1fe4f608)
=====> APP scheduler-docker-local information
       Scheduler docker local disable chown:
=====> APP storage information
       Storage build mounts:
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/APP/Static:/app/Static -v /var/lib/dokku/data/storage/APP/static:/app/static -v /var/lib/dokku/data/storage/images:/app/Static/images
       Storage run mounts:            -v /var/lib/dokku/data/storage/APP/Static:/app/Static -v /var/lib/dokku/data/storage/APP/static:/app/static -v /var/lib/dokku/data/storage/images:/app/Static/images`

**Comment by josegonzalez** [comment]
This will be fixed in the next release - and scheduler plugins will additionally be able to implement the enter command as well.
