### ISSUE TITLE
How to install Mailu with Dokku

### ISSUE THREAD

**Issue by dmp2tech** [dokku/dokku#3973]
Hello,
I would like install Mailu (mailu.io) with dokku. The problem is the docker-compose contain more container. I read the docs and i have see Procfile. That is possible use Procfile for deploy an image docker and link with app ?

Tank's for your response.
Best regardes
Didier

**Comment by josegonzalez** [comment]
Hi @dmp2tech 

As mentioned on [Slack](https://gliderlabs.slack.com/archives/C0FP0R13J/p1588715413329300), the general process for deploying mailu to Dokku is probably:

- Create the app (or git push if autocreation is enabled, which it is by default)
- Disable zero-downtime deploys (assuming it uses tcp/udp proxying, which our nginx implementation does not currently support).

If you'd like help with getting this deployed, you may consider sponsoring the work as outlined [here](https://github.com/dokku/.github/blob/master/SPONSORING.md).

The best place for questions like these is on Slack/IRC, or some other forum - unless there is a potential bug in Dokku, this isn't really a place for asking for help deploying a specific app. As such, I'll be closing this issue. Good luck.
