### ISSUE TITLE
Interpolate the domain in the CHECKS file

### ISSUE THREAD

**Issue by skorokithakis** [dokku/dokku#3974]
Currently the CHECKS file requires us to disable hostname checks in Django, as we can't hardcode the domain in it (the same repo is deployed to multiple hosts under different hostnames). It would be great if Dokku could interpolate the hostname, so the check would become:

```
//{HOSTNAME}/about/
```

Or something similar. The name could even be a setting, to avoid conflicts, though I can't see any.

**Comment by josegonzalez** [comment]
What would the hostname be if there are multiple domains associated with an app? Do we need to check each of them (yuck)?

**Comment by skorokithakis** [comment]
Could you allow interpolation of env vars into the CHECKS file? That way I could set a variable with the hostname and just interpolate that.

**Comment by josegonzalez** [comment]
Probably, but the best way to do that is via sigil. I think the config_export plugin can export in a KEY=VALUE pattern.

**Comment by skorokithakis** [comment]
Can you give me some more details on how I'd do that? I can't find that plugin on a search, or how a sigil can help.

**Comment by josegonzalez** [comment]
Sigil isn't a plugin, its a templating tool we use inside of Dokku (typically for nginx config files).

Probably would want to add the templating around [here](https://github.com/dokku/dokku/blob/0c388615cc6d51f2e80ace3e77fa6b3b42a5df7c/plugins/scheduler-docker-local/check-deploy#L83).

**Comment by skorokithakis** [comment]
> I think the config_export plugin can export in a KEY=VALUE pattern.

I was talking about this plugin. You mean exporting from config and then passing the results to sigil for rendering? That makes sense to me.

**Comment by josegonzalez** [comment]
`config_export` is a function that you can source from the `config/functions` file. It takes a format argument, and one of the possible values gives the KEY=VALUE pattern.

**Comment by AubreyHewes** [comment]
@skorokithakis Can't you just `CHECK` for a generic value within the deployed app's index page?

i.e. 
```
/ my-generic-value
```

Possibly I do not understand what you are trying to do.

Though in my experience even the same repo deployed hundreds of times (using different configs) has at least one bit of generic string on the index page that can be checked (as it is all the same codebase)..  i.e. has a "<script" (most errors do not have that)..

**Comment by skorokithakis** [comment]
@AubreyHewes No, this is about the hostname part being interpolated, not the text check.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
