### ISSUE TITLE
Node.js and Dokku: How to recover from app crashes?

### ISSUE THREAD

**Issue by arechsteiner** [dokku/dokku#398]
I finally have my Dokku server running on DigitalOcean and can deploy my Node.js app to it. My procfile looks like this:

```
web: node app.js
```

The problem with this is that once my app crashes for some reason, it won't restart. One solution would be to use the npm package called [Forever](https://npmjs.org/package/forever). This however is a package that needs to be installed globally using the -g tag.

I'm not sure how to go about this in Dokku since it installs dependencies through package.json. Would I need to manually install this package on the Docker container or is there another solution?

Or maybe there is a better way to recover from crashes when using Dokku altogether?

**Comment by Sadmansamee** [comment]
how can I use pm2 with dokku?

**Comment by josegonzalez** [comment]
Please don't comment on a 2 year old issue. If you're looking for support, please go to our slack or irc channels, which are linked to in our readme and in the documentation.
