### ISSUE TITLE
Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dcalixto** [dokku/dokku#3984]
after setup Dokku and the app and install the libvips on the pc, i added the https://github.com/brandoncc/heroku-buildpack-vips on the buldpacks to the app. 
But, right after the dokku push in the logs show:

> Could not open library 'libvips.so.42': libvips.so.42: cannot open
> shared object file: No such file or directory

So after some research the author of ruby-libvips pointed a path issue related. 

And check on the ubuntu 18.04 seems the **/usr/local/vips** is empty

Someone please can clarify what's is missing on using the libvips buildback on dokku?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/ip7Ce.png

**Comment by josegonzalez** [comment]
This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). 

Issues pertaining to buildpacks will be closed and/or locked.
