### ISSUE TITLE
How to resolve the hostname of the apps on the same network?

### ISSUE THREAD

**Issue by boramalper** [dokku/dokku#3995]
Hi,

I used `dokku network:*` to create a bridge and put my apps on the newly created network. Then I issued `network:rebuild` commands for each of those apps to bring their network configuration up to date.

My issue is that when I try (`curl http://<app-name>`) to access one container from another, it simply doesn't work. But when I use the IP address reported by `network:report <app>`, it does work so I presume the issue is with resolving the hostnames to IP addresses.

In "plain" Docker the hostname is the name of the container, so I tried that as well (e.g. `<app>.web.1`) which did not work either.

So if I try to access the web app `extractor` from `dashboard`, which hostname shall I use?

**Comment by josegonzalez** [comment]
This was previously documented on the network-management page, but I've clarified and expanded the documentation [here](http://dokku.viewdocs.io/dokku/networking/network/#network-aliases).

In short, the network alias should be `app.process-type`, and you need to also specify the port.

**Comment by boramalper** [comment]
Thanks!
