### ISSUE TITLE
`ps:inspect` concatenates container ids internally

### ISSUE THREAD

**Issue by msbit** [dokku/dokku#4015]
### Description of problem

When running `ps:inspect` for an app that is comprised of multiple containers, the container IDs are incorrectly concatenated.

From my testing, it looks like, https://github.com/dokku/dokku/blob/0c388615cc6d51f2e80ace3e77fa6b3b42a5df7c/plugins/scheduler-docker-local/scheduler-inspect#L49 should be replaced with:

`CIDS+=("$(<"$DOKKU_ROOT/$APP/$CONTAINER_FILE")")`

Note the additional set of parentheses around the value to add, as per https://linuxize.com/post/bash-arrays/#add-a-new-element

### How reproducible

For an app that is comprised of multiple containers, eg multiple entries in the `Procfile`

### Steps to Reproduce

1. `ssh dokku@<cluster> ps:inspect <app>`

#### Actual Results

```
[]
Error: No such container: cb8ca0f2e5638fc8f1afd7d1f05cced6ab63bb2522a950be1d3a45a041762cb06104d775eb8dc4b73d023df7d2f5091bd3ef1aa9ca9bee7547a4d82e61b90cd489c702561b3aed92099713627172c3f2a884d0175a74edba51d6575725923880
```

#### Expected Results

```
[...<docker inspect information>...]
```

**Comment by josegonzalez** [comment]
Good catch. Would you be able to file a pull request?

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
