### ISSUE TITLE
Nginx.conf.sigil file not found by Dokku?

### ISSUE THREAD

**Issue by Nezia1** [dokku/dokku#4017]
## Description of problem
I'm trying to push deploy a Vue.JS app with custom Nginx settings since I'm using history mode, I need to edit some lines of the Nginx config but I can't figure out how to do it. I've copied it to the Docker container but it doesn't seem to work?

### How reproducible
Easily reproducible. A single app with a custom nginx.conf.sigil file.

### Steps to Reproduce

1. Create an app with `dokku apps:create rss`
2. Run `git remote add dokku dokku@dokku-ip:rss` on the repo you want to push to (a Vue.JS application with history mode on generated with Vue CLI 3)
3. Push the app with the nginx.conf.sigil file and a Dockerfile (cf. down below)
4. Access the app with the domain name assigned to it

#### Actual Results
`dokku nginx:show-config rss` should return the custom config I wrote into nginx.conf.sigil
#### Expected Results
`dokku nginx:show-config rss` returns the default config

### `dokku report rss` output

-----> uname: Linux nezia 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:            985         237         280           0         467         592
       Swap:             0           0           0
-----> docker version:
       Client:
        Version:           18.09.6
        API version:       1.39
        Go version:        go1.10.8
        Git commit:        481bc77
        Built:             Sat May  4 02:35:57 2019
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          18.09.6
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.8
         Git commit:       481bc77
         Built:            Sat May  4 01:59:36 2019
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info:
       Containers: 3
        Running: 3
        Paused: 0
        Stopped: 0
       Images: 63
       Server Version: 18.09.6
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
       runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-52-generic
       Operating System: Ubuntu 18.04.2 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 985.5MiB
       Name: nezia
       ID: CEZV:RF6X:TOFX:EVTY:MA5T:C2FC:4TYG:WAWF:YQPF:MRAE:KGJH:AH7G
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine

-----> sigil version: 0.6.0
-----> herokuish version:
       herokuish: 0.5.14
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v215
         heroku-buildpack-nodejs    v171
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v170
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v176
         heroku-buildpack-go        v142
         buildpack-nginx            v13
-----> dokku version: dokku version 0.20.4
-----> dokku plugins:
       plugn: 0.5.0
         00_dokku-standard    0.20.4 enabled    dokku core standard plugin
         20_events            0.20.4 enabled    dokku core events logging plugin
         app-json             0.20.4 enabled    dokku core app-json plugin
         apps                 0.20.4 enabled    dokku core apps plugin
         builder-dockerfile   0.20.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.20.4 enabled    dokku core builder-herokuish plugin
         buildpacks           0.20.4 enabled    dokku core buildpacks plugin
         certs                0.20.4 enabled    dokku core certificate management plugin
         checks               0.20.4 enabled    dokku core checks plugin
         common               0.20.4 enabled    dokku core common plugin
         config               0.20.4 enabled    dokku core config plugin
         docker-options       0.20.4 enabled    dokku core docker-options plugin
         domains              0.20.4 enabled    dokku core domains plugin
         enter                0.20.4 enabled    dokku core enter plugin
         git                  0.20.4 enabled    dokku core git plugin
         letsencrypt          0.9.3 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.20.4 enabled    dokku core logs plugin
         network              0.20.4 enabled    dokku core network plugin
         nginx-vhosts         0.20.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.20.4 enabled    dokku core plugin plugin
         proxy                0.20.4 enabled    dokku core proxy plugin
         ps                   0.20.4 enabled    dokku core ps plugin
         repo                 0.20.4 enabled    dokku core repo plugin
         resource             0.20.4 enabled    dokku core resource plugin
         scheduler-docker-local 0.20.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.20.4 enabled    dokku core shell plugin
         ssh-keys             0.20.4 enabled    dokku core ssh-keys plugin
         storage              0.20.4 enabled    dokku core storage plugin
         tags                 0.20.4 enabled    dokku core tags plugin
         tar                  0.20.4 enabled    dokku core tar plugin
         trace                0.20.4 enabled    dokku core trace plugin
=====> rss app information
       App deploy source:
       App dir:                       /home/dokku/rss
       App locked:                    false
=====> rss buildpacks information
       Buildpacks list:
CN = rss.nezia.xyz
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> rss ssl information
       Ssl dir:                       /home/dokku/rss/tls
       Ssl enabled:                   true
       Ssl hostnames:                 rss.nezia.xyz
       Ssl expires at:                Sep 12 12:47:13 2020 GMT
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Jun 14 12:47:13 2020 GMT
       Ssl subject:                   subject=CN = rss.nezia.xyz
       Ssl verified:                  self signed
=====> rss checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> rss docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> rss domains information
       Domains app enabled:           true
       Domains app vhosts:            rss.nezia.xyz
       Domains global enabled:        true
       Domains global vhosts:         nezia.xyz
=====> rss git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       6509e78
=====> rss network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.4:80
=====> rss nginx information
       Nginx access log path:         /var/log/nginx/rss-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx error log path:          /var/log/nginx/rss-error.log
       Nginx hsts:                    true
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
=====> rss proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:80 https:443:80
       Proxy type:                    nginx
=====> rss ps information
       Processes:                     1
       Deployed:                      true
       Running:                       true
       Restore:                       true
       Restart policy:                on-failure:10
       Ps can scale:                  true
       Status web.1:                  running    (CID: 2ee51293eb63)
=====> rss scheduler-docker-local information
       Scheduler docker local disable chown:
=====> rss storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
It was installed on DigitalOcean via the one-click installer.

### Additional information

- Vue.JS application
- Dockerfile: 
```docker
FROM node:lts-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM nginx:stable-alpine as production
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by josegonzalez** [comment]
Your last image layer - starting with `production` - doesn't have the `nginx.conf.sigil` in it's workdir (the workdir seems like it might be `/usr/share/nginx/html`, but I'd have to check on that `nginx:stable-alpine` image). We only copy the file from the generated image, not any intermediate ones.

Hope that helps.

**Comment by Nezia1** [comment]
I've tried changing my nginx.conf.sigil to add it to the workdir like so:
```docker
FROM node:lts-alpine as builder
WORKDIR /app
COPY package*.json ./
ADD nginx.conf.sigil ./
RUN npm install
COPY . .
RUN npm run build
FROM nginx:stable-alpine as production
WORKDIR /usr/app
COPY --from=builder /app/nginx.conf.sigil /usr/app
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```
Still not working. Any insight on this?

**Comment by josegonzalez** [comment]
Can you post the logs for a deploy with that last Dockerfile?

**Comment by Nezia1** [comment]
````
remote: -----> Cleaning up...
remote: -----> Building rss from dockerfile...
remote: -----> Setting config vars
remote:        DOKKU_DOCKERFILE_PORTS:  80
remote: -----> Setting config vars
remote:        DOKKU_DOCKERFILE_CMD:  CMD ["nginx", "-g", "daemon off;"]
remote: Sending build context to Docker daemon  560.6kB
remote: Step 1/16 : FROM node:lts-alpine as builder
remote:  ---> 1c342643aa5c
remote: Step 2/16 : WORKDIR /app
remote:  ---> Using cache
remote:  ---> 7a0c8d26c762
remote: Step 3/16 : COPY package*.json ./
remote:  ---> Using cache
remote:  ---> 8f60bd4e6db4
remote: Step 4/16 : ADD nginx.conf.sigil ./
remote:  ---> Using cache
remote:  ---> 8dbcf849a532
remote: Step 5/16 : RUN npm install
remote:  ---> Using cache
remote:  ---> 360865a61e13
remote: Step 6/16 : COPY . .
remote:  ---> ee6e24473c39
remote: Step 7/16 : RUN npm run build
remote:  ---> Running in edfe105dffd5
remote: 
remote: > rss-reader@0.1.0 build /app
remote: > vue-cli-service build
remote:
remote: 
remote: -  Building for production...
remote:  WARNING  Compiled with 2 warnings7:05:21 PM
remote:
remote:  warning
remote:
remote: asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
remote: This can impact web performance.
remote: Assets:
remote:   css/app.e3d43094.css (365 KiB)
remote:   js/chunk-vendors.635861e0.js (594 KiB)
remote:
remote:  warning
remote:
remote: entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.     
remote: Entrypoints:
remote:   app (965 KiB)
remote:       js/chunk-vendors.635861e0.js
remote:       css/app.e3d43094.css
remote:       js/app.e3213a15.js
remote:
remote:
remote:   File                                 Size               Gzipped
remote:
remote:   dist/js/chunk-vendors.635861e0.js    593.91 KiB         169.88 KiB
remote:   dist/js/about.2728168c.js            5.84 KiB           2.13 KiB
remote:   dist/js/app.e3213a15.js              5.64 KiB           2.50 KiB
remote:   dist/css/app.e3d43094.css            365.44 KiB         43.74 KiB
remote:
remote:   Images and other types of assets omitted.
remote:
remote:  DONE  Build complete. The dist directory is ready to be deployed.
remote:  INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
remote:
remote: Removing intermediate container edfe105dffd5
remote:  ---> 3bc640aa8b93
remote: Step 8/16 : FROM nginx:stable-alpine as production
remote:  ---> ab94f84cc474
remote: Step 9/16 : WORKDIR /usr/app
remote:  ---> Running in 3d58370cbfa8
remote: Removing intermediate container 3d58370cbfa8
remote:  ---> 8122c6f72115
remote: Step 10/16 : COPY --from=builder /app/nginx.conf.sigil /usr/app
remote:  ---> e4ac63f6f00f
remote: Step 11/16 : COPY --from=builder /app/dist /usr/share/nginx/html
remote:  ---> 8201470357b1
remote: Step 12/16 : EXPOSE 80
remote:  ---> Running in 75cbda16818d
remote: Removing intermediate container 75cbda16818d
remote:  ---> 9e8d5d9ba03c
remote: Step 13/16 : CMD ["nginx", "-g", "daemon off;"]
remote:  ---> Running in c1600284912f
remote: Removing intermediate container c1600284912f
remote:  ---> 70c9677ceaad
remote: Step 14/16 : LABEL dokku=
remote:  ---> Running in 7e20b5122518
remote: Removing intermediate container 7e20b5122518
remote:  ---> 3ab9b51bdd4e
remote: Step 15/16 : LABEL org.label-schema.schema-version=1.0
remote:  ---> Running in ed981eeb7c23
remote: Removing intermediate container ed981eeb7c23
remote:  ---> 18a884f59c0c
remote: Step 16/16 : LABEL org.label-schema.vendor=dokku
remote:  ---> Running in 1329e175bfee
remote: Removing intermediate container 1329e175bfee
remote:  ---> f5da875098cd
remote: Successfully built f5da875098cd
remote: Successfully tagged dokku/rss:latest
remote: -----> Releasing rss (dokku/rss:latest)...
remote: -----> Deploying rss (dokku/rss:latest)...
remote: -----> No Procfile found in app image
remote:        DOKKU_SCALE declares scale -> web=1
remote: =====> Processing deployment checks
remote:        No CHECKS file found. Simple container checks will be performed.
remote:        For more efficient zero downtime deployments, create a CHECKS file. See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
remote: -----> Attempting pre-flight checks (web.1)
remote:        Waiting for 10 seconds ...
remote:        Default container check successful!
remote: -----> Running post-deploy
remote: -----> Overriding default nginx.conf with detected nginx.conf.sigil
remote: -----> Configuring rss.nezia.xyz...(using app-supplied template)
remote: -----> Creating https nginx.conf
remote:        Enabling HSTS
remote:        Reloading nginx
remote: -----> Renaming containers
remote:        Found previous container(s) (a6eb6415f65f) named rss.web.1
remote:        Renaming container (a6eb6415f65f) rss.web.1 to rss.web.1.1592334358
remote:        Renaming container (7ed84a508014) elastic_ptolemy to rss.web.1
remote: -----> Shutting down old containers in 60 seconds
remote:        a6eb6415f65fd2f107d4e6fd3f8e4068143b85a51be0642e483962419735a929
remote: =====> Application deployed:
remote:        http://rss.nezia.xyz
remote:        https://rss.nezia.xyz
remote:
To www.nezia.xyz:rss
   6f78aca..c25bfc2  master -> master
```

**Comment by josegonzalez** [comment]
```
remote: -----> Overriding default nginx.conf with detected nginx.conf.sigil
remote: -----> Configuring rss.nezia.xyz...(using app-supplied template)
```

That to me says that it's pulling your nginx.conf.sigil for the templating. Why do you say its not using it?

**Comment by Nezia1** [comment]
Because I added the line `    try_files $uri $uri/ /index.html` under location / and when i pull the config with `docker:show-config` it's not showing my line. I tried using grep to find it but it's not here.

**Comment by josegonzalez** [comment]
Can you show the output of the following two commands?

```shell
# from your local repository on the branch being pushed
cat nginx.conf.sigil

# from the server on which dokku is installed
# assuming your app name is called rss
dokku nginx:show-config rss
```

**Comment by Nezia1** [comment]
`cat nginx.conf.sigil`
```
{{ range $port_map := .PROXY_PORT_MAP | split " " }}
{{ $port_map_list := $port_map | split ":" }}       
{{ $scheme := index $port_map_list 0 }}
{{ $listen_port := index $port_map_list 1 }}
{{ $upstream_port := index $port_map_list 2 }}

{{ if eq $scheme "http" }}
server {
  listen      [{{ $.NGINX_BIND_ADDRESS_IP6 }}]:{{ $listen_port }};
  listen      {{ if $.NGINX_BIND_ADDRESS_IP4 }}{{ $.NGINX_BIND_ADDRESS_IP4 }}:{{end}}{{ $listen_port }};
  {{ if $.NOSSL_SERVER_NAME }}server_name {{ $.NOSSL_SERVER_NAME }}; {{ end }}
  access_log  {{ $.NGINX_ACCESS_LOG_PATH }};
  error_log   {{ $.NGINX_ERROR_LOG_PATH }};
{{ if (and (eq $listen_port "80") ($.SSL_INUSE)) }}
  return 301 https://$host:{{ $.PROXY_SSL_PORT }}$request_uri;
{{ else }}
  location    / {
    try_files $uri $uri/ /index.html;
    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://{{ $.APP }}-{{ $upstream_port }};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include {{ $.DOKKU_ROOT }}/{{ $.APP }}/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;        
  location /400-error.html {
    root {{ $.DOKKU_LIB_ROOT }}/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root {{ $.DOKKU_LIB_ROOT }}/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root {{ $.DOKKU_LIB_ROOT }}/data/nginx-vhosts/dokku-errors;
    internal;
  }
{{ end }}
}
{{ else if eq $scheme "https"}}
server {
  listen      [{{ $.NGINX_BIND_ADDRESS_IP6 }}]:{{ $listen_port }} ssl {{ if eq $.HTTP2_SUPPORTED "true" }}http2{{ else if eq $.SPDY_SUPPORTED "true" }}spdy{{ end }};
  listen      {{ if $.NGINX_BIND_ADDRESS_IP4 }}{{ $.NGINX_BIND_ADDRESS_IP4 }}:{{end}}{{ $listen_port }} ssl {{ if eq $.HTTP2_SUPPORTED "true" }}http2{{ else 
if eq $.SPDY_SUPPORTED "true" }}spdy{{ end }};
  {{ if $.SSL_SERVER_NAME }}server_name {{ $.SSL_SERVER_NAME }}; {{ end }}
  {{ if $.NOSSL_SERVER_NAME }}server_name {{ $.NOSSL_SERVER_NAME }}; {{ end }}
  access_log  {{ $.NGINX_ACCESS_LOG_PATH }};
  error_log   {{ $.NGINX_ERROR_LOG_PATH }};

  ssl_certificate           {{ $.APP_SSL_PATH }}/server.crt;
  ssl_certificate_key       {{ $.APP_SSL_PATH }}/server.key;
  ssl_protocols             TLSv1.2 {{ if eq $.TLS13_SUPPORTED "true" }}TLSv1.3{{ end }};
  ssl_prefer_server_ciphers off;

  keepalive_timeout   70;
  {{ if and (eq $.SPDY_SUPPORTED "true") (ne $.HTTP2_SUPPORTED "true") }}add_header          Alternate-Protocol  {{ $.PROXY_SSL_PORT }}:npn-spdy/2;{{ end }} 

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://{{ $.APP }}-{{ $upstream_port }};
    {{ if eq $.HTTP2_PUSH_SUPPORTED "true" }}http2_push_preload on; {{ end }}
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include {{ $.DOKKU_ROOT }}/{{ $.APP }}/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;        
  location /400-error.html {
    root {{ $.DOKKU_LIB_ROOT }}/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root {{ $.DOKKU_LIB_ROOT }}/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root {{ $.DOKKU_LIB_ROOT }}/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 502 /502-error.html;
  location /502-error.html {
    root {{ $.DOKKU_LIB_ROOT }}/data/nginx-vhosts/dokku-errors;
    internal;
  }
}
{{ else if eq $scheme "grpc"}}
{{ if eq $.GRPC_SUPPORTED "true"}}{{ if eq $.HTTP2_SUPPORTED "true"}}
server {
  listen      [{{ $.NGINX_BIND_ADDRESS_IP6 }}]:{{ $listen_port }} http2;
  listen      {{ if $.NGINX_BIND_ADDRESS_IP4 }}{{ $.NGINX_BIND_ADDRESS_IP4 }}:{{end}}{{ $listen_port }} http2;
  {{ if $.NOSSL_SERVER_NAME }}server_name {{ $.NOSSL_SERVER_NAME }}; {{ end }}
  access_log  {{ $.NGINX_ACCESS_LOG_PATH }};
  error_log   {{ $.NGINX_ERROR_LOG_PATH }};
  location    / {
    grpc_pass  grpc://{{ $.APP }}-{{ $upstream_port }};
  }
  include {{ $.DOKKU_ROOT }}/{{ $.APP }}/nginx.conf.d/*.conf;
}
{{ end }}{{ end }}
{{ else if eq $scheme "grpcs"}}
{{ if eq $.GRPC_SUPPORTED "true"}}{{ if eq $.HTTP2_SUPPORTED "true"}}
server {
  listen      [{{ $.NGINX_BIND_ADDRESS_IP6 }}]:{{ $listen_port }} ssl http2;
  listen      {{ if $.NGINX_BIND_ADDRESS_IP4 }}{{ $.NGINX_BIND_ADDRESS_IP4 }}:{{end}}{{ $listen_port }} ssl http2;
  {{ if $.NOSSL_SERVER_NAME }}server_name {{ $.NOSSL_SERVER_NAME }}; {{ end }}
  access_log  {{ $.NGINX_ACCESS_LOG_PATH }};
  error_log   {{ $.NGINX_ERROR_LOG_PATH }};

  ssl_certificate           {{ $.APP_SSL_PATH }}/server.crt;
  ssl_certificate_key       {{ $.APP_SSL_PATH }}/server.key;
  ssl_protocols             TLSv1.2 {{ if eq $.TLS13_SUPPORTED "true" }}TLSv1.3{{ end }};
  ssl_prefer_server_ciphers off;

  location    / {
    grpc_pass  grpc://{{ $.APP }}-{{ $upstream_port }};
  }
  include {{ $.DOKKU_ROOT }}/{{ $.APP }}/nginx.conf.d/*.conf;
}
{{ end }}{{ end }}
{{ end }}
{{ end }}

{{ if $.DOKKU_APP_WEB_LISTENERS }}
{{ range $upstream_port := $.PROXY_UPSTREAM_PORTS | split " " }}
upstream {{ $.APP }}-{{ $upstream_port }} {
{{ range $listeners := $.DOKKU_APP_WEB_LISTENERS | split " " }}
{{ $listener_list := $listeners | split ":" }}
{{ $listener_ip := index $listener_list 0 }}
  server {{ $listener_ip }}:{{ $upstream_port }};{{ end }}
}
{{ end }}{{ end }}
```

`dokku nginx:show-config rss`
```
server {
  listen      [::]:80;
  listen      80;
  server_name rss.nezia.xyz;
  access_log  /var/log/nginx/rss-access.log;
  error_log   /var/log/nginx/rss-error.log;

  return 301 https://$host:443$request_uri;

}

server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;

  server_name rss.nezia.xyz;
  access_log  /var/log/nginx/rss-access.log;
  error_log   /var/log/nginx/rss-error.log;

  ssl_certificate           /home/dokku/rss/tls/server.crt;
  ssl_certificate_key       /home/dokku/rss/tls/server.key;
  ssl_protocols             TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  keepalive_timeout   70;


  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://rss-80;
    http2_push_preload on;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/rss/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 502 /502-error.html;
  location /502-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }
}

upstream rss-80 {

  server 172.17.0.4:80;
}
```

**Comment by Nezia1** [comment]
Any idea why it's not functioning? Did I write something wrong?

**Comment by josegonzalez** [comment]
The `try_files` directive was added only to the `http` stanza, as an else to the check on whether ssl is in use. Thus, we only add the `return 301` there, as expected.

You'll also need to add that `try_files` directive to the https stanza as well.

If you need more help structuring your `nginx.conf.sigil`, feel free to join our [slack or irc](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/) (both are linked) for more help.
