### ISSUE TITLE
Exit code for non-deployed apps check should be consistent

### ISSUE THREAD

**Issue by philm** [dokku/dokku#4033]
###  Description of problem

Various commands check whether an app has been deployed. In some places, this is treated as a failure (with an exit code of 1), e.g.

https://github.com/dokku/dokku/blob/0c388615cc6d51f2e80ace3e77fa6b3b42a5df7c/plugins/logs/subcommands/default#L16

In other places, it is a warning (exit code of 0), e.g.

https://github.com/dokku/dokku/blob/0c388615cc6d51f2e80ace3e77fa6b3b42a5df7c/plugins/ps/subcommands/rebuild#L18

### Recommended Change

After searching for all instances of when the deployment check occurs (https://github.com/dokku/dokku/search?q=%22App+%24APP+has+not+been+deployed%22&unscoped_q=%22App+%24APP+has+not+been+deployed%22) it seems like using _dokku_log_fail_ throughout should be okay.

This enhancement will provide consistency in custom scripts that need to be able to handle non-running app states.

Thanks!

**Comment by josegonzalez** [comment]
I don't think thats necessarily correct. In some cases, we'll restart the app after setting a property - like a config value. I don't think we should exit non-zero in those cases.

If anything, more should move to warn + exit 0. It's not necessarily an error to _not_ be deployed, just that certain functionality won't actually do anything.

**Comment by josegonzalez** [comment]
Another good example - if the app hasn't been deployed and you call `ps:stop` on it, should you exit 0 or 1? The app isn't running, which was the desired output.

**Comment by philm** [comment]
Good points - missed those scenarios.
