### ISSUE TITLE
Dokku Setup main page doesn't show up after installation in CentOS

### ISSUE THREAD

**Issue by zzxwill** [dokku/dokku#4049]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you'd like to sponsor specific functionality, see the project's [Sponsoring](https://github.com/dokku/.github/blob/master/SPONSORING.md) document.
>
> If you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). Issues pertaining to buildpacks may be closed and locked.
>
> If you need support for a version of Dokku that is more than a year old, your issue may be closed without an answer. Please upgrade to a recent version.

## Description of problem
Dokku Setup main page doesn't show up after installation in CentOS

### Steps to Reproduce

1. http://dokku.viewdocs.io/dokku/getting-started/installation/#1-install-dokku
2. Check the ip in Chrome
3.

#### Actual Results
![image](https://user-images.githubusercontent.com/2805315/86874529-20f9c280-c113-11ea-962c-f492e9509ca7.png)

#### Expected Results
![image](https://user-images.githubusercontent.com/2805315/86874553-2820d080-c113-11ea-88fb-a431ba4a8785.png)

<-- Please replace APP_NAME with the name of your app -->

### `dokku report APP_NAME` output
```
[root@iZj6carqlu05piipfal1vnZ ~]# dokku report
 !     `report` is not a dokku command.
 !     See `dokku help` for a list of available commands.
```
> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> In these cases, you may run `dokku report` without any arguments to display the top-level reporting information.

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
In a VirtualMachine in Alibaba Cloud.
### Additional information

```
# uname -a
Linux iZj6carqlu05piipfal1vnZ 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Container Inspect Output (if applicable) via `dokku ps:inspect APP_NAME`
- The nginx configuration (if applicable) via `dokku nginx:show-config APP_NAME`
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
Yeah I’m not going to do this. In fact, there is an issue to replace this with a prompt to set things up from SSH instead (mobile so not easy to link to), as plenty of users forget this is there and then get hacked because of it.

Closing this for now, but thanks for filing it :)

**Comment by zzxwill** [comment]
Are you still on mobile? Could you please help append the link?

**Comment by josegonzalez** [comment]
https://github.com/dokku/dokku/issues/2247
