### ISSUE TITLE
dokku-installer.py creates VHOST file owned by root:root

### ISSUE THREAD

**Issue by hugopeixoto** [dokku/dokku#4052]
## Description of problem

When setting up through the dokku-installer, `/home/dokku/VHOST` ends up owned by `root:root`. This makes subsequent calls to `dokku domains:set-global` fail, with a permission denied error.

### Steps to Reproduce

1. Install dokku via the recommended way (wget & bash)
2. fill in every field in the setup page, including a hostname and ticking the virtualhost checkbox
3. Run `dokku domains:set-global something` 

I have worked around this by chowning the file to `dokku:dokku`.

```
root@carrot:~# dokku domains:set-global carrot.hugopeixoto.net
touch: cannot touch '/home/dokku/VHOST': Permission denied

root@carrot:~# ls -lah /home/dokku/VHOST
-rw-r--r-- 1 root root 22 Jul 12 02:25 /home/dokku/VHOST

root@carrot:~# chown dokku:dokku /home/dokku/VHOST
root@carrot:~# dokku domains:set-global carrot.hugopeixoto.net
-----> Set carrot.hugopeixoto.net
```

I think that the fix is adding a `os.chown` here:

https://github.com/dokku/dokku/blob/master/contrib/dokku-installer.py#L150

I'm not sure if the user is configurable, though, or if it can be hardcoded to `dokku`.

**Comment by hugopeixoto** [comment]
I was working on a fix for this, but I'm unable to install dokku from master in a debian system.

I haven't found the cause for that yet, but I noticed that you [plan on deprecating the web installer](https://github.com/dokku/dokku/issues/2247).

Maybe I should help out there instead. Let me know if you want me to try and fix this anyway.

**Comment by gridsystem** [comment]
I have run into this today on a clean install of the digitalocean droplet.

Possibly because the dokku droplet installs a version which still has this issue, and it persists after `apt-get upgrade`.
