### ISSUE TITLE
Change `dpkg-handling` to always set `VHOST` regardless of whether it exists

### ISSUE THREAD

**Issue by ltalirz** [dokku/dokku#4065]
This has been moved over from https://github.com/dokku/ansible-dokku/issues/19

@isundaylee writes:

> I just ran into this issue today. I did a little digging. Currently `ansible-dokku` relies on the `dpkg` configuration routine to set `VHOST` and `HOSTNAME`. However:
> 
> 1. `dpkg` will only set `VHOST` if it doesn't exist: https://github.com/dokku/dokku/blob/dd7d1d2f8d153b634527efc2d32d761bcc26b9b6/debian/postinst#L125
> 2. Earlier in the process, `dpkg` will set up the plugins. In particular, the `00_dokku-standard` plugin will create the `VHOST` file if it doesn't exist by copying over the `HOSTNAME` file: https://github.com/dokku/dokku/blob/dd7d1d2f8d153b634527efc2d32d761bcc26b9b6/plugins/00_dokku-standard/install#L9
> 3. As a result, `dpkg` will never set `VHOST` to the value we want.
> 
> Should we change `dpkg-handling` to always set `VHOST` regardless of whether it exists? This is what it currently does for `HOSTNAME`.
> 

@josegonzalez writes
> Yeah that makes sense to me.

**Comment by josegonzalez** [comment]
In the domains plugin, should we update the debconf value (this may require root) when manipulating the global domain? There can be more than 1 global domain, and they are newline delimited, so how should that be handled?

**Comment by josegonzalez** [comment]
I think the easier fix is to move the `dpkg-handling` up a bit in the `postinst`. The `plugin:install` check will be there as a fallback.

**Comment by josegonzalez** [comment]
Closing as there is an open pull request.
