### ISSUE TITLE
Documentation does not support SSL.

### ISSUE THREAD

**Issue by pawurb** [dokku/dokku#4070]
Apparently https://viewdocs.io/ does not support and will not support SSL https://github.com/progrium/viewdocs/issues/54 

Documentation without SSL looks a bit unprofessional for a project like Dokku and might discourage potential users. Maybe migrating docs to other service would be possible. I'm happy to help here.

Would https://readthedocs.org/ work?

**Comment by josegonzalez** [comment]
I'd love to do this, but have no real interest in using a system I don't have access to. Ideally we own the dokku.com domain and install something on a real server that we can better iterate on.

This is blocked on having access to the domain name, and I've already contacted @progrium to get access to it, which will allow us to do this and other work.

**Comment by hugopeixoto** [comment]
I worked on a solution that would enable viewdocs.io to work with SSL:

https://github.com/progrium/viewdocs/pull/56
https://github.com/progrium/viewdocs/issues/55

Maybe we can push in that direction?

**Comment by pawurb** [comment]
@hugopeixoto this is backwards incompatible change that would cause Dokku to loose all it's backlinks (over 6k according to ahrefs.com) and organic Google traffic:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/1131944/87823186-24a7ea80-c873-11ea-8e5c-f63c2799a5db.png">

Looks like viewdocs is using DNSimple for DNS. Wildcard certificate compatible with Heroku will cost $100/year. As long as @josegonzalez can get accesses it might be the best solution.

**Comment by josegonzalez** [comment]
Oh wait, heroku supports wildcard certs?

**Comment by pawurb** [comment]
@josegonzalez yes. You have to purchase the certificate separately and use [heroku certs:add](https://devcenter.heroku.com/articles/ssl#manually-uploading-certificates-and-intermediaries) command to upload them. Only free Let's Encrypt certificates don't support wildcard subdomains on Heroku.

**Comment by josegonzalez** [comment]
🤔

**Comment by pawurb** [comment]
I mean Let's Encrypt supports wildcard by itself, but Heroku plugin for Let's Encrypt does not. So you'd need to manually renew and reupload Let's Encrypt wildcard cert every 3 months.

**Comment by josegonzalez** [comment]
I have access to heroku, but not viewdocs dns, but I'll try to get access to that, at least as a stop-gap, so I can purchase a wildcard ssl certificate :)

**Comment by hugopeixoto** [comment]
> @hugopeixoto this is backwards incompatible change that would cause Dokku to loose all it's backlinks (over 6k according to ahrefs.com) and organic Google traffic:

It's backward compatible - every existing link would still work - but https would only work for the new links.
But if purchasing a wildcard certificate is a possibility, that also works :)

**Comment by josegonzalez** [comment]
I've got a meeting with Jeff to see if I can get access to some domains related to dokku, hopefully we can figure out a plan for viewdocs too :)

**Comment by hugopeixoto** [comment]
Should I close https://github.com/progrium/viewdocs/pull/56 then?

**Comment by josegonzalez** [comment]
Yeah for sure, I think we can add wildcard SSL support there too. I now have access to dokku.com DNS and am working on a new site, and will get viewdocs.io access in October likely (we had a small flub where transfers were accidentally locked because of clicking the wrong thing :P )

**Comment by josegonzalez** [comment]
Docs are now hosted on https://dokku.com and seem to work as expected.
