### ISSUE TITLE
set default resource limits

### ISSUE THREAD

**Issue by ltalirz** [dokku/dokku#4071]
The [documentation on resource management](http://dokku.viewdocs.io/dokku/advanced-usage/resource-management/) nicely explains how to set the resource limits for individual apps.

In a PaaS architecture, however, you will likely want to define default resource limits that apply to any new app.

Is there currently a way to do this?
If yes, I'm happy to add docs / to add a link from [here](http://dokku.viewdocs.io/dokku/advanced-usage/resource-management/) to the correct place.

**Comment by josegonzalez** [comment]
The best way to do this would be to implement a plugin to do this in the `post-create` hook. It can call out to the properties plugin (and config_set) as most/all plugins should use the former (or transition away from the latter).

**Comment by josegonzalez** [comment]
There currently isn't a great way to do this, though it might be interesting (once everything has switched to the properties system) to have a properties plugin that sets defaults/allows overriding properties for all apps at once.

This would be especially interesting for stuff like the scheduler or registry plugins, where you'd like want to set those settings globally for all apps vs one at a time.

**Comment by josegonzalez** [comment]
My biggest concern with a global properties plugin right now is property validation. Some plugins do it, some do not. We should make it optional, and something anyone can hook into. Other than that, I think the following is my tentative work plan:

### High Level Plan

- Add a `properties` plugin that more or less wraps the prop binary. Should have a `report` trigger, as well as as the `help` and `report` commands. Report should show only the defaults set via `properties:set`
- Add a `properties:set <PLUGIN> [<APP>|--global|--default] <KEY> [<VALUE>] ` command. In addition to app and global settings which will be equivalent to calling `PLUGIN:set` with respective args, the `--default` flag can be used to set a default for a given property key.
- Implement `property-set` trigger for all plugins. This takes `<PLUGIN> <APP> <KEY> <VALUE>` as arguments. Plugins can do what they want with the arguments, but generally should set the property if they are the plugin specified
- Implement `properties#post-create` trigger. This will iterate over all stored defaults and set them for the app via `property-set` calls.
- Document as part of Advanced Topics

**Comment by josegonzalez** [comment]
Thinking about this, I don't want to implement it. While it would certainly be nice, I think anyone that _needs_ this sort of functionality isn't exactly a hobbyist, and likely should be included in Dokku Pro.

That said, if someone needs this functionality in OSS, they are free to create a plugin that does the things they need on new app creation (which might be beyond setting some properties, and likely will be install-specific).
