### ISSUE TITLE
Dokku : how to have two ports for app and websocket (SocketIO)?

### ISSUE THREAD

**Issue by pirmax** [dokku/dokku#4081]
I need to use a second port with Dokku for my app, for websocket (SocketIO).

I used this command to add port to app:

> dokku proxy:ports-add my-app https:8001:8001 http:8001:8001

to add a new port for websocket. But I can't access to https://example.com:8001/socket.io/socket.io.js

Let's Encrypt is installed, and the app works on port http:80:5000 and https:443:5000.

    const socket = require('socket.io')();
    const io = socket.listen(process.env.SOCKET_PORT);
    
    socket.on('connection', function (socket) {
        socket.on('my other event', function (data) {
            console.log(data);
        });
    });
    
    module.exports = io;

This module is used in app.js. It works on local (in dev), but when I push my app on Dokku, impossible to have two ports added.

**Comment by AubreyHewes** [comment]
I may not understand what you are trying to do...

Why do you need another port for your websocket? You should be able to use a websocket on the same http(s) port i.e. `wss://example.com`

Does your provider/firewall allow external connections to port 8001?

**Comment by josegonzalez** [comment]
In order to proxy a second port, you'll currently need to use a custom nginx.conf.sigil to proxy the process-type specific ports. Please see the [nginx documentation](http://dokku.viewdocs.io/dokku/configuration/nginx/#customizing-the-nginx-configuration) for more information.
