### ISSUE TITLE
Cannot install Dokku (E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by silvanohirtie** [dokku/dokku#4089]
Hi, I'm trying to install Dokku, did everything that is written on the original doc
`wget https://raw.githubusercontent.com/dokku/dokku/v0.21.3/bootstrap.sh;`
`sudo DOKKU_TAG=v0.21.3 bash bootstrap.sh`

But I always get this error:
```
modprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-19041-Microsoft
WARNING: Restart server to finish installing dokku!
Setting up dokku user
docker:x:116:dokku
Setting up storage directories
Setting up plugin directories
Migrating old plugins
Enabling all core plugins
2020/07/29 15:25:04 fork/exec /home/silvano/.basher/bash: exec format error
dpkg: error processing package dokku (--configure):
 installed dokku package post-installation script subprocess returned error exit status 1
Setting up herokuish (0.5.15) ...
Importing herokuish into docker (around 5 minutes)
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
dpkg: error processing package herokuish (--configure):
 installed herokuish package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 dokku
 herokuish
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I get this error even if I try to install it through apt-get install

I'm trying to install it on an Ubuntu WSL
uname -a:
`Linux DESKTOP-96HV19T 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by josegonzalez** [comment]
I don't have access to a windows laptop, but the error looks like you're trying to install on a system where docker isn't available. Docker is listed as a requirement, so you're going to need to figure out why it isn't available in WSL.

I would suggest starting an actual VM - virtualbox? - and using that rather than the WSL.

**Comment by silvanohirtie** [comment]
> I don't have access to a windows laptop, but the error looks like you're trying to install on a system where docker isn't available. Docker is listed as a requirement, so you're going to need to figure out why it isn't available in WSL.
> 
> I would suggest starting an actual VM - virtualbox? - and using that rather than the WSL.

silvano@DESKTOP-96HV19T:~$ docker -v
Docker version 19.03.6, build 369ce74a3c

**Comment by josegonzalez** [comment]
Again, it looks like the problem is related to docker somehow not running/being available in the WSL:

```
Importing herokuish into docker (around 5 minutes)
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
dpkg: error processing package herokuish (--configure):
 installed herokuish package post-installation script subprocess returned error exit status 1
```

As I don't have a WSL-enabled system, I won't be able to investigate this. I also don't currently intend on the WSL being an installation target. Rather than keep the ticket open and mislead people into thinking this will be supported, I've closed it for now.

I think you should purge the dokku package from your WSL system and, if you wish to continue playing with Dokku, use an actual virtualmachine to set it up.

**Comment by alexgleason** [comment]
I'm getting a similar error on a new install. I'm sure it's an issue with the hosting provider, but I wanted to document it for anyone searching in the future:

```
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

journalctl for docker-ce says:

```
Aug 25 10:10:05 xyz.com dockerd[3848]: time="2022-08-25T10:10:05.127548414-04:00" level=warning msg="Running iptables --wait -t nat -L -n failed with message: `iptables v1.8.4 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.`, error: exit status 3"
Aug 25 10:10:05 xyz.com dockerd[3848]: time="2022-08-25T10:10:05.142457526-04:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Aug 25 10:10:05 xyz.com dockerd[3848]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables --wait -t nat -N DOCKER: iptables v1.8.4 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Aug 25 10:10:05 xyz.com dockerd[3848]: Perhaps iptables or your kernel needs to be upgraded.
Aug 25 10:10:05 xyz.com dockerd[3848]:  (exit status 3)
```

After some digging I found this:

> This is a limitation of the virtualization system we use (OpenVZ), basic iptables rules are possible but not those who use the nat table.

https://stackoverflow.com/a/26399654

Time to try a different VPS provider.
