### ISSUE TITLE
Consider prohibiting '_' in app names

### ISSUE THREAD

**Issue by richardcrichardc** [dokku/dokku#4102]
It leads to problems with virtual hosting domains and the letsencrypt plugin, because letsencrypt does not issue certificates for domain names with '_' in domain names.

It has hit me twice. I did not learn the first time.

**Comment by josegonzalez** [comment]
Hmm this might be good to do as a breaking change in 0.22.0. Similar would be this regex check on process types: https://github.com/dokku/dokku-scheduler-kubernetes/blob/master/post-extract

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
