### ISSUE TITLE
config:clear fails to run with "is not a dokku command" error

### ISSUE THREAD

**Issue by arimus** [dokku/dokku#4109]
## Description of problem
The config:clear command is not working. It displays in the config:help, but can not be run.

### How reproducible
Very.

### Steps to Reproduce

1. dokku config:clear <app>
2. see failure

#### Actual Results
Error when running: dokku config:clear <app>

```
root@dokku-s-1vcpu-2gb-sfo2-01:~# dokku version
dokku version 0.21.4
root@dokku-s-1vcpu-2gb-sfo2-01:~# dokku config:clear dev-admin
 !     `config:clear dev-admin` is not a dokku command.
 !     See `dokku help` for a list of available commands.
```

#### Expected Results
Config being cleared

### `dokku report APP_NAME` output

-----> uname: Linux dokku-s-1vcpu-2gb-sfo2-01 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           1993         263         205           0        1524        1569
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           19.03.12
        API version:       1.40
        Go version:        go1.13.10
        Git commit:        48a66213fe
        Built:             Mon Jun 22 15:45:36 2020
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          19.03.12
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.13.10
         Git commit:       48a66213fe
         Built:            Mon Jun 22 15:44:07 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.2.13
         GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info: 
       Client:
        Debug Mode: true
       
       Server:
        Containers: 0
         Running: 0
         Paused: 0
         Stopped: 0
        Images: 3
        Server Version: 19.03.12
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 4.15.0-52-generic
        Operating System: Ubuntu 18.04.5 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 1.947GiB
        Name: dokku-s-1vcpu-2gb-sfo2-01
        ID: GOXW:47IS:R4E6:FBCR:WCLK:GVBA:IQQI:BWPR:HJBB:J7U5:RZZV:4JYJ
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.15
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v218
         heroku-buildpack-nodejs    v174
         heroku-buildpack-clojure   v85
         heroku-buildpack-python    v173
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v178
         heroku-buildpack-go        v144
         buildpack-nginx            v14
-----> dokku version: dokku version 0.21.4
-----> dokku plugins: 
       plugn: 0.5.0
         00_dokku-standard    0.21.4 enabled    dokku core standard plugin
         20_events            0.21.4 enabled    dokku core events logging plugin
         app-json             0.21.4 enabled    dokku core app-json plugin
         apps                 0.21.4 enabled    dokku core apps plugin
         builder-dockerfile   0.21.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.21.4 enabled    dokku core builder-herokuish plugin
         buildpacks           0.21.4 enabled    dokku core buildpacks plugin
         certs                0.21.4 enabled    dokku core certificate management plugin
         checks               0.21.4 enabled    dokku core checks plugin
         common               0.21.4 enabled    dokku core common plugin
         config               0.21.4 enabled    dokku core config plugin
         docker-options       0.21.4 enabled    dokku core docker-options plugin
         domains              0.21.4 enabled    dokku core domains plugin
         enter                0.21.4 enabled    dokku core enter plugin
         git                  0.21.4 enabled    dokku core git plugin
         letsencrypt          0.9.4 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.21.4 enabled    dokku core logs plugin
         network              0.21.4 enabled    dokku core network plugin
         nginx-vhosts         0.21.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.21.4 enabled    dokku core plugin plugin
         proxy                0.21.4 enabled    dokku core proxy plugin
         ps                   0.21.4 enabled    dokku core ps plugin
         repo                 0.21.4 enabled    dokku core repo plugin
         resource             0.21.4 enabled    dokku core resource plugin
         scheduler-docker-local 0.21.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.21.4 enabled    dokku core shell plugin
         ssh-keys             0.21.4 enabled    dokku core ssh-keys plugin
         storage              0.21.4 enabled    dokku core storage plugin
         tags                 0.21.4 enabled    dokku core tags plugin
         tar                  0.21.4 enabled    dokku core tar plugin
         trace                0.21.4 enabled    dokku core trace plugin
=====> dev-admin app information
       App deploy source:             
       App dir:                       /home/dokku/dev-admin
       App locked:                    false
=====> dev-admin buildpacks information
       Buildpacks list:               
=====> dev-admin ssl information
       Ssl dir:                       /home/dokku/dev-admin/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> dev-admin checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> dev-admin docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> dev-admin domains information
       Domains app enabled:           true                     
       Domains app vhosts:            dev.appbloks.site
       Domains global enabled:        true                     
       Domains global vhosts:         appbloks.site       
=====> dev-admin git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                                                
       Git last updated at:                                    
=====> dev-admin network information
       Network attach post create:    
       Network attach post deploy:    
       Network bind all interfaces:   false
       Network web listeners:         
=====> dev-admin nginx information
       Nginx access log path:         /var/log/nginx/dev-admin-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx error log path:          /var/log/nginx/dev-admin-error.log
       Nginx hsts:                    true                     
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:                                  
=====> dev-admin proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 http:81:5001 https:443:5000 https:444:5001
       Proxy type:                    nginx
=====> dev-admin ps information
       Processes:                     0                        
       Deployed:                      false                    
       Running:                       false                    
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Ps can scale:                  true                     
=====> dev-admin scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> dev-admin storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts: 

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

DigitalOcean via the install shell script

### Additional information

None

**Comment by josegonzalez** [comment]
This should just be a matter of whitelisting the correct commands in the Makefile.

**Comment by Joebortscheller** [comment]
[](https://www.simulation-argument.com/simulation.pdf)
