### ISSUE TITLE
[remote rejected] dev -> master (pre-receive hook declined) when deployed Django application to dokku app

### ISSUE THREAD

**Issue by trungkmy** [dokku/dokku#4110]
## Description of problem
I'm trying to deploy django application to dokku app and facing this issue, please check logs:

remote: -----> Cleaning up...
remote: -----> Building siam-surety from herokuish...
remote: -----> Adding BUILD_ENV to build environment...
remote:        -----> Python app detected
remote: cp: cannot stat '/tmp/build/requirements.txt': No such file or directory
remote:        Skipping installation, as Pipfile.lock hasn't changed since last deploy.
remote: -----> Installing SQLite3
remote: mv: missing destination file operand after '/tmp/build/.heroku/python/include/'
remote: Try 'mv --help' for more information.
remote: mv: missing destination file operand after '/tmp/build/.heroku/python/lib/'
remote: Try 'mv --help' for more information.
remote: sed: can't read /tmp/build/.heroku/python/sqlite3/usr/lib/x86_64-linux-gnu/pkgconfig/sqlite3.pc: No such file or directory
remote: mv: missing destination file operand after '/tmp/build/.heroku/python/bin/'
remote: Try 'mv --help' for more information.
remote: -----> $ python manage.py collectstatic --noinput
remote:        /tmp/build
remote:        498 static files copied to '/tmp/build/staticfiles'.
remote:
remote:        -----> Discovering process types
remote:        Procfile declares types -> release, web
remote: -----> Releasing siam-surety (dokku/siam-surety:latest)...
remote: -----> Deploying siam-surety (dokku/siam-surety:latest)...
To dokku@dokku@[myIP]:[my dokku app]
 ! [remote rejected] dev -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@[myIP]:[my dokku app]'

### How reproducible
I just clone my existing django app and it run perfectly in my development environment but fail to deploy to dokku

### Steps to Reproduce

1. Create dokku app: dokku apps:create [my app]
2. Add git remote to dokku app: git remote add  dokku dokku@[myIP]:[my app]
3. Deploy apllication: git push dokku dev:master

#### Actual Results
 ! [remote rejected] dev -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@[myIP]:[my dokku app]'

#### Expected Results
Successfully deploy django app to dokku

## Environment Information
root@ip:~# dokku --version
dokku version 0.20.4

Python --version
Python 3.8.5

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by trungkmy** [comment]
Sorry for my basic mistake but I tried to put `release: python manage.py migrate --noinput` in Procfile before `web: gunicorn siamsurety.wsgi` so It raised the issue
