### ISSUE TITLE
Command `dokku apps:report` is not working

### ISSUE THREAD

**Issue by pradel** [dokku/dokku#4133]
## Description of problem

According to the [dokku docs](http://dokku.viewdocs.io/dokku/deployment/application-management/#displaying-reports-for-an-app) running `dokku apps:report` should print the reports for the apps. Running `dokku apps:report` not working as expected, the output is `FAILED: Please specify an app to run the command on`.

### Steps to Reproduce

Run `dokku apps:report`.

#### Actual Results

```
vagrant@dokku:~$ dokku apps:report
FAILED: Please specify an app to run the command on
```

#### Expected Results

List the reports for the apps.

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Local vagrant installation.

### Additional information

Tested on Dokku:
- v0.21.3
- v0.21.4

**Comment by aarhusgregersen** [comment]
I think there is either a misunderstanding or a problem with the documentation.
Visiting a dokku installation (`v0.21.4`) displays the following help message for the command `dokku apps:report`:
```
apps:report [<app>] [<flag>]     Display report about an app
```
So the command clearly takes an app argument. This is also the same thing it says on the page you linked, but you are right it *also* says that it can be used  to report for all apps.

For now, in my opnion, this is a documentation issue, but I guess it would be a nice feature to have.

However, what you may be looking to do

**Comment by josegonzalez** [comment]
Yeah this is a bug, looks like the other `:report` subcommands in golang seem to do the right thing. Thanks for the report!

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
