### ISSUE TITLE
App report command is not giving information if app was deployed

### ISSUE THREAD

**Issue by pradel** [dokku/dokku#4134]
## Description of problem

I am trying to see if an app was deployed or not using the app report command. According to the [dokku docs](http://dokku.viewdocs.io/dokku/deployment/application-management/#displaying-reports-for-an-app) running `dokku apps:report APP_NAME` should print `not deployed` message if the app was just created and never deployed.

### Steps to Reproduce

1. `dokku apps:create python-sample`
2. `dokku apps:report python-sample`

#### Actual Results

```
$ dokku apps:report python-sample
=====> python-sample app information
       App deploy source:             
       App dir:                       /home/dokku/python-sample
       App locked:                    false
```

#### Expected Results

```
$ dokku apps:report python-sample
=====> python-sample
not deployed
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Local vagrant installation.

### Additional information

Tested on Dokku:
- v0.21.3
- v0.21.4

**Comment by josegonzalez** [comment]
This seems to have changed in 0.20.x with the rewrite to golang. The current way to check if an app was deployed is to check the output of `ps:report`. If you want the _exact_ call, it should be:

```shell
dokku ps:report $APP_NAME --deployed
```

I'll get this fixed in our docs.
