### ISSUE TITLE
Dokku Nginx and Rails static assets expiration dates, how to?

### ISSUE THREAD

**Issue by onnimonni** [dokku/dokku#414]
I'm using Rails 4.0.0 application. Been googling and trying things for hours but my best guess is that this is related with the fact that app is running inside container.

/home/dokku/{app}/nginx.conf: 

```
upstream justontime { server 127.0.0.1:49177; }
server {
  listen      80;

  server_name justontime.koodimonni.fi;
  location    / {
    # enable gzip compression
    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/plain application/x-javascript text/xml text/css;
    gzip_vary on;
    # end gzip configuration

    proxy_pass  http://justontime;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
}
```

To enable expiration i'm supposed to use something like:

```
location ~ ^/assets/ {
  expires 1y;
  add_header Cache-Control public;

  add_header ETag "";
  break;
}
```

None of my assets gets loaded if i add that to nginx.conf. Sorry as this is possibly non-dokku-related, but how to do this?

**Comment by mrbrdo** [comment]
In 2022 I still have this issue, as soon as I add a blank `location ^~ /assets/ { }` to the nginx config, the assets stop working.
What's the deal?

**Comment by ferblape** [comment]
8 years.... the world (and the asset pipeline) has changed a lot, maybe you are using Webpacker, Esbuild, so the path of your assets is different. Anyway, in Rails you don't need your assets to expire, they have a checksum that makes the filenames unique.

If it helps I've used this rule for a long time in my Rails installations:

```
  location ~ ^/(assets|packs)/ {
    try_files $uri =404;
    expires max;
    add_header Cache-Control public;
    gzip_static on;
    break;
  }
```

**Comment by josegonzalez** [comment]
Yeah I think commenting on an 8 year old ticket that was closed is a bit much. If you're having issues, please open up a new one (or start a discussion) instead.

Thanks @ferblape for following up though :)
