### ISSUE TITLE
Error building java app: /tmp/buildpacks/05_buildpack-java/bin/compile: line 18: export_env: command not found  

### ISSUE THREAD

**Issue by paoesco** [dokku/dokku#4147]
## Description of problem
After upgrading to Debian Buster and dokku 0.21.4, my java application can't be built.
It throws the error `/tmp/buildpacks/05_buildpack-java/bin/compile: line 18: export_env: command not found`

The previous dokku version 0.18 worked perfectly.

### Steps to Reproduce

Deploy app using git push (via travis ci)
https://github.com/famivac/famivac-gestionnaire-api/blob/master/.travis/deploy.sh

#### Actual Results
Error when building the app
#### Expected Results
Successfully deploy the app

## Environment Information
dokku 0.21.4

https://pastebin.com/Lk9DhGf0

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
- Kimsufi
- Debian Buster

### Additional information
- Travis CI job: https://travis-ci.org/github/famivac/famivac-gestionnaire-api
- App: https://github.com/famivac/famivac-gestionnaire-api

**Comment by paoesco** [comment]
I completely reinstalled the server and it did work.

Not sure what happened when upgrading from 0.18 to 0.21.

**Comment by josegonzalez** [comment]
Might be that the java buildpack was out of date, as we're now on 0.5.18 of Herokuish. Glad you've solved it.
