### ISSUE TITLE
Deploy Django on dokku app stuck

### ISSUE THREAD

**Issue by trungkmy** [dokku/dokku#4150]
I'm trying to deploy my Django project to dokku application. It's success for many time before but now after long time develop, process is stucking for few hours. Please help!!!

_remote: Resolving deltas: 100% (4519/4519), completed with 148 local objects.
remote: -----> Cleaning up...
remote: -----> Building siam-surety from herokuish...
remote: -----> Adding BUILD_ENV to build environment...
remote:        -----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
remote:               Detected buildpacks: nodejs python
remote:        -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 12.x...
remote:        Downloading and installing node 12.19.0
remote:        Using default npm version: 6.14.8
remote:
remote: -----> Installing dependencies
remote:        Installing node modules
remote:
remote:        > fsevents@1.2.13 install /tmp/build/node_modules/watchpack-chokidar2/node_modules/fsevents
remote:        > node install.js
remote:
remote:
remote:        Skipping 'fsevents' build as platform linux is not supported
remote:        added 484 packages in 168.886s
remote:
remote: -----> Build
remote:
remote: -----> Caching build
remote:        - node_modules
remote:
remote: -----> Pruning devDependencies
remote:        removed 28 packages and audited 457 packages in 7.743s
remote:
remote:        20 packages are looking for funding
remote:        run `npm fund` for details
remote:
remote:        found 0 vulnerabilities
remote:
remote:
remote: -----> Build succeeded!
remote:        -----> Discovering process types
remote:        Procfile declares types -> release, web
remote: -----> Releasing siam-surety (dokku/siam-surety:latest)...
remote: -----> Deploying siam-surety (dokku/siam-surety:latest)...
remote:  !     Release command declared: 'npm run prod'_

**Comment by dannluciano** [comment]
Hi do you solve this problem?

**Comment by josegonzalez** [comment]
Without knowing the rest of the info we request in our [issue template](https://github.com/dokku/dokku/blob/masterUE_TEMPLATE.md), this is impossible to debug. I'm going to close the ticket for now, please comment with that info if you are still seeing this issue.

@dannluciano same for you, please open a new ticket if you are seeing a problem.

**Comment by dannluciano** [comment]
@josegonzalez Dont worry. I was trying to help. I'm Dokku user for years and I have never been there.

**Comment by josegonzalez** [comment]
Ah gotcha, thought you were having the same issue. Apologies!
