### ISSUE TITLE
Vagrant build error: the host path of the shared folder is missing

### ISSUE THREAD

**Issue by gnowland** [dokku/dokku#4158]
## Description of problem
`vagrant provision` results in the following error:

```shell
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: /Users/username/dokku/../dokku-arch
```
### How reproducible
Every time

### Steps to Reproduce

1. Clone repo
2. `vagrant up`

#### Actual Results

The aforementioned error

#### Expected Results

No error

<-- Please replace APP_NAME with the name of your app -->

### `dokku report APP_NAME` output

- MacOS Catalina 10.15.7
- Vagrant 2.2.10
- VirtualBox 6.1.14

(but this also happened with older versions of Vagrant and VirtualBox - I updated both to their latest versions in case this might fix it; it did not)

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

VirtualBox

### Additional information

The error is resolved by temporarily making a `dokku-arch` folder in the directory above `dokku`, re-running `vagrant provision`, and then deleting the aformentioned  `dokku-arch` folder... but I think this is likely a bug?

**Comment by gnowland** [comment]
I'm not super familiar with this repo but I believe it should possibly be looking for the `dokku-arch` folder in `.vagrant/machines`, yeah?

**Comment by gnowland** [comment]
The offending line being https://github.com/dokku/dokku/blob/2edbc3fe39bf193b86fe24f6377584c0f41d6cce/Vagrantfile#L106

**Comment by badsyntax** [comment]
Experienced the same issue, but got it working with `vagrant up dokku` or `vagrant provision dokku`

**Comment by gnowland** [comment]
Smart!!--
Gifford Nowland
(302) 898-4597 | gnowland@gmail.com | https://giffordnowland.com
he/him/his

Sent from a really tiny computer
