### ISSUE TITLE
Is it necessary to manually restart applications after redeployment?

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku#4161]
If I have to redeploy my application, am I required to restart it after deployment with `dokku ps:restart my_app` or the command `git push dokku master` would automatically restart linked containers and application?

**Comment by josegonzalez** [comment]
You don't need to restart your app. Deploys will build your application (unless you disable that for some reason) and thats all that is needed.

Linked services aren't auto-restarted, though thats a known issue and up to the plugin containers to implement (https://github.com/dokku/dokku-redis/issues/154).
