### ISSUE TITLE
Run Dokku App Installation failed due to server behind internet proxy

### ISSUE THREAD

**Issue by darasom1** [dokku/dokku#4163]
Hi All,

I try to run dokku install plugin but failed due to internet access issue. Our servers behind Proxy for out going access to the internet. Is there any way to run it behind proxy ?

`sudo dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres`

Failed result 
`+ local PLUGIN_NAME=postgres
+ plugn install https://github.com/dokku/dokku-postgres.git postgres
Cloning into 'postgres'...
fatal: unable to access 'https://github.com/dokku/dokku-postgres.git/': Failed connect to github.com:443; Connection timed out
`
Example we have http_proxy and https_proxy = proxy.example.com:8080

Thanks,

**Comment by josegonzalez** [comment]
You can configure a global proxy for git as shown here: https://stackoverflow.com/a/19213999/1515875

Hope that helps.
