### ISSUE TITLE
404 error for all wordpress subpages

### ISSUE THREAD

**Issue by trungkmy** [dokku/dokku#4169]
## Description of problem
After successfully deployed wordpress application to dokku. All subpages are return 404 error except home page
### How reproducible
Just deploy wordpress application by `git push dokku master`
### Steps to Reproduce
in my wordpress root folder
1.  `git init`
2. `git remote add dokku dokku@[ip]:[app_name]`
3. `git add .` `git commit -m "any comment"` `git push dokku master`

#### Actual Results
Homepage display correctly but all subpages like https://mydomain/subpage return 404 error 

====> Error display in browser <=====
_Not Found
The requested URL was not found on this server._

#### Expected Results
Homepage and subpages display correctly

### Additional information
I think problem come form NGINX configuration. I spend a day to research in internet and found so many issue about "nginx error 404 for subpages of wordpress" and I already tried all solution but none of theme work.

#### My nginx configuration
server {
  listen      [::]:80;
  listen      80;
  server_name [mydomain]; 
  access_log  /var/log/nginx/skynet-landing-access.log;
  error_log   /var/log/nginx/skynet-landing-error.log;

  return 301 https://$host:443$request_uri;
}

server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;
  
  server_name [mydomain]; 
  access_log  /var/log/nginx/skynet-landing-access.log;
  error_log   /var/log/nginx/skynet-landing-error.log;

  ssl_certificate           /home/dokku/skynet-landing/tls/server.crt;
  ssl_certificate_key       /home/dokku/skynet-landing/tls/server.key;
  ssl_protocols             TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  keepalive_timeout   70;
 
  location    / {
    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;
    proxy_pass  http://skynet-landing-5000;
    http2_push_preload on; 
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
  }
  include /home/dokku/skynet-landing/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 502 /502-error.html;
  location /502-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }
}
upstream skynet-landing-5000 {
  server 172.17.0.5:5000;
}

**Comment by josegonzalez** [comment]
This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). 

Issues pertaining to buildpacks will be closed and/or locked.
