### ISSUE TITLE
HTTPS Deployment

### ISSUE THREAD

**Issue by emados** [dokku/dokku#4174]
Does dokku support pushing to git over HTTPS? If not, are there any plans to add support in the future?

I thought of creating a container of git with Smart HTTP setup, that has the home directory of dokku mounted as the repositories directory on the container. Are there any security concerns about this setup other than maintaining the credentials and serving over HTTPS? And how can dokku deployment be triggered considering the git server is containerized?

**Comment by josegonzalez** [comment]
There is a project we've contributed to [here](https://github.com/dokku/git-http-backend) that implements the git-http-backend in golang (well, really its just a wrapper to the git-cli, but good enough) that you can use as the basis of your own work (and is the basis of similar functionality in my own, internal UI project).

Regarding mounting the path into a container, you'd still need to have a way to execute the `dokku` binary (and all the things it depends on) which run outside of that container. You could probably use our Docker image as a base though, and just have all the directories be mounts, which would work fine.

That said, this isn't something we're going to do in the Dokku core. There are lots of unanswered questions around authentication and git-server functionality that I'm not well equipped to perform. If others want to investigate this, they are more than welcome to, but it's not going to be something I can do for free.

Hope that helps. Feel free to jump on slack with further questions.
