### ISSUE TITLE
Java 11 / Java > 8 

### ISSUE THREAD

**Issue by vexa** [dokku/dokku#4176]
I always get an error if i push to the dokku repo with my maven java version 11 
remote:        [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project dokku-boot-demo: Fatal error compiling: invalid
target release: 11 -> [Help 1]

**Comment by josegonzalez** [comment]
This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). 

Issues pertaining to buildpacks will be closed and/or locked.
