### ISSUE TITLE
Feature request: nice if `tar:from` could handle GitHub tarball urls

### ISSUE THREAD

**Issue by anentropic** [dokku/dokku#4207]
It would be nice if `dokku tar:from <app> <url>` could handle the output of GitHub tarball urls (like `http://github.com/anentropic/<myproject>/tarball/master`) directly.

But the GitHub url downloads a `.tar.gz` file, so dokku complains "This does not look like a tar archive".

The workaround is not too onerous, I was able to:
```
curl -o - -L -u anentropic:<github token> http://github.com/anentropic/<myproject>/tarball/master | gunzip -dc | dokku tar:in <app>
```

But I just think it would nice if you could directly pass a GitHub tarball url to `tar:from`, it feels like it would be a common use case for this feature?

I'm using it in the user data cloud-init script for my DigitalOcean droplet, so that the current app version gets deployed when I boot up a server from scratch.

**Comment by josegonzalez** [comment]
How would we detect that the file is a `.tar` vs `.tar.gz`?

**Comment by Schlepptop** [comment]
GitHub tarballs should always be gzipped, but couldn't we also `curl -s -I the_url | grep "^Content-Type:"` to find out which case applies?

**Comment by anentropic** [comment]
There's a few options:

- check the `Content-Type` response header as @Schlepptop suggested e.g.:
  ```
  $ curl -s -I -L https://github.com/dokku/dokku/tarball/master

  ...

  HTTP/1.1 200 OK
  Date: Tue, 01 Dec 2020 21:30:45 GMT
  Content-Type: application/x-gzip
  ```
- just try/catch/fallback i.e. if gunzip fails treat as tar
- sniff the file:
  ```bash
  $ file /tmp/dokku-tarball
  /tmp/dokku-tarball: gzip compressed data, from Unix, original size modulo 2^32 4096000
  ```
- add an explicit arg `dokku tar:from <app> <url> --gzip`

**Comment by josegonzalez** [comment]
That plugin currently streams the curl output to `tar:in`, so we'd need to suss that out. I also feel people will want zip support in addition to `tar.gz` support.

In that light, is there a better plugin name we can use for this?

**Comment by josegonzalez** [comment]
I'm going to close this. As of 0.23.x, we support a `git:sync` command that will let you synchronize an app with a given remote repository, which covers your initial reason for using `tar:from`. Additionally, we're going to be deprecating the `tar` plugin in favor of `git:from-tar` in #3458, and we should be able to additionally create a `git:from-gz` for this particular use case, though I suspect `git:sync` will be the only real needed support here.

**Comment by josegonzalez** [comment]
@anentropic I was able to roll this into the upcoming `git:from-archive` command in 0.24.0. Thanks for the initial issue :)

**Comment by anentropic** [comment]
nice one
