### ISSUE TITLE
Create a circleci deployment orb

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#4216]
No idea how circleci orbs work, but would be cool to have one that supports all the same functionality that the [github-action](https://github.com/dokku/github-action) does.

**Comment by aaronstillwell** [comment]
@josegonzalez I have created an orb with similar functionality.

Repo: https://github.com/aaronstillwell/dokku-orb
Orb page: https://circleci.com/developer/orbs/orb/aaronstillwell/dokku

Feel free to raise issues against that repo and I'll be happy to add more as and when time permits. Alternatively, feel free to fork the repo and host/maintain it under the dokku namespace.

Feedback welcome.

**Comment by josegonzalez** [comment]
@aaronstillwell this is great! Would you mind adding my username to the repo as an admin? I'll transfer it to the dokku organization and give you full rights to work on it of course. This will ensure we keep the orb history intact :)

**Comment by aaronstillwell** [comment]
@josegonzalez I've sent the transfer request. You will need to create a dokku CircleCI namespace and configure CircleCI with your own api key to deploy the orb to the new namespace. I can follow up here with docs.

**Comment by josegonzalez** [comment]
@aaronstillwell seems I can't publish the orb because your orb already exists or something.

```
Thank you! Setting up your orb...
Error: Unable to create orb: Cannot create an Orb named 'dokku': an Orb with that name already exists.
```

Any chance you can take a look? You should have permissions on that repo.

**Comment by aaronstillwell** [comment]
Hey @josegonzalez - have you registered the dokku namespace? See this doc: https://circleci.com/docs/2.0/orb-author-intro/#register-a-namespace

Note you need to be an org admin on the dokku github org to perform this operation. So it's not something I can do.

**Comment by josegonzalez** [comment]
Yeah I did that, and it even says I created it already...

```
You are creating a namespace called "dokku".

This is the only namespace permitted for your github organization, dokku.

To change the namespace, you will have to contact CircleCI customer support.

? Are you sure you wish to create the namespace: `dokku` Yes
Error: Organizations may only create one namespace. This organization owns the following namespace: "dokku"
```

**Comment by josegonzalez** [comment]
The orb exists! Thanks @aaronstillwell for the donation, it's available [here](https://circleci.com/developer/orbs/orb/dokku/dokku) :)
