### ISSUE TITLE
Docs: Why Vagrant?

### ISSUE THREAD

**Issue by guettli** [dokku/dokku#4246]
I don't understand the docs at: http://dokku.viewdocs.io/dokku~v0.22.2/deployment/application-deployment/

> Note: This walkthrough uses the hostname dokku.me in commands. When deploying to your own server, you should set 
> the DOKKU_DOMAIN value in the Vagrantfile before you initialize the Vagrant VM.

I think this is confusing. I use my own server, a root-server from Hetzner. AFAIK there is no Vagrant involved.

**Comment by josegonzalez** [comment]
Probably worded wrongly. Should be something like:

> Note: This walkthrough uses the hostname `dokku.me` in commands. When deploying to your own server, you should substitute the domain `dokku.me` for the domain name or IP address associated with your server.
