### ISSUE TITLE
Docs: wildcard Domain

### ISSUE THREAD

**Issue by guettli** [dokku/dokku#4257]
I am looking at the docs of CapRover. In the first lines of "getting started" they write 

> During installation, you'll be asked to point a wildcard DNS entry to your CapRover IP Address. 

I think explaining a sane default (best practice) at the top of Dokku-docs would be nice.

Rule of thumb: Put the details and special cases at the bottom, and the bird-eye-perspective at the top.

I know this is difficult.

**Comment by josegonzalez** [comment]
There are a _lot_ of "sane defaults" we could document, both for setup and for general usage of specific plugins. On our installation docs, we currently have:

> You can optionally have a domain name pointed at the host's IP, though this is not necessary.

Probably could be rephrased, but that page is already fairly long (I keep meaning to make it much simpler). Feel free to PR what you think might be a good change. I know this is difficult.
