### ISSUE TITLE
Add ability to rename apps with old name restrictions to new name restrictions

### ISSUE THREAD

**Issue by sinys15** [dokku/dokku#4267]
I have an old one project with the name updater_local. And when I want to do something with this project I got a message "App name must begin with lowercase alphanumeric character, and cannot include uppercase characters, colons, or underscores". And now I can't do anything with this project. I can't get settings and I can't rename it:
$ dokku apps:rename updater_local updater-local
 !     App name must begin with lowercase alphanumeric character, and cannot include uppercase characters, colons, or underscores

Could you please fix it? I think it will be fair to allow renaming old projects to a new name with the new restrictions.

**Comment by afuno** [comment]
This is a problem in the new version (0.22.x). When updating Dokku, for some reason, protection didn't work (or it does not exist at all). But after updating Dokku almost completely stops working and displays this error text.

**Comment by josegonzalez** [comment]
There was a migration guide entry for this [here](http://dokku.viewdocs.io/dokku/appendices/0.22.0-migration-guide/), and that should have been performed prior to an upgrade.

That said, I can certainly add the ability to rename apps even if the old app is incorrectly named. I'll add that as a feature to Dokku 0.22.3.

**Comment by afuno** [comment]
> There was a migration guide entry for this here, and that should have been performed prior to an upgrade.

It's good. Well it would be nice to prohibit updating until the problems are fixed.

> That said, I can certainly add the ability to rename apps even if the old app is incorrectly named. I'll add that as a feature to Dokku 0.22.3.

Thank you. This should help other people get rid of their headaches. Now the situation in which there is Tom and his ilk really looks bad. It is extremely difficult to return from it.

**Comment by josegonzalez** [comment]
Users seeing this issue can downgrade dokku to the previous release via yum or apt. Here is the command for apt:

```shell
apt install dokku=0.21.4
```

**Comment by josegonzalez** [comment]
The linked PR (#4270) fixes this :)
