### ISSUE TITLE
Possible to git pull from a Dokku box?

### ISSUE THREAD

**Issue by jcraigk** [dokku/dokku#4271]
## Description of problem

I'm working with a deployment setup where the app boxes (running Dokku) are in a VPC that are not directly accessible from the internet except through a web load balancer. Unfortunately this setup is not compatible with `git push dokku...` type of deploys as I have no direct route to the Dokku boxes.

Is it possible to `git pull` from within a Dokku box instead to deploy a change? I would envision pulling from a private github or gitlab repository in this case.

I apologize if this is not a good use of Issues - I tried finding an answer to this and couldn't find it, so I'm posting here. Thanks so much for this great deploy tool!

**Comment by josegonzalez** [comment]
For the moment, there isn't anything built into Dokku, though I'd like to add a few commands to the `git` plugin for this.

There is a `dokku-clone` plugin that may help.

Alternative is to just clone from something in your VPC (even the box itself) and trigger the deploy.

Hope that helps.
