### ISSUE TITLE
Global domain is always resolved to an app

### ISSUE THREAD

**Issue by Kristonitas** [dokku/dokku#4277]
I am trying to host multiple apps via dokku on a domain http://ksonit.lt. After I figured out a few problems, I was able to set up each of those apps on different subdomains:

* http://ruby-getting-started.ksonit.lt/
* http://imaginer.ksonit.lt/
* http://next-test.ksonit.lt/
* http://foobar.ksonit.lt/ **THIS IS NOT AN ACTUAL APP**

While I don't have something yet to be displayed on the host/global domain (http://ksonit.lt), I want nothing to be visible there. I thought it was possible with dokku, but it seems I am always redirected to the "imaginer" app, if I go directly to http://ksonit.lt.

## Info

`dokku domains:report --global`

> =====> Global domains information
>        Domains global enabled:        false                    
>        Domains global vhosts:                                  

`dokku domains:report`

> =====> imaginer domains information
>        Domains app enabled:           true                     
>        Domains app vhosts:            imaginer.ksonit.lt       
>        Domains global enabled:        false                    
>        Domains global vhosts:                                  
> =====> next-test domains information
>        Domains app enabled:           true                     
>        Domains app vhosts:            next-test.ksonit.lt      
>        Domains global enabled:        false                    
>        Domains global vhosts:                                  
> =====> ruby-getting-started domains information
>        Domains app enabled:           true                     
>        Domains app vhosts:            ruby-getting-started.ksonit.lt
>        Domains global enabled:        false                    
>        Domains global vhosts:                                  

`dokku apps:report`

> =====> imaginer app information
>        App deploy source:             
>        App dir:                       /home/dokku/imaginer
>        App locked:                    false
> =====> next-test app information
>        App deploy source:             
>        App dir:                       /home/dokku/next-test
>        App locked:                    false
> =====> ruby-getting-started app information
>        App deploy source:             
>        App dir:                       /home/dokku/ruby-getting-started
>        App locked:                    false

### Nginx `dokku nginx:show-config APP_NAME`

```
server {
  listen      [::]:80;
  listen      80;
  server_name imaginer.ksonit.lt; 
  access_log  /var/log/nginx/imaginer-access.log;
  error_log   /var/log/nginx/imaginer-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://imaginer-5000;
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_buffer_size 4096;
    proxy_buffering on;
    proxy_buffers 8 4096;
    proxy_busy_buffers_size 8192;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/imaginer/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

}

upstream imaginer-5000 {

  server 172.17.0.4:5000;
}
```

```
server {
  listen      [::]:80;
  listen      80;
  server_name next-test.ksonit.lt; 
  access_log  /var/log/nginx/next-test-access.log;
  error_log   /var/log/nginx/next-test-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://next-test-5000;
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_buffer_size 4096;
    proxy_buffering on;
    proxy_buffers 8 4096;
    proxy_busy_buffers_size 8192;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/next-test/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

}

upstream next-test-5000 {

  server 172.17.0.5:5000;
}
```

```
server {
  listen      [::]:80;
  listen      80;
  server_name ruby-getting-started.ksonit.lt; 
  access_log  /var/log/nginx/ruby-getting-started-access.log;
  error_log   /var/log/nginx/ruby-getting-started-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://ruby-getting-started-5000;
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_buffer_size 4096;
    proxy_buffering on;
    proxy_buffers 8 4096;
    proxy_busy_buffers_size 8192;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/ruby-getting-started/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

}

upstream ruby-getting-started-5000 {

  server 172.17.0.3:5000;
}
```

## Remarks

I suspect the nginx defaults to the first config, if no `server_name` matches the request. It would be helpful to add a note to the documentation about this behaviour in the domains configuration, since its confusing if you don't know whats going on.

Maybe this behaviour of opening any app, if getting a request, is expected... But it was not mentioned in the docs AFAIK. Maybe I could at least provide some 404, when someone opens an arbitrary subdomain, like http://foobar.ksonit.lt/? 

P. S. My initial experience after getting a VM and installing dokku was very poor. The `hostname` in Linux defaulted to "123456.s.SERVICE_PROVIDER.lt". And I was using my own domain "ksonit.lt", so when I was attempting to use the links like http://imaginer.ksonit.lt/, I was actually just getting the fall-back "global-domain" logic. Even after I disabled the global domains with `domains:clear-global`, I got the same behaviour.

**Comment by josegonzalez** [comment]
As you suspect, this is due to how nginx handles domains. We've documented it in our [nginx documentation](http://dokku.viewdocs.io/dokku/configuration/nginx/#default-site) and have a link at the bottom of the [domains documentation](http://dokku.viewdocs.io/dokku/configuration/domains/#default-site). When you first install Dokku, there is also a [link on the tutorial page](http://dokku.viewdocs.io/dokku/deployment/application-deployment/#default-vhost) you get directed to that points out how to manage this.

Regarding the initial experience, there is a web installer that asks you to set the global domain, and it also shows you what app urls will look like. Not sure if you maybe missed that or it wasn't clear enough.

Hope the above helps.

**Comment by Kristonitas** [comment]
This is really helpful and now I feel like a fool for not reading the nginx part fully...

I just thought that "global domain" or "domain-global" is the keyword that corresponds to the default site behaviour I was talking about. Now I understand those are separate things.

> Regarding the initial experience, there is a web installer that asks you to set the global domain, and it also shows you what app urls will look like. Not sure if you maybe missed that or it wasn't clear enough.

At the time, I didn't think about it and later forgot to take care of it (the hostname). I was just very excited to use Dokku immediately after finding it, so I was rushing to get it working. I hope others don't bump into the same mistakes.

P. S.
I don't want to create another uninformed issue, but for me the remote git origin syntax of `dokku@{serveripordomain}:{dokkuappname}` seems to be hidden in the documentation:

> ![image](https://user-images.githubusercontent.com/9002285/103179434-b0975700-4894-11eb-9bce-3ad0ef4dedc4.png)

It actually seems, like the comment ends, and "Push in the form of: ..." alludes to the next line. The important bit needs to be scrolled to:

> ![image](https://user-images.githubusercontent.com/9002285/103179489-5c40a700-4895-11eb-98d8-50347d89a932.png)

From the way [this section](http://dokku.viewdocs.io/dokku/deployment/application-deployment/#deploying-to-subdomains) was presented, it seemed, that the `dokkuappname` was the desired subdomain or hostname of the app (instead of the app name). Of course its another case of me rushing through the docs/installation.
