### ISSUE TITLE
Better error message when ssh-key is missing

### ISSUE THREAD

**Issue by EmilStenstrom** [dokku/dokku#4278]
## Description of problem

When running commands with the dokku_client.sh (latest master)

### How reproducible
```bash
$ dokku
This is not a git repository
$ dokku help
This is not a git repository
$ ssh-add ~/.ssh/<my-key>
Identity added: /home/<me>/.ssh/<my-key>
$ dokku help
This is not a git repository
Usage: dokku [--quiet|--trace|--rm-container|--rm|--force] COMMAND <app> [command-specific-options]
...
```

#### Actual Results
Gives no error message when ssh fails to connect due to insufficient credentials.

#### Expected Results
Should give a better error message when ssh client can't connect.

## Environment Information

Dokku client is triggered with a bash alias in .profile. Also, the DOKKU_HOST is set to point to my server.

alias dokku='$HOME/.dokku/contrib/dokku_client.sh'

### `dokku report APP_NAME` output

$ dokku report
<details>
This is not a git repository
-----> uname: Linux sammanfatta.se 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:            985         732          53           2         199          86
       Swap:          2047         772        1275
-----> docker version:
       Client:
        Version:           18.09.7
        API version:       1.39
        Go version:        go1.10.8
        Git commit:        2d0083d
        Built:             Thu Jun 27 17:56:23 2019
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          18.09.7
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.8
         Git commit:       2d0083d
         Built:            Thu Jun 27 17:23:02 2019
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info:
       Containers: 20
        Running: 16
        Paused: 0
        Stopped: 4
       Images: 131
       Server Version: 18.09.7
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
       runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-54-generic
       Operating System: Ubuntu 18.04.2 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 985.5MiB
       Name: sammanfatta.se
       ID: SVEG:AAEB:6GKT:PF7L:KABE:NJ5P:2ICV:WGTZ:FQQB:MTH3:ALTJ:ABAQ
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine

-----> sigil version: 0.6.0
-----> herokuish version:
       herokuish: 0.5.21
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v222
         heroku-buildpack-nodejs    v178
         heroku-buildpack-clojure   v86
         heroku-buildpack-python    v186
         heroku-buildpack-java      v68
         heroku-buildpack-gradle    v33
         heroku-buildpack-scala     v88
         heroku-buildpack-play      v26
         heroku-buildpack-php       v185
         heroku-buildpack-go        v148
         buildpack-nginx            v14
-----> dokku version: dokku version 0.22.3
-----> dokku plugins:
       plugn: 0.6.0
         00_dokku-standard    0.22.3 enabled    dokku core standard plugin
         20_events            0.22.3 enabled    dokku core events logging plugin
         app-json             0.22.3 enabled    dokku core app-json plugin
         apps                 0.22.3 enabled    dokku core apps plugin
         builder-cnb          0.22.3 enabled    dokku core builder-cnb plugin
         builder-dockerfile   0.22.3 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.22.3 enabled    dokku core builder-herokuish plugin
         buildpacks           0.22.3 enabled    dokku core buildpacks plugin
         certs                0.22.3 enabled    dokku core certificate management plugin
         checks               0.22.3 enabled    dokku core checks plugin
         common               0.22.3 enabled    dokku core common plugin
         config               0.22.3 enabled    dokku core config plugin
         docker-options       0.22.3 enabled    dokku core docker-options plugin
         domains              0.22.3 enabled    dokku core domains plugin
         enter                0.22.3 enabled    dokku core enter plugin
         git                  0.22.3 enabled    dokku core git plugin
         letsencrypt          0.9.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.22.3 enabled    dokku core logs plugin
         network              0.22.3 enabled    dokku core network plugin
         nginx-vhosts         0.22.3 enabled    dokku core nginx-vhosts plugin
         plugin               0.22.3 enabled    dokku core plugin plugin
         postgres             1.8.1 enabled    dokku postgres service plugin
         proxy                0.22.3 enabled    dokku core proxy plugin
         ps                   0.22.3 enabled    dokku core ps plugin
         redirect             0.6.2 enabled    Plugin for managing application redirects
         repo                 0.22.3 enabled    dokku core repo plugin
         resource             0.22.3 enabled    dokku core resource plugin
         scheduler-docker-local 0.22.3 enabled    dokku core scheduler-docker-local plugin
         shell                0.22.3 enabled    dokku core shell plugin
         ssh-keys             0.22.3 enabled    dokku core ssh-keys plugin
         storage              0.22.3 enabled    dokku core storage plugin
         tags                 0.22.3 enabled    dokku core tags plugin
         tar                  0.22.3 enabled    dokku core tar plugin
         trace                0.22.3 enabled    dokku core trace plugin
</details>

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

DigitalOcean droplet.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by EmilStenstrom** [comment]
@josegonzalez Thank you so much! This is a small but (I think) effective way to make beginner's lives easier!
