### ISSUE TITLE
Implement git:from-image and deprecate tags plugin

### ISSUE THREAD

**Issue by badsyntax** [dokku/dokku#4296]
## Description of problem

I'm using a `Dockerfile` to package my app. I can't follow the dokku/heroku workflow of `git push` and build on my server as my apps take forever to build and this kills my runtime server. 
So I'm building my docker images in CI and publishing to GitHub container registry, but before deploying the app i need to pull the docker image onto the server and tag it. 

It's somewhat awkward to achieve this as I can't use the `dokku` user to interact with `docker` remotely as it's using `sshcommand` which will forward all commands to `/usr/bin/dokku`. 

After reaching out to the dokku maintainers in slack, they suggest we do the following:

> I think the proper way would be to expose like… a git:from-image command
> So you build your image, push it to $LOCATION, and then call that command to deploy that image which would make a temporary repository (or get the existing one and clear out its contents), add a Dockerfile with a FROM $IMAGE, and trigger the deploy as normal 
> That way we avoid rebuild issues that currently happen with the tags plugin
> i think its worth implementing and deprecating the tags plugin

Notes:

- It would be useful to accommodate moving tags (like `latest`) which would require a `docker pull` before deploy.

**Comment by josegonzalez** [comment]
I think what we need to do is the following:

- Create a new trigger called `git-from-directory $APP $DIRECTORY` that will replace the entire repository for an app with the directory and commit it. If it is a new repository, it'll initialize it, otherwise it'll be a clone + replace of everything but the `.git` directory. This should also trigger a `ps:rebuild`.
- Add a git property named `author` that will let folks customize the `--author="Name <email>"` flag on the git commit that will be performed from `git-from-directory`. It should default to `Automatic Commit <automated@$FIRST_GLOBAL_DOMAIN>`.
- Add a `git:from-image` command that takes the image name, creates a temporary `Dockerfile` with that image as it's contents, and calls `git-from-directory`.

I think this `git-from-directory` trigger can also be used for #3458 :)

**Comment by nisseknudsen** [comment]
@josegonzalez : 

- I like the first item - that would remove one copying step in my current implementation
- The third item is great! If I understand correctly: You would continue to leverage the existing Dockerfile build code in Dokku, but kind of "trick" it by simply referring inside the Dockerfile just to the app Docker image as base image - nothing else. Is my understanding correct? I hadn't thought about it, but is then also a good workaround for the moment.

**Comment by josegonzalez** [comment]
Yeah. Lets say you want to deploy [adminer](https://www.adminer.org/), a sql web interface:


```shell
dokku git:from-image adminer adminer:latest
```

This would create a temporary directory with the current app code in it. All the contents would be deleted except for the `.git` directory, and a new `Dockerfile` would be created in that directory with the following as it's contents:

```Dockerfile
FROM adminer:latest
```

Next, there would be a commit (with whatever necessary for author etc) and the resulting repository would then be "pushed" locally, triggering a build. This would allow us to keep history of what was deployed when - you can just pull the repo and do a `git log` - while also leveraging all the existing code around application management.

**Comment by nisseknudsen** [comment]
Nice, I like that. By not building the image pull mechanism, but just relying on the locally available images, you'd also avoid registry authentication etc. in dokku, I suppose.

**Comment by AubreyHewes** [comment]
just my 2 cents....

> I'm using a Dockerfile to package my app. I can't follow the dokku/heroku workflow of git push and build on my server as my apps take forever to build and this kills my runtime server.
So I'm building my docker images in CI and publishing to GitHub container registry, but before deploying the app i need to pull the docker image onto the server and tag it.

So why not in your CI, create a new Dockerfile after the new container registry image... `FROM container-registry-image:tag` and push that to the dokku instance? This would ensure that the new `image:tag` would be pulled and deployed. I am not seeing or understanding the reason for the extra functionality which can be solved by pushing a Dockerfile containing the new tag.

**Comment by josegonzalez** [comment]
I think that workflow _does_ work but its like... a ton of extra steps for users. Folks have been asking for a way to pull docker images through the `dokku` binary for years now, but I never had a good idea around how to introduce that. I think creating a temp git repo on their behalf is a good way to properly support this (nasty IMO) workflow of deploying arbitrary docker images.

Of note, one nice thing this would add is the ability to automate docker pushes from the official github action we've built, since now there isnt a weird workflow of either pushing up a temp repo or attempting to shunt an image into place.

**Comment by AubreyHewes** [comment]
Still do not understand, though that may just be me ;-)

When using Dockerfile deployment you should CD your latest application Dockerfile to dokku (which can depend on an upstream image created by your CI/CD). 

Dokku itself has nothing to do with CI or CD (except being a possible CD destination)... ?

**Comment by josegonzalez** [comment]
There are a ton of people that want to deploy a docker image. To do that, they currently need to:

- pull the image via `docker pull`
- `tags:deploy` it
- avoid `ps:rebuild`, which ignores `tags:deploy`
- avoid git repositories, which will result in breaking `tags:deploy`

The above doesn't quite work without root server access, so anyone who only exposes the `dokku` user cannot use the above workflow without an extra plugin.

They can also do a git repository workflow, but there are more than a few steps needed to do that correctly and keep history.

This workflow implements all those steps for users in a way that allows me to ignore exposing `docker pull` as a direct command in dokku. It keeps the git workflow (so you get history) and enables a whole class of users to properly deploy docker images.

There is other stuff this might enable, like an app library, but the main idea is to enable a class of users that has been typically under-served.

**Comment by AubreyHewes** [comment]
Or Just push a `Dockerfile` that is `FROM wanted image`...

**Comment by josegonzalez** [comment]
Again, someone needs to:

- clone the remote repo (or initialize a new one if the remote app doesnt yet exist)
- write a dockerfile (and remove all the other contents)
- push it

I actually outlined this workflow in the github action for a user, which proves the point that while it seems straightforward, its not going to be the first thing our users do (and they won't do it right). It's not a ton of work, but enables stuff like:

- deploying an image straight from a remote registry
- simpler CI/CD processes
- webhook wrappers
- app stores (think a single binary that can read the ansible yaml task to setup an app and then deploy... the wordpress image as is)

**Comment by badsyntax** [comment]
> just my 2 cents.... correct me if I am missing something
> 
> > I'm using a Dockerfile to package my app. I can't follow the dokku/heroku workflow of git push and build on my server as my apps take forever to build and this kills my runtime server.
> > So I'm building my docker images in CI and publishing to GitHub container registry, but before deploying the app i need to pull the docker image onto the server and tag it.
> 
> So why not, in your CI/CD; create a new Dockerfile after the new container registry image... `FROM container-registry-image:tag` and push that to the dokku instance?. This would ensure that the new `image:tag` would be pulled and deployed.
> 
> I am not seeing or understanding the reason for extra functionality which can be solved by pushing a Dockerfile containing the new tag.

That's basically what I'm doing. Perhaps my [my blog post](https://richardwillis.info/blog/deploy-dokku-app-remote-docker-image) gives a better overview of my scenario. I'd prefer if this feature was supported by dokku, but I'm not against keeping my deploy setup as is described in the blog post.

**Comment by AubreyHewes** [comment]
@badsyntax this is the way. Though as you can see there was a lot of on and off discussion about this. 

I think I just am against turning dokku into a CI/CD platform.. CI should be done elsewhere and push for CD.. IMHO.

nice blog post by the way :+1:

**Comment by AubreyHewes** [comment]
@badsyntax sidenote: I see the problem in your CI... you should label the newly built image with the new version... and then create a new dockerfile that uses that specific label. This forces dokku Dockerfile deployment to update the image. If you always use latest then the docker engine will always use the latest (which will never change from the first pull; out of the box docker).

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
