### ISSUE TITLE
Possible to deploy (on port 80) without virtual hosting?

### ISSUE THREAD

**Issue by stuartpb** [dokku/dokku#431]
Maybe I'm reading the docs wrong: is there a way I can use Dokku to just push an app meant to apply for the entire domain, rather than as a virtual host? The readme says it creates ports if VHOST is missing or invalid- is there a way to tell it to use the default/base ports (80/443)?

I'm just looking for an image I can quickly spin up for a dedicated server on DigitalOcean that lets me `git push` an app for the server to run.

**Comment by sibeliusseraphini** [comment]
You can change your /home/dokku/aloudflare.com/nginx.conf to:

    upstream flask-domains { server 127.0.0.1:PORT; }
      server {
        listen        [::]:80;
        listen        80;
        server_name   external_ip;

        location / {
          proxy_pass http://flask-domains;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection upgrade;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
    }

your PORT is the port number inside the PORT file (/home/dokku/appname/PORT), 
and external_ip is the IP of your app or the domain name
