### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by capriciousduck** [dokku/dokku#4314]
Is it possible to run Dokku on heroku?

**Comment by josegonzalez** [comment]
No, Dokku is something of a Heroku clone. Please use Heroku directly if that is your intention.

**Comment by capriciousduck** [comment]
Are there any free VPS solutions so that I can host Dokku?

**Comment by josegonzalez** [comment]
You can host a Vagrant VM locally - that is included with this repository.

I do not think there are any free VPS services out there. Giving away free compute seems like the opposite of a good business strategy.

Heroku has a free tier, which I encourage you to use. Hopefully that meets your needs.
