### ISSUE TITLE
Q: Resetting X-Forwarded-For header?

### ISSUE THREAD

**Issue by bjornpost** [dokku/dokku#4339]
Hi,

I was wondering why the `X-Forwarded-For` header is being reset with the `$remote_addr` value in the [default Dokku nginx config](https://github.com/dokku/dokku/blob/e64b69248a4327bc41b3a3e1eb3736ccfb5b6bbb/plugins/nginx-vhosts/templates/nginx.conf.sigil#L100). This causes issues with fetching the client's IP address with an intermediate proxy server, like this example:

Client (1.1.1.1) --> Intermediate proxy (2.2.2.2) --> Dokku nginx --> Dokku app

In this case, the user's IP address in the Dokku app is reported as 2.2.2.2 (iso 1.1.1.1). This is because the Dokku nginx config overwrites any present `X-Forwarded-For` header with the current `$remote_addr` (2.2.2.2), rather than appending a second IP address.

An easy fix for this issue would be to replace $remote_addr with `$proxy_add_x_forwarded_for`.

P.s. Thank you for Dokku <3

**Comment by josegonzalez** [comment]
I did a bit of research, and that seems reasonable. Mind making a pull request?

**Comment by bjornpost** [comment]
Will do! 👌🏻

**Comment by bjornpost** [comment]
PR is ready. Just to be sure: if you're not running Dokku behind an intermediate proxy/load balancer, this PR will allow clients to set arbitrary headers.

For example:
```bash
curl -H "X-Forwarded-For: 1.1.1.1, 2.2.2.2, <iframe src=//malware.attack>" https://dokku-app-not-behind-proxy.example.com/
```

Will be available in your application as:

```
 ["HTTP_X_FORWARDED_FOR"]=>
  string(63) "1.1.1.1, 2.2.2.2, <iframe src=//malware.attack>, [client ip]"
```

Seems like a bit of a theoretical security issue, but I'm no expert. Just wanted to point it out :-). 

https://research.securitum.com/x-forwarded-for-header-security-problems/

**Comment by josegonzalez** [comment]
Lets chat in the PR :)
