### ISSUE TITLE
docs darkmode [for fun]

### ISSUE THREAD

**Issue by AubreyHewes** [dokku/dokku#4344]
## Description of problem

Documentation should have a dark mode toggle

### How reproducible

Just look at it

### Steps to Reproduce

1. Go to the documentation site
2. Get [blinded by the lights](https://www.youtube.com/watch?v=sTNsHSCXfmo)

#### Actual Results

1. Get [blinded by the lights](https://www.youtube.com/watch?v=sTNsHSCXfmo)

#### Expected Results

1.  Some toggle (that remembers me; cookie)
2.  Not getting [blinded by the lights](https://www.youtube.com/watch?v=sTNsHSCXfmo)

**Comment by josegonzalez** [comment]
I did a first pass at dark mode, but if anyone has improvements, I'm all ears :)

**Comment by AubreyHewes** [comment]
chrome on linux does not yet listen to os-preference (without desktop-file tweaks).. a cookie would solve this for recurring users (though requires front and back changes).
