### ISSUE TITLE
Protect the web installer with a randomly generated password to not expose SSH keys before setup is done

### ISSUE THREAD

**Issue by bschne** [dokku/dokku#4361]
After setting up dokku on a server from the console, the web installer interface is publicly accessible until setup is completed there. The problem with this is that it publicly exposes SSH keys that have been previously added to the `.ssh/authorized_keys` file and can thus be used to access the server, which is risky even if it's only temporarily.

I would therefore suggest that it might be better to do the following after finishing set-up on the console:

1. Randomly generate a password
2. Only expose the installer protected by that password
3. Print the password to the console that was used to set up dokku, together with a short instruction text telling the user to enter it to finish the configuration

**Comment by josegonzalez** [comment]
Closing in favor of #2247. Thanks for the report.

**Comment by bschne** [comment]
Thanks & sorry, missed that one!
