### ISSUE TITLE
Error: Unknown error installing "12.x" of node

### ISSUE THREAD

**Issue by mightytyphoon** [dokku/dokku#4362]
Hi,

I have the problem described on heroku help [here](https://devcenter.heroku.com/articles/troubleshooting-node-deploys#aws-proxy-error). But I am not using AWS, also I don't have HTTP_PROXY and HTTPS_PROXY env_vars set. I am currently on the problem because it is urgent, any help or ideas is appreciated, thanks. I tried setting engines to several different versions of node in package.json (last, 14x, 10x, 8x) without any change.

The VPS is from Godaddy, under ubuntu 18.04.5 LTS

Output from dokku :
```
remote: -----> Cleaning up...
remote: -----> Building yperlab from herokuish
remote: -----> Adding BUILD_ENV to build environment...
remote:        -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 12.x...
remote:        Error: Unknown error installing "12.x" of node
remote:
remote: -----> Build failed
remote: 
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote: 2021/01/27 21:13:58 exit status 1
remote: 2021/01/27 14:13:58 exit status 1
To dokku:app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku:app'
```
Bye.

**Comment by josegonzalez** [comment]
This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [irc or slack channels](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels). 

Issues pertaining to buildpacks will be closed and/or locked.
