### ISSUE TITLE
Where are my static files in a Dokku based installation?

### ISSUE THREAD

**Issue by shaief** [dokku/dokku#437]
I finished a dokku deployment on a Digitalocean server. My application seems to work, except for my static files.

Here are the relevant parts of my settings.py file:

```
PROJECT_DIR = Path(__file__).absolute().ancestor(2)

MEDIA_ROOT = ''
MEDIA_URL = ''
STATIC_ROOT = ''
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    PROJECT_DIR.child('static'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STATIC_ROOT = PROJECT_DIR.child('staticroot')
```

Does someone know how can i point my app at my static files on a dokku based system? Thanks!

**Comment by Suor** [comment]
This article is explaining how to serve static files with python, which is not usually what you want to do in production. How do I set up things to serve them with nginx?

**Comment by josegonzalez** [comment]
Use the php buildpack, which can serve any static file via nginx or apache.

**Comment by Suor** [comment]
I have django app, why should I use php buildpack? It could probably serve static, but will fail with everything else.

**Comment by josegonzalez** [comment]
Oh, I thought you meant just static applications.

If you are using the python buildpack, then the heroku docs should suffice. Here is how to set it up with django: https://devcenter.heroku.com/articles/django-assets

**Comment by josegonzalez** [comment]
Note: the buildpack will almost certainly serve up the files from `static`, if not, thats an issue with the buildpack, not dokku.

**Comment by Suor** [comment]
Yeah, it advises to use whitenoise, but that's not you want to do on
production.

**Comment by josegonzalez** [comment]
Then I suggest you use a CDN url for your static assets pointing at your app server.

**Comment by Suor** [comment]
If I want to serve static with nginx then that couldn't be done by
buildpack alone, cause it knows nothing about nginx out of container.

**Comment by josegonzalez** [comment]
You can just point the cdn at your server, no need to configure nginx any more. The cdn will hit your url for the asset, cache it, and then serve it up.

**Comment by Suor** [comment]
Then I'll need to create 2 apps one for dynamic and one for static? Also,
static is not entirely static as I need to collect and preprocess it.

This way, I will, however, loose atomicity of deploys and done my users
will end up in broken state.
7 марта 2015 г. 12:09 пользователь "Jose Diaz-Gonzalez" <
notifications@github.com> написал:

**Comment by Suor** [comment]
Oh, I didn't get that. What if I don't want CDN at all?

**Comment by josegonzalez** [comment]
No one said anything about creating two applications. You make one application, use the recommendations of heroku to serve static assets using whitenoise, place the cdn in front of that for static assets, and you are done.

If you don't want a CDN, then I personally don't see what the concern is about performance re: production. You'll need to customize your buildpack to have nginx serve the assets, which is outside of dokku's domain (we just use heroku's buildpacks and let you use your own if specified).

**Comment by Suor** [comment]
This has nothing to do with buildpack. It does the job - prepares static,
then I am supposed to point nginx to that, but I can't cause it's hidden in
a docker container.

So there is a solution in dokku responsibility domain - add a setting or
something to mount a directory inside container and serve it with nginx.

**Comment by josegonzalez** [comment]
I have to respectfully disagree about whose job it is to host static assets.

PHP's buildpack includes apache/nginx support by necessity, and as such includes native static asset handling as a side-effect. If you customized your python buildpack to place nginx *in front of* the python webserver you are using, then you would also have the same outcome. Again, this is all inside of the buildpack.

While it would be quite nice to serve static assets from dokku using one of several features, it's not something that I think should be in the core - as it would conflict with functionality from buildpacks that already do this properly, such as PHP - but could be a custom plugin you create. 

If you'd like to solve this problem for your applications, you could write such a plugin to add docker options for mounting a directory in the container when running a python app, and then customize your dokku nginx conf for that app to serve up assets from that directory. You can use [this plugin](https://github.com/dyson/dokku-docker-options) to add custom options, and there should be documentation on using a custom nginx configuration in the docs.
