### ISSUE TITLE
failing to delete old image prevents deployment of app

### ISSUE THREAD

**Issue by ltalirz** [dokku/dokku#4371]
## Description of problem

I just upgraded to dokku 0.23.1 and wanted to try the new `git:sync --build` command.

When trying to update a running app (seekpath), I got 
```
dokku git:sync --build seekpath https://github.com/materialscloud-org/tools-seekpath v20.09.1
...
-----> Releasing seekpath...
Failed to delete old image (Error response from daemon: conflict: unable to delete d11427bb766f (cannot be forced) - image has dependent child images)
2021/02/02 17:05:42 exit status 1
2021/02/02 17:05:42 exit status 1
2021/02/02 17:05:42 exit status 1
 !     exit status 1
```
Note: I started by specifying the git tag that was already deployed, i.e. docker could reuse the cache at every step. I'm also omitting some trial/error steps here.

There was no image with id `d11427bb766f` in `docker image list`, but as [mentioned here](https://stackoverflow.com/questions/38118791/can-t-delete-docker-image-with-dependent-child-images), this sort of thing can happen when there are multiple tags to the same image and one tries to delete the image by ID.

Deleting all tags corresponding to the app name and rebuilding the app solved the issue.

```
ubuntu@dev-dokku:~$ docker image list | grep seek
dokku/seekpath2                  latest                 5ae3c8ea1403   2 months ago        1.3GB
dokku/seekpath                   latest                 232608e14bca   41 years ago        1.3GB
ubuntu@dev-dokku:~$ docker rmi dokku/seekpath2 dokku/seekpath
ubuntu@dev-dokku:~$ dokku ps:rebuild seekpath
```

Easter egg: it seems docker was convinced that `dokku/seekpath`  was built around the dawn of unix time, several decades before docker was created.

Repeating 
```
dokku git:sync --build seekpath https://github.com/materialscloud-org/tools-seekpath v20.09.1
```
afterwards went fine.

### How reproducible

If necessary, I can try to make a standalone example - perhaps the mechanism is already clear from the symptoms.

#### Expected Results

Besides the issue with multiple tags (probably related to the upgrade from a previous dokku version), my main concern here is that this error prevented deployment - without a way to ignore it.
If I had been a regular user, there may have been nothing that I could have done to fix deployment.

I would expect that it is possible to deploy an app even if deleting previous images fails (no matter for what reason).

### `dokku report APP_NAME` output

$ dokku report seekpath
-----> uname: Linux dev-dokku 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:          32167        3152       11139          14       17875       28667
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.3
        API version:       1.41
        Go version:        go1.13.15
        Git commit:        48d30b5
        Built:             Fri Jan 29 14:33:13 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.3
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       46229ca
         Built:            Fri Jan 29 14:31:25 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.3
         GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
        runc:
         Version:          1.0.0-rc92
         GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

       Server:
        Containers: 22
         Running: 20
         Paused: 0
         Stopped: 2
        Images: 315
        Server Version: 20.10.3
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
        Default Runtime: runc
WARNING: No swap limit support
        Init Binary: docker-init
        containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
        runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 4.15.0-122-generic
        Operating System: Ubuntu 18.04.5 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 8
        Total Memory: 31.41GiB
        Name: dev-dokku
        ID: 73QI:TDXC:BCRL:7V3Z:OIAI:F5BP:23MX:57OI:47VR:RYUK:EEHC:2FN6
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.17.1
-----> sigil version: 0.6.0
-----> herokuish version:
       herokuish: 0.5.18
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v218
         heroku-buildpack-nodejs    v175
         heroku-buildpack-clojure   v85
         heroku-buildpack-python    v177
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v179
         heroku-buildpack-go        v145
         buildpack-nginx            v14
-----> dokku version: dokku version 0.23.1
-----> plugn version: plugn: 0.6.1
-----> dokku plugins:
         00_dokku-standard    0.23.1 enabled    dokku core standard plugin
         20_events            0.23.1 enabled    dokku core events logging plugin
         acl                  1.5.1 enabled    dokku plugin that can be used to restrict push privileges for app to certain users
         app-json             0.23.1 enabled    dokku core app-json plugin
         apps                 0.23.1 enabled    dokku core apps plugin
         builder-cnb          0.23.1 enabled    dokku core builder-cnb plugin
         builder-dockerfile   0.23.1 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.23.1 enabled    dokku core builder-herokuish plugin
         buildpacks           0.23.1 enabled    dokku core buildpacks plugin
         certs                0.23.1 enabled    dokku core certificate management plugin
         checks               0.23.1 enabled    dokku core checks plugin
         clone                0.4.1 enabled    dokku git clone plugin
         common               0.23.1 enabled    dokku core common plugin
         config               0.23.1 enabled    dokku core config plugin
         cron                 0.23.1 enabled    dokku core cron plugin
         docker-options       0.23.1 enabled    dokku core docker-options plugin
         domains              0.23.1 enabled    dokku core domains plugin
         enter                0.23.1 enabled    dokku core enter plugin
         git                  0.23.1 enabled    dokku core git plugin
         global-cert          0.4.5 enabled    manages a global certificate for dokku
         logs                 0.23.1 enabled    dokku core logs plugin
         network              0.23.1 enabled    dokku core network plugin
         nginx-vhosts         0.23.1 enabled    dokku core nginx-vhosts plugin
         plugin               0.23.1 enabled    dokku core plugin plugin
         postgres             1.11.6 enabled    dokku postgres service plugin
         proxy                0.23.1 enabled    dokku core proxy plugin
         ps                   0.23.1 enabled    dokku core ps plugin
         repo                 0.23.1 enabled    dokku core repo plugin
         resource             0.23.1 enabled    dokku core resource plugin
         scheduler-docker-local 0.23.1 enabled    dokku core scheduler-docker-local plugin
         shell                0.23.1 enabled    dokku core shell plugin
         ssh-keys             0.23.1 enabled    dokku core ssh-keys plugin
         storage              0.23.1 enabled    dokku core storage plugin
         tags                 0.23.1 enabled    dokku core tags plugin
         tar                  0.23.1 enabled    dokku core tar plugin
         trace                0.23.1 enabled    dokku core trace plugin
=====> seekpath app information
       App deploy source:
       App dir:                       /home/dokku/seekpath
       App locked:                    false
=====> seekpath buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
CN = *.matcloud.xyz
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> seekpath ssl information
       Ssl dir:                       /home/dokku/seekpath/tls
       Ssl enabled:                   true
       Ssl hostnames:                 *.matcloud.xyz
       Ssl expires at:                Apr  4 12:43:43 2021 GMT
       Ssl issuer:                    C = US, O =
       Ssl starts at:                 Jan  4 12:43:43 2021 GMT
       Ssl subject:                   subject=CN = *.matcloud.xyz
       Ssl verified:                  self signed
=====> seekpath checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> seekpath cron information
       Cron task count:               0
=====> seekpath docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> seekpath domains information
       Domains app enabled:           true
       Domains app vhosts:            seekpath.matcloud.xyz
       Domains global enabled:        true
       Domains global vhosts:         matcloud.xyz
=====> seekpath git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       076938b
       Git last updated at:           1612281178
=====> seekpath logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> seekpath network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.2:80
=====> seekpath nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/seekpath-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/seekpath-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1612283029
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
=====> seekpath proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:80 https:443:80 test:123:123
       Proxy type:                    nginx
=====> seekpath ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 8e2976ec532)
=====> seekpath resource information
       _default_ limit cpu:           4
       _default_ limit memory:        8G
=====> seekpath scheduler-docker-local information
       Scheduler docker local disable chown:
=====> seekpath storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

dokku ansible role

**Comment by josegonzalez** [comment]
Yeah if you have a way to replicate this so I can write a bats test, that would be awesome. Was this app somehow previously deployed to another app name?

**Comment by josegonzalez** [comment]
Will be released in next docker-image-labeler release :)

**Comment by ltalirz** [comment]
Cheers!
