### ISSUE TITLE
git:sync prompts for credentials - consider timeout/non-interactive mode?

### ISSUE THREAD

**Issue by ltalirz** [dokku/dokku#4375]
## Description of problem

This was originally reported for the dokku clone plugin at https://github.com/dokku/ansible-dokku/issues/92 but also applies to `git:sync`:

On github, it will prompt for credentials when told to sync a repository that is not valid (say, the url contains a typo)
```
$ dokku git:sync seekpath https://github.com/materialscloud-org3/tools-seekpath2
-----> Cloning seekpath from https://github.com/materialscloud-org3/tools-seekpath2#master
Username for 'https://github.com':
```

This is a problem when using `git:sync` as part of automation tools like `ansible`, since it will hang forever without any output.

### How reproducible

Every time.

### Steps to Reproduce

1. Create a new app
2. Use `dokku git:sync seekpath https://github.com/materialscloud-org3/tools-seekpath2`

#### Actual Results

Hangs on prompt.

#### Expected Results

Perhaps a "non-interactive mode" that will fail when prompted for credentials?
This might apply to other dokku commands as well. Could be toggled via an environment variable?

The related, broader question is to which degree the `dokku` binary should support both interactive and non-interactive use, and whether automation tools like ansible should eventually move to another form of API.

## Environment Information

dokku v0.23.1

**Comment by josegonzalez** [comment]
I think I should actually make it fully non-interactive. This will ensure users are using one of the following methods for syncing private repositories:

- ssh key (preferred)
- netrc (accepted basically by all tools)
- libsecret (has a git credential helper integration)

**Comment by josegonzalez** [comment]
Going to wrap this work into #4364.
