### ISSUE TITLE
Push failing due to vendor folder custom gem

### ISSUE THREAD

**Issue by weefunker** [dokku/dokku#4381]
During the initial push for a new app, the push is failing with the push rejected error code because I am using a custom (private) gem in the vendor folder. 

The Dokku bundler tries to install from source at `vendor/custom_gem_name`

Stalls for about 10 plus minutes then finally times out.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Closing as it's been two weeks since the initial report with no update. Please comment if there is anything to follow up on and we'll reopen the issue as appropriate.
