### ISSUE TITLE
[feature request] Support nginx ssl_client_certificate

### ISSUE THREAD

**Issue by mjmaurer** [dokku/dokku#4409]
## Description of problem

Right now, dokku only supports a crt + key pair for TLS. `ssl_client_certificate` is another option. It allows for signing only with a specific client. Cloudflare is my usecase, and they provide a good [description of the difference here](https://support.cloudflare.com/hc/en-us/articles/204899617-Authenticated-Origin-Pulls). (i.e. I want all 443 traffic to come from cloudflare).

It would be nice to support this with the `certs` plugin. `certs:add-client` could add the required nginx config.

### Issues with my current solution

Running `dokku proxy:ports-add https:443:5000` intelligently changes the nginx config to include the crt + key. So unfortunately I have to go around Dokku to support SSL with `ssl_client_certificate`, or otherwise use an unused self signed certificate next to the Cloudflare one.

**Comment by josegonzalez** [comment]
Is there a specific filetype for that file that will allow us to differentiate it with the crt+key pair? Or maybe a command to validate the file is valid for ssl_client_certificate?

**Comment by mjmaurer** [comment]
I'm sorry, I misunderstood the use of ssl_client_certificate. I thought it was possible to use by itself as a means of authn. Turns out you still need the TLS handshake (with key pair) to enable it. This feature is a lot less useful than I thought. Still nice convenience, but I'll describe below the easy DIY solution while answering your questions.

> Is there a specific filetype for that file that will allow us to differentiate it with the crt+key pair?

Both go in the `server {}` block in nginx.conf. I noticed hsts is implemented as an extra file in `nginx.conf.d` so in that sense it could be differentiated. For example, here's what my `cloudflare.conf` in that directory looks like:

```
ssl_client_certificate /etc/nginx/client-certs/cloudflare.crt;
ssl_verify_client on;
```

> Or maybe a command to validate the file is valid for ssl_client_certificate?

Because they are client specific, I believe logic would need to be added for each provider.

**Comment by josegonzalez** [comment]
I'm going to close this issue. Seems the feature is of limited utility - it's for ensuring requests come from a specific network proxy - and would be a bit annoying to implement (there is also a `ssl_trusted_certificate`, which do we use? what happens if a user also includes a key?).

If someone feels strongly otherwise, please comment with a potential work-plan and more notes as to how the feature should work (both from a user perspective as well as internally).
