### ISSUE TITLE
docs: title of Process Scaling menu item is misleading

### ISSUE THREAD

**Issue by nerg4l** [dokku/dokku#4426]
The documentation has a menu item called "Process Scaling" under "Process Management". This item opens "Process and Container Management" (`/docs/processes/process-management/`) which describes the `ps` plugin. First of all, `ps` plugin does much more than just "Process Scaling". The title of the page is more descriptive than the menu item. Secondly, I was looking for the `ps` plugin docs and I was not able to find it until opening every item under "Process Management".

**Comment by josegonzalez** [comment]
What about a header section called "Interacting with Processes"? The title of the page in question (and the sidebar) would be changed to "Process Management".

**Comment by nerg4l** [comment]
Perfect
