### ISSUE TITLE
 Add notice about git 1.8.3 support

### ISSUE THREAD

**Issue by Lieunoir** [dokku/dokku#4429]
The recent changes in https://github.com/dokku/dokku/pull/4421 make use of the -C git option, which was added in version 1.8.5. Pushing to a git repository using version 1.8.3 fails because of this (or I didn't look hard enough to make it work).

git 1.8.3 is the default version for CentOS 7, so it may be interesting to add a warning about this in the migration guide.

**Comment by josegonzalez** [comment]
What the heck CentOS!

Would you be interested in making a PR to swap those to `GIT_DIR` instead? That would fix this issue and would be a patch release for sure.

Thoughts on future CentOS support, re the CentOS stream business? I don't even feel like adding support for them because of the whole EOL thing but I feel as though we have _some_ CentOS users that might care about this sort of thing.

**Comment by Lieunoir** [comment]
> What the heck CentOS!

Yeah, we still exist haha, but maybe not for long

> Would you be interested in making a PR to swap those to `GIT_DIR` instead? That would fix this issue and would be a patch release for sure.

Sure! I'll try to get something working soon
> Thoughts on future CentOS support, re the CentOS stream business? I don't even feel like adding support for them because of the whole EOL thing but I feel as though we have _some_ CentOS users that might care about this sort of thing.

Honnestly I don't know, we were already thinking about maybe migrating to debian so it might just speed up the process. The main appeal for us used to be the long support time, but it was less and less relevant for us anyway...

**Comment by josegonzalez** [comment]
Would you migrate to Debian or Ubuntu? I haven't been super on top of releasing for Debian, but could be convinced to do so if that is what the community wants.

**Comment by josegonzalez** [comment]
Also, nice pallas' cat :)

**Comment by josegonzalez** [comment]
Gonna close this as there is a PR open, but still interested in your thoughts re: host OS.
