### ISSUE TITLE
documentation page titles on dokku.com

### ISSUE THREAD

**Issue by michaelwood** [dokku/dokku#4433]
## Description of problem

[Docs website](https://dokku.com/docs/configuration/environment-variables/) doesn't include the title of doc. When looking down a list of web search results for a dokku related things it is more difficult to work out which link to click.

### Steps to Reproduce

1. Do a [websearch](https://duckduckgo.com/?q=dokku+log+command
) for some dokku documentation

#### Actual Results

All pages have the same title

#### Expected Results

It'd be really nice if the title were more along the lines of "Dokku - docs - $page_name - etc"

**Comment by josegonzalez** [comment]
Good call. Will require a few changes to the viewdocs fork the docs run to extract the first `h1` from the page, but should be doable.

**Comment by lovasoa** [comment]
I still see the problem : 

![image](https://user-images.githubusercontent.com/552629/112510070-60e00300-8d91-11eb-91b0-882e07beb3cc.png)

![image](https://user-images.githubusercontent.com/552629/112510242-8a992a00-8d91-11eb-8449-9c5ecf0cb446.png)

**Comment by josegonzalez** [comment]
Interesting, looks like the old versions of the docs are being indexed. Should be "fun" to fix - probably set `canonical` meta key or something?

**Comment by josegonzalez** [comment]
@lovasoa i've added issue #4521 to track that work.
