### ISSUE TITLE
dokku upgrade instructions improvement

### ISSUE THREAD

**Issue by rjaus** [dokku/dokku#4434]
In regards to this issue: https://github.com/dokku/dokku/issues/3178

The after-upgrading instructions on dokku.com (https://dokku.com/docs/getting-started/upgrading/#after-upgrading) should be changed from:

```
dokku ps:rebuild --all
```

```
cd /home/dokku
dokku ps:rebuild --all
```

The current instructions result in (after an upgrade):
```
root@dokku:~# dokku ps:rebuild --all
 !     Running rebuild in serial mode
-----> Running rebuild against app super-performance-api
find: Failed to change directory: /root: Permission denied
find: Failed to restore initial working directory: /root: Permission denied
2021/02/25 05:10:52 exit status 1
 !     Error running rebuild against app super-performance-api: exit status 1
 !     rebuild command returned 1 errors

```

Dokku is excellent!! Keep up the great work team!

**Comment by josegonzalez** [comment]
Thanks for reporting. This was actually a bug, and I've filed a PR to fix it in the next patch release.

Closing as there is a pull request open.
