### ISSUE TITLE
Docs version selector not working

### ISSUE THREAD

**Issue by RyukerLiu** [dokku/dokku#4440]
### How reproducible

Go to https://dokku.com/docs/getting-started/installation/

Open the version selector

![image](https://user-images.githubusercontent.com/48594384/109160297-91437a00-77b0-11eb-85e9-5b8c43a6e282.png)

And no versions could select

**Comment by HugoPoi** [comment]
Confirm this `versions.json` is missing, the front get a 404

**Comment by josegonzalez** [comment]
This should be fixed now, sorry about that.
