### ISSUE TITLE
Support Mac OS X

### ISSUE THREAD

**Issue by shalakhin** [dokku/dokku#445]
Hi everyone!

As Docker 0.8 supports Mac OS X it should be possible to use dokku from Mac.

**Comment by glawson6** [comment]
For those of us that run Mac Mini as a server , this is the PERFECT solution . It is unfortunate that you have decided not to pursue this further. In the meantime I may have to consider the pf to forward all requests to a VM running Ubunutu and Dokku on a Mac Mini.............Feels like a hack......

**Comment by josegonzalez** [comment]
@glawson6 Docker runs on OS X inside of Vagrant, so you're not even really doing anything different. We have an open issue for docker-based deployments, which will make it a bit easier to run "directly" on OS X, but it's still the same hack...
