### ISSUE TITLE
Couldn't use heroku-community/apt in .buildpack

### ISSUE THREAD

**Issue by xward** [dokku/dokku#4452]
## Description of problem

Couldn't use `heroku-community/apt` in my .buildpacks file, I had to use https://github.com/heroku/heroku-buildpack-apt instead.

### How reproducible
100 %

### Steps to Reproduce

.buildpacks file:
```
heroku-community/apt
```
then deploy

#### Actual Results
```
=====> Downloading Buildpack: heroku-community/apt
To <project>:pnglight
 ! [remote rejected]     chore/pngquant -> master (pre-receive hook declined)
error: failed to push some refs to '<project>:pnglight'
```

#### Expected Results
deploy success with the buildpack

**Comment by josegonzalez** [comment]
We can probably modify the `buildpacks#post-extract` trigger to parse/rewrite the file if it exists. We should 100% notify the user if this happens. Also just thinking we should notify them if we're overwriting their buildpacks too...

**Comment by josegonzalez** [comment]
Closing as a pull request exists.
