### ISSUE TITLE
Docs: Broken link in git.md

### ISSUE THREAD

**Issue by cstuder** [dokku/dokku#4455]
The link on line https://github.com/dokku/dokku/blame/v0.24.0/docs/deployment/methods/git.md#L149 is broken:

```md
See the [dockerfile documentation](/docs/deployment/methods/dockerfiles.md) to learn about the different ways to configure Dockerfile-based deploys.
```

Is it supposed to go to [`docs/deployment/builders/dockerfiles.md`](https://github.com/dokku/dokku/blob/v0.24.0/docs/deployment/builders/dockerfiles.md)?

**Comment by josegonzalez** [comment]
Closed by #4456, thanks for the issue!
