### ISSUE TITLE
"Clone in progress" after git:sync fails during release

### ISSUE THREAD

**Issue by matijakolaric** [dokku/dokku#4458]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you'd like to sponsor specific functionality, see the project's [Sponsoring](https://github.com/dokku/.github/blob/master/SPONSORING.md) document.
>
> If you need help figuring out how to use a specific buildpack, are seeing an issue in during the buildpack process, or are having issues using multiple buildpacks, please see our [slack channels or github discussion board](https://dokku.com/docs/getting-started/where-to-get-help/#monitored-locations). Issues pertaining to buildpacks may be closed and locked.
>
> If you need support for a version of Dokku that is more than a year old, your issue may be closed without an answer. Please upgrade to a recent version.

## Description of problem

If git:sync fails during release, the next time it is run, there is an error "Clone in progress".

### Steps to Reproduce

1. Add an error-creating command to release: in Procfile
2. run git:sync --build
3. run git:sync --build  again

#### Actual Results

error "Clone in progress"
after deleting /var/lib/dokku/data/git/<app>/ folder, all is fine

#### Expected Results

git:sync to start over without a need to manually delete a folder.

Removed the rest, as this is not related to environment.

dokku version 0.24.0

**Comment by josegonzalez** [comment]
Did the first `git:sync` fail, or did you ctrl+c it?

I think we can add a command similar to `apps:unlock` to allow users to remove the clone. Maybe `git:unlock-clone`?

**Comment by matijakolaric** [comment]
It failed. (I dont excpect an app to handle CTRL-C nicely.)
It is a Django app, and I tested a bit, it happens when it fails on collect static (no folder), database migrations (wrong password) or commands in Procfile under release.

I must say that the error messageis a bit confusing, as there is nothing going on. I think "lock" should be somewhere in that message. "Clone in progress or failed, lock present, see git:unlock." I think git:unlock would be best in that case. It only took some 2 minutes to figure out what to delete, but then, not everyone may be as fast.

It would be nice if the error could be handled gracefully, but I have no clue if bash has try/catch.

**Comment by Akirtovskis** [comment]
Facing the same issue and even if first build succeeds, second one is always failing with "Clone in progress" error. 

I am also fairly sure, that this didn't happen on the previous version.

**Comment by josegonzalez** [comment]
So I think the fix here is as follows:

- Add `git:unlock` command that is similar to `apps:unlock`, except it deletes the clone folder
- Modify the existing `git:sync` command to allow a developer to remove a lock if there is a tty (we have a `has_tty` function in the core that can be used) and then would proceed with the sync call.
- Modify the error in `git:sync` to tell the developer what to do when there is no tty.
- Modify `git:sync` to return with a different exit code (5? 15?) when a lock exists and it was not removed
  - Might be worth doing the same for `apps:unlock`, and maybe documenting error codes somewhere...
- Take a look at why the `git:sync` command fails to remove the temp clone on failure.

I'm dealing with something of a medical emergency over the next few weeks so my response here will be quite slow. That said, if anyone wants to submit a PR for any/all of the above, that would be _super_ useful.

**Comment by Akirtovskis** [comment]
@josegonzalez firstly, take care and absolutely no worries. 🤞 

Secondly, thanks for the elaborate response, despite my very limited knowledge of Go, I will try to have a go at this.

**Comment by josegonzalez** [comment]
All the code referenced here should be in shell :)

**Comment by matijakolaric** [comment]
@josegonzalez I think @Akirtovskis meant we will be playing Go until you get back to normal.

**Comment by josegonzalez** [comment]
Closed by #4465.
