### ISSUE TITLE
Add flag for linking vs copying ssl certificates

### ISSUE THREAD

**Issue by matijakolaric** [dokku/dokku#4459]
This is a proposal to take a different look at certificates.

The use case here is to able to use one set of certificates for many apps, using wildcards.

LetsEncrypt now supports wildcards, and it is simple for some DNS providers, like DigitalOcean. The same is with may others.

So, the proposal is to be able to add paths to certs, that get copied over to nginx configuration, without moving/copying the actual files. So, when certificates are renewed (using certbot), everything works. 

.pem files should work without conversion

I hope this makes sense.

**Comment by josegonzalez** [comment]
Its not clear what you would like to do. Are you saying certs:add should be able to take _only_ a pem key? Or that it should somehow be a symlink?

Also, if you could output the contents of `dokku report` so I know what version you're basing this on, that would be awesome :)

**Comment by matijakolaric** [comment]
Sorry, ok, what I really want is a way to say:
Add these paths to /home/dokku/dmp/nginx.conf without touching the files.

So, instead of:
```
       ssl_certificate           /home/dokku/dmp/tls/server.crt;
       ssl_certificate_key       /home/dokku/dmp/tls/server.key;
```

I want:
```
        ssl_certificate         /etc/letsencrypt/live/thatgreenthing.uk/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/thatgreenthing.uk/privkey.pem;]
```

The certs linked are for *.thatgreenthing.uk, so I am using them for many client containers. When they are renewed, everything stays the same in the latter case.

So, something like:

`dokku certs:add-paths dmp /etc/letsencrypt/live/thatgreenthing.uk/fullchain.pem /etc/letsencrypt/live/thatgreenthing.uk/privkey.pem
`

I hope it make sense

Matija

-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           1987         527         182           1        1278        1303
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.4
        API version:       1.41
        Go version:        go1.13.15
        Git commit:        d3cb89e
        Built:             Thu Feb 25 07:05:27 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.4
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       363e9a8
         Built:            Thu Feb 25 07:03:23 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.3
         GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
        runc:
         Version:          1.0.0-rc92
         GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
       
       Server:
        Containers: 14
WARNING: No swap limit support
         Running: 4
         Paused: 0
         Stopped: 10
        Images: 12
        Server Version: 20.10.4
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
        runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-66-generic
        Operating System: Ubuntu 20.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 1.941GiB
        Name: ubuntu-s-2vcpu-2gb-lon1-01
        ID: WTV5:O5NX:GI6J:ZZT5:SUW3:WGLK:D6PR:O36F:BOUZ:FXII:SGX6:ART6
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.26
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v224
         heroku-buildpack-nodejs    v183
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v191
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v89
         heroku-buildpack-play      v26
         heroku-buildpack-php       v189
         heroku-buildpack-go        v152
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.24.0
-----> plugn version: plugn: 0.6.1
-----> dokku plugins: 
         00_dokku-standard    0.24.0 enabled    dokku core standard plugin
         20_events            0.24.0 enabled    dokku core events logging plugin
         app-json             0.24.0 enabled    dokku core app-json plugin
         apps                 0.24.0 enabled    dokku core apps plugin
         builder              0.24.0 enabled    dokku core builder plugin
         builder-dockerfile   0.24.0 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.24.0 enabled    dokku core builder-herokuish plugin
         builder-pack         0.24.0 enabled    dokku core builder-pack plugin
         buildpacks           0.24.0 enabled    dokku core buildpacks plugin
         certs                0.24.0 enabled    dokku core certificate management plugin
         checks               0.24.0 enabled    dokku core checks plugin
         common               0.24.0 enabled    dokku core common plugin
         config               0.24.0 enabled    dokku core config plugin
         cron                 0.24.0 enabled    dokku core cron plugin
         docker-options       0.24.0 enabled    dokku core docker-options plugin
         domains              0.24.0 enabled    dokku core domains plugin
         enter                0.24.0 enabled    dokku core enter plugin
         git                  0.24.0 enabled    dokku core git plugin
         letsencrypt          0.9.4 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.24.0 enabled    dokku core logs plugin
         network              0.24.0 enabled    dokku core network plugin
         nginx-vhosts         0.24.0 enabled    dokku core nginx-vhosts plugin
         plugin               0.24.0 enabled    dokku core plugin plugin
         proxy                0.24.0 enabled    dokku core proxy plugin
         ps                   0.24.0 enabled    dokku core ps plugin
         redirect             0.6.2 enabled    Plugin for managing application redirects
         repo                 0.24.0 enabled    dokku core repo plugin
         resource             0.24.0 enabled    dokku core resource plugin
         scheduler-docker-local 0.24.0 enabled    dokku core scheduler-docker-local plugin
         shell                0.24.0 enabled    dokku core shell plugin
         ssh-keys             0.24.0 enabled    dokku core ssh-keys plugin
         storage              0.24.0 enabled    dokku core storage plugin
         tags                 0.24.0 enabled    dokku core tags plugin
         tar                  0.24.0 enabled    dokku core tar plugin
         trace                0.24.0 enabled    dokku core trace plugin

**Comment by josegonzalez** [comment]
Ah that makes sense. Will need to think about how this should work since we'll need to only do references in certain cases and probably also track if its a reference to a file path or should be imported...

**Comment by matijakolaric** [comment]
Sure, thanks for considering it, even if you don't include it.

**Comment by josegonzalez** [comment]
I've thought about this for a bit and think that instead, you should write a plugin that adds the cert in `post-create` and also forces the new cert whenever a command is called. I don't think this is common enough in the Dokku world for me to support otherwise, and introduces complications around permissions and file existence (and also somewhat brings back the global cert we used to support, which I'd like to avoid because it was a pain to reason about in the core).
