### ISSUE TITLE
[Feature Request]: Option to change default branch for deploys

### ISSUE THREAD

**Issue by tarzzz** [dokku/dokku#4463]
GH is encouraging renaming master to main for the default branch of repos. This is already the default default for repos created in the GH UI - see https://github.com/github/renaming and https://www.infoq.com/news/2020/10/github-main-branch/. 

Currently you need to use the master branch to deploy apps to dokku. Would be great if dokku could allow (and perhaps eventually encourage) users to deploy using the main branch, or potentially another branch name of their choosing.

**Comment by josegonzalez** [comment]
Does this work: https://dokku.com/docs/deployment/methods/git/#changing-the-deploy-branch

**Comment by tarzzz** [comment]
Yes, that will suffice. Thanks!!
