### ISSUE TITLE
Access the docker deploy source of an application

### ISSUE THREAD

**Issue by pradel** [dokku/dokku#4464]
## Description of problem

It's not possible to access the deploy source of an application deployed using the new `git:from-image` command. I would like to be able to see that the current application was deployed via docker but also which image and tag it's running.

For context see https://github.com/ledokku/ledokku/issues/242

### How reproducible

Deploy a docker image with the `git:from-image` command.

#### Actual Results

```
root@docker-ubuntu-s-1vcpu-1gb-fra1-01:~# dokku apps:report my-ghost-app
=====> my-ghost-app app information
       App deploy source:             
       App dir:                       /home/dokku/my-ghost-app
       App locked:                    false
```

#### Expected Results

```
root@docker-ubuntu-s-1vcpu-1gb-fra1-01:~# dokku apps:report my-ghost-app
=====> my-ghost-app app information
       App deploy source:             docker library/ghost:1.0.0
       App dir:                       /home/dokku/my-ghost-app
       App locked:                    false
```

**Comment by josegonzalez** [comment]
Okay I think we should have something like:

```shell
plugn trigger deploy-source-set $APP $SOURCE $EXTRA
```

And call that whenever a deploy is in progress progress. The input would be stored in the `apps` plugin properties. We would also deprecate/remove the `deploy-source` plugin, which is currently only implemented by the `git` and `tar` plugins (tar is going away in the next minor.

For `git:from-archive`, we'd call:

```shell
plugn trigger deploy-source-set $APP $ARCHIVE_TYPE $ARCHIVE_URL

# example
plugn trigger deploy-source-set node-js-app tar https://example.com/archive.tar
```

For `git:from-image`, we'd call:

```shell
plugn trigger deploy-source-set $APP docker $IMAGE

# example
plugn trigger deploy-source-set node-js-app docker dokku/node-js-app:1.0.0
```

For `git push`, we'd call:

```shell
plugn trigger deploy-source-set $APP git $SHA

# example
plugn trigger deploy-source-set node-js-app git 4661c62a16ba6a77336c043b44dda37d4f6b9cf0
```

Not sure _where_ we'd call it, as we reuse git internals within the `git:from-*` commands, but the above would roughly work.

Users could also implement their own ways to sync the git repo and set the deploy source appropriately.

**Comment by josegonzalez** [comment]
@pradel thoughts on the above? The `tar` and `tags` plugins go away in the next release, so I think the above would otherwise cover all working paths.

**Comment by pradel** [comment]
@josegonzalez Looks great, this would solve this problem perfectly 👌

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
