### ISSUE TITLE
Not able to build an application using an Dockerfile with multiple --build-arg

### ISSUE THREAD

**Issue by gustavorps** [dokku/dokku#4472]
## Description of problem
Not able to build a `Dockerfile` with multiple `--build-arg`  

### Steps to Reproduce

1. `git init dokku-issue`
2. Create a repo only with `Dockerfile`
  ```Dockerfile
  FROM hello-world
  ```
3. `git remote add dokku dokku@DOKKU_HOST:app`
4. `git add . && git commit -m "a commit" && git push dokku master:master` 
5. `dokku docker-options:add app build  --build-arg FOO=0 --build-arg BAR=1 `
6. `dokku ps:rebuild app`

#### Actual Results
```sh
$ git push dokku
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 653 bytes | 653.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0)
-----> Cleaning up...
-----> Building app from Dockerfile
-----> Setting config vars
       DOKKU_DOCKERFILE_PORTS:  3000
remote: "docker image build" requires exactly 1 argument.
remote: See 'docker image build --help'.
remote: 
remote: Usage:  docker image build [OPTIONS] PATH | URL | -
remote: 
remote: Build an image from a Dockerfile
remote: 2021/03/11 17:20:17 exit status 1
```
#### Expected Results

Successfully Dockerfile built

### `dokku report app` output
```
dokku docker-options:report app
=====> app docker options information
       Docker options build:    --build-arg FOO=0 --build-arg BAR=1 
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:  
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
DigitalOcean Marketplace 1-Click App

### Additional information

- [Container Inspect Output](https://gist.github.com/gustavorps/900b84af034e7a67e5117f221c7393eb#file-inspect-json)
- [The nginx configuration](https://gist.github.com/gustavorps/900b84af034e7a67e5117f221c7393eb#file-nginx-config)
- Link to the exact repository being deployed: Not possible
- If a deploy is failing or behaving unexpectedly:
  - Application name: app
  - The type of application being deployed: Node
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`: Not using
- [Output of failing Dokku commands after running `dokku trace:on`](https://gist.github.com/gustavorps/900b84af034e7a67e5117f221c7393eb#file-dokku-trace-log)

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by gustavorps** [comment]
@josegonzalez added new information based yours issue template

**Comment by josegonzalez** [comment]
Can you show the _entire_ output of `dokku report app`? Not just the parts you think are useful.

**Comment by josegonzalez** [comment]
Note: this `hello-world:latest` dockerfile doesn't get past the app start stage because it doesn't start a persistent process. Going to assume if we can get past app buiild, then its fine.

**Comment by josegonzalez** [comment]
Oh I see. Yeah, you can only add a docker option one at a time. We don't parse the newlines or allow them to "expand" otherwise. You'll need to run this command multiple times to get the effect you want.

First remove the args once:

```shell
dokku docker-options:remove app build --build-arg FOO=0 --build-arg BAR=1
```

Then re-add then one at a time:

```shell
dokku docker-options:add app build --build-arg FOO=0
dokku docker-options:add app build --build-arg BAR=1
```
