### ISSUE TITLE
Support elementary OS

### ISSUE THREAD

**Issue by djyde** [dokku/dokku#4482]
I ran `bootstrap.sh` in elementary OS (https://elementary.io/) which is an OS based on Ubuntu 18.04. But the command failed with `Unsupported Linux distribution`

I read the source code and I figured out it is because the output of `/etc/os-release` on elementary OS is:

```bash
NAME="elementary OS"
VERSION="5.1.6 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.6 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.6"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic
```

the `VERSION_ID` is pointed to the elementory OS version, instead of Ubuntu version, which is not in `SUPPORTED_VERSIONS`.

https://github.com/dokku/dokku/blob/4662ac2774edf8c66fa5668edb64b08abea50a7c/bootstrap.sh#L245

BTW, this is the output of `lsb_release -a -u` in elementary OS:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by josegonzalez** [comment]
How does elementary packaging work? Is this something you'd be interested in working on?

**Comment by djyde** [comment]
@josegonzalez Same as Ubuntu (apt-get). I tried hard code: 

```
if  [[ $DOKKU_DISTRO == "elementary" && $DOKKU_DISTRO_VERSION == "5.1.6"  ]]; then
	export DOKKU_DISTRO="ubuntu"
    export DOKKU_DISTRO_VERSION="18.04"
fi
```

and it works. But I'm not sure if it's a good solution.

**Comment by josegonzalez** [comment]
Okay seems like we can maybe instead just release our deb packages for Elementary OS.

The alternative is running the docker image as is, but I don't see any harm in this :)

**Comment by josegonzalez** [comment]
Going to close this. The recommended alternative is to run the Docker image.

**Comment by lmdc45** [comment]
If anyone is doing the same with Elementary 6 odin, need to change bootstrap.sh with:
at line 265 in main function
```
# see https://github.com/dokku/dokku/issues/4482
  if  [[ $DOKKU_DISTRO == "elementary" ]]; then
    echo 'Elementary OS'
    export DOKKU_DISTRO="$(lsb_release -ius | tr '[:upper:]' '[:lower:]')"
    export DOKKU_DISTRO_VERSION="$(lsb_release -rus)"
  fi
```
and also at line 191 before adding deb package link, change` lsb_release -cs `to` lsb_release -csu`
