### ISSUE TITLE
Dokku.com newsletter link does not work.

### ISSUE THREAD

**Issue by runephilosof-abtion** [dokku/dokku#4487]
Following the newsletter link https://gliderlabs.us10.list-manage.com/subscribe?u=49c4b06ffd30bcf49ec53c277&id=f526006fd5 on https://github.com/dokku/dokku/blob/7cb7d2aebf463cb5c64cbbac419668775127c7ae/docs/home.html#L69 you get:
> That's odd
> This page appears to be missing.

I expected something else :)

**Comment by josegonzalez** [comment]
Good catch. The newsletter is effectively gone, but we should have a working [XML feed here](https://dokku.github.io/feed.xml) (the blog will be migrated to dokku.com next week I hope, not sure how the feed will transition...).

That all said, we should drop the newsletter link, as I don't think that will come back anytime soon. Anyone looking for newsletter-like content should sponsor the project on [Github](https://github.com/sponsors/dokku), [Opencollective](https://opencollective.com/dokku), or [Patreon](https://www.patreon.com/dokku).
