### ISSUE TITLE
Builder cuts off arguments

### ISSUE THREAD

**Issue by aivils** [dokku/dokku#4515]
## Description of problem

Many docker-options were added to the project

### How reproducible
App with Dockerfile
```
dokku docker-options:add app build --build-arg PAYPAL_CLIENT_ID=abc-v123
dokku docker-options:add app build --build-arg PAYPAL_CLIENT_MODE=sandbox
```

```
dokku ps:rebuild app --trace true
```
Rebuild will end with an error stating that PAYPAL_CLIENT_ID is corrupted and both arguments are combined.

Or more easy reproduce is take code from source:
https://github.com/dokku/dokku/blob/master/plugins/builder-dockerfile/builder-build#L32

```
$ echo "PAYPAL_CLIENT_ID=abc-v123" | sed -e 's/--volume=[[:graph:]]\+[[:blank:]]\?//g' -e 's/-v[[:blank:]]\?[[:graph:]]\+[[:blank:]]\?//g'
PAYPAL_CLIENT_ID=abc
```
PAYPAL_CLIENT_ID is truncated to line "abc"
Obviously, the string "-v" is misinterpreted.

**Comment by josegonzalez** [comment]
Interesting. That sed call works fine on Macos, but not on Linux.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
