### ISSUE TITLE
Offline instalation

### ISSUE THREAD

**Issue by bralbral** [dokku/dokku#4533]
Good day! 
Is it possible to install dokku offline? I didn't find any instructions. We have a private network with no internet access.

Thanks!

**Comment by josegonzalez** [comment]
The `make install` would still need to grab random compiled binaries from the internet.

We don't really have any offline docs at the moment, but you could very easily get away with just using the Docker image method of installation. Assuming you have docker (which is probably a given, if you want to use Dokku), then save/load the docker image we release [here](https://hub.docker.com/r/dokku/dokku) and you're in a good spot.

If you're looking for something more involved, happy to do so if you're willing to [sponsor the work](https://github.com/dokku/.github/blob/master/SPONSORING.md), but pretty sure the docker image route is the best one for getting started.

Let me know if you need something else :)
