### ISSUE TITLE
Dokku post-deploy container is not connected to all the same networks as the regular containers

### ISSUE THREAD

**Issue by fomojola** [dokku/dokku#4543]
## Description of problem
I have a configuration that has 4 containers (app1.web.1, app2.web.1, app3.web.1 and app3.worker.1) on the same network (set with `dokku network:set attach-post-create backbone`). On restart of app2, I'm trying to have the postdeploy task call a webhook in app1 with curl. Unfortunately, the container started to execute the postdeploy hook on app2 isn't linked to the same network as app2.web.1, so the name lookup of app1.web.1 fails>

### How reproducible
All the time.

### Steps to Reproduce

1. Create 2 apps in a Dokku installation, app1 and app2. Run web servers on port 8080 in each app, and add a file called ready.txt in the root of app1.
2. Add the following app.json to app2.

`{
    "scripts": {
        "dokku": {
            "postdeploy": "./postdeploy"
        }
    }
}`

3. Add the following postdeploy script in the file **postdeploy** in app2: 

`#!/bin/bash

# call the container proxy with our new IP and port
notify-container-proxy() {
    # proxy address
    PROXYIP=`getent ahostsv4 app1.web.1 | grep STREAM | cut -f 1 -d ' '`
    PROXYPORT=8080

    echo "Notifying ${PROXYIP}..."
    curl -X POST "http://${PROXYIP}:${PROXYPORT}/ready.txt"
}

notify-container-proxy
`

4. Redeploy app2.

#### Actual Results

The deploy fails because the name resolution in the postdeploy doesn't succeed.

#### Expected Results

The name resolution should work, returning a valid IP address and the curl call should succeed.

**Comment by josegonzalez** [comment]
Def should not be possible... as the code [here](https://github.com/dokku/dokku/blob/master/plugins/app-json/functions.go#L418) for deploy task containers seems to be doing the right thing.

I'll need to investigate further, thanks for reporting!

**Comment by fomojola** [comment]
Thanks! I tried following through the code, but my search ran out of juice at  https://github.com/dokku/dokku/blob/master/plugins/app-json/functions.go:  I couldn't confirm if it was including custom `--network`  arguments at all.

**Comment by josegonzalez** [comment]
Hmm did I incorrectly order the args? https://github.com/dokku/dokku/blob/master/plugins/network/triggers.go#L187

I'll have to investigate a bit...
