### ISSUE TITLE
React Rails Dokku serve static file in production

### ISSUE THREAD

**Issue by dcalixto** [dokku/dokku#4549]
Hello after push a rails api with react, the login and signup screen is not served by dokku, as both are static, i use the gem 'rails-static-router' and did not worked, but before show up this on the logs

    ActionController::RoutingError (No route matches [GET] "/signup":

and then i put the action new on the users controller

    def new
    render :file => 'public/signup.html', :layout => false
    end

and on routes

    get "/signup",  to: 'users#new'

still not working, please someone can please help on how to get the static file with react and rails deployed on dokku?

**Comment by josegonzalez** [comment]
This seems to be an app problem, not something to do with Dokku. I would check with a rails forum/slack of some sort, or at the very least join us on [slack](https://glider-slackin.herokuapp.com/).
