### ISSUE TITLE
Add a command to un-pin plugin versions

### ISSUE THREAD

**Issue by arusa** [dokku/dokku#4551]
## Description of problem

The version gets pinned when updating a plugin like this:

```
dokku plugin:update letsencrypt 0.11.7
```

To "unpin" the plugin version currently these steps are necessary:

```
cd /var/lib/dokku/plugins/enabled/letsencrypt
git checkout master
dokku plugin:update letsencrypt
```

There should be a dokku command to make this easier

**Comment by josegonzalez** [comment]
I wonder if using `master` for the tag does the right thing?

**Comment by arusa** [comment]
That would be easy and it would just take a little addition in the description of `dokku plugin:help`

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
