### ISSUE TITLE
Exit status 128 for no apparent reason while downloading buildpack

### ISSUE THREAD

**Issue by samul-1** [dokku/dokku#4560]
I'm afraid I can't provide much details to this one as I don't have them myself. Up to a couple of hours ago, everything worked fine and I could push projects with no issues to my dokku (on ubuntu 20.04), and now this happens when I try to:

```
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 4 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (10/10), 1.48 KiB | 1.48 MiB/s, done.
Total 10 (delta 6), reused 0 (delta 0)
-----> Set main to DOKKU_DEPLOY_BRANCH.
-----> Cleaning up...
-----> Building jsplatform-frontend from herokuish
-----> Adding BUILD_ENV to build environment...
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi nodejs static
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs
remote: 2021/04/14 14:17:14 exit status 128
remote: 2021/04/14 14:17:15 exit status 1
To 131.114.22.89:jsplatform-frontend
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'dokku@131.114.22.89:jsplatform-frontend'
```

Full logs: https://gist.github.com/samul-1/6aa1487dedd58886e7bb56b308bbbb3e

Dokku report $APP output https://gist.github.com/samul-1/7585d91e4d2f098968bdcc56859144cc

This happens after a one-minute wait on the "downloading buildpack" line. I have no idea what's causing this and it happened unprovoked, apparently.

I'd be grateful if anybody was willing to try and help me, or point me to how I can provide more useful logs.

EDIT: After some more looking around, I realized that my Django apps stopped working on dokku as well.
Visiting any one of them results in this:

2021-04-14T14:59:08.449179900Z app[web.1]: [2021-04-14 14:59:08 +0000] [12] [CRITICAL] WORKER TIMEOUT (pid:168)
2021-04-14T14:59:09.456307903Z app[web.1]: [2021-04-14 14:59:09 +0000] [169] [INFO] Booting worker with pid: 169

I pushed the same git repository to a machine with a similar installation (https://gist.github.com/samul-1/5d0b521f41184bf2421fcea0e9d44464) and it worked fine there.

So there's more going on than just deployment issues.

**Comment by josegonzalez** [comment]
Turns out the issue was that someone accidentally borked `docker0` iptables rules. Restarting docker via `sudo service docker restart` allowed this to work again.
