### ISSUE TITLE
Freenode irc logs are not available

### ISSUE THREAD

**Issue by chemicalkosek** [dokku/dokku#4572]
## Description of problem
The link to Freenode irc logs redirects to a page about botbot.me being acquired
### How reproducible
Visit the link: [https://botbot.me/freenode/dokku/](https://botbot.me/freenode/dokku/)

**Comment by josegonzalez** [comment]
Yeah they've since closed down. Not much we can do there.

I _do_ need to set something back up to bridge slack and irc though. That would give us _some_ logs. I'll also change the irc header....

**Comment by josegonzalez** [comment]
Plan:

- sign into irc
- change header on channel
- setup an irc/slack bridge

**Comment by josegonzalez** [comment]
I setup a bridge. If you need chat logs, for now, they'll be on slack. Maybe in the future we'll have something better.
