### ISSUE TITLE
Apps with multiple processes leave running containers

### ISSUE THREAD

**Issue by tarzzz** [dokku/dokku#4576]
## Description of problem

When deploying an app with multiple processes, if one of the process containers fails to start the other containers are not killed but keep on running. This causes the server to be loaded with unused running containers. Running `ps:retire` does not seem to help in this case.

### How reproducible

It's a fairly common issue because developers deploy various "dev" versions of their app and some of them have syntax errors or invalid logic causing them to fail to start. This causes unused running containers to pile up on server.

### Steps to reproduce:

Deploy an app with two processes (`web` and `worker` for example). Make it so that worker fails to initialise and errors out. The `web` container will continue to run indefinitely unless there is a manual intervention.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
