### ISSUE TITLE
Unable to import `plugins/config` in a Go plugin

### ISSUE THREAD

**Issue by cjdenio** [dokku/dokku#4578]
## Description of problem

When I attempt to add `github.com/dokku/dokku/plugins/config` as a dependency in a Go plugin (`go get github.com/dokku/dokku/plugins/config`), it fails with the following message:

```
go get: github.com/dokku/dokku/plugins/config@none updating to
        github.com/dokku/dokku/plugins/config@v0.0.0-20210422055842-496ea8684054 requires
        github.com/dokku/dokku/plugins/common@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

It seems like the config plugin's `go.mod` needs to be updated, but I'm not sure why the plugin works in production 🤔 

### Steps to Reproduce

1. Initialize a Go module
2. Run `go get github.com/dokku/dokku/plugins/config`
3. Observe

#### Actual Results

The error above ^

#### Expected Results

I expected it to work

## Environment Information

Fails on a variety of systems

**Comment by josegonzalez** [comment]
Could you use a `replace` for that? Maybe add it to your go mod file.

Go modules are really stupid btw, the workaround I have is to just always compile plugins within a docker container and volume mount the Dokku dependencies. I have no idea how importing these packages would work outside of the dokku core.
