### ISSUE TITLE
relation "accounts_articleimageshared" does not exist on pull and migrate

### ISSUE THREAD

**Issue by welpie** [dokku/dokku#4579]
I created a new model on my already existing Django app.When i updated my git I did these:
```
git pull
git push dokku main
```
Then i did these:
```
python3 manage.py makemigrations 
python3 manage.py migrate
```
But i get this error whenever i try to do an operation:
```
relation "accounts_articleimageshared" does not exist
```
Why??
How can i solve this?

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
There has been no update in more than two weeks, so closing.
