### ISSUE TITLE
Opt-in or opt-out of Federated Learning of Cohorts

### ISSUE THREAD

**Issue by LukasSkywalker** [dokku/dokku#4580]
## High Level Plan

- Add an nginx property `chrome-floc-enabled`. Default it to no value. Empty value == false.
- Add an nginx property `global-chrome-floc-enabled`. Default it to no value. Empty value == false.
- Add support for the above to properties to the `report` output
- Add the header to each `server` stanza in the nginx template.

### Description of problem

Allegedly because third party cookies are being blocked more and more, Google is rolling out Federated Learning of Cohorts (FLoC) for Chrome. FLoC allows browsers to analyze their users behaviour, place them in a cohort (where other users are present as well) and to share the cohort identifier with websites and advertisers.

There are various problems associated with supporting FLoC:

* Fingerprinting is easier, since users only need to be distinguished from the others in their cohort
* Websites are able to cross reference known browser histories with the cohort identifier to reveal a specific cohorts properties

See [this](https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea) article for a (biased) explanation.

Apparently, Wordpress [is discussing](https://core.trac.wordpress.org/ticket/53069) opting out of FLoC by default, and Github just [opted out](https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/).

#### Steps

Websites can opt out of FLoC by sending the `Permissions-Policy` header with a value of `interest-cohort=()`.

What's Dokkus policy on FLoC? Should those kind of configurations be left to the user, or will Dokku implement a default value?

**Comment by josegonzalez** [comment]
I'd personally prefer to opt-out, butI think our users are installers of Dokku, not their downstream users. Our users might use stuff like Google AdwordsAs such, atm I'd rather not do anything.

That said, we could opt-out by default, and have an option to disable the opt out.

Feel free to implement this in a PR, working on this isn't a priority for me specifically.

**Comment by josegonzalez** [comment]
I'm going to close this for now. There hasn't been a forthcoming PR, and as I mentioned before, its not really in the purview of Dokku to constrain this sort of thing.
