### ISSUE TITLE
Rails tmp directory

### ISSUE THREAD

**Issue by JoshuaNovak919** [dokku/dokku#460]
Does anyone know if there is a way to access the rails tmp directory or any tmp directory for writing temp file uploads with rails and dokku?

**Comment by mmplisskin** [comment]
Hello, I have had the same issue and could not use the "xc-attach -n " attach command. 
The backup process creates a file in the tmp directory  "#{Rails.root}/tmp/" and then converts formats. I am not able to make a directory in the tmp folder. Can anyone point me in the right direction? Thanks.

**Comment by josegonzalez** [comment]
@mmplisskin please open a new issue with your question and the details we ask in the contributing.md

**Comment by JeffreyCheng92** [comment]
Im trying to do the same thing as @JoshuaNovak919 above where I write to a file in the tmp directory before I upload to S3 and I'm not sure this is working as intended. 

```ruby
File.open("/tmp/cool.txt", 'w') { |f| f.write("write your stuff here") }
File.read('/tmp/cool.txt')
=> "write your stuff here"
```

But the only issue is that when I look inside the tmp directory, that file doesnt really exist. Although I was able to restart the `rails c` and access the file again. Any idea on where the file actually resides?
