### ISSUE TITLE
Support Authentication for git:from-image command

### ISSUE THREAD

**Issue by jasonlimantoro** [dokku/dokku#4602]
## Description of problem
The command `git:from-image` doesn't support authentication
### Steps to Reproduce

1. Run the `git:from-image` against a private repository
2. See Forbidden Error

#### Actual Results
```
Get https://registry.gitlab.com/XXXXXX/manifests/XXXXXX: denied: access forbidden
```
#### Expected Results
Should be able to function as per normal workflow

### Additional information
- Right now the workaround is to pull it first manually via `docker` (of course, after logging in).

```bash
# Do this once
docker login $REGISTRY_IMAGE -u $USER -p $TOKEN

## do these every redeploy
docker pull $REGISTRY_IMAGE # this is required
dokku git:from-image APP_NAME $REGISTRY_IMAGE
```

**Comment by josegonzalez** [comment]
This will be handled by #4460.
