### ISSUE TITLE
Make focal default stack for herokuish builds

### ISSUE THREAD

**Issue by lmdc45** [dokku/dokku#4621]
It would be nice to have ubuntu focal as default instead of having to set up custom stack
As per discussions with "louis" on slack

**Comment by josegonzalez** [comment]
What we'll need to do is:

- Update gliderlabs/herokuish to always push a `latest`, `latest-18`, and `latest-20` image. `latest` should be whatever we currently support, so the `20.0.4` release.
- Update gliderlabs/herokuish packaging to pull the `-20` version in addition to the `-18` release.
- Update gliderlabs/herokuish to tag the pulled image as `latest-20`.
- Change [this](https://github.com/dokku/dokku/blob/master/dokku#L44) to be `latest-20`.
- Update release docs to tell folks to clear build cache before upgrading, or set the builder as appropriate.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
