### ISSUE TITLE
Git submodule url does not sync with .gitmodules

### ISSUE THREAD

**Issue by billbillington** [dokku/dokku#4624]
I'm in the process of trying to setup a dokku project to use git submodules that reference  private git repositories. I decided to implement this by taking an existing submodule that works with the project and and changing it to point at a new private repository containing the exact same code.

My plan was to update the url of the submodules repository in the projects `.gitmodules` file and deploy to trigger the error which I could then fix by correctly setting up the servers ssh to pull in the private repo. To my surprise the change deployed successfully. 

After some thought I reasoned that this must be due to the the commit in the new repository having the same SHA as the previous so perhaps dokku had worked out that nothing had to change and just used the previous code somehow.

I created a new change adding a random file, commited in to the private repository, updated the code to point at this and redeployed.

I, again, expected to see an error about accessing the repository that I could use to get my task done but instead I got this output (I've changed the urls).

```
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 12 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 754 bytes | 23.00 KiB/s, done.
Total 7 (delta 4), reused 0 (delta 0)
remote: Cloning into '/tmp/dokku-26874-git_build_app_repo.xKV0o7/app/frontend/assets'...
remote: fatal: remote error: upload-pack: not our ref 29b1457aaa6ffe8275d4500c74e39b8158b39d40
remote: fatal: The remote end hung up unexpectedly
remote: Fetched in submodule path 'app/frontend/assets', but it did not contain 29b1457aaa6ffe8275d4500c74e39b8158b39d40. Direct fetching of that commit failed.
To dev1-boss.jsmbars.co.uk:dev1-boss
 ! [remote rejected]     test-branch -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@my-server.com:my-app'
```

This error message, coupled with fact that it worked when I used a commit that was present in the public version of the repo, suggests to me that the submodule is still somehow pointing at the previous version of the repo. 

Looking into the git submodule code in the dokku source all I could find is this.

https://github.com/dokku/dokku/blob/dfd55d0eb0e182c173bd7fd9d056dee2f4d9c7e8/plugins/git/internal-functions#L567

I know that this code will correctly pull in a new repository if none exists but on my local machine I needed to call `git sync` to get git to respect the new url. 

Is it possible that this code should have a `git sync` call added to it? or am I  going about this the wrong way.

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

Additionally, if you have an exact sample app I can use to replicate this, that would be excellent.

**Comment by billbillington** [comment]
I've reformatted, added a test project and include all the information asked for although I think a lot of it isn't needed as the issue occurs before the dokku gets to buildpacks, nginx etc.

## Description of problem

It would appear that dokku does not handle syncing of a submodule that changes from a public repo to a private repo correctly. This is also the case when switching on my local machine where `git sync` must be run, for some reason, before git update to ensure that the correct repository is referenced by git.

### Steps to Reproduce

1. Create new dokku app and deploy `master` of `https://github.com/billbillington/dokku-issue-4624-example` (an empty static project referencing a public submodule repo). 

2a(v1). Attempt to deploy `private-submodule-old-commit` branch to dokku app.
or
2a(v2). Attempt to deploy `private-submodule-new-commit` branch to dokku app.

#### Expected Results

2a(v1+v2). Expected app deployment to fail deployment with error message along the lines of "server doesn't have creds setup with access to private repo".

#### Actual Results

2a(v1). Deployment succeeds (as I mentioned above, presumably because SHA on this branch also exists on the public version of the submodule)

2a(v2). Deployment fails for the wrong reason, because the commit didn't exist on the submodule repo (suggesting to me that we are still pointing at the public repo that does not contain this SHA).
```
remote: fatal: remote error: upload-pack: not our ref 9c0cb69458fe64b38ce049f7908745527b8d95f7
remote: fatal: The remote end hung up unexpectedly
remote: Fetched in submodule path 'submodule', but it did not contain 9c0cb69458fe64b38ce049f7908745527b8d95f7. Direct fetching of that commit failed.
``` 

### How reproducible

This happens every time.

## Environment Information

### `dokku report APP_NAME` output

```
-----> uname: Linux development1 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           1993         740         179           0        1073        1093
       Swap:          4095          90        4005
-----> docker version: 
       Client: Docker Engine - Community
        Version:           19.03.10
        API version:       1.40
        Go version:        go1.13.10
        Git commit:        9424aeaee9
        Built:             Thu May 28 22:16:49 2020
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          19.03.10
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.13.10
         Git commit:       9424aeaee9
         Built:            Thu May 28 22:15:20 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.2.13
         GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info: 
       Client:
        Debug Mode: true
       
       Server:
        Containers: 22
         Running: 5
         Paused: 0
         Stopped: 17
        Images: 48
        Server Version: 19.03.10
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 4.15.0-66-generic
        Operating System: Ubuntu 18.04.3 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 1.947GiB
        Name: development1
        ID: IYYU:QRG3:MPIV:YWWD:7IC2:2SKM:7TBE:HFAH:S7EW:OVOL:2UJX:TUAU
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.13
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v215
         heroku-buildpack-nodejs    v171
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v169
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v174
         heroku-buildpack-go        v142
         buildpack-nginx            v13
-----> dokku version: dokku version 0.20.4
-----> dokku plugins: 
       plugn: 0.5.0
         00_dokku-standard    0.20.4 enabled    dokku core standard plugin
         20_events            0.20.4 enabled    dokku core events logging plugin
         app-json             0.20.4 enabled    dokku core app-json plugin
         apps                 0.20.4 enabled    dokku core apps plugin
         builder-dockerfile   0.20.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.20.4 enabled    dokku core builder-herokuish plugin
         buildpacks           0.20.4 enabled    dokku core buildpacks plugin
         certs                0.20.4 enabled    dokku core certificate management plugin
         checks               0.20.4 enabled    dokku core checks plugin
         common               0.20.4 enabled    dokku core common plugin
         config               0.20.4 enabled    dokku core config plugin
         docker-options       0.20.4 enabled    dokku core docker-options plugin
         domains              0.20.4 enabled    dokku core domains plugin
         enter                0.20.4 enabled    dokku core enter plugin
         git                  0.20.4 enabled    dokku core git plugin
         logs                 0.20.4 enabled    dokku core logs plugin
         network              0.20.4 enabled    dokku core network plugin
         nginx-vhosts         0.20.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.20.4 enabled    dokku core plugin plugin
         proxy                0.20.4 enabled    dokku core proxy plugin
         ps                   0.20.4 enabled    dokku core ps plugin
         redis                1.12.5 enabled    dokku redis service plugin
         repo                 0.20.4 enabled    dokku core repo plugin
         resource             0.20.4 enabled    dokku core resource plugin
         scheduler-docker-local 0.20.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.20.4 enabled    dokku core shell plugin
         ssh-keys             0.20.4 enabled    dokku core ssh-keys plugin
         storage              0.20.4 enabled    dokku core storage plugin
         tags                 0.20.4 enabled    dokku core tags plugin
         tar                  0.20.4 enabled    dokku core tar plugin
         trace                0.20.4 enabled    dokku core trace plugin
=====> dokku-issue-test app information
       App deploy source:             
       App dir:                       /home/dokku/dokku-issue-test
       App locked:                    true
=====> dokku-issue-test buildpacks information
       Buildpacks list:               
=====> dokku-issue-test ssl information
       Ssl dir:                       /home/dokku/dokku-issue-test/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> dokku-issue-test checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> dokku-issue-test docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> dokku-issue-test domains information
       Domains app enabled:           true                     
       Domains app vhosts:            dokku-issue-test.development1
       Domains global enabled:        true                     
       Domains global vhosts:         development1             
=====> dokku-issue-test git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       d11ef00                  
=====> dokku-issue-test network information
       Network attach post create:    
       Network attach post deploy:    
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.8:5000
=====> dokku-issue-test nginx information
       Nginx access log path:         /var/log/nginx/dokku-issue-test-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx error log path:          /var/log/nginx/dokku-issue-test-error.log
       Nginx hsts:                    true                     
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
=====> dokku-issue-test proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000
       Proxy type:                    nginx
=====> dokku-issue-test ps information
       Processes:                     1                        
       Deployed:                      true                     
       Running:                       true                     
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Ps can scale:                  true                     
       Status web.1:                  running    (CID: b868e44e2604)
=====> dokku-issue-test scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> dokku-issue-test storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:                                     


```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

v0.20.4 installed from script
`wget https://raw.githubusercontent.com/dokku/dokku/v0.20.4/bootstrap.sh
sudo DOKKU_TAG=v0.20.4 bash bootstrap.sh`

### Additional information

  - Link to the exact repository being deployed
  See steps to reproduce above.

  - If using buildpacks, which custom buildpacks are in use
  `https://github.com/heroku/heroku-buildpack-static`

**Comment by josegonzalez** [comment]
Thanks for the example. I'll try and see if I have time to replicate this. My gut says that the manual fix on your side is just how git works, but I'll need to do some research to verify.

**Comment by akhil-naidu** [comment]
Yes, this is happening with my repository too.

`git push dokku master` or `git push dokku main` none of these are working. 

It doesn't matter if the repo is small or big or have any dependencies, the command was not able to push, and returning an error as mentioned above.

I'm also attaching an image that clearly shows that using **git push dokku master** I was not even able to login into my VPS; But using **git push dokku main**, I was able to login into my dokku vps, but unable to push and deploy

![image](https://user-images.githubusercontent.com/11688537/120999803-28a06c00-c7a7-11eb-9ae4-b4ea464dd88a.png)

**Comment by billbillington** [comment]
@akhil-naidu I might be wrong but I don't think this is the same issue (this issue is related to submodules that point at private git repos). It looks like you may have git pointing at the wrong remote or not have your ssh creds setup correctly but I couldn't say for sure.

**Comment by akhil-naidu** [comment]
@billbillington 

`git push dokku main:master` done my thing few minutes ago and I'm reframing my understanding regarding this.

**Comment by akhil-naidu** [comment]
> @billbillington
> 
> `git push dokku main:master` done my thing few minutes ago and I'm reframing my understanding regarding this.

I was able to push but was not able to deploy at the time of the release phase I guess. Can you take a look and tell me the issue.

![image](https://user-images.githubusercontent.com/11688537/121009613-03fdc180-c7b2-11eb-8274-b14b605286de.png)

**Comment by billbillington** [comment]
@akhil-naidu This is not the place to discuss this. Your problem could be caused by a number of things but you'd need to supply much more information than this to get a useful answer. Id try raising your own issue supplying all the information listen in the issue template.

**Comment by josegonzalez** [comment]
@akhil-naidu your issue is not this issue, please open a new ticket.

**Comment by billbillington** [comment]
Hi. Is there any news on this? I might have to go ahead and make a fork just so we can get going on our end.

**Comment by josegonzalez** [comment]
@billbillington what is `git sync`? That isn't a command in my version of git (`git version 2.30.1 (Apple Git-130)`).

If you have a fix for this, I'm happy to take it btw. A test would be awesome :)

**Comment by billbillington** [comment]
@josegonzalez I'm sorry, it looks like I've made a mistake in the description of this issue. 

The commend is not `git sync` its `git submodule sync`. It's my understanding that it ensures that it updates your `.git/config` to match the submodule config defined in the project's `.gitmodules` file https://stackoverflow.com/questions/33739376/git-submodule-sync-command-what-is-it-for/33739770. 

I wish I could just commit a fix and some tests but I don't know anything about bash programming and I'm not sure how id even setup a test that emulates a private repo so I'm afraid I'm not up to the task of writing an automated test matching this project style at the moment. 

If you mean manual testing though, setting up a dokku project and following the steps I've outlined above will reproduce the issues and as far as I know just changing dokku to run run  the`git submodule sync` command before it currently runs `git submodule update` will fix the issue. I haven't had a chance to test this update myself but this is what fixes the same issue for me outside of dokku.

Sorry for the confusion.

**Comment by josegonzalez** [comment]
Since I don't have this use case and you don't know how to replicate the bug with shell commands, I've thrown up the above PR, no tests. If it doesn't break anything existing, I'll merge it, but it may result in us deleting it later during a refactor because there isn't a test for it.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
