### ISSUE TITLE
Make server clean for non app containers(remove rails console containers)

### ISSUE THREAD

**Issue by misteral** [dokku/dokku#4626]
## Description of problem
I have small aws server with rails application, periodically I go there with ssh and run `dokku run rails console`, then ssh session is broken I open new one and run `dokku run rails console` again. 
### How reproducible
Just run Dokku with small rails app. 
### Steps to Reproduce

1. Run rails app in Dokku
2. Run ssh console and `dokku run rails console`
3. Close ssh session. 
4. Run ssh console and `dokku run rails console`
5. Run ssh console and run `sudo docker ps`

#### Actual Results
lot of rails console - it eat memory
#### Expected Results
I want way how I can run console and not rebuild new container or find way how I can clear It in script. 

### `dokku report APP_NAME` output

-----> uname: Linux shop-staging 5.4.0-1047-aws #49-Ubuntu SMP Wed Apr 28 22:47:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           1955         663         450           0         842        1110
       Swap:          2047         139        1908
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.5
        API version:       1.41
        Go version:        go1.13.15
        Git commit:        55c4c88
        Built:             Tue Mar  2 20:18:20 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.5
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       363e9a8
         Built:            Tue Mar  2 20:16:15 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.4
         GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
        runc:
         Version:          1.0.0-rc93
         GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

       Server:
WARNING: No swap limit support
        Containers: 14
         Running: 3
         Paused: 0
         Stopped: 11
        Images: 17
        Server Version: 20.10.5
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
        runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-1047-aws
        Operating System: Ubuntu 20.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 1.91GiB
        Name: shop-staging
        ID: BRXV:AIXI:HA5T:YI74:QLWM:M4TQ:4G4N:POXJ:B652:OF3H:KLQJ:6RIF
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.6.0
-----> herokuish version:
       herokuish: 0.5.27
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v225
         heroku-buildpack-nodejs    v183
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v191
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v90
         heroku-buildpack-play      v26
         heroku-buildpack-php       v190
         heroku-buildpack-go        v153
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.24.3
-----> plugn version: plugn: 0.6.1
-----> dokku plugins:
         00_dokku-standard    0.24.3 enabled    dokku core standard plugin
         20_events            0.24.3 enabled    dokku core events logging plugin
         app-json             0.24.3 enabled    dokku core app-json plugin
         apps                 0.24.3 enabled    dokku core apps plugin
         apt                  0.11.0 enabled    Inject deb packages into dokku based on files in project
         builder              0.24.3 enabled    dokku core builder plugin
         builder-dockerfile   0.24.3 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.24.3 enabled    dokku core builder-herokuish plugin
         builder-pack         0.24.3 enabled    dokku core builder-pack plugin
         buildpacks           0.24.3 enabled    dokku core buildpacks plugin
         certs                0.24.3 enabled    dokku core certificate management plugin
         checks               0.24.3 enabled    dokku core checks plugin
         common               0.24.3 enabled    dokku core common plugin
         config               0.24.3 enabled    dokku core config plugin
         cron                 0.24.3 enabled    dokku core cron plugin
         docker-options       0.24.3 enabled    dokku core docker-options plugin
         domains              0.24.3 enabled    dokku core domains plugin
         enter                0.24.3 enabled    dokku core enter plugin
         git                  0.24.3 enabled    dokku core git plugin
         letsencrypt          0.11.2 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.24.3 enabled    dokku core logs plugin
         mysql                1.12.1 enabled    dokku mysql service plugin
         network              0.24.3 enabled    dokku core network plugin
         nginx-vhosts         0.24.3 enabled    dokku core nginx-vhosts plugin
         plugin               0.24.3 enabled    dokku core plugin plugin
         proxy                0.24.3 enabled    dokku core proxy plugin
         ps                   0.24.3 enabled    dokku core ps plugin
         redis                1.13.0 enabled    dokku redis service plugin
         repo                 0.24.3 enabled    dokku core repo plugin
         resource             0.24.3 enabled    dokku core resource plugin
         scheduler-docker-local 0.24.3 enabled    dokku core scheduler-docker-local plugin
         shell                0.24.3 enabled    dokku core shell plugin
         ssh-keys             0.24.3 enabled    dokku core ssh-keys plugin
         storage              0.24.3 enabled    dokku core storage plugin
         tags                 0.24.3 enabled    dokku core tags plugin
         tar                  0.24.3 enabled    dokku core tar plugin
         trace                0.24.3 enabled    dokku core trace plugin
=====> store app information
       App deploy source:
       App dir:                       /home/dokku/store
       App locked:                    false
=====> store builder information
       Builder computed selected:
       Builder global selected:
       Builder selected:
=====> store buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
CN = staging.store.welladigital.com
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> store ssl information
       Ssl dir:                       /home/dokku/store/tls
       Ssl enabled:                   true
       Ssl hostnames:                 staging.store.welladigital.com
       Ssl expires at:                Jul  5 15:51:42 2021 GMT
       Ssl issuer:                    C = US, O =
       Ssl starts at:                 Apr  6 15:51:42 2021 GMT
       Ssl subject:                   subject=CN = staging.store.welladigital.com
       Ssl verified:                  self signed
=====> store checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> store cron information
       Cron task count:               0
=====> store docker options information
       Docker options build:          --link dokku.redis.redis_store:dokku-redis-redis-store
       Docker options deploy:         --link dokku.redis.redis_store:dokku-redis-redis-store --restart=on-failure:10
       Docker options run:            --link dokku.redis.redis_store:dokku-redis-redis-store
=====> store domains information
       Domains app enabled:           true
       Domains app vhosts:            staging.store.welladigital.com
       Domains global enabled:        true
       Domains global vhosts:         staging.store.welladigital.com
=====> store git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       0eb4ce3
       Git last updated at:           1622096147
=====> store logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> store network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.3:5000
=====> store nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/store-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/store-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1622372322
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> store proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> store ps information
       Deployed:                      true
       Processes:                     2
       Ps can scale:                  true
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: a14ba0626b8)
       Status worker 1:               running (CID: 2d0a36d6f4d)
=====> store resource information
=====> store scheduler-docker-local information
       Scheduler docker local disable chown:
=====> store storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

Main question: How to run rails console w.o. duplicate container or how to close rails console container automatically. Thanks.

**Comment by josegonzalez** [comment]
When you run one-off containers, you should use the `--rm` flag on them like so:

```shell
dokku --rm  run ...
```

If not, then the containers stick around. See [the docs](https://dokku.com/docs/processes/one-off-tasks/) for more info.
