### ISSUE TITLE
Docs: dokku backup, recovery should warning people that network backup is not included

### ISSUE THREAD

**Issue by hiepxanh** [dokku/dokku#4633]
## Description of problem

Hi, I'm using dokku backup which currently work very effectly, I just recovery full dokku from an server to other server, and I see that we are missing the backup data on network option.

### How reproducible
1) backup data follow instruction https://dokku.com/docs/advanced-usage/backup-recovery/
2) recovery from backup on new server
3) deploy 'reader-web' applicaion to server
4) getting error because network is missing

#### Actual Results

I got this error: "**remote:  !     Network graphql-network does not exist**"

```
remote: =====> Processing deployment checks
remote:        No CHECKS file found. Simple container checks will be performed.
remote:        For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples                                                                                      zero-downtime-deploys/ for examples
remote:  !     No procfile found
remote: 2021/06/03 01:59:44 exit status 1
remote:  !     Network graphql-network does not exist
remote: 2021/06/03 01:59:44 exit status 1
remote: 2021/06/03 01:59:44 exit status 1
remote: 2021/06/03 01:59:44 exit status 1
To awread-next:reader-web
 ! [remote rejected]   develop -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@awread-next:reader-web'
```

#### Expected Results

it should backup includes network information

### `dokku report APP_NAME` output

https://gist.github.com/hiepxanh/63ef84fa01206db711b43e91f182b95d

**Comment by josegonzalez** [comment]
Unfortunately, you still need to recreate those docker networks. All that backup does is write the config that dokku needs.

**Comment by josegonzalez** [comment]
We may wish to update the docs to note that this needs to be done.

**Comment by hiepxanh** [comment]
thank you, do you want me to close this issue?

**Comment by josegonzalez** [comment]
No lets leave it open. The fix is a doc update :)

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
