### ISSUE TITLE
git:sync does not clone bare 

### ISSUE THREAD

**Issue by caillou** [dokku/dokku#4636]
## Description of problem

When using `git:sync APP_NAME REPO BRANCH --build`, the resulting repo on the server is not `--bare`.

This results in an error, when trying to push to the repo.

### Steps to Reproduce

1. Create a new app.
2. `git:sync APP_NAME REPO BRANCH --build`
3. Push to the dokku remote.

#### Actual Results

The application is built and deployed, yet an error is shown.

#### Expected Results

No error after the build.

#### Workaround

```
git:sync APP_NAME REPO BRANCH --build
cd /home/dokku/APP_NAME
git config --add core.bare true
```

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by bits0rcerer** [comment]
@josegonzalez I am facing the same bug as described in #5247. 

I am on dokku 0.27.8. 
Since release 0.25.0 #4686 is merged therefore your fix should be included but still I get the following error.

```
remote: error: refusing to update checked out branch: refs/heads/master
remote: error: By default, updating the current branch in a non-bare repository
remote: is denied, because it will make the index and work tree inconsistent
remote: with what you pushed, and will require 'git reset --hard' to match
remote: the work tree to HEAD.
remote: 
remote: You can set the 'receive.denyCurrentBranch' configuration variable
remote: to 'ignore' or 'warn' in the remote repository to allow pushing into
remote: its current branch; however, this is not recommended unless you
remote: arranged to update its work tree to match what you pushed in some
remote: other way.
remote: 
remote: To squelch this message and still keep the default behaviour, set
remote: 'receive.denyCurrentBranch' configuration variable to 'refuse'.
To ssh://.../app
 ! [remote rejected] master -> master (branch is currently checked out)
```

The workaround mentioned above still works.

**Comment by josegonzalez** [comment]
@bits0rcerer can you open a new issue to track your problem?
