### ISSUE TITLE
Feature request: REST API

### ISSUE THREAD

**Issue by aaronstillwell** [dokku/dokku#4658]
Dokku currently requires all administrative commands to be run over SSH. This currently hinders the ability to build tooling on top of Dokku. I've written this issue after beginning to build a [terraform provider](https://github.com/aaronstillwell/terraform-provider-dokku) for managing dokku applications and services, which is relying on running commands over SSH and interpreting stdout and error codes, which is brittle and time consuming to build upon.

Further, a first-class REST API would more easily allow for more granular access control, which is currently only provided by the user-auth plugin.

I appreciate this is a non-trivial feature request, and one that I'm sure has been considered previously (I saw https://github.com/dokku/dokku-api), but in the absence of an issue discussing this topic (that I could find), I thought I'd raise a new issue to foster discussion of this potential addition to Dokku.

**Comment by josegonzalez** [comment]
This is not something I plan on working on as part of OSS. I have something that implements this (plus a web ui) that I'll be shortly releasing as a paid product.

Community members are free to work on other things outside of my own efforts, but there won't be any official oss package otherwise.
