### ISSUE TITLE
Wrong nodejs version

### ISSUE THREAD

**Issue by johncadengo** [dokku/dokku#4660]
Using a pretty basic setup.

My `.buildpacks` file:

```
https://github.com/heroku/heroku-buildpack-nodejs.git#v183
```

My `package.json` file:

```
  "engines": {
    "node": "14.x"
  },
```

When I deploy to dokku, I see this:

```
-----> Installing binaries
       engines.node (package.json):  >= 0.10
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version >= 0.10...
       Downloading and installing node 16.4.0...
       Using default npm version: 7.18.1
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.10)
       Installed yarn 1.22.10
```

I expect it to say `Downloading and installing node 14.x` instead.

What am I doing wrong?

**Comment by johncadengo** [comment]
Not sure how to get it to detect my `.buildpacks` file.

Here is what it says when I deploy:

```
-----> Adding BUILD_ENV to build environment...
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi ruby nodejs
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
```

Not even sure it's getting the right one since it doesn't include `#183`.

**Comment by johncadengo** [comment]
Ok, I would just like to confirm what I'm trying here is correct.

If so, then I think what I was running into was my package.json file not being properly checked in to the git branch I was deploying. It will take me awhile to confirm it, but I want to make sure, these are the steps I need in order to set the nodejs version. Thanks!

**Comment by josegonzalez** [comment]
The code _looks_ right but maybe something underneath is different.

Regardless, this appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [slack channels or github discussion board](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#monitored-locations). 

Issues pertaining to buildpacks will be closed and/or locked.
