### ISSUE TITLE
Allow requests coming to a certain host to be proxied to local port

### ISSUE THREAD

**Issue by bulters** [dokku/dokku#4665]
## Description of problem

Let's say I run a local web server (not as an app) on port 12345. I'd like to be able to taking incoming requests to some hostname (including an optional letsencrypt cert) and forward them to port 12345 on the host machine.

### How reproducible

n/a

### Steps to Reproduce

n/a

#### Actual Results

n/a

#### Expected Results

having a command available (e.g. dokku forward) that takes a name (like app name) hostname and a local port, e.g.:

    dokku forward:add local-dev development.some-domain.com 12345

as a result, either direct NGINX configuration is created to reverse_proxy requests to development.some-domain.com to host machine port 12345, or an application is created, running a lightweight proxy image that takes all requests and forwards them to "host.internal", having set the docker option "--add-host host.internal:host-gateway". 

The first solution would be more simple, but would not offer direct compatibility with e.g. letsencrypt plugin. The latter solution would be more involved (and opinionated, which is not bad per se) but would "just be an application", being compatible with plugins and current functionalities.

## Environment Information

n/a

### Additional information

n/a

**Comment by josegonzalez** [comment]
Maybe something like:

```
dokku network:set $APP static-web-listener $HOST:$PORT
```

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
