### ISSUE TITLE
ruby-getting-started repo has moved to "main" from "master" but the dokku docs contain "master"

### ISSUE THREAD

**Issue by j-a-h-i-r** [dokku/dokku#4675]
## Description of problem

Dokku getting started docs (https://dokku.com/docs~v0.21.4/deployment/application-deployment/) still refer to `master` branch of (https://github.com/heroku/ruby-getting-started). So the command `git push dokku master` fails with `error: src refspec master does not match any`.

## Solution
Update dokku docs to rename `master` to `main`

**Comment by josegonzalez** [comment]
Updated docs already showcase pushing `main` to `master`. You're referencing an old version...

https://dokku.com/docs/deployment/application-deployment/

**Comment by j-a-h-i-r** [comment]
Oh. My bad in that case.
