### ISSUE TITLE
Setting the Docker "Build Context" in the Build Phase of Deployment

### ISSUE THREAD

**Issue by asparagusfox** [dokku/dokku#4691]
We acknowledge this pull request addresses some mono-repo scenarios. https://github.com/dokku/dokku/pull/4502 
However, we think this is a use-case that has been missed regarding Docker build context.

Me and a team are currently working with a monorepo using multiple Dockerfiles, each of which we deploy using Dokku.
Each of the Dockerfiles are placed in sub-directories.

We know it's possible to set the Dockerfile file-path using `dokku docker-options`

However that does not (as far as I know) allow us to specify the build context (current working directory) when the docker build happens given the build context is hard coded: https://github.com/dokku/dokku/blob/52f2ce35f6f25d8e18b70e00679b902a5a536318/plugins/builder-dockerfile/builder-build#L50

For monorepos, being able to set the build context would allow Dockerfiles to be placed in sub-directories, without needing to specify relative paths in the Dockerfile (e.g. COPY . .  vs COPY ../ .) to successfully build.

### This is the workaround that we currently use:
As you know Dockerfile deployment is detected when a Dockerfile is in the root directory. So we have an empty Dockerfile in the root directory https://github.com/KarmaComputing/salon-booking-guru/blob/3235375f9f306790792149e79a2f62a28fb4f3de/Dockerfile#L1

We then set the Dockerfile file-path `dokku docker-options:add salon-booking-guru-api build --file=/home/dokku/APP_NAME/Dockerfile`

Finally we add a pre-recieve git hook in the dokku app directory: https://github.com/KarmaComputing/salon-booking-guru/blob/main/docs/deployment.md#set-dokku-git-pre-recieve-hook-to-get-dockerfile

`mkdir -p /home/dokku/salon-booking-guru-database && curl https://raw.githubusercontent.com/KarmaComputing/APP_NAME/main/database/Dockerfile > /home/dokku/APP_NAME/Dockerfile`

It would be great to be able to set this through Dokku. This would be the `PATH` argument in the docker command `docker build [OPTIONS] PATH | URL | -`.

We've had a go at implementing this ourselves but we can't work out where the best place to implement the fix is.

Maybe something like this:
`dokku builder-dockerfile:set APP_NAME --docker-build-context=<subdirectory>`
`dokku builder-dockerfile:set salon-booking-guru --docker-build-context=api/`

**Comment by josegonzalez** [comment]
Would the `build-dir` property set via `builder:set` not suffice?

**Comment by chrisjsimpson** [comment]
Thanks @josegonzalez I totally missed [changing the builder directory](https://dokku.com/docs/deployment/builders/builder-management/#changing-the-build-directory) in the docs. 

I assume `build-dir` will give the illusion of changing the build's context, which is good as it's the same outcome.
Will experiment and re-visit

Thank you

**Comment by josegonzalez** [comment]
Please note that none of this is released yet. I still have work to do on #4460 and #4508.

**Comment by chrisjsimpson** [comment]
Thanks for the links :+1: take your time :)

**Comment by josegonzalez** [comment]
I'm going to close this as the upcoming feature should resolve this. Feel free to reopen when we release if it does not.
