### ISSUE TITLE
In-line comments in DOKKU_SCALE file

### ISSUE THREAD

**Issue by jonashaag** [dokku/dokku#4694]
Feature request: In-line comments in DOKKU_SCALE file.

I added a comment to a DOKKU_SCALE file like so:

```
foo=1 # must always be 1
```

Turns out comments aren't supported and any lines that are different from `x=y` are ignored.

**Comment by josegonzalez** [comment]
Linking #4508 since we'll want to solve this there when migrating...

**Comment by josegonzalez** [comment]
DOKKU_SCALE will be deprecated in the next release. Users will be encouraged to use the new `formations` key in their `app.json` for scaling. Extra fields in that key will be ignored, so you can do something like:

```json
{
  "formations": {
    "web": {
      "description": "must always be 1",
      "quantity": 1
    }
  }
}
```

Hope that helps.
