### ISSUE TITLE
Command app-json seems to be disabled

### ISSUE THREAD

**Issue by mopx** [dokku/dokku#4696]
## Description of problem

The command app-json doesn't work and it's not listed on the commands list when I run dokku,

dokku plugin:list says it's enabled.

I tried this on 2 different machines one running 0.24.10 and the other running 0.19.13

### How reproducible

run dokku app-json:report or any other app-json commands

### Steps to Reproduce

1. dokku app-json:set APP_NAME appjson-path app-staging.json
2.
3.

#### Actual Results

 `app-json:set APP_NAME appjson-path app-staging.json` is not a dokku command.

#### Expected Results

set a custom path for my app.json

## Environment Information

➜  ~ dokku report APP_NAME
-----> uname: Linux localhost 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           3936         947         161           2        2826        2770
       Swap:           511         197         314
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.7
        API version:       1.41
        Go version:        go1.13.15
        Git commit:        f0df350
        Built:             Wed Jun  2 11:56:38 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.7
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       b0f5bc3
         Built:            Wed Jun  2 11:54:50 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.6
         GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
        runc:
         Version:          1.0.0-rc95
         GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
WARNING: No swap limit support
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
         scan: Docker Scan (Docker Inc., v0.8.0)
       
       Server:
        Containers: 17
         Running: 10
         Paused: 0
         Stopped: 7
        Images: 140
        Server Version: 20.10.7
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
        runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-74-generic
        Operating System: Ubuntu 20.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.844GiB
        Name: localhost
        ID: Z7QU:I2AL:JKP5:3X4A:TL6P:LMQP:Y7YZ:QMEM:5OPQ:MEZY:XU2V:4M5Y
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.29
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v228
         heroku-buildpack-nodejs    v185
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v197
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v90
         heroku-buildpack-play      v26
         heroku-buildpack-php       v195
         heroku-buildpack-go        v153
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.24.10
-----> plugn version: plugn: 0.6.1
-----> dokku plugins: 
         00_dokku-standard    0.24.10 enabled    dokku core standard plugin
         20_events            0.24.10 enabled    dokku core events logging plugin
         app-json             0.24.10 enabled    dokku core app-json plugin
         apps                 0.24.10 enabled    dokku core apps plugin
         builder              0.24.10 enabled    dokku core builder plugin
         builder-dockerfile   0.24.10 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.24.10 enabled    dokku core builder-herokuish plugin
         builder-pack         0.24.10 enabled    dokku core builder-pack plugin
         buildpacks           0.24.10 enabled    dokku core buildpacks plugin
         certs                0.24.10 enabled    dokku core certificate management plugin
         checks               0.24.10 enabled    dokku core checks plugin
         common               0.24.10 enabled    dokku core common plugin
         config               0.24.10 enabled    dokku core config plugin
         cron                 0.24.10 enabled    dokku core cron plugin
         docker-options       0.24.10 enabled    dokku core docker-options plugin
         domains              0.24.10 enabled    dokku core domains plugin
         enter                0.24.10 enabled    dokku core enter plugin
         git                  0.24.10 enabled    dokku core git plugin
         logs                 0.24.10 enabled    dokku core logs plugin
         memcached            1.13.0 enabled    dokku memcached service plugin
         mysql                1.14.0 enabled    dokku mysql service plugin
         network              0.24.10 enabled    dokku core network plugin
         nginx-vhosts         0.24.10 enabled    dokku core nginx-vhosts plugin
         plugin               0.24.10 enabled    dokku core plugin plugin
         proxy                0.24.10 enabled    dokku core proxy plugin
         ps                   0.24.10 enabled    dokku core ps plugin
         redis                1.15.0 enabled    dokku redis service plugin
         repo                 0.24.10 enabled    dokku core repo plugin
         resource             0.24.10 enabled    dokku core resource plugin
         scheduler-docker-local 0.24.10 enabled    dokku core scheduler-docker-local plugin
         shell                0.24.10 enabled    dokku core shell plugin
         ssh-keys             0.24.10 enabled    dokku core ssh-keys plugin
         storage              0.24.10 enabled    dokku core storage plugin
         tags                 0.24.10 enabled    dokku core tags plugin
         tar                  0.24.10 enabled    dokku core tar plugin
         trace                0.24.10 enabled    dokku core trace plugin
=====> APP_NAME app information
       App deploy source:             
       App dir:                       /home/dokku/APP_NAME
       App locked:                    false
=====> APP_NAME builder information
       Builder computed selected:     
       Builder global selected:       
       Builder selected:              
=====> APP_NAME buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
O = "CloudFlare, Inc.", OU = CloudFlare Origin CA, CN = CloudFlare Origin Certificate
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> APP_NAME ssl information
       Ssl dir:                       /home/dokku/APP_NAME/tls
       Ssl enabled:                   true                     
       Ssl hostnames:                 *.sample.net sample.net
       Ssl expires at:                Jul 27 00:48:00 2035 GMT 
       Ssl issuer:                    C = US, O = "CloudFlare, Inc.", OU = CloudFlare Origin SSL Certificate Authority, L = San Francisco, ST = California
       Ssl starts at:                 Jul 30 00:48:00 2020 GMT 
       Ssl subject:                   subject=O = "CloudFlare, Inc.", OU = CloudFlare Origin CA, CN = CloudFlare Origin Certificate
       Ssl verified:                  self signed              
=====> APP_NAME checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> APP_NAME cron information
       Cron task count:               0
=====> APP_NAME docker options information
       Docker options build:          --link dokku.memcached.APP_NAME-cache-staging:dokku-memcached-APP_NAME-cache-staging --link dokku.mysql.APP_NAME-db-staging:dokku-mysql-APP_NAME-db-staging --link dokku.redis.APP_NAME-redis-staging:dokku-redis-APP_NAME-redis-staging 
       Docker options deploy:         --link dokku.memcached.APP_NAME-cache-staging:dokku-memcached-APP_NAME-cache-staging --link dokku.mysql.APP_NAME-db-staging:dokku-mysql-APP_NAME-db-staging --link dokku.redis.APP_NAME-redis-staging:dokku-redis-APP_NAME-redis-staging --restart=on-failure:10 
       Docker options run:            --link dokku.memcached.APP_NAME-cache-staging:dokku-memcached-APP_NAME-cache-staging --link dokku.mysql.APP_NAME-db-staging:dokku-mysql-APP_NAME-db-staging --link dokku.redis.APP_NAME-redis-staging:dokku-redis-APP_NAME-redis-staging 
=====> APP_NAME domains information
       Domains app enabled:           true                     
       Domains app vhosts:            sample.net webtrack.sample.net quote.sample.net design.sample.net clients.sample.net support.sample.net
       Domains global enabled:        true                     
       Domains global vhosts:         localhost                
=====> APP_NAME git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       c726de33                 
       Git last updated at:           1626906440               
=====> APP_NAME logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> APP_NAME network information
       Network attach post create:    
       Network attach post deploy:    
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.13:5000
=====> APP_NAME nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/APP_NAME-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/APP_NAME-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1626912000               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> APP_NAME proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
Error: No such object: c894b0547a512d9cf707617fcc1240423be11946ebc09cfad8da3fd3ca3ed638
Error: No such object: 17ae9e7e94e0cbca3a88ef2997fb58b6201b395cb97d4b41d43464dc9d614e99
=====> APP_NAME ps information
       Deployed:                      true
       Processes:                     2
       Ps can scale:                  true
       Ps restart policy:             on-failure:10
       Restore:                       false
       Running:                       false
       Status web 1:                  missing (CID: c894b0547a5)
       Status worker 1:               missing (CID: 17ae9e7e94e)
=====> APP_NAME resource information
=====> APP_NAME scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> APP_NAME storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:                                     
➜  ~

**Comment by josegonzalez** [comment]
The `app-json` plugin has nothing to report until the  next minor release (0.25.0) so there won't be any output from it. Thus, this is currently expected behavior.
