### ISSUE TITLE
How to: Install dokku on Linode

### ISSUE THREAD

**Issue by JeanMertz** [dokku/dokku#47]
Maybe this belongs to the wiki, but for future reference, here is how I got Dokku working on a Linode instance:
- Build a Ubuntu 13.04 instance
- Follow these instructions: https://www.linode.com/wiki/index.php/PV-GRUB#Ubuntu_12.04_Precise
- If `apt-get update` no longer works, change `/etc/apt/sources.list` to one mentioned in http://mirrors.ubuntu.com/mirrors.txt
- Run the following commands:
  
  ``` bash
  apt-get update
  
  apt-get install lxc wget bsdtar linux-image-extra-$(uname -r)
  
  modprobe aufs
  ```
- After this, you can install dokku the default way:
  
  ``` bash
  wget -qO- https://raw.github.com/progrium/dokku/master/bootstrap.sh | sudo bash
  ```

**Comment by ascendbruce** [comment]
Just want to link this PR together to save a few minutes for people who is wondering where the Linode specific document went:

In https://github.com/dokku/dokku/pull/2679

> Modern versions of Docker work just fine on Linode's default kernel thanks to the overlay2 storage driver.
