### ISSUE TITLE
Is Dockerfile deployment a work in progress?

### ISSUE THREAD

**Issue by weisisheng** [dokku/dokku#4700]
*** I am a long-time monthly contributor.

## Description of problem

My experience with Dokku is using uploaded images and retagging.  However I would like to do a Dockerfile deploy for a new app (on a fresh install).  Reviewed a myriad of material and it seems the instructions for v0.24 are to place the Dockerfile in the created app's root directory but I can't seem to find how to trigger the deployment.  I was able to set this way, "dokku builder:set fooapp selected Dockerfile". The docs say the Dockerfile should be automatically recognized?

Separately, I was thinking of doing a local machine-->git-->dokku machine push.  Would this work? 

Thanks in advance.

Best, V.

### Steps to Reproduce

1.
2.
3.

#### Expected Results

<-- Please replace APP_NAME with the name of your app -->

### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> In these cases, you may run `dokku report` without any arguments to display the top-level reporting information.

### Additional information

- Container Inspect Output (if applicable) via `dokku ps:inspect APP_NAME`
- The nginx configuration (if applicable) via `dokku nginx:show-config APP_NAME`
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? The deployment output for your repository would be great as well. It is helpful for debugging problems. Thanks.

Additionally, the `builder:set` command isn't available until the next release of Dokku.

**Comment by josegonzalez** [comment]
Also, in case you weren't, you need to _commit_ the file to your repo.

**Comment by weisisheng** [comment]
Thanks for the fast response.  I will give the last recommendation a try and return to comment or close afterwards.

**Comment by weisisheng** [comment]
Rebuilding the server and starting my Dockerfile pushes from local to github did the trick.  Kudos on the great work.
