### ISSUE TITLE
Does Dokku have compose support?

### ISSUE THREAD

**Issue by rosman83** [dokku/dokku#4704]
## Description of problem
I have a frontend and backend node.js application initially setup using docker compose with two docker files in each of those two monolith folders to make it easy - following original docker best practices. This way I can startup both the frontend and backend through the single docker-compose command. However after trying to deploy the monolith folder and the docker-compose I kept running into errors and did some research to see old threads specifying that docker-compose support wasn't in Dokku. However, these were from early 2018 and so I want to know if this support is now there and if not - what is a suitable alternative to use - or should I just deploy frontend and backend images separately as separate apps.

### How reproducible
N/A
### Steps to Reproduce
N/A
#### Actual Results
N/A
#### Expected Results
N/A
## Environment Information
N/A
### `dokku report APP_NAME` output
N/A
### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?
N/A
### Additional information
N/A

**Comment by josegonzalez** [comment]
Dokku does not support docker-compose. If you have two web processes that need to live under the same hostname, you can use a custom `nginx.conf.sigil` for routing. The upcoming 0.25.x release will include better monorepo support (#4502)  , allowing you two deploy the app twice and easily specify different paths for the app root, `Dockerfile`, `Procfile`, etc.

I'll leave this ticket open for now until that gets merged.

**Comment by rosman83** [comment]
> Dokku does not support docker-compose. If you have two web processes that need to live under the same hostname, you can use a custom `nginx.conf.sigil` for routing. The upcoming 0.25.x release will include better monorepo support (#4502) , allowing you two deploy the app twice and easily specify different paths for the app root, `Dockerfile`, `Procfile`, etc.
> 
> I'll leave this ticket open for now until that gets merged.

Got it - since this comment I actually went with having separate apps for frontend and backend and find it actually cleaner to maintain and manage. I honestly think this system is best for now. Thanks for everything. Monorepo will be very nice though
