### ISSUE TITLE
Ubuntu 21 is unsupported Linux distribution

### ISSUE THREAD

**Issue by codecubix** [dokku/dokku#4705]
## Description of problem
Im installing dokku in localhost with ubuntu 21, and i encounter this issue: 

``` cmd
Unsupported Linux distribution. Only the following versions are supported: Debian [9, 10], CentOS [7], Ubuntu [16.04, 18.04, 20.04].
```

I hope we can address this and maybe consider ubuntu 21 as if it is also ubuntu 20 because i think there is no breaking changes in ubuntu 21 except for their gnome updates.  

### How reproducible
install dokku in  localhost with OS: ubuntu 21

### Steps to Reproduce

1. format a  PC with with ubuntu 21
2. update pc
3. install dokku

## Environment Information
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute

**Comment by josegonzalez** [comment]
Our packages are the same for all Debian systems, but we don't have a 21.04-specific repository atm as its a pain to test against anything other than an LTS and it's EOL is rather short.

You can use our [debian installation docs](https://dokku.com/docs/getting-started/install/debian/) instead to install on that OS, or try a [docker-based install](https://dokku.com/docs/getting-started/install/docker/).
