### ISSUE TITLE
VMware Photon OS is unsupported Linux distribution

### ISSUE THREAD

**Issue by lumpov** [dokku/dokku#4706]
## Description of problem

Cannot install latest Dokku on VMware Photon OS with issue.

Additional I try to install via rpm package and get an error.

### How reproducible

Install Dokku on clean install of Photon OS. Default way:

```
wget https://raw.githubusercontent.com/dokku/dokku/v0.24.10/bootstrap.sh;
sudo DOKKU_TAG=v0.24.10 bash bootstrap.sh
```

or by RPM-package:

```
curl -s https://packagecloud.io/install/repositories/dokku/dokku/script.rpm.sh | sudo bash
sudo yum install -y herokuish dokku
```

### Steps to Reproduce

1. clean install Photon OS
2. install updates
3. install dokku

#### Actual Results

```
sudo DOKKU_TAG=v0.24.10 bash bootstrap.sh
...
Unsupported Linux distribution. Only the following versions are supported: Debian [9, 10], CentOS [7], Ubuntu [16.04, 18.04, 20.04].
```

```
sudo yum install -y herokuish dokku
Refreshing metadata for: 'dokku_dokku-source'
Refreshing metadata for: 'dokku_dokku'     121   100%
1. nothing provides bind-utils needed by dokku-0.24.10-1.x86_64
Found 1 problem(s) while resolving
Error(1301) : Solv general runtime error
```

#### Expected Results

successfully installed Dokku.

### `dokku report APP_NAME` output

> none

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?

rpm, Photon as guest OS on standalone ESXi 6.7

### Additional information

cat /etc/*-release
DISTRIB_ID="VMware Photon OS"
DISTRIB_RELEASE="4.0"
DISTRIB_CODENAME=Photon
DISTRIB_DESCRIPTION="VMware Photon OS 4.0"
NAME="VMware Photon OS"
VERSION="4.0"
ID=photon
VERSION_ID=4.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
VMware Photon OS 4.0
PHOTON_BUILD_NUMBER=1526e30ba

I think, that problem is naming of bind-utils, because it named in Photon as buildutils...

**Comment by josegonzalez** [comment]
While I don't personally care to add support for Photon, I can certainly fix it so the package installation works if you want to install the RPMs directly.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
