### ISSUE TITLE
"ufw: command not found" during installation

### ISSUE THREAD

**Issue by marcmatias** [dokku/dokku#4710]
## Description of problem
After follow the [quick-start Instructions](https://dokku.com/#install-apt) i received the message 
`sudo: ufw: command not found`

### How reproducible
Install dokku in Debian 10 buster x86_64 Linux 4.19.0-17-amd64 following the quick-start instructions

### Steps to Reproduce

1. clean install Debian 10 buster x86_64 Linux 4.19.0-17-amd64
2. install updates
3. install dokku

#### Actual Results
`sudo: ufw: command not found`

#### Expected Results
Successfully installed Dokku with no `not found` messages.

### `dokku report APP_NAME` output

> none

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?
deb, vps machine Debian 10 buster x86_64 Linux 4.19.0-17-amd64

**Comment by josegonzalez** [comment]
Can you post the entire output here?

**Comment by marcmatias** [comment]
This happened at the end of the installation and I no longer have all logs. This is what i have:
```
Adding user dokku to group adm
-----> Priming bash-completion cache
Ensure proper sshcommand path
Setting up dokku-installer
sudo: ufw: command not found
```

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
