### ISSUE TITLE
help getting internal ip for upstream server

### ISSUE THREAD

**Issue by nileio** [dokku/dokku#4749]
I am trying to find the best way to obtain the internal ip of a rabbitmq container in order to use it in my modified `nginx.conf.sigil` for nginx proxy.

There are possible solutions but all of them are not perfect
1.  manually get the internal ip address of the container obtained via `dokku rabbitmq:info my_service --internal-ip` and use it as the `proxy_pass` url
2. create an env var named `my_service` by `dokku config:set` or use `.env` file and use it as `{{ var "my_service" }}` > my preferred way but this is again can't be a dynamic value
3. somehow manage to get the internal-ip as a post-deploy script and inject it as an env variable > great but at what point to run this command and how to then update the app env variable?
4. expose rabbitmq ports to the host and then use `proxy_pass` url to point to the desired rabbitmq port -> problem with that is that I have to expose all the ports of rabbitmq , can't select and it expose them all on `0.0.0.0` -> not recommended
5. other solutions?

I am looking for a dynamic solution similar to how the `upstream` server list is populated by `dokku`.

could I possibly run a command on post-deploy and let the output be the value of an application env variable which can then be using option 2. above ?

**Comment by nileio** [comment]
OK so I will answer my own question too for those who have similar question..
`nginx.conf.sigil` uses `sigil` template per docs. So I can use a command such as below to automatically run a shell command and update the config ..
{{ sh "dokku rabbitmq:info <rabbitmq service name here> --internal-ip" | trim }}
the other solution that worked is 
running `dokku config:set varname=$(dokku rabbitmq:info <rabbitmq service name here> --internal-ip)` then use `{{ var "varname" }}` in `nginx.conf.sigil`. the only drawback of this solution is you need to run it every time you restart or change containers, etc.

**Comment by josegonzalez** [comment]
I thought about this a bit longer and think the above pattern is both too annoying to handle (requires a code repo and custom nginx.conf.sigil) but also isn't as nice as it can be.

- the `sh` method only gets the ip on app nginx build. if a linked service's container restarts, it won't trigger an nginx rebuild
- the `sh` method seems hacky with the subprocess call :(
- the `config:set` method is unstable for the same reason

I came up with an alternative way to do it via a [service-proxy](https://github.com/dokku/service-proxy) (tested on 0.25.3):

```shell
# In this example, a rabbitmq service named lollipop will be exposed under the app service-proxy
dokku apps:create service-proxy
dokku config:set service-proxy SERVICE_NAME=queue SERVICE_TYPE=rabbitmq SERVICE_PORT=15672
dokku rabbitmq:create queue
dokku rabbitmq:link queue service-proxy
dokku git:from-image service-proxy dokku/service-proxy:latest
```

With a little work - see #4778 - this could even be a service command, `dokku $SERVICE:expose-web $SERVICE $NEW_APP_NAME`.

Hope the above helps.

**Comment by nileio** [comment]
@josegonzalez thanks for looking into this .. `service-proxy` project looks interesting. will keep an eye and log queries/issues in there.
