### ISSUE TITLE
Upstream Keepalive config

### ISSUE THREAD

**Issue by AlexBlokh** [dokku/dokku#4752]
How do I config `upstream keepalive` value through `dokku nginx` config? Is using sigil template is the only way?

**Comment by josegonzalez** [comment]
The only way to do this at this time is via a custom sigil template.

What exactly are you trying to achieve?

**Comment by AlexBlokh** [comment]
@josegonzalez I was following tutorials on Nginx performance tuning while benchmarking one of our services and `keepalive 128` was increasing performance immensely keeping low TCP port usage within VPS and I was manually changing file after deployment, so I was wondering if that is accessible somehow apart from sigil template and I'm not sure if it should be, I suppose 

What's your thoughts on that?

**Comment by josegonzalez** [comment]
If we exposed this, it would be on a per-app basis, which I think seems reasonable. Default to empty string, otherwise set to whatever you want. Thoughts?

**Comment by AlexBlokh** [comment]
@josegonzalez I completely agree, yet there's a caveat https://www.nginx.com/blog/tuning-nginx/

```
To enable keepalive connections to upstream servers you must also include the following directives in the configuration:

proxy_http_version 1.1;
proxy_set_header Connection "";
```

http version is 1.1 by default, yet `proxy_set_header` is different

**Comment by josegonzalez** [comment]
How would setting the Connection to empty string handle websockets? It seems like the value should be set as shown [here](http://nginx.org/en/docs/http/websocket.html), which is what we have now.

**Comment by josegonzalez** [comment]
Closing as there wasn't any followup. If folks want this sort of functionality, feel free to comment (and also respond to my above question).
