### ISSUE TITLE
dokku git:sync requires rsync

### ISSUE THREAD

**Issue by ltalirz** [dokku/dokku#4754]
## Description of problem

Using the new `dokku git:sync` command fails with
```
Cloning example-app from https://github.com/heroku/node-js-getting-started#b10a4d7a20a6bbe49655769c526a2b424e0e5d0b\\n/var/lib/dokku/plugins/available/git/internal-functions: line 422: rsync: command not found
```

### How reproducible

See e.g. Github action logs [here](https://github.com/dokku/ansible-dokku/runs/3477112001#step:7:903).

### Steps to Reproduce

1. Use `dokku git:sync` on a machine without `rsync`

#### Expected Results

Since `dokku git:sync` is now a built-in command of dokku, I suggest to install `rsync` as a dependency.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
