### ISSUE TITLE
"dokku run" refuses http connection to a service running in the container via localhost

### ISSUE THREAD

**Issue by yannguillon** [dokku/dokku#4768]
## Description of problem
`dokku run` refuses http connection to a service running in the container via localhost

### How reproducible

```
dokku run [app] curl http://127.0.0.1:5678
#where a service is running at http://127.0.0.1:5678 in the container
```

where the following works : 

```
dokku enter [app]
curl http://127.0.0.1:5678
{"code":200}


and 

dokku run [app] curl http://172.17.0.20:5678    # (network web listener IP)
{"code":200}



```

#### Actual Results

`curl: (7) Failed to connect to 127.0.0.1 port 5678: Connection refused`

#### Expected Results
`{"code":200}`

### `dokku report APP_NAME` output

-----> uname: Linux n8n 5.4.73-1-pve #1 SMP PVE 5.4.73-1 (Mon, 16 Nov 2020 10:52:16 +0100) x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:          16384        1922        8098         365        6362       14461
       Swap:          4096          28        4067
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.8
        API version:       1.41
        Go version:        go1.16.6
        Git commit:        3967b7d
        Built:             Fri Jul 30 19:54:02 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.8
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.16.6
         Git commit:       75249d8
         Built:            Fri Jul 30 19:52:10 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.9
         GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
        runc:
         Version:          1.0.1
         GitCommit:        v1.0.1-0-g4144b63
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)

       Server:
        Containers: 34
         Running: 18
         Paused: 0
         Stopped: 16
        Images: 82
        Server Version: 20.10.8
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: e25210fe30a0a703442421b0f60afac609f950a3
        runc version: v1.0.1-0-g4144b63
        init version: de40ad0
        Security Options:
         seccomp
          Profile: default
        Kernel Version: 5.4.73-1-pve
        Operating System: Debian GNU/Linux 10 (buster)
        OSType: linux
        Architecture: x86_64
        CPUs: 6
        Total Memory: 16GiB
        Name: n8n
        ID: OITE:PAEJ:BLXD:CTVV:WMOQ:7TGL:MNXC:PUNT:CPYL:4GYI:KNY4:BW32
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.20.1
-----> sigil version: 0.6.0
-----> herokuish version:
       herokuish: 0.5.30
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v228
         heroku-buildpack-nodejs    v185
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v197
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v90
         heroku-buildpack-play      v26
         heroku-buildpack-php       v196
         heroku-buildpack-go        v153
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.25.3
-----> plugn version: plugn: 0.6.1
-----> dokku plugins:
         00_dokku-standard    0.25.3 enabled    dokku core standard plugin
         20_events            0.25.3 enabled    dokku core events logging plugin
         app-json             0.25.3 enabled    dokku core app-json plugin
         apps                 0.25.3 enabled    dokku core apps plugin
         builder              0.25.3 enabled    dokku core builder plugin
         builder-dockerfile   0.25.3 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.25.3 enabled    dokku core builder-herokuish plugin
         builder-null         0.25.3 enabled    dokku core builder-null plugin
         builder-pack         0.25.3 enabled    dokku core builder-pack plugin
         buildpacks           0.25.3 enabled    dokku core buildpacks plugin
         certs                0.25.3 enabled    dokku core certificate management plugin
         checks               0.25.3 enabled    dokku core checks plugin
         clone                0.4.1 enabled    dokku git clone plugin
         common               0.25.3 enabled    dokku core common plugin
         config               0.25.3 enabled    dokku core config plugin
         cron                 0.25.3 enabled    dokku core cron plugin
         docker-options       0.25.3 enabled    dokku core docker-options plugin
         domains              0.25.3 enabled    dokku core domains plugin
         enter                0.25.3 enabled    dokku core enter plugin
         git                  0.25.3 enabled    dokku core git plugin
         logs                 0.25.3 enabled    dokku core logs plugin
         network              0.25.3 enabled    dokku core network plugin
         nginx-vhosts         0.25.3 enabled    dokku core nginx-vhosts plugin
         plugin               0.25.3 enabled    dokku core plugin plugin
         postgres             1.12.0 enabled    dokku postgres service plugin
         proxy                0.25.3 enabled    dokku core proxy plugin
         ps                   0.25.3 enabled    dokku core ps plugin
         registry             0.24.0 enabled    dokku core registry plugin
         repo                 0.25.3 enabled    dokku core repo plugin
         resource             0.25.3 enabled    dokku core resource plugin
         run                  0.25.3 enabled    dokku core run plugin
         scheduler-docker-local 0.25.3 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.25.3 enabled    dokku core scheduler-null plugin
         shell                0.25.3 enabled    dokku core shell plugin
         ssh-keys             0.25.3 enabled    dokku core ssh-keys plugin
         storage              0.25.3 enabled    dokku core storage plugin
         tags                 0.25.3 enabled    dokku core tags plugin
         tar                  0.25.3 enabled    dokku core tar plugin
         trace                0.25.3 enabled    dokku core trace plugin
=====> yo app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> yo app information
       App deploy source:
       App dir:                       /home/dokku/yo
       App locked:                    false
=====> yo builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> yo builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> yo builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> yo buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> yo ssl information
       Ssl dir:                       /home/dokku/yo/tls
       Ssl enabled:                   false
       Ssl hostnames:
       Ssl expires at:
       Ssl issuer:
       Ssl starts at:
       Ssl subject:
       Ssl verified:
=====> yo checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> yo cron information
       Cron task count:               0
=====> yo docker options information
       Docker options build:          --build-arg N8N_VERSION=0.130.0 --link dokku.postgres.yo-db:dokku-postgres-yo-db
       Docker options deploy:         --link dokku.postgres.yo-db:dokku-postgres-yo-db --restart=on-failure:10
       Docker options run:            --link dokku.postgres.yo-db:dokku-postgres-yo-db
=====> yo domains information
       Domains app enabled:           true
       Domains app vhosts:            yo.xxxxx.sh
       Domains global enabled:        true
       Domains global vhosts:         dokku.me
=====> yo git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       457193e
       Git last updated at:           1630961039
=====> yo logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> yo network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.20:5678
=====> yo nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/yo-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/yo-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         off
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1630958544
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> yo proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5678
       Proxy type:                    nginx
=====> yo ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: b8f5235bbb8)
=====> yo registry information
       Registry computed image repo:      dokku/yo
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> yo resource information
=====> yo scheduler-docker-local information
       Scheduler docker local disable chown:
=====> yo storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?

deb / physical / debian buster

**Comment by josegonzalez** [comment]
This is expected behavior as the one-off run containers start a brand new container with the command you specified, not with any processes in your Procfile or the CMD of a Dockerfile (if used).

**Comment by yannguillon** [comment]
> This is expected behavior as the one-off run containers start a brand new container with the command you specified, not with any processes in your Procfile or the CMD of a Dockerfile (if used).

Thanks, what would then be the recommended way to run  commands in this specific container ?
(to perform HTTP actions after deploy - i'm actually using this command in scripts.dokku.postdeploy)

**Comment by josegonzalez** [comment]
What are the exact commands you trying to run?

**Comment by yannguillon** [comment]
`node reload-workflows.js
`
reload-workflows.js :

`const axios = require('axios')

axios.get('http://localhost:5678/rest/workflows/18', {
  auth: {
    username: process.env.N8N_BASIC_AUTH_USER,
    password: process.env.N8N_BASIC_AUTH_PASSWORD
  }
}).then(function(res){
  axios.post('http://localhost:5678/rest/workflows/run', {
    workflowData: res.data.data
  },{
    auth: {
      username: process.env.N8N_BASIC_AUTH_USER,
      password: process.env.N8N_BASIC_AUTH_PASSWORD
    }
  });
});
`

**Comment by josegonzalez** [comment]
What does that endpoint actually do and why do you need to run it post deploy?

**Comment by yannguillon** [comment]
The endpoint activates some post-deploy tasks required by the app running in http://localhost:5678 . This app is built from a Dockerfile so API is the only way

**Comment by yannguillon** [comment]
The following works : 

`dokku enter [app] [process] curl http://127.0.0.1:5678`

get the process name with : 

`dokku ps:scale [app_name]`

**Comment by josegonzalez** [comment]
What exactly are those post deployment tasks? Why do they need to execute on the web process? What happens if you scale up the web process?

**Comment by josegonzalez** [comment]
I think the correct way to do what you are intending to do is either:

- have this be a part of your web process's startup
- hit the public url to your app from the postdeploy deployment task

Deployment tasks run in their own containers, separate from the scaled processes.

Entering containers is documented [here](https://dokku.com/docs/processes/entering-containers/), but I'll add some more on how this works.

**Comment by josegonzalez** [comment]
Closing as the correct way to do this is documented, and we're better documenting the enter process. Feel free to comment here if the above doesn't suffice for whatever reason.
