### ISSUE TITLE
Port mapping by domain

### ISSUE THREAD

**Issue by ppawlak** [dokku/dokku#4770]
## Description of problem

Hello,

I'd like to deploy a docker based app that exposes two ports internally (9000 and 9001) and I'd like to port map those ports based on virtual host name rather than on the source ports.

#### Actual Results

Currently I have to port map like this

```
=====> myapp proxy information
       Proxy enabled:                 true
       Proxy port map:                https:443:9000 https:444:9001
       Proxy type:                    nginx
```

and I access the second port of my app with https://mydomain1.com:444     

#### Expected Results

I'd like to access to the internal 9001 port from an other domain to be able to drop the explicit port specification in the browser, like https://mydomain2.com

The resulting `nginx.conf` would look something like this:

```
server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;

    server_name mydomain1.com;

    [...]

    location / {
       [...]
       proxy_pass  http://myapp-9000;
     }
}

server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;

    server_name mydomain2.com;

    [...]

    location / {
       [...]
       proxy_pass  http://myapp-9001;
     }
}
```

Is it possible to achieve this? 
If not, is it a feature to consider?

## Environment Information

dokku version 0.25.3

**Comment by josegonzalez** [comment]
What command do you expect to run in order to have this work?

**Comment by ppawlak** [comment]
> What command do you expect to run in order to have this work?

I don't know, I was asking 😃 
So I guess this is is not something possible at the moment.

Maybe the best place is an addition to `proxy:ports-add` where we can have an optional domain in the port specification:

`proxy:ports-add <app> <scheme>:[<domain>:]<host-port>:<container-port>` 

Of course, the domain must had been added to the domains list first.

In my previous example that would be:

```
domains:add myapp mydomain2.com
proxy:ports-add myapp https:mydomain2.com:443:9001
```  

What do you think?

**Comment by josegonzalez** [comment]
This isn't possible and I'm personally not interested in implementing this. It would make our nginx config fairly difficult to comprehend (it already is) in addition to making the port parsing awkward. I also don't think it would be of value to the majority of our users.

The current way to do this is to use a custom nginx.conf.sigil and implement this logic within your app.

I know thats not helpful, but hopefully this gives you a path forward (at least with the nginx.conf.sigil method)

**Comment by ppawlak** [comment]
> I know thats not helpful, but hopefully this gives you a path forward (at least with the nginx.conf.sigil method)

No worries, I totally understand. Thanks for pointing out the nginx.conf.sigil method, I'll give it a try.
