### ISSUE TITLE
Can't set up env

### ISSUE THREAD

**Issue by paulbraam** [dokku/dokku#4771]
I'm unable to deploy my Node JS app to a Dokku container.

I have a .env file that I push along with my app, but my env variables never can be read.
I could work around this by installing dotenv globally, but I thought it's supposed to work without it.

However, I tried to set up env variables using `dokku config:set <app-name> VARIABLE=value`, but the problem is that the app should be deployed first for me to be able to set them up, so I'm stuck there.

Could you please suggest what I'm doing wrong?

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Additionally, apps can be created via the `dokku apps:create $APP` command, and then you can set config from there.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response and the user may have simply neglected to create the app first.
