### ISSUE TITLE
Code of conduct URLs are right in the documentation source but wrong in the rendered HTML

### ISSUE THREAD

**Issue by bfontaine** [dokku/dokku#4779]
## Description of problem

The two links to the Code of conduct on this page are wrong: https://dokku.com/docs/getting-started/where-to-get-help/

They both point to https://github.com/dokku/.github/blob/master/CODE_OF_CONDUCT/ instead of https://github.com/dokku/.github/blob/master/CODE_OF_CONDUCT.md

The links are correct in the source and the HTML rendered by GitHub: https://github.com/dokku/dokku/blob/master/docs/getting-started/where-to-get-help.md

For some reason, the `.md` seems to disappear when the docs are built even if this is an external URL.

### How reproducible

easy

### Steps to Reproduce

1. Go to https://dokku.com/docs/getting-started/where-to-get-help/
2. Click on one link to the code of conduct

#### Actual Results

404 page

#### Expected Results

The Code of conduct.

## Environment Information

not relevant.

**Comment by josegonzalez** [comment]
Ugh thats no bueno. The url rewriting is too smart for it's own good. Maybe shouldn't rewrite if there is a url at the beginning.

Thanks for the report!

**Comment by c4lliope** [comment]
@josegonzalez can you link to a place where the rewrite is happening?
I'm happy to dig in and make changes.

**Comment by josegonzalez** [comment]
Its a very bad fork of the progrium/viewdocs repo. Thanks for offering, but the code is in a mess so its not great for external contributors.

I've made the requisite patch and pushed it up. Thanks for reporting!
