### ISSUE TITLE
Deploy dokku to CentOS

### ISSUE THREAD

**Issue by lcheng61** [dokku/dokku#478]
Hi,

Can anyone advise how to deploy dokku to CentOS OS ?

Thanks,

**Comment by marcellodesales** [comment]
@AlJohri @themasterchef Have you guys done anything on CENTOS? or is this really a dead end?

**Comment by josegonzalez** [comment]
Dokku won't work on CentOS unless someone wants to sponsor the work to make it do so. Feel free to contact me directly if you or your company is interested in doing so.
