### ISSUE TITLE
Update dependencies to include bullseye releases

### ISSUE THREAD

**Issue by adam12** [dokku/dokku#4781]
I'll submit PRs to these projects. Just keeping a central list here.

- [x] `dokku/sshcommand` (https://github.com/dokku/sshcommand/pull/59)
- [x] `dokku/plugn` (https://github.com/dokku/plugn/pull/55)
- [x] `dokku/docker-image-labeler` (https://github.com/dokku/docker-image-labeler/pull/10)
- [x] `josegonzalez/go-procfile-util` (https://github.com/josegonzalez/go-procfile-util/pull/28)
- [x] `gliderlabs/herokuish` (https://github.com/gliderlabs/herokuish/pull/697)
- [x] ~`dokku/dokku-update`~ There is no package management in this repo
- [x] `dokku/dokku-event-listener` (https://github.com/dokku/dokku-event-listener/pull/29)
- [x] `gliderlabs/sigil` (https://github.com/gliderlabs/sigil/pull/57)
- [x] `dokku/netrc` (https://github.com/dokku/netrc/pull/7)

**Comment by josegonzalez** [comment]
@adam12 thanks for all the PRs!
