### ISSUE TITLE
Feature suggestion: render a static response on apps without a HTTP port mapping

### ISSUE THREAD

**Issue by radiospiel** [dokku/dokku#4792]
## Description of problem

Currently at least the letsencrypt plugin fails if no HTTP mapping exists (https://github.com/dokku/dokku-letsencrypt/issues/243) As a consequence one cannot create an app, configure out to always use HTTPS, and only then push the actual app. 

An alternative would be to extend the proxy/nginx plugins to provide a static HTTP response ("This is the space where the <foo> app will arise.") or so.

**Comment by josegonzalez** [comment]
I don't think we should do this. If a user specifies a mapping that doesn't land on port 80 and we still respond with something on port 80, that would violate the principle of least surprise. Additionally, this might be weird if you have two apps on the same host, one on port 80/443 and one on another port.

I'd rather we warn/error out in letsencrypt (or wherever an ssl cert is added) first before attempting to do this, as I think it there are more corner cases that would crop up and be annoying to deal with.

**Comment by radiospiel** [comment]
fair enough - thanks for looking at this :+1:
