### ISSUE TITLE
dokku_client.sh: fails silently if cannot detect dokku remote

### ISSUE THREAD

**Issue by radiospiel** [dokku/dokku#4793]
## Description of problem

The dokku_client.sh script  fails silently if cannot detect the dokku remote.

### Steps to Reproduce

on a client machine, go to any directory and run `dokku` (Note that I don't know where I got the `dokku` script from, and why it is named so, but it is this one: https://github.com/dokku/dokku/blob/master/contrib/dokku_client.sh

This should print an error a la `"=====> Configure the DOKKU_HOST environment variable or run $0 from a repository with a git remote named dokku"` but it doesn't.

### Additional info:

The reason is that 

https://github.com/dokku/dokku/blob/master/contrib/dokku_client.sh#L58 calls the `fn-client-help-msg` function in a context where the STDOUT is being captured, and the error message is echo-ed to STDOUT.

This should be fixed by either:

    `fn-client-help-msg >&2`

or by redirecting the `echo` invocation to STDERR.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
