### ISSUE TITLE
Documentation: query params are interpreted as if they were part of the path

### ISSUE THREAD

**Issue by bfontaine** [dokku/dokku#4794]
## Description of problem

If you append query params to a documentation URL, it looks like they are interpreted as if they were part of the path. It looks like a bug, but maybe it’s a feature I don’t understand.

Try going to <https://dokku.com/docs/deployment/methods/git/?a=b>. It should work the same as <https://dokku.com/docs/deployment/methods/git/>, but it doesn’t. It even redirects you to a version with a trailing slash: <https://dokku.com/docs/deployment/methods/git/?a=b/>.

I noticed this because I saved a documentation link in [Pocket](https://getpocket.com/) and when I later clicked on it Pocket appended `?utm_source=pocket_mylist` to it: <https://dokku.com/docs/deployment/methods/git/?utm_source=pocket_mylist>.

Note: for this and #4779 I’d love to investigate and do PRs but I can’t find where the code responsible for building/serving the docs is.

### How reproducible

easy.

### Steps to Reproduce

1. Go to https://dokku.com/docs/deployment/methods/git/
2. Now go to https://dokku.com/docs/deployment/methods/git/?a=b

#### Actual Results

"Page not found"

#### Expected Results

The page should be the same.

## Environment Information

not relevant.

**Comment by josegonzalez** [comment]
The code for this is a forked version of [progrium/viewdocs](https://github.com/progrium/viewdocs). I've fixed the issue and pushed verified it. Thanks for reporting.
