### ISSUE TITLE
Vector Logs: Sending Proc Name as label

### ISSUE THREAD

**Issue by emilsedgh** [dokku/dokku#4803]
Is it possible to use Vector Logs to send the proc name as well as the app name?

Being able to filter out logs based on procname would be extremely useful but I'm not finding out if it's a possibility right now.

**Comment by josegonzalez** [comment]
Can you show me an example message that gets spit out by vector? As far as I know, they include all container labels, and we have the `com.dokku.process-type` label that should include this.

**Comment by emilsedgh** [comment]
Thank you for the swift response.

We send the logs to Papertrail, and this is what we see in there:

<img width="283" alt="Screen Shot 2021-09-26 at 12 43 40 PM" src="https://user-images.githubusercontent.com/120439/134821901-53dcbfa1-4bdc-4ed6-969c-4ad899d137c0.png">

So, I may be very well wrong here, and the dokku -> Vector setup may be alright, and it may be our Vector -> Papertrail setup that is not properly configured.

With that being said, seeing the source code and the configuration files, I'm not seeing any indication of `com.dokku.process-type` being sent to Vector (Although I may be wrong)

**Comment by emilsedgh** [comment]
Reading the source code to Vector's Papertrail sink, it appears that the `process: "Vector"` is hardcoded in.
I'll try to see if the _hostname_ can be configured though. This may be an irrelevant issue to dokku.

**Comment by josegonzalez** [comment]
Is com.dokku.app-name being sent?

**Comment by josegonzalez** [comment]
Also, can you get the raw data for a single message?

**Comment by emilsedgh** [comment]
I also tried to setup some logging with Datadog logs. Here is the result:

<img width="284" alt="Screen Shot 2021-09-26 at 1 36 42 PM" src="https://user-images.githubusercontent.com/120439/134823347-f8dca9f5-d654-4db3-a14f-189a709057cd.png">

It appears that neither host nor service are not sent to Datadog. I'm still not sure if this is a dokku limitation or a Vector one.

**Comment by josegonzalez** [comment]
May also be worth hopping into our slack channel so we can figure this out in real time...

**Comment by emilsedgh** [comment]
For future reference:

As of now, Dokku uses Vector 0.12 by default. This version of Vector doesn't send a lot of information automatically.

Updating Vector image to latest as described [here](https://dokku.com/docs/deployment/logs/) would fix this.

`dokku logs:vector-start --vector-image timberio/vector:latest-debian`

**Comment by emilsedgh** [comment]
This is an example message send to Datadog using 0.12:

<img width="920" alt="Screen Shot 2021-09-26 at 2 42 50 PM" src="https://user-images.githubusercontent.com/120439/134825152-9daf4045-78c0-4c15-b005-122ab9ec119a.png">

Now using 0.16:

<img width="710" alt="Screen Shot 2021-09-26 at 2 43 31 PM" src="https://user-images.githubusercontent.com/120439/134825170-dc5d1cb7-affb-4c60-9844-caffc1d376b6.png">

**Comment by emilsedgh** [comment]
Note that on papertrail, there's no notion of labels, etc. Thus, everything appears the same between 0.12 and 0.16

**Comment by josegonzalez** [comment]
Updated in #4784.
