### ISSUE TITLE
Create storage:ensure-directory command

### ISSUE THREAD

**Issue by nileio** [dokku/dokku#4805]
### High Level Plan

- Create a `storage:ensure-directory` command that creates subdirectories in `/var/lib/dokku/data/storage/` and chowns them to the herokuish user
- The chown can be disabled via the `--skip-chown`
- Running the command when a directory already exists does nothing, but it _may_ re-chown the directory if the `--skip-chown` flag is not set.

### Original Post

refering to 
[dokku Persistent Storage](https://dokku.com/docs/advanced-usage/persistent-storage/)

The example refers to the Recommended Location for storage being `/var/lib/dokku/data/storage/` however this location is owned by `dokku` user and so it is not possible to use it without `sudo` 
So the example below return `Permission denied` if not using `sudo`
```
# creating storage for the app 'node-js-app'
mkdir -p  /var/lib/dokku/data/storage/node-js-app
mkdir: cannot create directory ‘/var/lib/dokku/data/storage/node-js-app’: Permission denied
```
Not sure why this is the recommended location for storage though, but also want to raise to either correct the documentation and add `sudo` or so clarify if possible this point. Also just wanted to confirm that my setup doesn't have missed up permissions!

**Comment by josegonzalez** [comment]
On [storage plugin install](https://github.com/dokku/dokku/blob/be01d2f7ec9903b6d0a96b1a0693c23cb82cb4ad/plugins/storage/install#L10), we set the permissions of `/var/lib/dokku/data/storage` to dokku:dokku.

Can you check the permissions on that directory? Also, what is the output of `dokku report`?

**Comment by nileio** [comment]
`/var/lib/dokku/data/storage/` is owned by `dokku` user.
so the directory looks like 
```
drwxr-xr-x  3 dokku dokku 4096 Sep 19 07:39 .
drwxr-xr-x 10 dokku dokku 4096 Jul 20 05:35 ..
drwxr-xr-x  4 32767 32767 4096 Sep 20 09:53 node-js-demo
```

Now I had to use `sudo` on that directory because `dokku` user is created during installation but it is not the user we use to `ssh`  to the host. Am I missing something?

output of `dokku report`
```
-----> uname: Linux dokku 5.8.0-1041-azure #44~20.04.1-Ubuntu SMP Fri Aug 20 20:41:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           3935        1324         595          49        2015        2271
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.8
        API version:       1.41
        Go version:        go1.16.6
        Git commit:        3967b7d
        Built:             Fri Jul 30 19:54:27 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.8
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.16.6
         Git commit:       75249d8
         Built:            Fri Jul 30 19:52:33 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.9
         GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
        runc:
         Version:          1.0.1
         GitCommit:        v1.0.1-0-g4144b63
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
       
       Server:
        Containers: 8
         Running: 8
         Paused: 0
         Stopped: 0
        Images: 24
        Server Version: 20.10.8
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: false
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: e25210fe30a0a703442421b0f60afac609f950a3
        runc version: v1.0.1-0-g4144b63
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.8.0-1041-azure
        Operating System: Ubuntu 20.04.3 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.844GiB
        Name: dokku
        ID: DCE6:Z4WA:FWKT:AM65:LIKX:DYBR:SVV3:XH7M:VV76:7UN6:D5V3:U5QC
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.30
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v228
         heroku-buildpack-nodejs    v185
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v197
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v90
         heroku-buildpack-play      v26
         heroku-buildpack-php       v196
         heroku-buildpack-go        v153
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.25.4
-----> plugn version: plugn: 0.6.1
-----> dokku plugins: 
         00_dokku-standard    0.25.4 enabled    dokku core standard plugin
         20_events            0.25.4 enabled    dokku core events logging plugin
         app-json             0.25.4 enabled    dokku core app-json plugin
         apps                 0.25.4 enabled    dokku core apps plugin
         builder              0.25.4 enabled    dokku core builder plugin
         builder-dockerfile   0.25.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.25.4 enabled    dokku core builder-herokuish plugin
         builder-null         0.25.4 enabled    dokku core builder-null plugin
         builder-pack         0.25.4 enabled    dokku core builder-pack plugin
         buildpacks           0.25.4 enabled    dokku core buildpacks plugin
         certs                0.25.4 enabled    dokku core certificate management plugin
         checks               0.25.4 enabled    dokku core checks plugin
         common               0.25.4 enabled    dokku core common plugin
         config               0.25.4 enabled    dokku core config plugin
         cron                 0.25.4 enabled    dokku core cron plugin
         docker-direct        1.0.0 enabled    dokku plugin to issue docker commands directly
         docker-options       0.25.4 enabled    dokku core docker-options plugin
         domains              0.25.4 enabled    dokku core domains plugin
         enter                0.25.4 enabled    dokku core enter plugin
         git                  0.25.4 enabled    dokku core git plugin
         letsencrypt          0.12.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.25.4 enabled    dokku core logs plugin
         memcached            1.14.1 enabled    dokku memcached service plugin
         mysql                1.14.0 enabled    dokku mysql service plugin
         network              0.25.4 enabled    dokku core network plugin
         nginx-vhosts         0.25.4 enabled    dokku core nginx-vhosts plugin
         nuke                 1.0.0 enabled    stop all running containers, then delete all containers and images
         plugin               0.25.4 enabled    dokku core plugin plugin
         postgres             1.12.0 enabled    dokku postgres service plugin
         proxy                0.25.4 enabled    dokku core proxy plugin
         ps                   0.25.4 enabled    dokku core ps plugin
         rabbitmq             1.16.1 enabled    dokku rabbitmq service plugin
         registry             0.25.4 enabled    dokku core registry plugin
         repo                 0.25.4 enabled    dokku core repo plugin
         require              0.1.0 enabled    dokku plugin to setup all the requirement for your app on push
         resource             0.25.4 enabled    dokku core resource plugin
         run                  0.25.4 enabled    dokku core run plugin
         scheduler-docker-local 0.25.4 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.25.4 enabled    dokku core scheduler-null plugin
         shell                0.25.4 enabled    dokku core shell plugin
         ssh-keys             0.25.4 enabled    dokku core ssh-keys plugin
         storage              0.25.4 enabled    dokku core storage plugin
         tags                 0.25.4 enabled    dokku core tags plugin
         tar                  0.25.4 enabled    dokku core tar plugin
         trace                0.25.4 enabled    dokku core trace plugin
```

**Comment by josegonzalez** [comment]
Are you the dokku user when you run that mkdir call?

**Comment by nileio** [comment]
No - I am not. I never logged in as `dokku` user or su to `dokku`.. not even sure if thats possible without `sudoers` or perhaps I am missing something?

**Comment by josegonzalez** [comment]
Right so if the storage directory is owned by dokku, the user creating the directory needs to be the dokku user _or_ you run as root.

Maybe we should make a `storage:create-directory` command that creates that subdirectory and chowns as appropriate?

```
dokku storage:create-directory --skip-chown node-js-app
```

Would create the `/var/lib/dokku/data/storage/node-js-app` without the chown, but otherwise would chown as `32767:32767`. Thoughts?

**Comment by nileio** [comment]
> Right so if the storage directory is owned by dokku, the user creating the directory needs to be the dokku user _or_ you run as root.
Yeah that's right the user must be `dokku` or run as root.



> Maybe we should make a `storage:create-directory` command that creates that subdirectory and chowns as appropriate?

great suggestion, it definitely helps and saves couple of steps, however, the thing is .. that directory need to be managed constantly to copy data from some user-accessible directory to that location and then `chown -R` , that is recursively to change permissions. So not sure it solves the root cause there, ..
looks like we rather have different permissions on that particular location and make it rather owned by the user installing **dokku** in the first place, not sure ...

**Comment by josegonzalez** [comment]
If the directory needs to have files copied to it from another place, that is kind of up to you. Your script/automation should handle that. We can make the process of creating a directory and properly owning it easy, but anything else is up to whatever processes you have. In theory you could create a dokku plugin to automate that process too.

**Comment by nileio** [comment]
> If the directory needs to have files copied to it from another place, that is kind of up to you. Your script/automation should handle that. We can make the process of creating a directory and properly owning it easy, but anything else is up to whatever processes you have. In theory you could create a dokku plugin to automate that process too.

Yeah look I agree totally. 
I guess the alternative would be not to use that particular location and just directly mount other user-accssible location.

**Comment by josegonzalez** [comment]
The path we have in the docs is just so that users have a known directory to look at for storage folders. It's more of a convention than anything else. The permissions are set that way because the herokuish container starts the user/group with `32767:32767`, so ensuring the directory and it's contents are owned that way ensures that apps can properly access and modify files.

You're free to mount other paths if they work for you, which is why the `storage:mount` command takes a specified path versus assuming things.

**Comment by josegonzalez** [comment]
Just a note, the only concern with a different path is whether your app can read/write the files in that path. Other than that, the guidance is just there to make instructions straightforward for users, as folks otherwise asked where they should put their storage directories.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
