### ISSUE TITLE
Can't deploy with Dockerfile when setting dockerfile-path

### ISSUE THREAD

**Issue by fmorato** [dokku/dokku#4830]
Using a just deployed version of dokku v0.25.5. 

## Description of problem
I have couple of Dockerfiles, and would like to rename both of them to something other than Dockerfile. But Dokku doesn't recognize and builds with that dockerfile.

### Steps to Reproduce

1. Set up a project with a `Dockerfile-alternative` file name, for example
2. run `dokku builder-dockerfile:set myapp dockerfile-path Dockerfile-alternative`
3. Then `git push`

#### Actual Results
Build fails, as build is not detected for Dockerfile and buildpack can't detect what is my app.

#### Expected Results
Docker build is detected and is run.

If I undo and rename to Dockerfile, it is recognized and app is built.
I know almost nothing about the codebase, but a quick look gave the impression that detection doesn't take into account the config and is hardcoded. https://github.com/dokku/dokku/blob/master/plugins/builder-dockerfile/builder-detect#L29

**Comment by josegonzalez** [comment]
Seems we don't move the file into place during core-post-extract. I'll take a look.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. Thanks for reporting!
