### ISSUE TITLE
dokku_client.sh: the wrong app name is used if there are multiple apps on a single server

### ISSUE THREAD

**Issue by fomojola** [dokku/dokku#4838]
## Description of problem
Running multiple copies of the same app on a single server:

git remote -v:

prod	dokku@testserver:test2 (fetch)
prod	dokku@testserver:test2 (push)
stg	        dokku@testserver:test1(fetch)
stg   	dokku@testserver:test1 (push)

When I run `dokku --remote stg config:show` it incorrectly uses prod, because the code here (https://github.com/dokku/dokku/blob/master/contrib/dokku_client.sh#L107) that is filtering the remotes does not check if the same server is used in multiple remotes. Since the git remote -v call returns results in alphabetical order, attempts to communicate with the stg remote end up always using the prod app name.

### Steps to Reproduce

1. On a client machine, go to any directory and add 2 remotes to the same server. Name the first remote prod and the second stg
2. dokku --remote stg apps:report

#### Actual Results
=====> test2 app information
       App deploy source:             
       App dir:                       /home/dokku/test2
       App locked:                    false

#### Expected Results

=====> test1 app information
       App deploy source:             
       App dir:                       /home/dokku/test1
       App locked:                    false

### Additional information

The section in the main() function that looks like this:

```
DOKKU_REMOTE_HOST="$(fn-dokku-host "$DOKKU_GIT_REMOTE" "$DOKKU_HOST")"

  if [[ -z "$APP" ]]; then
    if [[ -d .git ]] || git rev-parse --git-dir >/dev/null 2>&1; then
      set +e
      APP=$(git remote -v 2>/dev/null | grep -Ei "dokku@$DOKKU_REMOTE_HOST" | head -n 1 | cut -f2 -d'@' | cut -f1 -d' ' | cut -f2 -d':' 2>/dev/null)
      set -e
    else
      echo " !     This is not a git repository" 1>&2
    fi
  fi
```
   Overwrites the DOKKU_GIT_REMOTE with the first remote it finds that uses the same host. However, if it was changed to this:

```
DOKKU_ORIGINAL_GIT_REMOTE="$DOKKU_GIT_REMOTE"  
  DOKKU_REMOTE_HOST="$(fn-dokku-host "$DOKKU_GIT_REMOTE" "$DOKKU_HOST")"

  if [[ -z "$APP" ]]; then
    if [[ -d .git ]] || git rev-parse --git-dir >/dev/null 2>&1; then
      set +e
      if [[ "dokku" == "$DOKKU_ORIGINAL_GIT_REMOTE" ]] ; then
        APP=$(git remote -v 2>/dev/null | grep -Ei "dokku@$DOKKU_REMOTE_HOST" | head -n 1 | cut -f2 -d'@' | cut -f1 -d' ' | cut -f2 -d':' 2>/dev/null)          
      else
        APP=$(git remote -v 2>/dev/null | grep "^$DOKKU_ORIGINAL_GIT_REMOTE\t" | grep -Ei "dokku@$DOKKU_REMOTE_HOST" | head -n 1 | cut -f2 -d'@' | cut -f1 -d' ' | cut -f2 -d':' 2>/dev/null)          
      fi
      set -e
    else
      echo "This is not a git repository"
    fi
  fi
```
  It would preserve the original remote information, and also filter for the specific remote specified on the command line.

**Comment by fomojola** [comment]
Also, note that the **fn-dokku-host** function may need to be updated: not quite sure about that.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
