### ISSUE TITLE
Allow users besides "dokku" to run dokku commands (remote access)

### ISSUE THREAD

**Issue by cburkins** [dokku/dokku#4851]
## Description of problem

Dokku forces you to use the user "dokku" when remotely accessing the server.    I'm not able to allow an arbitrary user to remotely access the server.   All users with remote access have to come from a central user repository (enabled via /etc/nsswitch.conf)

## Desired Solution

Rather than forcing to a single user "dokku", could you instead enable access based on group membership ?   So that way I could add my personal user account to the "dokku" group within /etc/group, and then when configuring the remote, I could do:

```
git remote add dokku chad@fqdn:repo
```

**Comment by josegonzalez** [comment]
You could do this by setting up `sshcommand` to send commands to the dokku binary (thats actually how it works now). The ssh key that a user uses has the command to run in it, and then sshcommand routes that appropriately. I don't know if there is a good way to support both normal ssh _and_ git push though, without having something that parses the ssh connection.

The alternative is to do https-based pushing, which then you could control in different ways (for example, user/password authentication would be possible, as would some token-based auth system). Dokku doesn't support that in the OSS project, but is something I've been including in a "Dokku Pro" offering (hopefully soon to be released). Would that be interesting to you?

**Comment by cburkins** [comment]
Thanks for the clue !   I was able to make it work.  I didn't understand how you were configuring the dokku user.  I didn't know you could hard-code a command into the ~/.ssh/authorized_keys file.   So I essentially copied ~dokku/.ssh/authorized_keys to ~cburkin/.ssh/authorized_keys, modifying to point at my own copy of ~dokku/.sshcommand.

**Comment by cburkins** [comment]
I should have mentioned, I did that config above using a secondary ssh key, not my primary ssh key.  The last trick is getting the git remote to use that secondary key, but achieved that by using an entry in ~/.ssh/config pointing to my secondary key, then when I created the git remote, I pointed to that entry in ~/.ssh/config

**Comment by cburkins** [comment]
Didn't realize you were creating a Pro version.  Sure, curious about that.   Have anything ready to read ?  If not, just send over when you do.

**Comment by josegonzalez** [comment]
There isn't too much save for the following:

- a simple page in our docs: https://dokku.com/docs/enterprise/pro/
- a mention at the bottom of the 0.26.x blog post: https://dokku.github.io/release/dokku-0.26.0

I'll post more details in a blog post and have a proper landing page over the next few days.
