### ISSUE TITLE
fpm config has a bug relative to version 4.11 of rpm

### ISSUE THREAD

**Issue by cburkins** [dokku/dokku#4852]
## Description of problem

Install fails on Centos7 (which I know is still experimental).   I think I'm here to help, not criticize :).   I've been developing my information over here: https://github.com/dokku/dokku/discussions/4848

But I'll try to reproduce here for you.

### How reproducible

Fresh install on CentOS 7

### Steps to Reproduce

1. Build a new CentOS 7 machine
2. Run the advertised install script

```
wget https://raw.githubusercontent.com/dokku/dokku/v0.25.6/bootstrap.sh;
DOKKU_TAG=v0.25.6 bash bootstrap.sh
```

3. Fails like this

```
--> Processing Dependency: or for package: dokku-0.25.6-1.x86_64
--> Processing Dependency: bindutils for package: dokku-0.25.6-1.x86_64
---> Package geoipupdate.x86_64 0:2.5.0-1.el7 will be installed
---> Package libtirpc.x86_64 0:0.2.4-0.16.el7 will be installed
--> Finished Dependency Resolution
Error: Package: dokku-0.25.6-1.x86_64 (dokku_dokku)
           Requires: or
Error: Package: dokku-0.25.6-1.x86_64 (dokku_dokku)
           Requires: bindutils
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

#### Expected Results

It should successfully install

## Environment Information

CentOS7 installation.  I ran a "yum update" to make sure everything is up-to-date.    Version of rpm is 4.11

### Additional information

Looks like you tweaked the fpm config in rpm.mk in commit 5c1d99a04c3c592da416454f6da0dd6eb4f32210 as such: 

```
	--depends '/usr/bin/docker' \
		--depends 'bind-utils or bindutils' \
		--depends 'cpio' \
		--depends 'curl' \
```

Looks like that  "or" logic "bind-utils or bindutils" was recently introduced in rpm 4.13; however, CentOS 7 by default runs rpm 4.11 so the install fails.

I can work around by altering your install to install the version of dokku just prior to that commit:

```
yum install dokku-0.24.10-1
```

Since your convenient bootstrap.sh script is specifically checking for CentOS 7, I figure this should be fixed ?

**Comment by josegonzalez** [comment]
Is there a way to do that `or` in older versions of rpm?

**Comment by josegonzalez** [comment]
I'm also personally fine with making a separate package just for photon.

**Comment by josegonzalez** [comment]
We could also make a stub dokku-bindutils package that depends on the right thing for each OS, then swap the dependency on the dokku side to that.

**Comment by cburkins** [comment]
Unsure how to accomplish the "or" in older versions of rpm; however, I think you're onto one of the accepted solutions, which is making that "stub" package that sorts out the dependency.

**Comment by josegonzalez** [comment]
Interesting, photon doesn't appear to be supported on Packagecloud. Is Photon based on something that isn't quite Centos, resulting in the bad package naming there?
