### ISSUE TITLE
Upgrade fails to complete when running dokku inside of an LXC container

### ISSUE THREAD

**Issue by buff0k** [dokku/dokku#4865]
Running Dokku and Docker in a Debian 11 LXC container with keyctl and nesting.

When attempting to do apt upgrade (to 0.25.7), upgrade requires reconfiguring of SSH keys and Hostname? Regardless of options chosen, proceeds to unpacking dokku and sits there for hours.

when using bootstrap.sh, same behaviour (except does not ask to reconfigure SSH keys and Hostname).

Seems to be an issue with the upgrade process?

**Comment by josegonzalez** [comment]
Can you do:

```shell
sudo su -
DOKKU_TRACE=1 TRACE=1 apt-get install dokku
```

The install scripts use those two env vars to output verbose debugging, so the above will be useful in figuring out where it's getting stuck/looping.

**Comment by josegonzalez** [comment]
https://github.com/dokku/dokku/commit/73b3c4af40575b7b1183ae871f0ec22678e9ab24 <-- this was it.

**Comment by josegonzalez** [comment]
@nemanjapetrovic I don't think you're issue is related. It seems you are installing onto Ubuntu Trusty (based on the output) and we no longer support that. Please file a new issue for your probkem.

**Comment by josegonzalez** [comment]
@buff0k okay sorry about the wait here.

I can create a new image here, but would you mind posting your steps on making that lxc environment? I'm hoping I can debug on my end/maybe even setup CI for this so we never break it :)

**Comment by buff0k** [comment]
Hi @josegonzalez , the thing of it is that I am thus far unable to replicate on any new LXC container build. There are some customizations that I made to the nginx-conf file (added an include for nginx sites-available so that I can also do reverse proxy for non dokku sites), but that doesn't seem to recreate the issue on a new container. What I do note is the dialogs when running the upgrade, which prompt me to configure the domain name, currently it is set to our domain name, but when I run apt upgrade or use the .sh, it shows the setting as dokku.me, perhaps the issue lies with the implementation of the changes caused by the dialogs? (They didn't exist prior to the 0.25.7 version)?
Alternatively I can create a replicated image and give you ssh access?

**Comment by josegonzalez** [comment]
None of those changed recently. Does the bug still exist with the latest 0.26.x releases?

**Comment by buff0k** [comment]
I have marked as unhold, these are the packages that are slated for upgrade:
dokku-event-listener/bullseye 0.9.1 amd64 [upgradable from: 0.7.0]
dokku-update/bullseye 0.3.1 amd64 [upgradable from: 0.2.0]
dokku/bullseye 0.26.4 amd64 [upgradable from: 0.25.6]

Results:
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
Reading changelogs... Done
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Preconfiguring packages ...
+ [[ -e /usr/share/debconf/confmodule ]]
+ . /usr/share/debconf/confmodule
++ '[' '!' 1 ']'
++ '[' -z '' ']'
++ exec
++ '[' '' ']'
++ exec
++ DEBCONF_REDIR=1
++ export DEBCONF_REDIR
+ readonly ACTION=configure
+ ACTION=configure
+ readonly VERSION=0.25.6
+ VERSION=0.25.6
+ db_input high dokku/nginx_enable
+ _db_cmd 'INPUT high' dokku/nginx_enable
+ _db_internal_IFS='
'
+ IFS=' '
+ printf '%s\n' 'INPUT high dokku/nginx_enable'
+ IFS='
'
+ read -r _db_internal_line
+ IFS='
'
+ RET='question will be asked'
+ case ${_db_internal_line%%[   ]*} in
+ return 0
+ db_input high dokku/hostname
+ _db_cmd 'INPUT high' dokku/hostname
+ _db_internal_IFS='
'
+ IFS=' '
+ printf '%s\n' 'INPUT high dokku/hostname'
+ IFS='
'
+ read -r _db_internal_line
+ IFS='
'
+ RET='question will be asked'
+ case ${_db_internal_line%%[   ]*} in
+ return 0
+ db_input high dokku/vhost_enable
+ _db_cmd 'INPUT high' dokku/vhost_enable
+ _db_internal_IFS='
'
+ IFS=' '
+ printf '%s\n' 'INPUT high dokku/vhost_enable'
+ IFS='
'
+ read -r _db_internal_line
+ IFS='
'
+ RET='question will be asked'
+ case ${_db_internal_line%%[   ]*} in
+ return 0
+ '[' configure '!=' reconfigure ']'
+ db_input high dokku/key_file
+ _db_cmd 'INPUT high' dokku/key_file
+ _db_internal_IFS='
'
+ IFS=' '
+ printf '%s\n' 'INPUT high dokku/key_file'
+ IFS='
'
+ read -r _db_internal_line
+ IFS='
'
+ RET='question will be asked'
+ case ${_db_internal_line%%[   ]*} in
+ return 0
+ db_go
+ _db_cmd 'GO '
+ _db_internal_IFS='
'
+ IFS=' '
+ printf '%s\n' 'GO '
+ IFS='
'
+ read -r _db_internal_line
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory

Package configuration






                        lqqqqu Configuring dokku tqqqqqk
                        x                              x
                        x                              x
                        x                              x
                        x Enable nginx-vhosts plugin?  x
                        x                              x
                        x     <Yes>        <No>        x
                        x                              x
                        mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj








Package configuration






                        lqqqqu Configuring dokku tqqqqqk
                        x                              x
                        x                              x
                        x Hostname or IP for server:   x
                        x                              x
                        x dokku.me____________________ x
                        x                              x
                        x            <Ok>              x
                        x                              x
                        mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj







Package configuration






                      lqqqqqqu Configuring dokku tqqqqqqqk
                      x                                  x
                      x                                  x
                      x                                  x
                      x Enable vhost-based deployments?  x
                      x                                  x
                      x       <Yes>          <No>        x
                      x                                  x
                      mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj








Package configuration






                        lqqqqu Configuring dokku tqqqqqk
                        x                              x
                        x                              x
                        x Keyfile for initial user:    x
                        x                              x
                        x /root/.ssh/id_rsa.pub_______ x
                        x                              x
                        x            <Ok>              x
                        x                              x
                        mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj






+ IFS='
'
+ RET=ok
+ case ${_db_internal_line%%[   ]*} in
+ return 0
(Reading database ... 83954 files and directories currently installed.)
Preparing to unpack .../dokku_0.26.4_amd64.deb ...
+ readonly DOKKU_ROOT=/home/dokku
+ DOKKU_ROOT=/home/dokku
+ readonly DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ main upgrade 0.26.4
+ grep -- --purge
+ ps_backtrace 68521
+ grep dpkg

**Comment by AmandaCameron** [comment]
So, I was hitting this problem myself, when I had a brain-wave. I was getting it when I did `lxc shell host:dokku` -- that spawns a shell in the lxc container, which will possibly not have a valid parent pid inside the container's PID Namespace. `ssh root@dokku-host` and suddenly I could upgrade from 0.25.7 ->  0.26.4

**Comment by josegonzalez** [comment]
@AmandaCameron what is the output of `ps auxf` when you spawn that shell?

**Comment by josegonzalez** [comment]
The thing we need to do is figure out if the `--purge` flag was passed to `dpkg` during `prerm` as Debian doesn't let us know in `prerm` if we are purging the install. If there is a way to detect that otherwise, I'm all ears.

Does anyone have the exact steps I might be able to replicate the lxc environment?

**Comment by AmandaCameron** [comment]
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         142  0.0  0.0  12716  4348 pts/1    Ss   17:09   0:00 su -l
root         207  0.0  0.0  10772  5032 pts/1    S    17:09   0:00  \_ -bash
root       11243  0.0  0.0  11864  3600 pts/1    R+   17:09   0:00      \_ ps auxf
root           1  0.0  0.1 169456 10804 ?        Ss   17:09   0:00 /sbin/init
root          78  0.0  0.3  91264 32092 ?        Ss   17:09   0:00 /lib/systemd/systemd-journald
root          91  0.0  0.0  21616  4740 ?        Ss   17:09   0:00 /lib/systemd/systemd-udevd
systemd+     113  0.0  0.0  26612  6704 ?        Ss   17:09   0:00 /lib/systemd/systemd-networkd
systemd+     130  0.0  0.1  23968 12624 ?        Ss   17:09   0:00 /lib/systemd/systemd-resolved
root         146  0.0  0.0   9420  2952 ?        Ss   17:09   0:00 /usr/sbin/cron -f
message+     147  0.0  0.0   7384  4032 ?        Ss   17:09   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root         149  0.0  0.1 710272  8980 ?        Ssl  17:09   0:00 /usr/bin/dokku-event-listener
root         151  0.0  0.2  31636 18084 ?        Ss   17:09   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
syslog       153  0.0  0.0 154720  4240 ?        Ssl  17:09   0:00 /usr/sbin/rsyslogd -n -iNONE
root         156  0.0  0.0  16800  7424 ?        Ss   17:09   0:00 /lib/systemd/systemd-logind
root         158  0.0  0.4 1714984 41232 ?       Ssl  17:09   0:00 /usr/bin/containerd
root         160  0.0  0.0   8208  2240 pts/0    Ss+  17:09   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
root         161  0.0  0.0  76644  5936 ?        Ss   17:09   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data    7659  0.0  0.0  76884  5484 ?        S    17:09   0:00  \_ nginx: worker process
www-data    7660  0.0  0.0  76884  5484 ?        S    17:09   0:00  \_ nginx: worker process
www-data    7661  0.0  0.0  76884  5484 ?        S    17:09   0:00  \_ nginx: worker process
www-data    7663  0.0  0.0  76884  5484 ?        S    17:09   0:00  \_ nginx: worker process
www-data    7664  0.0  0.0  76884  5484 ?        S    17:09   0:00  \_ nginx: worker process
www-data    7665  0.0  0.0  76884  5484 ?        S    17:09   0:00  \_ nginx: worker process
www-data    7667  0.0  0.0  76884  5484 ?        S    17:09   0:00  \_ nginx: worker process
www-data    7668  0.0  0.0  76884  5484 ?        S    17:09   0:00  \_ nginx: worker process
root         181  0.0  0.0  12184  6952 ?        Ss   17:09   0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root         195  0.0  1.5 1754664 127008 ?      Ssl  17:09   0:02 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root         198  0.0  0.0  16264  6316 ?        Ss   17:09   0:00 /lib/systemd/systemd-hostnamed
root         199  0.0  0.2 110512 21084 ?        Ssl  17:09   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
root         201  0.0  0.1  18168  9308 ?        Ss   17:09   0:00 /lib/systemd/systemd --user
root         202  0.0  0.0 170808  3644 ?        S    17:09   0:00  \_ (sd-pam)
root         357  0.0  0.0 712216  8040 ?        Sl   17:09   0:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 1a76ae96eaeeea42efa3fb8d73acedfbfa8e6f16c331c94b857913bb6d1a4b03 -addre
root         377  0.0  0.0   1112     4 ?        Ss   17:09   0:00  \_ /sbin/docker-init -- /start web
root         409  0.0  0.0   5828  2440 ?        Sl   17:09   0:00      \_ /start web
32767        416  0.0  0.0   3984  3180 ?        S    17:09   0:00          \_ /bin/bash bin/cgid
32767        964  0.0  0.0   3984  2980 ?        S    17:09   0:00              \_ /bin/bash bin/request-handler
32767        965  0.0  0.0   2608  1896 ?        S    17:09   0:00              \_ bin/nc -c -l -p 5000
dokku        569  0.0  0.0  10240  4300 ?        Ss   17:09   0:00 bash /usr/bin/dokku ps:restore
dokku        609  0.0  0.0 1075848 4456 ?        Sl   17:09   0:00  \_ /var/lib/dokku/plugins/enabled/ps/subcommands/restore ps:restore
dokku      10297  0.0  0.0 105868  3328 ?        Sl   17:09   0:00      \_ plugn trigger release-and-deploy dashboard latest
dokku      10305  0.0  0.0   1600  1264 ?        S    17:09   0:00          \_ /home/dokku/.basher/bash -c main 'trigger' 'release-and-deploy' 'dashboard' 'latest'
dokku      10493  0.0  0.0  10160  3904 ?        S    17:09   0:00              \_ bash /var/lib/dokku/plugins/enabled/common/release-and-deploy dashboard latest
dokku      10586  0.0  0.0 105868  3332 ?        Sl   17:09   0:00                  \_ plugn trigger builder-release herokuish dashboard latest
dokku      10593  0.0  0.0   1608  1268 ?        S    17:09   0:00                      \_ /home/dokku/.basher/bash -c main 'trigger' 'builder-release' 'herokuish' 'dashboard' 'latest'
dokku      10733  0.0  0.0  10160  4028 ?        S    17:09   0:00                          \_ bash /var/lib/dokku/plugins/enabled/builder-herokuish/builder-release herokuish dashboard latest
dokku      11184  0.0  0.5 1498444 47764 ?       Sl   17:09   0:00                              \_ docker image build --label=org.label-schema.schema-version=1.0 --label=org.label-schema.vend
```

**Comment by AmandaCameron** [comment]
Compaired to from under ssh:
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.1 169456 10860 ?        Ss   17:09   0:00 /sbin/init
root          78  0.0  0.4  91264 36620 ?        Ss   17:09   0:00 /lib/systemd/systemd-journald
root          91  0.0  0.0  21616  4748 ?        Ss   17:09   0:00 /lib/systemd/systemd-udevd
systemd+     113  0.0  0.0  26612  6704 ?        Ss   17:09   0:00 /lib/systemd/systemd-networkd
systemd+     130  0.0  0.1  23968 12624 ?        Ss   17:09   0:00 /lib/systemd/systemd-resolved
root         146  0.0  0.0   9420  2952 ?        Ss   17:09   0:00 /usr/sbin/cron -f
message+     147  0.0  0.0   7384  4032 ?        Ss   17:09   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root         149  0.0  0.1 710272  9424 ?        Ssl  17:09   0:00 /usr/bin/dokku-event-listener
root         151  0.0  0.2  31636 18096 ?        Ss   17:09   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
syslog       153  0.0  0.0 154720  4240 ?        Ssl  17:09   0:00 /usr/sbin/rsyslogd -n -iNONE
root         156  0.0  0.0  16800  7424 ?        Ss   17:09   0:00 /lib/systemd/systemd-logind
root         158  0.0  0.5 1714984 43048 ?       Ssl  17:09   0:00 /usr/bin/containerd
root         160  0.0  0.0   8208  2240 pts/0    Ss+  17:09   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
root         161  0.0  0.0  76680  5992 ?        Ss   17:09   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data   86504  0.0  0.0  76920  5620 ?        S    17:10   0:00  \_ nginx: worker process
www-data   86506  0.0  0.0  76920  5620 ?        S    17:10   0:00  \_ nginx: worker process
www-data   86507  0.0  0.0  76920  5620 ?        S    17:10   0:00  \_ nginx: worker process
www-data   86509  0.0  0.0  76920  5620 ?        S    17:10   0:00  \_ nginx: worker process
www-data   86510  0.0  0.0  76920  5620 ?        S    17:10   0:00  \_ nginx: worker process
www-data   86511  0.0  0.0  76920  5620 ?        S    17:10   0:00  \_ nginx: worker process
www-data   86514  0.0  0.0  76920  5620 ?        S    17:10   0:00  \_ nginx: worker process
www-data   86515  0.0  0.0  76920  5620 ?        S    17:10   0:00  \_ nginx: worker process
root         181  0.0  0.0  12184  6952 ?        Ss   17:09   0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root       86643  0.0  0.1  13824  8936 ?        Ss   17:11   0:00  \_ sshd: root@pts/1
root       86664  0.0  0.0  10772  5008 pts/1    Ss   17:11   0:00      \_ -bash
root       86675  0.0  0.0  11864  3588 pts/1    R+   17:12   0:00          \_ ps auxf
root         195  0.0  1.1 1755176 92660 ?       Ssl  17:09   0:26 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root         199  0.0  0.2 110512 21084 ?        Ssl  17:09   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
root         357  0.0  0.1 712856  8504 ?        Sl   17:09   0:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 1a76ae96eaeeea42efa3fb8d73acedfbfa8e6f16c331c94b857913bb6d1a4b03 -addre
root         377  0.0  0.0   1112     4 ?        Ss   17:09   0:00  \_ /sbin/docker-init -- /start web
root         409  0.0  0.0   5828  2440 ?        Sl   17:09   0:00      \_ /start web
32767        416  0.0  0.0   3984  3180 ?        S    17:09   0:00          \_ /bin/bash bin/cgid
32767        964  0.0  0.0   3984  2980 ?        S    17:09   0:00              \_ /bin/bash bin/request-handler
32767        965  0.0  0.0   2608  1896 ?        S    17:09   0:00              \_ bin/nc -c -l -p 5000
root       25235  0.0  0.1 712856  8816 ?        Sl   17:10   0:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 04953ab64f6ea1acacb39729fe374dee0360d6059ce6e51727bf2fa24655214d -addre
root       25255  0.0  0.0   1112     4 ?        Ss   17:10   0:00  \_ /sbin/docker-init -- /start web
root       25288  0.0  0.0 104324  2712 ?        Sl   17:10   0:00      \_ /start web
32767      25296  0.0  0.0   3984  3132 ?        S    17:10   0:00          \_ /bin/bash -e bin/boot
32767      29336  0.0  0.0   3984  1756 ?        S    17:10   0:00              \_ /bin/bash -e bin/boot
32767      29338  0.0  0.0   2660   584 ?        S    17:10   0:00              |   \_ cat logs/access.log
32767      29337  0.0  0.0   3984  1756 ?        S    17:10   0:00              \_ /bin/bash -e bin/boot
32767      29339  0.0  0.1  13420  9292 ?        S    17:10   0:00                  \_ nginx: master process bin/nginx -p . -c config/nginx.conf
32767      29340  0.0  0.0  14264  3268 ?        S    17:10   0:00                      \_ nginx: worker process
32767      29341  0.0  0.0  14264  3268 ?        S    17:10   0:00                      \_ nginx: worker process
32767      29342  0.0  0.0  14264  3268 ?        S    17:10   0:00                      \_ nginx: worker process
32767      29343  0.0  0.0  14264  3268 ?        S    17:10   0:00                      \_ nginx: worker process
32767      29344  0.0  0.0  14264  3268 ?        S    17:10   0:00                      \_ nginx: worker process
32767      29345  0.0  0.0  14264  3268 ?        S    17:10   0:00                      \_ nginx: worker process
32767      29346  0.0  0.0  14264  3268 ?        S    17:10   0:00                      \_ nginx: worker process
32767      29347  0.0  0.0  14264  3268 ?        S    17:10   0:00                      \_ nginx: worker process
root       86646  0.0  0.1  18288  9408 ?        Ss   17:11   0:00 /lib/systemd/systemd --user
root       86647  0.0  0.0 170808  3832 ?        S    17:11   0:00  \_ (sd-pam)
```

**Comment by AmandaCameron** [comment]
Thinking more on it, you can probably get a similar setup to reprecate the problem in ps_backtrace via `docker exec` inside an existing container. I suspect the `ps` chain you're doing might have a similar output in both cases.

**Comment by buff0k** [comment]
@AmandaCameron Thank you, I did not think of trying to directly login to the container via SSH (We don't allow remote root logon by default), doing so via root allowed the installation to complete, this confirms that it must be a PID issue.

**Comment by josegonzalez** [comment]
So how do I create this lxc environment thing?

**Comment by AmandaCameron** [comment]
I'd say try checking what the output of looking for the pid of 1 is, and
breaking on that instead, as that'll also apply to the pid that started
from the `lxc shell foo`

**Comment by josegonzalez** [comment]
I've never used lxc before. I'm asking how to get started with that so I can replicate the environment to test out a fix. I can setup a new VM via Vagrant + Vmware, and can also use DigitalOcean (or AWS in a pinch) if either support lxc.

**Comment by buff0k** [comment]
@josegonzalez I use Proxmox VE (Virtialization Platform built on Debian) and then deploy a Debian 11-01 LXC Template from the default Repo. Unfortunately I haven't tried deploying LXC containers from vanilla linux.
You could install Proxmox in a VM with nested virtualization and go from there?

**Comment by josegonzalez** [comment]
Does proxmox run on digitalocean?

**Comment by buff0k** [comment]
It should run on a Debian installation:
https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster

**Comment by josegonzalez** [comment]
Honestly I don't have time to debug this issue and I also don't run this setup. If someone can give me exact instructions to replicate this on a hosting provider such as Digitalocean or AWS, I can try to take a look, but for now it's just going to be unsupported. Sorry.
