### ISSUE TITLE
Supplying GDAL libraries to Django deployed on Dokku?

### ISSUE THREAD

**Issue by chrisjdixon** [dokku/dokku#4892]
[Asked over at SO](https://stackoverflow.com/questions/69775260/django-geodjango-cant-find-the-gdal-library-on-ubuntu-dokku): I'm trying to supply GDAL libraries to Django deployed on Dokku running on Postgis / Postgres and am struggling to troubleshoot the issue. We haven't got any responses to our question which suggests it might have something to do with Dokku.

I don't really know what I'm doing but I think Dokku can't access files more broadly on Ubuntu unless it's in some type of [persistent storage](https://dokku.com/docs/advanced-usage/persistent-storage/). If we've installed GDAL libraries as detailed in our SO question would Django not being able to access them while deployed in Dokku explain our issue? If so, how could we address this? Is there something else we're missing?

Also, we're wary this issue might not have anything to do with Dokku and we're new to Ubuntu so we're probably doing something silly, so apologies for a stupid question.

**Comment by Schlepptop** [comment]
Dokku deploys your app within a Docker Container, which you can think of as a virtual environment for your app that is completely seperate from your host system. It is possible to make files from your host available to this container, but for your usecase that's not the way to go.
You should install the GDAL libraries during the build phase of your container, which you can do by adding the following to your Dockerfile:
```
# Update and clean
RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean

# Install gdal
RUN apt-get install -y libgdal-dev

# Update C env vars so compiler can find gdal
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

# Clean up after your installs
RUN apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
```

This should be sufficient for Django to find the libs it's looking for.

**Comment by chrisjdixon** [comment]
Awesome, thank you! I've never used Dockerfiles before and am a little confused at how to specifically do this. Mind if I ask another dumb question?

I've figured out I need to place a file called exactly "Dockerfile" in the top level dir, and I've entered what you supplied but Dokku says "Error response from daemon: no build stage in current context". [This SO answer](https://stackoverflow.com/a/50453357/4107349) suggests checking whether the file has a `FROM repo/image`. I've tried adding `FROM scatch` at the top and now have this error:
```
remote: Step 1/9 : FROM scratch
remote:  --->
remote: Step 2/9 : RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
remote:  ---> Running in 5ee84625d1c6
remote: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```
Have I added `FROM scratch` mistakenly and do you know how I can address this from here?

Again, thanks for the help and sorry for the dumb questions not specific to Dokku.

**Comment by josegonzalez** [comment]
The following are general guidelines to follow for adding OS-level packages to your build environment:

- Herokuish buildpacks (default): Use the [dokku-apt](https://github.com/dokku-community/dokku-apt) package
- Pack CNB buildpacks: Use this [apt buildpack](https://github.com/fagiani/apt-buildpack)
- Dockerfile (if your app has  `Dockerfile`): modify your `Dockerfile` to include the packages you want.

Hope that helps.
