### ISSUE TITLE
Surprising shell interpolation messed my config values

### ISSUE THREAD

**Issue by benjamin-thomas** [dokku/dokku#4896]
## Description of problem

A surprising change of behavior happened between `v0.25.4` and `v0.26.3`

### How reproducible

Prior to `v0.26.3`,  I could inject an env var like this:

```
dokku config:set my_app VAR='$123*&456$'
```

And my app would indeed access `VAR` as `$123*&456$`

Upgrading to 0.26 caused `VAR` to be truncated as: `*&456$`. Note that this value was set months ago so this caused a production failure for me.

Furthermore, if i run this command on 0.26:

```
dokku config:set my_app VAR='$123'
```

Then other completely unrelated config values get interpolated

```
# I'm in my container here
env | grep VAR
VAR=--env=API=AAA
```

By using a leading backslash, I'm able to once again feed in the proper values to my app

```
dokku config:set my_app VAR='\$123'
```

```
# I'm in my container here
env | grep VAR
VAR=$123
```

I wouldn't think this change of behavior was intended (surprising!)

It seems `$` gets evaluated by the shell somehow.

Let me know if you need more info

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

Additionally, are these variables being set via the ssh client or directly on the server? Finally, are they being set on a herokuish app, dockerfile, or something else?

**Comment by josegonzalez** [comment]
We _did_ change how we start containers to set env vars in the environment of the container creation call [here](https://github.com/dokku/dokku/compare/v0.25.4...master#diff-84e51ae41852e11b7279c69b4c9ce8c56209c7c188f69569294d7d0fa2a0b3f5R240-R253) to fix a bug, but none of the tests failed. That said, dunno that we had a test for `$`, and this shouldn't have broken anything.

**Comment by josegonzalez** [comment]
I think this is related to #4895. I have a potential fix, but I'd like to also add some tests to verify. Fix incoming!

**Comment by benjamin-thomas** [comment]
I toggle my apps between 2 servers each week so I gathered the change was close enough for you to have a clue about when or where that change occurred (I update and reboot a server then redirect all the traffic to it. The other server gets updated the next week, and so on)

Both servers are identical.

```
root@dokku-blue:~# dokku version
dokku version 0.25.4

root@dokku-green:~# dokku version
dokku version 0.26.3
```

```
root@dokku-blue:~# cat /etc/apt/sources.list.d/dokku.list 
deb https://packagecloud.io/dokku/dokku/ubuntu/ focal main

root@dokku-green:~# cat /etc/apt/sources.list.d/dokku.list 
deb https://packagecloud.io/dokku/dokku/ubuntu/ focal main
```

...ok I see you probably found the potential source of the bug so I'm stopping there.

Let me know if you need anything else.

Reverting to the prior behavior seems to be the way to go as this looks like a potential for code execution

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. Thanks for reporting.
