### ISSUE TITLE
Add ability to send cron logs somewhere and add a way to tail cron output

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#4902]
Atm the output just _disappears_ into the ether. It would be nice to be able to do:

```
dokku logs:cron $app $cron_id
```

And get the log output. The log output would be fetched from a new triggers, `logs-cron-output $scheduler $app $cron_id`

For docker-local, that would be tailing a log file (we can write to `/var/log/dokku/$app-$cron_id.log`). For others, it depends :)

Might also be good to move cron writing to a `scheduler-cron-write` trigger, and each scheduler plugin implements it on it's own.

**Comment by tadamcz** [comment]
As a workaround, it's already possible to have the output not disappear into the ether as noted here https://github.com/dokku/dokku/discussions/4986#discussioncomment-2141856 : 

> just redirect all the output (stdout and stderr) to a file on the host. Something like this would do:
> 
> `mycommand &>> /var/log/myservice/somelog.txt`
> The myservice directory here need to be writeable by the dokku user.

**Comment by josegonzalez** [comment]
I'm going to close this. Cron task logs are shippable via our `vector` integration, which should be what folks use to grab their logs and shunt them anywhere. Doing any more would mean duplicating the work that went into that integration, and I'd rather not if possible.
