### ISSUE TITLE
Guide on how to to upgrade herokuish from source is outdated

### ISSUE THREAD

**Issue by IlyaSemenov** [dokku/dokku#4944]
### Steps to Reproduce

Per https://github.com/dokku/dokku/blob/e0c2e7846a551c21fab7595737ae3b988d59578e/docs/getting-started/upgrading.md#upgrading-from-source, following _"To upgrade Herokuish from source, upgrade with"_:

```
root@hz1 /etc/apt # cd /tmp
root@hz1 /tmp # git clone https://github.com/gliderlabs/herokuish.git
Cloning into 'herokuish'...

remote: Enumerating objects: 5445, done.
remote: Counting objects: 100% (636/636), done.
remote: Compressing objects: 100% (386/386), done.
remote: Total 5445 (delta 326), reused 401 (delta 191), pack-reused 4809
Receiving objects: 100% (5445/5445), 1.96 MiB | 13.40 MiB/s, done.
Resolving deltas: 100% (2856/2856), done.
root@hz1 /tmp # cd herokuish
root@hz1 /tmp/herokuish # git pull origin master

From https://github.com/gliderlabs/herokuish
 * branch            master     -> FETCH_HEAD
Already up to date.
root@hz1 /tmp/herokuish # IMAGE_NAME=gliderlabs/herokuish BUILD_TAG=latest VERSION=master make -e build-in-docker
make: *** No rule to make target 'build-in-docker'.  Stop.
```

#### Actual Results

Build fails. (meaning the guide is apparently outdated)

#### Expected Results

Build completes, local herokuish image is updated.

### Additional info

The published herokuish ubuntu package uses buildpack-static v14 which fails to compile (that was fixed in v15, but herokuish with the updated buildpack has not been yet published). That's why I decided to upgrade herokuish locally.

**Comment by IlyaSemenov** [comment]
FWIW, I apparently managed to update it with `docker build -t gliderlabs/herokuish:latest-20 .` - not sure how incorrect is that.

**Comment by josegonzalez** [comment]
Probably makes sense to just link to the herokuish docs...

**Comment by josegonzalez** [comment]
Mind making a PR doing that?

**Comment by IlyaSemenov** [comment]
Yep, but the problem is, I didn't find any relevant herokuish documentation.

https://github.com/gliderlabs/herokuish doesn't mention anything about building it, only about using it.

I had to figure `latest-20` by looking at the failing containers and tracing the image being used. (I could also possibly infer that from [.circleci/config.yml](https://github.com/gliderlabs/herokuish/blob/65d6aa5e5fc9a324362451b10c7b577c45bc5f73/.circleci/config.yml), but obviously that's not really the docs one links to).

**Comment by josegonzalez** [comment]
Looks like `make build` is what we want.

Mind updating the herokuish docs and then updating ours to link to them?

**Comment by IlyaSemenov** [comment]
> Looks like `make build` is what we want.

`make build` needs local go which is kind of overkill. `make docker/build` looks more like it, but for it to actually work I submitted a small PR for herokuish.
