### ISSUE TITLE
Docs for installing on hosting providers still rely on the deprecated web installer

### ISSUE THREAD

**Issue by namiwang** [dokku/dokku#4947]
Documents for installing on hosting providers like [install on azure](https://dokku.com/docs/getting-started/install/azure/) and [install on DO](https://dokku.com/docs/getting-started/install/digitalocean/) still guide the user to access the web installer, which is now deprecated.

**Comment by josegonzalez** [comment]
Unfortunately the Digitalocean image is still not on the latest (I really need to get control over it...) but I'll work through the other install docs.
