### ISSUE TITLE
Docker-compose to dokku commands

### ISSUE THREAD

**Issue by stockmind** [dokku/dokku#4953]
Hi!
Last spring I found myself needing to convert several docker-compose files for different apps to make them run on dokku, so I've put together a little utility to try to speed up the process. In the meanwhile, I've forgotten about it and just had occasion recently to clean up a bit the code and upload it somewhere.
I don't know if there's a more appropriate place to report this, but should anyone need to convert simple docker-compose without having to write all the commands by hand, here it is:

https://dokkupose.netlify.app/
https://github.com/stockmind/dokkupose

The converter is super simple and stupid, nothing fancy, but it worked for my use cases. I had fun writing a tokenizer for Monaco that try to syntax highlight commands for dokku. It's not perfect but works most of the time.

I'm pointing this out in case you want to add it to a section in case you plan to add something like Utilities among the COMMUNITY CONTRIBUTIONS.

Hope it can save some time to other people 😄

**Comment by josegonzalez** [comment]
Does any of this run on server-side, or is it all client-side?

**Comment by josegonzalez** [comment]
My question is because I'd _love_ to have this hosted as an official project on our site, and we can setup auto-deploys etc. and route to it like `dokku.com/compose`? I'd rather not have folks submit their code to our server(s), hence the question.

**Comment by stockmind** [comment]
Wow, that would be great! Everything runs exclusively client-side in the user browser, the application is a simple static HTML page + Vue.js compiled magic.

**Comment by josegonzalez** [comment]
Do you mind giving me (`josegonzalez`) admin rights on that repo so I can transfer it to our org and get the process kickstarted?

**Comment by stockmind** [comment]
Sure, I've sent you an invitation right away. I think I need to wait for you to accept to give you admin rights.

**Comment by josegonzalez** [comment]
I've accepted, mind raising my rights to whatever is highest? I can move the repo from there.

You could also transfer the repository to my username, that might work.

**Comment by stockmind** [comment]
Odd, I'm used to another UI for repository access permissions but maybe is valid only for Organization repositories, on this personal repository i couldn't find how to give you admin rights. I've just sent you a request to transfer ownership as you suggested so it would be easier.

**Comment by josegonzalez** [comment]
I just moved it to `dokku/compose-transpiler` and invited you to a team to edit it. I'll try and get it deployed this week at the path I specified above and will comment on this issue when thats up.

Thanks again for the neat tool!

**Comment by stockmind** [comment]
Thank you very much, I will also try to improve and polish it in the next weeks to make it more robust and complete 😄
