### ISSUE TITLE
ps:restore on boot is ran serially. Provide option or make default to run in parallel

### ISSUE THREAD

**Issue by chemicalkosek** [dokku/dokku#4967]
[Feature request]

Restoring all apps on server reboot runs `restore` in serial mode:
`dokku-redeploy` logs:
```
!     Running restore in serial mode
```
Provide an option or make it default to run in parallel and use all available CPU's (`--parallel -1`)

Related slack thread: https://gliderlabs.slack.com/archives/C0FP0R13J/p1638463645038200
Related docs change issue: https://github.com/dokku/dokku/issues/4966

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
