### ISSUE TITLE
[Feature request] Add a way to mount additional path to Vector container

### ISSUE THREAD

**Issue by divtiply** [dokku/dokku#4971]
Some Vector log sinks, e.g. https://vector.dev/docs/reference/configuration/sinks/gcp_stackdriver_logs/ require additional files for their configuration. Currently there is no clean way to provide such files to the Vector container.
One way I can think of is to extend log sink DSN format with bind mount form: `key@=/host/location:/container/location`.

**Comment by josegonzalez** [comment]
We could probably mount a `$DOKKU_LIB_ROOT/data/logs` path into the container - maybe into `/data`? - and then any configs can reference that folder?

**Comment by divtiply** [comment]
It might be cleaner to mount directory `/var/lib/dokku/data/logs:/etc/vector` to match existing `/var/lib/dokku/data/logs/vector.json:/etc/vector/vector.json`

**Comment by josegonzalez** [comment]
Hmmm that makes sense. Can you enter that container and check if there are any other files we might accidentally override if we do that?

**Comment by divtiply** [comment]
There are other vector configuration files there:

**Comment by josegonzalez** [comment]
Whats the toml file contents? I'm guessing we _should_ be able to override, but since the image isn't controlled by us, it's not unlikely they add something else there in the future...

**Comment by divtiply** [comment]
From https://hub.docker.com/r/timberio/vector
> As shown above, you can pass a custom Vector configuration file via the -v flag. You'll want to do this since the default /etc/vector/vector.toml configuration file doesn't do anything.
Looking at vector sources it looks safe to mount to /etc/vector, e.g. https://github.com/vectordotdev/vector/blob/ca4f68e148140a8503eac8f5266ff7a2ba27dffc/distribution/helm/vector-agent/templates/daemonset.yaml#L112, even better it will make possible to manage complex configs https://github.com/vectordotdev/vector/blob/master/website/content/en/guides/level-up/managing-complex-configs.md

**Comment by josegonzalez** [comment]
Again, if you can open a ticket for the vector project to see if thats okay, that would be great. Their docs are ambiguous and I'd rather not accidentally break something in the future for a fix today.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
