### ISSUE TITLE
bash_completion: ADD autocomplete app names

### ISSUE THREAD

**Issue by allanlaal** [dokku/dokku#4982]
would be convenient if in dokku cli commands APP_NAME would be tab-completed (none = show list of all apps)

## Environment Information

Ubuntu Server 18.04
dokku version 0.26.6

### `dokku report APP_NAME` output

not applicable

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?

by `dokku-update run -s` from:
`deb https://packagecloud.io/dokku/dokku/ubuntu/ bionic main`

**Comment by allanlaal** [comment]
would plugins be able to use the same autocomplete mechanism?

**Comment by josegonzalez** [comment]
That would be nice. Plugins probably could.

Not sure how this would be implemented, but I'll keep this open if someone wants to take a stab at it.

**Comment by allanlaal** [comment]
would each plugin have to implement their own autocomplete mechanism for their own non APP_NAME list data?

*i.e. `dokku mariadb:link <service> <app> `*

how would bash_completion know which autocomplete is wanted?

**Comment by allanlaal** [comment]
vote: just merge ALL lists and offer from them

**Comment by josegonzalez** [comment]
The dokku project would need to provide some sort of hooks for that. I think maybe just supporting the core first is a good step.

**Comment by josegonzalez** [comment]
This is our current completion code: https://github.com/dokku/dokku/blob/be01d2f7ec9903b6d0a96b1a0693c23cb82cb4ad/contrib/bash-completion

Feel free to investigate how bash completion works and come back with your findings (preferably in a single comment, not across several comments).

**Comment by josegonzalez** [comment]
Going to close this issue. I'm definitely interested in the functionality if someone wants to work on it, but I won't be actively working on this so I'll close it so as to not clutter the issue tracker.
