### ISSUE TITLE
Error destroying an app if nginx is disabled.

### ISSUE THREAD

**Issue by fomojola** [dokku/dokku#4987]
## Description of problem

If the nginx service on the server running Dokku is disabled (as it is for me since I'm using an alternate proxy), attempting to destroy an application fails because the nginx-vhosts plugin (specifically https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/functions#L131) always runs, even if the app doesn't use the nginx proxy.

### How reproducible

Always

### Steps to Reproduce

Done on an Ubuntu 20.04 LTS instance.

1. Install Dokku
2. Create an app: `dokku apps:create updates.p`
3. Disable nginx using `systemctl disable nginx`
4. Attempt to destroy the app: `dokku apps:destroy updates.p`

#### Actual Results
root@dev:/home/dokku/updates.p# dokku apps:destroy updates.p
 !     WARNING: Potentially Destructive Action
 !     This command will destroy app updates.p.
 !     To proceed, type "updates.p"
> updates.p
-----> Destroying updates.p (including all add-ons)
nginx.service is not active, cannot reload.
!     exit status 1

#### Expected Results
root@dev:/home/dokku/updates.p# dokku apps:destroy updates.p
 !     WARNING: Potentially Destructive Action
 !     This command will destroy app updates.p.
 !     To proceed, type "updates.p"
> updates.p
-----> Destroying updates.p (including all add-ons)
-----> Cleaning up...
-----> Retiring old containers and images

## Environment Information

App was destroyed before I got to dump this, but it always works.

### Additional information

The fix for this is to check if the app is using the nginx proxy and if not don't bother doing the reload. The following block fixes this for me:

    local PROXY_ENABLED="$(plugn trigger proxy-is-enabled "$APP")" 
    local PROXY_TYPE="$(plugn trigger proxy-type "$APP")"      
    if [[ "$PROXY_ENABLED" == "true" ]]; then                  
      if [[ "$PROXY_TYPE" == "nginx" ]]; then                
        fn-nginx-vhosts-nginx-init-cmd "reload"            
      fi                                                     
    fi

- Output of failing Dokku commands after running `dokku trace:on`

+ declare 'desc=destroy the properties for an app'
+ declare PLUGIN=git APP=updates.p
+ /var/lib/dokku/core-plugins/available/common/prop destroy git updates.p
+ source /var/lib/dokku/core-plugins/available/common/property-functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ source /var/lib/dokku/plugins/available/nginx-vhosts/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
++ source /var/lib/dokku/plugins/available/certs/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
++ source /var/lib/dokku/plugins/available/config/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
++ source /var/lib/dokku/plugins/available/nginx-vhosts/internal-functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/property-functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
+ trigger-nginx-vhosts-post-delete updates.p latest
+ declare 'desc=nginx-vhosts post-delete trigger'
+ declare trigger=post-delete
+ declare APP=updates.p
+ fn-plugin-property-destroy nginx updates.p
+ declare 'desc=destroy the properties for an app'
+ declare PLUGIN=nginx APP=updates.p
+ /var/lib/dokku/core-plugins/available/common/prop destroy nginx updates.p
+ restart_nginx updates.p latest
+ declare 'desc=restart nginx for given distros'
+ fn-nginx-vhosts-nginx-init-cmd reload
+ declare 'desc=start nginx for given distros'
+ declare CMD=reload
+ local NGINX_INIT_NAME
+ NGINX_INIT_NAME=nginx
+ fn-nginx-vhosts-uses-openresty
+ declare 'desc=returns whether openresty is in use or not'
+ [[ -x /usr/bin/openresty ]]
+ return 1
+ case "$DOKKU_DISTRO" in
+ [[ -x /usr/bin/sv ]]
+ sudo /etc/init.d/nginx reload
nginx.service is not active, cannot reload.
 !     exit status 1

**Comment by josegonzalez** [comment]
The way to disable nginx usage is to run `dokku proxy:disable $APP`. That said, this should work, albeit with a warning.

**Comment by fomojola** [comment]
Hi @josegonzalez , thanks! I did actually have the proxy disabled.

```
=====> updates.p proxy information
       Proxy enabled:                 false
       Proxy port map:                
       Proxy type:                    nginx
```

I think the only issue is that there isn't actually a check for the proxy status in the reload function call. I created https://github.com/dokku/dokku/pull/4988 to include both checks: one for proxy enabled/disabled and a second for proxy type matching nginx.

Of course, in the distant future where multiple proxies can be enabled for a single app (say, one for HTTP and an associated UDP proxy, like Traefik) it will get much more complicated.

**Comment by josegonzalez** [comment]
I feel like the best is to not have multiple proxies on one app (or even server, though its there for flexibility). If you used something like a traefik proxy plugin, it should handle _all_ the protocols your app needs, not just one-off.
