### ISSUE TITLE
502 Bad Gateway on fresh install - nginx & node

### ISSUE THREAD

**Issue by jem-computer** [dokku/dokku#499]
Hey - I set up a new Dokku instance using the Digital Ocean 1-click installer. My domain is added, SSH keys set up, and I can push apps.

I've got a very minimal app made with Node + Express that works fine on Heroku, but is giving me `502 Bad Gateway` after deploying with Dokku.
- there are no errors on deploying.
- the app isn't crashed when I run `docker ps`
- running `docker logs CONTAINER_ID` doesn't output anything
- running `dokku logs appname` doesn't output anything either
- `cat ../var/log/nginx/error.log` gives me the only discernable error messages - a bunch of entries like this:

```
2014/03/20 14:54:28 [error] 5128#0: *14 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 88.151.154.86, server: donethis.flatwhite.co, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:49154/", host: "donethis.flatwhite.co"
```

Any idea?

**Comment by fiatjaf** [comment]
I'm having the very same problem with 3 apps (but not a 4th in the same machine). They've worked for various months now, and since today they started to return this error. After a simple `ps:restart` they work again, but only for some minutes, then they start to fail again.

**Comment by josegonzalez** [comment]
@fiatjaf please open another issue instead of commenting on an 8 month old one. Thank you :)
