### ISSUE TITLE
How can I see deployments tracking (success/fail) (and datetime) ?

### ISSUE THREAD

**Issue by sostenesapollo** [dokku/dokku#5001]
Is there any interface (ui) or log for the  deployments(via github push) tracking ? 

![image](https://user-images.githubusercontent.com/35838667/149776301-40e7f178-b119-499d-8bd5-dd5fd46f82f1.png)

**Comment by josegonzalez** [comment]
The official web ui for Dokku is [Dokku Pro](https://pro.dokku.com/). Currently, there is no list of older deploys, though an upcoming release is scheduled to do just that (I need to find a way to log deploys triggered via the ssh endpoint, as currently only http(s) commands are logged).

**Comment by sostenesapollo** [comment]
yes, just trigger an action that stores the deployments infos
