### ISSUE TITLE
dokku User SSH Access Not Working

### ISSUE THREAD

**Issue by kylesuss** [dokku/dokku#502]
I booted up an Ubuntu machine running 12.04 and did the install. I have had no issues deploying apps using the standard procedure and dokku user as stated in the docs. I cannot SSH into the server using the dokku user for some reason though. I just get this message:

```
Connection to yoursite.com closed.
```

I can SSH using the ubuntu user, but I have to run all commands as sudo, which I know is not the right way to do things. What did I miss?

Thanks!

**Comment by ZeCarlosCoutinho** [comment]
Does this still stand today?

When I run
```
ssh dokku@host [command]
```
the `command` can be, for example, `ls`. It does not assume that I'm running a `dokku` command.

**Comment by darkpixel** [comment]
I just checked a recently installed box, and I am unable to run ```ssh dokku@myserver ls```.  I'm restricted/forced to use the dokku app.  i.e. ```ssh dokku@myserver apps:list```
