### ISSUE TITLE
Unable to install dokku on MacOS: 404 /etc/os-release: No such file or directory

### ISSUE THREAD

**Issue by nicofraisse** [dokku/dokku#5022]
## Description of problem
Unable to install dokku on MacOS 11.2.3

### Steps to Reproduce

1. Run in the terminal, as per dokku docs:
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.21.4/bootstrap.sh;
sudo DOKKU_TAG=v0.21.4 bash bootstrap.sh
```

#### Actual Results
```
--2022-02-05 12:17:58--  https://raw.githubusercontent.com/dokku/dokku/v0.21.4/bootstrap.sh;
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-05 12:17:58 ERROR 404: Not Found.

bootstrap.sh: line 266: /etc/os-release: No such file or directory
```

#### Expected Results
Dokku should install successfully

## Environment Information
MacOS 11.2.3

**Comment by josegonzalez** [comment]
Dokku does not install directly on MacOS. System requirements are outlined [here](https://dokku.com/docs/getting-started/installation/#system-requirements).

If you'd like to run this on your Mac, you'll need to run it inside of a docker container. See [this guide](https://dokku.com/docs/getting-started/install/docker/) for more details.
