### ISSUE TITLE
Support for raspbian bullseye

### ISSUE THREAD

**Issue by RyanGaudion** [dokku/dokku#5054]
## Description of problem

Installing dokku on a Raspberry Pi results in "E: Unable to locate package dokku". I've seen ARM is now supported for Dokku. Tried installing on Ubuntu 20.04 & Debian Bullseye. 

error on debian is:
```
deb https://packagecloud.io/dokku/dokku/debian/ bullseye main
E: Unable to locate package dokku
```

### Steps to Reproduce

1. Setup new Ubuntu 20.04 (64bit) or Debian Bullseye Pi (64bit)
2. Run run `wget https://raw.githubusercontent.com/dokku/dokku/v0.26.8/bootstrap.sh;`
3. Run `sudo DOKKU_TAG=v0.26.8 bash bootstrap.sh`

#### Actual Results
`E: Unable to locate package dokku`

#### Expected Results
Should install application

## Environment Information
Raspberry Pi 3b+

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?
 - Physical Raspberry Pi
 - OS = Raspberry Pi OS Lite (64-bit)

### Additional information
N/A

**Comment by RyanGaudion** [comment]
Could the issue be with me trying to use 64bit images for the Pi? If so, is there any chance 64bit Pi images will be supported?

**Comment by RyanGaudion** [comment]
Running on Bullseye Lite 32bit shows `Unsupported Linux distribution. For manual installation instructions, consult https://dokku.com/docs/getting-started/advanced-installation/`

Try a manual install from the steps above shows:
`E: Unable to locate package dokku` on line:
`sudo apt-get -qq -y install dokku`

**Comment by josegonzalez** [comment]
I've only tested it for Raspbian. No idea what happens on either of the others, and we don't yet have general 64-bit ARMv7 support (until the next minor).

**Comment by RyanGaudion** [comment]
@josegonzalez what version of Raspbian have you been able to get working?

**Comment by josegonzalez** [comment]
Hope this helps:

```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ uname -a
Linux pi1 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux
```

**Comment by RyanGaudion** [comment]
Thank you, I'll see if I can get that version. 

What would it take to get Raspbian Bullseye Lite 32 bit supported (from Raspberry Pi Imager)?

**Comment by josegonzalez** [comment]
Probably I need to update packaging for everything to add bullseye as a target. I can get that done.

**Comment by RyanGaudion** [comment]
Awesome, thank you. Anything I can do to help/test?

**Comment by RyanGaudion** [comment]
Will take a look at this tomorrow 👍

**Comment by josegonzalez** [comment]
I might grab some of these first since I'd like to make a release today to unblock a release of [Dokku Pro](https://pro.dokku.com/)

**Comment by josegonzalez** [comment]
I think the packages built for #4974 will work, but we'll need to test that before getting them auto-published.

**Comment by josegonzalez** [comment]
@RyanGaudion do you mind installing the following packages and seeing if the help/version output looks right on your raspbian bullseye install? https://packagecloud.io/app/dokku/dokku/search?dist=raspbian%2Fbullseye

**Comment by RyanGaudion** [comment]
- [x] docker-image-labeler_0.4.1_armhf.deb
- [x] netrc_0.5.1_armhf.deb
- [x] procfile-util_0.14.1_armhf.deb
- [ ] dokku-event-listener_0.12.0_armhf.deb (see below)

All work except Event Listener shows to both -v & -h:
```

{"level":"fatal","error":"Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.25/containers/json?filters=%7B%22label%22%3A%7B%22com.dokku.app-name%22%3Atrue%2C%22com.dokku.process-type%3Dweb%22%3Atrue%7D%7D&limit=0\": dial unix /var/run/docker.sock: connect: permission denied","time":1646223119,"message":"containers_init_failed"}
```
Trying as sudo returns nothing. This might be the expected output - just thought I'd check

**Comment by josegonzalez** [comment]
Yeah alright thats fine.

**Comment by RyanGaudion** [comment]
@josegonzalez - nice. Anything else I can do to help/test + estimated timeline on when this will be released?

**Comment by josegonzalez** [comment]
I have to get releases for the others + click the release button for this repo. This is actually the last issue I'm waiting on.

**Comment by RyanGaudion** [comment]
@josegonzalez of course - happy to do so. Any estimates on when these packages will be ready for test?

**Comment by josegonzalez** [comment]
Okay I created packages for the following:

- sigil
- plugn
- sshcommand
- dokku-update

Mind downloading them and ensuring they respond to the version flag? The `plugn` binary will need some env vars set, but as long as it launches, its fine.

**Comment by josegonzalez** [comment]
Also, [this link](https://github.com/dokku/dokku/suites/5501755071/artifacts/176065509) should have the build artifacts for the latest release. Can you download it and install the appropriate deb package of dokku on your host and see if it works?

**Comment by RyanGaudion** [comment]
@josegonzalez tested all packages. All work with the version flag. 
Dokku installed without issues.

Just testing Dokku - having some issues with SSH keys but I think that might be to do with my dev setup.

Will carry on testing tomorrow but all look good with those build artifacts

**Comment by josegonzalez** [comment]
Nice! Going to close this issue then. Feel free to follow up in chat if you have further troubles :)

**Comment by louwers** [comment]
When running the installation script, I see:

```
Unsupported Linux distribution. For manual installation instructions, consult https://dokku.com/docs/getting-started/advanced-installation/
```

Does that mean the installation script does not support Raspian?

**Comment by josegonzalez** [comment]
@louwers please file a ticket with your issue so I can take a look from there.
