### ISSUE TITLE
freeze while downloading heroku buildpack

### ISSUE THREAD

**Issue by scwall** [dokku/dokku#5059]
## Description of problem
Since this morning impossible to download the buildpack nodejs dokku freeze on the download
### How reproducible
I pushed my data to my dokku server
### Steps to Reproduce

1. push on server dokku

#### Actual Results
remote: -----> Cleaning up...        
remote: -----> Building horus from herokuish        
remote: -----> Adding BUILD_ENV to build environment...        
remote:        BUILD_ENV added successfully        
remote: -----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.        
remote:        Detected buildpacks: multi nodejs python        
remote: -----> Multipack app detected        
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git  

freeze since 40 minutes I restarted the vps but it does not change anything it still blocks

**Comment by scwall** [comment]
I don't know if there is a way to cache the buildpacks, otherwise I will use gitea to fork the buildpacks to keep them local
I have the impression to be limited on github I tested from another vps no problem, currently I do a lot of modifications on projects

**Comment by scwall** [comment]
After two hours, I have receveid this message 
remote: 
remote: -----> Build failed        
remote: 
remote:        We're sorry this build is failing! You can troubleshoot common issues here:        
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys        
remote: 
remote:        Some possible problems:        
remote: 
remote:        - Node version not specified in package.json        
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version        
remote: 
remote:        Love,        
remote:        Heroku        
remote: 
remote: 2022/03/04 22:18:42 exit status 56        
error: fail


But I never specified a version for nodejs

**Comment by josegonzalez** [comment]
This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [slack channels or github discussion board](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#monitored-locations). 

Issues pertaining to buildpacks will be closed and/or locked.
