### ISSUE TITLE
Dokku Enter and Dokku Run break when code that fails to build is pushed

### ISSUE THREAD

**Issue by HackedOS** [dokku/dokku#5065]
## Description of problem
`dokku enter` and `dokku run` break when broken code is pushed ie: code that fails to build
I have only tested with a python project
Dokku Version 0.27.0
### How reproducible
I reinstalled my linode 3 times with the same issue until i figured it out so VERY REPRODUCIBLE
### Steps to Reproduce

1. git push code that fails to build
2. try `dokku enter` and `dokku run` you end in a container with user root and random hostname
3. git push code that builds correctly
4. try `dokku enter` and `dokku run` you end up in the correct container with user herokuishuser and random hostname

**Comment by josegonzalez** [comment]
I think this is an artifact of how we reuse the image tag during the build process. Should be easy enough to filter all images by app tag that are labeled as "released" and use the latest one for run.

Enter should just enter a running container and should be fine though.

Do you have a sample app I can use to replicate this?

**Comment by HackedOS** [comment]
[hellodjango.zip](https://github.com/dokku/dokku/files/8222227/hellodjango.zip)
Just add remote and push should work just fine and delete line 124 to break the build

**Comment by josegonzalez** [comment]
Thanks I'll try this later today!

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
