### ISSUE TITLE
Can someone please clarify how the Scheduled Cron Tasks work?

### ISSUE THREAD

**Issue by railsfactory-umar** [dokku/dokku#5078]
Can someone please clarify how the Scheduled Cron Tasks work? I'm trying to run a rails rake task via the cron, but it doesn't run. The examples don't really show if you're supposed to use `dokku` in the command or how exactly that works. I also couldn't find any examples online.

My app.json

```
{
    "cron": [{
        "command": "rake my_task:import",
        "schedule": "@daily"
    }]
}
```

_Originally posted by @OpticNectar in https://github.com/dokku/dokku/issues/450#issuecomment-884207201_

**Comment by SM2DevLLC** [comment]
@railsfactory-umar I believe that should work, but you need to add `cron: sleep infinity` to your procfile. Also, make sure you scale the cron to 1.

**Comment by josegonzalez** [comment]
You don't need a `cron: sleep infinity` task. Thats for self-managed cron. The built-in stuff works exactly as documented - the command is run within the context of the app image, so no `dokku run` prefix or whatever is needed.

Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Closing as there hasn't been any followup in a while.

Note that the docs state the following:

> command: A command to be run within the built app image. Specified commands can also be Procfile entries.

I've clarified how the command in the example gets expanded into a dokku command. Hope that helps.
