### ISSUE TITLE
Build a docker dns server

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#5101]
### Description of feature

Lets build a dns server that responds with the container IPs based on labels. We'll call it `dokku-dns` or something.

We can specify a simple config file (actually this can just be hardcoded since the server is for dokku):

```json
{
	"socket": "unix:///var/run/docker.sock",
        "hostname": "com.dokku.app-name",
        "subdomain": "com.dokku.process-type",
        "tld": "local"
}
```

If a user requests A records for `node-js-app.local` from the dns server, it would respond with the IP addresses of all containers with the label `com.dokku.app-name=node-js-app`. You can optionally specify a subdomain `web.node-js-app.local` to get _only_ those for the `web` process type.

We should cache the lookups on boot and listen to the docker socket for any updates, handling docker socket restarts as well.

Once we package this up, we can then switch all the nginx templates to use a variable for the proxy upstream, which will then resolve for every single request (and be fast since its local lookups). This will allow us to avoid sending requests to the wrong IP addresses for a given app, fixing a long-standing issue with server reboots, docker restarts, and container crashes.

**Comment by josegonzalez** [comment]
Going to close this. I think a better plan would be for folks to switch to Caddy or Traefik instead (as well as the upcoming Haproxy plugin). All of those will listen to the Docker daemon for upstreams, whereas this will require a ton of work to do properly.

While I'd still like to do this, it's probably more in the realm of "someday" vs now. I'll resurrect this if I ever start working on the functionality.

**Comment by josegonzalez** [comment]
This could probably be used: https://github.com/kevinjqiu/coredns-dockerdiscovery

**Comment by hiepxanh** [comment]
yes, it very useful <3

**Comment by josegonzalez** [comment]
For anyone landing here, we are avoiding this by using one of the alternative proxy plugins - Caddy, Haproxy, OpenResty, and Traefik all support listening to the docker socket for live containers, and OpenResty should provide pretty good compatibility with the nginx plugin.

**Comment by josegonzalez** [comment]
I built the thing: [coredns-docker](https://github.com/dokku/coredns-docker). I'll probably be packaging this somehow for Dokku soon!
