### ISSUE TITLE
Support for NGINX Plus

### ISSUE THREAD

**Issue by haliliceylan** [dokku/dokku#5111]
### Description of feature

Dokku currently uses nginx in its architecture. Mainly for balancing http traffic and managing domain names and offering ssl certificates. While Nginx Plus provides these features, it can also enable the use of services other than http such as TCP and UDP Proxy. For example, using OpenVPN on port 443, this is possible with dokku, only the loadbalancer needs to be changed. Maybe instead of a very different service like HAPROXY, the NGİNX plux project, which is similar to Nginx, can be used.

**Comment by haliliceylan** [comment]
Oh sorry, I think Ngnix Plus is a paid service. So if its like that please close the issue.

**Comment by josegonzalez** [comment]
You're welcome to use nginx on your own, but I don't have a license so I can't test.
