### ISSUE TITLE
Do not default to the herokuish builder and fix report on armhf/arm64 installations

### ISSUE THREAD

**Issue by daitangio** [dokku/dokku#5113]
### Description of problem
I tried to deploy a python getting started demo but it fails:
```
git push dokku main:master
[...]
remote: ed23aa403f7f: Pull complete
remote: Digest: sha256:ba97d7949a8fa35fa114422b0bfd749cffe848c77cdc1934e6b3687a0f0fb4f5
remote: Status: Downloaded newer image for gliderlabs/herokuish:latest-20
remote: WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
remote:  !     Failure extracting app code
remote: 2022/04/21 19:04:46 exit status 1
```

I am using Dokku version 0.27.1 on a Oracle Cloud Infrastructure Altera host.
What is the correct way to specify ARM platform?
I was unable to find a solution on the issue page, but it seems this problem was already fixed, see issue
https://github.com/dokku/dokku/issues/4974 but I do not understand how to fix it :(
Thank you!

### dokku report $APP_NAME

# dokku report python-getting-started
-----> uname: Linux altera2x12 5.11.0-1028-oracle #31~20.04.1-Ubuntu SMP Wed Jan 26 14:20:52 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:          11948         378        4247           5        7322       11364
       Swap:          2047           0        2047
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.14
        API version:       1.41
        Go version:        go1.16.15
        Git commit:        a224086
        Built:             Thu Mar 24 01:47:10 2022
        OS/Arch:           linux/arm64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.14
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.16.15
         Git commit:       87a90dc
         Built:            Thu Mar 24 01:45:30 2022
         OS/Arch:          linux/arm64
         Experimental:     false
        containerd:
         Version:          1.5.11
         GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
        runc:
         Version:          1.0.3
         GitCommit:        v1.0.3-0-gf46b6ba
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.8.1-docker)

       Server:
        Containers: 2
         Running: 1
         Paused: 0
         Stopped: 1
        Images: 8
        Server Version: 20.10.14
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: false
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
        runc version: v1.0.3-0-gf46b6ba
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.11.0-1028-oracle
        Operating System: Ubuntu 20.04.4 LTS
        OSType: linux
        Architecture: aarch64
        CPUs: 2
        Total Memory: 11.67GiB
        Name: altera2x12
        ID: WBGM:5MJE:5QJ5:KUXC:PS3B:V2EI:RFG7:GFQC:NCDA:E3Z6:YLNT:T7CW
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.8.1build+dce1c9e
-----> herokuish version:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error

### Additional information

none

### Output of failing deploy after running: dokku trace:off

```shell
not provided
```

### Output of failing deploy after running: dokku trace:on

```shell
not provided
```

**Comment by josegonzalez** [comment]
There are two bugs here:

- `herokuish` isn't supported on arm64 (and won't be) but it's the default builder [here](https://github.com/dokku/dokku/blob/64e5cfd43c9fe334c7eff93b14e0a1e549a1f99c/plugins/git/functions#L61). We should instead bail if nothing was detected.
- `pack` is now supported on arm, but we only turn it on in [experimental mode](https://github.com/dokku/dokku/blob/master/plugins/builder-pack/builder-detect#L16). We should remove this check and default to it being on.
  - Even if its on, this may fail if the builder in use doesn't support arm, but thats a separate concern.
- The report output fails if on arm because it tries to run the herokuish image. It shouldnt

I'll fix both of those. You'll need to either switch to pack as a builder - via `builder:set` - or use a Dockerfile to build your app.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by c4lliope** [comment]
You can also run `dokku builder:set --global selected pack`, alongside:

```bash
sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
sudo apt-get update
sudo apt-get install pack-cli
```
