### ISSUE TITLE
Build argument is not available during dockerfile deployment

### ISSUE THREAD

**Issue by railsfactory-umar** [dokku/dokku#5121]
Description of problem:

Am trying to get a build argument be available during a image building using a dockerfile. Even after i set the build argument using docker-options in the server, get the values in dockerfile as argument but it is not available there. It causes problems to set variables at the start of image building.

Steps to Reproduce

1. set the variables in the server using the below command

> dokku docker-options:add foo newrelic_key=foo
> In the Dockerfile, add the following line

ARG newrelic_key
ENV license_key=newrelic_key

Actual Results:

license_key variable didnt get the value of foo in this case.

Expected Results: 

license_key should get the value of foo from newrelic_key argument like how the normal docker build arguments work.

**Comment by josegonzalez** [comment]
`docker-options` should include the flag, app, and the phase it is running against. Your example is missing the phase.

That said, you also need the flag, and it doesn't look like you did. You'll need to prefix the `newrelic_key=foo` with `--build-arg` probably.

**Comment by railsfactory-umar** [comment]
Hey @josegonzalez ,

Forgot to add it here since I worked on this a couple of days before. I have added it to the build phase with right argument tag, basically followed whatever mentioned in this document https://dokku.com/docs/deployment/builders/dockerfiles/

**Comment by josegonzalez** [comment]
Closing as there hasn't been any follow-up in two weeks. Please comment with further information if you have any.
