### ISSUE TITLE
Cron Task run once 

### ISSUE THREAD

**Issue by m7mdcc** [dokku/dokku#5136]
### Description of problem

Cron job task run once only 

### Steps to reproduce

I create app.json 

{
    "cron": [
      {
        "command": "php artisan schedule:run",
        "schedule": "*/5 * * * *"
      }

    ]
  }

then check 
dokku cron:report
=====> proxygrabberapi cron information
       Cron task count: 1

### dokku report $APP_NAME

dokku report proxygrabberapi
-----> uname: Linux ChunkyLabs 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:             976         247         170          17         558         562
       Swap:           3199         201        2998
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.14
        API version:       1.41
        Go version:        go1.16.15
        Git commit:        a224086
        Built:             Thu Mar 24 01:48:21 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.14
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.16.15
         Git commit:       87a90dc
         Built:            Thu Mar 24 01:46:14 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.5.11
         GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
        runc:
         Version:          1.0.3
         GitCommit:        v1.0.3-0-gf46b6ba
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
         compose: Docker Compose (Docker Inc., v2.3.3)
         scan: Docker Scan (Docker Inc., v0.17.0)

       Server:
        Containers: 2
         Running: 2
         Paused: 0
         Stopped: 0
        Images: 21
        Server Version: 20.10.14
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
        runc version: v1.0.3-0-gf46b6ba
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
         cgroupns
        Kernel Version: 5.10.0-13-amd64
        Operating System: Debian GNU/Linux 11 (bullseye)
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 976.4MiB
        Name: ChunkyLabs
        ID: IA6C:P5MM:M77L:FX3T:KL3N:5DAM:RTBS:EO7T:2DIN:WJMF:NY5K:D63H
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.30.2
-----> sigil version: 0.8.1build+dce1c9e
-----> herokuish version:
       herokuish: 0.5.34
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v236
         heroku-buildpack-nodejs    v189
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v205
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v36
         heroku-buildpack-scala     v91
         heroku-buildpack-play      v26
         heroku-buildpack-php       v205
         heroku-buildpack-go        v160
         heroku-buildpack-nginx     v16
         buildpack-null             v3
-----> dokku version: dokku version 0.27.1
-----> plugn version: plugn: 0.8.2build+1b2e2b4
-----> dokku plugins:
         00_dokku-standard    0.27.1 enabled    dokku core standard plugin
         20_events            0.27.1 enabled    dokku core events logging plugin
         app-json             0.27.1 enabled    dokku core app-json plugin
         apps                 0.27.1 enabled    dokku core apps plugin
         builder              0.27.1 enabled    dokku core builder plugin
         builder-dockerfile   0.27.1 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.27.1 enabled    dokku core builder-herokuish plugin
         builder-null         0.27.1 enabled    dokku core builder-null plugin
         builder-pack         0.27.1 enabled    dokku core builder-pack plugin
         buildpacks           0.27.1 enabled    dokku core buildpacks plugin
         certs                0.27.1 enabled    dokku core certificate management plugin
         checks               0.27.1 enabled    dokku core checks plugin
         common               0.27.1 enabled    dokku core common plugin
         config               0.27.1 enabled    dokku core config plugin
         cron                 0.27.1 enabled    dokku core cron plugin
         docker-options       0.27.1 enabled    dokku core docker-options plugin
         domains              0.27.1 enabled    dokku core domains plugin
         enter                0.27.1 enabled    dokku core enter plugin
         git                  0.27.1 enabled    dokku core git plugin
         letsencrypt          0.13.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.27.1 enabled    dokku core logs plugin
         mysql                1.19.4 enabled    dokku mysql service plugin
         network              0.27.1 enabled    dokku core network plugin
         nginx-vhosts         0.27.1 enabled    dokku core nginx-vhosts plugin
         plugin               0.27.1 enabled    dokku core plugin plugin
         proxy                0.27.1 enabled    dokku core proxy plugin
         ps                   0.27.1 enabled    dokku core ps plugin
         registry             0.27.1 enabled    dokku core registry plugin
         repo                 0.27.1 enabled    dokku core repo plugin
         resource             0.27.1 enabled    dokku core resource plugin
         run                  0.27.1 enabled    dokku core run plugin
         scheduler            0.25.6 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.27.1 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.27.1 enabled    dokku core scheduler-null plugin
         shell                0.27.1 enabled    dokku core shell plugin
         ssh-keys             0.27.1 enabled    dokku core ssh-keys plugin
         storage              0.27.1 enabled    dokku core storage plugin
         trace                0.27.1 enabled    dokku core trace plugin
=====> proxygrabberapi app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> proxygrabberapi app information
       App created at:                1651014681
       App deploy source:             proxygrabberapi
       App deploy source metadata:    proxygrabberapi
       App dir:                       /home/dokku/proxygrabberapi
       App locked:                    false
=====> proxygrabberapi builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> proxygrabberapi builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> proxygrabberapi builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> proxygrabberapi buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> proxygrabberapi ssl information
       Ssl dir:                       /home/dokku/proxygrabberapi/tls
       Ssl enabled:                   false
       Ssl hostnames:
       Ssl expires at:
       Ssl issuer:
       Ssl starts at:
       Ssl subject:
       Ssl verified:
=====> proxygrabberapi checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> proxygrabberapi cron information
       Cron task count:               1
=====> proxygrabberapi docker options information
       Docker options build:          --link dokku.mysql.proxygrabber_db:dokku-mysql-proxygrabber-db
       Docker options deploy:         --link dokku.mysql.proxygrabber_db:dokku-mysql-proxygrabber-db --restart=on-failure:10
       Docker options run:            --link dokku.mysql.proxygrabber_db:dokku-mysql-proxygrabber-db
=====> proxygrabberapi domains information
       Domains app enabled:           true
       Domains app vhosts:            proxygrabberapi.mylabs.me
       Domains global enabled:        true
       Domains global vhosts:         mylabs.me
=====> proxygrabberapi git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       ec74564
       Git last updated at:           1651012428
=====> proxygrabberapi logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> proxygrabberapi network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.5:5000
=====> proxygrabberapi nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/proxygrabberapi-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/proxygrabberapi-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1651014978
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> proxygrabberapi proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000
       Proxy type:                    nginx
=====> proxygrabberapi ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 3d8464e0c58)
=====> proxygrabberapi registry information
       Registry computed image repo:      dokku/proxygrabberapi
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> proxygrabberapi resource information
=====> proxygrabberapi scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> proxygrabberapi scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local parallel schedule count:
=====> proxygrabberapi storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

### Additional information

Application name : 

proxygrabberapi
The type of application being deployed (node, php, python, ruby, etc.)
PHP

If using buildpacks, which custom buildpacks are in use

https://github.com/heroku/heroku-buildpack-php

If using a Dockerfile, the contents of that file
NONE

If it exists, the contents of your Procfile.

web: vendor/bin/heroku-php-apache2 public/

### Output of failing commands after running: dokku trace:off

```shell
NONE
```

### Output of failing commands after running: dokku trace:on

```shell
NONE
```

**Comment by josegonzalez** [comment]
The task count there is how many cron tasks you have in your app.json, not how many times its been run. Are there any issues you're encountering?

**Comment by m7mdcc** [comment]
Oh , yeah i notice that , could i get how many time its been run ?

**Comment by josegonzalez** [comment]
No, we don't keep that (not sure how we'd even store it, a sql database somewhere?). Cron.d (the thing we use under the hood for cron with docker-local) doesn't expose this either afaik.

If you want metrics on your app, you might want to ship those somewhere within the bootstrap of the command you are running. Maybe if you're using something like datadog, you can emit a metric on each run? You could also maybe store a count in an attached [redis service](https://github.com/dokku/dokku-redis) (using a [counter](https://redis.io/commands/incr/)) and then read the metric out of that?

I don't think it makes sense for us to track counts directly - there wouldn't be a unified way of doing so across multiple schedulers anyhow - so I'm going to close this for now. I hope the workarounds I pointed out above help though :)
