### ISSUE TITLE
dokku apps:lifespan app-name 1month|1day|30m

### ISSUE THREAD

**Issue by chrisjsimpson** [dokku/dokku#5146]
### Description of feature

We use dokku extensively to test pr previews (and are aware of the dokku action to destroy apps on GitHub events)

This is a separate proposal to think about if adding 

```
dokku apps:lifespan app-name 1month|1day|30m
```

Is a generic / general enough feature to be considered useful to enough users 

Where , upon expiration of the lifespan, the app is automatically destroyed.

**Comment by josegonzalez** [comment]
This might be neat but... would require a daemon to handle. I'm loathe to require too many daemons in Dokku, as it's stuff that can happen magically out of band...

**Comment by josegonzalez** [comment]
Note: PRs should delete review apps on merge :)
