### ISSUE TITLE
Precompiling assets failed.  exit status 1

### ISSUE THREAD

**Issue by dcalixto** [dokku/dokku#5164]
### Description of problem

After setup the app and the database, i push the repo to dokku but on the end of deployment show this error

```

Precompiling assets failed.
       !
remote: 2022/05/06 20:04:53 exit status 1
```

someone can clarify this Precompiling assets failed?

with inspect command 

dokku ps:inspect nboats
```
"docker container inspect" requires at least 1 argument.
See 'docker container inspect --help'.

Usage:  docker container inspect [OPTIONS] CONTAINER [CONTAINER...]

Display detailed information on one or more containers
Traceback (most recent call last):
  File "/tmp/dokku-26386-trigger-scheduler-docker-local-scheduler-inspect.OpORtx", line 5, in <module>
    data = json.load(sys.stdin)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/05/06 20:06:14 exit status 1
 !     exit status 1
```

### Steps to reproduce

just push the repo to dokku using rails 6

### dokku report $APP_NAME

nboats

**Comment by josegonzalez** [comment]
There is a bunch of extra information we ask for in the issue template (the report output, the full logs with and without trace mode). These are important because they add needed context for debugging.

As an example, in this particular case, I don't know if it failed during a buildpack or Dockerfile deploy. Please include all the information asked for in the issue template.

**Comment by dcalixto** [comment]
@josegonzalez ahh sorry, because im in a hurry! but i did solve it already, i precomplied the assets! now is ok. seems that was the issue!
