### ISSUE TITLE
Would you be interested in a new homepage design?

### ISSUE THREAD

**Issue by yasoob** [dokku/dokku#5175]
### Description of feature

Hi! This is more so a feature offer than a feature request. I believe that Dokku is much more powerful and has a lot more to offer than the current homepage makes one believe. I might potentially be interested in redesigning the homepage and improving it a bit aesthetically. My question is, would you be interested in a new homepage design if I design and develop one?

Have a wonderful day :)

**Comment by yasoob** [comment]
Maybe something along the lines of the image below. I am envisioning some nice animations and interactions on the page 😄 

A few things that I feel like are missing from this mockup are:

1. Companies using Dokku. Need to give it some more social proof by showcasing other companies using Dokku
2. Feedback from people who have used it? I was thinking of grabbing some tweets and using those but I feel like if we are already showcasing so many people who are financially supporting the project, do we really need tweets? But one part of me likes some enthusiastic tweets on the homepage. It shows how much people are actually liking it (hopefully :p)

Thoughts?

<img width="1759" alt="dokku desktop" src="https://user-images.githubusercontent.com/3696393/168483015-c5233d03-9d59-43e4-8528-1a6ef8835ac8.png">

**Comment by josegonzalez** [comment]
This is great! I've been meaning to redo the homepage but haven't had much time for that recently.

A couple thoughts:

- The docs site is built with bootstrap, can you use whatever the latest version of that is?
- I'd like to align the design somewhat with the design on the pro site, if possible: https://pro.dokku.com/
  - Additionally, would be good to keep the existing blue color we have as the main color (if at all possible). Or at least have a color palette so I can update things elsewhere.
- Would be great to integrate some of the feedback from here: https://twitter.com/dokku/status/1507860688139694085
- I think we can probably have just the `curl | bash` install on the homepage, and then link off to individual docs for specific OS's. Thoughts on that?
- In conjunction with the above, would it maybe be possible to have some sort of example of the usage? Maybe an embedded asciinema.org for like "create an app, deploy an app image, scale it"? Lower-tech would be just the text of it of course.
- I'd like to deprioritize "smallest" copy, and better prioritize "self-hosted" if possible.
- Our chat links should be maybe... a list of links or a button-group for discord/irc/slack.
- Would be great to raise the profile of Dokku Pro. Folks don't know what it is and I'm sure at least some companies that would use Dokku would not use it because they don't have something like it.
- The links to "who sponsors this" are provided by OpenCollective. Not sure how easy it would be to style that integration, but wanna keep that in mind.

**Comment by yasoob** [comment]
You can find my responses inline below

> The docs site is built with bootstrap, can you use whatever the latest version of that is?

I will explore that. I worked with Bootstrap a long time ago but don't think it should be that hard to pick it back up again. I was initially thinking of making it in Webflow but realized that you might not be a big fan of that.

> I'd like to align the design somewhat with the design on the pro site, if possible: https://pro.dokku.com/

I looked through the pro site before designing the homepage and it seemed like there was no common theme hence I decided to ditch the idea of making it similar to pro homepage. Also, I feel like the pro homepage looks very _templatey_ (if that is even a word) so that is another reason I tried to avoid basing my design on that.

> Additionally, would be good to keep the existing blue color we have as the main color (if at all possible). Or at least have a color palette so I can update things elsewhere.

I just changed the color of the hero section to the blue color you have in the current navbar. I don't remember why I initially decided against using it. I guess it was probably because of the low contrast between the white text and the blue background. But on second thought blue color also looks fine as you have already been using that on the homepage.

> Would be great to integrate some of the feedback from here: https://twitter.com/dokku/status/1507860688139694085

I am not great at copywriting so maybe someone else can chime in with copy suggestions?

> I think we can probably have just the curl | bash install on the homepage, and then link off to individual docs for specific OS'. Thoughts on that?

I was initially of the same mind but didn't know how married you were to the idea of having all three install tabs on the homepage. I personally like the idea of having only one and then pointing people to the other install instructions just like you suggested.

> In conjunction with the above, would it maybe be possible to have some sort of example of the usage? Maybe an embedded asciinema.org for like "create an app, deploy an app image, scale it"? Lower-tech would be just the text of it of course.

We can definitely have that. Would you be willing to record one and share the link? Let's decided on this once we have a recording/s with us. If you can create three separate recordings, I can try to present them very nicely in tabs.

> I'd like to deprioritize "smallest" copy, and better prioritize "self-hosted" if possible.

I agree with the suggestion. I wasn't targetting copy changes in this iteration but still, this is good. I feel like we need to revamp the copy quite a lot. As I mentioned above, I am not the best person at copy so would love to get some help on this. I do know that there is certainly room for improvement in the current copy.

> Our chat links should be maybe... a list of links or a button-group for discord/irc/slack.

Oh I wasn't aware of discord+irc. Didn't see those on the homepage so thought there is only slack. Let me think about the best way to present those. How about putting "Support" in the navbar and then adding a drop-down to that which lists all these different services?

> Would be great to raise the profile of Dokku Pro. Folks don't know what it is and I'm sure at least some companies that would use Dokku would not use it because they don't have something like it.

I added an "Explore Pro" button right next to "View Documentation". Maybe we should have something like that at the end of the page as well but not sure what the most aesthetically pleasing way to do that would be. I will try to brainstorm a bit.

> The links to "who sponsors this" are provided by OpenCollective. Not sure how easy it would be to style that integration, but wanna keep that in mind.

Yeah, I took a look at that. We can probably use some Javascript to fetch them. I will have to look into CORS and whether we can fetch the OpenCollective API on the client-side.

Next iteration of homepage:
<img width="1759" alt="Dokku Homepage" src="https://user-images.githubusercontent.com/3696393/168486248-3077cd59-9c9b-4c87-99e4-e15117fb827e.png">

**Comment by Bilal-io** [comment]
@yasoob very nice design, I'd like to help with the implementation, feel free to ping me.

**Comment by josegonzalez** [comment]
Lets start with the above design for now. If you can get it into an html file ~somewhere, we can iterate from there (the file in the repository is home.html if you want to edit directly).

**Comment by yasoob** [comment]
Oof what a snazzy animation 😻 

![dokku globe animation floating](https://user-images.githubusercontent.com/3696393/168489810-a65a3ce0-4099-49a8-8650-f1fe24c3dd2e.svg)

**Comment by josegonzalez** [comment]
The animation is making me dizzy lol

**Comment by Bilal-io** [comment]
Maybe it'll work better if it's slowed down, try 2x slower.
Also, if this animated ends up included in the new design, make sure `prefers-reduced-motion` is checked and the animation is reduced or disabled all together.

**Comment by yasoob** [comment]
Just submitted the new website as a PR: https://github.com/dokku/dokku/pull/5184

**Comment by josegonzalez** [comment]
Closing as there is an MR open. Thanks for your work here!
