### ISSUE TITLE
How to uninstall a plugin?

### ISSUE THREAD

**Issue by arechsteiner** [dokku/dokku#519]
I've installed [dokku-bower-install](https://github.com/alexanderbeletsky/dokku-bower-install) as described on their GitHub readme. Now I get the nasty `! [remote rejected] master -> master (pre-receive hook declined)` error when pushing a node.js application. Not sure if it's the plugins fault, but before the install it worked, so there's that. So general question:

How to uninstall this (or any other) plugin properly?

The [Wiki Page](https://github.com/progrium/dokku/wiki/Plugins) only states how to create and install plugins, not how to remove them.

**Comment by juanpastas** [comment]
Thanks @AlJohri.

**Comment by josegonzalez** [comment]
@juanpastas please do not comment on old issues.
