### ISSUE TITLE
Dokku cron not removing containers intermittently

### ISSUE THREAD

**Issue by youjingwong** [dokku/dokku#5195]
### Description of problem

I've been using cron in `app.json`

```
{
"scripts": {
    "dokku": {
      "predeploy": "bundle exec rake assets:precompile",
      "postdeploy": "bundle exec rake db:migrate"
    }
  },
  "cron": [
    {
      "command": "bundle exec rake update_unleashed_stocks",
      "schedule": "*/10 * * * *"
    }
  ]
}
```

This works perfectly, calling the rake tasks. However, the docker containers are not removed occasionally. I would estimate one in perhaps 10 runs of the task would leave a trailing container.

I'm running a Ruby on Rails app.

### Steps to reproduce

I'm unable to reproduce this consistently.

### dokku report $APP_NAME

-----> uname: Linux tayarlo 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           7957        4187        2933          16         837        3451
       Swap:          8191         143        8048
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.16
        API version:       1.41
        Go version:        go1.17.10
        Git commit:        aa7e414
        Built:             Thu May 12 09:17:23 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.16
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.17.10
         Git commit:       f756502
         Built:            Thu May 12 09:15:28 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.4
         GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
        runc:
         Version:          1.1.1
         GitCommit:        v1.1.1-0-g52de29d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
         scan: Docker Scan (Docker Inc., v0.17.0)

       Server:
        Containers: 11
         Running: 11
         Paused: 0
         Stopped: 0
        Images: 47
        Server Version: 20.10.16
        Storage Driver: overlay2
         Backing Filesystem: extfs
WARNING: No swap limit support
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
        runc version: v1.1.1-0-g52de29d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-110-generic
        Operating System: Ubuntu 20.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 4
        Total Memory: 7.771GiB
        Name: tayarlo
        ID: KMQB:APSP:AIHX:2YFI:ILXP:CO7A:K7FT:NE3B:2QQY:U5K2:OUYJ:DG6U
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
       herokuish: 0.5.35
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v240
         heroku-buildpack-nodejs    v195
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v210
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v36
         heroku-buildpack-scala     v92
         heroku-buildpack-play      v26
         heroku-buildpack-php       v216
         heroku-buildpack-go        v161
         heroku-buildpack-nginx     v16
         buildpack-null             v3
-----> dokku version: dokku version 0.27.2
-----> plugn version: plugn: 0.9.1build+54616c0
-----> dokku plugins:
         00_dokku-standard    0.27.2 enabled    dokku core standard plugin
         20_events            0.27.2 enabled    dokku core events logging plugin
         app-json             0.27.2 enabled    dokku core app-json plugin
         apps                 0.27.2 enabled    dokku core apps plugin
         builder              0.27.2 enabled    dokku core builder plugin
         builder-dockerfile   0.27.2 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.27.2 enabled    dokku core builder-herokuish plugin
         builder-null         0.27.2 enabled    dokku core builder-null plugin
         builder-pack         0.27.2 enabled    dokku core builder-pack plugin
         buildpacks           0.27.2 enabled    dokku core buildpacks plugin
         certs                0.27.2 enabled    dokku core certificate management plugin
         checks               0.27.2 enabled    dokku core checks plugin
         common               0.27.2 enabled    dokku core common plugin
         config               0.27.2 enabled    dokku core config plugin
         cron                 0.27.2 enabled    dokku core cron plugin
         docker-options       0.27.2 enabled    dokku core docker-options plugin
         domains              0.27.2 enabled    dokku core domains plugin
         elasticsearch        1.20.3 enabled    dokku elasticsearch service plugin
         enter                0.27.2 enabled    dokku core enter plugin
         git                  0.27.2 enabled    dokku core git plugin
         letsencrypt          0.9.4 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.27.2 enabled    dokku core logs plugin
         network              0.27.2 enabled    dokku core network plugin
         nginx-vhosts         0.27.2 enabled    dokku core nginx-vhosts plugin
         plugin               0.27.2 enabled    dokku core plugin plugin
         proxy                0.27.2 enabled    dokku core proxy plugin
         ps                   0.27.2 enabled    dokku core ps plugin
         redis                1.12.6 enabled    dokku redis service plugin
         registry             0.27.2 enabled    dokku core registry plugin
         repo                 0.27.2 enabled    dokku core repo plugin
         resource             0.27.2 enabled    dokku core resource plugin
         run                  0.27.2 enabled    dokku core run plugin
         scheduler            0.27.2 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.27.2 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.27.2 enabled    dokku core scheduler-null plugin
         shell                0.27.2 enabled    dokku core shell plugin
         ssh-keys             0.27.2 enabled    dokku core ssh-keys plugin
         storage              0.27.2 enabled    dokku core storage plugin
         trace                0.27.2 enabled    dokku core trace plugin
=====> tayarlo app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> tayarlo app information
       App created at:                1653137063
       App deploy source:             tayarlo
       App deploy source metadata:    tayarlo
       App dir:                       /home/dokku/tayarlo
       App locked:                    false
=====> tayarlo builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> tayarlo builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> tayarlo builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> tayarlo buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> tayarlo ssl information
       Ssl dir:                       /home/dokku/tayarlo/tls
       Ssl enabled:                   true
       Ssl hostnames:                 admin.tayarlo.com api.tayarlo.com billing.tayarlo.com internal.tayarlo.com
       Ssl expires at:                Aug  2 09:24:53 2022 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 May  4 09:24:54 2022 GMT
       Ssl subject:                   subject=CN = internal.tayarlo.com
       Ssl verified:                  self signed
=====> tayarlo checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> tayarlo cron information
       Cron task count:               6
=====> tayarlo docker options information
       Docker options build:          --link dokku.elasticsearch.tayarlo-elasticsearch:dokku-elasticsearch-tayarlo-elasticsearch --link dokku.redis.tayarlo-redis:dokku-redis-tayarlo-redis
       Docker options deploy:         --link dokku.elasticsearch.tayarlo-elasticsearch:dokku-elasticsearch-tayarlo-elasticsearch --link dokku.redis.tayarlo-redis:dokku-redis-tayarlo-redis --restart=on-failure:10
       Docker options run:            --link dokku.elasticsearch.tayarlo-elasticsearch:dokku-elasticsearch-tayarlo-elasticsearch --link dokku.redis.tayarlo-redis:dokku-redis-tayarlo-redis
=====> tayarlo domains information
       Domains app enabled:           true
       Domains app vhosts:            internal.tayarlo.com admin.tayarlo.com api.tayarlo.com billing.tayarlo.com
       Domains global enabled:        false
       Domains global vhosts:
=====> tayarlo git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       18054a8
       Git last updated at:           1653137063
=====> tayarlo logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> tayarlo network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.10:5000
=====> tayarlo nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/tayarlo-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/tayarlo-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1653229711
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> tayarlo proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> tayarlo ps information
       Deployed:                      true
       Processes:                     2
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: ec40a5e3148)
       Status worker 1:               running (CID: 0300c61edbc)
=====> tayarlo registry information
       Registry computed image repo:      dokku/tayarlo
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> tayarlo resource information
=====> tayarlo scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> tayarlo scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local parallel schedule count:
=====> tayarlo storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

**Comment by josegonzalez** [comment]
What's the inspect output of one of those containers that stuck around? Is it still "running" or actually exited?

**Comment by youjingwong** [comment]
It is still "running"

```
[
    {
        "Id": "8de04070a9cc82e73d766dadd6dc03f8bc3f4fcdd37382797ee5966d55d80577",
        "Created": "2022-05-22T23:40:06.326327857Z",
        "Path": "bundle",
        "Args": [
            "exec",
            "rake",
            "update_unleashed_stocks"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 711255,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-05-22T23:40:07.084645418Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:ecd413c980c4f897b2bdf65b3be689fe49527b23b9fcb4e2205cbe613a28c0be",
        "ResolvConfPath": "/var/lib/docker/containers/8de04070a9cc82e73d766dadd6dc03f8bc3f4fcdd37382797ee5966d55d80577/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/8de04070a9cc82e73d766dadd6dc03f8bc3f4fcdd37382797ee5966d55d80577/hostname",
        "HostsPath": "/var/lib/docker/containers/8de04070a9cc82e73d766dadd6dc03f8bc3f4fcdd37382797ee5966d55d80577/hosts",
        "LogPath": "/var/lib/docker/containers/8de04070a9cc82e73d766dadd6dc03f8bc3f4fcdd37382797ee5966d55d80577/8de04070a9cc82e73d766dadd6dc03f8bc3f4fcdd37382797ee5966d55d80577-json.log",
        "Name": "/tayarlo.cron.10018",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "3",
                    "max-size": "10m"
                }
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": true,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": [
                "/dokku.elasticsearch.tayarlo-elasticsearch:/tayarlo.cron.10018/dokku-elasticsearch-tayarlo-elasticsearch",
                "/dokku.redis.tayarlo-redis:/tayarlo.cron.10018/dokku-redis-tayarlo-redis"
            ],
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/e2e86be76574753ed3432100de1f29a1d55c1581b24c38af7faaf1f6b298ec1c-init/diff:/var/lib/docker/overlay2/2d3e3b30d489834004503c4562932af5237350557b7e59ad09c41dcff17691e1/diff:/var/lib/docker/overlay2/8bbf40a659e4cd3b9aa10d8178198311d97cde22be0dcd4b1d51e9000a8bf244/diff:/var/lib/docker/overlay2/20041f8763747754ba2a586a70910449dcd44cdf090917b7a1484dc83fe8ff69/diff:/var/lib/docker/overlay2/bd05b3be807c37629442b789502eb7d05352f89e99ea66de573f404d0a996971/diff:/var/lib/docker/overlay2/b5004d48578b715a19c7c23d0edc2b9cb5fce02e2d0e5733e6c373b4658b438f/diff:/var/lib/docker/overlay2/3de6b4df20942c67bede38342aec9920457d3bca5f9613604fa5eb7db38c21a2/diff:/var/lib/docker/overlay2/a0170676ce494b6c2aae520d742535d8efa626c919697c276fb8b74b09e249be/diff:/var/lib/docker/overlay2/167549e800e9957f2e18e7d1f105c60c947fd7158e8fd73ede63e9513a5d29c1/diff:/var/lib/docker/overlay2/fe78cdc56ce8a1c85a9fc6b91b8452bf92b628f4758013a9fb9fcce0f4f63793/diff:/var/lib/docker/overlay2/d426d4a7e5402f70e7ec4c89529414825d498d35feb802fc341a8d170f550d74/diff:/var/lib/docker/overlay2/d72cc595f4f33c512a8266e8d720fd7e925cb056bfb8a743b12176d207347464/diff:/var/lib/docker/overlay2/efbc64b8359a41cde237ceb33c366ac8055da0f3e4070eb0de685e564bdfaf7c/diff:/var/lib/docker/overlay2/93ed495d28fb494d4a7840f8c25da3e387303777dfebb0ac3dc9a29556984382/diff:/var/lib/docker/overlay2/0f7b9aa63e23b54a43b4540a0ffeb0033d06800d165b4e03b3a43a1d23f9ad3d/diff:/var/lib/docker/overlay2/94d95199a7d1cb9ade83d04305b569ae5035a343d17a5423e7a9d0f7e130f443/diff:/var/lib/docker/overlay2/f7b344808a11a4a64736e7937c5d1b44cee08c04fd7a6ec77cce5bfdc731c22b/diff:/var/lib/docker/overlay2/c6c3a9e9018104a1d5aefe84477c80ba7d5c7b5b270ccb43d2824780bcb3f480/diff:/var/lib/docker/overlay2/3cc60aff4cc7b1c71c4c2db1e53cca119a1497630c10d56be6c9e11b590e39c3/diff:/var/lib/docker/overlay2/0f28546dccc9b0948817b662a14ee05943ab9e3473afb0003c2973840fba6704/diff:/var/lib/docker/overlay2/8250932cc5562d46dd09a969d685d592417917223b94ef8390c244783866d897/diff:/var/lib/docker/overlay2/2c7da94fae5752e2b214447b929e4cf517ff8c3309e24e27d3449a2504825692/diff:/var/lib/docker/overlay2/67c751f2b1538f424e1cc7f6bb32630dc291ee26f2fe73c12a40cfd80bc20cde/diff:/var/lib/docker/overlay2/82a085c479b740c4a193f5d41db95552b19684e6e1eed164e48b6b14d2a95fc5/diff:/var/lib/docker/overlay2/870e3e13dd82adace11255b27c9887f31208332298ebb079f95be8dbea22b3ea/diff:/var/lib/docker/overlay2/63213c05e139648e17724d23457c3c68d77c5866f8e9940bec34884da7b2be8b/diff:/var/lib/docker/overlay2/961192e0548bb15aee6d1256fe5125ad1cb3cdefec8a216452ca136897d49881/diff:/var/lib/docker/overlay2/44e861a25d77b7073139770f02f6bc9e5f0f5443390d4b1bed59bc1fd4df73fb/diff",
                "MergedDir": "/var/lib/docker/overlay2/e2e86be76574753ed3432100de1f29a1d55c1581b24c38af7faaf1f6b298ec1c/merged",
                "UpperDir": "/var/lib/docker/overlay2/e2e86be76574753ed3432100de1f29a1d55c1581b24c38af7faaf1f6b298ec1c/diff",
                "WorkDir": "/var/lib/docker/overlay2/e2e86be76574753ed3432100de1f29a1d55c1581b24c38af7faaf1f6b298ec1c/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "8de04070a9cc",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Cmd": [
                "bundle",
                "exec",
                "rake",
                "update_unleashed_stocks"
            ],
            "Image": "dokku/tayarlo:latest",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.dokku.app-name": "tayarlo",
                "com.dokku.container-type": "cron",
                "com.dokku.cron-id": "dGF5YXJsbz09PWJ1bmRsZSBleGVjIHJha2UgdXBkYXRlX3VubGVhc2hlZF9zdG9ja3M9PT0qLzEwICogKiAqICo=",
                "com.dokku.image-stage": "release",
                "com.dokku.predeploy-phase": "true",
                "dokku": "",
                "dokku_phase_script": "predeploy",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "dokku"
            }
        },
        "NetworkSettings": {
           // ...
        }
    }
]```

**Comment by youjingwong** [comment]
My rake tasks are pretty simple, it queues some tasks to be redis, which is later processed by my worker app. 

I wrapped the rake tasks with some `puts`, logging a message. The final `puts` message can be seen in `docker logs CONTAINER_ID`, which makes it unlikely to be a coding error.

**Comment by josegonzalez** [comment]
Is it possible that the tasks are stalling on a database connection or similar? And therefore just not exiting.

Note: We more or less just run the process in a docker container (nothing special about how we run it really) so if its not exiting, its not exiting.

**Comment by youjingwong** [comment]
My entire rake task is copied below. In case you're unfamiliar with Ruby on Rails, it basically queues a job in `Redis`, and that's all.

```
desc 'update unleashed stocks from api'
task update_unleashed_stocks: :environment do
  puts "starting update_unleashed_stocks"
  SyncUnleashedJob.perform_async
  puts "ending update_unleashed_stocks"
end

```

 It's unlikely to be stalling from a database connection, as when I run `docker logs CONTAINER_ID`, it shows 
 ```
starting update_unleashed_stocks
ending update_unleashed_stocks
 ```
So that doesn't seem where it's failing.

**Comment by josegonzalez** [comment]
Are you using any specific monitoring tools (newrelic/datadog) that might be monkeypatching ruby for you? Those sorts of things sometimes end up hanging rake in weird ways. Maybe worth checking to see if there are dependencies you should update?

**Comment by youjingwong** [comment]
Alright, I'll try that. Thanks!
