### ISSUE TITLE
Issue with app processes in app.json formation

### ISSUE THREAD

**Issue by AlejandroAkbal** [dokku/dokku#5205]
### Description of problem

Changing the name from a process in the formation section of the app.json file doesn't delete the old processes scale.

### Steps to reproduce

Create an app.json like this and deploy:

```json
{
    "formation": {
        "web": {
            "quantity": 1
        },
        "worker": {
            "quantity": 1
        },
    }
}
```

Then change the name of a process like this:

```json
{
    "formation": {
        "web": {
            "quantity": 1
        },
        "queue": {
            "quantity": 1
        },
    }
}
```

Now, both “worker” and “queue” processes are created and expected to be set in the Procfile, even though "worker" no longer exists.

### dokku report $APP_NAME

-----> uname: Linux hosting 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           3835        1828         514         211        1491        1500
       Swap:          4095         257        3838
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.16
        API version:       1.41
        Go version:        go1.17.10
        Git commit:        aa7e414
        Built:             Thu May 12 09:17:23 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.16
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.17.10
         Git commit:       f756502
         Built:            Thu May 12 09:15:28 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.4
         GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
        runc:
         Version:          1.1.1
         GitCommit:        v1.1.1-0-g52de29d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
         scan: Docker Scan (Docker Inc., v0.17.0)
       
       Server:
        Containers: 21
         Running: 21
         Paused: 0
         Stopped: 0
        Images: 184
        Server Version: 20.10.16
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
WARNING: No swap limit support
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
        runc version: v1.1.1-0-g52de29d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-113-generic
        Operating System: Ubuntu 20.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 3
        Total Memory: 3.746GiB
        Name: hosting
        ID: IXCS:RHAV:VRCO:BPHY:BZ6W:XBUW:OGHQ:I5WI:TYC4:BISH:5DWX:LIBE
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: 0.5.35
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v240
         heroku-buildpack-nodejs    v195
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v210
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v36
         heroku-buildpack-scala     v92
         heroku-buildpack-play      v26
         heroku-buildpack-php       v216
         heroku-buildpack-go        v161
         heroku-buildpack-nginx     v16
         buildpack-null             v3
-----> dokku version: dokku version 0.27.4
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.27.4 enabled    dokku core standard plugin
         20_events            0.27.4 enabled    dokku core events logging plugin
         app-json             0.27.4 enabled    dokku core app-json plugin
         apps                 0.27.4 enabled    dokku core apps plugin
         apt                  0.12.0 enabled    Inject deb packages into dokku based on files in project
         builder              0.27.4 enabled    dokku core builder plugin
         builder-dockerfile   0.27.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.27.4 enabled    dokku core builder-herokuish plugin
         builder-null         0.27.4 enabled    dokku core builder-null plugin
         builder-pack         0.27.4 enabled    dokku core builder-pack plugin
         buildpacks           0.27.4 enabled    dokku core buildpacks plugin
         certs                0.27.4 enabled    dokku core certificate management plugin
         checks               0.27.4 enabled    dokku core checks plugin
         common               0.27.4 enabled    dokku core common plugin
         config               0.27.4 enabled    dokku core config plugin
         cron                 0.27.4 enabled    dokku core cron plugin
         docker-options       0.27.4 enabled    dokku core docker-options plugin
         domains              0.27.4 enabled    dokku core domains plugin
         enter                0.27.4 enabled    dokku core enter plugin
         git                  0.27.4 enabled    dokku core git plugin
         logs                 0.27.4 enabled    dokku core logs plugin
         mariadb              1.18.2 enabled    dokku mariadb service plugin
         meilisearch          0.2.1 enabled    dokku meilisearch service plugin
         network              0.27.4 enabled    dokku core network plugin
         nginx-vhosts         0.27.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.27.4 enabled    dokku core plugin plugin
         postgres             1.19.3 enabled    dokku postgres service plugin
         proxy                0.27.4 enabled    dokku core proxy plugin
         ps                   0.27.4 enabled    dokku core ps plugin
         redis                1.19.2 enabled    dokku redis service plugin
         registry             0.27.4 enabled    dokku core registry plugin
         repo                 0.27.4 enabled    dokku core repo plugin
         resource             0.27.4 enabled    dokku core resource plugin
         run                  0.27.4 enabled    dokku core run plugin
         scheduler            0.27.4 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.27.4 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.27.4 enabled    dokku core scheduler-null plugin
         shell                0.27.4 enabled    dokku core shell plugin
         ssh-keys             0.27.4 enabled    dokku core ssh-keys plugin
         storage              0.27.4 enabled    dokku core storage plugin
         trace                0.27.4 enabled    dokku core trace plugin
=====> hentaiporn-app app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> hentaiporn-app app information
       App created at:                1653932268
       App deploy source:             hentaiporn-app
       App deploy source metadata:    hentaiporn-app
       App dir:                       /home/dokku/hentaiporn-app
       App locked:                    false
=====> hentaiporn-app builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> hentaiporn-app builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> hentaiporn-app builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> hentaiporn-app buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> hentaiporn-app ssl information
       Ssl dir:                       /home/dokku/hentaiporn-app/tls
       Ssl enabled:                   true                     
       Ssl hostnames:                 *.hentaiporn.app hentaiporn.app
       Ssl expires at:                May 13 09:39:00 2037 GMT 
       Ssl issuer:                    C = US, O = "CloudFlare, Inc.", OU = CloudFlare Origin SSL Certificate Authority, L = San Francisco, ST = California
       Ssl starts at:                 May 17 09:39:00 2022 GMT 
       Ssl subject:                   subject=O = "CloudFlare, Inc.", OU = CloudFlare Origin CA, CN = CloudFlare Origin Certificate
       Ssl verified:                  self signed              
=====> hentaiporn-app checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> hentaiporn-app cron information
       Cron task count:               1
=====> hentaiporn-app docker options information
       Docker options build:          --link dokku.meilisearch.hentai-porn-ms:dokku-meilisearch-hentai-porn-ms --link dokku.postgres.hentaiporn-db:dokku-postgres-hentaiporn-db --link dokku.redis.hentaiporn-redis:dokku-redis-hentaiporn-redis 
       Docker options deploy:         --link dokku.meilisearch.hentai-porn-ms:dokku-meilisearch-hentai-porn-ms --link dokku.postgres.hentaiporn-db:dokku-postgres-hentaiporn-db --link dokku.redis.hentaiporn-redis:dokku-redis-hentaiporn-redis --restart=on-failure:10 -v /var/lib/dokku/data/storage/hentaiporn-app:/app/storage/app/public 
       Docker options run:            --link dokku.meilisearch.hentai-porn-ms:dokku-meilisearch-hentai-porn-ms --link dokku.postgres.hentaiporn-db:dokku-postgres-hentaiporn-db --link dokku.redis.hentaiporn-redis:dokku-redis-hentaiporn-redis -v /var/lib/dokku/data/storage/hentaiporn-app:/app/storage/app/public 
=====> hentaiporn-app domains information
       Domains app enabled:           true                     
       Domains app vhosts:            hentaiporn.app           
       Domains global enabled:        true                     
       Domains global vhosts:         hosting                  
=====> hentaiporn-app git information
       Git deploy branch:             main                     
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                                                
       Git last updated at:           1653932268               
=====> hentaiporn-app logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> hentaiporn-app network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.23:5000
=====> hentaiporn-app nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/hentaiporn-app-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/hentaiporn-app-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1653978821               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> hentaiporn-app proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> hentaiporn-app ps information
       Deployed:                      true
       Processes:                     4
       Ps can scale:                  false
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status media queue 1:          running (CID: 96d5c22c093)
       Status queue 1:                running (CID: cde5e63c9a3)
       Status web 1:                  running (CID: 0a1827a84f7)
       Status worker 1:               running (CID: c8004148d33)
=====> hentaiporn-app registry information
       Registry computed image repo:      dokku/hentaiporn-app
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> hentaiporn-app resource information
=====> hentaiporn-app scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> hentaiporn-app scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local parallel schedule count:                          
=====> hentaiporn-app storage information
       Storage build mounts:                                   
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/hentaiporn-app:/app/storage/app/public 
       Storage run mounts:            -v /var/lib/dokku/data/storage/hentaiporn-app:/app/storage/app/public

**Comment by josegonzalez** [comment]
Thanks for reporting! This should be a relatively easy thing to fix :)

**Comment by josegonzalez** [comment]
The fix here is to ensure we delete any errant scale entries when there is a set of formations in app.json.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
