### ISSUE TITLE
Fix issues with https ports being accepted when there is no ssl cert available

### ISSUE THREAD

**Issue by pkail** [dokku/dokku#5207]
### Description of feature

I believe that this is possible because I've done it in the past.
There are multiple Stack Exchange posts, but they refer to deprecated pages in the documentation or plugins which are, themselves, deprecated.  
I have set port-forwarding, have two node applications starting on different ports and have both domains pointing to the IP address of the Dokku server.  There is obviously some essential step which is not documented.

**Comment by josegonzalez** [comment]
You can use the built-in domains plugin to add a domain to a specific app.

**Comment by pkail** [comment]
I cannot get this to work.  Maybe the docs could help us to steer round the bugs.

**Comment by josegonzalez** [comment]
What exactly did you try?

**Comment by pkail** [comment]
I have two nextjs applications which I am trying to run on the same $5 Digitalocean droplet.  I have increased swap-space to 2GB.

In both cases I set the domains using dokku domains:enable and set port-forwarding using dokku proxy:ports-add.  Letsencrypt worked (eventually).  The only difference was that, in the first, case, both apps had the same ports (http:80:5000 https:443:5000), whereas in the second case, they were set differently (5000/5001).  In the second case, I also set the port on the start script to be 5001.  Both apps work perfectly on 5000/5001 on my local machine.

In the first case, the second application pointed to the first one, regardless of port forwarding or domains.  In the second case, I was unable to get the second application to even deploy properly, apparently because of a lack of RAM (the cryptic message from dokku didn't explain this).  When it did eventually deploy, it destroyed the settings of first application so I had to start from scratch. 

At the moment, I have one working application and one broken one.  I can't even remove the second one, because dokku apps:destroy produces an error:

Job for nginx.service failed.
See "systemctl status nginx.service" and "journalctl -xe" for details.
 !     exit status 1

I then decided that, if even basic commands don't work properly, I would be better using docker.

If you have any insights I would be very grateful and will try out any suggestions: I have been struggling with this for a day and a half.

About a year ago I did get this to work, so I know that it's theoretically possible to do so.

**Comment by josegonzalez** [comment]
Do you have the entire log output of the deploy for the second, non working app?

You might be able to run "dokku nginx:validate-config" for the broken app, it should tell you what is wrong with nginx.

In regards to the "cryptic error message", I'm guessing you mean the "Killed" message. If so, that's from the OS and there isn't much we can do about detecting it (though I wonder if the exit code is something we can detect).

Lastly, we have slack/discord channels you can join to get live support in case the above doesn't get you going.

**Comment by pkail** [comment]
>>Do you have the entire log output of the deploy for the second, non working app?
dokku logs reports 'no such container', even though it's still listed when I run dokku apps:report.  And, as I mentioned, I can't delete with dokku apps:destroy.

>>In regards to the "cryptic error message", I'm guessing you mean the "Killed" message. If so, that's from the OS and there isn't much we can do about detecting it (though I wonder if the exit code is something we can detect).
There could at least be something in the docs which explains this.

>>You might be able to run "dokku nginx:validate-config" for the broken app, it should tell you what is wrong with nginx.
This returned no output at all, even before dokku failed to remove it.

**Comment by josegonzalez** [comment]
I don't mean running app logs, I mean the logs from when you git push your app.

I think we mention "killed" errors in our troubleshooting docs, though I have to check.

Interesting re: the validate command not working. What is the output of `sudo nginx -t`?

**Comment by pkail** [comment]
>>I mean the logs from when you git push your app.
I don't have a copy of the stdout from the git push, other than the error message above.

>>What is the output of sudo nginx -t
nginx: [emerg] cannot load certificate "/home/dokku/<domain name>/tls/server.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/dokku/<domain name>/tls/server.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by josegonzalez** [comment]
Sounds like a bug with your exposed ports for the app you redacted the name of in the output. Can you show me the output of `dokku proxy:report $APP`, where $APP is the name of your app?

**Comment by pkail** [comment]
Proxy enabled:                 true
       Proxy port map:                http:80:5001 https:443:5001
       Proxy type:                    nginx

**Comment by josegonzalez** [comment]
Got it. You have an extra mapping that shouldn't be there since your second app has no ssl cert.

Can you run:

```shell
dokku proxy:ports-remove $APP https:443:5001
```

I can change this ticket to fix that issue in the next release so folks adding https mappings without an ssl cert won't break nginx routing.

**Comment by pkail** [comment]
Thanks.  However, I get:
Setting config vars
       DOKKU_PROXY_PORT_MAP:  http:80:5001 https:443:5001
 !     Missing image for app
 !     exit status 1

**Comment by josegonzalez** [comment]
That's fine for now. You should be able to push your app now.

**Comment by pkail** [comment]
I've just pushed it again.  Unfortunately, when I try to use letsencrypt, I get:

root@dokku0214onubuntu2004-s-1vcpu-1gb-amd-sfo3-01:~# dokku letsencrypt:enable <domain name>
=====> Enabling letsencrypt for <domain name>
-----> Enabling ACME proxy for <domain name>...
Job for nginx.service failed.
See "systemctl status nginx.service" and "journalctl -xe" for details.
       Reloading nginx configuration (via systemctl): nginx.service failed!
root@dokku0214onubuntu2004-s-1vcpu-1gb-amd-sfo3-01:~#

**Comment by pkail** [comment]
Github seems to have messed up my comment.  I hope it's still clear what happened.  Thanks.

**Comment by pkail** [comment]
I'm not on either of those platforms.  Also, while I'm really grateful for your help with this, I have decided to use something else.

**Comment by josegonzalez** [comment]
Alright (for the record, we also have IRC in addition to the above, and all are linked).

I'll keep this open since I think there are two bugs:

- We allow https proxy ports to be utilized even if there is no ssl certificate available
- It seems that manipulating proxy ports tries an app rebuild (or tries to access the app image) and probably shouldn't (we should instead vendor whatever that file is out of the image post-build and use it later).

I think also it might make sense to show nginx process logs if there is a failure restarting/reloading nginx, as it doesn't make it super clear whats going on otherwise without running a command that needs sudo.

**Comment by josegonzalez** [comment]
Plan here:

- strip out all `https` ports from the mapping if there exists no ssl certificate
- verify that proxy-port setting via the proxy plugin does not fall into a path where we access files from the image. refactor that to remove such access

The former is definitely a patch-level change, while the latter is a minor-level change.

**Comment by josegonzalez** [comment]
The first thing is now implemented - https is now gated behind the file existing for nginx.

**Comment by josegonzalez** [comment]
Closing as there is now a pull request open for the latter item.
