### ISSUE TITLE
Support ARM CPU

### ISSUE THREAD

**Issue by arguskao** [dokku/dokku#5215]
### Description of feature

as above

**Comment by josegonzalez** [comment]
This is pretty vague. Dokku supports being installed on ARMv7 (armhf, or just plain arm) and ARMv8 (arm64) servers. Herokuish itself does not and will never support ARM, though Pack (with the correct builder) and Dockerfile builds (in addition to docker images) are supported.

What exactly isn't working for you?

**Comment by josegonzalez** [comment]
Closing as it has been two weeks and there hasn't been any response. Feel free to comment later and I'll re-open as necessary.
