### ISSUE TITLE
Two Apps Running, Both Subdomains Take Me to the Same App

### ISSUE THREAD

**Issue by jrneal1** [dokku/dokku#5226]
### Description of problem

Moving discussion #4542 as requested.  I've deployed two apps: dash-test and flask-dash.  No errors reported by either app during ```git push```.   The URLs are dash-test.dokku.me and flask-dash.dokku.me.  Both URLs take me to the dash-test app (which was the first one I deployed).  I have a VM running ubuntu server 22.04.  

### Steps to reproduce

deploy a dash app and a flask app and then try to access both by their respective URLs.

### dokku report $APP_NAME

Output of Dash app
[dash.txt](https://github.com/dokku/dokku/files/8984702/dash.txt)

Output of Flask app
[flask.txt](https://github.com/dokku/dokku/files/8984703/flask.txt)

**Comment by josegonzalez** [comment]
Can you post the output of

```
dokku nginx:show-config $APP
```

For both apps?

**Comment by jrneal1** [comment]
[dash_nginx.txt](https://github.com/dokku/dokku/files/8985344/dash_nginx.txt)
[flask_nginx.txt](https://github.com/dokku/dokku/files/8985345/flask_nginx.txt)

**Comment by josegonzalez** [comment]
Did you setup anything special for the dokku.me domain on your host server?

**Comment by josegonzalez** [comment]
What's weird is that your second flask app also has the dokku.me domain but that's not listed anywhere. If you could additionally run `dokku ps:rebuild $APP` for each app and post the output, that would help as well.

**Comment by jrneal1** [comment]
ok, I think I've sorted it out.  looks like I added the domain to each app via ```dokku domains:add flask-dash dokku.me```. That produced two server names in the nginx config - ```server _name flask-dash.dokku.me dokku.me;```.  Removing the ```dokku.me``` and leaving only the ```flask-dash.dokku.me``` seems to have resolved the conflict of everything routing to the first deployed app.
