### ISSUE TITLE
[fcos] Run on Fedora CoreOS >= 36

### ISSUE THREAD

**Issue by c4lliope** [dokku/dokku#5233]
### Description of feature

Hello, again; I am hoping I can run `dokku` and my usual deploy pipeline,
on arm64 machines (#5214), using Fedora CoreOS 36 and up.

Here are some commands used in recognizing FCOS:
```bash
[core@silicon-001 ~]$ . /etc/os-release && echo $ID
fedora
[core@silicon-001 ~]$ . /etc/os-release && echo $VERSION_ID
36
[core@silicon-001 ~]$ . /etc/os-release && echo $VARIANT_ID
coreos
```

A main issue here is, Fedora CoreOS (FCOS) uses `rpm-ostree` as a package manager.
In mainline Fedora, you use `sudo dnf install ...` for your dependencies.
In FCOS, you should use `sudo rpm-ostree install --apply-live --idempotent ....`.

I checked the `apt-get` commands inside your `Makefile`,
and they are all accessible on FCOS, as such:
```bash
sudo rpm-ostree install --apply-live --idempotent parallel jq dos2unix help2man man-db curl nginx
```
`docker` and `podman` are possible engine choices, and each comes pre-loaded.

Once I added dependencies, I had no success running: `make go-build` or similar commands.
I imagine a second `Makefile` is needed, using FCOS -specialized commands.

I could use some help building source on FCOS -
I can lend access on my FCOS arm64 board, should anyone send me an `~/.ssh/id_rsa.pub`.

**Comment by josegonzalez** [comment]
I'd rather not support multiple operating systems for installation, as that will require maintenance for an OS I won't normally be testing on.

Users of systems that we don't support outright should use the [docker-based installation process](https://dokku.com/docs/getting-started/install/docker/), which should work totally fine (and doesn't require any extra work when a new host os version is released).

I hope to remove everything but Ubuntu as an installation target in the future, and folks will be more or less expected to switch to the Docker-based installation process at that time if they aren't running Ubuntu.

**Comment by josegonzalez** [comment]
I've filed [this MR](https://github.com/dokku/dokku/pull/5240) to drop support for all non-supported operating systems. For better or worse, I just don't have the bandwidth to support anything but Ubuntu well in the long-term.
