### ISSUE TITLE
Custom error pages without customizing nginx.conf.sigil?

### ISSUE THREAD

**Issue by chrisjdixon** [dokku/dokku#5256]
In discussions with @josegonzalez elsewhere I asked about custom error pages and how I could specify which pages to use. I came to understand that [this is addressed in the docs](https://dokku.com/docs/configuration/nginx/#custom-error-pages) but it involves customizing the sigil which I know nothing about, and I am reluctant to risk bigger problems by customizing things I know nothing about for a nice to have feature which I hope users never see.

Ideally I'd like to specify settings in a simple file, like we can as described in the [customizing the nginx configuration docs](https://dokku.com/docs/configuration/nginx/#customizing-the-nginx-configuration). I was confused because I had configured Dokku to throw 503s if a file was found and this worked as intended with this .conf placed in "{{ .DOKKU_ROOT }}/{{ .APP }}/nginx.conf.d/*.conf":
```nginx
if (-f /home/projects/foo/503.html) {
    return 503;
}
```
But if we add `error_page 503 /home/projects/foo/error/503.html;` to this file it won't work, as that seems to be overwritten by the sigil file [here](https://github.com/dokku/dokku/blob/d5590b61af934c39411322da65b1c0abb8094f11/plugins/nginx-vhosts/templates/nginx.conf.sigil#L127).

@josegonzalez said, "we can also investigate moving the blocks downwards and seeing if moving the include after our error_page calls allows you to customize error_page later", and suggested making this a GH issue.

I'm new to all of this so I may have misinterpreted something, and I'm probably describing things poorly. Please feel free to correct.

**Comment by josegonzalez** [comment]
Once we move the include in the default template, I think you would be able to add the following to `/home/dokku/$APP/nginx.conf.d/503.conf`:

```
 error_page 503 /503.html;
 location /503-error.html {
   root //home/projects/foo/error/503.html;;
   internal;
 }
```

**Comment by chrisjdixon** [comment]
Awesome! Is there anything I can do to help from here? Or just wait for a release that incorporates this?

**Comment by josegonzalez** [comment]
You could do the moves yourself and make an MR. I think [this file](https://github.com/dokku/dokku/blob/d5590b61af934c39411322da65b1c0abb8094f11/plugins/nginx-vhosts/templates/nginx.conf.sigil) on lines 47 and 113 should have the `include` command moved below their respective error_page/location blocks.

**Comment by josegonzalez** [comment]
Closing as the pull request was merged. It'll come out in the next release.
