### ISSUE TITLE
Server multiple web process on single deployment?

### ISSUE THREAD

**Issue by l2radamanthys** [dokku/dokku#5271]
### Description of feature

It is possible to raise two or many web processes in a single instance 

I need to start a second process to received HTTP

```
Procfile
web: gunicorn backend.wsgi --log-file=- -t 600
notebook: python manage.py shell_plus --notebook
```

but Dokku only enable **web** to receive HTTPS traffic

**Comment by josegonzalez** [comment]
By default, Dokku only exposes the `web` process. Any domains associated to an app will be routed to that process. We don't have any plans to do anything more specific than that.

Users wishing to expose custom processes can use a custom `nginx.conf.sigil` to do so. From the docs:

> Finally, each process type has it's network listeners - a list of IP:PORT pairs for the respective app containers - exposed via an .DOKKU_APP_${PROCESS_TYPE}_LISTENERS variable - the PROCESS_TYPE will be upper-cased with hyphens transformed into underscores. Users can use the new variables to expose non-web processes via the nginx proxy.

In your case, there would be a `.DOKKU_APP_NOTEBOOK_LISTENERS` variable you could use in your custom template to reference the notebook containers.

More info on configuring it is available [here](https://dokku.com/docs/configuration/nginx/#customizing-the-nginx-configuration).

Hope that helps.
