### ISSUE TITLE
Add release script in app.json

### ISSUE THREAD

**Issue by jaulz** [dokku/dokku#5303]
### Description of feature

First of all, thanks for this great project! I started using it a couple of days ago and it makes a great impression. However, I find it confusing that there is an `app.json` and a `Procfile`. For example, the `release` script can only be defined in Procfile. Other scripts can be defined in `app.json` though. As far as I could see in the code (https://github.com/dokku/dokku/blob/3f28c24b57ea432e2a6b8daaadc64afa65a77ab1/plugins/app-json/functions.go#L124-L137) there is indeed no way to define the `release` script in `app.json`. Would you be open for a change to define the `release` script as well in `app.json` so we can define scripts are in one place?

**Comment by josegonzalez** [comment]
There are other scripts you can use instead of release that are available in app.json (they are just named differently). I would rather not add yet another thing there when we have triggers that run at the same time.

**Comment by jaulz** [comment]
@josegonzalez thanks for your feedback! Would you hence say that the `predeploy` in `app.json` is essentially the same?

**Comment by josegonzalez** [comment]
The `predeploy` phase happens at the same time but doesn't commit changes to the image.
