### ISSUE TITLE
allow to specify docker options with double quotes

### ISSUE THREAD

**Issue by javierav** [dokku/dokku#5305]
### Description of problem

Hi!

I'm using docker options in deploy phase to set custom label to the container. For that, I change the file `/home/dokku/my-app/DOCKER_OPTIONS_DEPLOY` and add the following line

```
--label com.datadoghq.ad.logs="[{\"source\": \"ruby\", \"service\": \"api\"}]"
```

 I'm not using the command `docker-options:add` to avoid issues with double quotes.

When container starts, if I inspect the container and search for labels, I get:

```
"Labels": {
    "com.datadoghq.ad.logs": "[{source: ruby, service: api}]"
}
```

As you can see, the string inside label is not a valid JSON: double quotes dissapear!

If I run another container manually, use the same option for set the label and then inspect the container, It works as expected:

```
docker run -ti --label com.datadoghq.ad.logs="[{\"source\": \"ruby\", \"service\": \"api\"}]" ubuntu /bin/bash

docker inspect <container_id>

"Labels": {
    "com.datadoghq.ad.logs": "[{\"source\": \"ruby\", \"service\": \"api\"}]"
}
```

So I think that dokku are bad parsing the `/home/dokku/my-app/DOCKER_OPTIONS_DEPLOY` file.

### Steps to reproduce

N/A

### dokku report $APP_NAME

N/A

**Comment by josegonzalez** [comment]
You need to escape the slashes too, so I think it ends up being something like:

```
--label com.datadoghq.ad.logs="[{\\\"source\\\": \\\"ruby\\\", \\\"service\\\": \\\"api\\\"}]"
```

**Comment by javierav** [comment]
My kudos @josegonzalez. It's works! 👏🏻
