### ISSUE TITLE
Add a run:logs command

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#5312]
### Description of feature

It should be possible to fetch logs from existing run containers via `run:logs`. Something like:

```shell
# get all run logs, similar to the `logs` command
dokku run:logs $APP

# get run logs for a specific cron id
dokku run:logs $APP $CRON_ID
```

**Comment by divtiply** [comment]
I can imagine output of `dokku run:logs $APP` (without a specific `$CRON_ID`) like
```
1234 | log message from job A
567  | log message from job B
```
where 1234 and 567 are CRON_IDs

**Comment by josegonzalez** [comment]
Closing as there is an open pull request.
