### ISSUE TITLE
[WebSite] Dokku logo disappeared from website and recent documentation

### ISSUE THREAD

**Issue by polettix** [dokku/dokku#5316]
## Description of problem

Opening the main page of the website, or many of the documentation pages, does not show the logo in the upper-left corner any more.

### Steps to Reproduce

Open the browser to one of:

- [https://dokku.com](https://dokku.com)

<img width="498" alt="homepage" src="https://user-images.githubusercontent.com/114540/185738992-ff1d84a9-6e65-4147-8982-1cda04035290.png">

- [https://dokku.com/docs~v0.27.9/getting-started/installation/](https://dokku.com/docs~v0.27.9/getting-started/installation/) (everything after has the problem, everything before seems to be fine)

<img width="537" alt="specific-docs" src="https://user-images.githubusercontent.com/114540/185738978-ae1308a7-680d-4094-9153-afda7a1e64da.png">

- [https://dokku.com/assets/dokku-logo.svg](https://dokku.com/assets/dokku-logo.svg)

<img width="570" alt="not-found" src="https://user-images.githubusercontent.com/114540/185739301-c2018f2f-7f11-4bdc-a6a2-fcc18bca106d.png">

**Comment by josegonzalez** [comment]
The docs have now been rebuilt to use Mkdocs and no longer have this issue. Thanks for reporting!
