### ISSUE TITLE
Add nginx rate limiting command

### ISSUE THREAD

**Issue by jonnyhoff** [dokku/dokku#5318]
### Description of feature

I've deployed an app & currently facing an issue where I need to set nginx rate limiting but need to configure the default sigil template to get it working. Would be nice to have a command to set this ie.

```
dokku nginx:set <app_name> rate_limit 10
```

10 requests per second

**Comment by josegonzalez** [comment]
I quickly looked at what rate limiting might require, and it seems [fairly complex to configure](https://www.nginx.com/blog/rate-limiting-nginx/). There are a bunch of knobs here, and it's not clear how we'd support this in a way that would be useful to everyone.

While it would be great from a user-perspective, I don't know that I've ever had anyone ask for this functionality before. I'm going to close this for now, but if other folks pile on a bunch of 👍🏽  and comment on how this might work for various rate limiting functionality, I'm willing to look into this again.

**Comment by josegonzalez** [comment]
Aside: I'd love to have something like https://github.com/lucaslorentz/caddy-docker-proxy but for nginx. This would allow us to use arbitrary labels to generate nginx config, and that would then more or less by default allow you to configure an nginx conf with rate limiting via dokku commands. It's how we integrate with Caddy and Traefik today.

**Comment by sjdonado** [comment]
@josegonzalez what do you think about this approach https://www.joseferben.com/posts/rate-limiting-with-dokku? I don't know much about nginx but happy to help with a PR

**Comment by josegonzalez** [comment]
@sjdonado that seems fine, if you're willing to come up with a PR, feel free to do so.
