### ISSUE TITLE
Document monorepo support

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#5323]
### Description of feature

There are a ton of knobs folks can turn to get monorepo support, and unfortunately they are documented on wildly different pages. We should at least have a special page that points off to all the monorepo knobs, which will help folks get started with such deploys.

**Comment by josegonzalez** [comment]
Closing this. The search works well for this now - just checked! - and we will have a dedicated tutorials section in the future that could cover something like this.

**Comment by TriStarGod** [comment]
@josegonzalez I'm trying add monorepo support to my project and trying to choose from one of the many monorepo options (rush, pnpm workspaces, etc). Dokku is central to my current config but I can't find any references to its usage with monorepo's. Could refer me to where to search for monorepo support? Is #4502 what you're referring to?

**Comment by josegonzalez** [comment]
If you go to [our docs](https://dokku.com/docs/getting-started/installation/) and use the search bar for the word `monorepo`, you'll find every reference to paths that can be changed in relation to monorepo deployments.
