### ISSUE TITLE
Unclear error for Caddy & Traefik when docker compose not installed

### ISSUE THREAD

**Issue by wheresalice** [dokku/dokku#5335]
### Description of problem

When I run `dokku traefik:start` or `dokku caddy:start` I get a Docker error message:

`unknown shorthand flag: 'f' in -f`

After re-reading the documentation, it became apparent that this is because I was lacking docker compose, although this is not explicitly stated as a requirement in the proxy documentation

The documentation for traefik and caddy (https://dokku.com/docs~v0.28.1/networking/proxies/traefik/ and https://dokku.com/docs~v0.28.1/networking/proxies/caddy/) could be clearer about this requirement

The error message given could also be clearer

This is quite an old installation of dokku that has been upgraded many times, so it is possible that newer installers or installation documentation covers this requirement

### Steps to reproduce

Docker version 20.10.17, build 100c701
Debian version 11.4
Dokku version 0.28.1
docker-compose-plugin: not installed

Run `dokku traefik:start`

### dokku report $APP_NAME

This is unrelated to a specific app

**Comment by josegonzalez** [comment]
Okay we'll need to add it to the dependency list. We can also add this check:

```shell
compose_installed="$(docker info -f '{{range .ClientInfo.Plugins}}{{if eq .Name "compose"}}true{{else}}false{{end}}{{end}}')"
```

It'll print `true` if the plugin is installed, and `false` otherwise.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
