### ISSUE TITLE
Support Nixpacks as a builder

### ISSUE THREAD

**Issue by IgnisDa** [dokku/dokku#5338]
### Description of feature

Nixpacks by Railway (https://nixpacks.com) is a buildpack alternative that will work wonderfully with Dokku. Since Dokku already supports running docker images, much of the plumbing should already be in place to be able to add Nixpacks as a builder. 

I can research into doing it if this feature request is approved.

**Comment by josegonzalez** [comment]
This was actually something I'd planned to do for the 0.28.x release but didn't get to it, but I am planning on adding a builder for 0.29.x.

**Comment by IgnisDa** [comment]
Cool once it lands, i can test it on my end.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
