### ISSUE TITLE
dokku certs:report Ssl verified: self signed on a purchased ssl certificate

### ISSUE THREAD

**Issue by gerardcarbo** [dokku/dokku#5339]
### Description of problem

We purchased a ssl certificate to Sectigo (not self singed) and installed via:

```
cat yourdomain_com.crt yourdomain_com.ca-bundle > server.crt
tar cvf cert-key.tar server.crt server.key
dokku certs:add **** < cert-key.tar
```
but when checking the report it informs that the ssl is self signed:

```
dokku certs:report
=====>  ssl information
       Ssl dir:                       /home/dokku//tls
       Ssl enabled:                   true                     
       Ssl hostnames:                 ******
       Ssl expires at:                Aug 21 23:59:59 2023 GMT 
       Ssl issuer:                    C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
       Ssl starts at:                 Jul 21 00:00:00 2022 GMT 
       Ssl subject:                   subject=CN = ****
       Ssl verified:                  **self signed** 
```

If you try to run the app with NODE_TLS_REJECT_UNAUTHORIZED='1' it fails with:

=====> Start of *** container output (web.1)
       Error: self signed certificate in certificate chain
           at TLSSocket.onConnectSecure (node:_tls_wrap:1535:34)
           at TLSSocket.emit (node:events:513:28)
           at TLSSocket.emit (node:domain:489:12)
           at TLSSocket._finishInit (node:_tls_wrap:949:8)
           at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:730:12) {
         code: 'SELF_SIGNED_CERT_IN_CHAIN'
       }

What could be wrong? 

### Steps to reproduce

cat yourdomain_com.crt yourdomain_com.ca-bundle > server.crt
tar cvf cert-key.tar server.crt server.key
dokku certs:add **** < cert-key.tar
dokku certs:report

### dokku report $APP_NAME

-----> uname: Linux DeltaLic0 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           1983         468         123          33        1391        1303
       Swap:          4095           4        4091
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.17
        API version:       1.41
        Go version:        go1.17.11
        Git commit:        100c701
        Built:             Mon Jun  6 23:02:57 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.17
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.17.11
         Git commit:       a89b842
         Built:            Mon Jun  6 23:01:03 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.7
         GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
        runc:
         Version:          1.1.3
         GitCommit:        v1.1.3-0-g6724737
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
WARNING: No swap limit support
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
         scan: Docker Scan (Docker Inc., v0.17.0)
       
       Server:
        Containers: 4
         Running: 4
         Paused: 0
         Stopped: 0
        Images: 55
        Server Version: 20.10.17
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
        runc version: v1.1.3-0-g6724737
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-124-generic
        Operating System: Ubuntu 20.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 1.937GiB
        Name: DeltaLic0
        ID: 2DXT:5SVH:OZOQ:6IMA:UTBJ:BR2I:CJWK:LD2H:LIVX:PVZA:MEN7:NGFL
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: 0.5.37
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v198
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v214
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v94
         heroku-buildpack-play      v26
         heroku-buildpack-php       v223
         heroku-buildpack-go        v166
         heroku-buildpack-nginx     v16
         buildpack-null             v3
-----> dokku version: dokku version 0.28.0
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.28.0 enabled    dokku core standard plugin
         20_events            0.28.0 enabled    dokku core events logging plugin
         app-json             0.28.0 enabled    dokku core app-json plugin
         apps                 0.28.0 enabled    dokku core apps plugin
         builder              0.28.0 enabled    dokku core builder plugin
         builder-dockerfile   0.28.0 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.28.0 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.27.0 enabled    dokku core builder-lambda plugin
         builder-null         0.28.0 enabled    dokku core builder-null plugin
         builder-pack         0.28.0 enabled    dokku core builder-pack plugin
         buildpacks           0.28.0 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.28.0 enabled    dokku core caddy-vhosts plugin
         certs                0.28.0 enabled    dokku core certificate management plugin
         checks               0.28.0 enabled    dokku core checks plugin
         common               0.28.0 enabled    dokku core common plugin
         config               0.28.0 enabled    dokku core config plugin
         cron                 0.28.0 enabled    dokku core cron plugin
         docker-options       0.28.0 enabled    dokku core docker-options plugin
         domains              0.28.0 enabled    dokku core domains plugin
         enter                0.28.0 enabled    dokku core enter plugin
         git                  0.28.0 enabled    dokku core git plugin
         letsencrypt          0.13.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.28.0 enabled    dokku core logs plugin
         network              0.28.0 enabled    dokku core network plugin
         nginx-vhosts         0.28.0 enabled    dokku core nginx-vhosts plugin
         plugin               0.28.0 enabled    dokku core plugin plugin
         postgres             1.19.3 enabled    dokku postgres service plugin
         proxy                0.28.0 enabled    dokku core proxy plugin
         ps                   0.28.0 enabled    dokku core ps plugin
         registry             0.28.0 enabled    dokku core registry plugin
         repo                 0.28.0 enabled    dokku core repo plugin
         resource             0.28.0 enabled    dokku core resource plugin
         run                  0.28.0 enabled    dokku core run plugin
         scheduler            0.28.0 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.28.0 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.28.0 enabled    dokku core scheduler-null plugin
         shell                0.28.0 enabled    dokku core shell plugin
         ssh-keys             0.28.0 enabled    dokku core ssh-keys plugin
         storage              0.28.0 enabled    dokku core storage plugin
         trace                0.28.0 enabled    dokku core trace plugin
         traefik-vhosts       0.28.0 enabled    dokku core traefik-vhosts plugin
=====> delta-lic-server app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> delta-lic-server app information
       App created at:                1660826967
       App deploy source:             delta-lic-server
       App deploy source metadata:    delta-lic-server
       App dir:                       /home/dokku/delta-lic-server
       App locked:                    false
=====> delta-lic-server builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     herokuish
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              herokuish
=====> delta-lic-server builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> delta-lic-server builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml               
       Builder lambda global lambdayml path: lambda.yml               
       Builder lambda lambdayml path:                          
=====> delta-lic-server builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> delta-lic-server buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> delta-lic-server ssl information
       Ssl dir:                       /home/dokku/delta-lic-server/tls
       Ssl enabled:                   true                     
       Ssl hostnames:                 register.deltainformatica.es www.register.deltainformatica.es
       Ssl expires at:                Aug 21 23:59:59 2023 GMT 
       Ssl issuer:                    C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
       Ssl starts at:                 Jul 21 00:00:00 2022 GMT 
       Ssl subject:                   subject=CN = register.deltainformatica.es
       Ssl verified:                  self signed              
=====> delta-lic-server checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> delta-lic-server cron information
       Cron task count:               0
=====> delta-lic-server docker options information
       Docker options build:          --link dokku.postgres.deltalic:dokku-postgres-deltalic 
       Docker options deploy:         --link dokku.postgres.deltalic:dokku-postgres-deltalic --restart=on-failure:10 
       Docker options run:            --link dokku.postgres.deltalic:dokku-postgres-deltalic 
=====> delta-lic-server domains information
       Domains app enabled:           true                     
       Domains app vhosts:            register.deltainformatica.es
       Domains global enabled:        true                     
       Domains global vhosts:         register.deltainformatica.es
=====> delta-lic-server git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       5583290                  
       Git last updated at:           1658852040               
=====> delta-lic-server logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> delta-lic-server network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.5:5000
=====> delta-lic-server nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/delta-lic-server-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/delta-lic-server-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1662030371               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> delta-lic-server proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> delta-lic-server ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: d1d894d8e7d)
=====> delta-lic-server registry information
       Registry computed image repo:      dokku/delta-lic-server
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> delta-lic-server resource information
=====> delta-lic-server scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> delta-lic-server scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local init process: true                     
       Scheduler docker local parallel schedule count:                          
=====> delta-lic-server storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:

**Comment by josegonzalez** [comment]
What is the output of these commands:

```
openssl verify -verbose -purpose sslserver "/home/dokku/delta-lic-server/server.crt"

openssl verify -verbose -purpose sslserver "/home/dokku/delta-lic-server/server.crt" 2>/dev/null | awk -F ':' '{ print $2 }' | tail -1 | xargs || true
```

**Comment by gerardcarbo** [comment]
Sorry for the delay, here they are (adding /tls to the path):

```
CN = register.deltainformatica.es
error 20 at 0 depth lookup: unable to get local issuer certificate
error /home/dokku/delta-lic-server/tls/server.crt: verification failed
```

And:

`verification failed`

On the other side I generated the CSR outside dokku, could it be the problem?

**Comment by josegonzalez** [comment]
I think maybe the server.crt file is malformed - as in it's not bundled properly - which is why the verification is failing. Where did you purchase the certicate/how did you create the crt file?

**Comment by gerardcarbo** [comment]
Hi Jose, I purchased the certificate to sectigostore.com but I generated the csr from another server (not the one running dokku) using:

openssl req -newkey rsa:2048 -keyout server.key -out server.csr

Then they sent me the .crt and the .ca-bundle that I merged and instaled using :

cat yourdomain_com.crt yourdomain_com.ca-bundle > server.crt
tar cvf cert-key.tar server.crt server.key
dokku certs:add **** < cert-key.tar

Can it be the problem generating the csr from another server?

**Comment by josegonzalez** [comment]
So nginx will terminate the ssl connection and then use http to proxy to your node app. You probably don't need to do anything special there in your node app re: redirects as nginx will handle that for you.

The cert seems fine from here: https://www.ssllabs.com/ssltest/analyze.html?d=register.deltainformatica.es

I would ask your certificate provider why that `openssl verify -verbose -purpose sslserver "/home/dokku/delta-lic-server/server.crt"` might fail, as maybe you created the server.crt incorrectly. Thats not really something I can solve as the command we're wrapping is openssl and its a pretty standard command afaik.

**Comment by gerardcarbo** [comment]
Ok, thank you very much for your support.

**Comment by josegonzalez** [comment]
Closing as I don't think there is much we can do here - the certificate seems fine externally and the openssl command we are running is also pretty straightforward, so I wonder if there is something weird about the way the certificate bundle is built (maybe missing an intermediary).

**Comment by gerardcarbo** [comment]
Hi Jose, I finally got a response from sectigo and found the missing intermediate CA certificate (SectigoRSADomainValidationSecureServerCA.crt) that I copied to /usr/local/share/ca-certificates/ and registered using 'update-ca-certificates'.
Now the command 'openssl verify -verbose -purpose sslserver "/home/dokku/delta-lic-server/tls/server.crt"' returns '/home/dokku/delta-lic-server/tls/server.crt: OK' and 'dokku certs:report delta-lic-server':

=====> delta-lic-server ssl information
       Ssl dir:                       /home/dokku/delta-lic-server/tls
       Ssl enabled:                   true                     
       Ssl hostnames:                 register1.deltainformatica.es www.register1.deltainformatica.es
       Ssl expires at:                Oct  2 23:59:59 2023 GMT 
       Ssl issuer:                    C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
       Ssl starts at:                 Sep  1 00:00:00 2022 GMT 
       Ssl subject:                   subject=CN = register1.deltainformatica.es
       Ssl verified:                  verified by a certificate authority

but when I try to activate reject unauthorized calls using 'dokku config:set delta-lic-server NODE_TLS_REJECT_UNAUTHORIZED='1'' I still get the error:

 !     App container failed to start (web.1)
=====> Start of delta-lic-server container output (web.1)
       Error: self signed certificate in certificate chain
           at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
           at TLSSocket.emit (node:events:513:28)
           at TLSSocket.emit (node:domain:489:12)
           at TLSSocket._finishInit (node:_tls_wrap:953:8)
           at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
         code: 'SELF_SIGNED_CERT_IN_CHAIN'
       }

Maybe the CA certificate is not available inside dokku?

**Comment by josegonzalez** [comment]
Certificates are not made available inside of the container, and are only used by the host nginx proxy. If you need it in the container, either set them as env vars or use persistent storage to mount the files into the container.
