### ISSUE TITLE
Wrong App created at: returned by dokku apps:report

### ISSUE THREAD

**Issue by esirK** [dokku/dokku#5343]
### Description of problem

`dokku apps:report` is supposed to return when I created an app but instead it returns the last time the `AppRoot` was modified.

My suggestion is creating a file(inside the AppRoot) during app creation that just holds the time the app is created and read this file anytime the report for created at is run.

### Steps to reproduce

1. Create an app and run dokku apps:report $APP_NAME and note the `created at` time
2. Perform a simple change e.g `dokku config:set X=X` and run the $APP_NAME and note the `created at` time and compare the 2

### dokku report $APP_NAME

```
=====> x app information
       App created at:                1662226840
       App deploy source:
       App deploy source metadata:
       App dir:                       /home/dokku/x
       App locked:                    false
```

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
