### ISSUE TITLE
Can't reach my app on the subdomain URL

### ISSUE THREAD

**Issue by Bilboramix** [dokku/dokku#5359]
### Description of problem

I'm trying to deploy a "hello world" expressJS app to be used with dokku so i managed to push my code but i'm not able to reach my app.

The app is running and should be accessible at this URL : testapi.api.codingbill.com
![image](https://user-images.githubusercontent.com/91626615/190219986-a3b8e56c-40b3-46f3-a9fa-780a6f9d0422.png)

Here are firewall settings, port mapping and logs from the running app :
![image](https://user-images.githubusercontent.com/91626615/190217822-0f97a3d1-4ec2-402e-a28c-9f808a4ca567.png)

But i can't reach it :
![image](https://user-images.githubusercontent.com/91626615/190219527-a5756908-8837-4e9d-b635-c832d1242c08.png)

If i check my domain name, i've got nginx homepage :
![image](https://user-images.githubusercontent.com/91626615/190219806-dd1396dc-9876-4052-b83b-04c29f68b375.png)

My config vars :
![image](https://user-images.githubusercontent.com/91626615/190218453-d141ec59-6672-45b2-b21d-5568dbbed21d.png)

I'm not sure if i did something wrong or if i'm missing something :(

### Steps to reproduce

1- Install dokku
2- Setup SSH and domain name
3- Create app with config vars
4- Push the app to deploy
5- Try to reach the app

### dokku report $APP_NAME

-----> uname: Linux vps-76430.fhnet.fr 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:             970         212         199           0         559         595
       Swap:           2047          70        1977
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.18
        API version:       1.41
        Go version:        go1.18.6
        Git commit:        b40c2f6
        Built:             Thu Sep  8 23:11:43 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.18
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.18.6
         Git commit:       e42327a
         Built:            Thu Sep  8 23:09:30 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.8
         GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
        runc:
         Version:          1.1.4
         GitCommit:        v1.1.4-0-g5fd4c4d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
         compose: Docker Compose (Docker Inc., v2.10.2)
         scan: Docker Scan (Docker Inc., v0.17.0)

       Server:
        Containers: 1
         Running: 1
         Paused: 0
         Stopped: 0
        Images: 15
        Server Version: 20.10.18
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
        runc version: v1.1.4-0-g5fd4c4d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
         cgroupns
        Kernel Version: 5.15.0-40-generic
        Operating System: Ubuntu 22.04.1 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 970.9MiB
        Name: vps-76430.fhnet.fr
        ID: CXPE:DITP:ZL2E:RLY2:ZK2O:BCE4:KDVN:SXXU:CD3A:JPTQ:WHVU:JERI
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.34.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
       herokuish: 0.5.37
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v198
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v214
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v94
         heroku-buildpack-play      v26
         heroku-buildpack-php       v223
         heroku-buildpack-go        v166
         heroku-buildpack-nginx     v16
         buildpack-null             v3
-----> dokku version: dokku version 0.28.1
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins:
         00_dokku-standard    0.28.1 enabled    dokku core standard plugin
         20_events            0.28.1 enabled    dokku core events logging plugin
         app-json             0.28.1 enabled    dokku core app-json plugin
         apps                 0.28.1 enabled    dokku core apps plugin
         builder              0.28.1 enabled    dokku core builder plugin
         builder-dockerfile   0.28.1 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.28.1 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.27.0 enabled    dokku core builder-lambda plugin
         builder-null         0.28.1 enabled    dokku core builder-null plugin
         builder-pack         0.28.1 enabled    dokku core builder-pack plugin
         buildpacks           0.28.1 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.28.1 enabled    dokku core caddy-vhosts plugin
         certs                0.28.1 enabled    dokku core certificate management plugin
         checks               0.28.1 enabled    dokku core checks plugin
         common               0.28.1 enabled    dokku core common plugin
         config               0.28.1 enabled    dokku core config plugin
         cron                 0.28.1 enabled    dokku core cron plugin
         docker-options       0.28.1 enabled    dokku core docker-options plugin
         domains              0.28.1 enabled    dokku core domains plugin
         enter                0.28.1 enabled    dokku core enter plugin
         git                  0.28.1 enabled    dokku core git plugin
         logs                 0.28.1 enabled    dokku core logs plugin
         network              0.28.1 enabled    dokku core network plugin
         nginx-vhosts         0.28.1 enabled    dokku core nginx-vhosts plugin
         plugin               0.28.1 enabled    dokku core plugin plugin
         proxy                0.28.1 enabled    dokku core proxy plugin
         ps                   0.28.1 enabled    dokku core ps plugin
         registry             0.28.1 enabled    dokku core registry plugin
         repo                 0.28.1 enabled    dokku core repo plugin
         resource             0.28.1 enabled    dokku core resource plugin
         run                  0.28.1 enabled    dokku core run plugin
         scheduler            0.28.1 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.28.1 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.28.1 enabled    dokku core scheduler-null plugin
         shell                0.28.1 enabled    dokku core shell plugin
         ssh-keys             0.28.1 enabled    dokku core ssh-keys plugin
         storage              0.28.1 enabled    dokku core storage plugin
         trace                0.28.1 enabled    dokku core trace plugin
         traefik-vhosts       0.28.1 enabled    dokku core traefik-vhosts plugin
=====> testapi app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> testapi app information
       App created at:                1663171420
       App deploy source:             testapi
       App deploy source metadata:    testapi
       App dir:                       /home/dokku/testapi
       App locked:                    false
=====> testapi builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> testapi builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> testapi builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> testapi builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> testapi buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> testapi ssl information
       Ssl dir:                       /home/dokku/testapi/tls
       Ssl enabled:                   false
       Ssl hostnames:
       Ssl expires at:
       Ssl issuer:
       Ssl starts at:
       Ssl subject:
       Ssl verified:
=====> testapi checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> testapi cron information
       Cron task count:               0
=====> testapi docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> testapi domains information
       Domains app enabled:           true
       Domains app vhosts:            testapi.api.codingbill.com
       Domains global enabled:        true
       Domains global vhosts:         api.codingbill.com
=====> testapi git information
       Git deploy branch:             main
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:
       Git last updated at:           1663171420
=====> testapi logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> testapi network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.2:5000
=====> testapi nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/testapi-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/testapi-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1663167671
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> testapi proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000
       Proxy type:                    nginx
=====> testapi ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 89185cf62b6)
=====> testapi registry information
       Registry computed image repo:      dokku/testapi
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> testapi resource information
=====> testapi scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> testapi scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> testapi storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

### Additional information

Output of dokku nginx:show-config :

```
server {
  listen      [::]:80;
  listen      80;
  server_name testapi.api.codingbill.com;
  access_log  /var/log/nginx/testapi-access.log;
  error_log   /var/log/nginx/testapi-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://testapi-5000;
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_buffer_size 4096;
    proxy_buffering on;
    proxy_buffers 8 4096;
    proxy_busy_buffers_size 8192;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-Start $msec;

  }



  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }
  include /home/dokku/testapi/nginx.conf.d/*.conf;

}

upstream testapi-5000 {

  server 172.17.0.2:5000;
}
```
Output of "dokku ps:inspect" :

```
[
    {
        "AppArmorProfile": "docker-default",
        "Args": [
            "web"
        ],
        "Config": {
            "AttachStderr": true,
            "AttachStdin": false,
            "AttachStdout": true,
            "Cmd": [
                "/start",
                "web"
            ],
            "Domainname": "",
            "Entrypoint": null,
            "Env": [
                "DOKKU_PROXY_PORT_MAP=http:80:5000",
                "GIT_REV=XXXXXX",
                "CURL_CONNECT_TIMEOUT=XXXXXX",
                "DOKKU_APP_RESTORE=1",
                "DOKKU_APP_TYPE=herokuish",
                "DOKKU_PROXY_PORT=80",
                "DYNO=web.1",
                "USER=herokuishuser",
                "CURL_TIMEOUT=XXXXXX",
                "NODE_ENV=XXXXXX",
                "PORT=5000",
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "STACK=XXXXXX",
                "DEBIAN_FRONTEND=XXXXXX"
            ],
            "Hostname": "89185cf62b65",
            "Image": "dokku/testapi:latest",
            "Labels": {
                "com.dokku.app-name": "testapi",
                "com.dokku.builder-type": "herokuish",
                "com.dokku.container-type": "deploy",
                "com.dokku.dyno": "web.1",
                "com.dokku.image-stage": "release",
                "com.dokku.process-type": "web",
                "com.gliderlabs.herokuish/stack": "heroku-20",
                "dokku": "",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "dokku"
            },
            "OnBuild": null,
            "OpenStdin": false,
            "StdinOnce": false,
            "Tty": false,
            "User": "",
            "Volumes": null,
            "WorkingDir": ""
        },
        "Created": "2022-09-14T16:03:19.35717725Z",
        "Driver": "overlay2",
        "ExecIDs": null,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/92b8ca11bf334fbe0753972aae03e3fea62c3c0276858b0446a3b02040030aa7-init/diff:/var/lib/docker/overlay2/a7f87cfa6d59737f5ece07e709e4fe7bdfa3ae2a73055c7f751ab72e6fe2736b/diff:/var/lib/docker/overlay2/fe355ccd0bb4d2fd33ab536c529aaa0eef7a85e5aef7a986493c7acf13674a8a/diff:/var/lib/docker/overlay2/3003234a3d8498ffd6a077b52d3c9e83395cb7d73b658177a1b05d523e8e58ce/diff:/var/lib/docker/overlay2/b3bf78f3ccc20e873a54152dbcbdad0772ff87607364c5bc894198690d1b632e/diff:/var/lib/docker/overlay2/6bfffc21d477d7c243e66f08d2b98e6340113b45d37d26166120d0558515457b/diff:/var/lib/docker/overlay2/849518fba72564e5ef86127b49ecdc309896300d8b28ceef3c5f1b32b613f5e3/diff:/var/lib/docker/overlay2/6373b90ba44706d05a8af548493c9305e0872dd79cb33f9ea554f2e870a8f70e/diff:/var/lib/docker/overlay2/e1d48c2267eaaada5f7773810bfbaff2de96bd3928ce936e28fedc6c14b53be8/diff:/var/lib/docker/overlay2/bfb9052981dfc6e6f7ad8e5d24a0622a1ec25e1d174a49b10d5fabb837ef2f0d/diff:/var/lib/docker/overlay2/f9941975b317047235d170eeaf3c4ca6d7dfd157889ce55128793272c290b7ac/diff:/var/lib/docker/overlay2/803d95e1227708747e2e0a4bd2eb9e971e89ca27ae05ceeab7abf9902950542e/diff:/var/lib/docker/overlay2/f7fc3139e9733dc7aa2e53a7693c850970d66e6eacf02c86ec780bfe0629bb33/diff:/var/lib/docker/overlay2/388cde56d1a4bd8a332785009172b695c57ff269a14d5637e3e271c75bb85e4a/diff:/var/lib/docker/overlay2/2fd3144ed7e2f4a5358e37561d0cc85021c0c4882236b97b8017efc5ecc708ae/diff:/var/lib/docker/overlay2/003455fc16732f92d27f59963c6eee1a46f4a3a0ca9137e4d60fccc8af1b1867/diff",
                "MergedDir": "/var/lib/docker/overlay2/92b8ca11bf334fbe0753972aae03e3fea62c3c0276858b0446a3b02040030aa7/merged",
                "UpperDir": "/var/lib/docker/overlay2/92b8ca11bf334fbe0753972aae03e3fea62c3c0276858b0446a3b02040030aa7/diff",
                "WorkDir": "/var/lib/docker/overlay2/92b8ca11bf334fbe0753972aae03e3fea62c3c0276858b0446a3b02040030aa7/work"
            },
            "Name": "overlay2"
        },
        "HostConfig": {
            "AutoRemove": false,
            "Binds": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceWriteIOps": null,
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "CapAdd": null,
            "CapDrop": null,
            "Cgroup": "",
            "CgroupParent": "",
            "CgroupnsMode": "private",
            "ConsoleSize": [
                0,
                0
            ],
            "ContainerIDFile": "",
            "CpuCount": 0,
            "CpuPercent": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpuShares": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "Devices": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IOMaximumBandwidth": 0,
            "IOMaximumIOps": 0,
            "Init": true,
            "IpcMode": "private",
            "Isolation": "",
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "Links": null,
            "LogConfig": {
                "Config": {
                    "max-size": "10m"
                },
                "Type": "json-file"
            },
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "NanoCpus": 0,
            "NetworkMode": "default",
            "OomKillDisable": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "PidsLimit": null,
            "PortBindings": {},
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "ReadonlyRootfs": false,
            "RestartPolicy": {
                "MaximumRetryCount": 10,
                "Name": "on-failure"
            },
            "Runtime": "runc",
            "SecurityOpt": null,
            "ShmSize": 67108864,
            "UTSMode": "",
            "Ulimits": null,
            "UsernsMode": "",
            "VolumeDriver": "",
            "VolumesFrom": null
        },
        "HostnamePath": "/var/lib/docker/containers/89185cf62b65f3e496462dfb3cf8e32c914b7892ae6b81d217ddfdf7d5e00afa/hostname",
        "HostsPath": "/var/lib/docker/containers/89185cf62b65f3e496462dfb3cf8e32c914b7892ae6b81d217ddfdf7d5e00afa/hosts",
        "Id": "89185cf62b65f3e496462dfb3cf8e32c914b7892ae6b81d217ddfdf7d5e00afa",
        "Image": "sha256:8e7ec5ce0597f6d79926bcce6d24d6b27fb3b25dbaf3e8111d0cfc08d2bd2460",
        "LogPath": "/var/lib/docker/containers/89185cf62b65f3e496462dfb3cf8e32c914b7892ae6b81d217ddfdf7d5e00afa/89185cf62b65f3e496462dfb3cf8e32c914b7892ae6b81d217ddfdf7d5e00afa-json.log",
        "MountLabel": "",
        "Mounts": [],
        "Name": "/testapi.web.1",
        "NetworkSettings": {
            "Bridge": "",
            "EndpointID": "2c7c265e8cac38968667529ab8742ce5e6a97292922178e2f23acdcdf59a3dd5",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "HairpinMode": false,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "Aliases": null,
                    "DriverOpts": null,
                    "EndpointID": "2c7c265e8cac38968667529ab8742ce5e6a97292922178e2f23acdcdf59a3dd5",
                    "Gateway": "172.17.0.1",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "IPAMConfig": null,
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "Links": null,
                    "MacAddress": "02:42:ac:11:00:02",
                    "NetworkID": "591b93d58ccd4a17d799349c9c446d68ec9a1e1d0b16ecb30c672de7f6a7c1c6"
                }
            },
            "Ports": {},
            "SandboxID": "429ed0ddf1ffadaa9de4d64c7a90c7b09adad6f651a39e57b4ce8c05470f1d03",
            "SandboxKey": "/var/run/docker/netns/429ed0ddf1ff",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null
        },
        "Path": "/start",
        "Platform": "linux",
        "ProcessLabel": "",
        "ResolvConfPath": "/var/lib/docker/containers/89185cf62b65f3e496462dfb3cf8e32c914b7892ae6b81d217ddfdf7d5e00afa/resolv.conf",
        "RestartCount": 0,
        "State": {
            "Dead": false,
            "Error": "",
            "ExitCode": 0,
            "FinishedAt": "0001-01-01T00:00:00Z",
            "OOMKilled": false,
            "Paused": false,
            "Pid": 173784,
            "Restarting": false,
            "Running": true,
            "StartedAt": "2022-09-14T16:03:20.188541148Z",
            "Status": "running"
        }
    }
]
```

**Comment by josegonzalez** [comment]
The domain isn't setup in dns:

```
% dig testapi.api.codingbill.com

; <<>> DiG 9.10.6 <<>> testapi.api.codingbill.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43791
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;testapi.api.codingbill.com.	IN	A

;; AUTHORITY SECTION:
codingbill.com.		60	IN	SOA	dns200.anycast.me. tech.ovh.net. 2022091306 86400 3600 3600000 60

;; Query time: 68 msec
;; SERVER: 10.9.165.187#53(10.9.165.187)
;; WHEN: Wed Sep 14 13:30:24 EDT 2022
;; MSG SIZE  rcvd: 120

```

You'll need an entry in your DNS provider for that subdomain.

**Comment by Bilboramix** [comment]
Thanks a lot for being so fast haha.
Gonna try this !

**Comment by Bilboramix** [comment]
Okay, debunked this with this page : https://dokku.com/docs/networking/dns/
There should be a link to it in the Getting Started section.
Thanks a lot for your work !
💯

**Comment by josegonzalez** [comment]
The dns documentation is linked to from the installation doc [here](https://dokku.com/docs/getting-started/installation/). Not sure what else we can do to make this more apparent :)

**Comment by Bilboramix** [comment]
Oh you're right sorry, feeling a bit dumb, i checked the domains doc link but not the dns one.
My bad :-|
