### ISSUE TITLE
Make the apps, config, and ps bare commands heroku-compatible

### ISSUE THREAD

**Issue by dogweather** [dokku/dokku#5362]
### Description of feature

Heroku's CLI gives the most commonly wanted report-type info when running a command. A sub-command isn't needed. This makes it easy and fast to get info. E.g.:

<img width="297" alt="Screen Shot 2022-09-16 at 7 04 17 PM" src="https://user-images.githubusercontent.com/150670/190834494-65d4aa07-1889-413c-99bb-d2e73758ddc1.png">

<img width="685" alt="Screen Shot 2022-09-16 at 7 04 43 PM" src="https://user-images.githubusercontent.com/150670/190834526-9a4685e8-7dde-48b4-a3ea-6616cef2e32d.png">

<img width="269" alt="Screen Shot 2022-09-16 at 7 06 04 PM" src="https://user-images.githubusercontent.com/150670/190834564-572c2906-9adf-4460-a5df-b223f4955c9c.png">

These really make it a pleasure to use. I know that I can add `--help` to get info about sub-commands. E.g., the simple `apps` list above becomes this easy-to-read help text:

<img width="786" alt="Screen Shot 2022-09-16 at 7 07 01 PM" src="https://user-images.githubusercontent.com/150670/190834588-f97383d3-76ae-492b-8f73-b223baded0b4.png">

**Comment by josegonzalez** [comment]
Do you have a list of bare commands that worked differently than their Heroku counterparts? I want to concentrate on that to avoid a long-running ticket.

**Comment by dogweather** [comment]
> Do you have a list of bare commands that worked differently than their Heroku counterparts? I want to concentrate on that to avoid a long-running ticket.

No, I don't - these are just the ones I use the most. We can start a ticket for each CLI command that's not compatible.

**Comment by josegonzalez** [comment]
Do you have the output for those commands when:

- There are no apps
- There are no env vars
- There are processes running?

**Comment by josegonzalez** [comment]
Any chance anyone has the output for the above?

**Comment by josegonzalez** [comment]
### No apps:

```
% heroku apps
You have no apps.
```

### No env vars

```
% heroku config
=== dry-earth-55231 Config Vars

```
% heroku ps
 ▸    Starting November 28th, 2022, free Heroku Dynos will no longer be available. To keep your apps running, upgrade to paid dynos. Learn more in our blog
 ▸    (https://blog.heroku.com/next-chapter).
No dynos on ⬢ dry-earth-55231
```

**Comment by josegonzalez** [comment]
What output should we show for `dokku ps`? Is that one as useful to change the output as the others?

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. If we want this to be changed on other commands, please file a ticket with the exact desired output.
