### ISSUE TITLE
Heroku compatibility: ps command

### ISSUE THREAD

**Issue by dogweather** [dokku/dokku#5363]
### Description of feature

I miss Heroku's ps command:

<img width="953" alt="Screen Shot 2022-09-16 at 7 41 21 PM" src="https://user-images.githubusercontent.com/150670/190835647-f79b0421-0627-470c-b36d-2a31c89d53c6.png">

It's literally just the `ps` command. It feels highly calibrated to show what I, the app developer need to see: High level of abstraction, app processes info.

Dokku's output seems to be for the Dokku developer - debug info that'd be helpful when working on Dokku itself. E.g., first it's not obvious how to get just that simple `ps` output:

<img width="634" alt="Screen Shot 2022-09-16 at 7 48 31 PM" src="https://user-images.githubusercontent.com/150670/190835813-d64cc11c-cb77-45a0-b3f8-b51cf0f14050.png">

The simplest output `report` is down in the list. Running it seems to give mostly Dokku debug output - internals, implementation details. The last line of the tables is probably closest to Heroku's ps, but it doesn't provide much.

<img width="566" alt="Screen Shot 2022-09-16 at 7 50 33 PM" src="https://user-images.githubusercontent.com/150670/190835864-29d433bf-8976-4328-9308-4bb57c1c3794.png">

**Comment by josegonzalez** [comment]
Closing in favor of #5362
