### ISSUE TITLE
git push to the running project and lost everything

### ISSUE THREAD

**Issue by baothi** [dokku/dokku#5364]
### Description of problem

I have 1 problem, project is running with dokku and it works fine but when I push next time it rebuilds from scratch and loses everything like image in media so what should I do.
I use python django push dockerfile to build dokku. I'm running on digitalocean server
FROM python:3.9.7

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /code
WORKDIR /code
RUN python3.9 -m pip install --no-cache-dir --upgrade \
    pip \
    setuptools \
    wheel

RUN addgroup --system django \
    && adduser --system --ingroup django django

COPY requirements.txt /code/

RUN pip install --no-cache-dir  -r requirements.txt && rm -rf /var/lib/apt/lists/*
COPY . /code/

# Collect static files
# RUN python manage.py collectstatic --noinput --clear
# RUN chmod -R 777 /code/static/
# RUN chmod -R 777 /code/staticfiles/

RUN chown -R django:django /code
USER django

# COPY ./entrypoint.sh /
# ENTRYPOINT ["sh", "/entrypoint.sh"]

EXPOSE 5000
# Run application
# CMD gunicorn phongthuy_thanhnhan.wsgi:application --bind 0.0.0.0:8000
CMD [ "gunicorn", "code:code" ]

### dokku report $APP_NAME

app_name is phongthuy_thanhnhan

### Additional information

python django

### Output of failing deploy after running: dokku trace:off

```shell
running ok
```

### Output of failing deploy after running: dokku trace:on

```shell
running ok
```

**Comment by javierav** [comment]
If I understood you, the problem that you have is that when you push a new version, all media (files uploades by users) are lost from you app / filesystem, no?

This is true due to how docker and dokku works. You should persist the files using an external service like S3.

https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

**Comment by baothi** [comment]
> If I understood you, the problem that you have is that when you push a new version, all media (files uploaded by users) are lost from you app / filesystem, no?
> 
> This is true due to how docker and dokku works. You should persist the files using an external service like S3.
> 
> https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

Exactly, when I push the new code on it will automatically rebuild new images and will lose the previously submitted images, Currently the project is not known to many people so it is not possible to buy or rent a server or using S3 so is there any other way you can save images outside docker images ?

**Comment by baothi** [comment]
> This is expected. The container environment is ephemeral (by design). You'll want to use persistent storage, either via [our persistent storage plugin](https://dokku.com/docs/advanced-usage/persistent-storage/) or externally like s3.

I want to use this storage plugin but I don't know how, even if I follow the documentation, can you help me? Currently I am running docker
