### ISSUE TITLE
Add warning/autofix when app has ssl certs but no active https proxy listening

### ISSUE THREAD

**Issue by holtergram** [dokku/dokku#5368]
## Description of problem
I was running into an issue with an app for which I enabled certs via letsencrypt but forgot to add the needed proxy listener via `dokku proxy:ports-add APP https:443:80`. As a result of this I was getting a server error without any specific clue why this was happening. 

If possible, I think it'd be great to add a warning/notice that when enabling certs the nginx conf is also updated. At lest in my case it'd have been good to have that kind of reminder.

**Comment by josegonzalez** [comment]
I think we can log when this is the case in the nginx plugin, and also log something similar if the cert is added but no associated proxy port is added.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
