### ISSUE TITLE
Path based routing/virtual host

### ISSUE THREAD

**Issue by fishnux** [dokku/dokku#5379]
### Description of feature

Ability to deploy an app on a custom path, like:
```
example.com/blog
```
Instead of:
```
blog.example.com
```

**Comment by josegonzalez** [comment]
What would happen if a user went to `example.com` in the above case? Where would we route requests to? Additionally, how would this fit with our existing `nginx.conf.sigil` generation process?

**Comment by fishnux** [comment]
> What would happen if a user went to example.com in the above case?

If another app is not deployed on the virtual path "/", then most likely we'd show a 404 error

> Additionally, how would this fit with our existing nginx.conf.sigil generation process?

For each virtual path (e.g.: "/blog"), we would have an nginx `location` block, e.g.:
```
location /blog {
    // proxy to app blog
}
```
The app would still need to be assigned to a domain name as it's currently done. As a reminder, the following directives are used on `nginx.sigil.conf` for the virtual host functionality:
```
server {
  {{ if $.SSL_SERVER_NAME }}server_name {{ $.SSL_SERVER_NAME }}; {{ end }}
  {{ if $.NOSSL_SERVER_NAME }}server_name {{ $.NOSSL_SERVER_NAME }}; {{ end }}
  // (...)
}
```

The `nginx.sigil.conf` template would have to be modified to iterate through the virtual paths assigned to a given app and consequently generate the `location` blocks. Perhaps the most difficult part is a vhost nginx file is no longer associated to a single app, but rather a domain name - as we need to be able to deploy different apps under the same domain name (but different paths)

**Comment by josegonzalez** [comment]
I think that the nginx.conf.sigil functionality would be fairly broken in this case, and we'd need to essentially build a new routing plugin. Thats not something I'm interested in doing today, but I won't be opposed to having someone contribute such a thing via a PR (assuming it doesn't break existing functionality).

I suggest taking a look at the caddy or traefik plugin, both of which expose much richer routing functionality via tags.
