### ISSUE TITLE
Docker options for build don't seem to be used

### ISSUE THREAD

**Issue by dnamsons** [dokku/dokku#5388]
### Description of problem

The docker options for build time arguments don't seem to actually be used, it doesn't seem to be related to the content of the arguments being passed(as far as i see, passing `--no-cache` is ignored as well)

### Steps to reproduce

1. Add docker option for build time
`dokku docker-options:add production build '--build-arg GITHUB_TOKEN="hello"'`

2. `git push dokku-production` to deploy with the Dockerfile
```Dockerfile
FROM node:16

ARG GITHUB_TOKEN

RUN echo "TOKEN is: $GITHUB_TOKEN"
```

The output for the `RUN` step is `TOKEN is:` without the actual token being passed.

### dokku report $APP_NAME

https://gist.github.com/dnamsons/956d148cc367cac582b3a42e1fffeee7

### Additional information

I am using the most recent version - 0.28.1

**Comment by josegonzalez** [comment]
This definitely works for me as expected. I'll merge the above test, but if you want to contribute a bats tests that proves otherwise, I'd be happy to take a look.

Closing as there is a PR open.
