### ISSUE TITLE
dokku command not found

### ISSUE THREAD

**Issue by unnimona** [dokku/dokku#5390]
### Description of problem

i ran the default installation steps

dokku
dokku: command not found

### Steps to reproduce

wget https://raw.githubusercontent.com/dokku/dokku/v0.28.1/bootstrap.sh
sudo DOKKU_TAG=v0.28.1 bash bootstrap.sh

### dokku report $APP_NAME

wget https://raw.githubusercontent.com/dokku/dokku/v0.28.1/bootstrap.sh
sudo DOKKU_TAG=v0.28.1 bash bootstrap.sh
--2022-10-09--  https://raw.githubusercontent.com/dokku/dokku/v0.28.1/bootstrap.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... :::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8642 (8.4K) [text/plain]
Saving to: ‘bootstrap.sh.1’

bootstrap.sh.1                             100%[=======================================================================================>]   8.44K  --.-KB/s    in 0s      

2022-10-09 15:21:04 (22.1 MB/s) - ‘bootstrap.sh.1’ saved [8642/8642]

Preparing to install v0.28.1 from https://github.com/dokku/dokku.git...
--> Ensuring we have the proper dependencies
E: The repository 'http://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/3.4 Release' does not have a Release file.

**Comment by josegonzalez** [comment]
The installation isn't completing because you have some mongodb apt repository that is misconfigured. You'll want to fix that so an `apt-get update` completes successfully.
