### ISSUE TITLE
When using Traefik with lets encrypt apps don't seem to get certificates issued.

### ISSUE THREAD

**Issue by cooperaj** [dokku/dokku#5457]
No apps that I've added have had anything other than the TRAEFIK_DEFAULT_CERT applied to them when I access them.

The API/Dashboard does however work with an appropriate certificate. I believe this is because of this line in the compose template https://github.com/dokku/dokku/blob/14ba1a214fa1fd82f3ac9b6757357696c85ab509/plugins/traefik-vhosts/templates/compose.yml.sigil#L37 

However, no such label gets applied to the newly created apps. I'd have though such a line would be in this section of the function:
https://github.com/dokku/dokku/blob/14ba1a214fa1fd82f3ac9b6757357696c85ab509/plugins/traefik-vhosts/docker-args-process-deploy#L102-L117

**Comment by josegonzalez** [comment]
In that label you mentioned, should that be `traefik.http.routers.$APP-$PROC_TYPE.tls.certresolver=leresolver` if applied to the container? Mind testing that to see if it works as expected with the change?

**Comment by cooperaj** [comment]
I think that looks about right. Will chuck it in my local instance and see what it does.

**Comment by cooperaj** [comment]
Close, needed '-https' on the end but that works. Apps now getting https certs.

**Comment by josegonzalez** [comment]
Awesome, thanks for the MR. I'll get this merged into the next release.

Closing as the MR is open.
