### ISSUE TITLE
How to deploy from a local docker image?

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku#5492]
### Discussed in https://github.com/dokku/dokku/discussions/5486

<div type='discussions-op-text'>

<sup>Originally posted by **IgnisDa** November 27, 2022</sup>
Earlier this was possible: https://dokku.com/docs~v0.8.2/deployment/methods/images/#deploying-an-image-from-ci

But `dokku:tags` has since been removed. `dokku git:from-image` does not respect locally present images.

Is it possible to deploy local docker images?</div>

**Comment by josegonzalez** [comment]
@IgnisDa do you mind adding some replication steps + the output of `dokku report` to this ticket so I can investigate?

**Comment by IgnisDa** [comment]
@josegonzalez `dokku git:from-image` works as expected. I was just running the commands wrong. However it would be good if we can have explicit docs on how to deploy local docker images. I can make a PR if necessary.

**Comment by josegonzalez** [comment]
Is there something different for local docker images that needs to be run from what is documented now?

**Comment by IgnisDa** [comment]
Would be good if this part can be brought back in albeit with new the new `dokku git:*` commands.

**Comment by IgnisDa** [comment]
```sh
# build the image
docker build -t my-image .
# copy the image to the dokku host
docker save my-image | bzip2 | ssh my.dokku.host "bunzip2 | docker load"
# deploy the image
ssh my.dokku.host 'dokku git:from-image my-image'
```

**Comment by josegonzalez** [comment]
@IgnisDa there is now a [tutorials repository](https://github.com/dokku/tutorials) you can add such a tutorial to. I recommend you contribute a tutorial for your use case there.

**Comment by josegonzalez** [comment]
There is now a tutorial for this: https://dokku.com/tutorials/other/deploying-an-image-without-a-registry/
