### ISSUE TITLE
Help instructions for `dokku apps:clone` has args in wrong order?

### ISSUE THREAD

**Issue by joevandyk** [dokku/dokku#5501]
### Description of problem

on dokku 0.28.4

```
$ dokku apps
Usage: dokku apps[:COMMAND]

Manage apps

Additional commands:
    apps:clone <old-app> <new-app>   Clones an app
  ...
```

So, `old-app` is first and `new-app` is second.  I have an app called `ruby-getting-started` and want to clone it to a new app called `ruby-getting-started-new`

```
dokku apps:clone ruby-getting-started ruby-getting-started-new-one
 !     Name is already taken
 ```
 
 didn't work - says name was already taken
 
 ```
 dokku apps:clone ruby-getting-started-new ruby-getting-started
-----> Cloning ruby-getting-started to ruby-getting-started-new
```
worked - but the arguments are not in the expected order. 

### Steps to reproduce

above

### dokku report $APP_NAME

doesn't seem related

**Comment by josegonzalez** [comment]
Are you sure this is right? We have tests for this, but more importantly, I just ran it on my end:

```
root@2e943ea9da29:~/go/src/github.com/dokku/dokku# dokku apps:create ruby-getting-started
-----> Creating ruby-getting-started...
-----> Creating new app virtual host file...
root@2e943ea9da29:~/go/src/github.com/dokku/dokku# dokku apps:clone ruby-getting-started ruby-getting-started-new-one
-----> Cloning ruby-getting-started to ruby-getting-started-new-one
-----> Creating ruby-getting-started-new-one...
-----> Creating new app virtual host file...
-----> Skipping DOKKU_PROXY_SSL_PORT, it is not set in the environment
-----> Skipping DOKKU_PROXY_PORT_MAP, it is not set in the environment
```

Can you fill out the rest of the output we ask for in the issue template? While you think it might not be related, its actually pretty important to help me figure out if something else might be happening here.

**Comment by josegonzalez** [comment]
Oh you know what probably happened? You're running the clone from your local repo using the official remote `dokku` client. That client sets the first arg to the detected remote app name, so you actually ended up running something like:

```shell
dokku apps:clone ruby-getting-started ruby-getting-started ruby-getting-started-new-one
```

In the above case, the third argument is ignored, and thats why you get the error you get.

For your other case, you actually ran:

```shell
dokku apps:clone ruby-getting-started ruby-getting-started-new ruby-getting-started
```

So it looks like the arguments are reversed but the third arg is actually ignored.

Hope that explains things.

**Comment by joevandyk** [comment]
Ah, yes.
