### ISSUE TITLE
Odd issues with Ubuntu 14.04

### ISSUE THREAD

**Issue by Tarang** [dokku/dokku#551]
I installed Dokku and it worked fine with a deployment. After restarting the server problems began to pop up.

If trying to access the deployed app via http it gives a 'Bad Gateway' error.

Checking the docker logs

```
docker logs 6b9dfd334bbb
2014/04/22 09:40:32 no such file or directory
```

Whats odd about this is that its not from the app but something docker or dokku related. On the apps that do give console input this appears just after it starts up.

Edit: Additionally If i try to redeploy/change the config this is what happens

```
remote: Error: Cannot kill container 6b9dfd334bbb0b0ceedcfed49177c31073cc41f49e7e68e585f6453718691187: no such process
remote: 2014/04/22 09:47:43 Error: failed to kill one or more containers
```

To fix it I just ran this again

```
wget -qO- https://raw.github.com/progrium/dokku/v0.2.3/bootstrap.sh | sudo DOKKU_TAG=v0.2.3 bash
```

But if I restart the machine the problem comes back

**Comment by debianmaster** [comment]
struggling with this issue :(
DOKKU_TAG=v0.4.1  /  ubuntu 14.04 machine

```sh
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> pay container output:
       Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
       Recommending WEB_CONCURRENCY=1
       > paytm@1.0.0 start /app
       > node server.js
=====> end pay container output
remote: Error response from daemon: Cannot kill container 1911520e8dfbf983c95fd6710b83324a073511f13182122f68ec0881a301a9b9: Container 1911520e8dfbf983c95fd6710b83324a073511f13182122f68ec0881a301a9b9 is not running
remote: Error: failed to kill containers: [1911520e8dfbf983c95fd6710b83324a073511f13182122f68ec0881a301a9b9]
To dokku@uat.i63.in:pay
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@uat.i63.in:pay'
```

**Comment by josegonzalez** [comment]
@debianmaster please do not comment on year old issues :)

You probably have a machine with too little memory. Dokku's requirements are at least 1GB of memory. You should add swap as noted [here](http://progrium.viewdocs.io/dokku/advanced-installation/#vms-with-less-than-1gb-of-memory).
