### ISSUE TITLE
RHEL 8 Support

### ISSUE THREAD

**Issue by cburkins** [dokku/dokku#5527]
### Description of feature

I've been using dokku on Centos 7, and it's been running great.

I'm required to migrate over to RHEL 8 servers, and I'm trying to get dokku installed, but the install script is claiming an unsupported distro.

Is there an endorsed method for installing dokku on RHEL 8 ?

**Comment by josegonzalez** [comment]
We dropped support for RHEL in 0.28.x. The blog post [here](https://dokku.com/blog/2022/dokku-0.28.x-wrapup/#no-more-support-for-centos-7-debian-9-fedora-opensuse) gives some reasoning behind this.

Please use our docker-based method for installing Dokku on unsupported operating systems.

**Comment by cburkins** [comment]
Thanks for info, Jose.   Let me try out that docker-based install
