### ISSUE TITLE
Traefik basic auth does not enable

### ISSUE THREAD

**Issue by jamesremuscat** [dokku/dokku#5536]
After following the instructions at https://dokku.com/docs/networking/proxies/traefik/#enabling-api-basic-auth I was still not getting prompted for basic authentication at the Traefik dashboard.

Inspecting the labels given to the Traefik container led me to this line:

https://github.com/dokku/dokku/blob/e6b1cbc057e0137f8966ff47d7b9336223ea6e96/plugins/traefik-vhosts/templates/compose.yml.sigil#L34

Manually correcting the label to `traefik.http.routers.api.middlewares=auth` (note the addition of `.api`) has the desired effect and basic auth works.

Sorry for not drawing this up as a full PR but I hope the change is small enough that it's not needed!

**Comment by josegonzalez** [comment]
Mind filing a PR anyways? I'm not at a computer so I can't create it myself but if you do it now, we can start the (rather lengthy) build time now while I'm traveling and hopefully skip a few steps?

**Comment by jamesremuscat** [comment]
Sure, I'll do so now.
