### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by kbuilds** [dokku/dokku#5562]
### Description of problem

I have a specific Dokku app which I use to catch all HTTP traffic to my server. This is what I would refer to as my "default app". On this same server, there are other deployed Dokku apps, each of which has one or more domain assigned to it. All HTTP requests which to not match any of the domains assigned to any of my running apps should end up hitting the "default app".

This is covered in the documentation here:

https://dokku.com/docs/networking/proxies/nginx/#default-site

It says:

>By default, Dokku will route any received request with an unknown HOST header value to the lexicographically first site in the nginx config stack.

However, this was not what actually happened. It looks like on a fresh install of Dokku on Ubuntu 20.04, nginx comes with a `default` site which is enabled under `/etc/nginx/sites-enabled/`, and which displays the "Welcome to Nginx" page. Once I removed the `default` symlink from that directory, and restarted nginx, everything worked as expected, with the default site (which is the lexicographically first site) handling all unknown hosts.

I would recommend mentioning this in this section of the docs. I am happy to make this change myself and submit a PR.

### Steps to reproduce

Install Dokku on Ubuntu 20.04.

Deploy two apps named:

- `0-app-1`
- `app-2`

Assign a domain to each app:

`dokku domains:add 0-app-1 app1.mydomain.com`
`dokku domains:add app-2 app2.mydomain.com`

Verify that traffic is being routed to the proper apps when you visit their respective domains.

Point the domain `app3.mydomain.com` to the same server, then visit that domain in a browser or send it a curl.

I would expect that the contents of `0-app-1` would be returned, since there is no app which as the domain `app3.mydomain.com`, but it returns the "Welcome to nginx" page, which is provided by the "default" site in `/etc/nginx/sites-enabled/`.

Remove the `default` symlink from `/etc/nginx/sites-enabled/`, and restart nginx with:

`service nginx restart`

Visit `app3.mydomain.com`, and receive the contents of `0-app-1`

### dokku report $APP_NAME

If this is necessary for this specific issue, please let me know, and I will provide it.

**Comment by josegonzalez** [comment]
PR to the docs welcome :)

**Comment by kbuilds** [comment]
@josegonzalez I swear to god, you are the most responsive maintainer on GH

I created a PR. Let me know if there is anything else I can do.

**Comment by josegonzalez** [comment]
Closing as there is an open pull request. Thanks for making that happen!
