### ISSUE TITLE
Can't open the dokku installer - always nginx

### ISSUE THREAD

**Issue by inveders** [dokku/dokku#5583]
### Description of problem

Hi,
I've been trying to install Dokku for several days, and I'm starting to give up. I installed Ubuntu on VirtualBox and I had a problem with the nginx (I couldn't go into the installer). Then I saw that Vagrant was possible and I did the installation from the terminal of my Mac, everything goes fine during the installation, but when I try to go into dokku.me, I have a nginx that shows up.
What would be wrong with my installations? I don't understand....

### Steps to reproduce

I don't know how you could reproduce that, just follow vagrant steps from dokku documentation

### dokku report $APP_NAME

Nothing

**Comment by josegonzalez** [comment]
There is no more web installer. That nginx config is just the default nginx.conf file.

Have you checked step 5+ in the vagrant docs to see how to connect and finish the installation? https://dokku.com/docs/getting-started/install/vagrant/

**Comment by inveders** [comment]
Yes, I edit the config file with Host dokku.me and  PORT 22. And in step 6 they tell me to copy my ssh key in the dokku installer at http://dokku.me. So I go on my navigator and type dokku.me or localhost or my IP address, and I see nginx or a page that not reached. So if there is no more web installer, how to "connect to the server"?

**Comment by josegonzalez** [comment]
> Connect to the server and add your ssh key to the install. Additionally, set the global domain name to dokku.me.

By `connect to the server`, we mean `vagrant ssh`. I guess that can be updated in the docs to be more clear?

**Comment by josegonzalez** [comment]
I wonder if we should also put a warning on why the default nginx site might load and how to remove it...

**Comment by inveders** [comment]
Oh yes for beginner like me it could be useful :) Thanks you

**Comment by josegonzalez** [comment]
Mind making a PR to the docs with that change? I'm not near a computer I can make this change on till later :)

**Comment by josegonzalez** [comment]
Okay, the default site is noted in the docs now as well :)
