### ISSUE TITLE
I want to destroy all apps

### ISSUE THREAD

**Issue by alexgleason** [dokku/dokku#5597]
### Description of feature

I have a Dokku node used for review apps. I'm lazy and didn't configure the CI correctly to shut down after branches get merged. So I have to go in manually and remove all the apps when it runs out of resources.

Best way I've found to do that is like this:

```
for app in $(dokku apps:list); do dokku --force apps:destroy $app; done
```

However, this leaves behind dangling extensions as well, so I also have to run:

```
for app in $(dokku postgres:list); do dokku --force postgres:destroy $app; done
for app in $(dokku redis:list); do dokku --force redis:destroy $app; done
```

I would like a nuclear "destroy absolutely everything" option.

**Comment by josegonzalez** [comment]
The datastores aren't apps, so idk that it would be included.

Why not just destroy the server and reinstall.

**Comment by josegonzalez** [comment]
I've thought about this for a bit and have decided against it. There isn't a great way to hook into every service plugin out there - folks might build their own - and I think the possibility of someone nuking their stuff by accident is very high, so for now I'll just leave this manual.
