### ISSUE TITLE
installation failed, uninstalling fails no matter what I do

### ISSUE THREAD

**Issue by Bounceysteve99** [dokku/dokku#5607]
# Description of problem
I have tried installing dokku on the server a couple of minutes ago, but I made a mistake in the configuration so I wanted to uninstall it.
I've been trying to uninstall dokku and reinstall it for a while, but I've had no luck.
I tried doing apt purge on dokku, dokker, etc. Still no luck.
Whenever I try uninstalling it, apt errors with 

````
Processing remove
 !     `cleanup` is not a dokku command.
 !     See `dokku help` for a list of available commands.
dpkg: error processing package dokku (--remove):
 installed dokku package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Errors were encountered while processing:
 dokku
````

I have tried removing everything I can manually, again, still no luck.

**Comment by josegonzalez** [comment]
I think it's looking for the `cleanup` command in a plugin and that no longer exists. How did you initially try to uninstall?

**Comment by Bounceysteve99** [comment]
I've been uninstalling through apt purge throughout the whole thing

**Comment by josegonzalez** [comment]
To be quite honest I havent exercised the purge process in a while, and we should probably add a unit test for it.

This is what is being called: https://github.com/dokku/dokku/blob/be01d2f7ec9903b6d0a96b1a0693c23cb82cb4ad/debian/prerm#L53

You could probably replace the contents of `/usr/bin/dokku` with `true` and a purge should work.

**Comment by Bounceysteve99** [comment]
I'm currently troubleshooting some other issues relating to the server, but was my initial message:
Now it's giving me `/var/lib/dpkg/info/dokku.prerm: line 53: /usr/bin/dokku: Permission denied`

**Comment by josegonzalez** [comment]
What are the permissions on that file? Run `ls -lah /usr/bin/dokku` to print them out.

**Comment by Bounceysteve99** [comment]
-rwxr-xr-x 1 ubuntu ubuntu 5
> What are the permissions on that file? Run `ls -lah /usr/bin/dokku` to print them out.

**Comment by josegonzalez** [comment]
You might need to change them to `root:root`. Here is what I have:

```
-rwxr-xr-x 1 root root 7.8K Jan 12 22:58 /usr/bin/dokku
```

**Comment by Bounceysteve99** [comment]
Re-installation worked!
I'll try doing the cleanup commands so I can finally cleanly install dokku.
> You might need to change them to `root:root`. Here is what I have:
> 
> ```
> -rwxr-xr-x 1 root root 7.8K Jan 12 22:58 /usr/bin/dokku
> ```
