### ISSUE TITLE
Support for github push webhooks

### ISSUE THREAD

**Issue by gufoe** [dokku/dokku#5623]
### Description of feature

Hello, I love this project but I'm relly not finding something that seems really basic.
Github can ping an HTTP endpoint when a push/merge is going on, and I'd like to trigger the `dokku git:sync --build` command every time I push to my repository.
I imagine it could have a UI as simple as
`dokku git:deploy-webhook appname` 
which could give a url like
`http://appname.myserver.com/.dokku/secret-deploy-token`
This would make push-to-deply as easy as it can be. I know there are github actions but this is a bit more invasive and is just for github, while a webhook is a generic solution that works with any repository manager that has webhooks.

**Comment by josegonzalez** [comment]
Dokku OSS does not support this functionality and will not - it is not meant to run any persistent daemons, and definitely not anything that exposes an http process. Folks can build that on their own if they like.

Our [CI integration](https://dokku.com/docs/deployment/continuous-integration/generic/) supports a number of CI services, and supports our [CircleCI](https://github.com/dokku/dokku-orb), [Github](https://github.com/dokku/github-action),  and [Gitlab](https://github.com/dokku/gitlab-ci) integrations. Its also generic enough to support any other CI solution.

For anyone that _requires_ an HTTP endpoint for deploys, please investigate Dokku Pro. The next release - dropping in the coming weeks - will have exactly this functionality.

Closing as I won't be working on this in Dokku OSS (but others are free to do so as a community project).
