### ISSUE TITLE
Official docker installation notes don't seem to work

### ISSUE THREAD

**Issue by epetre** [dokku/dokku#5624]
### Description of problem

Following the [official guide for a setup on Docker ](https://dokku.com/docs/getting-started/install/docker/) on my local OSX, it runs without errors, but nothing is available after starting.

![image](https://user-images.githubusercontent.com/1010282/216633286-e6aabb89-5faa-4474-b171-d8f7f44265f3.png)

Nothing is showing up when trying to access 
http://localhost:8080/
http://[localip]:8080/
http://0.0.0.0:8080/

![image](https://user-images.githubusercontent.com/1010282/216633531-e39e28a7-bf9b-4bf0-b706-8202e7039163.png)

I'm thinking there is either something I'm missing or misunderstanding or something that isn't clear.... maybe both?
Note: I also tried this on a Linode that runs Ubuntu 20.04 with the same results, but from my understanding it shouldn't matter since we are running it in a container.

## More details

The logs inside the container:
```
2023-02-03 09:31:58 *** Running /etc/my_init.d/10_dokku_init...
2023-02-03 09:31:59 *** Running /etc/my_init.d/15_regen_ssh_host_keys...
2023-02-03 09:31:59 *** Booting runit daemon...
2023-02-03 09:31:59 *** Runit started as PID 60
2023-02-03 09:37:36 *** Running /etc/my_init.d/10_dokku_init...
2023-02-03 09:37:36 *** Running /etc/my_init.d/15_regen_ssh_host_keys...
2023-02-03 09:37:36 *** Booting runit daemon...
2023-02-03 09:37:36 *** Runit started as PID 60
2023-02-03 09:31:59 -----> Set dokku.me
2023-02-03 09:37:36 -----> Set dokku.me
```

### Steps to reproduce

 [official guide for a setup on Docker ](https://dokku.com/docs/getting-started/install/docker/)

## Step 1
`docker pull dokku/dokku:0.29.4`

## Step 2
```
docker container run \                                   
  --env DOKKU_HOSTNAME=dokku.me \
  --env DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku \
  --name dokku \
  --publish 3022:22 \
  --publish 8080:80 \
  --publish 8443:443 \
  --volume /var/lib/dokku:/mnt/dokku \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  dokku/dokku:0.29.4
```
## Step 3
Check browser at port 8080, nothing shows up.

### dokku report $APP_NAME

I don't have an app yet, it's basically an issue with the original setup.

### Additional information

I don't have an app yet, it's basically an issue with the original setup.

### Output of failing commands after running: dokku trace:off

```shell
No failing command.
http://localhost:8080/ just doesn't respond.
```

### Output of failing commands after running: dokku trace:on

```shell
No failing command.
http://localhost:8080/ just doesn't respond.
```

**Comment by josegonzalez** [comment]
There is no default site so nothing will load if you have no apps setup. You'll want to deploy something for that request to have any content.

**Comment by epetre** [comment]
Thank you for the quick reply.
I went through the Getting Started documentation and never understood this part.

Even when doing that and following the next step, https://dokku.com/docs/deployment/application-deployment/
`git remote add dokku dokku@localhost:ruby-getting-started`
and then pushing
`git push dokku master`

It generates the error
```
ssh: connect to host localhost port 22: Connection refused
fatal: Could not read from remote repository.
```

It looks like :
1. It wants to connect to port 22 and the docker port is 3022
2. Even if I could force that port to be 3022, [maybe this is a required step?](https://dokku.com/docs/deployment/user-management/)
If I do this step, `dokku ssh-keys:add KEY_NAME path/to/id_rsa.pub`, we are in a container, path/to/id_rsa.pub would be a path outside the container? Wouldn't we need to copy the public key to the container first or just copy and paste in in there?

Sorry if I'm missing the obvious flow here, but I'm just trying to go through the basics in order to play with the actual features.

**Comment by josegonzalez** [comment]
Did you check the `Pushing Applications` section of the docker installation notes? It shows what the remote should be when you push. If you set the remote as just `localhost`, that assumes port 22, so you'll need to specify port `3022` somehow (which that section shows how to do).

Adding an ssh key is also important, and that is linked to on that same Docker Installation Notes page under the section `SSH Key Management`. You'll need to get your key into the container somehow (I normally do something like `echo "$PUBLIC_KEY" | dokku ssh-keys:add $KEY_NAME`), which is more or less the same as when you'd install on a normal server.

**Comment by epetre** [comment]
Thank you for clarifying this, but I already tried.
Just to clarify, the host of the container is also my main dev machine.

### 1
~/.ssh/config of the host has this:
```
Host dokku.docker
  HostName 127.0.0.1
 Port 3022
```

### 2
in the host,  I copied my key.
`cat ~/.ssh/id_rsa.pub`
Pasted it in the container, in a variable `KEY=xyzpubkey` then added it
`echo $KEY | dokku ssh-keys:add admin`
It all worked and got a SHA256xyz confirmation.


### 3
```
git remote add dokku dokku@dokku.me:ruby-getting-started
git push dokku master
```
*master is my main branch there

Gives me this error:
```
ssh: connect to host dokku.me port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm really just following the basic recommendations here, even tried to restart the container once the basic steps were done.
Most examples out there don't Don't use docker so I'm not sure if the documentation is up to date maybe?

**Comment by josegonzalez** [comment]
The remote should match the Host in your ssh config. Sorry that's not clear - I can change the ssh config example later tonight.

That said, dokku.me is a placeholder and likely won't resolve to your containers IP - the dns entry for it is 10.0.0.2. Please keep that in mind when making requests to your container - you'll need to either set an etc hosts entry or point a domain at that ip as appropriate.

**Comment by epetre** [comment]
Got it, it makes sense, thank you!
