### ISSUE TITLE
Redeploy same commit to dokku

### ISSUE THREAD

**Issue by robianmcd** [dokku/dokku#563]
Is there a way to redeploy a commit to dokku? When I try and push the same commit a second time it just says "Everything up-to-date". I installed some new plugins and would like to try restarting my server.

any ideas?

Thanks!

**Comment by cesarvarela** [comment]
This isn't working anymore right?

Any other option?

**Comment by michaelshobbs** [comment]
docs: http://dokku.viewdocs.io/dokku/deployment/process-management/#process-and-container-management
```
dokku ps:restart <app>
```
```
dokku ps:rebuild <app>
```
```
git commit --allow-empty -m 'empty commit'
git push dokku <app> # or whatever syntax you use to push
```

also, asking questions on a 2+ year old closed issue generally isn't the best way to get help. worked out this time though. 

locking this issue
