### ISSUE TITLE
Update debian installation docs to also refer to debian in addition to ubuntu

### ISSUE THREAD

**Issue by pinkfrog9** [dokku/dokku#5644]
### Description of problem

Missing docs on installation on Debian.  

### Steps to reproduce

see
https://dokku.com/docs/getting-started/install/debian/

This page discusses ubuntu instead of Debian.

### dokku report $APP_NAME

NA

**Comment by josegonzalez** [comment]
I think we want to add buster and bullseye to the mix, and also detect the release via `lsb_release -is` (with some way to downcase it).

**Comment by josegonzalez** [comment]
Closed by #5658.
