### ISSUE TITLE
how to re-enable `git push` deploy after initializing an app with `git:from-image`?

### ISSUE THREAD

**Issue by Quantisan** [dokku/dokku#5662]
## Description of problem

we have an app that starts off with a Docker image, which we `dokku git:from-image` to get it running. But later we want to push changes directly from our local git repo, i.e. `git push` deploy.

I managed to have it working with `dokku git:sync`. Subsequent `git push` from localhost works. The problem is that running `git:sync` requires giving dokku server access to our github repo. I'm wondering is there a way to get `git push` to work directly that I might have missed?

we're on `dokku version 0.29.4`

### Steps to Reproduce

1.
2.
3.

#### Expected Results

<-- Please replace APP_NAME with the name of your app -->

### `dokku report APP_NAME` output

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> In these cases, you may run `dokku report` without any arguments to display the top-level reporting information.

### Additional information

- Container Inspect Output (if applicable) via `dokku ps:inspect APP_NAME`
- The nginx configuration (if applicable) via `dokku nginx:show-config APP_NAME`
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace:on`
  (BEWARE: `trace:on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXX):

**Comment by josegonzalez** [comment]
The `git:from-image` command creates a repository to contain the image name in a Dockerfile and builds from there. You can either force-push onto the `master` branch to overwrite the code we build from or you can pull the repository down, commit your changes on top, then push again.

**Comment by Quantisan** [comment]
thanks for your quick response. here's what worked for me for future ref.

on the dokku server:

```
sudo -u dokku git config --global receive.denyCurrentBranch ignore
```

on localhost repo:

```
git push -f <remote> <branch>:master
```

**Comment by josegonzalez** [comment]
We already set `receive.denyCurrentBranch` on remote bare directories: https://github.com/dokku/dokku/blob/2a6e42a79cd87def7bd4e8bad6babd6c5ad66462/plugins/git/internal-functions#L541

**Comment by Quantisan** [comment]
hmm... I was getting the `receive.denyCurrentBranch` error which prevented me from force pushing. Is this line ran if the app is created fresh from a docker image (i.e. `git:from-image`)?

**Comment by josegonzalez** [comment]
It should be, as its triggered by the following chain:

git:from-image cmd => trigger git-from-image => trigger git-from-directory => git_receive_app => git_build  => git_build_app_repo => fn-git-setup-build-dir

**Comment by Quantisan** [comment]
seems like `receive.denyCurrentBranch` is only set when called from `fn-git-setup-build-dir-new()`. But for newer git version, the `-old()` version is called, which doesn't set `receive.denyCurrentBranch`. https://github.com/dokku/dokku/blob/2a6e42a79cd87def7bd4e8bad6babd6c5ad66462/plugins/git/internal-functions#L514

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
