### ISSUE TITLE
Regression in plugin dokku-redirect after update to dokku 0.30.0

### ISSUE THREAD

**Issue by trival** [dokku/dokku#5685]
### Description of problem

The plugin https://github.com/dokku/dokku-redirect stopped working after updating to dokku 0.30.0, and fails all builds or app starts using nginx proxy

The error happens while creating nginx.conf:

```
-----> Creating http nginx.conf
remote: /var/lib/dokku/plugins/enabled/redirect/nginx-pre-reload: line 7: /var/lib/dokku/plugins/available/proxy/functions: No such file or directory
```

Few more details in issue https://github.com/dokku/dokku-redirect/issues/32. 

I am cross-posting this here, because potentially other plugins might be affected as well. So far the issue seams to be with dokku-redirect. 

### Steps to reproduce

See https://github.com/dokku/dokku-redirect/issues/32. 

### dokku report $APP_NAME

See https://github.com/dokku/dokku-redirect/issues/32.

**Comment by josegonzalez** [comment]
Closing as you've already opened a bug in that plugin.

**Comment by josegonzalez** [comment]
Note: the file was removed as part of the release and noted in the migration docs. It isn't a regression in Dokku, and if it broke non-core plugins (official or otherwise) issues should be filed with those plugins, not here.

**Comment by trival** [comment]
fair enough! And thanks for the quick fix! Was just worried since the impact was pretty severe. All apps on the updated dokku instance where affected and broken, not only the ones using the plugin directly. Even after reading the migration guide this was hard to anticipate. I just thought maybe there would be a quick way to grep the source of other official plugins to see if the removed files were still sourced somewhere else, just in case... Otherwise congratulations to another great and feature packed release!
