### ISSUE TITLE
Original docker image is deleted after ps:rebuild

### ISSUE THREAD

**Issue by tribela** [dokku/dokku#5702]
### Description of problem

Original docker image is deleted after dokku ps:rebuild
version: 0.30.0+

### Steps to reproduce

1. Set docker image `dokku git:from-image <app> <image name>`
2. docker pull <image name>
3. dokku ps:rebuild <app>
4. wait for 2~3 minutes
5. Original docker image is removed after old containers removed

### dokku report $APP_NAME

.

### Additional information

.

### Output of failing commands after running: dokku trace:off

```shell
.
```

### Output of failing commands after running: dokku trace:on

```shell
.
```

**Comment by josegonzalez** [comment]
@tribela please include all the requested information asked for in the issue template.

**Comment by josegonzalez** [comment]
@tribela can you add the data I requested from the issue template? Specifically, some of the information I'm looking for comes in the report output.

Additionally, what are you running `docker pull` with, argument-wise?

**Comment by josegonzalez** [comment]
It took me a bit to figure out based on the instructions, but the above should fix the issue. I've tested it locally.

**Comment by josegonzalez** [comment]
Closing as there is an MR open.
