### ISSUE TITLE
Installation fails on ARM32 

### ISSUE THREAD

**Issue by louwers** [dokku/dokku#5720]
### Description of problem

Installation on Raspberry Pi, ARM32, fails.

According to the website it is supported:

> ARMV7 (alternatively known as armhf), commonly used for Raspberry PI

But there seem to be problems with the `plugn` binary, presumably because it is not compiled for ARM32.

```
--> Running post-install dependency installation
/var/lib/dokku/plugins/enabled/plugin/subcommands/install-dependencies: line 14: /usr/local/bin/plugn: cannot execute binary file: Exec format error
```

### Steps to reproduce

Install Dokku on Raspberry Pi with

```
sudo DOKKU_BRANCH=master bash bootstrap.sh
```

Or with 

```
sudo DOKKU_TAG=v0.30.1 bash bootstrap.sh
```

I patched bootstrap.sh:

```
install-dokku-from-package() {
  echo $DOKKU_DISTRO
  case "$DOKKU_DISTRO" in
    debian | ubuntu | raspbian)
```

to try this

### dokku report $APP_NAME

N/A

**Comment by louwers** [comment]
Interesting, the armf version seems to be installed:

```
apt list --installed | grep plugn

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

plugn/bullseye,now 0.12.0 armhf [installed,automatic]
```

**Comment by louwers** [comment]
```
file /usr/local/bin/plugn
/usr/local/bin/plugn: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=uAeWibrym1f8SMEdH1Tu/JRnA01KWwSLHzbtOaOqW/hQNwWLzUKpt5z2MJsxGm/E_V-TC-o8O9oYwpueoZp, stripped
```

**Comment by louwers** [comment]
Should have RTFM and use the Advanced Installation I guess.

**Comment by josegonzalez** [comment]
Ah if you install via the bootstrap script and set DOKKU_BRANCH=master, it'll be a source install. The source-based install currently uses the make commands and doesn't quite work for arm because it hardcodes the x86-64 files.
