### ISSUE TITLE
plugins are unusable and not working at all

### ISSUE THREAD

**Issue by maciejopalinski** [dokku/dokku#5739]
### Description of problem

Plugins are not persisted in the docker volume.

### Steps to reproduce

1. `docker run --env DOKKU_HOSTNAME=localhost --env DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku --name dokku -p 3022:22 -p 8080:80 -p 8443:443 -v /var/lib/dokku:/mnt/dokku -v /var/run/docker.sock:/var/run/docker.sock dokku/dokku:latest`
2. `docker exec dokku dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres`
3. `docker exec dokku dokku postgres` (displays help from postgres plugin)
4. `docker rm dokku`
5. repeat step 1.
6. repeat step 3. (plugin postgres does not exist)

### dokku report $APP_NAME

n/a

### Additional information

This is once again related to the unsolved issue with linking directories described in #5614, #5468, #5606. Plugins still don't work and crash because their configs are not visible in a volume on a host system. Please don't close my issues as this project is not usable with any plugins.

**Comment by josegonzalez** [comment]
The problem you are describing now is not the same as the one in the other issues (those were for the underlying data being missing, this one is for the plugin code not persisting across server restarts).

I think this is working as expected due to how the container bootstraps it's internal /var/lib/dokku directory (we rsync the plugins into place on boot). If you want the installed plugin to be persistent across recreations of the dokku container, you have two options:

- Use the documented method  for handling [plugin installation](https://dokku.com/docs/getting-started/install/docker/#plugin-installation) on docker installations via a plugin-list file
- Create a custom Dockerfile that installs your desired plugins out of the box and start your image based on that

**Comment by maciejopalinski** [comment]
> The problem you are describing now is not the same as the one in the other issues (those were for the underlying data being missing, this one is for the plugin code not persisting across server restarts).
> 
> I think this is working as expected due to how the container bootstraps it's internal /var/lib/dokku directory (we rsync the plugins into place on boot). If you want the installed plugin to be persistent across recreations of the dokku container, you have two options:
> 
> - Use the documented method  for handling [plugin installation](https://dokku.com/docs/getting-started/install/docker/#plugin-installation) on docker installations via a plugin-list file
> - Create a custom Dockerfile that installs your desired plugins out of the box and start your image based on that

Ok, I get it now, so it is the intended behavior... And what about the other issue that still persists?

**Comment by josegonzalez** [comment]
What other issue that still persists? I'm currently able to:

- start a 0.30.1 container as shown in the docs
- install the postgres plugin
- create a test postgres instance
- stop and then rm the dokku container
- restart the dokku container with the same command as shown in the docs
- enter the container and reinstall the postgres plugin (or install via plugin-list)
- list postgres dbs and see the test server
- check the postgres:info output on the test db

If you are referencing the issue regarding symlinking the services directory, are you sure you're running Dokku 0.30.1 and not an older version by accident? Running `latest` won't pull the latest image unless you force pull it.

**Comment by maciejopalinski** [comment]
> What other issue that still persists? I'm currently able to:
> 
> * start a 0.30.1 container as shown in the docs
> * install the postgres plugin
> * create a test postgres instance
> * stop and then rm the dokku container
> * restart the dokku container with the same command as shown in the docs
> * enter the container and reinstall the postgres plugin (or install via plugin-list)
> * list postgres dbs and see the test server
> * check the postgres:info output on the test db
> 
> If you are referencing the issue regarding symlinking the services directory, are you sure you're running Dokku 0.30.1 and not an older version by accident? Running `latest` won't pull the latest image unless you force pull it.

I still can't get redis to work. It requires a config, but it is not getting mirrored on a host filesystem.

`docker exec -it dokku dokku redis:create redis-test`
```
=====> Start of redis-test container output
       1:C 15 Mar 2023 07:44:18.322 # Fatal error, can't open config file '/usr/local/etc/redis/redis.conf': No such file or directory
       1:C 15 Mar 2023 07:44:19.052 # Fatal error, can't open config file '/usr/local/etc/redis/redis.conf': No such file or directory
```

**Comment by maciejopalinski** [comment]
Here is the issue: https://github.com/dokku/dokku-redis/issues/185

**Comment by josegonzalez** [comment]
I can replicate that but I can also fix it by specifying the following flag on the `docker run` command:

```
--env DOKKU_LIB_HOST_ROOT=/var/lib/dokku/var/lib/dokku
```

I'll update the docs and close this ticket. If a particular plugin does not work, please file a ticket in that plugin, and if someone has time to look, they will investigate.

**Comment by vedmaka** [comment]
I think there is still something wrong with in-docker setup as plugins being re-installed every time container starts, in addition, the letsencrypt plugin tries to access `/var/lib/dokku/home/dokku/ruby-getting-started` and `/var/lib/dokku/home` does not exist on the container filesystem and is not mounted from the host

**Comment by josegonzalez** [comment]
@vedmaka this issue was closed 2 years ago. Can you please open a new ticket with a description of what you are seeing and what you are expecting to happen?
