### ISSUE TITLE
Procfile is not getting recognized during deployment

### ISSUE THREAD

**Issue by railsfactory-umar** [dokku/dokku#5747]
### Description of problem

we have a rails application and use Procfile to differentiate commands for web and sidekiq containers. It has been working fine until we update dokku version to the latest(0.30). Now the containers are using command mentioned in Dockerfile and getting launched with same command for both web and sidekiq.

### Steps to reproduce

create a procfile with containers and its correspoding commands like below
```
web: bundle exec rails server -b 0.0.0.0
worker: bundle exec sidekiq
release: bundle exec rails db:migrate
```

### dokku report $APP_NAME

#Seems like it does not need report of the app
![image](https://user-images.githubusercontent.com/86765605/225639982-301c81e6-2b3d-4e5a-bb40-e9950ae8c23a.png)

### Additional information
<img width="586" alt="Screenshot 2023-03-16 at 19 08 40" src="https://user-images.githubusercontent.com/86765605/225635399-7f9238a0-15e4-4b4c-87c0-92bd264d5f96.png">

**Comment by railsfactory-umar** [comment]
@josegonzalez Sorry man. I work in a private company. I cant post all of the details here. It will be a security breach. Lemme post the deployment log here 
![image](https://user-images.githubusercontent.com/86765605/225695474-f5acc2ea-c49b-42ae-8ca2-79734d89242f.png)

**Comment by josegonzalez** [comment]
How do you know the worker is starting the web process?

**Comment by railsfactory-umar** [comment]
Kindly refer to the image below for the commands being same for both worker and web containers. But I have given different in procfile. This command is coming from dockerfile
![image](https://user-images.githubusercontent.com/86765605/225747517-4cd42b54-103c-4050-b1fe-431ee45fd9dc.png)

**Comment by josegonzalez** [comment]
Can I see your Dockerfile?

**Comment by railsfactory-umar** [comment]
Here it is,

-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:            3923        1383         539           0        2001        2253
       Swap:            511          87         424
-----> docker version:
       Client: Docker Engine - Community
        Version:           23.0.1
        API version:       1.42
        Go version:        go1.19.5
        Git commit:        a5ee5b1
        Built:             Thu Feb  9 19:47:01 2023
        OS/Arch:           linux/amd64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          23.0.1
         API version:      1.42 (minimum version 1.12)
         Go version:       go1.19.5
         Git commit:       bc3805a
         Built:            Thu Feb  9 19:47:01 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.18
         GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
        runc:
         Version:          1.1.4
         GitCommit:        v1.1.4-0-g5fd4c4d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.10.2
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.16.0
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
         scan: Docker Scan (Docker Inc.)
           Version:  v0.23.0
           Path:     /usr/libexec/docker/cli-plugins/docker-scan

       Server:
        Containers: 6
         Running: 4
         Paused: 0
         Stopped: 2
        Images: 13
        Server Version: 23.0.1
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
        runc version: v1.1.4-0-g5fd4c4d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-67-generic
        Operating System: Ubuntu 22.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.832GiB
        Name: localhost
        ID: 242efce4-a69d-4616-91bc-aa57c98e5a9b
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Experimental: false
        Insecure Registries:
        Live Restore Enabled: false

-----> git version: git version 2.34.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
       herokuish: v0.5.40
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v202
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v223
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v227
         heroku-buildpack-go        v169
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.30.1
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins:
         00_dokku-standard    0.30.1 enabled    dokku core standard plugin
         20_events            0.30.1 enabled    dokku core events logging plugin
         app-json             0.30.1 enabled    dokku core app-json plugin
         apps                 0.30.1 enabled    dokku core apps plugin
         builder              0.30.1 enabled    dokku core builder plugin
         builder-dockerfile   0.30.1 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.1 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.1 enabled    dokku core builder-lambda plugin
         builder-null         0.30.1 enabled    dokku core builder-null plugin
         builder-pack         0.30.1 enabled    dokku core builder-pack plugin
         buildpacks           0.30.1 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.1 enabled    dokku core caddy-vhosts plugin
         certs                0.30.1 enabled    dokku core certificate management plugin
         checks               0.30.1 enabled    dokku core checks plugin
         common               0.30.1 enabled    dokku core common plugin
         config               0.30.1 enabled    dokku core config plugin
         cron                 0.30.1 enabled    dokku core cron plugin
         docker-options       0.30.1 enabled    dokku core docker-options plugin
         domains              0.30.1 enabled    dokku core domains plugin
         enter                0.30.1 enabled    dokku core enter plugin
         git                  0.30.1 enabled    dokku core git plugin
         haproxy-vhosts       0.30.1 enabled    dokku core haproxy-vhosts plugin
         http-auth            0.10.0 enabled    HTTP authentication for apps
         letsencrypt          0.20.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.30.1 enabled    dokku core logs plugin
         network              0.30.1 enabled    dokku core network plugin
         nginx-vhosts         0.30.1 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.1 enabled    dokku core plugin plugin
         proxy                0.30.1 enabled    dokku core proxy plugin
         ps                   0.30.1 enabled    dokku core ps plugin
         redis                1.32.0 enabled    dokku redis service plugin
         registry             0.30.1 enabled    dokku core registry plugin
         repo                 0.30.1 enabled    dokku core repo plugin
         resource             0.30.1 enabled    dokku core resource plugin
         run                  0.30.1 enabled    dokku core run plugin
         scheduler            0.30.1 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.1 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.30.1 enabled    dokku core scheduler-null plugin
         shell                0.30.1 enabled    dokku core shell plugin
         ssh-keys             0.30.1 enabled    dokku core ssh-keys plugin
         storage              0.30.1 enabled    dokku core storage plugin
         trace                0.30.1 enabled    dokku core trace plugin
         traefik-vhosts       0.30.1 enabled    dokku core traefik-vhosts plugin
=====> foo-dev app-json information
       App json computed selected:    cron-dev.json
       App json global selected:      app.json
       App json selected:             cron-dev.json
=====> foo-dev app information
       App created at:                1678432002
       App deploy source:             foo-dev
       App deploy source metadata:    foo-dev
       App dir:                       /home/dokku/foo-dev
       App locked:                    false
=====> foo-dev builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:     dockerfile
       Builder global build dir:
       Builder global selected:
       Builder selected:              dockerfile
=====> foo-dev builder-dockerfile information
       Builder dockerfile computed dockerfile path: foo/Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path: foo/Dockerfile
=====> foo-dev builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> foo-dev builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> foo-dev buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> foo-dev ssl information
       Ssl dir:                       /home/dokku/foo-dev/tls
       Ssl enabled:                   true
       Ssl hostnames:                 foo
       Ssl expires at:                Jun 14 07:04:40 2023 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Mar 16 07:04:41 2023 GMT
       Ssl subject:                   subject=CN = foo
       Ssl verified:                  self signed
=====> foo-dev checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> foo-dev cron information
       Cron task count:               0
=====> foo-dev docker options information
       Docker options build:          --link dokku.redis.redis-dev:dokku-redis-redis-dev
       Docker options deploy:         --link dokku.redis.redis-dev:dokku-redis-redis-dev --restart=on-failure:10
       Docker options run:            --link dokku.redis.redis-dev:dokku-redis-redis-dev
=====> foo-dev domains information
       Domains app enabled:           true
       Domains app vhosts:            foo 
       Domains global enabled:        true
       Domains global vhosts:         foo
=====> foo-dev git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       
       Git source image:
       Git last updated at:           1678951891
=====> foo-dev http-auth information
       Http auth enabled:             false
       Http auth allowed ips:
       Http auth users:               cm-Admin
=====> foo-dev letsencrypt information
       Letsencrypt active:            true
       Letsencrypt autorenew:         false
       Letsencrypt computed dns provider:
       Letsencrypt global dns provider:
       Letsencrypt dns provider:
       Letsencrypt computed email:    foo
       Letsencrypt global email:
       Letsencrypt email:            foo
       Letsencrypt expiration:        1686726280
       Letsencrypt computed graceperiod: 2592000
       Letsencrypt global graceperiod:
       Letsencrypt graceperiod:
       Letsencrypt computed lego docker args:
       Letsencrypt global lego docker args:
       Letsencrypt lego docker args:
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:
       Letsencrypt server:
=====> foo-dev logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> foo-dev network information
       Network attach post create:           dev
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:  dev
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.3:3000
=====> foo-dev nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/foo-dev-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:    200M
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/foo-dev-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      900s
       Nginx last visited at:         1678998574
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> foo-dev proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:3000 https:443:3000
       Proxy type:                    nginx
=====> foo-dev ps information
       Deployed:                      true
       Processes:                     2
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 891060d4d23)
       Status worker 1:               running (CID: 7540891ddb1)
=====> foo-dev registry information
       Registry computed image repo:      dokku/foo-dev
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> foo-dev resource information
=====> foo-dev scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> foo-dev scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> foo-dev storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

**Comment by railsfactory-umar** [comment]
Here is the dockerfile end since I cant post full
<img width="497" alt="image" src="https://user-images.githubusercontent.com/86765605/225752395-ddbca919-baae-4115-9f9c-830d96676bcf.png">

**Comment by josegonzalez** [comment]
Do you have multiple Procfiles in your repo, and are you adding a specific one via the Dockerfile?

**Comment by railsfactory-umar** [comment]
Nope. There is only one.

**Comment by railsfactory-umar** [comment]
<img width="536" alt="Screenshot 2023-03-17 at 02 44 37" src="https://user-images.githubusercontent.com/86765605/225754426-c7c7387a-83fa-467d-82e4-0139c285575a.png">

**Comment by railsfactory-umar** [comment]
Am afraid that  I dont have trace output

**Comment by josegonzalez** [comment]
Ah okay I think I see whats happening.

Your Procfile isn't being picked up because its in a subfolder. We changed file extraction for Procfile in 0.29.x so it gets taken from the repo source. In your case, that means there is no Procfile (since its not at the top-level of the repo) and so you just run the `CMD` from your Dockerfile for all processes.

You probably want to set `procfile-path` to the path of your Procfile so that the deploy picks up the correct file.

**Comment by railsfactory-umar** [comment]
Oh,man. I did not see that coming. Now it is working fine as wine. Thank you so much for your support.
