### ISSUE TITLE
App name as placeholder in sink DSN

### ISSUE THREAD

**Issue by simoheinonen** [dokku/dokku#5752]
### Description of feature

This would be nice so wouldn't need to run the command separately for all my apps: 

```shell
dokku logs:set --global vector-sink 'file://?encoding=text&path=/var/log/dokku/apps/{appname}.log
```

**Comment by josegonzalez** [comment]
I wonder if we should support the full golang text/template engine or just something limited for now, like `{{appname}}`?

**Comment by josegonzalez** [comment]
Seems like you should be able to use the [template syntax](https://vector.dev/docs/reference/configuration/template-syntax/), so you might be able to do something like:

```shell
dokku logs:set --global vector-sink 'file://?encoding=text&path=/var/log/dokku/apps/{{ .labels.com.dokku.app-name }}.log
```

Should work. Mind trying it and reporting back if that works?

**Comment by josegonzalez** [comment]
Yeah I think that syntax should be correct. If not, I'd ask the Vector folks what the syntax is for a label with a dot in it.

Closing as there isn't a need to build anything into Dokku for this.
