### ISSUE TITLE
Use -O in wget args in upgrade documentation

### ISSUE THREAD

**Issue by incidentist** [dokku/dokku#5766]
### Description of problem

I tried upgrading dokku to 30.2 using the upgrade instructions:
```
wget https://dokku.com/install/v0.30.2/bootstrap.sh
sudo DOKKU_TAG=v0.30.2 bash bootstrap.sh
```

But got an error about an unsupported Linux distro. I'm on ubuntu 22.04, and when I load the boostrap script in a browser, I see it is a supported version, but looking at the script on my machine, it is not. It turns out that I forgot that there was an existing`bootstrap.sh` from the last upgrade I did, so the `wget` command downloaded the new script to `bootstrap.sh.1` and I didn't realize it.

This seems like an easy mistake to make. I think the documentation should call wget with the `-O` flag:
```
wget https://dokku.com/install/v0.30.2/bootstrap.sh -O bootstrap.sh
sudo DOKKU_TAG=v0.30.2 bash bootstrap.sh
```

This ensures that the file is downloaded to the expected path.

### Steps to reproduce

```
rm bootstrap.sh && touch bootstrap.sh
wget https://dokku.com/install/v0.30.2/bootstrap.sh
sudo DOKKU_TAG=v0.30.2 bash bootstrap.sh
```

### dokku report $APP_NAME

N/A

**Comment by josegonzalez** [comment]
Where in our docs do we state that the above is the recommended way to upgrade?

**Comment by incidentist** [comment]
Here is where it mentions upgrading via bootstrap.sh: https://github.com/dokku/dokku/releases/tag/v0.30.2

But I now see that the main readme points to an upgrade guide.
