### ISSUE TITLE
Allow dynamically reference environment variables when setting other environment variables

### ISSUE THREAD

**Issue by IgnisDa** [dokku/dokku#5771]
### Description of feature

It would be really useful if a configuration variable could reference another variable. [Here](https://docs.railway.app/develop/variables#reference-variables) is a reference on how Railway does it.

## Examples

1. Simple one:

```sh
dokku config:set myapp LEPTOS_BIND_ADDR='0.0.0.0:${{PORT}}'
```

This would result in the app running with an environment variable `LEPTOS_BIND_ADDR` whose value would be `0.0.0.0:5000` (or whatever port is set in the app's configuration).

2. A real world example

Most application use some kind of struct to hold configuration (which they load from the environment). Taking the example of [figment](https://docs.rs/figment/latest/figment/), here is a simple configuration struct:

```rs
#[derive(Serialize, Deserialize)]
struct DbConfig { conn_url: String };

#[derive(Serialize, Deserialize)]
struct AppConfig { db: DbConfig };

let config: AppConfig = Figment::new().merge(Env::prefixed("APP_").split("__")).extract()?;
```

Now let us say I have linked my postgres database to this app and the `DATABASE_URL` env variable is set. But according to the above code, figment expects the `APP_DB__CONN_URL` environment variable. Currently, we have to handle this discrepancy in the application code, typically via a custom `ENTRYPOINT` which re-exports `DATABASE_URL` as `APP_DB__CONN_URL`.

However, if reference variables are implemented, we can simply do `dokku config:set myapp APP_DB__CONN_URL='${{DATABASE_URL}}'` thus getting rid of having a custom entrypoint.

**Comment by josegonzalez** [comment]
I wonder in what order environment variables should be parsed. Do we keep going until everything is "resolved"? How do we know which to resolve first? What happens if we have cyclic dependencies, or never resolve due to missing environment variables?

**Comment by josegonzalez** [comment]
Do you know of a library that does the sort of parsing of config - in any language - you're looking for here?

**Comment by josegonzalez** [comment]
Going to close this out. There hasn't been any movement and I think the parsing here could become quite tricky. I think either re-aligning code to better use environment variables - DATABASE_URL is pretty common - or using a custom entrypoint - for Dockerfile-based deploys - is best.
