### ISSUE TITLE
Support for adding multiple SSH keys with debconf options

### ISSUE THREAD

**Issue by pawelad** [dokku/dokku#5773]
### Description of feature

Hi!

First of all, thanks for the awesome project.

I'm currently in the process of writing a Terraform and cloud init based setup that provisions dokku. Everything is working well, but I wanted to add two SSH keys (one for me, one for [GitHub Actions](https://github.com/dokku/github-action)) during setup, which I don't think is currently supported.

Specifically, the `debconf` `key_file` setting seems to work with an `authorized_keys` file that contains one SSH keys, but doesn't work when it contains two SSH keys.

Relevant config:

```
...
  debconf_selections:
    key_file: dokku dokku/key_file string /home/${username}/.ssh/authorized_keys
...
```

Relevant log error:

```
...
Setting VHOST contents to pawelad.me
Too many keys provided, set one per invocation of sshcommand acl-add <USER> <NAME>
Deleting invalid plugins
...
```

I'm not sure if dokku _should_ support this (after all, the config value is `key_file` and not `keys_file` or `authorized_keys_file`) , but I thought I might as well ask : )

**Comment by josegonzalez** [comment]
Yeah I don't think we will support this. If you want multiple keys, you should:

- install dokku
- run the `ssh-keys:add` command with your extra key on another name

SSH keys are named, and at install time we only set one to the admin user (and we wouldn't know what to use for the other names).

**Comment by pawelad** [comment]
OK, no worries, thanks for taking the time to consider : )
