### ISSUE TITLE
App not accessible (nginx connect() failed (111: Unknown error))

### ISSUE THREAD

**Issue by polgiron** [dokku/dokku#5778]
### Description of problem

I cannot access my dokku app

### Steps to reproduce

I did install an api app using dokku:

- installed dokku on a freshly created digital ocean droplet (dokku version 0.30.2)
- linked my domain to dokku's droplet IP address
- created and deployed my node js app (NestJS) using git and enabled HTTPS via letsencrypt
- my app is running fine without any error when I run dokku logs MY_APP

When I'm trying to reach my api via its new dokku URL I'm getting a 502 error
When I'm reaching the URL via a browser I'm getting the dokku "We're sorry, but something went wrong" error page

When I check dokku nginx:error-logs MY_APP I'm seeing some connection errors (but Unknown error...):
```
2023/04/03 15:14:50 [error] 95857#95857: *121 connect() failed (111: Unknown error) while connecting to upstream, client: 105.191.17.178, server: photol-api.dokku.paulgiron.com, request: "OPTIONS /image/public HTTP/2.0", upstream: "http://172.17.0.4:5000/image/public", host: "photol-api.dokku.paulgiron.com", referrer: "http://localhost:4200/"
```

### dokku report $APP_NAME

-----> uname: Linux pol-server-dokku 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:            1975         415         643           1         917        1367
       Swap:              0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           23.0.2
        API version:       1.42
        Go version:        go1.19.7
        Git commit:        569dd73
        Built:             Mon Mar 27 16:16:30 2023
        OS/Arch:           linux/amd64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          23.0.2
         API version:      1.42 (minimum version 1.12)
         Go version:       go1.19.7
         Git commit:       219f21b
         Built:            Mon Mar 27 16:16:30 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.20
         GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
        runc:
         Version:          1.1.5
         GitCommit:        v1.1.5-0-gf19387a
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.10.4
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.17.2
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
         scan: Docker Scan (Docker Inc.)
           Version:  v0.23.0
           Path:     /usr/libexec/docker/cli-plugins/docker-scan

       Server:
        Containers: 4
         Running: 2
         Paused: 0
         Stopped: 2
        Images: 15
        Server Version: 23.0.2
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
        runc version: v1.1.5-0-gf19387a
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-67-generic
        Operating System: Ubuntu 22.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 1.929GiB
        Name: pol-server-dokku
        ID: cca06cdf-5470-43a5-8f67-c71cdeb53f93
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.34.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
       herokuish: v0.5.41
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v252
         heroku-buildpack-nodejs    v203
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v226
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v231
         heroku-buildpack-go        v171
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.30.2
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins:
         00_dokku-standard    0.30.2 enabled    dokku core standard plugin
         20_events            0.30.2 enabled    dokku core events logging plugin
         app-json             0.30.2 enabled    dokku core app-json plugin
         apps                 0.30.2 enabled    dokku core apps plugin
         builder              0.30.2 enabled    dokku core builder plugin
         builder-dockerfile   0.30.2 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.2 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.2 enabled    dokku core builder-lambda plugin
         builder-null         0.30.2 enabled    dokku core builder-null plugin
         builder-pack         0.30.2 enabled    dokku core builder-pack plugin
         buildpacks           0.30.2 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.2 enabled    dokku core caddy-vhosts plugin
         certs                0.30.2 enabled    dokku core certificate management plugin
         checks               0.30.2 enabled    dokku core checks plugin
         common               0.30.2 enabled    dokku core common plugin
         config               0.30.2 enabled    dokku core config plugin
         cron                 0.30.2 enabled    dokku core cron plugin
         docker-options       0.30.2 enabled    dokku core docker-options plugin
         domains              0.30.2 enabled    dokku core domains plugin
         enter                0.30.2 enabled    dokku core enter plugin
         git                  0.30.2 enabled    dokku core git plugin
         haproxy-vhosts       0.30.2 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.30.2 enabled    dokku core logs plugin
         mongo                1.33.1 enabled    dokku mongo service plugin
         network              0.30.2 enabled    dokku core network plugin
         nginx-vhosts         0.30.2 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.2 enabled    dokku core plugin plugin
         proxy                0.30.2 enabled    dokku core proxy plugin
         ps                   0.30.2 enabled    dokku core ps plugin
         registry             0.30.2 enabled    dokku core registry plugin
         repo                 0.30.2 enabled    dokku core repo plugin
         resource             0.30.2 enabled    dokku core resource plugin
         run                  0.30.2 enabled    dokku core run plugin
         scheduler            0.30.2 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.2 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.30.2 enabled    dokku core scheduler-null plugin
         shell                0.30.2 enabled    dokku core shell plugin
         ssh-keys             0.30.2 enabled    dokku core ssh-keys plugin
         storage              0.30.2 enabled    dokku core storage plugin
         trace                0.30.2 enabled    dokku core trace plugin
         traefik-vhosts       0.30.2 enabled    dokku core traefik-vhosts plugin
=====> photol-api app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> photol-api app information
       App created at:                1680531859
       App deploy source:             git-push
       App deploy source metadata:    ac297cb704be1a15cacb4b6754e677b287fcd606
       App dir:                       /home/dokku/photol-api
       App locked:                    false
=====> photol-api builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> photol-api builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> photol-api builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> photol-api builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> photol-api buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> photol-api ssl information
       Ssl dir:                       /home/dokku/photol-api/tls
       Ssl enabled:                   true
       Ssl hostnames:                 photol-api.dokku.paulgiron.com
       Ssl expires at:                Jul  2 13:42:25 2023 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Apr  3 13:42:26 2023 GMT
       Ssl subject:                   subject=CN = photol-api.dokku.paulgiron.com
       Ssl verified:                  self signed
=====> photol-api checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> photol-api cron information
       Cron task count:               0
=====> photol-api docker options information
       Docker options build:          --link dokku.mongo.photol-db:dokku-mongo-photol-db
       Docker options deploy:         --link dokku.mongo.photol-db:dokku-mongo-photol-db --restart=on-failure:10
       Docker options run:            --link dokku.mongo.photol-db:dokku-mongo-photol-db
=====> photol-api domains information
       Domains app enabled:           true
       Domains app vhosts:            photol-api.dokku.paulgiron.com
       Domains global enabled:        true
       Domains global vhosts:         dokku.paulgiron.com
=====> photol-api git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       ac297cb
       Git source image:
       Git last updated at:           1680533531
=====> photol-api letsencrypt information
       Letsencrypt active:            true
       Letsencrypt autorenew:         true
       Letsencrypt computed dns provider:
       Letsencrypt global dns provider:
       Letsencrypt dns provider:
       Letsencrypt computed email:    pol.giron@gmail.com
       Letsencrypt global email:      pol.giron@gmail.com
       Letsencrypt email:
       Letsencrypt expiration:        1688305345
       Letsencrypt computed graceperiod: 2592000
       Letsencrypt global graceperiod:
       Letsencrypt graceperiod:
       Letsencrypt computed lego docker args:
       Letsencrypt global lego docker args:
       Letsencrypt lego docker args:
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:
       Letsencrypt server:
=====> photol-api logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> photol-api network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.4:5000
=====> photol-api nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/photol-api-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/photol-api-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1680535504
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> photol-api proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> photol-api ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: eea8b2bf948)
=====> photol-api registry information
       Registry computed image repo:      dokku/photol-api
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> photol-api resource information
=====> photol-api scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> photol-api scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> photol-api storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

### Additional information

------------------------------------------------------------------------------------------------------------
dokku ps:inspect APP_NAME
------------------------------------------------------------------------------------------------------------
```
[
    {
        "AppArmorProfile": "docker-default",
        "Args": [
            "web"
        ],
        "Config": {
            "AttachStderr": true,
            "AttachStdin": false,
            "AttachStdout": true,
            "Cmd": [
                "/start",
                "web"
            ],
            "Domainname": "",
            "Entrypoint": null,
            "Env": [
                "USER=herokuishuser",
                "CURL_CONNECT_TIMEOUT=XXXXXX",
                "CURL_TIMEOUT=XXXXXX",
                "MONGO_URL=XXXXXX",
                "S3_BUCKET=XXXXXX",
                "PORT=5000",
                "DOKKU_APP_TYPE=herokuish",
                "GIT_REV=XXXXXX",
                "PUBLIC_PAGE_EMAIL=XXXXXX",
                "AWS_ACCESS_KEY_ID=XXXXXX",
                "DOKKU_APP_RESTORE=1",
                "DOKKU_PROXY_PORT=80",
                "DOKKU_PROXY_PORT_MAP=http:80:5000 https:443:5000",
                "DOKKU_PROXY_SSL_PORT=443",
                "TOKEN_SECRET=XXXXXX",
                "AWS_SECRET_ACCESS_KEY=XXXXXX",
                "BIG_THUMB_SIZE=XXXXXX",
                "SMALL_THUMB_SIZE=XXXXXX",
                "DYNO=web.1",
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "STACK=XXXXXX",
                "DEBIAN_FRONTEND=XXXXXX"
            ],
            "Hostname": "eea8b2bf9481",
            "Image": "dokku/photol-api:latest",
            "Labels": {
                "com.dokku.app-name": "photol-api",
                "com.dokku.builder-type": "herokuish",
                "com.dokku.container-type": "deploy",
                "com.dokku.dyno": "web.1",
                "com.dokku.image-stage": "release",
                "com.dokku.process-type": "web",
                "com.gliderlabs.herokuish/stack": "heroku-20",
                "dokku": "",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "dokku",
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.version": "20.04"
            },
            "OnBuild": null,
            "OpenStdin": false,
            "StdinOnce": false,
            "Tty": false,
            "User": "",
            "Volumes": null,
            "WorkingDir": ""
        },
        "Created": "2023-04-03T14:51:44.930904141Z",
        "Driver": "overlay2",
        "ExecIDs": null,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/72843a324a46e651a5f0f2c57ac23066811a7da08eb8b3582013e95716591232-init/diff:/var/lib/docker/overlay2/enbsariio79qrakdjzz8uz7zj/diff:/var/lib/docker/overlay2/a66f8cef94f200f21f19605c2a038c746390571c6045d208cd8f81afc5da5679/diff:/var/lib/docker/overlay2/kt5xg5h0980jadxpi3wgbq4sh/diff:/var/lib/docker/overlay2/fn8xvbddbyykqv5c668h3c9jn/diff:/var/lib/docker/overlay2/2ab6954ec21cd8e38cb184841e86457a81437bdaa812b774d23a857e3cd93830/diff:/var/lib/docker/overlay2/026cc2babc162b48ad46229b200b7eec641ed956bf612c22ebc259ef03bc6586/diff:/var/lib/docker/overlay2/bb567bd050a12567978218de4c6bd6c33d267e7b8c97e365809aeaf1d25e97b2/diff:/var/lib/docker/overlay2/0f8ecc23eaa0980daf44b1b25cb0f7d46c91a4829923c8138c9d823d3b3b6b49/diff:/var/lib/docker/overlay2/22ee39f06ede3ea886187804e7f2424787932407ec49fab58b442e693f66d0d6/diff:/var/lib/docker/overlay2/3a101bec137fcb2ae0c149fc9ef90d1ca27fdc947b69933f16a965b05bdfa82c/diff:/var/lib/docker/overlay2/ae16cc959315d722a7497b47fb63d79cdfdec0766e450791e3b0ed0206551598/diff:/var/lib/docker/overlay2/0b2b6dbeae86b69005a981e39e52a006bbf4bf6cfa1501956088e6183c43b50d/diff:/var/lib/docker/overlay2/1b1a1c36ac6d0de78cceb67a2c706eebb47fa7e2a46806519229d06b284bcb7d/diff:/var/lib/docker/overlay2/175a2c2e4c8da372c5a3426775179546e0fa97015f860deac7358fb060aa2a68/diff:/var/lib/docker/overlay2/9da1fda872b91c72526d4d317feff76fdb887b9bbe1de08320f0e226f60df5cc/diff",
                "MergedDir": "/var/lib/docker/overlay2/72843a324a46e651a5f0f2c57ac23066811a7da08eb8b3582013e95716591232/merged",
                "UpperDir": "/var/lib/docker/overlay2/72843a324a46e651a5f0f2c57ac23066811a7da08eb8b3582013e95716591232/diff",
                "WorkDir": "/var/lib/docker/overlay2/72843a324a46e651a5f0f2c57ac23066811a7da08eb8b3582013e95716591232/work"
            },
            "Name": "overlay2"
        },
        "HostConfig": {
            "AutoRemove": false,
            "Binds": null,
            "BlkioDeviceReadBps": [],
            "BlkioDeviceReadIOps": [],
            "BlkioDeviceWriteBps": [],
            "BlkioDeviceWriteIOps": [],
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "CapAdd": null,
            "CapDrop": null,
            "Cgroup": "",
            "CgroupParent": "",
            "CgroupnsMode": "private",
            "ConsoleSize": [
                0,
                0
            ],
            "ContainerIDFile": "",
            "CpuCount": 0,
            "CpuPercent": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpuShares": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "Devices": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IOMaximumBandwidth": 0,
            "IOMaximumIOps": 0,
            "Init": true,
            "IpcMode": "private",
            "Isolation": "",
            "Links": [
                "/dokku.mongo.photol-db:/photol-api.web.1/dokku-mongo-photol-db"
            ],
            "LogConfig": {
                "Config": {
                    "max-size": "10m"
                },
                "Type": "json-file"
            },
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "NanoCpus": 0,
            "NetworkMode": "default",
            "OomKillDisable": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "PidsLimit": null,
            "PortBindings": {},
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "ReadonlyRootfs": false,
            "RestartPolicy": {
                "MaximumRetryCount": 10,
                "Name": "on-failure"
            },
            "Runtime": "runc",
            "SecurityOpt": null,
            "ShmSize": 67108864,
            "UTSMode": "",
            "Ulimits": null,
            "UsernsMode": "",
            "VolumeDriver": "",
            "VolumesFrom": null
        },
        "HostnamePath": "/var/lib/docker/containers/eea8b2bf94818521c6b39fb77dc324429aeb1a02a95f2196e8b2296e59410cdf/hostname",
        "HostsPath": "/var/lib/docker/containers/eea8b2bf94818521c6b39fb77dc324429aeb1a02a95f2196e8b2296e59410cdf/hosts",
        "Id": "eea8b2bf94818521c6b39fb77dc324429aeb1a02a95f2196e8b2296e59410cdf",
        "Image": "sha256:19faf9370ed030f2ba90ba63c8427b0565024e172d09929e86ad7d4017cf9af4",
        "LogPath": "/var/lib/docker/containers/eea8b2bf94818521c6b39fb77dc324429aeb1a02a95f2196e8b2296e59410cdf/eea8b2bf94818521c6b39fb77dc324429aeb1a02a95f2196e8b2296e59410cdf-json.log",
        "MountLabel": "",
        "Mounts": [],
        "Name": "/photol-api.web.1",
        "NetworkSettings": {
            "Bridge": "",
            "EndpointID": "761bb82d3a5e5f6b656076959d0a552a7e68518f553fa13e09c4466115cfa74d",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "HairpinMode": false,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "MacAddress": "02:42:ac:11:00:04",
            "Networks": {
                "bridge": {
                    "Aliases": null,
                    "DriverOpts": null,
                    "EndpointID": "761bb82d3a5e5f6b656076959d0a552a7e68518f553fa13e09c4466115cfa74d",
                    "Gateway": "172.17.0.1",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "IPAMConfig": null,
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "Links": null,
                    "MacAddress": "02:42:ac:11:00:04",
                    "NetworkID": "5adb1395fd226a4d005700d858047c8a883e13f3a52ffe5473a04dfe92e843d2"
                }
            },
            "Ports": {},
            "SandboxID": "d7df42c84a1986688192bda49b7122193fc1fd526d286e02c2e60b78397ddaec",
            "SandboxKey": "/var/run/docker/netns/d7df42c84a19",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null
        },
        "Path": "/start",
        "Platform": "linux",
        "ProcessLabel": "",
        "ResolvConfPath": "/var/lib/docker/containers/eea8b2bf94818521c6b39fb77dc324429aeb1a02a95f2196e8b2296e59410cdf/resolv.conf",
        "RestartCount": 0,
        "State": {
            "Dead": false,
            "Error": "",
            "ExitCode": 0,
            "FinishedAt": "0001-01-01T00:00:00Z",
            "OOMKilled": false,
            "Paused": false,
            "Pid": 54914,
            "Restarting": false,
            "Running": true,
            "StartedAt": "2023-04-03T14:51:45.565509772Z",
            "Status": "running"
        }
    }
]
```

------------------------------------------------------------------------------------------------------------
dokku nginx:show-config APP_NAME
------------------------------------------------------------------------------------------------------------

```
server {
  listen      [::]:80;
  listen      80;
  server_name photol-api.dokku.paulgiron.com;
  access_log  /var/log/nginx/photol-api-access.log;
  error_log   /var/log/nginx/photol-api-error.log;

  include /home/dokku/photol-api/nginx.conf.d/*.conf;
  location / {
    return 301 https://$host:443$request_uri;
  }

}

server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;

  server_name photol-api.dokku.paulgiron.com;
  access_log  /var/log/nginx/photol-api-access.log;
  error_log   /var/log/nginx/photol-api-error.log;

  ssl_certificate           /home/dokku/photol-api/tls/server.crt;
  ssl_certificate_key       /home/dokku/photol-api/tls/server.key;
  ssl_protocols             TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  keepalive_timeout   70;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://photol-api-5000;
    http2_push_preload on;
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_buffer_size 4096;
    proxy_buffering on;
    proxy_buffers 8 4096;
    proxy_busy_buffers_size 8192;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-Start $msec;

  }



  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 502 /502-error.html;
  location /502-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }
  include /home/dokku/photol-api/nginx.conf.d/*.conf;
}

upstream photol-api-5000 {

  server 172.17.0.4:5000;
}
```

**Comment by josegonzalez** [comment]
Is your application listening on all interfaces (0.0.0.0) and respecting the `PORT` environment variable?

**Comment by polgiron** [comment]
hey @josegonzalez my app was not respecting the `PORT` env variable, thank you very much, it's working as expected now

**Comment by Lexe003** [comment]
Same issue here, how did you solve it?

**Comment by polgiron** [comment]
You need to use the `PORT` environment variable in your app, instead of the hardcoded value.
I'm using a NestJS app, in `main.ts` I had to do `await app.listen(config.get('PORT') || 3000)`
