### ISSUE TITLE
Detect id_ed25519.pub in git:public-key command

### ISSUE THREAD

**Issue by obrienmd** [dokku/dokku#5785]
At line:
https://github.com/dokku/dokku/blob/5af750b4695f20fa45af2bf2086d5c921a04b6fd/plugins/git/internal-functions#L260

It looks like dokku checks for the file `~/.ssh/id_rsa.pub` to determine if a public key is available to the dokku user. Upon failure, the system recommends the user run ` ssh-keygen -t ed25519 -C 'example@example.com'` to resolve the issue.

On each system I've tested with, this command by default saves the public key to `~/.ssh/id_ed25519.pub`, which makes sense.

There's probably some super complex way to test this dynamically, but IMHO just adding an OR condition for the ED25519 pub key file is probably OK.

If no major disagreement, I'll work up a pull request ASAP.

**Comment by josegonzalez** [comment]
Seems like a good fix.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
