### ISSUE TITLE
There is no way to run dokku report without downloading herokuish images

### ISSUE THREAD

**Issue by gamedevsam** [dokku/dokku#5792]
### Description of problem

I use dokku exclusively with docker images. I don't even want to install any herokuish build packs ever.

It's unfortunate that every time I submit a bug report I'm forced to download the herokuish docker images.

### Steps to reproduce

Install dokku and then uninstall herokuish:

```
sudo apt-get purge herokuish
docker system prune -a
```

Then attempt to generate a dokku report:

```
dokku report
```

Notice herokuish docker images begin downloading.

### dokku report $APP_NAME

N/A

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
