### ISSUE TITLE
nginx-pre-reload problem on boot after dokku update

### ISSUE THREAD

**Issue by arusa** [dokku/dokku#5804]
### Description of problem

After updating dokku from 0.29.4 to 0.30.2 I did a reboot and suddenly nginx didn't listen on 443 anymore. After running `service nginx restart` everything worked fine again, but after another reboot 443 was down again.

I looked into /var/log/syslog and found:

```
Apr 16 09:52:38 xxx dokku[5254]: -----> Creating https nginx.conf
Apr 16 09:52:38 xxx dokku[5254]:        Enabling HSTS
Apr 16 09:52:38 xxx dokku[10177]: /var/lib/dokku/plugins/enabled/redirect/nginx-pre-reload: line 7: /var/lib/dokku/plugins/available/proxy/functions: No such file or directory
Apr 16 09:52:38 xxx dokku[1700]:  !     Error running restore against app xxx: exit status 1
Apr 16 09:52:38 xxx dokku[1700]:  !     restore command returned 1 errors
Apr 16 09:52:38 xxx systemd[1]: dokku-redeploy.service: Main process exited, code=exited, status=1/FAILURE
Apr 16 09:52:38 xxx systemd[1]: dokku-redeploy.service: Failed with result 'exit-code'.
```

My workaround that solved the problem was:

```
sudo -u dokku touch /var/lib/dokku/plugins/available/proxy/functions
```

I don't know what this "functions" file does, but it seems to be problematic if it is missing.

### Steps to reproduce

Reboot a dokku server that doesn't have a file /var/lib/dokku/plugins/available/proxy/functions

### dokku report $APP_NAME

The problem was not about an app, but about nginx in general.

**Comment by josegonzalez** [comment]
The problem is actually that you are running an older version of the dokku-redirect plugin. I can't say exactly which because you didn't include the information I asked for in the issue template.

That said, if you update that plugin, things will start working again.
