### ISSUE TITLE
how to run node.js app with 'npm start'

### ISSUE THREAD

**Issue by gholadr** [dokku/dokku#584]
as opposed to using `web: node app.js` in Procfile, I would love to simply call `npm start`, however Procfile doesnt seemt to support this directive. 
Should I give up on using npm start and rely on the traditional node app.js to run the app?

**Comment by malixsys** [comment]
You can also have a file `app.json` with:

```{
  "scripts": {
    "dokku": {
      "predeploy": "npm run build"
    }
  }
}```

**Comment by josegonzalez** [comment]
The nodejs buildpack should take care of building, @malixsys. For dockerfile deploys, just use the `RUN` command.
