### ISSUE TITLE
Allow any domains to reach an app

### ISSUE THREAD

**Issue by james-em** [dokku/dokku#5845]
### Description of feature

Hi,

I would like to have a dokku app that acts as the `default` nginx.

I currently have to do the following to get it done, but it breaks every deploy I make:

```
rm /etc/nginx/sites-enabled/default

nano /home/dokku/<app-name>/nginx.conf
-> edit server_name to `_`
```

This way, my app answers all incoming request no matter what the domain is.

Thank you

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
