### ISSUE TITLE
Unable to set proxy_set_header Connection "upgrade"; Nginx configuration option

### ISSUE THREAD

**Issue by charleshan** [dokku/dokku#5849]
### Description of problem

Basically the same as #4401 but for proxy_set_header Connection "upgrade"; Nginx configuration.

### Steps to reproduce

See #4401

### dokku report $APP_NAME

See #4401

**Comment by josegonzalez** [comment]
Why do you need this to be settable? What does the existing value break for you?

**Comment by charleshan** [comment]
Whether or not this is the right config, my thinking was that we we should be able to override anything. I realized that we can do this with `nginx.config.sigil`.

We can close this issue :)
