### ISSUE TITLE
Traefik always tries to get letsencrypt cert for traefik.dokku.me

### ISSUE THREAD

**Issue by caplod** [dokku/dokku#5855]
### Description of problem

``` 
dokku version
dokku version 0.30.3
```

I have disabled the api and dashboard of traefik.

But traefik still tries to get a cert for traefik.dokku.me.

### Steps to reproduce

```
dokku traefik:report --traefik-api-enabled
false
dokku traefik:report --traefik-dashboard-enabled
false
```

but when I check

```
dokku traefik:show-config

...

    labels:

      # Dashboard
      - "traefik.http.routers.api.rule=Host(`traefik.dokku.me`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=https"


```

therefore I have in log

```
dokku traefik:logs

...
{"entryPointName":"https","level":"error","msg":"api is not enabled","routerName":"api@docker","time":"2023-05-16T11:16:34Z"}
{"ACME CA":"https://acme-v02.api.letsencrypt.org/directory","level":"error","msg":"Unable to obtain ACME certificate for domains \"traefik.dokku.me\": unable to generate a certificate for the domains [traefik.dokku.me]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/","providerName":"leresolver.acme","routerName":"api@docker","rule":"Host(`traefik.dokku.me`)","time":"2023-05-16T11:16:35Z"}
...
```

### dokku report $APP_NAME

-----> uname: Linux web8 5.4.174-2-pve #1 SMP PVE 5.4.174-2 (Thu, 10 Mar 2022 15:58:44 +0100) x86_64 GNU/Linux
-----> memory: 
                     gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
       Speicher:       8192        1257        1019          42        5915        6934
       Swap:          16384           0       16383
-----> docker version: 
       Client: Docker Engine - Community
        Version:           23.0.6
        API version:       1.42
        Go version:        go1.19.9
        Git commit:        ef23cbc
        Built:             Fri May  5 21:18:28 2023
        OS/Arch:           linux/amd64
        Context:           default
       
       Server: Docker Engine - Community
        Engine:
         Version:          23.0.6
         API version:      1.42 (minimum version 1.12)
         Go version:       go1.19.9
         Git commit:       9dbdbd4
         Built:            Fri May  5 21:18:28 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.21
         GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
        runc:
         Version:          1.1.7
         GitCommit:        v1.1.7-0-g860f061
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.10.4
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.17.3
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
       
       Server:
        Containers: 8
         Running: 7
         Paused: 0
         Stopped: 1
        Images: 28
        Server Version: 23.0.6
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: false
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc io.containerd.runc.v2
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
        runc version: v1.1.7-0-g860f061
        init version: de40ad0
        Security Options:
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.4.174-2-pve
        Operating System: Debian GNU/Linux 11 (bullseye)
        OSType: linux
        Architecture: x86_64
        CPUs: 4
        Total Memory: 8GiB
        Name: web8
        ID: 3c1cf633-5788-48e6-b98a-0c4e9d13f152
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.30.2
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: v0.5.41
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v252
         heroku-buildpack-nodejs    v203
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v226
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v231
         heroku-buildpack-go        v171
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.30.3
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.30.3 enabled    dokku core standard plugin
         20_events            0.30.3 enabled    dokku core events logging plugin
         app-json             0.30.3 enabled    dokku core app-json plugin
         apps                 0.30.3 enabled    dokku core apps plugin
         builder              0.30.3 enabled    dokku core builder plugin
         builder-dockerfile   0.30.3 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.3 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.3 enabled    dokku core builder-lambda plugin
         builder-null         0.30.3 enabled    dokku core builder-null plugin
         builder-pack         0.30.3 enabled    dokku core builder-pack plugin
         buildpacks           0.30.3 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.3 enabled    dokku core caddy-vhosts plugin
         certs                0.30.3 enabled    dokku core certificate management plugin
         checks               0.30.3 enabled    dokku core checks plugin
         common               0.30.3 enabled    dokku core common plugin
         config               0.30.3 enabled    dokku core config plugin
         cron                 0.30.3 enabled    dokku core cron plugin
         docker-options       0.30.3 enabled    dokku core docker-options plugin
         domains              0.30.3 enabled    dokku core domains plugin
         enter                0.30.3 enabled    dokku core enter plugin
         git                  0.30.3 enabled    dokku core git plugin
         haproxy-vhosts       0.30.3 enabled    dokku core haproxy-vhosts plugin
         logs                 0.30.3 enabled    dokku core logs plugin
         mysql                1.32.2 enabled    dokku mysql service plugin
         network              0.30.3 enabled    dokku core network plugin
         nginx-vhosts         0.30.3 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.3 enabled    dokku core plugin plugin
         postgres             1.33.0 enabled    dokku postgres service plugin
         proxy                0.30.3 enabled    dokku core proxy plugin
         ps                   0.30.3 enabled    dokku core ps plugin
         redis                1.32.4 enabled    dokku redis service plugin
         registry             0.30.3 enabled    dokku core registry plugin
         repo                 0.30.3 enabled    dokku core repo plugin
         resource             0.30.3 enabled    dokku core resource plugin
         run                  0.30.3 enabled    dokku core run plugin
         scheduler            0.30.3 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.3 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.30.3 enabled    dokku core scheduler-null plugin
         shell                0.30.3 enabled    dokku core shell plugin
         ssh-keys             0.30.3 enabled    dokku core ssh-keys plugin
         storage              0.30.3 enabled    dokku core storage plugin
         trace                0.30.3 enabled    dokku core trace plugin
         traefik-vhosts       0.30.3 enabled    dokku core traefik-vhosts plugin
=====> myapp app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> myapp app information
       App created at:                1683891810
       App deploy source:             git-push
       App deploy source metadata:    f1c8a14967294d8d0ee24143e64faf8b2d6dbba9
       App dir:                       /home/dokku/myapp
       App locked:                    false
=====> myapp builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> myapp builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> myapp builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml               
       Builder lambda global lambdayml path: lambda.yml               
       Builder lambda lambdayml path:                          
=====> myapp builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> myapp buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> myapp ssl information
       Ssl dir:                       /home/dokku/myapp/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> myapp checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
       Checks computed wait to retire: 60                       
       Checks global wait to retire:  60                       
       Checks wait to retire:                                  
=====> myapp cron information
       Cron task count:               0
=====> myapp docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10 -v /var/lib/dokku/data/storage/myapp:/app/data 
       Docker options run:            -v /var/lib/dokku/data/storage/myapp:/app/data 
=====> myapp domains information
       Domains app enabled:           true                     
       Domains app vhosts:            myapp.de
       Domains global enabled:        true                     
       Domains global vhosts:         web8
=====> myapp git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       f1c8a14                  
       Git source image:                                       
       Git last updated at:           1683892479               
=====> myapp logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> myapp network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.9:5000
=====> myapp nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/myapp-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/myapp-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx computed nginx conf sigil path: nginx.conf.sigil         
       Nginx global nginx conf sigil path: nginx.conf.sigil         
       Nginx nginx conf sigil path:                            
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1684015240               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> myapp proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000
       Proxy type:                    traefik
=====> myapp ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 079a1130be6)
=====> myapp registry information
       Registry computed image repo:      dokku/myapp
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> myapp resource information
=====> myapp scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> myapp scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local init process: true                     
       Scheduler docker local parallel schedule count:                          
=====> myapp storage information
       Storage build mounts:                                   
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/myapp:/app/data 
       Storage run mounts:            -v /var/lib/dokku/data/storage/myapp:/app/data

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
