### ISSUE TITLE
DOKKU_CNB_BUILDER defaults to the `latest` tag of `heroku/buildpacks` which is about to be deleted

### ISSUE THREAD

**Issue by edmorley** [dokku/dokku#5861]
### Description of problem

The `DOKKU_CNB_BUILDER` config option defaults to `heroku/buildpacks` (ie: `heroku/buildpacks:latest`), and:

1. The `heroku/buildpacks:*` repo is deprecated in favour of the `heroku/builder:*` and `heroku/builder-classic:*` repos (see https://github.com/heroku/builder#heroku-builder-images)
2. (More urgently) The `latest` tag of `heroku/buildpacks` is no longer being updated, and will soon be deleted (in favour of using explicit version tags, such as `heroku/buildpacks:20`), since the latest tag is not something we document or recommend for stack images as it allows breaking changes with no warning. See: https://github.com/heroku/builder/pull/344

### Steps to reproduce

See:
https://github.com/dokku/dokku/blob/e72f5b1d90a12222db0c3e6813fa7fb945a8cb59/dokku#L45

### dokku report $APP_NAME

N/A

**Comment by josegonzalez** [comment]
Thanks for the heads up, I appreciate it!
