### ISSUE TITLE
Incorrectly closed code-block in documentation for one-off tasks

### ISSUE THREAD

**Issue by gerardpaapu** [dokku/dokku#5869]
The [one-off tasks page](https://dokku.com/docs/processes/one-off-tasks/) in the documentation has a malformed code block.

![image](https://github.com/dokku/dokku/assets/47387/a3807fd0-ec1e-4cfb-ae75-5d914de8330c)

I believe this is because the code-block starts with triple-backticks  but is closed with 4 backticks, causing the documentation page to render incorrectly. Removing the extra closing backtick should fix the issue.

**Comment by josegonzalez** [comment]
Mind filing a PR?

**Comment by gerardpaapu** [comment]
Sorry, didn't see the notification. Next time.
