### ISSUE TITLE
Auto Restart applications like Heroku Free Eco Dyno

### ISSUE THREAD

**Issue by SpEcHiDe** [dokku/dokku#5895]
### Description of feature

Heroku free Eco plan has the feature that application auto restarts every 24 hours. I would like to have similar feature available in Dokku.

**Comment by josegonzalez** [comment]
I don't think this sort of thing is a good idea for the core project - it invites poor practices around allowing your app to consume memory in an unlimited fashion - but it seemed like a fun enough plugin to work on, so I created one [here](https://github.com/dokku/dokku-cron-restart).
