### ISSUE TITLE
Access `GIT_REV` and other variables during the build phase (Dockerfile)

### ISSUE THREAD

**Issue by eillarra** [dokku/dokku#5903]
#### Discussed in https://github.com/dokku/dokku/discussions/5901

It would be nice to be able to load env vars during build-time. something like this:

```Dockerfile
ARG GIT_REV
ENV GIT_REV ${GIT_REV}
```

Currently `--build-arg` can be used to pass variables (in many cases, we are redefining config vars) but this is not an option for GIT_REV, as it should change on every deploy.

Something like this could be a nice solution (setting a `--build-arg` with no value):

```shell
dokku docker-options:add appname build "--build-arg GIT_REV"
```

**Comment by josegonzalez** [comment]
I think one thing we can do is modify the [`builder-build` trigger](https://github.com/dokku/dokku/blob/master/plugins/builder-dockerfile/builder-build) for the `builder-dockerfile` plugin to export the app environment prior to building. We do something similar [here](https://github.com/dokku/dokku/blob/master/plugins/builder-herokuish/builder-build#L32) for herokuish.

The nice thing about this is that any env var could be added via `--build-arg $KEY` at that point, without needing the user to respecify the value in docker-options.

If you want to make a PR with this change, I can help you guide adding a test :)

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by eillarra** [comment]
Great!
