### ISSUE TITLE
Can't install on Ubuntu 22.10 - maybe this is on purpose?

### ISSUE THREAD

**Issue by sec0ndhand** [dokku/dokku#5925]
### Description of problem

After starting a new droplet on Digital Ocean, I followed the setup guide and dokku wouldn't install.  It gave this error:

```Unsupported Linux distribution. Only the following versions are supported: Debian [10, 11], Ubuntu [18.04, 20.04, 22.04]```

I expected to be able to start a new ubuntu instance, running 22.10.

If this is expected, my bad.  I couldn't find documentation, nor an issue that talked about it.  Feel free to close this out if the requirement for ubuntu 22.04 is on purpose, I just wanted to make sure you bumped the version to 22.10 if you didn't know.

Also, Thank you so much for Dokku, it is a great tool for my smallish projects.

### Steps to reproduce

Start a new droplet on digital ocean running ubuntu.
Install dokku

### dokku report $APP_NAME

N/A installation error

### Additional information

N/A installation error

### Output of failing commands after running: dokku trace:off

```shell
N/A installation error
```

### Output of failing commands after running: dokku trace:on

```shell
N/A installation error
```

**Comment by sec0ndhand** [comment]
I switched to Debian, and it worked fine.

**Comment by josegonzalez** [comment]
This is on purpose. We only support LTS releases for Ubuntu, as the non-LTS ones tend to introduce a bunch of churn (requiring random changes that may not persist), have shorter lifecycles (meaning we have to do the changes more frequently), and aren't usually supported on CI (meaning I usually can't easily replicate issues).

**Comment by sec0ndhand** [comment]
Cool, thanks Jose!  I didn't know ubuntu had non LTS minor versions of their LTS major versions.  Thanks for the education!
