### ISSUE TITLE
Installing plugins via plugin-list on Docker still fails on reboot/restart

### ISSUE THREAD

**Issue by michaelmulley** [dokku/dokku#5929]
### Description of problem

When using docker, installing plugins via the [plugin-list method](https://dokku.com/docs/getting-started/install/docker/#on-dokku-start) succeeds on container boot. However, when the container is restarted, the init script attempts to install the plugins again and fails with a `fatal: destination path 'postgres' already exists and is not an empty directory` message. As a result, the container does not successfully start.

This is identical to issue #5549. A fix was committed for that issue, which was then closed, but it doesn't seem to work.

The init script has code to check if the plugin is already installed:
```bash
      local plugin_name="$(echo "$line" | awk '{print $2}')"
      if dokku plugin:installed "$plugin_name"; then
        log-warn "Skipping already installed plugin: $plugin_name"
      else
        dokku plugin:install "$plugin_name" "$(echo "$line" | cut -d':' -f1)"
      fi
```

However, plugin_name appears to be obtained incorrectly:
```shell
$ echo "postgres: https://github.com/dokku/dokku-postgres.git" | awk '{print $2}'
https://github.com/dokku/dokku-postgres.git
```

Fixing the awk syntax fixes the problem:
```shell
$ echo "postgres: https://github.com/dokku/dokku-postgres.git" | awk -F: '{print $1}'
postgres
```

Thanks to the dokku team for everything!

### Steps to reproduce

See #5549 

### dokku report $APP_NAME

N/A

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
