### ISSUE TITLE
Support for latest Debian 12

### ISSUE THREAD

**Issue by jaytula** [dokku/dokku#5960]
### Description of feature

When I tried to install on the latest Debian 12 "bookworm", it says it is not supported. I tried installing via the following method:

```shell
# for debian systems, installs Dokku via apt-get
wget -NP . https://dokku.com/install/v0.30.7/bootstrap.sh
sudo DOKKU_TAG=v0.30.7 bash bootstrap.sh
```

**Comment by josegonzalez** [comment]
Good call. We can probably:

- update this to add `12`: https://github.com/dokku/dokku/blob/master/bootstrap.sh#L163
- update this to add `12`: https://github.com/dokku/dokku/blob/master/bootstrap.sh#L15

That should make the bootstrap script work. We can also publish the packages for bookworm, but honestly they are the same everywhere so doesn't really matter too much.

**Comment by jaytula** [comment]
Thanks!

**Comment by josegonzalez** [comment]
Would you be willing to make a pull request with those changes?
