### ISSUE TITLE
Dokku docs navigation link broken

### ISSUE THREAD

**Issue by fishnux** [dokku/dokku#5969]
### Description of problem

Dokku docs navigation link broken

### Steps to reproduce

1. Open https://dokku.com/docs/
2. Search "Deploying an Application", click link
3. 404 Not Found error

### dokku report $APP_NAME

N/A

**Comment by josegonzalez** [comment]
@fishnux im not able to replicate this on chrome on a mac. Are you using a particular browser?

**Comment by fishnux** [comment]
> @fishnux im not able to replicate this on chrome on a mac. Are you using a particular browser?

Weird, it's working now, no idea what happened, maybe some JS failed to load at the time
