### ISSUE TITLE
dokku logs:set converting + to space character and messes up credential

### ISSUE THREAD

**Issue by nhatquang238** [dokku/dokku#5970]
### Description of problem

I was trying to set up vector log sink with aws s3 following the guide here: https://dokku.com/docs/deployment/logs/#configuring-a-log-sink

I noticed that i need to url escaped my config. However, when i tried to escape "+" (%2B) in my aws secret and ran the dokku log:set command, the generated vector.json file in /var/lib/dokku/data/logs/vector.json return a space character in place of "+" char.

The docker vector container subsequently failed the aws authentication as a result of mismatching secret credential.

### Steps to reproduce

Run this command:

dokku logs:set --global vector-sink "aws_s3://?bucket=sample&region=ap-southeast-1&compression=gzip&auth%5Baccess_key_id%5D=XXXYYYYZZZZZ&auth%5Bsecret_access_key%5D=fkd%2BfuieFDKAmmgUH&encoding%5Bcodec%5D=text&key_prefix=%25F"

### dokku report $APP_NAME

-----> uname: Linux ip-172-31-1-176 5.15.0-1031-aws #35-Ubuntu SMP Fri Feb 10 02:07:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:            7869        1488         318          43        6062        6019
       Swap:              0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           24.0.2
        API version:       1.43
        Go version:        go1.20.4
        Git commit:        cb74dfc
        Built:             Thu May 25 21:51:00 2023
        OS/Arch:           linux/amd64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          24.0.2
         API version:      1.43 (minimum version 1.12)
         Go version:       go1.20.4
         Git commit:       659604f
         Built:            Thu May 25 21:51:00 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.21
         GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
        runc:
         Version:          1.1.7
         GitCommit:        v1.1.7-0-g860f061
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client: Docker Engine - Community
        Version:    24.0.2
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.10.5
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.18.1
           Path:     /usr/libexec/docker/cli-plugins/docker-compose

       Server:
        Containers: 10
         Running: 10
         Paused: 0
         Stopped: 0
        Images: 8
        Server Version: 24.0.2
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
        runc version: v1.1.7-0-g860f061
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-1031-aws
        Operating System: Ubuntu 22.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 7.686GiB
        Name: ip-172-31-1-176
        ID: 095daaa6-9fe4-4f16-883c-422be13bca01
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.34.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
       herokuish: v0.6.0
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v254
         heroku-buildpack-nodejs    v213
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v232
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v234
         heroku-buildpack-go        v174
         heroku-buildpack-nginx     v23
         buildpack-null             v3
-----> dokku version: dokku version 0.30.6
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins:
         00_dokku-standard    0.30.6 enabled    dokku core standard plugin
         20_events            0.30.6 enabled    dokku core events logging plugin
         app-json             0.30.6 enabled    dokku core app-json plugin
         apps                 0.30.6 enabled    dokku core apps plugin
         builder              0.30.6 enabled    dokku core builder plugin
         builder-dockerfile   0.30.6 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.6 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.6 enabled    dokku core builder-lambda plugin
         builder-null         0.30.6 enabled    dokku core builder-null plugin
         builder-pack         0.30.6 enabled    dokku core builder-pack plugin
         buildpacks           0.30.6 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.6 enabled    dokku core caddy-vhosts plugin
         certs                0.30.6 enabled    dokku core certificate management plugin
         checks               0.30.6 enabled    dokku core checks plugin
         common               0.30.6 enabled    dokku core common plugin
         config               0.30.6 enabled    dokku core config plugin
         cron                 0.30.6 enabled    dokku core cron plugin
         docker-options       0.30.6 enabled    dokku core docker-options plugin
         domains              0.30.6 enabled    dokku core domains plugin
         enter                0.30.6 enabled    dokku core enter plugin
         git                  0.30.6 enabled    dokku core git plugin
         haproxy-vhosts       0.30.6 enabled    dokku core haproxy-vhosts plugin
         logs                 0.30.6 enabled    dokku core logs plugin
         network              0.30.6 enabled    dokku core network plugin
         nginx-vhosts         0.30.6 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.6 enabled    dokku core plugin plugin
         proxy                0.30.6 enabled    dokku core proxy plugin
         ps                   0.30.6 enabled    dokku core ps plugin
         registry             0.30.6 enabled    dokku core registry plugin
         repo                 0.30.6 enabled    dokku core repo plugin
         resource             0.30.6 enabled    dokku core resource plugin
         run                  0.30.6 enabled    dokku core run plugin
         scheduler            0.30.6 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.6 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.30.6 enabled    dokku core scheduler-null plugin
         shell                0.30.6 enabled    dokku core shell plugin
         ssh-keys             0.30.6 enabled    dokku core ssh-keys plugin
         storage              0.30.6 enabled    dokku core storage plugin
         trace                0.30.6 enabled    dokku core trace plugin
         traefik-vhosts       0.30.6 enabled    dokku core traefik-vhosts plugin
=====> backend app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> backend app information
       App created at:                1685612870
       App deploy source:             git-push
       App deploy source metadata:    fe656264500e4406671315a67352703af4f91a22
       App dir:                       /home/dokku/backend
       App locked:                    false
=====> backend builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> backend builder-dockerfile information
       Builder dockerfile computed dockerfile path: backend/Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path: backend/Dockerfile
=====> backend builder-herokuish information
       Builder herokuish computed allowed: true
       Builder herokuish global allowed: true
       Builder herokuish allowed:
=====> backend builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> backend builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> backend buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> backend caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.7
       Caddy letsencrypt email:
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR
       Caddy polling interval:        5s
       Caddy tls internal:            false
=====> backend ssl information
       Ssl dir:                       /home/dokku/backend/tls
       Ssl enabled:                   false
       Ssl hostnames:
       Ssl expires at:
       Ssl issuer:
       Ssl starts at:
       Ssl subject:
       Ssl verified:
=====> backend checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> backend cron information
       Cron task count:               0
=====> backend docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> backend domains information
       Domains app enabled:           false
       Domains app vhosts:
       Domains global enabled:        true
       Domains global vhosts:         13.251.45.239
=====> backend git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       fe65626
       Git source image:
       Git last updated at:           1687167600
=====> backend haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.3.0
       Haproxy letsencrypt email:
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR
=====> backend logs information
       Logs computed max size:        20m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:                 20m
       Logs vector sink:              aws_s3://?bucket=plantrips-log&region=ap-southeast-1&compression=gzip&auth%5Baccess_key_id%5D=xxxxxxxx&auth%5Bsecret_access_key%5D=yyyyyyyyyy&encoding%5Bcodec%5D=text&key_prefix=%25F&filename_time_format=backend_%25s
=====> backend network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.5:3000 172.17.0.6:3000 172.17.0.7:3000 172.17.0.8:3000
=====> backend nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/backend-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/backend-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1688100881
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> backend proxy information
       Proxy enabled:                 true
       Proxy port map:                http:3000:3000
       Proxy type:                    nginx
=====> backend ps information
       Deployed:                      true
       Processes:                     4
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 04e2e1ea903)
       Status web 2:                  running (CID: 55e65fea7d1)
       Status web 3:                  running (CID: fb20243311c)
       Status web 4:                  running (CID: d2caabc9345)
=====> backend registry information
       Registry computed image repo:      dokku/backend
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> backend resource information
=====> backend scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> backend scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> backend storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:
=====> backend traefik information
       Traefik api enabled:           false
       Traefik api vhost:             traefik.dokku.me
       Traefik basic auth password:
       Traefik basic auth username:
       Traefik dashboard enabled:     false
       Traefik image:                 traefik:v2.8
       Traefik letsencrypt email:
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR
       Traefik priority:

**Comment by josegonzalez** [comment]
This has to do with how nested values are handled in the DSN. See [this comment](https://github.com/dokku/dokku/issues/5502#issuecomment-1356916907) for more details.

We have a test-case [here](https://github.com/dokku/dokku/pull/5533) that shows how to escape `+` signs properly for usage. Hope that helps.
