### ISSUE TITLE
dokku app:destroy imports herokuish buildpacks

### ISSUE THREAD

**Issue by gamedevsam** [dokku/dokku#5983]
### Description of feature

I just ran a command to delete an app and dokku downloaded the herokish images (which I'm not using and don't plan on using). I've seen this happen for a few other commands (the upgrade command for example), and those other cases are more understandable, but this one seems weird.

Is there a reason why deleting apps requires the herokuish buildpack or is this just part of a common code path?

<img width="440" alt="image" src="https://github.com/dokku/dokku/assets/420996/d2f4788b-97fa-4ab4-a3c5-5c2e88443229">

**Comment by josegonzalez** [comment]
This is due to cache deletion, which changes to volume removal in the next minor, thus removing the need to download the herokuish layer. Going to close this for now.

See https://github.com/dokku/dokku/pull/5495 for more details on the change.
