### ISSUE TITLE
node app failing with ! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by MrFuentastic** [dokku/dokku#6002]
### Description of problem

Node app is failing to build with ! [remote rejected] master -> master (pre-receive hook declined), have previously deployed this app with no issues, the lat deploy was at the beginning of June or so. 

I did notice that the would lock after trying to deploy, after unlocking via dokku apps:unlock and trying again, it would just lock again.

### dokku report $APP_NAME

https://gist.github.com/MrFuentastic/8d8a088f747dba22d8dab416dbd69397

### Additional information

dokku ps:inspect server
[
    {
        "AppArmorProfile": "docker-default", 
        "Args": [
            "web"
        ], 
        "Config": {
            "AttachStderr": false, 
            "AttachStdin": false, 
            "AttachStdout": false, 
            "Cmd": [
                "/start", 
                "web"
            ], 
            "Domainname": "", 
            "Entrypoint": null, 
            "Env": [
                "PORT=5000", 
                "USER=herokuishuser", 
                "DYNO=web.1", 
                "CACHE_PATH=/cache", 
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", 
                "DEBIAN_FRONTEND=XXXXXX"
            ], 
            "Hostname": "91a1b5aeec9c", 
            "Image": "dokku/server:latest", 
            "Labels": {
                "dokku": ""
            }, 
            "OnBuild": null, 
            "OpenStdin": false, 
            "StdinOnce": false, 
            "Tty": false, 
            "User": "", 
            "Volumes": null, 
            "WorkingDir": ""
        }, 
        "Created": "2023-05-30T17:33:34.329256039Z", 
        "Driver": "overlay2", 
        "ExecIDs": null, 
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/699965d316c848eea0aa1bba265bf6508a43045ab904a1f248cb6861f43ddd75-init/diff:/var/lib/docker/overlay2/1599a8f18f177d8102f3b4e310e04afb774d18a463232ecc6270522cc05b4063/diff:/var/lib/docker/overlay2/b00c6ee00c2ba11d2996db3a9616e0ea23d2aae9af297bea6336f2cb8e252ed9/diff:/var/lib/docker/overlay2/d13032130d4d9bd00b51ddf3586f6787184eb3ff041aac0863665772a0cf7539/diff:/var/lib/docker/overlay2/59e31d67c300676f4400bbaeac2c944d35c757ed7a7738171272e61c502847f3/diff:/var/lib/docker/overlay2/e212cb9f09c92ceb23fd7d6be95877c4b6e56cdfc0c8fa4abbeb2b89d9cbc18e/diff:/var/lib/docker/overlay2/50cfc4b734ae23dd112607059e0a5ab46eea1867da539092baceaa849b82706b/diff:/var/lib/docker/overlay2/58015f8371348bef004c53402d9643e8be97ebeb101b3ead8c2d16f433fa2a3c/diff:/var/lib/docker/overlay2/bd9dddef209d2ae59b26afa76d6704835f3733a18816016c9f1a9e831f798343/diff:/var/lib/docker/overlay2/d1c38ae341d559a6cbc01d09361530ad7d6eea5a82346fa13167b8d4b02196d6/diff:/var/lib/docker/overlay2/d6054feb2f62203592bd0e7ffd6cd19fe6782580d9349fbb3f14d317e9621c98/diff:/var/lib/docker/overlay2/1ceecb88b2d06deeb9151a95d4800a664a9e366442b1a69336d325297f55fda0/diff:/var/lib/docker/overlay2/c2f60fdaf111117712c227f66f25436026fd9072ff5b1ab5ec11a3b7388cd219/diff:/var/lib/docker/overlay2/90a4e71441fab25476d491391bc5baa87d2b68fb339ca5006ffb5e58936decbf/diff:/var/lib/docker/overlay2/446b2b8e445da7f58efd41bb7e12075609b931f7b3b2c1c18308a2841a86bd3d/diff:/var/lib/docker/overlay2/698288682d8ef7d0d512e8b721a2781308a14af347d5966afb2b0d3739dd28f4/diff:/var/lib/docker/overlay2/e58d5886e2bc8b276f1bdebda715e0c43f1da8b37fd48776b8d14c15241e485a/diff:/var/lib/docker/overlay2/3e41ed95a6d36ae913e16559dbaeaa04c2ba5e1766a6af347f7b07dc19f6d6e8/diff:/var/lib/docker/overlay2/70c17098daa9989f8176470a5d96627fff804e61e88ee14ce5b29097aef169c7/diff:/var/lib/docker/overlay2/8ad0220b9a3fb45d72a4c300e1dee90b0b0500cfea7d262e5d361dd1aea19ddc/diff", 
                "MergedDir": "/var/lib/docker/overlay2/699965d316c848eea0aa1bba265bf6508a43045ab904a1f248cb6861f43ddd75/merged", 
                "UpperDir": "/var/lib/docker/overlay2/699965d316c848eea0aa1bba265bf6508a43045ab904a1f248cb6861f43ddd75/diff", 
                "WorkDir": "/var/lib/docker/overlay2/699965d316c848eea0aa1bba265bf6508a43045ab904a1f248cb6861f43ddd75/work"
            }, 
            "Name": "overlay2"
        }, 
        "HostConfig": {
            "AutoRemove": false, 
            "Binds": null, 
            "BlkioDeviceReadBps": null, 
            "BlkioDeviceReadIOps": null, 
            "BlkioDeviceWriteBps": null, 
            "BlkioDeviceWriteIOps": null, 
            "BlkioWeight": 0, 
            "BlkioWeightDevice": [], 
            "CapAdd": null, 
            "CapDrop": null, 
            "Cgroup": "", 
            "CgroupParent": "", 
            "ConsoleSize": [
                0, 
                0
            ], 
            "ContainerIDFile": "", 
            "CpuCount": 0, 
            "CpuPercent": 0, 
            "CpuPeriod": 0, 
            "CpuQuota": 0, 
            "CpuRealtimePeriod": 0, 
            "CpuRealtimeRuntime": 0, 
            "CpuShares": 0, 
            "CpusetCpus": "", 
            "CpusetMems": "", 
            "DeviceCgroupRules": null, 
            "Devices": [], 
            "DiskQuota": 0, 
            "Dns": [], 
            "DnsOptions": [], 
            "DnsSearch": [], 
            "ExtraHosts": null, 
            "GroupAdd": null, 
            "IOMaximumBandwidth": 0, 
            "IOMaximumIOps": 0, 
            "IpcMode": "shareable", 
            "Isolation": "", 
            "KernelMemory": 0, 
            "Links": null, 
            "LogConfig": {
                "Config": {}, 
                "Type": "json-file"
            }, 
            "MaskedPaths": [
                "/proc/asound", 
                "/proc/acpi", 
                "/proc/kcore", 
                "/proc/keys", 
                "/proc/latency_stats", 
                "/proc/timer_list", 
                "/proc/timer_stats", 
                "/proc/sched_debug", 
                "/proc/scsi", 
                "/sys/firmware"
            ], 
            "Memory": 0, 
            "MemoryReservation": 0, 
            "MemorySwap": 0, 
            "MemorySwappiness": null, 
            "NanoCpus": 0, 
            "NetworkMode": "default", 
            "OomKillDisable": false, 
            "OomScoreAdj": 0, 
            "PidMode": "", 
            "PidsLimit": 0, 
            "PortBindings": {}, 
            "Privileged": false, 
            "PublishAllPorts": false, 
            "ReadonlyPaths": [
                "/proc/bus", 
                "/proc/fs", 
                "/proc/irq", 
                "/proc/sys", 
                "/proc/sysrq-trigger"
            ], 
            "ReadonlyRootfs": false, 
            "RestartPolicy": {
                "MaximumRetryCount": 10, 
                "Name": "on-failure"
            }, 
            "Runtime": "runc", 
            "SecurityOpt": null, 
            "ShmSize": 67108864, 
            "UTSMode": "", 
            "Ulimits": null, 
            "UsernsMode": "", 
            "VolumeDriver": "", 
            "VolumesFrom": null
        }, 
        "HostnamePath": "/var/lib/docker/containers/91a1b5aeec9c41f6aeccf0478cd232c49b1964b5acb30a78dab5c55648696b79/hostname", 
        "HostsPath": "/var/lib/docker/containers/91a1b5aeec9c41f6aeccf0478cd232c49b1964b5acb30a78dab5c55648696b79/hosts", 
        "Id": "91a1b5aeec9c41f6aeccf0478cd232c49b1964b5acb30a78dab5c55648696b79", 
        "Image": "sha256:6fb2ea2af20918bc28d751783d3940e7a1089ecb042fa058671644e9d8c6d225", 
        "LogPath": "/var/lib/docker/containers/91a1b5aeec9c41f6aeccf0478cd232c49b1964b5acb30a78dab5c55648696b79/91a1b5aeec9c41f6aeccf0478cd232c49b1964b5acb30a78dab5c55648696b79-json.log", 
        "MountLabel": "", 
        "Mounts": [], 
        "Name": "/server.web.1", 
        "NetworkSettings": {
            "Bridge": "", 
            "EndpointID": "554ad215710c6d7c817ea090df7d477b1f985834aba25b922bbe3eda3173b520", 
            "Gateway": "172.17.0.1", 
            "GlobalIPv6Address": "", 
            "GlobalIPv6PrefixLen": 0, 
            "HairpinMode": false, 
            "IPAddress": "172.17.0.2", 
            "IPPrefixLen": 16, 
            "IPv6Gateway": "", 
            "LinkLocalIPv6Address": "", 
            "LinkLocalIPv6PrefixLen": 0, 
            "MacAddress": "02:42:ac:11:00:02", 
            "Networks": {
                "bridge": {
                    "Aliases": null, 
                    "DriverOpts": null, 
                    "EndpointID": "554ad215710c6d7c817ea090df7d477b1f985834aba25b922bbe3eda3173b520", 
                    "Gateway": "172.17.0.1", 
                    "GlobalIPv6Address": "", 
                    "GlobalIPv6PrefixLen": 0, 
                    "IPAMConfig": null, 
                    "IPAddress": "172.17.0.2", 
                    "IPPrefixLen": 16, 
                    "IPv6Gateway": "", 
                    "Links": null, 
                    "MacAddress": "02:42:ac:11:00:02", 
                    "NetworkID": "f1a8dc4330ce4bfc968673bcb1f7e3a16892ebcdaa6e7c0375b3472a9dbc2d3b"
                }
            }, 
            "Ports": {}, 
            "SandboxID": "b46d7d068257ed2e7aa6b87d2702521f145f607be8993cce8b4201fc85b06935", 
            "SandboxKey": "/var/run/docker/netns/b46d7d068257", 
            "SecondaryIPAddresses": null, 
            "SecondaryIPv6Addresses": null
        }, 
        "Path": "/start", 
        "Platform": "linux", 
        "ProcessLabel": "", 
        "ResolvConfPath": "/var/lib/docker/containers/91a1b5aeec9c41f6aeccf0478cd232c49b1964b5acb30a78dab5c55648696b79/resolv.conf", 
        "RestartCount": 0, 
        "State": {
            "Dead": false, 
            "Error": "", 
            "ExitCode": 0, 
            "FinishedAt": "2023-07-05T15:43:07.991868276Z", 
            "OOMKilled": false, 
            "Paused": false, 
            "Pid": 1179, 
            "Restarting": false, 
            "Running": true, 
            "StartedAt": "2023-07-05T15:43:33.845806228Z", 
            "Status": "running"
        }
    }
]

### Output of failing deploy after running: dokku trace:off

```shell
Enumerating objects: 69, done.
Counting objects: 100% (69/69), done.
Delta compression using up to 4 threads
Compressing objects: 100% (47/47), done.
Writing objects: 100% (47/47), 13.90 KiB | 2.78 MiB/s, done.
Total 47 (delta 35), reused 0 (delta 0), pack-reused 0
-----> Cleaning up...
-----> Building server from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  14.19.0
       engines.npm (package.json):   6.14.16
       
       Resolving node version 14.19.0...
       
       -----> Change to Node.js build process 
       Heroku has begun executing the "build" script defined in package.json
       during Node.js builds.
       
       Read more: https://devcenter.heroku.com/changelog-items/1573
       
       
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
To xxxx:xxxx
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'xxx:xxx'
```

### Output of failing deploy after running: dokku trace:on

```shell
https://gist.github.com/MrFuentastic/a1f7be1fc411055fefdd82354828958c
```

**Comment by josegonzalez** [comment]
This is a buildpack issue. As per our issue template, please join us on our slack or discord (links in our docs) for further debugging.
