### ISSUE TITLE
dokku ps:restart give "Deploying web (count=0)" no nginf.conf created.

### ISSUE THREAD

**Issue by eager-2-learn** [dokku/dokku#6066]
I have been using  dokku for a short time.

dokku 0.24.10 works correct on several Ubuntu 18.04 and 20.04 systems.
dokku is upgraded to 0.30.9

On all system, but one, "dokku ps:restart sms-portal" works correct.
-----> Deploying web (count=1)
         Attempting pre-flight checks (web.1)
         Waiting for 10 seconds (web.1)
         Default container check successful (web.1)
        Scheduling old container shutdown in 60 seconds (web.1)
===> Triggering early nginx proxy rebuild

-----> Creating http nginx.conf

So /home/dokku/sms-portal/nginx.conf is created.

On one system "dokku ps:restart sms-portal" give
-----> Deploying web (count=0)
===> Triggering early nginx proxy rebuild
-----> Running post-deploy
-----> Renaming containers
-----> Checking for postdeploy task
         No postdeploy task found, skipping
-----> Updated schedule file

 So /home/dokku/sms-portal/nginx.conf is not created.

So count=0 and no nginx.conf.

A "dokku ps:rebuild sms-portal" does not solve this problem.

Can you give me some suggestics to figure out this problem?

**Comment by josegonzalez** [comment]
You'll need to scale the services up. As per the [0.30.x migration guide](https://dokku.com/docs/appendices/0.30.0-migration-guide/):

> Important: Due to the removal of DOKKU_SCALE support, users with a version older than 0.25.x are heavily encouraged to upgrade to 0.29.x prior to 0.30.x. Not doing so will result in all app containers stopping on rebuild due to having no scale settings.
