### ISSUE TITLE
gpg-agent package not found

### ISSUE THREAD

**Issue by gideonmaina** [dokku/dokku#6067]
## Description of problem

Not sure whether this is a Dokku issue or not. Trying to install **v0.22.9** on Ubuntu 16.04 running on an AWS instance results in an error 
``` 
Preparing to install v0.22.9 from https://github.com/dokku/dokku.git...
--> Ensuring we have the proper dependencies
E: Unable to locate package gpg-agent

```

### Troubleshooting

1. Confirmed that **gpg-agent** was installed - `gpg-agent --version`: _gpg-agent (GnuPG) 2.1.11_
2. ```
      sudo apt update
      sudo apt install gpg-agent
     ```

**Comment by josegonzalez** [comment]
Ubuntu 16.04 probably doesn't have apt repositories anymore - it's not supported by Ubuntu.

That version is also quite old, so I won't be supporting it either. Please use a modern version of Ubuntu (22.04?) and the latest version of Dokku. Thanks.
