### ISSUE TITLE
Add ability to add environment variables to Dokku managed cron

### ISSUE THREAD

**Issue by RyanTG** [dokku/dokku#6117]
## High Level Plan

- Add a `:set` subcommand to the `cron` plugin that takes a `mailto` global setting
- Inject the mailto property into the template during generation only if there is a value

### Description of feature

For example, it would be useful to be able to add MAILTO to the Dokku managed cron.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. This will be released in the next minor.
