### ISSUE TITLE
Support custom docker build commands.

### ISSUE THREAD

**Issue by knpwrs** [dokku/dokku#6128]
### Description of feature

I may have missed this in the docs, but it would be great to support custom docker build commands. For instance, I build my app (currently hosted on Kubernetes) using https://depot.dev/. The `depot` cli is a drop-in replacement for the Docker CLI. Another example could be building an image with https://podman.io/.

**Comment by josegonzalez** [comment]
You can either:

- Create a [custom builder plugin](https://dokku.com/docs/deployment/builders/builder-management/#custom-builders) that builds your app however you want.
- Use a wrapper for `docker`
    - Create `/usr/local/bin/docker` and have it do what you need it to when calling `docker image build`
    - Set the `DOCKER_BIN` env var in `/etc/default/dokku` to a path to an alternative docker wrapper that does what you need for `docker image build`.

The wrapper option was prototyped for `podman` support and should mostly work (if it doesn't, we can fix that).

Hope that helps.

**Comment by josegonzalez** [comment]
Aside, `depot` is not a drop-in replacement for the `docker` cli, just for image builds:

```
josediazgonzalez@Joses-MacBook-Pro dokku % depot container ls
Error: unknown command "container" for "depot"
Run 'depot --help' for usage.
josediazgonzalez@Joses-MacBook-Pro dokku % depot --help
Depot CLI

Usage:
  depot <command> [flags]
  depot [command]

Available Commands:
  bake             Build from a file
  build            Start a build
  cache            Operations for the Depot project cache
  completion       Generate the autocompletion script for the specified shell
  configure-docker Configure Docker to use Depot for builds
  help             Help about any command
  init             Create a `depot.json` project config
  list             Display depot project and build information
  login            Authenticate the Depot CLI
  logout           Clear authentication token

Flags:
  -h, --help      help for depot
      --version   Print the version and exit

Use "depot [command] --help" for more information about a command.
```

**Comment by josegonzalez** [comment]
Chucking something like the following into `/usr/local/bin/docker` and making it executable should work for your use case.

```shell
#!/usr/bin/env bash
set -eo pipefail
[[ $TRACE ]] && set -x

main() {
  declare desc="re-runs docker commands as sudo"
  declare COMMAND="$1" SUBCOMMAND="$2"
  local DOCKER_BIN=""
  if [[ -x "/usr/bin/docker" ]]; then
    DOCKER_BIN="/usr/bin/docker"
  fi

  if [[ -z "$DOCKER_BIN" ]]; then
    echo "!   No docker binary found" 1>&2
    exit 1
  fi

  local DEPOT_BIN="$HOME/.depot/bin/depot"
  if [[ -x "$DEPOT_BIN" ]]; then
    echo "!   No docker binary found" 1>&2
    exit 1
  fi

  if [[ "$COMMAND" == "image" ]] && [[ "$SUBCOMMAND" == "build" ]]; then
    shift 1
    exec sudo -E "$DEPOT_BIN" "$@"
  fi

  sudo -E "$DOCKER_BIN" "$@"
}

main "$@"
```

**Comment by knpwrs** [comment]
Awesome, thank you!
