### ISSUE TITLE
migration to herokuish-20 failed.

### ISSUE THREAD

**Issue by l2radamanthys** [dokku/dokku#6142]
### Description of problem

Following the death of herokuish-18 two weeks ago, the deployment for Python apps broke. I'm trying to migrate from herokuish-18 to herokuish-20, but the health check tests are failing, and I'm not understanding why.

```
Running healthcheck name='default' type='uptime' uptime=30                      
remote:  !     Error for healthcheck name='default', output: state=restarting                  
remote:  !     Failure in name='default': container has restarted 8 times                      
1eb161a71bca4a7c599b09a427c30f70f9601a9142067d0f26fa55096613dba9
remote:  !     Could not start due to 1 failed checks (web.1)
=====> Start of wernher container output (web.1)
=====> End of wernher container output (web.1)
=====> Start of  container output (.)
=====> End of  container output (.)
remote: parallel: This job failed:
remote: /var/lib/dokku/plugins/available/scheduler-docker-local/bin/scheduler-deploy-process-container wernher herokuish dokku/wernher:latest latest web 1 1 
```

Is there a way to set the herokuish-18 Buildpack to a specific version? Since the last herokuish update (2 weeks ago), no Python 3.8.x version works anymore, and that's the version my project was using. I'm facing some bad news.

I've tried things without success, like...

dokku buildpacks:set-property wernher stack gliderlabs/herokuish:v0.5.42
dokku buildpacks:set wernher https://github.com/heroku/heroku-buildpack-python#v232

### dokku report $APP_NAME

dokku report wernher
-----> uname: Linux enjambre2022 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           1971         278         635          37        1056        1463
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           24.0.5
        API version:       1.43
        Go version:        go1.20.6
        Git commit:        ced0996
        Built:             Fri Jul 21 20:35:23 2023
        OS/Arch:           linux/amd64
        Context:           default
       
       Server: Docker Engine - Community
        Engine:
         Version:          24.0.5
         API version:      1.43 (minimum version 1.12)
         Go version:       go1.20.6
         Git commit:       a61e2b4
         Built:            Fri Jul 21 20:35:23 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.22
         GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
        runc:
         Version:          1.1.8
         GitCommit:        v1.1.8-0-g82f18fe
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
WARNING: No swap limit support
       Client: Docker Engine - Community
        Version:    24.0.5
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.11.2
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.20.2
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
         scan: Docker Scan (Docker Inc.)
           Version:  v0.23.0
           Path:     /usr/libexec/docker/cli-plugins/docker-scan
       
       Server:
        Containers: 6
         Running: 6
         Paused: 0
         Stopped: 0
        Images: 8
        Server Version: 24.0.5
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
        runc version: v1.1.8-0-g82f18fe
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
        Kernel Version: 5.4.0-156-generic
        Operating System: Ubuntu 20.04.6 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 1.925GiB
        Name: enjambre2022
        ID: 2efb80de-bdb9-4e6b-8cbb-d34d03ec0b52
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 61
         Goroutines: 62
         System Time: 2023-08-22T14:57:18.033384114Z
         EventsListeners: 1
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.10.1build+e443be0
-----> herokuish version: 
 !     Herokuish image gliderlabs/herokuish:latest-22 is not available
-----> dokku version: dokku version 0.31.0
-----> plugn version: plugn: 0.13.0build+fd5297a
-----> dokku plugins: 
         00_dokku-standard    0.31.0 enabled    dokku core standard plugin
         20_events            0.31.0 enabled    dokku core events logging plugin
         app-json             0.31.0 enabled    dokku core app-json plugin
         apps                 0.31.0 enabled    dokku core apps plugin
         apt                  0.12.0 enabled    Inject deb packages into dokku based on files in project
         builder              0.31.0 enabled    dokku core builder plugin
         builder-dockerfile   0.31.0 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.31.0 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.31.0 enabled    dokku core builder-lambda plugin
         builder-null         0.31.0 enabled    dokku core builder-null plugin
         builder-pack         0.31.0 enabled    dokku core builder-pack plugin
         buildpacks           0.31.0 enabled    dokku core buildpacks plugin
cat: /var/lib/dokku/plugins/available/cache/plugin.toml: No such file or directory
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.TomlGet({0xc000080080, 0x2, 0x61e601?})
	github.com/dokku/plugn/plugn.go:30 +0x238
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc0000b2280, {0xc000080050?, 0x5, 0x5})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:210 +0x292
github.com/progrium/go-basher.ApplicationWithPath(0x0?, {0xc0000dbe60, 0x4, 0xc00008c1d0?}, 0x49bc34?, 0x1, {0xc0000b80c0, 0x18})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:83 +0x326
github.com/progrium/go-basher.Application(0x61e3a1?, {0xc0000dbe60, 0x4, 0x4}, 0x5e9740?, 0x10?)
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:64 +0x1c5
main.main()
	github.com/dokku/plugn/plugn.go:106 +0x42c
cat: /var/lib/dokku/plugins/available/cache/plugin.toml: No such file or directory
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
main.TomlGet({0xc000080080, 0x2, 0x61e601?})
	github.com/dokku/plugn/plugn.go:30 +0x238
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc0000b2280, {0xc000080050?, 0x5, 0x5})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:210 +0x292
github.com/progrium/go-basher.ApplicationWithPath(0x0?, {0xc0000dbe60, 0x4, 0xc00008c1d0?}, 0x49bc34?, 0x1, {0xc0000b80c0, 0x18})
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:83 +0x326
github.com/progrium/go-basher.Application(0x61e3a1?, {0xc0000dbe60, 0x4, 0x4}, 0x5e9740?, 0x10?)
	/go/pkg/mod/github.com/progrium/go-basher@v5.1.6+incompatible/basher.go:64 +0x1c5
main.main()
	github.com/dokku/plugn/plugn.go:106 +0x42c
         cache                      enabled    
         caddy-vhosts         0.31.0 enabled    dokku core caddy-vhosts plugin
         certs                0.31.0 enabled    dokku core certificate management plugin
         checks               0.31.0 enabled    dokku core checks plugin
         common               0.31.0 enabled    dokku core common plugin
         config               0.31.0 enabled    dokku core config plugin
         cron                 0.31.0 enabled    dokku core cron plugin
         debug                1.0.0 enabled    dokku plugin for managing trace mode
         docker-options       0.31.0 enabled    dokku core docker-options plugin
         domains              0.31.0 enabled    dokku core domains plugin
         enter                0.31.0 enabled    dokku core enter plugin
         git                  0.31.0 enabled    dokku core git plugin
         haproxy-vhosts       0.31.0 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.31.0 enabled    dokku core logs plugin
         network              0.31.0 enabled    dokku core network plugin
         nginx-vhosts         0.31.0 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.31.0 enabled    dokku core openresty-vhosts plugin
         plugin               0.31.0 enabled    dokku core plugin plugin
         ports                0.31.0 enabled    dokku core ports plugin
         postgres             1.22.0 enabled    dokku postgres service plugin
         proxy                0.31.0 enabled    dokku core proxy plugin
         ps                   0.31.0 enabled    dokku core ps plugin
         redis                1.22.0 enabled    dokku redis service plugin
         registry             0.31.0 enabled    dokku core registry plugin
         repo                 0.31.0 enabled    dokku core repo plugin
         resource             0.31.0 enabled    dokku core resource plugin
         run                  0.31.0 enabled    dokku core run plugin
         scheduler            0.31.0 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.31.0 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.31.0 enabled    dokku core scheduler-null plugin
         shell                0.31.0 enabled    dokku core shell plugin
         ssh-keys             0.31.0 enabled    dokku core ssh-keys plugin
         storage              0.31.0 enabled    dokku core storage plugin
         trace                0.31.0 enabled    dokku core trace plugin
         traefik-vhosts       0.31.0 enabled    dokku core traefik-vhosts plugin
=====> wernher app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> wernher app information
       App created at:                1692367157
       App deploy source:             wernher
       App deploy source metadata:    wernher
       App dir:                       /home/dokku/wernher
       App locked:                    false
=====> wernher builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> wernher builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> wernher builder-herokuish information
       Builder herokuish computed allowed: true                     
       Builder herokuish global allowed: true                     
       Builder herokuish allowed:                              
=====> wernher builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml               
       Builder lambda global lambdayml path: lambda.yml               
       Builder lambda lambdayml path:                          
=====> wernher builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> wernher buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       gliderlabs/herokuish:latest-20
       Buildpacks list:               https://github.com/heroku/heroku-buildpack-python#v232
       Buildpacks stack:              gliderlabs/herokuish:latest-20
=====> wernher caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.8
       Caddy letsencrypt email:                                
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR                    
       Caddy polling interval:        5s                       
       Caddy tls internal:            false                    
=====> wernher ssl information
       Ssl dir:                       /home/dokku/wernher/tls  
       Ssl enabled:                   true                     
       Ssl hostnames:                 enjambrelab.ar wernher.enjambrelab.ar
       Ssl expires at:                Sep 29 23:00:23 2023 GMT 
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Jul  1 23:00:24 2023 GMT 
       Ssl subject:                   subject=CN = wernher.enjambrelab.ar
       Ssl verified:                  self signed              
=====> wernher checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
       Checks computed wait to retire: 60                       
       Checks global wait to retire:  60                       
       Checks wait to retire:                                  
=====> wernher docker options information
       Docker options build:          --link dokku.postgres.wernher-db:dokku-postgres-wernher-db --link dokku.redis.wernher-redis:dokku-redis-wernher-redis 
       Docker options deploy:         --link dokku.postgres.wernher-db:dokku-postgres-wernher-db --link dokku.redis.wernher-redis:dokku-redis-wernher-redis --restart=on-failure:10 -v /var/lib/dokku/data/storage/wernher:/storage 
       Docker options run:            --link dokku.postgres.wernher-db:dokku-postgres-wernher-db --link dokku.redis.wernher-redis:dokku-redis-wernher-redis -v /var/lib/dokku/data/storage/wernher:/storage 
=====> wernher domains information
       Domains app enabled:           true                     
       Domains app vhosts:            wernher.enjambrelab.ar enjambrelab.ar
       Domains global enabled:        true                     
       Domains global vhosts:         enjambrelab.ar           
=====> wernher git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       d01ce350                 
       Git source image:                                       
       Git last updated at:           1691799601               
=====> wernher haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.3.0  
       Haproxy letsencrypt email:                              
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR                    
=====> wernher letsencrypt information
       Letsencrypt active:            true                     
       Letsencrypt autorenew:         true                     
       Letsencrypt computed dns provider:                          
       Letsencrypt global dns provider:                          
       Letsencrypt dns provider:                               
       Letsencrypt computed email:    rquiroga@enjambrebit.com.ar
       Letsencrypt global email:                               
       Letsencrypt email:             rquiroga@enjambrebit.com.ar
       Letsencrypt expiration:        1696028423               
       Letsencrypt computed graceperiod: 2592000                  
       Letsencrypt global graceperiod:                          
       Letsencrypt graceperiod:                                
       Letsencrypt computed lego docker args:                          
       Letsencrypt global lego docker args:                          
       Letsencrypt lego docker args:                           
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:                              
       Letsencrypt server:                                     
=====> wernher logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> wernher network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.9:5000
=====> wernher nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/wernher-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/wernher-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx computed nginx conf sigil path: nginx.conf.sigil         
       Nginx global nginx conf sigil path: nginx.conf.sigil         
       Nginx nginx conf sigil path:                            
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      600s                     
       Nginx last visited at:         1692711116               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
/var/lib/dokku/plugins/available/openresty-vhosts/command-functions: line 62: fn-openresty-error-log-path: command not found
=====> wernher openresty information
       Openresty access log format:                            
       Openresty access log path:     /var/log/openresty/wernher-access.log
       Openresty bind address ipv4:                            
       Openresty bind address ipv6:   ::                       
       Openresty client max body size:                          
       Openresty error log path:                               
       Openresty global hsts:         true                     
       Openresty computed hsts:       true                     
       Openresty hsts:                                         
       Openresty hsts include subdomains: true                     
       Openresty hsts max age:        15724800                 
       Openresty hsts preload:        false                    
       Openresty image:               dokku/openresty-docker-proxy:0.5.6
       Openresty letsencrypt email:                            
       Openresty letsencrypt server:  https://acme-v02.api.letsencrypt.org/directory
       Openresty proxy buffer size:   4096                     
       Openresty proxy buffering:     on                       
       Openresty proxy buffers:       8 4096                   
       Openresty proxy busy buffers size: 8192                     
       Openresty proxy read timeout:  60s                      
       Openresty x forwarded for value: $remote_addr             
       Openresty x forwarded port value: $server_port             
       Openresty x forwarded proto value: $scheme                  
       Openresty x forwarded ssl:                              
=====> wernher ports information
       Ports map:                     http:80:5000 https:443:5000
       Ports map detected:            http:80:5000 https:443:5000
=====> wernher proxy information
       Proxy enabled:                 true
       Proxy type:                    nginx
Error: No such object: 915a79bef156bfe8fc308355ad50936e938649330c10792350a2797682540552
Error: No such object: 3844c14a0e214d6d4a1247809146c7b107305f6a77462f32bc4bb991d01eec38
=====> wernher ps information
       Deployed:                      true
       Processes:                     2
       Ps can scale:                  false
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       false
       Status web 1:                  missing (CID: 3844c14a0e2)
       Status worker 1:               missing (CID: 915a79bef15)
=====> wernher registry information
       Registry computed image repo:      dokku/wernher
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> wernher resource information
=====> wernher scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> wernher scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local init process: true                     
       Scheduler docker local parallel schedule count:                          
=====> wernher storage information
       Storage build mounts:                                   
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/wernher:/storage 
       Storage run mounts:            -v /var/lib/dokku/data/storage/wernher:/storage 
=====> wernher traefik information
       Traefik api enabled:           false                    
       Traefik api vhost:             traefik.dokku.me         
       Traefik basic auth password:                            
       Traefik basic auth username:                            
       Traefik dashboard enabled:     false                    
       Traefik image:                 traefik:v2.10            
       Traefik letsencrypt email:                              
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR                    
       Traefik priority:        

### Additional information

App name: wernher
Python 3.8.12 + Django App.

dokku ps:inspect wernher
Error response from daemon: No such container: 3844c14a0e214d6d4a1247809146c7b107305f6a77462f32bc4bb991d01eec38
Error response from daemon: No such container: 915a79bef156bfe8fc308355ad50936e938649330c10792350a2797682540552
[]
 !     exit status 1

dokku nginx:show-config wernher
 !     No nginx.conf exists for wernher

Procfile:
web: gunicorn wernher.wsgi --log-file=- -t 600
worker: python manage.py rqworker default

### Output of failing deploy after running: dokku trace:off

```shell
git push dokku dokku-fix:master -f                                                                                                           1 ↵
Enumerando objetos: 41, listo.
Contando objetos: 100% (41/41), listo.
Compresión delta usando hasta 12 hilos
Comprimiendo objetos: 100% (28/28), listo.
Escribiendo objetos: 100% (30/30), 11.58 KiB | 2.32 MiB/s, listo.
Total 30 (delta 20), reusados 0 (delta 0), pack-reusados 0
-----> Cleaning up...
-----> Building wernher from gliderlabs/herokuish:latest-20
-----> Compatible extended app image found, skipping system package installation
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi nodejs python
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-python#v232@v232
=====> Detected Framework: Python
-----> Using Python version specified in runtime.txt
-----> Installing python-3.8.16
-----> Installing pip 23.1.2, setuptools 67.7.2 and wheel 0.40.0
-----> Installing dependencies with Pipenv 2023.2.4
       Loading .env environment variables...
       Installing dependencies from Pipfile.lock (29f5bd)...
-----> Installing SQLite3
-----> Skipping Django collectstatic since the env var DISABLE_COLLECTSTATIC is set.
       Using release configuration from last framework (Python).
-----> Discovering process types
       Procfile declares types -> web, worker
-----> Releasing wernher...
-----> Checking for predeploy task
-----> Executing predeploy task from app.json: python manage.py migrate --noinput; python manage.py collectstatic --noinput
=====> Start of wernher predeploy task (a2aa52769) output
       Operations to perform:
         Apply all migrations: admin, auth, commands, components, contenttypes, django_rq, easy_thumbnails, easyaudit, filer, history, jobs, knowledgebase, launches, products, satellites, sessions, social_django, suppliers, taggit, units
       Running migrations:
         No migrations to apply.
         Your models in app(s): 'components' have changes that are not yet reflected in a migration, and so won't be applied.
         Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
       497 static files copied to '/app/static', 3 unmodified, 517 post-processed.
=====> End of wernher predeploy task (a2aa52769) output
-----> Checking for release task
       No release task found, skipping
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
-----> Deploying wernher via the docker-local scheduler...
-----> Deploying web (count=1)
       Attempting pre-flight checks (web.1)
-----> Executing 1 healthchecks                                                        
       Running healthcheck name='default' type='uptime' uptime=30                      
remote:  !     Error for healthcheck name='default', output: state=restarting                  
remote:  !     Failure in name='default': container has restarted 8 times                      
1eb161a71bca4a7c599b09a427c30f70f9601a9142067d0f26fa55096613dba9
remote:  !     Could not start due to 1 failed checks (web.1)
=====> Start of wernher container output (web.1)
=====> End of wernher container output (web.1)
=====> Start of  container output (.)
=====> End of  container output (.)
remote: parallel: This job failed:
remote: /var/lib/dokku/plugins/available/scheduler-docker-local/bin/scheduler-deploy-process-container wernher herokuish dokku/wernher:latest latest web 1 1
To enjambrelab.ar:wernher
 ! [remote rejected] dokku-fix -> master (pre-receive hook declined)
error: falló el empuje de algunas referencias a 'enjambrelab.ar:wernher'
```

### Output of failing deploy after running: dokku trace:on

```shell
very large size
```

**Comment by josegonzalez** [comment]
This appears to be a buildpack issue. As per our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md), if you need help figuring out how to use a specific buildpack, or are having issues using multiple buildpacks, please see our [slack channels or github discussion board](https://dokku.com/docs/getting-started/where-to-get-help/#monitored-locations). 

Issues pertaining to buildpacks will be closed and/or locked.

**Comment by josegonzalez** [comment]
Aside, you can select a specific herokuish base by specifying a suffix like -18. Default would be -22.

dokku buildpacks:set-property wernher stack gliderlabs/herokuish:v0.5.42-18

Note that heroku-18 is no longer maintained by anyone, so it's usage is considered deprecated.

**Comment by l2radamanthys** [comment]
It's not a multiple buildpack issue, although it does exist. The problem lies with an embedded micro framework. This framework was compiling during the development stage (I tried removing those files and the issue persisted). Additionally, I'm facing the same problem with another distinct project where I'm not using multiple buildpacks either.

```
remote: 2023-08-16 20:53:11 (105 MB/s) - 'wkhtmltox-0.12.4_linux-generic-amd64.tar.xz' saved [14541904/14541904]        
remote: 
-----> wkhtmltox installed!        
-----> Python app detected        
-----> Using Python version specified in runtime.txt        
       !     Requested runtime 'python-3.9.17' is not available for this stack (heroku-18).        
       !     For supported versions, see: https://devcenter.heroku.com/articles/python-support        
remote:  !     Failure during app build        
remote: 2023/08/16 20:53:28 exit status 1        
remote:  !     Retagging old image b3bd7b5fdc91 as dokku/spider-backend:latest        
remote:  !     App build failed        
To XXXXXXX.com:spider-backend
 ! [remote rejected]   in-qa -> master (pre-receive hook declined)
error: failed to push some refs to 'XXXXXXX.com:spider-backend'

Exited with code exit status 
```

I'm starting to suspect that it has something to do with projects using the [apt](https://github.com/dokku-community/dokku-apt) plugin because in both cases, the two projects install specific libraries. I'll try creating a project that requires package installation to isolate the case.

**Comment by josegonzalez** [comment]
If that is using the heroku-18-based herokuish image, it's likely that heroku has deleted their sources for any downloads of compiled tools like python etc. you could try switching to the -20 to see if you can get things working there.

**Comment by l2radamanthys** [comment]
The reported issue correspond to herokuish-20

Both projects were working on herokuish-18 without issues, but it's no longer possible to compile more versions of herokuish-18. Even your suggestion of adding the suffix *-18 didn't work.  Herokuish-18 is dead :(.

**Comment by l2radamanthys** [comment]
I've managed to isolate the issue. I deleted the 'apt-packages' file (disabled dependencies), and the deployment is working. As I suspected, in the last test, the problem is related to the 'apt' plugin." 

```
git push dokku dokku-fix:master -f
Enumerando objetos: 27, listo.
Contando objetos: 100% (27/27), listo.
Compresión delta usando hasta 12 hilos
Comprimiendo objetos: 100% (17/17), listo.
Escribiendo objetos: 100% (18/18), 9.76 KiB | 2.44 MiB/s, listo.
Total 18 (delta 13), reusados 0 (delta 0), pack-reusados 0
-----> Cleaning up...
-----> Building wernher from gliderlabs/herokuish:v0.5.40-20
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> Fetching custom buildpack
-----> Python app detected
-----> Using Python version specified in runtime.txt
       !
       !     A Python security update is available! Upgrade as soon as possible to: python-3.8.17
       !     See: https://devcenter.heroku.com/articles/python-runtimes
       !
-----> Installing python-3.8.12
-----> Installing pip 23.2.1, setuptools 68.0.0 and wheel 0.41.0
-----> Installing dependencies with Pipenv 2023.7.23
       Loading .env environment variables...
       Installing dependencies from Pipfile.lock (442b29)...
-----> Installing SQLite3
-----> Skipping Django collectstatic since the env var DISABLE_COLLECTSTATIC is set.
-----> Discovering process types
       Procfile declares types -> web, worker
-----> Releasing wernher...
-----> Checking for predeploy task
-----> Executing predeploy task from app.json: python manage.py migrate --noinput; python manage.py collectstatic --noinput
=====> Start of wernher predeploy task (00ed336cb) output
       Operations to perform:
         Apply all migrations: admin, auth, commands, components, contenttypes, django_rq, easy_thumbnails, easyaudit, filer, history, jobs, knowledgebase, launches, products, satellites, sessions, social_django, suppliers, taggit, units
       Running migrations:
         No migrations to apply.
         Your models in app(s): 'components' have changes that are not yet reflected in a migration, and so won't be applied.
         Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
       497 static files copied to '/app/static', 3 unmodified, 517 post-processed.
=====> End of wernher predeploy task (00ed336cb) output
-----> Checking for release task
       No release task found, skipping
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
-----> Deploying wernher via the docker-local scheduler...
-----> Deploying web (count=1)
       Attempting pre-flight checks (web.1)
-----> Executing 1 healthchecks                                                        
       Running healthcheck name='default' type='uptime' uptime=30                      
       Healthcheck succeeded name='default'                                            
       All checks successful (web.1)
=====> Start of wernher container output (web.1)
       [2023-08-22 23:28:06 +0000] [13] [INFO] Starting gunicorn 20.1.0
       [2023-08-22 23:28:06 +0000] [13] [INFO] Listening at: http://0.0.0.0:5000 (13)
       [2023-08-22 23:28:06 +0000] [13] [INFO] Using worker: sync
       [2023-08-22 23:28:06 +0000] [211] [INFO] Booting worker with pid: 211
=====> End of wernher container output (web.1)
       Scheduling old container shutdown in 60 seconds (web.1)
=====> Triggering early nginx proxy rebuild
-----> Ensuring network configuration is in sync for wernher
remote: Error: No such object: 915a79bef156bfe8fc308355ad50936e938649330c10792350a2797682540552
-----> Configuring enjambrelab.ar...(using built-in template)
-----> Configuring wernher.enjambrelab.ar...(using built-in template)
-----> Creating https nginx.conf
       Enabling HSTS
       Reloading nginx
-----> Deploying worker (count=1)
       Attempting pre-flight checks (worker.1)
-----> Executing 1 healthchecks                                                        
       Running healthcheck name='default' type='uptime' uptime=30                      
       Healthcheck succeeded name='default'                                            
       All checks successful (worker.1)
=====> Start of wernher container output (worker.1)
       23:28:45 Worker rq:worker:8ea8adcc49c441c589573d663cde2172: started, version 1.11.1
       23:28:45 Subscribing to channel rq:pubsub:8ea8adcc49c441c589573d663cde2172
       23:28:45 *** Listening on default...
       23:28:45 Cleaning registries for queue: default
=====> End of wernher container output (worker.1)
       Scheduling old container shutdown in 60 seconds (worker.1)
-----> Running post-deploy
remote:  !     Detected IPv4 domain name with nginx proxy enabled.
remote:  !     Ensure the default nginx site is removed before continuing.
-----> Ensuring network configuration is in sync for wernher
-----> Configuring enjambrelab.ar...(using built-in template)
-----> Configuring wernher.enjambrelab.ar...(using built-in template)
-----> Creating https nginx.conf
       Enabling HSTS
       Reloading nginx
-----> Renaming containers
       Renaming container wernher.web.1.upcoming-16003 (682e4ac90095) to wernher.web.1
       Renaming container wernher.worker.1.upcoming-17753 (b6e7614fafdb) to wernher.worker.1
-----> Checking for postdeploy task
       No postdeploy task found, skipping
-----> Updated schedule file
-----> Shutting down old containers in 60 seconds
=====> Application deployed:
       http://XXXXXXXXXXX
       https://XXXXXXXXXXX


To XXXXXX:wernher
   d01ce35..4ca63a8  dokku-fix -> mastergit push dokku dokku-fix:master -f
```

I really thought it was a herokuish-20 issue, but I guess I have an outdated plugin or something else.

Thank you so much again for your help. This was driving me crazy. I didn't prioritize the migration because herokuish-18 was supposed to be fully removed only in May 2024."
