### ISSUE TITLE
Wrong apps served after Docker upgrade

### ISSUE THREAD

**Issue by benr77** [dokku/dokku#6192]
### Description of problem

On my Ubuntu server, if Docker itself is upgraded as part of a normal `apt upgrade` then Dokku starts serving the wrong apps to the wrong domains - i.e. the routing is all messed up.

I've read other bug reports here that are pointing out similar behaviour, but they are from 3 years ago or more, so wanted to report that this is still an issue using the latest Dokku 0.31.3.

I can fix it with `dokku ps:restart --all` but this still takes a while, and during this period the wrong sites are served. From a web hosting client's point of view, having someone elses site showing under your domain is really not acceptable.

I understand that `dokku ps:restore` is faster than a restart, but there is no `--all` option.

Is there a known workaround for this that I've missed?

Happy to help test or debug etc.

Thank you.

### Steps to reproduce

Have multiple apps configured. Upgrade Docker via the package manager (or I guess just reboot). For a period, the wrong apps are served.

### dokku report $APP_NAME

Not relevant as it is regarding all configured apps.

**Comment by josegonzalez** [comment]
On restart, docker will restart all containers and potentially give them new IP addresses. This is a known problem and nothing we can do anything about. As such, dokku sets up a command to post docker restart called "dokku-restore" that resets all config. Sometimes this takes a few minutes.

You have a few alternatives:

- switch to another proxy implementation, such as openresty (which supports all the same config as the nginx one) that doesn't exhibit this behavior 
- enable docker's live-restore behavior that ensures containers are not restarted when docker is upgraded.

One other option is for us to implement a docker-based DNS server for nginx routing to containers based on names/labels. If you're interested in that, please let me know if you'd like to [sponsor the work](https://github.com/dokku/.github/blob/master/SPONSORING.md). It's probably somewhere around 15 hours of work.

Hope that helps.

**Comment by benr77** [comment]
Thank you for the explanation. I will investigate the options you have suggested.
