### ISSUE TITLE
Nginx template http2 configuration is deprecated

### ISSUE THREAD

**Issue by madwort** [dokku/dokku#6218]
### Description of problem

Saw this warning:

```
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /home/dokku/actions-registry/nginx.conf:17
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /home/dokku/actions-registry/nginx.conf:18
```

### Steps to reproduce

Deploy with nginx/1.25.2

### dokku report $APP_NAME

=====> actions-registry nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/actions-registry-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/actions-registry-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1695657192
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:

### Additional information

https://forum.hestiacp.com/t/nginx-1-25-1-listen-http2-directive-is-deprecated/9816 

```
server {
    listen      90.91.45.3:443 ssl http2;
```

has been deprecated in favour of 

```
server {
    listen      90.91.45.3:443 ssl;
    http2 on;

```

**Comment by josegonzalez** [comment]
Can you show the entire output of `dokku report actions-registry`?

**Comment by josegonzalez** [comment]
@madwort if you can post that output, that would be awesome. The output contains a bunch of context I need in order to replicate this issue. If I can't replicate it - and I can't on the current Dokku server - I can't really mark this ticket as fixed...

**Comment by josegonzalez** [comment]
Looking at this, it seems as if this is related to nginx 1.25.1, and the `http2` directive is [_only_ available at that version and up](https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2).

I then looked at the nginx versions available in supported OS releases:

- Ubuntu LTS
  - Focal (20.04): [nginx 1.18.0](https://packages.ubuntu.com/focal/nginx)
  - Jammy (22.04): [nginx 1.18.0](https://packages.ubuntu.com/jammy/nginx)
- Debian oldstable/stable:
  - Bullseye (oldstable): [nginx 1.18.0](https://packages.debian.org/bullseye/nginx)
  - Bookworm (stable): [nginx 1.22.1](https://packages.debian.org/bookworm/nginx)

So at least on stable, users can't get this warning (which is just that, a warning).

For the latest versions of each OS:

- Ubuntu Mantic (23.10): [nginx 1.24.0](https://packages.ubuntu.com/mantic/nginx)
- Debian Trixie (testing): [nginx 1.24.0](https://packages.debian.org/trixie/nginx)
- Debian Sid (unstable): [nginx 1.24.0](https://packages.debian.org/sid/nginx)

So even on the absolute latest, folks still can't get this warning.

---

I realize a user _can_ install nginx via upstream packages to get the absolute latest - and you shouldn't feel punished for doing so! - but atm I don't have the bandwidth to support that sort of config in a test environment. I also don't want to add another `if` to that config at this time (it's hard to read).

I'm going to close this for now, but will revisit it when Ubuntu/Debian get a new release, or when nginx does a release that removes the `http2` directive.
