### ISSUE TITLE
Rails app assets precompile failed due to missing environment variables

### ISSUE THREAD

**Issue by barrychc** [dokku/dokku#622]
Hi there,

I'm trying to migrate a rails app from heroku to dokku environment created by digital ocean pre-built image. 

I encountered assets precompile failure due to missing environment variables. After I set those variables using dokku config:set commands, I still face the same problem even though they can be listed with the dokku config command. 

Any suggestion on troubleshooting the problem? Thanks very much.

**Comment by ypadlyak** [comment]
I've encountered the same issue.  https://github.com/motin/dokku-user-env-compile seems to be broken.

**Comment by michaelshobbs** [comment]
This issue is almost two years old. 

This functionality is now handled by the core build-env plugin now. Anything that is defined in the app config is injected into the build environment. Please upgrade and open a new issue if you're still running into a problem.

**Comment by ypadlyak** [comment]
@michaelshobbs thanks! Is there any documentation on how to use core build-env?

**Comment by michaelshobbs** [comment]
From the documentation....http://dokku.viewdocs.io/dokku/configuration-management/

> The variables are available both at run time and during the application build/compilation step for buildpack-based deploys. For security reasons - and as per docker recommendations - Dockerfile-based deploys have variables available only during runtime, as noted in this issue.

**Comment by ypadlyak** [comment]
I'm not using Dockerfile based deploy. I'm using ruby buildpack.

**Comment by michaelshobbs** [comment]
Great! Read the first sentence of the quote...

**Comment by ypadlyak** [comment]
Oh, yes.. I missed that.

The problem is that I try to link .env file from the storage http://dokku.viewdocs.io/dokku/dokku-storage/ ,but is is linked too late (I use postdeploy hook http://dokku.viewdocs.io/dokku/deployment/deployment-tasks/ for the linking ) . Is there any way to link before buildpack is run?

**Comment by michaelshobbs** [comment]
Please open a new issue.
