### ISSUE TITLE
404 link in documentation

### ISSUE THREAD

**Issue by gregsadetsky** [dokku/dokku#6229]
### Description of problem

on the page

https://dokku.com/docs~v0.4.14/application-deployment/

there is a hyperlink to the latest documentation version:

<img width="454" alt="image" src="https://github.com/dokku/dokku/assets/1017304/4b549f55-ae2e-4e3b-a828-1207173a8f19">

that link points to

https://dokku.com/docs/application-deployment/

which is a 404 link. it should link instead to

https://dokku.com/docs/deployment/application-deployment/

### Steps to reproduce

go to https://dokku.com/docs~v0.4.14/application-deployment/ and click the link in the header

### dokku report $APP_NAME

n/a

**Comment by gregsadetsky** [comment]
a somewhat related, but different, issue:

on the same https://dokku.com/docs~v0.4.14/application-deployment/ page, picking any but the "latest" version in the version dropdown:

<img width="235" alt="image" src="https://github.com/dokku/dokku/assets/1017304/f83817de-f8c2-4f0d-96f8-df1211a12d85">

leads to an empty page. i.e. clicking v.0.31.4 leads to https://dokku.com/docs~v0.31.4/ which is an empty page. all other versions show a similar empty Home page

**Comment by Sesay081** [comment]
Code 266.0

**Comment by josegonzalez** [comment]
Just a note: you're _probably_ gonna have a bad time using old versions like `0.4.x` and should upgrade.

The dropdown menu will likely never lead to the correct page at another version - that menu is managed by readthedocs, so I think it will always just drop you to the homepage.

I'll see if I can fix the "click here to go to latest" header link, and also make it so you don't get directed to a blank page.

**Comment by josegonzalez** [comment]
Thanks for reporting. I've fixed the issues I can, and the others... folks are just gonna have to live with I guess.
