### ISSUE TITLE
Keep having "Welcome to nginx" after deploying my rails app

### ISSUE THREAD

**Issue by GXcode95** [dokku/dokku#6298]
### Description of problem

Hi, i'm trying to deploy a rails app with dokku for the first time.

Everything went good for installing dokku on a vps (arm).
I deployed my app without problem pushing to dokku remote.
My containers are running, my app rails is working as intended.
But when i try to connect to my domain http://dokkur7.xyz/ i get the "Nginx welcome page", it's not interacting with my rails app :/.

### Steps to reproduce

followed this guide
guide https://railsnotes.xyz/blog/deploying-ruby-on-rails-with-dokku-redis-sidekiq-arm-docker-hetzner#before-we-get-started--why-even-bother-with-dokku

### dokku report $APP_NAME

-----> uname: Linux dokku-ubuntu-4gb-nbg1-1 5.15.0-87-generic #97-Ubuntu SMP Tue Oct 3 09:52:42 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:            3813         673         482          21        2658        2933
       Swap:              0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           24.0.6
        API version:       1.43
        Go version:        go1.20.7
        Git commit:        ed223bc
        Built:             Mon Sep  4 12:31:57 2023
        OS/Arch:           linux/arm64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          24.0.6
         API version:      1.43 (minimum version 1.12)
         Go version:       go1.20.7
         Git commit:       1a79695
         Built:            Mon Sep  4 12:31:57 2023
         OS/Arch:          linux/arm64
         Experimental:     false
        containerd:
         Version:          1.6.24
         GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
        runc:
         Version:          1.1.9
         GitCommit:        v1.1.9-0-gccaecfc
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client: Docker Engine - Community
        Version:    24.0.6
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.11.2
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.21.0
           Path:     /usr/libexec/docker/cli-plugins/docker-compose

       Server:
        Containers: 4
         Running: 4
         Paused: 0
         Stopped: 0
        Images: 10
        Server Version: 24.0.6
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
        runc version: v1.1.9-0-gccaecfc
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-87-generic
        Operating System: Ubuntu 22.04.3 LTS
        OSType: linux
        Architecture: aarch64
        CPUs: 2
        Total Memory: 3.724GiB
        Name: dokku-ubuntu-4gb-nbg1-1
        ID: 8d32384e-3dcd-42f3-b7ef-032ef22727ae
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 50
         Goroutines: 51
         System Time: 2023-10-22T18:08:02.527385389Z
         EventsListeners: 0
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> herokuish version:
 !     herokuish not supported on arm64 architecture
-----> dokku version: dokku version 0.32.0
-----> dokku-event-listener version: 0.15.0build+5268732
-----> dokku-update version: dokku-update 0.7.2
-----> docker-container-healthchecker version: 0.7.2
-----> docker-image-labeler version: 0.6.1build+c6e15a9
-----> git version: git version 2.34.1
-----> lambda-builder version:        0.5.0
-----> netrc version: 0.7.1build+677c033
 !     pack binary is not available
-----> plugn version: plugn: 0.13.0build+fd5297a
-----> sigil version: 0.10.1build+e443be0
-----> sshcommand version: sshcommand 0.17.1
-----> dokku plugins:
         00_dokku-standard    0.32.0 enabled    dokku core standard plugin
         20_events            0.32.0 enabled    dokku core events logging plugin
         app-json             0.32.0 enabled    dokku core app-json plugin
         apps                 0.32.0 enabled    dokku core apps plugin
         builder              0.32.0 enabled    dokku core builder plugin
         builder-dockerfile   0.32.0 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.32.0 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.32.0 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.32.0 enabled    dokku core builder-nixpacks plugin
         builder-null         0.32.0 enabled    dokku core builder-null plugin
         builder-pack         0.32.0 enabled    dokku core builder-pack plugin
         buildpacks           0.32.0 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.32.0 enabled    dokku core caddy-vhosts plugin
         certs                0.32.0 enabled    dokku core certificate management plugin
         checks               0.32.0 enabled    dokku core checks plugin
         common               0.32.0 enabled    dokku core common plugin
         config               0.32.0 enabled    dokku core config plugin
         cron                 0.32.0 enabled    dokku core cron plugin
         docker-options       0.32.0 enabled    dokku core docker-options plugin
         domains              0.32.0 enabled    dokku core domains plugin
         enter                0.32.0 enabled    dokku core enter plugin
         git                  0.32.0 enabled    dokku core git plugin
         haproxy-vhosts       0.32.0 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.3 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.32.0 enabled    dokku core logs plugin
         network              0.32.0 enabled    dokku core network plugin
         nginx-vhosts         0.32.0 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.32.0 enabled    dokku core openresty-vhosts plugin
         plugin               0.32.0 enabled    dokku core plugin plugin
         ports                0.32.0 enabled    dokku core ports plugin
         postgres             1.36.0 enabled    dokku postgres service plugin
         proxy                0.32.0 enabled    dokku core proxy plugin
         ps                   0.32.0 enabled    dokku core ps plugin
         redis                1.37.1 enabled    dokku redis service plugin
         registry             0.32.0 enabled    dokku core registry plugin
         repo                 0.32.0 enabled    dokku core repo plugin
         resource             0.32.0 enabled    dokku core resource plugin
         run                  0.32.0 enabled    dokku core run plugin
         scheduler            0.32.0 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.32.0 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.32.0 enabled    dokku core scheduler-null plugin
         shell                0.32.0 enabled    dokku core shell plugin
         ssh-keys             0.32.0 enabled    dokku core ssh-keys plugin
         storage              0.32.0 enabled    dokku core storage plugin
         trace                0.32.0 enabled    dokku core trace plugin
         traefik-vhosts       0.32.0 enabled    dokku core traefik-vhosts plugin
=====> test-rails app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> test-rails app information
       App created at:                1697976231
       App deploy source:             git-push
       App deploy source metadata:    285a73ec48196d6cbe19eb2a41349a45f2312f4e
       App dir:                       /home/dokku/test-rails
       App locked:                    false
=====> test-rails builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> test-rails builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> test-rails builder-herokuish information
       Builder herokuish computed allowed: false
       Builder herokuish global allowed: false
       Builder herokuish allowed:
=====> test-rails builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> test-rails builder-nixpacks information
       Builder nixpacks computed nixpackstoml path: nixpacks.toml
       Builder nixpacks global nixpackstoml path: nixpacks.toml
       Builder nixpacks nixpackstoml path:
       Builder nixpacks computed no cache: false
       Builder nixpacks global no cache: false
       Builder nixpacks no cache:
=====> test-rails builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> test-rails buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-22
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> test-rails caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.8
       Caddy letsencrypt email:
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR
       Caddy polling interval:        5s
       Caddy tls internal:            false
=====> test-rails ssl information
       Ssl dir:                       /home/dokku/test-rails/tls
       Ssl enabled:                   false
       Ssl hostnames:
       Ssl expires at:
       Ssl issuer:
       Ssl starts at:
       Ssl subject:
       Ssl verified:
=====> test-rails checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> test-rails docker options information
       Docker options build:          --link dokku.postgres.test-rails-db:dokku-postgres-test-rails-db --link dokku.redis.test-rails-redis:dokku-redis-test-rails-redis
       Docker options deploy:         --link dokku.postgres.test-rails-db:dokku-postgres-test-rails-db --link dokku.redis.test-rails-redis:dokku-redis-test-rails-redis --restart=on-failure:10
       Docker options run:            --link dokku.postgres.test-rails-db:dokku-postgres-test-rails-db --link dokku.redis.test-rails-redis:dokku-redis-test-rails-redis
=====> test-rails domains information
       Domains app enabled:           true
       Domains app vhosts:            dokkur7.xyz
       Domains global enabled:        true
       Domains global vhosts:         78.47.123.141
=====> test-rails git information
       Git deploy branch:             main
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:
       Git source image:
       Git last updated at:           1697996802
=====> test-rails haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.3.0
       Haproxy letsencrypt email:
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR
Could not open file or uri for loading certificate from /home/dokku/test-rails/tls/server.crt
20A0F79AFFFF0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file
20A0F79AFFFF0000:error:80000002:system library:file_open:No such file or directory:../providers/implementations/storemgmt/file_store.c:267:calling stat(/home/dokku/test-rails/tls/server.crt)
Unable to load certificate
=====> test-rails letsencrypt information
       Letsencrypt active:            false
       Letsencrypt autorenew:         false
       Letsencrypt computed dns provider:
       Letsencrypt global dns provider:
       Letsencrypt dns provider:
       Letsencrypt computed email:    xavier.grenouillet@gmail.com
       Letsencrypt global email:
       Letsencrypt email:             xavier.grenouillet@gmail.com
       Letsencrypt expiration:        1697932800
       Letsencrypt computed graceperiod: 2592000
       Letsencrypt global graceperiod:
       Letsencrypt graceperiod:
       Letsencrypt computed lego docker args:
       Letsencrypt global lego docker args:
       Letsencrypt lego docker args:
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:
       Letsencrypt server:
=====> test-rails logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> test-rails network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.5:3000
=====> test-rails nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/test-rails-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/test-rails-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1697997971
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> test-rails openresty information
       Openresty access log format:
       Openresty access log path:     /var/log/nginx/test-rails-access.log
       Openresty bind address ipv4:
       Openresty bind address ipv6:   ::
       Openresty client max body size:
       Openresty error log path:      /var/log/nginx/test-rails-error.log
       Openresty global hsts:         true
       Openresty computed hsts:       true
       Openresty hsts:
       Openresty hsts include subdomains: true
       Openresty hsts max age:        15724800
       Openresty hsts preload:        false
       Openresty image:               dokku/openresty-docker-proxy:0.5.6
       Openresty letsencrypt email:
       Openresty letsencrypt server:  https://acme-v02.api.letsencrypt.org/directory
       Openresty proxy buffer size:   4096
       Openresty proxy buffering:     on
       Openresty proxy buffers:       8 4096
       Openresty proxy busy buffers size: 8192
       Openresty proxy read timeout:  60s
       Openresty x forwarded for value: $remote_addr
       Openresty x forwarded port value: $server_port
       Openresty x forwarded proto value: $scheme
       Openresty x forwarded ssl:
=====> test-rails ports information
       Ports map:                     http:80:3000
       Ports map detected:            http:3000:3000
=====> test-rails proxy information
       Proxy enabled:                 true
       Proxy type:                    http:80:3000
=====> test-rails ps information
       Deployed:                      true
       Processes:                     2
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 4a46fa79bfe)
       Status worker 1:               running (CID: 5ba9c6594d5)
=====> test-rails registry information
       Registry computed image repo:      dokku/test-rails
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> test-rails resource information
=====> test-rails scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> test-rails scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> test-rails storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:
=====> test-rails traefik information
       Traefik api enabled:           false
       Traefik api vhost:             traefik.dokku.me
       Traefik basic auth password:
       Traefik basic auth username:
       Traefik dashboard enabled:     false
       Traefik image:                 traefik:v2.10
       Traefik letsencrypt email:
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR
       Traefik priority:

### Additional information

Dockerfile content:
```
# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.2.2
FROM ruby:$RUBY_VERSION-slim as base

# Rails app lives here
WORKDIR /rails

# Set production environment
ENV RAILS_ENV="production" \
    BUNDLE_WITHOUT="development:test" \
    BUNDLE_DEPLOYMENT="1"

# Update gems and bundler
RUN gem update --system --no-document && \
    gem install -N bundler


# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential libpq-dev

# Install application gems
COPY --link Gemfile Gemfile.lock ./
RUN bundle install && \
    bundle exec bootsnap precompile --gemfile && \
    rm -rf ~/.bundle/ $BUNDLE_PATH/ruby/*/cache $BUNDLE_PATH/ruby/*/bundler/gems/*/.git

# Copy application code
COPY --link . .

# Precompile bootsnap code for faster boot times
RUN bundle exec bootsnap precompile app/ lib/

# Precompiling assets for production without requiring secret RAILS_MASTER_KEY
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile


# Final stage for app image
FROM base

# Install packages needed for deployment
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Copy built artifacts: gems, application
COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build /rails /rails

# Run and own only the runtime files as a non-root user for security
RUN useradd rails --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp
USER rails:rails

# Deployment options
ENV LD_PRELOAD="libjemalloc.so.2" \
    MALLOC_CONF="dirty_decay_ms:1000,narenas:2,background_thread:true" \
    RUBY_YJIT_ENABLE="1"

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["./bin/rails", "server"]
```

my nginx.conf:
```
server {
  listen      [::]:3000;
  listen      3000;
  server_name test-rails.78.47.123.141.sslip.io;
  access_log  /var/log/nginx/test-rails-access.log;
  error_log   /var/log/nginx/test-rails-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/wasm application/json application/xml application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://test-rails-3000;
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_buffer_size 4096;
    proxy_buffering on;
    proxy_buffers 8 4096;
    proxy_busy_buffers_size 8192;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-Start $msec;

  }



  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }
  include /home/dokku/test-rails/nginx.conf.d/*.conf;

}

upstream test-rails-3000 {

  server 172.17.0.4:3000;
}
```

the ouput of `dokku port:list`
```
dokku ports:list test-rails
-----> Port mappings for test-rails
    -----> scheme  host port  container port
    http           80         3000
```

**Comment by josegonzalez** [comment]
Your app uses an EXPOSE directive in the Dockerfile, so that's the thing your nginx is configured to listen on. If you'd like it to listen on port 80, you can remap the app ports like so:

dokku ports:set $APP http:80:3000

**Comment by GXcode95** [comment]
> Your app uses an EXPOSE directive in the Dockerfile, so that's the thing your nginx is configured to listen on. If you'd like it to listen on port 80, you can remap the app ports like so:
> 
> dokku ports:set $APP http:80:3000

I already did that, the output of dokku port:list

dokku ports:list test-rails
-----> Port mappings for test-rails
    -----> scheme  host port  container port
    http           80         3000

So i'm already redirecting from port 80 on my server to port 3000 on my container , or am i missing something ?

**Comment by josegonzalez** [comment]
What is the domain name you are using to access the app?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response in a month. If you're still having this issue, please feel free to respond and we'll dig in further.
