### ISSUE TITLE
Containers disappears

### ISSUE THREAD

**Issue by jesperordrup** [dokku/dokku#6321]
### Description of problem

From https://www.reddit.com/r/dokku/comments/17kxfy8/comment/k7ajxto/?context=3

I've seen it a few times. The container is running fine for days. Suddenly site is down. When I check

Docker ps -a

.. the container is gone.

Happens to several different setups and on different machines

Ex 1. A sveltkit nodejs app build with herokuish on server using GitHub actions Ex 2. An Umbraco .net app. Image not build on server but in public GitHub runner.

I think that I've seen a new container automatically created once or twice - after a loooong downtime.

### Steps to reproduce

I cant provide this as I dont know how to reproduce. It happens

### dokku report $APP_NAME

````
report fof
-----> uname: Linux frontend 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                      total        used        free      shared  buff/cache   available
       Mem:            3827        1584         875          21        1367        1915
       Swap:              0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.21
        API version:       1.41
        Go version:        go1.18.7
        Git commit:        baeda1f
        Built:             Tue Oct 25 18:01:58 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.21
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.18.7
         Git commit:       3056208
         Built:            Tue Oct 25 17:59:49 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.10
         GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
        runc:
         Version:          1.1.4
         GitCommit:        v1.1.4-0-g5fd4c4d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
         compose: Docker Compose (Docker Inc., v2.12.2)
         scan: Docker Scan (Docker Inc., v0.21.0)
       
       Server:
        Containers: 10
         Running: 10
         Paused: 0
         Stopped: 0
        Images: 134
        Server Version: 20.10.21
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
        runc version: v1.1.4-0-g5fd4c4d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
         cgroupns
        Kernel Version: 5.15.0-58-generic
        Operating System: Ubuntu 22.04.1 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 3
        Total Memory: 3.738GiB
        Name: frontend
        ID: 7OR3:5NSY:KHKD:IPQC:7KBO:D2QQ:XSDB:33YJ:WWR3:QGCP:DXUA:C7WL
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.34.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: v0.5.40
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v202
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v223
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v227
         heroku-buildpack-go        v169
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.28.4
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.28.4 enabled    dokku core standard plugin
         20_events            0.28.4 enabled    dokku core events logging plugin
         app-json             0.28.4 enabled    dokku core app-json plugin
         apps                 0.28.4 enabled    dokku core apps plugin
         builder              0.28.4 enabled    dokku core builder plugin
         builder-dockerfile   0.28.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.28.4 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.28.4 enabled    dokku core builder-lambda plugin
         builder-null         0.28.4 enabled    dokku core builder-null plugin
         builder-pack         0.28.4 enabled    dokku core builder-pack plugin
         buildpacks           0.28.4 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.28.4 enabled    dokku core caddy-vhosts plugin
         certs                0.28.4 enabled    dokku core certificate management plugin
         checks               0.28.4 enabled    dokku core checks plugin
         common               0.28.4 enabled    dokku core common plugin
         config               0.28.4 enabled    dokku core config plugin
         cron                 0.28.4 enabled    dokku core cron plugin
         docker-options       0.28.4 enabled    dokku core docker-options plugin
         domains              0.28.4 enabled    dokku core domains plugin
         enter                0.28.4 enabled    dokku core enter plugin
         git                  0.28.4 enabled    dokku core git plugin
         letsencrypt          0.18.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.28.4 enabled    dokku core logs plugin
         network              0.28.4 enabled    dokku core network plugin
         nginx-vhosts         0.28.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.28.4 enabled    dokku core plugin plugin
         proxy                0.28.4 enabled    dokku core proxy plugin
         ps                   0.28.4 enabled    dokku core ps plugin
         registry             0.28.4 enabled    dokku core registry plugin
         repo                 0.28.4 enabled    dokku core repo plugin
         resource             0.28.4 enabled    dokku core resource plugin
         run                  0.28.4 enabled    dokku core run plugin
         scheduler            0.28.4 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.28.4 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.28.4 enabled    dokku core scheduler-null plugin
         shell                0.28.4 enabled    dokku core shell plugin
         ssh-keys             0.28.4 enabled    dokku core ssh-keys plugin
         storage              0.28.4 enabled    dokku core storage plugin
         trace                0.28.4 enabled    dokku core trace plugin
         traefik-vhosts       0.28.4 enabled    dokku core traefik-vhosts plugin
=====> fof app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> fof app information
       App created at:                1698746148
       App deploy source:             fof
       App deploy source metadata:    fof
       App dir:                       /home/dokku/fof
       App locked:                    false
=====> fof builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> fof builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> fof builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml               
       Builder lambda global lambdayml path: lambda.yml               
       Builder lambda lambdayml path:                          
=====> fof builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> fof buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> fof ssl information
       Ssl dir:                       /home/dokku/fof/tls      
       Ssl enabled:                   true                     
       Ssl hostnames:                 fof.undervisernet.dk fof.undervisernet.umakers.io
       Ssl expires at:                Dec  4 21:00:18 2023 GMT 
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Sep  5 21:00:19 2023 GMT 
       Ssl subject:                   subject=CN = fof.undervisernet.umakers.io
       Ssl verified:                  self signed              
=====> fof checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> fof cron information
       Cron task count:               0
=====> fof docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> fof domains information
       Domains app enabled:           true                     
       Domains app vhosts:            fof.undervisernet.umakers.io fof.undervisernet.dk
       Domains global enabled:        true                     
       Domains global vhosts:         undervisernet.umakers.io 
=====> fof git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       0f6096d                  
       Git last updated at:           1674138004               
=====> fof letsencrypt information
       Letsencrypt active:            true                     
       Letsencrypt autorenew:         true                     
       Letsencrypt email:             ~cert+undervisernet@umakers.dk
       Letsencrypt expiration:        1701723618               
=====> fof logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> fof network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.8:5000
=====> fof nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/fof-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:    25m                      
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/fof-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1698832843               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> fof proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> fof ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: ada3e80bad6)
=====> fof registry information
       Registry computed image repo:      dokku/fof
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> fof resource information
=====> fof scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> fof scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local init process: true                     
       Scheduler docker local parallel schedule count:                          
=====> fof storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:                                     
dokku> 


### Additional information

````
ps:inspect fof
[
    {
        "AppArmorProfile": "docker-default",
        "Args": [
            "web"
        ],
        "Config": {
            "AttachStderr": true,
            "AttachStdin": false,
            "AttachStdout": true,
            "Cmd": [
                "/start",
                "web"
            ],
            "Domainname": "",
            "Entrypoint": null,
            "Env": [
                "UMBRACO_CLIENT=XXXXXX",
                "UMBRACO_URL=XXXXXX",
                "knownAuthorities=XXXXXX",
                "DYNO=web.1",
                "PORT=5000",
                "DOKKU_PROXY_PORT_MAP=http:80:5000 https:443:5000",
                "CURL_CONNECT_TIMEOUT=XXXXXX",
                "CURL_TIMEOUT=XXXXXX",
                "USER=herokuishuser",
                "DOKKU_APP_TYPE=herokuish",
                "DOKKU_APP_RESTORE=1",
                "DOKKU_PROXY_PORT=80",
                "DOKKU_PROXY_SSL_PORT=443",
                "GIT_REV=XXXXXX",
                "SENTRY_DSN=XXXXXX",
                "THEME=XXXXXX",
                "USE_SCOPES=XXXXXX",
                "authenticationB2BClientId=XXXXXX",
                "DOKKU_LETSENCRYPT_EMAIL=~cert+undervisernet@umakers.dk",
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "STACK=XXXXXX",
                "DEBIAN_FRONTEND=XXXXXX"
            ],
            "Hostname": "ada3e80bad62",
            "Image": "dokku/fof:latest",
            "Labels": {
                "com.dokku.app-name": "fof",
                "com.dokku.builder-type": "herokuish",
                "com.dokku.container-type": "deploy",
                "com.dokku.dyno": "web.1",
                "com.dokku.image-stage": "release",
                "com.dokku.process-type": "web",
                "com.gliderlabs.herokuish/stack": "heroku-20",
                "dokku": "",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "dokku"
            },
            "OnBuild": null,
            "OpenStdin": false,
            "StdinOnce": false,
            "Tty": false,
            "User": "",
            "Volumes": null,
            "WorkingDir": ""
        },
        "Created": "2023-10-31T09:55:31.229919099Z",
        "Driver": "overlay2",
        "ExecIDs": null,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/29f519083bd8962e0d9554d757c83365a35d0b93ab39f6d1b457f8d2e95b5e74-init/diff:/var/lib/docker/overlay2/d4e925e02b1ecb4636e95d4c6c3ec9b1cbf5345854ce5e238c92fd903c62fe2c/diff:/var/lib/docker/overlay2/fc7ab441df74fb27c4b5b858752506d3637f59e0f226bb8600c6e09f9bf0f98e/diff:/var/lib/docker/overlay2/b2744bb1dd8787087c61a91244e30c3a8ffbca35e1da0580d94e2521b3df239e/diff:/var/lib/docker/overlay2/bc9b291f616c0856059b8f12d2c8d2544791574652a4ab7f9953c961ed6a614a/diff:/var/lib/docker/overlay2/c07425dc6a641fd8b868e10625694a6a86fd8974da391a1546100597645ffd54/diff:/var/lib/docker/overlay2/eef2e165168aebf490c14557f6fc9a99aac14d9835ed80c5029680dae0fe206a/diff:/var/lib/docker/overlay2/d9a5078a6dab07fe716d3a1f0310ce2457a7f341a7b0920fa065bb2e3ce202a5/diff:/var/lib/docker/overlay2/ec48d39d9ce6245d64828fb751ee4a4b711df4697deab37b76511e95a209e241/diff:/var/lib/docker/overlay2/84b674987448bdb51b09c0df5a05793b4db14ca4d7df23045b7f292b335730f7/diff:/var/lib/docker/overlay2/08af4590e1e8c8aa6936c208f8cdd3fedf2cdc9c74fd281e6ed9ba5cc2f002f2/diff:/var/lib/docker/overlay2/0b3dbd22096d439927180b79b69ecff9e675f20d1cd90502dcb6162095ab0f8f/diff:/var/lib/docker/overlay2/1c2e17d4d491f4257bcee41944918dcf3a9c0de1919d166f1b7843c42f98aed3/diff:/var/lib/docker/overlay2/8a6b5af0999c91467d87ef1bbab3800f43fbae0a9fe114dc278346824163ca74/diff:/var/lib/docker/overlay2/9f7bdcbe6eea58232994119dd123df8d19a0ff470e1c4cd275b22da54d8000ff/diff:/var/lib/docker/overlay2/2fad6cbaca26c15b9a4d07ebd0a28a4507ca83fbab624633524aa78be3c57faf/diff",
                "MergedDir": "/var/lib/docker/overlay2/29f519083bd8962e0d9554d757c83365a35d0b93ab39f6d1b457f8d2e95b5e74/merged",
                "UpperDir": "/var/lib/docker/overlay2/29f519083bd8962e0d9554d757c83365a35d0b93ab39f6d1b457f8d2e95b5e74/diff",
                "WorkDir": "/var/lib/docker/overlay2/29f519083bd8962e0d9554d757c83365a35d0b93ab39f6d1b457f8d2e95b5e74/work"
            },
            "Name": "overlay2"
        },
        "HostConfig": {
            "AutoRemove": false,
            "Binds": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceWriteIOps": null,
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "CapAdd": null,
            "CapDrop": null,
            "Cgroup": "",
            "CgroupParent": "",
            "CgroupnsMode": "private",
            "ConsoleSize": [
                0,
                0
            ],
            "ContainerIDFile": "",
            "CpuCount": 0,
            "CpuPercent": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpuShares": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "Devices": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IOMaximumBandwidth": 0,
            "IOMaximumIOps": 0,
            "Init": true,
            "IpcMode": "private",
            "Isolation": "",
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "Links": null,
            "LogConfig": {
                "Config": {
                    "max-size": "10m"
                },
                "Type": "json-file"
            },
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "NanoCpus": 0,
            "NetworkMode": "default",
            "OomKillDisable": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "PidsLimit": null,
            "PortBindings": {},
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "ReadonlyRootfs": false,
            "RestartPolicy": {
                "MaximumRetryCount": 10,
                "Name": "on-failure"
            },
            "Runtime": "runc",
            "SecurityOpt": null,
            "ShmSize": 67108864,
            "UTSMode": "",
            "Ulimits": null,
            "UsernsMode": "",
            "VolumeDriver": "",
            "VolumesFrom": null
        },
        "HostnamePath": "/var/lib/docker/containers/ada3e80bad627797f2ec7fa8cf394f68416e29debead50aec7e7b08dc688f9d2/hostname",
        "HostsPath": "/var/lib/docker/containers/ada3e80bad627797f2ec7fa8cf394f68416e29debead50aec7e7b08dc688f9d2/hosts",
        "Id": "ada3e80bad627797f2ec7fa8cf394f68416e29debead50aec7e7b08dc688f9d2",
        "Image": "sha256:720e2574d671d40dfbc8355332964b0e7dbd8c6064e47de377fabdf20b7bd43c",
        "LogPath": "/var/lib/docker/containers/ada3e80bad627797f2ec7fa8cf394f68416e29debead50aec7e7b08dc688f9d2/ada3e80bad627797f2ec7fa8cf394f68416e29debead50aec7e7b08dc688f9d2-json.log",
        "MountLabel": "",
        "Mounts": [],
        "Name": "/fof.web.1",
        "NetworkSettings": {
            "Bridge": "",
            "EndpointID": "0c2e030ccf8c5a52117f86830ff42f0d74af5a5ca50fd120519f3c108af19691",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "HairpinMode": false,
            "IPAddress": "172.17.0.8",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "MacAddress": "02:42:ac:11:00:08",
            "Networks": {
                "bridge": {
                    "Aliases": null,
                    "DriverOpts": null,
                    "EndpointID": "0c2e030ccf8c5a52117f86830ff42f0d74af5a5ca50fd120519f3c108af19691",
                    "Gateway": "172.17.0.1",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "IPAMConfig": null,
                    "IPAddress": "172.17.0.8",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "Links": null,
                    "MacAddress": "02:42:ac:11:00:08",
                    "NetworkID": "cd854380cbb515c465b5fd6d196eb9fc3c0f49c3d04e5e5178caa8386f7433cb"
                }
            },
            "Ports": {},
            "SandboxID": "4aed79e170844989992273b1efe05def7ec10357154090ce59ee077648b57d86",
            "SandboxKey": "/var/run/docker/netns/4aed79e17084",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null
        },
        "Path": "/start",
        "Platform": "linux",
        "ProcessLabel": "",
        "ResolvConfPath": "/var/lib/docker/containers/ada3e80bad627797f2ec7fa8cf394f68416e29debead50aec7e7b08dc688f9d2/resolv.conf",
        "RestartCount": 0,
        "State": {
            "Dead": false,
            "Error": "",
            "ExitCode": 0,
            "FinishedAt": "0001-01-01T00:00:00Z",
            "OOMKilled": false,
            "Paused": false,
            "Pid": 2062909,
            "Restarting": false,
            "Running": true,
            "StartedAt": "2023-10-31T09:55:31.612068502Z",
            "Status": "running"
        }
    }
]

**Comment by jesperordrup** [comment]
Just "lost" another container on another server. Totally different solution. Here's what happens when i try getting the log:

```
root@hammercore:~# dokku logs deploy-test
Error response from daemon: No such container: a8d096dc52eaeb0f632373bd84fa9d043b0eb401e2b7021ec246f0c38161ad02
root@hammercore:~# 
```

`docker ps -a` shows that the container was there:

```
c62a21cc13ff   8caffa5ebac7                        "node ./build"          4 hours ago      Exited (143) 11 minutes ago              deploy-test.web.1.1698854994
```

The fix

`root@hammercore:~# dokku ps:rebuild deploy-test`

**Comment by josegonzalez** [comment]
Exit code 143 might be that the OS is killing the container due to OOM (Out of Memory) Kill. Can you check the output of `/var/log/syslog` to see if there are any OOM messages?

Additionally, can you post the output of `dokku-event-listener --version`?

**Comment by jesperordrup** [comment]
I've just checked mem usage. Its only 4 GB vps so you could be right. Searching syslog for oom sure makes it look like a mem problem:

```
26890:Nov  1 16:38:49 hammercore kernel: [465886.759719] .NET ThreadPool invoked oom-killer: gfp_mask=0x1100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
26899:Nov  1 16:38:50 hammercore kernel: [465886.759747]  oom_kill_process.cold+0xb/0x10
26957:Nov  1 16:38:50 hammercore kernel: [465886.759860] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
27020:Nov  1 16:38:50 hammercore kernel: [465886.759955] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=docker-899e8765a18ca521e66c782197feee1d93d8e1628bee8e8eca8acf7ab0e49b15.scope,mems_allowed=0,global_oom,task_memcg=/system.slice/docker-8ef81ea9a29ec1e65615346e46821d8a7391d8ac8ddc93477b06e9aeffa14975.scope,task=hammer,pid=1417088,uid=0
27021:Nov  1 16:38:50 hammercore kernel: [465886.760015] Out of memory: Killed process 1417088 (hammer) total-vm:275689932kB, anon-rss:2453612kB, file-rss:0kB, shmem-rss:83016kB, UID:0 pgtables:6252kB oom_score_adj:0
27022:Nov  1 16:38:50 hammercore systemd[1]: docker-8ef81ea9a29ec1e65615346e46821d8a7391d8ac8ddc93477b06e9aeffa14975.scope: A process of this unit has been killed by the OOM killer.
```


Output of `dokku-event-listener --version`

`0.15.0build+5268732`

**Comment by jesperordrup** [comment]
Yes it is:

<img width="1012" alt="image" src="https://github.com/dokku/dokku/assets/3120151/d998adf6-1aeb-4492-8d4d-deb6e8fe6a49">

**Comment by josegonzalez** [comment]
Mind grabbing logs for that via journalctl?

**Comment by josegonzalez** [comment]
Going to close this for now. I would definitely take a look at what is consuming all your memory, and then see if maybe you're hitting a restart limit. Ideally, the `dokku-event-listener` is still restarting after that limit, but without its logs, hard to say whats going on.

Feel free to comment with updates and we'll take a closer look.
