### ISSUE TITLE
How to start a new process in an existing Dokku dockerfile based deployment

### ISSUE THREAD

**Issue by mohamedrez** [dokku/dokku#6363]
### Description of problem

I have a rails app that is deployed in Dokku and was working fine, I wanted to add sidekiq, as the documentation recommends is to add a new Procfile, I did but I cannot get the worker to start

### Steps to reproduce

- deploy your app using a Dockerfile
- try to run a new process from the same docker file with a different command

### dokku report $APP_NAME

root@dev-grh:/home/application# dokku report $APP_NAME
-----> uname: Linux dev-grh 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                      total        used        free      shared  buff/cache   available
       Mem:            7746         855        2132           1        4759        6583
       Swap:           4014           0        4014
-----> docker version: 
       Client: Docker Engine - Community
        Version:           23.0.6
        API version:       1.42
        Go version:        go1.19.9
        Git commit:        ef23cbc
        Built:             Fri May  5 21:18:13 2023
        OS/Arch:           linux/amd64
        Context:           default
       
       Server: Docker Engine - Community
        Engine:
         Version:          23.0.6
         API version:      1.42 (minimum version 1.12)
         Go version:       go1.19.9
         Git commit:       9dbdbd4
         Built:            Fri May  5 21:18:13 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.21
         GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
        runc:
         Version:          1.1.7
         GitCommit:        v1.1.7-0-g860f061
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.10.4
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.17.3
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
       
       Server:
        Containers: 5
         Running: 3
         Paused: 0
         Stopped: 2
        Images: 18
        Server Version: 23.0.6
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
        runc version: v1.1.7-0-g860f061
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-89-generic
        Operating System: Ubuntu 22.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 8
        Total Memory: 7.565GiB
        Name: dev-grh
        ID: 8ecd06ad-98c9-48e2-9d06-18a5cf614889
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> herokuish version: 
       herokuish: v0.7.2
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v259
         heroku-buildpack-nodejs    v224
         heroku-buildpack-clojure   v91
         heroku-buildpack-python    v237
         heroku-buildpack-java      v73
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v239
         heroku-buildpack-go        v181
         heroku-buildpack-nginx     v24
         buildpack-null             v3
-----> dokku version: dokku version 0.32.1
-----> dokku-event-listener version: 0.15.0build+5268732                                                             
-----> dokku-update version: dokku-update 0.7.2
-----> docker-container-healthchecker version: 0.7.2                                                                           
-----> docker-image-labeler version: 0.6.1build+c6e15a9                                                              
-----> git version: git version 2.34.1
-----> lambda-builder version:        0.5.0                                                                           
-----> netrc version: 0.7.1build+677c033
 !     pack binary is not available
-----> plugn version: plugn: 0.13.0build+fd5297a
-----> sigil version: 0.10.1build+e443be0
-----> sshcommand version: sshcommand 0.17.1
-----> dokku plugins: 
         00_dokku-standard    0.32.1 enabled    dokku core standard plugin
         20_events            0.32.1 enabled    dokku core events logging plugin
         app-json             0.32.1 enabled    dokku core app-json plugin
         apps                 0.32.1 enabled    dokku core apps plugin
         builder              0.32.1 enabled    dokku core builder plugin
         builder-dockerfile   0.32.1 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.32.1 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.32.1 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.32.1 enabled    dokku core builder-nixpacks plugin
         builder-null         0.32.1 enabled    dokku core builder-null plugin
         builder-pack         0.32.1 enabled    dokku core builder-pack plugin
         buildpacks           0.32.1 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.32.1 enabled    dokku core caddy-vhosts plugin
         certs                0.32.1 enabled    dokku core certificate management plugin
         checks               0.32.1 enabled    dokku core checks plugin
         common               0.32.1 enabled    dokku core common plugin
         config               0.32.1 enabled    dokku core config plugin
         cron                 0.32.1 enabled    dokku core cron plugin
         docker-options       0.32.1 enabled    dokku core docker-options plugin
         domains              0.32.1 enabled    dokku core domains plugin
         enter                0.32.1 enabled    dokku core enter plugin
         git                  0.32.1 enabled    dokku core git plugin
         haproxy-vhosts       0.32.1 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.3 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.32.1 enabled    dokku core logs plugin
         mysql                1.32.2 enabled    dokku mysql service plugin
         network              0.32.1 enabled    dokku core network plugin
         nginx-vhosts         0.32.1 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.32.1 enabled    dokku core openresty-vhosts plugin
         plugin               0.32.1 enabled    dokku core plugin plugin
         ports                0.32.1 enabled    dokku core ports plugin
         proxy                0.32.1 enabled    dokku core proxy plugin
         ps                   0.32.1 enabled    dokku core ps plugin
         redis                1.32.4 enabled    dokku redis service plugin
         registry             0.32.1 enabled    dokku core registry plugin
         repo                 0.32.1 enabled    dokku core repo plugin
         resource             0.32.1 enabled    dokku core resource plugin
         run                  0.32.1 enabled    dokku core run plugin
         scheduler            0.32.1 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.32.1 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.32.1 enabled    dokku core scheduler-null plugin
         shell                0.32.1 enabled    dokku core shell plugin
         ssh-keys             0.32.1 enabled    dokku core ssh-keys plugin
         storage              0.32.1 enabled    dokku core storage plugin
         trace                0.32.1 enabled    dokku core trace plugin
         traefik-vhosts       0.32.1 enabled    dokku core traefik-vhosts plugin

**Comment by josegonzalez** [comment]
What are the contents of your Procfile, and where did you place it in your repository?

**Comment by mohamedrez** [comment]
web: ./bin/rails server
worker: bundle exec sidekiq -C config/sidekiq.yml

it is in the root folder same level as the Dockerfile

**Comment by josegonzalez** [comment]
Did you scale up the sidekiq process?
