### ISSUE TITLE
cannot deploy with git:from-image

### ISSUE THREAD

**Issue by ibadi-id** [dokku/dokku#6417]
### Description of problem

I always got error when deploy app, from git or from docker image

-----> Releasing go-app...
Usage: docker-image-labeler [--version] [--help] <command> [<args>]

Available commands are:
    relabel    Re-labels a docker image
    version    Return the version of the binary

 !     exit status 127

### Steps to reproduce

dokku ps:rebuild go-app

### dokku report $APP_NAME

dokku version 0.24.8

**Comment by josegonzalez** [comment]
A few things:

- Next time, please fill out the entire issue template. It's useful for helping me debug issues. Not filling it out makes it harder for me to figure out whats going on or what the user should do.
- Either downgrade `docker-image-labeler` or upgrade Dokku. Newer versions of Dokku are compatible with the version of `docker-image-labeler` I think you have.

Hope that helps.
