### ISSUE TITLE
Single Dokku App – map internal ports to added domains

### ISSUE THREAD

**Issue by markokraemer** [dokku/dokku#6441]
### Description of feature

I have a single Dokku App:
- example1.com Domain added that I want to map to server running on port 3080 in the container
- example2.com Domain added that I want to map to server running on port 8080 in the container

Is there an easy way to configure the routing to achieve that with a single dokku app?

**Comment by josegonzalez** [comment]
Unfortunately, there are only two options for this:

- to use a custom nginx.conf.sigil to perform the mapping
- deploy two different apps, each one listening on a different port

That said, what would be the desired interface for this? How would it work for apps that aren't mapped to a particular domain?

**Comment by markokraemer** [comment]
All right, thanks for getting back! I´ll try out the custom nginx.conf.sigil again. 

I think the optimal interface would be to be able to map it via CLI. 
So just as I mapping internal to external ports for an app, you could maybe also map an external facing port of the App to an Domain you have added to the app // directly map the internal port to the domain. If an App´s port is not mapped to a domain and is exposed externally, then its just accessible without the port.

**Comment by josegonzalez** [comment]
I mean it would be somehow mapped via the cli, but what do those commands look like in your head?

**Comment by markokraemer** [comment]
Maybe something like this would be intuitive
dokku ports:add app-name 80:8080 appname.com 

Although I dont know if 'ports' is the propper place to do that management, would rather fit into proxy 

---
For the custom nginx.conf.sigil I am running into the following issue:

When trying to: dokku nginx:set /root/softgen.ai/softgen.ai/template/nginx.conf.sigil project-13 .dokku/nginx.conf.sigil

Returns:  !     Invalid key specified, valid keys include: access-log-format, access-log-path, bind-address-ipv4, bind-address-ipv6, client-max-body-size, disable-custom-config, error-log-path, hsts, hsts-include-subdomains, hsts-preload, hsts-max-age, nginx-conf-sigil-path, proxy-read-timeout, proxy-buffer-size, proxy-buffering, proxy-buffers, proxy-busy-buffers-size, x-forwarded-for-value, x-forwarded-port-value, x-forwarded-proto-value, x-forwarded-ssl

I always get it back, even if I leave the nginx.conf.sigil exactly as it is in the template tehttps://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil – no matter if edited or not I get that error.

**Comment by josegonzalez** [comment]
The `ports:add` command already takes multiple port mappings, so your example wouldn't work.

---

You can't set the path of an `nginx.conf.sigil` file like that. Not sure where you got that command, but if it was ChatGPT, please try our docs site first...

https://dokku.com/docs/networking/proxies/nginx/?h=nginx.conf.sigil#customizing-the-nginx-configuration

**Comment by markokraemer** [comment]
I took the command from the docs directly, ChatGPT would probably have gotten it right – I thought the 'nginx-conf-sigil-path' is a placeholder for the path... 

Maybe something in this direction?
- dokku domains:map <app-name> <domain> <external-port> 
- dokku proxy:map <app-name> <domain> <external-port> 
Map a mapped external  port of an app to a specific domain.

**Comment by josegonzalez** [comment]
I'm going to close it. I don't think I'll be implementing this as the port map construct - as well as proxies implementing them - is already complex enough. While I think it would be useful, I think this would require a rethink on how process, ports, and domains all relate to each other.
