### ISSUE TITLE
Cannot destroy an old app with a colon in the name

### ISSUE THREAD

**Issue by jathayde** [dokku/dokku#6539]
### Description of problem

Somehow, I got an app created with a colon in the name, and when trying to destroy it (with or without `--force`) it returns:

` !     App name must begin with lowercase alphanumeric character, and cannot include uppercase characters, colons, or underscores`

### Steps to reproduce

Not sure how this got created in the first place (would have been in the 0.31 or 0.32 timeframe). It happened while trying to run a docker image install of Minecraft.

### dokku report $APP_NAME

root@gc2:/var/lib/docker/containers# dokku report minecraft:
-----> uname: Linux gc2.meticulous.net 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:          24037        7540       13869         195        2627       15910
       Swap:          4095         221        3874
-----> docker version: 
       Client: Docker Engine - Community
        Version:           25.0.0
        API version:       1.44
        Go version:        go1.21.6
        Git commit:        e758fe5
        Built:             Thu Jan 18 17:09:55 2024
        OS/Arch:           linux/amd64
        Context:           default
       
       Server: Docker Engine - Community
        Engine:
         Version:          25.0.0
         API version:      1.44 (minimum version 1.24)
         Go version:       go1.21.6
         Git commit:       615dfdf
         Built:            Thu Jan 18 17:09:55 2024
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.27
         GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
        runc:
         Version:          1.1.11
         GitCommit:        v1.1.11-0-g4bccb38
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client: Docker Engine - Community
        Version:    25.0.0
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.12.1
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.24.1
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
       
       Server:
        Containers: 29
         Running: 26
         Paused: 0
         Stopped: 3
        Images: 27
        Server Version: 25.0.0
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
        runc version: v1.1.11-0-g4bccb38
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
        Kernel Version: 5.4.0-169-generic
        Operating System: Ubuntu 20.04.6 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 3
        Total Memory: 23.47GiB
        Name: gc2.meticulous.net
        ID: b1990ef2-ed7b-47dc-877a-44866ca6aa83
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 181
         Goroutines: 155
         System Time: 2024-01-26T19:33:01.109287505Z
         EventsListeners: 1
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
WARNING: No swap limit support
        Live Restore Enabled: false
       
-----> herokuish version: 
       herokuish: v0.7.2
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v259
         heroku-buildpack-nodejs    v224
         heroku-buildpack-clojure   v91
         heroku-buildpack-python    v237
         heroku-buildpack-java      v73
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v239
         heroku-buildpack-go        v181
         heroku-buildpack-nginx     v24
         buildpack-null             v3
-----> dokku version: dokku version 0.33.1
-----> dokku-event-listener version: 0.15.0build+5268732                                                             
-----> dokku-update version: dokku-update 0.7.2
-----> docker-container-healthchecker version: 0.7.2                                                                           
-----> docker-image-labeler version: 0.6.1build+c6e15a9                                                              
-----> git version: git version 2.25.1
-----> lambda-builder version:        0.5.0                                                                           
-----> netrc version: 0.7.1build+677c033
 !     pack binary is not available
-----> plugn version: plugn: 0.13.0build+fd5297a
-----> sigil version: 0.10.1build+e443be0
-----> sshcommand version: sshcommand 0.17.1
-----> dokku plugins: 
         00_dokku-standard    0.33.1 enabled    dokku core standard plugin
         20_events            0.33.1 enabled    dokku core events logging plugin
         app-json             0.33.1 enabled    dokku core app-json plugin
         apps                 0.33.1 enabled    dokku core apps plugin
         builder              0.33.1 enabled    dokku core builder plugin
         builder-dockerfile   0.33.1 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.33.1 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.33.1 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.33.1 enabled    dokku core builder-nixpacks plugin
         builder-null         0.33.1 enabled    dokku core builder-null plugin
         builder-pack         0.33.1 enabled    dokku core builder-pack plugin
         buildpacks           0.33.1 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.33.1 enabled    dokku core caddy-vhosts plugin
         certs                0.33.1 enabled    dokku core certificate management plugin
         checks               0.33.1 enabled    dokku core checks plugin
         common               0.33.1 enabled    dokku core common plugin
         config               0.33.1 enabled    dokku core config plugin
         cron                 0.33.1 enabled    dokku core cron plugin
         docker-options       0.33.1 enabled    dokku core docker-options plugin
         dokku-wkhtmltopdf    0.1.1 disabled   dokku wkhtmltopdf
         domains              0.33.1 enabled    dokku core domains plugin
         enter                0.33.1 enabled    dokku core enter plugin
         git                  0.33.1 enabled    dokku core git plugin
         haproxy-vhosts       0.33.1 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.3 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.33.1 enabled    dokku core logs plugin
         network              0.33.1 enabled    dokku core network plugin
         nginx-vhosts         0.33.1 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.33.1 enabled    dokku core openresty-vhosts plugin
         plugin               0.33.1 enabled    dokku core plugin plugin
         ports                0.33.1 enabled    dokku core ports plugin
         postgres             1.34.0 enabled    dokku postgres service plugin
         proxy                0.33.1 enabled    dokku core proxy plugin
         ps                   0.33.1 enabled    dokku core ps plugin
         redis                1.34.0 enabled    dokku redis service plugin
         registry             0.33.1 enabled    dokku core registry plugin
         repo                 0.33.1 enabled    dokku core repo plugin
         resource             0.33.1 enabled    dokku core resource plugin
         run                  0.33.1 enabled    dokku core run plugin
         scheduler            0.33.1 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.33.1 enabled    dokku core scheduler-docker-local plugin
         scheduler-k3s        0.33.1 enabled    dokku core scheduler-k3s plugin
         scheduler-null       0.33.1 enabled    dokku core scheduler-null plugin
         shell                0.33.1 enabled    dokku core shell plugin
         ssh-keys             0.33.1 enabled    dokku core ssh-keys plugin
         storage              0.33.1 enabled    dokku core storage plugin
         trace                0.33.1 enabled    dokku core trace plugin
         traefik-vhosts       0.33.1 enabled    dokku core traefik-vhosts plugin
 !     App name must begin with lowercase alphanumeric character, and cannot include uppercase characters, colons, or underscores

**Comment by josegonzalez** [comment]
Can you try deleting it but with the trace flag?

dokku --trace apps:destroy APP --force

And paste the entire output?

**Comment by jathayde** [comment]
Yup. Here's that output:
```
root@gc2:/var/lib/docker/containers# dokku --trace apps:destroy minecraft: --force
+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOCKER_BIN=docker
+ DOCKER_BIN=docker
+ export DOKKU_IMAGE=gliderlabs/herokuish:latest-22
+ DOKKU_IMAGE=gliderlabs/herokuish:latest-22
+ export DOKKU_CNB_BUILDER=heroku/builder:22
+ DOKKU_CNB_BUILDER=heroku/builder:22
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_PID=160556
+ DOKKU_PID=160556
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args apps:destroy minecraft: --force
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ local flags
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ apps:destroy == \-\-\a\p\p ]]
+ [[ apps:destroy =~ ^--.* ]]
+ next_index=2
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ minecraft: == \-\-\a\p\p ]]
+ [[ minecraft: =~ ^--.* ]]
+ next_index=3
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ export DOKKU_APPS_FORCE_DELETE=1
+ DOKKU_APPS_FORCE_DELETE=1
+ [[ false == \t\r\u\e ]]
+ [[ --force == \-\-\a\p\p ]]
+ [[ --force =~ ^--.* ]]
+ flags=' --force'
+ next_index=4
+ [[ -z --trace --force ]]
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ apps:destroy =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
+ [[ '' == \t\r\u\e ]]
++ LC_ALL=C
++ /usr/bin/tty
+ [[ /dev/pts/0 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ apps:destroy =~ ^plugin:.* ]]
+ [[ apps:destroy == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ apps:destroy == \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
+ [[ apps:destroy == \s\c\h\e\d\u\l\e\r\-\k\3\s\:\i\n\i\t\i\a\l\i\z\e ]]
+ [[ apps:destroy == \s\c\h\e\d\u\l\e\r\-\k\3\s\:\u\n\i\n\s\t\a\l\l ]]
+ [[ -n '' ]]
+ dokku_auth apps:destroy minecraft: --force
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=root
+ SSH_USER=root
+ export SSH_NAME=default
+ SSH_NAME=default
+ export DOKKU_COMMAND=apps:destroy
+ DOKKU_COMMAND=apps:destroy
++ wc -l
++ find /var/lib/dokku/plugins/enabled/20_events/user-auth
+ local user_auth_count=1
+ [[ 1 == 0 ]]
+ [[ 1 == 1 ]]
+ [[ -f /var/lib/dokku/plugins/enabled/20_events/user-auth ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd apps:destroy minecraft: --force
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=apps:destroy
+ local PLUGIN_CMD=apps:destroy
+ local implemented=0
+ local script
+ argv=("$@")
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/apps
+ [[ /var/lib/dokku/core-plugins/available/apps == *core-plugins* ]]
+ [[ apps:destroy == \a\p\p\s\:\d\e\s\t\r\o\y ]]
+ shift 1
+ [[ -n '' ]]
+ set -- apps:destroy minecraft: --force
+ [[ -x /var/lib/dokku/plugins/enabled/apps:destroy/subcommands/default ]]
+ [[ -x /var/lib/dokku/plugins/enabled/apps:destroy/subcommands/apps:destroy ]]
+ [[ -x /var/lib/dokku/plugins/enabled/apps/subcommands/destroy ]]
+ [[ -n destroy ]]
+ /var/lib/dokku/plugins/enabled/apps/subcommands/destroy apps:destroy minecraft: --force
 !     App name must begin with lowercase alphanumeric character, and cannot include uppercase characters, colons, or underscores
```

**Comment by josegonzalez** [comment]
Is the app running anything or just accidentally exists?

**Comment by jathayde** [comment]
Accidentally exists.

**Comment by josegonzalez** [comment]
You can do `rm -rf "/home/dokku/minecraft:"` to delete it then.

**Comment by jathayde** [comment]
That did the trick. Thanks @josegonzalez !
