### ISSUE TITLE
Dokku website not reachable from ipv6-only machine

### ISSUE THREAD

**Issue by tauinger-de** [dokku/dokku#6597]
### Description of problem

I just started using dokku on a Hetzner cloud server, which I had configured to use ipv6 only.

The `wget` to the dokku install script always failed with "network is unreachable" (other wgets to e.g. the dokku logo as well). Once I added ipv4 to my cloud server I could connect. 

It seems that your website is not supporting ipv6 connectivity (AAAA records): https://www.nslookup.io/domains/dokku.com/dns-records/

### Steps to reproduce

1. configure a host to ipv6 only
2. perform "wget https://dokku.com/install/v0.33.3/bootstrap.sh"

### dokku report $APP_NAME

n/a

**Comment by josegonzalez** [comment]
If I add AAAA records, how can I test that the site is reachable from ipv6?

**Comment by killa-kyle** [comment]
website has SSL issue for me as well

![Screenshot 2024-02-14 093112](https://github.com/dokku/dokku/assets/6319238/9dbbb388-29cd-41f5-b79d-5fc830572e53)

**Comment by tauinger-de** [comment]
> If I add AAAA records, how can I test that the site is reachable from ipv6?

Maybe with this? https://ready.chair6.net/?url=dokku.com

**Comment by tauinger-de** [comment]
BTW for testing connectivity to v4 or v6 only website you can use:

- ipv6.google.com
- ipv4.google.com

**Comment by tauinger-de** [comment]
PS github doesn't support ipv6 yet: https://isgithubipv6.live/

**Comment by josegonzalez** [comment]
@killa-kyle you almost certainly aren't seeing the same issue, as this covers "not reachable" issues, not "curl protocol errors". Please open a separate ticket so we can track that.

**Comment by josegonzalez** [comment]
I setup an AAAA record pointing at the new IPv6 ip for the dokku server. Do you mind checking it out @tauinger-de ?

**Comment by tauinger-de** [comment]
Looks fine! I could connect from my Hetzner server and the other two online tests are positive, too.

**Comment by josegonzalez** [comment]
Nice! Closing :)
