### ISSUE TITLE
--force-tty cannot be used with run:detached

### ISSUE THREAD

**Issue by Tashows** [dokku/dokku#6606]
https://github.com/dokku/dokku/blob/96afb713b7980b08adfe68bb64599b301abfd8cc/plugins/run/internal-functions#L57C3-L59C5

This check introduced in #6576, does not take into account that run:detached will always set DOKKU_DISABLE_TTY. So suggested use of `dokku run:detached [--no-tty|--force-tty] <app> <cmd>` is invalid (btw --no-tty here is redundant anyway since run:detached will set the relevant variable anyway).

Suggested solutions:

1. Check for --force-tty flag in cmd-run-detached and if it's set, bypass setting DOKKU_DISABLE_TTY
2. Document that --force-tty will override other tty-related flags (because it's checked first and returns 0 in has_tty()) and remove referenced check
3. Make --force-tty unset DOKKU_DISABLE_TTY in the switch checks. This makes the referenced check kind of redundant, unless someone specifically runs --force-tty and --no-tty at the same time (in this order, so --force-tty unsets DOKKU_DISABLE_TTY and then --no-tty sets it again).

**Comment by josegonzalez** [comment]
Maybe the command `cmd-run-detached` should be rewritten to use flags instead of environment variables, which should allow what you are trying to do to work?
