### ISSUE TITLE
`cron:set` is not a dokku command

### ISSUE THREAD

**Issue by mykolasolodukha** [dokku/dokku#6655]
### Description of problem

I don't see `cron:set` neither in the list of `dokku cron` `Additional commands` ([source](https://github.com/dokku/dokku/blob/master/plugins/cron/src/commands/commands.go#L20-L23)), nor in the list of `cron`'s `subcommands` ([source](https://github.com/dokku/dokku/blob/master/plugins/cron/src/subcommands/subcommands.go#L20-L45)).

Did I do something wrong, maybe?

### Steps to reproduce

From [docs](https://dokku.com/docs/processes/scheduled-cron-tasks/#specifying-a-mailto-value):
```sh
dokku cron:set --global mailto example@example.com
```

### dokku report $APP_NAME

It's a `--global` command.

**Comment by josegonzalez** [comment]
Good catch! I must have dropped this in a rebase when adding the functionality. I'll fix in the next patch.

**Comment by mykolasolodukha** [comment]
@josegonzalez thanks!

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by josegonzalez** [comment]
This was released in 0.33.8.
