### ISSUE TITLE
dokku buildpacks:remove my-special-app --index 1 doesn't seem to work

### ISSUE THREAD

**Issue by davebytemfg** [dokku/dokku#6657]
### Description of problem

https://dokku.com/docs/deployment/builders/herokuish-buildpacks/

I'm trying to reorder my buildpacks, the doc page says I can :remove them

> Buildpacks can also be removed by index via the --index flag. This flag is specified starting at a 1-index value.

And yet, I'm getting this message about adding a buildpack:

```
root:~# dokku buildpacks:list my-special-app
-----> my-special-app buildpack urls
       https://github.com/heroku/heroku-buildpack-nodejs.git
       https://github.com/heroku/heroku-buildpack-ruby.git
       https://github.com/yespark/heroku-imagemagick-buildpack
root:~# dokku buildpacks:remove my-special-app --index 1 
 !     Must specify a buildpack to add


```
I'll just wipe them and re-specify them, but wanted to note this in case some else runs into it.

### Steps to reproduce

```
root:~# dokku buildpacks:list my-special-app
-----> my-special-app buildpack urls
       https://github.com/heroku/heroku-buildpack-nodejs.git
       https://github.com/heroku/heroku-buildpack-ruby.git
       https://github.com/yespark/heroku-imagemagick-buildpack
root:~# dokku buildpacks:remove my-special-app --index 1 
 !     Must specify a buildpack to add
```

### dokku report $APP_NAME

-----> dokku version: dokku version 0.33.6
-----> dokku-event-listener version: 0.15.0build+5268732                                                             
-----> dokku-update version: dokku-update 0.7.2

**Comment by josegonzalez** [comment]
In the future, please include the _entire_ `dokku report` output. I'm not asking for my health, it is often quite useful to figure out what is going on in a system.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
