### ISSUE TITLE
Documented `--global` option for `ps:set` does not exist

### ISSUE THREAD

**Issue by spiffytech** [dokku/dokku#6755]
### Description of problem

[The docs for Procfile settings](https://dokku.com/docs/processes/process-management/#changing-the-procfile-location) show a `ps:set --global` command. That flag does not appear to exist.

`ps:set <app> <key> <value>        Set or clear a ps property for an app`

Dokku 0.34.0

### Steps to reproduce

```
# dokku ps:set --global procfile-path .dokku/Procfile
unknown flag: --global
Usage of ps:set:
unknown flag: --global
```

### dokku report $APP_NAME

N/A

**Comment by josegonzalez** [comment]
Should be fixed [here](https://github.com/dokku/dokku/blob/master/plugins/ps/src/subcommands/subcommands.go#L75) similar to how we have it [here](https://github.com/dokku/dokku/blob/master/plugins/cron/src/subcommands/subcommands.go#L43), and we should write a test for the new functionality.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
