### ISSUE TITLE
Third level subdomain with SSL

### ISSUE THREAD

**Issue by yazinsai** [dokku/dokku#677]
Referencing issue #357, I have a similar setup but want to get SSL to work too. What would I need to change in order to make this happen?

Here's my `/etc/nginx/sites-available/talk` (where `<appname>` is `talk`):

``` nginx
server {
  listen [::]:80;
  listen 80;
  server_name *.talk.whitepayments.com;
  location / {
    proxy_pass http://talk.whitepayments.com;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
}

server {
  listen [::]:443;
  listen 443;
  server_name *.talk.whitepayments.com;
  location / {
    proxy_pass https://talk.whitepayments.com;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
}
```

I thought copying and pasting the code, replacing the port with `443` would fix it .. but it doesn't. Suggestions?

**Comment by aral** [comment]
Hey @yazinsai, in case that’s still a problem for you, you can try using an nginx proxy as a front controller to pass (e.g.) thirdlevel.talk.whitepayments.com to https://whitepayments.com/talk/thirdlevel and then you won‘t even need a wildcard certificate and can splurge on an EV instead ;)
