### ISSUE TITLE
Aborting a deployment of the release task fails

### ISSUE THREAD

**Issue by tcannonfodder** [dokku/dokku#6822]
### Link to the documentation page

https://dokku.com/docs/advanced-usage/deployment-tasks/

### Documentation problem

I’ve noticed that non-successful release commands do not stop a deployment from following through. This can lead to an app breaking (such as if a database migration fails, but the release continues with code that is designed for the post-migration DB).

is there a particular configuration missing from the docs, or is this a bug?

**Comment by josegonzalez** [comment]
This sounds like a bug. Can you include the output of `dokku report $APP` for your app, the entire deploy output, and a way to replicate your issue? I can investigate further once that is available.

**Comment by tcannonfodder** [comment]
Will do! Sorry, swamped currently; may take a bit

**Comment by josegonzalez** [comment]
@tcannonfodder any luck with this?

**Comment by tcannonfodder** [comment]
Hey Jose! Sorry, still haven’t had time to make a small test app yet. Feel free to close this until I’m able to; I’ll comment with the repo when it’s done!

in the meantime, I can say this is a standard rails app, and I was using the built-in `bin/rails` command:

~~~

#!/usr/bin/env ruby
APP_PATH = File.expand_path("../config/application", __dir__)
require_relative "../config/boot"
require "rails/commands"
~~~

**Comment by josegonzalez** [comment]
Feel free to re-comment when you have a repro for me :)
