### ISSUE TITLE
Buildpack cache being cleared before every deploy

### ISSUE THREAD

**Issue by sroddy** [dokku/dokku#683]
Hi,
I'm not able to remember exactly when, but after having updated both dokku and buildstep, every time I trigger a new build/deploy the cache of the application is being purged because it thinks that the stack is being updated (which is not true). This means that it installs and downloads every time all the bundler dependencies. Not a blocking issue, but i significantly slows down the deploy process and is a bit frustrating. Does anyone have some hint on what it could be?
Thanks a lot

Here is the log of the deployment

-----> Cleaning up ...
-----> Building staging ...
-----> Installing ENV in build environment ...
       Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.1.2
-----> Installing dependencies using 1.6.3
       Purging Cache. Changing stack from  to
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
       installing your bundle as root will break this application for all non-root
       users on this machine.
       Fetching source index from https://rubygems.org/
       Using minitest 4.7.5
...

**Comment by harshjv** [comment]
I am still facing the same issue.

Even when i push to dokku without changes, it starts with **Cleaning up...**, even with `STACK=cedar` configured.

Any ideas?

**Comment by michaelshobbs** [comment]
The `Cleaning up...` output comes just before the execution of `dokku cleanup`. This only removes exited containers and 'dangling' image layers. It has nothing to with the buildpack cache that exists in `$DOKKU_ROOT/$APP/cache`.

https://github.com/progrium/dokku/blob/d9334900fbb58a7711d934240c7fc2f450471f1b/dokku#L133-L140

To your specific issue, you may want to try using a newer version of your particular buildpack as well by specifying a BUILDPACK_URL. Check out the "specifying a custom buildpack" section here: http://progrium.viewdocs.io/dokku/application-deployment
