### ISSUE TITLE
Regression in dokku enter command

### ISSUE THREAD

**Issue by kminek** [dokku/dokku#6893]
### Description of problem

I no longer can enter app container with following command (dokku v0.34.4)

```
dokku enter appname
```

It was possible in previous versions of dokku (like v0.32.3) without specyfying any optional arguments. I think it was "broken" with this change: https://github.com/dokku/dokku/commit/83b0cf406530eb39e6be73644d1314632a70e045

### Steps to reproduce

see description field

### dokku report $APP_NAME

see description field

**Comment by josegonzalez** [comment]
Aside, I hate the enter command because I haven't figured out a great way to test it (if folks have good ideas, let me know!).

Closing as there is a pull request open. Thanks for reporting.
