### ISSUE TITLE
Add better garbage collection

### ISSUE THREAD

**Issue by snakysnake** [dokku/dokku#6912]
### Description of feature

I recently observed a potential issue, which is not always to be considered a bug, with a dokku pipeline I looked into.

When pushing code to Dokku (via ssh), I can observe files being put into /tmp which are not cleaned up. This can lead to a lot of issues, filling up the root directory of a Linux installation and potentially crashing servers.

Please let me know if from Dokku's Dev. Team's POV this is not a bug but a skill issue on my side, so I can better understand how to prevent this from creating downtime on my clients websites.

Thanks, dear regards
Snakysnake

**Comment by josegonzalez** [comment]
Can you list the files that were in the `/tmp` directory? Those should be cleaned up always, so if they aren't, thats a bug.

**Comment by josegonzalez** [comment]
Closing this as I there hasn't been any update in a few weeks. If someone sees this replicating, please comment with more details so I can investigate.
