### ISSUE TITLE
Update default CNB builder image to `heroku/builder:24`

### ISSUE THREAD

**Issue by edmorley** [dokku/dokku#6994]
### Description of feature

We (Heroku) released `heroku/builder:24`, our new CNB builder image version based upon Ubuntu 24.04 LTS, in June:
https://github.com/heroku/buildpacks/discussions/12
https://github.com/heroku/cnb-builder-images#available-images

Currently Dokku's default CNB builder image is `heroku/builder:22`:
https://github.com/dokku/dokku/blob/c5edd02655991bc55901b4a52af1a3158c2aeea9/dokku#L43

It would be great to update the default CNB builder image to `heroku/builder:24`.

The `heroku/builder:24` builder is now a multi-architecture image (AMD64 + ARM64), and offers smaller run image sizes thanks to dropping unnecessary build-time dependencies from the run image. The list of included buildpacks (and their versions) is identical between `heroku/builder:22` and `heroku/builder:24`. 

For more information on the differences between the two images, see:
https://devcenter.heroku.com/articles/heroku-24-stack#what-s-new
https://devcenter.heroku.com/articles/heroku-24-stack#upgrade-notes
https://devcenter.heroku.com/articles/stack-packages

**Comment by josegonzalez** [comment]
Closing as there is a pull request open. This will land in the next minor release of Dokku.
