### ISSUE TITLE
How to change GIT file size limit

### ISSUE THREAD

**Issue by BananaAcid** [dokku/dokku#7028]
### Documentation problem

Since GIT-LFS is not supported, it would be great, to have a workaround on how to increase the max file size for the GIT server somewhere in the documentation.

It is currently way lower as my Gitea, so pushing projects to dokku is always a hassle (yes, large image files, that get reduced during the app build process).

**Comment by josegonzalez** [comment]
I don't think there is any max file size? It's just a git repo backed by the git cli, so there shouldn't be any limitations here.

**Comment by BananaAcid** [comment]
We had several users here, having PDF files in the project folders, pushed to dokku.

Dokku rejected them with some error about filesize, Gitea had no problem.

We did need to SFTP into the server and drop them into the docker-volume directly. This is quite problematic, as commiting them with the project is not possible when using Dokku.

rather flaky hack: use LFS (which works with Gitea), push to Dokku, have script on the user pc to manually trigger to scp the files into the Docker-Volumes and overwrite the LFS-placeholder-files ... Since they can't be in the app-container

**Comment by josegonzalez** [comment]
What is an example size of a file that was pushed? Do you have a screenshot or the text output of the entire push? Again, this is all backed by the `git` binary - dokku isn't involved there - so its unclear what exactly is causing this issue for you.

**Comment by BananaAcid** [comment]
largest file: 12.3 MB - PNG file, 13MB - PDF

For the error, I would need to create a test project. I will try to add such a file int oan existing project if there is something to deploy.

Is there a way to configure the git binary? config file or alike?

**Comment by josegonzalez** [comment]
I don't think there is - your guess is as good as mine, but the git documentation doesn't suggest there is anything limiting there. We just setup a repo to accept code and then trigger stuff after the fact.

**Comment by BananaAcid** [comment]
Will try to sneak a file into an existing project tomorrow, for the error message :)

**Comment by josegonzalez** [comment]
Closing for now. Dokku itself has no limits, and without any further data, its hard to debug what is going on here.

Feel free to re-post with more data if you encounter this again.
