### ISSUE TITLE
dokku.prerm will loop forever in ps_backtrace() because $ppid == 0

### ISSUE THREAD

**Issue by andreby** [dokku/dokku#7082]
### Description of problem

This is a fresh installation of dokku inside a LXD virtual machine running Ubuntu 22.04.
```
$  apt install dokku
...
Preparing to unpack .../dokku_0.34.9_amd64.deb ...
```
However, the unpack operation hangs.

I've traced the problem to `/var/lib/dpkg/info/dokku.prerm` and the `ps_backtrace()` function. The problem is that `$ppid` at some point becomes 0, which causes an infinite loop.

I've worked around this problem by editing `ps_backtrace()` and changing this:
```
if [ $pid -eq 1 ]; then
    break
fi
```

Into this:
```
if [ $pid -eq 1 -o $pid -eq 0 ]; then
    break
fi
```
This makes the problem go away and I can install dokku. 

### Steps to reproduce

Create a LXD vm running ubuntu 22.04.
Add the dokku apt-repo.
$ apt install dokku

### dokku report $APP_NAME

I don't have an app yet.

**Comment by josegonzalez** [comment]
Oh fancy. Someone reported this years ago but I don't use LXD so I wasn't able to debug. Glad to see you found a solution!

Would you mind making a pull request with this change so we can get that out in the next Dokku release?

**Comment by josegonzalez** [comment]
Closing as that pull request was merged and should land in the next Dokku release.
