### ISSUE TITLE
Adding app name to `dokku apps:report`

### ISSUE THREAD

**Issue by zachahn** [dokku/dokku#7092]
### Description of feature

Hello!

I'm using `dokku apps:report --format json` for a small script. At some point before, the key `app-deploy-source` used to hold the application name, but now it seems to be `git push`.

Could we add a new key to the JSON output that lists the application name? (I see my dokku version is slightly out of date, but the code doesn't seem to return what I'm looking for)

```
$ dokku --version
dokku version 0.34.8
```

#### Current output

```
$ dokku apps:report --format json
{"app-created-at":"1724893494","app-deploy-source":"git-push","app-deploy-source-metadata":"7ad094be7ab23b7653c97d9761984811","app-dir":"/home/dokku/my-cool-app","app-locked":"false"}
{"app-created-at":"1722741576","app-deploy-source":"git-push","app-deploy-source-metadata":"f40f1652f8645835ca0813681ab4e8a6","app-dir":"/home/dokku/my-nice-app","app-locked":"false"}
```

#### Requested output

```
$ dokku apps:report --format json
{"app-name": "my-cool-app", "app-created-at":"1724893494","app-deploy-source":"git-push","app-deploy-source-metadata":"7ad094be7ab23b7653c97d9761984811","app-dir":"/home/dokku/my-cool-app","app-locked":"false"}
{"app-name": "my-nice-app", "app-created-at":"1722741576","app-deploy-source":"git-push","app-deploy-source-metadata":"f40f1652f8645835ca0813681ab4e8a6","app-dir":"/home/dokku/my-nice-app","app-locked":"false"}
```

**Comment by josegonzalez** [comment]
I think you mean `app-name`, which I don't know has ever been in the output. That said, should be easy enough to add

**Comment by zachahn** [comment]
Yeah, for some reason, a few of my apps show `"app-deploy-source":"my-app-name"`, but I was accidentally running a very old version of Dokku until pretty recently. 🤐

I figured out a workaround for my script! So I don't really need this feature request anymore. LMK if you'd like me to close it.

(Btw, thanks for your work on Dokku! I've been using it for a few years now, and I like using it.)

**Comment by josegonzalez** [comment]
Yeah it was a bug that it worked that way haha.

What was the workaround for the script/what are you using the output for? It's not too big of a deal to add, just want a good reason to do so.

**Comment by zachahn** [comment]
Haha makes sense!

Now that I think about it, what I need(ed) was a mapping of domains to app names. I have a script that gets wildcard certificates and maps those certificates to the correct apps using regex. But in my case, the app name is the same as the domain name, so I switched to using `dokku --quet apps:list`.

**Comment by josegonzalez** [comment]
Gotcha. Going to close this for now as I don't see a real need just yet, but if someone can convince me otherwise, I'd be interested in hearing it.
