### ISSUE TITLE
network:info does not appear to do anything 

### ISSUE THREAD

**Issue by bakatz** [dokku/dokku#7093]
### Description of problem

It looks like the network:info command doesn't do anything.

Example:
```
dokku@myserver:/var/mail$ dokku network:list
=====> Networks
bridge
host
none
watchdog-backend-network
dokku@myserver:/var/mail$ dokku network:info watchdog-backend-network
dokku@myserver:/var/mail$
```

I expected to see some output on the last command. Attached additional info below.

### Steps to reproduce

1. Create network named anything i.e. `dokku network:create watchdog-backend-network`
2. Run the info command and observe zero output. I verified this doesn't do anything on the `host` network either.

### dokku report $APP_NAME

-----> uname: Linux ip-172-31-19-162 6.1.0-23-cloud-arm64 #1 SMP Debian 6.1.99-1 (2024-07-15) aarch64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:            3854        1005         800           1        2236        2848
       Swap:              0           0           0
-----> disk utilization:
       Filesystem       Size  Used Avail Use% Mounted on
       /dev/nvme0n1p1   7.7G  5.0G  2.3G  69% /
       /dev/nvme0n1p15  127M   12M  115M  10% /boot/efi
-----> disk inode utilization:
       Filesystem      Inodes IUsed IFree IUse% Mounted on
       /dev/nvme0n1p1    504K  102K  403K   21% /
       /dev/nvme0n1p15      0     0     0     - /boot/efi
-----> docker version:
       Client: Docker Engine - Community
        Version:           27.2.0
        API version:       1.47
        Go version:        go1.21.13
        Git commit:        3ab4256
        Built:             Tue Aug 27 14:15:41 2024
        OS/Arch:           linux/arm64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          27.2.0
         API version:      1.47 (minimum version 1.24)
         Go version:       go1.21.13
         Git commit:       3ab5c7d
         Built:            Tue Aug 27 14:15:41 2024
         OS/Arch:          linux/arm64
         Experimental:     false
        containerd:
         Version:          1.7.21
         GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
        runc:
         Version:          1.1.13
         GitCommit:        v1.1.13-0-g58aa920
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client: Docker Engine - Community
        Version:    27.2.0
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.16.2
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.29.2
           Path:     /usr/libexec/docker/cli-plugins/docker-compose

       Server:
        Containers: 8
         Running: 6
         Paused: 0
         Stopped: 2
        Images: 17
        Server Version: 27.2.0
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
        runc version: v1.1.13-0-g58aa920
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 6.1.0-23-cloud-arm64
        Operating System: Debian GNU/Linux 12 (bookworm)
        OSType: linux
        Architecture: aarch64
        CPUs: 2
        Total Memory: 3.764GiB
        Name: ip-172-31-19-162
        ID: a7aaacf9-e5d2-4f3f-9429-9d7e159b6b9a
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 77
         Goroutines: 96
         System Time: 2024-08-29T06:47:40.81926294Z
         EventsListeners: 2
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> herokuish version:
 !     herokuish not supported on arm64 architecture
-----> dokku version: dokku version 0.34.9
-----> dokku-event-listener version: v0.17.0
-----> dokku-update version: dokku-update v0.9.4
-----> docker-container-healthchecker version: v0.11.0
-----> docker-image-labeler version: v0.8.0
-----> git version: git version 2.39.2
-----> lambda-builder version:        v0.8.0
-----> netrc version: v0.10.0
 !     pack binary is not available
-----> plugn version: plugn: v0.16.0
-----> sigil version: v0.11.0
-----> sshcommand version: sshcommand v0.18.0
-----> dokku plugins:
         00_dokku-standard    0.34.9 enabled    dokku core standard plugin
         20_events            0.34.9 enabled    dokku core events logging plugin
         app-json             0.34.9 enabled    dokku core app-json plugin
         apps                 0.34.9 enabled    dokku core apps plugin
         builder              0.34.9 enabled    dokku core builder plugin
         builder-dockerfile   0.34.9 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.34.9 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.34.9 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.34.9 enabled    dokku core builder-nixpacks plugin
         builder-null         0.34.9 enabled    dokku core builder-null plugin
         builder-pack         0.34.9 enabled    dokku core builder-pack plugin
         buildpacks           0.34.9 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.34.9 enabled    dokku core caddy-vhosts plugin
         certs                0.34.9 enabled    dokku core certificate management plugin
         checks               0.34.9 enabled    dokku core checks plugin
         common               0.34.9 enabled    dokku core common plugin
         config               0.34.9 enabled    dokku core config plugin
         cron                 0.34.9 enabled    dokku core cron plugin
         docker-options       0.34.9 enabled    dokku core docker-options plugin
         domains              0.34.9 enabled    dokku core domains plugin
         enter                0.34.9 enabled    dokku core enter plugin
         git                  0.34.9 enabled    dokku core git plugin
         haproxy-vhosts       0.34.9 enabled    dokku core haproxy-vhosts plugin
         logs                 0.34.9 enabled    dokku core logs plugin
         network              0.34.9 enabled    dokku core network plugin
         nginx-vhosts         0.34.9 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.34.9 enabled    dokku core openresty-vhosts plugin
         plugin               0.34.9 enabled    dokku core plugin plugin
         ports                0.34.9 enabled    dokku core ports plugin
         proxy                0.34.9 enabled    dokku core proxy plugin
         ps                   0.34.9 enabled    dokku core ps plugin
         registry             0.34.9 enabled    dokku core registry plugin
         repo                 0.34.9 enabled    dokku core repo plugin
         resource             0.34.9 enabled    dokku core resource plugin
         run                  0.34.9 enabled    dokku core run plugin
         scheduler            0.34.9 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.34.9 enabled    dokku core scheduler-docker-local plugin
         scheduler-k3s        0.34.9 enabled    dokku core scheduler-k3s plugin
         scheduler-null       0.34.9 enabled    dokku core scheduler-null plugin
         shell                0.34.9 enabled    dokku core shell plugin
         ssh-keys             0.34.9 enabled    dokku core ssh-keys plugin
         storage              0.34.9 enabled    dokku core storage plugin
         trace                0.34.9 enabled    dokku core trace plugin
         traefik-vhosts       0.34.9 enabled    dokku core traefik-vhosts plugin
=====> watchdog-backend-bot app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> watchdog-backend-bot app information
       App created at:                1724839586
       App deploy source:             docker-image
       App deploy source metadata:    ghcr.io/mockernut-ventures/watchdog-backend-bot:64d37985d519c8c80a50a7c512398b4139bb2942
       App dir:                       /home/dokku/watchdog-backend-bot
       App locked:                    false
=====> watchdog-backend-bot builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> watchdog-backend-bot builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> watchdog-backend-bot builder-herokuish information
       Builder herokuish computed allowed: false
       Builder herokuish global allowed: false
       Builder herokuish allowed:
=====> watchdog-backend-bot builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> watchdog-backend-bot builder-nixpacks information
       Builder nixpacks computed nixpackstoml path: nixpacks.toml
       Builder nixpacks global nixpackstoml path: nixpacks.toml
       Builder nixpacks nixpackstoml path:
       Builder nixpacks computed no cache: false
       Builder nixpacks global no cache: false
       Builder nixpacks no cache:
=====> watchdog-backend-bot builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> watchdog-backend-bot buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-22
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> watchdog-backend-bot caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.9
       Caddy letsencrypt email:
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR
       Caddy polling interval:        5s
       Caddy tls internal:            false
=====> watchdog-backend-bot ssl information
       Ssl dir:                       /home/dokku/watchdog-backend-bot/tls
       Ssl enabled:                   false
       Ssl hostnames:
       Ssl expires at:
       Ssl issuer:
       Ssl starts at:
       Ssl subject:
       Ssl verified:
=====> watchdog-backend-bot checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 2
       Checks global wait to retire:  60
       Checks wait to retire:         2
=====> watchdog-backend-bot docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> watchdog-backend-bot domains information
       Domains app enabled:           true
       Domains app vhosts:            api-bot.watchdog.chat api.watchdog.chat
       Domains global enabled:        false
       Domains global vhosts:
=====> watchdog-backend-bot git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       0c2b2c3e3dd07024b259e0f5de556612be88a487
       Git source image:              ghcr.io/mockernut-ventures/watchdog-backend-bot:64d37985d519c8c80a50a7c512398b4139bb2942
       Git last updated at:           1724856923
=====> watchdog-backend-bot haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.4.0
       Haproxy letsencrypt email:
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR
=====> watchdog-backend-bot logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       loki://?REDACTED_BECAUSE_SENSITIVE_KEYS_HERE
       Logs max size:
       Logs vector global image:      timberio/vector:0.39.0-debian
       Logs vector sink:
=====> watchdog-backend-bot network information
       Network attach post create:           watchdog-backend-network
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:  watchdog-backend-network
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.7:5000
=====> watchdog-backend-bot nginx information
       Nginx access log format:
       Nginx computed access log format:
       Nginx global access log format:
       Nginx access log path:
       Nginx computed access log path: /var/log/nginx/watchdog-backend-bot-access.log
       Nginx global access log path:  /var/log/nginx/watchdog-backend-bot-access.log
       Nginx bind address ipv4:
       Nginx computed bind address ipv4:
       Nginx global bind address ipv4:
       Nginx bind address ipv6:
       Nginx computed bind address ipv6: ::
       Nginx global bind address ipv6: ::
       Nginx client max body size:
       Nginx computed client max body size: 1m
       Nginx global client max body size: 1m
       Nginx disable custom config:
       Nginx computed disable custom config: false
       Nginx global disable custom config: false
       Nginx error log path:
       Nginx computed error log path: /var/log/nginx/watchdog-backend-bot-error.log
       Nginx global error log path:   /var/log/nginx/watchdog-backend-bot-error.log
       Nginx hsts include subdomains:
       Nginx computed hsts include subdomains: true
       Nginx global hsts include subdomains: true
       Nginx hsts max age:
       Nginx computed hsts max age:   15724800
       Nginx global hsts max age:     15724800
       Nginx hsts preload:
       Nginx computed hsts preload:   false
       Nginx global hsts preload:     false
       Nginx hsts:
       Nginx computed hsts:           true
       Nginx global hsts:             true
       Nginx last visited at:
       Nginx nginx conf sigil path:
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx proxy buffer size:
       Nginx computed proxy buffer size: 4k
       Nginx global proxy buffer size: 4k
       Nginx proxy buffering:
       Nginx computed proxy buffering: on
       Nginx global proxy buffering:  on
       Nginx proxy buffers:
       Nginx computed proxy buffers:  8 4k
       Nginx global proxy buffers:    8 4k
       Nginx proxy busy buffers size:
       Nginx computed proxy busy buffers size: 8k
       Nginx global proxy busy buffers size: 8k
       Nginx proxy read timeout:
       Nginx computed proxy read timeout: 60s
       Nginx global proxy read timeout: 60s
       Nginx underscore in headers:
       Nginx computed underscore in headers: off
       Nginx global underscore in headers: off
       Nginx x forwarded for value:
       Nginx computed x forwarded for value: $remote_addr
       Nginx global x forwarded for value: $remote_addr
       Nginx x forwarded port value:
       Nginx computed x forwarded port value: $server_port
       Nginx global x forwarded port value: $server_port
       Nginx x forwarded proto value:
       Nginx computed x forwarded proto value: $scheme
       Nginx global x forwarded proto value: $scheme
       Nginx x forwarded ssl:
       Nginx computed x forwarded ssl:
       Nginx global x forwarded ssl:
=====> watchdog-backend-bot openresty information
       Openresty access log format:
       Openresty access log path:     /var/log/nginx/watchdog-backend-bot-access.log
       Openresty allowed letsencrypt domains func base64: cmV0dXJuIHRydWUK
       Openresty bind address ipv4:
       Openresty bind address ipv6:   ::
       Openresty client max body size:
       Openresty error log path:      /var/log/nginx/watchdog-backend-bot-error.log
       Openresty global hsts:         true
       Openresty computed hsts:       true
       Openresty hsts:
       Openresty hsts include subdomains: true
       Openresty hsts max age:        15724800
       Openresty hsts preload:        false
       Openresty image:               dokku/openresty-docker-proxy:0.8.0
       Openresty letsencrypt email:
       Openresty letsencrypt server:  https://acme-v02.api.letsencrypt.org/directory
       Openresty proxy buffer size:   4k
       Openresty proxy buffering:     on
       Openresty proxy buffers:       8 4k
       Openresty proxy busy buffers size: 8k
       Openresty proxy read timeout:  60s
       Openresty underscore in headers: off
       Openresty x forwarded for value: $remote_addr
       Openresty x forwarded port value: $server_port
       Openresty x forwarded proto value: $scheme
       Openresty x forwarded ssl:
=====> watchdog-backend-bot ports information
       Ports map:
       Ports map detected:            http:80:5000
=====> watchdog-backend-bot proxy information
       Proxy computed type:           nginx
       Proxy enabled:                 true
       Proxy global type:             nginx
       Proxy type:
=====> watchdog-backend-bot ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: f3f60c7793d)
=====> watchdog-backend-bot registry information
       Registry computed image repo:        dokku/watchdog-backend-bot
       Registry computed push on release:   false
       Registry computed server:
       Registry global image repo template:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push extra tags:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> watchdog-backend-bot resource information
=====> watchdog-backend-bot scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> watchdog-backend-bot scheduler-docker-local information
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> watchdog-backend-bot scheduler-k3s information
       Scheduler k3s computed deploy timeout:       300s
       Scheduler k3s computed image pull secrets:
       Scheduler k3s computed letsencrypt server:   prod
       Scheduler k3s computed namespace:            default
       Scheduler k3s computed rollback on failure:  false
       Scheduler k3s deploy timeout:
       Scheduler k3s global deploy timeout:         300s
       Scheduler k3s global image pull secrets:
       Scheduler k3s global ingress class:          nginx
       Scheduler k3s global kube context:
       Scheduler k3s global kubeconfig path:        /etc/rancher/k3s/k3s.yaml
       Scheduler k3s global letsencrypt email prod:
       Scheduler k3s global letsencrypt email stag:
       Scheduler k3s global letsencrypt server:     prod
       Scheduler k3s global namespace:              default
       Scheduler k3s global network interface:      eth0
       Scheduler k3s global rollback on failure:    false
       Scheduler k3s image pull secrets:
       Scheduler k3s letsencrypt server:
       Scheduler k3s namespace:
       Scheduler k3s rollback on failure:
=====> watchdog-backend-bot storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:
=====> watchdog-backend-bot traefik information
       Traefik api enabled:           false
       Traefik api vhost:             traefik.dokku.me
       Traefik basic auth password:
       Traefik basic auth username:
       Traefik dashboard enabled:     false
       Traefik image:                 traefik:2.11.2
       Traefik letsencrypt email:
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR
       Traefik http entry point:      http
       Traefik https entry point:     https

### Additional information

N/A

### Output of failing commands after running: dokku trace:off

```shell
N/A, no output
```

### Output of failing commands after running: dokku trace:on

```shell
+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo debian
+ DOKKU_DISTRO=debian
+ export DOCKER_BIN=docker
+ DOCKER_BIN=docker
+ export DOKKU_IMAGE=gliderlabs/herokuish:latest-22
+ DOKKU_IMAGE=gliderlabs/herokuish:latest-22
+ export DOKKU_CNB_BUILDER=heroku/builder:22
+ DOKKU_CNB_BUILDER=heroku/builder:22
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_PID=2847986
+ DOKKU_PID=2847986
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ DOKKU_LOGS_HOST_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args network:info watchdog-backend-network
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=('network:info' 'watchdog-backend-network')
+ local args
+ local flags
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ network:info == \-\-\a\p\p ]]
+ [[ network:info =~ ^--.* ]]
+ next_index=2
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ watchdog-backend-network == \-\-\a\p\p ]]
+ [[ watchdog-backend-network =~ ^--.* ]]
+ next_index=3
+ [[ -z '' ]]
++ echo -e ''
++ sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
+ export DOKKU_GLOBAL_FLAGS=
+ DOKKU_GLOBAL_FLAGS=
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ network:info =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
+ [[ '' == \t\r\u\e ]]
+ [[ '' == \t\r\u\e ]]
++ LC_ALL=C
++ /usr/bin/tty
+ [[ /dev/pts/1 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ network:info =~ ^plugin:.* ]]
+ [[ network:info == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ network:info == \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
+ [[ network:info == \s\c\h\e\d\u\l\e\r\-\k\3\s\:\i\n\i\t\i\a\l\i\z\e ]]
+ [[ network:info == \s\c\h\e\d\u\l\e\r\-\k\3\s\:\u\n\i\n\s\t\a\l\l ]]
+ [[ -n '' ]]
+ dokku_auth network:info watchdog-backend-network
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=dokku
+ SSH_USER=dokku
+ export SSH_NAME=default
+ SSH_NAME=default
+ export DOKKU_COMMAND=network:info
+ DOKKU_COMMAND=network:info
++ wc -l
++ find /var/lib/dokku/plugins/enabled/20_events/user-auth
+ local user_auth_count=1
+ [[ 1 == 0 ]]
+ [[ 1 == 1 ]]
+ [[ -f /var/lib/dokku/plugins/enabled/20_events/user-auth ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd network:info watchdog-backend-network
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=network:info
+ local PLUGIN_CMD=network:info
+ local implemented=0
+ local script
+ argv=('network:info' 'watchdog-backend-network')
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/network
+ [[ /var/lib/dokku/core-plugins/available/network == *core-plugins* ]]
+ [[ network:info == \n\e\t\w\o\r\k\:\i\n\f\o ]]
+ shift 1
+ [[ -n '' ]]
+ set -- network:info watchdog-backend-network
+ [[ -x /var/lib/dokku/plugins/enabled/network:info/subcommands/default ]]
+ [[ -x /var/lib/dokku/plugins/enabled/network:info/subcommands/network:info ]]
+ [[ -x /var/lib/dokku/plugins/enabled/network/subcommands/info ]]
+ [[ -n info ]]
+ /var/lib/dokku/plugins/enabled/network/subcommands/info network:info watchdog-backend-network
+ implemented=1
+ [[ 1 -eq 0 ]]
+ [[ 1 -eq 0 ]]
```

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
