### ISSUE TITLE
502 Bad Gateway - nginx proxy_buffers too small

### ISSUE THREAD

**Issue by jeffcjohnson** [dokku/dokku#711]
When my application returns fairly large responses I get 502 Bad Gateway.  I tracked it down to needing the following settings added to the nginx.conf.  These settings get overwritten with each deployment followed by an nginx reload.  I'm next going to modify my local copy of dokku/plugins/nginx-vhosts/post-deploy so those settings will be hardcoded for my installation.

This would probably be of use to others but the sizes of the buffers would vary depending on the application.

dokku/plugins/nginx-vhosts/post-deploy creates /home/dokku/MYAPP/nginx.conf and I add the following:

```
    proxy_buffer_size   128k;
    proxy_buffers   4 256k;
    proxy_busy_buffers_size   256k;
```

**Comment by IlyaSemenov** [comment]
Note that in modern Dokku, this can be achieved with:

```
dokku nginx:set myapp proxy-buffer-size 128k
dokku nginx:set myapp proxy-buffers "4 256k"
dokku nginx:set myapp proxy-busy-buffers-size 256k
```

**Comment by gyaaniguy** [comment]
After above do

```bash
dokku ps:restart myapp
```
Thank you illyaSemenov ! This finally fixed an issue I was having with laravel, inertia.js . damn, 2 freaking on day on this..

**Comment by josegonzalez** [comment]
You do not need to ps:restart your app after setting nginx properties, though you will for other proxy implementations.

As [mentioned in the docs](https://dokku.com/docs/networking/proxies/nginx/#setting-properties-for-the-nginx-config), you should run `proxy:build-config` after to rebuild the nginx config.
