### ISSUE TITLE
Docs link is raising a 403 error

### ISSUE THREAD

**Issue by fabtjar** [dokku/dokku#7124]
### Description of problem

Clicking on the link to the docs is raising a 403 error.

### Steps to reproduce

https://dokku.com/docs/getting-started/where-to-get-help/

click:
- [https://dokku.com/docs/](https://dokku.com/docs/getting-started/)

result:
> 403 Forbidden
nginx/1.23.1

### dokku report $APP_NAME

n/a

**Comment by josegonzalez** [comment]
Should link [here](https://dokku.com/docs/getting-started/installation/).

**Comment by josegonzalez** [comment]
Closing as a pull request fixing the issue has been merged into the upcoming release. Thanks for reporting!
