### ISSUE TITLE
There is no way to set global client_max_body_size

### ISSUE THREAD

**Issue by shulcsm** [dokku/dokku#7151]
### Description of problem

I consider this a bug since it used to work.

You used to be able to just set client_max_body_size in global nginx config.
And variable here  would be optional https://github.com/dokku/dokku/blob/8e2b4dc68896310f37368f585bc420a9d40e247f/plugins/nginx-vhosts/templates/nginx.conf.sigil#L47C34-L47C54 

Now for some reason global value defaults to 1m and there is no way to change it:
```
Nginx computed client max body size: 1m
       Nginx global client max body size: 1m
```
```
# dokku nginx:set --global client-max-body-size 64m
 !     The key 'client-max-body-size' cannot be set globally
 ```

### Steps to reproduce

-

### dokku report $APP_NAME

-

**Comment by shulcsm** [comment]
Changing GLOBAL_KEYS allows to change the default:
` local GLOBAL_KEYS=("hsts" "nginx-conf-sigil-path" "client-max-body-size")`
But why was the default global value introduced if field supposed to be optional?

**Comment by josegonzalez** [comment]
I don't remember this working globally, just on a per-app basis. I think it does work globally for openresty. I just don't think I set most of the options to be able to be set globally (not sure why).

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by shulcsm** [comment]
What about default value of 1m. Not sure where it comes from. Is that intentional?

**Comment by josegonzalez** [comment]
Thats intentional. The default values are retrieved from the [nginx docs](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size), and I will not be changing them.
