### ISSUE TITLE
Dokku in Docker volume and env variable mismatch ?

### ISSUE THREAD

**Issue by Cactusbone** [dokku/dokku#7223]
### Link to the documentation page

https://dokku.com/docs/getting-started/install/docker/

### Documentation problem

DOKKU_HOST_ROOT & DOKKU_LIB_HOST_ROOT variables both use `/var/lib/dokku` which refer to a path within the container.

And `--volume /var/lib/dokku:/mnt/dokku` also uses `/var/lib/dokku` but this a path on the host !  

I think DOKKU_HOST_ROOT & DOKKU_LIB_HOST_ROOT should use `/mnt/dokku` instead, to avoid confusion.

**Comment by josegonzalez** [comment]
The path you showed isn't the whole path. The dockerized version of Dokku will store _all_ data in `/var/lib/dokku` and then the home folder (and dokku lib for) are relative to that. You'll notice the values are `/var/lib/dokku/home/dokku` - for the home folder - and `/var/lib/dokku/var/lib/dokku` - for the lib directory data. Those environment variables are used for mounting host paths into app containers as necessary. 

As for the mounted path, that's just that first `/var/lib/dokku` in the paths specified. You could change the _first_ reference to that path to `/data/dokku` if you wanted.

**Comment by Cactusbone** [comment]
`--volume source:target` or `--volume host:container`

the `/mnt/dokku` is the path inside the container where the volume is available, that's my issue here ... the env var do not point to the mounted volume in the example.

I'll try adding a schema tomorrow if needed :)

**Comment by josegonzalez** [comment]
That `/mnt/dokku` path inside the container is used by the container for symlinking. The paths are [symlinked](https://github.com/dokku/dokku/blob/fbf8a047284d1c77ba390356179ddb84d3462668/Dockerfile#L58-L62), and provide a way for the users to only need to have 1 volume mount. A skeleton of the required folder structure is [created](https://github.com/dokku/dokku/blob/fbf8a047284d1c77ba390356179ddb84d3462668/docker/etc/my_init.d/10_dokku_init#L43) on container start.

It's additionally used for:

- [The plugin-list file](https://github.com/dokku/dokku/blob/fbf8a047284d1c77ba390356179ddb84d3462668/docker/etc/my_init.d/10_dokku_init#L72)
- [dhparam](https://github.com/dokku/dokku/blob/fbf8a047284d1c77ba390356179ddb84d3462668/docker/etc/my_init.d/10_dokku_init#L100) (so you don't need to regenerate on each boot.

The paths and variables in the documentation are 100% correct.
