### ISSUE TITLE
Easy access to nginx logs on k3s scheduler

### ISSUE THREAD

**Issue by emilsedgh** [dokku/dokku#7268]
### Description of feature

Right now if you want to read your nginx logs on k3s scheduler you need an insanely complex command like this:

```
kubectl exec -it -n ingress-nginx $(kubectl get pods -n ingress-nginx --no-headers -o custom-columns=":metadata.name" | head -n1) -- tail -f /var/log/nginx/$app-access.log
```

Would be amazing if Dokku provides an easier way of accessing nginx access and error logs.

**Comment by josegonzalez** [comment]
Looking at it, the labels we use for the dokku helm chart are the same as those used by ingress-nginx, so:

- `app.kubernetes.io/part-of`: appName, or `ingress-nginx`
- `app.kubernetes.io/name`: processType, or `ingress-nginx`

We can mostly repurpose `TriggerSchedulerLogs` in the `k3s` plugin to take a namespace, then call it for the`ingress-nginx` namespace.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
