### ISSUE TITLE
Procfile processes not spun up on build

### ISSUE THREAD

**Issue by chgad** [dokku/dokku#7301]
### Description of problem

Having a Procfile like this

```
    web: gunicorn config.wsgi:application
    worker: /usr/local/bin/celery --workdir . -A api worker
    beat: /usr/local/bin/celery -A api beat -l INFO
```

will only launch a web process on deploy.

I had to manualle `dokku ps:scale my-app worker=1 beat=1` after resulting problems with those missing processes.

I do not think this is intended behavior.

### Steps to reproduce

Deploy a project wth the above mentioned Procfile like https://github.com/ClockGU/clock-backend

### dokku report $APP_NAME

-----> uname: Linux clock 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                      total        used        free      shared  buff/cache   available
       Mem:            3875        1836         144         120        1894        1627
       Swap:           3889         545        3344
-----> disk utilization: 
       Filesystem                         Size  Used Avail Use% Mounted on
       /dev/mapper/ubuntu--vg-ubuntu--lv   47G   42G  2.9G  94% /
       /dev/sda2                          2.0G  254M  1.6G  14% /boot
       /dev/sda1                          1.1G  6.1M  1.1G   1% /boot/efi
-----> disk inode utilization: 
       Filesystem                        Inodes IUsed IFree IUse% Mounted on
       /dev/mapper/ubuntu--vg-ubuntu--lv   3.0M  1.9M  1.2M   62% /
       /dev/sda2                           128K   310  128K    1% /boot
       /dev/sda1                              0     0     0     - /boot/efi
-----> docker version: 
       Client: Docker Engine - Community
        Version:           27.1.2
        API version:       1.46
        Go version:        go1.21.13
        Git commit:        d01f264
        Built:             Mon Aug 12 11:50:12 2024
        OS/Arch:           linux/amd64
        Context:           default
       
       Server: Docker Engine - Community
        Engine:
         Version:          27.1.2
         API version:      1.46 (minimum version 1.24)
         Go version:       go1.21.13
         Git commit:       f9522e5
         Built:            Mon Aug 12 11:50:12 2024
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.7.20
         GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
        runc:
         Version:          1.1.13
         GitCommit:        v1.1.13-0-g58aa920
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client: Docker Engine - Community
        Version:    27.1.2
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.16.2
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.29.1
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
       
       Server:
        Containers: 22
         Running: 21
         Paused: 0
         Stopped: 1
        Images: 25
        Server Version: 27.1.2
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
        Swarm: inactive
        Runtimes: runc io.containerd.runc.v2
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
        runc version: v1.1.13-0-g58aa920
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-122-generic
        Operating System: Ubuntu 22.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 3
        Total Memory: 3.785GiB
        Name: clock
        ID: 40531c13-e5b1-41b7-ba33-d38013794700
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 160
         Goroutines: 151
         System Time: 2024-10-22T13:39:09.762354956Z
         EventsListeners: 1
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> herokuish version: 
 !     Herokuish image gliderlabs/herokuish:latest-22 is not available
-----> dokku version: dokku version 0.34.8
-----> dokku-event-listener version: v0.17.0
-----> dokku-update version: dokku-update v0.9.4
-----> docker-container-healthchecker version: v0.11.0
-----> docker-image-labeler version: v0.8.0
-----> git version: git version 2.34.1
-----> lambda-builder version:        v0.8.0                                                                          
-----> netrc version: v0.10.0
 !     pack binary is not available
-----> plugn version: plugn: v0.16.0
-----> sigil version: v0.11.0
-----> sshcommand version: sshcommand v0.18.0
-----> dokku plugins: 
         00_dokku-standard    0.34.8 enabled    dokku core standard plugin
         20_events            0.34.8 enabled    dokku core events logging plugin
         app-json             0.34.8 enabled    dokku core app-json plugin
         apps                 0.34.8 enabled    dokku core apps plugin
         builder              0.34.8 enabled    dokku core builder plugin
         builder-dockerfile   0.34.8 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.34.8 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.34.8 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.34.8 enabled    dokku core builder-nixpacks plugin
         builder-null         0.34.8 enabled    dokku core builder-null plugin
         builder-pack         0.34.8 enabled    dokku core builder-pack plugin
         buildpacks           0.34.8 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.34.8 enabled    dokku core caddy-vhosts plugin
         certs                0.34.8 enabled    dokku core certificate management plugin
         checks               0.34.8 enabled    dokku core checks plugin
         common               0.34.8 enabled    dokku core common plugin
         config               0.34.8 enabled    dokku core config plugin
         cron                 0.34.8 enabled    dokku core cron plugin
         docker-options       0.34.8 enabled    dokku core docker-options plugin
         domains              0.34.8 enabled    dokku core domains plugin
         enter                0.34.8 enabled    dokku core enter plugin
         git                  0.34.8 enabled    dokku core git plugin
         haproxy-vhosts       0.34.8 enabled    dokku core haproxy-vhosts plugin
         logs                 0.34.8 enabled    dokku core logs plugin
         mongo                1.36.11 enabled    dokku mongo service plugin
         network              0.34.8 enabled    dokku core network plugin
         nginx-vhosts         0.34.8 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.34.8 enabled    dokku core openresty-vhosts plugin
         plugin               0.34.8 enabled    dokku core plugin plugin
         ports                0.34.8 enabled    dokku core ports plugin
         postgres             1.38.0 enabled    dokku postgres service plugin
         proxy                0.34.8 enabled    dokku core proxy plugin
         ps                   0.34.8 enabled    dokku core ps plugin
         rabbitmq             1.36.13 enabled    dokku rabbitmq service plugin
         registry             0.34.8 enabled    dokku core registry plugin
         repo                 0.34.8 enabled    dokku core repo plugin
         resource             0.34.8 enabled    dokku core resource plugin
         run                  0.34.8 enabled    dokku core run plugin
         scheduler            0.34.8 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.34.8 enabled    dokku core scheduler-docker-local plugin
         scheduler-k3s        0.34.8 enabled    dokku core scheduler-k3s plugin
         scheduler-null       0.34.8 enabled    dokku core scheduler-null plugin
         shell                0.34.8 enabled    dokku core shell plugin
         ssh-keys             0.34.8 enabled    dokku core ssh-keys plugin
         storage              0.34.8 enabled    dokku core storage plugin
         trace                0.34.8 enabled    dokku core trace plugin
         traefik-vhosts       0.34.8 enabled    dokku core traefik-vhosts plugin
=====> clock-backend-production app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> clock-backend-production app information
       App created at:                1724687905
       App deploy source:             git-push
       App deploy source metadata:    44e78c0b41d1bcd55a8a24e9364b04af4eece051
       App dir:                       /home/dokku/clock-backend-production
       App locked:                    false
=====> clock-backend-production builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> clock-backend-production builder-dockerfile information
       Builder dockerfile computed dockerfile path: docker/dokku/Dockerfile  
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path: docker/dokku/Dockerfile  
=====> clock-backend-production builder-herokuish information
       Builder herokuish computed allowed: true                     
       Builder herokuish global allowed: true                     
       Builder herokuish allowed:                              
=====> clock-backend-production builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml               
       Builder lambda global lambdayml path: lambda.yml               
       Builder lambda lambdayml path:                          
=====> clock-backend-production builder-nixpacks information
       Builder nixpacks computed nixpackstoml path: nixpacks.toml            
       Builder nixpacks global nixpackstoml path: nixpacks.toml            
       Builder nixpacks nixpackstoml path:                          
       Builder nixpacks computed no cache: false                    
       Builder nixpacks global no cache: false                    
       Builder nixpacks no cache:                              
=====> clock-backend-production builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> clock-backend-production buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-22
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> clock-backend-production caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.9
       Caddy letsencrypt email:                                
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR                    
       Caddy polling interval:        5s                       
       Caddy tls internal:            false                    
=====> clock-backend-production ssl information
       Ssl dir:                       /home/dokku/clock-backend-production/tls
       Ssl enabled:                   true                     
       Ssl hostnames:                 backend.clock.uni-frankfurt.de clock.uni-frankfurt.de staging.backend.clock.uni-frankfurt.de staging.clock.uni-frankfurt.de staging.time-vault.uni-frankfurt.de time-vault.uni-frankfurt.de
       Ssl expires at:                Sep 23 23:59:59 2025 GMT 
       Ssl issuer:                    C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Organization Validation Secure Server CA
       Ssl starts at:                 Sep 23 00:00:00 2024 GMT 
       Ssl subject:                   subject=C = DE, ST = Hessen, O = Goethe-Universit\C3\A4t Frankfurt am Main, CN = clock.uni-frankfurt.de
       Ssl verified:                  self signed              
=====> clock-backend-production checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
       Checks computed wait to retire: 60                       
       Checks global wait to retire:  60                       
       Checks wait to retire:                                  
=====> clock-backend-production docker options information
       Docker options build:          --link dokku.postgres.clock-production-db:dokku-postgres-clock-production-db --link dokku.rabbitmq.clock-production-mq:dokku-rabbitmq-clock-production-mq 
       Docker options deploy:         --link dokku.postgres.clock-production-db:dokku-postgres-clock-production-db --link dokku.rabbitmq.clock-production-mq:dokku-rabbitmq-clock-production-mq --restart=on-failure:10 -v /var/lib/dokku/data/storage/clock-backend-production/logs:/app/logs -v /var/lib/dokku/data/storage/clock-staticfiles:/app/staticfiles 
       Docker options run:            --link dokku.postgres.clock-production-db:dokku-postgres-clock-production-db --link dokku.rabbitmq.clock-production-mq:dokku-rabbitmq-clock-production-mq -v /var/lib/dokku/data/storage/clock-backend-production/logs:/app/logs -v /var/lib/dokku/data/storage/clock-staticfiles:/app/staticfiles 
=====> clock-backend-production domains information
       Domains app enabled:           true                     
       Domains app vhosts:            backend.clock.uni-frankfurt.de
       Domains global enabled:        false                    
       Domains global vhosts:                                  
=====> clock-backend-production git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       44e78c0b41d1bcd55a8a24e9364b04af4eece051
       Git source image:                                       
       Git last updated at:           1728484116               
=====> clock-backend-production haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.4.0  
       Haproxy letsencrypt email:                              
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR                    
=====> clock-backend-production logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector global image:      timberio/vector:0.39.0-debian
       Logs vector sink:              
=====> clock-backend-production network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.20.0.21:5000
=====> clock-backend-production nginx information
       Nginx access log format:                                
       Nginx computed access log format:                          
       Nginx global access log format:                          
       Nginx access log path:                                  
       Nginx computed access log path: /var/log/nginx/clock-backend-production-access.log
       Nginx global access log path:  /var/log/nginx/clock-backend-production-access.log
       Nginx bind address ipv4:                                
       Nginx computed bind address ipv4:                          
       Nginx global bind address ipv4:                          
       Nginx bind address ipv6:                                
       Nginx computed bind address ipv6: ::                       
       Nginx global bind address ipv6: ::                       
       Nginx client max body size:                             
       Nginx computed client max body size: 1m                       
       Nginx global client max body size: 1m                       
       Nginx disable custom config:                            
       Nginx computed disable custom config: false                    
       Nginx global disable custom config: false                    
       Nginx error log path:                                   
       Nginx computed error log path: /var/log/nginx/clock-backend-production-error.log
       Nginx global error log path:   /var/log/nginx/clock-backend-production-error.log
       Nginx hsts include subdomains:                          
       Nginx computed hsts include subdomains: true                     
       Nginx global hsts include subdomains: true                     
       Nginx hsts max age:                                     
       Nginx computed hsts max age:   15724800                 
       Nginx global hsts max age:     15724800                 
       Nginx hsts preload:                                     
       Nginx computed hsts preload:   false                    
       Nginx global hsts preload:     false                    
       Nginx hsts:                                             
       Nginx computed hsts:           true                     
       Nginx global hsts:             true                     
       Nginx last visited at:                                  
       Nginx nginx conf sigil path:                            
       Nginx computed nginx conf sigil path: nginx.conf.sigil         
       Nginx global nginx conf sigil path: nginx.conf.sigil         
       Nginx proxy buffer size:                                
       Nginx computed proxy buffer size: 4k                       
       Nginx global proxy buffer size: 4k                       
       Nginx proxy buffering:                                  
       Nginx computed proxy buffering: on                       
       Nginx global proxy buffering:  on                       
       Nginx proxy buffers:                                    
       Nginx computed proxy buffers:  8 4k                     
       Nginx global proxy buffers:    8 4k                     
       Nginx proxy busy buffers size:                          
       Nginx computed proxy busy buffers size: 8k                       
       Nginx global proxy busy buffers size: 8k                       
       Nginx proxy read timeout:                               
       Nginx computed proxy read timeout: 60s                      
       Nginx global proxy read timeout: 60s                      
       Nginx underscore in headers:                            
       Nginx computed underscore in headers: off                      
       Nginx global underscore in headers: off                      
       Nginx x forwarded for value:                            
       Nginx computed x forwarded for value: $remote_addr             
       Nginx global x forwarded for value: $remote_addr             
       Nginx x forwarded port value:                           
       Nginx computed x forwarded port value: $server_port             
       Nginx global x forwarded port value: $server_port             
       Nginx x forwarded proto value:                          
       Nginx computed x forwarded proto value: $scheme                  
       Nginx global x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
       Nginx computed x forwarded ssl:                          
       Nginx global x forwarded ssl:                           
=====> clock-backend-production openresty information
       Openresty access log format:                            
       Openresty access log path:     /var/log/nginx/clock-backend-production-access.log
       Openresty allowed letsencrypt domains func base64: cmV0dXJuIHRydWUK         
       Openresty bind address ipv4:                            
       Openresty bind address ipv6:   ::                       
       Openresty client max body size:                          
       Openresty error log path:      /var/log/nginx/clock-backend-production-error.log
       Openresty global hsts:         true                     
       Openresty computed hsts:       true                     
       Openresty hsts:                                         
       Openresty hsts include subdomains: true                     
       Openresty hsts max age:        15724800                 
       Openresty hsts preload:        false                    
       Openresty image:               dokku/openresty-docker-proxy:0.8.0
       Openresty letsencrypt email:                            
       Openresty letsencrypt server:  https://acme-v02.api.letsencrypt.org/directory
       Openresty proxy buffer size:   4k                       
       Openresty proxy buffering:     on                       
       Openresty proxy buffers:       8 4k                     
       Openresty proxy busy buffers size: 8k                       
       Openresty proxy read timeout:  60s                      
       Openresty underscore in headers: off                      
       Openresty x forwarded for value: $remote_addr             
       Openresty x forwarded port value: $server_port             
       Openresty x forwarded proto value: $scheme                  
       Openresty x forwarded ssl:                              
=====> clock-backend-production ports information
       Ports map:                     http:80:5000 https:443:5000
       Ports map detected:            http:80:5000 https:443:5000
=====> clock-backend-production proxy information
       Proxy computed type:           nginx
       Proxy enabled:                 true
       Proxy global type:             nginx
       Proxy type:                    
=====> clock-backend-production ps information
       Deployed:                      true
       Processes:                     3
       Ps can scale:                  true
       Ps computed procfile path:     docker/dokku/Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              docker/dokku/Procfile
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status beat 1:                 running (CID: e72bbf028d3)
       Status web 1:                  running (CID: 88bb51cc0c6)
       Status worker 1:               running (CID: 04c23eee3c4)
=====> clock-backend-production registry information
       Registry computed image repo:        dokku/clock-backend-production
       Registry computed push on release:   false
       Registry computed server:            
       Registry global image repo template: 
       Registry global push on release:     
       Registry global server:              
       Registry image repo:                 
       Registry push extra tags:            
       Registry push on release:            
       Registry server:                     
       Registry tag version:                
=====> clock-backend-production resource information
=====> clock-backend-production scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> clock-backend-production scheduler-docker-local information
       Scheduler docker local init process: true                     
       Scheduler docker local parallel schedule count:                          
=====> clock-backend-production scheduler-k3s information
       Scheduler k3s computed deploy timeout:       300s
       Scheduler k3s computed image pull secrets:   
       Scheduler k3s computed letsencrypt server:   prod
       Scheduler k3s computed namespace:            default
       Scheduler k3s computed rollback on failure:  false
       Scheduler k3s deploy timeout:                
       Scheduler k3s global deploy timeout:         300s
       Scheduler k3s global image pull secrets:     
       Scheduler k3s global ingress class:          nginx
       Scheduler k3s global kube context:           
       Scheduler k3s global kubeconfig path:        /etc/rancher/k3s/k3s.yaml
       Scheduler k3s global letsencrypt email prod: 
       Scheduler k3s global letsencrypt email stag: 
       Scheduler k3s global letsencrypt server:     prod
       Scheduler k3s global namespace:              default
       Scheduler k3s global network interface:      eth0
       Scheduler k3s global rollback on failure:    false
       Scheduler k3s image pull secrets:            
       Scheduler k3s letsencrypt server:            
       Scheduler k3s namespace:                     
       Scheduler k3s rollback on failure:           
=====> clock-backend-production storage information
       Storage build mounts:                                   
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/clock-backend-production/logs:/app/logs -v /var/lib/dokku/data/storage/clock-staticfiles:/app/staticfiles 
       Storage run mounts:            -v /var/lib/dokku/data/storage/clock-backend-production/logs:/app/logs -v /var/lib/dokku/data/storage/clock-staticfiles:/app/staticfiles 
=====> clock-backend-production traefik information
       Traefik api enabled:           false                    
       Traefik api vhost:             traefik.dokku.me         
       Traefik basic auth password:                            
       Traefik basic auth username:                            
       Traefik dashboard enabled:     false                    
       Traefik image:                 traefik:2.11.2           
       Traefik letsencrypt email:                              
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR                    
       Traefik http entry point:      http                     
       Traefik https entry point:     https

**Comment by josegonzalez** [comment]
This is intended behavior. This emulates how Heroku works.

See this doc for more details: https://dokku.com/docs/processes/process-management/
