### ISSUE TITLE
appendix that documents all the file formats

### ISSUE THREAD

**Issue by shijialee** [dokku/dokku#7315]
### Documentation problem

The documentation mentions `.buildpacks` file without detail. 

Dokku has limited support for app.json and would be nice to be documented too.

This ticket originated from this discussion https://github.com/dokku/dokku/discussions/7307#discussioncomment-11090508

**Comment by josegonzalez** [comment]
Probably an appendix section would be good. I think we can document the following files:

- `Procfile`
- `Dockerfile` (mostly just a link to the external doc, with any extra notes on how dokku might "enhance" the experience)
-  `.buildpacks`
- `app.json`
- `nginx.conf.sigil`
- `project.toml` (mostly just a link to the external doc)
- `lambda.yml`
- `nixpacks.toml` (mostly just a link to the external doc)

Not sure if there are any other files Dokku uses/respects, but they can all go in the appendix section :)
