### ISSUE TITLE
CopyFromImage silently fails to copy Procfile from temporary location when file permissions are too restrictive when dokku is run in docker

### ISSUE THREAD

**Issue by indrat** [dokku/dokku#7336]
### Description of problem

When running dokku in a docker container and building an app with `git:from-image` where the image has a `Procfile` that has the file mode `0600` the file is successfully copied out to `/tmp/dokku-XXX-CopyFromImageXXXX` owned by `root` with the file mode `0600`.

The subsequent `dos2unix` command at https://github.com/dokku/dokku/blob/master/plugins/common/docker.go#L147 fails to read the file due to the file mode and owner being root and the error is ignored.

The subsequent `tail` command at https://github.com/dokku/dokku/blob/master/plugins/common/docker.go#L153 fails and returns and a `ProcfileXXXX.missing` file is created and then removed later by some other trigger/step.

Ideally one of the errors about not being able to read the file from `dos2unix` or `tail` would be logged to indicate why the file was unable to be read.

Relatedly, since the root issue is that the files are owned by root, the [defer](https://github.com/dokku/dokku/blob/master/plugins/common/docker.go#L113) doesn't successfully remove the temporary files and leaks them in `/tmp`. A workaround may be to invoke `docker cp` and send the output to stdout and extract the file from the tar stream.

i.e the equivalent of something like the following will create the file owned by the `dokku` user and should allow it to be read and removed.
```
docker cp $CONTAINER:$WORK_DIR/Procfile - | tar -xOf - > /tmp/$TMP_PROCFILE
```

### Steps to reproduce

- Create an app image where the `Procfile` has the file mode `0600`.
- Run dokku in a docker container
- Deploy the app via `git:from-image`
- Observe that the commands from the `Procfile` are not used and no `Procfile` is created for the app in `/var/lib/dokku/data/ps/$APP/Procfile`
- The temporary files created by `CopyFromImage` are not removed from `/tmp/dokku-XXX-CopyFromImageXXX`

### dokku report $APP_NAME

Note: the app failed to deploy/start the container for the `web` process as it relied on the contents of the `Procfile` to start.

```
======> dokku-app app information
App created at:               1730928595
App deploy source:
App deploy source metadata:
App dir:                      /home/dokku/dokku-app
App locked:                   false
```

### Additional information

Procfile:
```
web: scripts/run
worker: scripts/run-worker
```

**Comment by josegonzalez** [comment]
Interesting... I suppose that will copy the file contents to stdout? If so, that should be sufficient for us, as we can capture stdout and write it to the temp file.

**Comment by indrat** [comment]
Yes the `docker container cp` command will stream the src files to stdout encapsulated in a tar-file when the `DEST_PATH` is `-`

https://docs.docker.com/reference/cli/docker/container/cp/
> If - is specified for either the SRC_PATH or DEST_PATH, you can also stream a tar archive from STDIN or to STDOUT. The CONTAINER can be a running or stopped container.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.

**Comment by josegonzalez** [comment]
Okay this is going to be split up in a few steps but I think I know how to fix it :)
