### ISSUE TITLE
DOKKU_LIB_HOST_ROOT isn't populated for dokku / the dokku user when running dokku in a container

### ISSUE THREAD

**Issue by indrat** [dokku/dokku#7352]
### Description of problem

The docs for getting started with [dokku in docker](https://dokku.com/docs/getting-started/install/docker/) document setting DOKKU_LIB_HOST_ROOT via `--env DOKKU_LIB_HOST_ROOT=/var/lib/dokku/var/lib/dokku `.

However when running dokku in the dokku/dokku container DOKKU_LIB_HOST_ROOT isn't populated for the dokku application / user. This leads to plugins like dokku-postgres etc putting their data into `/var/lib/dokku/` rather than `/var/lib/dokku/var/lib/dokku` and not working correctly.

### Steps to reproduce

```
docker container run -d \
  --env DOKKU_HOSTNAME=dokku.me \
  --env DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku \
  --env DOKKU_LIB_HOST_ROOT=/var/lib/dokku/var/lib/dokku \
  --name dokku \
  --publish 3022:22 \
  --publish 8080:80 \
  --publish 8443:443 \
  --volume /var/lib/dokku:/mnt/dokku \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  dokku/dokku:0.35.10

$ docker exec -it dokku /bin/bash
# dokku plugin:install https://github.com/dokku/dokku-postgres.git

$ docker exec -it dokku /bin/bash
$ dokku postgres:create lollipop
```

postgres data is created in `/var/lib/dokku` instead of `/var/lib/dokku/var/lib/dokku`

### dokku report $APP_NAME

N/A

**Comment by josegonzalez** [comment]
Great catch and thanks for the pull request! This will go out in the next release
