### ISSUE TITLE
Allow specifying MAILFROM for Cron Tasks

### ISSUE THREAD

**Issue by salomvary** [dokku/dokku#7362]
### Description of feature

I am running Dokku on a system that requires emails to be sent with a specific `from:` address. As far as I am aware, `crond` (at least the one shipped on Ubuntu) does not allow overriding this in any other way than specifying the `MAILFROM` variable in a crontab.

It would be great if Dokku allowed specifying `MAILFROM` similarly to how it allows `MAILTO`: https://dokku.com/docs/processes/scheduled-cron-tasks/#specifying-a-mailto-value

I might attempt a pull request if this is of interest.

**Comment by josegonzalez** [comment]
Seems like a good PR.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
