### ISSUE TITLE
Debian 12 - 'cgroupfs-mount' has no installation candidate

### ISSUE THREAD

**Issue by leandroembu** [dokku/dokku#7367]
### Description of problem

Dokku depends on package 'cgroupfs-mount', but this package is not in Debian anymore.

### Steps to reproduce

`sudo apt install dokku`

Errors:

```
The following packages have unmet dependencies:
 dokku : PreDepends: cgroupfs-mount but it is not installable or
                     cgroup-lite but it is not installable
         Recommends: herokuish (>= 0.10.2) but it is not going to be installed
         Recommends: dokku-update (>= 0.9.4) but it is not going to be installed
         Recommends: dokku-event-listener (>= 0.17.0) but it is not going to be installed
```

### dokku report $APP_NAME

There is no app since I could not install Dokku.

**Comment by josegonzalez** [comment]
This was a dependency for docker [here](https://github.com/moby/moby/issues/2990#issuecomment-29666967).

I'll need to see if I can spin up a debian box to figure out whats happening. Maybe we can just drop that package?

**Comment by leandroembu** [comment]
Currently docker-ce suggests but does not depend on cgroupfs-mount. Docker is already installed from the Ansible role dokku_bot.ansible_dokku, but the tasks stopped when installing Dokku.

```
leandro@tools:~$ apt depends docker-ce
docker-ce
  Depends: containerd.io (>= 1.6.24)
  Depends: docker-ce-cli
  Depends: iptables
  Depends: libseccomp2 (>= 2.3.0)
  Depends: libc6 (>= 2.34)
  Depends: libsystemd0
    libelogind0
  Conflicts: docker (<< 1.5~)
  Conflicts: <docker-engine>
  Conflicts: docker.io
  Recommends: apparmor
  Recommends: ca-certificates
  Recommends: docker-ce-rootless-extras
  Recommends: git
  Recommends: libltdl7
  Recommends: pigz
  Recommends: procps
  Recommends: xz-utils
  Suggests: <aufs-tools>
 |Suggests: cgroupfs-mount
  Suggests: <cgroup-lite>
  Replaces: <docker-engine>
```

**Comment by josegonzalez** [comment]
Maybe worth just removing it if we don't have a direct requirement for it... I'll need to check if that's fine with the docker-based installation method.

**Comment by leandroembu** [comment]
Something odd with my server, probably. I just uploaded a Debian 12.8 and the cgroupfs-mount package is there in main repo, it was removed only from Testing (13).

**Comment by josegonzalez** [comment]
Looks like we don't directly use any of the files [here](https://packages.debian.org/sid/all/cgroupfs-mount/filelist) so I think this is just safe for us to remove.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
