### ISSUE TITLE
Make footer year dynamic

### ISSUE THREAD

**Issue by Ripon876** [dokku/dokku#7413]
### Link to the documentation page

https://dokku.com

#### **Problem**  
The current footer on the Dokku website uses a static year range (`2013-2022`). This requires manual updates every year to keep the footer accurate, leading to unnecessary maintenance overhead and a potential for outdated information.

#### **Proposed Solution**  
Update the footer to dynamically generate the current year using JavaScript. For example:
- Use JavaScript to fetch the current year and append it to the starting year (`2013`).
- Example output: `© 2013-2024 Dokku`.

#### **Benefits**  
- Automates the year update process, reducing manual effort.
- Ensures the footer always displays the correct and up-to-date year.

**Comment by josegonzalez** [comment]
I've just removed it completely. No code is the best code.

The change should go out on the next release.
