### ISSUE TITLE
nginx not working due to "server_names_hash_bucket_size" directive is duplicate

### ISSUE THREAD

**Issue by serv** [dokku/dokku#799]
When I run the command `$ nginx`, I get this error message.
`nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/server_names_hash_bucket_size.conf:1`

When I comment out the `server_names_hash_bucket_size 64;` in `/etc/nginx/conf.d/server_names_hash_bucket_size.conf`, nginx command starts working.

But a day later, it seems like I have the same problem again.

**Comment by darkpixel** [comment]
I keep getting nailed by this issue.
If I remove the directive from ```/etc/nginx/nginx.conf``` or I remove ```/etc/nginx/conf.d/server_names_hash_bucket_size.conf``` they seem to get re-created the next time I push or perform a dokku action that involved nginx.

**Comment by darkpixel** [comment]
Running 0.6.5

**Comment by josegonzalez** [comment]
@darkpixel Mind hopping on slack/irc so we can figure out what your exact issue is? This was definitely fixed a long time ago in #1372.

**Comment by darkpixel** [comment]
I'm doing some more digging.  I'll hop on when I get it figured out.  I'm suspecting a 3rd party plugin.
