### ISSUE TITLE
Fails after Git resetting environment

### ISSUE THREAD

**Issue by ghostbar** [dokku/dokku#800]
I de-installed all the plugins I were using, reinstalled dokku and buildstep. Keeps happening. It just happened, in three of my machines, the local, staging and production at the same time. Not changing any code. This is the trace and does not makes sense to me.

```
-----> Resetting git environment
remote: + exit_code=1
remote: + set -e
remote: + '[' 1 -eq 10 ']'
remote: + implemented=1
remote: + '[' 1 -ne 0 ']'
remote: + exit 1
+ exit_code=0
+ set -e
+ '[' 0 -eq 10 ']'
+ implemented=1
+ '[' 0 -ne 0 ']'
+ for script in '$(ls -d $PLUGIN_PATH/*/commands)'
+ set +e
+ /var/lib/dokku/plugins/nginx-vhosts/commands git-receive-pack ''\''api'\'''
+ case "$1" in
+ exit 10
+ exit_code=10
+ set -e
+ '[' 10 -eq 10 ']'
+ continue
+ '[' 1 -eq 0 ']'
+ exit 0
To dokku@domain.tld:api
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Comment by stuartpb** [comment]
Ugh, I'm getting this issue in *Plushu* right now, that's how fragile Heroku has made the Node buildpack...

semver.io doesn't even appear to be having an outage, I don't now what's up.

**Comment by stuartpb** [comment]
Changing the line to `curl -vv --silent --get --data-urlencode range=0.10.x https://semver.herokuapp.com/node/resolve`:

```
curl -vv --silent --get --data-urlencode range=0.10.x https://semver.herokuapp.com/node/resolve
remote: * Hostname was NOT found in DNS cache
remote: * Could not resolve host: semver.herokuapp.com
remote: * Closing connection 0
```

So yeah, probably some kind of DNS outage again.

**Comment by stuartpb** [comment]
Actually, I seem to be having some kind of odd problem where `docker run --rm progrium/cedarish ping google.com` can't even find hosts.

**Comment by stuartpb** [comment]
I just rebuilt the image and I'm still getting this issue, *argh wtf*. I'm opening a ticket with DigitalOcean.

**Comment by stuartpb** [comment]
I figured it out. Docker doesn't like DigitalOcean's IPv6-compatible /etc/resolv.conf.

**Comment by stuartpb** [comment]
[Oh my gosh IPv6 Docker containers on DigitalOcean are a nightmare right now](https://jeffloughridge.wordpress.com/2015/01/17/native-ipv6-functionality-in-docker/).

**Comment by michaelshobbs** [comment]
:+1: it's true
