### ISSUE TITLE
413 Error (Request Entity Too Large) thrown by dokku (Nginx)

### ISSUE THREAD

**Issue by bricef** [dokku/dokku#802]
The nginx config for some reason rejects requests without passing them to the hosted applications (in my case a [bottle.py](http://bottlepy.org/docs/dev/index.html) app). This is an issue even with moderately sized uploads (4.6 MB). 

I don't have time right now to dig through and find the right files (surely some nginx.conf somewhere) to change for this, but I will eventually get to it. Thought it would be wise to document the issue in the meantime.
## Update

The right file to modify is `/home/dokku/<appname>/nginx.conf` and as @dipankar mentioned, you should add a `client_max_body_size 20M;` line to the `server` scope.

If you want to have a custom directive in this file defined from the app itself, you'll need to use the nginx-vhosts dokku plugin and add a custom `nginx.inc.conf` file at the root of your app repository.

Will post an example when I have one.

**Comment by mattions** [comment]
I think this didn't manage to get into dokku at the end:
was done here (https://github.com/incredlabs/dokku/commit/32301e5a3edb359c299d157f8165c7d42012cdfb) Pull Request not merged?

`client_max_body_size 10m;`

is not found in the current install, and even if that is added to the nginx.conf.template it does not seem to have an effect.

Can we add that to the normal dokku?
Basically after this line: https://github.com/progrium/dokku/blob/master/plugins/nginx-vhosts/install#L48

we should add 
`client_max_body_size 10m;`

or even `client_max_body_size 100m;`

so big uploads are accepted.

**Comment by josegonzalez** [comment]
That's not a normal configuration, so its not going to be merged. You can customize your nginx config if you need this for an app.

**Comment by chrisdobler** [comment]
doesn't this file just get overwritten each time your rebuild the container though?

**Comment by josegonzalez** [comment]
You can customize your nginx config as mentioned [here](http://dokku.viewdocs.io/dokku/configuration/nginx/).
