### ISSUE TITLE
Unable to select a buildpack

### ISSUE THREAD

**Issue by JanVanRyswyck** [dokku/dokku#819]
I'm pretty new to dokku. I've setup a new dokku droplet at DigitalOcean. I created a small static website with a www directory containing a single HTML file named index.html. In the root dir I added an empty .nginx file. When I tried to push, I got the following output:

Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 356 bytes | 0 bytes/s, done.
Total 5 (delta 0), reused 0 (delta 0)
-----> Cleaning up ...
remote: Cloning into '/tmp/tmp.FFdk4jjPhW'...
-----> Building dokkutest ...
remote: warning: You appear to have cloned an empty repository.
remote: done.
remote: HEAD is now at 0046a12... First implementation
-----> Unable to select a buildpack
To dokku@123.123.123.123:dokkutest
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@123.123.123.123:dokkutest'

Any thoughts on what I might be doing wrong?

**Comment by punnerud** [comment]
Add a .env file with this content:
`export BUILDPACK_URL=https://github.com/dokku/buildpack-nginx.git
`

Then add a empty file with .static (example with touch .static)

**Comment by josegonzalez** [comment]
Dokku comes with the static buildpack. Just add a `.static` file, no need to add that .env file or set any env vars.
